CORE-4877 deleteById/findAll persistence methods
corda/corda-runtime-os pull request #1354
Opened 2022-05-24 15:39 UTC by barrylapthorn

See also https://github.com/corda/corda-api/pull/380

Moved Avro messages to own package.

Added DeleteById and FindAll persistence methods.

Placeholder code to check that we do not attempt to return a
result set larger than a Kafka packet.

Fixed up some buggy unit tests, and added basic clean up.

Use the `failureResponse` method everywhere and also log any caught
exceptions, as errors if fatal, or warnings if not.  We want
to record any callstack or exception information particularly in the
case of a fatal error so we can investigate further.

Tidied up unit tests for readability.  Fixed a couple of bugs.

Replace usage of `Instant` with `Clock`. At component level, just create
a local `UTCClock` but then pass it in to places where it is _used_ so
we can substitute later if necessary.

2022-05-24 15:43 UTC, barrylapthorn commented on components/virtual-node/entity-processor-service-impl/src/main/kotlin/net/corda/entityprocessor/impl/internal/PersistenceServiceInternal.kt
> +        // Max bytes we will return (for findAll) in a single Kafka packet / message
"TODO" - still need to get this from "somewhere".

2022-05-25 07:56 UTC, driessamyn requested changes
Functionally seems fine. I just added some minor comments.

2022-05-25 07:56 UTC, driessamyn commented on components/virtual-node/entity-processor-service-impl/src/main/kotlin/net/corda/entityprocessor/impl/internal/PersistenceServiceInternal.kt
> +        // Max bytes we will return (for findAll) in a single Kafka packet / message
related to https://r3-cev.atlassian.net/browse/CORE-3856
@JamesHR3 , do you have any thoughts how we best handle this? E.g. can we get the configured message size from the Kafka broker directly, should we look up the kafka config, or should we choose a dedicated configuration key for this (which would then need to be somehow synchronized with the Kafka config, maybe through documentation).

2022-05-25 07:56 UTC, driessamyn commented on components/virtual-node/entity-processor-service-impl/src/main/kotlin/net/corda/entityprocessor/impl/internal/PersistenceServiceInternal.kt
> +        logger.info("Payload $kb kb < max Kafka payload size $maxKb kb")
I think this should be debug level logging.

2022-05-25 07:56 UTC, driessamyn commented on components/virtual-node/entity-processor-service-impl/src/main/kotlin/net/corda/entityprocessor/impl/internal/PersistenceServiceInternal.kt
> +            throw KafkaMessageSizeException("Payload $kb kb, exceeds max Kafka payload size $maxKb kb")
Let's maybe log the message as error as well (unless it's logged higher up the stack)?

2022-05-25 07:56 UTC, driessamyn commented on components/virtual-node/entity-processor-service-impl/src/main/kotlin/net/corda/entityprocessor/impl/internal/PersistenceServiceInternal.kt
> +        if (bytes.array().size > MAX_BYTES) {
Just beware that we need to have a buffer depending on what MAX_BYTES is. If it's the max Kafka message size, then we need to include a buffer for the message envelope and the rest of the message. If that value already contains the buffer, then it's fine.
Maybe this is a reason we should finalise where this value comes from?

2022-05-25 07:56 UTC, driessamyn commented on components/virtual-node/entity-processor-service-impl/src/main/kotlin/net/corda/entityprocessor/impl/internal/PersistenceServiceInternal.kt
> +        results: MutableList<out Any>
Why is this a Mutable list? Shouldn't a regular list do?
And in fact, does it even have to be a list at this stage, or can it just be `Any`?
The reason I ask is that I think we should apply this check to the regular `find` and `merge` operations too as they will at some point need chunk support as well and until then at least we would respond with an relevant exception.

2022-05-25 07:56 UTC, driessamyn commented on components/virtual-node/entity-processor-service-impl/src/main/kotlin/net/corda/entityprocessor/impl/internal/exceptions/KafkaMessageSizeException.kt
> + * This can happen if cpks broadcast over kafka have not yet arrived.
Docs are wrong.

2022-05-25 07:56 UTC, driessamyn commented on testing/bundles/testing-dogs/src/main/kotlin/net/corda/testing/bundles/dogs/CompositeDog.kt
> +data class CompositeDog(
Instead of adding one, can we not just make the key for `Dog` a composite one?
Or maybe the one in `Cat` as that is already the more "complex" example as it has an object relationship.

I'm not a fan of having too many of these test classes that are all similar. I think introducing another just has introduced a hole bunch of code (e.g. SQL migration scripts) that aren't really needed when we could just change the existing test objects.

2022-05-25 08:26 UTC, barrylapthorn commented on components/virtual-node/entity-processor-service-impl/src/main/kotlin/net/corda/entityprocessor/impl/internal/PersistenceServiceInternal.kt
> +            throw KafkaMessageSizeException("Payload $kb kb, exceeds max Kafka payload size $maxKb kb")
It is.

2022-05-25 08:27 UTC, barrylapthorn commented on components/virtual-node/entity-processor-service-impl/src/main/kotlin/net/corda/entityprocessor/impl/internal/PersistenceServiceInternal.kt
> +        results: MutableList<out Any>
Extract method dropped that in there for some reason.

2022-05-25 08:28 UTC, barrylapthorn commented on components/virtual-node/entity-processor-service-impl/src/main/kotlin/net/corda/entityprocessor/impl/internal/PersistenceServiceInternal.kt
> +        if (bytes.array().size > MAX_BYTES) {
Already asking James about this (and for chunking, once and for all), but that shouldn't block this PR.

2022-05-25 08:29 UTC, barrylapthorn commented on testing/bundles/testing-dogs/src/main/kotlin/net/corda/testing/bundles/dogs/CompositeDog.kt
> +data class CompositeDog(
I'll switch to 'Cat', if it's appropriate.  I needed to make sure we test composite and non-composite keys.

2022-05-25 13:05 UTC, driessamyn commented on components/virtual-node/entity-processor-service-impl/src/integrationTest/kotlin/net/corda/entityprocessor/impl/tests/helpers/AnimalCreator.kt
> +object AnimalCreator {
Some call it God :godmode:

2022-05-25 13:05 UTC, driessamyn commented on components/virtual-node/entity-processor-service-impl/src/main/kotlin/net/corda/entityprocessor/impl/internal/PersistenceServiceInternal.kt
> +    private fun findAllSizeCheck(
I think this should be called for everything that returns an object that could breach the message size (Find and Merge)

2022-05-25 14:15 UTC, driessamyn submitted a review, later dismissed
LGTM

2022-05-25 15:37 UTC, driessamyn submitted a review, later dismissed
LGTM

2022-05-25 17:20 UTC, driessamyn approved these changes
LGTM

2022-05-25 17:21 UTC, merged