NOTICK: Allow FlowSandboxGroupContext to close underlying SandboxGroupContext.
corda/corda-runtime-os pull request #1375
Opened 2022-05-27 13:49 UTC by chrisr3

The underlying `SandboxGroupContext` object may secretly also be a `MutableSandboxGroupContext` or a `CloseableSandboxGroupContext`.

Modify the `sandbox-app` to close the flow's underlying `SandboxGroupContext` _by any means necessary_.

2022-05-27 13:53 UTC, JamesHR3 approved these changes, later dismissed

2022-05-27 13:55 UTC, driessamyn requested changes

2022-05-27 13:55 UTC, driessamyn commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/sandbox/impl/FlowSandboxGroupContextImpl.kt
> +    }
We specifically didn't expose this as only the thing that creates SandboxGroupContexts and put them in cache should be able to close them.

2022-05-27 14:05 UTC, JamesHR3 commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/sandbox/impl/FlowSandboxGroupContextImpl.kt
> +    }
Ah apologies.

What I was trying to do here was ensure on the flow side that we had access to everything we needed - in theory we could have been throwing errors in odd places because we discovered a long way from accessing the sandbox that something had gone wrong with initialising it. Probably the right answer is that this doesn't need to implement `SandboxGroupContext` and should just hang on to the context as another property.

2022-05-27 15:00 UTC, driessamyn commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/sandbox/impl/FlowSandboxGroupContextImpl.kt
> +    }
So the `SandboxGroupContextInitializer` is `AutoCloseable`, so the idea is that everything that is created during initialisation, that you want cleaning up with the SandboxContext, should be added to the close in there.

2022-05-29 01:07 UTC, chrisr3 commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/sandbox/impl/FlowSandboxGroupContextImpl.kt
> +    }
> only the thing that creates SandboxGroupContexts and put them in cache should be able to close them.

By that logic, a `FileInputStream` shouldn't have a `close()` method either because the underlying file descriptor was created by the OS :no_mouth:.

OK, so this begs the question: How do I dispose of a `SandboxGroupContext` instance returned by `FlowSandboxService.get()`? The `FlowSandboxService.get()` is now returning a `FlowSandboxGroupContext` instead of a `SandboxGroupContext`, which means that the underlying `CloseableSndboxGroupContextImpl` object is no longer accessible to be cast to `AutoCloseable`.

Quite frankly, I don't understand how you expect this API to work. How do you intend to tell the `SandboxGroupContextService` that a flow has finished with a particular sandbox without a `close()` method for the flow to invoke at some point?

FYI: Recreating a sandbox using fresh bundles is the _only_ way to reset its `static final` fields.

2022-05-29 19:37 UTC, driessamyn commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/sandbox/impl/FlowSandboxGroupContextImpl.kt
> +    }
I can't comment on the `FlowSandboxGroupContext`, but  there isn't an API for closing `SandboxGroupContext` because we're not expecting consumers to close it.
The thing that is responsible for creating them (`SandboxGroupContextService`) is also responsible for cleaning them up, and that isn't the consumer of the API.

> How do you intend to tell the SandboxGroupContextService that a flow has finished with a particular sandbox

You're not because the `SandboxGroupContextService` decides when to clean up the sandbox and when to keep it in cache. This isn't the responsibility of the consumer of the API.
The flow doesn't need to let the service know it's finished with the sandbox and it certainly shouldn't close it because the next flow invocation may want to re-use it.
The API contract gives no guarantees about the Sandbox being freshly created or not.

2022-05-29 19:38 UTC, driessamyn commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/sandbox/impl/FlowSandboxGroupContextImpl.kt
> +    }
> By that logic, a FileInputStream shouldn't have a close() method either because the underlying file descriptor was created by the OS 

No, you can create a FileInputStream, so you can close it. In this case, it's the SandboxGroupContextService that creates the SandboxGroupContext, so it will make sure it's cleaned up.

2022-05-30 08:11 UTC, chrisr3 commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/sandbox/impl/FlowSandboxGroupContextImpl.kt
> +    }
@driessamyn I created this PR because I _require_ a means to destroy a flow sandbox _I_ have created by invoking `FlowSandboxService.get()`. Otherwise I cannot test for memory leaks and incomplete clean-up. And up until the flow team decided to wrap their `SandboxGroupContext` inside a `FlowSandboxGroupContext` last week, I was able to access the `close()` method by casting the object to `AutoCloseable`.

This PR just restores that capability by modifying `FlowSandboxGroupContextmpl` to implement `AutoCloseable`, and _not_ by modifying `FlowSandboxGroupContext` to extend `AutoCloseable`. This shouldn't be as issue; the `SandboxGroupContext` APIs are unaffected.

2022-05-30 09:05 UTC, driessamyn commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/sandbox/impl/FlowSandboxGroupContextImpl.kt
> +    }
Again, I can't comment on the design of `FlowSandboxService`, but it should not close a `SandboxGroupContext` as it's not responsible for its lifecycle and hence, the interface isn't Closeable.
If the `FlowSandboxService` would close the `SandboxGroupContext` when it's "done" with it, it would prevent us caching and re-using one.

2022-05-30 09:28 UTC, chrisr3 commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/sandbox/impl/FlowSandboxGroupContextImpl.kt
> +    }
Conversely, I don't believe the `SandboxGroupContextComponent` should close a `SandboxGroupContext` that is currently executing a flow either :no_mouth:. But where is the API that allows the flow service to tell the `SandboxGroupContextComponent` that it has finished using its `SandboxGroupContext`?

If `SandboxGroupContext` objects were reference-counted, and the `SandboxGroupContextComponent` could be configured to destroy contexts as soon as their reference counts reached zero, then that would work for me too.

2022-05-31 16:22 UTC, JamesHR3 approved these changes
I don't think I have much to add to the discussion at this point. The compromise here seems fine.

2022-05-31 16:25 UTC, chrisr3 commented
> I don't think I have much to add to the discussion at this point. The compromise here seems fine.

And it's not as if I was suggesting adding anything that didn't exist _before_ `FlowSandboxGroupContext` was created... :wink: :facepalm:.

2022-05-31 16:46 UTC, driessamyn approved these changes

2022-05-31 16:46 UTC, merged