CORE-4868 - sandbox changes for force cpi upload
corda/corda-runtime-os pull request #1385
Opened 2022-05-30 17:02 UTC by conal-smith

The main changes to look at first:
- CpkReadService API change to the get function and for implementation change the key of the map to checksum of CPK.
- VirtualNodeContext now has cpkFileChecksums rather than CPKIdentifiers because they uniquely identify files loaded from disk by CpkReadService.
- workers-smoketest build.gradle now builds two calculators and makes assertions about these in VirtualNodeRpcTest, including ability to run the new multiplication calculator, which verifies the flow sandbox cache has been updated and we're able to run the correct flow

See the following illustration:
![image](https://user-images.githubusercontent.com/68279385/175280252-63997dc2-70c9-4ebf-99e9-2ae246854519.png)

2022-06-20 15:45 UTC, conalsmith-r3 commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/persistence/DatabaseChunkPersistence.kt
> +            val cpiMetadataEntity = createCpiMetadataEntity(cpi, cpiFileName, checksum, requestId, groupId, cpkMetadataEntities)
Changes to `persistMetadataAndCpks` allows fetching existing CpiCpk entities so when we merge them, their `@Version` is preserved.

Also preserves version for CpkMetadataEntity and CpkFileEntity.

2022-06-23 09:32 UTC, conalsmith-r3 commented on components/chunking/chunk-db-write-impl/src/integrationTest/kotlin/net/corda/chunking/db/impl/tests/DatabaseChunkPersistenceTest.kt
> +        findAndAssertCpk(cpi.metadata.cpiId, cpk.metadata.cpkId, thirdChecksum.toString(), 2, 4, 2)
I found that https://github.com/corda/corda-runtime-os/pull/1483 actually lacked a test that made sure all the CPK entities could copy over a version higher than 1.

I found issue using kotlin copy() function where some fields weren't being copied, including the version field and insertTimestamp.

For now, I'm just creating new objects instead of "copying" data classes. There is a separate PR to see if we can use `em.getReference()`  and I'd prefer to get this jira finished and move onto that later. https://r3-cev.atlassian.net/browse/CORE-5271

2022-06-23 09:37 UTC, conalsmith-r3 commented on libs/packaging/packaging-core/src/main/kotlin/net/corda/libs/packaging/core/CpkIdentifier.kt
> +            0//todo conal - remove this
No longer need entityVersion on CpkIdentifier avro object, so I'll remove it later.

2022-06-23 09:38 UTC, conalsmith-r3 commented on libs/virtual-node/cpi-datamodel/src/main/kotlin/net/corda/libs/cpi/datamodel/CpiCpkEntity.kt
> +        val copy = CpiCpkEntity(
Here is where I saw using this.copy was not copying over entityVersion or insertTimestamp.

2022-06-23 09:40 UTC, conalsmith-r3 commented on libs/virtual-node/cpi-datamodel/src/main/kotlin/net/corda/libs/cpi/datamodel/CpiMetadataEntity.kt
> -            cpks = cpks.map { (originalFileName, cpiCpkEntity) ->
This also shouldn't have been creating new CpiCpk from the newly updated objects we passed in. But still, the new cpiCpk object didn't have insertTimestamp or entityVersion on it due to above copy issue.

2022-06-23 09:41 UTC, sprintengine commented on libs/virtual-node/sandbox-group-context/src/main/kotlin/net/corda/sandboxgroupcontext/VirtualNodeContext.kt
> +    val cpkFileChecksums: Set<SecureHash>,
Here is part of the crux of the change, we identify the CPKs this context has by their cpkFileChecksum as this is a natural unique identifier and we make sure we're targetting the correct cpk when it comes to finding the CPK from CpkReadService.

2022-06-23 09:42 UTC, conalsmith-r3 commented on testing/cpbs/calculator-for-cache-invalidation-testing/src/main/kotlin/net/cordapp/testing/calculator/CalculatorFlow.kt
> +class CalculatorFlow : RPCStartableFlow {
Multiplication calculator, produces exactly the same artifact as addition calculator so we can "force" upload it to overwrite the existing calculator.

2022-06-23 09:43 UTC, conalsmith-r3 commented on components/virtual-node/cpk-read-service/src/main/kotlin/net/corda/cpk/read/CpkReadService.kt
> +    fun get(cpkFileChecksum: SecureHash): Cpk?
Change to this API is important, allows us to correctly identify CPKs, now that multiple can have same cpkId, but they'll always have different fileChecksums

2022-06-23 09:44 UTC, conalsmith-r3 commented on components/virtual-node/cpk-read-service-impl/src/main/kotlin/net/corda/cpk/read/impl/CpkReadServiceImpl.kt
> +    private val cpksByChecksum = ConcurrentHashMap<SecureHash, Cpk>()
And changing this map to be keyed off the cpkFileChecksum to allow the API change.

2022-06-23 10:40 UTC, conalsmith-r3 commented on libs/virtual-node/cpi-datamodel/src/main/kotlin/net/corda/libs/cpi/datamodel/CpkMetadataEntity.kt
> +        copy.entityVersion = entityVersion
I think this entity should have var fields i.e. cpkFileChecksum, formatVersion, serializedMetadata, and id should be a val

2022-06-23 10:41 UTC, conalsmith-r3 commented on libs/virtual-node/cpi-datamodel/src/main/kotlin/net/corda/libs/cpi/datamodel/CpkFileEntity.kt
>          data: ByteArray,
fileChecksum, data, (insertTimestamp?) should be var fields, id should be a val

2022-06-23 11:06 UTC, conalsmith-r3 commented on libs/virtual-node/cpi-datamodel/src/main/kotlin/net/corda/libs/cpi/datamodel/CpiCpkEntity.kt
> +        val copy = CpiCpkEntity(
I'd quite like to improve these, I'll look into it.

2022-06-23 12:54 UTC, vkolomeyko commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/virtualnode/VirtualNodeRpcTest.kt
> +                assertThat(getCpkTimestamp()).isAfter(initialCpkTimeStamp)
I wonder if we can assert `entityVersion` being incremented here as well?

2022-06-23 12:54 UTC, vkolomeyko commented on libs/packaging/packaging-core/src/main/kotlin/net/corda/libs/packaging/core/CpkIdentifier.kt
> +            0//todo conal - remove this
Perhaps, we should raise a dedicated Jira for that, as this is likely to require `corda-api` change.

2022-06-23 13:01 UTC, conalsmith-r3 commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/virtualnode/VirtualNodeRpcTest.kt
> +                assertThat(getCpkTimestamp()).isAfter(initialCpkTimeStamp)
We'd have to add entityVersion onto CpkMetadata (cpi-upload-endpoints) as well as CpkMetadata (packaging-core) and the corresponding avro object CpkMetadata. However, maybe this will be required anyway when we move on to vnode lifecycle update, entityVersion may be required on the message bus for optimistic locking. I think for this PR, its enough to be without it, and maybe add in a separate PR or separate jira. Wdyt?

2022-06-23 13:37 UTC, conalsmith-r3 commented
Just fixing up a few issues post-rebase with recent changes to flow db integration

2022-06-23 15:50 UTC, driessamyn requested changes

2022-06-23 15:50 UTC, driessamyn commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/virtualnode/VirtualNodeRpcTest.kt
> +        Thread.sleep(FLOW_WAIT_DURATION.toMillis())
Bit unrelated to this PR but it might be worth checking with @owenstanford if this is still needed as I think it was being addressed and it would save you approx 60 seconds each time you run the test ;)

2022-06-23 15:50 UTC, driessamyn commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/virtualnode/VirtualNodeRpcTest.kt
> +                assertThat(getCpkTimestamp()).isAfter(initialCpkTimeStamp)
I think it's probably only the CPI entity version that is relevant as that is what you push. In terms of the API, the CPK entity version isn't that relevant, but then having it on the API may be useful from a troubleshooting point of view.
My feeling is, if we add it, probably under a separate JIRA/PR is fine.

2022-06-23 15:50 UTC, driessamyn commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/persistence/DatabaseChunkPersistence.kt
> +            val cpiCpkEntities = cpi.cpks.mapTo(HashSet()) { cpk ->
A bit outside the scope of this change, but could we take the opportunity to rename these methods? `persist` and `update` aren't distinctive enough. The original intention was `persist` could be generic (create or update), but that's not how it's panned out, so let's make it explicit.

2022-06-23 15:50 UTC, driessamyn commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/persistence/DatabaseChunkPersistence.kt
> +                        "1",
format version needs to be taken from the metadata: `cpk.metadata.manifest.cpkFormatVersion`

(this was relatively recently added) - FYI @josephzunigadaly

2022-06-23 15:50 UTC, driessamyn commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/persistence/DatabaseChunkPersistence.kt
> +                entityToUpdate.metadata.formatVersion = "1"
`cpk.metadata.manifest.cpkFormatVersion`

2022-06-23 15:50 UTC, driessamyn commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/persistence/DatabaseChunkPersistence.kt
> +                        "1",
`cpk.metadata.manifest.cpkFormatVersion`

2022-06-23 15:50 UTC, driessamyn commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/persistence/DatabaseChunkPersistence.kt
> +                existingCpkFileEntity.data = Files.readAllBytes(cpk.path!!)
This doesn't make sense I think. This assumes that the "new" CPKs are different to the existing, but that isn't always the case.  I think you need to do a checksum equality test first to establish this.
Otherwise it could be a bit wasteful in case of large CPK that weren't updated (think about somebody referencing something like Tokens SDK).

2022-06-23 15:50 UTC, driessamyn commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/persistence/DatabaseChunkPersistence.kt
> +    private fun createOrUpdateCpiCpkEntities(cpi: Cpi, existingCpks: Map<CpkKey, CpiCpkEntity>): Set<CpiCpkEntity> {
Minor thing: I think it's worth maybe breaking this class up a bit. If feels like the CPI lifecycle specific things could be on their own?

2022-06-23 15:50 UTC, driessamyn commented on components/virtual-node/sandbox-group-context-service/src/test/kotlin/net/corda/sandboxgroupcontext/impl/Helpers.kt
> +    private fun mockCpkMetadata(
Bit unrelated to this PR and I don't suggest changing it here, but I wonder if we should think about putting these test object generators somewhere central in the `testing` folder as I think we do this type of thing in a few places.
Maybe alongside `testing/cpi-info-read-service-fake` ?
I'd be interested in other opinions on this.

2022-06-23 15:50 UTC, driessamyn commented on libs/virtual-node/cpi-datamodel/src/main/kotlin/net/corda/libs/cpi/datamodel/CpiMetadataEntity.kt
> +                cpks
What was the reason for pulling this out of this class?

I thought `CpiCpk` was just a mapping entity, so could stay internal to this module.

2022-06-23 15:50 UTC, driessamyn commented on libs/virtual-node/cpi-datamodel/src/main/kotlin/net/corda/libs/cpi/datamodel/CpiMetadataEntity.kt
> -            cpks = cpks.map { (originalFileName, cpiCpkEntity) ->
That's because copy only copies things that are in the data class' constructor.
Can we not do a getReference here if we need the managed entity rather than create a new one?

2022-06-23 15:53 UTC, conalsmith-r3 commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/persistence/DatabaseChunkPersistence.kt
> +    private fun createOrUpdateCpiCpkEntities(cpi: Cpi, existingCpks: Map<CpkKey, CpiCpkEntity>): Set<CpiCpkEntity> {
Yeah I have a separate PR for later to do that - https://github.com/corda/corda-runtime-os/pull/1495

2022-06-23 15:55 UTC, conalsmith-r3 commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/persistence/DatabaseChunkPersistence.kt
> +            val cpiCpkEntities = cpi.cpks.mapTo(HashSet()) { cpk ->
Yeah I have a separate task https://r3-cev.atlassian.net/browse/CORE-5271 and I'll add this comment as a todo as well.

2022-06-23 15:59 UTC, conalsmith-r3 commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/persistence/DatabaseChunkPersistence.kt
> +                        "1",
Nice one thanks!

2022-06-23 16:02 UTC, sprintengine commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/persistence/DatabaseChunkPersistence.kt
> +                existingCpkFileEntity.data = Files.readAllBytes(cpk.path!!)
Yeah good point. I'll change to add a fileChecksum equality check. But this code will be optimized as part of https://r3-cev.atlassian.net/browse/CORE-5271 anyway to use getReference and avoid loading data if possible. I haven't got a solution working for it yet so didn't include in this PR.

2022-06-23 16:16 UTC, conalsmith-r3 commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/virtualnode/VirtualNodeRpcTest.kt
> +        Thread.sleep(FLOW_WAIT_DURATION.toMillis())
It seems to work locally without this, so I'll commit it and see

2022-06-24 09:35 UTC, sprintengine commented on libs/virtual-node/cpi-datamodel/src/main/kotlin/net/corda/libs/cpi/datamodel/CpiMetadataEntity.kt
> +                cpks
I pass in `Set<CpiCpkEntity>` instead of `List<Pair<String, CpkMetadata>>` because we need to set the correct version on the `CpiCpkEntity`. Alternatively we could have passed in a `List<Triple<fileName, cpkMetadata, cpiCpkVersion>>` but I thought that was a bit messy.

EntityVersion on cpiCpk gets incremented because it has the `cpkFileChecksum` which gets updated when we update the cpkMetadata. Though I'm not sure its actually necessary to have this column on cpi_cpk.

2022-06-24 09:42 UTC, barrylapthorn commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/virtualnode/VirtualNodeRpcTest.kt
> +            // BUG:  returning "OK" feels 'weakly' typed
Is this my comment cut'n'pasted?  I commented in this smoke test quite a bit about "odd" things I encountered as potential "customer" that would do something similiar (write an app against our REST api).

2022-06-24 09:44 UTC, barrylapthorn commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/virtualnode/VirtualNodeRpcTest.kt
> +            // Cannot use `assertWithRetry` as there is a strict type `Instant`
You could extend the "DSL" if you wanted with a new `assertAfterDelay` - but this is probably just as readable.

The `assertWithRetry` only came about because clearly anything we do with REST takes some time so we need to back off and give the corda cluster time to do "stuff".

2022-06-24 09:47 UTC, barrylapthorn commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/persistence/DatabaseChunkPersistence.kt
> +            val cpiCpkEntities = cpi.cpks.mapTo(HashSet()) { cpk ->
FWIW I renamed this class to `CpiPersistence` before I reverted it yesterday.

2022-06-24 10:54 UTC, conalsmith-r3 commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/virtualnode/VirtualNodeRpcTest.kt
> +            // Cannot use `assertWithRetry` as there is a strict type `Instant`
Yeah that would make the test a bit nicer. I can do that as a follow up just to get this PR merged as it already quite a large footprint.

2022-06-24 10:59 UTC, conalsmith-r3 commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/virtualnode/VirtualNodeRpcTest.kt
> +            // BUG:  returning "OK" feels 'weakly' typed
I think it's just appearing as a change because I moved some code around when creating function to runCalculatorFlow()

2022-06-24 11:02 UTC, conalsmith-r3 commented on libs/packaging/packaging-core/src/main/kotlin/net/corda/libs/packaging/core/CpkIdentifier.kt
> +            0//todo conal - remove this
Created https://r3-cev.atlassian.net/browse/CORE-5337

2022-06-24 14:26 UTC, driessamyn commented on libs/virtual-node/cpi-datamodel/src/main/kotlin/net/corda/libs/cpi/datamodel/CpiMetadataEntity.kt
> +                cpks
Maybe that's a leftover from when we were joining using the checksum. It's probably enough for the checksum to be on CpkMetadata only.

2022-06-24 14:27 UTC, driessamyn commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/virtualnode/VirtualNodeRpcTest.kt
> +            // BUG:  returning "OK" feels 'weakly' typed
Worth noting that I believe @owenstanford is refactoring these to take flow invocation out of the vnode smoketests, into their own set.

2022-06-24 14:29 UTC, barrylapthorn commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/virtualnode/VirtualNodeRpcTest.kt
> +            // Cannot use `assertWithRetry` as there is a strict type `Instant`
Yeah, just a comment, not "changes requested" thing.

2022-06-24 14:34 UTC, sprintengine commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/virtualnode/VirtualNodeRpcTest.kt
> +            // BUG:  returning "OK" feels 'weakly' typed
I think that change has already been merged, I'm rebasing with it now. The VirtualNodeRpcTest has a few conflicts such as no longer using calculator CPK. 

I think best course of action is to split out a few cpi upload specific tests into separate smoketest class (with order 30), and there I can upload the calculators and test them out. I will still need to call flows as part of this test, was the intention to have FlowTestUtils the only test that invokes flows? I guess as long as the flow tests run first that's OK (they are defined with `@Order(20)` at the class level.

2022-06-27 07:25 UTC, driessamyn commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/Utils.kt
> +const val CALCULATOR_CPI_NAME = "calculator"
Do we need 2 smoketest CPIs?
These are just smoketests, so should be a single happy path testcase through the system. To reduce maintenance overhead, I think we should reduce the number of test apps etc.

2022-06-27 07:32 UTC, driessamyn commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/cpi/CpiForceUploadRpcTest.kt
> +        }
I would prefer it if we didn't have overlapping test cases.
I think these could be additions to the existing tests.
If it's a matter of separating out tests in their own classes, we can [order the test class execution](https://junit.org/junit5/docs/snapshot/user-guide/index.html#writing-tests-test-execution-order-classes) similar to how we already order the method execution.

2022-06-27 08:20 UTC, barrylapthorn commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/Utils.kt
> +const val CALCULATOR_CPI_NAME = "calculator"
I think Owen added the `flow-worker-dev` in a previous PR - not sure about this one though.

2022-06-27 10:04 UTC, sprintengine commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/Utils.kt
> +const val CALCULATOR_CPI_NAME = "calculator"
Discussed with Viktor and Dries - I'll add a flow to flow-worker-dev that I can alter in a force-uploaded CPI and make an assertion on the return string. I'll revert a few changes here to the smoke tests.

2022-06-27 13:32 UTC, conalsmith-r3 commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/cpi/CpiForceUploadRpcTest.kt
> +        }
We now have a few extra tests in VirtualNodeRpcTest to test the force upload functionality. It was also required we run flows from this test, hence why it uses a few functions from the FlowTestUtils utility class.

2022-06-27 13:43 UTC, barrylapthorn commented on components/virtual-node/sandbox-group-context-service/src/test/kotlin/net/corda/sandboxgroupcontext/impl/Helpers.kt
> +    private fun mockCpkMetadata(
We should move more generators into the `testing` folder, though in this case I think in the new "packaging core"  these objects are easily constructable so do not need to be mocked (IIRC v1 cpi/cpk instances could only be easily generated by parsing an actual CPI).

2022-06-27 15:36 UTC, sprintengine commented on libs/virtual-node/cpi-datamodel/src/main/kotlin/net/corda/libs/cpi/datamodel/CpiMetadataEntity.kt
> +                cpks
Added to https://r3-cev.atlassian.net/browse/CORE-5271 to take care of

2022-06-27 15:39 UTC, driessamyn approved these changes
LGTM

2022-06-27 16:04 UTC, vkolomeyko approved these changes

2022-06-27 16:04 UTC, merged