CORE-5040 Config DB/Kafka reconciliation integration
corda/corda-runtime-os pull request #1405
Opened 2022-06-06 12:18 UTC by kyriathar

WIP: this is raised to fix issues from changing Configuration.version type to int.

2022-06-07 13:49 UTC, driessamyn requested changes

2022-06-07 13:49 UTC, driessamyn commented on applications/tools/kafka-setup/src/main/kotlin/net/corda/tools/kafka/KafkaConfigUploader.kt
> +                ConfigurationSchemaVersion(majorVersion.toInt(), minorVersion.toInt())
I'm not sure this is the right thing to do. Schema version for config is always 1.0 for now AFAIK, so we should leave it hardcoded like that.

2022-06-07 13:49 UTC, driessamyn commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/DBProcessorImpl.kt
> +    private val configKafkaReconcilerReader: ConfigReconcilerReader
Why the rename?

2022-06-07 13:49 UTC, driessamyn commented on components/configuration/configuration-write-service-impl/src/main/kotlin/net/corda/configuration/write/impl/validation/ConfigValidator.kt
> +class ConfigValidator @Activate constructor(
This is confusing as there is already a `ConfigurationValidator`.
Why do we need this?

2022-06-07 13:49 UTC, driessamyn commented on components/configuration/configuration-write-service-impl/src/main/kotlin/net/corda/configuration/write/impl/validation/ConfigValidator.kt
> +    private val smartConfigFactory = SmartConfigFactory.create(ConfigFactory.empty())
Doesn't this need the secrets service?

2022-06-07 13:49 UTC, driessamyn commented on components/configuration/configuration-write-service-impl/src/main/kotlin/net/corda/configuration/write/impl/writer/ConfigWriterProcessor.kt
> +    private val configValidator: ConfigValidator,
Why this change?

2022-06-07 13:49 UTC, driessamyn commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/DBProcessorImpl.kt
> +                event.config[ConfigKeys.RECONCILIATION_CONFIG]?.getLong(RECONCILIATION_CONFIG_INTERVAL_MS)
I think the config reconciler needs to start when bootconfig is received, as otherwise it will never trigger.

2022-06-07 13:49 UTC, driessamyn commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/DBProcessorImpl.kt
> +    private var configDbReconcilerReader: DbReconcilerReader<String, Configuration>? = null
Maybe it's worth pull all reconcilers in a separate class to simplify this code a bit.

This could possibly also make the lifecycle clearer in that the config reconciler needs to run at boot, then the others don't need to run until they received configuration.

2022-06-08 07:48 UTC, kyriathar commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/DBProcessorImpl.kt
> +    private val configKafkaReconcilerReader: ConfigReconcilerReader
Will revert, thought it made it a bit more straightforward and since we are using `kafkaReader` in reconciler stuff, perhaps we should be renaming those to `busReader` as well then to align things.

2022-06-08 08:09 UTC, kyriathar commented on components/configuration/configuration-write-service-impl/src/main/kotlin/net/corda/configuration/write/impl/validation/ConfigValidator.kt
> +    private val smartConfigFactory = SmartConfigFactory.create(ConfigFactory.empty())
This is exactly how it used to be, only brought it in here I believe.

2022-06-08 08:42 UTC, kyriathar commented on applications/tools/kafka-setup/src/main/kotlin/net/corda/tools/kafka/KafkaConfigUploader.kt
> +                ConfigurationSchemaVersion(majorVersion.toInt(), minorVersion.toInt())
Reverted

2022-06-08 08:47 UTC, kyriathar commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/DBProcessorImpl.kt
> +    private val configKafkaReconcilerReader: ConfigReconcilerReader
Reverted

2022-06-08 08:51 UTC, driessamyn commented on components/configuration/configuration-write-service-impl/src/main/kotlin/net/corda/configuration/write/impl/validation/ConfigValidator.kt
> +    private val smartConfigFactory = SmartConfigFactory.create(ConfigFactory.empty())
Looking at it again, I think it will work as we don't expect defaulting or validation of secret values. 
But, we just need to validate if you add a configuration setting with a secret that it still works once published on Kafka. We should be able to do that in a unit test.

2022-06-08 08:52 UTC, driessamyn commented on components/configuration/configuration-write-service-impl/src/main/kotlin/net/corda/configuration/write/impl/validation/ConfigValidator.kt
> +    private val smartConfigFactory = SmartConfigFactory.create(ConfigFactory.empty())
BTW. Unit tests for this are missing.

2022-06-08 09:38 UTC, kyriathar commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/DBProcessorImpl.kt
> +                event.config[ConfigKeys.RECONCILIATION_CONFIG]?.getLong(RECONCILIATION_CONFIG_INTERVAL_MS)
Good catch. So config reconciliation configuration should/ will be offered to db-worker boot configuration ok.

2022-06-08 10:08 UTC, kyriathar commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/DBProcessorImpl.kt
> +                event.config[ConfigKeys.RECONCILIATION_CONFIG]?.getLong(RECONCILIATION_CONFIG_INTERVAL_MS)
Please disregard my above comment. So config reconciliation should run at least once, to offer configuration to Kafka, and get its own configuration as well.

2022-06-08 11:06 UTC, kyriathar commented on components/configuration/configuration-write-service-impl/src/main/kotlin/net/corda/configuration/write/impl/validation/ConfigValidator.kt
> +class ConfigValidator @Activate constructor(
Removed `ConfigValidator`.

2022-06-08 11:15 UTC, kyriathar commented on components/configuration/configuration-write-service-impl/src/main/kotlin/net/corda/configuration/write/impl/writer/ConfigWriterProcessor.kt
> +    private val configValidator: ConfigValidator,
Reverted

2022-06-10 09:12 UTC, alexey-kadyrov-r3 commented on components/configuration/configuration-write-service-impl/src/main/kotlin/net/corda/configuration/write/impl/validation/ConfigValidator.kt
> +    private val smartConfigFactory = SmartConfigFactory.create(ConfigFactory.empty())
Question - how would you know that something is a secret? From the structure of the JSON schema?

2022-06-10 09:17 UTC, driessamyn commented on components/configuration/configuration-write-service-impl/src/main/kotlin/net/corda/configuration/write/impl/validation/ConfigValidator.kt
> +    private val smartConfigFactory = SmartConfigFactory.create(ConfigFactory.empty())
You don't because any configuration value of type string can be a secret.
Secrets are identified by a `configSecret` block in the config structure (https://github.com/corda/corda-runtime-os/wiki/Secrets-configuration).

2022-06-10 15:26 UTC, barrylapthorn commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/DBProcessorImpl.kt
> +    private var configDbReconcilerReader: DbReconcilerReader<String, Configuration>? = null
I was thinking of something like this:

```
interface Reconcilers : AutoCloseable {
    fun createOrUpdate(intervalMillis: Long)
}
```

then a "composite one", which contains all the others, and then you just call the top-most "composite one" from the db-processor.  That's why I was asking about all the various interval values we have (and have to add for each new reconciler).

2022-06-10 15:33 UTC, driessamyn commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/DBProcessorImpl.kt
> +    private var configDbReconcilerReader: DbReconcilerReader<String, Configuration>? = null
I think having a composite makes sense, @barrylapthorn, but I don't think we add much value by that one implementing the same interface. Somewhere we have to hardcode which reconcilers they are, so we may as well pick the interval from config at that point.
I think the above would only be useful if we don't know the list of reconcilers at compile time, but I don't think there's much value to that.

2022-06-10 15:38 UTC, LWogan reviewed
Looks ok to me, I see you left crypto boot logic in for now. It might be better to have Alexey port over the defaults to the new approach if it is not trivial for you to do.

2022-06-10 15:38 UTC, LWogan commented on components/configuration/configuration-write-service-impl/src/main/kotlin/net/corda/configuration/write/impl/writer/ConfigWriterProcessor.kt
> +            req.config = config.root().render(ConfigRenderOptions.concise())
your comment here is correct, you can delete this line

2022-06-10 15:44 UTC, kyriathar commented on components/configuration/configuration-write-service-impl/src/main/kotlin/net/corda/configuration/write/impl/writer/ConfigWriterProcessor.kt
> +            req.config = config.root().render(ConfigRenderOptions.concise())
Done

2022-06-10 15:46 UTC, kyriathar commented
Yes Crypto Config DB/Kafka reconciliation integration is going to be done under [CORE-5086](https://r3-cev.atlassian.net/browse/CORE-5086).

2022-06-10 15:59 UTC, driessamyn reviewed
Minor comment.

2022-06-10 15:59 UTC, driessamyn commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/DBProcessorImpl.kt
> +                createOrUpdateConfigReconciler(1000)
Minor thing, but this could probably be set to 0 as it should run as soon as possible rather than introduce a second delay.

2022-06-10 15:59 UTC, driessamyn commented on processors/rpc-processor/src/main/kotlin/net/corda/processors/rpc/internal/RPCProcessorImpl.kt
> -
FYI @vkolomeyko

2022-06-13 14:47 UTC, kyriathar commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/DBProcessorImpl.kt
> +                createOrUpdateConfigReconciler(1000)
Done -made it to reconciler and then schedule so we can have first Config reconciliation with 0 time offset-.

2022-06-13 16:54 UTC, driessamyn approved these changes
LGTM

2022-06-13 17:27 UTC, merged