Core 4600 kafka auth attempt2
corda/corda-runtime-os pull request #1439
Opened 2022-06-13 14:44 UTC by JasonSinclair95

changes made to enable sasl for Kafka authentication

2022-06-13 16:56 UTC, davidcurrie requested changes

2022-06-13 16:56 UTC, davidcurrie commented on charts/corda/templates/_helpers.tpl
> +- "-msasl.mechanism={{ .Values.kafka.sasl.mechanism }}"
For completeness, we should also cover the scenario where TLS is not enabled but SASL is (in which case we need to set `security.protocol=SASL_PLAINTEXT` along with the `sasl.mechanism`).

2022-06-13 16:56 UTC, davidcurrie commented on charts/corda/templates/sasl-configmap.yaml
> +kind: ConfigMap
As per my Slack message, if we're going to embed the password in here, this should be a secret, not a config map.

2022-06-13 16:56 UTC, davidcurrie commented on charts/corda/templates/topic-job.yaml
> +                {{- if .Values.kafka.sasl.enabled }}
Same again here for support SASL without TLS.

2022-06-14 15:16 UTC, davidcurrie commented on charts/corda/templates/topic-job.yaml
> +                echo "security.protocol=SASL_SSL\n" >> /tmp/working_dir/config.properties
```suggestion
                echo "security.protocol=SASL_PLAINTEXT\n" >> /tmp/working_dir/config.properties

```

2022-06-14 15:16 UTC, davidcurrie requested changes

2022-06-14 15:16 UTC, davidcurrie commented on charts/corda/templates/topic-job.yaml
> +                echo "security.protocol=SASL_SSL\n" >> /tmp/working_dir/config.properties
Worth testing this against a prereqs chart with TLS disabled but SASL enabled.

2022-06-16 14:57 UTC, JasonSinclair95 commented on charts/corda/templates/topic-job.yaml
> +                echo "security.protocol=SASL_SSL\n" >> /tmp/working_dir/config.properties
This works and all workers start. This was tested by disabling tls in the corda.values then changing the clientprotocal from sasl_tls to sasl in the prereqs.values @davidcurrie

2022-06-17 08:27 UTC, davidcurrie requested changes

2022-06-17 08:27 UTC, davidcurrie commented on charts/corda/templates/flow-worker.yaml
> +          periodSeconds: 10
I don't think this change should be here - suspect it was a bad merge as it was lowered to 5 in another PR

2022-06-17 08:27 UTC, davidcurrie commented on charts/corda/values.yaml
> +    # -- enabled/disable SASL for client connection to Kafka
```suggestion
    # -- enable/disable SASL for client connection to Kafka 

```

2022-06-17 08:27 UTC, davidcurrie commented on charts/corda/templates/kafka-sasl-secret.yaml
> +  name: {{ include "corda.fullname" . }}-sasl
I thought we'd renamed this to have `kafka` in the name?

2022-06-17 08:43 UTC, JasonSinclair95 commented on charts/corda/templates/flow-worker.yaml
> +          periodSeconds: 10
Okay

2022-06-17 08:44 UTC, JasonSinclair95 commented on charts/corda/templates/kafka-sasl-secret.yaml
> +  name: {{ include "corda.fullname" . }}-sasl
no, but ill add it now

2022-06-17 17:24 UTC, davidcurrie commented on charts/corda/templates/_helpers.tpl
> +    secretName: {{ include "corda.fullname" . }}kafka-sasl
```suggestion
    secretName: {{ include "corda.fullname" . }}-kafka-sasl

```

2022-06-20 09:18 UTC, davidcurrie requested changes

2022-06-20 09:18 UTC, davidcurrie commented on charts/corda/templates/flow-worker.yaml
> +          periodSeconds: 10
Still need to set this back to 5...

```suggestion
          periodSeconds: 5
```

2022-06-20 09:18 UTC, davidcurrie commented on charts/corda/values.yaml
> +
Sorry - the extra line was my fault (the GitHub suggestion always adds an extra newline by default for some reason)...

```suggestion
```

2022-06-20 13:30 UTC, davidcurrie approved these changes
👍

2022-06-20 14:31 UTC, merged