CORE-5120: New integration test for OpenAPI validation
corda/corda-runtime-os pull request #1488
Opened 2022-06-21 11:02 UTC by vkolomeyko

2022-06-24 11:01 UTC, vkolomeyko commented on libs/http-rpc/http-rpc-server-impl/src/main/kotlin/net/corda/httprpc/server/impl/apigen/processing/openapi/ResourceToOpenApiSpecMapper.kt
> +    val paths = Paths().apply { swaggerPathInfos.toSortedMap().forEach { addPathItem(it.key, it.value) } }
It was necessary to impose some order to simplify comparison against the baseline.

2022-06-24 11:01 UTC, vkolomeyko commented on libs/http-rpc/http-rpc-server-impl/src/main/kotlin/net/corda/httprpc/server/impl/apigen/processing/openapi/schema/OpenApiExample.kt
> +private val instant = Instant.parse("2022-06-24T10:15:30.00Z")
It is best to keep the date stable rather than using the current date to simplify comparison logic.

2022-06-24 11:02 UTC, vkolomeyko commented on libs/http-rpc/http-rpc-server-impl/src/main/kotlin/net/corda/httprpc/server/impl/factory/HttpRpcServerFactoryImpl.kt
> +        return HttpRpcServerImpl(rpcOpsImpls, rpcSecurityManager, httpRpcSettings, multiPartDir, devMode = devMode)
`devMode` was handy to expose to be able to stand-up HTTP (without SSL) server for the purpose of testcase.

2022-06-27 17:04 UTC, conalsmith-r3 commented on libs/http-rpc/http-rpc-server/src/main/kotlin/net/corda/httprpc/server/factory/HttpRpcServerFactory.kt
> +        devMode: Boolean = false
Does `devMode` actually change how anything works? I'm wondering if we can maybe get away without it?

2022-06-27 17:06 UTC, conalsmith-r3 commented on libs/http-rpc/http-rpc-server/src/main/kotlin/net/corda/httprpc/server/factory/HttpRpcServerFactory.kt
> +        devMode: Boolean = false
Oh I see it ignores insecure server connection which would otherwise stop openApi from being generated, so yes we do need it.

2022-06-27 17:15 UTC, conalsmith-r3 commented on processors/rpc-processor/src/integrationTest/resources/readme.md
> +file need to be updated or else `OpenApiCompatibilityTest` will fail.
Yes I think this is a good idea, for one it means API definitions that aren't following same pattern as others will stand out.

Also makes sure unnecessary changes to the API won't be accidentally made. The swagger baseline effectively has the definitions of our public HTTP API, and after release existing APIs shouldn't be changed. 

We should also make sure HTTP RPC team are code owners for this baseline file.

2022-06-27 17:16 UTC, conalsmith-r3 approved these changes, later dismissed
LGTM

2022-06-27 21:46 UTC, benmcmahon100 requested changes, later dismissed

2022-06-27 21:46 UTC, benmcmahon100 commented on processors/rpc-processor/src/integrationTest/kotlin/net/corda/processors/rpc/OpenApiCompatibilityTest.kt
> +            //Thread.sleep(1_000_000)
Presuming this should be dropped or does it represent something I've missed?

2022-06-28 07:36 UTC, vkolomeyko commented on libs/http-rpc/http-rpc-server/src/main/kotlin/net/corda/httprpc/server/factory/HttpRpcServerFactory.kt
> +        devMode: Boolean = false
It is possible to perform the test without `devMode`, but this would require SSL configuration to be setup. Also, HTTP Client will need to be tuned to trust a self-signed certificate. IMO this is an un-necessary complexity given that we just retrieve `swagger.json` and then immediately shut down the HTTP Server. So, I went ahead with HTTP (without `s`) route which can only be switched on with `devMode=true`.

2022-06-28 07:38 UTC, vkolomeyko commented on processors/rpc-processor/src/integrationTest/kotlin/net/corda/processors/rpc/OpenApiCompatibilityTest.kt
> +            //Thread.sleep(1_000_000)
Well, I left this comment for convenience.
I.e. if a developer would want to see SwaggerUI for their new HTTP endpoint, they can un-comment this line and connect to HTTP server started by this test.
I will add a comment to this effect.

2022-06-28 09:38 UTC, conal-smith approved these changes
LGTM

2022-06-28 09:38 UTC, benmcmahon100 approved these changes

2022-06-28 09:43 UTC, merged