NOTICK - OSGi Dependencies upgrade
corda/corda-runtime-os pull request #1499
Opened 2022-06-22 13:32 UTC by driessamyn

2022-06-22 15:23 UTC, chrisr3 requested changes
There's a new SCR too.

2022-06-22 15:23 UTC, chrisr3 commented on gradle.properties
>  felixScrVersion=2.2.0
Can you bump this to 2.2.2 please?

2022-06-22 16:13 UTC, driessamyn commented on gradle.properties
>  felixScrVersion=2.2.0
Sorry, was going to add in the comments. When I did, the `verifyApp` failed with

```
> Task :testing:apps:test-app:verifyApp FAILED
Resolution failed. Capabilities satisfying the following requirements could not be found:
    [<<INITIAL>>]
      ⇒ osgi.service: (objectClass=net.corda.osgi.api.Application)
          ⇒ [net.corda.test-app version=5.0.0.0-SNAPSHOT]
              ⇒ osgi.extender: (&(osgi.extender=osgi.component)(version>=1.5.0)(!(version>=2.0.0)))
                  ⇒ [org.apache.felix.scr version=2.2.2]
                      ⇒ osgi.wiring.package: (&(osgi.wiring.package=org.osgi.service.component)(version>=1.5.0)(!(version>=1.6.0)))
```

I didn't immediately understand why and suspected it may be relate to the version of api taking precedent. In my "picking of batches of easy ones first" approach of updating dependencies, I thought I'd get all these merged, then look into the tricky ones one-by-one.s

2022-06-23 07:58 UTC, driessamyn commented on applications/examples/amqp-custom-serializer-poc/build.gradle
> +    runtimeOnly "org.osgi:org.osgi.service.component:$osgiServiceComponentVersion"
This additional runtime dependency is needed because previously the interfaces were provided by `org.apache.felix.scr`, but not anymore in the new version.

https://issues.apache.org/jira/browse/FELIX-6521

2022-06-23 10:35 UTC, chrisr3 requested changes
Some modules already include `org.osgi.service.component` as "compileOnly", so these could just become "implementation". (This would also mean that `org.osgi.service.component` would appear in the published POM, but that shouldn't be a problem fo non-API modules.)

I also recommend adding `org.osgi.service.component` as an "integrationTestRuntimeOnly" dependency of `buildSrc/src/main/groovy/corda.osgi-test-conventions.gradle`.

2022-06-23 10:35 UTC, chrisr3 commented on libs/sandbox-internal/build.gradle
> +    testRuntimeOnly "org.osgi:org.osgi.service.component:$osgiServiceComponentVersion"
I think both `:sandbox-hooks` and `:sandbox-internal` already have a "compileOnly" dependency on `org.osgi.service.component`, which means that you might as well upgrade it to "implementation". This would then mean that you wouldn't need to add it back as "testRuntimeOnly" or "testCompileOnly".

2022-06-23 10:53 UTC, driessamyn commented on libs/sandbox-internal/build.gradle
> +    testRuntimeOnly "org.osgi:org.osgi.service.component:$osgiServiceComponentVersion"
Changed.
Along with a whole bunch of other things that needed the change. I didn't quite anticipate a patch version change to have such a wide impact. That's not a change Felix should have put in a patch version IMO.

2022-06-23 13:32 UTC, chrisr3 commented on libs/sandbox-internal/build.gradle
> +    testRuntimeOnly "org.osgi:org.osgi.service.component:$osgiServiceComponentVersion"
No, it seems more like SCR 2.3 than SCR 2.2.2 :angry:.

2022-06-23 13:43 UTC, chrisr3 requested changes
I think we can reduce the changes for the integration tests.

2022-06-23 13:43 UTC, chrisr3 commented on libs/layered-property-map/build.gradle
> +    integrationTestRuntimeOnly "org.osgi:org.osgi.service.component:$osgiServiceComponentVersion"
If these inetgration tests are `TestOSGi` tasks then you don't need to put this here. Just add it to `corda.osgi-test-conventions.gradle` instead (our convention plugin). After all, that is where the SCR dependency is being added too.
```diff
diff --git a/buildSrc/src/main/groovy/corda.osgi-test-conventions.gradle b/buildSrc/src/main/groovy/corda.osgi-test-conventions.gradle
index 4e44a98c3..a921327c4 100644
--- a/buildSrc/src/main/groovy/corda.osgi-test-conventions.gradle
+++ b/buildSrc/src/main/groovy/corda.osgi-test-conventions.gradle
@@ -45,6 +45,7 @@ dependencies {
     integrationTestRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:$junit5Version"
     integrationTestRuntimeOnly "org.apache.felix:org.apache.felix.framework:$felixVersion"
     integrationTestRuntimeOnly "org.apache.felix:org.apache.felix.scr:$felixScrVersion"
+    integrationTestRuntimeOnly "org.osgi:org.osgi.service.component:$osgiServiceComponentVersion"
     integrationTestRuntimeOnly "org.osgi:org.osgi.util.function:$osgiUtilFunctionVersion"
     integrationTestRuntimeOnly "org.osgi:org.osgi.util.promise:$osgiUtilPromiseVersion"
     integrationTestRuntimeOnly "org.slf4j:slf4j-simple:$slf4jVersion"
```

2022-06-23 13:43 UTC, chrisr3 commented on processors/crypto-processor/build.gradle
> +    integrationTestRuntimeOnly "org.osgi:org.osgi.service.component:$osgiServiceComponentVersion"
Best done in the `corda.osgi-test-conventions` plugin.

2022-06-23 13:43 UTC, chrisr3 commented on processors/member-processor/build.gradle
> +    integrationTestRuntimeOnly "org.osgi:org.osgi.service.component:$osgiServiceComponentVersion"
Best done in the `corda.osgi-test-conventions` plugin.

2022-06-23 13:43 UTC, chrisr3 commented on testing/message-patterns/build.gradle
> +    integrationTestRuntimeOnly "org.osgi:org.osgi.service.component:$osgiServiceComponentVersion"
Best done in the `corda.osgi-test-conventions` plugin.

2022-06-23 13:43 UTC, chrisr3 commented on tools/crypto-tck/build.gradle
> +    integrationTestRuntimeOnly "org.osgi:org.osgi.service.component:$osgiServiceComponentVersion"
Best done in the `corda.osgi-test-conventions` plugin.

2022-06-23 13:53 UTC, driessamyn commented on libs/layered-property-map/build.gradle
> +    integrationTestRuntimeOnly "org.osgi:org.osgi.service.component:$osgiServiceComponentVersion"
Point taken. But my intention was to bring some of our depenencies up to date, not fix the way people have set there tests up.

2022-06-23 15:05 UTC, chrisr3 commented on testing/message-patterns/build.gradle
> +    integrationTestRuntimeOnly "org.osgi:org.osgi.service.component:$osgiServiceComponentVersion"
Did you forget to remove this :innocent:?

2022-06-23 15:09 UTC, driessamyn commented on testing/message-patterns/build.gradle
> +    integrationTestRuntimeOnly "org.osgi:org.osgi.service.component:$osgiServiceComponentVersion"
No. That module doesn't use the convention plugin because it re-defines everything as it has 2 sets of osgi tests. 
I started to try to fix that up, but wasn't entirely sure that was the right thing to as I couldn't see a clean way of doing that and decided that'd be out of scope of the version upgrade.

2022-06-23 15:12 UTC, chrisr3 approved these changes
LGTM

2022-06-23 15:13 UTC, merged