CORE-4880 Persist cpk Liquibase scripts
corda/corda-runtime-os pull request #1501
Opened 2022-06-22 14:00 UTC by barrylapthorn

Persist any Liquibase script found in a cpk in to the database.

Perform a cursory check that we can parse the XML, find the root element
and that it has an `xmlns` attribute set.

Added unit tests.

Moved InMemoryZipFile to testing project.

2022-06-22 15:00 UTC, barrylapthorn commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/validation/JarWalker.kt
> +                    if (entry.name.lowercase().endsWith("jar") || entry.name.lowercase().endsWith("cpk")) {
Flagging this bit.

2022-06-22 15:02 UTC, barrylapthorn commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/validation/LiquibaseExtractor.kt
> +                            if (reader.name.localPart == XML_ROOT_LIQUIBASE_ELEMENT) {
And flagging this bit - I'm not explicitly checking the value of the `xmlns` attribute *or* the depth of the element.  I couldn't see anything obvious in the liquibase api that validates an XML file *without* using requiring database access.

2022-06-22 16:07 UTC, driessamyn requested changes
Mostly minor comments, except the one about the transaction scope.

2022-06-22 16:07 UTC, driessamyn commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/validation/CpiValidatorImpl.kt
> +        validationFunctions.extractLiquibaseScriptsFromCpi(cpi, entityManagerFactory)
Feels a bit strange for this to be in a `Validator`, but it's in line with the other things in this class. I wonder if the class should be renamed?

2022-06-22 16:07 UTC, driessamyn commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/validation/LiquibaseExtractor.kt
> +        private const val XML_ROOT_LIQUIBASE_ELEMENT = "databaseChangeLog"
Duplicate from https://github.com/corda/flow-worker/blob/5909c173db10ba36064ad9500324d44fa0e5bdaf/libs/db/db-admin/src/main/kotlin/net/corda/db/admin/LiquibaseXmlConstants.kt

Not sure if it's worth bringing in the library for this though.

2022-06-22 16:07 UTC, driessamyn commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/validation/JarWalker.kt
> +    internal class UncloseableInputStream(source: InputStream) : FilterInputStream(source) {
I think @josephzunigadaly & @mbrkic-r3 tried hard to get rid of the `UnclosableInputStream`

Do we need this JarWalker or is there something we can use from the packaging lib? @josephzunigadaly , what do you think?

2022-06-22 16:07 UTC, driessamyn commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/validation/LiquibaseExtractor.kt
> +                            if (reader.name.localPart == XML_ROOT_LIQUIBASE_ELEMENT) {
We could probably do an XSD validation as I think the XSDs are embedded in the Liquibase jar. 
But maybe not worth it and this is probably fine for now.

2022-06-22 16:07 UTC, driessamyn commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/validation/LiquibaseExtractor.kt
> +            BufferedReader(inputStream.reader()).readText()
Would it not be better to pass the stream to the `isLiquibaseXml` method and for that to return the string?

2022-06-22 16:07 UTC, driessamyn commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/validation/LiquibaseExtractor.kt
> +            entityManagerFactory.createEntityManager().transaction {
I think the transaction scope has to be for the entire CPI upload. I.e. all of the CPI/CPK data goes in or nothing.

Maybe this means that this needs to return the objects rather than persists them in this class.

2022-06-22 16:07 UTC, driessamyn commented on components/chunking/chunk-db-write-impl/src/test/kotlin/net/corda/chunking/db/impl/validation/LiquibaseExtractorTest.kt
> +        verify(em, times(1)).persist(any())
Maybe this needs to verify the contents of persist as well?

2022-06-22 16:07 UTC, driessamyn commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/validation/LiquibaseExtractor.kt
> +                val id = CpkDbChangeLogKey(cpkId.name, cpkId.version, cpkId.signerSummaryHashForDbQuery, path)
I think maybe we should remove the `MIGRATION_FOLDER` prefix from the path.
If not, we need to change https://github.com/corda/flow-worker/blob/be7a23a0618ba08e1d18237adad3acf4dad3a508/components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeDbChangeLog.kt to be aware of the prefix.

2022-06-22 16:07 UTC, driessamyn commented on components/chunking/chunk-db-write-impl/src/test/kotlin/net/corda/chunking/db/impl/validation/LiquibaseExtractorTest.kt
> +        verify(em, times(1)).persist(any())
As above. Verify contents of persist.

2022-06-23 08:50 UTC, barrylapthorn commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/validation/LiquibaseExtractor.kt
> +                            if (reader.name.localPart == XML_ROOT_LIQUIBASE_ELEMENT) {
Yes, I wasn't sure quite how "deep" we wanted to go to check that the xml is indeed xml, and also "likely to be" liquibase.  The xsd is possibly cleaner.

2022-06-23 08:52 UTC, barrylapthorn commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/validation/CpiValidatorImpl.kt
> +        validationFunctions.extractLiquibaseScriptsFromCpi(cpi, entityManagerFactory)
Originally that package (and class) were just a few simple functions.  I did almost rename this to something like `PostProcessing` or similar.

2022-06-23 08:53 UTC, barrylapthorn commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/validation/LiquibaseExtractor.kt
> +        private const val XML_ROOT_LIQUIBASE_ELEMENT = "databaseChangeLog"
Not sure why I didn't find that.  If I validate the xml using the xsd  I don't need it.

2022-06-23 08:57 UTC, barrylapthorn commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/validation/JarWalker.kt
> +    internal class UncloseableInputStream(source: InputStream) : FilterInputStream(source) {
It's internal to this class, so it's not a huge issue.

2022-06-23 09:02 UTC, barrylapthorn commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/validation/LiquibaseExtractor.kt
> +            BufferedReader(inputStream.reader()).readText()
The `isLiquibaseXml` method uses the streaming api over a stream (the string converted to a stream).  If I passed the stream in, I'd still have to write something to read the string "out".  I can flip it, but then I'll have to change all the unit tests and the `isLiquibaseXML` method is no long a `boolean` 'test' if it returns a nullable string.

2022-06-23 09:05 UTC, barrylapthorn commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/validation/LiquibaseExtractor.kt
> +            entityManagerFactory.createEntityManager().transaction {
Does it?  The actual table we're persisting in to is explicitly "cpk", and has no reference to a "cpi".

As written the only drawback (as discussed in slack call) is that this is `persist` and not `merge` so if we try and "persist" the same cpk twice in a second cpi that cpi would fail to upload all the liquibase scripts in _all_ cpks.  

Written as is, the "duplicate" cpk would be ignored (`persist` duplicate entity would be caught and handled), but we'd continue to upload the other cpks' liquibase scripts.

2022-06-23 09:07 UTC, barrylapthorn commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/validation/LiquibaseExtractor.kt
> +                val id = CpkDbChangeLogKey(cpkId.name, cpkId.version, cpkId.signerSummaryHashForDbQuery, path)
Upload just the filename, or chomp off the `migration` from the _front_ of the path (which presumably isn't in `include` directives in the XML?).

2022-06-23 09:10 UTC, barrylapthorn commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/validation/LiquibaseExtractor.kt
> +                val id = CpkDbChangeLogKey(cpkId.name, cpkId.version, cpkId.signerSummaryHashForDbQuery, path)
In fact it might be a little bit more "interesting" than that - 

![image](https://user-images.githubusercontent.com/1275154/175262772-9541d040-2d1e-4704-8e39-6f7a34b3a904.png)

2022-06-23 09:30 UTC, driessamyn commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/validation/LiquibaseExtractor.kt
> +            entityManagerFactory.createEntityManager().transaction {
Good point about the duplicate CPKs. I had been thinking about reset/update, but yes, we need to handle duplicate, similar to what we do for the CPK File.
I still think it needs to be the correct transaction scope though, that would be consistent with everything else. Otherwise we may end up with a CPI for which we have all metadata except the DB changelogs, and how do you then prevent a VNode being created with that CPI? It wouldn't be clear that that upload was incomplete.
With the other objects, if anything in the upload fails, the entire transaction should be rolled back so there are no side-effects of a failed upload.

2022-06-23 09:38 UTC, driessamyn commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/validation/LiquibaseExtractor.kt
> +                val id = CpkDbChangeLogKey(cpkId.name, cpkId.version, cpkId.signerSummaryHashForDbQuery, path)
I was thinking just chopping off `migration/` might be the cleanest as we consider that a fixed prefix.

Re: 'classloader://` see: https://github.com/corda/flow-worker/blob/471c8a004aeb69b31d5300617615cc7a94c8db8f/libs/db/readme.md

I don't think it's needed for the CPKs (in fact, I'm not convinced it's needed at all now, initially it was in there as I thought we may have system changelogs in different bundles), and we can probably deal with that in documentation in that we force all CPK relate changelogs to be in the CPK (so it can't reference a migration file in another as there's no reason for that really).

The only thing is that the reason it's in that example is that I think it supports a test, but it may be covered in another test.

2022-06-23 09:40 UTC, driessamyn commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/validation/LiquibaseExtractor.kt
> +                val id = CpkDbChangeLogKey(cpkId.name, cpkId.version, cpkId.signerSummaryHashForDbQuery, path)
Oh. Actually.
No, you're right, we need to keep the pre-fix as otherwise Liquibase itself isn't going to be able to resolve those paths.
Let's leave it as is, and we'll need to change `VirtualNodeDbChangeLog` to match. But we can assume we're not supporting `classloader://...`

2022-06-23 11:01 UTC, barrylapthorn commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/validation/LiquibaseExtractor.kt
> +                val id = CpkDbChangeLogKey(cpkId.name, cpkId.version, cpkId.signerSummaryHashForDbQuery, path)
We should not chop off the `migration` part of the path when we put it in the db, otherwise we'll have to search+replace in the XML file for all those `<include />` elements too.  

I need to investigate where that `classloader://` is coming from.  If that's in a `cpk`, we would have  to remove that from the XML regardless.

2022-06-23 11:04 UTC, barrylapthorn commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/validation/LiquibaseExtractor.kt
> +            entityManagerFactory.createEntityManager().transaction {
Then the `persist` for all cpks in a CPI would have to be a `merge` for each cpk instead if we want it in one transaction, as we don't want a duplicate insert (`persist`) to throw an entity exception and trigger a rollback of the entire transaction.

That  (probably?) means this will work in the event of a vnode "reset".

2022-06-23 14:13 UTC, barrylapthorn commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/validation/CpiValidatorImpl.kt
> +        validationFunctions.extractLiquibaseScriptsFromCpi(cpi, entityManagerFactory)
Renamed.

2022-06-23 14:14 UTC, barrylapthorn commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/validation/LiquibaseExtractor.kt
> +            entityManagerFactory.createEntityManager().transaction {
Updated to run `merge` over a collection of entities once we have them.  That should work with vnode "reset" code (subject to adding extra audit fields later).

2022-06-23 14:44 UTC, driessamyn commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/validation/LiquibaseExtractor.kt
> +                val id = CpkDbChangeLogKey(cpkId.name, cpkId.version, cpkId.signerSummaryHashForDbQuery, path)
See the readme posted above, that explains where it's coming from. It's us putting it in, but as mentioned above, we don't need to support that for CPKs, so we can assume everything starts with `migration`
And you're right we shouldn't be chopping it of, but we'll just have to make a small change in `VirtualNodeDbChangeLog`

2022-06-23 14:51 UTC, driessamyn requested changes

2022-06-23 14:51 UTC, driessamyn commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/cpi/liquibase/LiquibaseExtractor.kt
> +            }
This is still not right as it needs to be in the same transaction as the rest of the CPI/CPK data.

2022-06-23 14:51 UTC, driessamyn commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/cpi/CpiProcessorImpl.kt
> +        processingFunctions.extractLiquibaseScriptsFromCpi(cpi, entityManagerFactory)
I think this needs to be swapped around, with the extraction happening first and those files passed into the persisteToDatabase method so that it can be a single DB transaction.

(or broken up another way if you want, but the upload has to be complete or rolled back)

2022-06-23 15:02 UTC, barrylapthorn commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/cpi/CpiProcessorImpl.kt
> +        processingFunctions.extractLiquibaseScriptsFromCpi(cpi, entityManagerFactory)
I see.  That wasn't clear from the earlier discussion.

2022-06-23 15:11 UTC, barrylapthorn commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/validation/LiquibaseExtractor.kt
> +                val id = CpkDbChangeLogKey(cpkId.name, cpkId.version, cpkId.signerSummaryHashForDbQuery, path)
You know what they say about "assume".  

The correct way would be to stream the XML and when we find the `include` element and the `file` attribute, convert that to a URI, and then write the `path` part only to the XML that's going to be inserted into the db.  But if we don't need it or expect it, then "YAGNI" - no point writing it now and making this PR take any longer.

2022-06-23 15:39 UTC, dickon commented
Should we split out the refactoring move of `InMemoryZipFile` to another PR, so as to get that merged and keep this PR more focussed?

2022-06-23 15:40 UTC, dickon commented on components/chunking/chunk-db-write-impl/build.gradle
> +
The extra blank line looks redundant.

2022-06-23 15:40 UTC, dickon commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/validation/JarWalker.kt
> +        val buffer = inputStream.readAllBytes()
I feel if someone did upload a huge CPI/JAR  to us this would have the effect of mostly likely causing us to exceed our memory allocation at which point most likely Kubernetes will kill our pod before we have complete processing and I suppose (not knowing the surrounding system) we'd pick up the same piece of work, end up back here and get killed again in a loop.

2022-06-23 15:40 UTC, dickon commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/validation/JarWalker.kt
> +    private fun walk(depth: Int, inputStream: InputStream, onEntry: (String, InputStream) -> Unit) {
This code would probably be nicer to use if we returned a Sequence here rather than take the onEntry lambda, since it would allow the callers to avoid side-effects.

2022-06-23 15:40 UTC, dickon commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/validation/JarWalker.kt
> +                    if (entry.name.lowercase().endsWith("jar") || entry.name.lowercase().endsWith("cpk")) {
More robust to check for filenames ending ".jar" or ".cpk" rather than "jar" or "cpk".

2022-06-23 15:40 UTC, dickon commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/validation/LiquibaseExtractor.kt
> +                log.error("Unexpected exception when parsing possible liquibase XML file", e)
If we can we should include the filename within the archive for both these errors.

2022-06-23 15:40 UTC, dickon commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/validation/CpiValidatorImpl.kt
> +@Suppress("LongParameterList")
I suppose the compiler warning is a fair point. I wonder if some of these constructor arguments can at least have defaults, though I don't know if for instance the default for clock can make a UTCClock argument. And it might not remove the warning but would make ChunkDbWriteFactoryImpl more concise and localise the knowledge here to an extent.

2022-06-23 15:40 UTC, dickon commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/validation/CpiValidatorImpl.kt
> +        validationFunctions.extractLiquibaseScriptsFromCpi(cpi, entityManagerFactory)
I wonder if we should  inline this whole class into  ChunkWriteToDbProcessor.processChunk; it doesn't seem to be reusable.

2022-06-23 15:40 UTC, dickon commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/validation/CpiValidatorImpl.kt
> +        validationFunctions.extractLiquibaseScriptsFromCpi(cpi, entityManagerFactory)
How about we add a comment that the whole class has a few different concerns in it, and could do with being refactored? Also, is there any unit test coverage on this class, or do we rely on end to end testing?

2022-06-23 15:40 UTC, dickon commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/validation/ValidationFunctions.kt
> +        cpi.cpks.forEach { count += extractLiquibaseScriptsFromCpk(it, entityManagerFactory) }
I'd have written this something like:

   val count = cpi.cpks.map { extractLiquibaseScriptsFromCpk(it, entityManagerFactroy) }.sum()
   
but I haven't read enough r3 code to figure out if we prefer that style or not.

2022-06-23 15:40 UTC, dickon commented on components/chunking/chunk-db-write-impl/src/test/kotlin/net/corda/chunking/db/impl/validation/LiquibaseExtractorTest.kt
> +        <?xml version="1.1" encoding="UTF-8" standalone="no"?>
We don't need for a small amount of XML of the level we have in this file  this but for bigger structures it might be worth using  https://github.com/redundent/kotlin-xml-builder

2022-06-23 15:40 UTC, dickon commented on components/chunking/chunk-db-write-impl/src/test/kotlin/net/corda/chunking/db/impl/validation/LiquibaseExtractorTest.kt
> +        // We're testing a **CPI**, not a *CPK**, so we're persisting
It looks like we are testing the EXTENDABLE_CPB CPB not a CPI at this point, so I don't understand this comment.

2022-06-23 15:40 UTC, dickon commented on components/chunking/chunk-db-write-impl/src/test/kotlin/net/corda/chunking/db/impl/cpi/LiquibaseExtractorHelpersTest.kt
> +        // We're testing a **CPI**, not a *CPK**, so we're persisting
It looks to me as a newbie like the are testing a CPB here not a CPI.

2022-06-23 15:41 UTC, barrylapthorn commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/validation/ValidationFunctions.kt
> +        cpi.cpks.forEach { count += extractLiquibaseScriptsFromCpk(it, entityManagerFactory) }
I think you need a refresh - that now returns entities.  There's a bit of churn on this PR at the moment.

2022-06-23 15:47 UTC, barrylapthorn commented on components/chunking/chunk-db-write-impl/src/test/kotlin/net/corda/chunking/db/impl/cpi/LiquibaseExtractorHelpersTest.kt
> +        // We're testing a **CPI**, not a *CPK**, so we're persisting
CPI and CPB differ only by the fact that a CPI will contain a group policy file and will be cryptographically signed.

A CPK is just a jar (which must be an OSGi Bundle - which is a jar with certain attributes in the manifest), a CPB is just a collection of CPKs (but is a jar - i.e. has a manifest), and lastly the CPI, as above.

This comment is that when we iterate over a true CPI using the Cpi Reader code, it would extract the CPK information from the CPK manifest, and use the individual CPK metadata in each step of the loop here.

Because I don't care about the individual cpk metadata here, I just use the same meta data for each row I write (or entity I create) i.e.

This is doing:

```
(mock cpk, 1.0.0, hash,   <liquibase file 1>)
(mock cpk, 1.0.0, hash,   <liquibase file 2>)
(mock cpk, 1.0.0, hash,   <liquibase file 3>)
(mock cpk, 1.0.0, hash,   <liquibase file 4>)
(mock cpk, 1.0.0, hash,   <liquibase file 5>)
```

rather than

```
(cats cpk, 1.0.0, hash,   <liquibase file 1>)
(cats cpk, 1.0.0, hash,   <liquibase file 2>)
(cats cpk, 1.0.0, hash,   <liquibase file 3>)
(dogs cpk, 1.0.0, hash,   <liquibase file 4>)
(dogs cpk, 1.0.0, hash,   <liquibase file 5>)
```

2022-06-23 16:01 UTC, barrylapthorn commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/validation/LiquibaseExtractor.kt
> +                log.error("Unexpected exception when parsing possible liquibase XML file", e)
The path is printed out on next log message of the caller to this function, though I've bumped it to an error.

2022-06-23 16:06 UTC, driessamyn commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/validation/LiquibaseExtractor.kt
> +                val id = CpkDbChangeLogKey(cpkId.name, cpkId.version, cpkId.signerSummaryHashForDbQuery, path)
Ok. Let me re-phrase that.

> we can REQURE everything starts with migration

There is no use-case it AFAIK.

2022-06-23 16:10 UTC, driessamyn commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/validation/JarWalker.kt
> +        val buffer = inputStream.readAllBytes()
@josephzunigadaly will be able to confirm, but I'm 90% sure we shouldn't be using this JarWalker class but the `CpkReader` in the packaging module.
But I suggest resolving that separatly.

WRT somebody uploading a giant CPI, it'd have failed long before it gets here as the RPC worker would also run out of memory. It's a problem, but not one that we need to solve now I think.

2022-06-23 16:12 UTC, driessamyn commented on components/chunking/chunk-db-write-impl/src/test/kotlin/net/corda/chunking/db/impl/validation/LiquibaseExtractorTest.kt
> +        <?xml version="1.1" encoding="UTF-8" standalone="no"?>
I would be reluctant to bring in another 3rd party library for this as any 3rd party dependency is a liability to us and comes at a quite high cost in terms of security patching (especially when they become abandonware).

2022-06-23 16:19 UTC, driessamyn reviewed
I'm happy with this.

Just flagging this to @conalsmith-r3 as he's got a big PR with changes to `DatabaseChunkPersistence`, so the rename may be problematic if he has one too.

2022-06-23 16:19 UTC, driessamyn commented on components/chunking/chunk-db-write-impl/src/integrationTest/kotlin/net/corda/chunking/db/impl/tests/CpiDatabasePersistenceTest.kt
> +internal class CpiDatabasePersistenceTest {
FYI @conalsmith-r3 
I commented on this on a separate PR, so just flagging here as we may end up with a bit of a nasty merge conflict of both change name.

2022-06-23 16:25 UTC, sprintengine commented on components/chunking/chunk-db-write-impl/src/integrationTest/kotlin/net/corda/chunking/db/impl/tests/CpiDatabasePersistenceTest.kt
> +internal class CpiDatabasePersistenceTest {
I'd prefer we don't rename this if possible as I have another PR that refactors the database chunk persistence into two separate implementations with two different interfaces, one for chunk persistence and one for cpi persistence (https://github.com/corda/corda-runtime-os/pull/1495). and it might conflict with https://github.com/corda/corda-runtime-os/pull/1385), but this too is a big PR so its up to you.

2022-06-23 16:27 UTC, barrylapthorn commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/validation/JarWalker.kt
> +        val buffer = inputStream.readAllBytes()
The `CpkReader` has no hooks for me to say "give me the list of xml files in the `migration` folder".

2022-06-23 16:27 UTC, driessamyn commented on components/chunking/chunk-db-write-impl/src/integrationTest/kotlin/net/corda/chunking/db/impl/tests/CpiDatabasePersistenceTest.kt
> +internal class CpiDatabasePersistenceTest {
Let's be pragmatic about it. If it's ok with you @barrylapthorn, let's undo the rename, I think the rest can stay as is, but then at least @conalsmith-r3 has a fighting chance when it gets to the rebase.
Is that ok?

2022-06-23 16:30 UTC, driessamyn commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/validation/JarWalker.kt
> +        val buffer = inputStream.readAllBytes()
That's correct, which is why we probably shouldn't change this here, but I think the _right_ solution would be to integrate this with the CPKReader, given that that  will already have read the stream as part of the CPI/CPK validation that happens before this stage.
So I think we should leave it as is, and come back to it once @kyriathar 's change to integrate the verification library is in so that we avoid reading the file(s) twice.

2022-06-23 16:30 UTC, barrylapthorn commented on components/chunking/chunk-db-write-impl/src/integrationTest/kotlin/net/corda/chunking/db/impl/tests/CpiDatabasePersistenceTest.kt
> +internal class CpiDatabasePersistenceTest {
ok.  We should raise a Jira issue to rename this class at some point though.  The name is totally inaccurate now.

2022-06-23 16:32 UTC, sprintengine commented on components/chunking/chunk-db-write-impl/src/integrationTest/kotlin/net/corda/chunking/db/impl/tests/CpiDatabasePersistenceTest.kt
> +internal class CpiDatabasePersistenceTest {
I'll pick some nice names as part of https://github.com/corda/corda-runtime-os/pull/1495

2022-06-23 16:45 UTC, barrylapthorn commented on components/chunking/chunk-db-write-impl/src/integrationTest/kotlin/net/corda/chunking/db/impl/tests/CpiDatabasePersistenceTest.kt
> +internal class CpiDatabasePersistenceTest {
All renames have been "reverted".

2022-06-23 16:46 UTC, barrylapthorn commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/validation/JarWalker.kt
> +    private fun walk(depth: Int, inputStream: InputStream, onEntry: (String, InputStream) -> Unit) {
If you mean iterables - `hasNext` and `next` etc. I had an earlier version that did precisely that, but given we want to use the same code as what's already in the `CpiReader` this made a bit more sense at the time.

2022-06-23 17:10 UTC, driessamyn commented on components/chunking/chunk-db-write-impl/src/integrationTest/kotlin/net/corda/chunking/db/impl/tests/CpiDatabasePersistenceTest.kt
> +internal class CpiDatabasePersistenceTest {
🙇

2022-06-23 17:12 UTC, driessamyn approved these changes
LGTM

2022-06-23 17:19 UTC, merged