CORE-5325 `ReconcilerImpl` interval update can lead to reconciler disappearing
corda/corda-runtime-os pull request #1523
Opened 2022-06-24 16:30 UTC by kyriathar

- sets new timer on `ReconcilerImpl.onUpdateIntervalEvent`. Otherwise we are waiting for timer to wake up, which might be a big interval. Checked with debugger and the issue we had (We set first config reconciliation to run after 1 hour, and then it gets its updated configuration from the database. However, it would not start after 30 seconds as it should.) seems to get fixed.
- extracts `ReconcilerImpl` event handler to dedicated file.

2022-06-27 07:42 UTC, driessamyn requested changes
Just a couple of minor suggestions.

2022-06-27 07:42 UTC, driessamyn commented on components/reconciliation/reconciliation-impl/src/main/kotlin/net/corda/reconciliation/impl/ReconcilerImpl.kt
> +        coordinator.cancelTimer(name)
What does `cancelTimer` do when there is no timer with the given name? Does it just ignore?
Is it worth writing a test to prove that?

2022-06-27 07:42 UTC, driessamyn commented on components/reconciliation/reconciliation-impl/src/main/kotlin/net/corda/reconciliation/impl/ReconcilerImpl.kt
> +    @VisibleForTesting
Code smell.

2022-06-27 07:42 UTC, driessamyn commented on components/reconciliation/reconciliation-impl/src/main/kotlin/net/corda/reconciliation/impl/ReconcilerImpl.kt
> +    @VisibleForTesting
Code smell.
Let's try not to have `@VisibileForTesting` anywhere. It's generally a sign something isn't write with how the code is structured.

2022-06-27 09:18 UTC, kyriathar commented on components/reconciliation/reconciliation-impl/src/main/kotlin/net/corda/reconciliation/impl/ReconcilerImpl.kt
> +    @VisibleForTesting
Yes this needs to be refactored at some point, to take out the reconciler's event handler in its own file/ class. But maybe in another PR?

2022-06-27 09:18 UTC, kyriathar commented on components/reconciliation/reconciliation-impl/src/main/kotlin/net/corda/reconciliation/impl/ReconcilerImpl.kt
> +    @VisibleForTesting
Same as above.

2022-06-27 09:29 UTC, kyriathar commented on components/reconciliation/reconciliation-impl/src/main/kotlin/net/corda/reconciliation/impl/ReconcilerImpl.kt
> +        coordinator.cancelTimer(name)
Actually good point, just saw that `LifecycleStateManager.setTimer` actually cancels previous timer with same timer key so no need to call cancel previous timer in user code because it takes place in there. Will update.

2022-06-27 14:42 UTC, driessamyn commented on components/reconciliation/reconciliation-impl/src/main/kotlin/net/corda/reconciliation/impl/ReconcilerImpl.kt
> +    @VisibleForTesting
Let's not leave the tech debt build up and fix it once you are finished with your main task.

2022-06-28 16:06 UTC, kyriathar commented on components/reconciliation/reconciliation-impl/src/main/kotlin/net/corda/reconciliation/impl/ReconcilerImpl.kt
> +    @VisibleForTesting
Reconciler event handler is now extracted in its own file. `VisibleForTesting` annotations are now gone.

2022-06-28 16:56 UTC, driessamyn approved these changes
LGTM

2022-06-28 16:56 UTC, merged