CORE-5331: Use a single entity manager factory across all of DB messa…
corda/corda-runtime-os pull request #1529
Opened 2022-06-27 11:17 UTC by fowlerrr

…ge bus

2022-06-28 08:26 UTC, JamesHR3 commented on libs/messaging/db-message-bus-impl/src/main/kotlin/net/corda/messagebus/db/persistence/EmfCache.kt
> +    fun getEmf(resolvedConfig: ResolvedProducerConfig): EntityManagerFactory {
Shouldn't this just take a JDBC URL? Then you don't need both versions of this and can pull the relevant line out of each config at the call site. I was a bit concerned at first you were using the full configs as keys, which wouldn't work.

2022-06-28 08:26 UTC, JamesHR3 commented on libs/messaging/db-message-bus-impl/src/main/kotlin/net/corda/messagebus/db/persistence/EmfCache.kt
> +class EmfCache @Activate constructor(
I know it's annoying, but it is probably worth expanding the name of the class to `EntityManagerFactoryCache`. Also worth leaving a comment to explain why this needed even though the EMF should be pooling DB connections.

2022-06-28 08:49 UTC, fowlerrr commented on libs/messaging/db-message-bus-impl/src/main/kotlin/net/corda/messagebus/db/persistence/EmfCache.kt
> +    fun getEmf(resolvedConfig: ResolvedProducerConfig): EntityManagerFactory {
That was my original intent.  But we need the url, username and password, all wrapped up in those configs.  So I _could_ expose something that passes in all three instead, but felt this was more compact and readable

2022-06-28 12:20 UTC, fowlerrr commented on libs/messaging/db-message-bus-impl/src/main/kotlin/net/corda/messagebus/db/persistence/EmfCache.kt
> +    fun getEmf(resolvedConfig: ResolvedProducerConfig): EntityManagerFactory {
I've shifted the code to just use the values.  Let me know if you like the look better.

2022-06-28 16:16 UTC, JamesHR3 approved these changes, later dismissed
Seems reasonable - have you managed to verify it?

2022-06-30 10:14 UTC, driessamyn requested changes

2022-06-30 10:14 UTC, driessamyn commented on libs/messaging/db-message-bus-impl/src/main/kotlin/net/corda/messagebus/db/persistence/EntityManagerFactoryCache.kt
> +class EntityManagerFactoryCache @Activate constructor(
As discussed with @fowlerrr . I'm not very comfortable with this as we already cache EMFs that we consider cachable in https://github.com/corda/flow-worker/blob/f58549a2fb18c82161be83a85e51bf631d69285c/components/db/db-connection-manager-impl/src/main/kotlin/net/corda/db/connection/manager/impl/DbConnectionOpsCachedImpl.kt

Some, such as the VNode ones we don't want to cache (or want to ensure we evict from cache relatively quickly) as otherwise we'll quickly run out of connections as each vnode has its own connection.

I don't really understand the need for this abstraction, as there should only be a single message bus connection.

2022-07-01 11:24 UTC, fowlerrr commented on libs/messaging/db-message-bus-impl/src/main/kotlin/net/corda/messagebus/db/persistence/EntityManagerFactoryCache.kt
> +class EntityManagerFactoryCache @Activate constructor(
Okay, I've made it just a single connection for all of the message bus now.

2022-07-01 11:25 UTC, fowlerrr commented
After talking with @driessamyn I also made the auto topic creation use a pessimistic write lock rather than worry about catching various exceptions.  This should be a better way to avoid duplicate topic creations.

2022-07-04 08:00 UTC, driessamyn commented on libs/messaging/db-message-bus-impl/src/main/kotlin/net/corda/messagebus/db/persistence/DBAccess.kt
> +            entityManager.find(TopicEntry::class.java, topic)
I'm not suggesting changing this in this PR, but maybe a follow-up.
But I don't think `isCausedBy(PersistenceException::class.java)` is strong enough as this exception could be thrown for reasons other than the duplicate key exception.
I think a few options would be:

- Use a `INSERT ... ON CONFLICT DO NOTHING` query (native query and DB specific).
- Use a table lock (native query and would block any other operation on this table).
- Use `merge` rather than `persist` along with a `Version` attribute and handle the duplicate version exception (I'm not convinced this 100% rules out race conditions, though).
- When getting a `PersistenceException`, follow it by another find query. If you find an entity with the same ID, you can just move on.
- Given it's the all-in-one worker, therefore a single process, use a regular lock to ensure that the `createTopic` function is never run concurrently for a given topic name.

On reflection, I think the last might be the best trade-off.

2022-07-04 09:01 UTC, fowlerrr commented on libs/messaging/db-message-bus-impl/src/main/kotlin/net/corda/messagebus/db/persistence/DBAccess.kt
> +            entityManager.find(TopicEntry::class.java, topic)
Will this only ever be used for the all-in-one-worker?  Can we guarantee that?  I spoke briefly with @mnesbit and we might be able to can the auto create instead, given we have a set of topics to create now.  We can do something like with Kafka and have a setup create them instead.  But, again, that'll definitely be for another piece of work.

2022-07-05 16:07 UTC, driessamyn approved these changes
LGTM

2022-07-05 16:32 UTC, merged