CORE-5374: Refactor RPC Processor to use MAnagement request envelope
corda/corda-runtime-os pull request #1565
Opened 2022-06-29 11:50 UTC by benmcmahon100

2022-07-05 14:32 UTC, vkolomeyko commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/virtualnode/VirtualNodeRpcTest.kt
> +            println(vNodeJson)
We probably should remove it in the final version.

2022-07-05 14:32 UTC, vkolomeyko commented on components/virtual-node/virtual-node-rpcops-service-impl/src/main/kotlin/net/corda/virtualnode/rpcops/impl/v1/UnknownResponseDataTypeException.kt
> +class UnknownResponseDataTypeException(type: String) : Exception("Encountered a response containing data unknown type: $type")
Do we need this exception type? (it does not seem to be used)

2022-07-05 14:32 UTC, vkolomeyko commented on components/virtual-node/virtual-node-rpcops-service-impl/src/main/kotlin/net/corda/virtualnode/rpcops/impl/v1/VirtualNodeRPCOpsImpl.kt
> +            else -> throw throw UnknownResponseTypeException(resp.responseType::class.java.name)
Double `throw`

2022-07-05 14:32 UTC, vkolomeyko commented on components/virtual-node/virtual-node-rpcops-service-impl/src/main/kotlin/net/corda/virtualnode/rpcops/impl/v1/VirtualNodeRPCOpsImpl.kt
> +    ) : this(publisherFactory, virtualNodeInfoReadService, UTCClock())
Instead of having a secondary constructor, can we just have `private val clock = UTCClock()` ?
I do not think we would ever want to dependency inject anything different from `UTCClock`.

2022-07-05 14:32 UTC, vkolomeyko commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt
> +        holdingIdentity: HoldingIdentity,
It is probably best to leave those non-essential changes out of this PR.
If these formatting changes are necessary, it might be a good idea to make them as a separate PR, explicitly mentioning that it has no functional changes.

2022-07-05 14:32 UTC, vkolomeyko commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt
> +//            handleException(respFuture, e, request, cpiMetadata, holdingId)
Should we remove this comment?

2022-07-05 15:20 UTC, conalsmith-r3 commented on components/virtual-node/virtual-node-rpcops-service-impl/src/main/kotlin/net/corda/virtualnode/rpcops/impl/v1/VirtualNodeRPCOpsImpl.kt
> +    ) : this(publisherFactory, virtualNodeInfoReadService, UTCClock())
I actually prefer having the clock dependency injected, the unit test makes use of a mock clock returning EPOCH in `getVirtualNodeRPCOps`  method.

2022-07-05 15:48 UTC, conalsmith-r3 commented on components/virtual-node/virtual-node-write-service-impl/src/test/kotlin/net/corda/virtualnode/write/db/impl/tests/writer/VirtualNodeWriterProcessorTests.kt
> +        println(resp)
Don't forget to get rid of this

2022-07-05 15:58 UTC, vkolomeyko commented on components/virtual-node/virtual-node-rpcops-service-impl/src/main/kotlin/net/corda/virtualnode/rpcops/impl/v1/VirtualNodeRPCOpsImpl.kt
> +    ) : this(publisherFactory, virtualNodeInfoReadService, UTCClock())
But for the sake of a unit test, does it justify to have a secondary constructor which will never be used directly in production?
If we do need to validate the timestamp in the unit test we can always note the current time before the operation has started (as `before`) and assert that time of action is between `before` and `now`.

2022-07-05 16:13 UTC, benmcmahon100 commented on components/virtual-node/virtual-node-rpcops-service-impl/src/main/kotlin/net/corda/virtualnode/rpcops/impl/v1/VirtualNodeRPCOpsImpl.kt
> +            else -> throw throw UnknownResponseTypeException(resp.responseType::class.java.name)
![image](https://user-images.githubusercontent.com/10749142/177371351-423606f9-1887-49c2-b7f4-1409ba66b9de.png)
Seems like I'm not the only culprit! - but I've fixed

2022-07-05 16:14 UTC, benmcmahon100 commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt
> +        holdingIdentity: HoldingIdentity,
I've not got an easy way to extract the whitespace back out - ktlint applied the change for me in order to fix some other issues

2022-07-05 16:20 UTC, benmcmahon100 commented on components/virtual-node/virtual-node-rpcops-service-impl/src/main/kotlin/net/corda/virtualnode/rpcops/impl/v1/VirtualNodeRPCOpsImpl.kt
> +    ) : this(publisherFactory, virtualNodeInfoReadService, UTCClock())
I do prefer it as a pattern overall. It'd never be used for production in reality as well. It'll get more use with the new update code and the tests that'd go with it, but I'm not really strongly married to it, other than that it feels like a better solution than relying on the EPOCH timestamp

2022-07-05 16:21 UTC, benmcmahon100 commented on components/virtual-node/virtual-node-rpcops-service-impl/src/main/kotlin/net/corda/virtualnode/rpcops/impl/v1/VirtualNodeRPCOpsImpl.kt
> +    ) : this(publisherFactory, virtualNodeInfoReadService, UTCClock())
I know it's a bit obscure too and "something something Java" - but I believe different distros can also disagree on when the epoch is

2022-07-05 16:22 UTC, vkolomeyko commented on components/virtual-node/virtual-node-rpcops-service-impl/src/main/kotlin/net/corda/virtualnode/rpcops/impl/v1/VirtualNodeRPCOpsImpl.kt
> +    ) : this(publisherFactory, virtualNodeInfoReadService, UTCClock())
We had conversations with Matthew in the past where he was not particularly keen on having a non-Activate constructor just for the sake of a unit test.

2022-07-05 16:35 UTC, driessamyn commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeDbFactory.kt
> +    fun createVNodeDbs(holdingIdentityId: String, request: VirtualNodeCreateRequest): Map<VirtualNodeDbType, VirtualNodeDb> {
@dickon FYI
@benmcmahon100 beware, @dickon is making a significant change in this area for DB Schema migrations, so please synch up with him as I suspect a nasty merge conflict.
It's probably worth reducing/removing the formatting changes from this PR.

2022-07-05 16:37 UTC, driessamyn commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt
> +        }
Is this refactoring necessary?
Again, this may result in a quite unpleasant merge conflict with the changes @dickon is making.

2022-07-05 16:38 UTC, driessamyn requested changes

2022-07-05 16:38 UTC, driessamyn commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt
> +        holdingIdentity: HoldingIdentity,
Agree with @vkolomeyko here.

2022-07-05 16:39 UTC, vkolomeyko commented on components/virtual-node/virtual-node-rpcops-service-impl/src/main/kotlin/net/corda/virtualnode/rpcops/impl/v1/UnknownResponseDataTypeException.kt
> +class UnknownResponseDataTypeException(type: String) : Exception("Encountered a response containing data unknown type: $type")
This class does not seem to be used. Can we please have it deleted?

2022-07-05 16:39 UTC, vkolomeyko commented on components/virtual-node/virtual-node-rpcops-service-impl/src/main/kotlin/net/corda/virtualnode/rpcops/impl/v1/VirtualNodeRPCOpsImpl.kt
> -internal class VirtualNodeRPCOpsImpl @Activate constructor(
Please, let's revert this change and have a single `@Activate` constructor.

2022-07-05 17:01 UTC, benmcmahon100 commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt
> +        }
It needs to be done to support multiple return types in the case of virtual node updates - otherwise we'd need a whole separate topic

2022-07-06 06:18 UTC, driessamyn submitted a review, later dismissed
This PR is linked to the wrong JIRA.
That and the fact there is no description makes it hard for me to figure out why we're doing this refactoring. It seems mainly a rename/slight restructuring of the AVRO message  along with a pure cosmetic refactor, this is a very unfortunate time to do it as we have some functional changes in this area in progress.
If this change is necessary to unblock some other work, then I suggest undoing all non-essential changes so we're left with just the rename, so it will be possible for us to rebase without having to re-apply the entire PR.

2022-07-06 06:22 UTC, driessamyn commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt
> +        }
But most of the changes are simply reformatting/restructuring.

2022-07-06 09:41 UTC, benmcmahon100 commented
> This PR is linked to the wrong JIRA. That and the fact there is no description makes it hard for me to figure out why we're doing this refactoring. It seems mainly a rename/slight restructuring of the AVRO message along with a pure cosmetic refactor, this is a very unfortunate time to do it as we have some functional changes in this area in progress. If this change is necessary to unblock some other work, then I suggest undoing all non-essential changes so we're left with just the rename, so it will be possible for us to rebase without having to re-apply the entire PR.

Sorry manual copy paste error there - I've fixed the ticket number so that it matches properly. The idea of this is essentially to implement the same envelop you'd pointed me to for the virtual node operations. This is a precursor to adding and update operation for virtual node state.

WRT merging - I've had a chat with @dickon and neither of us are concerned about the others changes and we've managed not to step on each others toes. Additionally, I've just gone ahead and attempted a merge locally with minimal pain, git gets slightly confused on a function or two, but it's otherwise pretty normal.

2022-07-06 13:57 UTC, benmcmahon100 commented on components/virtual-node/virtual-node-rpcops-service-impl/src/main/kotlin/net/corda/virtualnode/rpcops/impl/v1/VirtualNodeRPCOpsImpl.kt
> +    ) : this(publisherFactory, virtualNodeInfoReadService, UTCClock())
Had a chat with Matthew and he said it's fine on the basis that it's denoted in some way that the constructor is for test. He also proposed some alternatives, but either would require a somewhat substantial bit of work. I think we should just leave it as is an re-tackle this problem on this ticket [CORE-5537](https://r3-cev.atlassian.net/browse/CORE-5537).

It was mentioned that @dimosr had a clock service for the P2P work, but @conalsmith-r3 and I were unable to find it.

2022-07-06 14:05 UTC, sprintengine commented on components/virtual-node/virtual-node-rpcops-service-impl/src/main/kotlin/net/corda/virtualnode/rpcops/impl/v1/VirtualNodeRPCOpsImpl.kt
> -internal class VirtualNodeRPCOpsImpl @Activate constructor(
Ben and I discussed with Matthew and he's OK with having the second constructor that gets called by tests as long as its indicated as such. Possibly we could use the @VisibleForTesting annotation here too. But in the long run we probably want to replace this non-osgi clock with an OSGified clock service

2022-07-06 15:06 UTC, conalsmith-r3 submitted a review, later dismissed
LGTM, once we lock corda-api and merge https://github.com/corda/corda-api/pull/451 we can bump cordaApiVersion here and merge with approval

2022-07-06 15:49 UTC, conalsmith-r3 approved these changes
LGTM

2022-07-06 16:04 UTC, merged

2022-07-06 16:28 UTC, dimosr commented on components/virtual-node/virtual-node-rpcops-service-impl/src/main/kotlin/net/corda/virtualnode/rpcops/impl/v1/VirtualNodeRPCOpsImpl.kt
> +    ) : this(publisherFactory, virtualNodeInfoReadService, UTCClock())
FWIW, the p2p team has been using the clock in a similar way e.g. we have a constructor with a default value and we only inject it from unit tests for deterministic testing (production code uses the default/UTC one). But, the p2p codebase so far has followed a slightly different approach to some other parts of the codebase, where dependency injection via OSGi happens only at the top/root level (i.e. at the processor/worker level) and components do plain constructor dependency injection manually without engaging OSGi at all.