CORE-4882: apply CPI migrations in each CPK when starting virtual node
corda/corda-runtime-os pull request #1569
Opened 2022-06-29 17:25 UTC by dickon

…

2022-06-30 08:22 UTC, driessamyn commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeDb.kt
> +    fun runLiquibaseMigrations(dbChange: DbChange) {
Name of this function may be confusing with the above as they both run liquibase migrations.

2022-06-30 08:22 UTC, driessamyn commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeDbChangeLog.kt
> +        //    https://docs.liquibase.com/concepts/bestpractices.html
Good spot. I picked this name as that's what we look for in C4 and didn't feel the need to change it.
Maybe we look for both `db.changelog-master.xml` or `db.changelog-root.xml`?

2022-06-30 08:22 UTC, driessamyn commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeDbChangeLog.kt
>          const val MASTER_CHANGE_LOG = "db.changelog-master.xml"
We need to prefix this with `migration/` (not directly related to your change).
Initially I thought we'd chop of the prefix everywhere, but @barrylapthorn pointed out that that's not practical as the prefix is also used inside the XML files.

2022-06-30 08:22 UTC, driessamyn commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeDbChangeLog.kt
> +            // CPK called "alpha-gamma" and filepath "beta"
Good spot.
Maybe we need to pick a seprating character that is not valid in a file name (`/` possibly, or maybe `//` to make it stand out from the normal directory separator ?)

2022-06-30 08:22 UTC, driessamyn commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt
> +            runCpiLiquibaseMigrations(cpiMetadata, vNodeDbs.values)
You only need 1 DB here, the VAULT one as that is the only one that has user defined schemas.

2022-06-30 08:22 UTC, driessamyn commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt
> +    private fun runCpiLiquibaseMigrations(cpiMetadata: CpiMetadataLite, vNodeDbs: Collection<VirtualNodeDb>) {
As above, this can just be a single `VirtualNodeDb` object.

2022-06-30 08:22 UTC, driessamyn commented on libs/virtual-node/cpi-datamodel/src/integrationTest/kotlin/net/corda/libs/cpi/datamodel/tests/CpkDbChangeLogEntityTest.kt
> +        </sql>
It doesn't really matter for your test, but we should really ever get these CREATE SCHEMA in CPK liquibase files.
They would likely fail with a permission issue.

2022-06-30 08:22 UTC, driessamyn commented on libs/virtual-node/cpi-datamodel/src/integrationTest/kotlin/net/corda/libs/cpi/datamodel/tests/CpkDbChangeLogEntityTest.kt
> +            persist(changeLog1)
It might be worth adding a changelog for a second CPK to `cpi1`, which would better test your changed query that we can pick up Liquibase files from multiple CPKs in a CPI.

2022-07-01 09:57 UTC, dickon commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeDb.kt
> +    fun runLiquibaseMigrations(dbChange: DbChange) {
Now called runCpiMigrations

2022-07-01 09:57 UTC, dickon commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeDbChangeLog.kt
> +        //    https://docs.liquibase.com/concepts/bestpractices.html
Now using / as separator

2022-07-01 09:58 UTC, dickon commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeDbChangeLog.kt
>          const val MASTER_CHANGE_LOG = "db.changelog-master.xml"
Added "migration/" prefix

2022-07-01 10:45 UTC, dickon commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeDbChangeLog.kt
> +            // CPK called "alpha-gamma" and filepath "beta"
I switched to `/`

2022-07-01 10:46 UTC, dickon commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt
> +    private fun runCpiLiquibaseMigrations(cpiMetadata: CpiMetadataLite, vNodeDbs: Collection<VirtualNodeDb>) {
done

2022-07-01 11:01 UTC, dickon commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt
> +            runCpiLiquibaseMigrations(cpiMetadata, vNodeDbs.values)
Done

2022-07-01 11:28 UTC, dickon commented on libs/virtual-node/cpi-datamodel/src/integrationTest/kotlin/net/corda/libs/cpi/datamodel/tests/CpkDbChangeLogEntityTest.kt
> +        </sql>
Done

2022-07-04 07:38 UTC, driessamyn requested changes
Some minor comments.

But I think it's worth debugging the E2E tests. Something is still wrong:

```
[pod/corda-rpc-worker-76c86b989f-rk2jd/corda-rpc-worker] 15:47:48.963 [qtp1651042371-99] WARN  net.corda.httprpc.server.impl.internal.HttpRpcServerInternal - Error invoking path '/api/v1/virtualnode'.
[pod/corda-rpc-worker-76c86b989f-rk2jd/corda-rpc-worker] net.corda.httprpc.exception.InternalServerException: net.corda.virtualnode.write.db.VirtualNodeWriteServiceException: Error running virtual node DB migration for CPI liquibase migrations Cause: liquibase.exception.ChangeLogParseException: liquibase.exception.SetupException: net.corda.v5.base.exceptions.CordaRuntimeException: Cannot find changelog file: com.r3.testing.testing-dogs-migration/db.changelog-master.xml
```

I think `com.r3.testing.testing-dogs-migration/db.changelog-master.xml` should be `com.r3.testing.testing-dogs/migration/db.changelog-master.xml`.

But once the migrations actually run, they should still fail until the migration scripts are also removed from the `corda-api` repo where they were temporarily added to get the E2E tests to work.

2022-07-04 07:38 UTC, driessamyn commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeDb.kt
> +        dbConnections[DDL]?.let { dbConnection ->
I think we need to log an error and throw when the connection is null rather than silently fail.

2022-07-04 07:38 UTC, driessamyn commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt
> +        if (vaultDb == null) return
`vaultDb` shouldn't be nullable here. We should log an error and throw earlier as it is not a valid state.

2022-07-04 07:38 UTC, driessamyn commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt
> +            if (changelogs.size == 0) return
changelog size of `0` is a valid scenario, but I think we should log (INFO level) here.
It'd probably also be useful to log after line 226. Maybe the name of the master file(s).

2022-07-04 07:38 UTC, driessamyn commented on components/virtual-node/virtual-node-write-service-impl/src/test/kotlin/net/corda/virtualnode/write/db/impl/tests/writer/VirtualNodeWriterProcessorTests.kt
>              clock
I think we're missing a new test in this class that verifies we're actually doing the DB migration.
For this reason, it'd make sense to mock out the find method.

2022-07-04 07:38 UTC, driessamyn commented on components/virtual-node/virtual-node-write-service-impl/src/test/kotlin/net/corda/virtualnode/write/db/impl/tests/writer/VirtualNodeWriterProcessorTests.kt
> +        }
The tests may be a bit more readable if this was a mocked function defined along the other mocks.

2022-07-04 07:39 UTC, driessamyn commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeDbChangeLog.kt
> +            "${it.id.cpkName}/${it.id.filePath}" to it.content
line 41 also needs to change.
Might be worth defining the seperator as a constant.

2022-07-04 14:55 UTC, kyriathar reviewed
Mostly minor things.

2022-07-04 14:55 UTC, kyriathar commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt
> +        val id = CpiIdentifier(cpiMetadata.id.name, cpiMetadata.id.version, cpiMetadata.id.signerSummaryHash)
Instead of creating a new `CpiIdentifier` object we could grab `cpiMetadata.id`.

2022-07-04 14:55 UTC, kyriathar commented on libs/virtual-node/cpi-datamodel/src/main/kotlin/net/corda/libs/cpi/datamodel/CpkDbChangeLogEntity.kt
> +            "${CpiCpkEntity::class.simpleName} AS i " +
Perhaps we could use better names for these SQL variables here `d` and `i`.

2022-07-04 14:55 UTC, kyriathar commented on libs/virtual-node/cpi-datamodel/src/integrationTest/kotlin/net/corda/libs/cpi/datamodel/tests/TestObject.kt
> +            val cpkId = "test-cpk-$cpkUuid.cpk"
Nitpicky: could we call this `cpkName` for consistency?

2022-07-04 14:55 UTC, kyriathar commented on libs/virtual-node/cpi-datamodel/src/integrationTest/kotlin/net/corda/libs/cpi/datamodel/tests/CpkDbChangeLogEntityTest.kt
>      init {
Needs a bit formatting here.

2022-07-04 14:55 UTC, kyriathar commented on libs/virtual-node/cpi-datamodel/src/integrationTest/kotlin/net/corda/libs/cpi/datamodel/tests/CpkDbChangeLogEntityTest.kt
> +        <createTable name="id" type="string">
I suppose we only interested into storing and fetching `CpkDbChangeLogEntity` in this DB integration test. So these liquibase contents do not need to be valid? I don't think there is a `type` attribute for `createTable` element.

2022-07-04 14:55 UTC, kyriathar commented on libs/virtual-node/cpi-datamodel/src/integrationTest/kotlin/net/corda/libs/cpi/datamodel/tests/CpkDbChangeLogEntityTest.kt
> +        dbConfig
Maybe we should keep exposing those as parameters on the `transaction` method. With their values defaulted call sites should look same as now.

2022-07-04 14:55 UTC, kyriathar commented on libs/virtual-node/cpi-datamodel/src/main/kotlin/net/corda/libs/cpi/datamodel/CpkDbChangeLogEntity.kt
> +    "SELECT NEW ${CpkDbChangeLogEntity::class.simpleName}(d.id, d.fileChecksum, d.content) " +
Not sure about this new object here, haven't ever used it, however could this mean it only fetches values for only these 3 columns therefore the rest of `CpkDbChangeLogEntity` properties are defaulted and then we will miss DB info like for e.g. `isDeleted`? @driessamyn could you please advice. Could we please enhance our test to assert these values too?

2022-07-04 14:55 UTC, kyriathar commented on libs/virtual-node/cpi-datamodel/src/integrationTest/kotlin/net/corda/libs/cpi/datamodel/tests/CpkDbChangeLogEntityTest.kt
> +            val changeLogs = findDbChangeLogForCpi(
Maybe it doesn't matter much but maybe we would want to run `findDbChangeLogForCpi` on a different transaction than inserts?

2022-07-04 14:55 UTC, kyriathar commented on libs/virtual-node/cpi-datamodel/src/integrationTest/kotlin/net/corda/libs/cpi/datamodel/tests/CpkDbChangeLogEntityTest.kt
> +    private fun transaction( callback: EntityManager.() -> Unit ): Unit = EntityManagerFactoryFactoryImpl().create(
Nitpicky: could we change `EntityManager.() -> Unit` to `(EntityManager) -> Unit` think it looks a bit better to get an `it` pointer.

2022-07-04 15:18 UTC, kyriathar commented on libs/virtual-node/cpi-datamodel/src/main/kotlin/net/corda/libs/cpi/datamodel/CpkDbChangeLogEntity.kt
> +    "SELECT NEW ${CpkDbChangeLogEntity::class.simpleName}(d.id, d.fileChecksum, d.content) " +
So yes I reproduced and we indeed not fetching values for columns outside above set (`d.id, d.fileChecksum, d.content`).

2022-07-04 15:34 UTC, kyriathar commented on libs/virtual-node/cpi-datamodel/src/main/kotlin/net/corda/libs/cpi/datamodel/CpkDbChangeLogEntity.kt
> +    "SELECT NEW ${CpkDbChangeLogEntity::class.simpleName}(d.id, d.fileChecksum, d.content) " +
After internal communication with @dickon query will be changed to filter out soft DB deleted rows at SQL level.

2022-07-04 16:03 UTC, driessamyn commented on libs/virtual-node/cpi-datamodel/src/main/kotlin/net/corda/libs/cpi/datamodel/CpkDbChangeLogEntity.kt
> +    "SELECT NEW ${CpkDbChangeLogEntity::class.simpleName}(d.id, d.fileChecksum, d.content) " +
This doesn't make sense. I think @kyriathar is correct in his initial comment. It doesn't make sense to return a `CpkDbChangeLogEntity` object that doesn't reflect what is in the DB. that's bound to catch somebody out even if today we don't need some of those 'defaulted' properties.
Why not just return `d` ?

2022-07-04 16:06 UTC, kyriathar commented on libs/virtual-node/cpi-datamodel/src/main/kotlin/net/corda/libs/cpi/datamodel/CpkDbChangeLogEntity.kt
> +    "SELECT NEW ${CpkDbChangeLogEntity::class.simpleName}(d.id, d.fileChecksum, d.content) " +
Yes indeed, we should be returning `d` but still filter out soft deleted rows at SQL level to save entity objects in memory.

2022-07-11 16:33 UTC, driessamyn approved these changes
LGTM

2022-07-11 16:54 UTC, merged