CORE-4368 MGM: Implement initial group policy REST API, and export service without persisted group policy data
corda/corda-runtime-os pull request #1600
Opened 2022-07-07 07:51 UTC by Sagar-Nenwani-R3

CORE-4368 MGM: Implement initial group policy REST API, and export service without persisted group policy data

https://r3-cev.atlassian.net/browse/CORE-4368

Currently working on Unit Tests

2022-07-07 08:04 UTC, charlieR3 commented
Was the deletion of the `.run` directory was accidental?

2022-07-07 09:19 UTC, charlieR3 reviewed
I think this might be still in progress. Adding my comments anyway for early feedback as I was most of the way through the review before realising.

2022-07-07 09:19 UTC, charlieR3 commented on components/membership/membership-client-impl/src/main/kotlin/net/corda/membership/impl/client/MGMOpsClientImpl.kt
> +        const val CLIENT_ID = "membership.ops.rpc"
Let's set this and group name to be different to the member ops client. e.g. `mgm-ops-client`

2022-07-07 09:19 UTC, charlieR3 commented on gradle.properties
> +compositeBuild=true
This will need to be reverted

2022-07-07 09:19 UTC, charlieR3 commented on dev.yaml
> +workers:
This shouldn't be checked in

2022-07-07 09:19 UTC, charlieR3 commented on debug.yaml
> +    debug:
This shouldn't be checked in

2022-07-07 09:19 UTC, charlieR3 commented on components/membership/membership-service-impl/src/main/kotlin/net/corda/membership/service/impl/MemberOpsServiceProcessor.kt
> +                    type.constructors.first { it.parameterCount == 3 }
Why `it.parameterCount == 3`?

2022-07-07 09:19 UTC, charlieR3 commented on components/membership/membership-service-impl/src/main/kotlin/net/corda/membership/service/impl/MemberOpsServiceProcessor.kt
>              RegistrationRpcRequest::class.java to RegistrationRequestHandler::class.java,
Could be nice to change this to be more like `MembershipP2PProcessor` where it's a class to factory mapping. Not saying you have to do it in this PR. Something we can do in the future. If you want to change it now then feel free.

2022-07-07 09:19 UTC, charlieR3 commented on components/membership/membership-service-impl/src/main/kotlin/net/corda/membership/service/impl/MemberOpsServiceProcessor.kt
> +                ?: throw MembershipRegistrationException("Could not find holding identity associated with ${request.holdingIdentityId}")
`MembershipRegistrationException` is for registration operations so is not applicable here. You could add a new exception here such as `MGMException` or `GroupPolicyGenerationException`.

2022-07-07 09:19 UTC, charlieR3 commented on components/membership/membership-service-impl/src/main/kotlin/net/corda/membership/service/impl/MemberOpsServiceProcessor.kt
> +                registrationProxy.register(holdingIdentity,request.context.toMap())
Oh maybe this PR is still in progress? This is trying to register, not generate a group policy file.

2022-07-07 09:19 UTC, charlieR3 commented on components/membership/membership-http-rpc/src/main/kotlin/net/corda/membership/httprpc/v1/MGMRpcOps.kt
> +    description = "MGM Registration APIs",
```suggestion
    description = "Membership Group Management APIs",
```

2022-07-07 09:19 UTC, charlieR3 commented on components/membership/membership-http-rpc/src/main/kotlin/net/corda/membership/httprpc/v1/MGMRpcOps.kt
> +     * @return [RegistrationRequestProgress] to indicate the last known status of the registration request based on
This return type is wrong

2022-07-07 09:19 UTC, charlieR3 commented on components/membership/membership-http-rpc/src/main/kotlin/net/corda/membership/httprpc/v1/MGMRpcOps.kt
> +    ): Set<Map.Entry<String, String?>>
Group policy doesn't match this return type. I would expect this to be either a json `String` or `Map<String, Any?>`

2022-07-07 09:19 UTC, charlieR3 commented on components/membership/membership-client/src/main/kotlin/net/corda/membership/client/MGMOpsClient.kt
> +     * @return [String] to indicate the last known status of the registration request based on
Wrong return type

2022-07-07 09:19 UTC, charlieR3 commented on components/membership/membership-http-rpc-impl/src/main/kotlin/net/corda/membership/impl/httprpc/v1/MGMRpcOpsImpl.kt
> +                return memberProvidedContext.entries
Needs to returns the MGMs member context within a group policy structure from the MGM ops service.

2022-07-07 09:19 UTC, charlieR3 commented on components/membership/membership-http-rpc-impl/src/main/kotlin/net/corda/membership/impl/httprpc/v1/MGMRpcOpsImpl.kt
> +                val filteredMembers = reader.lookup(parse(holdingIdentity.x500Name))
You're doing this lookup twice. Would be easier to just do it once. i.e. here and here: `val isMgm = reader.lookup(parse(holdingIdentity.x500Name))?.isMgm`

2022-07-07 09:19 UTC, charlieR3 commented on components/membership/membership-client-impl/src/main/kotlin/net/corda/membership/impl/client/MGMOpsClientImpl.kt
> +            return emptySet()
missing implementation

2022-07-11 07:26 UTC, Sagar-Nenwani-R3 commented on components/membership/membership-client-impl/src/main/kotlin/net/corda/membership/impl/client/MGMOpsClientImpl.kt
> +            return emptySet()
For this do we need to move the implementation from `MGMRpcOpsImpl`

2022-07-11 07:26 UTC, Sagar-Nenwani-R3 commented on components/membership/membership-http-rpc-impl/src/main/kotlin/net/corda/membership/impl/httprpc/v1/MGMRpcOpsImpl.kt
> +                val filteredMembers = reader.lookup(parse(holdingIdentity.x500Name))
Tried to value returned from lookup in `filteredMembers` outside the if block
and then tried to use `filteredMembers!!.isMgm` as the if condition but the compilation failed.
Also tried null check

2022-07-11 07:26 UTC, Sagar-Nenwani-R3 commented on components/membership/membership-http-rpc/src/main/kotlin/net/corda/membership/httprpc/v1/MGMRpcOps.kt
> +    ): Set<Map.Entry<String, String?>>
Group Policy data would be stored in mgmContext.entries right? which is a kind of set I believe

2022-07-11 08:48 UTC, Sagar-Nenwani-R3 commented on components/membership/membership-client-impl/src/main/kotlin/net/corda/membership/impl/client/MGMOpsClientImpl.kt
> +            return emptySet()
do we need to make a db call via corda-api as the mgm info would be available with group reader itself

2022-07-11 13:29 UTC, YashNabar commented on components/membership/membership-http-rpc/src/main/kotlin/net/corda/membership/httprpc/v1/MGMRpcOps.kt
> +    ): Set<Map.Entry<String, String?>>
`generateGroupPolicy` should construct a JSON string from those context entries and return that string as described [here](https://github.com/corda/platform-eng-design/blob/master/core/corda-5/corda-5.0/the-host/group-policy-export/group-policy-export.md).

2022-07-11 13:37 UTC, YashNabar commented on components/membership/membership-http-rpc-impl/src/main/kotlin/net/corda/membership/impl/httprpc/v1/MGMRpcOpsImpl.kt
> +                val filteredMembers = reader.lookup(parse(holdingIdentity.x500Name))
Perhaps something more kotlin-style would give better readability and avoid extra vals and lookups.
```suggestion
                val mgm = with (provider.getGroupReader(holdingIdentity)) {
                    lookup(parse(holdingIdentity.x500Name))?.apply {
                        require(isMgm) { "complain" }
                    } ?: throw Exception()
                }
```

2022-07-12 08:24 UTC, charlieR3 commented on components/membership/membership-http-rpc/src/main/kotlin/net/corda/membership/httprpc/v1/MGMRpcOps.kt
> +    ): Set<Map.Entry<String, String?>>
What Yash said 👆
We're returning Json and the mgmContext is only a small part of that Json string.

2022-07-12 08:33 UTC, charlieR3 commented on components/membership/membership-client-impl/src/main/kotlin/net/corda/membership/impl/client/MGMOpsClientImpl.kt
> +            return emptySet()
HTTP Request -> (forwarded to) -> `MGMRpcOpsImpl` -> (calls) -> `MGMOpsClientImpl` -> (calls backend service over kafka) -> `MemberOpsServiceImpl` -> (calls) -> `MGMGroupPolicyRequestHandler` (generates and returns **GroupPolicy.json** string)

Sample GroupPolicy.json can be seen here: https://github.com/corda/platform-eng-design/blob/master/core/corda-5/corda-5.0/the-host/group-policy.md
Note the `mgmInfo` section. You are not returning just the mgm memberinfo. You must use the mgm memberinfo to build the JSON, part of which is the member info.

2022-07-12 08:43 UTC, charlieR3 commented on components/membership/membership-http-rpc/src/main/kotlin/net/corda/membership/httprpc/v1/MGMRpcOps.kt
> +    ): Set<Map.Entry<String, String?>>
How we store it and how we return it are different

2022-07-18 14:06 UTC, Sagar-Nenwani-R3 commented
> Was the deletion of the `.run` directory was accidental?

Yes, added back the .run directory

2022-07-18 14:14 UTC, Sagar-Nenwani-R3 commented on gradle.properties
> +compositeBuild=true
had been reverted 
https://github.com/corda/corda-runtime-os/blob/sagar/CORE-4368/gradle.properties#L112

2022-07-18 14:14 UTC, Sagar-Nenwani-R3 commented on dev.yaml
> +workers:
removed dev.yaml and am using debug.yaml

2022-07-18 14:15 UTC, Sagar-Nenwani-R3 commented on debug.yaml
> +    debug:
reverted the changes similar to release/os/5.0

2022-07-18 14:15 UTC, Sagar-Nenwani-R3 commented on components/membership/membership-service-impl/src/main/kotlin/net/corda/membership/service/impl/MemberOpsServiceProcessor.kt
> +                    type.constructors.first { it.parameterCount == 3 }
changed to use 2 params

2022-07-18 14:15 UTC, Sagar-Nenwani-R3 commented on components/membership/membership-service-impl/src/main/kotlin/net/corda/membership/service/impl/MemberOpsServiceProcessor.kt
> +                ?: throw MembershipRegistrationException("Could not find holding identity associated with ${request.holdingIdentityId}")
Created `GroupPolicyGenerationException` and am using here

2022-07-18 14:18 UTC, Sagar-Nenwani-R3 commented on components/membership/membership-service-impl/src/main/kotlin/net/corda/membership/service/impl/MemberOpsServiceProcessor.kt
> +                registrationProxy.register(holdingIdentity,request.context.toMap())
Removed old logic

2022-07-18 14:18 UTC, Sagar-Nenwani-R3 commented on components/membership/membership-http-rpc/src/main/kotlin/net/corda/membership/httprpc/v1/MGMRpcOps.kt
> +    description = "MGM Registration APIs",
changed to Membership Group Management

2022-07-18 14:20 UTC, Sagar-Nenwani-R3 commented on components/membership/membership-http-rpc/src/main/kotlin/net/corda/membership/httprpc/v1/MGMRpcOps.kt
> +     * @return [RegistrationRequestProgress] to indicate the last known status of the registration request based on
changed to MGMGenerateGroupPolicyResponse

2022-07-18 14:43 UTC, Sagar-Nenwani-R3 commented on components/membership/membership-client/src/main/kotlin/net/corda/membership/client/MGMOpsClient.kt
> +     * @return [String] to indicate the last known status of the registration request based on
changed to MGMGenerateGroupPolicyResponseDto

2022-07-18 14:46 UTC, Sagar-Nenwani-R3 commented on components/membership/membership-http-rpc-impl/src/main/kotlin/net/corda/membership/impl/httprpc/v1/MGMRpcOpsImpl.kt
> +                return memberProvidedContext.entries
moved this to MGMOpsClient

2022-07-19 11:55 UTC, charlieR3 requested changes

2022-07-19 11:55 UTC, charlieR3 commented on components/membership/membership-client-impl/build.gradle
> +    implementation project(":libs:membership:membership-impl")
This might no longer be necessary after rebasing. Yash moved `MemberInfoExtension` to `membership-common` instead of `membership-impl`

2022-07-19 11:55 UTC, charlieR3 commented on components/membership/membership-client-impl/src/main/kotlin/net/corda/membership/impl/client/MGMOpsClientImpl.kt
> +                        LifecycleCoordinatorName.forComponent<ConfigurationReadService>()
This will also need to follow: `MembershipGroupReaderProvider` and `VirtualNodeInfoReadService` because they also implement `Lifecycle`

2022-07-19 11:55 UTC, charlieR3 commented on components/membership/membership-client-impl/src/main/kotlin/net/corda/membership/impl/client/MGMOpsClientImpl.kt
> +                ?: throw CordaRuntimeException("Could not find holding identity associated with member.")
`ResourceNotFoundException` would be better as it's mapped to a 404 http error code

2022-07-19 11:55 UTC, charlieR3 commented on components/membership/membership-client-impl/src/main/kotlin/net/corda/membership/impl/client/MGMOpsClientImpl.kt
> +            val filteredMembers = reader.lookup(MemberX500Name.parse(holdingIdentity.x500Name))?:throw CordaRuntimeException("Could not find holding identity associated with member.")
`ResourceNotFoundException` instead

2022-07-19 11:55 UTC, charlieR3 commented on components/membership/membership-client-impl/src/main/kotlin/net/corda/membership/impl/client/MGMOpsClientImpl.kt
> +            if(filteredMembers.isMgm) {
`else throw BadRequestException("Holding identity does not represent an MGM virtual node.")`

2022-07-19 11:55 UTC, charlieR3 commented on components/membership/membership-client-impl/src/main/kotlin/net/corda/membership/impl/client/MGMOpsClientImpl.kt
> +            return  MGMGenerateGroupPolicyResponseDto(
No need for this if you throw a `BadRequestExpection` as suggested above.

2022-07-19 11:55 UTC, charlieR3 commented on components/membership/membership-client-impl/src/main/kotlin/net/corda/membership/impl/client/MGMOpsClientImpl.kt
> +        private fun generateGroupPolicyResponse(response: MGMGroupPolicyResponse): MGMGenerateGroupPolicyResponseDto =
`MGMGroupPolicyResponse` should just return a string and that string should be passed back to the user.

2022-07-19 11:55 UTC, charlieR3 commented on components/membership/membership-client/src/main/kotlin/net/corda/membership/client/dto/MGMGenerateGroupPolicyResponseDto.kt
> +data class MGMGenerateGroupPolicyResponseDto(
No need to specify every field. String return type should be enough.

2022-07-19 11:55 UTC, charlieR3 commented on components/membership/membership-http-rpc-impl/src/test/resources/SampleStaticGroupPolicy.json
> +      "-----BEGIN CERTIFICATE-----\n{truncated for readability}\n-----END CERTIFICATE-----",
Can you use real samples here? i.e. no usage of `{truncated for readability}`. You can use what's in the dynamic group policy sample file above.

2022-07-19 11:55 UTC, charlieR3 commented on components/membership/membership-service-impl/build.gradle
> +    implementation project(":libs:membership:membership-impl")
Same comment as before. I think you'll need a `membership-common` dependency now instead due to `MemberInfoExtension` moving module.

2022-07-19 11:55 UTC, charlieR3 commented on components/membership/membership-service-impl/src/main/kotlin/net/corda/membership/service/impl/MemberOpsServiceProcessor.kt
> +import net.corda.data.membership.rpc.request.*
We generally try to avoid using `*` imports as a coding style here. You can replace this with the specific imports.

2022-07-19 11:55 UTC, charlieR3 commented on components/membership/membership-service-impl/src/main/kotlin/net/corda/membership/service/impl/MemberOpsServiceProcessor.kt
> +            val registrationProtocol =
This and `synchronisationProtocol` will come from persistence and not from the member info. It being present in the member info is a bug that I believe has been fixed so it shouldn't be there anymore. Hardcode it in this PR.

```
  "registrationProtocol": "net.corda.membership.impl.registration.dynamic.member.DynamicMemberRegistrationService",
  "synchronisationProtocol": "net.corda.membership.impl.sync.dynamic.MemberSyncService",
```

2022-07-19 11:55 UTC, charlieR3 commented on components/membership/membership-service-impl/src/main/kotlin/net/corda/membership/service/impl/MemberOpsServiceProcessor.kt
> +            return MGMGroupPolicyResponse(
This needs to be returned as string.

One handy way would be to build up a map and use jackson to return it as a json string.
e.g.
```
val groupPolicy = mapOf(
            "fileFormatVersion" to 1,
            "groupId" to filteredMembers.groupId,
            "registrationProtocol"
                    to "net.corda.membership.impl.registration.staticnetwork.StaticMemberRegistrationService",
            "synchronisationProtocol"
                    to "net.corda.membership.impl.sync.staticnetwork.StaticMemberSyncService",
            "protocolParameters" to mapOf(
                "sessionKeyPolicy" to "Combined",
                "staticNetwork" to mapOf(
                    "members" to
                        staticMemberNames.map {
                            mapOf(
                                "name" to it,
                                "memberStatus" to "ACTIVE",
                                "endpointUrl-1" to "http://localhost:1080",
                                "endpointProtocol-1" to 1
                            )
                        }
                )
            ),
            "p2pParameters" to mapOf(
                "sessionTrustRoots" to listOf(
                    createCertificate(),
                    createCertificate()
                ),
                "tlsTrustRoots" to listOf(
                    createCertificate()
                ),
                "sessionPki" to "Standard",
                "tlsPki" to "Standard",
                "tlsVersion" to "1.3",
                "protocolMode" to "Authentication_Encryption"
            ),
            "cipherSuite" to mapOf(
                "corda.provider" to "default",
                "corda.signature.provider" to "default",
                "corda.signature.default" to "ECDSA_SECP256K1_SHA256",
                "corda.signature.FRESH_KEYS" to "ECDSA_SECP256K1_SHA256",
                "corda.digest.default" to "SHA256",
                "corda.cryptoservice.provider" to "default"
            )
        )
ObjectMapper().writeValueAsString(groupPolicy)
```

2022-07-19 11:55 UTC, charlieR3 commented on components/membership/membership-service-impl/src/main/kotlin/net/corda/membership/service/impl/MemberOpsServiceProcessor.kt
> +                    KeyValuePair("corda.name", filteredMembers.name.toString()),
No, we don't want to hardcode the expected keys here.

You can just map from one to the other. e.g.
```
filteredMembers.memberProvidedContext.entries.map {
    it.key to it.value
}
```
```
filteredMembers.mgmProvidedContext.entries.map {
    it.key to it.value
}
```

2022-07-19 11:55 UTC, charlieR3 commented on components/membership/membership-service-impl/src/main/kotlin/net/corda/membership/service/impl/MemberOpsServiceProcessor.kt
> +            return MGMGroupPolicyResponse(
Note: that's just a quick sample. It's for a static network so it's not identical to what you need to do but along the same lines.

2022-07-19 11:55 UTC, charlieR3 commented on debug.yaml
>  workers:
No need to check in changes to this file.

2022-07-20 13:10 UTC, Sagar-Nenwani-R3 commented on components/membership/membership-client-impl/build.gradle
> +    implementation project(":libs:membership:membership-impl")
removed `":libs:membership:membership-impl"`

2022-07-20 13:10 UTC, Sagar-Nenwani-R3 commented on components/membership/membership-client-impl/src/main/kotlin/net/corda/membership/impl/client/MGMOpsClientImpl.kt
> +                        LifecycleCoordinatorName.forComponent<ConfigurationReadService>()
added MembershipGroupReaderProvider and VirtualNodeInfoReadService

2022-07-20 13:10 UTC, Sagar-Nenwani-R3 commented on components/membership/membership-client-impl/src/main/kotlin/net/corda/membership/impl/client/MGMOpsClientImpl.kt
> +                ?: throw CordaRuntimeException("Could not find holding identity associated with member.")
Added ResourceNotFoundException

2022-07-20 13:10 UTC, Sagar-Nenwani-R3 commented on components/membership/membership-client-impl/src/main/kotlin/net/corda/membership/impl/client/MGMOpsClientImpl.kt
> +            val filteredMembers = reader.lookup(MemberX500Name.parse(holdingIdentity.x500Name))?:throw CordaRuntimeException("Could not find holding identity associated with member.")
added ResourceNotFoundException

2022-07-20 13:10 UTC, Sagar-Nenwani-R3 commented on components/membership/membership-client-impl/src/main/kotlin/net/corda/membership/impl/client/MGMOpsClientImpl.kt
> +            if(filteredMembers.isMgm) {
added else block

2022-07-20 13:10 UTC, Sagar-Nenwani-R3 commented on components/membership/membership-client-impl/src/main/kotlin/net/corda/membership/impl/client/MGMOpsClientImpl.kt
> +            return  MGMGenerateGroupPolicyResponseDto(
added else block

2022-07-20 13:10 UTC, Sagar-Nenwani-R3 commented on components/membership/membership-client-impl/src/main/kotlin/net/corda/membership/impl/client/MGMOpsClientImpl.kt
> +        private fun generateGroupPolicyResponse(response: MGMGroupPolicyResponse): MGMGenerateGroupPolicyResponseDto =
replaced MGMGenerateGroupPolicyResponseDto  with string

2022-07-20 13:10 UTC, Sagar-Nenwani-R3 commented on components/membership/membership-client/src/main/kotlin/net/corda/membership/client/dto/MGMGenerateGroupPolicyResponseDto.kt
> +data class MGMGenerateGroupPolicyResponseDto(
removed MGMGenerateGroupPolicyResponseDto  and MGMGenerateGroupPolicyResponse

2022-07-20 13:10 UTC, Sagar-Nenwani-R3 commented on components/membership/membership-service-impl/build.gradle
> +    implementation project(":libs:membership:membership-impl")
removed `":libs:membership:membership-impl"`

2022-07-20 13:10 UTC, Sagar-Nenwani-R3 commented on components/membership/membership-service-impl/src/main/kotlin/net/corda/membership/service/impl/MemberOpsServiceProcessor.kt
> +import net.corda.data.membership.rpc.request.*
it was IntelliJ replacing it with * when more than 5 classes were being used from same package
changed settings to use single imports

2022-07-21 12:07 UTC, charlieR3 commented on components/membership/membership-http-rpc-impl/src/main/kotlin/net/corda/membership/impl/httprpc/v1/ClientDtoConverters.kt
> +import net.corda.membership.client.dto.*
Could you revert this change please?

2022-07-21 12:10 UTC, charlieR3 commented on components/membership/membership-client-impl/src/test/kotlin/net/corda/membership/impl/client/MGMOpsClientTest.kt
> +            "corda.group.protocol.registration" to "corda.group.protocol.registration",
You can remove anything starting with `corda.group` from here. It's not going to be in the member info.

2022-07-21 12:21 UTC, charlieR3 reviewed
Looking good. One or two small things to fix up yet.

2022-07-21 12:21 UTC, charlieR3 commented on debug.yaml
>  workers:
This still needs to be reverted

2022-07-21 12:21 UTC, charlieR3 commented on components/membership/membership-service-impl/src/test/kotlin/net/corda/membership/service/impl/MemberOpsServiceProcessorTest.kt
> +            "corda.group.protocol.registration" to "corda.group.protocol.registration",
Can remove `corda.group` properties from the member info.

2022-07-21 12:55 UTC, Sagar-Nenwani-R3 commented on components/membership/membership-http-rpc-impl/src/main/kotlin/net/corda/membership/impl/httprpc/v1/ClientDtoConverters.kt
> +import net.corda.membership.client.dto.*
Has been reverted

2022-07-21 12:56 UTC, Sagar-Nenwani-R3 commented on components/membership/membership-client-impl/src/test/kotlin/net/corda/membership/impl/client/MGMOpsClientTest.kt
> +            "corda.group.protocol.registration" to "corda.group.protocol.registration",
Additional properties with corda.group has been removed

2022-07-21 13:06 UTC, Sagar-Nenwani-R3 commented
https://github.com/corda/corda-runtime-os/pull/1600#discussion_r926604264
can be resolved

2022-07-22 12:33 UTC, Sagar-Nenwani-R3 commented on components/membership/membership-service-impl/src/test/kotlin/net/corda/membership/service/impl/MemberOpsServiceProcessorTest.kt
> +            "corda.group.protocol.registration" to "corda.group.protocol.registration",
corda.group properties have been removed

2022-07-22 14:02 UTC, charlieR3 commented on components/membership/membership-http-rpc/src/main/kotlin/net/corda/membership/httprpc/v1/MGMRpcOps.kt
> +        path = "{holdingIdentityId}/info",
I just remembered - there was a change that went in yesterday or the day before to standardise the parameter names for this. 
Could you change `holdingIdentityId` to `holdingIdentityShortHash` in this PR so we stick with that standard? (kdocs above, path here, and parameter below (also in the implementation).

This is from the email titled **"REST API tidy-up for Holding Identity usage"**

2022-07-22 14:04 UTC, charlieR3 commented on debug.yaml
>  #    debug:
Is it possible to revert this file so we aren't changing it at all? Looks like a line ending thing

2022-07-22 14:53 UTC, Sagar-Nenwani-R3 commented on debug.yaml
>  #    debug:
added the line ending to debug.yaml

2022-07-22 14:54 UTC, Sagar-Nenwani-R3 commented on components/membership/membership-http-rpc/src/main/kotlin/net/corda/membership/httprpc/v1/MGMRpcOps.kt
> +        path = "{holdingIdentityId}/info",
made changes to use `holdingIdentityShortHash` in place of `holdingIdentityId`

2022-07-22 15:34 UTC, charlieR3 approved these changes, later dismissed

2022-07-22 16:30 UTC, charlieR3 approved these changes, later dismissed

2022-07-22 19:22 UTC, charlieR3 approved these changes

2022-07-22 19:25 UTC, merged