Jansz/core 5663/test pipeline for combined worker
corda/corda-runtime-os pull request #1635
Opened 2022-07-13 11:55 UTC by E1P3

2022-08-05 13:07 UTC, ronanbrowne approved these changes
Approved from Jenkins file POV

2022-08-05 13:29 UTC, JamesHR3 reviewed
Looks like there's some extra code coming in that should already be in the release branch - can you double check that you're properly synced up with the release branch?

2022-08-05 13:29 UTC, JamesHR3 commented on libs/messaging/db-message-bus-impl/src/main/kotlin/net/corda/messagebus/db/consumer/DBCordaConsumerImpl.kt
> +        if (topicPartitions.isEmpty()) {
I don't think we should be seeing this diff if you're trying to merge into the release branch - have you synced up properly?

2022-08-05 13:29 UTC, JamesHR3 commented on libs/messaging/db-message-bus-impl/src/main/kotlin/net/corda/messagebus/db/persistence/DBAccess.kt
> +    private val defaultNumPartitions = 3
This is being committed under https://github.com/corda/corda-runtime-os/pull/1816 right?

2022-08-05 13:32 UTC, ronanbrowne requested changes
See comments

2022-08-05 13:32 UTC, ronanbrowne commented on .ci/e2eTests/JenkinsfileCombinedWorker
> +	// remove Database see here https://github.com/corda/corda-shared-build-pipeline-steps/blob/5.0/vars/cordaPipeline.groovy#L487-L500
Sorry @E1P3 actually few minor things prior to merge, please clean up redundant comments

2022-08-05 13:32 UTC, ronanbrowne commented on .ci/e2eTests/JenkinsfileCombinedWorker
> +                //somehow ensure this runs in background and execute smoke tests , we may need some paramaters specific to combined worker
remove these comments - these were just some suggestions i think when we started

2022-08-05 13:32 UTC, ronanbrowne commented on .ci/e2eTests/JenkinsfileCombinedWorker
> +    /// Build the Jar
remove comment

2022-08-05 13:32 UTC, ronanbrowne commented on .ci/e2eTests/JenkinsfileCombinedWorker
> +
```suggestion
```

Spacing is a little odd in this method id tighten it up a bit

2022-08-05 13:32 UTC, ronanbrowne commented on .ci/e2eTests/JenkinsfileCombinedWorker
> +
```suggestion
```

As above

2022-08-05 13:32 UTC, ronanbrowne commented on .ci/e2eTests/JenkinsfileCombinedWorker
> +
```suggestion
```
as above

2022-08-05 13:32 UTC, ronanbrowne commented on .ci/e2eTests/JenkinsfileCombinedWorker
> +            // we need the DB credetals here also
Redundant comment

2022-08-05 15:33 UTC, ronanbrowne approved these changes, later dismissed
All my comments on Jenkins file have been resolved thanks @E1P3 - leaving this in @mbrkic-r3   hands to address anything on kotlin side @JamesHR3 has called out

2022-08-08 07:58 UTC, mbrkic-r3 commented on libs/messaging/db-message-bus-impl/src/main/kotlin/net/corda/messagebus/db/consumer/DBCordaConsumerImpl.kt
> +        if (topicPartitions.isEmpty()) {
It hasn't been synced up

2022-08-08 07:59 UTC, mbrkic-r3 commented on libs/messaging/db-message-bus-impl/src/main/kotlin/net/corda/messagebus/db/persistence/DBAccess.kt
> +    private val defaultNumPartitions = 3
yes

2022-08-08 16:47 UTC, ronanbrowne submitted a review, later dismissed
LGTM

2022-08-09 07:55 UTC, mbrkic-r3 commented on libs/messaging/db-message-bus-impl/src/main/kotlin/net/corda/messagebus/db/consumer/DBCordaConsumerImpl.kt
> +        if (topicPartitions.isEmpty()) {
it's rebased now

2022-08-09 08:44 UTC, driessamyn approved these changes
LGTM

2022-08-09 08:54 UTC, JamesHR3 approved these changes

2022-08-09 09:01 UTC, merged