CORE-4423: Add vnode status and update
corda/corda-runtime-os pull request #1636
Opened 2022-07-13 12:11 UTC by benmcmahon100

2022-07-13 13:25 UTC, sprintengine commented on libs/virtual-node/virtual-node-endpoints/src/main/kotlin/net/corda/libs/virtualnode/endpoints/v1/VirtualNodeRPCOps.kt
> +        path = "{virtualNodeShortId}",
The path of this API will be `/api/v1/virtualnode/{virtualNodeShortId}`.

This endpoint suggests we're updating all fields of a virtual node resource, but we're just updating its status.

Would we be better adding a `status` component to the path to indicate we're updating the status of a virtual node resource? In that sense status becomes like its own sub-resource i.e.

`PUT /api/v1/virtualnode/{virtualNodeShortId}/status`

What are your thoughts @vkolomeyko ?

2022-07-13 13:30 UTC, vkolomeyko reviewed
Looks like a reasonable start to me with few comments posted.

I think it is also important to prove with E2E tests that functionality really works.

2022-07-13 13:30 UTC, vkolomeyko commented on build.gradle
> +            files(sourceTasks.collect{ it.outputs }.flatten())
It does not seem to be immediately related to the work in this PR.
Why do we need this, please?
Possibly, we should make this change as a separate PR?

2022-07-13 13:30 UTC, vkolomeyko commented on components/virtual-node/virtual-node-rpcops-service-impl/src/main/kotlin/net/corda/virtualnode/rpcops/impl/v1/VirtualNodeRPCOpsImpl.kt
> +    override fun updateVirtualNodeState(
As discussed, this needs to go under `VirtualNodeMaintenanceRPCOps`.

2022-07-13 13:30 UTC, vkolomeyko commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeEntityRepository.kt
> +            val latestVirtualNodeInstance = it.createQuery(
Should we refactor this sort of look-up into a separate method? As I would imagine there will be other instances when lookup by `holdingIdShortHash` will be required.

2022-07-13 13:30 UTC, vkolomeyko commented on libs/virtual-node/virtual-node-endpoints/src/main/kotlin/net/corda/libs/virtualnode/endpoints/v1/types/HTTPVirtualNodeStateChangeResponse.kt
> + * Exactly one of [cpiId] and [cpiFileChecksum] should be null.
Looks like this is a copy/paste from elsewhere.

2022-07-13 13:33 UTC, vkolomeyko commented on libs/virtual-node/virtual-node-endpoints/src/main/kotlin/net/corda/libs/virtualnode/endpoints/v1/VirtualNodeRPCOps.kt
> +        path = "{virtualNodeShortId}",
On Jira description, I put is as: `PUT /api/v1/maintenance/virtualnode/{virtualNodeId}/state?{state}`, part of the existing VirtualNodeMaintenanceRPCOps interface.

2022-07-13 13:35 UTC, conalsmith-r3 commented on libs/virtual-node/virtual-node-endpoints/src/main/kotlin/net/corda/libs/virtualnode/endpoints/v1/VirtualNodeRPCOps.kt
> +        path = "{virtualNodeShortId}",
Yes that's perfect, so also need to change body parameter to query parameter.

2022-07-13 13:42 UTC, benmcmahon100 commented on build.gradle
> +            files(sourceTasks.collect{ it.outputs }.flatten())
Ah yeah was some science to see would incremental builds work - but there's some more work that needs to be done to make it work on the plugin side. Will revert that back before opening for review

2022-07-13 13:42 UTC, benmcmahon100 commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeEntityRepository.kt
> +            val latestVirtualNodeInstance = it.createQuery(
There is a method that does this - but it takes it out of it's entity form. Might be worth refactoring that though instead

2022-07-13 13:42 UTC, conalsmith-r3 commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeEntityRepository.kt
> +    internal fun setVirtualNodeState(entityManager: EntityManager, holdingIdShortHash: String, newState: String) {
We should have associated integration test in `VirtualNodeEntityRepositoryTest`

2022-07-13 13:42 UTC, benmcmahon100 commented on libs/virtual-node/virtual-node-endpoints/src/main/kotlin/net/corda/libs/virtualnode/endpoints/v1/types/HTTPVirtualNodeStateChangeResponse.kt
> + * Exactly one of [cpiId] and [cpiFileChecksum] should be null.
Yep haven't had a chance to go through those yet - will be doing that after writing some tests

2022-07-13 13:48 UTC, conalsmith-r3 commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeEntityRepository.kt
> +            it.persist(updatedVirtualNodeInstance)
Don't need to call persist here, just merge

2022-07-13 13:48 UTC, conalsmith-r3 commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeEntityRepository.kt
> +            it.flush()
Shouldn't need to call flush here

2022-07-13 13:52 UTC, benmcmahon100 commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeEntityRepository.kt
> +            it.flush()
Seemed not to work without them, but possibly just a slow reconciliation. I'll give it a go without them

2022-07-13 13:52 UTC, conalsmith-r3 commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeEntityRepository.kt
> +                        entityVersion = latestVirtualNodeInstance.entityVersion + 1
We don't want to set entityVersion here, let hibernate do this itself. Pretty sure this will always result in "OptimisticLockException - missing change" or something, it expects entityVersion of the merged entity to match that of the one in the database i.e. it effectively does a `WHERE entityVersion = x`

2022-07-13 14:00 UTC, conalsmith-r3 commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeEntityRepository.kt
> +                VirtualNodeEntity::class.java
What's the purpose of the order by entityVersion? That won't be relevant, its just for optimistic locking, there'll only be one entity with this holdingIdentity id afaik.

Also, is it possible to use equality rather than LIKE in the WHERE clause? Would need the full holdingIdentityId.

2022-07-13 14:18 UTC, conalsmith-r3 commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeEntityRepository.kt
> +                VirtualNodeEntity::class.java
vnode_instance has the holding_identity_id column on it, can't we use that instead? would be interesting to see the query that gets generated when you add an integration test.

2022-07-13 14:27 UTC, conalsmith-r3 commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeEntityRepository.kt
> +                VirtualNodeEntity::class.java
Won't the query return a list of all vnodes associated with a holding identity, i.e. it could return many vnodes? PK for virtual_node is a composite of holding_id, cpiName, cpiVer, cpiSSH, which means getting by holdingId can return many VirtualNodeEntities. I think we'll have to update them all, rather than just one. Is that right @vkolomeyko ?

2022-07-13 14:59 UTC, benmcmahon100 commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeEntityRepository.kt
> +                VirtualNodeEntity::class.java
Chatted to Dries about this, - a holding ID short has can have many holding ID could have many versions of itself - that said different holding ID <> CPI combos would have he issue of missing stuff, so I think that's a fair longer term problem. We don't have a succinct way of looking up a particular instance without supplying both which I think is a bit annoying.

2022-07-13 14:59 UTC, benmcmahon100 commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeEntityRepository.kt
> +                        entityVersion = latestVirtualNodeInstance.entityVersion + 1
Ah okay that was my misunderstanding then.

2022-07-13 16:05 UTC, conalsmith-r3 commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeEntityRepository.kt
> +                VirtualNodeEntity::class.java
Discussed with Ben and I don't know quite enough to answer it. I think right now (could be wrong here) we could have the following in `vnode_instance`:

| cpi name        | cpi version  | cpiSSH | holdingIdentityId | entityVersion | state          |
|----------------|--------------|---------|---------------------|---------------|-------------|
| calculator.cpi | 5.0-snapshot |  abc   |  ALICE_GROUP1     | 1                   | ACTIVE      |
| subtractor.cpi | 5.0-snapshot |  abc   |  ALICE_GROUP1     | 0                   | ACTIVE     |
| adder.cpi        | 5.0-snapshot |  abc   |  ALICE_GROUP1     | 2                   | ACTIVE     |

> 3 different CPIs and all same holdingIdentity (X500 name + mgm groupId)

Q is how to pick which row to update, updating the state given a "holdingIdentityId" isn't enough info to update the correct vnode.

Even we can have multiple versions of one CPI:

| cpi name        | cpi version  | cpiSSH | holdingIdentityId | entityVersion | state          |
|----------------|--------------|---------|---------------------|---------------|-------------|
| calculator.cpi | 5.0-snapshot |  abc   |  ALICE_GROUP1     | 1                   | INACTIVE  |
| calculator.cpi | 5.1-snapshot |  abc   |  ALICE_GROUP1     | 0                   | INACTIVE  |
| calculator.cpi | 5.2-snapshot |  abc   |  ALICE_GROUP1     | 2                   | ACTIVE     |

> 3 different versions of the same CPI, assuming older ones are inactive

Maybe more information is needed in the request? I.e. cpiId?

2022-07-15 16:15 UTC, vkolomeyko commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/virtualnode/VirtualNodeRpcTest.kt
> +            val randomPair = states.elementAt(random.nextInt(states.size))
Do we have to pick a state at random? I would rather prefer to have it updated to a particular value for test to be deterministic.

2022-07-15 18:10 UTC, conalsmith-r3 reviewed
Just a few comments before I'm off for Mon & Tues

2022-07-15 18:10 UTC, sprintengine commented on libs/virtual-node/virtual-node-info/src/main/kotlin/net/corda/virtualnode/VirtualNodeInfo.kt
> +        const val DEFAULT_INITIAL_STATE = "ACTIVE"
We should probably use an enum for the state instead of a String and just set default in the constructor parameter ie. `val state: VirtualNodeState = VirtualNodeState.ACTIVE`.

I think enum would have something like this?:

```
enum class VirtualNodeState{
    ACTIVE,
    INACTIVE,
    IN_MAINTENANCE,
    DRAINING
}
```

2022-07-15 18:10 UTC, sprintengine commented on libs/virtual-node/virtual-node-datamodel/src/main/kotlin/net/corda/libs/virtualnode/datamodel/VirtualNodeEntity.kt
> +    var virtualNodeState: String,
We should make this an enum too, we'll effectively have a two `VirtualNodeState` enums, one in this module (`virtual-node-datamodel`) and one in `virtual-node-info`. We can set `@Enumerated(value = EnumType.STRING)` so it persists the name rather than the ordinal. Will just need some conversion between the two VirtualNodeStates in `VirtualNodeInfoDbReconcilerReader`

2022-07-15 18:10 UTC, sprintengine commented on libs/virtual-node/virtual-node-datamodel/src/main/kotlin/net/corda/libs/virtualnode/datamodel/VirtualNodeEntity.kt
> +    }
This looks a little strange, you could probably change it around a bit, i.e. the merge:
```
it.merge(latestVirtualNodeInstance.update(newState))
```
and the update function:
```
fun update(newState: String) = this.copy(virtualNodeState = newState)
```
Think that should work since all the fields are in the constructor therefore will get copied.

I'm not sure if you actually even have to do the copy though, you might be able to literally just do `latestVirtualNodeInstance.virtualNodeState = newState` and then merge it.

Ideally in the future we should get rid of data classes for entities tbh.

2022-07-15 18:10 UTC, conalsmith-r3 commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeEntityRepository.kt
> +                    "WHERE vnode_instance.holdingIdentity.holdingIdentityId = :shortVNodeId " +
Yeah will be interesting to see what query hibernate generates for this, will it join to holding identity table or not.

2022-07-15 18:10 UTC, conalsmith-r3 commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeEntityRepository.kt
> +            val latestVirtualNodeInstance = it.createQuery(
We could create a named query for this on the VIrtualNodeEntity.

2022-07-18 08:04 UTC, vkolomeyko commented on libs/virtual-node/virtual-node-info/src/main/kotlin/net/corda/virtualnode/VirtualNodeInfo.kt
> +        const val DEFAULT_INITIAL_STATE = "ACTIVE"
I guess we can introduce an internal enum for convenience. But I would not promote this enum to `corda-api` just yet.

2022-07-18 08:06 UTC, vkolomeyko commented on libs/virtual-node/virtual-node-datamodel/src/main/kotlin/net/corda/libs/virtualnode/datamodel/VirtualNodeEntity.kt
> +    var virtualNodeState: String,
TBH I would keep it as `String` for now, we can perform translation from enum to String in our code rather than delegate it to JPA.

2022-07-18 08:09 UTC, vkolomeyko commented
@benmcmahon100 currently the build fails with compilation error:
```
:components:virtual-node:virtual-node-write-service-impl:compileIntegrationTestKotlin FAILED |  
e: /var/jenkins/workspace/Corda5_corda-runtime-os_PR-1636/components/virtual-node/virtual-node-write-service-impl/src/integrationTest/kotlin/net/corda/virtualnode/write/db/impl/tests/VirtualNodeEntityRepositoryTest.kt: (347, 115): No value passed for parameter 'virtualNodeState'
```

2022-07-18 08:34 UTC, vkolomeyko commented on libs/virtual-node/virtual-node-info/src/main/kotlin/net/corda/virtualnode/VirtualNodeInfo.kt
> +    val state: String,
```suggestion
    val state: String = DEFAULT_INITIAL_STATE,
```
I think if we do that, we can undo changes in many of the files where we had to assign this value specifically.

2022-07-20 09:13 UTC, driessamyn commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeEntityRepository.kt
> +            println(updatedVirtualNodeInstance)
No `println` please.

2022-07-20 09:13 UTC, driessamyn commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt
> +        println("GLLOE")
println

2022-07-20 09:13 UTC, driessamyn commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt
>          }
I think having the switch here means too much duplication (e.g. Vnode Info publish to Kafka) and a danger refactoring or changes will miss things out.
The difference between a create and update should be fairly minimal, so my feeling is that it would be better to make the switch around much smaller blocks of code.

2022-07-22 07:07 UTC, driessamyn commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt
> +                dbConnectionManager.getClusterEntityManagerFactory().createEntityManager(),
Where is the entity manager closed?

2022-07-22 13:16 UTC, benmcmahon100 commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt
> +                dbConnectionManager.getClusterEntityManagerFactory().createEntityManager(),
It's `.use'd in the remote function, but it just a straight wrapper around a transaction, so I think I'll move the use to out here

2022-07-22 13:24 UTC, benmcmahon100 commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt
>          }
I agree, I think this part of the code is in need of a general overhaul to remove duplication, catch back up with the lifecycle API, improved readability, and increased testability of the queries it relies on.

At this stage I think it'd make sense as a separate PR due to the length of this one

2022-07-22 16:26 UTC, vkolomeyko commented
@benmcmahon100 - I can see this PR was opened for review, but CI checks are red. Have you had a chance to verify them? it looks like it is failing with NPE in the test you have added:
```
set virtual node state() – net.corda.applications.workers.smoketest.virtualnode.VirtualNodeRpcTest
<1s
Error
java.lang.NullPointerException
Stacktrace
java.lang.NullPointerException
	at net.corda.applications.workers.smoketest.virtualnode.VirtualNodeRpcTest$set virtual node state$1.invoke(VirtualNodeRpcTest.kt:247)
	at net.corda.applications.workers.smoketest.virtualnode.VirtualNodeRpcTest$set virtual node state$1.invoke(VirtualNodeRpcTest.kt:244)
	at net.corda.applications.workers.smoketest.virtualnode.helpers.ClusterBuilderKt.cluster(ClusterBuilder.kt:127)
	at net.corda.applications.workers.smoketest.virtualnode.VirtualNodeRpcTest.set virtual node state(VirtualNodeRpcTest.kt:244)
```

2022-07-22 16:58 UTC, benmcmahon100 commented
> @benmcmahon100 - I can see this PR was opened for review, but CI checks are red. Have you had a chance to verify them? it looks like it is failing with NPE in the test you have added:
> 
> ```
> set virtual node state() – net.corda.applications.workers.smoketest.virtualnode.VirtualNodeRpcTest
> <1s
> Error
> java.lang.NullPointerException
> Stacktrace
> java.lang.NullPointerException
> 	at net.corda.applications.workers.smoketest.virtualnode.VirtualNodeRpcTest$set virtual node state$1.invoke(VirtualNodeRpcTest.kt:247)
> 	at net.corda.applications.workers.smoketest.virtualnode.VirtualNodeRpcTest$set virtual node state$1.invoke(VirtualNodeRpcTest.kt:244)
> 	at net.corda.applications.workers.smoketest.virtualnode.helpers.ClusterBuilderKt.cluster(ClusterBuilder.kt:127)
> 	at net.corda.applications.workers.smoketest.virtualnode.VirtualNodeRpcTest.set virtual node state(VirtualNodeRpcTest.kt:244)
> ```

Bit of a synchronization issue there on my part. I think I'm also getting some weirdness from the build cache

2022-07-25 08:20 UTC, vkolomeyko commented on processors/rpc-processor/src/integrationTest/resources/swaggerBaseline.json
> -  "openapi" : "3.0.1",
Looks like this large file got completely re-formatted?
@benmcmahon100 - would you know why is that?
Could you undo all the formatting and leave just the one that is related to the change you were making?

2022-07-25 09:02 UTC, vkolomeyko requested changes

2022-07-25 09:02 UTC, vkolomeyko commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/virtualnode/VirtualNodeRpcTest.kt
> +import java.util.Random
I think we can remove use of `Random` from this file.

2022-07-25 09:02 UTC, vkolomeyko commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/virtualnode/VirtualNodeRpcTest.kt
> +                timeout(Duration.ofSeconds(60))
Is this timeout so large because we need reconciliation to take place?
If so, perhaps there is a Jira for this issue which we can mention in the comments such that when it is addressed we could perform this transition faster?

2022-07-25 09:02 UTC, vkolomeyko commented on components/virtual-node/virtual-node-rpcops-maintenance-impl/src/main/kotlin/net/corda/libs/virtualnode/maintenance/rpcops/impl/v1/Constants.kt
> +internal const val GROUP_NAME = "virtual.node.management"
Could those constant be moved to `VirtualNodeMaintenanceRPCOpsImpl` - this seems to be the only place where they are used?

2022-07-25 09:02 UTC, vkolomeyko commented on components/virtual-node/virtual-node-rpcops-maintenance-impl/src/main/kotlin/net/corda/libs/virtualnode/maintenance/rpcops/impl/v1/UnknownResponseTypeException.kt
> +class UnknownResponseTypeException(type: String) : Exception("Encountered a response of unknown type: $type")
Do we need this specialized type of exception? From what I can see it is not being caught anywhere specifically. Perhaps, we can use `IllegalStateException` instead?

2022-07-25 09:02 UTC, vkolomeyko commented on components/virtual-node/virtual-node-rpcops-maintenance-impl/src/main/kotlin/net/corda/libs/virtualnode/maintenance/rpcops/impl/v1/VirtualNodeMaintenanceRPCOpsHandler.kt
> +    private fun onFirstConfigEvent(coordinator: LifecycleCoordinator, event: BootstrapConfigEvent) {
Looks like there is a lot of duplication in methods `onConfigChangedEvent` and `onFirstConfigEvent` - can we merge them into a single method?

2022-07-25 09:02 UTC, vkolomeyko commented on components/virtual-node/virtual-node-rpcops-maintenance-impl/src/main/kotlin/net/corda/libs/virtualnode/maintenance/rpcops/impl/v1/VirtualNodeMaintenanceRPCOpsImpl.kt
> +class VirtualNodeMaintenanceRPCOpsImpl @VisibleForTesting constructor(
Looks like this constructor is never used on its own. Could we please get rid of it and just have a single `@Activate` constructor?

2022-07-25 09:02 UTC, vkolomeyko commented on components/virtual-node/virtual-node-rpcops-maintenance-impl/src/main/kotlin/net/corda/libs/virtualnode/maintenance/rpcops/impl/v1/VirtualNodeMaintenanceRPCOpsImpl.kt
>          val logger = contextLogger()
I think this can be made `private`.

2022-07-25 09:02 UTC, vkolomeyko commented on components/virtual-node/virtual-node-rpcops-maintenance-impl/src/main/kotlin/net/corda/libs/virtualnode/maintenance/rpcops/impl/v1/VirtualNodeMaintenanceRPCOpsImpl.kt
> +        logger.debug("Received request to update state for $virtualNodeShortId to $newState by $actor at $instant")
Can we please lambda version, as in `logger.debug {...}` ?

2022-07-25 09:02 UTC, vkolomeyko commented on components/virtual-node/virtual-node-rpcops-maintenance-impl/src/main/kotlin/net/corda/libs/virtualnode/maintenance/rpcops/impl/v1/VirtualNodeMaintenanceRPCOpsImpl.kt
> +        logger.debug("Received response to update for $virtualNodeShortId to $newState by $actor")
Can we please lambda version, as in logger.debug {...} ?

2022-07-25 09:02 UTC, vkolomeyko commented on components/virtual-node/virtual-node-rpcops-maintenance-impl/src/main/kotlin/net/corda/libs/virtualnode/maintenance/rpcops/impl/v1/VirtualNodeMaintenanceRPCOpsImpl.kt
> +                @Suppress("MaxLineLength")
I think it would not harm to break the line and remove `@Suppress`...

2022-07-25 09:02 UTC, vkolomeyko commented on components/virtual-node/virtual-node-rpcops-service-impl/src/main/kotlin/net/corda/virtualnode/rpcops/impl/VirtualNodeRPCOpsEventHandler.kt
> +            is StopEvent -> stop()
Can we please undo the change to this file?

2022-07-25 09:02 UTC, vkolomeyko commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeEntityRepository.kt
> +            if (it == "") null else SecureHash.create(it)
Should we use `isBlank` here?

2022-07-25 09:02 UTC, vkolomeyko commented on libs/virtual-node/virtual-node-endpoints/src/main/kotlin/net/corda/libs/virtualnode/endpoints/v1/types/HTTPVirtualNodeStateChangeResponse.kt
> +data class HTTPVirtualNodeStateChangeResponse(
This class does not seem to be used - can we please delete it?

2022-07-25 09:02 UTC, vkolomeyko commented on libs/virtual-node/virtual-node-endpoints/src/main/kotlin/net/corda/libs/virtualnode/endpoints/v1/VirtualNodeRPCOps.kt
> +}
Can we please undo changes to this file?

2022-07-25 09:07 UTC, vkolomeyko requested changes

2022-07-25 09:07 UTC, vkolomeyko commented on components/virtual-node/virtual-node-rpcops-maintenance-impl/src/main/kotlin/net/corda/libs/virtualnode/maintenance/rpcops/impl/v1/VirtualNodeMaintenanceRPCOpsImpl.kt
> +    fun setTimeout(millis: Int) {
```suggestion
    internal fun setTimeout(millis: Int) {
```

2022-07-25 09:07 UTC, vkolomeyko commented on components/virtual-node/virtual-node-rpcops-maintenance-impl/src/main/kotlin/net/corda/libs/virtualnode/maintenance/rpcops/impl/v1/VirtualNodeMaintenanceRPCOpsImpl.kt
> +    fun configureRPCSender(messagingConfig: SmartConfig) {
```suggestion
    internal fun configureRPCSender(messagingConfig: SmartConfig) {
```

2022-07-25 12:19 UTC, benmcmahon100 commented on components/virtual-node/virtual-node-rpcops-maintenance-impl/src/main/kotlin/net/corda/libs/virtualnode/maintenance/rpcops/impl/v1/UnknownResponseTypeException.kt
> +class UnknownResponseTypeException(type: String) : Exception("Encountered a response of unknown type: $type")
This is a copy of virtual node rpc ops and IMO the more specific exception greatly speeds up finding the source of them

2022-07-25 12:27 UTC, vkolomeyko commented on components/virtual-node/virtual-node-rpcops-maintenance-impl/src/main/kotlin/net/corda/libs/virtualnode/maintenance/rpcops/impl/v1/UnknownResponseTypeException.kt
> +class UnknownResponseTypeException(type: String) : Exception("Encountered a response of unknown type: $type")
But after this change we will have **two** `UnknownResponseTypeException` only different by package name. This is likely to cause confusion.

Let's remove this exception type and replace it with `IllegalStateException`.

> greatly speeds up finding the source of them

Hopefully, the message on the exception and the stack trace would provide enough information to locate the site from which exception is thrown.

2022-07-25 12:34 UTC, benmcmahon100 commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeEntityRepository.kt
> +            if (it == "") null else SecureHash.create(it)
Was trying to keep it the same as the other method but can change

2022-07-25 12:35 UTC, benmcmahon100 commented on components/virtual-node/virtual-node-rpcops-maintenance-impl/src/main/kotlin/net/corda/libs/virtualnode/maintenance/rpcops/impl/v1/VirtualNodeMaintenanceRPCOpsImpl.kt
> +    fun setTimeout(millis: Int) {
The functions are internal in the place they're copied from

2022-07-25 12:35 UTC, benmcmahon100 commented on components/virtual-node/virtual-node-rpcops-maintenance-impl/src/main/kotlin/net/corda/libs/virtualnode/maintenance/rpcops/impl/v1/VirtualNodeMaintenanceRPCOpsImpl.kt
> +    fun configureRPCSender(messagingConfig: SmartConfig) {
The functions are internal in the place they're copied from

2022-07-25 14:13 UTC, benmcmahon100 commented on components/virtual-node/virtual-node-rpcops-maintenance-impl/src/main/kotlin/net/corda/libs/virtualnode/maintenance/rpcops/impl/v1/VirtualNodeMaintenanceRPCOpsImpl.kt
> +class VirtualNodeMaintenanceRPCOpsImpl @VisibleForTesting constructor(
No, this is there for the same reason as its inclusion in the virtual node RPC ops. We're not meant to mix injectables and non-injectables. It also allows us to replace the clock with a mock clock in testing.

It could theoretically be removed with the code as is, but we'd likely end up adding it back for the sake of test, or entirely as the result of a refactor

2022-07-25 14:20 UTC, vkolomeyko commented on components/virtual-node/virtual-node-rpcops-maintenance-impl/src/main/kotlin/net/corda/libs/virtualnode/maintenance/rpcops/impl/v1/VirtualNodeMaintenanceRPCOpsImpl.kt
> +class VirtualNodeMaintenanceRPCOpsImpl @VisibleForTesting constructor(
As discussed, please remove this unused constructor.

2022-07-25 14:31 UTC, benmcmahon100 commented on components/virtual-node/virtual-node-rpcops-maintenance-impl/src/main/kotlin/net/corda/libs/virtualnode/maintenance/rpcops/impl/v1/UnknownResponseTypeException.kt
> +class UnknownResponseTypeException(type: String) : Exception("Encountered a response of unknown type: $type")
There are a lot of cases where there is duplication, though - that'd be fixed by some common module. I'd rather not drop to a more generic exception.

2022-07-25 14:35 UTC, vkolomeyko commented on components/virtual-node/virtual-node-rpcops-maintenance-impl/src/main/kotlin/net/corda/libs/virtualnode/maintenance/rpcops/impl/v1/UnknownResponseTypeException.kt
> +class UnknownResponseTypeException(type: String) : Exception("Encountered a response of unknown type: $type")
Can we at least have it renamed to `UnknownMaintenanceResponseTypeException` to avoid name clash from different package?

2022-07-25 15:22 UTC, vkolomeyko submitted a review, later dismissed
LGTM

2022-07-25 15:41 UTC, conalsmith-r3 approved these changes, later dismissed
LGTM, in the follow up I'd definitely like to see some integration test in `VirtualNodeEntityRepositoryTest`.

If you also wanted a bit of fun you could also think of refactoring `VirtualNodeWriterProcessor` as it's getting pretty big. In `PermissionStorageWriterProcessorImpl` I dependency injected writers for different entities which makes the code easy to unit test and makes it a bit more modular. I'm not entirely sure how to split `VirtualNodeWriterProcessor` though, maybe inject a `VirtualNodeValidator` and `VirtualNodeWriter` and try reduce the concerns of the "processor".

2022-07-25 15:45 UTC, benmcmahon100 commented
> LGTM, in the follow up I'd definitely like to see some integration test in `VirtualNodeEntityRepositoryTest`.
> 
> If you also wanted a bit of fun you could also think of refactoring `VirtualNodeWriterProcessor` as it's getting pretty big. In `PermissionStorageWriterProcessorImpl` I dependency injected writers for different entities which makes the code easy to unit test and makes it a bit more modular. I'm not entirely sure how to split `VirtualNodeWriterProcessor` though, maybe inject a `VirtualNodeValidator` and `VirtualNodeWriter` and try reduce the concerns of the "processor".

Definitely, makes sense to me

2022-07-25 15:51 UTC, vkolomeyko approved these changes
LGTM

2022-07-25 16:06 UTC, driessamyn commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeEntityRepository.kt
> +    }
I think maybe this query should be pulled out into a function in the entity module.

`internal` is a bit a smell. Pulling it out would allow you to integation test the query in the entities module, and mock the result in tests for this.

2022-07-25 16:10 UTC, driessamyn requested changes, later dismissed

2022-07-25 16:10 UTC, driessamyn commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt
> +            is VirtualNodeStateChangeRequest -> changeVirtualNodeState(request.timestamp, typedRequest, respFuture)
I'm really uncomfortable about the amount of overlap between these 2. It will be very easy to miss something during a refactor. 
For example, they should be identical in terms of publishing to Kafka.

2022-07-25 16:14 UTC, conalsmith-r3 commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeEntityRepository.kt
> +    }
If we're going with the "repository" kind of pattern like Spring, i.e. a repository per entity kind of thing, I think we should probably have a `CpiMetadataRepository`, `HoldingIdentityRepository` and `VirtualNodeEntityRepository`. Wdyt? I'm not really a fan of EntityManager extension functions in the entity definition class

2022-07-25 16:18 UTC, conalsmith-r3 commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt
> +            is VirtualNodeStateChangeRequest -> changeVirtualNodeState(request.timestamp, typedRequest, respFuture)
I think Ben was considering refactoring the publishing out to a separate class that gets injected and both code branches can call.

2022-07-25 16:21 UTC, driessamyn commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt
> +            is VirtualNodeStateChangeRequest -> changeVirtualNodeState(request.timestamp, typedRequest, respFuture)
I'm ok with that, but please reference a JIRA.

2022-07-25 16:23 UTC, benmcmahon100 commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt
> +            is VirtualNodeStateChangeRequest -> changeVirtualNodeState(request.timestamp, typedRequest, respFuture)
https://r3-cev.atlassian.net/browse/CORE-5906

2022-07-25 16:45 UTC, merged