CORE-5458 Catch Throwable instead of Exception
corda/corda-runtime-os pull request #1647
Opened 2022-07-14 08:30 UTC by simon-johnson-r3

- Catch Throwable instead of Exception when Flows are invoked.
- Tests for Flow invocation for innocuous and throwing Flow.

2022-07-14 08:32 UTC, simon-johnson-r3 commented on components/flow/flow-service/build.gradle
> +    instrumentTests = true
This likely adds a small overhead to the execution of the integration tests, as they are executed as a task of type Test and therefore will end up being instrumented by the Quasar agent. I don't see this as a problem.

2022-07-14 08:33 UTC, simon-johnson-r3 commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/fiber/FlowFiberImpl.kt
> +        } catch (t: Throwable) {
This is the actual fix.

2022-07-14 08:33 UTC, simon-johnson-r3 commented on components/flow/flow-service/src/test/kotlin/net/corda/flow/fiber/FlowFiberImplTest.kt
> +    fun `check throwing flow is handled safely`() {
This test fails without the fix.

2022-07-14 08:35 UTC, simon-johnson-r3 commented on components/flow/flow-service/src/test/kotlin/net/corda/flow/fiber/FlowFiberImplTest.kt
> +        val mockFlowLogic = mock<FlowLogicAndArgs>()
This was a 'happy flow' test which I created whilst trying to get Quasar instrumented tests running. Thought I might as well leave it in. There is scope to test more in FlowFiberImpl in this manner, but I didn't want to have this ticket continue on forever.

2022-07-14 08:46 UTC, simon-johnson-r3 commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/fiber/FlowFiberImpl.kt
> -    private fun Throwable.isUnrecoverable(): Boolean = this is VirtualMachineError && this !is StackOverflowError
Unused, so removed it

2022-07-14 08:59 UTC, lankydan reviewed
Change seems fine.

General question, why do we need to run a real fiber to test this, rather than having a unit test for `FlowFiberImpl`?

Then looking forward, what other scenarios would we want to write tests like this?

2022-07-14 09:40 UTC, JamesHR3 commented
> Change seems fine.
> 
> General question, why do we need to run a real fiber to test this, rather than having a unit test for `FlowFiberImpl`?
> 
> Then looking forward, what other scenarios would we want to write tests like this?

Annoyingly `Fiber` is a class, so I don't think you can trivially stub out the `parkAndSerialize` bit. We also call `unparkDeserialized` inside the fiber, but I think we probably shouldn't be doing that in the first place.

2022-07-14 09:50 UTC, JamesHR3 approved these changes
Seems reasonable. Might be worth @chrisr3 having a quick look to make sure we're not doing anything crazy with the quasar gradle plugin here, but it looks sensible to me.

2022-07-14 10:03 UTC, simon-johnson-r3 commented
> Change seems fine.
> 
> General question, why do we need to run a real fiber to test this, rather than having a unit test for `FlowFiberImpl`?
> 
> Then looking forward, what other scenarios would we want to write tests like this?

This is a unit test already in the context of how I would use that term. Fibers are just an implementation of coroutines when it comes down to it. If the code was using Kotlin coroutines I doubt it would raise eyebrows that the test was coroutine aware, you probably wouldn't even consciously acknowledge it was doing that.

An alternative way of looking at it is that this class is inherently based around being a Fiber and that it makes no sense to try and test it by making it not behave like a Fiber, because that doesn't really test it at all. In fact the class doesn't work if you try and do that, its behaviour is encapsulated by the `run` method, which is executed by the Quasar framework, not from the api. You possibly could fudge it all and get it working eventually, but would that offer any benefits? All I had to do here is "turn Quasar on" and now it's working exactly like in the real world and I can test with a few lines of code.

On the last question, I think everything that is Fiber related, where the behaviour is "coroutine-like" sensitive can be tested like this and probably should.

2022-07-14 10:04 UTC, lankydan approved these changes

2022-07-14 10:22 UTC, chrisr3 requested changes
What on Earth is going on here? This looks like an absolutely _terrible_ idea on every level - not least you applying the `quasar-utils` plugin and catching `Throwable`.

2022-07-14 10:35 UTC, JamesHR3 commented
> What on Earth is going on here? This looks like an absolutely _terrible_ idea on every level - not least you applying the `quasar-utils` plugin and catching `Throwable`.

We've always had to catch `Throwable` somewhere, that's saying we don't want any error to fully escape (turns out otherwise the fiber can hang forever and bring the flow worker down).

The intent here is to unit test our fiber code, which is going to require Quasar at some level (unless we do some pretty significant refactoring). It's fine to say there's a problem with doing that, but I'd like to understand what the problems are going to be.

2022-07-14 11:00 UTC, simon-johnson-r3 commented
> > What on Earth is going on here? This looks like an absolutely _terrible_ idea on every level - not least you applying the `quasar-utils` plugin and catching `Throwable`.
> 
> We've always had to catch `Throwable` somewhere, that's saying we don't want any error to fully escape (turns out otherwise the fiber can hang forever and bring the flow worker down).
> 
> The intent here is to unit test our fiber code, which is going to require Quasar at some level (unless we do some pretty significant refactoring). It's fine to say there's a problem with doing that, but I'd like to understand what the problems are going to be.

It's untenable to suggest a product can be based so deeply on a framework, but the unit tests (or any other level of testing) for that product cannot invoke the same framework. The code has compile time dependencies already on Quasar and relies on it heavily for almost its entire feature set. If Quasar did compile time instrumentation, it wouldn't even be possible to separate the two things, we can only do so now on a technicality.

I suggest this discussion centres on the use of Quasar in Corda, because to me the use of Quasar in the unit tests is incidental. If there is some significant blocker to using something so deeply rooted in Corda in its own tests, specifically where aspects of that framework are pivotal to the behaviour of the class under test, then something has gone very wrong already.

2022-07-14 11:01 UTC, chrisr3 requested changes
The `catch (Throwable: t)` needs changing to exclude `Error`, but my plan is to convert the Quasar Java agent into an OSGi `WeavingHook`, at which point `quasar-utils` will become obsolete - and will be removed.

2022-07-14 11:01 UTC, chrisr3 commented on components/flow/flow-service/build.gradle
> +    ]
These package exclusions are for an application running inside an OSGi framework. They are not sufficient to run a JUnit test from Gradle.

2022-07-14 11:01 UTC, chrisr3 commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/fiber/FlowFiberImpl.kt
> +        } catch (t: Throwable) {
Except this now catches `Error`, such as `StackOverflowError`, `LinkageError`, `VirtualMachineError`, `OutOfMemoryError` etc, which we _cannot_ catch. You're going to need to do something like:
```kotlin
} catch (e: Error) {
    throw e
} catch (t: Throwable) {
    log.error("Flow failed", t)
    // etc
}
```

2022-07-14 11:01 UTC, chrisr3 commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/fiber/FlowFiberImpl.kt
> -    private fun Throwable.isUnrecoverable(): Boolean = this is VirtualMachineError && this !is StackOverflowError
Odd that it was unused... :thinking:

2022-07-14 11:01 UTC, chrisr3 commented on components/flow/flow-service/build.gradle
> +    id 'net.corda.plugins.quasar-utils'
This will instrument _every_ instance of the `Test` task within this module, and hence _every class not explicitly excluded while executing every JUnit test_. The impact of doing this could be "large"...

2022-07-14 11:04 UTC, simon-johnson-r3 commented on components/flow/flow-service/build.gradle
> +    id 'net.corda.plugins.quasar-utils'
Yes, that's noted here: https://github.com/corda/corda-runtime-os/pull/1647#discussion_r920898995

Splitting these unit tests into another project would mitigate this if it's seen as a blocker.

2022-07-14 11:11 UTC, simon-johnson-r3 commented
> The `catch (Throwable: t)` needs changing to exclude `Error`, but my plan is to convert the Quasar Java agent into an OSGi `WeavingHook`, at which point `quasar-utils` will become obsolete - and will be removed.

I take this point. It's not quite so simple though, NotImplementedError is an Error as well, so excluding it would not fix the underlying bug. A more fine grained approach to which `Error`s should not be propagated might be required. However as @JamesHR3 alludes to in another comment, we cannot stop user code throwing Errors or any other Throwable, and we cannot simply let the FlowWorker crash in those cases.

2022-07-14 11:12 UTC, chrisr3 commented on components/flow/flow-service/build.gradle
> +    instrumentTests = true
> This likely adds a small overhead to the execution of the integration tests, as they are executed as a task of type Test and therefore will end up being instrumented by the Quasar agent. I don't see this as a problem.

The integration test task actually has type `TestOSGi`, with the corresponding `Test` task disabled:
```
tasks.named('integrationTest') {
    finalizedBy importTask
    dependsOn testOSGi
    enabled = false
}
```
The extra overhead will be instrumenting all of the other unit test classes, along with all of their dependencies.

2022-07-14 11:17 UTC, lankydan commented
> > The `catch (Throwable: t)` needs changing to exclude `Error`, but my plan is to convert the Quasar Java agent into an OSGi `WeavingHook`, at which point `quasar-utils` will become obsolete - and will be removed.
> 
> I take this point. It's not quite so simple though, NotImplementedError is an Error as well, so excluding it would not fix the underlying bug. A more fine grained approach to which `Error`s should not be propagated might be required. However as @JamesHR3 alludes to in another comment, we cannot stop user code throwing Errors or any other Throwable, and we cannot simply let the FlowWorker crash in those cases.

That being said, things like out of memory errors can be thrown which make the worker unresponsive, but won't always terminate the application itself (I might be wrong with how OOMs exit java processes).

2022-07-14 11:22 UTC, simon-johnson-r3 commented
> > > The `catch (Throwable: t)` needs changing to exclude `Error`, but my plan is to convert the Quasar Java agent into an OSGi `WeavingHook`, at which point `quasar-utils` will become obsolete - and will be removed.
> > 
> > 
> > I take this point. It's not quite so simple though, NotImplementedError is an Error as well, so excluding it would not fix the underlying bug. A more fine grained approach to which `Error`s should not be propagated might be required. However as @JamesHR3 alludes to in another comment, we cannot stop user code throwing Errors or any other Throwable, and we cannot simply let the FlowWorker crash in those cases.
> 
> That being said, things like out of memory errors can be thrown which make the worker unresponsive, but won't always terminate the application itself (I might be wrong with how OOMs exit java processes).

Indeed. There's no type in between OutOfMemoryError and Error, nor NotImplementedError and Error, so apart from their exact types there's nothing to distinguish them. We could have a whitelist of Errors to catch instead? I would then suggest that anything not on the whitelist would be a candidate for immediate termination of the process, if that's the requirement of those other kinds of errors.

2022-07-14 11:29 UTC, chrisr3 commented
> That being said, things like out of memory errors can be thrown which make the worker unresponsive, but won't always terminate the application itself (I might be wrong with how OOMs exit java processes).

I am thinking "core dump" when things go _really_ wrong. There's really nothing you can do when the JVM throws `StackOverflowError` or `OutOfMemoryError`. And if some CorDapps decide that throwing those is a Good Idea then that sounds like the Corda equivalent of shouting "FIRE!" in a crowded theatre.

2022-07-14 11:32 UTC, simon-johnson-r3 commented on components/flow/flow-service/build.gradle
> +    instrumentTests = true
Right, but let's keep in mind those are Flow Worker unit tests. The Flow Worker code is written with an expectation is it instrumented already.

I assume you are not suggesting this leaks to other sub-projects in Corda too, perhaps I'm wrong in assuming that?

2022-07-14 11:35 UTC, lankydan commented
> Indeed. There's no type in between OutOfMemoryError and Error, nor NotImplementedError and Error, so apart from their exact types there's nothing to distinguish them. We could have a whitelist of Errors to catch instead? I would then suggest that anything not on the whitelist would be a candidate for immediate termination of the process, if that's the requirement of those other kinds of errors.

Sounds reasonable to me.

@chrisr3 security manager question. Is it it possible/feasible to prevent users from manually creating `StacckOverflowError`s or other errors we care about?

Currently an argument for preventing any `Error`s from escaping is due to multi-tenancy, where a single CPK can screw up a worker. Whereas if we prevent anyone creating these sort of errors themselves, then we can exit like we want, but not allow bad CPKs to blow up the worker (guess they could always just stackoverflow since we can't do much there, but perhaps stackoverflows don't have to be an error that exits the worker).

2022-07-14 11:36 UTC, simon-johnson-r3 commented
> > That being said, things like out of memory errors can be thrown which make the worker unresponsive, but won't always terminate the application itself (I might be wrong with how OOMs exit java processes).
> 
> I am thinking "core dump" when things go _really_ wrong. There's really nothing you can do when the JVM throws `StackOverflowError` or `OutOfMemoryError`. And if some CorDapps decide that throwing those is a Good Idea then that sounds like the Corda equivalent of shouting "FIRE!" in a crowded theatre.

Agreed. The issue is that Kotlin decided calling a function marked as TODO is just the same. Perhaps we just catch that specific Error. The problem the reporter had is that we use TODO internally, they weren't even a part of this process.

2022-07-14 11:50 UTC, chrisr3 commented
> @chrisr3 security manager question. Is it it possible/feasible to prevent users from manually creating `StackOverflowError`s or other errors we care about?

`StackOverflowError`, `OutOfMemoryError`, `VirtualMachineError`, `InternalError` all belong to the `java.lang` package, and I don't think we can realistically prevent people from importing that. I don't believe you require any specific Java permission to create instances of them either.

2022-07-14 14:39 UTC, chrisr3 commented
> Whereas if we prevent anyone creating these sort of errors themselves, then we can exit like we want, but not allow bad CPKs to blow up the worker.

I don't know of _any_ means of differentiating an `Error` thrown by user code from one thrown by the JVM other than _massively rewritng the byte-code. (I suspect the DJVM was _close_ to supporting this, although we obviously don't want to get within "James Webb viewing distance" of anything like that!)

2022-07-14 15:21 UTC, chrisr3 commented on components/flow/flow-service/build.gradle
> +    instrumentTests = true
No, it should not "leak". However, if this test actually _needs_ Quasar instrumentation then it's more of an integration test than a unit test. I'm also observing that:
a) The new test uses a lot of mocking, and
b) None of the existing unit tests requires Quasar instrumentation.

2022-07-14 15:38 UTC, JamesHR3 commented on components/flow/flow-service/build.gradle
> +    instrumentTests = true
Well, we're trying to verify a fiber, so by definition it needs quasar to some extent! The argument here is that unit testing a quasar coroutine inherently needs quasar instrumentation, else you aren't really testing anything meaningful.

Your point b. is getting to the heart of the problem we're trying to solve. The flow engine in C5 has a lot of code running outside of a quasar fiber in contrast to C4, but inevitably we have to use quasar at some point. The current unit tests don't use quasar because we're not unit testing any of the code that needs it, and this represents a fairly large testing gap we need to close.

2022-07-14 16:14 UTC, chrisr3 commented on components/flow/flow-service/build.gradle
> +    instrumentTests = true
I am going to rewrite the Quasar Java agent as an OSGi `WeavingHook` (with any luck), at which point the OSGi version of the Quasar Java agent _will cease to exist._ The `corda.quasar-app` convention plugin will then be rewritten _not_ to use `quasar-utils`, and then `quasar-utils` itself will vanish into a vat of boiling acid.

When this happy day arrives, you will become able to write Quasar-aware integration tests by including the new Quasar _OSGi Framework Extension_ into your `TestOSGi` task's OSGi framework. And I would _greatly_ prefer to concentrate on achieving this goal rather than explaining to everyone how to configure `quasar-utils` correctly.

2022-07-14 16:34 UTC, simon-johnson-r3 commented on components/flow/flow-service/build.gradle
> +    instrumentTests = true
Quasar is not separable from this code. It wont compile without Quasar and it wont execute as the author intended without Quasar either so I don't agree it's not a unit test, there is no smaller unit you can go to. But is this a useful line of discussion anyway? If I renamed them, I don't see it would change much.

2022-07-15 07:33 UTC, simon-johnson-r3 commented
> > > The `catch (Throwable: t)` needs changing to exclude `Error`, but my plan is to convert the Quasar Java agent into an OSGi `WeavingHook`, at which point `quasar-utils` will become obsolete - and will be removed.
> > 
> > 
> > I take this point. It's not quite so simple though, NotImplementedError is an Error as well, so excluding it would not fix the underlying bug. A more fine grained approach to which `Error`s should not be propagated might be required. However as @JamesHR3 alludes to in another comment, we cannot stop user code throwing Errors or any other Throwable, and we cannot simply let the FlowWorker crash in those cases.
> 
> That being said, things like out of memory errors can be thrown which make the worker unresponsive, but won't always terminate the application itself (I might be wrong with how OOMs exit java processes).

Having given this some more thought it occurs to me some "internal" errors like OOM can be generated indirectly by user code prodding some other api. That OOM error might not be generated on a different day by the same code if the same memory pressures are not present. So allowing these errors to kill all Flows is likely still unacceptable?

2022-07-15 07:50 UTC, chrisr3 commented
> Having given this some more thought it occurs to me some "internal" errors like OOM can be generated indirectly by user code prodding some other api. That OOM error might not be generated on a different day by the same code if the same memory pressures are not present. So allowing these errors to kill all Flows is likely still unacceptable?

If the JVM throws `OutOfMemoryException` then as far as I'm concerned it is already dead, along with all of its flows.

2022-07-15 07:56 UTC, simon-johnson-r3 commented
> > Having given this some more thought it occurs to me some "internal" errors like OOM can be generated indirectly by user code prodding some other api. That OOM error might not be generated on a different day by the same code if the same memory pressures are not present. So allowing these errors to kill all Flows is likely still unacceptable?
> 
> If the JVM throws `OutOfMemoryException` then as far as I'm concerned it is _already_ as good as dead, along with all of its flows.

Is that entirely true? What if I tried to allocate 20 Gb of memory? It's my CorDapp which is at fault there, the JVM is running happily and will continue to do so after throwing.

As it happens I think this might be a moot point anyway, as I see Quasar's ScheduledSingleThreadExecutor uses a FutureTask which catches all Throwables itself, so they are always suppressed further up the chain no matter what we rethrow. I'm still looking into that, but in that case if we want to terminate the process, we'd need to do that explicitly in our own code.

2022-07-22 09:10 UTC, closed without merging