CORE-5273: Use `ComponentContext` for `PluggableRPCOps` discovery
corda/corda-runtime-os pull request #1651
Opened 2022-07-14 14:45 UTC by vkolomeyko

2022-07-14 15:48 UTC, chrisr3 requested changes
This looks mostly OK, although I am not a fan of using Kotlin reflection.

2022-07-14 15:48 UTC, chrisr3 commented on components/http-rpc-gateway-comp/src/main/kotlin/net/corda/components/rpc/internal/HttpRpcGatewayEventHandler.kt
> +    private val dynamicRpcOpsProperty: KProperty0<List<PluggableRPCOps<out RpcOps>>>,
_YIKES!_ Anything that says `KProperty` sounds like a Bad Idea :rotating_light:. How about:
```kotlin
private val dynamicRpcOpsProperty: Supplier<List<PluggableRPCOps<out RpcOps>>>,`
```

2022-07-14 15:48 UTC, chrisr3 commented on components/http-rpc-gateway-comp/src/main/kotlin/net/corda/components/rpc/internal/HttpRpcGatewayEventHandler.kt
> +            rpcOpsImpls = rpcOps.toList(),
No need for `toList()` if the `Supplier` already returns a list.

2022-07-14 15:48 UTC, chrisr3 commented on components/http-rpc-gateway-comp/src/main/kotlin/net/corda/components/rpc/HttpRpcGateway.kt
> +        ::dynamicRpcOps
Just `dynamicRpcOps`.

2022-07-14 16:01 UTC, vkolomeyko commented on components/http-rpc-gateway-comp/src/main/kotlin/net/corda/components/rpc/HttpRpcGateway.kt
> +        ::dynamicRpcOps
Looks like have to be `::dynamicRpcOps` or else compiler complains about type mismatch.

2022-07-15 08:37 UTC, chrisr3 commented on components/http-rpc-gateway-comp/src/main/kotlin/net/corda/components/rpc/internal/HttpRpcGatewayEventHandler.kt
> +    private val dynamicRpcOpsProperty: Supplier<List<PluggableRPCOps<out RpcOps>>>,
Maybe `dynamicRpcOpsProvider` rather than `dynamicRpcOpsProperty`?

2022-07-15 08:41 UTC, chrisr3 approved these changes
LGTM.

2022-07-15 09:06 UTC, merged