CORE-5601 Unified external events
corda/corda-runtime-os pull request #1669
Opened 2022-07-18 18:59 UTC by lankydan

The sending on events to external workers is unified to simplify the handling of sending requests and receiving responses. This reduces the amount of code we have to write to add new functionality that requires communication with other workers.

As we are making a generic solution there will be limitations that each specific use-case requires, however a number of scenarios have already been identified and the solution _should_ cater for them all.

The generic code handles the sending of events to other workers, receiving `ExternalEventResponse`s from them and determining whether to resume a flow or not based on the responses.

## How to use

After these changes, to send an event/request to a worker and receive a response in a service running in a flow, the following must be done:

### Inside the flow worker

- Inject `ExternalEventExecutor` into the service that needs to send an event.
- Create an OSGi component that implements the `ExternalEventFactory` interface and make it discoverable via that interface.
- In the `ExternalEventFactory.createExternalEvent` implementation, use the `ExternalEventContext` passed in to set the `flowExternalEventContext` property of the created payload/event.
- Call `ExternalEventExecutor.execute` and pass it the created `ExternalEventFactory`.
- Once the response is received, the flow will resume with the `RESUME` type defined in `ExternalEventFactory`.

### Inside the external worker

- Define a `DurableProcessor` or `StateAndEventProcessor` that receives the Avro object that the processor wants to receive. The external event framework does not restrict this.
- Process the event, which ends in either a successful response or an error response.
- Use `ExternalEventResponseFactory` to create a successful response or error response as required.

2022-07-18 19:00 UTC, lankydan commented
API PR - https://github.com/corda/corda-api/pull/480

2022-07-19 14:28 UTC, lankydan commented
Pretty sure @driessamyn and @dickon are aware of this, but linking anyway.

2022-08-05 16:51 UTC, lankydan commented
__When merged used my commit description__

2022-08-08 09:55 UTC, simon-johnson-r3 requested changes, later dismissed

2022-08-08 09:55 UTC, simon-johnson-r3 commented on libs/flows/flows/src/main/kotlin/net/corda/flow/external/events/executor/ExternalEventExecutor.kt
> +     * @param RESUME The type that the flow will resume with after calling [execute].
there are missing @return

2022-08-08 09:55 UTC, simon-johnson-r3 commented on libs/flows/flows/src/main/kotlin/net/corda/flow/external/events/handler/ExternalEventHandler.kt
> +     * [suspending] is called by [ExternalEventExecutor] when the after the calling flow suspends.
typo - remove `when the` ?

2022-08-08 09:55 UTC, simon-johnson-r3 commented on libs/flows/flows/src/main/kotlin/net/corda/flow/external/events/handler/ExternalEventHandler.kt
> +/**
I think the naming in the class is a little confusing. An event handler would normally have methods like `onSuspending` / `onResuming` but actually these methods are building something rather than event handling methods. I'm not sure this is really a handler so to speak, it's more of a factory, and it's methods factory methods.

2022-08-08 09:55 UTC, simon-johnson-r3 commented on libs/flows/flows/src/main/kotlin/net/corda/flow/external/events/handler/ExternalEventHandler.kt
> +     * [suspending] is called by [ExternalEventExecutor] when the after the calling flow suspends.
Given the comment at the top of this file, I think this would be better written in the context of when an ExternalEventRecord is created, rather than using `this function is called` which also builds up a false impression this is more like a handler.

E.g.

`[suspending] is called to create an [ExternalEventRecord] by [ExternalEventExecutor] after the calling flow suspends.`

2022-08-08 09:55 UTC, simon-johnson-r3 commented on libs/flows/flows/src/main/kotlin/net/corda/flow/external/events/handler/ExternalEventHandler.kt
> +     * [resuming] is called after receiving a response from an external processor and before the calling flow resumes.
Same here, `[resuming]s is called to create a [RESUME] after...`

2022-08-08 09:55 UTC, simon-johnson-r3 commented on libs/flows/flows/src/main/kotlin/net/corda/flow/external/events/handler/ExternalEventRecord.kt
> +    constructor(topic: String, payload: Any) : this(topic, null, payload)
This strikes me as un-Kotlin like, instead the key can be defaulted to null. It forces the use of named parameters at the point of calling, but that's far less error prone given there are two `Any` types in play here, which could easily be assigned the wrong values.

2022-08-08 09:55 UTC, simon-johnson-r3 commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/external/events/impl/ExternalEventManagerImpl.kt
> +        const val INSTANT_COMPARE_BUFFER = 100L
Name's not very explanatory, maybe consider `INSTANT_COMPARE_WINDOW_MILLISECONDS` ?

2022-08-08 09:55 UTC, simon-johnson-r3 commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/external/events/impl/ExternalEventManagerImpl.kt
> +            // Have a "sending" and "resending" log line
I don't understand this comment, perhaps remove it?

2022-08-08 09:55 UTC, simon-johnson-r3 commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/application/persistence/PersistenceServiceImpl.kt
> +        enforceNotPrimitive(entity::class.java)
It's not directly related to this review but only `remove()` prohibits primitive types like this which seems asymmetrical. Alongside that, the error from `enforceNotPrimitive()` suggests something was the subject of a "receive", whereas the only time it's called nothing was being received.

2022-08-08 14:03 UTC, LWogan commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/external/events/impl/ExternalEventManagerImpl.kt
> +        const val INSTANT_COMPARE_BUFFER = 100L
I'll rename it to INSTANT_COMPARE_BUFFER_MILLIS to avoid any confusion with the sliding window logic which is a little different.

Ill add a comment in the code to explain why we use it. Comparing two instants which are the same can yield inconsistent comparison results. A small buffer is added to make sure we pick up new messages to be sent. I'll reduce the buffer to 10 as I think that is all that is required.

2022-08-23 16:08 UTC, JamesHR3 reviewed
Some thoughts - I haven't reviewed everything in detail but I know you have a bit of refactoring to do anyway to rebase this properly.

2022-08-23 16:08 UTC, JamesHR3 commented on components/flow/flow-service/build.gradle
> +    implementation project(':libs:flows:flows')
This module name isn't totally clear - what is this referring to?

2022-08-23 16:08 UTC, JamesHR3 commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/application/persistence/external/events/AbstractPersistenceExternalEventFactory.kt
> +abstract class AbstractPersistenceExternalEventFactory<PARAMETERS : Any> :
Can we model this without using an abstract class? It feels like we're using inheritance when really all we need to do is pass a parameter that generates the request to a concrete class that deals with everything else.

I suppose the argument is that you need the subclasses anyway to register as services, but I'd prefer to represent those with a has-a relationship to this.

2022-08-23 16:08 UTC, JamesHR3 commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/external/events/impl/ExternalEventManager.kt
> +interface ExternalEventManager {
Can you document this? (Happy to raise a follow up to do it.)

Should it be in the flow service or as a separate module like the session manager? I think there's arguments either way so I'm happy to leave it here if you think that makes sense, but it is worth thinking about.

2022-08-23 16:08 UTC, JamesHR3 commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/external/events/impl/ExternalEventManagerImpl.kt
> +        const val INSTANT_COMPARE_BUFFER_MILLIS = 10L
We've run into this sort of problem before and the other way of looking at it is to truncate the timestamp to some precision and then do the comparison. That's effectively what you're doing here, although remember that you should truncate both in the comparison.

2022-08-23 16:08 UTC, JamesHR3 commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/external/events/impl/ExternalEventManagerImpl.kt
> +                val error = externalEventResponse.error
Should we log in the event of an error? We're currently logging more at the debug level in the happy path than we are on failure.

2022-08-23 16:08 UTC, JamesHR3 commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/handlers/events/ExternalEventResponseHandler.kt
> +            // do something, probably discard the event
This comment doesn't seem to line up with anything that's happening here - does it need an update?

We may want to add some logging here too to address those concerns.

2022-08-23 16:08 UTC, JamesHR3 commented on processors/crypto-processor/build.gradle
> +    runtimeOnly project(':libs:flows:external-events-impl')
I wonder if we should rename this module (and its API) to make it clearer that it's for working with external events that the flow worker is sending / receiving, and it's not for the flow worker itself to use?

2022-08-24 12:11 UTC, lankydan commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/application/persistence/external/events/AbstractPersistenceExternalEventFactory.kt
> +abstract class AbstractPersistenceExternalEventFactory<PARAMETERS : Any> :
I think the class either stays as it is or is removed completely. The class currently, defines the `responseType`, simplifies the creation of an `EntityRequest` and handles the response. This means that each actual persistence factory only needs to define how to create their specific request type, making their classes like 5 lines long.

2022-08-25 11:30 UTC, lankydan commented on components/flow/flow-service/build.gradle
> +    implementation project(':libs:flows:flows')
Not sure what else to call it. It is the internal API for flow related functionality.

2022-08-25 16:16 UTC, JamesHR3 approved these changes, later dismissed
I don't have much to say, but you will need to get a re-approval from someone to merge this once things have been synced up.

2022-08-25 16:16 UTC, JamesHR3 commented on processors/crypto-processor/src/integrationTest/kotlin/net/corda/processors/crypto/tests/infra/FlowOpsResponses.kt
> +            receivedEvents[it.key] = flowOpsResponse
These logs look pretty aggressive, although it's in an integration test so maybe that's fine. How many events come through here? If it's a lot (more than ~5) we should tone this down a bit.

2022-08-25 16:16 UTC, JamesHR3 commented on gradle.properties
> -cordaApiVersion=5.0.0.162-beta+
Obviously you'll need to update this (and the API repo seems to be moving pretty quickly at the moment!)

2022-08-25 16:20 UTC, lankydan commented on processors/crypto-processor/src/integrationTest/kotlin/net/corda/processors/crypto/tests/infra/FlowOpsResponses.kt
> +            receivedEvents[it.key] = flowOpsResponse
Ah I can remove these, i put these in to try and fix this test.

2022-08-26 15:06 UTC, mnesbit approved these changes, later dismissed
ok

2022-08-26 17:01 UTC, dickon submitted a review, later dismissed
LGTM, there was a bad merge that caused a problem with one of the tests I touched.

2022-08-26 18:49 UTC, dickon approved these changes
LGTM

2022-08-26 19:37 UTC, merged