NOTICK: Update dependency versions for detekt, hibernate, jackson, javalin and junit
corda/corda-runtime-os pull request #1746
Opened 2022-07-27 13:11 UTC by JamesHR3

This PR updates the following dependency versions:
- Detekt 1.20 -> 1.21
- Hibernate 5.6.9.FINAL -> 5.6.10.FINAL
- Jackson 2.13.2 -> 2.13.3
- Javalin 4.6.3 -> 4.6.4
- JUnit 5.8.2 -> 5.9.0

Notes:
- The detekt update has resulted in a lot of extra errors being flagged in the AMQP code. I re-baselined it but I still had to set some new suppressions. The rest of the codebase was unaffected.
- The detekt update also resulted in errors being reported in the detekt configuration. These have been addressed.
- The JUnit update ended up being more impactful than might be expected from a minor version bump, as a bugfix introduced in this version is actually a breaking change. Previously test lifecycle methods (e.g. a method marked as `@BeforeEach`) were incorrectly allowed to be `private`. I've updated instances where this was causing a problem. See https://junit.org/junit5/docs/snapshot/release-notes/ for details.

2022-07-27 13:11 UTC, JamesHR3 commented
These are not the only dependencies that need updating, but this PR is large enough without fixing further dependencies.

2022-07-27 14:48 UTC, JamesHR3 commented
@chrisr3 Updating JUnit causes an osgi resolution problem in the sandbox test code. I've had a go at resolving by adding some extra dependencies into the test code, but it's very possible there's a better approach here. I'm not totally familiar with what's going on so you might want to have a quick look.

2022-07-27 15:32 UTC, chrisr3 requested changes
The latest version of JUnit Jupiter must have slightly "smarter" OSGi metadata :grinning:.

2022-07-27 15:32 UTC, chrisr3 commented on gradle.properties
> -jacksonDatabindVersion = 2.13.2.2
As the comment says.... :wink:

2022-07-27 15:32 UTC, chrisr3 commented on testing/sandboxes/build.gradle
> +    implementation "org.junit.platform:junit-platform-launcher:$junitPlatformVersion"
You shouldn't need these. Are you trying to resolve `:applications:examples:sandbox-app` by any chance? Because in that case, try this:
```diff
diff --git a/testing/sandboxes/build.gradle b/testing/sandboxes/build.gradle
index bba6d30eef..68c6c0b3e2 100644
--- a/testing/sandboxes/build.gradle
+++ b/testing/sandboxes/build.gradle
@@ -13,8 +13,9 @@ dependencies {
     compileOnly 'org.osgi:osgi.core'
 
     api project(':libs:sandbox')
-    api project(':libs:virtual-node:virtual-node-info')
     api project(":libs:packaging:packaging")
+    api project(':libs:packaging:packaging-core')
+    api project(':libs:virtual-node:virtual-node-info')
     api "org.junit.jupiter:junit-jupiter-api:$junit5Version"
 
     implementation platform("net.corda:corda-api:$cordaApiVersion")
@@ -23,10 +24,6 @@ dependencies {
     implementation project(':components:virtual-node:cpi-info-read-service')
     implementation project(':components:virtual-node:virtual-node-info-read-service')
     implementation project(':components:virtual-node:cpk-read-service')
-    implementation "org.junit.jupiter:junit-jupiter-engine:$junit5Version"
-    implementation "org.junit.platform:junit-platform-launcher:$junitPlatformVersion"
-
-    implementation project(':libs:packaging:packaging-core')
 
     runtimeOnly "org.apache.felix:org.apache.felix.configadmin:$felixConfigAdminVersion"
     runtimeOnly project(':libs:sandbox-internal')
@@ -36,6 +33,9 @@ tasks.named('jar', Jar) {
     bundle {
         bnd '''\
 Bundle-SymbolicName: \${project.group}.sandbox-testing
+Import-Package: \
+    org.junit.jupiter.api.extension;resolution:=optional,\
+    *
 '''
     }
 }
```
The `sandbox-app` doesn't need the pieces of `sandbox-testing` that use JUnit.

2022-07-27 15:32 UTC, chrisr3 commented on testing/sandboxes/build.gradle
>      implementation project(':libs:packaging:packaging-core')
This doesn't look right, though! The `CpiLoader` interface uses `packaging-core` types, which means that `packaging-core` is needed at compile time. And that means that this should be an `api` dependency (and moved up to be with the rest of this module's `api` dependencies).

2022-07-27 15:36 UTC, JamesHR3 commented on gradle.properties
> -jacksonDatabindVersion = 2.13.2.2
Good catch :)

2022-07-27 15:56 UTC, chrisr3 approved these changes, later dismissed
LGTM - assuming the tests still pass :wink:

2022-07-27 17:27 UTC, ronanbrowne submitted a review, later dismissed
LGTM

2022-07-28 09:28 UTC, JamesHR3 commented
Don't merge just yet in the event this succeeds - establishing whether a forced quasar downgrade helps with the e2e tests.

2022-07-28 12:16 UTC, JamesHR3 commented
Should be ok now, we're back on snapshot versions of quasar.

2022-07-28 13:05 UTC, vkolomeyko approved these changes
LGTM

2022-07-28 13:24 UTC, merged