CORE-6008: CordaMock PersistenceService injected into flows
corda/corda-runtime-os pull request #1830
Opened 2022-08-08 15:42 UTC by LizR3

Uses HSQLDB in-memory by default
Registered with the FiberMock to keep connections alive & allow access for testing
Made example CorDapp a bit more sane

2022-08-09 12:45 UTC, driessamyn commented on gradle.properties
> +jpaVersion=2.2
This is already defined in https://github.com/corda/corda-api/blob/e4473e2e17975405ff31ec5f99b6b55bf63f933e/gradle.properties#L45
and provided by `platform("net.corda:corda-api:$cordaApiVersion")` 

Example: https://github.com/corda/flow-worker/blob/feef661738a2fdf750f00671ec2400b5bdcd929b/libs/db/db-orm/build.gradle

2022-08-09 13:37 UTC, LizR3 commented on gradle.properties
> +jpaVersion=2.2
Thanks, will take it out.

2022-08-09 15:07 UTC, JamesHR3 reviewed
I've mostly looked at the `DbPersistenceService`.  Not too much to say, but I am a little concerned we might not properly represent what will happen in error scenarios.

2022-08-09 15:07 UTC, JamesHR3 commented on cordapp-test-utils/test-utils/src/main/kotlin/net/corda/testutils/services/DbPersistenceService.kt
> +            return entities.map { em.merge(it) }
Not really a comment on this, but a note that as of today the list versions of these APIs isn't implemented in Corda. That should be done prior to DP2 so it shouldn't be an issue, but be aware that if you try this out now it won't succeed.

2022-08-09 15:07 UTC, JamesHR3 commented on cordapp-test-utils/test-utils/src/main/kotlin/net/corda/testutils/services/DbPersistenceService.kt
> +class DbPersistenceService(x500 : MemberX500Name) : PersistenceService {
If any of the APIs in this fail, what will they throw? I think the actual flow service implementation will throw a `CordaPersistenceException`, which is exposed on the API so I think it is possible for flow code to catch it. (That's not very well tested at the moment!)

2022-08-09 15:35 UTC, LizR3 commented on cordapp-test-utils/test-utils/src/main/kotlin/net/corda/testutils/services/DbPersistenceService.kt
> +            return entities.map { em.merge(it) }
Thanks! I spotted that `query` wasn't implemented but missed those. I'll leave them in for now but will make a story for myself to revisit and refresh what I'm doing closer to time.

2022-08-09 15:42 UTC, LizR3 commented on cordapp-test-utils/test-utils/src/main/kotlin/net/corda/testutils/services/DbPersistenceService.kt
> +class DbPersistenceService(x500 : MemberX500Name) : PersistenceService {
I can do that now for sure; there's a TODO in the README.md to make all the exceptions match.

2022-08-09 16:27 UTC, driessamyn requested changes
Most of these comments are very nitpicky, feel free to ignore, but there are some things like EMs and EMFs need to be closed when you're finished, which I feel should be tidied up before this is merged.

I think calling this a mock isn't entirely correct as it's a stub, and I wonder if a mock would be more useful in certain cases, but realise this is debatable.
However, if we have this as a stub, and go through the effort of using a real DB (which has it's own downsides), then I think at least we should integration DB migrations as well as that is one of the few things I can think of that would add value when using a real DB rather than real mocks. DB migrations are otherwise very hard to test before doing an actual deployment.

I haven't reviewed the CordApp.

2022-08-09 16:27 UTC, driessamyn commented on cordapp-test-utils/README.md
> +- via a class, which will be constructed when a response flow is initialized
```suggestion
- via a class, which will be constructed when a response flow is initialized.
```

2022-08-09 16:27 UTC, driessamyn commented on cordapp-test-utils/README.md
> +Uploading an instance allows flows to be constructed containing other mocks, injected logic, etc.. It also allows
```suggestion
Uploading an instance allows flows to be constructed containing other mocks, injected logic, etc. It also allows
```

2022-08-09 16:27 UTC, driessamyn commented on cordapp-test-utils/README.md
> +- A `CordaFlowChecker` which checks your flow for a default constructor and required Corda annotations
```suggestion
- A `CordaFlowChecker` which checks your flow for a default constructor and required Corda annotations.
```

2022-08-09 16:27 UTC, driessamyn commented on cordapp-test-utils/README.md
> +- A `SimpleJSonMarshallingService` which can be used to convert objects to JSON and vice-versa
```suggestion
- A `SimpleJSonMarshallingService` which can be used to convert objects to JSON and vice-versa.
```

2022-08-09 16:27 UTC, driessamyn commented on cordapp-test-utils/README.md
> +- A Json-formatted string, as you would submit with `curl`:
```suggestion
- A JSON-formatted string, as you would submit with `curl`:
```

2022-08-09 16:27 UTC, driessamyn commented on cordapp-test-utils/README.md
> +- A `PassThroughFlowEngine` which will call any `SubFlows` you give to it
```suggestion
- A `PassThroughFlowEngine` which will call any `SubFlows` you give to it.
```

2022-08-09 16:27 UTC, driessamyn commented on cordapp-test-utils/README.md
> +- A `DbPersistenceService` using an in-memory HSQLDB
```suggestion
- A `DbPersistenceService` using an in-memory HSQLDB.
```

2022-08-09 16:27 UTC, driessamyn commented on cordapp-test-utils/example-app/src/integrationTest/kotlin/net/cordacon/example/RollCallTest.kt
> +        val persistence = corda.getPersistenceServiceFor(teacher)
Should there be a concept of a Node (teacher)? A Vnode in C5 is a combination of the X500 and a group ID. For now, it probably doesn't matter too much as I don't _think_ we support x-network operations, but this would technically be possible.
I also wonder if we have a `Node` or `VirtualNode` data structure it may be clearer what it is as X500 names could exist outside of a Corda Node.

2022-08-09 16:27 UTC, driessamyn commented on cordapp-test-utils/test-utils/src/main/kotlin/net/corda/testutils/internal/BaseFiberMock.kt
> +class BaseFiberMock : FiberMock {
I think this is more of a Stub or Fake than a Mock. 
If it was a Mock, it'd be great to be able to test behaviour. The examples show asserting state at the end of the flow, and stubs can be very useful, but mocks are often more powerful as you can verify behaviour. E.g. `did it invoke a delete` rather than `is the end result it has deleted`. 
Supporting this with mocks would also mean you may not need a HSQL implementation, which has its own limitations. For example some queries will behave differently in Postgres vs. HSQL, and/or we may want to support native queries at some point for example. Somebody testing their CordApp is generally only interested in how their code is interacting with the API, not the result of the interaction.

2022-08-09 16:27 UTC, driessamyn commented on cordapp-test-utils/example-app/src/main/kotlin/net/cordacon/example/RollCallFlow.kt
> +import java.util.*
I thought we disallowed wildcard imports? I'm surprised detekt hasn't moaned about it.

2022-08-09 16:27 UTC, driessamyn commented on cordapp-test-utils/example-app/src/main/kotlin/net/cordacon/example/RollCallFlow.kt
> +data class AbsenceRecordEntity(
This should probably be in a contract CPK. This will work technically, and it doesn't matter probably till we have a ledger, but I thought our guidance was to have custom schemas in a separate CPK.

Possibly more important, this app doesn't seem to have a liquibase file. If we go through the effort of creating a HSQL DB, then we may as well do the DB migration as well as that is possibly one of the only good reasons to have a real DB, at least it validates the migration files, which are very hard to otherwise test without doing an actual deployment.

2022-08-09 16:27 UTC, driessamyn commented on cordapp-test-utils/test-utils/build.gradle
> +    implementation "org.hsqldb:hsqldb:$hsqldbVersion"
I think you only need this as a runtime dependency.

2022-08-09 16:27 UTC, driessamyn commented on cordapp-test-utils/test-utils/src/main/kotlin/net/corda/testutils/CordaMock.kt
> +    private val injector: FlowServicesInjector = SensibleServicesInjector()
Not a big fan of calling something `SensibleServicesInjector` as it sort of implies the real one isn't a sensible implementation.

2022-08-09 16:27 UTC, driessamyn commented on cordapp-test-utils/test-utils/src/main/kotlin/net/corda/testutils/internal/BaseFiberMock.kt
> +    override fun registerPersistenceService(x500: MemberX500Name, persistence: PersistenceService) {
I think you use `member` elsewhere and here `x500`. Probably worth keeping consistent, although I think node/vnode would be more suitable (along with a vnode type)

2022-08-09 16:27 UTC, driessamyn commented on cordapp-test-utils/test-utils/src/main/kotlin/net/corda/testutils/internal/BaseFiberMock.kt
> +    override fun getPersistenceService(x500: MemberX500Name): PersistenceService {
As above x500/member

2022-08-09 16:27 UTC, driessamyn commented on cordapp-test-utils/test-utils/src/main/kotlin/net/corda/testutils/internal/FiberMock.kt
> +    fun registerPersistenceService(x500: MemberX500Name, persistence: PersistenceService)
As above x500/member

2022-08-09 16:27 UTC, driessamyn commented on cordapp-test-utils/test-utils/src/main/kotlin/net/corda/testutils/internal/FiberMock.kt
> +    fun getPersistenceService(x500: MemberX500Name): PersistenceService
As above x500/member

2022-08-09 16:27 UTC, driessamyn commented on cordapp-test-utils/test-utils/src/main/kotlin/net/corda/testutils/internal/JpaPersistenceUnitInfo.kt
> +class JpaPersistenceUnitInfo : PersistenceUnitInfo {
FYI, we already have one of these: https://github.com/corda/flow-worker/blob/6d23693274f7eaa61f4f9421a22d65bf46e79433/libs/db/db-orm-impl/src/main/kotlin/net/corda/orm/impl/CustomPersistenceUnitInfo.kt

Some of the other classes in `db-core` and `db-orm` (and `db-admin` if you add DB migration) may be applicable, but I'm not sure it's worth taking a reference or re-implementing. Definitely worth thinking about and coming up with pros/cons.

2022-08-09 16:27 UTC, driessamyn commented on cordapp-test-utils/test-utils/src/main/kotlin/net/corda/testutils/services/DbPersistenceService.kt
> +    private val emf = createEntityManagerFactory(x500)
EMFs need to be closed when you're done with them.

2022-08-09 16:27 UTC, driessamyn commented on cordapp-test-utils/test-utils/src/main/kotlin/net/corda/testutils/services/DbPersistenceService.kt
> +inline fun <R> EntityManagerFactory.transaction(block: (EntityManager) -> R): R {
A lot of duplication with https://github.com/corda/flow-worker/blob/6d23693274f7eaa61f4f9421a22d65bf46e79433/libs/db/db-orm/src/main/kotlin/net/corda/orm/utils/EntityManagerUtils.kt

2022-08-09 16:27 UTC, driessamyn commented on cordapp-test-utils/test-utils/src/main/kotlin/net/corda/testutils/services/DbPersistenceService.kt
> +    }
You need to do something like: 
```suggestion
this.createEntityManager().use { em ->
    val t = em.transaction
    t.begin()
    return try {
        block(em)
    } catch (e: Exception) {
        t.setRollbackOnly()
        throw CordaPersistenceException(e.message ?: "Error in persistence", e)
    } finally {
        if (!t.rollbackOnly) {
            t.commit()
        } else {
            t.rollback()
        }
    }
}
```

To ensure the EM is closed when you're finished.
As it stands, this will leak.

2022-08-11 07:41 UTC, LizR3 commented on cordapp-test-utils/example-app/src/main/kotlin/net/cordacon/example/RollCallFlow.kt
> +import java.util.*
Me too, also I thought I had disabled it in IntelliJ... will fix.

2022-08-11 11:39 UTC, LizR3 commented
All the review comments are now addressed, or have stories raised against them, except for the pros / cons discussion about using corda-runtime-os's internal classes. I'm not keen to do that at the moment as I think we have slightly different requirements, and our classes do seem to keep diverging, but I'll put together a list of pros / cons and post it to the channel.

2022-08-11 12:15 UTC, driessamyn commented on cordapp-test-utils/test-utils/src/main/kotlin/net/corda/testutils/services/DbPersistenceService.kt
> +        em.close()
This will not be closed when commit or rollback throws.

Why not use `em.use {...}` ?

2022-08-12 09:21 UTC, driessamyn approved these changes
I just left a couple more comments about closing things. Up to you if you want to make the change before merging or not. If not, I suggest doing this soon after as it sets a good example to close up resources when you're done with them.

2022-08-12 09:21 UTC, driessamyn commented on cordapp-test-utils/test-utils/src/test/kotlin/net/corda/testutils/FakeCordaTest.kt
> +        val corda = FakeCorda(flowChecker)
Bit of a detail, but now that FakeCorda is closeable (good), you should close these even in the test.
I think the Kotlion idiomatic way would be to do:

```kotlin
FakeCorda(flowChecker).use { corda ->
 ...
}
```

2022-08-12 09:21 UTC, driessamyn commented on cordapp-test-utils/test-utils/src/test/kotlin/net/corda/testutils/internal/DefaultServicesInjectorTest.kt
> +        val fiber = BaseFakeFiber()
Similar to the above, but possibly more important as this is an "example", the fiber needs to be closed now that it is Closeable.

So:

```kotlin
BasFakeFiber().use { fiber ->
...
}
```

2022-08-12 09:21 UTC, driessamyn commented on cordapp-test-utils/test-utils/src/test/kotlin/net/corda/testutils/services/DbPersistenceServiceTest.kt
> +        val persistence = DbPersistenceService(member)
Same comment as above about closing things. This case is probably the most important one as it would clean up the DB when the test is done.

2022-08-12 10:31 UTC, ronanbrowne approved these changes
LGTM - for build changes - merging on @LizR3  request

2022-08-12 10:32 UTC, merged