Add support for buildkit
corda/corda-runtime-os pull request #1852
Opened 2022-08-10 12:28 UTC by E1P3

2022-09-02 09:22 UTC, chrisr3 commented on tools/plugins/build.gradle
> +task cliInstallArchive(type: Zip) {
No, the previous task definition was correct, as it only "registered" the new task but not ask Gradle to configure it. Conversely, you are now asking Gradle to configure the "cliInstallArchive" task _immediately_, regardless of whether Gradle will actually execute it. See [Task Configuration Avoidance](https://docs.gradle.org/current/userguide/task_configuration_avoidance.html).

2022-09-05 19:08 UTC, ronanbrowne requested changes
First light pass - haven't looked at code in much detail yet - @benmcmahon100 can you also please do a run through.

2022-09-05 19:08 UTC, ronanbrowne commented on buildSrc/src/main/groovy/BuildkitBuild.groovy
> +
No need for double spacing

2022-09-05 19:08 UTC, ronanbrowne commented on buildSrc/src/main/groovy/corda.docker-app.gradle
> +    // buildctl \
this is more suited to docs not code

2022-09-05 19:08 UTC, ronanbrowne commented on tools/plugins/build.gradle
> +    // Task executes the buildctl build command below
as above below lines more suited to docs

2022-09-05 19:08 UTC, ronanbrowne commented on tools/plugins/build.gradle
> +tasks.register('publishBuildkitImage' , BuildkitBuild) {
Question has this been tested in a composite build locally?

2022-09-06 15:41 UTC, E1P3 commented on tools/plugins/build.gradle
> +task cliInstallArchive(type: Zip) {
The task requires most of the same inputs as publishOSGiImage. That snippet was left over from a previous commit modifying publishOSGiImage. I have changed it back as it was in the current commit.

2022-09-06 15:42 UTC, E1P3 commented on tools/plugins/build.gradle
> +tasks.register('publishBuildkitImage' , BuildkitBuild) {
I have tested it just now. Everything looks fine.

2022-09-06 16:02 UTC, ronanbrowne requested changes
Can you set up a call with @benmcmahon100  for Thursday ( me optional) to go through this as likely will be easier on a call

2022-09-06 16:02 UTC, ronanbrowne commented on Jenkinsfile
> +@Library('corda-shared-build-pipeline-steps@jansz/CORE-4935/buildkit-POC') _
need to change before merge back in FYI

2022-09-06 16:02 UTC, ronanbrowne commented on buildSrc/src/main/groovy/corda.docker-app.gradle
> +            commandLine 'bash', '-c', "buildctl --addr tcp://localhost:3476 build --frontend=dockerfile.v0 --local context=/ --local dockerfile=${project.rootDir.toString() + "/docker"} --opt build-a
docker-js-temp.software.r3.com needs to change to the default.

2022-09-06 16:02 UTC, ronanbrowne commented on buildSrc/src/main/groovy/corda.docker-app.gradle
> +            commandLine 'bash', '-c', "buildctl --addr tcp://localhost:3476 build --frontend=dockerfile.v0 --local context=/ --local dockerfile=${project.rootDir.toString() + "/docker"} --opt build-a
We need to do _something_  about this, it's just a but messy.  

At minimum formatted properly (ctrl + shift + f on selection ) and likely better to build this as a string in a support method which has a few comments of explainer (not just the buildKit equivalent code commented in)

2022-09-06 16:02 UTC, ronanbrowne commented on docker/Dockerfile
> +ARG BUILD_PATH="/applications/workers/release/crypto-worker/build/tmp/publishOSGiImage/containerization/corda-crypto-worker-5.0.0.0-SNAPSHOT.jar"
Not sure about this default value, why just the crypto worker and why this version

2022-09-06 16:02 UTC, ronanbrowne commented on buildSrc/src/main/groovy/BuildkitBuild.groovy
> +// Task to publish worker images to artifactory using buildkit image builder
Formatting still looks off here FYI

2022-09-13 15:48 UTC, benmcmahon100 commented on buildSrc/src/main/groovy/corda.docker-app.gradle
> +            commandLine 'bash', '-c', "buildctl --addr tcp://localhost:3476 build --frontend=dockerfile.v0 --local context=/ --local dockerfile=${project.rootDir.toString() + "/docker"} --opt build-a
--addr should parameterizable but default as above would be correct
`--local context = /` needs be checked in case `./` works instead of `/`

Overall we should try function this. i.e.:

```
buildkitdCommandBuilder(extraOpts =[]) {
  def baseCommand = ["buildctl", "--addr tcp://localhost:3476" "build" "--frontend=dockerfile.v0" "--local context=." "--local dockerfile=${project.rootDir.toString() + "/docker"}"]
   def opts = []
   def commandTail = []
   return baseCommand + opts + extraOpts + commandTail
}
```

2022-09-13 15:51 UTC, benmcmahon100 commented on buildSrc/src/main/groovy/corda.docker-app.gradle
> +            commandLine 'bash', '-c', "buildctl --addr tcp://localhost:3476 build --frontend=dockerfile.v0 --local context=/ --local dockerfile=${project.rootDir.toString() + "/docker"} --opt build-a
Only other thing is to change to tar output instead of pushing

2022-10-13 10:25 UTC, closed without merging