CORE-5894 Creating a Corda CLI install zip and scripts.
corda/corda-runtime-os pull request #1857
Opened 2022-08-10 14:38 UTC by pmck91

A gradle task was created to bundle all of the cli plugin jars, and the cli host into a zip file to be published to artifactory.

Two install scripts are written one for windows and one for linux. These move the jars to the users home dir, and then generate a corda-cli.cmd or sh

2022-08-10 14:52 UTC, vkolomeyko commented on tools/plugins/buildSrc/install.ps1
> +$cliCommand = "java -Dpf4j.pluginsDir=$cliHomeDir\plugins -jar corda-cli.jar %*"
```suggestion
$cliCommand = "$ENV:JAVA_HOME\bin\java -Dpf4j.pluginsDir=$cliHomeDir\plugins -jar corda-cli.jar %*"
```

2022-08-10 15:16 UTC, ronanbrowne requested changes

2022-08-10 15:16 UTC, ronanbrowne commented on tools/plugins/build.gradle
> +    cliHostDist 'net.corda.cli.host:corda-cli:0.0.1-beta-+'
we already have a property for this can you update this to substitute in ${pluginHostVersion} rather then this embedded version

2022-08-10 15:16 UTC, ronanbrowne commented on tools/plugins/build.gradle
> +        from "$projectDir/buildsrc"
FYI buildsrc is generally a special folder structure in gradle for plugins - so this is a little against convention, maybe better to call the folder installScripts or similar IMO

2022-08-10 15:16 UTC, ronanbrowne commented on tools/plugins/build.gradle
> +    dependsOn tasks.named("cliDistZip")
you shouldn't need to do tasks.named as its declared in same file

2022-08-10 15:16 UTC, ronanbrowne commented on tools/plugins/build.gradle
> +    myZip
you'll need to add a publish block in here as well to actually send this to Artifactory ( if i recall Zips arent picked by by default by the corda-internal-gradle-plugins plugin but worth double checking )

2022-08-10 15:16 UTC, ronanbrowne commented on tools/plugins/build.gradle
> +tasks.register('cliDistZip') {
seems a bit messy i think you can do this with out multiple copy blocks , just declare copy as they task type and specify your From statements see https://docs.gradle.org/current/dsl/org.gradle.api.tasks.Copy.html

2022-08-10 17:21 UTC, pmck91 commented on tools/plugins/build.gradle
> +    cliHostDist 'net.corda.cli.host:corda-cli:0.0.1-beta-+'
brilliant Ill update that

2022-08-10 17:21 UTC, pmck91 commented on tools/plugins/build.gradle
> +        from "$projectDir/buildsrc"
will do

2022-08-11 12:12 UTC, pmck91 commented on tools/plugins/build.gradle
> +tasks.register('cliDistZip') {
the issue is there two intos, multiple froms is fine, but it always uses the last into

2022-08-11 13:58 UTC, pmck91 commented on tools/plugins/build.gradle
> +    dependsOn tasks.named("cliDistZip")
for some odd reason, when I remove this, and use the raw task name, I get errors about missing cliPluginTask in the sub projects

2022-08-11 14:54 UTC, vkolomeyko approved these changes
LGTM

2022-08-11 17:08 UTC, ronanbrowne approved these changes
LGTM

2022-08-11 17:09 UTC, merged