CORE-4364 CPK verification during Sandbox creation
corda/corda-runtime-os pull request #1862
Opened 2022-08-10 22:24 UTC by mbrkic-r3

2022-08-11 11:11 UTC, kyriathar commented on libs/packaging/packaging/src/main/kotlin/net/corda/libs/packaging/Cpk.kt
> +     * @throws [FileNotFoundException] FileNotFoundException - if Cpk file cannot be opened for reading.
```suggestion
     * @throws [FileNotFoundException] if Cpk file cannot be opened for reading.
```

2022-08-11 12:05 UTC, kyriathar commented on libs/sandbox-internal/src/main/kotlin/net/corda/sandbox/internal/SandboxServiceImpl.kt
> +            throw SandboxException("The sandbox can't find CPK ${cpk.metadata.cpkId.name} with file checksum $fileChecksum")
```suggestion
            throw SandboxException("CPK ${cpk.metadata.cpkId.name} with file checksum $fileChecksum not found")
```

2022-08-11 12:41 UTC, kyriathar commented
I understand we brought this check close to Sandbox creation to prevent Cpks tampering on disk when creating sandboxes. The way it currently is there is I think there is a tiny window but still there between `verifyCpks(cpks)` and sandboxes creation below it within `SandboxServiceImpl.createSandboxes`. Would it make sense to read all Cpk content data in memory one Cpk at the time when installing main/library bundles and calculate checksum and verify just before installing it in memory?

2022-08-11 14:18 UTC, chrisr3 requested changes
I recommend moving this check up into `SandboxGroupContextServiceImpl.getOrCreate()`

2022-08-11 14:18 UTC, chrisr3 commented on libs/sandbox-internal/src/main/kotlin/net/corda/sandbox/internal/SandboxServiceImpl.kt
> +    private val cpkReadService: CpkReadService,
This is breaking the `:testing:sandboxes` code because the "test" `CpkReadService` is waiting to be told its `baseDirectory` before it can start. What is supposed to happen is:
- The test framework injects `SandboxSetup` using `@InjectService`
- The tests execute `sandboxSetup.configure(bundleContext, tempDir)`, which tells `CpkReadService` which `baseDirectory` to use.
- Once its configuration is available, the OSGi framework automatically starts the "test" `CpkReadService`.
- Once the framework contains a working `CpkReadService`, the framework automatically starts everything that depends on `CpkReadService`.

Unfortunately, `SandboxSetup` depends on `SandboxCreationService`, which is implemented by `SandboxServiceImpl`. And `SandboxServiceImpl` can no longer start without `CpkReadService`, which in turn cannot start until the tests execute `SandboxSetup.configure()`. And so have you have introduced a dependency cycle.

The `:testing:sandboxes` code needs to integrate both the JUnit and OSGi component lifecycles. Specifically, creating/destroying sandboxes either for "each test" or for "all tests", and then ensuring that all sandboxes have been terminated _before_ JUnit tries to delete `@TempDir baseDirectory`. These two lifecycles don't align naturally, which is why `SandboxSetup` resorts to enabling/disabling he `CpkReadService` programmatically. And it's already more than complicated enough.

Your easiest solution is to move this `verifyCpks` step up into `SandboxGroupContextServiceImpl` rather than `SandboxServiceImpl`. `SandboxGroupContextServiceImpl` already contains a reference to `CpkReadService`, and is the common entry point for creating sandboxes anyway.

2022-08-11 14:22 UTC, mbrkic-r3 commented on libs/sandbox-internal/src/main/kotlin/net/corda/sandbox/internal/SandboxServiceImpl.kt
> +    private val cpkReadService: CpkReadService,
thank you for detailed analysis

2022-08-11 14:37 UTC, chrisr3 commented
> I understand we brought this check close to Sandbox creation to prevent Cpks tampering on disk when creating sandboxes. The way it currently is there is, I think, a tiny window but still there between `verifyCpks(cpks)` and sandboxes creation below it within `SandboxServiceImpl.createSandboxes`. Would it make sense to read all Cpk content data in memory one Cpk at the time when installing main/library bundles and calculate checksum and verify just before installing it in memory?

That's an interesting point, but "all Cpk content data" could be _really **BIG**_! Perhaps it would be cheaper to open a file descriptor for verifying a CPK and then _keep it open_ so that we re-use it when installing that CPK? And _then_ close it, of course. This would guarantee that both verification and installation step would use the exact same data. However, I don't know how easy it would be to implement... :thinking:.

2022-08-12 08:08 UTC, mbrkic-r3 commented
> Edit: Does the `Cpk` metadata contain the SHA-256 of each of its component bundles, i.e. "main" bundle and each "library" bundle? Because it seems that the best way to guard against a corrupted filesystem is for this `inputStream` to be wrapped inside a `DigestInputStream` so that you can compute the bundle's hash "on the fly" and compare the result with an expected value:
> 
> ```kotlin
> class SandboxServiceImpl {
> 
>     private fun installBundle(
>         bundleSource: String,
>         inputStream: InputStream,
>         expectedHash: SecureHash,
>         sandboxId: UUID,
>         securityDomain: String
>     ): Bundle {
>         ...
>             val digest = // get MessageDigest from somewhere
>             DigestInputStream(inputStream, digest).use {
>                 bundleContext.installBundle(sandboxLocation.toString(), it)
>             }
> 
>             // check that digest.digest() matches expectedHash
>         ...
>     }
> 
> }
> ```
> 
> Although having said all this, I cannot see how to ask `net.corda.v5.crypto.DigestService` for a suitable `DigestInputStream` shrug.

I don't see we have hashes of component bundles. We do have hash of the CPK though (`cpk.metadata.fileChecksum`), so maybe we don't need to go to `CpkReadService`, but validate against that?
Still there remains question how to after that safely read component bundles without storing validated CPK in memory.

2022-08-12 12:24 UTC, josephzunigadaly commented
`DigestInputStream` isn't going to help here. The example where we wrap `installBundle` puts the checksum check after we have already installed the bundle. We shouldn't even have `Cpk` objects when we do the check, it should be done before any processing of the stream.

If we want to close the window where someone could modify the file between check and loading, then we need it fully loaded into memory and used for both tasks.

`CpkChunksFileManagerImpl.assembleCpk` is missing a check to see if the complete file matches the checksum it has been given. It has a `cpkChecksum` parameter but only uses it to build folder and file names. Adding a check here would be a good step forward. 

`assembleCpk` builds the file with its final name, without checking the file matched the checksum expected of it. This allows an attacker with access to the message bus to feed a bad file into the system giving it any checksum they want. They can overwrite valid CPKs. Then when we come to create sandboxes for them we will load the unwanted file. This method needs to build the file under a temporary filename and only rename the file to the final filename once it has passed the checksum check.

When it comes to building a sandbox, we get a CPK from `CpkReadServiceImpl.get` by passing in the file hash. We know the caller is asking for that particular hash so it would be enough to check the hash passed as a parameter matches the file loaded from disk. To close that window mentioned earlier, we'd need to load the file into memory at this point. We could build a different implementation of `CpkImpl` with the file in memory and the checksum checked, then return that from `get`. We'd want to check code paths to make sure references to such an object don't last long.

2022-08-12 13:32 UTC, chrisr3 commented
> `DigestInputStream` isn't going to help here. The example where we wrap `installBundle` puts the checksum check after we have already installed the bundle. We shouldn't even have `Cpk` objects when we do the check, it should be done before any processing of the stream.

The bundle may have been installed, but it has not yet been started. OSGi describes the "install" phase [here](https://docs.osgi.org/javadoc/r4v43/core/org/osgi/framework/BundleContext.html#installBundle(java.lang.String,%20java.io.InputStream)), but the bottom line is that the returned bundle is `INSTALLED` and _possibly_ `RESOLVED`, but certainly not `ACTIVE`. You will also notice in `SandboxServiceImpl.createSandbox()` that we start the bundles together, and only after they have _all_ been installed successfully.

I don't think that loading all sandbox bundles into memory is a good idea because we don't set a limit on the size of CPKs.

2022-08-15 13:50 UTC, mbrkic-r3 commented
I've refactored code to implement option #3 from https://r3-cev.atlassian.net/browse/CORE-4364?focusedCommentId=205602 as it was closest to the previous implementation in this PR (which had security issue) and it didn't require much effort.
Please review and provide feedback in case you think that some other approach would be better

2022-08-15 14:15 UTC, chrisr3 reviewed
Just a few thoughts... If I've understood this correctly, you are avoiding the need for knowing the individual bundle checksums since everything is part of the overall CPK file's checksum :+1:.

2022-08-15 14:15 UTC, chrisr3 commented on libs/sandbox-internal/src/main/kotlin/net/corda/sandbox/internal/SandboxServiceImpl.kt
> +            ZipInputStream(dis).use { zipStream ->
I think you're closing your streams several times, because closing `ZipInputStream` will close both `DigestInputStream` and the underling `input` too. So you probably don't need to wrap this block inside `input.use {}`.

2022-08-15 14:15 UTC, chrisr3 commented on libs/sandbox-internal/src/main/kotlin/net/corda/sandbox/internal/SandboxServiceImpl.kt
> +                }
You can only reach these lines if `zipStream.nextEntry` has returned `null`. Doesn't this mean that the stream has already been read completely?

2022-08-15 14:15 UTC, chrisr3 commented on libs/sandbox-internal/src/main/kotlin/net/corda/sandbox/internal/SandboxServiceImpl.kt
>              bundles.add(mainBundle)
Do we also need to check that `mainBundle` has been assigned? E.g.
```kotlin
if (!::mainBundle.isInitialized) {
    throw SandboxException("Main bundle eaten by Evil Bunnies!")
}
```

2022-08-15 15:17 UTC, kyriathar commented
I suppose and since @chrisr3 hasn't flagged it, it does not matter much that we might have installed some bundles to osgi only to find out that cpk actual checksum is not the expected, since we are not creating the `Sandbox`.

2022-08-15 15:27 UTC, chrisr3 commented
> I suppose and since @chrisr3 hasn't flagged it, it does not matter much that we might have installed some bundles to osgi only to find out later that cpk actual checksum is not the expected, since we are not creating and exposing the `Sandbox`.

If the checksum doesn't match then we _must not_ start _any_ of the sandbox bundles. I am assuming that we also _uninstall_ any bundles we have already installed if we cannot create the sandbox, but haven't checked.

2022-08-15 15:56 UTC, josephzunigadaly commented on libs/sandbox-internal/src/main/kotlin/net/corda/sandbox/internal/SandboxServiceImpl.kt
> +                throw SandboxException("File checksum validation failed for CPK ${cpk.metadata.cpkId.name} during sandbox creation")
This is too late to perform the check. There should be no processing of the stream until we have checked the checksum.

Plus `cpk.metadata.fileChecksum` is calculated from the file itself, it is not the expected checksum.

2022-08-15 16:06 UTC, chrisr3 commented on libs/sandbox-internal/src/main/kotlin/net/corda/sandbox/internal/SandboxServiceImpl.kt
> +                throw SandboxException("File checksum validation failed for CPK ${cpk.metadata.cpkId.name} during sandbox creation")
< This is too late to perform the check. There should be no processing of the stream until we have checked the checksum.

Please explain what the risk is of allowing the OSGi framework _only_ to analyse the OSGi metadata, (Or _attempt_ to analyse, if the file is corrupt.) As I have already demonstrated, the classes _are not instantiated_ unless the bundles are started, which will only happen once all bundles have been installed successfully.

2022-08-15 16:10 UTC, mbrkic-r3 commented on libs/sandbox-internal/src/main/kotlin/net/corda/sandbox/internal/SandboxServiceImpl.kt
> +                throw SandboxException("File checksum validation failed for CPK ${cpk.metadata.cpkId.name} during sandbox creation")
> This is too late to perform the check. There should be no processing of the stream until we have checked the checksum.
Could you please give more background regarding this, what would be the issue with current implementation?

> Plus cpk.metadata.fileChecksum is calculated from the file itself, it is not the expected checksum.
Doesn't this value come from CpiInfoReadService, which should have the correct value (created by CpiValidator)?

2022-08-15 16:20 UTC, chrisr3 commented on libs/sandbox-internal/src/main/kotlin/net/corda/sandbox/internal/SandboxServiceImpl.kt
> +                throw SandboxException("File checksum validation failed for CPK ${cpk.metadata.cpkId.name} during sandbox creation")
- A CPKv1 file is a ZIP containing a "main" bundle and all the "library" bundles as ZIP entries.
- A CPKv2 file _is_ the "main" bundle, whose "library" bundles are entries in the `META-INF` directory.

In both cases, I would expect the `fileChecksum` to be the SHA-256 of the CPK. However, your code would need updating for CPKv2.

2022-08-15 16:52 UTC, josephzunigadaly commented on libs/sandbox-internal/src/main/kotlin/net/corda/sandbox/internal/SandboxServiceImpl.kt
> +                throw SandboxException("File checksum validation failed for CPK ${cpk.metadata.cpkId.name} during sandbox creation")
> Please explain what the risk

If we do any parsing of the structure of the file, we open ourselves up to attacks on the code doing that parsing. Zip files themselves have potential attacks on their file structures.

If we check the file hash matches what is expected, we establish some level of trust in that file before we start working with it. We can reject bad files before running any code that may have been open to attack.


> Doesn't this value come from CpiInfoReadService

No, it comes from the CPK reading code which calculates it from the file. The comparison is currently comparing two checksum calculations of the file on disk. We need a comparison of the expected checksum from the DB with the file on disk.

2022-08-15 17:15 UTC, chrisr3 commented on libs/sandbox-internal/src/main/kotlin/net/corda/sandbox/internal/SandboxServiceImpl.kt
> +                throw SandboxException("File checksum validation failed for CPK ${cpk.metadata.cpkId.name} during sandbox creation")
> If we do any parsing of the structure of the file, we open ourselves up to attacks on the code doing that parsing. Zip files themselves have potential attacks on their file structures.

We are currently vulnerable to "zip bomb" attacks in any case. Corda 4 contains a [ZipBombDetector](https://github.com/corda/corda/blob/release/os/4.10/core/src/main/kotlin/net/corda/core/internal/utilities/ZipBombDetector.kt) which we should probably integrate with the sandbox regardless.

2022-08-15 20:04 UTC, chrisr3 commented on libs/sandbox-internal/src/main/kotlin/net/corda/sandbox/internal/SandboxServiceImpl.kt
> +                throw SandboxException("File checksum validation failed for CPK ${cpk.metadata.cpkId.name} during sandbox creation")
> No, it comes from the CPK reading code which calculates it from the file. The comparison is currently comparing two checksum calculations of the file on disk. We need a comparison of the expected checksum from the DB with the file on disk.

So to summarise, this problem involves **3** CPK hashes:
- _A_ -> the SHA-256 of the CPK, as stored in the database.
- _B_ -> the SHA-256 contained in `cpk.metadata.fileChecksum`
- _C_ -> the SHA-256 of the CPK, as stored on disk _right now_.

We can trivially verify that _A_ == _B_ from within `SandboxGroupContextServiceImpl.getOrCreate()` because `SandboxGroupContextServiceImpl` already contains a `CpkReadService` reference. The real problem here is that there is a race condition between verifying _B_ == _C_, and then loading the CPK _again_ from disk to load it into the OSGi framework.

I _do not_ want to resolve this by loading the entire CPK into memory because we don't know how large CPKs will be, _and nor should we care_. And I can _live with_ wrapping a CPK inside a `DigestInputStream` with zip-bomb detection. However, I think the best solution would be to keep an open file descriptor for the CPI on disk, for the lifetime of its `Cpi` object. For example, an underlying open `JarFile` providing its component CPK input streams via `JarFile.getInputStream()`. On UNIX, I _believe_ we could invoke `File.deleteOnExit()` for this `JarFile`, which would delete the file's directory entry immediately while still keeping the descriptor open, UNIX would not be able to reclaim the disk space until all its open file descriptors had been closed. On Windows, an open file handle acts like an exclusive file lock. But in either case, the CPI information on disk would become unmodifiable, thus removing the need to verify _B_ == _C_ in the first place.

And then I thought "Wait a minute, this sounds familiar. I thought we did something like this already..." :thinking:

And that was when I suddenly remembered PR #1417.

I think #1417 was supposed to make the code simpler, but its looking like long-lived file descriptors were actually an intentional and desirable - although maybe poorly documented - feature. And now we need that feature back.

2022-08-15 20:52 UTC, josephzunigadaly commented on libs/sandbox-internal/src/main/kotlin/net/corda/sandbox/internal/SandboxServiceImpl.kt
> +                throw SandboxException("File checksum validation failed for CPK ${cpk.metadata.cpkId.name} during sandbox creation")
This assumes the file locking seen on Windows also happens on other operating systems. It does not. An open file will not protect against modification.

2022-08-15 23:48 UTC, chrisr3 commented on libs/sandbox-internal/src/main/kotlin/net/corda/sandbox/internal/SandboxServiceImpl.kt
> +                throw SandboxException("File checksum validation failed for CPK ${cpk.metadata.cpkId.name} during sandbox creation")
I assumed no such thing, which is why I also mentioned using `File.deleteOnExit()` for UNIX. Actually, I've just checked and discovered that `File.deleteOnExit()` _isn't_ implemented on UNIX as I described after all, which is a pity. But that just means that we implement the semantics I described _explicitly_ instead (for `File f`):
```java
try (InputStream input = new FileInputStream(f)) {
    if (f.delete()) {
        System.out.println("Successfully deleted file: " + f.getName());
    } else {
        System.out.println("Delete failed! Are you using Windows?");
        f.deleteOnExit();  // Meh, delete it anyway!
    }

    // Read the open FileInputStream ...
}
```
The point is that UNIX allows you delete an open file _and still read from it_, because the allocated storage space isn't returned to the file system until all of the file's descriptors have been closed. _This_ is the behaviour that would make the file effectively immutable on UNIX. There is no assumption here about file locking.

You cannot delete an open file on Windows, of course, but you don't need to either.

2022-08-16 09:29 UTC, mbrkic-r3 commented on libs/sandbox-internal/src/main/kotlin/net/corda/sandbox/internal/SandboxServiceImpl.kt
> +                throw SandboxException("File checksum validation failed for CPK ${cpk.metadata.cpkId.name} during sandbox creation")
> We can trivially verify that A == B from within SandboxGroupContextServiceImpl.getOrCreate() because SandboxGroupContextServiceImpl already contains a CpkReadService reference. 

There is already: https://github.com/corda/corda-runtime-os/blob/8bad574d1db31dfd7cb3b5bf33194dba8bc87b82/components/virtual-node/sandbox-group-context-service/src/main/kotlin/net/corda/sandboxgroupcontext/service/impl/SandboxGroupContextServiceImpl.kt#L87

2022-08-16 09:32 UTC, mbrkic-r3 commented on libs/sandbox-internal/src/main/kotlin/net/corda/sandbox/internal/SandboxServiceImpl.kt
> +                throw SandboxException("File checksum validation failed for CPK ${cpk.metadata.cpkId.name} during sandbox creation")
> However, your code would need updating for CPKv2.

My code should work similar to existing code, so I guess that existing code also need updating? There is only one Cpk implementation (`CpkImpl`) although it seems to be used by both CPK 1.0 and 2.0 loaders - does that work correctly since resource names are different in CPK v1/v2?

2022-08-16 11:34 UTC, chrisr3 commented on libs/sandbox-internal/src/main/kotlin/net/corda/sandbox/internal/SandboxServiceImpl.kt
> +                throw SandboxException("File checksum validation failed for CPK ${cpk.metadata.cpkId.name} during sandbox creation")
Actually, we don't need to delete the [`JarFile`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/jar/JarFile.html#%3Cinit%3E(java.io.File,boolean,int)) ourselves at all, because it supports an [`OPEN_DELETE`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/zip/ZipFile.html#OPEN_DELETE) mode which already does what we want:
```kotlin
import java.io.File
import java.nio.file.Files
import java.nio.file.StandardCopyOption.REPLACE_EXISTING
import java.util.jar.JarFile
import java.util.zip.ZipFile.OPEN_DELETE
import java.util.zip.ZipFile.OPEN_READ
import org.junit.jupiter.api.Test

class BonkTest {
    @Test
    fun bonk() {
        val file = File.createTempFile("bonk", ".tmp");
        Test::class.java.protectionDomain.codeSource.location.openStream().use { input ->
            Files.copy(input, file.toPath(), REPLACE_EXISTING)
            JarFile(file, true, OPEN_READ or OPEN_DELETE)
        }.use { jarFile ->
            println(jarFile.name)
            Thread.sleep(60000)
        }
    }
}
```
On Linux, this creates a read-only `JarFile` object _which no longer exists on the file system_. (Good luck tampering with that...!) It would be useful to check its behaviour on Windows too.

2022-08-16 12:50 UTC, mbrkic-r3 commented on libs/sandbox-internal/src/main/kotlin/net/corda/sandbox/internal/SandboxServiceImpl.kt
> +                throw SandboxException("File checksum validation failed for CPK ${cpk.metadata.cpkId.name} during sandbox creation")
> On Linux, this creates a read-only JarFile object which is no longer visible on the file system. (Good luck tampering with that...!)

It's easy to find file descriptor and it seems you can mess with it without any problem:

`miljenko@miljenko-XPS-15-9570 ~/p/t/corda-runtime-os (mbrkic-r3/core-4364/sandbox-cpk-verification)> ls -l /proc/3177581/fd/343
lr-x------ 1 miljenko miljenko 64 Aug 16 13:32 /proc/3177581/fd/343 -> '/tmp/bonk16014812205661914932.tmp (deleted)'
miljenko@miljenko-XPS-15-9570 ~/p/t/corda-runtime-os (mbrkic-r3/core-4364/sandbox-cpk-verification)> cat /tmp/malicious.jar > /proc/3177581/fd/343`

2022-08-16 13:59 UTC, chrisr3 commented on libs/sandbox-internal/src/main/kotlin/net/corda/sandbox/internal/SandboxServiceImpl.kt
> +                throw SandboxException("File checksum validation failed for CPK ${cpk.metadata.cpkId.name} during sandbox creation")
> It's easy to find file descriptor and it seems you can mess with it without any problem:
> 
> ```shell
> miljenko@miljenko-XPS-15-9570 ~/p/t/corda-runtime-os (mbrkic-r3/core-4364/sandbox-cpk-verification)> ls -l /proc/3177581/fd/343
> lr-x------ 1 miljenko miljenko 64 Aug 16 13:32 /proc/3177581/fd/343 -> '/tmp/bonk16014812205661914932.tmp (deleted)'
> miljenko@miljenko-XPS-15-9570 ~/p/t/corda-runtime-os (mbrkic-r3/core-4364/sandbox-cpk-verification)> cat /tmp/malicious.jar > /proc/3177581/fd/343
> ```

OK, I didn't expect that :face_with_head_bandage:. We can tweak that to:
```kotlin
Files.copy(input, file.toPath(), REPLACE_EXISTING)
file.setReadOnly()
JarFile(file, true, OPEN_READ or OPEN_DELETE)
```
although that seems only to protect against _accidental_ writing :thinking:. However, the implications of writing to files in the `/proc` filesystem like this are that _nothing_ is protected?! That can't be right either...

2022-08-17 08:47 UTC, kyriathar submitted a review, later dismissed

2022-08-17 08:48 UTC, josephzunigadaly submitted a review, later dismissed

2022-08-17 08:51 UTC, kyriathar commented
Approving based on internal communication that we decided to go in with first version which has the above issue. Maybe it would be worth registering a JIRA describing the above issue which still remains to be tackled later?

2022-08-17 09:24 UTC, mbrkic-r3 commented
> Approving based on internal communication that we decided to go with first version which has the above described issue. Maybe it would be worth registering a JIRA describing the above issue which still remains to be tackled later/ have it recorded?

Created CORE-6257

2022-08-17 09:36 UTC, chrisr3 reviewed
I think this is OK, but I do have a question about these cache files' file permissions.

2022-08-17 09:36 UTC, chrisr3 commented on libs/sandbox-internal/src/main/kotlin/net/corda/sandbox/internal/SandboxServiceImpl.kt
> +            throw SandboxException("File checksum validation failed for CPK ${cpk.metadata.cpkId.name} during sandbox creation")
Can we have `{}` for this `if` please?

2022-08-17 09:36 UTC, chrisr3 commented on libs/sandbox-internal/src/main/kotlin/net/corda/sandbox/internal/SandboxServiceImpl.kt
> +        // TODO there is a small time window between verification and installation during which CPK files might still be modified
This "time window" assumes that a user _other_ than the file owner has "write" permissions to the file, which we don't want to allow anyway. And we _can_ at least address that, e.g.:
```kotlin
import java.nio.file.StandardOpenOption.CREATE
import java.nio.file.StandardOpenOption.TRUNCATE_EXISTING
import java.nio.file.StandardOpenOption.WRITE
import java.nio.file.attribute.PosixFilePermission.OWNER_WRITE
import java.nio.file.attribute.PosixFilePermissions.asFileAttribute
import java.util.EnumSet

Files.newByteChannel(path, EnumSet.of(WRITE, CREATE, TRUNCATE_EXISTING), asFileAttribute(setOf(OWNER_WRITE)))
```
or
```kotlin
Files.newOutputStream(path, WRITE, CREATE, TRUNCATE_EXISTING)
Files.setPosixFilePermissions(path, setOf(OWNER_WRITE))
```
followed by
```kotlin
import java.nio.file.attribute.PosixFilePermission.OWNER_READ

Files.setPosixFilePermissions(path, setOf(OWNER_READ))
```
For wherever these cache files are created. Otherwise, we are at the mercy of the current `umask` value (on UNIX, anyway).

2022-08-17 09:37 UTC, chrisr3 submitted a review, later dismissed

2022-08-17 09:43 UTC, mbrkic-r3 commented on libs/sandbox-internal/src/main/kotlin/net/corda/sandbox/internal/SandboxServiceImpl.kt
> +            throw SandboxException("File checksum validation failed for CPK ${cpk.metadata.cpkId.name} during sandbox creation")
added

2022-08-17 09:52 UTC, chrisr3 approved these changes
LGTM, but we _do_ need to set explicit file permissions for these cache files.

2022-08-17 09:54 UTC, mbrkic-r3 commented
> LGTM, but we _do_ need to set explicit file permissions for these cache files.

That should be done with another JIRA ticket

2022-08-17 10:26 UTC, merged