NOTICK - Exclude unused transitive dependencies
corda/corda-runtime-os pull request #1870
Opened 2022-08-11 14:13 UTC by driessamyn

Trying to exclude Protobuf and Wicket as transitive dependencies from the kryo serialiser as they are not needed.

2022-08-11 16:17 UTC, JamesHR3 approved these changes

2022-08-11 16:48 UTC, chrisr3 requested changes
I don't think this has done what you were intending :cry:.

2022-08-11 16:48 UTC, chrisr3 commented on libs/serialization/serialization-kryo/build.gradle
> +}
Do you realise that this `kryo-serializers` project is only converting the third party `kryo-serializers` jar into a `kryo-serializers` bundle? The final POM should only have this dependency:
```
api "com.esotericsoftware:kryo:$kryoVersion"
```
In other words, there should be nothing to exclude here because we only introduced `wicket` and `protobuf-java` as `compileOnly` dependencies. In fact, I can confirm this:
```xml
  <dependencies>
    <dependency>
      <groupId>com.esotericsoftware</groupId>
      <artifactId>kryo</artifactId>
      <version>4.0.2</version>
      <scope>compile</scope>
    </dependency>
  </dependencies>
```
But more importantly, you haven't changed the byte-code inside this jar in any way. All you have done is prevent Bnd from generating correct OSGi metadata for some of its package imports:
- com.google.protobuf;resolution:=optional;version="[3.6,4)" -> com.google.protobuf
- org.apache.wicket.util.collections;resolution:=optional;version="[1.4,2)" -> org.apache.wicket.util.collections

and I'm not sure that was your intention either.

2022-08-11 16:48 UTC, mnesbit approved these changes
Not my favourite way to fix this, but good enough as a tactial

2022-08-11 16:50 UTC, chrisr3 commented
> Not my favourite way to fix this, but good enough as a tactical

I'm not seeing a "fix" here. All I'm seeing is broken OSGi metadata for the exact same byte-code contents.

2022-08-11 17:10 UTC, chrisr3 commented
Ah yes, here is the **real** reason why we are creating our own `kryo-serializers` bundle:
```
Import-Package: \
    com.google.common.collect;resolution:=optional;version='[17.0,\${versionmask;+;\${project.guavaOsgiVersion}})',\
```
We are creating one whose OSGi metadata includes our own version of Guava... :construction_worker_man:.

2022-08-11 17:16 UTC, chrisr3 commented
Try running this instead:
```
$ ./gradlew snyk-test -PsnykSeverity=high -PsnykArguments="-sub-project=kryo-serializers --configuration-matching='^runtimeClasspath\$'"
```
You seem to have an API key, whereas I do not.

2022-08-12 08:26 UTC, driessamyn commented on libs/serialization/serialization-kryo/build.gradle
> +}
@ronanbrowne, what do you think ^ ?

@chrisr3's suggestion seems reasonable. I'm happy to throw away this change if the snyk report was resolved differently. My aim was purely to reduce noise on this report and avoid what I'm sure would be an endlessly repeated discussion about why this can or should be waived every time we do a release.

2022-08-12 09:48 UTC, chrisr3 commented on libs/serialization/serialization-kryo/build.gradle
> +}
Snyk seems to work by scanning the contents of all Gradle configurations, but without any understanding of what the project is trying to achieve. This `:libs:serialization:kryo-serializers` sub-project is rewriting the OSGi metadata for:
```
de.javakaffee:kryo-serializers:$kryoSerializerVersion
```
so that it will resolve against our version of Guava. It also drops the original artifact's transitive dependencies on anything other than Kryo itself. Corda then uses the build artifact from `:libs:serialization:kryo-serializers` everywhere else, so Snyk can only be complaining about "ephemeral build garbage" in this sub-project's `compileClasspath` configuration :shrug:.

If there are references to `wicket` and `protobuf-java` in sub-projects _other_ than `:libs:serialization:kryo-serializers` then that _would_ be a problem, of course.

2022-08-15 09:40 UTC, ronanbrowne commented
Just catching up on this now - got lost among a sea of GH notifications - @chrisr3 Sure I agree we can look to tighten up what's actually monitored here, Let me have a look at the jobs which actually send data to the Snyk server to create our baseline and do some testing regarding what actual class path we are scanning

2022-08-19 16:33 UTC, ronanbrowne commented
FYI @chrisr3  / @driessamyn / @mnesbit  Snyk scanning has been updated to scan the runtime classpath of corda-runtime-os and as such the issues which were being addressed in this JIra are no longer flagged.

2022-08-19 16:37 UTC, chrisr3 commented
> FYI @chrisr3 / @driessamyn / @mnesbit Snyk scanning has been updated to scan the runtime classpath of corda-runtime-os and as such the issues which were being addressed in this JIra are no longer flagged.

Thanks. Is this for every subproject, or just for this particular one?

2022-08-19 17:02 UTC, ronanbrowne commented
> > FYI @chrisr3 / @driessamyn / @mnesbit Snyk scanning has been updated to scan the runtime classpath of corda-runtime-os and as such the issues which were being addressed in this JIra are no longer flagged.
> 
> Thanks. Is this for every subproject, or just for this particular one?

Every one @chrisr3

2022-09-02 09:38 UTC, driessamyn commented
Closing this PR as this has been resolved by ensuring Snyk only scans `runtimeClasspath`.

2022-09-02 09:38 UTC, closed without merging