INFRA-1843 update tagging for arm64 arch
corda/corda-runtime-os pull request #1894
Opened 2022-08-15 13:12 UTC by ronanbrowne

Enabler piece for the production of arch64 images, we need to ensure we do not override existing arm images

- WIP while testing further

2022-08-16 10:30 UTC, mcgovc submitted a review, later dismissed
LGTM

2022-08-16 14:09 UTC, wzur-r3 requested changes

2022-08-16 14:09 UTC, wzur-r3 commented on .ci/nightly/JenkinsfileNightlyARM64
> +    publishPreTestImage: true, // change this to true when images don't overwrite AMD64 ones
```suggestion
    publishPreTestImage: true,
```

2022-08-16 17:45 UTC, yarivus reviewed
LGTM

2022-08-17 08:35 UTC, mcgovc submitted a review, later dismissed
LGTM

2022-08-17 09:23 UTC, yarivus reviewed
LGTM

2022-08-17 10:21 UTC, mcgovc submitted a review, later dismissed

2022-08-17 11:52 UTC, wzur-r3 approved these changes
LGTM

2022-08-17 12:14 UTC, merged

2022-08-17 13:19 UTC, yarivus reviewed
LGTM