CORE-5011 Add support for soak test Java thread/heap/OOM dumps and YourKit profiling
corda/corda-runtime-os pull request #1901
Opened 2022-08-15 14:45 UTC by oscardalmau-r3

Tickets involved:
https://r3-cev.atlassian.net/browse/CORE-5011
https://r3-cev.atlassian.net/browse/CORE-4990
https://r3-cev.atlassian.net/browse/CORE-4991
https://r3-cev.atlassian.net/browse/CORE-4992
https://r3-cev.atlassian.net/browse/CORE-5078

- Add pod **security context** function in helpers:
    - Required to grant access to the pod to create the log files for the java dumps and application profiling.
    - When profiling is enabled on the workers or _dumpHostPath_ is defined, the pod user will be root instead of 1000.

- Update **volumeMounts** and **volumes** functions:
    -  When _dumpHostPath_ is defined, it triggers the setting up of a _/dumps_ mount path on all of the workers and a hostPath volume on the desired path.

- Update worker templates files to use the functions mentioned above and to expose the profiling port when enabled.

- Update **workerEnv** function:
    -  Include additional JAVA TOOL OPTIONS for enabling JVM dump on OOM.
    - Update JAVA TOOL OPTIONS _agentpath_ value to include _dir_ and _logDir_ flags when _dumpHostPath_ is defined,

2022-08-25 15:35 UTC, oscardalmau-r3 commented on charts/corda/templates/_helpers.tpl
> +      -XX:HeapDumpPath=/dumps/heap
@davidcurrie should the HeapDumpPath for OOM and "normal" JVM heap dump be the same? or should this one be "/dumps/oom-heap"?

2022-08-25 15:39 UTC, davidcurrie commented on charts/corda/templates/_helpers.tpl
> +      -XX:HeapDumpPath=/dumps/heap
I think `/heap` is fine for both.

2022-08-25 15:53 UTC, davidcurrie commented on charts/corda/templates/_helpers.tpl
> +{{- if and ( not .Values.dumpHostPath ) ( not ( get .Values.workers .worker ).profiling.enabled ) }}
I think we only need to check `dumpHostPath` here. If profiling is enabled but it's only writing inside the container then we can stick with the default security context.

2022-08-25 15:53 UTC, davidcurrie commented on charts/corda/templates/_helpers.tpl
> +    {{- end -}}
I'd always just set `dir` and `logdir` to use those directories under `/dumps`. If there's no mount on `/dumps` that's fine - we'll just write to that location inside the container.

2022-08-25 15:53 UTC, davidcurrie commented on charts/corda/values.yaml
> +# Dump host path configuration
```suggestion
# -- Path on Kubernetes hosts to mount on Corda workers for collecting dumps
```

2022-08-25 15:53 UTC, davidcurrie commented on charts/corda/values.yaml
> +# Enables capturing JVM heap memory dump from unexpectedly terminated pods
```suggestion
# -- Enables capturing JVM heap dumps from Corda workers on an OutOfMemory error

```

2022-08-25 15:53 UTC, davidcurrie commented on gradle.properties
> +enableProfiling=true
Don't forget... 😄

2022-08-25 16:17 UTC, oscardalmau-r3 commented on charts/corda/templates/_helpers.tpl
> +{{- if and ( not .Values.dumpHostPath ) ( not ( get .Values.workers .worker ).profiling.enabled ) }}
We need this in both cases. When profiling is enabled and we set dir and logdir in the agentpath, it fails if the pod user don't have access to create directories within the container.

2022-08-25 16:17 UTC, oscardalmau-r3 commented on charts/corda/templates/_helpers.tpl
> +    {{- end -}}
Makes sense

2022-08-25 16:17 UTC, oscardalmau-r3 commented on gradle.properties
> +enableProfiling=true
Will remove this before merging, want to test a soak test deployment with this enabled first.

2022-08-25 16:19 UTC, davidcurrie commented on charts/corda/templates/_helpers.tpl
> +{{- if and ( not .Values.dumpHostPath ) ( not ( get .Values.workers .worker ).profiling.enabled ) }}
That's something we fix but not under this PR.

2022-08-25 16:23 UTC, oscardalmau-r3 commented on charts/corda/templates/_helpers.tpl
> +{{- if and ( not .Values.dumpHostPath ) ( not ( get .Values.workers .worker ).profiling.enabled ) }}
Yeah agree, we tried using _privileged_ but didn't work. We probably need to take a look at the Dockerfile to fix this and do it the proper way.

2022-08-26 07:40 UTC, davidcurrie requested changes
One tiny change otherwise LGTM

2022-08-26 07:40 UTC, davidcurrie commented on charts/corda/values.yaml
> +
My fault... the GitHub suggestions always try to add an extra newline...
```suggestion
```

2022-08-26 09:45 UTC, davidcurrie submitted a review, later dismissed
👍 LGTM

2022-08-26 10:34 UTC, davidcurrie commented on charts/corda/templates/_helpers.tpl
> +
I'd just take the quotes out of `corda.workerName` and change the existing places it is used to `{{ include "corda.workerName" . | quot }}`

2022-08-26 10:34 UTC, davidcurrie commented on gradle.properties
> +      oerviceAccountName: privileged
don't think this should be here!

2022-08-26 10:45 UTC, davidcurrie approved these changes, later dismissed
👍

2022-08-26 10:49 UTC, davidcurrie approved these changes

2022-08-26 11:19 UTC, merged