CORE-6307/Multiple corda clusters
corda/corda-runtime-os pull request #1924
Opened 2022-08-18 15:13 UTC by mag1c-48

Multiple cord clusters now deployed in E2E during the `deploy clusters` stage.

Each cluster has:
Shared kafka instance
Separate postgres instance
Shared namespace

Made changes to accommodate the change in the name of the helm releases - 
corda -> corda-alice, bob, caroline
prereqs-postgresql - alice-db-postgresql ...bob...caroline

Added the ability to create a separate db in the db-job if needed. Left disabled by default.

2022-08-18 16:13 UTC, ronanbrowne commented
Converting to draft until test issues resolved @charlieR3  looking at in separate branch - Note please squash commits before merge

2022-08-26 10:17 UTC, davidcurrie commented on .ci/e2eTests/Jenkinsfile
>                  withCredentials([usernamePassword(credentialsId: 'artifactory-credentials', passwordVariable: 'PASSWORD', usernameVariable: 'USER')]) {
Maybe move the `withCredentials`/`helm registry login` out into a separate stage to make it clear it's no longer being used for installing the prereqs. It's just needed for the subsequent install of the Corda chart.

2022-08-26 10:17 UTC, davidcurrie commented on .ci/e2eTests/Jenkinsfile
> +                        pgrep kubectl | xargs kill -9
glad someone's finally cleaned this up!

2022-08-26 10:17 UTC, davidcurrie commented on .ci/e2eTests/Jenkinsfile
> +    if(name.contains('prereqs-kafka')) {
Would it make more sense for this to be conditional on `portMapping` being zero? Or even just remove the default and specify a mapping (to the same value) for the Kafka case?

2022-08-26 10:17 UTC, davidcurrie commented on charts/corda/templates/db-job.yaml
> +{{- $_ := set . "job" "db" }}
This was a bit of a hack in the workers - I wouldn't replicate it here...

2022-08-26 10:17 UTC, davidcurrie commented on charts/corda/templates/db-job.yaml
> +  name: {{ include "corda.jobName" . }}
just use `"{{ include "corda.fullname" . }}-setup-db"`

2022-08-26 10:17 UTC, davidcurrie commented on charts/corda/templates/topic-job.yaml
> +  name: {{ include "corda.jobName" . }}
as above, just use `"{{ include "corda.fullname" . }}-create-topics"`

2022-08-26 10:17 UTC, davidcurrie commented on charts/corda/values.yaml
> +  create: false
if we have this option, it should be under `bootstrap` not under `db` but, as it doesn't appear to be used, can we remove it?

2022-08-26 10:17 UTC, davidcurrie commented on charts/corda/templates/db-job.yaml
> +      {{ if .Values.db.create }}
is this used any more? if not, can we delete it?

2022-08-26 10:17 UTC, davidcurrie commented on charts/corda/templates/db-job.yaml
> +          image: {{ include "corda.dbClientImage" . }}
delete?

2022-08-26 10:17 UTC, davidcurrie commented on charts/corda/templates/db-job.yaml
> +              DBNAME={{ include "corda.clusterDbName" . }}
specify as env variables on the container

2022-08-26 10:17 UTC, davidcurrie commented on charts/corda/templates/db-job.yaml
> +              if psql -h {{ required "A db host is required" .Values.db.cluster.host }} -U $DBUSER -lqt | cut -d \| -f 1 | grep -qw $DBNAME; then
prefer to avoid embedded variables into scripts - set the host via another env variable

2022-08-26 10:17 UTC, davidcurrie commented on charts/corda/templates/db-job.yaml
> +                psql -h {{ required "A db host is required" .Values.db.cluster.host }} -U $DBUSER -c "CREATE DATABASE $DBNAME WITH OWNER='$DBUSER' ENCODING='UTF8'" postgres
should `postgres` at the end here not be `$DBUSER` again?

2022-08-26 10:17 UTC, davidcurrie commented on .ci/e2eTests/Jenkinsfile
> +                  }
extract repeated code as another function?

2022-08-26 10:17 UTC, davidcurrie commented on .ci/e2eTests/Jenkinsfile
> +                        helm install prereqs bitnami/kafka -f ./.ci/e2eTests/kafka.yaml -n $NAMESPACE --wait --timeout 600s
we could still use the `corda-dev` Helm chart and just disable the the postgres sub-chart

2022-08-26 10:17 UTC, davidcurrie commented on .ci/e2eTests/Jenkinsfile
> +                            helm install alice-db bitnami/postgresql -f ./.ci/e2eTests/postgres.yaml -n $NAMESPACE --wait --timeout 600s
we could still use the `corda-dev` Helm chart and just disable the the kafka sub-chart

2022-08-26 10:44 UTC, yarivus requested changes
Aligned w/ @davidcurrie 's comments

2022-08-26 11:14 UTC, ronanbrowne commented on .ci/e2eTests/Jenkinsfile
> +                    def clusters = ['alice','bob','caroline'] // parameratize fuck you
Forced Pushed to remove this from history - Removing this comment for sanity reasons

2022-08-26 13:06 UTC, ronanbrowne commented
Putting back to draft, comments to be addressed next week

2022-09-05 08:50 UTC, mag1c-48 commented on .ci/e2eTests/Jenkinsfile
> +                        helm install prereqs bitnami/kafka -f ./.ci/e2eTests/kafka.yaml -n $NAMESPACE --wait --timeout 600s
If you think that makes more sense I could switch to doing that, however I'd first like to ask what is the benefit over just using the bitnami charts, as I am not too familiar with our own corda-dev chart yet

2022-09-05 08:51 UTC, mag1c-48 commented
Back from first the holiday and then the sick leave, so now I will be taking a look at all of the comments 😄

2022-09-05 09:23 UTC, davidcurrie commented on .ci/e2eTests/Jenkinsfile
> +                        helm install prereqs bitnami/kafka -f ./.ci/e2eTests/kafka.yaml -n $NAMESPACE --wait --timeout 600s
It would save replicating the overrides (`kafka.yaml` and `postgres.yaml`) from the corda-dev chart into this repo.

2022-09-05 09:56 UTC, mag1c-48 commented on .ci/e2eTests/Jenkinsfile
> +                        helm install prereqs bitnami/kafka -f ./.ci/e2eTests/kafka.yaml -n $NAMESPACE --wait --timeout 600s
okay I see your point, I'll do it this way then

2022-09-05 14:51 UTC, mag1c-48 commented on .ci/e2eTests/Jenkinsfile
> +                  }
extracted into deployCorda function

2022-09-05 15:25 UTC, yarivus reviewed
LGTM

2022-09-05 16:06 UTC, mag1c-48 commented on .ci/e2eTests/Jenkinsfile
> +                        helm install prereqs bitnami/kafka -f ./.ci/e2eTests/kafka.yaml -n $NAMESPACE --wait --timeout 600s
using the corda-dev chart again

2022-09-05 16:15 UTC, yarivus reviewed
LGTM

2022-09-05 16:51 UTC, mag1c-48 commented on .ci/e2eTests/Jenkinsfile
>                  withCredentials([usernamePassword(credentialsId: 'artifactory-credentials', passwordVariable: 'PASSWORD', usernameVariable: 'USER')]) {
As we have moved back to using the corda-dev chart the login is once again required so I have kept it in

2022-09-05 16:51 UTC, mag1c-48 commented on charts/corda/templates/db-job.yaml
> +{{- $_ := set . "job" "db" }}
Understood, I've removed it and replaced the name with corda.fullname as advised below

2022-09-05 17:11 UTC, mag1c-48 commented on charts/corda/templates/db-job.yaml
> +                psql -h {{ required "A db host is required" .Values.db.cluster.host }} -U $DBUSER -c "CREATE DATABASE $DBNAME WITH OWNER='$DBUSER' ENCODING='UTF8'" postgres
Good catch, I've changed this now

2022-09-06 12:32 UTC, mag1c-48 commented on charts/corda/templates/db-job.yaml
> +              if psql -h {{ required "A db host is required" .Values.db.cluster.host }} -U $DBUSER -lqt | cut -d \| -f 1 | grep -qw $DBNAME; then
I've actually removed this alltogether as the create-db init container was originally used when we wanted to keep the same DBMS however now that each cluster has their own DBMS this was no longer needed

2022-09-06 16:19 UTC, ronanbrowne commented on .ci/e2eTests/Jenkinsfile
> +    if(name.contains('prereqs-kafka')) {
Resolved

2022-09-06 16:26 UTC, yarivus reviewed
LGTM

2022-09-07 07:57 UTC, davidcurrie reviewed
Nearly there! A couple of new comments and then a couple of earlier comments that were unresolved.

2022-09-07 07:57 UTC, davidcurrie commented on .ci/e2eTests/Jenkinsfile
> +                      }
nit: if you're passing this through to `deployCorda` as a parameter, does it need to be an environment variable set in a `script` block any more?

2022-09-07 07:57 UTC, davidcurrie commented on .ci/e2eTests/Jenkinsfile
> +                        kubectl logs -lapp.kubernetes.io/instance=corda-caroline -n ${NAMESPACE} --all-containers=true --prefix=true --tail=-1 >> logs.txt
Either just use a single `kubectl logs` and select on the label `app.kubernetes.io/name=corda` or, what I suspect may be more useful, send the logs for each cluster to a separate file.

2022-09-07 07:57 UTC, davidcurrie commented on .ci/e2eTests/Jenkinsfile
> +                       portForwarding("deploy/corda-$c-rpc-worker", 8886 + index+1, 8888)
Probably just my ignorance but why `8886 + index+1` vs `8887 + index`?

2022-09-07 07:57 UTC, davidcurrie commented on .ci/e2eTests/Jenkinsfile
> +                        kubectl logs -lapp.kubernetes.io/instance=corda -n ${NAMESPACE} --all-containers=true --prefix=true --tail=-1 > logs.txt
This should be collecting logs from all the clusters again.

2022-09-08 12:13 UTC, mag1c-48 commented on .ci/e2eTests/Jenkinsfile
> +                      }
I could remove the `.env` and just make it a variable rather than an environment variable, however this got me thinking if I could do this only once, since it should be the same for all 3 deployments, so I tried setting it as an environment variable in an environment block before the parallel stages, that didnt work, i tried setting them in another stage before the parallel stage, that didn't work either, any ideas how I could set this only once rather than 3 times?

2022-09-08 16:12 UTC, yarivus reviewed
LGTM

2022-09-08 16:53 UTC, yarivus approved these changes, later dismissed
LGTM

2022-09-09 08:59 UTC, davidcurrie reviewed
Looking good. Just a few nits...

2022-09-09 08:59 UTC, davidcurrie commented on .ci/e2eTests/Jenkinsfile
> +                      }
Did you try setting it in the environment block at the pipeline level? That's pretty much the only place I've had any luck. You could just pass `params.BUILD_REV` to `deployCorda` and put the rest of the logic in there although it seems cleaner if that function is taking the image name.

2022-09-09 08:59 UTC, davidcurrie commented on .ci/e2eTests/Jenkinsfile
> +                        kubectl logs -lapp.kubernetes.io/instance=corda-bob -n ${NAMESPACE} --all-containers=true --prefix=true --tail=-1 >> logs-bob.txt
```suggestion
                        kubectl logs -lapp.kubernetes.io/instance=corda-bob -n ${NAMESPACE} --all-containers=true --prefix=true --tail=-1 > logs-bob.txt
```

2022-09-09 08:59 UTC, davidcurrie commented on .ci/e2eTests/Jenkinsfile
> +                        kubectl logs -lapp.kubernetes.io/instance=corda-caroline -n ${NAMESPACE} --all-containers=true --prefix=true --tail=-1 >> logs-caroline.txt
```suggestion
                        kubectl logs -lapp.kubernetes.io/instance=corda-caroline -n ${NAMESPACE} --all-containers=true --prefix=true --tail=-1 > logs-caroline.txt
```

2022-09-09 08:59 UTC, davidcurrie commented on charts/corda/templates/_helpers.tpl
> +
is this now unused?

2022-09-09 10:09 UTC, mag1c-48 commented on charts/corda/templates/_helpers.tpl
> +
ah yes, good catch, its now unused ill remove it

2022-09-12 14:16 UTC, yarivus approved these changes, later dismissed
LGTM

2022-09-12 14:28 UTC, davidcurrie approved these changes, later dismissed
LGTM 🚀

2022-09-14 15:24 UTC, yarivus submitted a review, later dismissed
LGTM

2022-09-19 10:25 UTC, yarivus reviewed
@mag1c-48 see my questions/comments

2022-09-19 10:25 UTC, yarivus commented on .ci/e2eTests/kafka.yaml
> +  zookeeper:
Why do we have:
```
zookeeper:
  replicaCount: 3
```
twice in the file ?

2022-09-19 10:25 UTC, yarivus commented on .ci/e2eTests/postgres.yaml
> +  password:
what's the point of having an empty password field ?

2022-09-21 07:15 UTC, driessamyn submitted a review, later dismissed
The JIRA reference for this PR is wrong.

2022-09-21 10:55 UTC, mag1c-48 commented
> The JIRA reference for this PR is wrong.

fixed

2022-09-21 12:29 UTC, davidcurrie requested changes
Little bit more tidying needed...

2022-09-21 12:29 UTC, davidcurrie commented on .ci/e2eTests/Jenkinsfile
> +String k8Namespace = "run-${UUID.randomUUID().toString()}"
nit: `k8sNamespace` else it's Kubernete!

2022-09-21 12:29 UTC, davidcurrie commented on .ci/e2eTests/build.properties
> +e2eClusterARpcHost = localhost
Is this file used anywhere?

2022-09-21 12:29 UTC, davidcurrie commented on .ci/e2eTests/kafka.yaml
> +enabled: true
is this file used anywhere?

2022-09-21 12:29 UTC, davidcurrie commented on .ci/e2eTests/postgres.yaml
> +enabled: true
is this file used anywhere?

2022-09-21 12:29 UTC, davidcurrie commented on charts/corda/templates/db-job.yaml
> +      {{ if .Values.db.create }}
question still stands: can this go now?

2022-09-21 12:29 UTC, davidcurrie commented on charts/corda/templates/topic-job.yaml
> +  name: {{ include "corda.fullname" . }}
why the name change?

2022-09-21 12:29 UTC, davidcurrie commented on charts/corda/values.yaml
> +  create: false
comment still stands

2022-09-21 12:29 UTC, davidcurrie commented on gradle.properties
> +enableProfiling=true
this should stay as `false`

2022-09-21 16:15 UTC, yarivus reviewed
see comments @mag1c-48

2022-09-21 16:15 UTC, yarivus commented on .ci/e2eTests/build.properties
> +e2eClusterARpcHost = localhost
shouldn't it be used in the previous Jenkinsfile ?

2022-09-22 09:28 UTC, mag1c-48 commented on .ci/e2eTests/build.properties
> +e2eClusterARpcHost = localhost
deleted the file, as unfortunately it didnt work as needed

2022-09-22 09:28 UTC, mag1c-48 commented on .ci/e2eTests/kafka.yaml
> +enabled: true
deleted

2022-09-22 09:28 UTC, mag1c-48 commented on .ci/e2eTests/postgres.yaml
> +enabled: true
deleted

2022-09-22 09:30 UTC, mag1c-48 commented on charts/corda/templates/topic-job.yaml
> +  name: {{ include "corda.fullname" . }}
one of the merges i did mustve brought this back to that name

2022-09-22 09:31 UTC, mag1c-48 commented
Sorry folks, one of the rebases i did must have brought back some of the issues i fixed earlier

2022-09-22 09:38 UTC, yarivus approved these changes, later dismissed
LGTM

2022-09-22 09:46 UTC, yarivus submitted a review, later dismissed
LGTM

2022-09-22 10:16 UTC, davidcurrie approved these changes, later dismissed
LGTM!

2022-09-22 13:35 UTC, yarivus submitted a review, later dismissed
LGTM - can we merge this @mag1c-48 / @davidcurrie ?

2022-09-22 13:41 UTC, davidcurrie submitted a review, later dismissed
Merge away once green!

2022-09-22 16:15 UTC, yarivus approved these changes, later dismissed
LGTM

2022-09-22 17:43 UTC, mag1c-48 commented
> LGTM - can we merge this @mag1c-48 / @davidcurrie ?

Would love to but some rpc tests are still failing on a read time out / internal server errors

2022-09-23 09:59 UTC, yarivus reviewed
LGTM

2022-09-23 11:34 UTC, yift-r3 commented on .ci/e2eTests/Jenkinsfile
> +                    portForwarding("prereqs-kafka-0", 9092,9092)
Do we need this?

2022-09-23 11:34 UTC, yift-r3 commented on .ci/e2eTests/Jenkinsfile
> +                       portForwarding("deployment/corda-alice-$w", 7001 + index, 7000)
Alice will map to 8887, and Bob will map to 8888. I think we use this to check the status of the cluster that we talk on 8888 later, so it should probably be bob.

2022-09-23 11:34 UTC, yift-r3 commented on applications/workers/release/rpc-worker/build.gradle
> +def setE2eClusterConfig = { Task testTask, String envVarName, String propName ->
Is this used?

2022-09-23 11:39 UTC, charlieR3 commented on applications/workers/release/rpc-worker/build.gradle
> +def setE2eClusterConfig = { Task testTask, String envVarName, String propName ->
Probably not used after your changed removed the need for mine.

2022-09-23 12:11 UTC, mag1c-48 commented on applications/workers/release/rpc-worker/build.gradle
> +def setE2eClusterConfig = { Task testTask, String envVarName, String propName ->
do you wanna remove it @charlieR3 or should i

2022-09-23 12:12 UTC, mag1c-48 commented on .ci/e2eTests/Jenkinsfile
> +                    portForwarding("prereqs-kafka-0", 9092,9092)
the release branch forwards kafka 9092:9092 so i assume its used in someones test somewhere

2022-09-23 12:19 UTC, davidcurrie commented on .ci/e2eTests/Jenkinsfile
> +                    portForwarding("prereqs-kafka-0", 9092,9092)
this *may* be a hangover from my previous attempt at exposing Kafka for the P2P team which didn't cut it so possible it can be removed for now

2022-09-23 12:26 UTC, mag1c-48 commented on .ci/e2eTests/Jenkinsfile
> +                       portForwarding("deployment/corda-alice-$w", 7001 + index, 7000)
sure no problem

2022-09-23 12:29 UTC, mag1c-48 commented on applications/workers/release/rpc-worker/build.gradle
> +def setE2eClusterConfig = { Task testTask, String envVarName, String propName ->
i've removed it

2022-09-23 12:37 UTC, yarivus approved these changes
LGTM

2022-09-23 13:06 UTC, benmcmahon100 approved these changes

2022-09-23 13:19 UTC, benmcmahon100 requested changes
In the mid to long term, I think there are a few more enhancements we need to do here, but at this stage, it'd be nice to get this in and start testing this style of deployment.

A few concerns I'd have:
 - all the tests are targeted against the A cluster, but I think we could split the smoke tests to the B one to try and take some of the pressure off. I suspect that will be a faster net build time.
 - I'm worried about the scaling of the backing cluster when this is being used to test all PRs, especially considering the number of people using the same cluster across multiple teams.
 - It'd be nice to run some stress testing on this, and to try and validate what the "correct" number of kafka brokers is for the 3 clusters. Right now, we think 3 is too few, and 7 works.

Right now, I'd suggest merging this to a feature branch and exercising it a lot before making every PR gate rely on this.

2022-09-23 14:00 UTC, mag1c-48 commented
New Jira issues have been created as per your concerns and as discusses @benmcmahon100 under CORE-6036 , this Jira is finished however the PR will stay here and for the subsequent stories they should branch off of this branch and when everything is complete is when this branch should be merged.

2022-09-23 14:50 UTC, dimosr commented
Sorry to jump out of the blue here. But, I just wanted to stress a bit the fact that these tests are the only tests that are exercising all the cross-cluster dynamic network & p2p messaging functionality and it would be get to get them integrated with CI in as soon as possible to avoid people introducing regressions without them knowing.

Agree with everything that Ben pointed out, but I think it would be good to differentiate between things that are optimisations/refinements and things that are needed to ensure that making this a gate won't cause stability issues, so that we don't wait for all this work to complete before we can merge this in the main branch (but only the latter part).

2022-09-23 14:54 UTC, davidcurrie commented
I suggested to @mag1c-48 that we should look to get this merged with the additional clusters/tests behind a flag and then we can gradually increase the scenarios in which we enable them e.g. starting with just builds on the release branch and working out from there.

2022-09-27 08:44 UTC, ronanbrowne commented
Discussed this on the team and we're going to merge this today and monitor infra stability - this will be a time of low infra traffic with CordaCon ongoing

2022-09-27 12:22 UTC, benmcmahon100 approved these changes

2022-09-27 12:25 UTC, ronanbrowne approved these changes

2022-09-27 13:10 UTC, davidcurrie approved these changes
LGTM

2022-09-27 13:17 UTC, merged