NOTICK - fix concurrency issue with linked list in smoke tests
corda/corda-runtime-os pull request #1933
Opened 2022-08-22 10:45 UTC by conalsmith-r3

2022-08-22 16:44 UTC, conalsmith-r3 commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/websocket/client/MessageQueueWebSocketHandler.kt
> +        get() = ArrayList(_messageQueue)
Maybe you're right Chris might not be able to use ArrayList constructor -
```
Constructs a list containing the elements of the specified collection, in the order they are returned by the collection's iterator.
```
if its iterating over the elements

2022-08-23 22:58 UTC, chrisr3 requested changes
This is OK, _but_ AssertJ should still be able to use this API in the obvious way, because that is what everyone else will expect.

2022-08-23 22:58 UTC, chrisr3 commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/websocket/FlowStatusFeedSmokeTest.kt
> +                assertThat(wsHandler.messageQueueSnapshot.size).isEqualTo(3)
Actually, I prefer
```kotlin
assertThat(wsHandler.messageQueue).hasSize(3)
```
on the basis that the API _should not_ break when used like this.

2022-08-23 22:58 UTC, chrisr3 commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/websocket/FlowStatusFeedSmokeTest.kt
> +                    assertThat(wsHandler2.messageQueueSnapshot.size).isEqualTo(3)
Again, I think rewriting the tests like this is _avoiding_ the problem rather than resolving it.

2022-08-23 22:58 UTC, chrisr3 commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/websocket/client/MessageQueueWebSocketHandler.kt
> +    private val _messageQueue = CopyOnWriteArrayList<String>()
This is hopefully enough not to break under AssertJ too :+1:

2022-08-24 10:34 UTC, chrisr3 reviewed
Patience may be a virtue, but you can still wait "too much" :wink:.

2022-08-24 10:34 UTC, chrisr3 commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/websocket/FlowStatusFeedSmokeTest.kt
>              }
So many uses of `eventually`! I would have thought that once the message queue satisfies `hasSize(1)` then all of the other assertions about the queue's contents would follow automatically :thinking:

2022-08-24 10:34 UTC, chrisr3 commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/websocket/FlowStatusFeedSmokeTest.kt
>          }
Isn't this enough?
```kotlin
eventually {
    assertThat(wsHandler1.messageQueueSnapshot).hasSize(1)
}
assertThat(wsHandler1.messageQueueSnapshot[0]).contains(FlowStates.COMPLETED.name)
```
```

2022-08-24 10:34 UTC, chrisr3 commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/websocket/FlowStatusFeedSmokeTest.kt
>          }
Similar to above. You only need to wait for the contents to _arrive_.

2022-08-24 11:00 UTC, conalsmith-r3 commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/websocket/FlowStatusFeedSmokeTest.kt
>              }
Yeah you're right, I've removed a few extra eventually blocks which aren't needed. Each block waits 100ms before first poll so we've shaved off about half a second here

2022-08-24 15:34 UTC, conalsmith-r3 reviewed
Hi @chrisr3 I think I'm satisfied with the changes now, could you please check that you're satisfied all required changes have been addressed and if so approve the PR so we can get this change merged?

2022-08-24 15:38 UTC, chrisr3 approved these changes
LGTM :+1:

2022-08-24 15:41 UTC, merged