CORE-5375vnode db reset
corda/corda-runtime-os pull request #1943
Opened 2022-08-23 21:54 UTC by benmcmahon100

2022-08-23 21:54 UTC, benmcmahon100 commented
Initial impl to test out structure. Not expecting tests and detekt to pass yet

2022-08-25 16:07 UTC, conalsmith-r3 reviewed
Some initial comments. Would be good to get @vkolomeyko opinion here.

Will be interesting to see how to e2e test this, maybe a flow that persists some object to the database and force upload a change and assert the new object persists and old object doesn't persist - possibly this scenario can't be tested yet.

2022-08-25 16:07 UTC, sprintengine commented on components/chunking/chunk-db-write/src/main/kotlin/net/corda/chunking/db/ChunkDbWriterFactory.kt
> +        virtualNodeSender: VirtualNodeSender
Probably should rename this interface to `VirtualNodeManagementSender`, and the factory `VirtualNodeManagementSenderFactory`.

2022-08-25 16:07 UTC, sprintengine commented on components/chunking/chunk-read-service-impl/build.gradle
> +    implementation project(':components:virtual-node:virtual-node-rpcops-common')
We could probably rename this module to `virtual-node-management-sender`, rpcops doesn't have anything to do with this module, and then it'll make more sense when people see virtual-node-management-sender they'll know what this dependency is for.

2022-08-25 16:07 UTC, sprintengine commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/validation/CpiValidatorImpl.kt
> +        val nodes = virtualNodeInfoReadService.getAll().filter { it.holdingIdentity.groupId == groupId }
You could extract these bits out into a few functions to improve readability e.g. setVnodesIntoMaintenance and resetVnodeDbs

2022-08-25 16:07 UTC, sprintengine commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/validation/CpiValidatorImpl.kt
> +                    VirtualNodeStateChangeRequest(
Wonder if we should change this `VirtualNodeStateChangeRequest` to take a list of holdingIdentities so it updates them all a bit more atomically. There would also be less overhead than sending one message per identity.

2022-08-25 16:07 UTC, sprintengine commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/validation/CpiValidatorImpl.kt
> +            val resetResponse = virtualNodeSender.sendAndReceive(
same here, probably `VirtualNodeDBResetRequest` should have a list of holding identities since we're updating vnode for all holding identities in a group

2022-08-25 16:07 UTC, sprintengine commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/validation/CpiValidatorImpl.kt
> +            nodes.forEach {
we should be able to extract the setting maintenance mode and resetting vnodeDb to a couple of fuinctions to improve readability - `setVnodeStatus(ACTIVE)` and `resetVnodeDb(list<holdingIds>)`

2022-08-25 16:07 UTC, sprintengine commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/validation/CpiValidatorImpl.kt
> +        val nodes = virtualNodeInfoReadService.getAll().filter { it.holdingIdentity.groupId == groupId }
Probably could add function to the virtualNodeInfoReadService API to getVnodesInGroup, will we reuse it elsewhere?

2022-08-25 16:07 UTC, sprintengine commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/validation/CpiValidatorImpl.kt
> +    @Suppress("ForbiddenComment", "ComplexMethod")
Never seen ForbiddenComment before! Maybe with some extraction to functions we can get rid of the suppress

2022-08-25 16:07 UTC, sprintengine commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/validation/CpiValidatorImpl.kt
>      override fun validate(requestId: RequestId): SecureHash {
Definitely be nice to have this validator only validate and a separate class perform the updating. But happy if that's not done part of this PR

2022-08-25 16:07 UTC, sprintengine commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/validation/CpiValidatorImpl.kt
> +            if (maintenanceResponse.responseType is VirtualNodeManagementResponseFailure) {
So if one vnode fails to move into maintenance state, this will throw and all the vnodes that have been set to maintenance will be stuck there.. Maybe this could be resolved by above comment and changing a list of vnodes to maintenance in one transaction?

Or we'd have to roll back for nodes that are already put into in_maintenance before throwing. Possibly setting into maintenance should be a separate task and outside the scope of this PR to keep change surface area minimal.

2022-08-25 16:48 UTC, benmcmahon100 commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/validation/CpiValidatorImpl.kt
>      override fun validate(requestId: RequestId): SecureHash {
We've a ticket for that yeah (to the tune of refactoring the validator)

2022-08-25 16:49 UTC, benmcmahon100 commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/validation/CpiValidatorImpl.kt
> +            if (maintenanceResponse.responseType is VirtualNodeManagementResponseFailure) {
Fair

2022-08-26 09:18 UTC, benmcmahon100 commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/validation/CpiValidatorImpl.kt
> +    @Suppress("ForbiddenComment", "ComplexMethod")
It's for the TODOs, but agree it could probably be simplified

2022-08-26 09:19 UTC, benmcmahon100 commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/validation/CpiValidatorImpl.kt
> +            val resetResponse = virtualNodeSender.sendAndReceive(
Kept them individual to match the maintenance mode setting, But maybe it's worth dropping the maintenance mode change, and opening a ticket to allow mass changes of state for upgrade as a separate ticket.

2022-08-26 09:19 UTC, benmcmahon100 commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/validation/CpiValidatorImpl.kt
> +                    VirtualNodeStateChangeRequest(
Commented below

2022-08-26 09:38 UTC, benmcmahon100 commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/validation/CpiValidatorImpl.kt
> +            val resetResponse = virtualNodeSender.sendAndReceive(
https://r3-cev.atlassian.net/browse/CORE-6416

2022-08-26 09:39 UTC, benmcmahon100 commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/validation/CpiValidatorImpl.kt
>      override fun validate(requestId: RequestId): SecureHash {
https://r3-cev.atlassian.net/browse/CORE-6205

2022-08-26 09:40 UTC, benmcmahon100 commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/validation/CpiValidatorImpl.kt
> +            if (maintenanceResponse.responseType is VirtualNodeManagementResponseFailure) {
Same as the ticket related to bulk state operation https://r3-cev.atlassian.net/browse/CORE-6416

2022-08-26 17:16 UTC, benmcmahon100 commented
> Will be interesting to see how to e2e test this, maybe a flow that persists some object to the database and force upload a change and assert the new object persists and old object doesn't persist - possibly this scenario can't be tested yet.

I think like you say, that's not something we can currently test without the finalized ledger, but maybe we could have a CPI with a migration, do reset, and validate the "same" CPI with an entirely different migration can apply.

Should be doable with something like changing a VARCHAR to a BIGINT

2022-08-30 11:05 UTC, vkolomeyko reviewed
I have done first pass of the review with few comments posted.

I would like footprint of the changes reduced to the bare minimum to achieve required functionality. We could do module moves and renamings as follow-up PRs to follow.

I have not yet checked out the branch to do more thorough code review.

2022-08-30 11:05 UTC, vkolomeyko commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/virtualnode/helpers/ClusterBuilder.kt
> +            client!!.postMultiPart(cmd, mapOf("resetDb" to "true"), mapOf("upload" to HttpsClientFileUpload(it, fileName)))
Do we need to pass it from the client? IMO by default when not specified `resetDb` should be `true`.
Also `uploadCpiResource` is a regular CPI upload, so this property should not be important?

2022-08-30 11:05 UTC, vkolomeyko commented on components/chunking/chunk-db-write-impl/build.gradle
> +    implementation project(':libs:http-rpc:http-rpc-common')
I wonder why would we need dependency on HTTP RPC module here?

2022-08-30 11:05 UTC, vkolomeyko commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/validation/CpiValidatorImpl.kt
> +                    // TODO: It might make a lot of sense to have a "why field" here
I am a bit concerned about leaving these `TODO` items. Also, should `VirtualNodeDBResetRequest` only be sent in case of Force CPI upload?

2022-08-30 11:05 UTC, vkolomeyko commented on components/chunking/chunk-read-service-impl/src/main/kotlin/net/corda/chunking/read/impl/ChunkReadServiceImpl.kt
> +        private const val REGISTRATION = "REGISTRATION"
TBH, I would not do this change in this PR as this is Lifecycle change may have side effects.

Let's pass `virtualNodeManagementSenderFactory` and use it with minimal change to this file.

2022-08-30 11:05 UTC, vkolomeyko commented on components/virtual-node/virtual-node-management-sender/build.gradle
> +description "Virtual Node RPC Ops Virtual Node Management Sender"
Do we need to make this module move as part of this PR?

I.e. can we do it later on as a separate PR if necessary?

2022-08-30 11:05 UTC, vkolomeyko commented on components/virtual-node/virtual-node-management-sender/src/main/kotlin/net/corda/virtualnode/rpcops/virtualNodeManagementSender/VirtualNodeManagementSender.kt
> +interface VirtualNodeManagementSender : AutoCloseable {
Again, I propose we stick with `VirtualNodeSender` for now to limit the footprint of the changes and if we need to introduce `VirtualNodeManagementSenderFactory` - we can do it as a separate PR.

2022-08-30 11:05 UTC, vkolomeyko commented on libs/virtual-node/virtual-node-endpoints-maintenance/src/main/kotlin/net/corda/libs/virtualnode/maintenance/endpoints/v1/VirtualNodeMaintenanceRPCOps.kt
> +    fun forceCpiUpload(upload: HttpFileUpload, resetDb: String = "true"): CpiUploadRPCOps.CpiUploadResponse
In Jira description it says "The goal is to introduce an addition optional query parameter". Let's annotate `resetDb` with `HttpRpcQueryParameter` which will permit passing the `default` value.

2022-08-30 11:05 UTC, vkolomeyko commented on components/virtual-node/virtual-node-rpcops-service-impl/src/main/kotlin/net/corda/virtualnode/rpcops/impl/v1/VirtualNodeRPCOpsImpl.kt
> +        @Reference(service = VirtualNodeManagementSenderFactory::class)
Again, let's save those refactorings for a separate PR.

2022-08-30 11:05 UTC, vkolomeyko commented on processors/rpc-processor/src/integrationTest/resources/swaggerBaseline.json
> +                  "resetDb" : {
As discussed, this needs to be an optional query parameter.

2022-09-01 11:49 UTC, conalsmith-r3 commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/validation/CpiValidatorImpl.kt
> +            ?: throw CordaRuntimeException("Actor is undefined for forceUpload operation $requestId")
Isn't this also for normal cpi upload operations not just force upload?

2022-09-01 12:18 UTC, benmcmahon100 commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/validation/CpiValidatorImpl.kt
> +                    // TODO: It might make a lot of sense to have a "why field" here
I can remove them. My idea was that to reduce the change footprint, I wanted to leave the audit stuff for another PR (I think there's a ticket to add audit stuff to all the virtual node code, but I've added the actor so that the change later on should be trivial.

That said, maybe you're right about the reset only being possible in the case of the forceUpload and therefore there is no other reason that'd require parameterization

2022-09-01 12:20 UTC, benmcmahon100 commented on components/chunking/chunk-read-service-impl/src/main/kotlin/net/corda/chunking/read/impl/ChunkReadServiceImpl.kt
> +        private const val REGISTRATION = "REGISTRATION"
I made this change it I think it is the smaller change overall. Add the code to manage the state of both should end up creating a larger diff overall

2022-09-01 12:26 UTC, conalsmith-r3 commented on components/virtual-node/virtual-node-management-sender/build.gradle
> +description "Virtual Node RPC Ops Virtual Node Management Sender"
Yeah I suggested a couple refactorings of the naming of this module and some of the classes in it, but I'm happy if it's done as a separate PR

2022-09-01 13:15 UTC, fowlerrr reviewed
Looks okay.  Some small comments if you want to keep the managed resources changes.

2022-09-01 13:15 UTC, fowlerrr commented on components/chunking/chunk-read-service-impl/src/main/kotlin/net/corda/chunking/read/impl/ChunkReadServiceImpl.kt
> +        coordinator.closeManagedResources()
This is already done for you on stop so you don't need to do it yourself.  We should probably update the API to make that clearer.  It _is_ in the kdocs but maybe I can think of a way to make it more obvious.

2022-09-01 13:15 UTC, fowlerrr commented on components/chunking/chunk-read-service-impl/src/main/kotlin/net/corda/chunking/read/impl/ChunkReadServiceImpl.kt
> +            coordinator.createManagedResource("CHUNK_DB_WRITER") {
Worth making this key a static constant?

2022-09-01 13:41 UTC, benmcmahon100 commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/validation/CpiValidatorImpl.kt
> +            ?: throw CordaRuntimeException("Actor is undefined for forceUpload operation $requestId")
Fixed that, that was a dangling comment

2022-09-01 14:09 UTC, benmcmahon100 commented on components/virtual-node/virtual-node-management-sender/build.gradle
> +description "Virtual Node RPC Ops Virtual Node Management Sender"
Pulled it out to do later for the sake of reducing this PR size

2022-09-01 14:32 UTC, benmcmahon100 commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/validation/CpiValidatorImpl.kt
> +        val nodes = virtualNodeInfoReadService.getAll().filter { it.holdingIdentity.groupId == groupId }
Resolving since the maintenance part has been dropped

2022-09-01 14:32 UTC, benmcmahon100 commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/validation/CpiValidatorImpl.kt
> +            nodes.forEach {
Making as resolved with the maintenance stuff dropped.

2022-09-01 16:37 UTC, vkolomeyko commented on components/chunking/chunk-db-write/build.gradle
> +    implementation project(':components:virtual-node:virtual-node-rpcops-common')
Since `VirtualNodeSender` is passes as a parameter should this not be `api` type dependency? As in:
```suggestion
    api project(':components:virtual-node:virtual-node-rpcops-common')
```

2022-09-01 16:37 UTC, vkolomeyko commented on components/chunking/chunk-read-service-impl/build.gradle
> +    implementation project(':components:virtual-node:virtual-node-rpcops-common')
If we do `api` dependency above, this line may not be necessary.

2022-09-02 09:19 UTC, vkolomeyko reviewed
Overall looks quite reasonable.
I have posted few comments.

As agreed with @benmcmahon100, we will not be pushing too many new changes into this PR unless absolutely necessary and will be aiming to:
1. Merge it without E2E tests;
2. As a separate Jira/PR we will add operation for retrieval of vNode AuditLog entries. Which will include DB reset operation;
3. Then we should be in position to write a good E2E test asserting on AuditLog entries post DB reset.

2022-09-02 09:19 UTC, vkolomeyko commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/validation/CpiValidatorImpl.kt
> +        val nodes = virtualNodeInfoReadService.get(groupId)
1. I would prefer moving `nodes` lookup logic further down, such that we only run this call inside `if (resetDB) {...}` clause.

2. Currently, we are performing lookup by `groupId` only. I think this criteria is too broad and may cause us to reset DBs on the unaffected nodes. I think it would be better to include CPI name and version when looking up affected nodes as well.
As discussed with @driessamyn it seems to be possible to have two distinct vNodes which belong to the same `groupId` but which have different CPIs deployed into them.

2022-09-02 09:19 UTC, vkolomeyko commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt
> +                vnodeDbFactory.createVNodeDbs(
This was looking somewhat puzzling to me, i.e. the fact that we do `create` inside `drop` call. Surely, when this method is called we do already expect DBs to be available, so there should be no need to create them.

Also, below at line 186 we call `createVNodeDbs` again.

Could we at least capture the result of `createVNodeDbs` inside `dropVirtualNodeDBs` to a `val virtualNodeDbToDrop`?

Long term, I think it would make sense to rename `createVNodeDbs` function to `getVNodeDbs` and not take `VirtualNodeCreateRequest` as a parameter to it, but have a dedicated structure for holding DDL and DML connection details.

2022-09-02 09:19 UTC, vkolomeyko commented on libs/virtual-node/virtual-node-endpoints-maintenance/src/main/kotlin/net/corda/libs/virtualnode/maintenance/endpoints/v1/VirtualNodeMaintenanceRPCOps.kt
> +            description = "Set whether we want to reset the node db when we upload the new CPI",
```suggestion
            description = "Sets whether we want to reset the node DB when we upload the new CPI. If omitted, the DB will be reset.",
```

2022-09-02 09:19 UTC, vkolomeyko commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt
> +    private fun resetVirtualNodeDB(
I think this is "meat" of the change.

I would appreciate some input from @mbrkic-r3, @dickon and @driessamyn.

2022-09-02 09:19 UTC, vkolomeyko commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/validation/CpiValidatorImpl.kt
> +            virtualNodeSender.sendAndReceive(request)
We (@corda/http-rpc) agreed to use a new pattern here for performing reset of the DB, by sending another message onto Kafka to self (DB Worker).
Since this is something I have not seen in other places wanted to bring to the attention of @driessamyn.

2022-09-02 09:25 UTC, conalsmith-r3 commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/validation/CpiValidatorImpl.kt
> +            ?: throw CordaRuntimeException("Actor is undefined for forceUpload operation $requestId")
I mean the message in the CordaRuntimeException, don't think it should reference forceUpload. Could it be something like "Actor must be provided for CPI upload operations"

2022-09-02 09:28 UTC, conalsmith-r3 commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/validation/CpiValidatorImpl.kt
> +            ?: throw CordaRuntimeException("Actor is undefined for forceUpload operation $requestId")
In fact since this is a programming bug not caused by user, perhaps replace it with requireNotNull?

```
        val actor = requireNotNull(fileInfo.actor) {
            "Actor must not be undefined for CPI operations ($requestId)"
        }
```

2022-09-02 09:42 UTC, conalsmith-r3 commented on components/chunking/chunk-read-service-impl/src/main/kotlin/net/corda/chunking/read/impl/ChunkReadServiceImpl.kt
> +        if (requiredKeys.all { it in event.config.keys } and event.keys.any { it in requiredKeys }) {
I don't think the `if` is necessary, the configurationReadService API `registerComponentForUpdates` says you'll only get the `ConfigChangedEvent` when all the required keys are present:

```
Register a component for configuration updates on a particular set of top-level keys.

This function provides a standard mechanism for components with lifecycle to receive configuration events. The
configuration read service will deliver a [ConfigChangedEvent] when a configuration update occurs, provided that
the update is for one of the [requiredKeys] and all the [requiredKeys] have been received.
```

I would remove `requiredKeys` static val, when you call `registerComponentForUpdates` declare the set of keys there, and remove the `if` in `onConfigChangedEvent`.

2022-09-02 10:48 UTC, conalsmith-r3 commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt
> +                vnodeDbFactory.createVNodeDbs(
Yes this is quite sinister looking, can only tell `createVNodeDbs` doesn't actually run any migration scripts or create schemas by looking into the code. 

I think for the sake of the reader of this code we should create private function in this class wrapping this API call and call it "getVirtualNodeDbs"

2022-09-02 10:52 UTC, benmcmahon100 commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt
> +                vnodeDbFactory.createVNodeDbs(
Yeah, so that create method does a getOrCreate type of operation essentially. This is to support the usage of externally provided DBs, which makes sense.

Let me have another look and I'll see what cleaning I can do of my change

2022-09-02 11:04 UTC, mbrkic-r3 commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeDb.kt
> +            val dbSchema = dbType.getSchemaName(holdingIdentityShortHash)
This won't work for externally provided DBs

2022-09-02 11:13 UTC, vkolomeyko commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeDb.kt
> +            val dbSchema = dbType.getSchemaName(holdingIdentityShortHash)
This is probably fine.
Force CPI upload functionality is on DevTool capacity to quickly try new code in the private cluster.
That said it is reasonably unlikely that externally provided DB will be used in this setup.

2022-09-02 11:14 UTC, driessamyn requested changes

2022-09-02 11:14 UTC, driessamyn commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeDb.kt
> +            val dbSchema = dbType.getSchemaName(holdingIdentityShortHash)
I agree with @mbrkic-r3 here. This is the wrong approach, we should not make any assumptions about that DB or the schema.

I'm also not sure that this is what you want because it would wipe any system tables, which are unrelated to the CPI, and I wouldn't expect DB users to be deleted. 
It should just remove the tables managed by the CPI so that the updated CPI DB migration can work when doing a force-upload.

2022-09-02 11:22 UTC, mbrkic-r3 commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt
> +                        DDL to it.findDbConnectionByNameAndPrivilege(VirtualNodeDbType.VAULT.getSchemaName(shortHash), DDL),
`getConnectionName` should be used here instead of `getSchemaName`

2022-09-02 11:34 UTC, driessamyn commented on components/chunking/chunk-db-write-impl/build.gradle
> +    implementation project(':components:virtual-node:virtual-node-info-read-service')
This is a bit of a red flag. 
I wouldn't expect virtual node dependencies, and certainly not RPC dependencies in the chunking component.

2022-09-02 11:34 UTC, driessamyn commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/validation/CpiValidatorImpl.kt
> +            virtualNodeSender.sendAndReceive(request)
In principle, I think the pattern is right, but looking at the code, I wonder it feels a bit wrong. CPI upload should not really have a reference to VNode. I appreciate that we're combining this with force-upload, but it starts to couple things that shouldn't.
Maybe it's be cleaner to implement it as an operation on the vnode REST endpoint and the entire "force upload and reset" experience can be orchestrated in the cli (force upload CPI first, then find all vnode and force reset all of them).

2022-09-02 11:34 UTC, driessamyn commented on components/virtual-node/virtual-node-info-read-service/src/main/kotlin/net/corda/virtualnode/read/VirtualNodeInfoReadService.kt
> +
I don't think we should have this on the API. It's a smell.
This could potentially be a very large list and I don't think we have a good usecase for finding out all vnodes in a group on a cluster.

2022-09-02 11:34 UTC, driessamyn commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt
> +                vnodeDbFactory.createVNodeDbs(
As mentioned above, I don't think dropping everything and re-creating it is the right approach. This would wipe the system tables, for example, and may have impact on things like the MGM registration.

2022-09-02 11:35 UTC, mbrkic-r3 commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt
> +                        null,
Since connections are not provided this will create them in our DB (won't work correctly if original connections were using externally provided DBs)

2022-09-02 12:34 UTC, benmcmahon100 commented on components/chunking/chunk-db-write-impl/build.gradle
> +    implementation project(':components:virtual-node:virtual-node-info-read-service')
The idea here was to try use the existing code for getting the information about the virtual nodes that need to be operated upon.
The common component at the time only had the sender that creates virtual node maintenance requests and could possibly have been called something else TBH

2022-09-02 12:39 UTC, benmcmahon100 commented
@driessamyn @mbrkic-r3 just to bring the conversation into one thread. From what you guys are saying, there are two main issues.
One is the intermingling of the CPI and virtual node operations, and Two is the wrong DBs are getting reset here. Is that correct?

My inclination is that I probably need to take another swing at it and make the reset operation it's own endpoint as Dries suggests, to prevent the coupling.

I think it might also be an easier change to validate. @vkolomeyko main issue on our end will be the time it'll take to redo it and the slightly different scope of the ticket.

Another option is just to fix the DBs that are being dropped and instead make it a standalone endpoint as a follow up task

2022-09-02 13:56 UTC, driessamyn commented
> just to bring the conversation into one thread. From what you guys are saying, there are two main issues.

I think there is an important 3rd one in that dropping the DB/Schema is not the right approach as this will wipe out system tables.
It'll probably also add complexity down the line when @relyafi implements the notary vnodes. I don't think force-updating a CPI should have side effects that aren't related to the CPI.

2022-09-02 14:02 UTC, benmcmahon100 commented
> > just to bring the conversation into one thread. From what you guys are saying, there are two main issues.
> 
> I think there is an important 3rd one in that dropping the DB/Schema is not the right approach as this will wipe out system tables. It'll probably also add complexity down the line when @relyafi implements the notary vnodes. I don't think force-updating a CPI should have side effects that aren't related to the CPI.

That's fair enough. I guess then the two outstanding things is that I guess it'll then be on the user to decide whether to reset via that separate API endpoint you've suggested, and the other one would be some pointers on how best to achieve the "reset" then. I'm not sure how one would identify custom tables in the vault/crypto schemas since a user can more or less call them whatever they want.

2022-09-02 14:13 UTC, dickon commented
In general, the user would have deployed the CPI, the liquibase migrations have run, they have a bunch of flows running and created some data and now they want to upload a new CPI. Dropping the tables would be surprising and unacceptable in some situations. I think the best thing to do is rerun the migrations. A careful user would be able to develop the CPI to  update the migrations in a backwards compatible way.  Or a user could role back the database to a snapshot before the earlier CPI uploads. 

We have to handle liquibase migrations failing in any case.

What bothers me and I think may be causing confusion is the coupling of CPI file upload with virtual node creation and lifecycle. We should think of them as separate operations.

2022-09-02 14:13 UTC, conalsmith-r3 commented on components/chunking/chunk-db-write-impl/build.gradle
> +    implementation project(':components:virtual-node:virtual-node-info-read-service')
`virtual-node-rpcops-common` is really just a badly named `virtual-node-management-sender`

2022-09-02 15:57 UTC, benmcmahon100 commented
> In general, the user would have deployed the CPI, the liquibase migrations have run, they have a bunch of flows running and created some data and now they want to upload a new CPI. Dropping the tables would be surprising and unacceptable in some situations. I think the best thing to do is rerun the migrations. A careful user would be able to develop the CPI to update the migrations in a backwards compatible way. Or a user could role back the database to a snapshot before the earlier CPI uploads.
> 
> We have to handle liquibase migrations failing in any case.
> 
> What bothers me and I think may be causing confusion is the coupling of CPI file upload with virtual node creation and lifecycle. We should think of them as separate operations.

I might have caused some confusion - the intent was that this should only be done in the case of forceUploading which is a dev only workflow. I think the other main issue is the mingling of vnode and cpi code. (funnily enough, the endpoint that triggers it is a vnode maintenance one but runs cpi code, but I digress)

I'm totally happy to split this into two endpoints. The original forceUpload one, and a new reset db endpoint. The thing I'm not confident in is how to find the custom user tables in a way that won't break as an alternative to dropping the entire schema.

If there's some functionality to retrieve those tables already that'd be amazing, but I hadn't seen anything for it.

2022-09-03 16:27 UTC, driessamyn commented
@dickon, @benmcmahon100 is right, we must not forget the usecase for this. The `force-update` (which this PR is extending) is purely a development usecase. The scenio is a developer is writing an app and want to go through a cycle of making code changes and pushing it quickly, without needing to worry about incrementing version numbers etc. 
These code changes could include DB changes, which is why the reset is needed, because Liquibase will only run migrations that haven't been migrated yet, so if the developer has just added a column to a table, for example, this will never be executed unless they version their Liquibase files (which off course is expected in "real" updates).

For this reason, @benmcmahon100, I think the best way may be to use Liquibase to roll back the DB and re-migrate. I.e. we know which files are in the CPI/CPK that is being force-uploaded, so we should be able to say "roll all these scripts back, then migrate them again".
The downside of this approach is that it may leave some tables behind in case they have, for example, removed a CPK from the CPI, but I think that would be ok as, going back to the usecase, we're only concerned about being able to run the migrations that may have some changes as part of the development cycle.
Off course it's not waterproof as somebody may rename migrations, for example, in which case they'll have to reset their dev environment, which is probably also ok.

Let's jump on a quick call to discuss if needed.

2022-09-22 13:44 UTC, conalsmith-r3 commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeEntityRepository.kt
> +    internal fun getHoldingIdentityEntity(holdingIdentityShortHash: ShortHash): HoldingIdentityEntity? {
Just a note on this for when you come back, the repository shouldn't be passing back entities, they should be translated into an object like other methods here, ideally there'd be a boundary where entity operations are within the repository so we don't end up with a pile of detached JPA entities hanging around outside transactional boundaries. 

Same for `setVirtualNodeState` we return a JPA entity but we can return a dto / lite representation of it instead. 

Reason for bringing this up: for VNode upgrade I also need a function to get the db connection details from the holding identity. I'll send you some code I write for this function

2022-09-23 12:13 UTC, benmcmahon100 commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeEntityRepository.kt
> +    internal fun getHoldingIdentityEntity(holdingIdentityShortHash: ShortHash): HoldingIdentityEntity? {
Makes sense to me. Going to close this PR in favor of redoing a more contemporary one, but will revisit this when doing the new one.

2022-09-23 12:13 UTC, closed without merging

2022-09-27 10:01 UTC, sprintengine commented on components/virtual-node/virtual-node-rpcops-common/src/main/kotlin/net/corda/virtualnode/rpcops/common/impl/VirtualNodeSenderFactoryImpl.kt
> +    private val publisherFactory: PublisherFactory
I noticed `SENDER_CONFIG` points to the old `virtual.node.creation.request` topic, we'll probably want to update this in a separate jira later.