CB-2597: PoC Use CRAFT5 in smoketests
corda/corda-runtime-os pull request #1950
Opened 2022-08-24 14:35 UTC by tlawson3

Proof of concept to see if we can use CRAFT5 in the smoketests to reduce the boilerplate code

2022-08-26 13:47 UTC, yarivus approved these changes
LGTM

2022-08-30 14:04 UTC, driessamyn requested changes

2022-08-30 14:04 UTC, driessamyn commented on build.gradle
> +        }
This duplication isn't great.
This also can't be merged in unless CRAFT 5 is available to the open source community.

2022-08-30 14:04 UTC, driessamyn commented on applications/workers/workers-smoketest/build.gradle
> +    smokeTestImplementation "r3.pqa.craft5:craft5-common:$craft5Version"
It was as concious choice that the smoketests shouldn't have any corda dependencies so that we exercise that the APIs can be consumed from a "vanilla" HTTP client and that this would be easy to do.

2022-08-30 14:16 UTC, fenryka commented
We should absolutely not be merging PoC into the main shipping branch

2022-08-30 14:16 UTC, closed without merging

2022-08-30 14:30 UTC, yarivus commented on build.gradle
> +        }
@driessamyn can you clarify which duplication ?
Please provide more details to your comment - "isn't great doesn't tell much"

2022-08-30 14:35 UTC, driessamyn commented on build.gradle
> +        }
Those 12 lines share 8 with the 12 above (sorry, did that counting by eye so may be a couple off, but hopefully you get the gist).

But it's sort of irrelevant, this should never have been approved as it breaks the open source story.

2022-08-30 14:43 UTC, abellagonzalo commented
@owenstanford