CORE-6332: enable E2E tests for ARM64 architecture
corda/corda-runtime-os pull request #1976
Opened 2022-08-30 18:56 UTC by wzur-r3

* added nodeSelector to the bootstrap jobs
* bootstrap jobs have their own bootstrap.nodeSelector in `values.yaml`,
  but failback to the `nodeSelector` used by the rest of deployments
* bootstrap jobs
* updated E2E pipeline to start workers on requested architecture
* E2E pipeline can start tests for AMD64 or ARM64 arch, selected by a
  new build parameter `BUILD_ARCH`, if not selected, default to AMD64
* fixed `sanitizedBranchName` to handle `-` at the end of branch name

2022-08-31 11:32 UTC, yarivus requested changes

2022-08-31 11:32 UTC, yarivus commented on .ci/e2eTests/Jenkinsfile
> +        E2EWORKERARCH = "${e2eArchitecture}"
Maybe more readable to have: E2E_WORKER_ARCH

2022-08-31 17:48 UTC, wzur-r3 commented
added @benmcmahon100 for Helm chart changes

2022-08-31 18:26 UTC, yarivus submitted a review, later dismissed
LGTM

2022-09-01 07:47 UTC, yarivus approved these changes
LGTM

2022-09-01 08:15 UTC, merged