A draft of the install script from s3 bucket
corda/corda-runtime-os pull request #1990
Opened 2022-09-01 11:03 UTC by pmck91

This PR is a draft

2022-09-01 11:07 UTC, benmcmahon100 reviewed
Other than the `..` I think this looks great as a first pass. We might look at using a tar instead longer term as it's actually easier to unzip. Also there are other checksums, but all something to worry about after DP2

2022-09-01 11:07 UTC, benmcmahon100 commented on tools/plugins/installScripts/s3Install.sh
> +  wget "${s3Bucket}/cliInstall..zip.md5" -O "${tempDir}/cliInstall.zip.md5"
```suggestion
  wget "${s3Bucket}/cliInstall.zip.md5" -O "${tempDir}/cliInstall.zip.md5"
```

2022-09-01 14:53 UTC, benmcmahon100 commented on tools/plugins/templateScripts/s3Install.sh
> +tempDir="/tmp/corda/cli/"
Did another pass at this and this dir won't exist.

You'll need to do 
`mkdir -p $tempDir`
Presumably this also applies for `cliHome` also

2022-09-07 10:48 UTC, benmcmahon100 approved these changes

2022-09-07 10:52 UTC, vkolomeyko reviewed
Looks fine to me, few minor comments posted.

2022-09-07 10:52 UTC, vkolomeyko commented on tools/plugins/build.gradle
> +tasks.register("cleanDir", Delete){
Minor:
```suggestion
tasks.register("cleanDir", Delete) {
```

2022-09-07 10:52 UTC, vkolomeyko commented on tools/plugins/build.gradle
> +tasks.register("cliInstallScriptsS3", Copy){
Minor:
```suggestion
tasks.register("cliInstallScriptsS3", Copy) {
```

2022-09-07 10:52 UTC, vkolomeyko commented on tools/plugins/build.gradle
> +
Minor:
```suggestion
```

2022-09-07 10:54 UTC, ceebee-dev commented on tools/plugins/installScripts/install.sh
> +echo "java -Dpf4j.pluginsDir=$cliHome\plugins -jar corda-cli.jar $@" > $cliHome\corda-cli.sh
For Linux/MacOS we need to use '/' not '\' for separating elements of a file path.
This instead:
`echo "java -Dpf4j.pluginsDir=$cliHome/plugins -jar corda-cli.jar $@" > $cliHome/corda-cli.sh`

2022-09-07 11:01 UTC, benmcmahon100 commented on tools/plugins/installScripts/install.sh
> +echo "java -Dpf4j.pluginsDir=$cliHome\plugins -jar corda-cli.jar $@" > $cliHome\corda-cli.sh
```suggestion
echo "java -Dpf4j.pluginsDir=$cliHome/plugins -jar corda-cli.jar $@" > $cliHome\corda-cli.sh
```

2022-09-07 11:01 UTC, benmcmahon100 requested changes

2022-09-07 11:01 UTC, benmcmahon100 commented on tools/plugins/installScripts/install.sh
> +echo "java -Dpf4j.pluginsDir=$cliHome\plugins -jar corda-cli.jar $@" > $cliHome\corda-cli.sh
Applies for linux too actually

2022-09-07 12:06 UTC, ronanbrowne requested changes

2022-09-07 12:06 UTC, ronanbrowne commented on tools/plugins/build.gradle
> +tasks.register("cliInstallScriptsS3", Copy){
What / who is the consumer of this task, as it stands nothing is calling this in the task graph unless a user manually triggers it, Which i _presume_ is not the intent

2022-09-07 12:06 UTC, ronanbrowne commented on tools/plugins/build.gradle
> +    if (project.hasProperty('s3Url')) {
Just to be clear, Presuming this is to be provided by a pipeline during the build process?

2022-09-07 15:25 UTC, ronanbrowne approved these changes
LGTM

2022-09-07 15:36 UTC, ronanbrowne requested changes
one minor thing i missed

2022-09-07 15:36 UTC, ronanbrowne commented on tools/plugins/build.gradle
> +            artifactId "corda-cli-installer-s3"
```suggestion
            artifactId "corda-cli-installer-script"
```

2022-09-07 16:36 UTC, vkolomeyko commented
Looks like there is a genuine build failure with this PR atm:
```

[2022-09-07T16:24:09.042Z] Caused by: org.gradle.api.publish.maven.InvalidMavenPublicationException: Invalid publication 'maven': artifact file does not exist: '/var/jenkins/workspace/Corda5_corda-runtime-os_PR-1990/tools/plugins/build/generatedScripts/corda-cli-installer-script.sh'

[2022-09-07T16:24:09.042Z] 	at org.gradle.api.publish.maven.internal.publisher.ValidatingMavenPublisher.checkCanPublish(ValidatingMavenPublisher.java:129)

[2022-09-07T16:24:09.042Z] 	at org.gradle.api.publish.maven.internal.publisher.ValidatingMavenPublisher.validateArtifacts(ValidatingMavenPublisher.java:103)

[2022-09-07T16:24:09.042Z] 	at org.gradle.api.publish.maven.internal.publisher.ValidatingMavenPublisher.publish(ValidatingMavenPublisher.java:47)

[2022-09-07T16:24:09.042Z] 	at org.gradle.api.publish.maven.tasks.PublishToMavenLocal$1.publish(PublishToMavenLocal.java:60)

[2022-09-07T16:24:09.042Z] 	at org.gradle.api.publish.internal.PublishOperation.run(PublishOperation.java:43)

[2022-09-07T16:24:09.042Z] 	... 125 more
```

2022-09-07 17:15 UTC, benmcmahon100 commented
> Looks like there is a genuine build failure with this PR atm:
> 
> ```
> 
> [2022-09-07T16:24:09.042Z] Caused by: org.gradle.api.publish.maven.InvalidMavenPublicationException: Invalid publication 'maven': artifact file does not exist: '/var/jenkins/workspace/Corda5_corda-runtime-os_PR-1990/tools/plugins/build/generatedScripts/corda-cli-installer-script.sh'
> 
> [2022-09-07T16:24:09.042Z] 	at org.gradle.api.publish.maven.internal.publisher.ValidatingMavenPublisher.checkCanPublish(ValidatingMavenPublisher.java:129)
> 
> [2022-09-07T16:24:09.042Z] 	at org.gradle.api.publish.maven.internal.publisher.ValidatingMavenPublisher.validateArtifacts(ValidatingMavenPublisher.java:103)
> 
> [2022-09-07T16:24:09.042Z] 	at org.gradle.api.publish.maven.internal.publisher.ValidatingMavenPublisher.publish(ValidatingMavenPublisher.java:47)
> 
> [2022-09-07T16:24:09.042Z] 	at org.gradle.api.publish.maven.tasks.PublishToMavenLocal$1.publish(PublishToMavenLocal.java:60)
> 
> [2022-09-07T16:24:09.042Z] 	at org.gradle.api.publish.internal.PublishOperation.run(PublishOperation.java:43)
> 
> [2022-09-07T16:24:09.042Z] 	... 125 more
> ```

Think this is down to the question you asked me @ronanbrowne I suspect the task that needs to be ran to actually generate that script isn't being invoked in the pipeline

2022-09-08 12:19 UTC, vkolomeyko commented on tools/plugins/build.gradle
> +        def s3Url = project.findProperty("maven.repo.s3").replace('s3://','https://')+ "/" +
Since we are using this property name in the few places in this file, possibly it would be a good idea to create a constant?

2022-09-08 12:23 UTC, benmcmahon100 commented on tools/plugins/build.gradle
> +        def s3Url = project.findProperty("maven.repo.s3").replace('s3://','https://')+ "/" +
Possibly, let me test this with @ronanbrowne against an RC and presuming that all works as expected I can then I can do that

2022-09-08 13:54 UTC, vkolomeyko approved these changes
LGTM

2022-09-08 15:21 UTC, ronanbrowne approved these changes
LGTM

2022-09-08 15:22 UTC, benmcmahon100 approved these changes
Approving to drop my requested changes

2022-09-08 15:23 UTC, merged