CORE-6422 base api cleanup
corda/corda-runtime-os pull request #2004
Opened 2022-09-02 11:30 UTC by blsemo

Removing things that are unused from the api base package.
Moving things to a runtime base package where possible.

2022-09-02 17:05 UTC, lankydan approved these changes, later dismissed

2022-09-05 08:17 UTC, vkolomeyko commented on components/http-rpc-gateway-comp/src/main/kotlin/net/corda/components/rpc/internal/HttpRpcGatewayEventHandler.kt
> +import net.corda.utilities.NetworkHostAndPort
Minor: Would be good to have imports aligned in alpabetical order.

2022-09-05 14:53 UTC, vkolomeyko submitted a review, later dismissed
LGTM

2022-09-05 15:55 UTC, ronanbrowne commented on libs/http-rpc/http-rpc-server-impl/build.gradle
> +implementation project(":libs:http-rpc:http-rpc")
formatting

2022-09-05 16:05 UTC, ronanbrowne requested changes

2022-09-05 16:05 UTC, ronanbrowne commented on libs/base/build.gradle
> +    // Concluded this is the one acceptable dependency in addition to kotlin.
Was this intentionally left in or a note to self in development?

2022-09-05 16:05 UTC, ronanbrowne commented on libs/http-rpc/http-rpc-server-impl/build.gradle
> +implementation project(":libs:http-rpc:http-rpc")
formatting

2022-09-05 16:37 UTC, ronanbrowne approved these changes
LGTM (build changes reviewed)

2022-09-05 17:10 UTC, lankydan approved these changes

2022-09-05 17:53 UTC, merged