added doc for vnode commands
corda/corda-runtime-os pull request #2031
Opened 2022-09-06 14:56 UTC by pmck91

2022-09-07 20:10 UTC, nadinequinr3 requested changes

2022-09-07 20:10 UTC, nadinequinr3 commented on tools/plugins/virtual-node/README.md
> +Upload and overwrite earlier stored CPI record.
```suggestion
Uploads and replaces a previously stored CPI record.
```

2022-09-07 20:10 UTC, nadinequinr3 commented on tools/plugins/virtual-node/README.md
> +# Virtual Node Cli Plugin
```suggestion
# Virtual Node CLI Plugin
```

2022-09-07 20:10 UTC, nadinequinr3 commented on tools/plugins/virtual-node/README.md
> +Any sandboxes running an overwritten version of CPI will be purged and optionally
```suggestion
The plugin purges any sandboxes running an overwritten version of a CPI and optionally
```

2022-09-07 20:10 UTC, nadinequinr3 commented on tools/plugins/virtual-node/README.md
> +vault data for the affected Virtual Nodes wiped out.
Can we use something other than "wiped out" ? Deleted?
How is it optional? Is this a subcommand or configured somewhere?

2022-09-08 08:18 UTC, vkolomeyko commented on tools/plugins/virtual-node/README.md
> +vault data for the affected Virtual Nodes wiped out.
Yes, "deleted" would be fine.

There will be an additional sub-command which will allow choosing whether to delete the DB or not once @benmcmahon100 changes are merged.

2022-09-08 08:25 UTC, vkolomeyko submitted a review, later dismissed
LGTM

2022-09-08 09:40 UTC, nadinequinr3 requested changes

2022-09-08 09:40 UTC, nadinequinr3 commented on tools/plugins/virtual-node/README.md
> +vault data for the affected Virtual Nodes deleted.
```suggestion
deletes vault data for the affected Virtual Nodes.
```

2022-09-08 09:40 UTC, nadinequinr3 commented on tools/plugins/virtual-node/README.md
> +vault data for the affected Virtual Nodes deleted.
We will need to add info about the sub-command

2022-09-08 09:40 UTC, nadinequinr3 commented on libs/virtual-node/virtual-node-endpoints-maintenance/src/main/kotlin/net/corda/libs/virtualnode/maintenance/endpoints/v1/VirtualNodeMaintenanceRPCOps.kt
>       * Furthermore, any sandboxes running an overwritten version of CPI will be purged and optionally vault data for
```suggestion
     * The plugin purges any sandboxes running an overwritten version of a CPI and optionally deletes vault data for the affected Virtual Nodes.
```

2022-09-08 09:40 UTC, nadinequinr3 commented on tools/plugins/virtual-node/src/main/kotlin/net/corda/cli/plugins/vnode/commands/ResetCommand.kt
>          "Any sandboxes running an overwritten version of CPI will be purged and optionally",
```suggestion
        "The plugin purges any sandboxes running an overwritten version of a CPI and optionally ",
```"

2022-09-08 09:40 UTC, nadinequinr3 commented on tools/plugins/virtual-node/src/main/kotlin/net/corda/cli/plugins/vnode/commands/ResetCommand.kt
> +        "vault data for the affected Virtual Nodes deleted."]
```suggestion
        "deletes vault data for the affected Virtual Nodes."]
```

2022-09-08 10:19 UTC, nadinequinr3 approved these changes, later dismissed

2022-09-08 10:36 UTC, nadinequinr3 approved these changes, later dismissed

2022-09-08 12:51 UTC, vkolomeyko approved these changes
LGTM

2022-09-08 13:29 UTC, merged