Core 6419 helm schema
corda/corda-runtime-os pull request #2044
Opened 2022-09-08 08:32 UTC by JasonSinclair95

2022-09-08 11:08 UTC, davidcurrie requested changes
A raft of review comments but I probably haven't caught everything. In particular, the comments for the crypto worker also apply to the other workers. Hopefully it gives you some indication of what is possible in JSON schema though.

As an aside, a lot of the fields that it has assumed are "required" are just because we provide a default value of `""` rather than `null` even though we treat them equally i.e. it isn't really required.

2022-09-08 11:08 UTC, davidcurrie commented on charts/corda/README.md
> +# corda
The problem with checking this in is that we then need to ensure it is yet another file to keep in-sync. I'd remove it for now and let's create a separate ticket for generating it as part of the CI and adding it to the packaged chart and/or having it as a build artifact.

2022-09-08 11:08 UTC, davidcurrie commented on charts/corda/values.schema.json
> +    "$id": "http://example.com/example.json",
Doesn't really matter what this is for now but probably shouldn't be example.com. How about:
```suggestion
    "$id": "http://corda.net/corda-helm.json",
```

2022-09-08 11:08 UTC, davidcurrie commented on charts/corda/values.schema.json
> +        "workers"
I don't believe all of these are actually required. Try taking them out of the default values.yaml and see if you can still run `helm template` without them.

2022-09-08 11:08 UTC, davidcurrie commented on charts/corda/values.schema.json
> +            "items": {},
this should give the type of the items in the array (i.e. `string`)

2022-09-08 11:08 UTC, davidcurrie commented on charts/corda/values.schema.json
> +            "title": "imagePullPolicy",
`title` should be English text so, at a minimum, `image pull policy`

2022-09-08 11:08 UTC, davidcurrie commented on charts/corda/values.schema.json
> +            "pattern":"^(Always|Never|IfNotPresent)$",
you should use `enum` here rather than `pattern`

2022-09-08 11:08 UTC, davidcurrie commented on charts/corda/values.schema.json
> +                    "properties": {},
this should have `cpu` and `memory` as nested properties

2022-09-08 11:08 UTC, davidcurrie commented on charts/corda/values.schema.json
> +                    "properties": {},
this should have `cpu` and `memory` as nested properties

2022-09-08 11:08 UTC, davidcurrie commented on charts/corda/values.schema.json
> +    "type": "object",
in general, to get maximum benefit from the validation, for anything of type `object` we should set `"additionalProperties": false`

2022-09-08 11:08 UTC, davidcurrie commented on charts/corda/values.schema.json
> +                    "pattern": "^(json|text)$"
use `enum`

2022-09-08 11:08 UTC, davidcurrie commented on charts/corda/values.schema.json
> +                    "pattern": "^(all|trace|debug|info|warn|error|fatal|off)$"
use `enum`

2022-09-08 11:08 UTC, davidcurrie commented on charts/corda/values.schema.json
> +            "title": "Path on Kubernetes hosts to mount on Corda workers for collecting dumps",
we should be consistent about upper or lower case for the start of the title

2022-09-08 11:08 UTC, davidcurrie commented on charts/corda/values.schema.json
> +                "endpoint": {
think you should be able to have `"format": "uri"` here if it's supported by this version of the JSON schema spec

2022-09-08 11:08 UTC, davidcurrie commented on charts/corda/values.schema.json
> +                    "pattern":"^(grpc|http/protobuf)$"
`enum`

2022-09-08 11:08 UTC, davidcurrie commented on charts/corda/values.schema.json
> +            "properties": {},
not overly concerned about specifying the properties for this given it's a well-known Kubernetes construct

2022-09-08 11:08 UTC, davidcurrie commented on charts/corda/values.schema.json
> +                        "host": {
`"format": "hostname"`

2022-09-08 11:08 UTC, davidcurrie commented on charts/corda/values.schema.json
> +                        "type": {
this is an `enum` which currently only has one value

2022-09-08 11:08 UTC, davidcurrie commented on charts/corda/values.schema.json
> +                        "user": {
as with many of the string values, this should probably have `"minLength": 1` to indicate that an empty string is not valid

2022-09-08 11:08 UTC, davidcurrie commented on charts/corda/values.schema.json
> +                        }
you should be able to express in JSON schema the constraint that one of these two fields has to be set

2022-09-08 11:08 UTC, davidcurrie commented on charts/corda/values.schema.json
> +                        "host": "prereqs-postgresql.$PREREQS_NAMESPACE",
using `$PREREQS_NAMESPACE` is not a good example as it's not a valid valid

2022-09-08 11:08 UTC, davidcurrie commented on charts/corda/values.schema.json
> +                        "registry": {
`"format": "hostname"`

2022-09-08 11:08 UTC, davidcurrie commented on charts/corda/values.schema.json
> +                            "type": "number",
this is actually a string not a number (which suggests it is missing quotes in `values.yaml`)

2022-09-08 11:08 UTC, davidcurrie commented on charts/corda/values.schema.json
> +                        "prereqs-kafka.:9092"
```suggestion
                        "prereqs-kafka:9092"
```

2022-09-08 11:08 UTC, davidcurrie commented on charts/corda/values.schema.json
> +                        "truststore"
`truststore` is only required if `enabled` is true - you should be able to represent that condition in the constraint

2022-09-08 11:08 UTC, davidcurrie commented on charts/corda/values.schema.json
> +                                    "pattern":"^(PEM|JKS)$"
`enum`

2022-09-08 11:08 UTC, davidcurrie commented on charts/corda/values.schema.json
> +                                "password"
`password` is actually optional

2022-09-08 11:08 UTC, davidcurrie commented on charts/corda/values.schema.json
> +                        "enabled"
only `enabled` is required - the others are only required if `enabled` is `true`

2022-09-08 11:08 UTC, davidcurrie commented on charts/corda/values.schema.json
> +                        "secretRef"
again, this should be replaced by a condition that indicates that one of `secretRef` or `username` is required

2022-09-08 11:08 UTC, davidcurrie commented on charts/corda/values.schema.json
> +                        }
this should be split into two examples: one using `username` and the other giving the name of a `secretRef`

2022-09-08 11:08 UTC, davidcurrie commented on charts/corda/values.schema.json
> +                        "partitions": {
for each of the worker types, there should be a constraint that the number of replicas is not greater than this partition count

2022-09-08 11:08 UTC, davidcurrie commented on charts/corda/values.schema.json
> +                            "properties": {},
as before `cpu` and `memory` should be properties

2022-09-08 11:08 UTC, davidcurrie commented on charts/corda/values.schema.json
> +                                "memory": "20Gi"
`20Gi` of memory is probably on the high side!

2022-09-08 11:08 UTC, davidcurrie commented on charts/corda/values.schema.json
> +                            "properties": {},
as for `requests`

2022-09-08 11:08 UTC, davidcurrie commented on charts/corda/values.schema.json
> +                                "tag"
`registry` and `tag` are not required as they default to values from elsewhere

2022-09-08 11:08 UTC, davidcurrie commented on charts/corda/values.schema.json
> +                        "replicaCount": {
`"minimum": 0`

2022-09-08 11:08 UTC, davidcurrie commented on charts/corda/values.schema.json
> +                                "level"
not required

2022-09-08 11:08 UTC, davidcurrie commented on charts/corda/values.schema.json
> +                                    "type": "string",
should have the same `enum` as `logging.level`

2022-09-08 11:08 UTC, davidcurrie commented on charts/corda/values.schema.json
> +                                    "title": "run DB worker with profiling enabled",
this is the crypto worker

2022-09-08 11:08 UTC, davidcurrie commented on charts/corda/values.schema.json
> +                        "resources": {
same comments as elsewhere

2022-09-08 11:08 UTC, davidcurrie commented on charts/corda/values.schema.json
> +                        "salt",
not required

2022-09-08 11:08 UTC, davidcurrie commented on charts/corda/values.schema.json
> +                        "passphrase",
not required

2022-09-08 11:08 UTC, davidcurrie commented on charts/corda/values.schema.json
> +        "imagePullSecrets": ["docker-registry-cred"]
this is not a valid minimal example as you must specify DB and Kafka properties

2022-09-15 13:37 UTC, JasonSinclair95 commented on charts/corda/values.schema.json
> +                        "truststore"
i need help with this

2022-09-15 13:37 UTC, JasonSinclair95 commented on charts/corda/values.schema.json
> +                        "user": {
That's why required is used so that an empty string cant be specified

2022-09-15 13:38 UTC, JasonSinclair95 commented on charts/corda/values.schema.json
> +                        "type": {
this can be different depending on RDS or prereqs. Also, it includes the namespace in the hostname so enums cant be specified

2022-09-15 13:38 UTC, JasonSinclair95 commented on charts/corda/values.schema.json
> +                        "partitions": {
i need help with this

2022-09-15 13:38 UTC, JasonSinclair95 commented on charts/corda/values.schema.json
> +                                    "type": "string",
They cant have enum because the default is "" so unless this is in the enum then you continue to get an error...

2022-09-16 09:26 UTC, davidcurrie requested changes
thanks for all the updates - another round needed I'm afraid

2022-09-16 09:26 UTC, davidcurrie commented on charts/corda/values.schema.json
> +    "title": "CORDA HELMCHART SCHEMA",
WHY THE CAPITALS?!

2022-09-16 09:26 UTC, davidcurrie commented on charts/corda/values.schema.json
> +                    "enum": ["json"]
`text` is also a valid value (more generally,  you need to check that the contents of `values.yaml` and `debug.yaml` in the root of this repo validate correctly otherwise there'll be lots of angry developers!

2022-09-16 09:26 UTC, davidcurrie commented on charts/corda/values.schema.json
> +            "title": "Path on Kubernetes hosts to mount on Corda workers for collecting dumps",
it still starts with a capital `P`

2022-09-16 09:26 UTC, davidcurrie commented on charts/corda/values.schema.json
> +                "additionalProperties": false,
this should be at the level above

2022-09-16 09:26 UTC, davidcurrie commented on charts/corda/values.schema.json
> +                "enabled": false,
`true` would be a better example as the other values don't matter if it's `false`

2022-09-16 09:26 UTC, davidcurrie commented on charts/corda/values.schema.json
> +                "endpoint": "test",
```suggestion
                "endpoint": "http://otel-collector:4317",
```

2022-09-16 09:26 UTC, davidcurrie commented on charts/corda/values.schema.json
> +                        "existingSecret"
`password` and `existingSecret` should not be required - you need to specify one or the other but not both

2022-09-16 09:26 UTC, davidcurrie commented on charts/corda/values.schema.json
> +                        "additionalProperties": false,
should be a level up

2022-09-16 09:26 UTC, davidcurrie commented on charts/corda/values.schema.json
> +                        "type": {
What are the other values you've seen used? I'm fairly sure this is just used in constructing the JDBC URL in which case it will always be `postgresql` at the moment.

2022-09-16 09:26 UTC, davidcurrie commented on charts/corda/values.schema.json
> +                        "user": {
In JSON schema, `required` just means not `null` which is satisfied by an empty string (unlike the `if` condition in Helm templates).

2022-09-16 09:26 UTC, davidcurrie commented on charts/corda/values.schema.json
> +                    ],
`oneOf` takes a list of which at least one element must be satisfied. You only have one element in your list and it says that both values are required. I think you want something more like:
```suggestion
                    "oneOf": [
                        {
                            "required": ["password"]
                        },
                        {
                            "required": ["existingSecret"]
                        }
                    ],
```

2022-09-16 09:26 UTC, davidcurrie commented on charts/corda/values.schema.json
> +                                "corda-os-docker.software.r3.com"
not a good example here as we don't host DB client images - `docker.io` might be a better example

2022-09-16 09:26 UTC, davidcurrie commented on charts/corda/values.schema.json
> +                        "registry": "corda-os-docker.software.r3.com",
as above, not a good example here

2022-09-16 09:26 UTC, davidcurrie commented on charts/corda/values.schema.json
> +                    "host": "prereqs-postgresql.$PREREQS_NAMESPACE",
```suggestion
                    "host": "prereqs-postgresql",
```

2022-09-16 09:26 UTC, davidcurrie commented on charts/corda/values.schema.json
> +                    "registry": "corda-os-docker.software.r3.com",
and again

2022-09-16 09:26 UTC, davidcurrie commented on charts/corda/values.schema.json
> +                "bootstrapServers": {
although applicable more generally, this is another place where a minimum length would be good to indicate that the default value of `""` is not sufficient

2022-09-16 09:26 UTC, davidcurrie commented on charts/corda/values.schema.json
> +                                            "title": "if TLS is enabled, the name of an existing Kubernetes secret containing the truststore for client connections to Kafka",
```suggestion
                                            "title": "if TLS is enabled, the name of the key used in the Kubernetes secret containing the truststore for client connections to Kafka",
```

2022-09-16 09:26 UTC, davidcurrie commented on charts/corda/values.schema.json
> +                        "enabled"
you should be able to express this using `oneOf` again - one element has `enabled` set to `false` and the other has it set to `true` and with the other properties required

2022-09-16 09:26 UTC, davidcurrie commented on charts/corda/values.schema.json
> +                    ],
this isn't needed as we do accept neither being specified (at which point we generate a password)

2022-09-16 09:26 UTC, davidcurrie commented on charts/corda/values.schema.json
> +                                "name": "",
```suggestion
                                "name": "initial-admin-secret",
```

2022-09-16 09:26 UTC, davidcurrie commented on charts/corda/values.schema.json
> +                            "name": "",
```suggestion
                            "name": "initial-admin-secret",
```

2022-09-16 09:26 UTC, davidcurrie commented on charts/corda/values.schema.json
> +                    "properties": {
need to merge in from `release/os/5.0` here as I've added some extra properties

2022-09-16 09:26 UTC, davidcurrie commented on charts/corda/values.schema.json
> +                    "required": [
only `enabled` is required - the others should only be required if `enabled` is `true`

2022-09-16 09:26 UTC, davidcurrie commented on charts/corda/values.schema.json
> +                        "partitions": {
leave this one for now as we should probably have a think about how we can actually do better here (the number of partitions should potentially be different for each topic)

2022-09-16 09:26 UTC, davidcurrie commented on charts/corda/values.schema.json
> +                            "title": "cli image registry; defaults to image.registry",
nit: here and elsewhere `cli` => `CLI`

2022-09-16 09:26 UTC, davidcurrie commented on charts/corda/values.schema.json
> +                                "tag"
still true that they're not required!

2022-09-16 09:26 UTC, davidcurrie commented on charts/corda/values.schema.json
> +                                    "type": "string",
OK - so this is an example of where we should change the default to be `null` so that it can only take valid values from the `enum` when set

2022-09-16 09:26 UTC, davidcurrie commented on charts/corda/values.schema.json
> +                                    "title": "log level(defaults to logging.level if not specified)",
```suggestion
                                    "title": "log level (defaults to logging.level if not specified)",
```

2022-09-16 09:26 UTC, davidcurrie commented on charts/corda/values.schema.json
> +    "properties": {
missing a `required` at the top level as, at the moment, I can get away without passing any values at all

2022-09-21 09:29 UTC, JasonSinclair95 commented on charts/corda/values.schema.json
> +                "endpoint": {
if i use "format: URI" then the helm install fails due the default openTelemetry.endpoint="". should I use a random URI for the default, for example, "https://otel.example.com:4317", or do you have another way around this? @davidcurrie

2022-09-21 09:34 UTC, JasonSinclair95 commented on charts/corda/values.schema.json
> +                        "type": {
Apologies, i thought we was referring to db.cluster.host not db.cluster.type

2022-09-21 09:38 UTC, JasonSinclair95 commented on charts/corda/values.schema.json
> +                        "user": {
Okay

2022-09-21 10:26 UTC, JasonSinclair95 commented on charts/corda/values.schema.json
> +                                    "type": "string",
I have had to add empty string to the list like so ["all","trace","debug","info","warn","error","fatal","off", ""] as it still takes the empty string in the value.yaml and because this is not one of the options in the list it fails. The error is 
`
Error: values don't meet the specifications of the schema(s) in the following chart(s):
Corda:
workers.db.logging.level: workers.db.logging.level must be one of the following: "all", "trace", "debug", "info", "warn", "error", "fatal", "off"
`

and the config is 
``` yaml
                                "level": {
                                    "type": "string",
                                    "default": null,
                                    "title": "log level: one of all, trace, debug, info, warn, error, fatal, or off; defaults to logging.level if not specified",
                                    "examples": [
                                        "warn"
                                    ],
                                    "enum": ["all","trace","debug","info","warn","error","fatal","off"]

```

Is this solution okay? @davidcurrie

2022-09-21 10:28 UTC, davidcurrie commented on charts/corda/values.schema.json
> +                                    "type": "string",
Remember that `default` here is effectively just documentation for the user. You'll actually need to set the value to `null` in the Chart `values.yaml` as well.

2022-09-21 10:30 UTC, davidcurrie commented on charts/corda/values.schema.json
> +                "endpoint": {
set the endpoint to `null` in the chart

2022-09-21 10:43 UTC, JasonSinclair95 commented on charts/corda/values.schema.json
> +                                    "type": "string",
I did change originally however what i was missing was i the json schema the following should be used if using null and string
````yaml
["string", "null"]

2022-09-21 10:49 UTC, davidcurrie commented on charts/corda/values.schema.json
> +                                    "type": "string",
Ah - that I had not appreciated. I had assumed it was sufficient for it to not be required.

2022-09-21 10:51 UTC, JasonSinclair95 commented on charts/corda/values.schema.json
> +                "endpoint": {
I can apply the same knowledge from logging.level now

2022-09-21 10:51 UTC, JasonSinclair95 commented on charts/corda/values.schema.json
> +                "endpoint": {
thanks

2022-09-21 11:16 UTC, JasonSinclair95 commented on charts/corda/values.schema.json
> +                    "enum": ["json"]
Okay ill overlook again

2022-09-21 13:14 UTC, JasonSinclair95 commented on charts/corda/values.schema.json
> +                    ],
If I do it this way, it doesn't reply with a significant error indicating which one to specify. For example, this is the error doing it the way above...
```bash
db.cluster: Must validate one and only one schema (oneOf)
```
Where as the error produced my way is 

```bash 
[debug] execution error at (corda/templates/cluster-db-secret.yaml:13:15): Must specify db.cluster.existingSecret or db.cluster.password
```

2022-09-21 13:23 UTC, davidcurrie commented on charts/corda/values.schema.json
> +                    ],
That second error isn't coming from the schema validation though - that's coming from the `required` function in `db-worker-secret.yaml`. That said, it's disappointing that the schema validation error is not more specific. We could just leave the requirement for those fields out of the schema entirely and rely on the runtime validation.

2022-09-21 13:52 UTC, JasonSinclair95 commented on charts/corda/values.schema.json
> +    "properties": {
ive now specified 
``` yaml
        "imagePullSecrets",
        "db",
        "kafka"
```
as this is the minimum needed for an deployment. like seen in the example as the bottem of the schema
```yaml
    "examples": [{
        "imagePullSecrets": ["docker-registry-cred"],
        "db": {
            "cluster": {
                "existingSecret": "prereqs-postgresql",
                "host": "db.cluster.host=prereqs-postgresql"
            }
        },
        "kafka": {
            "bootstrapServers": "prereqs-Kafka"
        }
    }
```

2022-09-21 13:55 UTC, JasonSinclair95 commented on charts/corda/values.schema.json
> +                    ],
okay

2022-09-21 15:56 UTC, closed without merging