CORE-3510: Prevent Kryo Serializing Avro Classes
corda/corda-runtime-os pull request #2066
Opened 2022-09-09 09:18 UTC by jujoramos

Reject Kryo serialization of avro generated classes by registering a default serializer.

- Add 'asMap' extension function to 'KeyValuePairList' class.
- Remove references to 'FlowStackItem' from the flow checkpoint.
- Implement and register 'AvroRecordSerializer' as the default serialiser for any class that implements the SpecificRecord inteface, preventing the kryo serialisation of avro generated classes.

2022-09-09 10:28 UTC, lankydan commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/fiber/FlowIORequest.kt
> +        val contextPlatformProperties: Map<String, String>
Should we have a non-Avro version of `FlowStackItem` so that `SubFlowFinished` and `SubFlowFailed` can both reference that instead of having the properties duplicated between them?

2022-09-09 10:28 UTC, lankydan commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/application/services/FlowEngineImpl.kt
> +            flowFiberService.getExecutingFiber().suspend(FlowIORequest.SubFlowFailed.from(t, peekCurrentFlowStackItem()))
Have you run this for real and checked that the serialization error is thrown?

I'm a bit suspicious of this code, since I thought it would get a `FlowStackItem` in the call stack, just before calling `suspend`. It is possible that this is not the case though. If it is an issue, then moving the creation of `SubFlowFailed` to a separate non suspendable method would resolve this.

2022-09-09 10:28 UTC, lankydan commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/fiber/FlowIORequest.kt
> +            fun from(flowStackItem: FlowStackItem): SubFlowFinished {
Not particularly a fan of this method, we can remove it depending on what we do about the comment above.

2022-09-12 10:14 UTC, jujoramos commented
Apologies for the force push, had to rebase against the original branch due to some conflicts.

2022-09-12 10:15 UTC, jujoramos commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/fiber/FlowIORequest.kt
> +            fun from(flowStackItem: FlowStackItem): SubFlowFinished {
Removed

2022-09-12 10:15 UTC, jujoramos commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/fiber/FlowIORequest.kt
> +        val contextPlatformProperties: Map<String, String>
Done

2022-09-12 14:04 UTC, lankydan reviewed
@simon-johnson-r3 can you have a quick review of this since some of the context code is changed in this PR.

2022-09-12 14:04 UTC, lankydan commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/state/impl/FlowStackImpl.kt
> + * serializable), only the non-serializable version is exposed so Avro generated types don't end in the stack
Even though I get what you mean, its a bit confusing, since both types are serializable just by different means.

I think just changing `only the non-serializable version is exposed` to `only the non-avro-serializable version is exposed` clears this up.

2022-09-12 14:04 UTC, lankydan commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/state/impl/FlowStackImpl.kt
> +        addAll(stackItems.map {
You can do:

```kotlin
stackItems.map {
    FlowStackItem(
            it.flowName,
            it.isInitiatingFlow,
            it.sessionIds.toMutableList(),
            it.contextUserProperties.toMutableMap(),
            it.contextPlatformProperties.toMutableMap()
    )
}.toMutableMap()
```

2022-09-12 14:04 UTC, lankydan commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/state/impl/FlowStackImpl.kt
> +    fun toAvro(): List<AvroFlowStackItem> {
Same comment as before.

2022-09-12 14:04 UTC, lankydan commented on components/flow/flow-service/src/test/kotlin/net/corda/flow/state/FlowStackImplTest.kt
> +    return Objects.equal(this.flowName, other.flowName) &&
Think this would be better as a series of `assertEquals` or `assertThat().isEqualTo` so its easier to tell what values are wrong.

2022-09-12 14:04 UTC, lankydan commented on components/flow/flow-service/src/test/kotlin/net/corda/flow/state/FlowCheckpointImplTest.kt
>      fun `flow stack - peek first returns first item on the stack`() {
Seems like we have somewhat duplicated tests now since `FlowStackImpl` is tested here and in `FlowStackImplTest`.

2022-09-12 14:44 UTC, jujoramos commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/state/impl/FlowStackImpl.kt
> + * serializable), only the non-serializable version is exposed so Avro generated types don't end in the stack
Done, thanks for the suggestion 👍

2022-09-12 14:44 UTC, jujoramos commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/state/impl/FlowStackImpl.kt
> +        addAll(stackItems.map {
👍

2022-09-12 14:45 UTC, jujoramos commented on components/flow/flow-service/src/test/kotlin/net/corda/flow/state/FlowStackImplTest.kt
> +    return Objects.equal(this.flowName, other.flowName) &&
Done, I've created a new Assertion to make the code more readable as well.

2022-09-12 14:51 UTC, jujoramos commented on components/flow/flow-service/src/test/kotlin/net/corda/flow/state/FlowCheckpointImplTest.kt
>      fun `flow stack - peek first returns first item on the stack`() {
Yeah, I've noticed this too... the main difference is that the new `FlowStackImplTest` aims to exercise methods from `FlowStack` in complete isolation, though, and `FlowCheckpointImplTest` mocks several dependencies and tests multiple integrations (`FlowStack` - `FlowCheckpoint`, etc) instead.
I can delete the new `FlowStackImplTest` if you want, but I think is worth having it.

2022-09-13 12:30 UTC, simon-johnson-r3 commented
I've spoken to Dan about this offline just to ensure my understand is correct, but I will leave a comment here too for the record. I think this PR reflects the solution outlined in the ticket, but I wonder whether the ticket could have done with a little more refinement. We have a general premise where things outside the stack are held as Avro types, largely to aid serialization. Now we see this is getting in the way of, ironically, serialization. I think then we can't use the argument that Avro works for us because of serialization *and* implement special cases where we find it doesn't just to keep the first rule afloat.

Actually though if we look at the specific problem here, the IO request handlers need some information about the FlowStackItem. Right now that is limited to session ids (a list of strings). We don't need to expose non-Avro FlowStackItems to the entire system just to get those in the IO request messages, we can instead change what those messages contain. In the future we might load them with more information from the flow stack item, but this is localised to that one place at the point of use. With the dual serialization solution we are constantly having to keep both data structures in sync, whether the consumer of the information needs that extra stuff or not.

2022-09-13 13:06 UTC, jujoramos commented
@simon-johnson-r3 : thanks for pointing out the flaw in the approach, it certainly makes sense, I'll go ahead and make the changes 👍 .

2022-09-13 13:36 UTC, lankydan commented
I take the blame for it since I told @jujoramos to do it that way 😢

2022-09-13 13:37 UTC, jujoramos commented
@lankydan : no blame to take, was a good learning exercise 🍻 .

2022-09-14 08:22 UTC, lankydan submitted a review, later dismissed
LGTM, @simon-johnson-r3 ?

2022-09-14 14:32 UTC, simon-johnson-r3 requested changes

2022-09-14 14:32 UTC, simon-johnson-r3 commented on libs/flows/utils/src/main/kotlin/net/corda/flow/utils/KeyValueStore.kt
> +fun KeyValuePairList.asMap(): Map<String, String> {
Think you must behind release branch slightly, there's already a `toMap` function in this file: 
https://github.com/corda/corda-runtime-os/blob/release/os/5.0/libs/flows/utils/src/main/kotlin/net/corda/flow/utils/KeyValueStore.kt#L44

2022-09-14 14:32 UTC, simon-johnson-r3 commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/fiber/FlowIORequest.kt
> +    data class SubFlowFinished(val sessionIds: List<String>) : FlowIORequest<Unit?>
This says the IO request returns `Unit` or `null`, I expect you just want `Unit` here?

2022-09-14 14:32 UTC, simon-johnson-r3 commented on components/flow/flow-service/src/test/kotlin/net/corda/flow/pipeline/impl/FlowEventPipelineImplTest.kt
> +        val flowResult = FlowIORequest.SubFlowFinished(listOf())
If you want an empty list it's more usual to write `emptyList()` as it's a little more expressive.

As I recall it will also return you the same empty list of each type each time, so doesn't require allocating memory, although that isn't important here.

2022-09-14 14:32 UTC, simon-johnson-r3 commented on libs/flows/utils/src/test/kotlin/net/corda/flow/utils/KeyValueStoreTest.kt
> +            .isInstanceOf(MutableMap::class.java)
This is an interesting one. Do you care that it's a `MutableMap` or that the map is mutable, or both? I think it would be worth adding something to the map to check it's mutable at least. `MutableMap` is an interface, so it's not technically correct that checking the type means it's definitely going to let you add stuff at runtime, even though the contract might suggest it should.

2022-09-14 14:32 UTC, simon-johnson-r3 commented on libs/serialization/serialization-kryo/src/main/kotlin/net/corda/kryoserialization/DefaultKryoCustomizer.kt
> +                // Do not kryo serialize avro generated classes
I think this could be clearer, if you are new to this code you seem to be doing the opposite of what you claim here, by adding something called `AvroRecordSerializer` explicitly. See next comment too, that might resolve this.

2022-09-14 14:32 UTC, simon-johnson-r3 commented on libs/serialization/serialization-kryo/src/main/kotlin/net/corda/kryoserialization/serializers/AvroRecordSerializer.kt
> +internal object AvroRecordSerializer : Serializer<SpecificRecord>() {
I would be surprised to come here and find this doesn't actually do Avro serialization given the name. Is there a name which better suits the idea it's turning Avro serialization into an error condition perhaps?

2022-09-14 14:32 UTC, simon-johnson-r3 commented on libs/serialization/serialization-kryo/src/test/kotlin/net/corda/kryoserialization/KryoCheckpointSerializerTest.kt
> +            .hasMessage("${FlowStackItem::class.java.canonicalName} is an avro generated class and should never be " +
I expect opinions vary on this, but I'm not so keen on exact string matching in errors personally. They are usually copied and pasted, which mean any typos make it across, and they create PR bloat if you ever want to change it. But I appreciate this is subjective and there's no hard rule either way, so consider this optional.

2022-09-14 14:37 UTC, jujoramos commented on libs/flows/utils/src/main/kotlin/net/corda/flow/utils/KeyValueStore.kt
> +fun KeyValuePairList.asMap(): Map<String, String> {
I've removed this already (it's actually not part of the current `PR` code), maybe you were reviewing an older commit or something? 🤔

2022-09-14 14:39 UTC, jujoramos commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/fiber/FlowIORequest.kt
> +    data class SubFlowFinished(val sessionIds: List<String>) : FlowIORequest<Unit?>
Good catch 👍

2022-09-14 14:40 UTC, jujoramos commented on components/flow/flow-service/src/test/kotlin/net/corda/flow/pipeline/impl/FlowEventPipelineImplTest.kt
> +        val flowResult = FlowIORequest.SubFlowFinished(listOf())
Good to know, thanks for the heads up!

2022-09-14 14:49 UTC, jujoramos commented on libs/flows/utils/src/test/kotlin/net/corda/flow/utils/KeyValueStoreTest.kt
> +            .isInstanceOf(MutableMap::class.java)
Yeah, good point. Will update the test to make sure the map can be modified 👍

2022-09-14 14:58 UTC, jujoramos commented on libs/serialization/serialization-kryo/src/main/kotlin/net/corda/kryoserialization/DefaultKryoCustomizer.kt
> +                // Do not kryo serialize avro generated classes
I've changed the name to `AvroRecordRejectSerializer` but I'm not a native language speaker, happy to change the name if you have something better in mind 👍 .

2022-09-14 14:58 UTC, jujoramos commented on libs/serialization/serialization-kryo/src/main/kotlin/net/corda/kryoserialization/serializers/AvroRecordSerializer.kt
> +internal object AvroRecordSerializer : Serializer<SpecificRecord>() {
I've changed the name to `AvroRecordRejectSerializer` but I'm not a native language speaker, happy to change the name if you have something better in mind 👍 .

2022-09-14 15:03 UTC, simon-johnson-r3 approved these changes

2022-09-14 15:59 UTC, merged