CORE-5114 wiretransaction serializer kryo test
corda/corda-runtime-os pull request #2069
Opened 2022-09-09 10:22 UTC by vlajos

It looks like we need a proper (with all required classes) sandbox for this.
I started to add the classes one by one, but I hope there is a better way to build a good-enough sandbox.

2022-09-11 15:35 UTC, chrisr3 commented
Shouldn't `ledger-common-impl` depend on `serialization-kryo`, rather than vice versa?

_OSGi Is Your Friend_, so you should be able to define your serializer within the `ledger-common-impl` bundle, and then declare it as an OSGi component:
```kotlin
@Component
class PrivacySaltImplSerializer : Serializer<PrivacySaltImpl>() {
    // etc
}
```

2022-09-12 09:29 UTC, vlajos commented
> Shouldn't `ledger-common-impl` depend on `serialization-kryo`, rather than vice versa?

Thanks. I have changed it.

> _OSGi Is Your Friend_, so you should be able to define your serializer within the `ledger-common-impl` bundle, and then declare it as an OSGi component:
> 
> ```kotlin
> @Component
> class PrivacySaltImplSerializer : Serializer<PrivacySaltImpl>() {
>     // etc
> }
> ```

The other Kryo serializers are not declared as OSGI components.
Also the integration test seems to find the serializers.
Is this needed?

> Edit: _Ah!_ It's `com.esotericsoftware.kryo.Serializer`, so I'd actually expect `ledger-common-impl` only to need to depend on Kryo itself rather than on our `serialization-kryo` module.

Thanks. This is done.

> 
> The point is that you'd then ask the OSGi framework for all components which implement the `Serializable` service, c.f. our `InternalCustomSerializer` interface and `PublicKeySerializer` for AMQP serialization.

I am a bit lost here. How can the integration test work without that Component declaration?

2022-09-12 15:36 UTC, chrisr3 commented
> The other Kryo serializers are not declared as OSGI components.

The `serialization-kryo` module has some basic serializers built in, yes. These should only be for the simple Java types which don't require Corda dependencies.

More sophisticated Corda types should declare a Kryo serializer as an OSGi component so that the OSGi framework can find them all. See `FlowSandboxServiceImpl` and how it handles custom AMQP serializers as instances of `InternalCustomSerializer`.

2022-09-15 14:06 UTC, blsemo reviewed
Looks generally good, but I have a few question/remarks to be addressed, please.

2022-09-15 14:06 UTC, blsemo commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/sandbox/impl/FlowSandboxServiceImpl.kt
> +                log.info("Registering internal checkpoint serializer {}", serializer.javaClass.name)
That probably shouldn't be an info log line.

2022-09-15 14:06 UTC, blsemo commented on libs/serialization/serialization-checkpoint-api/src/main/kotlin/net/corda/serialization/checkpoint/CustomSerializer.kt
> +    val type: Class<OBJ>
Why do we need this field? Is it to work around type erasure?

2022-09-15 14:06 UTC, blsemo commented on libs/serialization/serialization-kryo/src/main/kotlin/net/corda/kryoserialization/impl/KryoCheckpointSerializerBuilderImpl.kt
> +    private val kryo: Kryo = (Fiber.getFiberSerializer(false) as KryoSerializer).kryo
I believe this is ok - this class only ever gets created in a factory, so it's not like anyone could pass in a malicious version of Kryo,

2022-09-15 14:06 UTC, blsemo commented on processors/flow-processor/build.gradle
> +    runtimeOnly project(':libs:ledger:ledger-common-impl')
Why does the flow processor need a dependency on ledger-common now?

2022-09-15 14:06 UTC, blsemo commented on testing/kryo-serialization-testkit/src/main/kotlin/net/corda/kryoserialization/testkit/KryoTestUtils.kt
> +class KryoTestUtils {
Why put these functions in a companion object of a class that doesn't do anything apart from having this companion object? Couldn't they just be free functions?

2022-09-20 09:21 UTC, vlajos commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/sandbox/impl/FlowSandboxServiceImpl.kt
> +                log.info("Registering internal checkpoint serializer {}", serializer.javaClass.name)
@blsemo
I copied this from its amqp serializer equivalent: https://github.com/corda/corda-runtime-os/blob/release/os/5.0/components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/sandbox/impl/FlowSandboxServiceImpl.kt#L168
Should debug or trace be OK?

2022-09-20 09:24 UTC, vlajos commented on libs/serialization/serialization-checkpoint-api/src/main/kotlin/net/corda/serialization/checkpoint/CustomSerializer.kt
> +    val type: Class<OBJ>
https://github.com/corda/corda-runtime-os/pull/2069/commits/fe377a967408987cbb1add0b92f9714cfb5cd8a1#diff-e626587a875b7d0048665080f0e26a70150050781d232512580c8e351d458339R146
needs a type.
I could not find a better way to extract the class to be serialized from the serializer.
(And the AMQP one seems to use the same pattern.)
Anyway I think you are right and it feels  a bit redundant, but I am not too sure if there is a better way to achieve the same.

2022-09-20 09:24 UTC, vlajos commented on libs/serialization/serialization-kryo/src/main/kotlin/net/corda/kryoserialization/impl/KryoCheckpointSerializerBuilderImpl.kt
> +    private val kryo: Kryo = (Fiber.getFiberSerializer(false) as KryoSerializer).kryo
Thanks!

2022-09-20 09:27 UTC, vlajos commented on processors/flow-processor/build.gradle
> +    runtimeOnly project(':libs:ledger:ledger-common-impl')
@blsemo 
The module containing the new Kryo serializers need to be loaded to let OSGi catch them when the Sandbox gets initialized. Or are there a better way to do that?

2022-09-20 09:59 UTC, vlajos commented on testing/kryo-serialization-testkit/src/main/kotlin/net/corda/kryoserialization/testkit/KryoTestUtils.kt
> +class KryoTestUtils {
Thanks. I have updated it.

2022-09-20 16:05 UTC, blsemo submitted a review, later dismissed
LGTM (but I am not the expert on kryo serialization)

2022-09-20 16:30 UTC, ronanbrowne approved these changes, later dismissed
LGTM (build changes)

2022-09-20 16:32 UTC, chrisr3 requested changes
I'm not a Kryo serialization expert either, but there are a few Gradle / OSGi things I've noticed.

2022-09-20 16:32 UTC, chrisr3 commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/sandbox/impl/FlowSandboxServiceImpl.kt
> +                log.info("Registering internal checkpoint serializer {}", serializer.javaClass.name)
`serializer::class.java.name`

2022-09-20 16:32 UTC, chrisr3 commented on libs/ledger/ledger-common-impl/build.gradle
> +    integrationTestImplementation project(":libs:serialization:serialization-checkpoint-api")
Isn't this dependency already inherited from the `implementation` configuration?

2022-09-20 16:32 UTC, chrisr3 commented on libs/ledger/ledger-common-impl/src/main/java/net/corda/ledger/common/impl/transaction/serializer/package-info.java
> +import org.osgi.annotation.bundle.Export;
Do you need to export this package? The serializer should only be visible as an instance of `CheckpointInternalCustomSerializer` outside this bundle. I'd be worried if anyone else were looking to reference the `WireTransactionKryoSerializer` class directly.

2022-09-20 16:32 UTC, chrisr3 commented on testing/kryo-serialization-testkit/build.gradle
> +    implementation "org.apache.felix:org.apache.felix.framework:$felixVersion"
You _really_ shouldn't need a dependency on Felix! Can you use
```
org.osgi:osgi.core
```
instead?

2022-09-20 16:32 UTC, chrisr3 commented on testing/kryo-serialization-testkit/build.gradle
> +    implementation "net.corda.kotlin:kotlin-stdlib-jdk8-osgi"
I would expect you also to need
```
implementation platform("net.corda:corda-api:$cordaApiVersion")
```
to ensure that you get the correct version of `kotlin-stdlib-jdk8-osgi` here.

2022-09-20 16:32 UTC, chrisr3 commented on testing/kryo-serialization-testkit/src/main/kotlin/net/corda/kryoserialization/testkit/KryoTestUtils.kt
> +import java.util.*
Can you replace this with the actual `java.util` classes you are importing please?

2022-09-21 07:39 UTC, vlajos commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/sandbox/impl/FlowSandboxServiceImpl.kt
> +                log.info("Registering internal checkpoint serializer {}", serializer.javaClass.name)
Thanks. Done.

2022-09-21 07:40 UTC, vlajos commented on libs/ledger/ledger-common-impl/build.gradle
> +    integrationTestImplementation project(":libs:serialization:serialization-checkpoint-api")
Thanks. It was. I have removed the extra.

2022-09-21 07:48 UTC, vlajos commented on testing/kryo-serialization-testkit/src/main/kotlin/net/corda/kryoserialization/testkit/KryoTestUtils.kt
> +import java.util.*
Thanks. Done.

2022-09-21 07:49 UTC, vlajos commented on testing/kryo-serialization-testkit/build.gradle
> +    implementation "org.apache.felix:org.apache.felix.framework:$felixVersion"
Thanks. I have updated to that.

2022-09-21 07:50 UTC, vlajos commented on testing/kryo-serialization-testkit/build.gradle
> +    implementation "net.corda.kotlin:kotlin-stdlib-jdk8-osgi"
Done. I have added that.

2022-09-21 07:54 UTC, vlajos commented on libs/ledger/ledger-common-impl/src/main/java/net/corda/ledger/common/impl/transaction/serializer/package-info.java
> +import org.osgi.annotation.bundle.Export;
I use that class directly in the integration test: https://github.com/corda/corda-runtime-os/pull/2069/files#diff-0c487a3b88f0f7ba27974debe8ada038874b39aa03895c23678a017250523111R114
I could not find a way to emulate FlowSandboxServiceImpl's fetch multiple services for an interface and then register them in integration tests. 
Are there any ways to do that?

2022-09-21 08:58 UTC, chrisr3 commented on libs/ledger/ledger-common-impl/src/main/java/net/corda/ledger/common/impl/transaction/serializer/package-info.java
> +import org.osgi.annotation.bundle.Export;
The `:testing:sandboxes` code doesn't because I didn't have this particular use-case at the time.  However, I don't think it's difficult to include a service filter since every componnent has a `component.name` property which by default is the name of the implementing class.

I have created a small PR which should help you: #2176

2022-09-21 09:23 UTC, vlajos commented on libs/ledger/ledger-common-impl/src/main/java/net/corda/ledger/common/impl/transaction/serializer/package-info.java
> +import org.osgi.annotation.bundle.Export;
Your PR gave me an idea which seem to be working:
```
private lateinit var wireTransactionKryoSerializer: CheckpointInternalCustomSerializer<WireTransaction>
...
wireTransactionKryoSerializer = setup.fetchService(1500)
...
```
looks like doing what is expected.
Originally I wanted to load all the serializers like `FlowSandboxServiceImpl` does, but since we have only this single one, I think this is good enough.

2022-09-21 13:38 UTC, chrisr3 commented on testing/kryo-serialization-testkit/build.gradle
> +    implementation "org.osgi:osgi.core"
Can this be a `compileOnly` dependency?

2022-09-21 16:34 UTC, chrisr3 submitted a review, later dismissed
LGTM

2022-09-21 16:59 UTC, chrisr3 commented on testing/kryo-serialization-testkit/build.gradle
> +    implementation "org.osgi:osgi.core"
Is this `testkit` supposed to be used inside an OSGi framework? Or is it only for unit tests?

If the latter then you will probably _need_ `org.osgi:osg.core` to be `implementation` rather than `compileOnly` because unit tests won't include Felix.

2022-09-21 22:39 UTC, vlajos commented on testing/kryo-serialization-testkit/build.gradle
> +    implementation "org.osgi:osgi.core"
The plan is to used this for both.

2022-09-22 08:11 UTC, chrisr3 commented on testing/kryo-serialization-testkit/build.gradle
> +    implementation "org.osgi:osgi.core"
OK, that's going to be awkward because you're only going to be able to import the OSGi framework interfaces from one place, and for integration tests that _must_ be the framework itself. It sounds like the best solution would be not having _any_ dependencies on `org.osgi.framework.*` classes. Because otherwise the cleanest solution (and it's still not very nice) is for this artifact to have a `compileOnly` dependency on `osgi.core`, and then for unit tests:
```
testImplementation project(':testing:kryoserialization-testkit')
testRuntimeOnly 'org.osgi:osgi.core'
```
and for OSGi integration test - which are hopefully already applying the convention plugin:
```
integrationTestImplementation project(':testing:kryo-serialization-testkit')
```

2022-09-22 08:16 UTC, chrisr3 commented on testing/kryo-serialization-testkit/build.gradle
> +    implementation "org.osgi:osgi.core"
I'll also point out that this dependency has been discovered not to contain any OSGi metadata, which means it cannot be used inside an OSGi framework anyway:
```
    implementation "org.mockito.kotlin:mockito-kotlin:$mockitoKotlinVersion"
```
So maybe this should only be used for unit testing?

2022-09-22 08:18 UTC, chrisr3 commented on testing/kryo-serialization-testkit/build.gradle
> +    id 'corda.common-publishing'
Do we need to publish this artifact? Doesn't it only exist for local testing?

2022-09-22 08:42 UTC, vlajos commented on testing/kryo-serialization-testkit/build.gradle
> +    id 'corda.common-publishing'
Thanks. I have removed this. (from another new test lib as well.)

2022-09-22 08:49 UTC, vlajos commented on testing/kryo-serialization-testkit/build.gradle
> +    implementation "org.osgi:osgi.core"
I have updated the dependencies. Hopefully they are correct now. (Thanks for checking it...)

Re mockito: Good question. It seems to be working in integration tests. I am not too sure how exactly.
On the other hand I think I converted a few tests previously to the other mock thing.
I suppose doing the same would not be a big deal here neither.

2022-09-22 08:55 UTC, chrisr3 commented on testing/kryo-serialization-testkit/build.gradle
> +    implementation "org.osgi:osgi.core"
A jar without OSGi metadata _cannot_ be used as a bundle, so my guess is that no OSGi integration test is really using this testkit.

2022-09-22 09:05 UTC, vlajos commented on testing/kryo-serialization-testkit/build.gradle
> +    implementation "org.osgi:osgi.core"
I mixed with the other two testkits I am working on in another branch.
Sorry for the confusion.
This one is unit test only.
I am updating this branch in a bit.

2022-09-22 10:03 UTC, chrisr3 submitted a review, later dismissed
LGTM :man_dancing:

2022-09-22 11:06 UTC, blsemo commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/sandbox/impl/FlowSandboxServiceImpl.kt
> +import net.corda.flow.pipeline.sandbox.impl.FlowSandboxServiceImpl.Companion.CHECKPOINT_INTERNAL_CUSTOM_SERIALIZERS
That import looks fishy - isnt' that constant defined in this same file?

2022-09-22 12:11 UTC, vlajos commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/sandbox/impl/FlowSandboxServiceImpl.kt
> +import net.corda.flow.pipeline.sandbox.impl.FlowSandboxServiceImpl.Companion.CHECKPOINT_INTERNAL_CUSTOM_SERIALIZERS
@blsemo I have removed this import and its original as well.

2022-09-23 08:27 UTC, blsemo approved these changes
LGTM

2022-09-23 09:10 UTC, benmcmahon100 approved these changes
Reapporving build changes

2022-09-23 09:18 UTC, merged