CORE-5566: Add Explicit Test Assertions
corda/corda-runtime-os pull request #2070
Opened 2022-09-09 10:49 UTC by jujoramos

Explicitly assert within tests that a flow execution failed due an invalid flow constructor.

2022-09-09 11:20 UTC, lankydan commented
The change itself is fine, but I wonder if we should take this chance to add a few more tests.

These would both be tests for Java `Flow`s:

- Has no constructors defined (should run).
- Has no default constructor (should fail).
- Has a private default constructor (should fail?).

Right now I think our Java test coverage is non existent, and surely we should check that Java flows can actually run for DP2.

2022-09-13 10:36 UTC, simon-johnson-r3 requested changes

2022-09-13 10:36 UTC, simon-johnson-r3 commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/flow/FlowTests.kt
> +        assertThat(result.flowError!!.message).matches("Could not create $invalidConstructorFlowName for virtual node.*")
do you need the !! here?

2022-09-13 10:36 UTC, simon-johnson-r3 commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/flow/FlowTests.kt
> +        assertThat(result.flowError!!.message).matches("Could not create $invalidConstructorFlowName for virtual node.*")
I don't know what the consensus is, but I'm not entirely keen on tests which do error string matching like this. It creates a bit of a maintenance headache, and also this test doesn't ensure that the failure is because the flow has no constructor, it could still have positively failed for any other reason.

I think it would be ok to check the name of the flow is mentioned in the error message, because we can consider that a hard requirement, otherwise the user has no idea which flow we refer to.

2022-09-13 10:36 UTC, simon-johnson-r3 commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/flow/FlowTests.kt
> +                invalidConstructorFlowName
If we think it's important to have a test which uses a flow with no valid constructor, then is it worth reflecting that in the title of the test to formalise it? Maintainers in the future could switch the flow for another which generates some other error and everything would seem perfectly valid. I can see a time when other erroring flows are created and we write tests for those too.

2022-09-13 12:50 UTC, jujoramos commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/flow/FlowTests.kt
> +                invalidConstructorFlowName
That change was done but not part of the `PR`, sorry, will update the `PR` soon.

2022-09-13 12:50 UTC, jujoramos commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/flow/FlowTests.kt
> +        assertThat(result.flowError!!.message).matches("Could not create $invalidConstructorFlowName for virtual node.*")
Sounds good, I'll make the change and update the `PR`.

2022-09-13 12:50 UTC, jujoramos commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/flow/FlowTests.kt
> +        assertThat(result.flowError!!.message).matches("Could not create $invalidConstructorFlowName for virtual node.*")
Even though we know the field is not null because we asserted the fact in the previous line, the code won't compile if we don't add `?` or `!!` so, unless I'm missing some cool trick, I think we need the `!!`, yeah.

2022-09-13 13:32 UTC, lankydan commented on components/flow/flow-service/src/test/java/net/corda/flow/pipeline/factory/FlowFactoryImplJavaTest.java
> +public class FlowFactoryImplJavaTest {
We should be able to write this test in Kotlin and still reference the java flows from them. The Java flows will just be in the `java` src instead.

2022-09-13 13:36 UTC, jujoramos commented on components/flow/flow-service/src/test/java/net/corda/flow/pipeline/factory/FlowFactoryImplJavaTest.java
> +public class FlowFactoryImplJavaTest {
I thought the idea was to write the unit test in java as well, that’s why I created the new class instead of using the existing `FlowFactoryImplTest`. No worries, will make the change and update the `PR` 👍

2022-09-13 13:53 UTC, simon-johnson-r3 requested changes

2022-09-13 13:53 UTC, simon-johnson-r3 commented on testing/cpbs/flow-worker-dev/src/main/java/net/cordapp/flowworker/development/smoketests/flow/errors/InvalidJavaFlows.java
> +public class InvalidJavaFlows {
I don't know whether Corda supports nested classes by accident or design, but it looks a little clunky at the point of invocation in the tests. I would consider scoping by package and splitting them instead.

2022-09-13 13:53 UTC, simon-johnson-r3 commented on components/flow/flow-service/src/test/java/net/corda/flow/pipeline/factory/FlowFactoryImplJavaTest.java
> +public class FlowFactoryImplJavaTest {
FlowFactoryImpl is not a public facing api of course, is the rationale that having a Java unit test for this is useful to check the Java flows are compatible with it? If so, perhaps a short comment to indicate that will help future readers?

2022-09-14 09:25 UTC, jujoramos commented on testing/cpbs/flow-worker-dev/src/main/java/net/cordapp/flowworker/development/smoketests/flow/errors/InvalidJavaFlows.java
> +public class InvalidJavaFlows {
Done

2022-09-14 09:26 UTC, jujoramos commented on components/flow/flow-service/src/test/java/net/corda/flow/pipeline/factory/FlowFactoryImplJavaTest.java
> +public class FlowFactoryImplJavaTest {
Done (I've entirely removed the class and just test the java flows from within the kotlin unit test as requested by @lankydan).

2022-09-14 10:08 UTC, lankydan approved these changes

2022-09-14 14:07 UTC, simon-johnson-r3 approved these changes

2022-09-14 14:09 UTC, merged