CORE-6723 add additional logging to flow event pipeline
corda/corda-runtime-os pull request #2106
Opened 2022-09-14 14:22 UTC by LWogan

add additional debug logging of services which are common or system. log kryo errors when they are thrown. Adjust timeout for the fiber to be less than the processor timeout so that the flow can return before it times out from the subscription thread

2022-09-20 12:05 UTC, simon-johnson-r3 requested changes

2022-09-20 12:05 UTC, simon-johnson-r3 commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/impl/FlowEventProcessorImpl.kt
> +        val flowTimeout = (config.getLong(PROCESSING_MAX_FLOW_EXECUTION_DURATION) * 0.75).toLong()
I'm not sure this is the best change to make. PROCESSING_MAX_FLOW_EXECUTION_DURATION was added by me for this purpose specifically. My misunderstanding was that a timeout in the other thread was relating to Kafka polling only, and not killing anything.

To fix this either you could make this a factor of the processor timeout and delete this value from the configuration, or you should change the default value to be lower than the other, and then document that must always be the case. If the latter, then it's probably best to run some check that these values do not collide at runtime.

2022-09-20 14:13 UTC, LWogan commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/impl/FlowEventProcessorImpl.kt
> +        val flowTimeout = (config.getLong(PROCESSING_MAX_FLOW_EXECUTION_DURATION) * 0.75).toLong()
I hadn't even noticed that it was a new timeout added. I thought this was pointing to PROCESSOR_TIMEOUT. ill update

2022-09-21 13:29 UTC, simon-johnson-r3 requested changes, later dismissed

2022-09-21 13:29 UTC, simon-johnson-r3 commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/impl/FlowEventProcessorImpl.kt
> +        //flow result timeout must be lower than the processor timeout as the processor thread will be killed by the subscription consumer
very minor, but are you missing a space here?

2022-09-21 13:30 UTC, simon-johnson-r3 commented
I assume you'll raise an api PR at some point after this is merged to remove the value there?

2022-09-22 09:24 UTC, LWogan commented
> I assume you'll raise an api PR at some point after this is merged to remove the value there?

https://github.com/corda/corda-api/pull/600 got one here. its already plugged into this pr to make sure i removed all references to the path, of which there was a few i did miss

2022-09-22 10:24 UTC, simon-johnson-r3 approved these changes

2022-09-22 10:33 UTC, JamesHR3 approved these changes

2022-09-22 10:38 UTC, merged