CORE-6732, CORE-6688: new test cases, care over entityVersion
corda/corda-runtime-os pull request #2111
Opened 2022-09-14 16:44 UTC by dickon

Refactor test cases to reduce the duplication, add new test cases, rework DatabaseCpiPersistence to handle entityVersion consistently

In some places we did not retrieve entity version and so could get optimistic concurrency exceptions from JPA. This required changing the expected entity version level assertions in the tests.

Refactor to combine CPI persist and update paths. The code for persist and update had a lot of similarities which caused significant duplication and made it hard to read.

Make a number of entity fields val (i.e. readonly), since that is easier to reason about and maintain.

Have CpiMetadataEntity comply with the pattern that synthetic primary keys are embedded, to make the code more uniform and shorter.

Use the standard timestamp mechanism for dCpkDbChnageLogEntity

Note that insertTimestamp changes on update since that might be surprising.

f

2022-09-23 09:26 UTC, dickon commented
I've added `equals` and `hashCode` where necessary; maybe we should consistently implement those methods for all our entity classes which are not `data class`.
 
There's still some scope for tidying up the test cases a little, e.g. eliminate makeCpks.

2022-09-23 10:25 UTC, conalsmith-r3 reviewed
Just a few comments on equals and hashcode implementations.

Hibernate docs say you should override these if you intend to put managed instances into a set or use reattachment of detached entities, the latter I don't think we do anyway, but we do have CpiCpkEntity in a set so this one we should add the overrides with the identifier.

- https://docs.jboss.org/hibernate/core/4.0/manual/en-US/html/persistent-classes.html#persistent-classes-equalshashcode

TL;DR, If you compare using the primary key, then if two entities are equal, they are the same row, and I think that's what you want with JPA entities and equality.

2022-09-23 10:25 UTC, sprintengine commented on libs/virtual-node/cpi-datamodel/src/main/kotlin/net/corda/libs/cpi/datamodel/CpkMetadataEntity.kt
> +        id.hashCode() + cpkFileChecksum.hashCode() + formatVersion.hashCode() + serializedMetadata.hashCode() + isDeleted.hashCode()
Just use the ID and cpkFIleChecksum as these are unique identifiers for instances of this table (maybe you don't even need cpkFileChecksum)

```
override fun equals(other: Any?) = other is CpkMetadataEntity &&
            other.id == id &&
            other.cpkFileChecksum == cpkFileChecksum

override fun hashCode() =
        id.hashCode() + cpkFileChecksum.hashCode()
```

Source - https://thorben-janssen.com/ultimate-guide-to-implementing-equals-and-hashcode-with-hibernate/#:~:text=Java's%20default%20implementation%20of%20the,entity%20twice%20within%20a%20Session.

2022-09-23 10:25 UTC, conalsmith-r3 commented on libs/virtual-node/cpi-datamodel/src/main/kotlin/net/corda/libs/cpi/datamodel/CpiCpkEntity.kt
> +@Suppress("LongParameterList")
Is this actually needed here?

2022-09-23 10:25 UTC, conalsmith-r3 commented on libs/virtual-node/cpi-datamodel/src/main/kotlin/net/corda/libs/cpi/datamodel/CpiCpkEntity.kt
> +            other.cpkFileName == cpkFileName &&
Same here, just the id comparison necessary and generate hashcode using id.

2022-09-23 10:25 UTC, conalsmith-r3 commented on libs/virtual-node/cpi-datamodel/src/main/kotlin/net/corda/libs/cpi/datamodel/CpiCpkEntity.kt
> +    override fun equals(other: Any?): Boolean = other is CpiCpkKey &&
Same here, just the id comparison necessary and generate hashcode using id.

2022-09-23 10:25 UTC, conalsmith-r3 commented on libs/virtual-node/cpi-datamodel/src/main/kotlin/net/corda/libs/cpi/datamodel/CpiMetadataEntity.kt
>  }
Think this missing equals and hashcode

2022-09-23 10:25 UTC, conalsmith-r3 commented on libs/virtual-node/cpi-datamodel/src/main/kotlin/net/corda/libs/cpi/datamodel/CpkDbChangeLogEntity.kt
> +    }
This also missing equals and hashcode

2022-09-23 10:25 UTC, conalsmith-r3 commented on libs/virtual-node/cpi-datamodel/src/main/kotlin/net/corda/libs/cpi/datamodel/CpkFileEntity.kt
>      override fun equals(other: Any?): Boolean {
I suspect this equals and hashcode might need changed too, they include the data which is not part of the primary key. Maybe this could lead to some strange behaviour if we put CpkFileEntities into a set or hashmap, or if we have lazy loaded the instance (with no data), or if we have updated an entity's data and have some detached entities.

Might be worth removing data from the equals and hashcode

2022-10-03 09:42 UTC, vkolomeyko commented
Given that we have https://github.com/corda/corda-runtime-os/pull/2172 in progress being worked on by @benmcmahon100 - we need to decide in which order we are going to merge those 2 PRs.

2022-10-05 16:39 UTC, dickon commented
This PR rotted quite badly. After agreement with @vkolomeyko , @benmcmahon100, @conalsmith-r3 let's try and get this work through in small pieces. Therefore, this first PR now just has one file of test case changes.

2022-10-05 17:14 UTC, dickon commented on libs/virtual-node/cpi-datamodel/src/main/kotlin/net/corda/libs/cpi/datamodel/CpkDbChangeLogEntity.kt
> +    }
That change is now slated for another PR.

2022-10-05 17:14 UTC, dickon commented on libs/virtual-node/cpi-datamodel/src/main/kotlin/net/corda/libs/cpi/datamodel/CpiMetadataEntity.kt
>  }
That change is now slated for another PR.

2022-10-05 17:15 UTC, dickon commented on libs/virtual-node/cpi-datamodel/src/main/kotlin/net/corda/libs/cpi/datamodel/CpiCpkEntity.kt
> +    override fun equals(other: Any?): Boolean = other is CpiCpkKey &&
That change is now slated for another PR.

I've been doing some more reading on this, and the situation is more nuanced, but you are right in that's all we need in this case.

2022-10-05 17:15 UTC, dickon commented on libs/virtual-node/cpi-datamodel/src/main/kotlin/net/corda/libs/cpi/datamodel/CpiCpkEntity.kt
> +            other.cpkFileName == cpkFileName &&
That change is now slated for another PR.

2022-10-05 17:15 UTC, dickon commented on libs/virtual-node/cpi-datamodel/src/main/kotlin/net/corda/libs/cpi/datamodel/CpiCpkEntity.kt
> +@Suppress("LongParameterList")
That change is now slated for another PR. It was needed at one point.

2022-10-05 17:16 UTC, dickon commented on libs/virtual-node/cpi-datamodel/src/main/kotlin/net/corda/libs/cpi/datamodel/CpkMetadataEntity.kt
> +        id.hashCode() + cpkFileChecksum.hashCode() + formatVersion.hashCode() + serializedMetadata.hashCode() + isDeleted.hashCode()
There's a nice detailed discussion of the issue here 

https://web.archive.org/web/20170710132916/http://www.onjava.com/pub/a/onjava/2006/09/13/dont-let-hibernate-steal-your-identity.html?page=3

which I found via the equally useful

https://stackoverflow.com/questions/5031614/the-jpa-hashcode-equals-dilemma

Anyway, this is for another PR now.

2022-10-05 18:12 UTC, benmcmahon100 requested changes, later dismissed
Only one small concern on my part. My main worry is we'll forget about this.

2022-10-05 18:12 UTC, benmcmahon100 commented on components/chunking/chunk-db-write-impl/src/integrationTest/kotlin/net/corda/chunking/db/impl/tests/DatabaseCpiPersistenceTest.kt
> +    }
This doesn't look good.

IMO I think it'd make more sense to add the assert that requires it fails, and mark it as 
`@Disabled("pending https://link/to.ticket)`

2022-10-06 09:19 UTC, conalsmith-r3 approved these changes, later dismissed
LGTM

2022-10-06 09:30 UTC, conalsmith-r3 commented on components/chunking/chunk-db-write-impl/src/integrationTest/kotlin/net/corda/chunking/db/impl/tests/DatabaseCpiPersistenceTest.kt
> +    fun `cannot store multiple versions of the same CPI name in the same group`() {
I'm a little confused about this test, CPI table's PK is `(name, version, signerSummaryHash)`. If one group cannot have two different versions of the same CPI, how will a CPI ever be upgraded to a new version, the CPI has to exist already. Hence why there is no uniqueness constraint on (name, group_id) in `cpi` table.

2022-10-06 09:41 UTC, dickon commented on libs/virtual-node/cpi-datamodel/src/main/kotlin/net/corda/libs/cpi/datamodel/CpkFileEntity.kt
>      override fun equals(other: Any?): Boolean {
To be address in a new PR.

2022-10-06 09:42 UTC, dickon commented on components/chunking/chunk-db-write-impl/src/integrationTest/kotlin/net/corda/chunking/db/impl/tests/DatabaseCpiPersistenceTest.kt
> +    fun `cannot store multiple versions of the same CPI name in the same group`() {
The original bug and discussion was https://r3-cev.atlassian.net/browse/CORE-6068 ; I have updated the reference in the @Disabled annotation.

2022-10-06 09:49 UTC, dickon commented on components/chunking/chunk-db-write-impl/src/integrationTest/kotlin/net/corda/chunking/db/impl/tests/DatabaseCpiPersistenceTest.kt
> +    fun `cannot store multiple versions of the same CPI name in the same group`() {
And, to be clear, by the time update is ready and to be supported we should delete or rewrite this test case.

2022-10-06 09:50 UTC, dickon commented on components/chunking/chunk-db-write-impl/src/integrationTest/kotlin/net/corda/chunking/db/impl/tests/DatabaseCpiPersistenceTest.kt
> +    fun `cannot store multiple versions of the same CPI name in the same group`() {
The point is that @driessamyn has said upgrade (without force) should not work in DP2, but the fact is the test case, before I added  the assertion that it should fail, passed fine due to missing checks in corda-runtime-os.

2022-10-06 10:08 UTC, conalsmith-r3 commented on components/chunking/chunk-db-write-impl/src/integrationTest/kotlin/net/corda/chunking/db/impl/tests/DatabaseCpiPersistenceTest.kt
> +    fun `cannot store multiple versions of the same CPI name in the same group`() {
I do see there is validation in CpiValidatorImpl
```
cpiPersistence.verifyGroupIdIsUniqueForCpi(cpi)
```
This just loads the CPI by its full identifier (name, version, ssh) and gets the group, so it will always allow two CPIs with different versions in same group.

If it were to actually enforce uniqueness on (CPI name, groupId) it would need to find all CPIs with the CPI name via `em.find("FROM CpiMetadataEntity where name = :name"` and make sure the group is unique.

I think current behaviour is correct in terms of support for virtual node upgrade, which I'm actively designing and POC'ing and will be implementing in the coming weeks.

2022-10-06 10:28 UTC, dickon commented on components/chunking/chunk-db-write-impl/src/integrationTest/kotlin/net/corda/chunking/db/impl/tests/DatabaseCpiPersistenceTest.kt
> +    fun `cannot store multiple versions of the same CPI name in the same group`() {
Okay

2022-10-06 10:28 UTC, dickon commented on components/chunking/chunk-db-write-impl/src/integrationTest/kotlin/net/corda/chunking/db/impl/tests/DatabaseCpiPersistenceTest.kt
> +    }
Done

2022-10-06 10:34 UTC, conalsmith-r3 approved these changes
LGTM

2022-10-06 10:35 UTC, benmcmahon100 approved these changes

2022-10-06 10:35 UTC, merged