CORE-6758 - API and KDoc updates.
corda/corda-runtime-os pull request #2135
Opened 2022-09-16 13:15 UTC by driessamyn

2022-09-16 15:49 UTC, driessamyn commented on libs/virtual-node/cpi-upload-endpoints/src/main/kotlin/net/corda/libs/cpiupload/endpoints/v1/CpiUploadRPCOps.kt
>      data class CpiUploadResponse(val id: String)
FYI @mattbradburyr3 - this is one I think we should rename to `requestId`, but this would have an impact on existing tooling.
Same for the parameter of the `status` method.

2022-09-16 16:18 UTC, nadinequinr3 requested changes

2022-09-16 16:18 UTC, nadinequinr3 commented on libs/virtual-node/cpi-upload-endpoints/src/main/kotlin/net/corda/libs/cpiupload/endpoints/v1/CpiIdentifier.kt
> + * with anywhere they are used as parameter.
```suggestion
 * anywhere they are used as parameters.
```

2022-09-16 16:18 UTC, nadinequinr3 commented on libs/virtual-node/cpi-upload-endpoints/src/main/kotlin/net/corda/libs/cpiupload/endpoints/v1/CpiIdentifier.kt
> + * so the variable names are significant, and should be consistent
```suggestion
 * so the variable names are significant and should be consistent
```

2022-09-16 16:18 UTC, nadinequinr3 commented on libs/virtual-node/cpi-upload-endpoints/src/main/kotlin/net/corda/libs/cpiupload/endpoints/v1/CpiUploadRPCOps.kt
> +    description = "The CPI API consists of a number of endpoints used to manage Corda Package Installer (CPI) " +
```suggestion
    description = "The CPI API consists of a number of endpoints used to manage CorDapp Package Installer (CPI) " +
```

2022-09-16 16:18 UTC, nadinequinr3 commented on libs/virtual-node/cpi-upload-endpoints/src/main/kotlin/net/corda/libs/cpiupload/endpoints/v1/CpiUploadRPCOps.kt
> +        description = "The upload endpoint uses the POST method to upload a CPI (Corda Packing Installer) file to the " +
```suggestion
        description = "The upload endpoint uses the POST method to upload a CPI (CorDapp Package Installer) file to the " +
```

2022-09-16 16:18 UTC, nadinequinr3 commented on libs/virtual-node/cpi-upload-endpoints/src/main/kotlin/net/corda/libs/cpiupload/endpoints/v1/CpiUploadRPCOps.kt
> +     * @param status Status of the Upload request.
Are there specific statuses we should call out?

2022-09-16 16:18 UTC, nadinequinr3 commented on libs/virtual-node/cpi-upload-endpoints/src/main/kotlin/net/corda/libs/cpiupload/endpoints/v1/CpiUploadRPCOps.kt
> +        responseDescription = "Details of all the CPIs uploaded to the cluster."
```suggestion
        responseDescription = "Details of all of the CPIs uploaded to the cluster."
```

2022-09-16 16:19 UTC, nadinequinr3 commented on libs/virtual-node/cpi-upload-endpoints/src/main/kotlin/net/corda/libs/cpiupload/endpoints/v1/CpiMetadata.kt
> + * NOTE:
as above

2022-09-16 16:25 UTC, driessamyn commented on libs/virtual-node/cpi-upload-endpoints/src/main/kotlin/net/corda/libs/cpiupload/endpoints/v1/CpiUploadRPCOps.kt
> +    description = "The CPI API consists of a number of endpoints used to manage Corda Package Installer (CPI) " +
It's always been "Corda Package" not "CorDapp package". See last year's cordacon presentation, for example:

![image](https://user-images.githubusercontent.com/5557551/190685660-8ae98233-836b-411e-b23c-645b76d26bd9.png)

2022-09-16 16:25 UTC, driessamyn commented on libs/virtual-node/cpi-upload-endpoints/src/main/kotlin/net/corda/libs/cpiupload/endpoints/v1/CpiUploadRPCOps.kt
> +        description = "The upload endpoint uses the POST method to upload a CPI (Corda Packing Installer) file to the " +
As above.

2022-09-16 16:26 UTC, driessamyn commented on libs/virtual-node/cpi-upload-endpoints/src/main/kotlin/net/corda/libs/cpiupload/endpoints/v1/CpiUploadRPCOps.kt
> +     * @param status Status of the Upload request.
We will need to for Beta. Currently, they're not really used, so not sure we can call any out.

2022-09-16 18:28 UTC, nadinequinr3 commented on libs/virtual-node/cpi-upload-endpoints/src/main/kotlin/net/corda/libs/cpiupload/endpoints/v1/CpiUploadRPCOps.kt
> +    description = "The CPI API consists of a number of endpoints used to manage Corda Package Installer (CPI) " +
That is interesting! I saw them referred to as "CorDapp xxx" when I first started and so have always written them that way... I'll have to do a replace throughout the Docs Portal.
Just had a quick look and it must have been this section of the wiki that I was first pointed to... https://r3-cev.atlassian.net/wiki/spaces/CB/pages/3863773283/The+Installer

2022-09-17 16:59 UTC, driessamyn commented on libs/virtual-node/cpi-upload-endpoints/src/main/kotlin/net/corda/libs/cpiupload/endpoints/v1/CpiUploadRPCOps.kt
> +    description = "The CPI API consists of a number of endpoints used to manage Corda Package Installer (CPI) " +
I don't mind if we rename it, but we'll have to go through and change it everywhere. I personally prefer Corda Package, as in the future it may not always be a CorDapp I think.

2022-09-19 09:09 UTC, nadinequinr3 commented on libs/virtual-node/cpi-upload-endpoints/src/main/kotlin/net/corda/libs/cpiupload/endpoints/v1/CpiUploadRPCOps.kt
> +    description = "The CPI API consists of a number of endpoints used to manage Corda Package Installer (CPI) " +
No, it sounds like it may have been called Corda Package more often so better to stick with that, especially if it's more future-proof. I'll update the Docs Portal.

2022-09-19 09:49 UTC, AnnaK-R3 commented on libs/virtual-node/cpi-upload-endpoints/src/main/kotlin/net/corda/libs/cpiupload/endpoints/v1/CpiUploadRPCOps.kt
> +    description = "The CPI API consists of a number of endpoints used to manage Corda Package Installer (CPI) " +
I've never heard about CorDapp Packages. It'd always used Corda Package and it's called like that in the Corda 5 DP1 docs.

2022-09-19 09:49 UTC, AnnaK-R3 commented on libs/virtual-node/cpi-upload-endpoints/src/main/kotlin/net/corda/libs/cpiupload/endpoints/v1/CpiUploadRPCOps.kt
> +        description = "The upload endpoint uses the POST method to upload a CPI (Corda Packing Installer) file to the " +
```suggestion
        description = "The upload endpoint uses the POST method to upload a Corda Package Installer (CPI) file to the " +
```

2022-09-19 09:49 UTC, AnnaK-R3 commented on libs/virtual-node/cpi-upload-endpoints/src/main/kotlin/net/corda/libs/cpiupload/endpoints/v1/CpiUploadRPCOps.kt
>       * @param id request id returned from the [cpi] method
```suggestion
     * @param id Request ID returned from the [cpi] method.
```

2022-09-19 09:49 UTC, AnnaK-R3 commented on libs/virtual-node/cpi-upload-endpoints/src/main/kotlin/net/corda/libs/cpiupload/endpoints/v1/CpiUploadRPCOps.kt
>       * @return a status object that is converted to json on the client side `{status: OK}`
```suggestion
     * @return A status object that is converted to .json on the client side `{status: OK}`.
```

2022-09-19 09:49 UTC, AnnaK-R3 commented on libs/virtual-node/cpi-upload-endpoints/src/main/kotlin/net/corda/libs/cpiupload/endpoints/v1/CpkMetadata.kt
> + * This class is visible to end-users via json serialization,
```suggestion
 * This class is visible to end-users via .json serialization,
```

2022-09-19 09:49 UTC, AnnaK-R3 commented on libs/virtual-node/cpi-upload-endpoints/src/main/kotlin/net/corda/libs/cpiupload/endpoints/v1/CpiIdentifier.kt
> + * This class is visible to end-users via json serialization,
```suggestion
 * This class is visible to end-users via .json serialization,
```

2022-09-19 09:49 UTC, AnnaK-R3 commented on libs/virtual-node/cpi-upload-endpoints/src/main/kotlin/net/corda/libs/cpiupload/endpoints/v1/CpkMetadata.kt
> + * @param type Type of CPK (e.g. Contract, Workflow).
```suggestion
 * @param type Type of CPK (for example, contract, workflow).
```

2022-09-19 09:49 UTC, AnnaK-R3 commented on libs/virtual-node/cpi-upload-endpoints/src/main/kotlin/net/corda/libs/cpiupload/endpoints/v1/CpiMetadata.kt
>   * This class is visible to end-users via json serialization,
```suggestion
 * This class is visible to end-users via .json serialization,
```

2022-09-19 09:49 UTC, AnnaK-R3 commented on libs/virtual-node/cpi-upload-endpoints/src/main/kotlin/net/corda/libs/cpiupload/endpoints/v1/CpiMetadata.kt
>   * with anywhere they are used as parameter inputs, e.g.`cpiFileChecksum`
```suggestion
 * with anywhere they are used as parameter inputs, for example, `cpiFileChecksum`.
```

2022-09-19 11:00 UTC, driessamyn commented on libs/virtual-node/cpi-upload-endpoints/src/main/kotlin/net/corda/libs/cpiupload/endpoints/v1/CpiIdentifier.kt
> + * This class is visible to end-users via json serialization,
I'm not sure the `.` here is needed before `json`. JSON as a protocol, not necessarily a file extension.

I think I made all other changes.

2022-09-19 11:11 UTC, AnnaK-R3 commented on libs/virtual-node/cpi-upload-endpoints/src/main/kotlin/net/corda/libs/cpiupload/endpoints/v1/CpiIdentifier.kt
> + * This class is visible to end-users via json serialization,
Sorry, my bad. Just had a look at the R3 docs and it should be JSON.

2022-09-19 11:24 UTC, AnnaK-R3 approved these changes

2022-09-19 11:27 UTC, nadinequinr3 approved these changes

2022-09-19 13:04 UTC, conal-smith approved these changes
LGTM

2022-09-19 13:08 UTC, merged