CORE-6759- update vnode api docs
corda/corda-runtime-os pull request #2136
Opened 2022-09-16 13:31 UTC by driessamyn

2022-09-16 14:44 UTC, nadinequinr3 requested changes

2022-09-16 14:44 UTC, nadinequinr3 commented on libs/virtual-node/virtual-node-endpoints/src/main/kotlin/net/corda/libs/virtualnode/endpoints/v1/VirtualNodeRPCOps.kt
> +    description = "The Virtual Nodes API consists of a number of endpoints to manage Virtual Nodes.",
```suggestion
    description = "The Virtual Nodes API consists of a number of endpoints to manage virtual nodes.",
```

2022-09-16 14:44 UTC, nadinequinr3 commented on libs/virtual-node/virtual-node-endpoints/src/main/kotlin/net/corda/libs/virtualnode/endpoints/v1/VirtualNodeRPCOps.kt
> +        title = "List all virtual nodes",
```suggestion
        title = "Lists all virtual nodes",
```

2022-09-16 14:44 UTC, nadinequinr3 commented on libs/virtual-node/virtual-node-endpoints/src/main/kotlin/net/corda/libs/virtualnode/endpoints/v1/types/VirtualNodeInfo.kt
> + * @param holdingIdentity The holding identity of this virtual node.
Can we elaborate on this at all? It doesn't really give any more info than the name.

2022-09-16 14:44 UTC, nadinequinr3 commented on libs/virtual-node/virtual-node-endpoints/src/main/kotlin/net/corda/libs/virtualnode/endpoints/v1/types/VirtualNodeInfo.kt
> + * @param state The virtual node state.
```suggestion
 * @param state The state of the virtual node.
```

2022-09-16 14:44 UTC, nadinequinr3 commented on libs/virtual-node/virtual-node-endpoints/src/main/kotlin/net/corda/libs/virtualnode/endpoints/v1/types/VirtualNodeInfo.kt
> + */
As above, all of these descriptions are a bit terse.

2022-09-16 14:44 UTC, nadinequinr3 commented on libs/virtual-node/virtual-node-endpoints/src/main/kotlin/net/corda/libs/virtualnode/endpoints/v1/types/VirtualNodes.kt
> + * This class is serialized and returned as JSON in the REST api
```suggestion
 * This class is serialized and returned as JSON in the REST API.
```

2022-09-16 14:44 UTC, nadinequinr3 commented on libs/virtual-node/virtual-node-endpoints/src/main/kotlin/net/corda/libs/virtualnode/endpoints/v1/types/VirtualNodes.kt
> + * @param virtualNodes List of virtual node info.
Should this link to VirtualNodeInfo?

2022-09-16 15:15 UTC, driessamyn commented on libs/virtual-node/virtual-node-endpoints/src/main/kotlin/net/corda/libs/virtualnode/endpoints/v1/types/VirtualNodeInfo.kt
> + * @param holdingIdentity The holding identity of this virtual node.
Holding Identity is a fundamental concept of Corda 5 (similar to Virtual Node or Application Network), so I'm not sure how much we can or should elaborate without a quite detailed explanation.

2022-09-16 15:22 UTC, driessamyn commented on libs/virtual-node/virtual-node-endpoints/src/main/kotlin/net/corda/libs/virtualnode/endpoints/v1/types/VirtualNodeInfo.kt
> + */
I fixed the wording a bit (just order), but I don't think we can explain much more. Most of these fields aren't actually very useful for the users at the moment, but will be in future when we support bring your own DB and possibly for node upgrade. They can also be useful in a debugging scenario. So we may refer to these fields in other documentation or troubleshooting guides, but I don't think we need to add more details descriptions.

2022-09-16 15:24 UTC, paulmoloneyr3 requested changes

2022-09-16 15:24 UTC, paulmoloneyr3 commented on libs/virtual-node/virtual-node-endpoints/src/main/kotlin/net/corda/libs/virtualnode/endpoints/v1/VirtualNodeRPCOps.kt
> +    description = "The Virtual Nodes API consists of a number of endpoints to manage virtual nodes.",
I would add a short description of what a virtual node is. From here:

https://r3-cev.atlassian.net/wiki/spaces/CB/pages/4059365421/2022+07+07+-+Virtual+Nodes+-+Blog+Post

It's quite long, perhaps a summary is;


"A virtual node represents a Corda identity, a person or business that wants to interact with other people or businesses using Corda. The virtual node also contains everything needed to communicate and transact on Corda: keys, certificates, and storage. Corda virtualizes the execution of flow process steps, allowing flows for multiple identities and from multiple applications to be executed within the same environment at the same time. An instance of a virtual node is created for long enough to handle the execution steps needed and then allowed to dematerialize."

2022-09-16 15:27 UTC, driessamyn commented on libs/virtual-node/virtual-node-endpoints/src/main/kotlin/net/corda/libs/virtualnode/endpoints/v1/VirtualNodeRPCOps.kt
> +    description = "The Virtual Nodes API consists of a number of endpoints to manage virtual nodes.",
I disagree. If somebody doesn't know what a Virtual Node is, they won't be using this API. I think it just adds noise.

The above description is also not technically correct. We can't ever create "an instance of a virtual node". It's not a thing, no instance can ever exist. It's a context in which something is executed.

2022-09-16 15:37 UTC, driessamyn commented on libs/virtual-node/virtual-node-endpoints/src/main/kotlin/net/corda/libs/virtualnode/endpoints/v1/VirtualNodeRPCOps.kt
> +    description = "The Virtual Nodes API consists of a number of endpoints to manage virtual nodes.",
Maybe we need a separate data dictionary. Similar to: https://developer.twitter.com/en/docs/twitter-api/data-dictionary/object-model/tweet

It's not content that belongs in the code though.

2022-09-16 15:39 UTC, paulmoloneyr3 commented on libs/virtual-node/virtual-node-endpoints/src/main/kotlin/net/corda/libs/virtualnode/endpoints/v1/VirtualNodeRPCOps.kt
> +    description = "The Virtual Nodes API consists of a number of endpoints to manage virtual nodes.",
Hi Dries, do you know where I can find a more accurate description of virtual nodes? That was the most recently updated description I could find (and the first hit on Confluence), cheers.

2022-09-16 15:45 UTC, driessamyn commented on libs/virtual-node/virtual-node-endpoints/src/main/kotlin/net/corda/libs/virtualnode/endpoints/v1/VirtualNodeRPCOps.kt
> +    description = "The Virtual Nodes API consists of a number of endpoints to manage virtual nodes.",
https://github.com/corda/platform-eng-design/blob/master/core/corda-5/corda-5.0/virtual-node/onboarding-journey.md#definition-of-terms is probably the best we have. At least that I am aware of.

2022-09-16 15:46 UTC, nadinequinr3 commented on libs/virtual-node/virtual-node-endpoints/src/main/kotlin/net/corda/libs/virtualnode/endpoints/v1/VirtualNodeRPCOps.kt
> +    description = "The Virtual Nodes API consists of a number of endpoints to manage virtual nodes.",
https://nadine.preview.docs.r3.com/en/platform/corda/5.0-dev-preview-2/introduction/key-concepts.html#virtual-nodes

(This was reviewed by Kat)

2022-09-16 15:47 UTC, nadinequinr3 approved these changes, later dismissed

2022-09-16 15:56 UTC, driessamyn commented on libs/virtual-node/virtual-node-endpoints/src/main/kotlin/net/corda/libs/virtualnode/endpoints/v1/VirtualNodeRPCOps.kt
> +    description = "The Virtual Nodes API consists of a number of endpoints to manage virtual nodes.",
Maybe that's conceptually how we want to refer to them, but it's not technically how it works. We create instances of Sandboxes, which have the application code (CorDapp) and execute in the Virtual Node context.

For example, there is no `VirtualNode` type in the code. There is a `VirtualNodeInfo` class that has metadata about a virtual node, and we have a `VirtualNodeContext` type that is used to define the context of a Sandbox.

This API is about managing the Virtual Node metadata (Identity, Vault connection, keys etc).

2022-09-16 16:26 UTC, paulmoloneyr3 approved these changes, later dismissed

2022-09-19 09:51 UTC, AnnaK-R3 commented on libs/virtual-node/virtual-node-endpoints/src/main/kotlin/net/corda/libs/virtualnode/endpoints/v1/types/VirtualNodes.kt
> + * List of Virtual Nodes
```suggestion
 * List of virtual nodes
```

2022-09-19 10:15 UTC, driessamyn commented on processors/rpc-processor/src/integrationTest/kotlin/net/corda/processors/rpc/OpenApiCompatibilityTest.kt
> +                    "New baseline written to: $tmpBaselineFile"
@conalsmith-r3 , I added this so it is easier to get the new baseline. Are you ok with this? If so, can you approve on behalf of the HTTP-RPC team?

2022-09-19 10:17 UTC, AnnaK-R3 approved these changes

2022-09-19 10:33 UTC, conalsmith-r3 approved these changes
LGTM

2022-09-19 10:44 UTC, merged