CORE-6376: DB admin impl needs to be published for DP2
corda/corda-runtime-os pull request #2140
Opened 2022-09-16 17:08 UTC by ronanbrowne

`simulator' module depends on this at runtime, sample apps / cordApps having a tetsRuntime dependency on simulator require this to be resolvable

2022-09-17 11:31 UTC, yarivus approved these changes, later dismissed
LGTM

2022-09-20 07:34 UTC, driessamyn commented on libs/db/db-admin-impl/build.gradle
> +
Is it worth adding a comment/note that this should be temporary only?

We need to have a good think about how these dependencies work before Beta. For example, I believe everything that is releases (and hence becomes public API), should reside in a separate repo than the modules which we can evolve between minor versions and patches.

2022-09-20 08:39 UTC, ronanbrowne commented on libs/db/db-admin-impl/build.gradle
> +
@driessamyn - updated

2022-09-20 09:28 UTC, yarivus requested changes

2022-09-20 09:28 UTC, yarivus commented on libs/db/db-admin-impl/build.gradle
> +// temporary measure for DP2, required as a trasnitive dependecy by simulator modules
typo: trasnitive

2022-09-20 09:28 UTC, yarivus commented on libs/db/db-admin-impl/build.gradle
> +// temporary measure for DP2, required as a trasnitive dependecy by simulator modules
Also - if this is temporary - let's leave a TODO comment.

2022-09-20 09:28 UTC, yarivus commented on libs/db/db-admin-impl/build.gradle
> +// temporary measure for DP2, required as a trasnitive dependecy by simulator modules
See same comments below

2022-09-20 09:37 UTC, yarivus approved these changes
Thanks @ronanbrowne 
LGTM

2022-09-20 12:26 UTC, merged