CORE-6763 Update membership API documentation
corda/corda-runtime-os pull request #2144
Opened 2022-09-19 08:23 UTC by YashNabar

2022-09-19 09:33 UTC, nikinagy commented on components/membership/membership-http-rpc/src/main/kotlin/net/corda/membership/httprpc/v1/CertificatesRpcOps.kt
> +                " tenant of the P2P services, or the value 'rpc-api' for a cluster-level tenant of the HTTP RPC API.")
Would love to see an example usage for either p2p or rpc-api. Just to completely avoid confusion.

2022-09-19 09:33 UTC, nikinagy commented on components/membership/membership-http-rpc/src/main/kotlin/net/corda/membership/httprpc/v1/CertificatesRpcOps.kt
> +            description = "Valid certificate chain in PEM format obtained from a certificate authority.",
Can we do something like a dummy cert chain pem in the example above to contain the "begin" and "end" cert parts? So if someone is not familiar with PEM format will have a clue.

2022-09-19 09:33 UTC, nikinagy commented on components/membership/membership-http-rpc/src/main/kotlin/net/corda/membership/httprpc/v1/CertificatesRpcOps.kt
> +     * certificatesOps.importCertificateChain("58B6030FABDD", "cert58B6030FABDD", certificateChain)
Can we double-check with tech writing team if we need to provide curl commands too for these docs?

2022-09-19 09:33 UTC, nikinagy commented on components/membership/membership-http-rpc/src/main/kotlin/net/corda/membership/httprpc/v1/KeysRpcOps.kt
> +     * category. For example, 'CORDA.RSA', 'CORDA.ECDSA.SECP256K1', 'CORDA.ECDSA_SECP256R1', 'CORDA.EDDSA.ED25519',
I would rephrase it to say something like, "an example list would look like this" or something like that. Just to be a little bit more accurate what is the example.

2022-09-19 09:33 UTC, nikinagy commented on components/membership/membership-http-rpc/src/main/kotlin/net/corda/membership/httprpc/v1/KeysRpcOps.kt
> +     * keysOps.listKeys(tenantId = "58B6030FABDD", skip = 4, take = 400, orderBy = "ALIAS", category = CI, alias = null,
This has so many params that can we add a short summary in a comment about what and how we are listing in these examples?

2022-09-19 09:33 UTC, nikinagy commented on components/membership/membership-http-rpc/src/main/kotlin/net/corda/membership/httprpc/v1/MemberRegistrationRpcOps.kt
> +     * The [startRegistration] method enables you to start the registration process for a holding identity represented
I wonder if we should highlight that we currently do not support re-registration if a member already registered successfully?

2022-09-19 11:06 UTC, paulmoloneyr3 commented on components/membership/membership-http-rpc/src/main/kotlin/net/corda/membership/httprpc/v1/CertificatesRpcOps.kt
> +     * certificatesOps.importCertificateChain("58B6030FABDD", "cert58B6030FABDD", certificateChain)
@nadinequinr3 Hi Nadine I would assume that we don't need to include command-line versions of all the methods in this documentation but what do you think?

2022-09-19 11:10 UTC, nadinequinr3 commented on components/membership/membership-http-rpc/src/main/kotlin/net/corda/membership/httprpc/v1/CertificatesRpcOps.kt
> +     * certificatesOps.importCertificateChain("58B6030FABDD", "cert58B6030FABDD", certificateChain)
I don't think so either but something we should maybe revisit post DP2 to make sure they're documented somewhere..

2022-09-19 11:29 UTC, paulmoloneyr3 commented on components/membership/membership-http-rpc/src/main/kotlin/net/corda/membership/httprpc/v1/CertificatesRpcOps.kt
> +    description = "The Certificates API consists of endpoints used to work with certificates and related operations.",
I would add the sentence from the comment to this description as well ("The API allows you
 * to import a certificate chain, and generate a certificate signing request (CSR) to be submitted to a certificate
 * authority (CA)")

2022-09-19 11:30 UTC, paulmoloneyr3 commented on components/membership/membership-http-rpc/src/main/kotlin/net/corda/membership/httprpc/v1/CertificatesRpcOps.kt
> +     * @param alias Unique alias under which the certificate chain will be stored.
```suggestion
     * @param alias The unique alias under which the certificate chain will be stored.
```

2022-09-19 11:31 UTC, paulmoloneyr3 commented on components/membership/membership-http-rpc/src/main/kotlin/net/corda/membership/httprpc/v1/CertificatesRpcOps.kt
> +            description = "Unique alias under which the certificate chain will be stored.",
```suggestion
            description = "The unique alias under which the certificate chain will be stored.",
```

2022-09-19 11:31 UTC, paulmoloneyr3 commented on components/membership/membership-http-rpc/src/main/kotlin/net/corda/membership/httprpc/v1/CertificatesRpcOps.kt
> +            description = "Valid certificate chain in PEM format obtained from a certificate authority.",
```suggestion
            description = "A valid certificate chain in PEM format obtained from a certificate authority.",
```

2022-09-19 11:33 UTC, paulmoloneyr3 commented on components/membership/membership-http-rpc/src/main/kotlin/net/corda/membership/httprpc/v1/KeysRpcOps.kt
> +    description = "The Keys Management API consists of endpoints used to work with cryptographic keys and related operations.",
Add the info from the above comment to this description as well ("The API allows you to list scheme codes which are supported by the associated HSM integration, retrieve keys owned by a tenant, generate a key pair for a tenant, and retrieve a tenant's key in PEM format.")

2022-09-19 11:33 UTC, paulmoloneyr3 commented on components/membership/membership-http-rpc/src/main/kotlin/net/corda/membership/httprpc/v1/KeysRpcOps.kt
> +        responseDescription = "List of scheme codes which are supported by the associated HSM integration."
```suggestion
        responseDescription = "The list of scheme codes which are supported by the associated HSM integration."
```

2022-09-19 11:33 UTC, paulmoloneyr3 commented on components/membership/membership-http-rpc/src/main/kotlin/net/corda/membership/httprpc/v1/KeysRpcOps.kt
> +        @HttpRpcPathParameter(description = "Category of the HSM. Can be the value 'ACCOUNTS', 'CI', 'LEDGER', 'NOTARY'," +
```suggestion
        @HttpRpcPathParameter(description = "The category of the HSM. Can be the value 'ACCOUNTS', 'CI', 'LEDGER', 'NOTARY'," +
```

2022-09-19 11:35 UTC, paulmoloneyr3 commented on components/membership/membership-http-rpc/src/main/kotlin/net/corda/membership/httprpc/v1/KeysRpcOps.kt
> +            description = "The response paging information, number of records to return, the actual number may be less" +
```suggestion
            description = "The response paging information; that is, the number of records to return. The actual number returned may be less" +
```

2022-09-19 11:40 UTC, paulmoloneyr3 commented on components/membership/membership-http-rpc/src/main/kotlin/net/corda/membership/httprpc/v1/MGMRpcOps.kt
> +            " a specific set of CorDapps.",
Also add the line "The API allows you to generate the group policy for a membership group, required for new members to join the group." here.

2022-09-19 11:41 UTC, paulmoloneyr3 commented on components/membership/membership-http-rpc/src/main/kotlin/net/corda/membership/httprpc/v1/MemberRegistrationRpcOps.kt
> +            " participation in membership groups.",
Also add the info from the comment: "To participate in a membership group, the holding identity is required to make a registration request that needs to be approved by the MGM for that group. This API allows you to start the registration process for a holding identity, and check the status of a previously created registration request."

2022-09-19 11:42 UTC, paulmoloneyr3 requested changes
Very good, just added some comments mainly about using some of the info from the comments in the descriptions as well.

2022-09-19 15:07 UTC, alexey-kadyrov-r3 commented on components/membership/membership-http-rpc/src/main/kotlin/net/corda/membership/httprpc/v1/KeysRpcOps.kt
> + * tenant, generate a key pair for a tenant, and retrieve a tenant's key in PEM format.
The Keys Management API consists of endpoints used to manage public and private encryption keys. The API
allows you to list scheme codes which are supported by the associated HSM integration, retrieve keys owned by a
tenant, generate a key pair for a tenant, and retrieve a tenant's key in PEM format.

TO

The Keys Management API consists of endpoints used to manage public and private key pairs. The API
allows you to list scheme codes which are supported by the associated HSM integration, retrieve key pairs information owned by a tenant, generate a key pair for a tenant, and retrieve a tenant's public key in PEM format.

2022-09-19 15:08 UTC, alexey-kadyrov-r3 commented on components/membership/membership-http-rpc/src/main/kotlin/net/corda/membership/httprpc/v1/KeysRpcOps.kt
> + * The Keys Management API consists of endpoints used to manage public and private encryption keys. The API
We don't support encryption here

2022-09-19 15:09 UTC, paulmoloneyr3 commented on components/membership/membership-http-rpc/src/main/kotlin/net/corda/membership/httprpc/v1/KeysRpcOps.kt
> + * The Keys Management API consists of endpoints used to manage public and private encryption keys. The API
Please amend/delete as appropriate thanks.

2022-09-19 15:10 UTC, alexey-kadyrov-r3 commented on components/membership/membership-http-rpc/src/main/kotlin/net/corda/membership/httprpc/v1/KeysRpcOps.kt
> + * tenant, generate a key pair for a tenant, and retrieve a tenant's key in PEM format.
For he bellow - we don't retrieve **keys** as we never return private keys. Change throughout to be "key pair" or "public key" whichever fits better in the specific context what you are describing

2022-09-19 15:27 UTC, paulmoloneyr3 commented on components/membership/membership-http-rpc/src/main/kotlin/net/corda/membership/httprpc/v1/KeysRpcOps.kt
> + * tenant, generate a key pair for a tenant, and retrieve a tenant's key in PEM format.
Thanks Alexey

2022-09-19 15:51 UTC, YashNabar commented on components/membership/membership-http-rpc/src/main/kotlin/net/corda/membership/httprpc/v1/KeysRpcOps.kt
> + * tenant, generate a key pair for a tenant, and retrieve a tenant's key in PEM format.
Thanks, corrected in [69f8bc3](https://github.com/corda/corda-runtime-os/pull/2144/commits/69f8bc30ebe0097003dca2e40cb766b02213c541)

2022-09-19 15:51 UTC, YashNabar commented on components/membership/membership-http-rpc/src/main/kotlin/net/corda/membership/httprpc/v1/KeysRpcOps.kt
> + * The Keys Management API consists of endpoints used to manage public and private encryption keys. The API
Thanks, corrected in [69f8bc3](https://github.com/corda/corda-runtime-os/pull/2144/commits/69f8bc30ebe0097003dca2e40cb766b02213c541)

2022-09-20 08:40 UTC, vkolomeyko submitted a review, later dismissed

2022-09-20 08:43 UTC, YashNabar commented
The Jiras suggest updating the descriptions for `get_<api>_getprotocolversion` (currently - “Integer value specifying the version of the endpoint.“) and `HttpFileUpload` params (currently - “A file to upload”). These have been updated in code, however, descriptions for these seem to be overwritten to the previously mentioned strings in `StaticExposedMethods::13` and `SchemaPrimitiveBuilders::107` respectively.

2022-09-20 10:59 UTC, paulmoloneyr3 commented on components/membership/membership-http-rpc/src/main/kotlin/net/corda/membership/httprpc/v1/CertificatesRpcOps.kt
> +            description = "The unique alias under which the certificate chain will be stored.",
```suggestion
            description = "The unique alias under which the certificate chain will be stored",
```

2022-09-20 11:00 UTC, paulmoloneyr3 commented on components/membership/membership-http-rpc/src/main/kotlin/net/corda/membership/httprpc/v1/CertificatesRpcOps.kt
> +            description = "A valid certificate chain in PEM format obtained from a certificate authority.",
```suggestion
            description = "A valid certificate chain in PEM format obtained from a certificate authority",
```

2022-09-20 11:00 UTC, paulmoloneyr3 commented on components/membership/membership-http-rpc/src/main/kotlin/net/corda/membership/httprpc/v1/CertificatesRpcOps.kt
> +        @HttpRpcPathParameter(description = "Identifier of the public key that will be included in the certificate.")
```suggestion
        @HttpRpcPathParameter(description = "Identifier of the public key that will be included in the certificate")
```

2022-09-20 11:00 UTC, paulmoloneyr3 commented on components/membership/membership-http-rpc/src/main/kotlin/net/corda/membership/httprpc/v1/CertificatesRpcOps.kt
> +            description = "Can be the value 'ACCOUNTS', 'CI', 'LEDGER', 'NOTARY', 'SESSION_INIT', 'TLS', or 'JWT_KEY'.",
```suggestion
            description = "Can be the value 'ACCOUNTS', 'CI', 'LEDGER', 'NOTARY', 'SESSION_INIT', 'TLS', or 'JWT_KEY'",
```

2022-09-20 11:03 UTC, paulmoloneyr3 commented on components/membership/membership-http-rpc/src/main/kotlin/net/corda/membership/httprpc/v1/CertificatesRpcOps.kt
> +            description = "Lets you add additional attributes to the CSR e.g. signature spec.",
```suggestion
            description = Used to add additional attributes to the CSR; for example, signature spec",
```

2022-09-20 11:03 UTC, paulmoloneyr3 commented on components/membership/membership-http-rpc/src/main/kotlin/net/corda/membership/httprpc/v1/CertificatesRpcOps.kt
> +            description = "Lets you specify additional subject names.",
```suggestion
            description = "Used to specify additional subject names",
```

2022-09-20 11:04 UTC, paulmoloneyr3 commented on components/membership/membership-http-rpc/src/main/kotlin/net/corda/membership/httprpc/v1/HsmRpcOps.kt
> +        description = "Enables you to retrieve information on the HSM of the specified category assigned to the tenant."
```suggestion
        description = "Enables you to retrieve information on the HSM of the specified category assigned to the tenant"
```

2022-09-20 11:05 UTC, paulmoloneyr3 commented on components/membership/membership-http-rpc/src/main/kotlin/net/corda/membership/httprpc/v1/HsmRpcOps.kt
> +                " tenant of the P2P services, or the value 'rpc-api' for a cluster-level tenant of the HTTP RPC API.")
```suggestion
                " tenant of the P2P services, or the value 'rpc-api' for a cluster-level tenant of the HTTP RPC API")
```

2022-09-20 11:05 UTC, paulmoloneyr3 commented on components/membership/membership-http-rpc/src/main/kotlin/net/corda/membership/httprpc/v1/HsmRpcOps.kt
> +        @HttpRpcPathParameter(description = "Category of the HSM. Can be the value 'ACCOUNTS', 'CI', 'LEDGER'," +
```suggestion
        @HttpRpcPathParameter(description = "The category of the HSM; can be the value 'ACCOUNTS', 'CI', 'LEDGER'," +
```

2022-09-20 11:06 UTC, paulmoloneyr3 commented on components/membership/membership-http-rpc/src/main/kotlin/net/corda/membership/httprpc/v1/HsmRpcOps.kt
> +        @HttpRpcPathParameter(description = "Category of the HSM. Can be the value 'ACCOUNTS', 'CI', 'LEDGER'," +
```suggestion
        @HttpRpcPathParameter(description = "The category of the HSM; can be the value 'ACCOUNTS', 'CI', 'LEDGER'," +
```

2022-09-20 11:06 UTC, paulmoloneyr3 commented on components/membership/membership-http-rpc/src/main/kotlin/net/corda/membership/httprpc/v1/HsmRpcOps.kt
> +                " 'NOTARY', 'SESSION_INIT', 'TLS', or 'JWT_KEY'.")
```suggestion
                " 'NOTARY', 'SESSION_INIT', 'TLS', or 'JWT_KEY'")
```

2022-09-20 11:07 UTC, paulmoloneyr3 commented on components/membership/membership-http-rpc/src/main/kotlin/net/corda/membership/httprpc/v1/MemberRegistrationRpcOps.kt
> +        description = "Enables you to start the registration process for a holding identity."
```suggestion
        description = "Enables you to start the registration process for a holding identity"
```

2022-09-20 11:08 UTC, paulmoloneyr3 commented on components/membership/membership-http-rpc/src/main/kotlin/net/corda/membership/httprpc/v1/MemberRegistrationRpcOps.kt
> +        @HttpRpcPathParameter(description = "The holding identity ID of the requesting virtual node.")
```suggestion
        @HttpRpcPathParameter(description = "The holding identity ID of the requesting virtual node")
```

2022-09-20 11:10 UTC, paulmoloneyr3 commented on components/membership/membership-http-rpc/src/main/kotlin/net/corda/membership/httprpc/v1/NetworkRpcOps.kt
> +                    " the session initiation key is stored, and the session key identifier.",
```suggestion
                    " the session initiation key is stored, and the session key identifier",
```

2022-09-20 11:11 UTC, paulmoloneyr3 commented on components/membership/membership-http-rpc/src/main/kotlin/net/corda/membership/httprpc/v1/NetworkRpcOps.kt
> +                " required for P2P messaging."
```suggestion
                " required for P2P messaging"
```

2022-09-20 11:11 UTC, paulmoloneyr3 commented on components/membership/membership-http-rpc/src/main/kotlin/net/corda/membership/httprpc/v1/MemberRegistrationRpcOps.kt
> +        @HttpRpcPathParameter(description = "The ID of the registration request.")
```suggestion
        @HttpRpcPathParameter(description = "The ID of the registration request")
```

2022-09-20 11:11 UTC, paulmoloneyr3 commented on components/membership/membership-http-rpc/src/main/kotlin/net/corda/membership/httprpc/v1/MemberRegistrationRpcOps.kt
> +        @HttpRpcPathParameter(description = "The ID of the holding identity whose registration progress is to be checked.")
```suggestion
        @HttpRpcPathParameter(description = "The ID of the holding identity whose registration progress is to be checked")
```

2022-09-20 11:11 UTC, paulmoloneyr3 commented on components/membership/membership-http-rpc/src/main/kotlin/net/corda/membership/httprpc/v1/MemberRegistrationRpcOps.kt
> +        description = "Enables you to check the status of the specified registration request for a holding identity."
```suggestion
        description = "Enables you to check the status of the specified registration request for a holding identity"
```

2022-09-20 11:11 UTC, paulmoloneyr3 commented on components/membership/membership-http-rpc/src/main/kotlin/net/corda/membership/httprpc/v1/MemberRegistrationRpcOps.kt
> +        @HttpRpcPathParameter(description = "The ID of the holding identity whose registration progress is to be checked.")
```suggestion
        @HttpRpcPathParameter(description = "The ID of the holding identity whose registration progress is to be checked")
```

2022-09-20 11:12 UTC, paulmoloneyr3 commented on components/membership/membership-http-rpc/src/main/kotlin/net/corda/membership/httprpc/v1/MemberRegistrationRpcOps.kt
> +        description = "Enables you to check the statuses of all registration requests for a holding identity."
```suggestion
        description = "Enables you to check the statuses of all registration requests for a holding identity"
```

2022-09-20 11:13 UTC, paulmoloneyr3 reviewed
Hi Yash, looks fine - I've just removed full stops where the description is not a complete sentence (which is used for parameters etc)

2022-09-21 08:37 UTC, paulmoloneyr3 approved these changes
All good.

2022-09-21 08:42 UTC, nikinagy approved these changes
LGTM

2022-09-21 08:48 UTC, vkolomeyko approved these changes
LGTM

2022-09-21 08:58 UTC, merged