CORE-5539: Config Change Test & Other Improvements
corda/corda-runtime-os pull request #2150
Opened 2022-09-19 15:12 UTC by jujoramos

Add new smoke test that makes a messaging configuration change (which triggers a full reload on all workers) and executes some flows exercising multiple features from different workers afterwards.

- Add 'awaitility-kotlin' as a a dependency to 'workers-smoke-test'.
- Update 'FlowTests' to automatically install prerequisites as part of the setup logic instead of requiring external intervention.
- Fix assertions within 'VirtualNodeRpcTest' to correctly detect conflict errors when uploading CPIs.
- Add helper methods to make the interaction with REST configuration endpoints easier.
- Refactor 'ConfigTests' to use new helper methods and avoid duplicating logic across tests.
- Create new smoke test flow within 'RpcSmokeTestFlow' to exercise membership lookup.
- Add 'corda-config-schema' as a dependency to 'workers-smoke-test' in order to use already defined constants instead of duplicating the keys across modules.
- Prevent test 'start multiple RPC flow and validate they complete' from failing when executed multiple times by specifically checking the result of the flows fired by the test instead of all flows for a particular 'holdingID'.

2022-09-21 10:09 UTC, yarivus reviewed
see my comments

2022-09-21 10:09 UTC, yarivus commented on .ci/e2eTests/utils/kubectl-port-forward-with-reconnect.sh
> +while true;
should this be an endless loop ?!

2022-09-21 10:09 UTC, yarivus commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/Utils.kt
> +const val TEST_CPI_NAME = "flow-worker-dev"
I think this should be changed to "flow-worker-dev-test"

2022-09-21 10:09 UTC, yarivus commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/Utils.kt
> +const val CACHE_INVALIDATION_TEST_CPB = "/META-INF/cache-invalidation-testing/flow-worker-dev.cpb"
same applies here "flow-worker-dev-test.cpb"

2022-09-21 10:12 UTC, jujoramos commented on .ci/e2eTests/utils/kubectl-port-forward-with-reconnect.sh
> +while true;
I'm afraid so, we want to automatically re-establish the port forwarding as soon as there's a problem with the current connection (`kubectl` doesn't automatically reconnect whenever the pod goes down, restart, etc.). The build step seems to automatically kill whatever it started at the very end, anyways, so we shouldn't have any problems.
I'm open to suggestions for better options, though, maybe install yet another external tool to keep the `kubectl port-forward` alive (it will likely be an endless loop under the hood anyways 😅).

2022-09-21 10:14 UTC, jujoramos commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/Utils.kt
> +const val TEST_CPI_NAME = "flow-worker-dev"
There's another [PR](https://github.com/corda/corda-runtime-os/pull/2114) in flight addressing this change, I'll need to rebase the current one and use the new name once that one is merged 👍 .

2022-09-21 10:14 UTC, jujoramos commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/Utils.kt
> +const val CACHE_INVALIDATION_TEST_CPB = "/META-INF/cache-invalidation-testing/flow-worker-dev.cpb"
There's another [PR](https://github.com/corda/corda-runtime-os/pull/2114) in flight addressing this change, I'll need to rebase the current one and use the new name once that one is merged 👍 .

2022-09-21 10:23 UTC, yarivus commented on .ci/e2eTests/utils/kubectl-port-forward-with-reconnect.sh
> +while true;
Maybe you can make it more event based ?
Also - add some unix delays inbetween the iterations.
Lastly, shouldn't you add something to the beginning of the script for interrupts etc (cannot remember what was the syntax for bash) ?

2022-09-21 11:39 UTC, jujoramos commented on .ci/e2eTests/utils/kubectl-port-forward-with-reconnect.sh
> +while true;
Not a `bash` expert here but I'll see what I can do (probably checking whether port 8888 can be reached or not is a better condition than `while true` 😅).

2022-09-21 13:17 UTC, jujoramos commented on .ci/e2eTests/utils/kubectl-port-forward-with-reconnect.sh
> +while true;
I've made some changes to the script, let me know what you think about it 👍

2022-09-21 14:18 UTC, ronanbrowne commented on .ci/e2eTests/Jenkinsfile
> +                    ./gradlew e2eTest ${GRADLE_PERFORMANCE_TUNING}
just curious why these are split now, as this has a performance impact

2022-09-21 14:35 UTC, simon-johnson-r3 requested changes

2022-09-21 14:35 UTC, simon-johnson-r3 commented on .ci/e2eTests/utils/kubectl-port-forward-with-reconnect.sh
> +	echo "kubectl port-forward connection to ${2}:${4} lost, sleeping 5 seconds before trying again..."
This and the line below will execute even if successful first time I believe?

2022-09-21 14:35 UTC, simon-johnson-r3 commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/ConfigTestUtils.kt
> +        // Wait for the service to become unavailable
Did you consider not bothering with this (I'm not sure the test cares that the service is restarted) and instead poll for the new configuration becoming available instead? That might be more robust as it doesn't rely on you catching non-availability. I appreciate I've not played with this and might be over simplifying here.

2022-09-21 14:35 UTC, simon-johnson-r3 commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/ConfigTests.kt
> +        val sourceConfigValues = existing.sourceConfigNode().count()
minor, but this would be better as sourceConfigValueCount, it took me a while to process line 17 as I thought you were comparing config values

2022-09-21 14:35 UTC, simon-johnson-r3 commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/ConfigTests.kt
> +        assertThat(defaultedConfigValues).isGreaterThan(sourceConfigValues)
does this sufficiently prove the title of the test?

2022-09-21 14:35 UTC, simon-johnson-r3 commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/ConfigTests.kt
> +        val newValue = (currentValue * 1.5).toInt()
This doesn't work for 0 or 1, in that newValue and currentValue will be the same and failing functionality will lead to a false passing of the test. Would it perhaps be better to add 1?

2022-09-21 14:35 UTC, simon-johnson-r3 commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/virtualnode/helpers/AssertWithRetryBuilder.kt
> + * Same as [assertWithRetry], but exceptions thrown are also ignored during the retry process.
it's clear why you would benefit from this when you search the code for uses, but maybe identify those reasons in the comment here too?

2022-09-21 14:38 UTC, wzur-r3 commented on .ci/e2eTests/utils/kubectl-port-forward-with-reconnect.sh
> +while true;
> should this be an endless loop ?!

yes - `kubectl port-forward` itself runs forever until it is killed, and that script is a simple wrapper to make sure it is restarted if a service it forwards ports to disappears thus ending `kubectl` process

2022-09-21 14:41 UTC, wzur-r3 commented on .ci/e2eTests/utils/kubectl-port-forward-with-reconnect.sh
> +	echo "kubectl port-forward connection to ${2}:${4} lost, sleeping 5 seconds before trying again..."
`kubectl port-forward` runs forever, so this will be executed only if forwarding is broken on the other end

2022-09-21 14:53 UTC, jujoramos commented on .ci/e2eTests/Jenkinsfile
> +                    ./gradlew e2eTest ${GRADLE_PERFORMANCE_TUNING}
Sorry for not being more explicit in the commit message, I'll try again here: by design, the automatic reload triggered on the `rpc-worker` causes the internal HTTP server to become unavailable for a small period of time. If we have enough bad luck (we always do) as to be running an `e2eTest` alongside the `smokeTest` that triggered the reload, the `e2eTest` will fail as it can't connect to the http server exposed by the `rpc-worker`.
We could update all `e2eTest` to be more resilient to transient connection failures, but that would be out of scope for this `PR`. Another option would be keep executing all tests in parallel as before, exclude the new test and then execute it at the very end (syntax is wrong, just an example):
```
./gradlew cleanE2eTest smokeTest e2eTest ${GRADLE_PERFORMANCE_TUNING} --ignore 'new config test'
./gradlew smokeTest ${GRADLE_PERFORMANCE_TUNING} --tests 'new config test'
```

The above, though, looks worse than running these two set of tests serially.

2022-09-21 15:01 UTC, jujoramos commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/ConfigTestUtils.kt
> +        // Wait for the service to become unavailable
I've hit some race conditions for which the actual configuration change was applied and the new value returned when hitting the `/api/v1/config` endpoint, but the actual reload on the `rpc-worker` didn't even started yet, that's why the method waits for unavailability first.

2022-09-21 15:01 UTC, jujoramos commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/ConfigTests.kt
> +        val sourceConfigValues = existing.sourceConfigNode().count()
👍

2022-09-21 15:04 UTC, jujoramos commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/ConfigTests.kt
> +        assertThat(defaultedConfigValues).isGreaterThan(sourceConfigValues)
It certainly doesn't, no 😓. I've only re-factored this test to use the new utilities and prevent duplicating code, guess I should have improved the implementation as well, will do so and update the `PR`.

2022-09-21 15:07 UTC, jujoramos commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/ConfigTests.kt
> +        val newValue = (currentValue * 1.5).toInt()
The actual value for this property can never be zero, neither 1 (enforced by the schema validator), so we don't need to worry about it:
```
    "configIntervalMs": {
      "description": "Interval in ms between aligning Kafka Configuration Sections state with DB Configuration Sections.",
      "type": "integer",
      "minimum": 5000,
      "maximum": 2147483647,
      "default": 30000
    }
```

Good catch, though!.

2022-09-21 16:15 UTC, jujoramos commented on .ci/e2eTests/utils/kubectl-port-forward-with-reconnect.sh
> +	echo "kubectl port-forward connection to ${2}:${4} lost, sleeping 5 seconds before trying again..."
Thanks @wzur-r3 for answering 👍

2022-09-21 16:28 UTC, jujoramos commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/virtualnode/helpers/AssertWithRetryBuilder.kt
> + * Same as [assertWithRetry], but exceptions thrown are also ignored during the retry process.
👍

2022-09-21 16:31 UTC, jujoramos commented
@yarivus : looks like `while true` is still a better option (at least until [INFRA-1859](https://r3-cev.atlassian.net/browse/INFRA-1859) is implemented). More details [here](https://r3holdco.slack.com/archives/C039J1A3ZQB/p1663768152497899).

2022-09-21 16:38 UTC, yarivus approved these changes
LGTM

2022-09-22 08:10 UTC, simon-johnson-r3 approved these changes

2022-09-22 08:11 UTC, merged