CORE-6791: Simulator API KDocs
corda/corda-runtime-os pull request #2168
Opened 2022-09-20 15:32 UTC by LizR3

2022-09-20 16:35 UTC, ronanbrowne submitted a review, later dismissed
LGTM -  **(Only build.gradle changes reviewed)**  someone needs to review Kdoc - i presume that's tech writers cc @nadinequinr3

2022-09-21 09:23 UTC, nadinequinr3 requested changes

2022-09-21 09:23 UTC, nadinequinr3 commented on simulator/api/src/main/kotlin/net/corda/simulator/HoldingIdentity.kt
> +         * @param commonName the string to use as the common name
```suggestion
         * @param commonName The string to use as the common name.
```

2022-09-21 09:23 UTC, nadinequinr3 commented on simulator/api/src/main/kotlin/net/corda/simulator/HoldingIdentity.kt
> +         * @return a [HoldingIdentity] whose [MemberX500Name] has the given common name
```suggestion
         * @return A [HoldingIdentity] whose [MemberX500Name] has the given common name.
```

2022-09-21 09:23 UTC, nadinequinr3 commented on simulator/api/src/main/kotlin/net/corda/simulator/HoldingIdentity.kt
> +         * Creates a holding identity using the provided member
```suggestion
         * Creates a holding identity using the provided member.
```

2022-09-21 09:23 UTC, nadinequinr3 commented on simulator/api/src/main/kotlin/net/corda/simulator/HoldingIdentity.kt
> +         * @param member the member for which to create a holding identity
```suggestion
         * @param member The member for which to create a holding identity.
```

2022-09-21 09:23 UTC, nadinequinr3 commented on simulator/api/src/main/kotlin/net/corda/simulator/HoldingIdentity.kt
> +         * @return a [HoldingIdentity]
```suggestion
         * @return A [HoldingIdentity].
```

2022-09-21 09:23 UTC, nadinequinr3 commented on simulator/api/src/main/kotlin/net/corda/simulator/RequestData.kt
> +     * The client request which would be used by Corda to identify a particular request for a flow call
```suggestion
     * The client request which would be used by Corda to identify a particular request for a flow call.
```

2022-09-21 09:23 UTC, nadinequinr3 commented on simulator/api/src/main/kotlin/net/corda/simulator/RequestData.kt
> +     * The name of the flow class to be run
```suggestion
     * The name of the flow class to be run.
```

2022-09-21 09:23 UTC, nadinequinr3 commented on simulator/api/src/main/kotlin/net/corda/simulator/RequestData.kt
> +     * A Json string containing the request body to be passed to the flow
```suggestion
     * A JSON string containing the request body to be passed to the flow.
```

2022-09-21 09:23 UTC, nadinequinr3 commented on simulator/api/src/main/kotlin/net/corda/simulator/RequestData.kt
> +         * Creates a [RequestData] using the given strongly-typed parameters
```suggestion
         * Creates a [RequestData] using the given strongly-typed parameters.
```

2022-09-21 09:23 UTC, nadinequinr3 commented on simulator/api/src/main/kotlin/net/corda/simulator/RequestData.kt
> +         * @param requestId the client request which would be used by Corda to identify a particular request
```suggestion
         * @param requestId The client request which would be used by Corda to identify a particular request
```

2022-09-21 09:23 UTC, nadinequinr3 commented on simulator/api/src/main/kotlin/net/corda/simulator/RequestData.kt
> +         * for a flow call
```suggestion
         * for a flow call.
```

2022-09-21 09:23 UTC, nadinequinr3 commented on simulator/api/src/main/kotlin/net/corda/simulator/RequestData.kt
> +         * @param flowClass the flow class to be constructed and called
```suggestion
         * @param flowClass The flow class to be constructed and called.
```

2022-09-21 09:23 UTC, nadinequinr3 commented on simulator/api/src/main/kotlin/net/corda/simulator/RequestData.kt
> +         * @param request data which will be serialized using a
```suggestion
         * @param request Data which will be serialized using a
```

2022-09-21 09:23 UTC, nadinequinr3 commented on simulator/api/src/main/kotlin/net/corda/simulator/RequestData.kt
> +         * [net.corda.v5.application.marshalling.JsonMarshallingService] and passed to the flow
```suggestion
         * [net.corda.v5.application.marshalling.JsonMarshallingService] and passed to the flow.
```

2022-09-21 09:23 UTC, nadinequinr3 commented on simulator/api/src/main/kotlin/net/corda/simulator/RequestData.kt
> +         * @return a [RequestData] with properties that match the provided parameters
```suggestion
         * @return A [RequestData] with properties that match the provided parameters.
```

2022-09-21 09:23 UTC, nadinequinr3 commented on simulator/api/src/main/kotlin/net/corda/simulator/RequestData.kt
> +         * @param requestId the client request which would be used by Corda to identify a particular request
```suggestion
         * @param requestId The client request which would be used by Corda to identify a particular request
```

2022-09-21 09:23 UTC, nadinequinr3 commented on simulator/api/src/main/kotlin/net/corda/simulator/RequestData.kt
> +         * for a flow call
```suggestion
         * for a flow call.
```

2022-09-21 09:23 UTC, nadinequinr3 commented on simulator/api/src/main/kotlin/net/corda/simulator/RequestData.kt
> +         * @param flowClass the name of the flow class to be constructed and called
```suggestion
         * @param flowClass The name of the flow class to be constructed and called.
```

2022-09-21 09:23 UTC, nadinequinr3 commented on simulator/api/src/main/kotlin/net/corda/simulator/RequestData.kt
> +         * @param request data to be passed to the flow
```suggestion
         * @param request Data to be passed to the flow.
```

2022-09-21 09:23 UTC, nadinequinr3 commented on simulator/api/src/main/kotlin/net/corda/simulator/RequestData.kt
> +         * @return a [RequestData] with the provided parameters as properties
```suggestion
         * @return A [RequestData] with the provided parameters as properties.
```

2022-09-21 09:23 UTC, nadinequinr3 commented on simulator/api/src/main/kotlin/net/corda/simulator/RequestData.kt
> +         * @param jsonInput a Json-formatted string containing a client-provided `requestId`, the `flowClass` to
```suggestion
         * @param jsonInput A JSON-formatted string containing a client-provided `requestId`, the `flowClass` to
```

2022-09-21 09:23 UTC, nadinequinr3 commented on simulator/api/src/main/kotlin/net/corda/simulator/SimulatedCordaNetwork.kt
> +     * @param holdingIdentity the holding identity for which to create the flow
```suggestion
     * @param holdingIdentity The holding identity for which to create the flow.
```

2022-09-21 09:23 UTC, nadinequinr3 commented on simulator/api/src/main/kotlin/net/corda/simulator/SimulatedCordaNetwork.kt
> +     * @param flowClasses a list of flow classes to be checked
```suggestion
     * @param flowClasses A list of flow classes to be checked.
```

2022-09-21 09:23 UTC, nadinequinr3 commented on simulator/api/src/main/kotlin/net/corda/simulator/SimulatedCordaNetwork.kt
> +     * @return a simulated virtual node in which flows can be run
```suggestion
     * @return A simulated virtual node in which flows can be run.
```

2022-09-21 09:23 UTC, nadinequinr3 commented on simulator/api/src/main/kotlin/net/corda/simulator/SimulatedCordaNetwork.kt
> +     * @param responder the holding identity which will respond with this flow
```suggestion
     * @param responder The holding identity which will respond with this flow.
```

2022-09-21 09:23 UTC, nadinequinr3 commented on simulator/api/src/main/kotlin/net/corda/simulator/SimulatedCordaNetwork.kt
> +     * @param protocol the protocol for which this responder instance should be run
```suggestion
     * @param protocol The protocol for which this responder instance should be run.
```

2022-09-21 09:23 UTC, nadinequinr3 commented on simulator/api/src/main/kotlin/net/corda/simulator/SimulatedCordaNetwork.kt
> +     * @param responderFlow an instance of a responder flow
```suggestion
     * @param responderFlow An instance of a responder flow.
```

2022-09-21 09:23 UTC, nadinequinr3 commented on simulator/api/src/main/kotlin/net/corda/simulator/SimulatedCordaNetwork.kt
> +     * @return a simulated virtual node which can run this instance of a responder flow
```suggestion
     * @return A simulated virtual node which can run this instance of a responder flow.
```

2022-09-21 09:23 UTC, nadinequinr3 commented on simulator/api/src/main/kotlin/net/corda/simulator/SimulatedVirtualNode.kt
> +     * @return the persistence service associated with this node
```suggestion
     * @return The persistence service associated with this node.
```

2022-09-21 09:23 UTC, nadinequinr3 commented on simulator/api/src/main/kotlin/net/corda/simulator/SimulatedVirtualNode.kt
> +     * @param alias an alias for the key
```suggestion
     * @param alias An alias for the key.
```

2022-09-21 09:23 UTC, nadinequinr3 commented on simulator/api/src/main/kotlin/net/corda/simulator/SimulatedVirtualNode.kt
> +     * @param hsmCategory the HSM category for the key
```suggestion
     * @param hsmCategory The HSM category for the key.
```

2022-09-21 09:23 UTC, nadinequinr3 commented on simulator/api/src/main/kotlin/net/corda/simulator/SimulatedVirtualNode.kt
> +     * @param scheme the scheme for the key - not used, except in verification; an ECDSA key will be returned
```suggestion
     * @param scheme The scheme for the key. This is only used in verification. An ECDSA key will be returned.
```

2022-09-21 09:23 UTC, nadinequinr3 commented on simulator/api/src/main/kotlin/net/corda/simulator/Simulator.kt
> +     * @param holdingIdentity the holding identity for which to create the flow
```suggestion
     * @param holdingIdentity The holding identity for which to create the flow.
```

2022-09-21 09:23 UTC, nadinequinr3 commented on simulator/api/src/main/kotlin/net/corda/simulator/Simulator.kt
> +     * @param flowClasses a list of flow classes to be checked
```suggestion
     * @param flowClasses A list of flow classes to be checked.
```

2022-09-21 09:23 UTC, nadinequinr3 commented on simulator/api/src/main/kotlin/net/corda/simulator/Simulator.kt
> +     * @return a simulated virtual node in which flows can be run
```suggestion
     * @return A simulated virtual node in which flows can be run.
```

2022-09-21 09:23 UTC, nadinequinr3 commented on simulator/api/src/main/kotlin/net/corda/simulator/Simulator.kt
> +     * @param responder the holding identity which will respond with this flow
```suggestion
     * @param responder The holding identity which will respond with this flow.
```

2022-09-21 09:23 UTC, nadinequinr3 commented on simulator/api/src/main/kotlin/net/corda/simulator/Simulator.kt
> +     * @param protocol the protocol for which this responder instance should be run
```suggestion
     * @param protocol The protocol for which this responder instance should be run.
```

2022-09-21 09:23 UTC, nadinequinr3 commented on simulator/api/src/main/kotlin/net/corda/simulator/Simulator.kt
> +     * @param responderFlow an instance of a responder flow
```suggestion
     * @param responderFlow An instance of a responder flow.
```

2022-09-21 09:23 UTC, nadinequinr3 commented on simulator/api/src/main/kotlin/net/corda/simulator/Simulator.kt
> +     * @return a simulated virtual node which can run this instance of a responder flow
```suggestion
     * @return A simulated virtual node which can run this instance of a responder flow.
```

2022-09-21 09:23 UTC, nadinequinr3 commented on simulator/api/src/main/kotlin/net/corda/simulator/SimulatorConfiguration.kt
> +     * The interval at which to check for responder flow health.
```suggestion
     * The interval at which to check responder flow health.
```

2022-09-21 09:23 UTC, nadinequinr3 commented on simulator/api/src/main/kotlin/net/corda/simulator/factories/HoldingIdentityFactory.kt
> +     * @param memberX500Name the member for which to create a [HoldingIdentity]
```suggestion
     * @param memberX500Name The member for which to create a [HoldingIdentity].
```

2022-09-21 09:23 UTC, nadinequinr3 commented on simulator/api/src/main/kotlin/net/corda/simulator/factories/JsonMarshallingServiceFactory.kt
> +         * parsing and formatting of arbitrary objects into Json.
```suggestion
         * parsing and formatting of arbitrary objects into JSON.
```

2022-09-21 09:23 UTC, nadinequinr3 commented on simulator/api/src/main/kotlin/net/corda/simulator/factories/JsonMarshallingServiceFactory.kt
> +         * @return a [JsonMarshallingService]
```suggestion
         * @return A [JsonMarshallingService].
```

2022-09-21 09:23 UTC, nadinequinr3 commented on simulator/api/src/main/kotlin/net/corda/simulator/factories/JsonMarshallingServiceFactory.kt
> +     * @return a [JsonMarshallingService]
```suggestion
     * @return A [JsonMarshallingService].
```

2022-09-21 09:23 UTC, nadinequinr3 commented on simulator/api/src/main/kotlin/net/corda/simulator/factories/SimulatorConfigurationBuilder.kt
> +     * @param clock the clock with which to build the configuration
```suggestion
     * @param clock The clock with which to build the configuration.
```

2022-09-21 09:23 UTC, nadinequinr3 commented on simulator/api/src/main/kotlin/net/corda/simulator/factories/SimulatorConfigurationBuilder.kt
> +     * @return a copy of this builder, with the given clock
```suggestion
     * @return A copy of this builder, with the given clock.
```

2022-09-21 09:23 UTC, nadinequinr3 commented on simulator/api/src/main/kotlin/net/corda/simulator/factories/SimulatorConfigurationBuilder.kt
> +     * @param pollInterval the interval at which to check for responder flow health
```suggestion
     * @param pollInterval The interval at which to check for responder flow health.
```

2022-09-21 09:23 UTC, nadinequinr3 commented on simulator/api/src/main/kotlin/net/corda/simulator/factories/SimulatorConfigurationBuilder.kt
> +     * @return a copy of this builder, with the given poll interval
```suggestion
     * @return A copy of this builder, with the given poll interval.
```

2022-09-21 09:23 UTC, nadinequinr3 commented on simulator/api/src/main/kotlin/net/corda/simulator/factories/SimulatorConfigurationBuilder.kt
> +     * @param timeout the maximum length of time to wait for a responder flow to respond
```suggestion
     * @param timeout The maximum length of time to wait for a responder flow to respond.
```

2022-09-21 09:23 UTC, nadinequinr3 commented on simulator/api/src/main/kotlin/net/corda/simulator/factories/SimulatorConfigurationBuilder.kt
> +     * @return a copy of this builder, with the given timeout
```suggestion
     * @return A copy of this builder, with the given timeout.
```

2022-09-21 09:23 UTC, nadinequinr3 commented on simulator/api/src/main/kotlin/net/corda/simulator/factories/SimulatorConfigurationBuilder.kt
> +     * @return configuration built using chosen options or defaults if no overriding options have been selected
```suggestion
     * @return Configuration built using chosen options or defaults if no overriding options have been selected.
```

2022-09-21 09:23 UTC, nadinequinr3 commented on simulator/api/src/main/kotlin/net/corda/simulator/factories/SimulatorConfigurationBuilder.kt
> +         * @return a factory for building [net.corda.simulator.SimulatorConfiguration]
```suggestion
         * @return A factory for building [net.corda.simulator.SimulatorConfiguration].
```

2022-09-21 09:23 UTC, nadinequinr3 commented on simulator/api/src/main/kotlin/net/corda/simulator/factories/SimulatorDelegateFactory.kt
> +     * @param configuration the configuration with which to construct [net.corda.simulator.Simulator]
```suggestion
     * @param configuration The configuration with which to construct [net.corda.simulator.Simulator].
```

2022-09-21 09:23 UTC, nadinequinr3 commented on simulator/api/src/main/kotlin/net/corda/simulator/factories/SimulatorDelegateFactory.kt
> +     * @return a [net.corda.simulator.Simulator] delegate
```suggestion
     * @return A [net.corda.simulator.Simulator] delegate.
```

2022-09-21 09:23 UTC, nadinequinr3 commented on simulator/api/src/main/kotlin/net/corda/simulator/tools/FlowChecker.kt
> +     * and was required
```suggestion
     * and was required.
```

2022-09-21 09:23 UTC, nadinequinr3 commented on simulator/api/src/main/kotlin/net/corda/simulator/tools/FlowChecker.kt
> +     * found with its accompanying protocol and was required
```suggestion
     * found with its accompanying protocol and was required.
```

2022-09-21 09:23 UTC, nadinequinr3 commented on simulator/api/src/main/kotlin/net/corda/simulator/tools/FlowChecker.kt
> +     * recognized flow class
```suggestion
     * recognized flow class.
```

2022-09-21 09:23 UTC, nadinequinr3 commented on simulator/api/src/main/kotlin/net/corda/simulator/tools/FlowChecker.kt
> +     * [net.corda.v5.base.annotations.Suspendable] annotation on the `call` method
```suggestion
     * [net.corda.v5.base.annotations.Suspendable] annotation on the `call` method.
```

2022-09-21 09:23 UTC, nadinequinr3 commented on simulator/api/src/main/kotlin/net/corda/simulator/tools/FlowChecker.kt
> +         * @param flowClass the [Flow] to check
```suggestion
         * @param flowClass The [Flow] to check.
```

2022-09-21 11:33 UTC, nadinequinr3 approved these changes

2022-09-21 12:56 UTC, ronanbrowne approved these changes
LGTM

2022-09-21 12:58 UTC, merged