CORE-5375: vnode db rollback [part 1]
corda/corda-runtime-os pull request #2172
Opened 2022-09-20 18:20 UTC by benmcmahon100

Adds write only audit for the creation of cpk changelogs.

One issue encountered is if two cpis have the same file checksums internally, then JPA doesn't detect a change and increase the entity version.

This means that we can't add a pk on (cpiName, cpiVersion, cpiSignerSummaryHash, entityVersion)

2022-09-21 13:25 UTC, conalsmith-r3 commented on gradle.properties
> +cordaApiVersion=5.0.0.402-SNAPSHOT
Can now upgrade to 5.0.0.403-alpha-1663765303666

2022-09-21 13:30 UTC, conalsmith-r3 commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/persistence/database/DatabaseCpiPersistence.kt
> +        println(cpkDbChangeLogEntities.map { it.fileChecksum })
printlns

2022-09-21 13:37 UTC, conalsmith-r3 commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/persistence/database/DatabaseCpiPersistence.kt
> +            em.flush()
Why are you calling flush here? This shouldn't be necessary

2022-09-21 13:38 UTC, conalsmith-r3 commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/persistence/database/DatabaseCpiPersistence.kt
> +
Create some integration tests in DatabaseCpiPersistenceTest

2022-09-21 13:44 UTC, conalsmith-r3 commented on libs/virtual-node/cpi-datamodel/src/main/kotlin/net/corda/libs/cpi/datamodel/CpkDbChangeLogAuditEntity.kt
> +    @EmbeddedId
Will this even work at runtime? at present there is no primary key of this table so the JPA entity doesn't match up with the database table

2022-09-21 13:47 UTC, conalsmith-r3 commented on libs/virtual-node/cpi-datamodel/src/main/kotlin/net/corda/libs/cpi/datamodel/CpkDbChangeLogAuditEntity.kt
> +fun findDbChangeLogAuditForCpi(
Not a fan of functions like this inside the entity class, I'd prefer these to be in a repository, but its OK for now, I see CpkDbChangeLogEntity also does it

2022-09-21 13:47 UTC, driessamyn commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/persistence/database/DatabaseCpiPersistence.kt
>      }
Why do you need this rather than just persist them with the main update, like we do elsewhere, e.g.: https://github.com/corda/corda-runtime-os/blob/b7e3bc6f09a6fec707d722ed2ace42b2f2333135/components/configuration/configuration-write-service-impl/src/main/kotlin/net/corda/configuration/write/impl/writer/ConfigEntityWriter.kt#L44

2022-09-21 14:12 UTC, benmcmahon100 commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/persistence/database/DatabaseCpiPersistence.kt
>      }
Was trying to make it the same as how the config create/update stuff worked as those are separate functions, but I don't mind merging them in

2022-09-21 14:23 UTC, driessamyn commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/persistence/database/DatabaseCpiPersistence.kt
>      }
Which example are you looking at? The above link is the "config create/update stuff".

2022-09-21 14:23 UTC, driessamyn commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/persistence/database/DatabaseCpiPersistence.kt
>      }
I think having another DB query is wasteful and complicates things.

2022-09-21 14:30 UTC, benmcmahon100 commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/persistence/database/DatabaseCpiPersistence.kt
>      }
One issue I saw with doing that was it didn't seem to get an updated entity version, but I can retest that now and verify

2022-09-21 14:32 UTC, benmcmahon100 commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/persistence/database/DatabaseCpiPersistence.kt
> +
I added a test into there to test creating the audit entry with the normal one as well as updating it. I can add more, but that seemed to be the only test for it in the config audit code

2022-09-21 14:32 UTC, benmcmahon100 commented on libs/virtual-node/cpi-datamodel/src/main/kotlin/net/corda/libs/cpi/datamodel/CpkDbChangeLogAuditEntity.kt
> +    @EmbeddedId
Unsure, but I can remove the annotation to be safe. That sort of thing won't be visible without a smoke/e2eTest

2022-09-21 15:07 UTC, driessamyn commented on libs/virtual-node/cpi-datamodel/src/main/kotlin/net/corda/libs/cpi/datamodel/CpkDbChangeLogAuditEntity.kt
> +    @EmbeddedId
All of these things should be uncovered in integration tests. Please don't rely on smoke tests for _anything_!!
If a smoketest fails, it's a sign you're missing a unit and/or integration test!!

2022-09-21 15:28 UTC, benmcmahon100 commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/persistence/database/DatabaseCpiPersistence.kt
>      }
Observed the same behaviour either way (which is strange), so I've merged the operations together

2022-09-21 15:43 UTC, benmcmahon100 commented on libs/virtual-node/cpi-datamodel/src/main/kotlin/net/corda/libs/cpi/datamodel/CpkDbChangeLogAuditEntity.kt
> +    @EmbeddedId
I'm more inclined to just drop the lookup for now and have something there as a stand-in, as I'm not sure what the best primary key will actually be.

Looking at the other tables, they use a sequence to define the order which would be required on a primary key for this, but I don't think you can do a composite sequence to track multiple in one table

2022-09-21 16:22 UTC, driessamyn commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/persistence/database/DatabaseCpiPersistence.kt
>      }
You shouldn't have `@Version` on this entity as it you don't want optimistic locking on an append-only table. 
You'll need to set this field manually as the one in `cpk_db_change_log` will only be updated by Hibernate when it persists.

2022-09-21 21:18 UTC, benmcmahon100 commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/persistence/database/DatabaseCpiPersistence.kt
>      }
Ah that'd be what's causing the version number bug - I could've sworn I deleted that

2022-09-23 08:21 UTC, driessamyn requested changes
There are no tests covering the changes in `DatabaseCpiPersistence`.

2022-09-23 08:21 UTC, driessamyn commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/persistence/database/DatabaseCpiPersistence.kt
> +        if (changelogsDiffered) {
I don't understand this switch. Audit tables should _always_ be inserted into when the main table is inserted into or updated.

2022-09-23 08:21 UTC, driessamyn commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/persistence/database/DatabaseCpiPersistence.kt
> +                val inDb = em.find(CpkDbChangeLogEntity::class.java, it.id)
This DB operation is not necessary and wasteful.

2022-09-23 08:21 UTC, driessamyn commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/persistence/database/DatabaseCpiPersistence.kt
> +            log.info("Updating Changelogs")
I think this log statement is not useful. Maybe as `debug` level, but then I would add more information about which changelogs are being updated.

2022-09-23 08:21 UTC, driessamyn commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/persistence/database/DatabaseCpiPersistence.kt
> +            log.info("Updating Changelogs")
As above, this log statement is not useful. In particularly as it is identical to the one above.

2022-09-23 08:21 UTC, driessamyn commented on libs/virtual-node/cpi-datamodel/src/integrationTest/kotlin/net/corda/libs/cpi/datamodel/tests/CpkDbChangeLogEntityTest.kt
> +                .isNotEqualTo(loadedDbLogAuditEntity)
This assert is odd. You're loading the DbLogEntity and converting it to an audit log entity and then verifying that it is _not_ equal to the audit entity from the DB.
That seems like a pretty useless assertion.

2022-09-23 08:21 UTC, driessamyn commented on libs/virtual-node/cpi-datamodel/src/integrationTest/kotlin/net/corda/libs/cpi/datamodel/tests/CpkDbChangeLogEntityTest.kt
> +            loadedDbLogEntity.isDeleted = !loadedDbLogEntity.isDeleted
huh?

2022-09-23 08:21 UTC, driessamyn commented on libs/virtual-node/cpi-datamodel/src/integrationTest/kotlin/net/corda/libs/cpi/datamodel/tests/CpkDbChangeLogEntityTest.kt
> +            val loadedDbLogAuditEntity = findDbChangeLogAuditForCpi(
```suggestion
            val loadedDbLogAuditEntities = findDbChangeLogAuditForCpi(
```

2022-09-23 08:21 UTC, driessamyn commented on libs/virtual-node/cpi-datamodel/src/main/kotlin/net/corda/libs/cpi/datamodel/CpkDbChangeLogAuditEntity.kt
> +    @EmbeddedId
For the DB, I think the natural key is fine (the same PK as the main table + Version).
For the JPA entity, it probably doesn't matter too much as it's append only and we don't need any one-to-many or many-to-one mappings.

2022-09-23 08:21 UTC, driessamyn commented on libs/virtual-node/cpi-datamodel/src/main/kotlin/net/corda/libs/cpi/datamodel/CpkDbChangeLogAuditEntity.kt
> +fun findDbChangeLogAuditForCpi(
I don't mind this. To me, these are very similar to stored procs (and in fact, this could be a named query). But I don't feel strongly about it either way. Definitely rather here than in the component that consumes this.

2022-09-23 08:21 UTC, driessamyn commented on libs/virtual-node/cpi-datamodel/src/main/kotlin/net/corda/libs/cpi/datamodel/CpkDbChangeLogAuditEntity.kt
> +    // TODO - what order should we return?
Is this todo valid? Does it need an order? If so, it should be made clear in the function name. I'd say it's ok for this not to have an order specified as we're talking relatively small sets.

2022-09-23 08:21 UTC, driessamyn commented on libs/virtual-node/cpi-datamodel/src/integrationTest/kotlin/net/corda/libs/cpi/datamodel/tests/CpkDbChangeLogEntityTest.kt
> +                .isEqualTo(loadedDbLogAuditEntity.last().id.entityVersion)
This makes an assumption on the order of objects returned by the `findDbChangeLogAuditForCpi` function which is incorrect.

2022-09-23 12:54 UTC, benmcmahon100 commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/persistence/database/DatabaseCpiPersistence.kt
> +        if (changelogsDiffered) {
It breaks if you try force reupload a previous CPI, as the pk columns will be duplicated. Though it'd be possible to get around that with a seq column if that's the best thing to do?

2022-09-23 12:55 UTC, benmcmahon100 commented on libs/virtual-node/cpi-datamodel/src/integrationTest/kotlin/net/corda/libs/cpi/datamodel/tests/CpkDbChangeLogEntityTest.kt
> +            loadedDbLogEntity.isDeleted = !loadedDbLogEntity.isDeleted
This is just to cause some change so the merge increases the entity version

2022-09-23 12:56 UTC, benmcmahon100 commented on libs/virtual-node/cpi-datamodel/src/main/kotlin/net/corda/libs/cpi/datamodel/CpkDbChangeLogAuditEntity.kt
> +    // TODO - what order should we return?
It's inherited from the non audity entry, but maybe it's less relevant here

2022-09-23 14:11 UTC, driessamyn commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/persistence/database/DatabaseCpiPersistence.kt
> +        if (changelogsDiffered) {
But if you do a force-upload, the version field should change if there is a change, if not, we shouldn't do a merge.
I.e. what I'm saying is that they always should go together.

2022-09-23 14:11 UTC, driessamyn commented on libs/virtual-node/cpi-datamodel/src/main/kotlin/net/corda/libs/cpi/datamodel/CpkDbChangeLogAuditEntity.kt
> +    // TODO - what order should we return?
Remove it if it's not relevant.

2022-09-23 14:13 UTC, driessamyn commented on libs/virtual-node/cpi-datamodel/src/integrationTest/kotlin/net/corda/libs/cpi/datamodel/tests/CpkDbChangeLogEntityTest.kt
> +            loadedDbLogEntity.isDeleted = !loadedDbLogEntity.isDeleted
It looks odd and leaves the reader of the code wondering what the signficance is of swapping the deleted state. Make a more obvious change like the content or something.

2022-09-27 13:11 UTC, benmcmahon100 commented on libs/virtual-node/cpi-datamodel/src/integrationTest/kotlin/net/corda/libs/cpi/datamodel/tests/CpkDbChangeLogEntityTest.kt
> +                .isEqualTo(loadedDbLogAuditEntity.last().id.entityVersion)
Function now returns a deterministic order

2022-09-27 13:24 UTC, benmcmahon100 commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/persistence/database/DatabaseCpiPersistence.kt
> +                val inDb = em.find(CpkDbChangeLogEntity::class.java, it.id)
Trying to combine the db operations ends up having the audit step recording the wrong entityVersion. So you end up with `0 > 1 > 3 > 5 > ...` instead of `0 > 2 > 4 > 6 > ...`

2022-09-27 13:24 UTC, benmcmahon100 commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/persistence/database/DatabaseCpiPersistence.kt
> +        if (changelogsDiffered) {
Fixed the entity version and removed this check

2022-09-27 13:36 UTC, driessamyn commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/persistence/database/DatabaseCpiPersistence.kt
> +                val inDb = em.find(CpkDbChangeLogEntity::class.java, it.id)
That's fixable.

2022-09-27 13:59 UTC, benmcmahon100 commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/persistence/database/DatabaseCpiPersistence.kt
> +                val inDb = em.find(CpkDbChangeLogEntity::class.java, it.id)
I'm not sure how without flushing on every merge which seems even more wasteful. Is there some other way I can get it?

2022-09-27 14:13 UTC, conalsmith-r3 commented on libs/virtual-node/cpi-datamodel/src/main/kotlin/net/corda/libs/cpi/datamodel/CpkDbChangeLogAuditEntity.kt
> +    var cpkVersion: String,
missing cpkSignerSummaryHash

2022-09-28 16:11 UTC, vkolomeyko commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/validation/ValidationFunctions.kt
> +        log.error("$ex")
```suggestion
        log.error("Unexpected error when persisting CPI to the database", ex)
```

2022-09-28 16:12 UTC, benmcmahon100 commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/validation/ValidationFunctions.kt
> +        log.error("$ex")
Sure, was debating adding a caused by bit too, but wanted to get a green build

2022-09-29 08:15 UTC, driessamyn commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/persistence/database/DatabaseCpiPersistence.kt
> +                val inDb = em.find(CpkDbChangeLogEntity::class.java, it.id)
You know what the version number is going to be (current +1) and you know what if there is a concurrency issue the main entity update will fail, so it should roll back the entire transaction.

2022-09-29 08:17 UTC, driessamyn commented on components/chunking/chunk-db-write-impl/src/integrationTest/kotlin/net/corda/chunking/db/impl/tests/DatabaseCpiPersistenceTest.kt
> +        assertThat(updatedChangelogAudits.size).isEqualTo(2)
I think you ought to extend the asserts to validate the correct data has been persisted.

2022-09-29 08:17 UTC, driessamyn commented on components/chunking/chunk-db-write-impl/src/integrationTest/kotlin/net/corda/chunking/db/impl/tests/DatabaseCpiPersistenceTest.kt
> +        assertThat(updatedChangelogAudits.size).isEqualTo(3)
As above.

2022-09-29 08:19 UTC, driessamyn commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/validation/ValidationFunctions.kt
> +        log.error("Unexpected error when persisting CPI to the database", ex)
This shouldn't be `error` level as it could be a user error.

2022-09-29 08:23 UTC, driessamyn commented on libs/virtual-node/cpi-datamodel/src/integrationTest/kotlin/net/corda/libs/cpi/datamodel/tests/CpkDbChangeLogEntityTest.kt
> +                .isEqualTo(loadedDbLogAuditEntity!!.id.cpkName)
Maybe extend the asserts to validate all fields?

2022-09-29 08:23 UTC, driessamyn commented on libs/virtual-node/cpi-datamodel/src/integrationTest/kotlin/net/corda/libs/cpi/datamodel/tests/CpkDbChangeLogEntityTest.kt
> +                .isEqualTo(loadedDbLogAuditEntities.last().id.entityVersion)
This still assumes an order to the results.

2022-09-29 08:23 UTC, driessamyn commented on libs/virtual-node/cpi-datamodel/src/main/kotlin/net/corda/libs/cpi/datamodel/CpkDbChangeLogAuditEntity.kt
> +        "ORDER BY changelog.id.entityVersion",
I would remove the `order by` clause or if you leave it in, you have to make sure from the function signature that there is a guaranteed order.
But the sets are so small that it may not be worth introducing this risk of a refactoring changing the order without realising other code depends on it.

2022-09-29 09:20 UTC, benmcmahon100 commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/persistence/database/DatabaseCpiPersistence.kt
> +                val inDb = em.find(CpkDbChangeLogEntity::class.java, it.id)
That's not always the case, though. In a true update, it should just be a +1 to mark it as deleted, as the second operation will be an insert.

2022-09-29 09:20 UTC, benmcmahon100 commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/validation/ValidationFunctions.kt
> +        log.error("Unexpected error when persisting CPI to the database", ex)
Is `warn` more appropriate?

2022-09-29 09:31 UTC, driessamyn commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/validation/ValidationFunctions.kt
> +        log.error("Unexpected error when persisting CPI to the database", ex)
If it's a user error, I think info is actually enough. If it's an error caused by the platform, then error is ok.

2022-09-29 09:32 UTC, driessamyn commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/persistence/database/DatabaseCpiPersistence.kt
> +                val inDb = em.find(CpkDbChangeLogEntity::class.java, it.id)
So in which case is it not +1 ?

2022-09-29 09:34 UTC, benmcmahon100 commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/persistence/database/DatabaseCpiPersistence.kt
> +                val inDb = em.find(CpkDbChangeLogEntity::class.java, it.id)
When you persist a cpk initially, it'll be version 0, as the mark as deleted is a noop, and the update just persists them normally. Both code paths use this function ATM

2022-09-29 09:38 UTC, benmcmahon100 commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/validation/ValidationFunctions.kt
> +        log.error("Unexpected error when persisting CPI to the database", ex)
Changed it to be info for now, seeing as how we don't know for sure at that stage whether it was user or platform error. Should be addressed in CORE-6205

2022-09-29 09:40 UTC, driessamyn commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/persistence/database/DatabaseCpiPersistence.kt
> +                val inDb = em.find(CpkDbChangeLogEntity::class.java, it.id)
Yes, so when it's a new one, it's 0 (which could be -1 +1) and otherwise always +1.

2022-09-29 13:21 UTC, vkolomeyko commented on gradle.properties
> +cordaApiVersion=5.0.0.404-alpha-1664379547680
Gentle reminder: We will need to revert to beta version once changes to `corda-api` PR merged.

2022-09-29 13:41 UTC, vkolomeyko commented on libs/virtual-node/cpi-datamodel/src/main/kotlin/net/corda/libs/cpi/datamodel/CpkDbChangeLogAuditEntity.kt
> +        "FROM ${CpkDbChangeLogAuditEntity::class.simpleName} AS changelog INNER JOIN " +
Do we need `INNER JOIN` on `CpiCpkEntity`?

I.e. why cannot we just execute `select` on `CpkDbChangeLogAuditEntity`?

2022-09-29 13:41 UTC, vkolomeyko commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/persistence/database/DatabaseCpiPersistence.kt
> +        // This is required to make sure we get the right entity version for the given
```suggestion
        // This is required to make sure we get the right entity version for the given CpkDbChangeLogEntity
```

2022-09-29 13:41 UTC, vkolomeyko commented on libs/virtual-node/cpi-datamodel/src/main/kotlin/net/corda/libs/cpi/datamodel/CpkDbChangeLogEntity.kt
> +    var content: String,
Why it was necessary to make this change, please?

2022-09-29 13:51 UTC, vkolomeyko commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/persistence/database/DatabaseCpiPersistence.kt
> +     * Update the changelogs in the db for force upload
I do not think the call to this method is happening **only** during force CPI upload, therefore: 

```suggestion
     * Update the changelogs in the db during CPI upload
```

2022-09-29 13:51 UTC, vkolomeyko commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/persistence/database/DatabaseCpiPersistence.kt
> +     * @property cpi: [Cpi] is the Cpi that has just been forceUploaded
```suggestion
     * @property cpi: [Cpi] is the Cpi that has just been uploaded
```

2022-09-29 16:29 UTC, driessamyn commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/persistence/database/DatabaseCpiPersistence.kt
> +        val changeLogUpdates = cpkDbChangeLogEntities.associateBy { it.id }
The comments are not accurate anymore.

2022-09-29 16:29 UTC, driessamyn commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/persistence/database/DatabaseCpiPersistence.kt
> +                val inDb = em.find(CpkDbChangeLogEntity::class.java, changelogId)
Are these not in `allChangelogs`?

2022-09-29 16:29 UTC, driessamyn commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/persistence/database/DatabaseCpiPersistence.kt
> +                log.info("THIS IS THE NEW CHANGELOG ${ret.id.cpkName} ${ret.id.cpkName} ${ret.id.cpkName} ${ret.entityVersion}")
info -> debug (and remove caps)

2022-10-03 13:27 UTC, benmcmahon100 commented on libs/virtual-node/cpi-datamodel/src/main/kotlin/net/corda/libs/cpi/datamodel/CpkDbChangeLogEntity.kt
> +    var content: String,
Primarily for an integration test as @driessamyn thought marking as deleted instead looked odd

2022-10-03 13:28 UTC, benmcmahon100 commented on libs/virtual-node/cpi-datamodel/src/main/kotlin/net/corda/libs/cpi/datamodel/CpkDbChangeLogAuditEntity.kt
> +        "FROM ${CpkDbChangeLogAuditEntity::class.simpleName} AS changelog INNER JOIN " +
I just took the functionality from the non audit class in order to have them behave the same

2022-10-03 15:04 UTC, benmcmahon100 commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/persistence/database/DatabaseCpiPersistence.kt
> +                val inDb = em.find(CpkDbChangeLogEntity::class.java, changelogId)
Renamed from clarity

2022-10-03 16:08 UTC, vkolomeyko commented on libs/virtual-node/cpi-datamodel/src/main/kotlin/net/corda/libs/cpi/datamodel/CpkDbChangeLogAuditEntity.kt
> +        "FROM ${CpkDbChangeLogAuditEntity::class.simpleName} AS changelog INNER JOIN " +
Sure, appreciate this. But is there any practical reason for `INNER JOIN` we can think of?

Possibly, @dickon would know why it was introduced in the first place?

2022-10-03 16:15 UTC, vkolomeyko commented on libs/virtual-node/cpi-datamodel/src/main/kotlin/net/corda/libs/cpi/datamodel/CpkDbChangeLogEntity.kt
> +    var content: String,
But if in production code we never update `content`, perhaps making it `var` just for the sake of integration test would be an over-kill?

On the other hand in production code we do change `isDeleted` attribute (e.g. in `DatabaseCpiPersistence#updateChangeLogs`) therefore IMO there should be nothing wrong with updating it in the integration test, if all we are doing is updating a field.

@driessamyn - WDYT?

2022-10-04 07:39 UTC, driessamyn reviewed
Couple more minor comments.

The logic still seems a bit convoluted, and I think there may still be too many DB queries.

2022-10-04 07:39 UTC, driessamyn commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/persistence/database/DatabaseCpiPersistence.kt
> +                val inDb = em.find(CpkDbChangeLogEntity::class.java, changelogId)
This queries the DB for each changeLog?
That seems wasteful.

2022-10-04 07:39 UTC, driessamyn commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/persistence/database/DatabaseCpiPersistence.kt
>          }
Is this still needed or can this be folded in the below logic?

2022-10-04 07:39 UTC, driessamyn commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/persistence/database/DatabaseCpiPersistence.kt
> +                        log.info("They're the same")
This isn't a good log message. Info level is probably the wrong level as well.

2022-10-04 07:39 UTC, driessamyn commented on libs/virtual-node/cpi-datamodel/src/main/kotlin/net/corda/libs/cpi/datamodel/CpkDbChangeLogAuditEntity.kt
> +        "FROM ${CpkDbChangeLogAuditEntity::class.simpleName} AS changelog INNER JOIN " +
I agree. The join seems unnecessary. It is possible the entity structure changed and that it used to be needed for the where clause.

2022-10-04 07:39 UTC, driessamyn commented on libs/virtual-node/cpi-datamodel/src/main/kotlin/net/corda/libs/cpi/datamodel/CpkDbChangeLogEntity.kt
> +    var content: String,
Makes sense. The test looked confusion, because it flipped the flag and it wasn't clear why. I'd just set it to a hardcoded `true` rather than be clever about it.

2022-10-04 08:07 UTC, benmcmahon100 commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/persistence/database/DatabaseCpiPersistence.kt
> +                val inDb = em.find(CpkDbChangeLogEntity::class.java, changelogId)
That's the same as before, but I can take another look to see can I get it to work without it

2022-10-04 08:08 UTC, benmcmahon100 commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/persistence/database/DatabaseCpiPersistence.kt
>          }
Let me take a look and see what I can do

2022-10-04 08:08 UTC, benmcmahon100 commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/persistence/database/DatabaseCpiPersistence.kt
> +                        log.info("They're the same")
Yep that's something I missed in tidying up, will remove

2022-10-04 10:32 UTC, benmcmahon100 commented
@driessamyn @vkolomeyko WRT:
> I agree. The join seems unnecessary. It is possible the entity structure changed and that it used to be needed for the where clause.
We do need that join, as the audit and non audit entries don't have any reference to the CPI itself. That join connects the CPIS to the CPKs, and then in turn to the changelogs

2022-10-04 10:39 UTC, vkolomeyko commented on libs/virtual-node/cpi-datamodel/src/main/kotlin/net/corda/libs/cpi/datamodel/CpkDbChangeLogAuditEntity.kt
> +        "FROM ${CpkDbChangeLogAuditEntity::class.simpleName} AS changelog INNER JOIN " +
Noted a comment: https://github.com/corda/corda-runtime-os/pull/2172#issuecomment-1266742930
Marking this thread as resolved.

2022-10-04 10:42 UTC, vkolomeyko commented on libs/virtual-node/cpi-datamodel/src/main/kotlin/net/corda/libs/cpi/datamodel/CpkDbChangeLogEntity.kt
> -
Minor: This change is non-material and can be undone.

2022-10-04 10:48 UTC, benmcmahon100 commented on libs/virtual-node/cpi-datamodel/src/main/kotlin/net/corda/libs/cpi/datamodel/CpkDbChangeLogEntity.kt
> -
Thought it made the file more consistent

2022-10-04 11:09 UTC, driessamyn approved these changes
I think the below can still be optimised by replacing it with a single DB query, but happy for it to be merged as is in the interest of moving things on.

```
val inDb = em.find(CpkDbChangeLogEntity::class.java, changelogId)
```

2022-10-04 11:43 UTC, merged