CORE-4730 Integrate Uniqueness Checker Client service with message bus
corda/corda-runtime-os pull request #2191
Opened 2022-09-22 09:38 UTC by nkovacsx

### Overview

Added `UniquenessCheckExternalEventFactory` which will communicate with the uniquness checker through the `Schemas.UniquenessChecker.UNIQUENESS_CHECK_TOPIC` topic which was added by @relyafi in the latest PR.

This means a request of type `UniquenessCheckRequestAvro` will be put to the given topic and the `BatchedUniquenessChecker` will reply with a `UniquenessCheckResult` which is NOT an avro object.
After that result is received by the client service it will sign if necessary and return the response to the flow.

Since we had `@ServiceRanking` annotations on the fake uniqueness checker and backing store I had to move that annotation to the "real" implementations so OSGi can pick those up.

### Testing

The smoke test which calls a dummy uniqueness flow was run and the data in the backing store database was verified.
<img width="1215" alt="Screenshot 2022-09-22 at 10 18 55" src="https://user-images.githubusercontent.com/57627796/191713113-7428ab79-f86a-4f2b-b048-82f96dfbcebe.png">
<img width="1217" alt="Screenshot 2022-09-22 at 10 19 10" src="https://user-images.githubusercontent.com/57627796/191713132-ab71570b-a8c6-4b43-9a37-a519952be930.png">

The instantiated backing store/uniqueness checker type was also verified from the logs:
`2022-09-22 09:48:52.470 [lifecycle-coordinator-26] INFO  net.corda.uniqueness.backingstore.impl.JPABackingStoreImpl - Backing store is UP`

`2022-09-22 09:48:52.470 [lifecycle-coordinator-26] INFO  net.corda.uniqueness.checker.impl.BatchedUniquenessCheckerImpl - Uniqueness checker is UP`

Also flow outcome was verified too from the logs:
```
2022-09-22 09:56:00.424 [single-threaded-scheduled-executor-1] INFO  net.cordapp.flowworker.development.testflows.UniquenessCheckTestFlow - Uniqueness check for consume transaction was successful, signature: DigitalSignatureAndMetadata(signature=[3045022100E42FA0236F61D6F2D13D47534F0118966825169711158F102AFBF14583711C3002206F548D2620DBAD907BD714EF89EADBB331A66B8C0B785A4BADC79A6CFC79C307], metadata=DigitalSignatureMetadata(timestamp=2022-09-22T08:56:00.424556Z, properties={platformVersion=10}))
2022-09-22 09:56:00.424 [Thread-90] INFO  net.corda.flow.pipeline.impl.FlowEventPipelineImpl - Postprocessing of FlowFinished(result="Uniqueness Check operation complete.")
```

2022-09-23 09:37 UTC, relyafi requested changes
Some minor comments, but generally looks good. I also think it would be worth clarifying a couple of things in the PR overview:

- _the BatchedUniquenessChecker will reply with a UniquenessCheckResult which is NOT an avro object_ I don't think this is true, this responds with an avro response message, and the client logic translates that into the non-avro result?
- _Since we had @ServiceRanking annotations on the fake uniqueness checker and backing store I had to move that annotation to the "real" implementations so OSGi can pick those up._ Not sure this is necessary anymore now the underlying issue (incorrect inclusion of test libraries in real implementations) has been resolved.

2022-09-23 09:37 UTC, relyafi commented on testing/uniqueness/backing-store-fake/src/main/kotlin/net/corda/uniqueness/backingstore/impl/fake/BackingStoreImplFake.kt
> -@ServiceRanking(Int.MAX_VALUE)
Why do we still need to remove this given we are (correctly) no longer pulling in these test modules into the real code? These rankings ensure that if we are using an injectable service in tests that these implementations are preferred over the real implementations.

2022-09-23 09:37 UTC, relyafi commented on testing/uniqueness/uniqueness-checker-fake/src/main/kotlin/net/corda/uniqueness/checker/impl/fake/UniquenessCheckerImplFake.kt
> -@ServiceRanking(Int.MAX_VALUE)
Same as other file

2022-09-23 09:37 UTC, relyafi commented on components/uniqueness/uniqueness-checker-client-service-impl/src/main/kotlin/net/corda/uniqueness/client/impl/UniquenessCheckClientExternalEventFactory.kt
> +data class RequestUniquenessCheck(
Is there a reason we need this vs just using `UniquenessCheckRequestAvro`, or pulling out and reusing `UniquenessCheckRequestInternal`?

2022-09-23 09:37 UTC, relyafi commented on components/uniqueness/uniqueness-checker-client-service-impl/src/main/kotlin/net/corda/uniqueness/client/impl/UniquenessCheckerClientServiceImpl.kt
>  class UniquenessCheckerClientServiceImpl @Activate constructor(
I should probably have mentioned this on the previous review when we introduced this class - but as this is implementing the Ledger specific service, should this be called `LedgerUniquenessCheckerClientServiceImpl`?

We may also want to reconsider the types being passed in on `requestUniquenessCheck` - if this is ledger specific it may make more sense to take in ledger objects such as secure hashes and state refs and then do the conversion to primitive types internally, in order to be more defensive against bad data being passed in.

2022-09-23 09:37 UTC, relyafi commented on components/uniqueness/uniqueness-checker-client-service-impl/src/main/kotlin/net/corda/uniqueness/client/impl/UniquenessCheckerClientServiceImpl.kt
> +        val txIds = listOf(SecureHash.parse(txId))
We only use this once, so I'd be tempted to simply inline this where it is used. It also avoids a bit of confusion (having a variable called txIds when we only ever sign one at a time is a bit misleading).

I expect down the line this code will be replaced with another external events call to sign, but this would presumably still be one at a time (the other end would do the batching).

2022-09-23 11:46 UTC, nkovacsx commented on testing/uniqueness/backing-store-fake/src/main/kotlin/net/corda/uniqueness/backingstore/impl/fake/BackingStoreImplFake.kt
> -@ServiceRanking(Int.MAX_VALUE)
I see what you mean, good point, I’ll keep this annotation in place.

2022-09-23 13:02 UTC, nkovacsx commented on components/uniqueness/uniqueness-checker-client-service-impl/src/main/kotlin/net/corda/uniqueness/client/impl/UniquenessCheckClientExternalEventFactory.kt
> +data class RequestUniquenessCheck(
`UniquenessCheckRequestAvro` cannot be used in external events because it is an avro object. I wanted to use `UniquenessCheckRequestInternal` in the first place but it has `SecureHash` and `UniquenessCheckStateRef` as a representation and I'm not sure if it's worth converting back-and-forth rather than just creating a new data class.

2022-09-23 13:03 UTC, nkovacsx commented on components/uniqueness/uniqueness-checker-client-service-impl/src/main/kotlin/net/corda/uniqueness/client/impl/UniquenessCheckerClientServiceImpl.kt
>  class UniquenessCheckerClientServiceImpl @Activate constructor(
Yeah since we moved away from it being generic I'm happy to use `SecureHash` and state ref objects if you prefer that.

2022-09-23 13:06 UTC, nkovacsx commented on components/uniqueness/uniqueness-checker-client-service-impl/src/main/kotlin/net/corda/uniqueness/client/impl/UniquenessCheckClientExternalEventFactory.kt
> +data class RequestUniquenessCheck(
However, if we want to change the signature of `requestUniquenessCheck` we can easily use `UniquenessCheckRequestInternal` without back and forth conversions.

2022-09-23 13:25 UTC, relyafi commented on components/uniqueness/uniqueness-checker-client-service-impl/src/main/kotlin/net/corda/uniqueness/client/impl/UniquenessCheckerClientServiceImpl.kt
>  class UniquenessCheckerClientServiceImpl @Activate constructor(
Maybe worth quickly checking with Matthew, but yeah I'd suggest lets use the specific types since we have now made this particular interface + impl ledger specific.

2022-09-23 13:27 UTC, relyafi commented on components/uniqueness/uniqueness-checker-client-service-impl/src/main/kotlin/net/corda/uniqueness/client/impl/UniquenessCheckClientExternalEventFactory.kt
> +data class RequestUniquenessCheck(
I see your point, I think the difficulty is that we (correctly) are not tied to ledger on the internal object, because that side of things we don't want a dependency on ledger. So there would still need to be a conversion from `StateRef` to `UniquenessCheckStateRef`.

So think I'm happy to keep this separate, but think we should consider renaming - `RequestUniquenessCheck` is the same as `UniquenessCheckRequest` in a different order, which may be very confusing to people. Maybe something like `UniquenessCheckExternalEventParams` would be more specific and clear?

2022-09-26 08:58 UTC, nkovacsx commented on components/uniqueness/uniqueness-checker-client-service-impl/src/main/kotlin/net/corda/uniqueness/client/impl/UniquenessCheckerClientServiceImpl.kt
>  class UniquenessCheckerClientServiceImpl @Activate constructor(
After discussing this with @mnesbit the signature of `requestUniquenessCheck` will stay as it is for now. I'll rename the service implementation to `LedgerUniquenessCheckerClientServiceImpl`.

2022-09-26 16:17 UTC, relyafi approved these changes
LGTM

2022-09-26 19:16 UTC, ronanbrowne approved these changes
LGTM (build changes)

2022-09-27 08:00 UTC, merged