CORE-6149: Add integration and unit tests for notary JPA backing store
corda/corda-runtime-os pull request #2211
Opened 2022-09-23 14:50 UTC by r3hj

### Overview
This PR adds both integration tests and unit-tests for notary JPA backing store implementation. Only tests are added and no changes' been made on the backing store implementation. Any issues and improvements found will/should be handled as a separate PR.

### Code coverage
Intellij coverage data by both integration tests and unit-tests were used to identify and increase coverage area. 

#### Coverage set up
For running integration tests with coverage, the following classes should be excluded in the Intellij configuration.
* `org.hibernate.hql.internal.antlr.HqlTokenTypes`
* `org.hibernate.hql.internal.antlr.SqlTokenTypes`
* `org.hibernate.sql.ordering.antlr.GeneratedOrderByFragmentRendererTokenTypes`

#### Statistics
* Integration tests: **83%**/**90%**/**85%** for class, method and line respectively
* Unit tests: **83%**/**85%**/**86%** for class, method and line respectively

### Changes
* `JPABackingStoreImplIntegrationTests` for integration tests using HSQLDB (default) and PostgreSQL
* `JPABackingStoreImplTests` for unit-tests

2022-09-30 09:18 UTC, r3hj commented
[int-tests cov 0930.zip](https://github.com/corda/corda-runtime-os/files/9682665/int.cov.0930.zip)
[unit-tests cov 0930.zip](https://github.com/corda/corda-runtime-os/files/9682666/unittests.cov.0930.zip)
[combined cov 0930.zip](https://github.com/corda/corda-runtime-os/files/9682667/combined.cov.0930.zip)

2022-09-30 14:09 UTC, relyafi requested changes
Some general comments beyond those raised inline in the code:

- There are many examples of overly complex boiler plate code in functions and tests, mostly relating to id setup and lists. This mostly appears to be down to using an imperative programming approach rather than using the functional approach supported by Kotlin, which allows for far more succinct code. I've listed a number of examples and made a couple of suggestions in some comments as to how these could be streamlined, but I'd suggest a self review of the entire PR is required to systematically review the code and simplify where applicable.
- Similarly, there are a number of instances of inappropriate use of implementations instead of interfaces, for example, there's a lot of usage of `LinkedList` where `List` would suffice. I've commented on some instances of these, but this also needs systemic self review to check that all uses of implementations are really necessary.
- There is a lot of code in the unit tests that is a duplicate of the integration test code. Rather than raise duplicate comments, I've raised a number of comments in the integration tests. Please self review and also resolve these in the unit tests where applicable.
- Most of the unit tests appear to be redundant, as they are either testing implementation detail (not behavior) or are tested by integration tests which are of higher value for this class. It has been stated repeatedly not to duplicate test cases, so for the test cases marked as redundant / duplicated, please either remove these, or provide a justification for what value they are adding over the integration tests.

2022-09-30 14:09 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/main/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImpl.kt
> +    private val schemaMigrator: LiquibaseSchemaMigrator = LiquibaseSchemaMigratorImpl()
I think this _should_ be ok, but we should have a manual test (and document this in the PR test notes) to sanity check that we are able to start a combined worker locally, and / or the DB worker in a cluster setup to ensure that these do successfully start. Instructions for the latter can be found here: https://github.com/corda/corda-runtime-os/wiki/Local-development-with-Kubernetes

2022-09-30 14:09 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +    private val maxAttemptsCnt = 10 // Set it same as "MAX_ATTEMPTS" in JPABackingStoreImpl.kt
Think this should be a const

2022-09-30 14:09 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +    }
```suggestion
    private fun generateSecureHashes(cnt: Int) = List(cnt) { SecureHashUtils.randomSecureHash() }
```

Could be simplified to the above. This is then sufficiently trivial that I'd question whether it's worth a dedicated function, or if we just inline the above in your tests.

If we do want a separate function, I'd suggest moving it to a common `listOfRandomSecureHashes` function in `SecureHashUtils`, as this function is duplicated in the unit tests.

2022-09-30 14:09 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +    }
This function doesn't really make any sense to me. Using `let` in this way seems inappropriate and over-complicated. It also looks like there's a misunderstanding of how state refs should be generated - for a given tx id, state refs would always start at 0, and then go to 1, 2 etc if we had multiple output states produced for a given transaction id. This looks like if it is given hashes (transaction ids) A, B and C it will generate A:0, B:1 and C:2, whereas realistic behaviour would be A:0, B:0, C:0. The function also lacks the ability to produce multiple state references for a given transaction.

If all we want to do is generate a single state for each tx id, then we can simplify the whole thing with the below suggestion. We can either hard-code 0, or choose a random integer between 0 and 32k if we want to test "random" values.

```suggestion
    private fun generateUniquenessCheckStateRef(hashes: List<SecureHash>): List<UniquenessCheckStateRef> =
        hashes.map { UniquenessCheckStateRefImpl(it, 0) }
```

As with `generateSecureHashes`, I think it becomes questionable whether this is adding any value, especially since some test cases only have the one tx id to begin with.

2022-09-30 14:09 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +    private fun generateUniquenessCheckStateRef(hashes: LinkedList<SecureHash>): LinkedList<UniquenessCheckStateRef> {
General observation - there are a number of instances in these PR's where we are using implementations instead of interfaces in parameters and return values. In this instance, there's no reason not to use `List` instead of `LinkedList`.

I'd suggest self-reviewing the whole PR yourself and correcting all instances of this pattern.

2022-09-30 14:09 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +    }
The backing store never interacts with Avro objects, only the internal ones, so why not just create the internal objects directly and avoid the extra complexity?

I'm assuming the reason is the constructor on the internal class is private. This may be an argument to make it public. I'm not generally in favor of changing scope simply for testing purposes, but it's just a data class so there's probably no harm in this and I don't see a reason why it needs to be private.

2022-09-30 14:09 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +            }
I think you should self-review whether you need all this code, based on the fact there's only one transaction, and also whether we can simplify the code in a similar way to what was suggested earlier in `generateSecureHashes` / `generateUniquenessCheckStateRef`

2022-09-30 14:09 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +                result.forEach { secureHashTxnDetails ->
There's only one element, so we could just use first / single etc.

2022-09-30 14:09 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +                    assertTrue(secureHashTxnDetails.value.result.toCharacterRepresentation() == 'A')
For multiple assertions like this, consider using `assertAll`, `assertEquals`, `assertThat` and others as appropriate, which ensures we won't stop checking on the first failure. There are numerous examples in the existing uniqueness checker tests of how to use these.

This applies to multiple test cases in this PR, so please self-review all test cases to see if this applies.

2022-09-30 14:09 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +            )
Again, consider whether we really need this much code to achieve this.

2022-09-30 14:09 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +                    assertTrue(secureHashTxnDetails.value.result.toCharacterRepresentation() == 'R')
We should also check the result is of the expected type and it contains the expected information. We may be able to re-use the functions in `UniquenessAssertions` with some refactoring to overload / template the existing functions to handle either `UniquenessCheckResponseAvro` or `UniquenessCheckResult`.

2022-09-30 14:09 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +                        Clock.systemUTC().instant(), UniquenessCheckErrorGeneralImpl("some error")
This is only testing one specific type of error. I think there is value in testing each type of error (in different test cases) with populated fields and verifying their values when retrieved, since each has a different structure and could be serialized / deserialized from the database differently.

2022-09-30 14:09 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +                    assertTrue(secureHashTxnDetails.value.result.toCharacterRepresentation() == 'A')
I'd suggest using the constant definitions in `UniquenessConstants` rather than hard-coding the characters in these test cases.

2022-09-30 14:09 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +                }
Could probably be simplified using something like `hasSameElementsAs` or `containsExactlyInAnyOrderElementsOf`.

We should also be ensuring the state references of the stored states are null.

2022-09-30 14:09 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +            val consumingTxId: SecureHash = secureHashes[0]
This is wrong - we've used this transaction id already for generating the unconsumed state.

2022-09-30 14:09 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +                assertEquals(consumingTxId, filteredStates[consumingStateRef]?.consumingTxId)
It would probably be a more rigorous test to also check that the state that wasn't consumed still has a null `consumingTxId`.

2022-09-30 14:09 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +            val consumingStateRef = UniquenessCheckStateRefImpl(consumingTxId, 0)
Why not use `stateRefs[0]`?

2022-09-30 14:09 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +            val consumingTxId = secureHashes[0]
This is wrong - we've used this transaction id already for generating the unconsumed state.

2022-09-30 14:09 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +            val consumingStateRef = UniquenessCheckStateRefImpl(consumingTxId, 0)
Why not use `stateRefs[0]`?

2022-09-30 14:09 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +        fun `Double spend is prevented`() {
This is actually only testing one of two double spend scenarios. What happens if we try and spend the same state twice in the same `executeTransaction` block? That should also be tested.

2022-09-30 14:09 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +        )
I'm not convinced of the need for this to be a separate val, or a string to exception map as opposed to a list of exceptions. It's only used in one parameterised test, and it should be possible to simply use the exception as a parameter (either using class as the value source instead of string, or by using another source type).

2022-09-30 14:09 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +            // Find a way to mock a TypedQuery while make the logic JPA implementation agnostic.
Not sure what this means or why it needs to be JPA agnostic? We are testing the JPA backing store.

2022-09-30 14:09 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/test/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplTests.kt
> +        }
I'm not sure these test cases are really adding value, beyond coverage. It would be much better if we were testing this in integration tests with a real lifecycle, but appreciate that is much more involved.

At the least we should look through other tests in the codebase which are mocking the lifecycle co-ordinator for inspiration - they take a similar approach to this but are also checking that things like `updateStatus` are called. I see there are some later tests that do this so it may be a case of combining the logic of the tests to have more meaningful test cases.

I also note there is a `LifecycleTest` class that is used by some unit tests, which superficially looks like it is acting as a mock / fake. This may be worth investigating as a way of more meaningfully testing this functionality.

2022-09-30 14:09 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/test/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplTests.kt
> +                    "This test fails because life cycle status is not updated to UP upon receiving StartEvent."
Which is expected behaviour, because the state of this is dependent on it's dependencies and is set to up later when `RegistrationStatusChangeEvent` is received.

2022-09-30 14:09 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/test/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplTests.kt
> +                    "This test fails because life cycle status is not updated to DOWN upon receiving StopEvent."
Same as `StartEvent`.

2022-09-30 14:09 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/test/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplTests.kt
> +    inner class TransactionOpsTests {
This block of tests appears to be duplicating test cases from the integration tests, which as have been repeatedly stated are more valuable for this particular class. Writing to and retrieving from a real database is indirectly proving these test cases anyway.

2022-09-30 14:09 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/test/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplTests.kt
> +        @Test
Similarly, I believe this is already covered by the integration tests.

2022-09-30 14:09 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/test/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplTests.kt
> +        fun `Executing transaction retries upon expected exceptions`(exception: String) {
Similarly, I believe this is already covered by the integration tests.

2022-09-30 14:09 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/test/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplTests.kt
> +        fun `Executing transaction does not retry upon unexpected exception`() {
Similarly, I believe this is already covered by the integration tests.

2022-09-30 14:09 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/test/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplTests.kt
> +        fun `Executing transaction triggers rollback upon receiving expected exception if transaction is active`() {
Similarly, I believe this is already covered by the integration tests.

2022-09-30 14:09 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/test/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplTests.kt
> +        fun `Getting state details invokes correct query`() {
This is testing an implementation detail - why do we care what query is invoked as long as we get the correct details (which is already being tested in the integration tests)

2022-09-30 14:09 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/test/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplTests.kt
> +        fun `Getting transaction details invokes correct query for a successful result`() {
Similarly, I believe this is already covered by the integration tests.

2022-09-30 14:09 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/test/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplTests.kt
> +        fun `Getting transaction details invokes correct query for a failed result`() {
This is testing an implementation detail - why do we care what query is invoked as long as we get the correct details (which is already being tested in the integration tests)

2022-09-30 14:09 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/test/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplTests.kt
> +        fun `Getting transaction details invokes correct query for an invalid result`() {
This is testing an implementation detail - why do we care what query is invoked as long as we get the correct details (which is already being tested in the integration tests)

2022-09-30 14:09 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/test/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplTests.kt
> +        fun `Throw if no error detail is available for a failed transaction`() {
As an observation this is actually a useful test case because it is testing something that should be impossible to get in an integration test, short of directly editing the DB data post commit.

2022-09-30 14:51 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/test/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplTests.kt
> +        fun `Throw if no error detail is available for a failed transaction`() {
Thanks

2022-09-30 15:04 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +            // Find a way to mock a TypedQuery while make the logic JPA implementation agnostic.
Here "JPA implementation agnostic" means it shouldn't use specific DB implementation types such as Hibernate.

The mocking code says the exception will get thrown when invoking .createNamedQuery(). But the execution of the query happens at calling `.resultList`. I attempted to mock TypedQuery to simulate that behaviour but haven't been successful.

2022-09-30 15:09 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/main/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImpl.kt
> +    private val schemaMigrator: LiquibaseSchemaMigrator = LiquibaseSchemaMigratorImpl()
- [ ]  Update PR about running a manual test

2022-09-30 15:10 UTC, relyafi commented
@r3hj also another comment that I missed in the original review, I note we are missing integration test cases for the following that we discussed during our initial feedback meeting:

- Unable to connect to the database
- Have a database connection, but lack permissions to read and / or write

One way or the other these should be addressed, either by adding new cases, or explaining why these are not possible.

2022-09-30 15:15 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +    private val maxAttemptsCnt = 10 // Set it same as "MAX_ATTEMPTS" in JPABackingStoreImpl.kt
It's already val but I assume you suggest to name it `MAX_ATTEMPTS_CNT`.

2022-09-30 15:18 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +    private val maxAttemptsCnt = 10 // Set it same as "MAX_ATTEMPTS" in JPABackingStoreImpl.kt
No I mean change it to const, `const` and `val` are different things. But yes consts should also follow the naming convention you specified.

2022-09-30 15:20 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +    }
- [ ] Remove generateSecureHashes with an inline code. 
- [ ] Review and update use of LinkedList(). Replace with List().

2022-09-30 15:31 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +                    assertTrue(secureHashTxnDetails.value.result.toCharacterRepresentation() == 'A')
Thanks. Updated.

2022-09-30 15:46 UTC, nkovacsx requested changes
First skim through

2022-09-30 15:46 UTC, nkovacsx commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +    private val maxAttemptsCnt = 10 // Set it same as "MAX_ATTEMPTS" in JPABackingStoreImpl.kt
I'd go the extra mile and make it static too 😄, I don't see a point why this should be object bound.

2022-09-30 15:46 UTC, nkovacsx commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +    private val entityManagerFactory: EntityManagerFactory
I feel a general inconsistency in this class. There are properties which are `lateinit` an initialised in the `init()` function, there are properties which are initialised in the `init` function. In addition, most of these could be in a `companion object` and initialised there. Is there a reason these are not static?

2022-09-30 15:46 UTC, nkovacsx commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +            mock<DbConnectionManager>().apply {
`.apply` shouldn't be needed here, there's a mock syntax which looks (something) like this:
```
mock<DbConnectionManager>() {
       on { getOrCreateEntityManagerFactory(any(), any(), any()) } doReturn emFactory
}
```
You can search for mocking examples throughout the `corda-runtime-os` test files.

2022-09-30 15:46 UTC, nkovacsx commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +    private fun generateUniquenessCheckStateRef(hashes: LinkedList<SecureHash>): LinkedList<UniquenessCheckStateRef> {
I agree with Ramzi here, is there a reason we use LinkedList in the first place? Just a suggestion, instantiating LinkedList or ArrayList is not really Kotlin-style, always use listOf or mutableListOf (if you need a mutable list) and it will optimise it for you. :)

2022-09-30 15:46 UTC, nkovacsx commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +                LocalDate.of(2200, 1, 1).atStartOfDay().toInstant(ZoneOffset.UTC)
I'm not a fan of using "magic numbers" in tests, can we move this to a companion object as a `val`? Same with the holding identity in line `136`. We are hardcoding strings and dates which will be hard to modify/debug later on.

2022-09-30 15:46 UTC, nkovacsx commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +            var execCounter = 0
The exec counter logic comes back a lot and there's a lot of boilerplate. Just an idea, it could be moved to function like this:
```
inline fun <reified E: Throwable> execWithMaxRetries(noinline block: () -> Unit) {
            var execCounter = 0
            assertThrows<E> {
                execCounter++
                block()
            }
            assertEquals(MAX_ATTEMPTS, execCounter)
}
```
This is just a "fun" way of doing this, since this is a test file I don't have a problem with duplication, just looks neater imo. :)

2022-09-30 16:04 UTC, nkovacsx commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +    }
I agree, I wanted to make the constructor public in my PR because I don't see a reason why a basic data class (POJO) should have a private constructor. Generally throughout the Corda code even if there's a static `create` function for the object the constructor is still public.

2022-09-30 16:06 UTC, nkovacsx commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +            repeat(txCnt) {
Is there a rationale behind this `repeat` here when we only do it once? 😨

2022-09-30 16:12 UTC, nkovacsx commented on components/uniqueness/backing-store-impl/src/main/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImpl.kt
> +    // NOTE: This is a temporary change for dependency injection for testing convenience around
Inconsistent line lengths here

2022-09-30 16:34 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +            // Find a way to mock a TypedQuery while make the logic JPA implementation agnostic.
Ok, fair enough - I saw JPA and assumed it was a JPA exception, rather than a JPA _implementation_ exception.

Would probably be a bit clearer to me if it said a Hibernate exception (which is equally true), but technically the comment is correct as is.

2022-09-30 20:04 UTC, r3hj commented
> @r3hj also another comment that I missed in the original review, I note we are missing integration test cases for the following that we discussed during our initial feedback meeting:
> 
> * Unable to connect to the database
> * Have a database connection, but lack permissions to read and / or write
> 
> One way or the other these should be addressed, either by adding new cases, or explaining why these are not possible.

- [ ] Address the point

2022-09-30 20:05 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +                    assertTrue(secureHashTxnDetails.value.result.toCharacterRepresentation() == 'A')
- [x] Review assert statements and update them.

2022-09-30 20:05 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +    private val maxAttemptsCnt = 10 // Set it same as "MAX_ATTEMPTS" in JPABackingStoreImpl.kt
Renamed it to MAX_ATTEMPTS.

2022-09-30 20:05 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +    private fun generateUniquenessCheckStateRef(hashes: LinkedList<SecureHash>): LinkedList<UniquenessCheckStateRef> {
I'm working on adapting to Kotlin style. Thanks for making the point.

2022-09-30 20:05 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +            repeat(txCnt) {
Cleaned up the repeat and related logic, thanks.

2022-09-30 20:05 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/main/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImpl.kt
> +    // NOTE: This is a temporary change for dependency injection for testing convenience around
Not quite sure what you meant. The comment's been split into lines for readability.

2022-09-30 20:08 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/test/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplTests.kt
> +        fun `Getting transaction details invokes correct query for a failed result`() {
It was for coverage. That said, I agree with the point. I'll remove this.

2022-09-30 20:09 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/test/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplTests.kt
> +        fun `Getting transaction details invokes correct query for an invalid result`() {
Removed.

2022-09-30 20:14 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +            mock<DbConnectionManager>().apply {
Thanks for the suggestion and it's good to know the alternative. I referenced the `.apply` pattern from other existing tests and it seems both patterns are used in our code base. Do let me know if this is an issue.

2022-09-30 20:15 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/test/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplTests.kt
> +        fun `Getting transaction details invokes correct query for a successful result`() {
Removed.

2022-09-30 20:17 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +    private fun generateUniquenessCheckStateRef(hashes: LinkedList<SecureHash>): LinkedList<UniquenessCheckStateRef> {
> I agree with Ramzi here, is there a reason we use LinkedList in the first place? Just a suggestion, instantiating LinkedList or ArrayList is not really Kotlin-style, always use listOf or mutableListOf (if you need a mutable list) and it will optimise it for you. :)

Thanks for the tip. I'll review the code and update them accordingly.

- [ ] Apply Kotlin style

2022-10-04 12:21 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/test/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplTests.kt
> +        fun `Getting state details invokes correct query`() {
Removed.

2022-10-04 12:25 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +    private fun generateUniquenessCheckStateRef(hashes: LinkedList<SecureHash>): LinkedList<UniquenessCheckStateRef> {
@relyafi @nkovacsx Replaced unnecessary mutable lists with immutable lists. Also, applied Kotlin style such as `listOf` and `mutableListOf` wherever it makes sense for better readability.

2022-10-04 13:01 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +    }
Thanks for the detailed explanation. Will update the logic.

- [ ] Simply the helper logic. Also, use a random number for the  state index.

2022-10-04 13:43 UTC, nkovacsx commented on components/uniqueness/backing-store-impl/src/main/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImpl.kt
> +    // NOTE: This is a temporary change for dependency injection for testing convenience around
Which is fine but the line lengths were all over the place.

2022-10-04 13:46 UTC, nkovacsx commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +    private fun generateUniquenessCheckStateRef(hashes: List<SecureHash>): MutableList<UniquenessCheckStateRef> {
Is there a reason this is `MutableList` rather than `List`? I couldn't find a place where this list is actually modified after returning but I might be wrong.

2022-10-04 13:47 UTC, nkovacsx commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +            val consumingStateRefs = listOf<UniquenessCheckStateRef>(consumingStateRef)
No need to explicitly define the list type here, it will be referred from the element type.

2022-10-04 13:48 UTC, nkovacsx commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +            val consumingStateRefs = listOf<UniquenessCheckStateRef>(consumingStateRef)
Same goes for other occurrences as well.

2022-10-04 13:49 UTC, nkovacsx commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +    private val maxAttemptsCnt = 10 // Set it same as "MAX_ATTEMPTS" in JPABackingStoreImpl.kt
It's still not a constant

2022-10-04 14:54 UTC, r3hj commented
> @r3hj also another comment that I missed in the original review, I note we are missing integration test cases for the following that we discussed during our initial feedback meeting:
> 
> * Unable to connect to the database
> * Have a database connection, but lack permissions to read and / or write
> 
> One way or the other these should be addressed, either by adding new cases, or explaining why these are not possible.
@relyafi Tested with PostgreSQL, if it is unable to connect to the DB, it will fail at the initialisation stage where its data source is instantiated. (`dbConfig = DbUtils.getEntityManagerConfiguration(..)`) Given that `dbConfig` is an input parameter to `JPABackingStoreImpl` such DB connection tests should be implemented at a higher level where the initialisation of those parameters happens.

As for testing a scenario with lack of permissions, those errors should be wrapped as `PersistentException` and thrown by the persistence provider. I'll see if I can reproduce this programmatically.

- [ ] Reproduce permission error(s).

2022-10-04 15:08 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +    private val entityManagerFactory: EntityManagerFactory
@nkovacsx These setup style is borrowed from UniquenessChecker tests. I refactored those properties who don't need to re-initialised for each test into companion object. That makes code slightly neater but I don't see an issue in both cases. Can you explain why using init block is considered bad? Thanks.

2022-10-04 15:09 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +                LocalDate.of(2200, 1, 1).atStartOfDay().toInstant(ZoneOffset.UTC)
That's a fair point. Will update.

2022-10-04 15:20 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +    private val entityManagerFactory: EntityManagerFactory
(I'll refactor them to use companion object)

2022-10-04 15:31 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +    private fun generateUniquenessCheckStateRef(hashes: List<SecureHash>): MutableList<UniquenessCheckStateRef> {
That was during refactoring to remove LinkedList and the helper's been replaced with map.

2022-10-04 15:38 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +            val consumingStateRefs = listOf<UniquenessCheckStateRef>(consumingStateRef)
The types can be inferred but I found they sometimes (not always) help readability - don't need to hover mouse over the variable to the type.

2022-10-04 15:40 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +            }
Removed the helper function and simplified the test.

2022-10-04 16:01 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +            val consumingStateRef = UniquenessCheckStateRefImpl(consumingTxId, 0)
Updated

2022-10-04 16:02 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +            val consumingStateRef = UniquenessCheckStateRefImpl(consumingTxId, 0)
Updated, thanks.

2022-10-04 16:03 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +        fun `Double spend is prevented`() {
- [ ] Add a double-spend test which it tries to spend the same state twice in the same executeTransaction block.

2022-10-04 16:04 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +            // Find a way to mock a TypedQuery while make the logic JPA implementation agnostic.
Will improve the comment (i.e. `.e.g. Hibernate ...`)

- [ ] Improve the comment // Actual execution of the query...

2022-10-04 16:24 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +                result.forEach { secureHashTxnDetails ->
Updated with firstNotNullOf.

2022-10-04 16:24 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/main/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImpl.kt
> +    // NOTE: This is a temporary change for dependency injection for testing convenience around
Do you suggest using - to break a long word to make lines fit? If that's what we normally do then I'm good with it too.

2022-10-04 16:27 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +            val consumingTxId: SecureHash = secureHashes[0]
Ah, thanks for the good spot. Will fix it.

2022-10-04 18:58 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +            val consumingTxId = secureHashes[0]
Updated

2022-10-04 19:37 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +        )
Good point. Just figured out how to use `classes` type for `ValueSource`. Also, remove the list.

2022-10-04 19:40 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +            )
Simplified the logic.

2022-10-05 08:09 UTC, nkovacsx commented on components/uniqueness/backing-store-impl/src/main/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImpl.kt
> +    // NOTE: This is a temporary change for dependency injection for testing convenience around
No I'm suggesting, break the long line into equal length lines. As you see here:
```
//  createDefaultUniquenessDb(). It can/should be removed when the temporary hack (createDefaultUniquenessDb()) is
     //  refactored. If createDefaultUniquenessDb() can't be refactored and we want to remove this default parameter,
     //  revert this change and the only affected test is
     //  "Registration status change event instantiates entity manager when event status is up"
```
The line length are not the same for each line and it looks weird.

2022-10-05 08:20 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/main/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImpl.kt
> +    // NOTE: This is a temporary change for dependency injection for testing convenience around
@r3hj you generally can't go wrong by following the existing precedent - there are numerous examples of block comments like this throughout the codebase, and I suspect you'll find few (if any) that are inconsistent like this.

Personally I have my IntelliJ editor to show a line at character 100 and use that as a guide, and ensure lines generally
stay within that and are of a consistent length.

FWIW I suspect this particular bit of code will disappear when you pull down the latest changes that I merged anyway.

2022-10-05 09:17 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/main/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImpl.kt
> +    // NOTE: This is a temporary change for dependency injection for testing convenience around
Okay, I see the point now. I deliberately put the whole test name at the bottom but it may look weird. I'll set this resolved as this bit of code will disappear as Ramzi said.

2022-10-05 09:19 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +            var execCounter = 0
Thanks for the suggestion. I'll note the technique for future reference.

2022-10-05 13:10 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +                assertEquals(consumingTxId, filteredStates[consumingStateRef]?.consumingTxId)
Thanks. I've added two more asserts that also verifies the remaining / unconsumed state has null consumingTxId.

2022-10-05 14:23 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +        fun `Double spend is prevented`() {
@relyafi @nkovacsx 
If double-spend happens in the same transaction then EntityExistsException will be thrown from .consumeStates(). This will be get caught in .executeTransaction() and retried 10 times. Finally it will throw an IllegalStateException at the end of the retry.

2022-10-05 14:40 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/test/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplTests.kt
> +                    "This test fails because life cycle status is not updated to UP upon receiving StartEvent."
Thanks for clarifying it. I've updated the test name following an existing example from MGM tests.

2022-10-05 14:42 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/test/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplTests.kt
> +                    "This test fails because life cycle status is not updated to DOWN upon receiving StopEvent."
Thanks. I'll remove this test as no assertion is available.

2022-10-05 14:45 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/test/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplTests.kt
> +                    "This test fails because life cycle status is not updated to DOWN upon receiving StopEvent."
I don't understand what you mean by "no assertion check is available in this test"?

2022-10-05 15:23 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +                }
@relyafi For the context, `contains` works and improves the semantic a bit.
As for the second point, can you clarify which field of the stored states should be null? (perhaps consumingTxId not stateRef?)

2022-10-05 15:28 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +                }
I don't think `contains` would simplify things nearly as much as what has been suggested, because it's not an assertion. But I'll wait and see the submission.

And yes - it's `consumingTxId` that should be null for unspent states.

2022-10-05 15:34 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/test/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplTests.kt
> +                    "This test fails because life cycle status is not updated to DOWN upon receiving StopEvent."
What I meant, if the lifecycle coordinator shouldn't be updated upon receiving a stop event, the only assert statement should be removed.

2022-10-05 15:45 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/test/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplTests.kt
> +                    "This test fails because life cycle status is not updated to DOWN upon receiving StopEvent."
But the event does do something, so I suggest revisiting what it does and thinking about how you could verify the impact of that call. Just because it doesn't do the specific thing you assumed it did isn't a reason in and of itself to delete the test case, unless you are suggesting there is nothing to test?

2022-10-05 16:36 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +        fun `Double spend is prevented`() {
Ok, so sounds like you have what you need to write another test case covering this.

2022-10-05 16:40 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +                    assertTrue(secureHashTxnDetails.value.result.toCharacterRepresentation() == 'R')
- [ ] Update UniquenessAssertions to handle UniquenessCheckResult for both successful and failed result.
- [ ] Update tests to use the utility

2022-10-05 16:40 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +                        Clock.systemUTC().instant(), UniquenessCheckErrorGeneralImpl("some error")
- [x] Add test cases for different types of errors.

2022-10-06 11:03 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +                    assertTrue(secureHashTxnDetails.value.result.toCharacterRepresentation() == 'R')
@relyafi I've done usability experiment and think having separate methods like `assertAcceptedUniquenessCheckResult()` and `assertRejectedUniqunessCheckResult()` might be better. If you've already thought of some interface design please let me know.

2022-10-06 12:10 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +                    assertTrue(secureHashTxnDetails.value.result.toCharacterRepresentation() == 'R')
I'm not opposed to having separate functions, given the backing store talks in transaction details rather than responses. But I don't see any difference in terms of what we would be checking. For example, you wouldn't have a single rejected assertion function, since we would be interested in exactly what type of rejection we received.

I'd expect that the acceptance and rejection scenarios (and the checks that need to be performed) are almost if not entirely identical to the existing set, it's just they're acting on a `UniquenessCheckTransactionDetails` instead of `UniquenessCheckResponseAvro` object.

Given the existing functions are quite lightweight, I'll leave it to your discretion whether to have slightly different named functions that duplicate the internal logic of the existing functions. What I'm really looking for is that we are checking for a specific response type, and performing the same validation as we do for the existing functions unless there's a good reason not to.

2022-10-06 12:34 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +                    assertTrue(secureHashTxnDetails.value.result.toCharacterRepresentation() == 'R')
@relyafi I'll look into the design again. It might feel different this time.

2022-10-06 14:51 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +                    assertTrue(secureHashTxnDetails.value.result.toCharacterRepresentation() == 'R')
Discussed. I've added two assert methods for verifying UniquenessCheckResult. We may want to reduce the total number of assert methods but this should be done in a separate PR.

2022-10-06 15:10 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/test/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplTests.kt
> +                    "This test fails because life cycle status is not updated to DOWN upon receiving StopEvent."
The only logic for stop event handler is `dependentComponents.stopAll()` and I found it quite tricky to test it last time. I'll revisit this if I can write a meaningful test.

2022-10-07 09:42 UTC, ifrankrui commented
As discussed, we need to add a test to make sure we explicitly get a failure/error when the `error_details` for the rejected transaction exceeds the `1024` bytes size limit.

2022-10-07 16:54 UTC, r3hj commented
> As discussed, we need to add a test to make sure we explicitly get a failure/error when the `error_details` for the rejected transaction exceeds the `1024` bytes size limit.

- [x] Add a test for checking and verifying the size of error_details.

2022-10-10 08:23 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +        fun `Double spend is prevented`() {
Added another double-spend test that verifies the current behaviour.

2022-10-10 12:36 UTC, r3hj commented
> 

Added a test.

Confirmed that using an error text with 1024 letters fails due

2022-10-10 13:08 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +    }
Updated UniquenessCheckRequestInternal so that its constructor is now public. Also, updated all tests to directly create internal requests.

2022-10-10 13:45 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/test/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplTests.kt
> +        }
@relyafi  I've re-reviewed the logic and looked at other life cycle tests. I think those tests have still value though they are not very interesting. In addition, I haven't been able to find life cycle tests that appear to be more meaningful/useful.

Some other examples:
* DbConnectionManagerImplTest.kt
* MgmSynchronisationServiceImplTest.kt
* VirtualNodeMaintenanceRPCOpsImplTest.kt

I'll have a look if I can run tests with a real life cycle but I'm not sure what value it adds for us. I'll time-box it.

2022-10-10 13:52 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/test/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplTests.kt
> +        }
@r3hj There are a couple of things that are not clear from your comment:

- Did you look at tests that use `LifecycleTest` as suggested? If so, how did you reach the conclusion that they are not more meaningful / useful? What is the difference between those tests and our use case?
- What about the suggestion of _At the least we should look through other tests in the codebase which are mocking the lifecycle co-ordinator for inspiration - they take a similar approach to this but are also checking that things like updateStatus are called. I see there are some later tests that do this so it may be a case of combining the logic of the tests to have more meaningful test cases._ Are you saying there are no such test cases?

2022-10-10 15:06 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/test/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplTests.kt
> +        }
@relyafi I looked at some example of LifecycleTest. Apart from the set up, it provides additional test methods like verifyIsUp and verifyIsDown. For simple tests, it doesn't seem to justify its complexity. That said, I didn't go into details though.

Some other tests check if updateStatus() is invoked and those tests are for testing event handler. The above three tests are intended for testing the exposed methods/property such as .start(), .stop() and .isRunning. There is no other logic other than invoking life cycle coordinator in .start(), .stop() so I'm not sure what more tests we can add.

2022-10-10 15:28 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/test/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplTests.kt
> +        }
@r3hj saying that a test is "simple" is subjective - in my view some of the tests that utilise this are relatively simple too, and there hasn't been a concrete argument presented as to how our tests differ.

Regarding the other point, here are two tests that use the mock of the coordinator to interrogate that the lifecycle would be updated correctly as a result of the API calls:

https://github.com/corda/corda-runtime-os/blob/b997449ec18aaea3bc73386be041a151d5408f09/components/configuration/configuration-read-service-impl/src/test/kotlin/net/corda/configuration/read/impl/ConfigReadServiceEventHandlerTest.kt

https://github.com/corda/corda-runtime-os/blob/43549157cb6892c033494403be10744d0d1919d0/processors/member-processor/src/test/kotlin/net/corda/processors/member/internal/MemberProcessorImplTest.kt

That would be a way of showing that something meaningful happened as a result of those calls.

In other words, it looks like there are a few options to do something more substantial than what is there currently.

2022-10-10 20:49 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/test/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplTests.kt
> +        fun `Executing transaction retries upon expected exceptions`(exception: String) {
Removed

2022-10-10 20:49 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/test/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplTests.kt
> +        fun `Executing transaction does not retry upon unexpected exception`() {
Removed

2022-10-10 20:49 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/test/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplTests.kt
> +        fun `Executing transaction triggers rollback upon receiving expected exception if transaction is active`() {
Removed

2022-10-10 20:53 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/test/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplTests.kt
> +    inner class TransactionOpsTests {
I'll remove these tests.

2022-10-10 21:03 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/test/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplTests.kt
> +        @Test
Removed all TransactionOps tests and some others. In case I missed to remove it, please let me know.

2022-10-11 09:34 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/test/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplTests.kt
> +                    "This test fails because life cycle status is not updated to DOWN upon receiving StopEvent."
@relyafi  Added a test verifying that stop event stops its dependent component. Also, added a similar assertion to the start event test.

2022-10-11 13:28 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/test/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplTests.kt
> +        }
@relyafi I'm looking at ConfigReadServiceEventHandlerTest for any useful testing setup, etc. I looked at MemberProcessorImplTest and updated the our tests with better naming and more strict verification.

2022-10-11 15:28 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +    private val maxAttemptsCnt = 10 // Set it same as "MAX_ATTEMPTS" in JPABackingStoreImpl.kt
@r3hj reopening this, as this has not been properly addressed.

2022-10-11 15:42 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +                txnDetails.firstNotNullOf { secureHashTxnDetail ->
(Follow-up of https://github.com/corda/corda-runtime-os/pull/2211#discussion_r984426124)

Why `firstNotNullOf`? The previous line asserts that we have exactly one element already, and I don't see how it would ever be null?

2022-10-11 15:42 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +                    assertTrue(secureHashTxnDetails.value.result.toCharacterRepresentation() == 'A')
@r3hj reopening this as this has only been partially addressed. The tests now do use `assertThat`, however there only appears to be a single test case that uses `assertAll`. I can count at least 5, if not more test cases that would benefit from using this.

2022-10-11 15:44 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +    private val maxAttemptsCnt = 10 // Set it same as "MAX_ATTEMPTS" in JPABackingStoreImpl.kt
Updated it with const keyword.

2022-10-11 15:48 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +                    assertTrue(secureHashTxnDetails.value.result.toCharacterRepresentation() == 'R')
@r3hj reopening as this has only partially done what was asked - as was made clear before, _What I'm really looking for is that we are checking for a specific response type, and performing the same validation as we do for the existing functions unless there's a good reason not to._

Instead, it appears that the logic for checking the exact type has been done directly in the tests, rather than having specific assertion functions in this library as was requested. This needlessly deviates from the pattern set with the existing  Avro based helper functions, and is a barrier to future reuse.

2022-10-11 15:54 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +                txnDetails.firstNotNullOf { secureHashTxnDetail ->
txnDetails is a type of map. Can you suggest a better method please?

2022-10-11 16:03 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +                txnDetails.firstNotNullOf { secureHashTxnDetail ->
`txnDetails.entries.single`

2022-10-11 16:26 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +                    assertTrue(secureHashTxnDetails.value.result.toCharacterRepresentation() == 'R')
Following the pattern, updated the assert to check the specific error type as well. The fields of error types vary so making a unified assert function in the library doesn't seem like a good idea. Please make a suggestion if you think otherwise.

2022-10-11 16:38 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +                txnDetails.firstNotNullOf { secureHashTxnDetail ->
That is for returning an item matching the predicate?

2022-10-11 16:39 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +                txnDetails.firstNotNullOf { secureHashTxnDetail ->
I'll research if there is other method that can improve the readability.

2022-10-11 16:46 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +                txnDetails.firstNotNullOf { secureHashTxnDetail ->
@relyafi What about txnDetails.toList().first().apply { ... }

2022-10-11 18:55 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +                    assertTrue(secureHashTxnDetails.value.result.toCharacterRepresentation() == 'A')
Updated remaining assert statements to use assertAll.

2022-10-12 08:54 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +                txnDetails.firstNotNullOf { secureHashTxnDetail ->
This looks okay:

txnDetails.entries.single { true }.apply { ... }

2022-10-12 09:38 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +                txnDetails.firstNotNullOf { secureHashTxnDetail ->
@relyafi Replaced all firstNotNullOf with entries.single { true }.apply { ... }. Also, moved txId assert into assertAll block for consistency.

2022-10-12 10:32 UTC, relyafi requested changes
Another review will follow as this is very much a moving target given the number of commits. There are still some significant deficiencies that need addressing, some of which are down to earlier comments not being addressed completely. There remains a number of instances of unnecessary boiler plate code - I've made a proposed change to simplify one test case, but the entire suite still needs reviewing and simplifying.

2022-10-12 10:32 UTC, relyafi commented on testing/uniqueness/uniqueness-utilities/build.gradle
> +    implementation "net.corda:corda-ledger-utxo"
What is this dependency needed for?

2022-10-12 10:32 UTC, relyafi commented on testing/uniqueness/uniqueness-utilities/src/main/kotlin/net/corda/uniqueness/utils/UniquenessAssertions.kt
> +        val failureImpl = result as UniquenessCheckResultFailureImpl
This looks like it has tried to copy `getResultOfType`, but hasn't properly handled the differences of the `UniquenessCheckResult` type. Either take a `UniquenessCheckResultFailure` to begin with, or start by asserting the result is of that type as a first action (asserting is better than the test throwing with a cast exception).

2022-10-12 10:32 UTC, relyafi commented on testing/uniqueness/uniqueness-utilities/src/main/kotlin/net/corda/uniqueness/utils/UniquenessAssertions.kt
> +    inline fun <reified T> toErrorType(result: UniquenessCheckResult): T {
`getErrorOfType` would be more consistent with the naming of the existing Avro based function.

2022-10-12 10:32 UTC, relyafi commented on testing/uniqueness/uniqueness-utilities/src/main/kotlin/net/corda/uniqueness/utils/UniquenessAssertions.kt
> +        return errorImpl
I'm not sure the assertion will ever fail, because won't it fail with a cast exception on the previous line if there is a type mismatch?

I don't see why we wouldn't just follow the pattern used in the existing function.

2022-10-12 10:32 UTC, relyafi commented on testing/uniqueness/uniqueness-utilities/src/main/kotlin/net/corda/uniqueness/utils/UniquenessAssertions.kt
> +    }
This is duplicating some of the logic of `assertStandardSuccessResponse`. Whilst extracting this into a function may be useful as there are now two places we want to do this check, I think we should go back and update `assertStandardSuccessResponse` to use this function.

2022-10-12 10:32 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/test/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplTests.kt
> +                createNamedQuery("UniquenessStateDetailEntity.select", UniquenessStateDetailEntity::class.java)
Formatting of this block is inconsistent with the next two whenever blocks, despite following the same pattern.

2022-10-12 10:32 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +                    assertTrue(secureHashTxnDetails.value.result.toCharacterRepresentation() == 'R')
@r3hj that is exactly what I said - a unified assert function in the library doesn't make sense for the rejection cases, and the Avro based ones have separate assertion functions for each specific type.

The PR as it stands has a single function for testing rejections.

2022-10-12 10:32 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +        private val defaultEmFactory: EntityManagerFactory = EntityManagerFactoryFactoryImpl().create(
I'd call this something else, as default implies it's used by most of the tests as the default, which is not the case here.

`noDbEmFactory` might be better, and consistent with the approach `UniquenessCheckerImplDBIntegrationTests` takes.

2022-10-12 10:32 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +        "test", JPABackingStoreEntities.classes.toList(), dbConfig)
Indentation looks wrong on this line

2022-10-12 10:32 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +    private fun generateRequestInternal(txId: SecureHash): UniquenessCheckRequestInternal {
Given a good number of the calls to this don't care about `txId`, you could remove some boilerplate from the tests by setting a default for this (similar to the uniqueness checker tests with their Avro equivalent functions)

2022-10-12 10:32 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +        private val UPPER_BOUND = LocalDate.of(2200, 1, 1).atStartOfDay().toInstant(ZoneOffset.UTC)
```suggestion
        private val DEFAULT_TIME_WINDOW_UPPER_BOUND = LocalDate.of(2200, 1, 1).atStartOfDay().toInstant(ZoneOffset.UTC)
```

Bit clearer in my opinion

2022-10-12 10:32 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +                )
I find this quite hard to read. Generally, if I can't fit all arguments on a single line, I have a single argument on each line.

There are a number of instances like this throughout this file - please review all of them.

2022-10-12 10:32 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +                    assertThat(txIds.contains(secureHashTxnDetail.key))
This feels unnecessarily clunky, given there is only one element. All that is really needed is to check that the (single) `txId` equals the (single) key.

`getTransactionDetails` above does need to take a list, but this can then be done inline in the call.

This pattern appears in a number of test cases - please review them all and simplify where appropriate.

2022-10-12 10:32 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +                    UniquenessAssertions.assertRejectedUniquenessCheckResult(uniquenessCheckResult)
Why is this not also included within `assertAll`?

Another repeated pattern - please fix all instances.

2022-10-12 10:32 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +                txDetails.firstNotNullOf { secureHashTxnDetail ->
You can save yourself having to do `secureHashTxnDetail.key` and `secureHashTxnDetail.value` later on by doing `(resultTxId, resultDetails)` instead of `secureHashTxnDetail` here.

2022-10-12 10:32 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +                txnDetails.firstNotNullOf { secureHashTxnDetail ->
A Google search for "Kotlin single function" returns this as its top result: https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/single.html

I.e. use `single()`

2022-10-12 10:32 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +                                    UniquenessCheckStateRefImpl(txId, 0), consumingTxId = null))))))
Wouldn't it be more realistic to specify a state that has a `consumingTxId`?

2022-10-12 10:32 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +                                    UniquenessCheckStateRefImpl(txId, 0), consumingTxId = null))))))
Wouldn't it be more realistic to specify a state that has a `consumingTxId`?

2022-10-12 10:32 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +            val maxErrMsgLength = 1024
@ifrankrui introduced a constant as part of his changes - probably makes sense to update the test to use that.

2022-10-12 10:32 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +                }
It seems odd to be doing assertions whilst running within a session - this may give some strange behavior if the assertions actually fail.

It's probably safer and more correct to be doing the assertions after exiting the session.

This comment applies to other test cases in this file as well - please self review and fix all instances.

2022-10-12 10:32 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +            }
This test case is one  example of the unnecessary complexity that remains in many of these test cases. I provide the example below as to how this can be simplified:

```suggestion
            val stateRefs = List(2) { 
                UniquenessCheckStateRefImpl(SecureHashUtils.randomSecureHash(), 0) }

            // Generate unconsumed states in DB.
            backingStoreImpl.session(aliceIdentity) { session ->
                session.executeTransaction { _, txnOps -> txnOps.createUnconsumedStates(stateRefs) }
            }

            // Consume one of unconsumed states in DB.
            val consumingTxId: SecureHash = SecureHashUtils.randomSecureHash()
            backingStoreImpl.session(aliceIdentity) { session ->
                session.executeTransaction { _, txnOps ->
                    txnOps.consumeStates(consumingTxId = consumingTxId, stateRefs = listOf(stateRefs[0]))
                }
            }

            lateinit var stateDetails: Map<UniquenessCheckStateRef, UniquenessCheckStateDetails>

            // Verify if the target state has been correctly updated.
            backingStoreImpl.session(aliceIdentity) { session ->
                stateDetails = session.getStateDetails(stateRefs)
            }

            stateDetails.values.partition { it.consumingTxId == null }.let { (unconsumedStates, consumedStates) ->
                assertAll(
                    { assertThat(unconsumedStates.count()).isEqualTo(1) },
                    { assertThat(unconsumedStates.single().stateRef.txHash).isEqualTo(stateRefs[1].txHash) },
                    { assertThat(unconsumedStates.single().consumingTxId).isNull() },
                    { assertThat(consumedStates.count()).isEqualTo(1) },
                    { assertThat(consumedStates.single().stateRef.txHash).isEqualTo(stateRefs[0].txHash) },
                    { assertThat(consumedStates.single().consumingTxId).isEqualTo(consumingTxId) }
                )
            }
```

Note:

- Unnecessary temporary variables and data structures have been removed
- Use of `partition` to avoid having to filter twice
- Use of `let` to avoid further temporary variable creation
- Doing assertions outside of the session
- Performing the same assertions for the unconsumed and consumed states (for some reason the tests were looking at the `stateRef.txHash` for one case and not the other, and similarly the `consumingTxId` for one case and noth the other
- Using the same ordering of arguments in the assertions - the `stateRefs[1].txHash` was in reverse order compared to the consumed state test for some reason
- Use of `single()` given each list only has one element.

Please once again, self review all test cases and ensure these are simplified appropriately.

2022-10-12 10:32 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +            }
Should wrap with `assertDoesNotThrow`?

2022-10-12 10:32 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +                    session.executeTransaction { _, txnOps -> txnOps.consumeStates(consumingTxId, consumingStateRefs) }
It would be more realistic to have two different transaction ids trying to consume the same state.

2022-10-12 10:32 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +                        txnOps.consumeStates(consumingTxId, consumingStateRefs)
It would be more realistic to have two different transaction ids trying to consume the same state.

2022-10-12 10:32 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +            }
Isn't all of this redundant?

2022-10-12 10:32 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +        )
Are you therefore making the statement that you believe such an exception should be triggering retry?

In this scenario, I don't see why we wouldn't just test the current behavior, and reference the existing ticket for reviewing caught exceptions in a comment.

2022-10-12 10:32 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +        )
So there's no need to disable the whole test - can just comment out the specific failing exception type and comment that it will be reviewed as part of the existing caught exception ticket

2022-10-12 10:32 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +    fun `Persisting with an incorrect identity throws an expected exception`() {
This name doesn't appear to match up with what is happening - what exactly are we trying to test here? We've provided a backing store with a DB connection for a non-existent DB, is that it?

2022-10-12 10:32 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +        }
Doesn't this fail to detect the case where no exception was thrown?

2022-10-12 10:33 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +                txnDetails.firstNotNullOf { secureHashTxnDetail ->
See https://github.com/corda/corda-runtime-os/pull/2211#discussion_r993202539

2022-10-12 10:34 UTC, relyafi commented
This test scenario still appears to be missing: 

- Have a database connection, but lack permissions to read and / or write

2022-10-12 12:11 UTC, r3hj commented on testing/uniqueness/uniqueness-utilities/build.gradle
> +    implementation "net.corda:corda-ledger-utxo"
That's for UniquenessCheckResult.

2022-10-12 12:13 UTC, r3hj commented on testing/uniqueness/uniqueness-utilities/src/main/kotlin/net/corda/uniqueness/utils/UniquenessAssertions.kt
> +    inline fun <reified T> toErrorType(result: UniquenessCheckResult): T {
Updated

2022-10-12 12:22 UTC, r3hj commented on testing/uniqueness/uniqueness-utilities/src/main/kotlin/net/corda/uniqueness/utils/UniquenessAssertions.kt
> +        return errorImpl
Good point. We can remove the assert and type check. Updated.

2022-10-12 12:27 UTC, r3hj commented on testing/uniqueness/uniqueness-utilities/src/main/kotlin/net/corda/uniqueness/utils/UniquenessAssertions.kt
> +    }
Updated. I didn't touch initially it because some reviewer(s) think such change only hinders review and it should be done in a separate PR.

2022-10-12 12:30 UTC, relyafi commented on testing/uniqueness/uniqueness-utilities/build.gradle
> +    implementation "net.corda:corda-ledger-utxo"
I believe that is in `:application` now? https://github.com/corda/corda-api/blob/release/os/5.0/application/src/main/kotlin/net/corda/v5/application/uniqueness/model/UniquenessCheckResults.kt

Admittedly it may have been where you said when this PR was first started as there has been some refactoring in recent weeks.

2022-10-12 12:46 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +        )
That's based on the documentation of the exception and open for discussion.

I tried to find an existing ticket with 'exception' but couldn't. I'd appreciate if you let me know the ticket.

2022-10-12 12:50 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/test/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplTests.kt
> +                createNamedQuery("UniquenessStateDetailEntity.select", UniquenessStateDetailEntity::class.java)
Updated

2022-10-12 12:54 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +        )
There is reference to https://r3-cev.atlassian.net/browse/CORE-4983 in one of the TODOs in `JPABackingStoreImpl`, but to be fair this is not referenced in the other TODOs in that file that more closely relate to this specific problem. I think referencing this ticket is sufficient and they will all be considered together as part of that.

Could I ask for the link for the documentation you are referring to? [This](https://docs.jboss.org/hibernate/orm/5.0/javadocs/org/hibernate/QueryTimeoutException.html) doesn't appear to provide much detail.

2022-10-12 13:13 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +        )
I referenced that document and the API document (ctrl + click). I'll update the test with the ticket number so that it tests the current behaviour.

2022-10-12 13:28 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +        )
So I'm still not following what you mean by it's "based on the documentation" - as far as I can see, the `resultList` doc doesn't make any statement about how to handle this type of exception?

```
Execute a SELECT query and return the query results as a typed List.
Returns:
a list of the results
Throws:
...
QueryTimeoutException – if the query execution exceeds the query timeout value set and only the statement is rolled back
...
```

Am I missing something?

2022-10-12 13:38 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +        )
It doesn't state how we should handle. Is that what you're looking for?

2022-10-12 13:53 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +        )
I assumed that _"That's based on the documentation of the exception and open for discussion."_ was in response to my comment of _"Are you therefore making the statement that you believe such an exception should be triggering retry?"_. Did I misunderstand the point you were trying to make?

2022-10-12 14:12 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +        )
Sorry that there was a misunderstanding. Querying could throw a timeout error which could be caused by network issues. The general approach for such problem is retry, usually with an exponential delay. If it can throw a timeout exception then it may be reasonable to expect retry logic is triggered as we have (but it doesn't catch QueryTimeoutException).

2022-10-12 14:13 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +        )
Updated with the same ticket number.

2022-10-12 14:16 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +        )
Ok thanks, that explanation is what I was after. It does sound like something that should be reviewed as part of CORE-4983 then, and we'd want to establish whether Hibernate itself is already doing retry + exponential backoff.

So I think as we're not certain that the current behavior is wrong (it just needs to be reviewed), the approach of test the current behavior and revisit in a separate ticket is what I'd prefer.

2022-10-12 14:17 UTC, r3hj commented on testing/uniqueness/uniqueness-utilities/build.gradle
> +    implementation "net.corda:corda-ledger-utxo"
Updated with :application after pulling the latest.

2022-10-12 15:04 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +        private val defaultEmFactory: EntityManagerFactory = EntityManagerFactoryFactoryImpl().create(
Updated

2022-10-12 15:05 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +        "test", JPABackingStoreEntities.classes.toList(), dbConfig)
Updated

2022-10-12 15:43 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +            }
Thanks. Will update accordingly. 

- [x] Refactor tests

2022-10-12 16:13 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +        }
Thanks. Added an Assertions.fail at the end of the try block.

2022-10-13 08:18 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +                    assertTrue(secureHashTxnDetails.value.result.toCharacterRepresentation() == 'R')
- [ ] Add assert helper for each type of error

2022-10-13 08:21 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +                txnDetails.firstNotNullOf { secureHashTxnDetail ->
Replaced with single()

2022-10-13 09:19 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +            val maxErrMsgLength = 1024
Actually, please disregard this comment - I realised the change mentioned has not yet been merged.

2022-10-13 10:47 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +            val maxErrMsgLength = 1024
Thanks

2022-10-13 10:47 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +                }
Updated tests to use assert outside a session

2022-10-13 11:35 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +        private val UPPER_BOUND = LocalDate.of(2200, 1, 1).atStartOfDay().toInstant(ZoneOffset.UTC)
Updated

2022-10-13 11:38 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +    private fun generateRequestInternal(txId: SecureHash): UniquenessCheckRequestInternal {
Added a default parameter and removed passing txId if not needed.

2022-10-13 13:59 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +                    session.executeTransaction { _, txnOps -> txnOps.consumeStates(consumingTxId, consumingStateRefs) }
Updated

2022-10-13 14:00 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +                        txnOps.consumeStates(consumingTxId, consumingStateRefs)
Updated

2022-10-13 14:04 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +                                    UniquenessCheckStateRefImpl(txId, 0), consumingTxId = null))))))
Updated

2022-10-13 14:04 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +                                    UniquenessCheckStateRefImpl(txId, 0), consumingTxId = null))))))
Updated

2022-10-13 14:40 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +            }
Added

2022-10-13 14:43 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +                    UniquenessAssertions.assertRejectedUniquenessCheckResult(uniquenessCheckResult)
Updated

2022-10-13 14:43 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +        private val UPPER_BOUND = LocalDate.of(2200, 1, 1).atStartOfDay().toInstant(ZoneOffset.UTC)
Updated

2022-10-17 09:16 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +                )
@relyafi We may want to run and use Intellij auto formatting. The formatting feature usually increases line counts but it seems to provide a consistent and often better look.

2022-10-17 09:18 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +            }
If you refer to the first three lines, I've updated them. Otherwise, can you please specify which part can be removed?

2022-10-17 10:27 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +        )
Updated the test with the ticket number.

2022-10-17 12:24 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +            }
FYI: Refactoring to use partition is applied to the test you suggested where both consumed and unconsumed states need to be tested.

2022-10-17 16:43 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/test/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplTests.kt
> +        }
@relyafi Looked into ConfigReadServiceEventHandlerTest. Those tests verify what arguments are passed to .postEvent() and .updateStatus() utilising Mockito argument captor. In our event handler we don't use postEvent() and a test for .updateStatus() exists to verify what argument has been called. For this test there is no need for using argument captor.

2022-10-18 11:32 UTC, nkovacsx commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +            : UniquenessCheckRequestInternal =
No need to explicitly add the type if you are using `=`

2022-10-18 11:46 UTC, nkovacsx requested changes, later dismissed
We are getting there

2022-10-18 11:46 UTC, nkovacsx commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +            lateinit var txnDetails: Map<SecureHash, UniquenessCheckTransactionDetailsInternal>
NIT: Couldn't we just have an initialised map and insert into that? I feel like `lateinit`s are a bit harder to manage/track, especially inside functions. I don't think it's a good practice. What if we just did:
```
val txnDetails = mutableMapOf<SecureHash, UniquenessCheckTransactionDetailsInternal>
backingStoreImpl.session(aliceIdentity) { session -> txnDetails.putAll(session.getTransactionDetails(txIds)) }
```

or something similar

2022-10-18 11:46 UTC, nkovacsx commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +            backingStoreImpl.session(aliceIdentity) { session -> txnDetails = session.getTransactionDetails(txIds) }
This pattern 
```
session {
    get details and store them
}
assert that it is a given size
assert that it contains given elements
assert that the given element is of type
```
is reoccurring a lot, couldn't we create a helper function for this? It would make the code much cleaner and would remove a lot of boilerplate imo.

2022-10-18 11:46 UTC, nkovacsx commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +    fun `Persisting with an incorrect identity throws an expected exception`() {
I think this comment is still valid, the test name is a bit confusing.

2022-10-18 11:46 UTC, nkovacsx commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +    fun `Persisting with an incorrect identity throws an expected exception`() {
"Incorrect identity" means something entirely different for me, especially the Corda world.

2022-10-18 11:46 UTC, nkovacsx commented on testing/uniqueness/uniqueness-utilities/src/main/kotlin/net/corda/uniqueness/utils/UniquenessAssertions.kt
> +    private inline fun <reified T>assertRejectedResultCommon(result: UniquenessCheckResult,
NIT: space missing after `<reified T>`

2022-10-18 11:46 UTC, nkovacsx commented on testing/uniqueness/uniqueness-utilities/src/main/kotlin/net/corda/uniqueness/utils/UniquenessAssertions.kt
> +    {
NIT: `{` in new line is not Kotlin coding style

2022-10-18 11:46 UTC, nkovacsx commented on testing/uniqueness/uniqueness-utilities/src/main/kotlin/net/corda/uniqueness/utils/UniquenessAssertions.kt
> +        val failureImpl = result as UniquenessCheckResultFailureImpl
I agree with Ramzi here, `UniquenessCheckResult` can be a failure or a success. You'd need to check that `result` is actually a failure. However, I'd probably rewrite this function to take in `UniquenessCheckResultFailure` in the first place.

2022-10-18 12:44 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +    fun `Persisting with an incorrect identity throws an expected exception`() {
@nkovacsx I agree. All comments either not replied or resolved are work-in-progress.

2022-10-18 12:48 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +            : UniquenessCheckRequestInternal =
Updated

2022-10-18 13:11 UTC, r3hj commented on testing/uniqueness/uniqueness-utilities/src/main/kotlin/net/corda/uniqueness/utils/UniquenessAssertions.kt
> +    private inline fun <reified T>assertRejectedResultCommon(result: UniquenessCheckResult,
Updated

2022-10-18 13:11 UTC, r3hj commented on testing/uniqueness/uniqueness-utilities/src/main/kotlin/net/corda/uniqueness/utils/UniquenessAssertions.kt
> +    {
Applied formatting here and other places

2022-10-18 13:23 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +            backingStoreImpl.session(aliceIdentity) { session -> txnDetails = session.getTransactionDetails(txIds) }
@nkovacsx The common assert appear 7 times and the first two assert statements can be moved to a helper. Suggestion: UniquenssAssertions.assertSizeAndTxId(...). Or, can you make a suggestion please?

2022-10-18 13:27 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +            lateinit var txnDetails: Map<SecureHash, UniquenessCheckTransactionDetailsInternal>
@nkovacsx Thanks for the alternative. Either with lateinit or putAll looks fine in these tests. Do you suggest changing them here? Could you explain for the reason?

2022-10-18 15:20 UTC, r3hj commented on testing/uniqueness/uniqueness-utilities/src/main/kotlin/net/corda/uniqueness/utils/UniquenessAssertions.kt
> +        val failureImpl = result as UniquenessCheckResultFailureImpl
I've updated so that it casts to UniquenssCheckResultFailure. 
@nkovacsx I experimented the suggestion to take UniquenessCheckresultFailure and it seems the current casting logic is simpler. Please let me know if you want to pair up to test the idea.

2022-10-19 09:33 UTC, nkovacsx commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +            lateinit var txnDetails: Map<SecureHash, UniquenessCheckTransactionDetailsInternal>
As we discussed this morning I don't have a strong opinion on this. I'm really not a fan of `lateinit`s especially in functions they look a bit off. `lateinit` has the risk that it doesn't get initiated and will throw an unitialised property exception which is a bit hard to track. We had problems with `lateinit` in C4 because it's very easy to leave it unitialised and can cause problems. Since this is just a test file I'm okay if we keep this so I'll leave it to you.

2022-10-19 12:18 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +            lateinit var txnDetails: Map<SecureHash, UniquenessCheckTransactionDetailsInternal>
Thanks. Though it won't make much difference here, I agree that it'd be a better practice to avoid using lateinit. I've updated tests.

2022-10-19 12:21 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +            backingStoreImpl.session(aliceIdentity) { session -> txnDetails = session.getTransactionDetails(txIds) }
@nkovacsx Discussed and agreed that it'd be better to move to a helper. As for the helper name, I've updated it to `assertContainingTxId(..)`. Please let me know if you have a better alternative.

2022-10-19 12:34 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +                )
@relyafi I've applied auto formatting and improved some manually. Please have a look at the changes.

2022-10-20 15:17 UTC, nkovacsx commented on testing/uniqueness/uniqueness-utilities/src/main/kotlin/net/corda/uniqueness/utils/UniquenessAssertions.kt
> +        val failureImpl = result as UniquenessCheckResultFailureImpl
`val failureImpl = result as UniquenessCheckResultFailureImpl` this line will still fail with a `ClassCastException` if `result` is not a failure. I'd advise:
`assertInstanceOf(result::class.java, UniquenessCheckResultFailure::class.java)` or something similar

2022-10-20 15:19 UTC, nkovacsx commented
I'm mostly happy on my end, but will hold back the approval until Ramzi checks his comments too, I might have missed something (especially that there are 200+ comments 😄 )

2022-10-21 09:27 UTC, relyafi commented on testing/uniqueness/uniqueness-utilities/src/main/kotlin/net/corda/uniqueness/utils/UniquenessAssertions.kt
> +        val failureImpl = result as UniquenessCheckResultFailureImpl
@r3hj This still doesn't appear to have been done properly. While there is a check now done, it's in a completely different (private) function, but this (public) function will still fail if it is called directly with a `ClassCastException`. Basically this solution has introduced unnecessary complexity and relies on the caller using the private `assertRejectedResultCommon` function first.

I don't see any reason why the pattern here needs to differ from `getResultOfType`, so please can you explain why we haven't taken this approach?

2022-10-21 09:29 UTC, relyafi commented on testing/uniqueness/uniqueness-utilities/src/main/kotlin/net/corda/uniqueness/utils/UniquenessAssertions.kt
> +        val failureImpl = result as UniquenessCheckResultFailureImpl
@r3hj While this check has now been done, I don't understand why it has been done in `assertRejectedResultCommon`, given that function doesn't care about the specific type of result. The approach taken relies on the writer of the test calling the common function before `getErrorOfType`.

Please can you explain why we haven't done what has been suggested and simply following the existing pattern of `getResultOfType`, which does the assertion immediately before the cast?

2022-10-21 10:42 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +            }
More generally - why do you need to create unconsumed states, if the test scenario is consuming unknown states?

2022-10-21 14:49 UTC, relyafi requested changes

2022-10-21 14:49 UTC, relyafi commented on testing/uniqueness/uniqueness-utilities/src/main/kotlin/net/corda/uniqueness/utils/UniquenessAssertions.kt
> +import net.corda.v5.application.uniqueness.model.*
I'm assuming this was manually added, as it is out of order with respect to the other includes?

Regardless, you presumably don't need both this and line 10. I'd suggest that you:

- Set up your IntelliJ not to do Wildcard imports (you might get away with this in tests but it will fail detekt checks in proper source code)
- Run optimise imports in IntelliJ to tidy up

2022-10-21 14:49 UTC, relyafi commented on testing/uniqueness/uniqueness-utilities/src/main/kotlin/net/corda/uniqueness/utils/UniquenessAssertions.kt
> +    }
This function is a bit confusing to me, because the interface and comment describe something different to what it is doing.

The intent seems to be to check that a map of results contains exactly one entry. If that is the intent, then the function name and comment should reflect that and not imply that the size can be variable, or that it is only asserting that a specific tx id is present.

Further, if this is the intent, I don't see why we would take a list of `txIds` in this scenario. If we are expecting exactly one result, surely we'd be expecting only a single transaction id, not a list of possible ids? As far as I can see, every single invocation of this function is only providing a single tx id, and worse, we're unnecessarily having to wrap that in a list just to pass into this function.

2022-10-21 14:49 UTC, relyafi commented on testing/uniqueness/uniqueness-utilities/src/main/kotlin/net/corda/uniqueness/utils/UniquenessAssertions.kt
> +    fun assertContainingTxId(txnDetails: Map<SecureHash, UniquenessCheckTransactionDetailsInternal>,
The ordering of all of these new functions seems a bit arbitrary - we have the "success" function for Avro responses, all of the functions relating to accepted and rejected results, and then the rejected Avro response functions. It's good practice to group related functions together, so I'd suggest keep the "result" functions together, the "avro" functions together, and then the "common" functions together.

2022-10-21 14:49 UTC, relyafi commented on testing/uniqueness/uniqueness-utilities/src/main/kotlin/net/corda/uniqueness/utils/UniquenessAssertions.kt
> +    private inline fun <reified T> assertRejectedResultCommon(
Again seems a bit inconsistent to have thrown a private function amongst a load of public functions, but there's some argument to say that this is then used by the following "rejected" response functions, so I won't insist on changing this.

Just bear in mind there should be some sensible pattern to how these are ordered, and it should be consistent, which means conforming to the existing precedent in the file if you're not writing one from scratch.

2022-10-21 14:49 UTC, relyafi commented on testing/uniqueness/uniqueness-utilities/src/main/kotlin/net/corda/uniqueness/utils/UniquenessAssertions.kt
> +        assertInstanceOf(T::class.java, result)
This shouldn't be reified / take T, because we know that in the accepted case it must always be of type `UniquenessCheckResultSuccess`

2022-10-21 14:49 UTC, relyafi commented on testing/uniqueness/uniqueness-utilities/src/main/kotlin/net/corda/uniqueness/utils/UniquenessAssertions.kt
> +        clock: AutoTickTestClock? = null
This is defining arguments in a different order to the existing Avro functions, i.e. the response (or result) in this case should be the first argument, followed by the parameters. Consistency is good engineering practice in any API, to avoid confusing users.

I don't really see a reason to deviate from what we did with the existing Avro functions, so please review all of these new functions and ensure that the arguments follow the same ordering as those where applicable.

2022-10-21 14:49 UTC, relyafi commented on testing/uniqueness/uniqueness-utilities/src/main/kotlin/net/corda/uniqueness/utils/UniquenessAssertions.kt
> +            { assertThat(unknownStates.single().stateIndex).isEqualTo(0) },
Why are we assuming that the state index will always be 0? It may be that it's because this is how it is being used now, but unlike my earlier comment regarding taking a single (vs list) of states this one isn't acceptable because it's in no way obvious from the API that this limitation exists.

(This pattern exists in all of these state based rejection functions)

2022-10-21 14:49 UTC, relyafi commented on testing/uniqueness/uniqueness-utilities/src/main/kotlin/net/corda/uniqueness/utils/UniquenessAssertions.kt
> +        txId: SecureHash,
I'd point out that these state based functions don't follow the pattern of the Avro functions in that they assume that we are always dealing with a single unknown / conflicting state. That might be acceptable because they are currently only used in such a scenario, but does limit their reuse without a further refactoring exercise.

I won't insist on this being changed as this is potentially a "not how I would have done it" rather than a problem.

2022-10-21 14:49 UTC, relyafi commented on testing/uniqueness/uniqueness-utilities/build.gradle
> +    implementation "net.corda:corda-application"
Group this with the earlier `net.corda` includes

2022-10-21 14:49 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +    private fun now() =  Clock.systemUTC().instant()
Not sure this function is adding much value. But more importantly, this is bad practice in a test, because we can't reliably test the values. I note that in the tests where we are using this function, we are using them to generate timestamps, but are not then checking them via the support we have in the assertion functions (which we probably should do).

I'd recommend using `AutoTickTestClock` as is used in the uniqueness checker tests. This will give deterministic clock values, and will allow you to then pass it into the assertion functions to improve the time checking functionality.

2022-10-21 14:49 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +        private val DEFAULT_TIME_WINDOW_UPPER_BOUND = LocalDate.of(2200, 1, 1).atStartOfDay().toInstant(ZoneOffset.UTC)
This should be in camel case like other (non-const) variables.

2022-10-21 14:49 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +        @Disabled("This test fails because it fails to persist an error message with 1024 bytes.")
Do we have a ticket for this? If not, please can you create one, and regardless, add the Jira reference here?

2022-10-21 14:49 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +            assertThat(stateDetails.size).isEqualTo(hashCnt)
```suggestion
            assertThat(stateDetails.size).isEqualTo(secureHashes.size)
```

Would mean we can get rid of `hashCnt`

2022-10-21 14:49 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +                    session.executeTransaction { _, txnOps -> txnOps.consumeStates(consumingTxId, consumingStateRefs) }
@r3hj this still appears to be using the same tx id for both consume attempts?

2022-10-21 14:49 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +            val consumingTxId: SecureHash = SecureHashUtils.randomSecureHash()
I don't think the explicit `SecureHash` type is necessary (similar to what @nkovacsx has mentioned in a similar example [here](https://github.com/corda/corda-runtime-os/pull/2211#discussion_r986889815))

2022-10-21 14:49 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +            val spyEm = Mockito.spy(em)
Do we need explicit vals for `emFactory` and `em` given they are never used in the tests? Can;t the function calls be inlined in `spyEmFactory` and `spyEm` respectively?

2022-10-21 14:49 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +            val spyEm = Mockito.spy(em)
Do we need explicit vals for `emFactory` and `em` given they are never used in the tests? Can't the function calls be inlined in `spyEmFactory` and `spyEm` respectively?

2022-10-21 14:49 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +            val spyEmTransaction = Mockito.spy(emTransaction)
Do we need explicit vals for `emFactory`, `em` and `emTransaction` given they are never used in the tests? Can't the function calls be inlined in `spyEmFactory`, `spyEm` and `spyEmTransaction` respectively?

2022-10-21 14:49 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +        val spyEmFactory = Mockito.spy(emFactory)
Do we need an explicit val for `emFactory` given it is never used in the tests? Can't the function call be inlined in `spyEmFactory`?

2022-10-21 14:49 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +              "the reason is not clearly understood thus it can be misleading. Review with CORE-7201.")
For the record - agreed to review in the referenced ticket in the interests of time so that we can get what has been done committed, but this is an example of a test case that should have been delivered as requested in this ticket, or the reason for why it cannot be done should have been clearly understood and communicated.

2022-10-21 15:10 UTC, nkovacsx commented on testing/uniqueness/uniqueness-utilities/src/main/kotlin/net/corda/uniqueness/utils/UniquenessAssertions.kt
> +    }
I agree with this. We could either make it actually usable with multiple transactions, or just pass in one value instead of list/map. Also as I see you only get the `key` part of the map, so does it need to be a map even?

2022-10-24 10:12 UTC, r3hj commented on testing/uniqueness/uniqueness-utilities/src/main/kotlin/net/corda/uniqueness/utils/UniquenessAssertions.kt
> +import net.corda.v5.application.uniqueness.model.*
Thanks for the tip on the setting. I've updated the setting, ran intellij optimisation.

2022-10-24 10:21 UTC, r3hj commented on testing/uniqueness/uniqueness-utilities/src/main/kotlin/net/corda/uniqueness/utils/UniquenessAssertions.kt
> +    fun assertContainingTxId(txnDetails: Map<SecureHash, UniquenessCheckTransactionDetailsInternal>,
Fair point. I've regrouped them so that Avro functions appear first followed by result functions then common functions.

2022-10-24 10:28 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +            val spyEm = Mockito.spy(em)
Updated

2022-10-24 10:28 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +            val spyEm = Mockito.spy(em)
Updated

2022-10-24 10:29 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +        val spyEmFactory = Mockito.spy(emFactory)
Updated

2022-10-24 10:35 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +            val spyEmTransaction = Mockito.spy(emTransaction)
Updated to reduce lines.

2022-10-24 10:36 UTC, r3hj commented on testing/uniqueness/uniqueness-utilities/src/main/kotlin/net/corda/uniqueness/utils/UniquenessAssertions.kt
> +    private inline fun <reified T> assertRejectedResultCommon(
Updated so that all Avro functions appear first then response functions followed by any common functions.

2022-10-24 12:34 UTC, r3hj commented on testing/uniqueness/uniqueness-utilities/src/main/kotlin/net/corda/uniqueness/utils/UniquenessAssertions.kt
> +    }
What about "Checks if the given transaction details has the single and expected transaction ID." which perhaps describes the intention better.

2022-10-24 12:37 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +            }
Thanks for the clarification. Updated.

2022-10-24 13:21 UTC, relyafi commented on testing/uniqueness/uniqueness-utilities/src/main/kotlin/net/corda/uniqueness/utils/UniquenessAssertions.kt
> +    }
That sounds like a better description, yes. And we'd want to update the function signature to reflect that as well.

2022-10-24 14:16 UTC, r3hj commented on testing/uniqueness/uniqueness-utilities/src/main/kotlin/net/corda/uniqueness/utils/UniquenessAssertions.kt
> +    }
Okay. I also removed the size assert for txnDetails which seems redundant. 

    /**
     * Checks if the given transaction details has the single and expected transaction ID.
     */
    fun assertContainingTxId(txnDetails: Map<SecureHash, UniquenessCheckTransactionDetailsInternal>, txId:SecureHash) {
        assertThat(txId).isEqualTo(txnDetails.entries.single().key)
    }

2022-10-24 14:18 UTC, r3hj commented on testing/uniqueness/uniqueness-utilities/src/main/kotlin/net/corda/uniqueness/utils/UniquenessAssertions.kt
> +    }
Now it seems the helper itself is overkill. Perhaps, it's best to remove the helper itself?

2022-10-24 14:38 UTC, relyafi commented on testing/uniqueness/uniqueness-utilities/src/main/kotlin/net/corda/uniqueness/utils/UniquenessAssertions.kt
> +    }
It's probably not redundant to check for the size of `txnDetails` if you're taking a map, because you have no guarantee that a caller wouldn't provide multiple entries. An assert function shouldn't really be throwing exceptions, which this will now do without the assert.

The correct interface would be to take a `Pair`, not a `Map`, then it could only ever take one. But I get that pushes complexity into the tests since the backing store calls will return a map.

Ultimately you need to make a decision as to what the function is trying to achieve and whether it's worth having or not. I'm not too bothered either way as long as it's consistent and we're not throwing unnecessary unhandled exceptions in tests.

2022-10-24 14:55 UTC, r3hj commented on testing/uniqueness/uniqueness-utilities/src/main/kotlin/net/corda/uniqueness/utils/UniquenessAssertions.kt
> +    }
If the size assert is not redundant, keeping the help method would make tests slightly neater. I'll make the help take a map and a single secure hash.

2022-10-24 15:25 UTC, r3hj commented on testing/uniqueness/uniqueness-utilities/src/main/kotlin/net/corda/uniqueness/utils/UniquenessAssertions.kt
> +        assertInstanceOf(T::class.java, result)
Good point. Removed the reified and type check.

2022-10-24 16:13 UTC, r3hj commented on testing/uniqueness/uniqueness-utilities/src/main/kotlin/net/corda/uniqueness/utils/UniquenessAssertions.kt
> +        val failureImpl = result as UniquenessCheckResultFailureImpl
The type check in assertRejectedResultCommon is redundant in tests so removed.

As for the second point, I tested again using a test for UniquenessCheckErrorInputStateUnknown.

        assertInstanceOf(T::class.java, result)
        val failure = result as UniquenessCheckResultFailure
        return failure.error as T
    OR
        val failure = result as UniquenessCheckResultFailure
        assertInstanceOf(T::class.java, failure)
        return failure.error as T
Both result in a failure because UniquenessCheckErrorInputStateUnknown was expected but it was UniquenessCheckResultFailureImpl. Admittedly, the result and error type hierarchy is confusing to me and I'm still learning Kotlin. Can you please clarify if the above examples are what you meant by following the pattern or if anything is missing? Or do you suggest the helper signature should be updated?

2022-10-24 16:26 UTC, relyafi commented on testing/uniqueness/uniqueness-utilities/src/main/kotlin/net/corda/uniqueness/utils/UniquenessAssertions.kt
> +        val failureImpl = result as UniquenessCheckResultFailureImpl
`UniquenessCheckResultFailure` is the interface, `UniquenessCheckResultFailureImpl` is the implementation, so `assertInstanceOf` is probably going to fail unless you check for `UniquenessCheckResultFailureImpl`. I suspect you're getting confused because as it stands, you need to do two casts, and therefore you'd need to do two assertions - first for `UniquenessCheckResultFailureImpl`, then for T.

If you did what @nkovacsx said in his first comment in this conversation, you could avoid this altogether by just taking a `UniquenessCheckResultFailure` as the argument. That would mean this code could basically be the same as the existing `getResultOfType` function.

2022-10-25 08:44 UTC, r3hj commented on testing/uniqueness/uniqueness-utilities/src/main/kotlin/net/corda/uniqueness/utils/UniquenessAssertions.kt
> +            { assertThat(unknownStates.single().stateIndex).isEqualTo(0) },
Updated the test and the helper to verify state index.

2022-10-25 09:39 UTC, r3hj commented on testing/uniqueness/uniqueness-utilities/src/main/kotlin/net/corda/uniqueness/utils/UniquenessAssertions.kt
> +        clock: AutoTickTestClock? = null
Updated

2022-10-25 10:07 UTC, r3hj commented on testing/uniqueness/uniqueness-utilities/src/main/kotlin/net/corda/uniqueness/utils/UniquenessAssertions.kt
> +        txId: SecureHash,
Thanks for the feedback.

2022-10-25 12:25 UTC, r3hj commented on testing/uniqueness/uniqueness-utilities/src/main/kotlin/net/corda/uniqueness/utils/UniquenessAssertions.kt
> +        val failureImpl = result as UniquenessCheckResultFailureImpl
Below is the updated helper and its usage. 

    private inline fun <reified T> getErrorOfType(result: UniquenessCheckResultFailure): T {
        assertInstanceOf(T::class.java, result.error)
        return result.error as T
    }
    
    val unknownStates = (getErrorOfType<UniquenessCheckErrorInputStateUnknown>(
            result as UniquenessCheckResultFailure
        )).unknownStates

2022-10-26 12:36 UTC, relyafi commented on testing/uniqueness/uniqueness-utilities/src/main/kotlin/net/corda/uniqueness/utils/UniquenessAssertions.kt
> +            { assertThat(unknownStates.single().stateIndex).isEqualTo(0) },
@r3hj this has not been properly resolved; the conflict functions are still hard-coded to 0.

2022-10-26 12:42 UTC, relyafi commented
@r3hj This is not ready for re-review, as there appear to still be multiple comments that have not been addressed.

Please resolve / respond to all comments before submitting for re-review.

2022-10-26 12:44 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +        private val DEFAULT_TIME_WINDOW_UPPER_BOUND = LocalDate.of(2200, 1, 1).atStartOfDay().toInstant(ZoneOffset.UTC)
Updated

2022-10-26 12:58 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +        @Disabled("This test fails because it fails to persist an error message with 1024 bytes.")
Created CORE-7278 and updated the description, thanks.

2022-10-26 12:59 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +            assertThat(stateDetails.size).isEqualTo(hashCnt)
Updated

2022-10-26 13:01 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +            val consumingTxId: SecureHash = SecureHashUtils.randomSecureHash()
Updated

2022-10-26 13:12 UTC, r3hj commented on testing/uniqueness/uniqueness-utilities/src/main/kotlin/net/corda/uniqueness/utils/UniquenessAssertions.kt
> +            { assertThat(unknownStates.single().stateIndex).isEqualTo(0) },
Thanks. Updated.

2022-10-26 13:22 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +    private fun now() =  Clock.systemUTC().instant()
Updated to use AutoTickTestClock following the example in other test suite.

2022-10-26 13:24 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +    fun `Persisting with an incorrect identity throws an expected exception`() {
The title has been updated to be clearer. Also, the test's been disabled to be dealt as a separate ticket.

2022-10-26 13:25 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +              "the reason is not clearly understood thus it can be misleading. Review with CORE-7201.")
Updated the comment regarding the risk, and reason why it's been postponed. Please let me know if you think this is a blocker.

2022-10-26 13:26 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +                    session.executeTransaction { _, txnOps -> txnOps.consumeStates(consumingTxId, consumingStateRefs) }
Updated to use two random hashes.

2022-10-26 14:25 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +    private fun now() =  Clock.systemUTC().instant()
@r3hj reopening as this has still not been resolved properly; the same clock value is being used for every test case and we are not checking the clock value in the assertions as was suggested in the review comment.

2022-10-26 14:56 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +    private fun now() =  Clock.systemUTC().instant()
I've updated so that assert methods take testClock. Can you explain what's the proper usage and why using the same clock for each test can be an issue here? Thank you.

2022-10-26 15:03 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +    private fun now() =  Clock.systemUTC().instant()
It's not an issue as such, more an example of doing the bare minimum we can get away with rather than thinking about how it is being used, and how to then make a more realistic test.

You should get rid of `currentTime()` altogether and instead call `testClock.instant()` directly in each test when you need it. This will give you a new, ever-incrementing value on each invocation. You can then pass in the test clock object into the new assertion functions you have written so that it can perform stronger checks on the expected value.

2022-10-26 15:19 UTC, r3hj commented on components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
> +    private fun now() =  Clock.systemUTC().instant()
Thanks for the explanation. Updated as suggested.

2022-10-27 10:14 UTC, relyafi commented on testing/uniqueness/uniqueness-utilities/build.gradle
> +    implementation "net.corda:corda-application"
@r3hj reopening as this still appears unaddressed

2022-10-27 10:35 UTC, r3hj commented on testing/uniqueness/uniqueness-utilities/build.gradle
> +    implementation "net.corda:corda-application"
Updated, thanks.

2022-10-27 11:47 UTC, relyafi approved these changes

2022-10-27 12:22 UTC, ronanbrowne approved these changes
LGTM (build)

2022-10-27 13:28 UTC, merged