NOTICK: investigate multi arch building of images - WIP
corda/corda-runtime-os pull request #2223
Opened 2022-09-27 17:18 UTC by ronanbrowne

Allow our CIs to produce multi arch compatible images and remove the need for a dedicated ARM job.

- Jenkins will produce 1 image, but it's manifest file will have 2 different architecture types. Local users with ARM machines (M1s etc) may still build from source if they wish.

sample output of  `docker manifest inspect <image>`  after this change from a image produced by this PR

```
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 760,
         "digest": "sha256:77daa02e02f869158cc901082aec29e39cc2a7f5d3f06ef5f4ab4b342c88f0e3",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 760,
         "digest": "sha256:c112eb0dba6d482131deb0cecd1b9e06177efc449f62347c1f15b38115c3f725",
         "platform": {
            "architecture": "arm64",
            "os": "linux"
         }
      }
   ]
}
```

Here we see both Arch types supported

2022-10-11 17:17 UTC, yarivus requested changes

2022-10-11 17:17 UTC, yarivus commented on buildSrc/src/main/groovy/DeployableContainerBuilder.groovy
> +            logger.quiet("Running on CI server - producing arm64 and amd64 images")
Code can be simplified by calling repetitive statements of all 3 clauses just once

2022-10-12 06:36 UTC, wzur-r3 commented on buildSrc/src/main/groovy/DeployableContainerBuilder.groovy
> +            logger.quiet("Running on CI server - producing arm64 and amd64 images")
or consider using https://github.com/GoogleContainerTools/jib/blob/5e30297e1e3aa31f3b4f6dbd1d715d205a734bc4/jib-core/src/main/java/com/google/cloud/tools/jib/api/JibContainerBuilder.java#L538 instead

2022-10-12 08:39 UTC, ronanbrowne commented on buildSrc/src/main/groovy/DeployableContainerBuilder.groovy
> +            logger.quiet("Running on CI server - producing arm64 and amd64 images")
Updated, thanks

2022-10-12 12:39 UTC, yarivus approved these changes
LGTM

2022-10-12 13:22 UTC, merged