CORE-5375: vnode db rollback pt2
corda/corda-runtime-os pull request #2226
Opened 2022-09-28 21:57 UTC by benmcmahon100

2022-10-18 13:57 UTC, vkolomeyko commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/cpi/liquibase/CpkDbChangeLogDTO.kt
> +package net.corda.chunking.db.impl.cpi.liquibase
Do we need this file?

2022-10-18 13:57 UTC, vkolomeyko commented on testing/cpbs/test-cordapp-for-cache-testing/src/main/kotlin/net/cordapp/testing/smoketests/virtualnode/SimplePersistenceCheckFlow.kt
> +        return jsonMarshallingService.format("Could persist fish")
```suggestion
        return with("Could persist $fish") {
             log.info(this)
             jsonMarshallingService.format(this)
        }
```

2022-10-18 13:57 UTC, vkolomeyko commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/virtualnode/helpers/ClusterBuilder.kt
> +        post("/api/v1/maintenance/virtualnode/rollbackdb/$id", "")
```suggestion
    fun syncVirtualNode(vNodeShortHashId: String) =
        post("/api/v1/maintenance/virtualnode/resyncVault/$vNodeShortHashId", "")
```

2022-10-18 13:57 UTC, vkolomeyko commented on libs/virtual-node/virtual-node-endpoints-maintenance/src/main/kotlin/net/corda/libs/virtualnode/maintenance/endpoints/v1/VirtualNodeMaintenanceRPCOps.kt
> +        description = "Rollback the virtual node database for the given virtual node short ID. Then apply current CPI " +
I think description need to be updated.

2022-10-18 13:57 UTC, vkolomeyko commented on libs/virtual-node/virtual-node-endpoints-maintenance/src/main/kotlin/net/corda/libs/virtualnode/maintenance/endpoints/v1/VirtualNodeMaintenanceRPCOps.kt
> +        responseDescription = "A list of the shortIDs or the exception encountered"
What sort of `shortIDs` being returned, please? (esp. given that we pass `virtualNodeShortId` as an input parameter)

2022-10-18 14:03 UTC, benmcmahon100 commented on libs/virtual-node/virtual-node-endpoints-maintenance/src/main/kotlin/net/corda/libs/virtualnode/maintenance/endpoints/v1/VirtualNodeMaintenanceRPCOps.kt
> +        responseDescription = "A list of the shortIDs or the exception encountered"
The shortIds of the vaults that were successfully reset. We'll need to add an exception translator around the results for the operations.

2022-10-20 14:18 UTC, benmcmahon100 commented on libs/virtual-node/virtual-node-endpoints-maintenance/src/main/kotlin/net/corda/libs/virtualnode/maintenance/endpoints/v1/VirtualNodeMaintenanceRPCOps.kt
> +        description = "Rollback the virtual node database for the given virtual node short ID. Then apply current CPI " +
It should be accurate to what the operation does

2022-10-25 18:04 UTC, benmcmahon100 commented
Will take a look at the swagger baseline problem tomorrow, and also need to add an integration test or two to check the new query, but otherwise this is probably good for another pass as is.

2022-10-26 07:22 UTC, vkolomeyko commented
> Will take a look at the swagger baseline problem tomorrow, and also need to add an integration test or two to check the new query, but otherwise this is probably good for another pass as is.

Looks like `swaggerBaseline.json` had been re-formatted. @benmcmahon100 - could you please undo formatting change leaving only the endpoint that had been added?

2022-10-26 08:53 UTC, vkolomeyko commented on components/virtual-node/virtual-node-rpcops-maintenance-impl/src/main/kotlin/net/corda/libs/virtualnode/maintenance/rpcops/impl/v1/VirtualNodeMaintenanceRPCOpsImpl.kt
> +    private fun resyncVirtualNodeDbs(virtualNodeShortIds: List<String>): List<String> {
Do we need to have this `private` function taking a `List`? (btw why not `Set`?)
Is intention to sync DBs for multiple vNodes in one invocation? IMO this is unnecessary as it will complicate things when we have to deal with partial success scenario.

2022-10-26 08:53 UTC, vkolomeyko commented on libs/virtual-node/virtual-node-endpoints-maintenance/src/main/kotlin/net/corda/libs/virtualnode/maintenance/endpoints/v1/VirtualNodeMaintenanceRPCOps.kt
> +        responseDescription = "A list of the shortIDs or the exception encountered"
But in case of a successful call will it ever be different to `listOf(virtualNodeShortId)` ? If not, what is the point of having return value at all?

2022-10-26 08:53 UTC, vkolomeyko commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeDbChangeLogAudit.kt
> +class VirtualNodeDbChangeLogAudit(
Minor: Normally there is at least one empty line between `import` and class definition.

2022-10-26 08:53 UTC, vkolomeyko commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeDbChangeLogAudit.kt
> +    override val masterChangeLogFiles: List<String>
Can it ever be more than one `MASTER_CHANGE_LOG` ?

2022-10-26 08:53 UTC, vkolomeyko commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt
> +            vNodeDbs.forEach { it.runDbMigration("${it.dbType.name}-system-final") }
Looks like `-system-final` suffix is duplicated in `systemTerminatorTag`, should we intdource it as a constant?

2022-10-26 08:53 UTC, vkolomeyko commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt
> +            "SELECT tag FROM ${dataSource.connection.schema}.databasechangelog " +
I wonder if there is public LB api we can use to retrieve the list of tags, rather than approach their DB table `databasechangelog` directly?

2022-10-26 08:53 UTC, vkolomeyko commented on libs/db/db-admin/src/main/kotlin/net/corda/db/admin/LiquibaseSchemaMigrator.kt
> +    fun rollBackDb(datasource: Connection, dbChange: DbChange, tagToRollbackTo: String)
Probably need to add `tagToRollbackTo` to KDocs as well.

2022-10-26 08:53 UTC, vkolomeyko commented on libs/db/db-admin/src/main/kotlin/net/corda/db/admin/LiquibaseSchemaMigrator.kt
> +    fun rollBackDb(datasource: Connection, dbChange: DbChange, controlTablesSchema: String, tagToRollbackTo: String)
Probably need to add `tagToRollbackTo` to KDocs as well.

2022-10-26 08:53 UTC, vkolomeyko commented on libs/virtual-node/cpi-datamodel/src/main/kotlin/net/corda/libs/cpi/datamodel/CpkDbChangeLogAuditEntity.kt
> +        "      changelog.id.changesetId IN :changeUUIDs",
As discussed on different PR, we need to put safeguards to ensure too long lists (> 100 elements) are not passed into `IN` clause.

2022-10-26 08:53 UTC, vkolomeyko commented on processors/rpc-processor/src/integrationTest/resources/swaggerBaseline.json
> -  "servers" : [ {
Please undo formatting for this file.

2022-10-26 09:24 UTC, sprintengine commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeDb.kt
> +    fun runDbMigration(tagToUse: String?) {
Should probably rename this parameter to indicate what `tagToUse `means

2022-10-26 09:24 UTC, conalsmith-r3 commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeDbChangeLogAudit.kt
> +        const val MASTER_CHANGE_LOG = "migration/db.changelog-master.xml"
what will happen when someone names their root changelog file differently?

2022-10-26 09:30 UTC, vkolomeyko commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/virtualnode/VirtualNodeRpcTest.kt
> +    @Order(82)
Should this test be repeated as `@Order(110)` to make sure DB updated as expected when force CPI update is reverted?

2022-10-26 10:37 UTC, benmcmahon100 commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeDbChangeLogAudit.kt
> +        const val MASTER_CHANGE_LOG = "migration/db.changelog-master.xml"
So this is lifted straight from the non audit equivalent so I'd presume that we don't support it there either. We also don't have a mechanism anywhere to support identifying a different file as the master (I believe that's the default)

2022-10-26 10:38 UTC, benmcmahon100 commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeDb.kt
> +    fun runDbMigration(tagToUse: String?) {
Sure, makes sense

2022-10-26 10:39 UTC, benmcmahon100 commented on libs/virtual-node/cpi-datamodel/src/main/kotlin/net/corda/libs/cpi/datamodel/CpkDbChangeLogAuditEntity.kt
> +        "      changelog.id.changesetId IN :changeUUIDs",
Agree with the limit, but not sure 100 makes sense. I've seen projects exceed that before and we need the whole list. Let me take another look at this though as I think it l it might always be a list of 1

2022-10-26 10:40 UTC, benmcmahon100 commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt
> +            "SELECT tag FROM ${dataSource.connection.schema}.databasechangelog " +
I don't think so, but @driessamyn proposed adding it to the virtual node instance which I think makes sense. Agreed to do that change as a follow up pr

2022-10-26 10:40 UTC, benmcmahon100 commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt
> +            vNodeDbs.forEach { it.runDbMigration("${it.dbType.name}-system-final") }
Can have a look. Constants don't seem to support that string templating, but it might work if VAULT is a constant

2022-10-26 10:41 UTC, benmcmahon100 commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeDbChangeLogAudit.kt
> +    override val masterChangeLogFiles: List<String>
I don't think so but this is copied from the non audit equivalent so I'm hesitant to change it

2022-10-26 10:42 UTC, benmcmahon100 commented on components/virtual-node/virtual-node-rpcops-maintenance-impl/src/main/kotlin/net/corda/libs/virtualnode/maintenance/rpcops/impl/v1/VirtualNodeMaintenanceRPCOpsImpl.kt
> +    private fun resyncVirtualNodeDbs(virtualNodeShortIds: List<String>): List<String> {
The idea was to allow another endpoint for bulk operations later on, but maybe that's overkill for now

2022-10-26 11:30 UTC, benmcmahon100 commented on libs/virtual-node/cpi-datamodel/src/main/kotlin/net/corda/libs/cpi/datamodel/CpkDbChangeLogAuditEntity.kt
> +        "      changelog.id.changesetId IN :changeUUIDs",
Ah okay I got the wrong idea - this will be a list as it was meant to allow more complex rollbacks involving multiple changesets. I think let's introduce the limit for now, as I think this might be more complex again - depending on what we want to achieve in terms of flexibility

2022-10-26 11:36 UTC, benmcmahon100 commented
So something for consideration is the combination of these two ideas: https://github.com/corda/corda-runtime-os/pull/2226#discussion_r1005402353 and https://github.com/corda/corda-runtime-os/pull/2226#discussion_r1005395665.

The issue with adding the last applied changeset to the virtual node instance table would be that it'd only allow rollingback the last applied changetset, which I think would break if there's been other changesets applied between the start of time and now. A case that'd trigger the above is cpi upload > upload new cpi and upgrade with compatible changset, force upload with incompatible changeset and attempt a resync.

 I guess the thing here is how complex of a scenario we want to support. Looking up the databasechangelog table directly allows all changesets to be rolledback to the system state no matter what, but does have the downside of requiring no changes in the liquibase API.
 
 @vkolomeyko I'd like to propose for the sake of this change that we'd stick with it as is like suggested before, but we'd probably want to have another table that maps the relations of applied schemas to virtual nodes so we can keep track of multiple values instead of just the last one.
 
 Additionally, WRT the limit, I'm worried we'll get a bug on it pretty much immediately, but I think maybe an arbirarty limit of 100 would be fine if I change the query to `SELECT DISTINCT`, but possibly also worth adding an index on that column for lookup.

WDYT @conalsmith-r3 @vkolomeyko ?

2022-10-26 11:38 UTC, benmcmahon100 commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/virtualnode/VirtualNodeRpcTest.kt
> +    @Order(82)
This is to ensure that the previous CPIs `dog` was persisted and that the change to fish actually meant something. This is a new flow that's not been used previously like this so I thought it made sense to sanity check that the initial state made sense

2022-10-26 11:39 UTC, benmcmahon100 commented on libs/virtual-node/virtual-node-endpoints-maintenance/src/main/kotlin/net/corda/libs/virtualnode/maintenance/endpoints/v1/VirtualNodeMaintenanceRPCOps.kt
> +        responseDescription = "A list of the shortIDs or the exception encountered"
No it won't. Possibly makes sense to modify the type to indicate more information, but not sure what to include, and would also require an API change.

2022-10-26 11:46 UTC, conalsmith-r3 commented on libs/virtual-node/cpi-datamodel/src/main/kotlin/net/corda/libs/cpi/datamodel/CpkDbChangeLogAuditEntity.kt
> +        "      changelog.id.changesetId IN :changeUUIDs",
Dan did something similar for chunking IDs in the IN query, could do something like this:

```
    private inline fun <reified T> findAll(qlString: String, ids: List<String>): List<T> {
        return entityManagerFactory.transaction { entityManager ->
            ids.chunked(100) { chunkedIds ->
                entityManager.createQuery(qlString, T::class.java)
                    .setParameter("ids", chunkedIds)
                    .resultList
            }.flatten()
        }
    }
```

2022-10-26 11:54 UTC, conalsmith-r3 commented on libs/virtual-node/virtual-node-endpoints-maintenance/src/main/kotlin/net/corda/libs/virtualnode/maintenance/endpoints/v1/VirtualNodeMaintenanceRPCOps.kt
> +            "migrations. This operation is destructive and will resort in user vault data being deleted, but will " +
Typo - "resort" -> "result"

2022-10-26 12:11 UTC, conalsmith-r3 commented on libs/virtual-node/virtual-node-endpoints-maintenance/src/main/kotlin/net/corda/libs/virtualnode/maintenance/endpoints/v1/VirtualNodeMaintenanceRPCOps.kt
> +        path = "resyncVault/{virtualNodeShortId}",
From a REST endpoint perspective I think we could rearrange this path to better follow the pattern of "resource/<identifier>/subresource"
- `/api/v1/maintenance/virtualnode/{virtualNodeShortHash}/resyncVault`

How do you feel about adding a subresource under `virtualnode`, maybe this could make it clearer to the user that they are re-synchronizing the vault schema after a CPI has been force uploaded, along with the word "force" in the path:

- `/api/v1/maintenance/virtualnode/{virtualNodeShortHash}/vault-schema/force-synchronize`
- `/api/v1/maintenance/virtualnode/{virtualNodeShortHash}/vault-schema/force-resync`
- `/api/v1/maintenance/virtualnode/{virtualNodeShortHash}/vault/force-resync-vault`

Personally I like the first option, I think it makes it clearer what's happening. Wdyt @vkolomeyko ?

2022-10-26 12:40 UTC, vkolomeyko commented on libs/virtual-node/virtual-node-endpoints-maintenance/src/main/kotlin/net/corda/libs/virtualnode/maintenance/endpoints/v1/VirtualNodeMaintenanceRPCOps.kt
> +        path = "resyncVault/{virtualNodeShortId}",
Yes, second option: `/api/v1/maintenance/virtualnode/{virtualNodeShortHash}/vault-schema/force-resync` would be my preference.

2022-10-26 13:32 UTC, conalsmith-r3 commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/virtualnode/VirtualNodeRpcTest.kt
> +            runSimplePersistenceCheckFlow("\"Could persist dog\"")
Just a thought, you don't have to change it, but if you don't use jsonMarshallingService in your flow and just return this string you won't have to add escaped quotation marks

2022-10-26 16:24 UTC, benmcmahon100 commented on libs/virtual-node/cpi-datamodel/src/main/kotlin/net/corda/libs/cpi/datamodel/CpkDbChangeLogAuditEntity.kt
> +        "      changelog.id.changesetId IN :changeUUIDs",
So I don't think we can chunk this as is. I think you'd have to add support to it in the liquibase resource accessor and I think that might be a bride too far for this PR. I'm not against doing it as a follow up task though.

2022-10-26 16:26 UTC, benmcmahon100 commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeDbChangeLogAudit.kt
> +        const val MASTER_CHANGE_LOG = "migration/db.changelog-master.xml"
Also considered trying to homogenize the two but not sure it's worth doing in this PR

2022-10-26 16:27 UTC, conalsmith-r3 commented on libs/virtual-node/cpi-datamodel/src/main/kotlin/net/corda/libs/cpi/datamodel/CpkDbChangeLogAuditEntity.kt
> +        "      changelog.id.changesetId IN :changeUUIDs",
It just breaks up the query into several queries, as using too many ids in an `IN` clause can cause poor performance, after the chunking query you still result in all the entities loaded in memory

2022-10-26 16:35 UTC, benmcmahon100 commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt
> +            vNodeDbs.forEach { it.runDbMigration("${it.dbType.name}-system-final") }
I've made both use the same variable at least as it should be the only place it turns up.

2022-10-26 17:25 UTC, benmcmahon100 commented on libs/virtual-node/cpi-datamodel/src/main/kotlin/net/corda/libs/cpi/datamodel/CpkDbChangeLogAuditEntity.kt
> +        "      changelog.id.changesetId IN :changeUUIDs",
Ah sorry I get you I thought it was trying to chunk the results too - sure let's do that

2022-10-27 08:50 UTC, vkolomeyko commented on components/virtual-node/virtual-node-rpcops-maintenance-impl/src/main/kotlin/net/corda/libs/virtualnode/maintenance/rpcops/impl/v1/VirtualNodeMaintenanceRPCOpsImpl.kt
> +    private fun resyncVirtualNodeDbs(virtualNodeShortIds: List<String>): List<String> {
I do not think it would be worthwhile to extend it to bulk operation at this point in time.
Could we merge those 2 methods into 1?

2022-10-27 08:50 UTC, vkolomeyko commented on libs/virtual-node/virtual-node-endpoints-maintenance/src/main/kotlin/net/corda/libs/virtualnode/maintenance/endpoints/v1/VirtualNodeMaintenanceRPCOps.kt
> +        responseDescription = "A list of the shortIDs or the exception encountered"
I propose we remove return value completely.
@conalsmith-r3 - WDYT?

2022-10-27 09:17 UTC, conalsmith-r3 commented on libs/virtual-node/virtual-node-endpoints-maintenance/src/main/kotlin/net/corda/libs/virtualnode/maintenance/endpoints/v1/VirtualNodeMaintenanceRPCOps.kt
> +        responseDescription = "A list of the shortIDs or the exception encountered"
Makes sense to return nothing, if it fails there is exception handling to throw an `InternalServerError`.

We are running this operation against one virtual node, it would be different if the endpoint was `/api/v1/cpi/{checksum}/sync-all-vaults` and synchronized all virtual nodes using the force uploaded CPI, but after force uploading the user/admin has to manually sync each vnode one by one, which is what we want, thus they can tell if the success response is a 200 that it succeeded.

2022-10-27 10:04 UTC, vkolomeyko commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/virtualnode/VirtualNodeRpcTest.kt
> +    @Order(82)
As discussed on [Slack](https://r3holdco.slack.com/archives/C03AYSL75HQ/p1666861701257999?thread_ts=1666788313.753379&cid=C03AYSL75HQ), let's add another test which asserts that `Dog` table is indeed restored once we reverted to the original CPI.

2022-10-27 10:08 UTC, vkolomeyko commented on libs/virtual-node/virtual-node-endpoints-maintenance/src/main/kotlin/net/corda/libs/virtualnode/maintenance/endpoints/v1/VirtualNodeMaintenanceRPCOps.kt
> +        responseDescription = "A list of the shortIDs or the exception encountered"
I am a bit worried about running `syncVaultDb` operation as one call against multiple vNodes as in this case we might have partial success scenario from which it may be not trivial to recover.

I think it would make sense to operation aimed at one vNode only, if multiple vNodes will need to be DB sync-ed, it should be possible to make individual Rest calls.

2022-10-27 10:33 UTC, benmcmahon100 commented on libs/virtual-node/virtual-node-endpoints-maintenance/src/main/kotlin/net/corda/libs/virtualnode/maintenance/endpoints/v1/VirtualNodeMaintenanceRPCOps.kt
> +        responseDescription = "A list of the shortIDs or the exception encountered"
Sure makes sense to me. I'll drop the inner type from runtime as I think that'll just work. I'll do a separate PR to remove the type from api

2022-10-27 13:32 UTC, vkolomeyko approved these changes, later dismissed
LGTM

2022-10-27 16:43 UTC, driessamyn requested changes
Overall looks ok, but there's a couple of small things that I think won't work.

2022-10-27 16:43 UTC, driessamyn commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeDbChangeLogAudit.kt
> +        const val MASTER_CHANGE_LOG = "migration/db.changelog-master.xml"
As discussed before. This is copy/pasted straight out of the non-audit one and isn't necessary.
The comments don't make sense in this location, and the constant should only be defined in one place.

2022-10-27 16:43 UTC, driessamyn commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeDbChangeLogAudit.kt
> +    }
These are duplicates of the non-audit class. Can they be made common?

2022-10-27 16:43 UTC, driessamyn commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeEntityRepository.kt
> +                val evaluatedCpiSignerSummaryHash = if (cpiSignerSummaryHash.isEmpty()) null else SecureHash.parse(cpiSignerSummaryHash)
`cpiSignerSummaryHash` can never be null or empty since V2

@josephzunigadaly , can you confirm if this can be removed here? (or add it to the ticket we have to remove v1 support)

2022-10-27 16:43 UTC, driessamyn commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt
> +                    val connectionConfig = SmartConfigFactory.create(dbConfig).create(dbConfig)
The usage of SmartConfig here is incorrect.
You need to get hold of the factory that is already configured with the secret detail. Here you are just passing in the dbConfig as the SmartConfigFactory config, which is not going to work.

2022-10-27 16:43 UTC, driessamyn commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt
> +                    val connectionConfig = SmartConfigFactory.create(dbConfig).create(dbConfig)
I'm not convinced you need to do any of this either. I think you should be able to use the `DbConnectionManager` to get the connection by id and privilege

2022-10-27 16:43 UTC, driessamyn commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt
> +        val systemTerminatorTag = "${VAULT.name}-system-final"
What does systemTerminatorTag do?

2022-10-27 16:43 UTC, driessamyn commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt
> +                        measureTimeMillis {
We don't need these metrics like this. They were (temporarily) put in the other operations to troubleshoot an issue. 
If we want them, we should add them as proper metrics with the recently introduced metrics library, but I would suggest taking them out for now. This isn't a performance critical operation.

2022-10-27 16:43 UTC, driessamyn commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt
> +    @Suppress("UNCHECKED_CAST")
We need a JIRA to remove this and add it to the Vnode table as we don't want a reference to the Liquibase internals in our code.

2022-10-28 07:37 UTC, driessamyn commented on libs/db/db-admin-impl/src/main/kotlin/net/corda/db/admin/impl/LiquibaseSchemaMigratorImpl.kt
> +        } else {
Try to limit unnecessary formatting changes that make the PR harder to review.

Why was the log instruction removed?

2022-10-28 07:40 UTC, driessamyn commented on libs/virtual-node/cpi-datamodel/src/main/kotlin/net/corda/libs/cpi/datamodel/CpkDbChangeLogAuditEntity.kt
> +): List<CpkDbChangeLogAuditEntity> = changesetIds.chunked(100) { changesetIdSlice ->
Why is this chunked?

2022-10-28 07:48 UTC, driessamyn commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt
> +            val newChangeSetId = cpkChangelogs.first().changesetId
Can you explain this filter/sort logic in a comment?
I don't really understand what is going on here and why it is sorted, for example.

2022-10-28 07:49 UTC, driessamyn commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt
> +                val changesetId = cpkChangelogs.last().changesetId
What is `last` here? What order of the changelogs list is assumed?

2022-10-28 07:54 UTC, driessamyn commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeDbChangeLogAudit.kt
> +        const val MASTER_CHANGE_LOG = "migration/db.changelog-master.xml"
Looking at this again. Why do you need this class at all? There is no difference between `VirtualNodeDbChangeLog` and `VirtualNodeDbChangeLogAudit` apart from the type in the list (`CpkDbChangeLogEntity` vs `CpkDbChangeLogAuditEntity`), which are nearly identical either (for obvious reasons, and non of the differences are relevant in this class, so this could just be handled by using an interface as the type in that list instead of concrete types.

2022-10-28 10:04 UTC, benmcmahon100 commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeDbChangeLogAudit.kt
> +        const val MASTER_CHANGE_LOG = "migration/db.changelog-master.xml"
Yeah they are the same - I didn't try unify them to try reduce the footprint of the change, but strictly speaking they could be unified into one.

2022-10-28 10:06 UTC, benmcmahon100 commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt
> +        val systemTerminatorTag = "${VAULT.name}-system-final"
It's a tag added to the last migration ran by `runDbMigraions` it's used as an anchor to a point in time that we roll back to.

2022-10-28 10:09 UTC, benmcmahon100 commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt
> +    @Suppress("UNCHECKED_CAST")
Small thing here - but we can't add it to the vnode table itself, as there could be multiple changesets applied, but agreed on the ticket - will link

2022-10-28 10:12 UTC, benmcmahon100 commented on libs/virtual-node/cpi-datamodel/src/main/kotlin/net/corda/libs/cpi/datamodel/CpkDbChangeLogAuditEntity.kt
> +): List<CpkDbChangeLogAuditEntity> = changesetIds.chunked(100) { changesetIdSlice ->
Was in response to this https://github.com/corda/corda-runtime-os/pull/2226#discussion_r1005402353

2022-10-28 10:14 UTC, benmcmahon100 commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt
> +            val newChangeSetId = cpkChangelogs.first().changesetId
I took this from the other migration code so that it'd behave the same. I didn't want to change one and not the other one. https://github.com/corda/corda-runtime-os/blob/66808658dd55730cf1861d3367f4f352f717710b/components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt#L440-L441

2022-10-28 10:15 UTC, benmcmahon100 commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt
> +                val changesetId = cpkChangelogs.last().changesetId
Last could be first. They'll all have the same ID so you can use any one to extract the ID.

2022-10-28 10:21 UTC, benmcmahon100 commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt
> +                    val connectionConfig = SmartConfigFactory.create(dbConfig).create(dbConfig)
That method returns a different type. The runCpiMigrations method requires the connection config as well, so that'd also require changing to accommodate.

2022-10-28 10:31 UTC, benmcmahon100 commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt
> +    @Suppress("UNCHECKED_CAST")
https://r3-cev.atlassian.net/browse/CORE-7302

2022-10-28 10:59 UTC, driessamyn commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt
> +    @Suppress("UNCHECKED_CAST")
> but we can't add it to the vnode table itself, as there could be multiple changesets applied, but agreed on the ticket 

Wouldn't they all have the same change ID?

Or to put it differently, why shouldn't they have the same change ID?

2022-10-28 11:00 UTC, driessamyn commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeDbChangeLogAudit.kt
> +        const val MASTER_CHANGE_LOG = "migration/db.changelog-master.xml"
But you added more code. This class doesn't add anything that isn't in the other.

2022-10-28 11:02 UTC, driessamyn commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt
> +                    val connectionConfig = SmartConfigFactory.create(dbConfig).create(dbConfig)
Not sure I understand. The responsibility of the `DbConnectionManager` is to manage the DB connections so that you don't have to do this.
Either way, what you have can't work (and I'm suspicious about why that isn't caught in the smoketests) as you're passing the wrong config into the factory.

2022-10-28 11:03 UTC, driessamyn commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt
> +        val systemTerminatorTag = "${VAULT.name}-system-final"
But what happens after you have done 2 upgrades? Doesn't this mean you'd have 2 identical tags?
I still don't really understand the design of this.

2022-10-28 11:04 UTC, benmcmahon100 commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt
> +                    val connectionConfig = SmartConfigFactory.create(dbConfig).create(dbConfig)
The two methods return different types so they aren't interchangeable
![image](https://user-images.githubusercontent.com/10749142/198572689-9117aec4-55c0-44d5-b974-0cb7d500ad3c.png)
So I'm not sure what the right thing to do here is.

2022-10-28 11:05 UTC, driessamyn commented on libs/virtual-node/cpi-datamodel/src/main/kotlin/net/corda/libs/cpi/datamodel/CpkDbChangeLogAuditEntity.kt
> +): List<CpkDbChangeLogAuditEntity> = changesetIds.chunked(100) { changesetIdSlice ->
Ok. I get it now. I think realistically the allowed set is much larger than 100, but 100 is probably larger than what will generally be needed, so it's ok.
It's worth clarifying this in a comment though.

2022-10-28 11:06 UTC, driessamyn commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt
> +                val changesetId = cpkChangelogs.last().changesetId
last will iterate of the entire set. If the first will do, why not pick that one?

2022-10-28 11:06 UTC, benmcmahon100 commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt
> +    @Suppress("UNCHECKED_CAST")
If you had apply migrations -> upgrade to next set of compatible migrations, then do a forceupload and resync. Obviously this isn't possible right now, but will be once the upgrade stuff is done

2022-10-28 11:07 UTC, benmcmahon100 commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt
> +        val systemTerminatorTag = "${VAULT.name}-system-final"
Not unless you change the system tables

2022-10-28 11:55 UTC, benmcmahon100 commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeDbChangeLogAudit.kt
> +        const val MASTER_CHANGE_LOG = "migration/db.changelog-master.xml"
I've combined some of the stuff from the two new types back into the original

2022-10-28 16:33 UTC, driessamyn commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt
> +    @Suppress("UNCHECKED_CAST")
But, in that case, I think you would only want to roll back the last migration (i.e. only roll back the changes you're wiping out by force-upload).

2022-10-28 16:34 UTC, driessamyn commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt
> +        val systemTerminatorTag = "${VAULT.name}-system-final"
I mean after an upgrade (so same vnode, just 2 CPIs)

2022-10-28 17:12 UTC, driessamyn commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt
> +                    val connectionConfig = SmartConfigFactory.create(dbConfig).create(dbConfig)
I think you just need to add a method to that interface to expose the appropriate type, which is effectively similar to this:

![image](https://user-images.githubusercontent.com/5557551/198694325-21c8f457-447e-44be-b955-97e33383642c.png)

2022-11-01 11:07 UTC, benmcmahon100 commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt
> +        val systemTerminatorTag = "${VAULT.name}-system-final"
That won't make a difference here. The systemTerminator is only to show when the virtual node setup has finished which is done in `runDbMigrations`. Cpi migrations are always applied via `runCpiMigrations`

2022-11-01 11:09 UTC, benmcmahon100 commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt
> +    @Suppress("UNCHECKED_CAST")
It's not guaranteed that the last migration == the changes that the forceCpiUpload will impact. The idea of this implementation is to reset the virtual node back to it's initial state but without any CPI migrations applied, and then apply the ones from the force upload. That way we don't make any assumptions about the state of the vnode - which would provide the best developer experience possible IMO.

2022-11-01 11:26 UTC, driessamyn commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt
> +    @Suppress("UNCHECKED_CAST")
But force-upload only supports replacing the last update. 

Can you sketch up a diagram that shows the flow of events? Also including the role of the `systemTerminatorTag` marker as I still don't understand how it all fits together.

2022-11-01 12:25 UTC, benmcmahon100 commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt
> +    @Suppress("UNCHECKED_CAST")
These are the two main complex cases I'm trying to cater for. The one on the right is for when upgrade is in place and you could have a complex history of applied changesets. The one on the left is multiple forceuploads without necessarily resyncing every time.
![Virtual node resync diagram](https://user-images.githubusercontent.com/10749142/199231811-142f0713-cb7f-4994-9ae9-2920aa29c018.png)

2022-11-01 13:41 UTC, driessamyn commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt
> +    @Suppress("UNCHECKED_CAST")
- What happens with "system terminator tag" when the Corda platform upgrades?
- Isn't good enough to always roll back the last changeset that was applied for the current version? I.e. if the current version is 1.0 and you force upload, then undo the last changeset that was applied as part of 1.0. If the current version is 1.1. and you force update, then ignore the 1.0 changesets, but just roll back the last one that was applied to 1.1. 

If I understand it correctly, instead you always reset all of the changesets that were applied, but doing this by "system terminator tag" I think makes some assumptions that aren't necessarily correct (e.g. when a platform upgrade has happened). 
If undoing all change sets is what we want, then why not record all applied changesets against the vnode? Although I still think it may be easier to just roll back the latest one as that is closest aligned to what force upload does.

2022-11-01 14:17 UTC, benmcmahon100 commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt
> +    @Suppress("UNCHECKED_CAST")
We could change the system terminator to include the version, of platform to get around this, but also the keeping track of what's actually applied makes sense too.
Doing that is covered in the follow up ticket to decouple from the liquibase databasechangelog table https://r3-cev.atlassian.net/browse/CORE-7302

2022-11-01 16:43 UTC, ronanbrowne approved these changes, later dismissed
LGTM (only build changes reviewed)

2022-11-02 13:13 UTC, driessamyn approved these changes
LGTM

2022-11-02 13:16 UTC, vkolomeyko approved these changes

2022-11-02 13:17 UTC, ronanbrowne approved these changes
LGTM (build)

2022-11-02 13:19 UTC, merged