CORE-7033 Uniqueness checker logging improvements
corda/corda-runtime-os pull request #2283
Opened 2022-10-10 15:39 UTC by relyafi

### Summary
Currently, the uniqueness checker is a bit light on logging. This PR adds additional logging to provide some information as to how many requests are processed when, and also provides batch processing information for each holding id. This allows some rudimentary tracing of which requests are processed when. As part of these changes, existing log messages have also been reviewed for their content and logging levels. Most messages are raised on the debug level, in accordance with [these guidelines](https://github.com/corda/platform-eng-design/blob/master/core/corda-5/corda-5.0/standards/logging.md).

This PR also makes a change to the uniqueness check test flow, used by the smoke tests so that each new request generates unique transaction hashes. Previously fixed hashes were used, which would mean that multiple calls to the smoke test would actually simply return the results from the first call.

### Testing

Temporarily added log4j2 configuration to enable logging and set to debug level when running the uniqueness checker unit tests. Ran the tests, and ensured that logging output was as expected.

Spun up a cluster, ensuring that the debug log level was enabled on the DB worker. Ran the uniqueness checker smoke test. Ensured that the DB worker correctly output the new log messages introduced in this PR.

2022-10-10 15:52 UTC, nkovacsx requested changes

2022-10-10 15:52 UTC, nkovacsx commented on components/uniqueness/backing-store-impl/src/main/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImpl.kt
> +                                log.debug { "Rolled back transaction" }
For debug we use function as a parameter `{}`, but for the others we use strings `("")`. Could we normalise this somehow?

2022-10-10 15:52 UTC, nkovacsx commented on components/uniqueness/backing-store-impl/src/main/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImpl.kt
> +                log.warn("Unexpected event ${event}, ignoring")
Why do we need curly braces for one variable? `$event` should be fine.

2022-10-10 15:52 UTC, nkovacsx commented on components/uniqueness/uniqueness-checker-impl/src/main/kotlin/net/corda/uniqueness/checker/impl/BatchedUniquenessCheckerImpl.kt
> +                log.warn("Unexpected event ${event}, ignoring")
see my comment before

2022-10-10 16:01 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/main/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImpl.kt
> +                log.warn("Unexpected event ${event}, ignoring")
That is the case when the variable name is followed by a space, but wanted to avoid ambiguity due to the following comma. IntelliJ normally warns if this is redundant and it didn't in this case.

2022-10-10 16:03 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/main/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImpl.kt
> +                                log.debug { "Rolled back transaction" }
The {} is a Corda library function which is an optimisation to only evaluate and print the log message if debug logging is actually enabled - basically it avoids having to explicitly check before each time we write to the debug level. It's important because a) debug generally won't be on and b) you're probably doing more verbose / complex logging.

I don't think we have equivalents for info and warn because we'd generally expect them to be always enabled anyway.

2022-10-12 08:43 UTC, nkovacsx commented on components/uniqueness/backing-store-impl/src/main/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImpl.kt
> +                                log.debug { "Rolled back transaction" }
That makes sense, I was mostly aiming for consistency but if we can't do it, it's fine :)

2022-10-12 08:43 UTC, nkovacsx commented on components/uniqueness/backing-store-impl/src/main/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImpl.kt
> +                log.warn("Unexpected event ${event}, ignoring")
Good point!

2022-10-12 08:44 UTC, nkovacsx approved these changes

2022-10-12 08:48 UTC, merged