CORE-6663: Create `FlowExecutorRole`
corda/corda-runtime-os pull request #2292
Opened 2022-10-11 13:39 UTC by vkolomeyko

2022-10-13 14:11 UTC, vkolomeyko commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt
> +            executorService.submit {
The "meat" of the change.

2022-10-13 15:21 UTC, vkolomeyko commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt
> +                        permissionManagerSupplier.get().createRbacRole(
This code is executed on DBWorker side, here we send a Kafka messages for the role and permissions  to be created. These messages DBWorker in effect sends to self.

@driessamyn - since I have not seen this pattern used anywhere else, I wanted to make sure you are comfortable with this approach at vNode creation time.

2022-10-14 10:07 UTC, conalsmith-r3 commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt
> +                        permissionManagerSupplier.get().createRbacRole(
I think in future the whole create virtual node endpoint will have to become asynchronous, membership registration could take some time. So I think adding some async elements to this endpoint are OK. In future maybe we can update a status topic with progress i.e. "Creating virtual node RBAC roles"

2022-10-14 10:16 UTC, vkolomeyko commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt
> +                        permissionManagerSupplier.get().createRbacRole(
Yes, I though along the same lines.

However, it was necessary to move roles creation into a separate thread pretty much now or else vNode create Rest will timeout after 12 seconds waiting for ack of vNode creation.

2022-10-14 11:10 UTC, conalsmith-r3 commented on processors/db-processor/build.gradle
> +    implementation project(':components:permissions:permission-management-service')
Just checking if you need to bring in entire permission management service or can you get away with just the PermissionManagerFactory?

2022-10-14 11:14 UTC, conalsmith-r3 submitted a review, later dismissed
Looks good to me

2022-10-14 13:03 UTC, ronanbrowne submitted a review, later dismissed
LGTM (Build Changes)

2022-10-14 15:45 UTC, driessamyn commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt
> +            // operation asynchronously in order not to delay main vNode creation function.
I'm not sure if this is the right thing to do. I'd be keen to get @mnesbit 's input.

I think a general design principle was that all operations are single threaded and that Kafka is how we distribute work.
I agree that this is now doing a lot of things, and we definitely need to make the whole operation asynchronous, but I wonder if the design here isn't right and if instead we should publish "create permission" instructions on a durable Kafka topic for another processor to pick up and complete.

2022-10-17 08:05 UTC, mnesbit commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt
> +            // operation asynchronously in order not to delay main vNode creation function.
We shouldn't be doing any automatic logic of this kind for permissions. It is an external choice what permission structure admins want. Also we had sufficient wildcard pattern logic in the original that we could make a universal filter for flow/non-flow operations without reference to knowing the vnode id.

2022-10-17 08:08 UTC, mnesbit requested changes
We need to discuss this as I don't think this is right way to do things

2022-10-24 11:23 UTC, vkolomeyko commented
@mnesbit - as discussed, I have re-worked this PR and created a dedicated CLI command for `FlowExecutor` RBAC role creation.

2022-10-24 13:25 UTC, mnesbit approved these changes
OK

2022-10-24 13:56 UTC, ronanbrowne approved these changes
LGTM (build changes)

2022-10-24 13:57 UTC, merged