CORE-6336 add MDC logging info to the flow service
corda/corda-runtime-os pull request #2357
Opened 2022-10-19 14:19 UTC by LWogan

add MDC logging info to the flow service  for clientid, vnodeid and external event id. Pass MDC logging to the fiber via flow fiber execution context.

2022-10-25 09:37 UTC, JamesHR3 commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/impl/FlowEventProcessorImpl.kt
> +        pushLoggingMDC(getFlowMDCLogging(state, event.value))
I don't think this function is completely safe when it comes to setting and clearing the MDC. You might bail out the function early if the pipeline isn't created successfully for example.

I think you might want to create some extension that allows you to execute some block of code with an MDC attached, and clear it once the block has returned, e.g.

```kotlin
fun withMDC(mdcProperties: Map<String, String>, block: () -> Unit) {
    try {
       pushLoggingMDC(mdcProperties)
       block()
    } finally {
        clearLoggingMDC(mdcProperties)
    }
}
```

2022-10-25 09:37 UTC, JamesHR3 commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/fiber/FlowFiberImpl.kt
> +        }
We should probably clear the previous context first. The context is a thread local, so I think it's possible that the strand that quasar is using to execute this flow has a context on it from a previous run. In theory this should overwrite the old properties and it should be fine, but I suppose if we ever added some extra property in some but not all circumstances we might get something weird.

I think this might currently break for external events because we'd hold on to the external event ID even after the request has completed?

2022-10-25 09:37 UTC, JamesHR3 commented on libs/logging/build.gradle
> +    implementation "net.corda:corda-base"
Do you need `base` here?

2022-10-25 09:37 UTC, JamesHR3 commented on libs/logging/build.gradle
> +plugins {
I'm wondering if we need this module at all? The string constants on the flow side are only going to be used in one place, and a lot of the MDC extensions are not adding much over the base slf4j API anyway. The main things I can see being useful are:

- The suggested `withMDC` function I mentioned above
- The external event string

If you do keep it I suggest simplifying a bit, and just having a file with a list of string constants in (you don't need to wrap these in an object necessarily), and a couple of utility functions for working with MDCs. I wouldn't mind removing it entirely though - a duplicated string constant isn't the end of the world.

(The reason I mention this is that there is a build time cost to more modules - when we have small ones it is worth considering why we're adding them.)

2022-10-25 11:21 UTC, simon-johnson-r3 requested changes, later dismissed

2022-10-25 11:21 UTC, simon-johnson-r3 commented on libs/logging/src/main/kotlin/net/corda/logging/mdc/MDCUtils.kt
> +fun Any.pushLoggingMDC(mdcData: Map<String, String>) {
`push` might be interpreted as stack push/pop like behaviour, would this be better as `set` which would match `clear` nicely?

2022-10-25 11:21 UTC, simon-johnson-r3 commented on libs/logging/src/main/kotlin/net/corda/logging/mdc/MDCUtils.kt
> +fun Any.clearLoggingMDC(mdcDataKeys: Set<String>) {
What is the thinking behind making these extensions of `Any`?

2022-10-25 11:21 UTC, simon-johnson-r3 commented on libs/logging/src/main/kotlin/net/corda/logging/mdc/FlowMDCFields.kt
> +    const val MDC_CLIENT_ID = "client_Id"
inconsistent capitalisation here, is this deliberate?

2022-10-25 11:21 UTC, simon-johnson-r3 commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/factory/impl/FlowFiberExecutionContextFactoryImpl.kt
> +            MDC.getCopyOfContextMap() ?: emptyMap()
It feels like there should be a better way to get the MDC context into the fiber execution context than reading it out of a singleton. `FlowEventContext` seems to be the thing that tracks such entities, so it's not really a coincidence it's passed to the factory, could it perhaps be set on that?

2022-10-25 11:21 UTC, simon-johnson-r3 commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/fiber/FlowFiberImpl.kt
> +        flowFiberExecutionContext?.mdcLoggingData?.let {
You clear logging in the other thread everywhere it's set on the way out, but the equivalent is not done in this thread I notice.

2022-10-25 11:21 UTC, simon-johnson-r3 commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/impl/FlowEventProcessorImpl.kt
> +            clearLoggingMDC(setOf(MDC_CLIENT_ID, MDC_VNODE_ID, MDC_EXTERNAL_EVENT_ID))
You could make this a bit more maintainable by storing these fields as a single enum backed by a string:
```
    enum class FlowMdcFields(val field: String) {
        MDC_CLIENT_ID("external_event_id"),
        MDC_VNODE_ID("client_Id"),
        MDC_EXTERNAL_EVENT_ID("vnode_id")
    }
```
And then clear them all without caring about any new items added:
```
clearLoggingMDC(FlowMdcFields.values().map { it.field }.toSet())
```

2022-10-26 15:04 UTC, LWogan commented on libs/logging/build.gradle
> +plugins {
>  flow side are only going to be used in one place 

yeah i went back and forth with this. external event id is flow side and db side. it seemed reasonable to to centralize it rather than define a string constant in multiple places. i considered putting them into base but that seemed bad idea. Id expect the MDC logging to be expanded quite a bit over time and for it to cross lib/component boundaries. its external event id that drove this.

we do have too many projects, but this wont be the first time  something like this has come up. i wonder is there value in some simple common constants lib that can be a catch all. although its late in the day for it

2022-10-27 09:10 UTC, lankydan commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/impl/FlowEventProcessorImpl.kt
> +    private fun getFlowMDCLogging(checkpoint: Checkpoint?, event: FlowEvent?): Map<String, String> {
I think we should extract all this code out to another service or some functions not contained in this file (probably doesn't need to be a service)

2022-10-27 09:11 UTC, lankydan commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/impl/FlowEventProcessorImpl.kt
> +    private fun getFlowMDCLogging(checkpoint: Checkpoint?, event: FlowEvent?): Map<String, String> {
Actually after writing the comment, I'm not so sure. I'll leave it to you :)

2022-10-27 09:13 UTC, lankydan commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/impl/FlowEventProcessorImpl.kt
> +        return if (payload is StartFlow) {
Wouldn't session inits cause the `else` block to execute?

2022-10-27 09:16 UTC, lankydan commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/impl/FlowEventProcessorImpl.kt
> +    private fun setExternalEventIdIfNotComplete(
I wonder if there is really any benefit to logging the external event id. Since the external event id itself is already logged where needed. Seeing non-external event log lines including the external event id, is unlikely to bring any benefit.

2022-10-27 09:23 UTC, lankydan commented on components/flow/flow-service/src/test/java/net/corda/flow/application/sessions/FlowSessionImplJavaTest.java
> +            Collections.emptyMap()
Since we're on Java 11, you should be able to do `Map.of()`.

2022-10-27 09:32 UTC, lankydan commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/impl/FlowEventProcessorImpl.kt
> +    private fun setExternalEventIdIfNotComplete(
Saw your comment about it on other workers, I think that makes sense, but that is because there is more general processing occurring on the other workers. Whereas an external event comes in here goes only through the external event processing code and back out.

2022-10-27 10:43 UTC, LWogan commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/fiber/FlowFiberImpl.kt
> +        }
made some updates around external event id handling. it will only set it if there's no response or we have a response that it is still retrying internally

2022-10-27 10:43 UTC, LWogan commented on libs/logging/build.gradle
> +    implementation "net.corda:corda-base"
no i was just pulling in slf4j that way, removed

2022-10-27 10:44 UTC, LWogan commented on libs/logging/src/main/kotlin/net/corda/logging/mdc/MDCUtils.kt
> +fun Any.clearLoggingMDC(mdcDataKeys: Set<String>) {
remnant of a previous impl where i was calling the functions off the logger

2022-10-27 10:46 UTC, LWogan commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/impl/FlowEventProcessorImpl.kt
> +    private fun setExternalEventIdIfNotComplete(
on the other workers we're only logging the external event id so it has to be logged this side to tie the two together

2022-10-27 10:55 UTC, LWogan commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/impl/FlowEventProcessorImpl.kt
> +    private fun getFlowMDCLogging(checkpoint: Checkpoint?, event: FlowEvent?): Map<String, String> {
yeah i considered it but then i thought as this is the only class this code will ever be used and the class isnt that long it didnt seem so bad. 50/50 call

2022-10-27 10:58 UTC, LWogan commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/impl/FlowEventProcessorImpl.kt
> +        return if (payload is StartFlow) {
i had not considered this. ill add handling for the initiated session.

i wonder should i set client_id as the session_id. 

We dont put sessionids into MDC on the initiating side. There could be many nested sessions so logging all would not be good.  if the received event into the pipeline is not a SessionEvent i dont think its possible to tell which session is the "active" one. 
@fowlerrr what do you think ?

2022-10-27 15:47 UTC, fowlerrr commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/impl/FlowEventProcessorImpl.kt
> +        return if (payload is StartFlow) {
I'm not sure a session would be useful at the level of logging we're talking about.  It's all within that one client_id anyway, isn't it?  As in, anything logged with that client_id would be a superset of the session_id?  And we really care about following the whole event as it progresses, which is marked by client_id

2022-10-28 08:50 UTC, fowlerrr reviewed
A few things.  Nothing particularly big.  Mostly usability.  From what I can tell I think we'll get what we want from the changes as they are.  But I think we can make it a bit cleaner.

2022-10-28 08:50 UTC, fowlerrr commented on libs/logging/src/main/kotlin/net/corda/logging/mdc/MDCUtils.kt
> +fun <R> withMDCAndReturn(mdcProperties: Map<String, String>, block: () -> R) : R {
I'm not sure I see the point of the two functions.  I think this one should be `withMDC` and still return.  The other can be removed (it's not used anyway) and you can use the return or not.

2022-10-28 08:50 UTC, fowlerrr commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/fiber/FlowFiberImpl.kt
> +        clearMDC()
This is the clear all for MDC.  I wonder if we should signal that more clearly?  I'm not sure what would be best.  A comment on the method and maybe a rename?  `resetLoggingContext`?

2022-10-28 08:50 UTC, fowlerrr commented on components/persistence/entity-processor-service-impl/src/main/kotlin/net/corda/entityprocessor/impl/internal/EntityMessageProcessor.kt
> +                    setMDC(mapOf(MDC_EXTERNAL_EVENT_ID to request.flowExternalEventContext.requestId))
Can we use `return withMDC {}` here?  Seeing as we've written it.  I _think_ the semantics would be the same

2022-10-28 12:53 UTC, LWogan commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/impl/FlowEventProcessorImpl.kt
> +        return if (payload is StartFlow) {
the initiated side doesnt have a client id as it was started by p2p not by rpc

2022-10-28 13:02 UTC, fowlerrr commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/impl/FlowEventProcessorImpl.kt
> +        return if (payload is StartFlow) {
Well that's awkward.  So how would we link that up with the initiating side?

2022-11-02 15:17 UTC, fowlerrr reviewed
Just the one leftover file

2022-11-02 15:17 UTC, fowlerrr commented on libs/logging/src/main/kotlin/net/corda/logging/mdc/MDCUtils.kt
>  import org.slf4j.MDC
Do you just want to delete this file?

2022-11-02 15:31 UTC, fowlerrr submitted a review, later dismissed

2022-11-02 16:48 UTC, ronanbrowne submitted a review, later dismissed
LGTM (build()

2022-11-03 08:41 UTC, fowlerrr approved these changes

2022-11-03 08:55 UTC, ronanbrowne approved these changes

2022-11-03 09:12 UTC, merged