CORE-4935 Add support for buildkit
corda/corda-runtime-os pull request #2360
Opened 2022-10-20 10:18 UTC by E1P3

2022-10-24 16:01 UTC, ronanbrowne requested changes

2022-10-24 16:01 UTC, ronanbrowne commented on buildSrc/src/main/groovy/BuildkitBuild.groovy
> +abstract class BuildkitBuild extends Exec {
```suggestion
/**
 *  Task to publish worker images to artifactory using buildkit image builder
 *  Requires buildctl client installed and a working buildkit pod from aws cluster (TBD)
 *  https://r3-cev.atlassian.net/wiki/spaces/CB/pages/4063035406/BuildKit
 */
abstract class BuildkitBuild extends Exec {
```

2022-10-24 16:01 UTC, ronanbrowne commented on buildSrc/src/main/groovy/BuildkitBuild.groovy
> +import java.nio.file.Path
import java.nio.file.Path Seems to be not used

2022-10-24 16:01 UTC, ronanbrowne commented on buildSrc/src/main/groovy/BuildkitBuild.groovy
> +import org.gradle.api.tasks.Exec
Run the default formatter on full file https://www.jetbrains.com/idea/guide/tips/reformat-file/#:~:text=You%20can%20use%20%E2%8C%98%E2%8C%A5,L%20(Windows%2FLinux).

2022-10-24 16:01 UTC, ronanbrowne commented on buildSrc/src/main/groovy/BuildkitBuild.groovy
> +                PublishImage(buildkitCommand)
```suggestion
                String[] buildkitCommand = baseCommand + opts + commandTail

                logger.info("${buildkitCommand.join('\n')}")

                PublishImage(buildkitCommand)
```

2022-10-24 16:01 UTC, ronanbrowne commented on buildSrc/src/main/groovy/BuildkitBuild.groovy
> +                PublishImage(buildkitCommand)
use logger + can drop finalCommand var

2022-10-24 16:26 UTC, ronanbrowne commented
Also i'm a bit confused as you have 2 branches now , this and the feature/jansz/buildkit-nightly - So im only reviewing what is in this PR - suggest maintaining just 1 branch for simplicity

2022-10-27 14:07 UTC, benmcmahon100 commented on buildSrc/src/main/groovy/BuildkitBuild.groovy
> +            getObjects().property(String).convention('')
Can we get comments on all of these so it's visible at a glance what they're for?

2022-10-27 14:07 UTC, benmcmahon100 commented on buildSrc/src/main/groovy/BuildkitBuild.groovy
> +        }
These are identical and as such can be one loop. IIRC groovy supports `+` lists together.
```groovy
(sourceFiles + extraSourceFiles).forEach { 
  // Do something
}
```

2022-10-27 14:07 UTC, benmcmahon100 commented on buildSrc/src/main/groovy/BuildkitBuild.groovy
> +        }
Also q WRT the implementation of the short name stuff. You make it optional, but I presume you're doing this so that the entrypoint can be `java -jar corda-thing.jar`, but at that stage it isn't optional.

IMO you could potentially drop this entirely and just use the full name of the jar in question. This would let you do all of them in one loop.

2022-12-02 10:55 UTC, benmcmahon100 commented on docker/Dockerfile
> +ENTRYPOINT ["bin/sh","-c","${IMAGE_ENTRYPOINT_ENV} $@","$@"]
```suggestion
ENTRYPOINT ["/bin/sh","-c","${IMAGE_ENTRYPOINT_ENV} $@","$@"]
```

2022-12-02 11:57 UTC, ronanbrowne requested changes
few comments

2022-12-02 11:57 UTC, ronanbrowne commented on buildSrc/src/main/groovy/BuildkitBuild.groovy
> +        try {
if using isBuildx this bit is irrelevant

2022-12-02 11:57 UTC, ronanbrowne commented on buildSrc/src/main/groovy/BuildkitBuild.groovy
> +        List<String> javaArgs = new ArrayList<String>(arguments.get())
potentially could be args in the docker file rather than here to reduce complexity here, ( can be handled in separate ticket)

2022-12-02 11:57 UTC, ronanbrowne commented on buildSrc/src/main/groovy/BuildkitBuild.groovy
> +    final Property<Boolean> isBuildx =
isBuildx should be true by default

2022-12-02 11:57 UTC, ronanbrowne commented on buildSrc/src/main/groovy/BuildkitBuild.groovy
> +    final Property<Boolean> isBuildx =
and false on CI

2022-12-02 11:57 UTC, ronanbrowne commented on docker/Dockerfile
> +ENV JAVA_HOME="/usr/lib/jvm/zulu11-ca-amd64"
why do you need to set `JAVA_HOME`  ? is this explicitly needed  ( it's also hard coded to amd version)

2022-12-02 12:33 UTC, E1P3 commented on buildSrc/src/main/groovy/BuildkitBuild.groovy
> +        try {
added the change that only runs this if isBuildx is false

2022-12-02 12:33 UTC, E1P3 commented on buildSrc/src/main/groovy/BuildkitBuild.groovy
> +    final Property<Boolean> isBuildx =
set it to true and updated the pipeline

2022-12-09 18:00 UTC, ronanbrowne requested changes

2022-12-09 18:00 UTC, ronanbrowne commented on Jenkinsfile
> +@Library('corda-shared-build-pipeline-steps@jansz/CORE-4935/buildkit-nightly-pipeline') _
I'd expect this to align with your open shared lib PR , but it does not you have a different branch open there for PR which makes it difficult to review these together .

2022-12-23 13:43 UTC, ronanbrowne requested changes

2022-12-23 13:43 UTC, ronanbrowne commented on buildSrc/src/main/groovy/BuildkitBuild.groovy
> +    // Handles to set the output image's name:tag
replace all occurrences of Handles with property in various comments here.

Also comments are inconstant some properties have them some do not?

2022-12-23 13:43 UTC, ronanbrowne commented on buildSrc/src/main/groovy/BuildkitBuild.groovy
> +        if(!isBuildx){
format file

2022-12-23 13:43 UTC, ronanbrowne commented on buildSrc/src/main/groovy/corda.docker-app.gradle
see https://github.com/corda/corda-cli-plugin-host/pull/126#discussion_r1056345579

2022-12-23 13:45 UTC, ronanbrowne commented
Also can you update the description off this PR in detail please.

2022-12-29 09:26 UTC, ronanbrowne commented
https://gradle.dev.r3.com/s/uryqwb632vzy4 it seems i can not build this locally

2024-03-27 00:01 UTC, closed without merging