Core 6690/consistent overrides
corda/corda-runtime-os pull request #2364
Opened 2022-10-20 13:32 UTC by JasonSinclair95

This ticket is incomplete however I recommend we merge what has been done as a-lot has changed. This PR is to make changes so that the Corda workers can query an existing secret for both the db password and username
 
To test the changes the following should be put in your overrides 
```yaml
db:
  cluster:
    host: prereqs-postgresql 
    password:
      valueFrom:
        secretkeyRef:
          name: test-secret
          passwordKey: password 

    user:
      valueFrom: 
        secretkeyRef:
          name: test-secret2
          usernameKey: namename
```
For this deployment i created a secret for the username and one for the password. It was also tested using the same secret and no secret at all.

2022-10-20 13:40 UTC, oscardalmau-r3 submitted a review, later dismissed
LGTM

2022-10-20 14:21 UTC, davidcurrie requested changes

2022-10-20 14:21 UTC, davidcurrie commented on charts/corda/values.yaml
> +          usernameKey: ""
```suggestion
    user:
      # -- the cluster database user
      value: user
      # the cluster database user secret configuration; used in preference to value if name is set
      valueFrom: 
        # the cluster database user secret key reference
        secretKeyRef:
          # -- the cluster database user secret name 
          name: ""
          # -- the cluster database user secret key 
          key: ""
```

2022-10-20 14:21 UTC, davidcurrie commented on charts/corda/values.yaml
>      # -- the cluster database password (ignored if existingSecret is set, otherwise required)
```suggestion
    # the cluster database password configuration
```

2022-10-20 14:21 UTC, davidcurrie commented on charts/corda/values.yaml
>      # -- the cluster database user
```suggestion
    # the cluster database user configuration
```

2022-10-20 14:21 UTC, davidcurrie commented on charts/corda/values.yaml
> +          passwordKey: ""
```suggestion
    password: 
      # -- the cluster database password
      value: "" 
      # the cluster database password secret configuration; used in preference to value if name is set
      valueFrom:
        # the cluster database password secret key reference
        secretKeyRef:
          # -- the cluster database password secret name
          name: ""
          # -- the cluster database password secret key
          key: ""
```

2022-10-20 14:21 UTC, davidcurrie commented on charts/corda/values.schema.json
> +                            "type": "object",
schema will need updating to reflect changes proposed in values

2022-10-20 14:21 UTC, davidcurrie commented on charts/corda/templates/cluster-db-secret.yaml
>  kind: Secret
We should also put the user in this secret (which means the secret needs to be created if either the user or password is not specified via a user-provided secret.

2022-10-20 14:21 UTC, davidcurrie commented on charts/corda/templates/_helpers.tpl
>  {{- define "corda.clusterDbSecretName" -}}
```suggestion
{{- define "corda.clusterDbPasswordEnv" -}}
```

2022-10-20 14:21 UTC, davidcurrie commented on charts/corda/templates/_helpers.tpl
>  {{- define "corda.clusterDbUser" -}}
```suggestion
{{- define "corda.clusterDbUseEnvr" -}}
```

2022-10-20 14:21 UTC, davidcurrie commented on charts/corda/templates/_helpers.tpl
> +{{- end }}
Will need to retrieve from secret if not set (as for password)

2022-10-20 14:21 UTC, davidcurrie commented on charts/corda/templates/_helpers.tpl
> +Cluster DB password secret
```suggestion
Cluster DB password environment variable 
```

2022-10-20 14:21 UTC, davidcurrie commented on charts/corda/templates/_helpers.tpl
> +Cluster DB user secret
```suggestion
Cluster DB user environment variable 
```

2022-10-20 14:21 UTC, davidcurrie commented on charts/corda/templates/cluster-db-secret.yaml
> +  password: {{ required "Must specify db.cluster.password.valueFrom.secretRef.name or db.cluster.password.value" .Values.db.cluster.password.value | b64enc | quote }}
the `password` key here needs to use the `key` name specified in the values (or default to `password`)

2022-10-20 15:14 UTC, JasonSinclair95 commented on charts/corda/templates/cluster-db-secret.yaml
> +  password: {{ required "Must specify db.cluster.password.valueFrom.secretRef.name or db.cluster.password.value" .Values.db.cluster.password.value | b64enc | quote }}
The default of this value .Values.db.cluster.password.value  is password @davidcurrie

2022-10-20 15:17 UTC, davidcurrie commented on charts/corda/templates/cluster-db-secret.yaml
> +  password: {{ required "Must specify db.cluster.password.valueFrom.secretRef.name or db.cluster.password.value" .Values.db.cluster.password.value | b64enc | quote }}
I'm talking about the key here though i.e. the bit before the colon at the start of the line. You're always calling it `password` here but when you retrieve it, you use the value from `secretRef.key`.

2022-10-20 15:18 UTC, JasonSinclair95 commented on charts/corda/templates/_helpers.tpl
> +{{- end }}
That's what the function is. it looks for the value for the secret if set and if not it gets the default value which is user. Or is this not what you're suggesting @davidcurrie

2022-10-20 15:22 UTC, JasonSinclair95 commented on charts/corda/templates/cluster-db-secret.yaml
>  kind: Secret
Okay

2022-10-20 15:38 UTC, davidcurrie commented on charts/corda/templates/_helpers.tpl
> +{{- end }}
Hopefully it made sense by the time you got to the comment about adding the user to the secret.

2022-10-25 11:03 UTC, JasonSinclair95 commented on charts/corda/templates/cluster-db-secret.yaml
> +  password: {{ required "Must specify db.cluster.password.valueFrom.secretRef.name or db.cluster.password.value" .Values.db.cluster.password.value | b64enc | quote }}
Could we have a conversation regarding this if statement please

2022-10-25 11:11 UTC, JasonSinclair95 commented on charts/corda/templates/cluster-db-secret.yaml
> +  password: {{ required "Must specify db.cluster.password.valueFrom.secretRef.name or db.cluster.password.value" .Values.db.cluster.password.value | b64enc | quote }}
The key for the password should always be secret here, as this secret only gets created if SecretRef.name is not set. I don't see how any of the values are retrieved from SecretRef for this secret. @davidcurrie

2022-11-11 19:26 UTC, yarivus requested changes

2022-11-11 19:26 UTC, yarivus commented on charts/corda/templates/_helpers.tpl
> +<<<<<<< HEAD
bad merge

2022-11-11 21:01 UTC, yarivus submitted a review, later dismissed
LGTM

2022-11-14 12:14 UTC, oscardalmau-r3 approved these changes
LGTM

2022-11-14 12:35 UTC, davidcurrie approved these changes

2022-11-14 12:44 UTC, ronanbrowne approved these changes
LGTM

2022-11-14 13:09 UTC, merged