CORE-4733 Create the non-validating notary plugin (migration)
corda/corda-runtime-os pull request #2373
Opened 2022-10-24 15:55 UTC by nkovacsx

## Overview

This PR will create a brand new top-level module for the notary plugins. It will contain a common sub-module for shared logic between plugins (e.g. validating - future work) and one sub-module for the non-validating plugin itself.

The plugin's API/Client/Server modules will be packaged as separate CPKs, that's why they have a standalone `cordapp` blocks in their build.gradle.

## TODOs

The code has some TODOs that have no ticket number. That is because they are either small investigation tasks that I intend to do ASAP and raising a ticket would be overkill for them or they are not blockers, mostly questions that need answering.

The following tickets has been raised for follow-up:
https://r3-cev.atlassian.net/browse/CORE-7248
https://r3-cev.atlassian.net/browse/CORE-7249
https://r3-cev.atlassian.net/browse/CORE-7251

## Testing

Unfortunately, smoke testing is not yet possible, because the `NonValidatingNotaryClientFlowImpl` requires a `UtxoSignedTransaction` in its constructor, and there's no way to generate a signed transaction for now (i.e. there's no builder for it). Once the builder gets merged, the smoke test can be created (https://github.com/corda/corda-runtime-os/pull/2368).

2022-10-26 11:11 UTC, relyafi requested changes
I think there's some scope to simplify these changes, as some of the logic seems unnecessarily complicated to me

2022-10-26 11:11 UTC, relyafi commented on notary-plugins/notary-plugin-common/src/main/kotlin/com/r3/corda/notary/plugin/common/BaseNotarisationPayloadImpl.kt
> +            "(validating/non-validating) and the one advertised on the network parameters."
```suggestion
    protected fun unexpectedTransactionType() = IllegalArgumentException("Unexpected transaction type ${transaction::class.java} in " +
            "notarisation payload. There may be a mismatch between the configured notary type and the one advertised on the " +
            "network parameters."
```

Slightly more succinct, consistent line lengths, remove assumption that we will be dealing with validating / non-validating

2022-10-26 11:11 UTC, relyafi commented on notary-plugins/notary-plugin-common/src/main/kotlin/com/r3/corda/notary/plugin/common/BaseNotarisationPayloadImpl.kt
> + * It runs a validation that checks if the given [transaction]'s type is actually one of [validTypes].
```suggestion
 * It runs validation that checks if the given [transaction]'s type is actually one of [validTypes].
```

2022-10-26 11:11 UTC, relyafi commented on notary-plugins/notary-plugin-common/src/main/kotlin/com/r3/corda/notary/plugin/common/TransactionParts.kt
> +    val references: List<StateRef> = emptyList()
Is there a reason we've given this a default value, but not other arguments? We could equally argue `inputs` and `numOutputs` could have sensible defaults.

Personally I'd rather not use the default arguments unless there's a strong argument for it, which also means we can logically group the inputs and references next to each other in the class.

2022-10-26 11:11 UTC, relyafi commented on notary-plugins/notary-plugin-common/src/main/kotlin/com/r3/corda/notary/plugin/common/TransactionParts.kt
> + * any sensitive transaction details.
Is this really true? Wouldn't this be notary plugin specific?

Do we mean it's the information needed in order to perform uniqueness checking for a transaction? And if so, should this be part of `uniqueness` instead of the notary plugins? This information is effectively already specified in `LedgerUniquenessCheckerClientServiceImpl.requestUniquenessCheck`, so if we want a data class it might make sense to update that call to use this object, given it's a ledger specific interface?

2022-10-26 11:11 UTC, relyafi commented on notary-plugins/notary-plugin-common/src/main/kotlin/com/r3/corda/notary/plugin/common/BaseNotarisationPayloadImpl.kt
> +    protected fun unexpectedTransactionType() = IllegalArgumentException("Unexpected transaction type in the notarisation payload: " +
I can't see where this is used? As it stands wouldn't we want this message text to be passed into the `lazyMessage` of the  `require` we do in this class?

2022-10-26 11:11 UTC, relyafi commented on notary-plugins/notary-plugin-common/src/main/kotlin/com/r3/corda/notary/plugin/common/BaseNotarisationPayloadImpl.kt
> +        require(validTypes.any { it.isAssignableFrom(transaction::class.java) })
Is this ok that we potentially throw an exception on construction (IIRC this is no longer a security issue post JDK8?)

2022-10-26 11:11 UTC, relyafi commented on notary-plugins/notary-plugin-common/src/main/kotlin/com/r3/corda/notary/plugin/common/BaseNotarisationPayloadImpl.kt
> +    final override val validTypes: List<Class<*>>
Do we have a reason to lock these down here? Any inheriting class would need to use these, or use their own classes that derive from these anyway?

2022-10-26 11:11 UTC, relyafi commented on notary-plugins/notary-plugin-common/src/main/kotlin/com/r3/corda/notary/plugin/common/NotarisationRequestImpl.kt
> +data class NotarisationRequestImpl(
This class doesn't feel right to me. It's claiming to be a data class, but then has two functions that have nothing to do with the data class elements.

I'd suggest keep it simple - if you need the data class, have that, and define the functions elsewhere as standalone or private class functions.

2022-10-26 11:11 UTC, relyafi commented on notary-plugins/notary-plugin-common/src/main/kotlin/com/r3/corda/notary/plugin/common/NotaryException.kt
> +    val error: UniquenessCheckError,
This feels  like either the class name / description, or this argument is wrong. Uniqueness check errors are surely only a subset of reasons that the notary may reject a transaction. What happens if the responder flow fails validation before doing uniqueness checks?

2022-10-26 11:11 UTC, relyafi commented on notary-plugins/notary-plugin-common/src/main/kotlin/com/r3/corda/notary/plugin/common/NotaryException.kt
> + * Exception thrown by the notary service if any issues are encountered while trying to commit a transaction. The
What do we mean by "notary service"?

2022-10-26 11:11 UTC, relyafi commented on notary-plugins/notary-plugin-common/src/main/kotlin/com/r3/corda/notary/plugin/common/PluggableNotaryServerFlowHelpers.kt
> +}
I don't understand what value this function is adding - why wouldn't the caller just call `request.verifySignature` directly?

2022-10-26 11:11 UTC, relyafi commented on notary-plugins/notary-plugin-common/src/main/kotlin/com/r3/corda/notary/plugin/common/PluggableNotaryServerFlowHelpers.kt
> +fun PublicKey.toBase58String(): String = this.encoded.toBase58()
This looks more like a crypto helper function than a notary helper?

2022-10-26 11:11 UTC, relyafi commented on notary-plugins/notary-plugin-common/src/main/kotlin/com/r3/corda/notary/plugin/common/PluggableNotaryServerFlowHelpers.kt
> +                                      uniquenessCheckResponse: UniquenessCheckResponse) {
This function is a bit problematic to me for a few reasons:

- The name doesn't match the description / implementation. Fundamentally this is sending a notarisation response back.
- Taking a logger into a standalone function seems a bit of a code smell to me. It's also not the most important argument (which I'd infer from it being the first parameter)
- The logging levels seem inappropriate - success and failure events are both part of normal operation, and will generate a lot of noise. I'd recommend both be moved to the debug level.

What it looks like to me is we really want a standalone (or extension) function that acts as a converter from a UniquenessCheckResponse to a NotarisationResponse. It feels like the actual sending should be part of the calling flow, as that's a fundamental part of ending the flow that would be hidden as it stands.

As for the logging, we could probably do this as a single line within the calling flow, and use the same message for both success and failure, since both would be on the same log level and the response contents let you infer a success or failure.

This approach also means that we are able to cope with the case where we want to send a notarisation response (most likely failure) based on things other than the uniqueness checker result.

2022-10-26 11:11 UTC, relyafi commented on notary-plugins/notary-plugin-non-validating/notary-plugin-non-validating-api/build.gradle
> +    cordaProvided 'net.corda:corda-notary-plugin'
NIT: Appears out of order with respect to the other dependencies

2022-10-26 11:11 UTC, relyafi commented on notary-plugins/notary-plugin-non-validating/notary-plugin-non-validating-client/build.gradle
> +    cordaProvided 'net.corda:corda-notary-plugin'
NIT: Appears out of order with respect to the other dependencies

2022-10-26 11:11 UTC, relyafi commented on notary-plugins/notary-plugin-non-validating/notary-plugin-non-validating-api/build.gradle
> +    cordaProvided project(":notary-plugins:notary-plugin-common")
Is using this correct vs. `implementation`? I must admit I'm struggling to find docs / messages on when to use this, beyond using it for things in corda-api.

I'm assuming that there is no "common" CPK, so what we would want to do is pull the source files we want into the  bundle for the API CPK? That also protects against API / client / server moving on independently since they may use different versions of the "common" libraries.

2022-10-26 11:11 UTC, relyafi commented on notary-plugins/notary-plugin-non-validating/notary-plugin-non-validating-client/build.gradle
> +    cordaProvided project(":notary-plugins:notary-plugin-non-validating:notary-plugin-non-validating-api")
As before, not sure if this is correct or not? In this case, there's also questions around how we pull in API as well as common.

2022-10-26 11:11 UTC, relyafi commented on notary-plugins/notary-plugin-non-validating/notary-plugin-non-validating-server/build.gradle
> +    cordaProvided project(":notary-plugins:notary-plugin-non-validating:notary-plugin-non-validating-client")
As before, not sure if this is correct or not? In this case, there's also questions around how we pull in API as well as common.

Also, what is the dependency on `client`? Doesn't having this dependency defeat the object of having a separate API module?

2022-10-26 11:11 UTC, relyafi commented on notary-plugins/notary-plugin-non-validating/notary-plugin-non-validating-client/src/main/kotlin/com/r3/corda/notary/plugin/nonvalidating/NonValidatingNotaryClientFlowImpl.kt
> +        val logger = LoggerFactory.getLogger(this::class.java)
Would it be a bit cleaner to use `contextLogger()`?

2022-10-26 11:11 UTC, relyafi commented on notary-plugins/notary-plugin-non-validating/notary-plugin-non-validating-client/src/main/kotlin/com/r3/corda/notary/plugin/nonvalidating/NonValidatingNotaryClientFlowImpl.kt
> +        val requestSignature = generateRequestSignature()
Can be inlined into the call to `generatePayload`. Or consider combining the functions given they're both pretty trivial.

2022-10-26 11:11 UTC, relyafi commented on notary-plugins/notary-plugin-non-validating/notary-plugin-non-validating-client/src/main/kotlin/com/r3/corda/notary/plugin/nonvalidating/NonValidatingNotaryClientFlowImpl.kt
> +        return notarisationRequest.generateSignature(memberLookupService.myInfo(), signingService, serializationService)
I think this backs up my earlier comment about having this function in `NotarisationRequestImpl` being incorrect - we're constructing an object, only to call a function on it that doesn't make use of the data instantiated at construction time.

2022-10-26 11:11 UTC, relyafi commented on notary-plugins/notary-plugin-non-validating/notary-plugin-non-validating-server/src/main/kotlin/com/r3/corda/notary/plugin/nonvalidating/NonValidatingNotaryServerFlowImpl.kt
> +@InitiatedBy(protocol = "non-validating-notary")
Out of curiosity - is there any convention on how we should name protocols? I'm assuming these should be globally unique? That being the case, should we be using fully qualified package names (i.e. whatever we use as the protocol name in the MGM member info) to minimise the chance of inadvertent collisions in future?

2022-10-26 11:11 UTC, relyafi commented on notary-plugins/notary-plugin-non-validating/notary-plugin-non-validating-server/src/main/kotlin/com/r3/corda/notary/plugin/nonvalidating/NonValidatingNotaryServerFlowImpl.kt
> +        val logger: Logger = LoggerFactory.getLogger(this::class.java)
Would it be a bit cleaner to use `contextLogger()`?

2022-10-26 11:11 UTC, relyafi commented on notary-plugins/notary-plugin-non-validating/notary-plugin-non-validating-server/src/main/kotlin/com/r3/corda/notary/plugin/nonvalidating/NonValidatingNotaryServerFlowImpl.kt
> +     * 5. Send the [net.corda.v5.application.uniqueness.model.UniquenessCheckResponse] back to the client
This needs more thought - consider the case of what happens when `verifyTransaction` does something and we need to communicate an error from that back to the client.

2022-10-26 11:11 UTC, relyafi commented on notary-plugins/notary-plugin-non-validating/notary-plugin-non-validating-server/src/main/kotlin/com/r3/corda/notary/plugin/nonvalidating/NonValidatingNotaryServerFlowImpl.kt
> +     * 4. Commit to the database using the [LedgerUniquenessCheckerClientService]
```suggestion
     * 4. Request uniqueness checking using the [LedgerUniquenessCheckerClientService]
```
Committing to the database is an implementation detail of what should be a black box

2022-10-26 11:11 UTC, relyafi commented on notary-plugins/notary-plugin-non-validating/notary-plugin-non-validating-server/src/main/kotlin/com/r3/corda/notary/plugin/nonvalidating/NonValidatingNotaryServerFlowImpl.kt
> +    }
Not sure this function is adding any value?

2022-10-26 11:11 UTC, relyafi commented on notary-plugins/notary-plugin-non-validating/notary-plugin-non-validating-server/src/main/kotlin/com/r3/corda/notary/plugin/nonvalidating/NonValidatingNotaryServerFlowImpl.kt
> +        val request = NotarisationRequestImpl(tx.inputs, tx.id)
Having seen how 'NotarisationRequestImpl` is being used throughout this PR, I don't see what value it is adding. As far as I can see we're never using the data stored in it, we're just invoking functions that could be standalone.

2022-10-26 11:11 UTC, relyafi commented on notary-plugins/notary-plugin-non-validating/notary-plugin-non-validating-server/src/main/kotlin/com/r3/corda/notary/plugin/nonvalidating/NonValidatingNotaryServerFlowImpl.kt
> +        logger.debug { "Tx [$transactionId] contains ${transaction.numOutputs} output states" }
Not sure if this is useful info in isolation? Might be a hangover from our hack to communicate this separately from the tx object.

2022-10-26 11:11 UTC, relyafi commented on notary-plugins/notary-plugin-non-validating/notary-plugin-non-validating-server/src/main/kotlin/com/r3/corda/notary/plugin/nonvalidating/NonValidatingNotaryServerFlowImpl.kt
> +        logger.info("Received a notarisation request for Tx [$transactionId] from [${otherSideSession.counterparty}]")
Should probably be on debug level

2022-10-26 14:58 UTC, nkovacsx commented on notary-plugins/notary-plugin-non-validating/notary-plugin-non-validating-server/src/main/kotlin/com/r3/corda/notary/plugin/nonvalidating/NonValidatingNotaryServerFlowImpl.kt
> +        logger.debug { "Tx [$transactionId] contains ${transaction.numOutputs} output states" }
Good point.

2022-10-26 15:04 UTC, nkovacsx commented on notary-plugins/notary-plugin-common/src/main/kotlin/com/r3/corda/notary/plugin/common/TransactionParts.kt
> +    val references: List<StateRef> = emptyList()
Good point

2022-10-26 15:06 UTC, nkovacsx commented on notary-plugins/notary-plugin-common/src/main/kotlin/com/r3/corda/notary/plugin/common/BaseNotarisationPayloadImpl.kt
> +    protected fun unexpectedTransactionType() = IllegalArgumentException("Unexpected transaction type in the notarisation payload: " +
Good point

2022-10-26 15:07 UTC, nkovacsx commented on notary-plugins/notary-plugin-common/src/main/kotlin/com/r3/corda/notary/plugin/common/BaseNotarisationPayloadImpl.kt
> +        require(validTypes.any { it.isAssignableFrom(transaction::class.java) })
I think we had a discussion about this last time, AFAIK there's no security issue with this in Java 11.

2022-10-26 15:09 UTC, nkovacsx commented on notary-plugins/notary-plugin-common/src/main/kotlin/com/r3/corda/notary/plugin/common/BaseNotarisationPayloadImpl.kt
> +    final override val validTypes: List<Class<*>>
Since we are doing a constructor validation in an abstract class, these should be final. If they are not, it can cause some issues. https://discuss.kotlinlang.org/t/why-does-this-fix-the-accessing-non-final-property-in-constructor-warning/9782

2022-10-26 15:10 UTC, nkovacsx commented on notary-plugins/notary-plugin-common/src/main/kotlin/com/r3/corda/notary/plugin/common/NotarisationRequestImpl.kt
> +data class NotarisationRequestImpl(
Do you suggest `generateSignature` and `verifySignature` should be part of our function library rather than the class?

2022-10-26 15:13 UTC, relyafi commented on notary-plugins/notary-plugin-common/src/main/kotlin/com/r3/corda/notary/plugin/common/NotarisationRequestImpl.kt
> +data class NotarisationRequestImpl(
Yes, that sounds reasonable to me.

2022-10-26 15:21 UTC, nkovacsx commented on notary-plugins/notary-plugin-non-validating/notary-plugin-non-validating-client/src/main/kotlin/com/r3/corda/notary/plugin/nonvalidating/NonValidatingNotaryClientFlowImpl.kt
> +        return notarisationRequest.generateSignature(memberLookupService.myInfo(), signingService, serializationService)
I understand your argument about the function not placed properly. However, having a `NotarisationRequest` seems reasonable to me as we are serialising it when generating the signature:

`serializationService.serialize(request).bytes`

Do you suggest that we should serialise the transaction id concatenated with the list of staterefs instead of an actual object? That seems super dirty to me. 

My proposal is, move the functions to the library, but keep the data class.

2022-10-26 15:49 UTC, relyafi commented on notary-plugins/notary-plugin-non-validating/notary-plugin-non-validating-client/src/main/kotlin/com/r3/corda/notary/plugin/nonvalidating/NonValidatingNotaryClientFlowImpl.kt
> +        return notarisationRequest.generateSignature(memberLookupService.myInfo(), signingService, serializationService)
Ah, sorry - I missed that request was being used for serialization. Yes, think your proposal makes sense in that case.

2022-10-27 07:19 UTC, nkovacsx commented on notary-plugins/notary-plugin-non-validating/notary-plugin-non-validating-client/src/main/kotlin/com/r3/corda/notary/plugin/nonvalidating/NonValidatingNotaryClientFlowImpl.kt
> +        val requestSignature = generateRequestSignature()
Please note that this PR is an interim step so `generatePayload` might become more complex when the `FilteredTransaction` be added but will merge these two functions for now.

2022-10-27 07:21 UTC, nkovacsx commented on notary-plugins/notary-plugin-common/src/main/kotlin/com/r3/corda/notary/plugin/common/PluggableNotaryServerFlowHelpers.kt
> +fun PublicKey.toBase58String(): String = this.encoded.toBase58()
I agree, need to chase someone from the crypto team about this, adding a TODO for now.

2022-10-27 07:27 UTC, nkovacsx commented on notary-plugins/notary-plugin-non-validating/notary-plugin-non-validating-api/build.gradle
> +    cordaProvided project(":notary-plugins:notary-plugin-common")
Yes, we don't build a CPK from the common module that's why I'm using `cordaProvided`. Implementation cannot really be used in CorDapps for Corda dependencies AFAIK.

Frankly though, I'm not an expert in this subject either, hopefully there'll be an extensive documentation about this later on.

2022-10-27 07:28 UTC, nkovacsx commented on notary-plugins/notary-plugin-non-validating/notary-plugin-non-validating-client/build.gradle
> +    cordaProvided project(":notary-plugins:notary-plugin-non-validating:notary-plugin-non-validating-api")
Actually you are right, this should be `cordapp project` as we are pulling in CPK bundles. This would have come out as an error during the smoke test.

2022-10-27 07:29 UTC, nkovacsx commented on notary-plugins/notary-plugin-non-validating/notary-plugin-non-validating-server/src/main/kotlin/com/r3/corda/notary/plugin/nonvalidating/NonValidatingNotaryServerFlowImpl.kt
> +        val request = NotarisationRequestImpl(tx.inputs, tx.id)
As discussed we are using it for serialisation so we can't really avoid having it unless we want a nasty code.

2022-10-27 07:35 UTC, nkovacsx commented on notary-plugins/notary-plugin-common/src/main/kotlin/com/r3/corda/notary/plugin/common/TransactionParts.kt
> + * any sensitive transaction details.
I think what you say is correct because this is the information needed to perform a uniqueness check. However, I'm a bit against having to pass in a data class to a flow service API call directly. 

That means the flow needs construct a data class beforehand and pass that to the flow service call. In my opinion having the current signature in `LedgerUniquenessCheckerClientService` is cleaner. 

In this context `TransactionParts` only acts as a container for transaction related data so we don't have to extract it from the STX everytime. The KDocs is inherited from DP1, so I'll modify that but keep the data class as it is if that's okay with you.

2022-10-27 08:06 UTC, relyafi commented on notary-plugins/notary-plugin-common/src/main/kotlin/com/r3/corda/notary/plugin/common/TransactionParts.kt
> + * any sensitive transaction details.
Ok, I can see that rationale - it would certainly be useful if we were passing `TransactionParts` around in function calls (to avoid upsetting detekt with long parameter lists) and reusing the values, as the extraction logic is indeed non-trivial. None of that seems to be the case right now though - as far as I can see we use the input states and tx ids in two places, and everything else in only one place, when requesting the uniqueness check, where we have to do processing anyway?

I can see how it could become more useful though as the code complexity increases, so will leave it at your discretion as to whether to keep it. If keeping it, I would consider a couple of other things though:

- Whether `common` is the right place for it, because if it is a notary (as opposed to uniqueness) data structure, it is not generic - e.g. the contract validating notary would want the _actual_ output states, not the number of output states.
- Whether we need a more specific name than `TransactionParts` - it is part of the notary package but might aid readability if the name more closely reflected how / what it's being used for.

2022-10-27 13:35 UTC, nkovacsx commented on notary-plugins/notary-plugin-common/src/main/kotlin/com/r3/corda/notary/plugin/common/PluggableNotaryServerFlowHelpers.kt
> +                                      uniquenessCheckResponse: UniquenessCheckResponse) {
I agree, I refined this logic now.

2022-10-27 13:35 UTC, nkovacsx commented on notary-plugins/notary-plugin-common/src/main/kotlin/com/r3/corda/notary/plugin/common/NotaryException.kt
> +    val error: UniquenessCheckError,
Discussed this offline, will add a new type called `NotaryError`.

2022-10-27 14:16 UTC, nkovacsx commented on notary-plugins/notary-plugin-non-validating/notary-plugin-non-validating-server/src/main/kotlin/com/r3/corda/notary/plugin/nonvalidating/NonValidatingNotaryServerFlowImpl.kt
> +@InitiatedBy(protocol = "non-validating-notary")
Yes, that's a good point. I'm just wondering how we should tackle this, because we can only use constant strings in annotations. I'm wondering if having a `const` string in the API for the protocol name could work?

2022-10-27 14:22 UTC, relyafi commented on notary-plugins/notary-plugin-non-validating/notary-plugin-non-validating-server/src/main/kotlin/com/r3/corda/notary/plugin/nonvalidating/NonValidatingNotaryServerFlowImpl.kt
> +@InitiatedBy(protocol = "non-validating-notary")
I'm happy either way really, not too fussed how we get there as long as we've thought about it. Might be worth consulting more broadly within engineering as to whether there is a general pattern we should be using for these, since this is something that will be present on every flow.

I also think though this is something we could potentially leave for now and raise as a tech debt ticket.

2022-10-27 14:55 UTC, nkovacsx commented on notary-plugins/notary-plugin-non-validating/notary-plugin-non-validating-server/src/main/kotlin/com/r3/corda/notary/plugin/nonvalidating/NonValidatingNotaryServerFlowImpl.kt
> +@InitiatedBy(protocol = "non-validating-notary")
Okay, that sounds like a plan to me.

2022-10-31 10:57 UTC, relyafi commented on notary-plugins/notary-plugin-non-validating/notary-plugin-non-validating-server/build.gradle
> +    cordaProvided project(":notary-plugins:notary-plugin-non-validating:notary-plugin-non-validating-client")
@nkovacsx reopening as client dependency still appears to be there

2022-11-01 16:36 UTC, relyafi reviewed
A few minor comments. Otherwise as an interim step, this is looking good.

2022-11-01 16:36 UTC, relyafi commented on notary-plugins/notary-plugin-non-validating/notary-plugin-non-validating-api/build.gradle
> +
NIT: Unnecessary whitespace

2022-11-01 16:36 UTC, relyafi commented on notary-plugins/notary-plugin-common/src/main/kotlin/com/r3/corda/notary/plugin/common/CommonNotaryErrors.kt
> +// TODO CORE-7249 Extend with more errors once FilteredTransaction support has been added
But I suspect not in this file (so TODO is misplaced), because any validation based on `FilteredTransaction` would imply non-validating notary specific validation?

2022-11-01 16:36 UTC, relyafi commented on notary-plugins/notary-plugin-common/src/main/kotlin/com/r3/corda/notary/plugin/common/CommonNotaryErrorsImpl.kt
> +// TODO CORE-7249 Extend with more errors once FilteredTransaction support has been added
But I suspect not in this file (so TODO is misplaced), because any validation based on FilteredTransaction would imply non-validating notary specific validation?

2022-11-01 16:36 UTC, relyafi commented on notary-plugins/notary-plugin-common/src/main/kotlin/com/r3/corda/notary/plugin/common/PluggableNotaryFlowHelpers.kt
> +    return NotarisationResponse(signature, notaryError)
```suggestion
    return when (val uniquenessResult = result) {
        is UniquenessCheckResultSuccess -> NotarisationResponseImpl(
            listOf(signature!!),
            null
        )
        is UniquenessCheckResultFailure -> NotarisationResponseImpl(
            emptyList(),
            uniquenessResult.error.toNotaryError()
        )
        else -> NotarisationResponseImpl(
            emptyList(),
            NotaryErrorGeneralImpl(
                "Unknown uniqueness check result: $uniquenessResult"
            )
        )
    }
```

Bit more succinct, and follows the pattern of the similar `toNotaryError` function below

2022-11-01 16:36 UTC, relyafi commented on notary-plugins/notary-plugin-non-validating/notary-plugin-non-validating-server/build.gradle
> +    cordaProvided 'net.corda:corda-notary-plugin'
NIT: Out of order with respect to other includes

2022-11-02 08:19 UTC, nkovacsx commented on notary-plugins/notary-plugin-common/src/main/kotlin/com/r3/corda/notary/plugin/common/CommonNotaryErrors.kt
> +// TODO CORE-7249 Extend with more errors once FilteredTransaction support has been added
Yeah, good point!

2022-11-02 10:35 UTC, relyafi approved these changes, later dismissed
LGTM

2022-11-02 11:57 UTC, relyafi approved these changes

2022-11-02 11:58 UTC, ronanbrowne approved these changes
LGTN (build)

2022-11-02 12:00 UTC, merged