CORE-7291 Tx Factories
corda/corda-runtime-os pull request #2396
Opened 2022-10-27 15:27 UTC by vlajos

2022-11-01 13:37 UTC, lankydan commented on libs/ledger/ledger-common-data/src/main/kotlin/net/corda/ledger/common/data/transaction/TransactionBuilderInternal.kt
> +interface TransactionBuilderInternal {
Can we just make this `TransactionBuilder` since we don't have a public interface for it.

2022-11-01 13:41 UTC, lankydan commented on libs/ledger/ledger-common-data/src/main/kotlin/net/corda/ledger/common/data/transaction/factory/WireTransactionFactoryImpl.kt
> +        val componentGroupLists = transactionBuilderInternal.calculateComponentGroups(
Since we have a `ConsensualSignedTransactionFactory` and will therefore have a `UtxoSignedTransactionFactory`, is there any reason that `calculateComponentGroups` can't be moved into each factory rather than introducing `TransactionBuilderInternal` which implements calculateComponentGroups`?

2022-11-01 13:43 UTC, lankydan commented on libs/ledger/ledger-common-data/src/main/kotlin/net/corda/ledger/common/data/transaction/factory/WireTransactionFactoryImpl.kt
> +    }
Can we try keep the public/overridden functions towards the top with the private ones further down.

2022-11-01 13:44 UTC, lankydan commented on components/ledger/ledger-common-flow/src/main/kotlin/net/corda/ledger/common/flow/impl/transaction/factory/TransactionMetadataFactoryImpl.kt
> +class TransactionMetadataFactoryImpl @Activate constructor(
Nice addition

2022-11-01 13:45 UTC, lankydan reviewed
Main comment is about the calculation of the component groups. Otherwise looks about right.

2022-11-01 17:02 UTC, vlajos commented on libs/ledger/ledger-common-data/src/main/kotlin/net/corda/ledger/common/data/transaction/TransactionBuilderInternal.kt
> +interface TransactionBuilderInternal {
I ended up removing this.
Only the Utxo one needed a similar one.

2022-11-01 17:03 UTC, vlajos commented on libs/ledger/ledger-common-data/src/main/kotlin/net/corda/ledger/common/data/transaction/factory/WireTransactionFactoryImpl.kt
> +        val componentGroupLists = transactionBuilderInternal.calculateComponentGroups(
I moved them there.

2022-11-01 17:03 UTC, vlajos commented on libs/ledger/ledger-common-data/src/main/kotlin/net/corda/ledger/common/data/transaction/factory/WireTransactionFactoryImpl.kt
> +    }
OK. I moved them.

2022-11-03 10:38 UTC, MrMatthewLayton reviewed
Just one comment to review, but other than that, LGTM!

2022-11-03 10:38 UTC, MrMatthewLayton commented on components/ledger/ledger-utxo-flow/src/main/kotlin/net/corda/ledger/utxo/flow/impl/transaction/UtxoTransactionBuilderInternal.kt
> +interface UtxoTransactionBuilderInternal {
What is the value of having this interface if it represents stuff that the user won't see?

2022-11-03 10:56 UTC, ronanbrowne requested changes

2022-11-03 10:56 UTC, ronanbrowne commented on libs/ledger/ledger-common-data/build.gradle
> +    testImplementation project(':testing:ledger:ledger-common-base-test')
can be be consistent with " or ' this and line above uses 2 different quote types - check other gradle files changed also 

 I would suggest using double quotes as we sometimes have to do groovy string interpolation for versions which is only supported with double.

2022-11-03 11:59 UTC, vlajos commented on components/ledger/ledger-utxo-flow/src/main/kotlin/net/corda/ledger/utxo/flow/impl/transaction/UtxoTransactionBuilderInternal.kt
> +interface UtxoTransactionBuilderInternal {
I pass the transaction builder to UtxoSignedTransactionFactory and we need to access the fields it populates which are no on the public API. So I needed an alternative interface which exposes the required fields.

2022-11-03 13:05 UTC, vlajos commented on libs/ledger/ledger-common-data/build.gradle
> +    testImplementation project(':testing:ledger:ledger-common-base-test')
Thanks for checking.
I have just changed them.

2022-11-04 16:10 UTC, chrisr3 commented on components/ledger/ledger-common-flow/build.gradle
> +    id "corda.common-library"
Where did all this noise come from? Single quotes are fine here. You only need double quotes if you intend to expand a property.

2022-11-04 16:19 UTC, vlajos commented on components/ledger/ledger-common-flow/build.gradle
> +    id "corda.common-library"
From here: https://github.com/corda/corda-runtime-os/pull/2396#discussion_r1012751478
But maybe I over did it a little bit..
Would you prefer to keep the `id`s single quoted everywhere?

2022-11-04 16:43 UTC, chrisr3 requested changes
The completely unnecessary replacement of single quotes with double quotes in the `build.gradle` files aside, you are using the platform's versions of services in places where you should be using the sandbox's versions. `ConsensualLedgerMessageProcessor` and `ConsensualLedgerRepository` are a case in point - I don't believe you need to change `ConsensualLedgerMessageProcessor` _at all_.

2022-11-04 16:43 UTC, chrisr3 commented on components/ledger/ledger-common-flow/src/main/java/net/corda/ledger/common/flow/impl/transaction/factory/package-info.java
> +package net.corda.ledger.common.flow.impl.transaction.factory;
A package name containing `.impl.` seems an unlikely candidate for exporting.

2022-11-04 16:43 UTC, chrisr3 commented on components/ledger/ledger-consensual-flow/build.gradle
> +    id "corda.common-library"
Again, you don't need to do this. There's nothing wrong with single quotes here since you have no properties to expand.

2022-11-04 16:43 UTC, chrisr3 commented on components/ledger/ledger-consensual-flow/src/main/java/net/corda/ledger/consensual/flow/impl/transaction/factory/package-info.java
> +package net.corda.ledger.consensual.flow.impl.transaction.factory;
Another curious export of an `.impl.` package...

2022-11-04 16:43 UTC, chrisr3 commented on components/ledger/ledger-consensual-flow/src/main/kotlin/net/corda/ledger/consensual/flow/impl/transaction/factory/ConsensualSignedTransactionFactory.kt
> +    @Suspendable
I'm not convinced that Quasar can see a `@Suspendable` annotation on an interface method. Have you tested whether this actually works?

2022-11-04 16:43 UTC, chrisr3 commented on components/ledger/ledger-consensual-flow/src/main/kotlin/net/corda/ledger/consensual/flow/impl/transaction/factory/ConsensualSignedTransactionFactoryImpl.kt
> +            .toByteArray(Charsets.UTF_8) // TODO(update with CORE-6890)
`UTF_8` is the default charset. You don't need to specify it.

2022-11-04 16:43 UTC, chrisr3 commented on components/ledger/ledger-consensual-persistence-impl/src/integrationTest/kotlin/net/corda/ledger/consensual/persistence/impl/processor/tests/ConsensualLedgerMessageProcessorTests.kt
> +    lateinit var wireTransactionFactory: WireTransactionFactory
No, you want the sandbox's instances of these services. The `@InjectService` annotation can only give you the platform's instances.

2022-11-04 16:43 UTC, chrisr3 commented on components/ledger/ledger-consensual-persistence-impl/src/integrationTest/kotlin/net/corda/ledger/consensual/persistence/impl/processor/tests/ConsensualLedgerMessageProcessorTests.kt
> +            wireTransactionFactory,
No, this cannot be correct.

2022-11-04 16:43 UTC, chrisr3 commented on components/ledger/ledger-consensual-persistence-impl/src/main/kotlin/net/corda/ledger/consensual/persistence/impl/processor/ConsensualLedgerMessageProcessor.kt
> +        )
No, the `ConsensualLedgerMessageProcessor` **must** obtain a `ConsensualLedgerRepository` instance created with all of the sandbox's services. This is the whole point of invoking `sandbox.getSandboxSingletonServices()`.

In fact, these lines almost certainly don't need changing at all. Just allow the sandbox code to create an instance of `ConsensulLedgerRepository`, and then use it.

2022-11-04 16:43 UTC, chrisr3 commented on components/ledger/ledger-consensual-persistence-impl/src/main/kotlin/net/corda/ledger/consensual/persistence/impl/processor/factory/ConsensualLedgerProcessorFactoryImpl.kt
> +    private val wireTransactionFactory: WireTransactionFactory
No, these don't belong here.

2022-11-04 16:43 UTC, chrisr3 commented on components/ledger/ledger-consensual-persistence-impl/src/main/kotlin/net/corda/ledger/consensual/persistence/impl/processor/factory/ConsensualLedgerProcessorFactoryImpl.kt
> +            wireTransactionFactory,
No, these are the platform's instances but you need the sandbox's.

2022-11-04 16:43 UTC, chrisr3 commented on components/ledger/ledger-utxo-flow/build.gradle
> +    compileOnly "org.osgi:org.osgi.service.component.annotations"
Is IntelliJ doing this? Please ask it to stop.

2022-11-04 16:43 UTC, chrisr3 commented on components/ledger/ledger-utxo-flow/src/main/kotlin/net/corda/ledger/utxo/flow/impl/transaction/factory/UtxoSignedTransactionFactory.kt
> +    @Suspendable
Again, not convinced Quasar supports putting `@Suspendable` annotations on interface methods.

2022-11-04 16:43 UTC, chrisr3 commented on libs/ledger/ledger-common-data/build.gradle
>  }
Bad IntelliJ again?

2022-11-04 16:43 UTC, chrisr3 commented on libs/ledger/ledger-consensual-data/build.gradle
Bad IntelliJ.

2022-11-04 16:43 UTC, chrisr3 commented on libs/ledger/ledger-utxo-data/build.gradle
> +    compileOnly "org.osgi:org.osgi.service.component.annotations"
Bad IntelliJ.

2022-11-04 16:43 UTC, chrisr3 commented on testing/ledger/ledger-common-testkit/build.gradle
> +    compileOnly "org.osgi:osgi.annotation"
Bad IntelliJ. Why does it hate single quotes so much?

2022-11-04 16:43 UTC, chrisr3 commented on testing/ledger/ledger-consensual-testkit/build.gradle
> +    implementation project(":testing:ledger:ledger-common-testkit")
Bad IntelliJ.

2022-11-04 16:43 UTC, chrisr3 commented on testing/ledger/ledger-utxo-testkit/build.gradle
> +    implementation project(":testing:ledger:ledger-common-testkit")
Another completely unnecessary replacement of single quotes with double quotes.

2022-11-04 16:52 UTC, chrisr3 commented on components/ledger/ledger-common-flow/build.gradle
> +    id "corda.common-library"
> From here: [#2396 (comment)](https://github.com/corda/corda-runtime-os/pull/2396#discussion_r1012751478) But maybe I over did it a little bit.. Would you prefer to keep the `id`s single quoted everywhere?

Yes please. Single quotes are Java `String` but double quotes are Groovy Strings. You only need Groovy if you intend to expand properties e.g. "net.corda:burble:$burbleVersion".

2022-11-04 17:00 UTC, vlajos commented on components/ledger/ledger-common-flow/build.gradle
> +    id "corda.common-library"
OK.
I reverted them in `id`s and `description`s and kept the double ones in `dependencies`.
Still a bit noise, but much less.

2022-11-04 17:03 UTC, chrisr3 commented on components/ledger/ledger-common-flow/build.gradle
> +    id "corda.common-library"
I see no reason for using double quotes unless you need to expand a property :shrug:.

2022-11-04 17:28 UTC, vlajos commented on components/ledger/ledger-consensual-persistence-impl/src/main/kotlin/net/corda/ledger/consensual/persistence/impl/processor/ConsensualLedgerMessageProcessor.kt
> +        )
Ehh. Sorry. My conflict resolution was not perfect.
Anyway these are reverted now.

2022-11-04 17:30 UTC, vlajos commented on components/ledger/ledger-consensual-persistence-impl/src/main/kotlin/net/corda/ledger/consensual/persistence/impl/processor/ConsensualLedgerMessageProcessor.kt
> +        )
So the only changes remaining in `persistence-impl` are in `ConsensualLedgerRepository.kt`.
Do those use correctly the services?

2022-11-04 17:39 UTC, vlajos commented on components/ledger/ledger-consensual-flow/src/main/kotlin/net/corda/ledger/consensual/flow/impl/transaction/factory/ConsensualSignedTransactionFactoryImpl.kt
> +            .toByteArray(Charsets.UTF_8) // TODO(update with CORE-6890)
I have removed it.

2022-11-07 08:20 UTC, vlajos commented on components/ledger/ledger-common-flow/src/main/java/net/corda/ledger/common/flow/impl/transaction/factory/package-info.java
> +package net.corda.ledger.common.flow.impl.transaction.factory;
I could move the related TransactionMetadataFactory to the ledger-common-flow-api module to be able to get rid of this.

2022-11-07 10:25 UTC, MrMatthewLayton commented on testing/ledger/ledger-common-testkit/build.gradle
> +    compileOnly "org.osgi:osgi.annotation"
@chrisr3 I actually prefer double quotes  for a couple of reasons:
1. Consistency in gradle files; no mismatch of single or double quotes
2. Even if you _don't_ decide to extend a property (i.e. "$foo:bar") the strings still work, and you don't have to change them if/when you _do_ decide to extend a property.

2022-11-07 11:10 UTC, chrisr3 commented on testing/ledger/ledger-common-testkit/build.gradle
> +    compileOnly "org.osgi:osgi.annotation"
> @chrisr3 I actually prefer double quotes for a couple of reasons:
>     2. Even if you _don't_ decide to extend a property (i.e. "$foo:bar") the strings still work, and you don't have to change them if/when you _do_ decide to extend a property.

The dependencies which don't have explicit versions are acquiring their versions from the `platform`. In which case, it would be an error to assign an explicit version using a property. Nor do `project(':x:y:z')` dependencies need a version anyway.

2022-11-07 13:57 UTC, vlajos commented on components/ledger/ledger-consensual-flow/src/main/java/net/corda/ledger/consensual/flow/impl/transaction/factory/package-info.java
> +package net.corda.ledger.consensual.flow.impl.transaction.factory;
I have opened this: CORE-7649, to fix this problem when it its other obstacles will be already removed.

2022-11-07 13:57 UTC, vlajos commented on components/ledger/ledger-consensual-flow/src/main/kotlin/net/corda/ledger/consensual/flow/impl/transaction/factory/ConsensualSignedTransactionFactory.kt
> +    @Suspendable
I have removed it.

2022-11-07 14:16 UTC, vlajos commented on components/ledger/ledger-utxo-flow/src/main/kotlin/net/corda/ledger/utxo/flow/impl/transaction/factory/UtxoSignedTransactionFactory.kt
> +    @Suspendable
I have remove this too.

2022-11-07 14:38 UTC, vlajos commented on components/ledger/ledger-consensual-flow/src/main/kotlin/net/corda/ledger/consensual/flow/impl/transaction/factory/ConsensualSignedTransactionFactory.kt
> +    @Suspendable
Hmm. Without it, I get this:
```
WARNING: Uninstrumented whole methods ('**') or single calls ('!!') detected:
        at co.paralleluniverse.common.util.ExtendedStackTrace.here() (ExtendedStackTrace.java:46)
        at co.paralleluniverse.fibers.Fiber.checkInstrumentation() (Fiber.java:1762)
        at co.paralleluniverse.fibers.Fiber.verifySuspend(co.paralleluniverse.fibers.Fiber) (Fiber.java:1735)
        at co.paralleluniverse.fibers.Fiber.verifySuspend() (Fiber.java:1730)
        at co.paralleluniverse.fibers.Fiber.park(java.lang.Object,co.paralleluniverse.fibers.Fiber$ParkAction,long,java.util.concurrent.TimeUnit) (Fiber.java:713)
        at co.paralleluniverse.fibers.Fiber.park(java.lang.Object,co.paralleluniverse.fibers.Fiber$ParkAction) (Fiber.java:717)
        at co.paralleluniverse.fibers.Fiber.parkAndSerialize(co.paralleluniverse.fibers.FiberWriter) (Fiber.java:2070)
        at net.corda.flow.fiber.FlowFiberImpl.suspend(net.corda.flow.fiber.FlowIORequest) (FlowFiberImpl.kt:124)
        at net.corda.flow.external.events.impl.executor.ExternalEventExecutorImpl.execute(java.lang.String,java.lang.Class,java.lang.Object) (ExternalEventExecutorImpl.kt:30)
        at net.corda.flow.external.events.impl.executor.ExternalEventExecutorImpl.execute(java.lang.Class,java.lang.Object) (ExternalEventExecutorImpl.kt:55)
        at net.corda.flow.application.crypto.SigningServiceImpl.sign(byte[],java.security.PublicKey,net.corda.v5.crypto.SignatureSpec) (SigningServiceImpl.kt:34)
        at net.corda.ledger.common.flow.transaction.TransactionSignatureUtilsKt.createTransactionSignature(net.corda.v5.application.crypto.SigningService,net.corda.v5.application.serialization.SerializationService,net.corda.ledger.common.data.transaction.CordaPackageSummary,net.corda.v5.crypto.SecureHash,java.security.PublicKey) (TransactionSignatureUtils.kt:26)
        at net.corda.ledger.consensual.flow.impl.transaction.factory.ConsensualSignedTransactionFactoryImpl.create(net.corda.v5.ledger.consensual.transaction.ConsensualTransactionBuilder,java.lang.Iterable) (ConsensualSignedTransactionFactoryImpl.kt:65)
        at net.corda.ledger.consensual.flow.impl.transaction.ConsensualTransactionBuilderImpl.sign(java.lang.Iterable) (ConsensualTransactionBuilderImpl.kt:36) (optimized) !! (instrumented suspendable calls at: lines [],  calls [])
        at net.corda.ledger.consensual.flow.impl.transaction.ConsensualTransactionBuilderImpl.sign(java.security.PublicKey[]) (ConsensualTransactionBuilderImpl.kt:28)
        at net.cordapp.demo.consensual.ConsensualDemoFlow.call(net.corda.v5.application.flows.RPCRequestData) (ConsensualDemoFlow.kt:82)
        at net.corda.flow.fiber.RPCStartedFlow.invoke() (RPCStartedFlow.kt:14)
        at net.corda.flow.fiber.FlowFiberImpl.runFlow() (FlowFiberImpl.kt:90)
        at net.corda.flow.fiber.FlowFiberImpl.run() (FlowFiberImpl.kt:62)
        at net.corda.flow.fiber.FlowFiberImpl.run() (FlowFiberImpl.kt:22)
        at co.paralleluniverse.fibers.Fiber.run1() (Fiber.java:1164)
```
in the combined-worker's output.
So I think I'll add it back.

2022-11-08 10:40 UTC, MrMatthewLayton commented on components/ledger/ledger-utxo-flow/src/main/kotlin/net/corda/ledger/utxo/flow/impl/transaction/factory/UtxoSignedTransactionFactory.kt
> +    @Suspendable
@chrisr3 Interesting...I've got a load of `@Suspendable` annotations on interfaces too. Worth investigating or reviewing whether they're applicable or not.

2022-11-08 10:59 UTC, lankydan commented on components/ledger/ledger-common-flow-api/build.gradle
> +    implementation project(":libs:virtual-node:sandbox-group-context")
What code in the api module would need the `flow-service` dependency? Suggests something is wrong.

2022-11-08 10:59 UTC, lankydan commented on components/ledger/ledger-common-flow-api/src/main/kotlin/net/corda/ledger/common/flow/transaction/factory/TransactionMetadataFactoryImpl.kt
> +class TransactionMetadataFactoryImpl @Activate constructor(
This should be in `ledger-common-flow` not the api module.

2022-11-08 10:59 UTC, lankydan commented on components/ledger/ledger-consensual-flow/src/main/kotlin/net/corda/ledger/consensual/flow/impl/transaction/ConsensualTransactionBuilderImpl.kt
> +// Is this still needed? TODO Create an AMQP serializer if we plan on sending transaction builders between virtual nodes
Just remove the TODO for now.

2022-11-08 10:59 UTC, lankydan commented on components/ledger/ledger-consensual-flow/src/test/kotlin/net/corda/ledger/consensual/flow/impl/transaction/ConsensualLedgerTransactionImplTest.kt
> +internal class ConsensualLedgerTransactionImplTest: ConsensualLedgerTest() {
why do we need to make this test class internal

2022-11-08 11:22 UTC, vlajos commented on components/ledger/ledger-consensual-flow/src/test/kotlin/net/corda/ledger/consensual/flow/impl/transaction/ConsensualLedgerTransactionImplTest.kt
> +internal class ConsensualLedgerTransactionImplTest: ConsensualLedgerTest() {
I have removed that. It was not needed.

2022-11-08 11:22 UTC, vlajos commented on components/ledger/ledger-consensual-flow/src/main/kotlin/net/corda/ledger/consensual/flow/impl/transaction/ConsensualTransactionBuilderImpl.kt
> +// Is this still needed? TODO Create an AMQP serializer if we plan on sending transaction builders between virtual nodes
Done.

2022-11-08 19:46 UTC, vlajos commented on components/ledger/ledger-common-flow-api/build.gradle
> +    implementation project(":libs:virtual-node:sandbox-group-context")
I moved the related TxMetadataFactoryImpl back to flow-api with these dependencies.

2022-11-08 19:47 UTC, vlajos commented on components/ledger/ledger-common-flow-api/src/main/kotlin/net/corda/ledger/common/flow/transaction/factory/TransactionMetadataFactoryImpl.kt
> +class TransactionMetadataFactoryImpl @Activate constructor(
I moved it back to ledger-common-flow.

2022-11-09 12:55 UTC, lankydan commented on components/ledger/ledger-common-flow/src/main/kotlin/net/corda/ledger/common/flow/impl/transaction/factory/TransactionMetadataFactoryImpl.kt
> +    private val platformInfoProvider: net.corda.libs.platform.PlatformInfoProvider
Why are there not imports for these classes.

2022-11-09 12:55 UTC, lankydan commented on components/ledger/ledger-utxo-flow/src/main/kotlin/net/corda/ledger/utxo/flow/impl/transaction/factory/UtxoSignedTransactionFactoryImpl.kt
> +    service = [UtxoSignedTransactionFactory::class, UsedByFlow::class, UsedByPersistence::class],
Technically I don't think we need the `UsedByPersistence` since we have `ConsensualSignedTransactionContainer` to send to db worker.

2022-11-09 13:37 UTC, vlajos commented on components/ledger/ledger-common-flow/src/main/kotlin/net/corda/ledger/common/flow/impl/transaction/factory/TransactionMetadataFactoryImpl.kt
> +    private val platformInfoProvider: net.corda.libs.platform.PlatformInfoProvider
Thanks. I have just removed it.

2022-11-09 13:37 UTC, vlajos commented on components/ledger/ledger-utxo-flow/src/main/kotlin/net/corda/ledger/utxo/flow/impl/transaction/factory/UtxoSignedTransactionFactoryImpl.kt
> +    service = [UtxoSignedTransactionFactory::class, UsedByFlow::class, UsedByPersistence::class],
I have updated it.

2022-11-09 14:05 UTC, lankydan submitted a review, later dismissed

2022-11-09 20:25 UTC, ronanbrowne submitted a review, later dismissed
LGTM (build)

2022-11-10 09:29 UTC, chrisr3 requested changes, later dismissed
I think the OSGi tests needs to be using the sanfbox's instances of these components, and not the platform's.

2022-11-10 09:29 UTC, chrisr3 commented on components/ledger/ledger-common-flow/build.gradle
> +    compileOnly "org.osgi:osgi.annotation"
I don't understand this superfluous switching of single to double quotes. I _delibrately_ used single quotes here because the version number should _always_ be obtained from the platform and _never_ via property expansion.

In other words, property expansion here would be a bug, so there is no reason to allow it.

2022-11-10 09:29 UTC, chrisr3 commented on components/ledger/ledger-common-flow/build.gradle
>      implementation project(":libs:serialization:serialization-internal")
Diito here. Which property expansion bugs are you planning to introduce now?

2022-11-10 09:29 UTC, chrisr3 commented on components/ledger/ledger-consensual-persistence-impl/src/integrationTest/kotlin/net/corda/ledger/consensual/persistence/impl/processor/tests/ConsensualLedgerRepositoryTest.kt
> +    lateinit var wireTransactionFactory: WireTransactionFactory
Shouldn't this service be created by the sandbox? In fact, the same is probably true for `JsonMarshallingService` as well.

You should be able to replace
```kotlin
@InjectService
lateinit var jsonMarshallingService: JsonMarshallingService
```
with
```kotlin
private lateinit var jsonMarshallingService: JsonMarshallingService
...
@BeforeAll
fun setup(...) {
    lifecycle.accept(sandboxSetup) { setup ->
        ...
        jsonMarshallingService = ctx.getSandboxSingletonService()
        ...
    }
}
```
and similarly for the other sandbox services. Anything injected by `@InjectService` will be the platform's version, which is unlikely to be the one you want to use.`

2022-11-10 09:36 UTC, chrisr3 commented on components/ledger/ledger-consensual-persistence-impl/src/integrationTest/kotlin/net/corda/ledger/consensual/persistence/impl/processor/tests/ConsensualLedgerRepositoryTest.kt
> +    lateinit var wireTransactionFactory: WireTransactionFactory
I should have merged enough "OSGi Bongo" into the `release/os/5.0` branch for you to use, although you may need to rebase first.

2022-11-10 20:43 UTC, benmcmahon100 approved these changes
Github won't let me do a nice comment - just attaching this:
![image](https://user-images.githubusercontent.com/10749142/201201751-5cd53650-d9cb-41eb-8e07-aef05759954e.png)

I agree with @ronanbrowne on standardization, but I think `'` is the wrong choice as I don't think it'll allow string interpolation for versions. However, I think this is better done as a follow up build change to make all of them `"` across the board.

Going to approve the build side as is.

2022-11-10 20:59 UTC, merged