CORE-7219: (consensual ledger) Don't allow TX builder to be reused after signing
corda/corda-runtime-os pull request #2409
Opened 2022-10-28 18:55 UTC by omfR3

To avoid unintended behaviour when constructing transactions, this PR adds a flag to `ConsensualTransactionBuilderImpl` which marks it as spent after a signing operation is successfully performed. Subsequent calls to `sign()` will throw an `IllegalStateException`.

2022-10-31 09:39 UTC, lankydan commented on components/ledger/ledger-consensual-flow/src/main/kotlin/net/corda/ledger/consensual/flow/impl/transaction/ConsensualTransactionBuilderImpl.kt
> +        check(!spent) { "This transaction builder has already been consumed and cannot be used again." }
Can we split this out to a separate function.

2022-10-31 09:53 UTC, blsemo requested changes

2022-10-31 09:53 UTC, blsemo commented on components/ledger/ledger-consensual-flow/src/main/kotlin/net/corda/ledger/consensual/flow/impl/transaction/ConsensualTransactionBuilderImpl.kt
> +        check(!spent) { "This transaction builder has already been consumed and cannot be used again." }
Can we not call it `spent`, please? That is semantically too close to a spent token, which mean something quite different.
Tricky to find a good name that isn't an overload of another ledger concept - how about `used` or `done`?

2022-10-31 10:36 UTC, lankydan commented on components/ledger/ledger-consensual-flow/src/main/kotlin/net/corda/ledger/consensual/flow/impl/transaction/ConsensualTransactionBuilderImpl.kt
> +        check(!spent) { "This transaction builder has already been consumed and cannot be used again." }
Probably just go with `alreadySigned`?

2022-10-31 11:12 UTC, vlajos commented on components/ledger/ledger-consensual-flow/src/main/kotlin/net/corda/ledger/consensual/flow/impl/transaction/ConsensualTransactionBuilderImpl.kt
> +        spent = true
only the sign() operations should consume the builder.

2022-10-31 11:13 UTC, lankydan commented on components/ledger/ledger-consensual-flow/src/main/kotlin/net/corda/ledger/consensual/flow/impl/transaction/ConsensualTransactionBuilderImpl.kt
> +        spent = true
Can't believe i didnt catch that 🤦

2022-10-31 16:11 UTC, blsemo commented on components/ledger/ledger-consensual-flow/src/main/kotlin/net/corda/ledger/consensual/flow/impl/transaction/ConsensualTransactionBuilderImpl.kt
> +        spent = true
No no, that is correct because it returns a copy - so the original (without the states) is spent. Whether it is desirable to do a copy everytime you modify it is a different question.

2022-11-01 10:57 UTC, omfR3 commented on components/ledger/ledger-consensual-flow/src/main/kotlin/net/corda/ledger/consensual/flow/impl/transaction/ConsensualTransactionBuilderImpl.kt
> +        spent = true
Ok. It wasn't entirely clear to me from the ticket, and I figured we'd want to prevent something like this:
```kotlin
val builder2 = builder1.withStates(...)
val signed = builder1.sign(...)
```
Will remove.

2022-11-01 11:43 UTC, omfR3 commented on components/ledger/ledger-consensual-flow/src/main/kotlin/net/corda/ledger/consensual/flow/impl/transaction/ConsensualTransactionBuilderImpl.kt
> +        check(!spent) { "This transaction builder has already been consumed and cannot be used again." }
Probably no need now if we're only asserting in one place.

2022-11-01 11:43 UTC, omfR3 commented on components/ledger/ledger-consensual-flow/src/main/kotlin/net/corda/ledger/consensual/flow/impl/transaction/ConsensualTransactionBuilderImpl.kt
> +        check(!spent) { "This transaction builder has already been consumed and cannot be used again." }
Sure thing -- changed to `alreadySigned` which makes more sense now that we're not setting the flag in `withStates()`.

2022-11-02 15:13 UTC, lankydan submitted a review, later dismissed

2022-11-02 16:21 UTC, vlajos submitted a review, later dismissed

2022-11-04 15:43 UTC, vlajos commented on components/ledger/ledger-consensual-flow/src/test/kotlin/net/corda/ledger/consensual/flow/impl/transaction/ConsensualTransactionBuilderImplTest.kt
> +
Could you please duplicate this for UTXO as well?

2022-11-04 15:45 UTC, omfR3 commented on components/ledger/ledger-consensual-flow/src/test/kotlin/net/corda/ledger/consensual/flow/impl/transaction/ConsensualTransactionBuilderImplTest.kt
> +
Will do.

2022-11-08 15:14 UTC, blsemo approved these changes

2022-11-08 15:18 UTC, merged