CORE-7229: Performance improvement for repeated logons
corda/corda-runtime-os pull request #2415
Opened 2022-10-31 16:36 UTC by vkolomeyko

Before the changes:

For local run:
Single threaded: ~60 seconds
Multi-threaded: ~13 seconds

After the changes:

For local run:
Single threaded: ~?? seconds
Multi-threaded: ~?? seconds

2022-11-01 12:32 UTC, benmcmahon100 commented on libs/permissions/permission-manager-impl/src/main/kotlin/net/corda/libs/permissions/manager/impl/RbacBasicAuthenticationService.kt
> +
Am I reading right that we'd have a cache of cleartext pws in memory?

2022-11-01 12:36 UTC, davidcurrie reviewed
I'm liking those numbers but I have a couple of questions.

2022-11-01 12:36 UTC, davidcurrie commented on libs/permissions/permission-manager-impl/src/main/kotlin/net/corda/libs/permissions/manager/impl/RbacBasicAuthenticationService.kt
> +        repeatedLogonsCache.remove(loginName)
Interested to understand the logic for this. Is the intention that, if my password has changed but the old value is cached, I only get a failed login attempt once?

2022-11-01 12:36 UTC, davidcurrie commented on libs/permissions/permission-manager-impl/src/main/kotlin/net/corda/libs/permissions/manager/impl/RepeatedLogonsCache.kt
> +        cache.put(loginName, clearTextPassword.toCacheValue())
If we're sufficiently concerned about leaking the cache to hash the values, should we also be adding a salt to prevent comparison of hashes?

2022-11-01 12:37 UTC, davidcurrie commented on libs/permissions/permission-manager-impl/src/main/kotlin/net/corda/libs/permissions/manager/impl/RbacBasicAuthenticationService.kt
> +
No - because the cache then hashes the password before storing it.

2022-11-01 12:51 UTC, conalsmith-r3 commented on libs/permissions/permission-manager-impl/src/main/kotlin/net/corda/libs/permissions/manager/impl/RepeatedLogonsCache.kt
> +    fun verifies(loginName: String, clearTextPassword: String): Boolean {
Would it be better to have clearTextPassword as a CharArray on this API?

2022-11-01 13:18 UTC, driessamyn requested changes
Small comment on the perf test, but not a deal-breaker.
But we need to use the Caffeine Cache factory though. That will mean it's exposing the metrics and, more importantly, uses a `ForkJoinPool` that works with the security managers (otherwise you may get issues when Caffeine removes things from cache).

2022-11-01 13:18 UTC, driessamyn commented on libs/permissions/permission-manager-impl/src/main/kotlin/net/corda/libs/permissions/manager/impl/RepeatedLogonsCache.kt
> +    private val cache: Cache<String, ByteArray> = Caffeine.newBuilder()
Please use https://github.com/corda/flow-worker/blob/a0988576f0e4eb7225c988d14fecf3c676de891c/libs/cache/cache-caffeine/src/main/kotlin/net/corda/cache/caffeine/CacheFactoryImpl.kt for integrating with Caffeine.

2022-11-01 13:18 UTC, driessamyn commented on libs/permissions/permission-manager-impl/src/integrationTest/kotlin/net/corda/libs/permissions/manager/impl/RbacBasicAuthenticationServicePerfTest.kt
> +class RbacBasicAuthenticationServicePerfTest {
I'm not overly keen on having performance tests as part of the unit tests, especially as it doesn't assert any results.
Ideally, this should be an assertion in the non-functional test suite.

2022-11-01 13:42 UTC, vkolomeyko commented on libs/permissions/permission-manager-impl/src/main/kotlin/net/corda/libs/permissions/manager/impl/RbacBasicAuthenticationService.kt
> +        repeatedLogonsCache.remove(loginName)
I was more aiming at the case when an adversary is trying to guess the password. Ensuring that it is removed from the cache after the first wrong guess will mean that they are guaranteed to hit a slow hashing function next time they tried.

2022-11-01 13:45 UTC, vkolomeyko commented on libs/permissions/permission-manager-impl/src/main/kotlin/net/corda/libs/permissions/manager/impl/RepeatedLogonsCache.kt
> +        cache.put(loginName, clearTextPassword.toCacheValue())
Yes, it might be a good idea to put this extra protection measure.
But generating a new salt value and hashing with it will make things slower when working with cache.
Would be interested to get some input from @jamesbr3 - if this is worthwhile in this case from security point of view.

2022-11-01 13:46 UTC, vkolomeyko commented on libs/permissions/permission-manager-impl/src/main/kotlin/net/corda/libs/permissions/manager/impl/RepeatedLogonsCache.kt
> +    fun verifies(loginName: String, clearTextPassword: String): Boolean {
Yes, I was thinking of that, but we need password as `String` anyway for the other (slow hash) `verifies` call anyway.

2022-11-01 13:47 UTC, vkolomeyko commented on libs/permissions/permission-manager-impl/src/main/kotlin/net/corda/libs/permissions/manager/impl/RepeatedLogonsCache.kt
> +    private val cache: Cache<String, ByteArray> = Caffeine.newBuilder()
Yes, I saw that module, but desided against using it as it was not adding much of a benefit. And I wanted to see where we stand in simplistic case performance-wise.
I will change to use it now.

2022-11-01 13:54 UTC, vkolomeyko commented on libs/permissions/permission-manager-impl/src/integrationTest/kotlin/net/corda/libs/permissions/manager/impl/RbacBasicAuthenticationServicePerfTest.kt
> +class RbacBasicAuthenticationServicePerfTest {
>  as part of the unit tests

Well it is an integration test and also my understanding that we do not currently have non-functional test suite in the project.
The main reason for this test is that I wanted to have a benchmark in place to make sure I am indeed making a tangible improvement.

I am sort of flexible of whether:
1. Leave this integration test place as it takes ~2 seconds to run;
or
2. `@Disable` it with a comment should people need to make modification to `RbacBasicAuthenticationService`
or
3. Delete it all together, as it served its purpose for now.

> as it doesn't assert any results.

The are some asserts actually: 
```
assertTrue(rbacBasicAuthenticationService.authenticateUser(userLogons.first(), passwordString.toCharArray()))
...
assertThat(result).allMatch { true }
```

2022-11-01 13:59 UTC, driessamyn commented on libs/permissions/permission-manager-impl/src/integrationTest/kotlin/net/corda/libs/permissions/manager/impl/RbacBasicAuthenticationServicePerfTest.kt
> +class RbacBasicAuthenticationServicePerfTest {
The non-functional tests are here: https://github.com/corda/corda-non-functional-test/

We should probably arrange a demo. I'll discuss that with the group.

WRT the asserts, I appreciate there's asserts, but they don't assert the performance, so there's little value in having them as they wouldn't catch a regression. 
I know that's unlikely and it's not a show-stopper, but I do wonder if we should have a follow-up task to move this test into the non-functional one.

I.e. similar to these assertions: https://github.com/corda/corda-non-functional-test/blob/4f5a3dbe05114a4be2de0289a9c36d832bc48d4a/soak-tests/src/gatling/kotlin/net.corda.test.performance/simulations/Soak.kt#L49 we can specify that x % of authentication request must complete within y ms, for example.

2022-11-01 14:18 UTC, davidcurrie commented on libs/permissions/permission-manager-impl/src/main/kotlin/net/corda/libs/permissions/manager/impl/RepeatedLogonsCache.kt
> +        cache.put(loginName, clearTextPassword.toCacheValue())
Can you use the login as the salt?

2022-11-01 14:20 UTC, vkolomeyko commented on libs/permissions/permission-manager-impl/src/integrationTest/kotlin/net/corda/libs/permissions/manager/impl/RbacBasicAuthenticationServicePerfTest.kt
> +class RbacBasicAuthenticationServicePerfTest {
Thanks @driessamyn for sharing links to the non-functional test repository.

Having a quick look at it, it seems to be testing against running cluster and can asserts that certain Rest operations complete within predefined timeframe.
But it a way it would be a rather complex system test which looks at the cluster as a whole. We can though add some asserts for simple operations (like starting a flow) that Rest call completes within certain time.

For the test I wrote, it checks specifically Basic Authentication sub-system only which is a lot more focused.
I wonder if it would be easy to move the test I wrote to `corda-non-functional-test` repo given that `RbacBasicAuthenticationService` is not OSGi exported and is really not meant to be visible outside of the module.
I can add an assert on performance for the test to check that operation completes under 10 seconds for example.

2022-11-01 14:21 UTC, davidcurrie commented on libs/permissions/permission-manager-impl/src/main/kotlin/net/corda/libs/permissions/manager/impl/RbacBasicAuthenticationService.kt
> +        repeatedLogonsCache.remove(loginName)
If you miss on the cache due to an incorrect password, don't you fall through to the slow hashing anyway? By the time they only get the fast hash then they have the correct password!

2022-11-01 14:25 UTC, vkolomeyko commented on libs/permissions/permission-manager-impl/src/main/kotlin/net/corda/libs/permissions/manager/impl/RepeatedLogonsCache.kt
> +        cache.put(loginName, clearTextPassword.toCacheValue())
That is a good idea and should be easy to do. Let me do that.

2022-11-01 14:27 UTC, vkolomeyko commented on libs/permissions/permission-manager-impl/src/main/kotlin/net/corda/libs/permissions/manager/impl/RbacBasicAuthenticationService.kt
> +        repeatedLogonsCache.remove(loginName)
That is true, but then second time trying to guess the password (if the entry is not removed from cache) the first check is done against SHA-256 function which I view as weaker.
Therefore, I thought it would be sensible to remove the cache entry after first wrong guess. But I do not have a strong opinion here.

2022-11-01 14:36 UTC, vkolomeyko commented on libs/permissions/permission-manager-impl/src/integrationTest/kotlin/net/corda/libs/permissions/manager/impl/RbacBasicAuthenticationServicePerfTest.kt
> +class RbacBasicAuthenticationServicePerfTest {
I have added assert on the elapsed time.

2022-11-01 15:38 UTC, davidcurrie commented on libs/permissions/permission-manager-impl/src/main/kotlin/net/corda/libs/permissions/manager/impl/RbacBasicAuthenticationService.kt
> +        repeatedLogonsCache.remove(loginName)
I'm not sure I have a strong opinion here either. My initial thought was that I can cause you pain by repeatedly incorrectly guessing your password but then that's the position we have with the current approach anyway where my incorrect attempts would chew up CPU.

2022-11-01 15:39 UTC, davidcurrie submitted a review, later dismissed
LGTM but I'd like to see a 👍 from @jamesbr3 to this approach

2022-11-01 17:10 UTC, driessamyn submitted a review, later dismissed
LGTM

2022-11-01 17:16 UTC, ronanbrowne submitted a review, later dismissed
LGTM (build)

2022-11-01 17:27 UTC, conalsmith-r3 submitted a review, later dismissed
lgtm

2022-11-02 13:37 UTC, jamesbr3 approved these changes, later dismissed
looks good (i.e. hasn't introduced a problem); added some comments inline.

Might be worth considering, or documenting: what attack(s) are you defending against with this change? Does this PR address these risks, and what benefit does it have overall? 

Two I can think of OTOH are:
* in-memory snooping by a rogue progress / debugger. In which case, your whole service is compromised, and an attacker will get to see clear-text passwords anyway as they are sent over the HTTP request. So not very useful against this attack?
* core dumps / lazy garbage collection / in-memory passwords being dumped to disk by a mechanism outside of your control. In this case, you've got some plausible looking benefit. 

Obviously it feels 'wrong' to be storing cleartext passwords, even in memory only, so the concept of this change is a good one. Do you see this as a 'belt and braces' mitigation? You need to balance over-complicating the code, with the security benefit it introduces which I think you've done here well. 

Your use of the loginName as a sort-of-salt is a nice touch. Not sure if that is deliberate, but it helps against the rainbow-table attack scenario. You can easily evolve this code if you need to - it seems nice & self-contained atm.

2022-11-02 13:37 UTC, jamesbr3 commented on libs/permissions/permission-manager-impl/src/main/kotlin/net/corda/libs/permissions/manager/impl/RepeatedLogonsCache.kt
> +        return "$first:$second".toByteArray().sha256Bytes()
ok so this is the magic line. when toCacheValue is being used, loginName is acting as form of low-entropy salt which is combined with the password to derive the digest value. Was that the intention? (might be worth putting in a comment here, or down on the line where it is called by the verifies() function).

AFAICT there isn't a functional need to combine the loginName this way, because the cache already provides the name/hashed password mapping. 

If you want the real benefit of a salt, consider using a true salt value? i.e something strong/random that is calculated when this service starts up.

2022-11-02 13:37 UTC, jamesbr3 commented on libs/permissions/permission-manager-impl/src/main/kotlin/net/corda/libs/permissions/manager/impl/RbacBasicAuthenticationService.kt
> +        if(repeatedLogonsCache.verifies(loginName, clearTextPassword)) {
this is where a vulnerability might _potentially_ creep in, as this is the way to bypass the actual authentication mechanism (passwordService) below. But your code is nice and clear (10/10 - super important for authentication logic) so I think you're good here.

2022-11-02 13:37 UTC, jamesbr3 commented on libs/permissions/permission-manager-impl/src/main/kotlin/net/corda/libs/permissions/manager/impl/RepeatedLogonsCache.kt
> +        return (loginName to clearTextPassword).toCacheValue().contentEquals(cachedValue)
looks good. Really important that the cached value must exactly equal the computed value, otherwise the authentication must fail. IMHO I would add a comment in on this line as its the most important change in the whole PR

2022-11-02 14:38 UTC, vkolomeyko commented on libs/permissions/permission-manager-impl/src/main/kotlin/net/corda/libs/permissions/manager/impl/RepeatedLogonsCache.kt
> +        return "$first:$second".toByteArray().sha256Bytes()
Yes, @davidcurrie commented along similar lines earlier on: https://github.com/corda/corda-runtime-os/pull/2415#discussion_r1010376423

We settled not to generate (and store) an individual hash for every user, but to have a userLogon as a salt. That way if two users have the same password hashes stored in the cache will be different. I.e. we do not want adversary to know that two logins have the same password.

2022-11-02 15:14 UTC, merged