CORE-7298 Virtual node vault database reconcile reader for group parameters tables
corda/corda-runtime-os pull request #2453
Opened 2022-11-04 11:31 UTC by charlieR3

2022-11-07 16:14 UTC, charlieR3 commented on libs/membership/membership-common/src/main/kotlin/net/corda/membership/lib/GroupParametersFactory.kt
> +interface GroupParametersFactory {
Interface added in https://github.com/corda/corda-runtime-os/pull/2434
Copied here without implementation to develop against while waiting for that PR.

2022-11-08 16:29 UTC, nikinagy commented on libs/membership/membership-common/src/main/kotlin/net/corda/membership/lib/GroupParametersFactory.kt
> +interface GroupParametersFactory {
You can do a rebase now and remove this.

2022-11-08 16:29 UTC, nikinagy commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/reconcile/db/ClusterDbReconcilerReader.kt
> + * [GetRecordsErrorEvent]. Then depending on if the exception is a transient or not its state should be taken to
```suggestion
 * [GetRecordsErrorEvent]. Then depending on if the exception is transient or not its state should be taken to
```

2022-11-08 16:29 UTC, nikinagy commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/reconcile/db/DbReconcilerReaderComponent.kt
> +        // TODO based on exception determine component's next state i.e if transient exception or not -> DOWN or ERROR
can we map this to a jira ticket to make sure this will be really done in the future?

2022-11-08 16:29 UTC, nikinagy commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/reconcile/db/VirtualNodeVaultDbReconcilerReader.kt
> + * [reconcilerQuery#invoke()] is called once per vnode and the results of each call are combine in to a single stream.
```suggestion
 * [reconcilerQuery#invoke()] is called once per vnode and the results of each call are combined into a single stream.
```

2022-11-08 16:29 UTC, nikinagy commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/reconcile/db/VirtualNodeVaultDbReconcilerReader.kt
> + *  records. This is applied against all virtual node vault DB and the results are combined in to a single stream.
```suggestion
 *  records. This is applied against all virtual node vault DB and the results are combined into a single stream.
```

2022-11-08 16:29 UTC, nikinagy commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/reconcile/db/VirtualNodeVaultDbReconcilerReader.kt
> +                "persistenceUnitName ${CordaDb.Vault.persistenceUnitName} is not registered."
I think we should somehow have a distinction when we are throwing exceptions with variable names and their values by using '' or something.

2022-11-08 16:29 UTC, nikinagy commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/reconcile/db/query/GroupParametersReconciliationQuery.kt
> +            ?: throw CordaRuntimeException("Could not deserialize group parameters from the database.")
Do we need the duplicate and almost identical error message from line 31?

2022-11-08 16:29 UTC, nikinagy commented on processors/db-processor/src/test/kotlin/net/corda/processors/db/internal/reconcile/db/query/GroupParametersReconciliationQueryTest.kt
> +import java.util.*
Remove star import

2022-11-08 16:29 UTC, nikinagy commented on processors/db-processor/src/test/kotlin/net/corda/processors/db/internal/reconcile/db/query/GroupParametersReconciliationQueryTest.kt
> +        Assertions.assertThat(versionedRecord.version).isEqualTo(epochValue)
Import Assertions.assertThat instead

2022-11-08 16:29 UTC, nikinagy commented on processors/db-processor/src/test/kotlin/net/corda/processors/db/internal/reconcile/db/VirtualNodeVaultDbReconcilerReaderTest.kt
> +import java.util.*
remove * import

2022-11-08 16:36 UTC, charlieR3 commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/reconcile/db/DbReconcilerReaderComponent.kt
> +        // TODO based on exception determine component's next state i.e if transient exception or not -> DOWN or ERROR
I kept this as it originally was. I'm not sure who is tracking that TODO but it's outside of our backlog.

2022-11-08 16:47 UTC, charlieR3 commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/reconcile/db/DbReconcilerReaderComponent.kt
> +        // TODO based on exception determine component's next state i.e if transient exception or not -> DOWN or ERROR
@kyriathar are you aware if there is a jira tracking that?

2022-11-08 17:03 UTC, kyriathar commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/reconcile/db/DbReconcilerReaderComponent.kt
> +        // TODO based on exception determine component's next state i.e if transient exception or not -> DOWN or ERROR
There wasn't, just registered [CORE-7792](https://r3-cev.atlassian.net/browse/CORE-7792) for it, thank you.

2022-11-08 17:23 UTC, charlieR3 commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/reconcile/db/DbReconcilerReaderComponent.kt
> +        // TODO based on exception determine component's next state i.e if transient exception or not -> DOWN or ERROR
Thanks @kyriathar 
Added to PR

2022-11-10 10:09 UTC, yift-r3 commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/reconcile/db/ClusterDbReconcilerReader.kt
> +                em.close()
Do we need to close it in a `finally` pattern (if we had an exception after the begin)?

2022-11-10 10:09 UTC, yift-r3 commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/reconcile/db/GroupParametersReconciler.kt
> +        logger.debug("Group parameters reconciliation interval set to $intervalMillis ms")
Are we using the `intervalMillis` for something besides logging?

2022-11-10 10:09 UTC, yift-r3 commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/reconcile/db/GroupParametersReconciler.kt
> +        if (dbReconciler == null) {
If it's not null, should we close and recreate it?

2022-11-10 10:09 UTC, yift-r3 commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/reconcile/db/VirtualNodeVaultDbReconcilerReader.kt
> +                    )
We can have `.use {..` instead of `try... finally...`

2022-11-10 10:14 UTC, charlieR3 commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/reconcile/db/GroupParametersReconciler.kt
> +        logger.debug("Group parameters reconciliation interval set to $intervalMillis ms")
Not yet. We have another Jira to pull together the DB reader, the kafka reader and the kafka writer which should then use that property.

2022-11-10 10:14 UTC, driessamyn reviewed
Only did a superficial review. Conceptually, this looks ok, but I would like @kyriathar to have a a more detailed review.
My only comment would that I don't think using abstract base classes is great as a general pattern. Composition is nearly always a better pattern than inheritance for code-reuse.

2022-11-10 10:14 UTC, driessamyn commented on processors/db-processor/build.gradle
> +    implementation "net.corda:corda-membership"
```suggestion
    implementation 'net.corda:corda-membership'
```

2022-11-10 10:14 UTC, driessamyn commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/reconcile/db/DbReconcilerReaderComponent.kt
> +abstract class DbReconcilerReaderComponent<K : Any, V : Any>(
Not a fan of inheritence for re-use. It ends up being super fragile and things like having to mark things as `VisibleForTesting` is a smell.
Composition is nearly always a better patter for re-use.

2022-11-10 10:14 UTC, driessamyn commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/reconcile/db/GroupParametersReconciler.kt
> +        logger.debug("Group parameters reconciliation interval set to $intervalMillis ms")
```suggestion
        logger.debug { "Group parameters reconciliation interval set to $intervalMillis ms" }
```

2022-11-10 10:18 UTC, charlieR3 commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/reconcile/db/GroupParametersReconciler.kt
> +        if (dbReconciler == null) {
Yep, good point. Will do that.

2022-11-10 10:20 UTC, charlieR3 commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/reconcile/db/VirtualNodeVaultDbReconcilerReader.kt
> +                    )
I was going to do that but `use` for `EntityManagerFactory` doesn't close the EMF. It only closes the `EntityManager`.

2022-11-10 10:25 UTC, charlieR3 commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/reconcile/db/ClusterDbReconcilerReader.kt
> +                em.close()
I wonder will that impact the versioned records streaming since the em is closed currently when the streams are closed. Closing it in finally would be safer I think but I'm not sure if it was intentionally implemented in the current way previously. @kyriathar do you know?

2022-11-10 10:43 UTC, driessamyn commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/reconcile/db/VirtualNodeVaultDbReconcilerReader.kt
> +                    )
We need to have a bit a think about this.
Creating and closing EntityManagerFactory is expensive. For cluster connections, we don't close it because they are created once, then re-used. For VNodes, we can't really do this as in the case of 100s of Vnodes, we'd run out of connections. 
This hasn't been too much of a problem because when Vnode connections are used in flows, they are using an EntityManagerFactory that is stored in the Sandbox, which in turn is cached. 
When this happens outside the Sandbox, we don't have a caching mechanism in place. 
We have an item on the backlog to profile and optimise the way we use connections and the pools, so it's probably ok for now, but just wanted to let you know.

As for closing the EMF, @charlieR3 is right that `use` doesn't close it because it doesn't implement `Autocloseable`. This has been [fixed](https://github.com/jakartaee/persistence/issues/77) in later versions, but we can't easily upgrade as the java ecosystem, in all their wisdom, have changed the package namespace from `javax.persistence` to `jakarta.persistence`.

2022-11-10 11:11 UTC, kyriathar reviewed
Conceptually looks ok, some comments.

2022-11-10 11:11 UTC, kyriathar commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/reconcile/db/GroupParametersReconciler.kt
> +) : ReconcilerWrapper {
Not to do with this PR but I believe `ReconcilerWrapper` adds unneeded overhead, something to revise and maybe refactor later/ remove.

2022-11-10 11:11 UTC, kyriathar commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/reconcile/db/DbReconcilerReader.kt
> +interface DbReconcilerReader<K : Any, V : Any>: ReconcilerReader<K, V>, Lifecycle
Maybe this marker interface adds maybe unneeded overhead I believe.

2022-11-10 11:11 UTC, kyriathar commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/reconcile/db/GroupParametersReconciler.kt
> +        if (dbReconciler == null) {
This is meant to be this way, i.e. update the reconciler interval but I do agree is not clear enough from the context.

2022-11-10 11:11 UTC, kyriathar commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/reconcile/db/DbReconcilerReaderComponent.kt
> +abstract class DbReconcilerReaderComponent<K : Any, V : Any>(
I agree with Dries in favour of composition here .

2022-11-10 11:11 UTC, kyriathar commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/reconcile/db/DbReconcilerReaderComponent.kt
> +    internal abstract val name: String
If we are to keep inheritance let's better pass in to abstract class constructor key and value `Class` and create name here for any implementation, using `this` to reference impl class at runtime.

2022-11-10 11:11 UTC, kyriathar commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/reconcile/db/DbReconcilerReaderComponent.kt
> +abstract class DbReconcilerReaderComponent<K : Any, V : Any>(
If we are to stay with inheritance let's better name it `AbstractDbReconcilerReader` I think.

2022-11-10 11:11 UTC, kyriathar commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/reconcile/db/DbReconcilerReaderComponent.kt
> +    }
Making above `name` property non abstract then `name` is available at construction time.

2022-11-10 11:11 UTC, kyriathar commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/reconcile/db/VirtualNodeVaultDbReconcilerReader.kt
> +                .map { vnode ->
I think we could better stream through result set here. 

Maybe convert it to a `Stream` before `map` to better stream through the virtual node info, because at the moment we just go and fetch virtual node and info and then just converting to stream.

Then I think after map function a 
```kotlin
.flatMap {
    it.stream()
}
```

would do it?

2022-11-10 11:28 UTC, kyriathar commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/reconcile/db/ClusterDbReconcilerReader.kt
> +                em.close()
I think exceptions will not be thrown here but at stream consumption site.

So `finally` pattern not much use here I think.

I think it is rather we need to make sure we call `close` on stream after consumed which I believe we do at `ReconcilerEventHandler.reconciler()`.

2022-11-10 12:35 UTC, charlieR3 commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/reconcile/db/DbReconcilerReaderComponent.kt
> +abstract class DbReconcilerReaderComponent<K : Any, V : Any>(
Fair point. I've refactored it for a composition approach. Will push in a moment.

2022-11-10 12:50 UTC, charlieR3 commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/reconcile/db/DbReconcilerReaderComponent.kt
> +abstract class DbReconcilerReaderComponent<K : Any, V : Any>(
Refactored approach is pushed now.

2022-11-10 12:51 UTC, charlieR3 commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/reconcile/db/DbReconcilerReader.kt
> +interface DbReconcilerReader<K : Any, V : Any>: ReconcilerReader<K, V>, Lifecycle
This interface is more useful now after refactoring to remove inheritance for the common lifecycle handling.

2022-11-10 12:52 UTC, charlieR3 commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/reconcile/db/DbReconcilerReaderComponent.kt
> +    internal abstract val name: String
Removed inheritance.

2022-11-10 12:52 UTC, charlieR3 commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/reconcile/db/DbReconcilerReaderComponent.kt
> +abstract class DbReconcilerReaderComponent<K : Any, V : Any>(
Removed inheritance.

2022-11-10 12:53 UTC, charlieR3 commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/reconcile/db/DbReconcilerReaderComponent.kt
> +    }
Was able to change this when refactoring to remove inheritance.

2022-11-11 09:24 UTC, charlieR3 commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/reconcile/db/VirtualNodeVaultDbReconcilerReader.kt
> +                .map { vnode ->
Spoke offline, will not add this change.

2022-11-11 09:25 UTC, charlieR3 commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/reconcile/db/VirtualNodeVaultDbReconcilerReader.kt
> +                    )
Thanks, Dries. I know this came up before in another area we were looking at persistence and the outcome was to close the EMF after use, knowing that there would be a future review of performance and how to tweak this which is why I took the same approach here.

2022-11-11 10:51 UTC, kyriathar commented
I believe it looks more confusing with composition in this case after all. I would say let's revert back to inheritance. `DbReconcilerReader` interface as it stands now I believe it does not add much conceptually, and with inheritance it was more clear and straightforward the error handling at `getAllVersionedRecords`. @driessamyn what do you think?

2022-11-11 11:49 UTC, driessamyn commented
> I believe it looks more confusing with composition in this case after all. I would say let's revert back to inheritance. `DbReconcilerReader` interface as it stands now I believe it does not add much conceptually, and with inheritance it was more clear and straightforward the error handling at `getAllVersionedRecords`. @charlieR3, @driessamyn what do you think?

I'm not sure about reverting back to the inheritance model. It's an anti-pattern in my opinion.
But, do we need the 2 different readers? Isn't the only difference between them the way the EMF is created? In this case, can't we just inject an EMF factory function?

2022-11-11 12:47 UTC, charlieR3 commented
> > I believe it looks more confusing with composition in this case after all. I would say let's revert back to inheritance. `DbReconcilerReader` interface as it stands now I believe it does not add much conceptually, and with inheritance it was more clear and straightforward the error handling at `getAllVersionedRecords`. @charlieR3, @driessamyn what do you think?
> 
> I'm not sure about reverting back to the inheritance model. It's an anti-pattern in my opinion. But, do we need the 2 different readers? Isn't the only difference between them the way the EMF is created? In this case, can't we just inject an EMF factory function?

@driessamyn That main difference is that for cluster DBs the EMF is created based on the lifecycle start event, cached, and reused, whereas for the virtual node vault DB it's created on demand and closed after use. As I understand it, we shouldn't cached the vault EMFs. The other difference is that for the vault queries we're combining multiple sources, and the cluster queries are against a single DB.

2022-11-11 13:32 UTC, driessamyn commented
> That main difference is that for cluster DBs the EMF is created based on the lifecycle start event, cached, and reused, whereas for the virtual node vault DB it's created on demand and closed after use. As I understand it, we shouldn't cached the vault EMFs. 

But this could be supported by injecting a factory method, right? In one case it'll make one, in the other, it'll get the cached on. This feels like a concern outside of this class.

> The other difference is that for the vault queries we're combining multiple sources, and the cluster queries are against a single DB.

That also seems to be a concern outside this class. I.e. The reader takes data from a db and streams it out. If it needs to do that for x virtual nodes, then in my view this means this just needs to be triggered for each vnode.

2022-11-11 15:25 UTC, charlieR3 commented
> > That main difference is that for cluster DBs the EMF is created based on the lifecycle start event, cached, and reused, whereas for the virtual node vault DB it's created on demand and closed after use. As I understand it, we shouldn't cached the vault EMFs.
> 
> But this could be supported by injecting a factory method, right? In one case it'll make one, in the other, it'll get the cached on. This feels like a concern outside of this class.
> 
> > The other difference is that for the vault queries we're combining multiple sources, and the cluster queries are against a single DB.
> 
> That also seems to be a concern outside this class. I.e. The reader takes data from a db and streams it out. If it needs to do that for x virtual nodes, then in my view this means this just needs to be triggered for each vnode.

So I'm not leaving this hanging - I'm looking at how I can improve the implementation now with that feedback and will get back to you.

2022-11-14 16:53 UTC, charlieR3 commented
@driessamyn @kyriathar Could I get another review of this please? I've taken a new approach which I hope is in line with what you were suggesting. It does look much cleaner now, although I've had to create multiple readers for the group parameters reconciliation to keep that common base class.

2022-11-15 12:08 UTC, yift-r3 commented on components/reconciliation/reconciliation-impl/src/main/kotlin/net/corda/reconciliation/impl/ReconcilerEventHandler.kt
> +            dbReaders.map {
You can do `flatMap` and put the filter outside. (I'm not sure if it will be better)

2022-11-15 12:08 UTC, yift-r3 commented on components/reconciliation/reconciliation-impl/src/main/kotlin/net/corda/reconciliation/impl/ReconcilerFactoryImpl.kt
>          ReconcilerImpl(dbReader, kafkaReader, writer, keyClass, valueClass, coordinatorFactory, reconciliationIntervalMs)
Maybe `ReconcilerImpl(listOf(dbReader),...)` to have a single constructor?

2022-11-15 12:08 UTC, yift-r3 commented on components/reconciliation/reconciliation/src/main/kotlin/net/corda/reconciliation/ReconcilerFactory.kt
>      ): Reconciler
Or maybe, we can have the first create call the second one in the interface?

2022-11-15 12:08 UTC, yift-r3 commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/reconcile/db/DbReconcilerReader.kt
> +    private val dependencies: Set<LifecycleCoordinatorName>,
Have you considered using the DominoTile?

2022-11-15 12:08 UTC, yift-r3 commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/reconcile/db/GroupParametersReconciler.kt
> +    @VisibleForTesting
If it's internal, do we need the `VisibleForTesting`?

2022-11-15 12:08 UTC, yift-r3 commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/reconcile/db/GroupParametersReconciler.kt
> +            val uniqueId = "${vnodeInfo.holdingIdentity.shortHash.value}-${UUID.randomUUID()}"
`val uniqueId = "${holdingId.shortHash.value}-${UUID.randomUUID()}"`

2022-11-15 12:08 UTC, yift-r3 commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/reconcile/db/GroupParametersReconciler.kt
> +            fun emfTearDown() = emfBucket.computeIfPresent(uniqueId) { _, oldValue ->
`emfBucket.remove(uniqueId)?.close()`?

2022-11-15 12:33 UTC, charlieR3 commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/reconcile/db/DbReconcilerReader.kt
> +    private val dependencies: Set<LifecycleCoordinatorName>,
I thought the domino logic was only used by p2p before the lifecycle handling was added. I'm unfamiliar with those classes though so not 100% sure if that's the case. You think it's worth checking to see if it can be used here?

2022-11-15 12:35 UTC, charlieR3 commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/reconcile/db/GroupParametersReconciler.kt
> +    @VisibleForTesting
I only added the annotation because I would have made it private if I didn't want to access it for assertions in the tests. i.e. internal visibility is only there for the tests. 
The annotation doesn't add any value as far as I'm aware really other than to flag why it's internal and not private.

2022-11-15 12:39 UTC, charlieR3 commented on components/reconciliation/reconciliation/src/main/kotlin/net/corda/reconciliation/ReconcilerFactory.kt
>      ): Reconciler
I think I prefer adding the changes to the imple class instead of having default implementations on the interfaces.

2022-11-15 12:59 UTC, charlieR3 commented on components/reconciliation/reconciliation-impl/src/main/kotlin/net/corda/reconciliation/impl/ReconcilerEventHandler.kt
> +            dbReaders.map {
I had a look at this and I'm not sure it works as intended since `flatMap` requires that you return `Iterable` but `getAllVersionedRecords` returns `Stream`

2022-11-15 14:27 UTC, driessamyn commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/reconcile/db/GroupParametersReconciler.kt
> +        }
I don't think this is necessary. You can just iterate over all the nodes every time.
Is there a big advantage in caching them? Especially as the EMF can't be cached alongside it anyway, so maybe it makes more sense to just create the reconciler objects on demand and expose of them immediately.

2022-11-15 14:37 UTC, charlieR3 commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/reconcile/db/GroupParametersReconciler.kt
> +        }
Storing a reference to the DB reconcilers is no different to existing `ReconcilerWrapper` implementations that I can see other than it's a list instead of a single reconciler. 
Creating them on demand and then disposing of them I think would require changing the reconciler factory and reconciler lifecycle handling to create it on demand since that's where the actual scheduling happens and I'm not sure it makes sense to push that logic to there. 
I'll take a look again if I can refactor the DBReconciler to have an EMF factory that produces multiple EMFs and then I might be able to query on demand. I just need to figure out the best way to close those EMFs after use and combine the output streams.

2022-11-15 16:33 UTC, driessamyn commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/reconcile/db/GroupParametersReconciler.kt
> +        }
I appreciate it's a bit different, and I'm ok with it if we think this is the best way.
Keep in mind that the difference with the other reconcilers are that they use a connection to the config DB, for which we can cache the EMF because it's re-used in a lot of places.

2022-11-15 17:17 UTC, charlieR3 commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/reconcile/db/GroupParametersReconciler.kt
> +        }
I have pushed an alternative and running tests at the moment. I've had to add a reconciliation info so that we can include some vnode context when creating the versioned records and that allows us to look up the vnode info on demand and have the necessary context in the additional lambda passed in to the db reconciler.

2022-11-16 13:10 UTC, charlieR3 commented
@driessamyn @kyriathar I've refactored again to remove the dependency on the virtual node callback handler. Could you take a look and see if the approach is ok in your opinion?
From talking to @kyriathar it seems like the automated tests at the moment wouldn't pick up on whether this PR broke existing reconciliation behavior so I'm going to try some manual tweaking on the database to double check reconciliation works in these cases.

2022-11-17 17:32 UTC, charlieR3 commented
I have manually verified that the existing reconcilers continue to work as expected by modifying data directly in the database and observing the values returned through the HTTP API change once the reconciliation has ran.

2022-11-18 08:51 UTC, driessamyn requested changes

2022-11-18 08:51 UTC, driessamyn commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/reconcile/db/GroupParametersReconciler.kt
> +                ),
Sorry, @charlieR3, I think this still isn't right because this will create an EMF (and datasource) per VNode and not close it when it's finished.
I think you need a context factory that creates and EMF on demand and closes it (if appropriate, so only for Vnode EMFs) when it's done.

2022-11-18 08:51 UTC, driessamyn commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/reconcile/db/CpiReconciler.kt
> +    dbConnectionManager: DbConnectionManager,
I think needing to make this non-private is a bit of a smell.

2022-11-18 08:51 UTC, driessamyn commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/reconcile/db/DbReconcilerReader.kt
> +                val em = context.emf.createEntityManager()
This is the bit that needs to behave differently depending on the EMF. So it may make more sense to make the Context AutoClosable and delegate the creation of the EM to the Context so that when you close it, the implementation of the Context can decide whether to also close the EMF or not.

2022-11-18 08:51 UTC, driessamyn commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/reconcile/db/GroupParametersReconciler.kt
> +            .singleResult
This I think should be moved out so it can be integration tested, and the query result can simply be mocked out when testing this class.
Building the query is, I think, a different responsibility to Reconciling, and as much as possible we should respect the single responsibility principle.

2022-11-18 08:51 UTC, driessamyn commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/reconcile/db/ReconciliationContext.kt
> +    abstract val emf: EntityManagerFactory
Maybe just a style comment, but this looks a bit odd to me.
What is the benefit of this pattern over just defining a `ReconciliationContex` interface with multiple implementations? 
That would then mean you can unit test things without needing to worry about mocking sealed classes.

2022-11-18 17:31 UTC, charlieR3 commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/reconcile/db/GroupParametersReconciler.kt
> +                ),
The `onStreamClose` callback was previously closing the EMF once the stream closed, but I agree with your latest feedback regardless.

2022-11-18 17:32 UTC, charlieR3 commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/reconcile/db/CpiReconciler.kt
> +    dbConnectionManager: DbConnectionManager,
`dbConnectionManager` is only used during construction (`val` was removed also with `private`) so `dbConnectionManager` won't be accessible outside construction of the class.

2022-11-18 17:33 UTC, charlieR3 commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/reconcile/db/DbReconcilerReader.kt
> +                val em = context.emf.createEntityManager()
Nice suggestion 👍 I've refactored it now so it should be more in line with your feedback.

2022-11-18 17:33 UTC, charlieR3 commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/reconcile/db/GroupParametersReconciler.kt
> +            .singleResult
Good point. I've included that in the latest refactor.

2022-11-18 17:34 UTC, charlieR3 commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/reconcile/db/ReconciliationContext.kt
> +    abstract val emf: EntityManagerFactory
Changed to interface in the latest refactor since I don't think `sealed class` has much of an advantage here over interface.

2022-11-18 17:59 UTC, charlieR3 commented
Manually tested existing 3 reconcilers continue to work after latest refactor.

2022-11-21 11:42 UTC, driessamyn approved these changes
LGTM

2022-11-21 11:42 UTC, driessamyn commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/reconcile/db/ReconciliationContext.kt
> +        entityManager.close()
Really nitpicky here, but if em.close throws and exception, then the emf will never be closed. 
It may not matter in practise.

2022-11-21 11:57 UTC, mcgovc approved these changes
LGTM - build changes

2022-11-21 12:01 UTC, merged