CORE-7089 Distribute group parameters after registration approval
corda/corda-runtime-os pull request #2473
Opened 2022-11-08 16:35 UTC by YashNabar

The MGM now distributes updated membership packages in response to a new `DistributeMembershipPackage` command - this was previously done during registration approval. The new command is issued after registration approval, and the membership packages distributed by the MGM now include the signed group parameters.
https://r3-cev.atlassian.net/browse/CORE-7089

2022-11-10 12:19 UTC, yift-r3 commented on components/membership/membership-p2p/src/main/kotlin/net/corda/membership/p2p/helpers/MembershipPackageFactory.kt
> +        val wireGroupParameters = with(serializer.serialize(groupParameters.toAvro())) {
I would use the `?.let {... } :? throw CordaRuntimeException...` pattern.

2022-11-10 12:19 UTC, yift-r3 commented on components/membership/registration-impl/src/main/kotlin/net/corda/membership/impl/registration/dynamic/handler/mgm/ApproveRegistrationHandler.kt
> +            val newEpoch = memberInfo.notaryDetails
If we are not using the `notaryDetails`, an explicit `if (memberInfo.notaryDetails != null)` will be clearer.

2022-11-10 12:19 UTC, yift-r3 commented on components/membership/registration-impl/src/main/kotlin/net/corda/membership/impl/registration/dynamic/handler/mgm/ApproveRegistrationHandler.kt
> +                ?.run {
why not `let`?

2022-11-10 12:19 UTC, yift-r3 commented on components/membership/registration-impl/src/main/kotlin/net/corda/membership/impl/registration/dynamic/handler/mgm/ApproveRegistrationHandler.kt
> +            val epochForDistribution = if (newEpoch != null) {
Isn't that the same condition from above?

2022-11-10 12:19 UTC, yift-r3 commented on components/membership/synchronisation-impl/src/test/kotlin/net/corda/membership/impl/synchronisation/MgmSynchronisationServiceImplTest.kt
> +        on { groupParameters } doReturn mock()
We need a test to verify that we are using the correct group parameter (or mock the group parameters as private member and replace the `any()`s with that member)

2022-11-10 15:13 UTC, YashNabar commented on components/membership/registration-impl/src/main/kotlin/net/corda/membership/impl/registration/dynamic/handler/mgm/ApproveRegistrationHandler.kt
> +            val epochForDistribution = if (newEpoch != null) {
Fixed in [0c3b61e](https://github.com/corda/corda-runtime-os/pull/2473/commits/0c3b61ef25e0b38cf9ff55cbfd40fa8724491013)

2022-11-10 15:13 UTC, YashNabar commented on components/membership/synchronisation-impl/src/test/kotlin/net/corda/membership/impl/synchronisation/MgmSynchronisationServiceImplTest.kt
> +        on { groupParameters } doReturn mock()
Applied in [a28dd93](https://github.com/corda/corda-runtime-os/pull/2473/commits/a28dd9346c43217b81a818abe7c0c25780038d5b)

2022-11-10 17:01 UTC, charlieR3 commented on components/membership/registration-impl/src/main/kotlin/net/corda/membership/impl/registration/dynamic/handler/mgm/DistributeMembershipPackageHandler.kt
> +            logger.warn("Could not approve registration request: '$registrationId'", e)
I think approval should already be complete at this stage and this handler is only concerned with distributing the membership package. 
It would be better to republish the command to distribute so it retries instead of declining the member.

2022-11-11 09:48 UTC, YashNabar commented on components/membership/registration-impl/src/main/kotlin/net/corda/membership/impl/registration/dynamic/handler/mgm/DistributeMembershipPackageHandler.kt
> +            logger.warn("Could not approve registration request: '$registrationId'", e)
Changed in [0c3b61e](https://github.com/corda/corda-runtime-os/pull/2473/commits/0c3b61ef25e0b38cf9ff55cbfd40fa8724491013)

2022-11-11 10:50 UTC, charlieR3 submitted a review, later dismissed

2022-11-21 09:51 UTC, charlieR3 requested changes
Needs a few changes.

2022-11-21 09:51 UTC, charlieR3 commented on components/membership/membership-p2p/src/test/kotlin/net/corda/membership/p2p/helpers/MembershipPackageFactoryTest.kt
> +        on { mgmSigner.sign(groupParametersBytes) } doReturn signedGroupParameters
Seems strange to configure other mocks in the setup of this mock. I think it's better to mock functions for a class within the setup of that mock. 

e.g. 
```
private val serializer = mock<CordaAvroSerializer<KeyValuePairList>> {
    on { serialize(eq(groupParameters.toAvro())) } doReturn groupParametersBytes
}
private val mgmSigner = mock<Signer> {
    on { sign(eq(groupParametersBytes)) } doReturn signedGroupParameters
}
```

2022-11-21 09:51 UTC, charlieR3 commented on components/membership/registration-impl/src/main/kotlin/net/corda/membership/impl/registration/dynamic/handler/mgm/ApproveRegistrationHandler.kt
> +                val parametersMap = result.getOrThrow().toMap()
Should we be persisting the updated group parameters to kafka at this stage also?

2022-11-21 09:51 UTC, charlieR3 commented on components/membership/registration-impl/src/main/kotlin/net/corda/membership/impl/registration/dynamic/handler/mgm/DistributeMembershipPackageHandler.kt
> +            (members + approvedMemberInfo).forEach {
We should do this once for the MGM when it approves a member who is a notary or when creating the initial snapshot of group parameters. I don't think this should be a concern for distribution and the MGM doesn't need to persist a record for each member as the group has one view on the group parameters.

2022-11-21 09:51 UTC, charlieR3 commented on components/membership/registration-impl/src/main/kotlin/net/corda/membership/impl/registration/dynamic/mgm/MGMRegistrationGroupPolicyHandler.kt
> +        // Publish group parameters to Kafka
Why are we handling group parameters in a group policy handler class?

2022-11-21 09:51 UTC, charlieR3 commented on components/membership/registration-impl/src/test/kotlin/net/corda/membership/impl/registration/dynamic/handler/mgm/ApproveRegistrationHandlerTest.kt
> +        verify(membershipPersistenceClient, times(1)).addNotaryToGroupParameters(
```suggestion
        verify(membershipPersistenceClient).addNotaryToGroupParameters(
```
Default is checking for a single call.

2022-11-21 09:51 UTC, charlieR3 commented on components/membership/registration-impl/src/test/kotlin/net/corda/membership/impl/registration/dynamic/handler/mgm/DistributeMembershipPackageHandlerTest.kt
> +    fun `invoke publishes group parameters to kafka for all members`() {
Highlighted on other areas of this PR but I don't think this should be tested.
1) MGM publishes one record to kafka (it then includes that in the distribution message and each member publishes to their own kafka)
2) Publishing to kafka should not be part of distribution (other than publishing the p2p messages)

2022-11-21 09:51 UTC, charlieR3 commented on components/membership/registration-impl/src/test/kotlin/net/corda/membership/impl/registration/dynamic/mgm/MGMRegistrationServiceTest.kt
> +            verify(writerService, times(1)).put(eq(mgm), groupParametersCaptor.capture())
```suggestion
            verify(writerService).put(eq(mgm), groupParametersCaptor.capture())
```
Once is the default

2022-11-21 12:16 UTC, YashNabar commented on components/membership/registration-impl/src/main/kotlin/net/corda/membership/impl/registration/dynamic/mgm/MGMRegistrationGroupPolicyHandler.kt
> +        // Publish group parameters to Kafka
Group parameters persistence seems to have moved here in a separate story, I'll move both back to `MGMRegistrationService`

2022-11-21 12:17 UTC, charlieR3 commented on components/membership/registration-impl/src/main/kotlin/net/corda/membership/impl/registration/dynamic/mgm/MGMRegistrationGroupPolicyHandler.kt
> +        // Publish group parameters to Kafka
Apologies if I did that - I know I was refactoring in this area some time ago

2022-11-21 14:19 UTC, YashNabar commented on components/membership/registration-impl/src/main/kotlin/net/corda/membership/impl/registration/dynamic/handler/mgm/ApproveRegistrationHandler.kt
> +                val parametersMap = result.getOrThrow().toMap()
Added in [abf5fac](https://github.com/corda/corda-runtime-os/pull/2473/commits/abf5fac7dcaea2edcd933a48599a03ec7248cccf)

2022-11-21 14:19 UTC, YashNabar commented on components/membership/registration-impl/src/main/kotlin/net/corda/membership/impl/registration/dynamic/handler/mgm/DistributeMembershipPackageHandler.kt
> +            (members + approvedMemberInfo).forEach {
Removed in [abf5fac](https://github.com/corda/corda-runtime-os/pull/2473/commits/abf5fac7dcaea2edcd933a48599a03ec7248cccf)

2022-11-21 14:32 UTC, charlieR3 submitted a review, later dismissed

2022-11-21 15:51 UTC, charlieR3 approved these changes

2022-11-21 16:24 UTC, ronanbrowne approved these changes
LGTM (build)

2022-11-21 16:28 UTC, merged