CORE-7943 integration test updates
corda/corda-runtime-os pull request #2505
Opened 2022-11-11 11:31 UTC by vlajos

* CORE-7943 Use sandboxes services
* :testing:sandboxes-testkit with VirtualNodeService(@chrisr3)
*

2022-11-14 08:25 UTC, vlajos commented on libs/crypto/crypto-serialization-impl/src/main/kotlin/net/corda/crypto/impl/serialization/PublicKeySerializer.kt
> +) : BaseDirectSerializer<PublicKey>(), UsedByFlow, UsedByPersistence, UsedByVerification {
I am not too sure if this is needed.
At least somehow the tests passed before this PR too.

2022-11-14 08:53 UTC, chrisr3 commented on libs/crypto/crypto-serialization-impl/src/main/kotlin/net/corda/crypto/impl/serialization/PublicKeySerializer.kt
> +) : BaseDirectSerializer<PublicKey>(), UsedByFlow, UsedByPersistence, UsedByVerification {
These marker interfaces won't do anything for non-PROTOTYPE components. So if `KeyEncodingService` isn't also a `PROTOTYPE` service then you can remove them and allow the sandbox to use this as a platform singleton.

2022-11-14 09:09 UTC, vlajos commented on libs/crypto/crypto-serialization-impl/src/main/kotlin/net/corda/crypto/impl/serialization/PublicKeySerializer.kt
> +) : BaseDirectSerializer<PublicKey>(), UsedByFlow, UsedByPersistence, UsedByVerification {
@chrisr3 
If I revert the changes in `crypto-serialization-impl`, I get this:

`./gradlew :components:ledger:ledger-consensual-flow:integrationTest`

```
# Execution Started: successfully serialize and deserialize a Consensual Signed Transaction() - [engine:bnd-bundle-engine]/[bundle:ledger-consensual-flow-tests;5.0.0.0-SNAPSHOT]/[sub-engine:junit-jupiter]/[class:net.corda.ledger.consensual.flow.impl.transaction.serializer.tests.ConsensualSignedTransactionAMQPSerializationTest]/[method:successfully serialize and deserialize a Consensual Signed Transaction()]
[main] ERROR net.corda.internal.serialization.amqp.SerializationOutput - Serialization failed direction="Serialize", type="java.security.PublicKey", msg="Class "interface java.security.PublicKey" is not annotated with @CordaSerializable.", ClassChain="signatures(java.util.List<net.corda.v5.application.crypto.DigitalSignatureAndMetadata>) -> java.util.List<net.corda.v5.application.crypto.DigitalSignatureAndMetadata> -> java.security.PublicKey"
# Execution Finished: successfully serialize and deserialize a Consensual Signed Transaction() - [engine:bnd-bundle-engine]/[bundle:ledger-consensual-flow-tests;5.0.0.0-SNAPSHOT]/[sub-engine:junit-jupiter]/[class:net.corda.ledger.consensual.flow.impl.transaction.serializer.tests.ConsensualSignedTransactionAMQPSerializationTest]/[method:successfully serialize and deserialize a Consensual Signed Transaction()] - TestExecutionResult [status = FAILED, throwable = java.io.NotSerializableException: Class "interface java.security.PublicKey" is not annotated with @CordaSerializable.]
java.io.NotSerializableException: Class "interface java.security.PublicKey" is not annotated with @CordaSerializable.
        at net.corda.internal.serialization.amqp.SerializationOutput.serialize(SerializationOutput.kt:52)
        at net.corda.ledger.consensual.flow.impl.transaction.serializer.tests.ConsensualSignedTransactionAMQPSerializationTest.successfully serialize and deserialize a Consensual Signed Transaction(ConsensualSignedTransactionAMQPSerializationTest.kt:23)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
...
```

2022-11-14 11:24 UTC, chrisr3 commented on libs/crypto/crypto-serialization-impl/src/main/kotlin/net/corda/crypto/impl/serialization/PublicKeySerializer.kt
> +) : BaseDirectSerializer<PublicKey>(), UsedByFlow, UsedByPersistence, UsedByVerification {
This is odd. The sandboxing code does appear still to _register_ `PublicKeySerializer` with AMQP when it's declared as a platform singleton:
```
[main] INFO net.corda.sandbox.serialization.amqp.AMQPSerializationProvider - Registering internal serializer net.corda.crypto.impl.serialization.PublicKeySerializer (net.corda.crypto.impl.serialization.PublicKeySerializer@18d6ac02)
# Execution Started: successfully serialize and deserialize a Consensual Signed Transaction() - [engine:bnd-bundle-engine]/[bundle:ledger-consensual-flow-tests;5.0.0.0-SNAPSHOT]/[sub-engine:junit-jupiter]/[class:net.corda.ledger.consensual.flow.impl.transaction.serializer.tests.ConsensualSignedTransactionAMQPSerializationTest]/[method:successfully serialize and deserialize a Consensual Signed Transaction()]
[main] ERROR net.corda.internal.serialization.amqp.SerializationOutput - Serialization failed direction="Serialize", type="java.security.PublicKey", msg="Class "interface java.security.PublicKey" is not annotated with @CordaSerializable.", ClassChain="signatures(java.util.List<net.corda.v5.application.crypto.DigitalSignatureAndMetadata>) -> java.util.List<net.corda.v5.application.crypto.DigitalSignatureAndMetadata> -> java.security.PublicKey"
```

2022-11-14 11:49 UTC, chrisr3 requested changes, later dismissed
A few things, but mainly I think `PublicKeySerilalizer` should still be a platform service. And the `ConsensualSignedTransactionAMQPSerializationTest` should test the AMQP serializer that exists in the `SandboxGroupContext` rather than creating its own.

2022-11-14 11:49 UTC, chrisr3 commented on testing/ledger/ledger-consensual-testkit/src/main/kotlin/net/corda/ledger/consensual/testkit/ConsensualLedgerIntegrationTest.kt
> +        )
This should be
```kotlin
consensualSignedTransaction = consensualSignedTransactionFactory.createExample(
    jsonMarshallingService,
    wireTransactionFactory
)
```
because it's an extension function and so doesn't need to pass itself as another parameter.

2022-11-14 11:49 UTC, chrisr3 commented on testing/ledger/ledger-consensual-testkit/src/main/kotlin/net/corda/ledger/consensual/testkit/ConsensualSignedTransactionExample.kt
> +    consensualSignedTransactionFactory: ConsensualSignedTransactionFactory
You can remove this parameter because it's an extension function.

2022-11-14 11:49 UTC, chrisr3 commented on testing/ledger/ledger-consensual-testkit/src/main/kotlin/net/corda/ledger/consensual/testkit/ConsensualSignedTransactionExample.kt
> +    return consensualSignedTransactionFactory.create(wireTransaction, listOf(signatureWithMetadataExample))
Then this becomes
```kotlin
return create(wireTransaction, listOf(signatureWithMetadataExample))
```

2022-11-14 11:49 UTC, chrisr3 commented on testing/ledger/ledger-common-base-integrationtest/src/main/kotlin/net/corda/ledger/common/integrationtest/CommonLedgerIntegrationTest.kt
> +            ?: org.junit.jupiter.api.fail("No CheckpointSerializer in sandbox context")
I think you can `import` the `fail` function.

2022-11-14 11:49 UTC, chrisr3 commented on testing/ledger/ledger-common-base-integrationtest/src/main/kotlin/net/corda/ledger/common/integrationtest/CommonLedgerIntegrationTest.kt
> +        }
I don't think you _ever_ want this function because the `SerializerFactory` it creates doesn't contain any platform serializers.... :thinking:

2022-11-14 11:55 UTC, chrisr3 commented on libs/crypto/crypto-serialization-impl/src/main/kotlin/net/corda/crypto/impl/serialization/PublicKeySerializer.kt
> +) : BaseDirectSerializer<PublicKey>(), UsedByFlow, UsedByPersistence, UsedByVerification {
You don't need to do this. Your test is almost certainly failing because you're not testing the SerializationService` that the `AMQPSerializationProvider` creates:
```kotlin
context.putObjectByKey(AMQP_SERIALIZATION_SERVICE, serializationService)
```

2022-11-14 11:56 UTC, chrisr3 commented on libs/crypto/crypto-serialization-impl/build.gradle
> +    implementation project(':libs:sandbox-types')
You don't need this dependency.

2022-11-14 14:36 UTC, vlajos commented on testing/ledger/ledger-consensual-testkit/src/main/kotlin/net/corda/ledger/consensual/testkit/ConsensualLedgerIntegrationTest.kt
> +        )
Thanks.I have updated this.

2022-11-14 14:36 UTC, vlajos commented on testing/ledger/ledger-consensual-testkit/src/main/kotlin/net/corda/ledger/consensual/testkit/ConsensualSignedTransactionExample.kt
> +    consensualSignedTransactionFactory: ConsensualSignedTransactionFactory
Removed.

2022-11-14 14:37 UTC, vlajos commented on testing/ledger/ledger-consensual-testkit/src/main/kotlin/net/corda/ledger/consensual/testkit/ConsensualSignedTransactionExample.kt
> +    return consensualSignedTransactionFactory.create(wireTransaction, listOf(signatureWithMetadataExample))
Thanks. I have updated this.

2022-11-14 14:37 UTC, vlajos commented on testing/ledger/ledger-common-base-integrationtest/src/main/kotlin/net/corda/ledger/common/integrationtest/CommonLedgerIntegrationTest.kt
> +            ?: org.junit.jupiter.api.fail("No CheckpointSerializer in sandbox context")
Updated.

2022-11-14 14:39 UTC, vlajos commented on testing/ledger/ledger-common-base-integrationtest/src/main/kotlin/net/corda/ledger/common/integrationtest/CommonLedgerIntegrationTest.kt
> +        }
Its consensual/utxo child classes use that.

2022-11-14 15:03 UTC, vlajos commented on libs/crypto/crypto-serialization-impl/src/main/kotlin/net/corda/crypto/impl/serialization/PublicKeySerializer.kt
> +) : BaseDirectSerializer<PublicKey>(), UsedByFlow, UsedByPersistence, UsedByVerification {
@chrisr3 
Thanks. This seems to be correct.
At least if I revert the PublicKeySerializer changes, but use the serializationservice from the sandbox like this:
```
    override fun initialize(setup: SandboxSetup){
        super.initialize(setup)

        sandboxSerializationService = sandboxGroupContext.getObjectByKey(AMQP_SERIALIZATION_SERVICE)
            ?: fail("No Serializer in sandbox context")

    }

    @Test
    @Suppress("FunctionName")
    fun `successfully serialize and deserialize a Consensual Signed Transaction - via sandbox serializer`() {
        val serialised = sandboxSerializationService.serialize(consensualSignedTransaction)

        // Perform deserialization and check if the correct class is deserialized
        val deserialized =
            sandboxSerializationService.deserialize(serialised)

        assertThat(deserialized.javaClass.name)
            .isEqualTo("net.corda.ledger.consensual.flow.impl.transaction.ConsensualSignedTransactionImpl")

        assertThat(deserialized)
            .isInstanceOf(ConsensualSignedTransaction::class.java)
            .isEqualTo(consensualSignedTransaction)

        assertDoesNotThrow {
            deserialized.id
        }
        assertThat(deserialized.id).isEqualTo(consensualSignedTransaction.id)
    }
```


That one can serialize and deserialize properly.

Then only one problem is left:
In the original serialization example:
https://github.com/corda/corda-runtime-os/blob/release/os/5.0/libs/serialization/serialization-amqp/src/integrationTest/kotlin/net/corda/serialization/amqp/test/AMQPwithOSGiSerializationTests.kt#L86
They used intentionally two SerializationFactories to rule out the possibility of caching.
So I need two sandbox serializers.
Is it OK if create two sandboxes and their serializers?
Can those overlap anyhow?

2022-11-14 15:22 UTC, vlajos commented on testing/ledger/ledger-common-base-integrationtest/src/main/kotlin/net/corda/ledger/common/integrationtest/CommonLedgerIntegrationTest.kt
> +        }
Actually these are not needed at all with the sandbox services.

2022-11-14 19:33 UTC, chrisr3 reviewed
A few small comments.

2022-11-14 19:33 UTC, chrisr3 commented on testing/ledger/ledger-common-base-integration-test/src/main/kotlin/net/corda/ledger/common/integration/test/CommonLedgerIntegrationTest.kt
> +        setup.withCleanup { virtualNode2.unloadSandbox(sandboxGroupContext2) }
Do you need both sandboxes? There is a risk that you will accidentally use (say) the `JsonMarshallerService` from `sandboxGroupContext1` with something from `sandboxGroupContext2`.

2022-11-14 19:33 UTC, chrisr3 commented on testing/ledger/ledger-utxo-testkit/src/main/kotlin/net/corda/ledger/utxo/testkit/UtxoStateClassExample.kt
> +                other.participants.containsAll(participants)
I think the operator precedence is OK here, but a few brackets wouldn't hurt readability either.

2022-11-14 19:33 UTC, chrisr3 commented on testing/ledger/ledger-utxo-state-app/src/main/kotlin/net/cordapp/testing/ledger/utxo/TestUtxoState.kt
> +                other.participants.containsAll(participants)
A few brackets here would help readability. (General comment applying to all other cases too.)

2022-11-14 19:42 UTC, vlajos commented on testing/ledger/ledger-common-base-integration-test/src/main/kotlin/net/corda/ledger/common/integration/test/CommonLedgerIntegrationTest.kt
> +        setup.withCleanup { virtualNode2.unloadSandbox(sandboxGroupContext2) }
A bit more details: https://github.com/corda/corda-runtime-os/pull/2505#discussion_r1021652875
In a nutshell, I could not figure out a better way to have two different serializationservices.
(Which seemed to be useful for serialization tests, based on the original examples.)

To restrict the visibility of the second sandbox, it is not really visible outside that setup function. (apart from its serializationservice.)

2022-11-14 19:47 UTC, vlajos commented on testing/ledger/ledger-utxo-testkit/src/main/kotlin/net/corda/ledger/utxo/testkit/UtxoStateClassExample.kt
> +                other.participants.containsAll(participants)
I have updated these.

2022-11-14 19:48 UTC, chrisr3 commented on testing/ledger/ledger-common-base-integration-test/src/main/kotlin/net/corda/ledger/common/integration/test/CommonLedgerIntegrationTest.kt
> +        setup.withCleanup { virtualNode2.unloadSandbox(sandboxGroupContext2) }
Every `SandboxGroupContext` should contain an instance of `SerializationService` under the key "AMQP_SERIALIZER", which is the value of `RequireSandboxAMQP.AMQP_SERIALIZATION_SERVICE`.

The `AMQPSerializationProvider` should create this for you automatically.

2022-11-14 19:51 UTC, vlajos commented on testing/ledger/ledger-common-base-integration-test/src/main/kotlin/net/corda/ledger/common/integration/test/CommonLedgerIntegrationTest.kt
> +        setup.withCleanup { virtualNode2.unloadSandbox(sandboxGroupContext2) }
Yes. That looks like working fine.
In the original serialization examples what I have found: https://github.com/corda/corda-runtime-os/blob/release/os/5.0/libs/serialization/serialization-amqp/src/integrationTest/kotlin/net/corda/serialization/amqp/test/AMQPwithOSGiSerializationTests.kt#L86
It seemed that ideally we should serialize with one instance and deserialize with another to avoid potential caching.
That is what I am trying to achieve with the two sandboxes/two serializers.

2022-11-15 09:39 UTC, chrisr3 reviewed
LGTM, but I'll leave the final approval to the ledger team.

2022-11-15 10:42 UTC, lankydan approved these changes

2022-11-15 10:45 UTC, ronanbrowne approved these changes
LGTM (build)

2022-11-15 10:46 UTC, merged