CORE-4734 Add smoke and unit tests for non-validating plugin
corda/corda-runtime-os pull request #2511
Opened 2022-11-11 14:47 UTC by nkovacsx

## Overview
- Added some error handling to non-validating plugin client-server: The server will never throw an exception, just return the error back to the client. Will throw `InternalNotaryException` in several cases but that'll be caught internally and an error response will be returned to the client.
- Added unit tests for both the client and server
- Added smoke test for two scenarios: Valid request, invalid time window request
- API/Client/Server modules' structure has been reworked to satisfy OSGi (build.gradle, packages)
- Made the data that is transported between client<->server serializable (`@CordaSerializable`)

## TODOs
- Unfortunately the Ledger still limits us to create the following test cases: Double spend (ref, input), Unknown state (ref, input). Please see https://r3-cev.atlassian.net/browse/CORE-7939 for more details/follow-up.
- For now, I couldn't include the `common` module with `cordaEmbedded`. It was throwing erros when packaging. This needs further investigation. For now, it is defined as a CorDapp but this is only a temporary solution. Please refer to https://r3-cev.atlassian.net/browse/CORE-7945 for more details.
- With https://r3-cev.atlassian.net/browse/CORE-7939 the flow `net.cordapp.testing.testflows.NonValidatingNotaryTestFlow` will be extended to accept state refs through HTTP RPC call, this will make our life easier when testing unknown states for example. That part of the code is not committed because it's not used anywhere.

2022-11-14 11:53 UTC, relyafi requested changes

2022-11-14 11:53 UTC, relyafi commented on processors/flow-processor/build.gradle
> +    implementation project(":notary-plugins:notary-plugin-common")
Out of order with respect to other includes

2022-11-14 11:53 UTC, relyafi commented on testing/cpbs/test-cordapp/src/main/kotlin/net/cordapp/testing/testflows/NonValidatingNotaryTestFlow.kt
> +        const val DUMMY_TX_ID = "SHA-256:CDFF8A944383063AB86AFE61488208CCCC84149911F85BE4F0CACCF399CA9903"
Can't we use `SecureHashUtils.randomSecureHash()` instead?

2022-11-14 11:53 UTC, relyafi commented on testing/cpbs/test-cordapp/src/main/kotlin/net/cordapp/testing/testflows/NonValidatingNotaryTestFlow.kt
> +            }
This doesn't look right, because this field is optional. If this is due to Ledger limitations requiring the lower bound, this should be commented as a TODO.

2022-11-14 11:53 UTC, relyafi commented on testing/cpbs/test-cordapp/src/main/kotlin/net/cordapp/testing/testflows/NonValidatingNotaryTestFlow.kt
> +        val myKey = myInfo.sessionInitiationKey
Unnecessary variable; this is only used once later on.

2022-11-14 11:53 UTC, relyafi commented on testing/cpbs/test-cordapp/src/main/kotlin/net/cordapp/testing/testflows/NonValidatingNotaryTestFlow.kt
> +        }
This seems fragile, and possibly wrong. How do we know that this will always return a notary member? And even if it did, crucially, it is returning a member, not a service - shouldn't we be looking up a notary service, using the dedicated MGM API for this?

2022-11-14 11:53 UTC, relyafi commented on testing/cpbs/test-cordapp/src/main/kotlin/net/cordapp/testing/testflows/NonValidatingNotaryTestFlow.kt
> +            .addReferenceInputState(generateStateAndRef(DUMMY_TX_ID, 0, notaryParty))
It's not a realistic test case to use the same tx id for both of these.

2022-11-14 11:53 UTC, relyafi commented on testing/cpbs/test-cordapp/src/main/kotlin/net/cordapp/testing/testflows/NonValidatingNotaryTestFlow.kt
> +            .addOutputState(TestContract.TestState(emptyList()))
The ordering of these calls seem a bit arbitrary. I'd group this with the other "state" operations for readability.

2022-11-14 11:53 UTC, relyafi commented on testing/cpbs/test-cordapp/src/main/kotlin/net/cordapp/testing/testflows/NonValidatingNotaryTestFlow.kt
> + *  we'll need to ISSUE states first before we can CONSUME them.
Regardless of this, we need a real KDoc comment explaining what this flow does and how to use it.

2022-11-14 11:53 UTC, relyafi commented on testing/cpbs/test-cordapp/src/main/kotlin/net/cordapp/testing/testflows/NonValidatingNotaryTestFlow.kt
> +        return "Received ${sigs.size} signatures from the uniqueness checker, notary plugin ran successfully."
I'm not sure how useful this message is, given we will always return one signature if it gets this far. More importantly, what happens if an exception is thrown? This isn't being handled by this flow at all.

Also, on a separate note, I can see that the client plugin isn't actually validating the signature returned from the server plugin, should we be doing this?

Finally, there is no signature from the uniqueness checker - it's the plugin doing the signing, so it's the notary that has signed.

2022-11-14 11:53 UTC, relyafi commented on testing/cpbs/test-cordapp/src/main/kotlin/net/cordapp/testing/testflows/NonValidatingNotaryTestFlow.kt
> +    }
This has been duplicated from two test classes in Ledger, however there is already a `ledger-utxo-testkit` module that may provide what we need. Have you considered using `UtxoContractExample`, and if this doesn't work, maybe it needs modifying, or adding this as an alternative in this module.

2022-11-14 11:53 UTC, relyafi commented on testing/cpbs/test-cordapp/src/main/kotlin/net/cordapp/testing/testflows/NonValidatingNotaryTestFlow.kt
> +    class TestCommand : Command
Similarly, can we  use `UtxoCommandExample`?

2022-11-14 11:53 UTC, relyafi commented on testing/cpbs/test-cordapp/build.gradle
> +    cordapp project(':notary-plugins:notary-plugin-non-validating:notary-plugin-non-validating-server')
Why is this required, given the test flow is only invoking the client flow? Is this because on a test network, we are currently installing the same CPI on all nodes?

2022-11-14 11:53 UTC, relyafi commented on notary-plugins/notary-plugin-non-validating/notary-plugin-non-validating-server/src/main/kotlin/com/r3/corda/notary/plugin/nonvalidating/server/NonValidatingNotaryServerFlowImpl.kt
> +// TODO CORE-7249 Remove `open` qualifier when we have an actual logic
I don't really understand this comment - I think there needs to be more detail explaining the problem this solves.

2022-11-14 11:53 UTC, relyafi commented on notary-plugins/notary-plugin-non-validating/notary-plugin-non-validating-server/src/main/kotlin/com/r3/corda/notary/plugin/nonvalidating/server/NonValidatingNotaryServerFlowImpl.kt
> +    internal lateinit var clientService: LedgerUniquenessCheckerClientService
Similarly, there's no explanation for the bulk change from `private` to `internal`.

2022-11-14 11:53 UTC, relyafi commented on notary-plugins/notary-plugin-non-validating/notary-plugin-non-validating-server/src/main/kotlin/com/r3/corda/notary/plugin/nonvalidating/server/NonValidatingNotaryServerFlowImpl.kt
> +    // TODO CORE-7249 Remove `open` qualifier when we have an actual logic
Again, no explanation provided

2022-11-14 11:53 UTC, relyafi commented on notary-plugins/notary-plugin-non-validating/notary-plugin-non-validating-server/src/main/kotlin/com/r3/corda/notary/plugin/nonvalidating/server/NonValidatingNotaryServerFlowImpl.kt
> +            logger.debug { "Cause: $e" }
I think there's a couple of issues around this logging:

- Raising an error breaks the documented [logging level conventions](https://r3-cev.atlassian.net/wiki/spaces/CB/pages/4169859082/C5+Logging+goals#Logging-Levels). This is not a fatal error for the processor / worker, so we should be using `warn`
- Placing the cause on a separate more granular logging level is a nice idea, but will probably confuse any logging monitors that will be processing JSON messages, as this will lead to two totally separate messages for the same event. I'd say keep it simple and just put the cause in the first message - these should be relatively rare anyway, and the first line isn't very useful without further information.

2022-11-14 11:53 UTC, relyafi commented on notary-plugins/notary-plugin-non-validating/notary-plugin-non-validating-server/src/main/kotlin/com/r3/corda/notary/plugin/nonvalidating/server/NonValidatingNotaryServerFlowImpl.kt
> +            ))
Given this branch, I don't really see the value in a dedicated `InternalNotaryException` class, given this isn't being sent back to the client anyway. We could use a standard exception and just always pass through the exact exception details.

2022-11-14 11:53 UTC, relyafi commented on notary-plugins/notary-plugin-non-validating/notary-plugin-non-validating-server/src/test/kotlin/com/r3/corda/notary/plugin/nonvalidating/server/NonValidatingNotaryServerFlowImplTest.kt
> +        val bobKey = mock<PublicKey>()
These aren't used anywhere other than in the memberInfo objects, so why not inline them?

2022-11-14 11:53 UTC, relyafi commented on notary-plugins/notary-plugin-non-validating/notary-plugin-non-validating-server/src/test/kotlin/com/r3/corda/notary/plugin/nonvalidating/server/NonValidatingNotaryServerFlowImplTest.kt
> +        }
We don't actually use bob anywhere in the tests?

2022-11-14 11:53 UTC, relyafi commented on notary-plugins/notary-plugin-non-validating/notary-plugin-non-validating-server/src/test/kotlin/com/r3/corda/notary/plugin/nonvalidating/server/NonValidatingNotaryServerFlowImplTest.kt
> +        val uniquenessResponseDigitalSignature = mock<DigitalSignature.WithKey>()
Again I'd consider inlining the one-time use in the next object - this is part of the reason why we have 100+ lines of val setup.

2022-11-14 11:53 UTC, relyafi commented on notary-plugins/notary-plugin-non-validating/notary-plugin-non-validating-server/src/test/kotlin/com/r3/corda/notary/plugin/nonvalidating/server/NonValidatingNotaryServerFlowImplTest.kt
> +        )
Ok, it looks like there's lots of instances like this of explicit declarations of one-time use vals. Please review all of these vals and make sure we've reduced them to only what we need (without compromising readability too much).

2022-11-14 11:53 UTC, relyafi commented on notary-plugins/notary-plugin-non-validating/notary-plugin-non-validating-server/src/test/kotlin/com/r3/corda/notary/plugin/nonvalidating/server/NonValidatingNotaryServerFlowImplTest.kt
> +            on { serialize(any()) } doReturn SerializedBytes("ABC".toByteArray())
This seems over-trivial - if this is invoked, isn't this going to return fundamentally wrong data?

2022-11-14 11:53 UTC, relyafi commented on notary-plugins/notary-plugin-non-validating/notary-plugin-non-validating-server/src/test/kotlin/com/r3/corda/notary/plugin/nonvalidating/server/NonValidatingNotaryServerFlowImplTest.kt
> +class NonValidatingNotaryServerFlowImplTest {
```suggestion
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
class NonValidatingNotaryServerFlowImplTest {
```

If this works for the use case here, this should speed up the test runs: https://phauer.com/2018/best-practices-unit-testing-kotlin/#avoid-static-and-reuse-the-test-class-instance

2022-11-14 11:53 UTC, relyafi commented on notary-plugins/notary-plugin-non-validating/notary-plugin-non-validating-server/src/test/kotlin/com/r3/corda/notary/plugin/nonvalidating/server/NonValidatingNotaryServerFlowImplTest.kt
> +            it.signatureVerifier = mockSigVerifierError
Generally these tests are only changing at most 2 of these arguments, and generally it's 0 or 1. This is a candidate for extraction into a function with default arguments. Even more elegant might be to have a function that takes a Lambda so you can abstract the standard boilerplate setup and checking (e.g. we always do `server.call` and assert a single response).

2022-11-14 11:53 UTC, relyafi commented on notary-plugins/notary-plugin-non-validating/notary-plugin-non-validating-server/build.gradle
> +    testImplementation project(":libs:uniqueness:common")
Ordering

2022-11-14 11:53 UTC, relyafi commented on notary-plugins/notary-plugin-non-validating/notary-plugin-non-validating-client/src/main/kotlin/com/r3/corda/notary/plugin/nonvalidating/client/NonValidatingNotaryClientFlowImpl.kt
> +    internal lateinit var flowMessaging: FlowMessaging
Why did we change from `private` to `internal`?

2022-11-14 11:53 UTC, relyafi commented on notary-plugins/notary-plugin-non-validating/notary-plugin-non-validating-client/src/main/kotlin/com/r3/corda/notary/plugin/nonvalidating/client/NonValidatingNotaryClientFlowImpl.kt
>          return notarisationResponse.error?.let {
Not new to this PR - but shouldn't we be checking the notary signature on receiving a response?

2022-11-14 11:53 UTC, relyafi commented on notary-plugins/notary-plugin-non-validating/notary-plugin-non-validating-client/src/test/kotlin/com/r3/corda/notary/plugin/nonvalidating/client/NonValidatingNotaryClientFlowImplTest.kt
> +        val dummyX500Name = MemberX500Name("Alice", "Alice Corp", "LDN", "GB")
In this case, this is the notary service right? In which case, shouldn't we reflect this in the name, and also actually be specifying a service, not a member?

2022-11-14 11:53 UTC, relyafi commented on notary-plugins/notary-plugin-non-validating/notary-plugin-non-validating-client/src/test/kotlin/com/r3/corda/notary/plugin/nonvalidating/client/NonValidatingNotaryClientFlowImplTest.kt
> +        val dummyStateRef = StateRef(SecureHashUtils.randomSecureHash(), 0)
As with the server tests, I'd suggest a self-review to check if all of these need to be explicitly defined.

2022-11-14 11:53 UTC, relyafi commented on notary-plugins/notary-plugin-non-validating/notary-plugin-non-validating-client/src/test/kotlin/com/r3/corda/notary/plugin/nonvalidating/client/NonValidatingNotaryClientFlowImplTest.kt
> +            on { serialize(any()) } doReturn SerializedBytes("ABC".toByteArray())
Same concerns with this as the server tests

2022-11-14 11:53 UTC, relyafi commented on notary-plugins/notary-plugin-non-validating/notary-plugin-non-validating-client/src/test/kotlin/com/r3/corda/notary/plugin/nonvalidating/client/NonValidatingNotaryClientFlowImplTest.kt
> +        assertThat(signatures).isNotNull
Aren't these redundant, as they should be covered by `containsExactly`?

2022-11-14 11:53 UTC, relyafi commented on notary-plugins/notary-plugin-non-validating/notary-plugin-non-validating-client/src/test/kotlin/com/r3/corda/notary/plugin/nonvalidating/client/NonValidatingNotaryClientFlowImplTest.kt
> +        assertThat(payload.requestSignature.platformVersion).isEqualTo(DUMMY_PLATFORM_VERSION)
These should probably be wrapped in `assertAll` so they can be checked in parallel, rather than stopping on the first failure.

2022-11-14 11:53 UTC, relyafi commented on notary-plugins/notary-plugin-non-validating/notary-plugin-non-validating-client/src/test/kotlin/com/r3/corda/notary/plugin/nonvalidating/client/NonValidatingNotaryClientFlowImplTest.kt
> +            it.signingService = mockSigningService
As with the server tests - consider a helper function to buld the flow, or a function that takes a code block to execute the actual test code.

2022-11-14 11:53 UTC, relyafi commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/flow/FlowTests.kt
> +                    )
I think this test case is wrong - shouldn't one of these be in the `inputStates` list? It'd be perfectly ok (if odd) to use the same reference state twice as long as it wasn't spent / being spent.

2022-11-14 11:53 UTC, relyafi commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/flow/FlowTests.kt
> +    //  finalised.
Specifically, to actually do something, like create a state?

Probably also want another test case to spend a state.

2022-11-14 14:22 UTC, nkovacsx commented on testing/cpbs/test-cordapp/src/main/kotlin/net/cordapp/testing/testflows/NonValidatingNotaryTestFlow.kt
> +        const val DUMMY_TX_ID = "SHA-256:CDFF8A944383063AB86AFE61488208CCCC84149911F85BE4F0CACCF399CA9903"
Yeah good point

2022-11-14 14:27 UTC, nkovacsx commented on testing/cpbs/test-cordapp/src/main/kotlin/net/cordapp/testing/testflows/NonValidatingNotaryTestFlow.kt
> +            }
Well, the transaction builder has two function calls:
`setTimeWindowBetween` and `setTimeWindowUntil`. 
If I don't use a default here, it means I need to add an extra `if-else` branch to decide which one to call. That seems less nice to me but if you think that's better I'm happy to change it.

2022-11-14 14:30 UTC, nkovacsx commented on testing/cpbs/test-cordapp/src/main/kotlin/net/cordapp/testing/testflows/NonValidatingNotaryTestFlow.kt
> +        }
Yeah that's a good point, I'm not entirely sure what state that service is in but will give it a try.

2022-11-14 14:32 UTC, nkovacsx commented on testing/cpbs/test-cordapp/src/main/kotlin/net/cordapp/testing/testflows/NonValidatingNotaryTestFlow.kt
> +            .addReferenceInputState(generateStateAndRef(DUMMY_TX_ID, 0, notaryParty))
I'm happy to change it if you prefer that but I don't see much value in there. When the ledger is finished we'll need to rework the issuance/spending part anyway. Currently, we don't have any checks because of the unfinished ledger, and as the comment on the class level says:
```
After the ledger is in a better state we'll need to ISSUE states first before we can CONSUME them.
```

2022-11-14 14:44 UTC, nkovacsx commented on testing/cpbs/test-cordapp/src/main/kotlin/net/cordapp/testing/testflows/NonValidatingNotaryTestFlow.kt
> +        return "Received ${sigs.size} signatures from the uniqueness checker, notary plugin ran successfully."
Why do you think this flow should handle exceptions? If there's an exception thrown on the client side, it will be escalated to this flow, then to the test. That way we can use `assertThrows` in the test call, or if it's called via HTTP the exception thrown will be wrapped in the HTTP response.

2022-11-14 14:46 UTC, nkovacsx commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/flow/FlowTests.kt
> +                    )
Hmm, that's a good point, this will just trigger the idempotency logic.

2022-11-14 14:51 UTC, nkovacsx commented on testing/cpbs/test-cordapp/src/main/kotlin/net/cordapp/testing/testflows/NonValidatingNotaryTestFlow.kt
> +    }
Same as before, since this flow is in a simulated "external" CPB I would rather not use any internal dependencies.

2022-11-14 14:51 UTC, nkovacsx commented on testing/cpbs/test-cordapp/src/main/kotlin/net/cordapp/testing/testflows/NonValidatingNotaryTestFlow.kt
> +    class TestCommand : Command
Same as before, since this flow is in a simulated "external" CPB I would rather not use any internal dependencies.

2022-11-14 14:51 UTC, nkovacsx commented on testing/cpbs/test-cordapp/build.gradle
> +    cordapp project(':notary-plugins:notary-plugin-non-validating:notary-plugin-non-validating-server')
Yes, unfortunately both client and server CPKs will be installed on all nodes.

2022-11-14 14:54 UTC, nkovacsx commented on notary-plugins/notary-plugin-non-validating/notary-plugin-non-validating-server/src/main/kotlin/com/r3/corda/notary/plugin/nonvalidating/server/NonValidatingNotaryServerFlowImpl.kt
> +    internal lateinit var clientService: LedgerUniquenessCheckerClientService
Do you have any idea how else we could instantiate this class in a test if these properties are private? Maybe an internal constructor?

2022-11-14 14:56 UTC, nkovacsx commented on notary-plugins/notary-plugin-non-validating/notary-plugin-non-validating-server/src/main/kotlin/com/r3/corda/notary/plugin/nonvalidating/server/NonValidatingNotaryServerFlowImpl.kt
> +    // TODO CORE-7249 Remove `open` qualifier when we have an actual logic
Mockito needs this function to be open, in order to mock it via spy. Once we have the logic we won't need to mock it anymore.

2022-11-14 14:56 UTC, nkovacsx commented on notary-plugins/notary-plugin-non-validating/notary-plugin-non-validating-server/src/main/kotlin/com/r3/corda/notary/plugin/nonvalidating/server/NonValidatingNotaryServerFlowImpl.kt
> +// TODO CORE-7249 Remove `open` qualifier when we have an actual logic
Mockito needs this class to be open, in order to spy it. Once we have the logic we won't need to spy it anymore.

2022-11-14 14:59 UTC, nkovacsx commented on notary-plugins/notary-plugin-non-validating/notary-plugin-non-validating-server/src/main/kotlin/com/r3/corda/notary/plugin/nonvalidating/server/NonValidatingNotaryServerFlowImpl.kt
> +            ))
Hmm, that's a good point actually.

2022-11-14 15:17 UTC, nkovacsx commented on notary-plugins/notary-plugin-non-validating/notary-plugin-non-validating-server/src/test/kotlin/com/r3/corda/notary/plugin/nonvalidating/server/NonValidatingNotaryServerFlowImplTest.kt
> +        val bobKey = mock<PublicKey>()
`aliceKey` is used in the request signature, `bobKey` can be inlined though.

2022-11-14 15:18 UTC, nkovacsx commented on notary-plugins/notary-plugin-non-validating/notary-plugin-non-validating-server/src/test/kotlin/com/r3/corda/notary/plugin/nonvalidating/server/NonValidatingNotaryServerFlowImplTest.kt
> +        }
I'm not entirely sure what you mean. These will be used in the client flow, since Bob is the initiator.

2022-11-14 15:41 UTC, nkovacsx commented on notary-plugins/notary-plugin-non-validating/notary-plugin-non-validating-server/src/test/kotlin/com/r3/corda/notary/plugin/nonvalidating/server/NonValidatingNotaryServerFlowImplTest.kt
> +            on { serialize(any()) } doReturn SerializedBytes("ABC".toByteArray())
Doesn't matter since it is only used here:
```
signatureVerifier.verify(
            digitalSignature.by,
            SignatureSpec.ECDSA_SHA256, // TODO This shouldn't be hardcoded?
            digitalSignature.bytes,
            expectedSignedBytes
        )
```
and this will be mocked anyway.

2022-11-14 15:48 UTC, nkovacsx commented on notary-plugins/notary-plugin-non-validating/notary-plugin-non-validating-server/src/test/kotlin/com/r3/corda/notary/plugin/nonvalidating/server/NonValidatingNotaryServerFlowImplTest.kt
> +            it.signatureVerifier = mockSigVerifierError
Good idea, thanks!

2022-11-14 15:53 UTC, nkovacsx commented on notary-plugins/notary-plugin-non-validating/notary-plugin-non-validating-client/src/main/kotlin/com/r3/corda/notary/plugin/nonvalidating/client/NonValidatingNotaryClientFlowImpl.kt
> +    internal lateinit var flowMessaging: FlowMessaging
Do you have any idea how else we could instantiate this class in a test if these properties are private? Maybe an internal constructor?

2022-11-14 16:04 UTC, nkovacsx commented on notary-plugins/notary-plugin-non-validating/notary-plugin-non-validating-client/src/test/kotlin/com/r3/corda/notary/plugin/nonvalidating/client/NonValidatingNotaryClientFlowImplTest.kt
> +        val dummyX500Name = MemberX500Name("Alice", "Alice Corp", "LDN", "GB")
Worker selection will happen **before** the plugin instantiation if I'm not wrong.

2022-11-14 16:14 UTC, nkovacsx commented on notary-plugins/notary-plugin-non-validating/notary-plugin-non-validating-client/src/test/kotlin/com/r3/corda/notary/plugin/nonvalidating/client/NonValidatingNotaryClientFlowImplTest.kt
> +            on { serialize(any()) } doReturn SerializedBytes("ABC".toByteArray())
Similarly to the server, the serialization is only used here:
```
val signature = signingService.sign(
        serializedRequest,
        myLegalIdentity,
        SignatureSpec.ECDSA_SHA256
    )
```
and this will be mocked anyway.

2022-11-14 16:15 UTC, nkovacsx commented on notary-plugins/notary-plugin-non-validating/notary-plugin-non-validating-client/src/test/kotlin/com/r3/corda/notary/plugin/nonvalidating/client/NonValidatingNotaryClientFlowImplTest.kt
> +        assertThat(signatures).isNotNull
Good point!

2022-11-14 16:24 UTC, relyafi commented on testing/cpbs/test-cordapp/src/main/kotlin/net/cordapp/testing/testflows/NonValidatingNotaryTestFlow.kt
> +            }
I think we should change it - I suspect an absent lower bound will be the common case in real world usage, and the change as it stands prevents testing this scenario.

2022-11-14 16:24 UTC, relyafi commented on testing/cpbs/test-cordapp/src/main/kotlin/net/cordapp/testing/testflows/NonValidatingNotaryTestFlow.kt
> +        const val DUMMY_TX_ID = "SHA-256:CDFF8A944383063AB86AFE61488208CCCC84149911F85BE4F0CACCF399CA9903"
Fair point.

2022-11-14 16:26 UTC, relyafi commented on testing/cpbs/test-cordapp/src/main/kotlin/net/cordapp/testing/testflows/NonValidatingNotaryTestFlow.kt
> +            .addReferenceInputState(generateStateAndRef(DUMMY_TX_ID, 0, notaryParty))
I think it's generally good practice to make test cases reflect real world usage where possible. I take the point re. there's more work to be done, but I don't really see how that impacts getting this bit correct now?

2022-11-14 16:28 UTC, relyafi commented on testing/cpbs/test-cordapp/src/main/kotlin/net/cordapp/testing/testflows/NonValidatingNotaryTestFlow.kt
> +        return "Received ${sigs.size} signatures from the uniqueness checker, notary plugin ran successfully."
Ok, fair point re. the exception handling - I was thinking that a real CorDapp should handle this gracefully rather than having the flow blow up, but you're right in the context of a test CorDapp.

2022-11-14 16:29 UTC, relyafi commented on testing/cpbs/test-cordapp/src/main/kotlin/net/cordapp/testing/testflows/NonValidatingNotaryTestFlow.kt
> +    }
Ok - I think it's maybe worth commenting on these classes that's the reasoning then so in future no one accidentally undoes this and introduces the dependency.

2022-11-14 16:29 UTC, relyafi commented on testing/cpbs/test-cordapp/build.gradle
> +    cordapp project(':notary-plugins:notary-plugin-non-validating:notary-plugin-non-validating-server')
Ok. This is probably something we can revisit then once we have updated things to deploy different CPIs to different nodes.

2022-11-14 16:32 UTC, relyafi commented on notary-plugins/notary-plugin-non-validating/notary-plugin-non-validating-server/src/main/kotlin/com/r3/corda/notary/plugin/nonvalidating/server/NonValidatingNotaryServerFlowImpl.kt
> +    internal lateinit var clientService: LedgerUniquenessCheckerClientService
Ok, so it's to do with testing - I was asking the why it had been done, not that what has been done is necessarily wrong. Is this how other tests generally deal with exposing injectables to tests?

If so, should these have the `VisibleForTesting` annotation?

2022-11-14 16:35 UTC, relyafi commented on notary-plugins/notary-plugin-non-validating/notary-plugin-non-validating-server/src/test/kotlin/com/r3/corda/notary/plugin/nonvalidating/server/NonValidatingNotaryServerFlowImplTest.kt
> +        }
But this is a unit test, so the "client" flow is mocked is it not? We seem to be using 'mockClientSession' which contains alice as the counterparty, I don't see anywhere where bob is being included in the mock objects?

2022-11-14 16:38 UTC, relyafi commented on notary-plugins/notary-plugin-non-validating/notary-plugin-non-validating-client/src/main/kotlin/com/r3/corda/notary/plugin/nonvalidating/client/NonValidatingNotaryClientFlowImpl.kt
> +    internal lateinit var flowMessaging: FlowMessaging
Same as earlier comment - the `VisibleForTesting` annotation might make things clearer, if this is the precedent used in other tests

2022-11-14 16:40 UTC, relyafi commented on notary-plugins/notary-plugin-non-validating/notary-plugin-non-validating-client/src/test/kotlin/com/r3/corda/notary/plugin/nonvalidating/client/NonValidatingNotaryClientFlowImplTest.kt
> +        val dummyX500Name = MemberX500Name("Alice", "Alice Corp", "LDN", "GB")
Fair point. There is a question then, of what should these tests be invoking - `FinalityFlow`, with a notary registered with the plugin metadata, or directly invoking the notary plugin client flow? The former would be a more complete test. But also appreciate that can't be done until Ledger is more mature.

(There is also arguably a security concern here of whether we want to allow these flows to be directly invokable outside of `FinalityFlow`, but I think that's a post-Beta question)

2022-11-14 16:51 UTC, nkovacsx commented on testing/cpbs/test-cordapp/src/main/kotlin/net/cordapp/testing/testflows/NonValidatingNotaryTestFlow.kt
> +            }
Makes sense, thanks!

2022-11-15 04:26 UTC, nkovacsx commented on testing/cpbs/test-cordapp/src/main/kotlin/net/cordapp/testing/testflows/NonValidatingNotaryTestFlow.kt
> +        }
After consulting with the MGM team, it seems like that the `NotaryLookup` class is still unfinished. There's an open PR for it, https://github.com/corda/corda-runtime-os/pull/2498/files#diff-3eda7eb9c33b74b00312373929dc06e1d6ad84f5ca4503529bf360e370a096bd. Once that's merged, I'll update this flow to use that. On the other hand, I did add a logic to register notary VNodes to the smoke test network.

2022-11-15 04:32 UTC, nkovacsx commented on processors/flow-processor/build.gradle
> +    implementation project(":notary-plugins:notary-plugin-common")
Actually after re-testing seems like this is not needed at all.

2022-11-15 04:33 UTC, nkovacsx commented on testing/cpbs/test-cordapp/src/main/kotlin/net/cordapp/testing/testflows/NonValidatingNotaryTestFlow.kt
> +            .addReferenceInputState(generateStateAndRef(DUMMY_TX_ID, 0, notaryParty))
Yeah that makes sense

2022-11-15 16:19 UTC, nkovacsx commented on notary-plugins/notary-plugin-non-validating/notary-plugin-non-validating-client/src/main/kotlin/com/r3/corda/notary/plugin/nonvalidating/client/NonValidatingNotaryClientFlowImpl.kt
> +    internal lateinit var flowMessaging: FlowMessaging
I ended up creating an internal constructor, and annotating that with `@VisibleForTesting` probably cleaner.

2022-11-15 16:21 UTC, nkovacsx commented on notary-plugins/notary-plugin-non-validating/notary-plugin-non-validating-server/src/test/kotlin/com/r3/corda/notary/plugin/nonvalidating/server/NonValidatingNotaryServerFlowImplTest.kt
> +        }
Oh rats! I completely missed this 🤦

2022-11-15 16:23 UTC, nkovacsx commented on notary-plugins/notary-plugin-non-validating/notary-plugin-non-validating-server/src/test/kotlin/com/r3/corda/notary/plugin/nonvalidating/server/NonValidatingNotaryServerFlowImplTest.kt
> +        )
I tried to reduce this as much as possible, let me know if you think that's good enough.

2022-11-15 17:20 UTC, relyafi requested changes
Looking much cleaner now. Some new minor comments, a few original comments also still need to be addressed

2022-11-15 17:20 UTC, relyafi commented on testing/cpbs/test-cordapp/src/main/kotlin/net/cordapp/testing/testflows/NonValidatingNotaryTestFlow.kt
> +        }
The logic looks fine, but is there a reason this needs to be done separately from the builder logic, i.e. just do a `run` within the builder? That way we avoid introducing a separate `stxBuilder` variable and duplicating the `sign` call.

2022-11-15 17:20 UTC, relyafi commented on notary-plugins/notary-plugin-non-validating/notary-plugin-non-validating-server/build.gradle
> +    testImplementation project(":libs:uniqueness:common")
@nkovacsx reopening as appears to still be unresolved

2022-11-15 17:20 UTC, relyafi commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/flow/FlowTests.kt
> +    fun `Notary - Non-validating plugin returns error when double spend occurs`() {
```suggestion
    fun `Notary - Non-validating plugin returns error when using reference state that is spent in same tx`() {
```

Avoids confusion - I'd assume a "double spend" is trying to spend the same input state in two different txs.

2022-11-15 17:20 UTC, relyafi commented on notary-plugins/notary-plugin-non-validating/notary-plugin-non-validating-client/src/test/kotlin/com/r3/corda/notary/plugin/nonvalidating/client/NonValidatingNotaryClientFlowImplTest.kt
> +class NonValidatingNotaryClientFlowImplTest {
As with the server side tests, is the `PER_CLASS` lifecycle beneficial here?

2022-11-15 17:20 UTC, relyafi commented on notary-plugins/notary-plugin-non-validating/notary-plugin-non-validating-server/src/test/kotlin/com/r3/corda/notary/plugin/nonvalidating/server/NonValidatingNotaryServerFlowImplTest.kt
> +        val bobName = MemberX500Name("Bob", "Bob Corp", "LDN", "GB")
Unused?

2022-11-15 17:20 UTC, relyafi commented on testing/cpbs/test-cordapp/src/main/kotlin/net/cordapp/testing/testflows/NonValidatingNotaryTestFlow.kt
> +/**
We now have 2 KDoc comments, not sure if they will play nicely together. If they don't, suggest combining into one block, or just make this one a regular block comment (since it's only relevant to a reader of the code)

2022-11-15 17:20 UTC, relyafi commented on testing/cpbs/test-cordapp/src/main/kotlin/net/cordapp/testing/testflows/NonValidatingNotaryTestFlow.kt
> + * window's lower bound will be the current UTC time ([Instant.now]).
```suggestion
 * UTC time ([Instant.now]) - 10 seconds. If not provided, no lower bound is assumed.
```

2022-11-16 09:47 UTC, nkovacsx commented on testing/cpbs/test-cordapp/src/main/kotlin/net/cordapp/testing/testflows/NonValidatingNotaryTestFlow.kt
> +        }
good point

2022-11-16 13:06 UTC, relyafi approved these changes, later dismissed
LGTM, subject to detekt issues being resolved

2022-11-17 08:59 UTC, ronanbrowne approved these changes, later dismissed
LGTM (build changes)

2022-11-17 15:12 UTC, relyafi approved these changes

2022-11-17 15:48 UTC, ronanbrowne approved these changes

2022-11-17 15:51 UTC, merged