CORE-7908: Always Capture Test Result
corda/corda-runtime-os pull request #2515
Opened 2022-11-14 03:36 UTC by knguyen-r3

* Added an always statement into 'smoketests' stage and moved the capturing of Junit results into this stage.

2022-11-14 13:49 UTC, ronanbrowne requested changes
see comments

2022-11-14 13:49 UTC, ronanbrowne commented on .ci/e2eTests/JenkinsfileCombinedWorker
> +                junit allowEmptyResults: true, testResults: '**/test-results/**/TEST-*.xml'
needs to be in a post stage see example [here ](https://github.com/corda/corda-runtime-os/blob/release/os/5.0/.ci/e2eTests/Jenkinsfile#L125-L134)

2022-11-17 11:03 UTC, ronanbrowne approved these changes
LGTM

2022-11-17 11:03 UTC, merged

2022-11-17 11:42 UTC, yarivus reviewed
thx @ronanbrowne