CORE-6669: Instance flow service injection in Simulator
corda/corda-runtime-os pull request #2530
Opened 2022-11-15 11:50 UTC by ashutoshmeher-r3

Instance Flow Service Injection

2022-11-17 11:46 UTC, LizR3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/SimulatedVirtualNodeBase.kt
> +        log.info("Calling flow $flowClassName for member \"$member\" with request: ${input.requestBody}")
Can we pop a "Calling flow _instance_" into this message to distinguish it from the ordinary flow class call please?

Also please remove comment below (it's in Git history if we need it).

2022-11-17 11:46 UTC, LizR3 commented on simulator/runtime/src/test/kotlin/net/corda/simulator/runtime/SimulatedVirtualNodeBaseTest.kt
> +        whenever(flowFactory.createInitiatingFlow(any(), any())).thenReturn(flow)
Fairly sure we don't need to stub the flow factory call here; we're giving it an instance of a flow so it shouldn't be creating one. If you wanted to you could add a check at the end that the createInitiatingFlow method is _never_ called.

2022-11-17 11:46 UTC, LizR3 commented on simulator/runtime/src/test/kotlin/net/corda/simulator/runtime/flows/DefaultServicesInjectorTest.kt
>  }
Very nice tests, very clean. However, we're now using the whole of Simulator in what should really be a test just for `DefaultServicesInjector`, which means this is an integration test rather than a unit test. Is it possible to do this just with `DefaultServicesInjector` and some mocks? Happy to pair on it.

2022-11-17 11:46 UTC, LizR3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/flows/DefaultServicesInjector.kt
>              FlowContext(configuration, member, protocol),
This is great work. I think though that it's now significantly complex. You have a test that this gets injected correctly which is great, but the test doesn't cover whether the flow messaging service has been set up with the correct config etc.

"Single Responsibility Principle" suggests this class should only be responsible for injecting services. Maybe there's a factory that could be responsible for constructing the flow messaging, then we could mock it out for this class's test and test it separately. Happy to chat on that at your convenience.

2022-11-17 11:46 UTC, LizR3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/messaging/SimFiberBase.kt
> +    override fun registerInitiatorInstance(initiator: MemberX500Name, protocol: String, initatingFlow: RPCStartableFlow) {
Detekt flags this line up as too long; need to move args onto separate lines. Small stuff.

2022-11-17 11:46 UTC, LizR3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/messaging/SimFiberBase.kt
> +    }
I feel like there's another class missing here, too. Maybe a `FlowRegistry` that holds all of this stuff, letting the `SimFiberBase` be responsible only for coordinating the shared state. Up to you though, it's not so complex just yet.

Also worth looking up Kotlin's `by` keyword - I suspect there's a lot of methods on `SimFiberBase` that could be delegated to a `FlowRegistry` and help to shrink this rapidly-growing class.

2022-11-17 11:46 UTC, LizR3 commented on simulator/api/src/main/kotlin/net/corda/simulator/SimulatedVirtualNode.kt
> +     * @flow The flow to be called
This should say `@param input` and `@param flow` - I can see you've copied it from the method above; a mistake I made while a bit tired and obviously haven't corrected yet! Please could you correct both methods? The methods lower down in this class are good examples. Thank you!

2022-11-17 11:46 UTC, LizR3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/SimulatorDelegateBase.kt
> +        return SimulatedVirtualNodeBase(holdingIdentity, fiber, injector, flowFactory, BaseSimKeyStore())
If we go down the route of creating a `FlowRegistry` in the fiber (see comment below) then the whole check for what kind of flow it is could move into that.

(Note that inside the `SimFiberBase`, we can call `registerMember` at any time; if it's already registered it does nothing. So it can be called regardless of type of flow.)

2022-11-28 12:26 UTC, ashutoshmeher-r3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/flows/DefaultServicesInjector.kt
>              FlowContext(configuration, member, protocol),
Added FlowMessaging factory

2022-11-28 17:02 UTC, ashutoshmeher-r3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/messaging/SimFiberBase.kt
> +    }
Added MemberAndFloww registry delegate for SimFiberBase

2022-11-28 17:06 UTC, ashutoshmeher-r3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/SimulatorDelegateBase.kt
> +        return SimulatedVirtualNodeBase(holdingIdentity, fiber, injector, flowFactory, BaseSimKeyStore())
moved to flowregistry delegate

2022-11-29 14:02 UTC, fenryka requested changes
Same points I raised on the demo a few weeks ago

2022-11-29 14:02 UTC, fenryka commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/messaging/BaseFlowRegistry.kt
> +            nodeClasses[responder] = hashMapOf(protocol to flowClass)
Race, I've mentioned this before

2022-11-29 14:02 UTC, fenryka commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/messaging/BaseFlowRegistry.kt
> +            nodeInitiatorInstances[initiator] = hashMapOf(initatingFlow to protocol)
GetOrDefault

2022-11-29 14:02 UTC, fenryka commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/messaging/BaseFlowRegistry.kt
> +        if(instanceFlow is ResponderFlow) {
Why isn't this more OO

2022-11-29 14:02 UTC, fenryka commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/messaging/BaseFlowRegistry.kt
> +        if(nodeClasses[responder]?.get(protocol) != null) {
Use asserf?

2022-11-29 14:02 UTC, fenryka commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/messaging/BaseFlowRegistry.kt
> +            nodeInstances[responder] = hashMapOf(protocol to responderFlow)
Same comments as above

2022-11-29 14:02 UTC, fenryka commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/messaging/SimFiberBase.kt
> +        val instanceFlowMap = lookUpInitiatorInstance(member)
The logic expressed in this function doesn't read very well!

2022-11-29 14:02 UTC, fenryka commented on simulator/runtime/src/test/kotlin/net/corda/simulator/runtime/flows/DefaultServicesInjectorTest.kt
> +                val session = flowMessaging.initiateFlow(whoToPing)
Use apply

2022-11-30 09:14 UTC, mattbradburyr3 reviewed
Initial set of comments (I'm still reviewing)

2022-11-30 09:14 UTC, mattbradburyr3 commented on simulator/runtime/src/test/kotlin/net/corda/simulator/runtime/flows/DefaultServicesInjectorTest.kt
> +                val session = flowMessaging.initiateFlow(whoToPing)
I'm not sure how you would use apply here. InitiateFlow isn't setting a variable on the session, I think its a straight method call on the class. 

You could inline whoToPing but it would make for quite a long expression.

2022-11-30 09:14 UTC, mattbradburyr3 commented on simulator/runtime/src/test/kotlin/net/corda/simulator/runtime/flows/DefaultServicesInjectorTest.kt
>  }
@LizR3 do we have any integration tests(apart from those in the example app)

2022-11-30 09:14 UTC, mattbradburyr3 commented on simulator/runtime/src/test/kotlin/net/corda/simulator/runtime/messaging/SimFiberBaseTest.kt
Why did we drop the below test?

2022-11-30 09:14 UTC, mattbradburyr3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/messaging/SimFiber.kt
> +     * @param protocol The protocol for the initiator flow.
This method doesn't have a protocol param.

2022-11-30 09:14 UTC, mattbradburyr3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/messaging/SimFiber.kt
> +    /**
For the above function createSigningService, shouldn't be GetOrCreate based on the description. (I think I raised this before)

2022-11-30 09:14 UTC, mattbradburyr3 commented on simulator/api/src/main/kotlin/net/corda/simulator/SimulatedCordaNetwork.kt
> +     * @param holdingIdentity The holding identity which will call/respond to this flow.
Above comment needs updating: 
`Creates a simulated virtual node holding a concrete instance of a responder flow. Note that this bypasses all checks for constructor and annotations on the flow.`

It looks like it's initiator and responder flows that it accepts.

2022-11-30 09:14 UTC, mattbradburyr3 commented on simulator/api/src/main/kotlin/net/corda/simulator/SimulatedCordaNetwork.kt
> +     * @return A simulated virtual node which can run this instance of a initiator/responder flow.
typo a -> an

2022-11-30 09:14 UTC, mattbradburyr3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/messaging/BaseFlowRegistry.kt
> +    private val nodeInstances = HashMap<MemberX500Name, HashMap<String, ResponderFlow>>()
Does this store Responder instances, if so we should call it nodeResponderInstances (to mirror nodeInitiatorInstance) that would make things a lot clearer.

2022-11-30 09:14 UTC, mattbradburyr3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/messaging/BaseFlowRegistry.kt
> +            nodeClasses[responder] = hashMapOf(protocol to flowClass)
I would be good to understand the circumstances where this race condition would occur. Eg a cordapp writer writes a Simulator test which starts up multiple nodes on different threads. What else? 

Also what is the overhead of making this thread safe?

2022-11-30 09:22 UTC, ashutoshmeher-r3 commented on simulator/runtime/src/test/kotlin/net/corda/simulator/runtime/messaging/SimFiberBaseTest.kt
As a result of refactoring and introducing the flow registry deletegate, the registerMember is called explicitly when the flow is started, hence that test won't work with the current logic. The registerMember is already included in another test.

2022-11-30 09:25 UTC, ashutoshmeher-r3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/messaging/BaseFlowRegistry.kt
> +    private val nodeInstances = HashMap<MemberX500Name, HashMap<String, ResponderFlow>>()
Perhaps I should rename them,  there were only nodeClasses and nodeInstances when i introduced the nodeInitiatorInstances. It makes more sense to rename to nodeResponderClasses and nodeResponderInstances

2022-11-30 09:29 UTC, fenryka commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/messaging/BaseFlowRegistry.kt
> +            nodeClasses[responder] = hashMapOf(protocol to flowClass)
Anytime the lifecycle of this object could be interacted with by two threads. People need to stop assuming that just because two lines of code are listed one after the other that's how they'll be executed by the schedular

2022-11-30 09:57 UTC, mattbradburyr3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/messaging/BaseFlowRegistry.kt
> +            nodeClasses[responder] = hashMapOf(protocol to flowClass)
Understood, that makes sense in the general case. I'm looking at how two threads would end up interacting in this case. For example, somebody kicks off a test which spins up multiple nodes on different threads. (I'm not sure why they'd do that.) 

I guess the balance here is Is it worth retro fitting the whole simulator to be thread safe if it is unlikely it would be used in a multithread way. 

It would be no good changing this bit of the code if the rest of the Simulator is unsafe. And making the whole thing thread safe, and testing it to be thread safe might not be the optimum use of time.

2022-12-01 08:51 UTC, LizR3 commented on simulator/runtime/src/test/kotlin/net/corda/simulator/runtime/flows/DefaultServicesInjectorTest.kt
>  }
@mattbradburyr3 No, but we do have a ticket to write some; they will generally be badly-behaved apps, and be designed to test node interaction rather than anything stand-alone.

2022-12-02 09:14 UTC, LizR3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/messaging/BaseFlowRegistry.kt
> +            nodeClasses[responder] = hashMapOf(protocol to flowClass)
Note this is part of flow/node set-up, rather than flow/node running. I think if we want to make the whole of Simulator thread-safe it should be in a different ticket, but I would want to see a realistic use-case for why someone might want to set up flows in the same instance of Simulator in separate threads.

2022-12-02 09:25 UTC, fenryka commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/messaging/BaseFlowRegistry.kt
> +            nodeClasses[responder] = hashMapOf(protocol to flowClass)
trouble is the code doesn't enforce that distinction of modality, which means "people can do stupid things". Should we protect them from that.... debatable, in general, I would suggest that since Java has threadsafe containers with "atomic" operations we should use them and move on. 

We should also make sure we all understand the issues in these cases where it doesn't ***really*** matter so when working on something where it does we're practiced

2022-12-02 09:30 UTC, LizR3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/messaging/SimFiberBase.kt
> +        val instanceFlowMap = lookUpInitiatorInstance(member)
The logic to get the protocol from a flow class is used in a lot of different places. Might be possible to add an extension function to handle it which would clean up this function too.

2022-12-02 09:33 UTC, LizR3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/SimulatorDelegateBase.kt
> +        return SimulatedVirtualNodeBase(holdingIdentity, fiber, injector, flowFactory, BaseSimKeyStore())
This is really great, SimFiberBase is so much cleaner now, I love it. Can we move the tests across too please? Keeps them where the functionality actually is; they act as living documentation then too.

2022-12-02 09:41 UTC, LizR3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/messaging/BaseFlowRegistry.kt
> +            nodeClasses[responder] = hashMapOf(protocol to flowClass)
Ashutosh is following a pattern I set here and this appears elsewhere in the code, so I've created a new ticket for this, CORE-8654 to go look at all of them.

2022-12-02 09:44 UTC, mattbradburyr3 reviewed
MOre comments

2022-12-02 09:44 UTC, mattbradburyr3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/messaging/BaseFlowMessagingFactory.kt
> +class BaseFlowMessagingFactory: FlowMessagingFactory {
This naming convention isn't consistent with other classes. Should be FLowMessagingFactoryBase 

What's the naming convention across the simulator code?

2022-12-02 09:44 UTC, mattbradburyr3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/messaging/BaseFlowRegistry.kt
> +class BaseFlowRegistry: FlowRegistry {
FlowRegistryBase?

2022-12-02 09:44 UTC, mattbradburyr3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/messaging/FlowMessagingFactory.kt
> +interface FlowMessagingFactory {
There no description on this interface - what is it for?

2022-12-02 09:44 UTC, mattbradburyr3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/messaging/FlowMessagingFactory.kt
> +interface FlowMessagingFactory {
Why are we using a factory pattern to create the concurrentFlowMessaging object, why not just create it directly?

2022-12-02 09:44 UTC, mattbradburyr3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/messaging/BaseFlowRegistry.kt
> +            nodeInitiatorInstances[initiator] = hashMapOf(initatingFlow to protocol)
or computeIfAbsent()

2022-12-02 09:44 UTC, mattbradburyr3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/messaging/BaseFlowRegistry.kt
> +        if(instanceFlow is ResponderFlow) {
Note: 
extend ResponderFlow and RPCStartableFlow with a .register() function, then just call .register() in here.

2022-12-02 09:47 UTC, ashutoshmeher-r3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/SimulatorDelegateBase.kt
> +        return SimulatedVirtualNodeBase(holdingIdentity, fiber, injector, flowFactory, BaseSimKeyStore())
Sure

2022-12-02 14:11 UTC, LizR3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/messaging/BaseFlowRegistry.kt
> +            nodeInitiatorInstances[initiator] = hashMapOf(initatingFlow to protocol)
[getOrPut](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/get-or-put.html)? We are setting the value here.

2022-12-02 15:00 UTC, LizR3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/messaging/FlowMessagingFactory.kt
> +interface FlowMessagingFactory {
Testability. I asked Ashutosh in previous PR comments to take out some functionality that was becoming significantly complex and more to do with constructing the FlowMessaging than injecting services, and move it into another class (Single Responsibility Principle).

2022-12-02 15:07 UTC, LizR3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/messaging/BaseFlowMessagingFactory.kt
> +class BaseFlowMessagingFactory: FlowMessagingFactory {
Across Simulator, XYZBase - I think I have a few which are different but should be renamed. Across Corda, though, it's XYZImpl. There are a couple of places where things got named differently (ConcurrentFlowMessaging, DbPersistenceService), mostly hangovers from where there were more than one implementation but others disappeared on refactoring. There is a renaming ticket in Todo.

2022-12-05 11:51 UTC, ashutoshmeher-r3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/messaging/BaseFlowRegistry.kt
> +class BaseFlowRegistry: FlowRegistry {
Most of the base files are named with Base prefix. We have a separate ticker CORE-7218 for updating this.

2022-12-05 11:58 UTC, ashutoshmeher-r3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/messaging/FlowMessagingFactory.kt
> +interface FlowMessagingFactory {
Added comments

2022-12-05 11:58 UTC, ashutoshmeher-r3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/messaging/BaseFlowRegistry.kt
> +    private val nodeInstances = HashMap<MemberX500Name, HashMap<String, ResponderFlow>>()
Renamed

2022-12-05 11:59 UTC, ashutoshmeher-r3 commented on simulator/api/src/main/kotlin/net/corda/simulator/SimulatedCordaNetwork.kt
> +     * @return A simulated virtual node which can run this instance of a initiator/responder flow.
Fixed

2022-12-06 05:17 UTC, ashutoshmeher-r3 commented on simulator/api/src/main/kotlin/net/corda/simulator/SimulatedCordaNetwork.kt
> +     * @param holdingIdentity The holding identity which will call/respond to this flow.
updated comments

2022-12-06 08:53 UTC, ashutoshmeher-r3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/messaging/SimFiber.kt
> +    /**
The function just creates a new signing service, updated the description

2022-12-06 08:57 UTC, ashutoshmeher-r3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/messaging/BaseFlowRegistry.kt
> +            nodeClasses[responder] = hashMapOf(protocol to flowClass)
Added a WARNING section in the README to discourage users from using async setup code for the simulator. We would look at thread safety as part of the new ticket (CORE-8654) Liz created earlier.

2022-12-06 10:18 UTC, ashutoshmeher-r3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/messaging/SimFiberBase.kt
> +        val instanceFlowMap = lookUpInitiatorInstance(member)
Added an extension function to get protocol from flow

2022-12-06 10:19 UTC, ashutoshmeher-r3 commented on simulator/runtime/src/test/kotlin/net/corda/simulator/runtime/flows/DefaultServicesInjectorTest.kt
>  }
Updated the tests to unit test just the DefaultServicesInjector

2022-12-06 11:49 UTC, ashutoshmeher-r3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/messaging/FlowMessagingFactory.kt
> +interface FlowMessagingFactory {
Moved the logic to create flow messaging into flow messaging factory.

2022-12-06 14:07 UTC, fenryka approved these changes, later dismissed
LGTM!, 

discussed thread safety out-of-band and a new JIRA / PR will address that on a wider scale, so for now... SHIP IT!!! :)

2022-12-06 14:11 UTC, LizR3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/messaging/BaseFlowRegistry.kt
> +            nodeClasses[responder] = hashMapOf(protocol to flowClass)
Thanks, it's still just not designed for async, there's other work we would have to do to make it properly thread-safe (migrations running in parallel is an issue for a start).

2022-12-06 14:21 UTC, mattbradburyr3 approved these changes

2022-12-06 14:21 UTC, mattbradburyr3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/messaging/BaseFlowMessagingFactory.kt
> +class BaseFlowMessagingFactory: FlowMessagingFactory {
@LizR3 I can't see the ticket in the backlog/ todo

2022-12-06 14:21 UTC, mattbradburyr3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/messaging/BaseFlowMessagingFactory.kt
> +class BaseFlowMessagingFactory: FlowMessagingFactory {
Found it, it wasn't in todo, it was in backlog. I think we should do this before the beta cut

2022-12-07 05:57 UTC, merged