CORE-8112 tx signing api
corda/corda-runtime-os pull request #2546
Opened 2022-11-15 18:39 UTC by vlajos

* CORE-8112 Set, Harmonize TransactionBuilder, SignedTransaction signature related methods.
 * Port LedgerService API from Consensual to Utxo.

API: https://github.com/corda/corda-api/pull/699

2022-11-15 19:29 UTC, lankydan commented on components/ledger/ledger-consensual-flow/src/main/kotlin/net/corda/ledger/consensual/flow/impl/flows/finality/ConsensualFinalityFlow.kt
> +                    (signedByParticipantsTransaction as ConsensualSignedTransactionImpl).addSignature(signature)
We should add these functions to `ConsensualSignedTransactionInternal`. I would prefer not to be casting to implementations where possible.

2022-11-16 14:48 UTC, vlajos commented on components/ledger/ledger-consensual-flow/src/main/kotlin/net/corda/ledger/consensual/flow/impl/flows/finality/ConsensualFinalityFlow.kt
> +                    (signedByParticipantsTransaction as ConsensualSignedTransactionImpl).addSignature(signature)
I have removed this and a few more casts.
The only one left: https://github.com/corda/corda-runtime-os/pull/2546/files#diff-dfe1d000ee94da5815c588b752d29d672ee5d0749219b813d2c9aa39c9bd843eR67
I suspect this is more or less inevitable since that is the point where we get the signed tx from the user.

2022-11-16 16:04 UTC, MrMatthewLayton submitted a review, later dismissed

2022-11-17 10:02 UTC, MrMatthewLayton submitted a review, later dismissed
Implementation looks okay to me, however the API review might incur further changes.

2022-11-17 14:26 UTC, MrMatthewLayton requested changes

2022-11-17 14:26 UTC, MrMatthewLayton commented on libs/ledger/ledger-consensual-data/src/main/kotlin/net/corda/ledger/consensual/data/transaction/ConsensualLedgerTransactionImpl.kt
> +            .flatMap { it.participants }.distinct().toSet()
You don't need `.distinct()` and `.toSet()` here as sets _should by definition_ be distinct anyway.

2022-11-17 14:41 UTC, vlajos commented on libs/ledger/ledger-consensual-data/src/main/kotlin/net/corda/ledger/consensual/data/transaction/ConsensualLedgerTransactionImpl.kt
> +            .flatMap { it.participants }.distinct().toSet()
Thanks. Updated.
(I think I added that distinct when these were lists, and forgot to remove it.)

2022-11-17 15:19 UTC, MrMatthewLayton approved these changes, later dismissed

2022-11-17 16:21 UTC, MrMatthewLayton approved these changes, later dismissed
LGTM, Great Work!

2022-11-17 16:48 UTC, MrMatthewLayton approved these changes, later dismissed

2022-11-18 11:17 UTC, MrMatthewLayton approved these changes, later dismissed

2022-11-18 12:14 UTC, mnesbit submitted a review, later dismissed
OK

2022-11-18 15:03 UTC, mnesbit approved these changes, later dismissed
OK

2022-11-18 15:11 UTC, lankydan approved these changes, later dismissed

2022-11-18 16:22 UTC, lankydan approved these changes

2022-11-18 16:23 UTC, merged