CORE-7629: Use resultList instead of resultStream when querying for CPI metadata
corda/corda-runtime-os pull request #2562
Opened 2022-11-16 17:06 UTC by fowlerrr

2022-11-16 17:22 UTC, fowlerrr commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/reconcile/db/DbReconcilerReader.kt
> +            } finally {
These nested try's are weird.  But I couldn't think of another way to catch all of the issues _including_ a throw when creating the `EntityManager`.  Might be my brain is just tired...

2022-11-16 17:23 UTC, fowlerrr commented on libs/virtual-node/cpi-datamodel/src/main/kotlin/net/corda/libs/cpi/datamodel/CpiMetadataEntity.kt
> +    ).resultList
This here is the crux of the change.  The streams seem to be failing us.

2022-11-17 10:06 UTC, driessamyn requested changes

2022-11-17 10:06 UTC, driessamyn commented on components/reconciliation/reconciliation/src/main/kotlin/net/corda/reconciliation/ReconcilerReader.kt
> +    fun getAllVersionedRecords(): List<VersionedRecord<K, V>>?
We shouldn't change the API. It's a stream for a good reason, as Lists will not be sustainable in the long term.

2022-11-17 10:08 UTC, driessamyn commented on libs/virtual-node/cpi-datamodel/src/main/kotlin/net/corda/libs/cpi/datamodel/CpiMetadataEntity.kt
> +    ).resultList
Have you tried to log the generated SQL query and inspected it?
I wonder if it's an order problem. Maybe the CPKs come in out of order.

2022-11-17 10:11 UTC, fowlerrr commented on libs/virtual-node/cpi-datamodel/src/main/kotlin/net/corda/libs/cpi/datamodel/CpiMetadataEntity.kt
> +    ).resultList
There's nothing wrong with the SQL.  It works fine.  It's something about the stream (or the stream.toList()) that's the problem.

Getting a direct list works fine.  As I understand it (though I'll just quickly verify it myself) a stream works okay.  It's the conversion of the stream to the list that's breaking.

2022-11-17 10:40 UTC, fowlerrr commented
We're backing out 94.3% of these changes so I'll raise a new PR

2022-11-17 10:40 UTC, closed without merging

2022-11-17 10:41 UTC, Tom-Fitzpatrick commented
Sorry, I was looking at this PR in IntelliJ and accidentally closed it