CORE-6171: JPA backing store performance improvement
corda/corda-runtime-os pull request #2594
Opened 2022-11-21 17:57 UTC by ifrankrui

### Summary

The existing Uniqueness checker database access and processing is pretty basic. This change implements Hibernate's batch insert and multiLoad so that the database operations can be processed in batches to improve performance. 

For the batch insert, the batch size is defined at Hibernate session level using `entityManager.unwrap(Session::class.java).jdbcBatchSize`. The value is set to 50. This value should be reviewed when we have a realistic workload to test. For multiLoad, Hibernate uses the batch size defined in the database-specific dialect based on the application. In our instance, we use Postgres and the default batch size is 50. 

We also need to change some hibernate properties to facilitate the baching. These properties are    `hibernate.jdbc.batch_versioned_data`, `hibernate.order_inserts` and `hibernate.order_updates`. More information on the properties can be found [here](https://docs.jboss.org/hibernate/orm/5.6/userguide/html_single/Hibernate_User_Guide.html#batch). 

When PostgreSQL JDBC driver is used, we also need to add `reWriteBatchedInserts=true` to JDBCURL for database connection.

### Testing

The change has been tested using [CORE-6169](https://r3-cev.atlassian.net/browse/CORE-6169) benchmarks. All the tests are performed on a local Postgres instance and the results are illustrated in the following graph. 
<img width="1170" alt="image" src="https://user-images.githubusercontent.com/42246789/203114692-d3964f55-2835-4655-af56-dadc386bceda.png">

The above graph demonstrates significant performance improvement with the Hibernate batching (either global or session level settings). Only `state_write_consumed` operation can't be batched, therefore there is not much difference in the tests.

For more explanation on the test results and comparison please refer to [CORE-6171](https://r3-cev.atlassian.net/browse/CORE-6171).

2022-11-23 10:09 UTC, relyafi requested changes
Concerningly, there are a number of failing unit and integration tests in both the backing store and uniqueness checker tests. These all need investigating and either updating if there is an intentional change in behavior, or any introduced bugs fixing. There appears to be a clear bug in the transaction lookup logic for example.

The performance tests will need re-running after we have confirmed the changes are functionally correct, as the existing results may be impacted.

2022-11-23 10:09 UTC, relyafi commented on testing/db-testkit/src/main/kotlin/net/corda/db/testkit/DbUtils.kt
> +        var jdbcUrl = "jdbc:postgresql://$host:$port/$postgresDb&reWriteBatchedInserts=true"
A few comments on this:

1. Is it desirable / safe to do this for all database connections? If not this probably needs to be an additional option. @driessamyn may have an opinion on this.
2. This is fine for our automated tests, but is not going to apply if we are using a real database. We presumably need to make an equivalent change when provisioning databases as part of VNode creation. Point 1 regarding optionality also applies here, but it may be this is easier to apply in this case by applying this only when creating uniqueness databases.
3. What is the impact of setting the earlier Hibernate settings, without setting this in the JDBC URL? I'm assuming that it would simply not give the desired performance improvements as opposed to failing. If this assumption is incorrect, this may have implications as it's possible that we will be given an operator-specified JDBC URL at VNode creation time.

2022-11-23 10:09 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/main/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImpl.kt
> +import net.corda.uniqueness.backingstore.jpa.datamodel.*
This is causing your detekt warning. You need to configure your IntelliJ settings to have a very large value at which it will auto-wildcard import to prevent it from doing this.

2022-11-23 10:09 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/main/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImpl.kt
> +import net.corda.uniqueness.datamodel.common.UniquenessConstants.HIBERNATE_JDBC_BATCH_SIZE
Out-of-order include - use optimise imports to fix this.

2022-11-23 10:09 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/main/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImpl.kt
> +                val statePk = UniquenessTxAlgoStateRefKey(txId.algorithm, txId.bytes, stateIndex)
Unnecessary variables that are only used once - can be inlined.

2022-11-23 10:09 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/main/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImpl.kt
> +                entityManager.unwrap(Session::class.java).byMultipleIds(UniquenessStateDetailEntity::class.java)
Conversely, we are calling `unwrap` several times in different functions. I'm not sure what the overheads are of doing this. If they are significant, we may want to consider doing this once and storing it as a private val in `SessionImpl`, as we do for `entityManager`. I'm ok to leave as is if the overheads are negligible though.

2022-11-23 10:09 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/main/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImpl.kt
> +            existing.firstOrNull()?.let { txEntity ->
This looks wrong - previously this was evaluated within the context of a `forEach` loop, now this is simply returning the first transaction found. This may be one of the reasons we have failing test cases.

2022-11-23 10:09 UTC, relyafi commented on libs/db/db-orm-impl/src/main/kotlin/net/corda/orm/impl/EntityManagerFactoryFactoryImpl.kt
> +            "hibernate.order_updates" to "true",
This is a wide-reaching change that may impact more than just the uniqueness checker sessions. Is this really what we want to do? @driessamyn may have an opinion on this.

2022-11-23 11:48 UTC, ifrankrui commented on testing/db-testkit/src/main/kotlin/net/corda/db/testkit/DbUtils.kt
> +        var jdbcUrl = "jdbc:postgresql://$host:$port/$postgresDb&reWriteBatchedInserts=true"
I was thinking of adding `reWriteBatchedInserts` as an option. As there is no obvious disadvantage to enabling this setting for the Postgres connections, I think it's not a bad idea to enable it by default here.
  
Without this setting, Hibernate won't be able to batch the insert operations, so the performance will not be as good but won't fail.

2022-11-24 14:09 UTC, nkovacsx commented on components/uniqueness/backing-store-impl/src/main/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImpl.kt
> +                entityManager.unwrap(Session::class.java).byMultipleIds(UniquenessStateDetailEntity::class.java)
From my experience, calling entity manager is always expensive so I'd just export `entitymnager.unwrap(Session::class.java)` to a variable.

2022-11-24 14:16 UTC, nkovacsx requested changes, later dismissed

2022-11-24 14:16 UTC, nkovacsx commented on components/uniqueness/backing-store-impl/src/main/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImpl.kt
> +            val txPks = mutableListOf<UniquenessTxAlgoIdKey>()
could we use `map` here instead of `forEach`? Filling up a mutable list in a foreach is Java-like, I'd prefer something like this:
```
val txPks = txIds.map {
    UniquenessTxAlgoIdKey(it.algorithm, it.bytes)
}
```
That way txPks can be an immutable list and we got rid of a `forEach`.

2022-11-24 14:16 UTC, nkovacsx commented on components/uniqueness/backing-store-impl/src/main/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImpl.kt
> +            existing.forEach { txEntity ->
Same here, we are using a mutable collection instead of mapping it:
```
val results = existing.map { txEntity ->
    val result = when (txEntity.result) {
        RESULT_ACCEPTED_REPRESENTATION -> {
            UniquenessCheckResultSuccessImpl(txEntity.commitTimestamp)
        }
        RESULT_REJECTED_REPRESENTATION -> {
            // If the transaction is rejected we need to make sure it is also
            // stored in the rejected tx table
            UniquenessCheckResultFailureImpl(
                txEntity.commitTimestamp,
                getTransactionError(txEntity) ?: throw IllegalStateException(
                    "Transaction with id ${txEntity.txId} was rejected but no records were " +
                            "found in the rejected transactions table"
                )
            )
        }
        else -> throw IllegalStateException(
            "Transaction result can only be " +
                    "'$RESULT_ACCEPTED_REPRESENTATION' or '$RESULT_REJECTED_REPRESENTATION'"
        )
    }
    val txHash = SecureHash(txEntity.txIdAlgo, txEntity.txId)
    txHash to UniquenessCheckTransactionDetailsInternal(txHash, result)
}.toMap()
```
Or is there a reason this needs to be a HashMap specifically? @relyafi ?

2022-11-24 14:16 UTC, nkovacsx commented on libs/db/db-orm-impl/src/main/kotlin/net/corda/orm/impl/EntityManagerFactoryFactoryImpl.kt
> +            "hibernate.order_updates" to "true",
Agreed, this will have affect the whole code-base, not sure if this is a good idea.

2022-11-24 14:25 UTC, nkovacsx commented on testing/db-testkit/src/main/kotlin/net/corda/db/testkit/DbUtils.kt
> +        var jdbcUrl = "jdbc:postgresql://$host:$port/$postgresDb&reWriteBatchedInserts=true"
Are you sure this is the right syntax/place to put this switch? Seems like that might be why the integration tests are failing:
```
Caused by: org.postgresql.util.PSQLException: FATAL: database "test_f2c867dd-c504-4b52-9b39-5455a810ad5f&reWriteBatchedInserts" does not exist
```
Might be unrelated though, haven't figured it out yet.

2022-11-24 14:29 UTC, nkovacsx commented on testing/db-testkit/src/main/kotlin/net/corda/db/testkit/DbUtils.kt
> +        var jdbcUrl = "jdbc:postgresql://$host:$port/$postgresDb&reWriteBatchedInserts=true"
Quite strange because it runs locally:
```
Test run finished after 128583 ms
[         4 containers found      ]
[         0 containers skipped    ]
[         4 containers started    ]
[         0 containers aborted    ]
[         4 containers successful ]
[         0 containers failed     ]
[         5 tests found           ]
[         0 tests skipped         ]
[         5 tests started         ]
[         0 tests aborted         ]
[         5 tests successful      ]
[         0 tests failed          ]
```

2022-11-25 09:45 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/main/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImpl.kt
> +            existing.forEach { txEntity ->
@nkovacsx I suspect its because in the original logic, we weren't always adding an entry (we could fail the lookup). In such a scenario, you wouldn't be able to call `map`, you'd have to do `mapNotNull` and then use null for the negative case internally, which personally I find messier and less intuitive than adding to a mutable map.

On the surface it looks like this new implementation is always adding a result now (or throwing), so yes just using the map function may make sense.

2022-12-02 11:53 UTC, driessamyn commented on components/uniqueness/backing-store-impl/src/main/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImpl.kt
> +        private val hibernateSession = entityManager.unwrap(Session::class.java)
Sorry for the fly-by review. Was curious about this PR in context of another discussion about Native SQL vs JPA in the ledger layer.
I think we should be careful with this as this is basically breaking the JPA abstraction and tying us to Hibernate as a JPA implementation.
The way things are evolving around ledger, it may make more sense to completely remove JPA if there is a reason such as performance, rather than break the abstraction.

Feel free to ignore this though, it's just a thought.

2022-12-02 13:29 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/main/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImpl.kt
> +        private val hibernateSession = entityManager.unwrap(Session::class.java)
Thanks @driessamyn. Ironically the reason we've done this is for performance (whilst being DB agnostic). You might remember we discussed this living in the DB worker and using direct access rather than the persistence API because the notary needs high DB performance.

We can always revert, or replace with another implementation down the line. At the moment the order of magnitude performance improvements we're seeing in some cases whilst requiring minimal code changes. That seems like quite a low hanging fruit if there ever was one!

2022-12-06 14:35 UTC, ifrankrui commented on components/uniqueness/backing-store-impl/src/main/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImpl.kt
> +        private val hibernateSession = entityManager.unwrap(Session::class.java)
@driessamyn out of interest, where can I find the information about the discussion about Native SQL vs JPA in the ledger layer?

2022-12-06 17:10 UTC, relyafi approved these changes
LGTM, subject to confirmation of single comment (and test notes updated to reflect this)

2022-12-06 17:10 UTC, relyafi commented on testing/db-testkit/src/main/kotlin/net/corda/db/testkit/DbUtils.kt
> +        val jdbcUrlPara = getPropertyNonBlank("jdbcUrlPara", "&reWriteBatchedInserts=true")
This implies that we can specify a `-PjdbcUrlPara` argument to change this. Have we tested this scenario?

2022-12-07 10:20 UTC, relyafi commented on testing/db-testkit/src/main/kotlin/net/corda/db/testkit/DbUtils.kt
> +        var jdbcUrl = "jdbc:postgresql://$host:$port/$postgresDb&reWriteBatchedInserts=true"
Reopening this as I think point 2 still needs to be addressed.

2022-12-07 10:21 UTC, relyafi requested changes
Sorry, revoking previous approval as I missed an unaddressed comment yesterday.

2022-12-14 14:56 UTC, mnesbit commented on components/uniqueness/backing-store-impl/src/main/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImpl.kt
> +        private val hibernateSession = entityManager.unwrap(Session::class.java)
I am definitely in favour of not using JPA when it is an internal API. We have to use JPA for customer facing and customer specified schemas and queries, but not much value for things we hide behind service interfaces. We will have to document these tables properly and treat evolution as API, but don't have to define JPA objects

2022-12-14 14:57 UTC, mbrkic-r3 commented on components/uniqueness/backing-store-impl/src/main/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImpl.kt
> +        private val hibernateSession = entityManager.unwrap(Session::class.java)
Why don't you set it via properties? E.g. in `EntityManagerFactoryFactoryImpl` where other properties are set:
```
...
"hibernate.jdbc.batch_size" to HIBERNATE_JDBC_BATCH_SIZE,
"hibernate.order_inserts" to "true",
"hibernate.order_updates" to "true",
"hibernate.jdbc.batch_versioned_data" to "true",
...
```

2022-12-14 14:58 UTC, mnesbit commented on components/uniqueness/backing-store-impl/src/main/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImpl.kt
> +        private val hibernateSession = entityManager.unwrap(Session::class.java)
Note we will ultimately need to support various DB's some some cut point interfaces to allow alternates would be needed too

2022-12-15 10:14 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/main/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImpl.kt
> +        private val hibernateSession = entityManager.unwrap(Session::class.java)
@mnesbit I think your points are valid, and regarding support for various DB's, this is actually precisely the reason we use JPA - it gives us a baseline (if not optimal) ability to in theory support any JPA database with little to no code change. That does not preclude us from writing more optimized non-JPA implementations in future; in fact, C4 did exactly this, optimising a couple of write based operations with native SQL for Postgres / Cockroach DB, and using JPA for other operations and databases.

The scope of this PR is simply to make low-hanging fruit improvements to our baseline JPA implementation. I'm happy to discuss further improvements post-Beta (in fact I'm sure there will be at least one more optimization pass), but I suspect in the grand scheme of things we will have bigger things to worry about in the run up to GA.

2022-12-15 19:30 UTC, ifrankrui commented on components/uniqueness/backing-store-impl/src/main/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImpl.kt
> +        private val hibernateSession = entityManager.unwrap(Session::class.java)
> Why don't you set it via properties? E.g. in `EntityManagerFactoryFactoryImpl` where other properties are set:
> 
> ```
> ...
> "hibernate.jdbc.batch_size" to HIBERNATE_JDBC_BATCH_SIZE,
> "hibernate.order_inserts" to "true",
> "hibernate.order_updates" to "true",
> "hibernate.jdbc.batch_versioned_data" to "true",
> ...
> ```
Here I don't want to set the batch size globally to force other code in the project to use the same value. I also need to use Hibernate's `multiLoad` to speed up read operations. Therefore, I unwrap a hibernate session. This is also explained in https://r3-cev.atlassian.net/browse/CORE-6171.

2022-12-19 13:44 UTC, relyafi approved these changes, later dismissed
One trivial comment, otherwise LGTM. Probably not worth addressing the comment in isolation and having to go through another PR gate cycle.

2022-12-19 13:44 UTC, relyafi commented on testing/db-testkit/src/main/kotlin/net/corda/db/testkit/DbUtils.kt
> +                {"$jdbcUrl?currentSchema=$schemaName"}
```suggestion
            jdbcUrl = if (rewriteBatchedInserts) {
                "$jdbcUrl?currentSchema=$schemaName&reWriteBatchedInserts=true"
            } else {
                "$jdbcUrl?currentSchema=$schemaName"
            }
```

I believe this is the correct style for if / else

2022-12-19 13:49 UTC, relyafi submitted a review, later dismissed

2022-12-20 11:12 UTC, ronanbrowne submitted a review, later dismissed
lgtm (build changes)

2022-12-20 16:19 UTC, relyafi approved these changes

2022-12-20 16:58 UTC, ronanbrowne approved these changes

2022-12-20 17:00 UTC, merged