CORE-7414 Initial draft
corda/corda-runtime-os pull request #2603
Opened 2022-11-22 18:23 UTC by oscardalmau-r3

2022-11-28 09:01 UTC, davidcurrie requested changes

2022-11-28 09:01 UTC, davidcurrie commented on charts/corda/templates/_helpers.tpl
> +{{- with .Values.podSecurityContext | default .Values.podSecurityContext }}
?!?!?
```suggestion
{{- with .Values.podSecurityContext }}
```

2022-11-28 09:01 UTC, davidcurrie commented on charts/corda/templates/_helpers.tpl
> +{{- define "corda.workerConainterSecurityContext" -}}
```suggestion
{{- define "corda.workerContainerSecurityContext" -}}
```

2022-11-28 09:01 UTC, davidcurrie commented on charts/corda/templates/_helpers.tpl
> +{{- with .Values.securityContext | default .Values.securityContext }}
```suggestion
{{- with .Values.securityContext }}
```

2022-11-28 09:01 UTC, davidcurrie commented on charts/corda/templates/_helpers.tpl
> +
```suggestion
```

2022-11-28 09:01 UTC, davidcurrie commented on charts/corda/templates/_helpers.tpl
> +
```suggestion
```

2022-11-28 09:01 UTC, davidcurrie commented on charts/corda/templates/_helpers.tpl
> +
```suggestion
```

2022-11-28 09:01 UTC, davidcurrie commented on charts/corda/templates/crypto-worker.yaml
> +        {{- include "corda.workerConainterSecurityContext" . | nindent 8 }}
And in all the other workers...
```suggestion
        {{- include "corda.workerContainerSecurityContext" . | nindent 8 }}

```

2022-11-28 09:01 UTC, davidcurrie commented on charts/corda/values.yaml
> +serviceAccount: ""
suggest using:
```
serviceAccount:
  name: ""
```
to give us the flexibility if we later want to create a service account as part of the install

2022-11-28 09:01 UTC, davidcurrie commented on charts/corda/values.yaml
> +  allowPrivilegeEscalation: false
Just looking at these now and wondering whether we actually need to expose them in the `values.yaml`? If we are able to supply secure values by default, why would anyone want/need to override them?

2022-11-28 11:42 UTC, oscardalmau-r3 commented on charts/corda/values.yaml
> +  allowPrivilegeEscalation: false
Moved the default values back to the helpers file.

2022-11-28 11:53 UTC, davidcurrie commented on charts/corda/values.yaml
> +securityContext: {}
Do you need these overrides to be able to deploy on OpenShift? If not, can we remove them now along with the bootstrap `securityContext`.

2022-11-28 14:05 UTC, oscardalmau-r3 commented on charts/corda/values.yaml
> +securityContext: {}
There is no `securityContext` set at all on the current bootstrap templates. Are you asking me to keep it that way or to add it but using hardcoded values?

2022-11-28 14:12 UTC, davidcurrie commented on charts/corda/values.yaml
> +  securityContext: { }
What is this if it's not a security context on the bootstrap container?

2022-11-28 14:16 UTC, oscardalmau-r3 commented on charts/corda/values.yaml
> +  securityContext: { }
Sorry I meant there's no boostrap securityContext on the current Helm chart in the `release/os/5.0` branch.

2022-11-28 14:34 UTC, oscardalmau-r3 commented on charts/corda/values.yaml
> +securityContext: {}
Also, for the bootstrap jobs I do need the `securityContext` to be overwritten to use `allowPrivilegeEscalation: true`

2022-11-28 15:22 UTC, davidcurrie commented on charts/corda/values.yaml
> +securityContext: {}
This was what I was trying to say this morning: don't do this via overrides. If it needs to be set, just do it in the chart. There's no point in having a default of `false` if it simply doesn't work.

2022-11-29 15:41 UTC, davidcurrie approved these changes
LGTM - I'm sure we're going to want a service account name per worker at some point but happy to tackle that when it comes up

2022-11-29 16:06 UTC, merged