CORE-7299 - Integrate reconciliaton services
corda/corda-runtime-os pull request #2611
Opened 2022-11-24 13:41 UTC by nikinagy

Created final version for group parameters reconciliation.

Testing:
Removed from code base every usage of GroupParametersWriterService.put(), except for reconciliation. This way kafka records got pushed by the sync with db when reconciliation ran. Checked log messages to see what was published on kafka and for which member.
In this particular test scenario MGM was `9E6408D0B03E` and notary member was `9A6A28E8193C`.
After checking the db worker I could see that reconciliation happened for both identities and db entries got published to kafka:
1) only MGM registered so far:
<img width="1663" alt="Screenshot 2022-11-24 at 13 34 00" src="https://user-images.githubusercontent.com/61757742/203797108-8a32497d-c1c7-465d-a0d8-38a755aafdb5.png">
2) notary member registered, database got updated with new version of group params:
<img width="1674" alt="Screenshot 2022-11-24 at 13 33 38" src="https://user-images.githubusercontent.com/61757742/203797219-3af1be90-bdd9-4486-bf9e-c08a6d826386.png">
<img width="1671" alt="Screenshot 2022-11-24 at 13 32 38" src="https://user-images.githubusercontent.com/61757742/203797231-057e62de-4eff-484d-bdc7-920d899a6f72.png">

Also this ticket fixed a bug found in `PersistGroupParametersHandler`. We used `.singleResult` which assumes that the db already has some kind of data stored. When we tried to persist the group parameters for member for the first time we ended up with `17:19:50.558 [rpc subscription thread membership.db.persistence-membership.db.rpc.ops] WARN  net.corda.membership.impl.persistence.service.MembershipPersistenceRPCProcessor {} - Exception thrown while processing membership persistence request: No entity found for query`, because the db table was empty and no entry was found. I added an extra check to the places where we are using `.singleResult` to make sure the query from db did not resulted in an empty list before validations.

2022-11-24 13:57 UTC, fenryka reviewed
I have some comments, feel free to slack me to talk 'me through :)

2022-11-24 13:57 UTC, fenryka commented on components/membership/membership-persistence-service-impl/src/main/kotlin/net/corda/membership/impl/persistence/service/handler/PersistGroupParametersHandler.kt
> +            if(latestEntry.resultList.isNotEmpty()) {
what if it is empty? The problem I have with this code is to the reader coming in at a later date its unclear if it being empty is expected (and we don't do anything) or if its an unhandled issue!

2022-11-24 13:57 UTC, fenryka commented on components/membership/membership-persistence-service-impl/src/main/kotlin/net/corda/membership/impl/persistence/service/handler/AddNotaryToGroupParametersHandler.kt
> +            if(previous.resultList.isEmpty()) {
I'm not a fan of lots of vals being created for one-off uses, especially in Kotlin where it can be easier to avoid - It's me being a little picky but I'm fairly sure this funciton could be re-written to be clearer to future readers what its doing

2022-11-24 13:57 UTC, fenryka commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/reconcile/db/GroupParametersReconciler.kt
> +                kafkaReader = reconcilerReader,
nomenclature miss, one is dbReconciler, one is reconilerReader, shouldn't that be kafkaREconciler?

2022-11-24 13:57 UTC, fenryka commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/reconcile/db/GroupParametersReconciler.kt
> +        if (reconciler == null) {
is this thread safe? what happens if two threads want to updateInterval and both read reconciler as null?

2022-11-24 14:09 UTC, charlieR3 reviewed
Some minor comments on top of Kat's. Could you update the PR name also to mention "group parameters reconciliation services" just to give a bit more context?

2022-11-24 14:09 UTC, charlieR3 commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/DBProcessorImpl.kt
> +    private val jpaEntitiesRegistry: JpaEntitiesRegistry,
This is already injected as:
```
@Reference(service = JpaEntitiesRegistry::class)
private val entitiesRegistry: JpaEntitiesRegistry,
```

2022-11-24 14:09 UTC, charlieR3 commented on processors/db-processor/src/test/kotlin/net/corda/processors/db/internal/reconcile/db/GroupParametersReconcilerTest.kt
> +            verify(reconciler, times(1)).start()
```suggestion
            verify(reconciler).start()
```
Once is the default so no need to specify it explicitly.

2022-11-24 15:58 UTC, charlieR3 commented on components/membership/membership-persistence-service-impl/src/main/kotlin/net/corda/membership/impl/persistence/service/handler/PersistGroupParametersHandler.kt
> +            if(latestEntry.resultList.isNotEmpty()) {
If it's empty there is no existing record so the group parameters with matching epoch cannot exist and it's safe to insert the new record.

Created https://r3-cev.atlassian.net/browse/CORE-8384 to cover this comment and the other persistence comment up a bit since they are out of scope for this PR (other than fixing this bug Niki found). We can put in a comment here under that linked jira if it makes it clearer.

2022-11-24 15:58 UTC, charlieR3 commented on components/membership/membership-persistence-service-impl/src/main/kotlin/net/corda/membership/impl/persistence/service/handler/AddNotaryToGroupParametersHandler.kt
> +            if(previous.resultList.isEmpty()) {
Created https://r3-cev.atlassian.net/browse/CORE-8384 to look at this as it's out of scope for this PR.

2022-11-24 16:50 UTC, charlieR3 submitted a review, later dismissed
LGTM

2022-11-25 09:07 UTC, fenryka commented on components/membership/membership-persistence-service-impl/src/main/kotlin/net/corda/membership/impl/persistence/service/handler/AddNotaryToGroupParametersHandler.kt
> +            if(previous.resultList.isEmpty()) {
fair!

2022-11-25 09:19 UTC, fenryka requested changes
Need to think more about the changes your making in relation to the wider context

2022-11-25 09:19 UTC, fenryka commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/reconcile/db/GroupParametersReconciler.kt
> +        val lock = ReentrantLock()
I don't think you want this on the companion object, that would give a single lock instance for all instances of the class which would overly serialize things, protecting access to each instance is what you need.

2022-11-25 09:19 UTC, fenryka commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/reconcile/db/GroupParametersReconciler.kt
> +            if (reconciler == null) {
still don't love that the above is called dbReconcilerReader whilst this is just REconciler (is it the Kafka one?)

2022-11-25 09:19 UTC, fenryka commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/reconcile/db/GroupParametersReconciler.kt
> +        dbReconcilerReader?.stop()
this access the var, should also use the lock

2022-11-25 09:22 UTC, nikinagy commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/reconcile/db/GroupParametersReconciler.kt
> +            if (reconciler == null) {
This is just a standard reconciler which will use the both the kafka and db reconciler in order to reconcile.

2022-11-25 09:23 UTC, fenryka commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/reconcile/db/GroupParametersReconciler.kt
> +            if (reconciler == null) {
fair! :)

2022-11-25 09:51 UTC, fenryka approved these changes
LGTM!

2022-11-25 10:28 UTC, mcgovc approved these changes
LGTM - build changes

2022-11-25 10:30 UTC, merged