CORE-8111/salt-passphrase-secret added Kubernetes secret configuratio…
corda/corda-runtime-os pull request #2616
Opened 2022-11-25 11:45 UTC by JasonSinclair95

Added functionality for the db.worker.salt and db.worker.passphrase to be passed In by the client's Kubernetes secret. 
https://r3-cev.atlassian.net/browse/CORE-8111

2022-11-25 11:49 UTC, JasonSinclair95 commented
@davidcurrie when testing the changes, I noticed that in an override file, You could specify the secret key without the secret name, value and secret key and value and secret name together without the helm chart complaining. Is this something the hem schema should deal with or...

2022-11-25 13:41 UTC, davidcurrie commented
@JasonSinclair95 - the only requirement should be that, if you specify a secret name, then you must also specify the key. The name is the trigger to use the secret rather than the value. So if they specify a key but no name then it's fine to ignore it. Likewise, if they specify a value and a secret name and key then it is fine to ignore the value.

2022-11-28 08:48 UTC, davidcurrie requested changes

2022-11-28 08:48 UTC, davidcurrie commented on charts/corda/templates/_helpers.tpl
> +      key: {{ .Values.workers.db.salt.valueFrom.secretKeyRef.key | default "salt"}}
I think this relates to the question you asked but, rather than using `default`, it would be better to have an `if` block that was conditional on `secretKeyRef.name`. If it is set, then you should require that `secretKeyRef.key` is set. If it is not set, then you should ignore `secretKeyRef.key` and use `salt`.

2022-11-28 08:48 UTC, davidcurrie commented on charts/corda/templates/_helpers.tpl
> +      key: {{ .Values.workers.db.passphrase.valueFrom.secretKeyRef.key | default "passphrase"}}
As for `SALT`, make this conditional on `secretKeyRef.name`.

2022-11-28 08:48 UTC, davidcurrie commented on charts/corda/values.yaml
> +
remember that `--` should only be used a prefix on the "leaf" entries in the tree

2022-11-28 08:48 UTC, davidcurrie commented on charts/corda/values.yaml
> +      # -- the passphrase secret configuration
```suggestion
      # the passphrase secret configuration; used in preference to value if name is set
```

2022-12-01 18:10 UTC, davidcurrie requested changes
Just tidying up the spacing but otherwise LGTM

2022-12-01 18:10 UTC, davidcurrie commented on charts/corda/templates/_helpers.tpl
> +      name: {{ .Values.workers.db.salt.valueFrom.secretKeyRef.name | quote}}
```suggestion
      name: {{ .Values.workers.db.salt.valueFrom.secretKeyRef.name | quote }}
```

2022-12-01 18:10 UTC, davidcurrie commented on charts/corda/templates/_helpers.tpl
> +      name: {{  (printf "%s-db-worker" (include "corda.fullname" .)) | quote }}
```suggestion
      name: {{ (printf "%s-db-worker" (include "corda.fullname" .)) | quote }}
```

2022-12-01 18:10 UTC, davidcurrie commented on charts/corda/templates/_helpers.tpl
> +      name: {{ .Values.workers.db.passphrase.valueFrom.secretKeyRef.name | quote}}
```suggestion
      name: {{ .Values.workers.db.passphrase.valueFrom.secretKeyRef.name | quote }}
```

2022-12-01 18:10 UTC, davidcurrie commented on charts/corda/templates/_helpers.tpl
> +      name: {{  (printf "%s-db-worker" (include "corda.fullname" .)) | quote }}
```suggestion
      name: {{ (printf "%s-db-worker" (include "corda.fullname" .)) | quote }}
```

2022-12-02 11:38 UTC, davidcurrie approved these changes
🎉

2022-12-02 12:59 UTC, merged