CORE-7939 Improve smoke tests so issuance/consume can be executed
corda/corda-runtime-os pull request #2623
Opened 2022-11-28 09:52 UTC by nkovacsx

## Overview

The goal of this PR to have a test flow (`NonValidatingNotaryTestFlow`) that is able to execute with a proper real-life workflow. In this case this means issuing states before consuming them.

Doing an issuance before consuming is not essential right now because the ledger layer is still incomplete. However, once we have a fully functional ledger these tests will work out of the box because they are following the full workflow order..

Please note that the tests that are doing actual consuming are **disabled** for now because we have no back-chain resolution as of now. However, once the back-chain resolution gets added, these tests will function when removing the `@Disabled` annotation.

2022-11-29 14:25 UTC, relyafi requested changes
Generally looking good, I like the use of private functions with function parameters to create DSL-like test cases.

2022-11-29 14:25 UTC, relyafi commented on testing/cpbs/test-cordapp/src/main/kotlin/net/cordapp/testing/testflows/NonValidatingNotaryTestFlow.kt
> +)
Does it make sense for this to be a nested inner class, given it only appears to be used internally by this flow?

2022-11-29 14:25 UTC, relyafi commented on testing/cpbs/test-cordapp/src/main/kotlin/net/cordapp/testing/testflows/NonValidatingNotaryTestFlow.kt
> +    @Suppress("unchecked_cast", "deprecation", "ComplexMethod")
Ideally these should be fixed rather than being suppressed. I'd also suggest if we really need the deprecation and unchecked cast suppressions, we suppress at the specific instance, rather than being function-wide.

2022-11-29 14:25 UTC, relyafi commented on testing/cpbs/test-cordapp/src/main/kotlin/net/cordapp/testing/testflows/NonValidatingNotaryTestFlow.kt
> +                // Since the builder will always be copied with the new attributes, we always need to re-assign it
Ewww! Have we raised this with the ledger team and got a ticket for them to fix it? It's not really a builder if it's doing this.

Would be good to have a ticket to reference in a TODO here, as this could then be revisited in future to improve efficiency.

2022-11-29 14:25 UTC, relyafi commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/flow/FlowTests.kt
> +    @Suppress("unchecked_cast")
We have a few instances of this throughout this file. Ideally we'd fix these, but if not, it would be better to suppress specific instances to avoid other unintended instances falling through the cracks in future?

In this case, I'm assuming it's the list conversions causing the problem. Do we need to cast these, given we're just checking the number of elements?

2022-11-29 14:25 UTC, relyafi commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/flow/FlowTests.kt
> +            assertThat(issuedStateRefs).hasSize(3)
Can't these lines be combined, as we are doing for the consumed state assertions below?

2022-11-29 14:25 UTC, relyafi commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/flow/FlowTests.kt
> +            assertThat(flowResultMap["consumedInputStateRefs"] as List<String>).hasSize(1)
It would be more rigorous to check that we have a state ref matching the one that was previously created as well.

2022-11-29 14:25 UTC, relyafi commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/flow/FlowTests.kt
> +            val flowResultMap = ObjectMapper().readValue<Map<String, Any>>(consumeResult.flowResult!!)
This is boilerplate code used frequently throughout these tests. Might want to consider adding an extension function to hide this, or make the function lambdas for the `*StatesAndValidateResult` supply an additional argument into this body.

2022-11-29 14:25 UTC, relyafi commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/flow/FlowTests.kt
> +            // 3. Make sure no extra states were consumed
```suggestion
            // 3. Make sure no states were consumed
```

2022-11-29 14:25 UTC, relyafi commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/flow/FlowTests.kt
> +        // 4. Consume one of the issued states twice in the same TX (as input and as ref)
Strictly speaking, using a reference state is not consuming it, so might want to refine the comment.

2022-12-02 13:53 UTC, nkovacsx commented on testing/cpbs/test-cordapp/src/main/kotlin/net/cordapp/testing/testflows/NonValidatingNotaryTestFlow.kt
> +)
Good point

2022-12-02 14:32 UTC, nkovacsx commented on testing/cpbs/test-cordapp/src/main/kotlin/net/cordapp/testing/testflows/NonValidatingNotaryTestFlow.kt
> +    @Suppress("unchecked_cast", "deprecation", "ComplexMethod")
Deprecation is only there because ledger made their `sign` function deprecated but no other versions of that function is working. :) will add a comment

2022-12-02 14:43 UTC, nkovacsx commented on testing/cpbs/test-cordapp/src/main/kotlin/net/cordapp/testing/testflows/NonValidatingNotaryTestFlow.kt
> +                // Since the builder will always be copied with the new attributes, we always need to re-assign it
I agree, will get in touch with them about this

2022-12-02 14:55 UTC, nkovacsx commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/flow/FlowTests.kt
> +    @Suppress("unchecked_cast")
I managed to reduce these, in some cases we don't need the actual type of the list, just the size, that's a good point.

2022-12-02 15:00 UTC, nkovacsx commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/flow/FlowTests.kt
> +            assertThat(flowResultMap["consumedInputStateRefs"] as List<String>).hasSize(1)
Good point!

2022-12-06 09:39 UTC, relyafi commented on testing/cpbs/test-cordapp/src/main/kotlin/net/cordapp/testing/testflows/NonValidatingNotaryTestFlow.kt
> +                // Since the builder will always be copied with the new attributes, we always need to re-assign it
Actually, isn't real application code is potentially going to have a variable number of both? There's nothing to say a CorDapp would be hard-coded to always use a fixed number, unless it was always 0 or 1.

Maybe the real answer is it'd be cleaner if the interface provided alternative methods that take a list / varargs of states. That approach would be far more efficient for large numbers of states in a transaction by removing a load of unnecessary copies.

2022-12-06 09:58 UTC, relyafi reviewed
Mostly looks good now. Still seem to be a few issues around unnecessary or inappropriately scoped `unchecked_cast` suppressions.

Re. the ledger comment - I think this is something to feed back to the ledger team, and shouldn't block integrating these changes.

2022-12-06 09:58 UTC, relyafi commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/flow/FlowTests.kt
> +            assertThat((flowResultMap["issuedStateRefs"] as List<String>)).hasSize(3)
```suggestion
            assertThat((flowResultMap["issuedStateRefs"] as List<*>)).hasSize(3)
```

We're only checking size, so can't we do the same as we're doing for the input / ref state checks below, and remove the unchecked cast suppression? Could also add this to the `assertAll` block.

2022-12-06 09:58 UTC, relyafi commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/flow/FlowTests.kt
> +            @Suppress("unchecked_cast")
Couldn't this be moved to just above line 828 so we're only suppressing for that exact instance?

2022-12-06 09:58 UTC, relyafi commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/flow/FlowTests.kt
> +    @Suppress("unchecked_cast")
A function level suppression seems overkill. What exactly is this suppressing? I can't see anything obvious that would cause this issue in the function?

2022-12-06 09:58 UTC, relyafi commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/flow/FlowTests.kt
> +    @Suppress("unchecked_cast")
A function level suppression seems overkill. What exactly is this suppressing? I can't see anything obvious that would cause this issue in the function?

2022-12-06 10:07 UTC, nkovacsx commented on testing/cpbs/test-cordapp/src/main/kotlin/net/cordapp/testing/testflows/NonValidatingNotaryTestFlow.kt
> +                // Since the builder will always be copied with the new attributes, we always need to re-assign it
Hmm, that's a good point. Let me raise a ticket for this.

2022-12-06 10:23 UTC, nkovacsx commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/flow/FlowTests.kt
> +    @Suppress("unchecked_cast")
Good point, I completely missed this occurrence

2022-12-06 13:16 UTC, relyafi approved these changes

2022-12-06 13:17 UTC, merged