CORE-8435: Cooperative Rebalace in RPC Pattern
corda/corda-runtime-os pull request #2641
Opened 2022-11-30 16:19 UTC by jujoramos

Kafka executes a rebalance within a consumer group whenever a member
joins or leaves the group. The "eager rebalance" algorithm is used by
default, and it causes a stop the world effect by revoking and
re-assigning all partitions within the group (even those that don't
need to be moved), making consumers unavailable while rebalancing.
Changes in this commit aim to reduce the unavailability window during
rebalances within the RPC message pattern by forcing the usage of the 
"incremental cooperative rebalance" algorithm [1].

- Update javadocs and tests.
- Add 'InconsistentGroupProtocolException' to the list of unrecoverable
  (fatal) exceptions while polling from the topics.
- Configure the 'rpcSender.consumer' to use 'CooperativeStickyAssignor'
  as the partition strategy, this assignor acts as the 'StickyAssignor'
  but supports cooperative rebalances (consumers can continue consuming
  from the partitions that are not reassigned).
- Configure the 'rpcResponder.consumer' to use the 'StickyAssignor' as
  the partition strategy, works as the 'RoundRobinAssignor' but reduces
  the amount of partitions to move during rebalancing. Incremental
  cooperative rebalance is not used to prevent different consumers from
  handling a task that might not be idempotent (exceptional cases where
  the partitions are assigned to new consumers without first being
  revoked by the cooperative rebalance algorithm).

[1]: https://cwiki.apache.org/confluence/display/KAFKA/Incremental+Cooperative+Rebalancing:+Support+and+Policies

2022-12-01 14:16 UTC, simon-johnson-r3 requested changes

2022-12-01 14:16 UTC, simon-johnson-r3 commented on libs/messaging/kafka-message-bus-impl/src/test/kotlin/net/corda/messagebus/kafka/config/MessageBusConfigResolverTest.kt
> +        @Suppress("unused", "LongMethod")
what's unused here that wasn't before?

2022-12-01 14:16 UTC, simon-johnson-r3 commented on libs/messaging/message-bus/src/main/kotlin/net/corda/messagebus/api/consumer/CordaConsumerRebalanceListener.kt
> +     * data. In cooperative rebalancing, it will be called at the end of a rebalance on the set of partitions being
Either this isn't that useful to know, or the text at line 14 is wrong. In other words, I don't think it's clear from this text what the developer is expected to do with this information. And it might lead them to believe they cannot commit offsets as instructed if the rebalance mode is cooperative.

I read this as meaning in the cooperative case the rebalance has been completed, but perhaps you meant the partition list is assembled prior to the actual rebalance. I think that needs clarifying.

2022-12-05 10:19 UTC, jujoramos commented on libs/messaging/kafka-message-bus-impl/src/test/kotlin/net/corda/messagebus/kafka/config/MessageBusConfigResolverTest.kt
> +        @Suppress("unused", "LongMethod")
Nothing, both methods (`consumerConfigSource` and `producerConfigSource`) were, and still are, used as the single parameter for the `@MethodSource` annotation but as a simple string, that's why IntelliJ annoyingly reports them as unused if we don't mark them with `@Suppress("unused")`.

2022-12-05 11:21 UTC, jujoramos commented on libs/messaging/message-bus/src/main/kotlin/net/corda/messagebus/api/consumer/CordaConsumerRebalanceListener.kt
> +     * data. In cooperative rebalancing, it will be called at the end of a rebalance on the set of partitions being
Under regular conditions, the `onPartitionsRevoked` method is guaranteed to be invoked before `onPartitionsAssigned`, so the developer might want to commit offsets at this point to prevent messages from being processed more than once. The docs for this method might be confusing on their own, but they make sense when read within the scope of the whole interface including the docs for the other methods, right?. (I plan to update the internal `Kafka 4 Corda Devs` with more details as well).

2022-12-05 11:51 UTC, jujoramos commented on libs/messaging/message-bus/src/main/kotlin/net/corda/messagebus/api/consumer/CordaConsumerRebalanceListener.kt
> +     * data. In cooperative rebalancing, it will be called at the end of a rebalance on the set of partitions being
Result of offline discussion with @simon-johnson-r3: remove the added lines as the specific details are not needed for a developer to implement the interface. The internal `Kafka 4 Corda Devs` will be updated with extra information and developers can always get extra details from that document.

2022-12-05 13:26 UTC, simon-johnson-r3 approved these changes

2022-12-05 15:42 UTC, fowlerrr approved these changes
LGTM.

Note that we will now have a divergence between how the db message bus works as I only wrote the greedy algorithm.  I don't think that's a problem as it's different, usually in a single process, and I probably didn't get _that_ close to Kafka anyway.  Just wanted to point it out in case it matters later.

2022-12-05 16:27 UTC, merged