CORE-7059: FlowContextProperties for Simulator
corda/corda-runtime-os pull request #2662
Opened 2022-12-05 11:25 UTC by ashutoshmeher-r3

2022-12-06 13:46 UTC, mattbradburyr3 reviewed
Comments for your consideration.

2022-12-06 13:46 UTC, mattbradburyr3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/messaging/ConcurrentFlowMessaging.kt
> +    private val flowSessionFactory: FlowSessionFactory = BaseFlowSessionFactory()
Kdocs text not updated for this extra parameter.

Also, shouldn't it be @param param_name rather than @param_name

2022-12-06 13:46 UTC, mattbradburyr3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/messaging/ConcurrentFlowMessaging.kt
> +        val sessions =
Can use destructuring declarations to avoid declaring the sessions variable, ie: 

val (initiatorSession, recipientSession) = flowSessionFactory....etc...

2022-12-06 13:46 UTC, mattbradburyr3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/messaging/ConcurrentFlowMessaging.kt
> +        flowContextPropertiesBuilder: FlowContextPropertiesBuilder?): FlowSession{
Space after FlowSession

2022-12-06 13:46 UTC, mattbradburyr3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/messaging/ConcurrentFlowMessaging.kt
Move the 'Not yet implemented.' comment to after initiateFlow() as that has now been implemented.

2022-12-06 13:46 UTC, mattbradburyr3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/flows/InjectingFlowEngine.kt
> +    private val flowChecker: FlowChecker = CordaFlowChecker(),
what's the erroneous ',' for, how come it doesn't throw an error because it's expecting another parameter?

2022-12-06 13:46 UTC, mattbradburyr3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/messaging/BaseFlowSessionFactory.kt
> +            fiber.getFlowContextProperties()
Why store FlowContextProperties on the SimFibre, why not just store them here on the FlowSession?

2022-12-06 13:46 UTC, mattbradburyr3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/messaging/SimFiber.kt
> +    fun updateFlowContextProperties(operation: Boolean, contextProperties: SimFlowContextProperties?)
The Boolean to switch between push and pop looks unnecessarily complicated, why not just have two functions:
- addFlowContextProperties(contextProperties)
- removeFlowContextProperties()

2022-12-06 13:46 UTC, mattbradburyr3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/messaging/SimFiberBase.kt
> +    private val flowContextPropertiesStack = ArrayDeque<SimFlowContextProperties>()
As discussed, I don't think a stack is the right data structure here. Flows can spawn multiple sessions which are in existence at the same time. Hence you can't use a single stack to capture the head of all the sessions. A tree structure feels like it would be a better structure. The root being the flow context properties of the RPCIntitaingFLow, with branches created for each session or subflow created in that flow, then further levels of the tree if those.

Alternatively, just a map of Flow session Ids -> FlowContextProperties 

Although there is a wider question about why the FlowContextProperties are stored on the SimFibre at all instead of on the individual FlowSessions which they relate to.

2022-12-06 13:46 UTC, mattbradburyr3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/messaging/SimFiberBase.kt
> +    private var currFlowContextProperties : SimFlowContextProperties = SimFlowContextProperties(emptyMap())
We should use full words in when naming things

2022-12-06 13:49 UTC, mattbradburyr3 reviewed
I think should have an integration test which shows the FlowContext properties working with something approximating a real cordapp

2022-12-08 03:30 UTC, ashutoshmeher-r3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/messaging/ConcurrentFlowMessaging.kt
> +    private val flowSessionFactory: FlowSessionFactory = BaseFlowSessionFactory()
Corrected

2022-12-08 03:31 UTC, ashutoshmeher-r3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/messaging/ConcurrentFlowMessaging.kt
> +        flowContextPropertiesBuilder: FlowContextPropertiesBuilder?): FlowSession{
Done.

2022-12-08 03:32 UTC, ashutoshmeher-r3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/flows/InjectingFlowEngine.kt
> +    private val flowChecker: FlowChecker = CordaFlowChecker(),
The compiler just doesn't complain, corrected it though

2022-12-08 03:35 UTC, ashutoshmeher-r3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/messaging/ConcurrentFlowMessaging.kt
Done

2022-12-08 03:36 UTC, ashutoshmeher-r3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/messaging/ConcurrentFlowMessaging.kt
> +        val sessions =
This code is reverted as per the new logic.

2022-12-08 03:38 UTC, ashutoshmeher-r3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/messaging/BaseFlowSessionFactory.kt
> +            fiber.getFlowContextProperties()
Changed the logic to store FlowContextProperties, removed the use of SimFiber

2022-12-08 03:38 UTC, ashutoshmeher-r3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/messaging/SimFiber.kt
> +    fun updateFlowContextProperties(operation: Boolean, contextProperties: SimFlowContextProperties?)
Not relevant anymore

2022-12-08 03:39 UTC, ashutoshmeher-r3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/messaging/SimFiberBase.kt
> +    private val flowContextPropertiesStack = ArrayDeque<SimFlowContextProperties>()
Changed the logic to store FlowContextProperties, removed the use of SimFiber, and storing it locally in FlowEngine, FlowSession and FlowMessaging

2022-12-08 03:40 UTC, ashutoshmeher-r3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/messaging/SimFiberBase.kt
> +    private var currFlowContextProperties : SimFlowContextProperties = SimFlowContextProperties(emptyMap())
Not relevant anymore

2022-12-08 03:41 UTC, ashutoshmeher-r3 commented
> 

Added couple of integration tests

2022-12-08 10:43 UTC, LizR3 requested changes

2022-12-08 10:43 UTC, LizR3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/messaging/SimFlowContextProperties.kt
>  }
Does this new class have a test?

2022-12-08 10:43 UTC, LizR3 commented on simulator/example-app/src/integrationTest/kotlin/net/cordacon/example/flowcontextproperties/FlowContextPropertiesTest.kt
> +        ))
Really great that these tests are here, nice one! Can we stick these lines in a list and use `joinToString(System.lineSeparator())`? I think it will be easier to read.

2022-12-08 10:43 UTC, LizR3 commented on simulator/example-app/src/integrationTest/kotlin/net/cordacon/example/flowcontextproperties/FlowContextPropertiesTest.kt
> +        ))
Same as above.

2022-12-08 10:43 UTC, LizR3 commented on simulator/example-app/src/main/kotlin/net/cordacon/example/flowcontextproperties/FlowContextPropertiesUtils.kt
> +}
I think you can use `.map` on a range to get a list, then `joinToString` means you don't need the `if`, or the string builder.

2022-12-08 10:43 UTC, LizR3 commented on simulator/example-app/src/main/kotlin/net/cordacon/example/flowcontextproperties/FlowContextPropertiesWithResponder.kt
> +}
map, joinToString. They are your friends :)

2022-12-08 10:43 UTC, LizR3 commented on simulator/example-app/src/main/kotlin/net/cordacon/example/flowcontextproperties/FlowContextPropertiesWithResponder.kt
> +        val flag = session.receive<Boolean>()
I have learned from extremely painful refactoring experience not to use Boolean if we don't actually mean "true" or "false". We end up having some third value and by then it's really hard to untangle. Stick a small [enum](https://kotlinlang.org/docs/enum-classes.html) here instead; it's cheap and quick, pass in the string for the responder and use `valueOf` to work out what it is in the flow. You can also make this "more OO" to use Kat's terminology by putting the strings into the enum, can do it via the constructor, and then just use them from there so no need for the `if`.

2022-12-08 10:43 UTC, LizR3 commented on simulator/example-app/src/main/kotlin/net/cordacon/example/flowcontextproperties/FlowContextPropertiesWithSubFlow.kt
> +
You know what I'm going to suggest here :D

2022-12-08 10:43 UTC, LizR3 commented on simulator/example-app/src/main/kotlin/net/cordacon/example/flowcontextproperties/FlowContextPropertiesWithSubFlow.kt
> +
Same thing again with enum instead of flag. I love that there are two responders, though, that's nice.

2022-12-08 10:45 UTC, LizR3 commented
This is really nice now; all my comments are about maintainability, the actual functionality looks great. Please do get someone from Platform to review too though!

2022-12-08 12:54 UTC, mattbradburyr3 reviewed
Much improved PR, looks functionally sound and with integration tests which is important. 

Some tidying up to do though.

2022-12-08 12:54 UTC, mattbradburyr3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/SimulatedVirtualNodeBase.kt
> +        injector.injectServices(flow, member, fiber, SimFlowContextProperties(emptyMap()), flowFactory)
Why are we passing the flowFactory in here, I can't see it being used anywhere

I think the factory has already done tis work to generate the flow.

2022-12-08 12:54 UTC, mattbradburyr3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/messaging/ConcurrentFlowMessaging.kt
> +        val updatedContextProperties = contextProperties.let {
This bit of code is really hard to follow, but I think it's doing something quite simple.

Ah, I see, the apply() function is not a kotlin scope function its how FlowContextProperties get set. Feels like bad naming in corda, that's what was confusing me. still feels over complicated though.

2022-12-08 12:54 UTC, mattbradburyr3 commented on simulator/runtime/src/test/kotlin/net/corda/simulator/runtime/messaging/ConcurrentFlowMessagingTest.kt
> +        val anotherSession = flowMessaging.initiateFlow(receiverX500)
Should we check that val-2 is not present on anotherSession?

2022-12-08 12:54 UTC, mattbradburyr3 commented on simulator/example-app/src/integrationTest/kotlin/net/cordacon/example/flowcontextproperties/FlowContextPropertiesTest.kt
> +        val aliceNode = simulator.createVirtualNode(alice, Flow1::class.java)
Flow 1 isn't a very descriptive name. also, it appears to be implemented in the main module of examples: simulator/example-app/src/main/kotlin/net/cordacon/example/flowcontextproperties/FlowContextPropertiesWithSubFlow.kt

This doesn't feel like the right place for a test flow, it should be with the integration tests in runtime. 

To clarify, this is not an example, it's a test. Examples should only have full cordapp examples in.

2022-12-08 12:54 UTC, mattbradburyr3 commented on simulator/example-app/src/main/kotlin/net/cordacon/example/flowcontextproperties/FlowContextPropertiesUtils.kt
> +
Should be in integrationTest for runtime, not main for examples

2022-12-08 12:54 UTC, mattbradburyr3 commented on simulator/example-app/src/main/kotlin/net/cordacon/example/flowcontextproperties/FlowContextPropertiesWithResponder.kt
> +package net.cordacon.example.flowcontextproperties
Should be in integrationTest for runtime, not main for examples

2022-12-08 12:54 UTC, mattbradburyr3 commented on simulator/example-app/src/main/kotlin/net/cordacon/example/flowcontextproperties/FlowContextPropertiesWithSubFlow.kt
> +package net.cordacon.example.flowcontextproperties
Should be in integrationTest for runtime, not main for examples

2022-12-08 12:54 UTC, mattbradburyr3 commented on simulator/example-app/src/main/kotlin/net/cordacon/example/flowcontextproperties/FlowContextPropertiesWithResponder.kt
> +@InitiatedBy("flow-context-2")
Should the subflow have the same protocol as the RPCStartable flow. 

Would it be a better test it if had a different protocol?

2022-12-08 12:54 UTC, mattbradburyr3 commented on simulator/example-app/src/integrationTest/kotlin/net/cordacon/example/flowcontextproperties/FlowContextPropertiesTest.kt
> +        "flow-1 : { key-1 : flow-1, key-2 : flow-1, key-3 : null, key-4 : null } "
Feels like there is an easier way to do this return other than manually turning it into a string. Why not json serialise the HashMap, then deserialise in the test to check the values.

2022-12-08 12:54 UTC, mattbradburyr3 commented on simulator/example-app/src/main/kotlin/net/cordacon/example/flowcontextproperties/FlowContextPropertiesWithSubFlow.kt
> +                "responder-1 : { " +
maybe line up this naming 'responder-1' with the node naming to make it easier to understand.

2022-12-08 12:54 UTC, mattbradburyr3 commented on simulator/example-app/src/integrationTest/kotlin/net/cordacon/example/flowcontextproperties/FlowContextPropertiesTest.kt
> +        val aliceNode = simulator.createVirtualNode(alice, Initiator1::class.java)
Naming is a bit ambiguous, can we make it more specific to this test. If we add 20 more integration tests, each requiring their own set of flows 'Initiator1' is going to be pretty hard to associate with the correct test.

2022-12-08 12:54 UTC, mattbradburyr3 commented on simulator/example-app/src/main/kotlin/net/cordacon/example/flowcontextproperties/FlowContextPropertiesWithResponder.kt
> +            flowEngine.flowContextProperties["key-3"] = "responder-1"
You can lift this line out of the if.

2022-12-09 12:51 UTC, ashutoshmeher-r3 commented on simulator/example-app/src/integrationTest/kotlin/net/cordacon/example/flowcontextproperties/FlowContextPropertiesTest.kt
> +        ))
Changes applied as suggested.

2022-12-09 12:53 UTC, ashutoshmeher-r3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/SimulatedVirtualNodeBase.kt
> +        injector.injectServices(flow, member, fiber, SimFlowContextProperties(emptyMap()), flowFactory)
Removed it

2022-12-09 12:53 UTC, ashutoshmeher-r3 commented on simulator/runtime/src/test/kotlin/net/corda/simulator/runtime/messaging/ConcurrentFlowMessagingTest.kt
> +        val anotherSession = flowMessaging.initiateFlow(receiverX500)
Added the check

2022-12-09 12:54 UTC, ashutoshmeher-r3 commented on simulator/example-app/src/integrationTest/kotlin/net/cordacon/example/flowcontextproperties/FlowContextPropertiesTest.kt
> +        val aliceNode = simulator.createVirtualNode(alice, Flow1::class.java)
Moved the tests to runtime

2022-12-09 12:55 UTC, ashutoshmeher-r3 commented on simulator/example-app/src/main/kotlin/net/cordacon/example/flowcontextproperties/FlowContextPropertiesWithResponder.kt
> +@InitiatedBy("flow-context-2")
Chnaged the protocol of subflows

2022-12-09 12:56 UTC, ashutoshmeher-r3 commented on simulator/example-app/src/integrationTest/kotlin/net/cordacon/example/flowcontextproperties/FlowContextPropertiesTest.kt
> +        val aliceNode = simulator.createVirtualNode(alice, Initiator1::class.java)
renamed the classes

2022-12-09 12:57 UTC, ashutoshmeher-r3 commented on simulator/example-app/src/main/kotlin/net/cordacon/example/flowcontextproperties/FlowContextPropertiesWithResponder.kt
> +            flowEngine.flowContextProperties["key-3"] = "responder-1"
This is supposed to set the flowContextProperties for only one responder, moving it out would set it for both responders.

2022-12-09 13:18 UTC, ashutoshmeher-r3 commented on simulator/example-app/src/main/kotlin/net/cordacon/example/flowcontextproperties/FlowContextPropertiesWithSubFlow.kt
> +                "responder-1 : { " +
remaned most of the keys and value, it should be easier to understand where its coming from now.

2022-12-09 13:21 UTC, ashutoshmeher-r3 commented on simulator/example-app/src/integrationTest/kotlin/net/cordacon/example/flowcontextproperties/FlowContextPropertiesTest.kt
> +        "flow-1 : { key-1 : flow-1, key-2 : flow-1, key-3 : null, key-4 : null } "
We can't access the property directly, will have to call get on each property manually anyways, so I had just converted it into string rather than making a map and dealing with serialise/ deserialise at both ends.

2022-12-09 17:25 UTC, yarivus reviewed
see my comments

2022-12-09 17:25 UTC, yarivus commented on simulator/runtime/src/integrationTest/kotlin/net/corda/simulator/runtime/flows/FlowContextPropertiesUtils.kt
> +enum class Member{
how is this definition (enum) related to the Utils source file ?

2022-12-09 17:25 UTC, yarivus commented on simulator/runtime/src/integrationTest/kotlin/net/corda/simulator/runtime/flows/FlowContextPropertiesWithResponder.kt
> +        flowEngine.flowContextProperties["key-1"] = "initiator"
I would use keys: "key-21", "key-22" etc for "flow-context-2"
(Same for "flow-context-3" - "key-31", "key-32" etc)

2022-12-09 17:25 UTC, yarivus commented on simulator/runtime/src/integrationTest/kotlin/net/corda/simulator/runtime/flows/FlowContextPropertiesTest.kt
> +    @Test
@abellagonzalo - worth having a quick look - maybe CRAFT5 can be leveraged for less code in these tests ?

2022-12-09 17:25 UTC, yarivus commented on simulator/runtime/src/integrationTest/kotlin/net/corda/simulator/runtime/flows/FlowContextPropertiesWithSubFlow.kt
> +        flowEngine.flowContextProperties["key-3"] = "subflow-2"
see my previous comment on keys

2022-12-12 09:02 UTC, ashutoshmeher-r3 commented on simulator/runtime/src/integrationTest/kotlin/net/corda/simulator/runtime/flows/FlowContextPropertiesUtils.kt
> +enum class Member{
moved it to the flow class

2022-12-12 09:15 UTC, ashutoshmeher-r3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/messaging/ConcurrentFlowMessaging.kt
> +        val updatedContextProperties = contextProperties.let {
This is how they do it in Corda. Removed one line of code though which was not needed. Should be a little less complex now.

2022-12-12 09:18 UTC, ashutoshmeher-r3 commented on simulator/runtime/src/integrationTest/kotlin/net/corda/simulator/runtime/flows/FlowContextPropertiesWithResponder.kt
> +        flowEngine.flowContextProperties["key-1"] = "initiator"
We are overriding some of the keys in the subflow/ responder, which I think will make it more complicated to understand if we follow that pattern

2022-12-12 09:32 UTC, ashutoshmeher-r3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/messaging/SimFlowContextProperties.kt
>  }
Added test for it

2022-12-12 11:36 UTC, yarivus reviewed
Some comments unresolved from my end.

2022-12-12 11:36 UTC, yarivus commented on simulator/runtime/src/integrationTest/kotlin/net/corda/simulator/runtime/flows/FlowContextPropertiesWithSubFlow.kt
> +enum class Member{
I don't understand why this enum should be part of the sub-flow ...
@mattbradburyr3 - any input on this one ?

2022-12-12 15:17 UTC, LizR3 commented on simulator/runtime/src/integrationTest/kotlin/net/corda/simulator/runtime/flows/FlowContextPropertiesTest.kt
> +    @Test
@yarivus Simulator is not real Corda; it's intended to give Cordapp devs fast feedback on their flows. So these aren't tests for real Corda, they're tests for Simulator's lighterweight classes, and have a very different API. We've already spoken a fair bit to Gonzalo.

2022-12-12 16:11 UTC, LizR3 requested changes
The `initiateFlow` being called twice looks like an error. My other comments here are me being picky; it looks good other than that one line.

2022-12-12 16:11 UTC, LizR3 commented on simulator/runtime/src/integrationTest/kotlin/net/corda/simulator/runtime/flows/FlowContextPropertiesWithResponder.kt
> +        flowMessaging.initiateFlow(participants[0])
Do we need to initiate the flow here twice?

2022-12-12 16:11 UTC, LizR3 commented on simulator/runtime/src/test/kotlin/net/corda/simulator/runtime/messaging/ConcurrentFlowMessagingTest.kt
>          )
Good catch that the flow factory isn't being used any more. However, this test is explicitly checking that the injector gets the correct values - is there something better we can use here than `any()`? Could always use Mockito's arg matchers, or implement equality on the context properties object.

This is me being picky so if it's hard for any reason it's OK.

2022-12-12 16:11 UTC, LizR3 commented on simulator/runtime/src/test/kotlin/net/corda/simulator/runtime/messaging/ConcurrentFlowMessagingTest.kt
> +            any()
Same here; worth trying to avoid `any()` in a verify (I am happier about it being in stubs). Again, if it's hard to do don't worry, we have integration tests too.

2022-12-13 04:07 UTC, ashutoshmeher-r3 commented on simulator/runtime/src/test/kotlin/net/corda/simulator/runtime/messaging/ConcurrentFlowMessagingTest.kt
>          )
Changed as suggested. Added equals to context properties class

2022-12-13 04:07 UTC, ashutoshmeher-r3 commented on simulator/runtime/src/integrationTest/kotlin/net/corda/simulator/runtime/flows/FlowContextPropertiesWithResponder.kt
> +        flowMessaging.initiateFlow(participants[0])
corrected

2022-12-13 09:26 UTC, LizR3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/messaging/SimFlowContextProperties.kt
> +
There are some rules around equality that are worth looking up, and other good examples around the codebase. At the moment this would throw an error if we looked to see if it was equal to something that wasn't a `SimFlowContextProperties`, or equal to a null, rather than returning `false`.

2022-12-13 09:56 UTC, yarivus reviewed
Some pending comments on equality from @LizR3

2022-12-13 10:06 UTC, ashutoshmeher-r3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/messaging/SimFlowContextProperties.kt
> +
fixed it

2022-12-13 15:26 UTC, LizR3 submitted a review, later dismissed
Approved from Simulator perspective; please get Corda platform approval too

2022-12-14 04:00 UTC, ashutoshmeher-r3 commented on simulator/runtime/src/integrationTest/kotlin/net/corda/simulator/runtime/flows/FlowContextPropertiesWithSubFlow.kt
> +enum class Member{
If this is about why we are using it, its to identify the member with the responder that has been used, and we are setting different properties for different members.

2022-12-14 17:35 UTC, simon-johnson-r3 requested changes

2022-12-14 17:35 UTC, simon-johnson-r3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/flows/InjectingFlowEngine.kt
> +        get() = contextProperties
I wonder if you want to take a copy of contextProperties here too as you do for subflows. The way you have it now you could potentially change the context of a running Flow externally, which the Flow wont be expecting. This isn't a problem as long as your simulation/test behaves like a real Corda would and treats this as immutable, but that puts the emphasis on the user to understand the contract.

2022-12-14 17:35 UTC, simon-johnson-r3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/messaging/BlockingQueueFlowSession.kt
> +            return (flowContextProperties as SimFlowContextProperties).toImmutableContext()
The header of this method is now out of date.

2022-12-14 17:35 UTC, simon-johnson-r3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/messaging/BlockingQueueFlowSession.kt
> +    private val flowContextProperties: FlowContextProperties
This class can only accept a `SimFlowContextProperties` to remain operational. Is there a reason to accept the base class here?

2022-12-14 17:35 UTC, simon-johnson-r3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/messaging/SimFlowContextProperties.kt
> +fun FlowContextProperties.copy() : FlowContextProperties {
I'm not convinced this is a good use of an extension function given it's public here. It makes it look like you are extending `FlowContextProperties` to be copiable, but if you tried that it would throw unexpectedly in all cases other than SimFlowContextProperties.

As `copy` is already on the public api of SimFlowContextProperties, I think it might be better if you just do any casting at the point you need a copy. At least then you can't misuse this accidentally.

2022-12-14 17:35 UTC, simon-johnson-r3 commented on simulator/runtime/src/integrationTest/kotlin/net/corda/simulator/runtime/flows/FlowContextPropertiesUtils.kt
> +fun convertFlowContextPropertiesToString(flowContextProperties: FlowContextProperties?, numberOfKeys: Int): String {
Does this need to accept a nullable FlowContextProperties? I find it unusual I would need to call this method if I didn't have an instance of it, and I think it would return weird output in that case?

2022-12-14 17:35 UTC, simon-johnson-r3 commented on simulator/runtime/src/integrationTest/kotlin/net/corda/simulator/runtime/flows/FlowContextPropertiesUtils.kt
> +fun buildResponseString(keys: List<String>, contextPropertiesMap: Map<String, FlowContextProperties>): String {
The previous function is documented even though the name describes exactly what it's for. This function isn't documented and I can't work that out from the name.

2022-12-14 17:35 UTC, simon-johnson-r3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/SimulatedVirtualNodeBase.kt
> +        injector.injectServices(flow, member, fiber, SimFlowContextProperties(emptyMap()))
Should the user of the simulator be able to set up their own initial context? The platform sets up some context now, a placeholder for account, so I expect that should at least be possible. In the future I imagine Flows will want more context to be tested against.

2022-12-15 04:40 UTC, ashutoshmeher-r3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/flows/InjectingFlowEngine.kt
> +        get() = contextProperties
Making a copy here would mean that any updates to it cannot be tracked by the flow and hence cant be propagated to subsequent subflows/responders. 

What are the different ways that the context could be changed externally, one obvious way would be to send it to the responder and have him update it. I have added a check to prevent that. 

Since the Simulator doesn't do flow checkpoints, perhaps we can add a note in the README to discourage users from doing any external change to the context property.

2022-12-15 04:40 UTC, ashutoshmeher-r3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/messaging/BlockingQueueFlowSession.kt
> +            return (flowContextProperties as SimFlowContextProperties).toImmutableContext()
Updated

2022-12-15 04:54 UTC, ashutoshmeher-r3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/messaging/BlockingQueueFlowSession.kt
> +    private val flowContextProperties: FlowContextProperties
The flow session is internally created by simulator, and it always receives a SimFlowContextProperties, SimFlowContextProperties has a function that converts it into an immutable one.

2022-12-15 04:55 UTC, ashutoshmeher-r3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/messaging/SimFlowContextProperties.kt
> +fun FlowContextProperties.copy() : FlowContextProperties {
Changed it to a function instead

2022-12-15 04:56 UTC, ashutoshmeher-r3 commented on simulator/runtime/src/integrationTest/kotlin/net/corda/simulator/runtime/flows/FlowContextPropertiesUtils.kt
> +fun convertFlowContextPropertiesToString(flowContextProperties: FlowContextProperties?, numberOfKeys: Int): String {
This is the test which receives the context from a map, hence it was needed to be nullable, changed it however to be non-nullable

2022-12-15 04:57 UTC, ashutoshmeher-r3 commented on simulator/runtime/src/integrationTest/kotlin/net/corda/simulator/runtime/flows/FlowContextPropertiesUtils.kt
> +fun buildResponseString(keys: List<String>, contextPropertiesMap: Map<String, FlowContextProperties>): String {
Added documentation to it, it build a response string from a map of string to flowcontextproperties, which is needed to be returned by the rpc flow.

2022-12-15 04:58 UTC, ashutoshmeher-r3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/SimulatedVirtualNodeBase.kt
> +        injector.injectServices(flow, member, fiber, SimFlowContextProperties(emptyMap()))
This is where is rpc flow is called. Is there an API which allows the user to pass its own context here?

2022-12-15 10:01 UTC, simon-johnson-r3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/flows/InjectingFlowEngine.kt
> +        get() = contextProperties
To be clearer I'm suggesting
```
InjectingFlowEngine(
...
    contextProperties: FlowContextProperties,  // <- not a member property here, just a parameter
...
```
and then:
```
    private val contextProperties = contextProperties.copy()
```
The subflow context is created from `contextProperties` the member val at line 52 so that should be fine?

2022-12-15 10:04 UTC, simon-johnson-r3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/messaging/BlockingQueueFlowSession.kt
> +    private val flowContextProperties: FlowContextProperties
Yes, but I'm asking why does this class not accept a `SimFlowContextProperties` as a parameter type? That's all you ever pass it as you point out, and the class cannot accept any other type of `FlowContextProperties` and operate correctly. You wouldn't normally pass a base class type in those circumstances.

2022-12-15 10:08 UTC, simon-johnson-r3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/SimulatedVirtualNodeBase.kt
> +        injector.injectServices(flow, member, fiber, SimFlowContextProperties(emptyMap()))
It's internal to Corda, that is, when you look at a contextProperties in a new flow you would find that Corda has already set some up for you. At the moment it's just this one, but that will expand in the future:
https://github.com/corda/corda-runtime-os/blob/a293ce0f517b0bb75675e61d097415015e7c2c3b/components/flow/flow-rpcops-service-impl/src/main/kotlin/net/corda/flow/rpcops/impl/v1/FlowRPCOpsImpl.kt#L136

The writer of any test which uses the simulator will want to set up similar platform properties which the Flow can see in its context. The content doesn't matter so much, I would leave the test author to determine what they need for their particular test.

2022-12-15 13:39 UTC, ashutoshmeher-r3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/flows/InjectingFlowEngine.kt
> +        get() = contextProperties
Made the changes as suggested

2022-12-15 13:40 UTC, ashutoshmeher-r3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/messaging/BlockingQueueFlowSession.kt
> +    private val flowContextProperties: FlowContextProperties
Changed as suggested

2022-12-15 13:40 UTC, ashutoshmeher-r3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/SimulatedVirtualNodeBase.kt
> +        injector.injectServices(flow, member, fiber, SimFlowContextProperties(emptyMap()))
Added a new function which allows users to pass a map

2022-12-15 14:37 UTC, simon-johnson-r3 approved these changes, later dismissed

2022-12-15 14:41 UTC, LizR3 approved these changes, later dismissed

2022-12-15 15:52 UTC, LizR3 approved these changes

2022-12-15 15:53 UTC, merged