CORE-7248 Add plugin loading and selection logic with tests
corda/corda-runtime-os pull request #2687
Opened 2022-12-06 22:51 UTC by nkovacsx

## Overview

This PR introduces the loading mechanism of the classes that implement `PluggableNotaryClientFlowProvider` from the sandbox. These classes are used to instantiate a `PluggableNotaryClientFlow` and they will be stored inside the `PluggableNotaryClientFlowFactoryImpl` class. 

This factory can be used to instantiate a plugin of a given type (if it is stored in the factory).

This factory is injectable to flows, for example it will be injected to the UTXO finality flow that will instantiate the proper notary client flow provider.

## Tests

Multiple tests were created to test the plugin loading logic. The `NonValidatingNotaryTestFlow` has been renamed to `NotarisationTestFlow` because from now on it will be runnable with a custom plugins as well, not just the non-validating one. 

An extra parameter has been added called `pluginType` which will define the plugin that should be used for the notarisation. This will default to `corda.notary.type.non-validating` so that the non-validating plugin will be used by default. This way the existing tests will work just as before.

Two new "plugins" has been added to the test CPB, one invalid, and one valid (returns empty signature list but throws no exception).

2022-12-07 13:43 UTC, relyafi requested changes
Broadly looks good. I like that the test flow can now support different plugins, but have concerns about the fact type is being explicitly set instead of using MGM data.

2022-12-07 13:43 UTC, relyafi commented on components/virtual-node/sandbox-notary/detekt-baseline.xml
> +</SmellBaseline>
Do we need this file given there's no suppressions?

2022-12-07 13:43 UTC, relyafi commented on notary-plugins/notary-plugin-non-validating/notary-plugin-non-validating-client/src/main/kotlin/com/r3/corda/notary/plugin/nonvalidating/client/NonValidatingNotaryClientFlowProvider.kt
> + * A provider class that will instantiates a [NonValidatingNotaryClientFlowImpl].
```suggestion
 * A provider class that will instantiate a [NonValidatingNotaryClientFlowImpl].
```

2022-12-07 13:43 UTC, relyafi commented on testing/cpbs/test-cordapp/src/main/kotlin/net/cordapp/testing/notary/plugin/valid/ValidNotaryClientFlow.kt
> +        return emptyList()
Is this realistic, or should we always be returning a (single) signature?

2022-12-07 13:43 UTC, relyafi commented on components/virtual-node/sandbox-notary/src/main/kotlin/net/corda/ledger/notary/plugin/factory/PluggableNotaryClientFlowFactoryImpl.kt
> +            }
It feels like we're missing a couple of bits of validation here:

- Is the implication of getting `notaryProviderTypes.first()` that we could have providers which have defined the annotation more than once? if so, shouldn't this be an error condition that fails startup?
- What happens if we get two different providers that try and register with the same type? Similarly should we guard against this?

2022-12-07 13:43 UTC, relyafi commented on components/virtual-node/sandbox-notary/src/main/kotlin/net/corda/ledger/notary/plugin/factory/PluggableNotaryClientFlowFactoryImpl.kt
> +    override fun create(notary: Party, type: String, stx: UtxoSignedTransaction): PluggableNotaryClientFlow {
It doesn't seem right that this allows type to be specified. Shouldn't this be using the MGM notary metadata to determine the correct type, based on the supplied notary party?

2022-12-07 13:43 UTC, relyafi commented on testing/cpbs/test-cordapp/src/main/kotlin/net/cordapp/testing/testflows/NotarisationTestFlow.kt
>          // TODO CORE-6996 For now `NotaryLookup` is still work in progress, once it is finished, we
Are we at a point where this can be fixed now? We're 1 week away from beta so if this is still not working we need to escalate with the MGM team ASAP.

2022-12-07 13:43 UTC, relyafi commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/flow/FlowTests.kt
> +
Should these be smoke tests, or unit tests? We might be able to do away with the specific plugin implementations and use mocks by doing as unit tests.

2022-12-07 13:43 UTC, relyafi commented on components/virtual-node/sandbox-notary/src/main/kotlin/net/corda/ledger/notary/plugin/factory/PluggableNotaryClientFlowFactoryImpl.kt
> +                    "caused by: ${e.message}")
```suggestion
            throw CordaRuntimeException("Exception while trying to create notary client with name: $type", e)
```

There's already a constructor for this exception that takes cause as an explicit argument.

2022-12-07 13:43 UTC, relyafi commented on components/virtual-node/sandbox-notary/src/main/kotlin/net/corda/ledger/notary/plugin/factory/PluggableNotaryClientFlowFactoryImpl.kt
> +                            "but was not present in ${provider.javaClass.name}."
```suggestion
                    "A @PluggableNotaryType annotation must exist on every PluggableNotaryClientFlowProvider " +
                            "but was not present in ${provider.javaClass.name}. Skipping provider."
```

2022-12-09 03:36 UTC, nkovacsx commented on components/virtual-node/sandbox-notary/src/main/kotlin/net/corda/ledger/notary/plugin/factory/PluggableNotaryClientFlowFactoryImpl.kt
> +            }
1. It is not possible to add `@PluggableNotaryType` twice because it is not a repeatable annotation. That being said, I'm happy to add a check just in case. An extra check it couldn't hurt. Or we can use `single` instead of `first`.

2. Hmm that's a good point.

2022-12-09 04:13 UTC, nkovacsx commented on components/virtual-node/sandbox-notary/detekt-baseline.xml
> +</SmellBaseline>
Yes, unfortunately detekt will complain if there's no baseline at all. 😞

2022-12-09 04:37 UTC, nkovacsx commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/flow/FlowTests.kt
> +
Good point, smoke tests might be overkill for these tests. Will move them to a unit test.

2022-12-09 04:39 UTC, nkovacsx commented on testing/cpbs/test-cordapp/src/main/kotlin/net/cordapp/testing/notary/plugin/valid/ValidNotaryClientFlow.kt
> +        return emptyList()
I removed this flow now, it was moved to unit tests

2022-12-09 04:52 UTC, nkovacsx commented on components/virtual-node/sandbox-notary/src/main/kotlin/net/corda/ledger/notary/plugin/factory/PluggableNotaryClientFlowFactoryImpl.kt
> +    override fun create(notary: Party, type: String, stx: UtxoSignedTransaction): PluggableNotaryClientFlow {
That's fair.

2022-12-09 06:07 UTC, nkovacsx commented on testing/cpbs/test-cordapp/src/main/kotlin/net/cordapp/testing/testflows/NotarisationTestFlow.kt
>          // TODO CORE-6996 For now `NotaryLookup` is still work in progress, once it is finished, we
The `NotaryLookup`'s `notaryServices` call returns the notary service identity correctly but we still don't have a notary "worker" selection logic atm. Since we cannot initiate a session with the service identity (it's not an actual vnode) we can't use that until we actually have the worker vnode identity.

2022-12-09 08:54 UTC, relyafi commented on components/virtual-node/sandbox-notary/src/main/kotlin/net/corda/ledger/notary/plugin/factory/PluggableNotaryClientFlowFactoryImpl.kt
> +            }
For point 1, yes I think `single` would be preferable - if our assumption is broken in future, this will result in a clear, predictable failure as opposed to the system appearing to work but potentially doing the wrong thing.

2022-12-09 08:57 UTC, relyafi commented on components/virtual-node/sandbox-notary/src/main/kotlin/net/corda/ledger/notary/plugin/factory/PluggableNotaryClientFlowFactoryImpl.kt
> +    override fun create(notary: Party, type: String, stx: UtxoSignedTransaction): PluggableNotaryClientFlow {
I think it's a philosophical thing, but my view would be that part of the small interfaces rule is you only pass in what needs to be passed in on an API. The crucial information needed to select the plugin is the notary, and internally it can use the notary lookup service. I think that's preferable to exposing extra arguments that the caller can get wrong.

2022-12-09 10:39 UTC, nkovacsx commented on components/virtual-node/sandbox-notary/src/main/kotlin/net/corda/ledger/notary/plugin/factory/PluggableNotaryClientFlowFactoryImpl.kt
> +    override fun create(notary: Party, type: String, stx: UtxoSignedTransaction): PluggableNotaryClientFlow {
Okay, that makes sense.

2022-12-09 11:26 UTC, relyafi commented on testing/cpbs/test-cordapp/src/main/kotlin/net/cordapp/testing/testflows/NotarisationTestFlow.kt
>          // TODO CORE-6996 For now `NotaryLookup` is still work in progress, once it is finished, we
So just to be clear, it's not that we think there's anything wrong / missing with the MGM API, it's just that we haven't hooked it up / reinstated round robin selection etc. yet?

2022-12-09 11:29 UTC, nkovacsx commented on testing/cpbs/test-cordapp/src/main/kotlin/net/cordapp/testing/testflows/NotarisationTestFlow.kt
>          // TODO CORE-6996 For now `NotaryLookup` is still work in progress, once it is finished, we
That's correct. The MGM API does return the correct notary service identity and plugin class we just need to add the round-robin selection logic. However, that'll need to be in a different PR as it is not in the scope of this ticket.

2022-12-09 11:42 UTC, relyafi commented on testing/cpbs/test-cordapp/src/main/kotlin/net/cordapp/testing/testflows/NotarisationTestFlow.kt
>          // TODO CORE-6996 For now `NotaryLookup` is still work in progress, once it is finished, we
Ok, as discussed this will be in scope of https://r3-cev.atlassian.net/browse/CORE-8760

2022-12-09 19:11 UTC, nkovacsx commented on testing/cpbs/test-cordapp/src/main/kotlin/net/cordapp/testing/testflows/NotarisationTestFlow.kt
>          // TODO CORE-6996 For now `NotaryLookup` is still work in progress, once it is finished, we
We discussed this offline. Using the notary worker lookup is impossible as it is an internal service. This test will go away after beta anyway so we won't spend more time working on it.

2022-12-12 10:04 UTC, relyafi requested changes

2022-12-12 10:04 UTC, relyafi commented on components/notary/notary-worker-selection/build.gradle
> +    implementation 'net.corda:corda-ledger-common'
I think there is a question (for both this and the impl module) as to whether these should be standalone modules, or should be submodules of either the ledger or flow component modules. We have a clear ledger dependency here, so it wouldn't be possible to use this without ledger anyway.

I'm not too concerned either way, but others might be.

2022-12-12 10:04 UTC, relyafi commented on components/notary/notary-worker-selection/build.gradle
> +description 'Corda Sandbox Notary'
Looks like a copy / paste error.

2022-12-12 10:04 UTC, relyafi commented on components/notary/notary-worker-selection-impl/build.gradle
> +description 'Corda Sandbox Notary'
Looks like a copy / paste error.

2022-12-12 10:04 UTC, relyafi commented on components/notary/notary-worker-selection/src/main/kotlin/net/corda/ledger/notary/worker/selection/NotaryWorkerSelectorService.kt
> + */
This is mostly describing implementation detail in an interface - the "current" implemented strategy is set by the implementation, not the interface.

A good KDoc here should describe what a user of the API needs to know, not how it's implemented.

2022-12-12 10:04 UTC, relyafi commented on components/notary/notary-worker-selection/src/main/kotlin/net/corda/ledger/notary/worker/selection/NotaryWorkerSelectorService.kt
> +    fun next(list: List<Party>): Party
Similarly, consider whether this has inadvertently encoded implementation detail. From an API perspective, I want to pass in a notary service party, and get back a single notary worker. I shouldn't be having to provide lists of available workers (that should be abstracted by the framework), and calling the function `next` implies a certain behavior in how the worker is selected.

I suspect what we really want is:

- The service _implementation_ has access to the service that can lookup services to members
- The function should be called something like `getVirtualNodeForService`, so as not to suggest how that decision is made.

2022-12-12 10:04 UTC, relyafi commented on components/notary/notary-worker-selection/src/main/kotlin/net/corda/ledger/notary/worker/selection/NotaryWorkerSelectorService.kt
> + * Performs a selection of notary workers for notary cluster. Used by notary client, which implements idempotent timed-flow logic:
Make sure that we are referring to things as notary _virtual nodes_, not _workers_, throughout comments, APIs etc. Remember we retired the worker terminology due to it being confusing with the C5 worker concept.

2022-12-12 10:04 UTC, relyafi commented on components/notary/notary-worker-selection-impl/src/main/kotlin/net/corda/ledger/notary/worker/selection/impl/NotaryWorkerSelectorServiceImpl.kt
> +            list[selection.getAndUpdate { (it + 1) % list.size }]
Going back to the comments on the interface, this code shows how it's inappropriate to be passing in the list of notary vnodes on each call - the list could be different each time, which would defeat the object of the selection logic. This may not be a corner case either as I assume being a singleton this will be shared across multiple notary services on a network, so we could legitimately be dealing with different lists on each call.

2022-12-12 10:04 UTC, relyafi commented on components/notary/notary-worker-selection-impl/src/main/kotlin/net/corda/ledger/notary/worker/selection/impl/NotaryWorkerSelectorServiceImpl.kt
> +            selection.set(0)
This is a good way of recovering / continuing gracefully, but we might want to consider logging a warning message, as it potentially indicates something that needs investigating.

2022-12-12 10:04 UTC, relyafi commented on components/notary/notary-worker-selection-impl/src/test/kotlin/net/corda/ledger/notary/worker/selection/impl/NotaryWorkerSelectorServiceImplTest.kt
> +class NotaryWorkerSelectorServiceImplTest {
I'd suggest a test case for different notary service requests being interleaved as well. We will need to fix up the selector interface first.

2022-12-12 10:04 UTC, relyafi commented on components/virtual-node/sandbox-notary/src/main/kotlin/net/corda/ledger/notary/plugin/factory/PluggableNotaryClientFlowFactory.kt
> +        val nextWorker = selectWorker(notaryService)
Can be inlined where `nextWorker` is used.

2022-12-12 10:04 UTC, relyafi commented on components/virtual-node/sandbox-notary/src/main/kotlin/net/corda/ledger/notary/plugin/factory/PluggableNotaryClientFlowFactory.kt
> +    }
This feels to me to be something that should be abstracted by the selector service; the contract with the selector service is "I give you a notary service, you give me a notary worker back (and I don't care how you decided which to give me)"

2022-12-12 10:04 UTC, relyafi commented on components/virtual-node/sandbox-notary/src/main/kotlin/net/corda/ledger/notary/plugin/factory/PluggableNotaryClientFlowFactory.kt
> +            if (notaryProviderTypes.size > 1) {
Can be an `else if` with previous block.

2022-12-12 10:04 UTC, relyafi commented on components/virtual-node/sandbox-notary/src/main/kotlin/net/corda/ledger/notary/plugin/factory/PluggableNotaryClientFlowFactory.kt
> +            val currentProvider = pluggableNotaryClientFlowProviders[providerType]
Can be inlined on next line.

2022-12-12 10:04 UTC, relyafi commented on components/virtual-node/sandbox-notary/src/test/kotlin/net/corda/ledger/notary/plugin/factory/PluggableNotaryClientFlowFactoryTest.kt
> +        )
If this test fails it will raise an unhandled exception, which isn't great. Should probably use `assertDoesNotThrow` around this.

2022-12-12 10:04 UTC, relyafi commented on components/virtual-node/sandbox-notary/src/test/kotlin/net/corda/ledger/notary/plugin/factory/PluggableNotaryClientFlowFactoryTest.kt
> +    @Test
We probably also want a test case that has multiple valid entries (for different notary services).

2022-12-12 10:15 UTC, nkovacsx commented on components/notary/notary-worker-selection/build.gradle
> +    implementation 'net.corda:corda-ledger-common'
Okay, that's a fair point. Tbh I wasn't sure if we want to put notary stuff under ledger atm but we already introduced a dependency anyway so I'm happy to move this.

2022-12-12 10:15 UTC, nkovacsx commented on components/notary/notary-worker-selection/build.gradle
> +description 'Corda Sandbox Notary'
Yes, thanks!

2022-12-12 10:16 UTC, nkovacsx commented on components/notary/notary-worker-selection/src/main/kotlin/net/corda/ledger/notary/worker/selection/NotaryWorkerSelectorService.kt
> +    fun next(list: List<Party>): Party
That's a good point, thanks

2022-12-12 11:57 UTC, nkovacsx commented on components/virtual-node/sandbox-notary/src/main/kotlin/net/corda/ledger/notary/plugin/factory/PluggableNotaryClientFlowFactory.kt
> +    }
Yeah you are right on this, selector service will do this part now.

2022-12-12 12:09 UTC, nkovacsx commented on components/notary/notary-worker-selection-impl/src/test/kotlin/net/corda/ledger/notary/worker/selection/impl/NotaryWorkerSelectorServiceImplTest.kt
> +class NotaryWorkerSelectorServiceImplTest {
I'm not sure what you mean by this

2022-12-12 12:19 UTC, nkovacsx commented on components/virtual-node/sandbox-notary/src/test/kotlin/net/corda/ledger/notary/plugin/factory/PluggableNotaryClientFlowFactoryTest.kt
> +    @Test
Added an extra case

2022-12-12 12:19 UTC, nkovacsx commented on components/virtual-node/sandbox-notary/src/test/kotlin/net/corda/ledger/notary/plugin/factory/PluggableNotaryClientFlowFactoryTest.kt
> +        )
added

2022-12-12 12:19 UTC, nkovacsx commented on components/virtual-node/sandbox-notary/src/main/kotlin/net/corda/ledger/notary/plugin/factory/PluggableNotaryClientFlowFactory.kt
> +            val currentProvider = pluggableNotaryClientFlowProviders[providerType]
done

2022-12-12 12:19 UTC, nkovacsx commented on components/virtual-node/sandbox-notary/src/main/kotlin/net/corda/ledger/notary/plugin/factory/PluggableNotaryClientFlowFactory.kt
> +            if (notaryProviderTypes.size > 1) {
added

2022-12-12 12:19 UTC, nkovacsx commented on components/virtual-node/sandbox-notary/src/main/kotlin/net/corda/ledger/notary/plugin/factory/PluggableNotaryClientFlowFactory.kt
> +        val nextWorker = selectWorker(notaryService)
done

2022-12-12 12:20 UTC, nkovacsx commented on components/notary/notary-worker-selection-impl/src/main/kotlin/net/corda/ledger/notary/worker/selection/impl/NotaryWorkerSelectorServiceImpl.kt
> +            selection.set(0)
This is no longer relevant as we are using a random selection now.

2022-12-12 12:20 UTC, nkovacsx commented on components/notary/notary-worker-selection-impl/src/main/kotlin/net/corda/ledger/notary/worker/selection/impl/NotaryWorkerSelectorServiceImpl.kt
> +            list[selection.getAndUpdate { (it + 1) % list.size }]
This is no longer relevant as we are using a random selection now.

2022-12-12 12:20 UTC, nkovacsx commented on components/notary/notary-worker-selection/src/main/kotlin/net/corda/ledger/notary/worker/selection/NotaryWorkerSelectorService.kt
> + * Performs a selection of notary workers for notary cluster. Used by notary client, which implements idempotent timed-flow logic:
Modified to VNode where applicable

2022-12-12 12:21 UTC, relyafi commented on components/notary/notary-worker-selection-impl/src/test/kotlin/net/corda/ledger/notary/worker/selection/impl/NotaryWorkerSelectorServiceImplTest.kt
> +class NotaryWorkerSelectorServiceImplTest {
So, have a test case where we have two notary services (each with their own set of workers), and then call the selector for service A, service B, service A etc. and ensure the returned worker is correct. That would prove state is maintained independently.

(If we're selecting randomly now this might be harder - best we could probably do is check that each service has returned a worker that is associated with that service)

2022-12-12 13:13 UTC, relyafi commented on components/ledger/notary-worker-selection-impl/build.gradle
> +description 'Corda notary virtual node selector - API'
I think this should be implementation (and the other gradle file API)

2022-12-12 13:13 UTC, relyafi commented on components/ledger/notary-worker-selection-impl/src/main/kotlin/net/corda/ledger/notary/worker/selection/impl/NotaryVirtualNodeSelectorServiceImpl.kt
> +        val workers = notaryVirtualNodeLookup.getNotaryVirtualNodes(serviceIdentity.name)
Can be inlined on next line.

2022-12-12 13:13 UTC, relyafi commented on components/notary/notary-worker-selection/src/main/kotlin/net/corda/ledger/notary/worker/selection/NotaryWorkerSelectorService.kt
> +    fun next(list: List<Party>): Party
@nkovacsx reopening as I still see references to `next`.

2022-12-12 13:19 UTC, relyafi commented on components/ledger/notary-worker-selection/src/main/kotlin/net/corda/ledger/notary/worker/selection/NotaryVirtualNodeSelectorService.kt
> + * A service that is used to select the next notary virtual node for the given notary service.
```suggestion
 * A service that is used to select a notary virtual node for the given notary service.
```

The current text still implies something about how the worker is selected.

2022-12-12 15:08 UTC, nkovacsx commented on components/notary/notary-worker-selection/src/main/kotlin/net/corda/ledger/notary/worker/selection/NotaryWorkerSelectorService.kt
> +    fun next(list: List<Party>): Party
Oh yes, forgot to commit this.

2022-12-12 16:50 UTC, relyafi submitted a review, later dismissed

2022-12-12 17:42 UTC, blsemo commented on components/ledger/notary-worker-selection-impl/src/main/java/net/corda/ledger/notary/worker/selection/impl/package-info.java
> +package net.corda.ledger.notary.worker.selection.impl;
Why do we need to export an impl package? That is usually a sign of something slightly dodgy.

2022-12-12 17:42 UTC, blsemo commented on components/ledger/notary-worker-selection-impl/src/main/kotlin/net/corda/ledger/notary/worker/selection/impl/NotaryVirtualNodeSelectorServiceImpl.kt
> +    service = [ UsedByFlow::class ],
Shouldn't that also list an interface that is used to get hold of this service impl? I.e. `NotaryVirtualNodeSelectorService`?

2022-12-12 17:42 UTC, blsemo commented on components/virtual-node/sandbox-notary/src/main/kotlin/net/corda/ledger/notary/plugin/factory/PluggableNotaryClientFlowFactory.kt
> +class PluggableNotaryClientFlowFactory @Activate constructor(
How do you get OSGi to provide an instance of this class if it has no service specific interface it implements?

2022-12-12 17:47 UTC, nkovacsx commented on components/virtual-node/sandbox-notary/src/main/kotlin/net/corda/ledger/notary/plugin/factory/PluggableNotaryClientFlowFactory.kt
> +class PluggableNotaryClientFlowFactory @Activate constructor(
Using `corda.marker.only:Boolean=true` should mean that we only have the marker interfaces (UsedByFlow etc.) so it shouldn't need a specific service interface. Or at least that's what I understood.

2022-12-12 17:47 UTC, nkovacsx commented on components/ledger/notary-worker-selection-impl/src/main/kotlin/net/corda/ledger/notary/worker/selection/impl/NotaryVirtualNodeSelectorServiceImpl.kt
> +    service = [ UsedByFlow::class ],
Yeah, that's a good point, I missed that.

2022-12-12 17:48 UTC, nkovacsx commented on components/ledger/notary-worker-selection-impl/src/main/java/net/corda/ledger/notary/worker/selection/impl/package-info.java
> +package net.corda.ledger.notary.worker.selection.impl;
That's just my fault, I'm used to adding exports to all modules, removing now.

2022-12-12 18:05 UTC, blsemo approved these changes

2022-12-12 18:09 UTC, relyafi approved these changes
LGTM

2022-12-12 18:46 UTC, ronanbrowne approved these changes
LGTM ( build)

2022-12-12 18:47 UTC, merged