CORE-8433 Public API for filtering transactions
corda/corda-runtime-os pull request #2699
Opened 2022-12-08 12:59 UTC by lankydan

2022-12-08 13:24 UTC, vlajos commented on components/ledger/ledger-common-flow-api/src/main/kotlin/net/corda/ledger/common/flow/transaction/filtered/factory/ComponentGroupFilterParameters.kt
> +    data class AuditProof<T : Any>(override val componentGroupIndex: Int, val deserializedClass: Class<T>, val predicate: Predicate<T>) : ComponentGroupFilterParameters {
docblock became outdated.

2022-12-08 13:24 UTC, vlajos commented on testing/ledger/ledger-utxo-testkit/src/main/kotlin/net/corda/ledger/utxo/testkit/UtxoSignedTransactionExample.kt
> +import java.time.Instant
Is this used?

2022-12-08 13:24 UTC, vlajos commented on components/ledger/ledger-utxo-flow/src/main/kotlin/net/corda/ledger/utxo/flow/impl/transaction/filtered/UtxoFilteredTransactionBuilderImpl.kt
> +        // only filters out the notary, adjust the lambda to also filter out time window
is this a todo?

2022-12-08 16:36 UTC, blsemo requested changes, later dismissed
The rules for filtering the outputs need to be fixed to match what the `UtxoFilteredTransactionImpl` expects to find in the filtered transaction.
Ideally write a test that use the UtxoFiltereredTransactionBuilder and then tries to load filtered outputs.

2022-12-08 16:36 UTC, blsemo commented on components/ledger/ledger-utxo-flow/src/main/kotlin/net/corda/ledger/utxo/flow/impl/transaction/filtered/UtxoFilteredTransactionBuilderImpl.kt
> +    @Suspendable
If you filter the output states, you need to filter the output state infos as well. That's a bit of a pain with the predicates, of course.

2022-12-08 16:36 UTC, blsemo commented on components/ledger/ledger-utxo-flow/src/main/kotlin/net/corda/ledger/utxo/flow/impl/transaction/filtered/UtxoFilteredTransactionBuilderImpl.kt
> +    override fun withCommands(): UtxoFilteredTransactionBuilderInternal {
Similar to outputs - if you filter the commands, you want to apply the same filter to the command infos.

2022-12-08 16:36 UTC, blsemo commented on components/ledger/ledger-utxo-flow/src/main/kotlin/net/corda/ledger/utxo/flow/impl/transaction/filtered/UtxoFilteredTransactionBuilderImpl.kt
> +        // only filters out the notary, adjust the lambda to also filter out time window
That filter doesn't look right - I think we want to be able to specify to filter either notary or timeWindow or both. See API PR.

2022-12-09 14:34 UTC, blsemo reviewed
Nearly there, but I think there is still a slight logic flaw as in that the output state infos are inluded when output states are a size only proof (and that is a very common use case for the notary, so we need to make sure it's correct and tested properly).

2022-12-09 14:34 UTC, blsemo commented on components/ledger/ledger-utxo-flow/src/main/kotlin/net/corda/ledger/utxo/flow/impl/transaction/filtered/factory/UtxoFilteredTransactionFactoryImpl.kt
> +        val notaryAndTimeWindow = if (filteredTransactionBuilder.notary || filteredTransactionBuilder.timeWindow) {
Nice, that's the kind of logic I was thinking of.

2022-12-09 14:34 UTC, blsemo commented on components/ledger/ledger-utxo-flow/src/main/kotlin/net/corda/ledger/utxo/flow/impl/transaction/filtered/factory/UtxoFilteredTransactionFactoryImpl.kt
> +                    filteredTransactionBuilder.outputStates?.let { _ ->
You probably need to check if the outputStates are an AUDIT proof - if there's a size only proof, we shouldn't include the infos. Same for commands.

2022-12-09 14:34 UTC, blsemo commented on components/ledger/ledger-utxo-flow/src/test/kotlin/net/corda/ledger/utxo/flow/impl/transaction/filtered/factory/UtxoFilteredTransactionFactoryImplTest.kt
> +    fun `does not include output state infos if the output state component group is not included`() {
Should have a test `does not inlude output state infos if the output state component group is size only proof`.

2022-12-09 15:00 UTC, blsemo approved these changes, later dismissed
LGTM

2022-12-12 12:33 UTC, blsemo approved these changes

2022-12-12 12:36 UTC, merged