CORE-6057: Add down/error component name to SubscriptionDominoTileBase log
corda/corda-runtime-os pull request #2710
Opened 2022-12-12 11:06 UTC by yift-r3

2022-12-12 14:38 UTC, fowlerrr approved these changes, later dismissed
LifecycleProcessor changes look okay

2022-12-13 09:29 UTC, williamvigorr3 commented on components/domino-logic/src/main/kotlin/net/corda/lifecycle/domino/logic/util/SubscriptionDominoTileBase.kt
> +                updateState(StoppedDueToChildStopped)
We no longer set `StoppedDueToError`, if `LifecycleStatus.ERROR`. Looks like this is the correct behavour, going off what complex domino tile does.

2022-12-13 14:47 UTC, williamvigorr3 commented on components/domino-logic/src/main/kotlin/net/corda/lifecycle/domino/logic/util/SubscriptionDominoTileBase.kt
> +                updateState(StoppedDueToChildStopped)
Just checking you made this change on purpose?

2022-12-13 14:58 UTC, yift-r3 commented on components/domino-logic/src/main/kotlin/net/corda/lifecycle/domino/logic/util/SubscriptionDominoTileBase.kt
> +                updateState(StoppedDueToChildStopped)
Sorry, missed that comment...

2022-12-13 15:41 UTC, williamvigorr3 approved these changes
LGTM

2022-12-13 15:49 UTC, williamvigorr3 requested changes

2022-12-13 15:49 UTC, williamvigorr3 commented on components/domino-logic/src/main/kotlin/net/corda/lifecycle/domino/logic/util/SubscriptionDominoTileBase.kt
> +                if (status == LifecycleStatus.ERROR) {
Should this be reversed?

2022-12-13 15:53 UTC, yift-r3 commented on components/domino-logic/src/main/kotlin/net/corda/lifecycle/domino/logic/util/SubscriptionDominoTileBase.kt
> +                if (status == LifecycleStatus.ERROR) {
Yes, it should

2022-12-14 08:47 UTC, williamvigorr3 approved these changes
LGTM

2022-12-14 10:43 UTC, merged