CORE-6684: Custom Serializer Loading for Simulator
corda/corda-runtime-os pull request #2711
Opened 2022-12-12 13:51 UTC by ashutoshmeher-r3

2022-12-12 14:05 UTC, mattbradburyr3 submitted a review, later dismissed
Looks good to me, but I'd like Liz to okay it.

2022-12-12 14:23 UTC, fenryka requested changes
One comment about test names

2022-12-12 14:23 UTC, fenryka commented on simulator/runtime/src/test/kotlin/net/corda/simulator/runtime/config/DefaultConfigurationBuilderTest.kt
> +    fun `should allow registration of custom serializer via configuration`(){
this doesn't test what the test name says

2022-12-13 07:49 UTC, ashutoshmeher-r3 commented on simulator/runtime/src/test/kotlin/net/corda/simulator/runtime/config/DefaultConfigurationBuilderTest.kt
> +    fun `should allow registration of custom serializer via configuration`(){
updated the test name to "should be able to add custom serializers to configuration"

2022-12-16 09:07 UTC, LizR3 approved these changes

2022-12-16 09:14 UTC, ashutoshmeher-r3 commented on simulator/runtime/src/test/kotlin/net/corda/simulator/runtime/config/DefaultConfigurationBuilderTest.kt
> +    fun `should allow registration of custom serializer via configuration`(){
@fenryka Could you approve this please?

2022-12-16 09:51 UTC, closed without merging