CORE-8691: Delay Closing SandboxGroupContext
corda/corda-runtime-os pull request #2745
Opened 2022-12-14 18:06 UTC by jujoramos

Prevent automatically closing SandboxGroupContexts as soon as they are
evicted from the cache since they might still be in use. Instead, keep
a WeakReference to an internal wrapper and only close the evicted
SandboxGroupContext once all strong references to the wrapper are gone.

- Fix adapted from https://github.com/corda/corda/commit/4316838.

2022-12-15 11:00 UTC, JamesHR3 commented on components/virtual-node/sandbox-group-context-service/src/main/kotlin/net/corda/sandboxgroupcontext/service/impl/SandboxGroupContextCacheImpl.kt
>          contexts.invalidate(virtualNodeContext)
Should we do these the other way around in case we can immediately remove it, or does that lead to problems?

2022-12-15 11:00 UTC, JamesHR3 commented on components/virtual-node/sandbox-group-context-service/src/test/kotlin/net/corda/sandboxgroupcontext/impl/SandboxGroupContextCacheTest.kt
> +    fun `sandboxes of different types do not trigger close on eviction of other sandbox types`() {
Is this test valid? We're not partitioning the cache by sandbox type right?

2022-12-15 11:38 UTC, jujoramos commented on components/virtual-node/sandbox-group-context-service/src/test/kotlin/net/corda/sandboxgroupcontext/impl/SandboxGroupContextCacheTest.kt
> +    fun `sandboxes of different types do not trigger close on eviction of other sandbox types`() {
We're not partitioning the cache, no, but I still considered it as a valid test to have checked in (specially for the combined worker situation), that's the only reason why I copied it over from your previous `PR`. Happy to remove it if you consider it necessary, though.

2022-12-15 11:41 UTC, JamesHR3 commented on components/virtual-node/sandbox-group-context-service/src/test/kotlin/net/corda/sandboxgroupcontext/impl/SandboxGroupContextCacheTest.kt
> +    fun `sandboxes of different types do not trigger close on eviction of other sandbox types`() {
The change I made before was to partition the cache by sandbox type, so adding a new flow sandbox should never trigger persistence sandbox eviction for example. That's why I added that test. I don't think that's true for your code though? So I think this could (should?) fail.

2022-12-15 11:41 UTC, jujoramos commented on components/virtual-node/sandbox-group-context-service/src/main/kotlin/net/corda/sandboxgroupcontext/service/impl/SandboxGroupContextCacheImpl.kt
>          contexts.invalidate(virtualNodeContext)
Invalidated entries are closed straight away (they are not added to the internal `toBeClosed` structure) because they are not "evictions", so it shouldn't make any difference: 
```
.removalListener { key, context, cause ->
                if (cause.wasEvicted()) {
                  ...
                } else {
                    logger.info(
                        "Closing ${key!!.sandboxGroupType} sandbox for " +
                                "${key.holdingIdentity.x500Name} [${cause.name}]"
                    )

                    (context?.wrappedSandboxGroupContext as? AutoCloseable)?.close()
                }
```

2022-12-15 11:46 UTC, jujoramos commented on components/virtual-node/sandbox-group-context-service/src/test/kotlin/net/corda/sandboxgroupcontext/impl/SandboxGroupContextCacheTest.kt
> +    fun `sandboxes of different types do not trigger close on eviction of other sandbox types`() {
The cache has size `2` and we're adding `3` different `SandboxGroupContext`s to it, two of them will be evicted and the other will remain in the cache, but no context will be closed (that's what the test asserts, so it shouldn't fail). I'll remove the test anyway 👍 .

2022-12-15 13:27 UTC, JamesHR3 commented on components/virtual-node/sandbox-group-context-service/src/main/kotlin/net/corda/sandboxgroupcontext/service/impl/SandboxGroupContextCacheImpl.kt
>          contexts.invalidate(virtualNodeContext)
Great!

2022-12-15 13:28 UTC, JamesHR3 submitted a review, later dismissed

2022-12-15 15:11 UTC, chrisr3 requested changes
I don't think `SandboxGroupContextWrapper` should implement `AutoCloseable` precisely because we don't want anyone closing it and destroying the underlying sandbox.

I was also using SLF4J placeholders in those log messages _for a reason_.

2022-12-15 15:11 UTC, chrisr3 commented on components/virtual-node/sandbox-group-context-service/src/main/kotlin/net/corda/sandboxgroupcontext/service/impl/SandboxGroupContextCacheImpl.kt
> +        override fun close() = wrappedSandboxGroupContext.close()
Isn't this dangerous? In fact, why make `SandboxGroupContextWrapper` implement `AutoCloseable` at all when we cannot allow anyone to invoke its `close()` method? Only the _underlying_ context should be closed, and only when its wrapper has already been garbage-collected.

2022-12-15 15:11 UTC, chrisr3 commented on components/virtual-node/sandbox-group-context-service/src/main/kotlin/net/corda/sandboxgroupcontext/service/impl/SandboxGroupContextCacheImpl.kt
> +            )
Please revert these log messages back to using SLF4J placeholders, which exist precisely to avoid lots of unnecessary string concatenation. Just because Kotlin has made all that concatenation "more convenient" to write still doesn't make it a Good Idea.

2022-12-15 15:11 UTC, chrisr3 commented on components/virtual-node/sandbox-group-context-service/src/main/kotlin/net/corda/sandboxgroupcontext/service/impl/SandboxGroupContextCacheImpl.kt
> +                    )
You didn't need to change these log messages, they were better using SLF4J placeholders.

2022-12-15 15:11 UTC, chrisr3 commented on components/virtual-node/sandbox-group-context-service/src/test/kotlin/net/corda/sandboxgroupcontext/impl/SandboxGroupContextCacheTest.kt
Do these mocks test the behaviour during _actual_ garbage collection? Because that's the behaviour that matters.

2022-12-15 15:24 UTC, jujoramos commented on components/virtual-node/sandbox-group-context-service/src/main/kotlin/net/corda/sandboxgroupcontext/service/impl/SandboxGroupContextCacheImpl.kt
> +            )
👍

2022-12-15 15:24 UTC, jujoramos commented on components/virtual-node/sandbox-group-context-service/src/main/kotlin/net/corda/sandboxgroupcontext/service/impl/SandboxGroupContextCacheImpl.kt
> +                    )
👍

2022-12-15 15:36 UTC, jujoramos commented on components/virtual-node/sandbox-group-context-service/src/main/kotlin/net/corda/sandboxgroupcontext/service/impl/SandboxGroupContextCacheImpl.kt
> +        override fun close() = wrappedSandboxGroupContext.close()
It wasn't `AutoCloseable` originally, but [there's code](https://github.com/corda/corda-runtime-os/blob/release/os/5.0/components/virtual-node/sandbox-group-context-service/src/integrationTest/kotlin/net/corda/sandboxgroupcontext/test/VirtualNodeService.kt#L85-L97) within the `VirtualNodeService` that relies on manually unloading and closing the `SandboxGroupContext`.
Apparently you added this code back in February?, do you think it needs to be removed or should the wrapper somehow remove itself from the cache when somebody manually closes it (as it's not valid anymore for anyone else)?.

2022-12-15 15:40 UTC, jujoramos commented on components/virtual-node/sandbox-group-context-service/src/test/kotlin/net/corda/sandboxgroupcontext/impl/SandboxGroupContextCacheTest.kt
I haven't found a reliable way of making the JVM invoke the garbage collector so, instead of that, I'm "simulating" the behaviour by invoking `WeakReference.enqueue()` from within the relevant tests.

2022-12-15 15:59 UTC, jujoramos commented on components/virtual-node/sandbox-group-context-service/src/main/kotlin/net/corda/sandboxgroupcontext/service/impl/SandboxGroupContextCacheImpl.kt
> +        override fun close() = wrappedSandboxGroupContext.close()
The code that manually closes the context is only used within tests (`CustomCryptoDigestTests`), I'll need to update things so the sandboxes are removed from the cache instead of manually closed by the `VirtualNodeService`.

2022-12-15 19:25 UTC, chrisr3 commented on components/virtual-node/sandbox-group-context-service/src/test/kotlin/net/corda/sandboxgroupcontext/impl/SandboxGroupContextCacheTest.kt
As a rule, you null out all string references, invoke `System.gc()` and then "wait a bit"... :wink:

2022-12-15 23:29 UTC, jujoramos commented on components/virtual-node/sandbox-group-context-service/src/test/kotlin/net/corda/sandboxgroupcontext/impl/SandboxGroupContextCacheTest.kt
The `System.gc()` call just suggests the JVM to trigger a garbage collection execution, there's no guarantee that it's going to actually do it when we want it to. Aside from that, it might take more than just one GC cycle for the JVM to effectively update the `ReferenceQueue`. I'd rather keep the current approach and use `enqueue()` directly, it'll reduce the chance of flakiness.

2022-12-16 09:24 UTC, chrisr3 commented on components/virtual-node/sandbox-group-context-service/src/test/kotlin/net/corda/sandboxgroupcontext/impl/SandboxGroupContextCacheTest.kt
> The System.gc() call just suggests the JVM to trigger a garbage collection execution, there's no guarantee that it's going to actually do it when we want it to.

Yes, that's why I said you need to "wait a bit" :no_mouth:.

The biggest risk with using `WeakReference` is that you might accidentally miss a strong reference which prevents the object from ever  being enqueued in practice. I don't see how you can test that using mocks.

2022-12-16 12:25 UTC, jujoramos commented on components/virtual-node/sandbox-group-context-service/src/test/kotlin/net/corda/sandboxgroupcontext/impl/SandboxGroupContextCacheTest.kt
I've updated the test to continuously force a GC execution followed by a cache eviction, the `ReferenceQueue` will be eventually updated and there should be no flakiness.

2022-12-20 12:55 UTC, chrisr3 commented on components/virtual-node/sandbox-group-context-service/src/test/kotlin/net/corda/sandboxgroupcontext/impl/SandboxGroupContextCacheTest.kt
> +}
This function is neither safe nor necessary, and appears to assume that garbage-collection is an instant "all or nothing" kind of operation anyway!!? _In my experience,_ it is sufficient to invoke `System.gc()` and then use something like:
```kotlin
eventually(duration = of(60, SECONDS)) {
    // Has sandbox been garbage-collected yet?
}
```

2022-12-20 13:28 UTC, jujoramos commented on components/virtual-node/sandbox-group-context-service/src/test/kotlin/net/corda/sandboxgroupcontext/impl/SandboxGroupContextCacheTest.kt
> +}
You're right about the the assertion, I forgot to wrap all invocations to `forceGarbageCollectionExecution()` within a `eventually` clause, thanks for catching that.
I've dealt with `System.gc()` in the past and, according to what I recall from those situations, _it is not sufficient to just call it once and wait for the gc to run_. Considering that within this test we're wrapping the call within an outer `eventually` call, though, things should be fine. I've removed the `forceGarbageCollectionExecution()` function entirely as requested.

2022-12-21 11:12 UTC, chrisr3 commented on components/virtual-node/sandbox-group-context-service/src/main/kotlin/net/corda/sandboxgroupcontext/service/impl/SandboxGroupContextCacheImpl.kt
> +    }
FYI, Kotlin allows you to rewrite this class as:
```kotlin
internal class SandboxGroupContextWrapper(
    private val wrappedSandboxGroupContext: SandboxGroupContext
) : SandboxGroupContext by wrappedSandboxGroupContext
```
and we probably _do_ want `wrappedSandboxGroupContext` to be `private`.

2022-12-21 11:31 UTC, jujoramos commented on components/virtual-node/sandbox-group-context-service/src/main/kotlin/net/corda/sandboxgroupcontext/service/impl/SandboxGroupContextCacheImpl.kt
> +    }
Thanks for the tip, new to `kotlin` here :-). That said, we need access to the `wrappedSandboxGroupContext` from within the outer class in order to close it, so I don't think we can make it `private` (I've changed it to `internal`, though).

2022-12-21 11:39 UTC, chrisr3 commented on components/virtual-node/sandbox-group-context-service/src/main/kotlin/net/corda/sandboxgroupcontext/service/impl/SandboxGroupContextCacheImpl.kt
> +    }
> That said, we need access to the `wrappedSandboxGroupContext` from within the outer class in order to close it, so I don't think we can make it `private` (I've changed it to `internal`, though).

Fair enough, it was the potential for `public` access that was worrying me, even if `internal` scope is only a figment of Kotlin's imagination... Come to think of it, could we have
```kotlin
private class SandboxGroupContextWrapper
```
because I think a `private` class in Kotlin is equivalent to "package private" in Java.

2022-12-21 11:41 UTC, chrisr3 commented on components/virtual-node/sandbox-group-context-service/src/test/kotlin/net/corda/sandboxgroupcontext/impl/SandboxGroupContextCacheTest.kt
> +        assertThat(contextStrongRef as? Any).isNull() // Annoying check to prevent compilation failure due to unused var
You can always use `@Suppress("unused")` or similar to remove the compiler warning.

2022-12-21 11:46 UTC, chrisr3 commented on components/virtual-node/sandbox-group-context-service/src/test/kotlin/net/corda/sandboxgroupcontext/impl/SandboxGroupContextCacheTest.kt
> +        assertThat(contextStrongRef as? Any).isNull() // Annoying check to prevent compilation failure due to unused var
Try
```kotlin
// Remove the strong reference to the context, so it can be garbage collected
@Suppress("unused_value")
contextStrongRef = null
```

2022-12-21 12:05 UTC, jujoramos commented on components/virtual-node/sandbox-group-context-service/src/test/kotlin/net/corda/sandboxgroupcontext/impl/SandboxGroupContextCacheTest.kt
> +        assertThat(contextStrongRef as? Any).isNull() // Annoying check to prevent compilation failure due to unused var
👍

2022-12-21 12:05 UTC, jujoramos commented on components/virtual-node/sandbox-group-context-service/src/main/kotlin/net/corda/sandboxgroupcontext/service/impl/SandboxGroupContextCacheImpl.kt
> +    }
That might work... let me check how can I accommodate the tests with this change.

2022-12-21 12:08 UTC, chrisr3 commented on components/virtual-node/sandbox-group-context-service/src/main/kotlin/net/corda/sandboxgroupcontext/service/impl/SandboxGroupContextCacheImpl.kt
> +    }
I'm hoping the tests only see `SandboxGroupContext`, and don't care which class is actually implementing it.

2022-12-21 12:17 UTC, jujoramos commented on components/virtual-node/sandbox-group-context-service/src/main/kotlin/net/corda/sandboxgroupcontext/service/impl/SandboxGroupContextCacheImpl.kt
> +    }
They will now 💯

2022-12-21 12:27 UTC, chrisr3 approved these changes
LGTM

2022-12-21 13:33 UTC, merged