Conal/core 8610 change cpk pk
corda/corda-runtime-os pull request #2804
Opened 2022-12-21 23:57 UTC by conalsmith-r3

2023-01-03 12:59 UTC, driessamyn commented on components/chunking/chunk-db-write-impl/src/integrationTest/kotlin/net/corda/chunking/db/impl/tests/DatabaseCpiPersistenceTest.kt
> +        ssh: SecureHash = newRandomSecureHash()
I know the `ssh` name has been introduced elsewhere, but I would stay away from it as it's a well know abbreviation for `Secure Shell` and is a bit confusion. I think it's better to stick to `signerSummaryHash` consistently.

2023-01-03 12:59 UTC, driessamyn commented on components/chunking/chunk-db-write-impl/src/integrationTest/kotlin/net/corda/chunking/db/impl/tests/DatabaseCpiPersistenceTest.kt
> +        assertThat(forceUploadedCpi.entityVersion).isEqualTo(3)
Bit of a detail and probably not introduced in this PR, but does this need to increment by 2? That feels a bit wrong.

2023-01-03 12:59 UTC, driessamyn commented on components/chunking/chunk-db-write-impl/src/integrationTest/kotlin/net/corda/chunking/db/impl/tests/DatabaseCpiPersistenceTest.kt
> +//        assertChangeLogPersistedWithCpi(cpk2)
Can these be put back?

2023-01-06 14:08 UTC, vkolomeyko commented on libs/virtual-node/cpi-datamodel/src/main/kotlin/net/corda/libs/cpi/datamodel/CpiCpkEntity.kt
>  data class CpiCpkEntity(
Referenced Jira also says: "Apply recent JPA guidance."
should we do this as part of this PR (e.g. eliminate `data class` on entities) or would you rather do it as a separate one?

I would probably go for the latter, as this PR is sufficiently big already.

2023-01-06 14:08 UTC, conalsmith-r3 commented on components/chunking/chunk-db-write-impl/src/integrationTest/kotlin/net/corda/chunking/db/impl/tests/DatabaseCpiPersistenceTest.kt
> +        assertThat(forceUploadedCpi.entityVersion).isEqualTo(3)
Afaik first increment is caused by the optimistic force increment flag we set on the find query

https://github.com/corda/corda-runtime-os/blob/54f6cc660e3559a94bfb76807ebbba98b6a1764e/components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/persistence/database/DatabaseCpiPersistence.kt#L229-L252

Second increment is caused by calling merge on the CPI entity.

2023-01-06 14:10 UTC, conalsmith-r3 commented on libs/virtual-node/cpi-datamodel/src/main/kotlin/net/corda/libs/cpi/datamodel/CpiCpkEntity.kt
>  data class CpiCpkEntity(
Thanks I meant to update the description, CORE-8744 covers this JPA guidance refactoring.

2023-01-06 14:19 UTC, wzur-r3 requested changes, later dismissed

2023-01-06 14:19 UTC, wzur-r3 commented on gradle.properties
> +cordaApiVersion=5.0.0.606-alpha-1673001400834
that is surely wrong

2023-01-06 14:25 UTC, vkolomeyko commented on gradle.properties
> +cordaApiVersion=5.0.0.606-alpha-1673001400834
I think the plan is to change it to `beta` version once associated `corda-api` PR is merged.

2023-01-06 14:30 UTC, conalsmith-r3 commented on gradle.properties
> +cordaApiVersion=5.0.0.606-alpha-1673001400834
Yes, we typically achieve green build on the alpha artifact from corda-api first, I'll be changing this to 606-beta+ if corda-api gets approval

2023-01-06 15:21 UTC, driessamyn commented on components/chunking/chunk-db-write-impl/src/integrationTest/kotlin/net/corda/chunking/db/impl/tests/DatabaseCpiPersistenceTest.kt
> +        assertThat(forceUploadedCpi.entityVersion).isEqualTo(3)
And why do we set this, do you know? It feels like we should maybe always be incrementing it when we write, not read.

2023-01-06 15:34 UTC, driessamyn commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt
> +                    runCpiResyncMigrations(
This is a good observation. It think we should actually create a bug JIRA for this. Maybe it makes sense to look at it alongside CORE-8744, but we need to be careful it does't fall through the cracks as it sounds like it could cause a worker to fail.

2023-01-06 16:39 UTC, conalsmith-r3 commented on components/chunking/chunk-db-write-impl/src/main/kotlin/net/corda/chunking/db/impl/persistence/database/DatabaseCpiPersistence.kt
> +            CpiCpkEntity(
This is wrong, we should first try load CpiCpkEntity because it might exist, for example, if CPI force uploaded doesn't change a CPK it will already be associated with the CPI and merging this entity could fail with optimistic lock exception

2023-01-06 17:42 UTC, conalsmith-r3 commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt
> +                        dbConnectionManager.createDatasource(virtualNodeInfo.vaultDdlConnectionId!!),
This is missing a close of the datasource

2023-01-06 19:02 UTC, conalsmith-r3 commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt
> +                        }
This is all quite messy, but https://r3-cev.atlassian.net/browse/CORE-8744 will refactor this code into repositories, etc.

2023-01-06 19:05 UTC, conalsmith-r3 commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt
> +                    changelogsToRun.forEach { (cpkFileChecksum, changelogsForThisCpk) ->
I found when there were multiple CPK's changelogs to update, there was a liquibase exception in the original function:

```
java.sql.SQLTransientConnectionException: HikariPool-22 - Connection is not available, request timed out after 30005ms.
	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:696) ~[?:?]
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:181) ~[?:?]
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:146) ~[?:?]
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100) ~[?:?]
	at net.corda.db.core.HikariDataSourceFactory$DataSourceWrapper.getConnection(HikariDataSourceFactory.kt) ~[?:?]
	at net.corda.virtualnode.write.db.impl.writer.VirtualNodeWriterProcessor.runCpiResyncMigrations(VirtualNodeWriterProcessor.kt:633) ~[?:?]
	at net.corda.virtualnode.write.db.impl.writer.VirtualNodeWriterProcessor.resetVirtualNodeDb(VirtualNodeWriterProcessor.kt:341) ~[?:?]
	at net.corda.virtualnode.write.db.impl.writer.VirtualNodeWriterProcessor.onNext(VirtualNodeWriterProcessor.kt:466) ~[?:?]
	at net.corda.virtualnode.write.db.impl.writer.VirtualNodeWriterProcessor.onNext(VirtualNodeWriterProcessor.kt:83) ~[?:?]
	at net.corda.messaging.subscription.RPCSubscriptionImpl.processRecords$lambda$6$lambda$5(RPCSubscriptionImpl.kt:196) ~[?:?]
	at io.micrometer.core.instrument.composite.CompositeTimer.recordCallable(CompositeTimer.java:129) ~[?:?]
	at net.corda.messaging.subscription.RPCSubscriptionImpl.processRecords(RPCSubscriptionImpl.kt:196) ~[?:?]
	at net.corda.messaging.subscription.RPCSubscriptionImpl.pollAndProcessRecords(RPCSubscriptionImpl.kt:115) ~[?:?]
	at net.corda.messaging.subscription.RPCSubscriptionImpl.createProducerConsumerAndStartPolling(RPCSubscriptionImpl.kt:106) ~[?:?]
	at net.corda.messaging.subscription.RPCSubscriptionImpl.runConsumeLoop(RPCSubscriptionImpl.kt:77) ~[?:?]
	at net.corda.messaging.subscription.RPCSubscriptionImpl.access$runConsumeLoop(RPCSubscriptionImpl.kt:34) ~[?:?]
	at net.corda.messaging.subscription.RPCSubscriptionImpl$threadLooper$1.invoke(RPCSubscriptionImpl.kt:48) ~[?:?]
	at net.corda.messaging.subscription.RPCSubscriptionImpl$threadLooper$1.invoke(RPCSubscriptionImpl.kt:48) ~[?:?]
	at net.corda.messaging.subscription.ThreadLooper.runConsumeLoop(ThreadLooper.kt:174) ~[?:?]
	at net.corda.messaging.subscription.ThreadLooper.access$runConsumeLoop(ThreadLooper.kt:27) ~[?:?]
	at net.corda.messaging.subscription.ThreadLooper$StoppableThread$start$1$1.invoke(ThreadLooper.kt:106) ~[?:?]
	at net.corda.messaging.subscription.ThreadLooper$StoppableThread$start$1$1.invoke(ThreadLooper.kt:106) ~[?:?]
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30) ~[?:?]
```

I now run each CPK's migrations in a separate call to the liquibase API and close the connection after each run. https://r3-cev.atlassian.net/browse/CORE-8744 can likely improve this code.

2023-01-06 19:05 UTC, sprintengine commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt
> +                            logger.error(
Liquibase errors were causing the entire worker to go down. Catching here prevents this. Potentially we can log at a less severe level.

2023-01-10 10:17 UTC, conalsmith-r3 commented on components/chunking/chunk-db-write-impl/src/integrationTest/kotlin/net/corda/chunking/db/impl/tests/DatabaseCpiPersistenceTest.kt
> +        assertThat(forceUploadedCpi.entityVersion).isEqualTo(3)
https://github.com/corda/corda-runtime-os/commit/4072aa9e6b4f40a6f8dd4a5edcf4f82701f7998e

Looks like it was an attempt to bump CPI version when we force upload a CPI, I'm not sure if it's necessary since this does seem to already happen when calling merge, maybe there is an edge case it was covering?

2023-01-23 17:22 UTC, conalsmith-r3 commented on gradle.properties
> +cordaApiVersion=5.0.0.606-alpha-1673001400834
Can you lift the restriction on this otherwise you become a dependency on this getting merged and the release of a corda-api version lock

2023-01-23 17:48 UTC, driessamyn approved these changes
LGTM

2023-01-23 17:55 UTC, ronanbrowne approved these changes
Lgtm - build

2023-01-23 17:56 UTC, mag1c-48 approved these changes
LGTM - Build

2023-01-23 18:37 UTC, merged