CORE-6173 CORE-6181 Use notary keys for signing/validation
corda/corda-runtime-os pull request #2887
Opened 2023-01-09 17:37 UTC by nkovacsx

### Overview

Currently, we use the ledger key for signing which is wrong. This PR introduces a new `MemberInfo` extension called `notaryKeys`. This property will return the notary keys of the VNode (if it is a notary VNode).

We'll use the **first** element of those notary keys, which will always be the **latest** notary key. This means if there's a key rotation we'll always use the latest key for signing.

When the notary signature is validated we check that the response was signed by one of the notary VNodes. This means, we check that the key is part of the notary composite key.

Test scenario `Notary - Uniqueness client service flow is finishing without exceptions` has been removed since we can only sign on a notary VNode now however, the `test-cordapp` is not installed on the notary so we can't call the `LedgerUniquenessClientService`. This scenario will be tested implicitly by the other scenarios anyway. 

### Test Notes

- Existing smoke test are running successfully as both the signing and validation part has been modified
- Added extra validation for signature in the `NonValidatingNotaryTestFlow` when it is not run through the finality flow
- Removed `UniquenessCheckTestFlow` altogether as this is no longer needed, the uniqueness checker client service will be tested through the plugin
- Added extra test scenario to Utxo finality flow tests - when a signature is received from an identity that is not part of the notary composite key
- Current tests has been modified to use the new API (with the notary keys)
- Added new test scenarios in `LedgerUniquenessCheckerClientServiceImplTest`

2023-01-10 11:55 UTC, vlajos submitted a review, later dismissed
The finality flow/ledger specific parts look OK to me.

2023-01-10 13:38 UTC, relyafi reviewed
Only one trivial comment to address, others are observations / follow on actions.

I would note however there is a lack of test notes on this PR, beyond saying that a test case has been removed. I'm not really sure why we've removed this - what is the barrier to setting up a proper test scenario using notary virtual nodes if needed?

If possible, I'd also like to see some evidence that the composite key verification logic works when we have multiple notary virtual nodes for the same notary service. The MGM does actively prevent this at present, so may need to be done via unit tests etc.

I'd also add the fact that we've fundamentally changed the key being used to sign, without changing any test cases implies that there are existing gaps in our test coverage.

2023-01-10 14:04 UTC, nkovacsx commented
@relyafi To answer your questions in order:

1. The `Notary - Uniqueness client service flow is finishing without exceptions` test case was removed because we can only sign in a notary VNode now (as that's the only VNode that has notary keys). 
The only way to execute this test is to call the `UniquenessCheckTestFlow` which is part of the `test-cordapp` CPB which is **NOT** installed on the notary VNode. What I could do is install `test-cordapp` on the notary VNode which is a big overhead because we won't use 90% of the CPB or I could create a separate CPB which **ONLY** includes the `UniquenessCheckTestFlow` which would require a new sub-module. I chose not to do any of these because I feel like this test scenario is only an intermediate step and this scenario will be tested in the other scenarios where the actual plugin is called.

2. `we've fundamentally changed the key being used to sign, without changing any test cases implies that there are existing gaps in our test coverage.` I don't necessarily agree with this. If you check the code, we've changed the key we use for signing, but we also changed the signature verification logic. That means both sides of the process were changed (signing-verifying). Do you think we should add a test scenario that explicitly checks the key that we used for signing?

2023-01-10 14:25 UTC, relyafi commented
@nkovacsx Ok, understood re. point 1.

Re. point 2 - ok, yes I guess that as long as we are running finality flow, that itself will verify that we have the correct signature. Are we confident that all of the test cases we have that are testing the uniqueness checker client (which is generating the signature) are using finality flow? If so, then I think we're good. If not, those other test cases should probably check that the expected signature is there.

2023-01-10 14:44 UTC, nkovacsx commented
Thanks @relyafi for your comment, that's actually a good point. Consuming transactions don't go through the finality flow so we should add an extra validation step in our test flow.

2023-01-10 16:06 UTC, vlajos submitted a review, later dismissed
Ledger/Finality flow parts look good.

2023-01-10 17:58 UTC, relyafi commented on components/ledger/ledger-utxo-flow/src/test/kotlin/net/corda/ledger/utxo/flow/impl/flows/finality/UtxoFinalityFlowTest.kt
> +    private val invalidNotarySignature = digitalSignatureAndMetadata(invalidNotaryVNodeKey, byteArrayOf(1, 2, 3))
I'm assuming the byte array should be different from `signatureAlice1`, just to be safe?

2023-01-11 08:40 UTC, nkovacsx commented on components/ledger/ledger-utxo-flow/src/test/kotlin/net/corda/ledger/utxo/flow/impl/flows/finality/UtxoFinalityFlowTest.kt
> +    private val invalidNotarySignature = digitalSignatureAndMetadata(invalidNotaryVNodeKey, byteArrayOf(1, 2, 3))
Good point!

2023-01-11 08:52 UTC, relyafi submitted a review, later dismissed
LGTM

2023-01-11 10:50 UTC, ronanbrowne approved these changes, later dismissed
lgtm - build

2023-01-17 11:03 UTC, vlajos submitted a review, later dismissed
Ledger/Finality flow parts reapproved.

2023-01-17 11:35 UTC, relyafi requested changes
I think there needs to be additional logic to send the notary service key from client to server flows.

Also, are we missing test cases to cover this new behavior, specifically:

- Testing that we can successfully notarise when the composite key contains multiple leaf keys (since we can't currently test this in a real system). This test should also should also ensure that the notary vnode used to notarise is not the first in that list of leaf keys (since incorrectly using `first()` is a common bug)
- Testing that rejection occurs if the client specifies a notary service key with leaf keys that the notary vnode does not have a corresponding private key for (which simulates routing to the wrong vnode for a notary service)

2023-01-17 11:35 UTC, relyafi commented on components/ledger/ledger-utxo-flow/src/main/kotlin/net/corda/ledger/utxo/flow/impl/flows/finality/UtxoFinalityBase.kt
> +            log.debug("Verifying signature($signature) of transaction: $transactionId")
```suggestion
            log.debug { "Verifying signature($signature) of transaction: $transactionId" }
```

2023-01-17 11:35 UTC, relyafi commented on components/ledger/ledger-utxo-flow/src/main/kotlin/net/corda/ledger/utxo/flow/impl/flows/finality/UtxoFinalityBase.kt
> +            log.debug("Verifying signature($signature) of transaction: $transactionId")
More efficient as will only be evaluated when debug logging is enabled.

2023-01-17 11:35 UTC, relyafi commented on notary-plugins/notary-plugin-non-validating/notary-plugin-non-validating-server/src/main/kotlin/com/r3/corda/notary/plugin/nonvalidating/server/NonValidatingNotaryServerFlowImpl.kt
> +                ?: listOf(notaryServiceKey)
This looks incorrect - we can't assume only one notary service on the network.

I believe @mnesbit 's intent (which solves this problem) is that the client node sends the notary service key across as part of the payload from client to server. Then the server plugin has no selection to do - it's provided with the service key the client is expecting a signature from.

2023-01-17 12:08 UTC, nkovacsx commented on notary-plugins/notary-plugin-non-validating/notary-plugin-non-validating-server/src/main/kotlin/com/r3/corda/notary/plugin/nonvalidating/server/NonValidatingNotaryServerFlowImpl.kt
> +                ?: listOf(notaryServiceKey)
hmm, okay, that makes sense

2023-01-17 16:37 UTC, relyafi reviewed
Couple of minor comments, then LGTM.

@mnesbit I think this change should now address most of your concerns - the only place that we're still using member info is to lookup the key on the notary vnode, which I think is unavoidable until the crypto API is updated.

2023-01-17 16:37 UTC, relyafi commented on components/uniqueness/uniqueness-checker-client-service-impl/src/test/kotlin/net/corda/uniqueness/client/impl/LedgerUniquenessCheckerClientServiceImplTest.kt
> +    fun `Uniqueness check client responds with success if uniqueness check was successful`() {
This test case appears to be redundant, as the next test case is identical?

2023-01-17 16:37 UTC, relyafi commented on components/ledger/ledger-utxo-flow/src/main/kotlin/net/corda/ledger/utxo/flow/impl/flows/finality/UtxoFinalityBase.kt
> +            }
```suggestion
            log.debug { "Verifying signature($signature) of transaction: $transactionId" }
```

Consistent formatting with debug statement 2 lines further down.

2023-01-17 17:23 UTC, relyafi submitted a review, later dismissed
LGTM

2023-01-18 14:04 UTC, relyafi approved these changes

2023-01-18 15:04 UTC, dimosr approved these changes

2023-01-18 15:10 UTC, ronanbrowne approved these changes
lgtm - build

2023-01-18 15:10 UTC, merged