CORE-9184 - secret service factory and discovery
corda/corda-runtime-os pull request #2894
Opened 2023-01-10 18:10 UTC by driessamyn

WIP

2023-01-11 16:19 UTC, vkolomeyko commented on libs/configuration/configuration-core/src/main/kotlin/net/corda/libs/configuration/SmartConfigFactoryFactory.kt
> +class SmartConfigFactoryFactory
Could we possibly call it `SmartConfigFactoryCreator` or `SmartConfigFactoryProducer`?

2023-01-11 16:19 UTC, vkolomeyko commented on libs/configuration/configuration-core/src/main/kotlin/net/corda/libs/configuration/SmartConfigFactoryFactory.kt
> +        private val secretsServiceFactories: List<SecretsServiceFactory>
Possibly better way of doing it will by using `org.osgi.service.component.ComponentContext` similar to how this is done in `ExternalEventFactoryMapImpl` or `HttpRpcGateway`.

@chrisr3 might know better why this method of `ReferenceCardinality.MULTIPLE` discovery is more preferable.

2023-01-11 16:19 UTC, vkolomeyko commented on libs/configuration/configuration-core/src/main/kotlin/net/corda/libs/configuration/secret/SecretsServiceFactory.kt
> +    fun create(config: Config): SecretsService?
```suggestion
    fun create(config: Config): SecretsService
```
and then throw an exception if `SecretsService` cannot be created.

2023-01-11 16:19 UTC, vkolomeyko commented on applications/tools/p2p-test/dump-topic/src/main/kotlin/net/corda/p2p/app/topic/dump/TopicDumper.kt
> +import java.util.*
Possibly, best not to use `*` in imports, I think this requires IntelliJ settings change.

2023-01-11 16:25 UTC, driessamyn commented on libs/configuration/configuration-core/src/main/kotlin/net/corda/libs/configuration/SmartConfigFactoryFactory.kt
> +class SmartConfigFactoryFactory
I was trying to keep it to the standard pattern name. But happy to change if the consensus is that it is confusing.

2023-01-11 16:25 UTC, driessamyn commented on libs/configuration/configuration-core/src/main/kotlin/net/corda/libs/configuration/SmartConfigFactoryFactory.kt
> +        private val secretsServiceFactories: List<SecretsServiceFactory>
I wasn't aware of that. I'll have a look, thanks for pointing this out!

2023-01-11 16:26 UTC, driessamyn commented on libs/configuration/configuration-core/src/main/kotlin/net/corda/libs/configuration/secret/SecretsServiceFactory.kt
> +    fun create(config: Config): SecretsService?
If we throw an exception, then we need to catch/use the exception in the logic around finding out which factory is relevant to the configuration.
Isn't that also an anti-pattern?

2023-01-11 16:34 UTC, vkolomeyko commented on libs/configuration/configuration-core/src/main/kotlin/net/corda/libs/configuration/secret/SecretsServiceFactory.kt
> +    fun create(config: Config): SecretsService?
OK, I see your point whereby `SecretServiceFactory` may not recognise the config therefore returning `null` meaning to say "I cannot handle it, please try the next factory avalable."

2023-01-11 17:14 UTC, driessamyn commented on libs/configuration/configuration-core/src/main/kotlin/net/corda/libs/configuration/secret/SecretsServiceFactory.kt
> +    fun create(config: Config): SecretsService?
Correct. I considered an alternative interface where you have methods, a `match` that returns a boolean and a `create`, but it would double up the work needing to be done, so wasn't sure if it'd be worth it. But maybe it is if it's a cleaner api?

2023-01-11 17:43 UTC, vkolomeyko commented on libs/configuration/configuration-core/src/main/kotlin/net/corda/libs/configuration/secret/SecretsServiceFactory.kt
> +    fun create(config: Config): SecretsService?
I think it is fine "as is".

2023-01-12 10:07 UTC, vkolomeyko commented on libs/configuration/configuration-core/src/main/kotlin/net/corda/libs/configuration/SmartConfigFactoryFactory.kt
> +class SmartConfigFactoryFactory
Another idea for the name: `SmartConfigFactorySupplier`.

2023-01-12 11:22 UTC, chrisr3 commented on libs/configuration/configuration-core/src/main/kotlin/net/corda/libs/configuration/SmartConfigFactoryFactory.kt
> +        private val secretsServiceFactories: List<SecretsServiceFactory>
I think you are assuming that _all_ `SecretsServiceFactory` components will already have been registered by the time your new component asks for them. I don't believe you can guarantee that because it depends on the order that the OSGi framework activates its bundles.

The `HttpRpcGateway` solves this problem by using `MULTIPLE` with a `DYNAMIC` reference policy so that the set of service references isn't frozen when the component is created. And it also uses `ComponentContext.locateServices()` so that it can continue to use constructor injection.

2023-01-12 14:27 UTC, driessamyn commented on libs/configuration/configuration-core/src/main/kotlin/net/corda/libs/configuration/secret/SecretsServiceFactory.kt
> +    fun create(config: Config): SecretsService?
After discussion, I changed the code so to use an explicit `type` attribute, which feels cleaner.

2023-01-12 14:28 UTC, driessamyn commented on libs/configuration/configuration-core/src/main/kotlin/net/corda/libs/configuration/SmartConfigFactoryFactory.kt
> +        private val secretsServiceFactories: List<SecretsServiceFactory>
Thanks both.
I created https://r3-cev.atlassian.net/browse/CORE-9429 as I will need to make the same change for the add-on discovery, so would prefer to refactor those afterwards.

2023-01-12 15:32 UTC, dickon reviewed
I think this approach spreads a lot of details on how the layered secrets service works to places which construct and use it. That's one reason the code is so big. @vkolomeyko asked about alternatives to `SmartConfigFactoryFactory` but the truth is we may well want a factory which makes a factory, but if we do so, that's fine, but let's keep those details to one approach.

A cleaner approach would be to keep something called SmartConfigFactory with a companion object method which would be used like this:

`val smartConfig = SmartConfigFactory.create(config)` where config is a string of HSON. 

Then, the implementation details of multiple underlying config providers, e.g. HashicorpVaultSecretsService, EncryptedSecretsService  would all be handled within the single factory function, and what you get back is of type `SmartConfig`. We need to do something quite dynamic here, but we don't need to expose that complexity to the whole platform, who just want to be make use of the smart config.

I agree with renaming the current secrets with encryption code, though I think EncryptedSecretService would be a better name, since the code concernes encrytped secrets, whereas to me "EncrptionSecretsService" suggests handling secrets _about_ encryption instead.

2023-01-12 15:32 UTC, dickon commented on libs/configuration/configuration-core/src/main/kotlin/net/corda/libs/configuration/secret/EncryptionSecretsServiceImpl.kt
> +    override fun getValue(secretConfig: Config):    String {
unnecessary whitespace change, but harmless

2023-01-12 15:44 UTC, simon-johnson-r3 commented on libs/configuration/configuration-core/src/main/kotlin/net/corda/libs/configuration/SmartConfigFactoryFactory.kt
> + * Factory for creating [SmartConfigFactory] objects based on configuration.
If you want to create a `SmartConfigFactory` which differs in behaviour based on configuration, a normal way to do that would be to pass the configuration to the constructor of that factory. Is there a reason you can't discover the secrets in the first level factory you already have?

To put it another way, if you already have a level of abstraction between the thing you want to construct and the manner in which you construct it, having two levels of abstraction then seems overkill because the second level logic can be handled internally by the first level.

I'm putting the `createWithoutSecurityServices` method aside in this comment, because I don't think you'd create a class called `FactoryFactory` just for that over a non-class scoped factory function, e.g.
```
bootConfig = smartConfigFactoryWithoutSecurityServices().create(
```
reads better than.
```
bootConfig = SmartConfigFactoryFactory.createWithoutSecurityServices().create(
```

2023-01-12 15:44 UTC, simon-johnson-r3 commented on libs/configuration/configuration-core/src/main/kotlin/net/corda/libs/configuration/secret/EncryptionSecretsServiceFactory.kt
> +        const val TYPE = "encryption"
Out of interest, is there a technical reason you declare this inside the companion object, or is it just to keep the strings together?

2023-01-12 16:07 UTC, driessamyn commented on libs/configuration/configuration-core/src/main/kotlin/net/corda/libs/configuration/secret/EncryptionSecretsServiceImpl.kt
> +    override fun getValue(secretConfig: Config):    String {
Fixed

2023-01-12 16:08 UTC, driessamyn commented
> I think this approach spreads a lot of details on how the layered secrets service works to places which construct and use it. That's one reason the code is so big. @vkolomeyko asked about alternatives to `SmartConfigFactoryFactory` but the truth is we may well want a factory which makes a factory, but if we do so, that's fine, but let's keep those details to one approach.
> 
> A cleaner approach would be to keep something called SmartConfigFactory with a companion object method which would be used like this:
> 
> `val smartConfig = SmartConfigFactory.create(config)` where config is a string of HSON.
> 
> Then, the implementation details of multiple underlying config providers, e.g. HashicorpVaultSecretsService, EncryptedSecretsService would all be handled within the single factory function, and what you get back is of type `SmartConfig`. We need to do something quite dynamic here, but we don't need to expose that complexity to the whole platform, who just want to be make use of the smart config.
> 
> I agree with renaming the current secrets with encryption code, though I think EncryptedSecretService would be a better name, since the code concernes encrytped secrets, whereas to me "EncrptionSecretsService" suggests handling secrets _about_ encryption instead.

I changed `create(config: Config)` to `create(secretsServiceConfig: Config)`, which hopefully makes things a bit clearer. (see response to Simon's comment).

2023-01-12 16:20 UTC, driessamyn commented on libs/configuration/configuration-core/src/main/kotlin/net/corda/libs/configuration/SmartConfigFactoryFactory.kt
> + * Factory for creating [SmartConfigFactory] objects based on configuration.
> If you want to create a SmartConfigFactory which differs in behaviour based on configuration, a normal way to do that would be to pass the configuration to the constructor of that factory. Is there a reason you can't discover the secrets in the first level factory you already have?

But they are different things.
You need to configure the `SmartConfigFactory`, or more specifically the implementation of `SecretsService` that the factory is using. That is a `Config` object because we don't know at compile time what the concrete implementation will need (so it's effectively a map).

For example:
the encryption version needs:

```
type: encryption
salt: foo
passphrase: micky mouse
```

The Vault service needs something like:

```
type: hashicorp-vault
address: my-vault.fred.com
auth-token: #ABC
namespace: corda
```

In contrast, the config you pass into the `create` function of the `SmartFactory` is completely unrelated to this. This can be anything of type `Config`, and it'll basically wrap this into a `SmartConfig` object.

So there are 2 factories for a reason. 
- `SmartConfigFactory` - is responsible for turning an instance of `Config` into one of `SmartConfig`, and also for creating a `SmartConfig` "secret" object from a string. I.e. it's a factory for SmartConfig objects.
- `SmartConfigFactoryFactory` - is responsible for making one of the above. For that it needs to know what secrets service it needs to use, and for that reason you need to supply it with some configuration.

The `createWithoutSecurityServices` is a special case, mainly used in tests that don't care about secrets (but also during config validation). We could achieve the same by adding a `MaskedSecretsService` to the list of injected services, but we don't really want anybody to use one of them unless they explicitly want something that doesn't support secrets.

2023-01-12 16:24 UTC, driessamyn commented on libs/configuration/configuration-core/src/main/kotlin/net/corda/libs/configuration/secret/EncryptionSecretsServiceFactory.kt
> +        const val TYPE = "encryption"
Not sure. Where otherwise would you declare it?
I wanted it to be available as a public static member so that in the `SmartConfigFactoryFactory`, we can do this, for example: `val type = secretsServiceConfig.getStringOrDefault(SECRET_SERVICE_TYPE, EncryptionSecretsServiceFactory.TYPE)`. I realise I could do `EncryptionSecretsServiceFactory().type`, but it seems a bit unnecessary to create an instance of the class just to get the constant.

2023-01-12 17:33 UTC, simon-johnson-r3 commented on libs/configuration/configuration-core/src/main/kotlin/net/corda/libs/configuration/secret/EncryptionSecretsServiceFactory.kt
> +        const val TYPE = "encryption"
Yes, that's what I was asking indeed. Makes sense.

2023-01-12 17:34 UTC, simon-johnson-r3 commented on libs/configuration/configuration-core/src/main/kotlin/net/corda/libs/configuration/SmartConfigFactoryFactory.kt
> + * Factory for creating [SmartConfigFactory] objects based on configuration.
Resolved offline. There might be some scope to refactor after the other parts of this have gone in, otherwise all solutions are pretty much logically equivalent and really just a subjective view on semantics.

2023-01-12 17:34 UTC, simon-johnson-r3 approved these changes, later dismissed

2023-01-12 19:38 UTC, ronanbrowne requested changes

2023-01-12 19:38 UTC, ronanbrowne commented on libs/configuration/configuration-osgi-test/build.gradle
> +//    implementation "net.corda:corda-config-schema"
accidentally committed ?

2023-01-13 09:06 UTC, driessamyn commented on charts/corda/templates/flow-worker.yaml
> +          - -ssalt=$(SALT)
@davidcurrie 
FYI, this PR change the behaviour in that it throws an exception if you haven't configured a "Secrets Service" instead of a warning (it's mandatory for all workers as otherwise they would not be able to resolve sensitive configuration).

2023-01-13 10:13 UTC, ronanbrowne approved these changes, later dismissed
LGTM - build changes

2023-01-13 10:15 UTC, davidcurrie commented on charts/corda/templates/flow-worker.yaml
> +          - -ssalt=$(SALT)
You'll need to replicate the following for those environment variables to actually be available though:
https://github.com/corda/corda-runtime-os/blob/release/os/5.0/charts/corda/templates/crypto-worker.yaml#L44

If you're now making them available on all workers, it's probably better just to add `dbSaltAndPassphraseEnv` to `workerEnv`. Might also be worth expanding `workerKafkaArgs` to `workerArgs` and adding the salt and passphrase in there.

2023-01-13 10:16 UTC, davidcurrie commented on charts/corda/templates/flow-worker.yaml
> +          - -ssalt=$(SALT)
(As an aside: the configuration for the workers has diverged much less than I thought it might. I'm tempted to actually create a single parameterised template for a worker but that's a bigger piece of work.)

2023-01-13 10:29 UTC, driessamyn commented on charts/corda/templates/flow-worker.yaml
> +          - -ssalt=$(SALT)
So I'm guessing this works because we're effectively passing empty values for this? 
`dbSaltAndPassphraseEnv` doesn't seem right as this has nothing to do with the DB.

2023-01-13 10:55 UTC, davidcurrie approved these changes
👍 for the chart changes

2023-01-13 11:20 UTC, ronanbrowne approved these changes

2023-01-13 11:36 UTC, driessamyn commented on libs/configuration/configuration-core/src/main/kotlin/net/corda/libs/configuration/SmartConfigFactoryFactory.kt
> +class SmartConfigFactoryFactory
As per https://github.com/corda/corda-runtime-os/pull/2894#discussion_r1068411544, will follow-up with a rename/restructure proposal separately.

2023-01-13 11:47 UTC, conalsmith-r3 approved these changes
Lgtm

2023-01-13 11:48 UTC, merged