CORE-9206: Add localWorkerPlatformVersion to the PlatformInfoProvider
corda/corda-runtime-os pull request #2897
Opened 2023-01-11 11:38 UTC by fowlerrr

Plumb in `PlatformInfoProvider.localWorkerPlatformVersion`.

We're reading the version defined in `gradle.properties` and feeding it to the Bundle context.  We can then read it back out in the `PlatformInfoProvider`.

2023-01-11 11:42 UTC, fowlerrr commented on libs/platform-info/src/integrationTest/kotlin/net/corda/libs/platform/test/PlatformInfoProviderTest.kt
> +    //fun `Service returns expected stub value for local worker platform version`() {
Let the note here.  I didn't think doing some gradle magic to add to the test bundle context here was useful as it's only really testing that specific gradle change.

2023-01-11 11:58 UTC, mnesbit commented on libs/platform-info/src/main/kotlin/net/corda/libs/platform/impl/PlatformInfoProviderImpl.kt
>          bundleManifest?.mainAttributes?.getValue(BUNDLE_VERSION)
Is bundle version the full version or only the first 3 'semantic' version entries? We would very much like to be able to identify exactly what build we are on

2023-01-11 12:24 UTC, simon-johnson-r3 requested changes

2023-01-11 12:24 UTC, simon-johnson-r3 commented on buildSrc/src/main/groovy/corda.common-app.gradle
> +    frameworkProperties.put('net.corda.platform.version', osgiRun.platformVersion)
Is there a reason this is a special case and not part of frameworkProperties? It feels overly burdensome to have to remember to do 2 things every time you add one of these. If there's some good reason for keeping them apart perhaps consider that the object could coalesce these for you via a member, then this line could be a simple call to a getter again?

2023-01-11 12:24 UTC, simon-johnson-r3 commented on libs/platform-info/src/integrationTest/kotlin/net/corda/libs/platform/test/PlatformInfoProviderTest.kt
> +    //fun `Service returns expected stub value for local worker platform version`() {
I think the comment is good, but the inclusion of the commented out `fun` declaration with the open brace looks a bit clunky.

2023-01-11 12:24 UTC, simon-johnson-r3 commented on libs/platform-info/src/main/kotlin/net/corda/libs/platform/impl/PlatformInfoProviderImpl.kt
> +    override val localWorkerPlatformVersion by lazy {
This is interesting, it suggests we know fetching the property from the bundle is costly (or is it that it's not possible on construction?) but keeping the bundle reference in here isn't. I'm not disputing either of those assumptions, I just wondered if that was your reasoning for information.

2023-01-11 12:24 UTC, simon-johnson-r3 commented on libs/platform-info/src/test/kotlin/net/corda/libs/platform/impl/PlatformInfoProviderImplTest.kt
>      fun `local worker platform version returns stub value`() {
I think the test should now be renamed `local worker platform version returns software version from bundle manifest`?

2023-01-11 12:24 UTC, simon-johnson-r3 commented on libs/platform-info/src/main/kotlin/net/corda/libs/platform/impl/PlatformInfoProviderImpl.kt
> +    private val classLoader: ClassLoader,
This is a bit nit picking but the tests highlight this has created a api where you can instantiate using either
```
PlatformInfoProviderImpl(classLoader, bundleContext)
```
or
```
PlatformInfoProviderImpl(bundleContext)
```
In these cases it would be more usual to leave the optional param to the end in the first.

2023-01-11 12:38 UTC, chrisr3 commented on buildSrc/src/main/groovy/corda.common-app.gradle
> +    frameworkProperties.put('net.corda.platform.version', osgiRun.platformVersion)
You don't need to remember to do two things every time because the `FrameworkPropertyFile` task is internal to the `corda.common-app` convention plugin. In other words, the `osgiRun.platformVersion` provider is automatically added to the generated framework properties file without any user action whatsoever.

I toyed briefly with adding `platformVersion` to `osgiRun.frameworkProperties` during initialisation, but the value was far too easily clobbered later by:
```gradle
osgiRun {
    frameworkProperties = [ ... ]
}
```
which _replaces_ the original contents rather than adding to it.

2023-01-11 12:55 UTC, chrisr3 reviewed
I don't think you need to touch the bundle's manifest. Why not leave that to the OSGi framework, and read the bundle version and bundle symbolic name from its associated `Bundle`?

2023-01-11 12:55 UTC, chrisr3 commented on libs/platform-info/src/main/kotlin/net/corda/libs/platform/impl/PlatformInfoProviderImpl.kt
> +    private val classLoader: ClassLoader,
I don't think you need either the `ClassLoader` or the `Manifest` now that you have the `BundleContext`:
```kotlin
override val localWorkerSoftwareVersion = bundleContext.bundle.version.toString()
```

2023-01-11 12:55 UTC, chrisr3 commented on libs/platform-info/src/main/kotlin/net/corda/libs/platform/impl/PlatformInfoProviderImpl.kt
>          val logger = contextLogger()
This `logger` should probably be `private`. This component is also a singleton so there's probably no harm in creating it as property either:
```kotlin
private val logger = loggerFor<PlatformInfoProviderImpl>()
```

2023-01-11 13:03 UTC, fowlerrr commented on libs/platform-info/src/integrationTest/kotlin/net/corda/libs/platform/test/PlatformInfoProviderTest.kt
> +    //fun `Service returns expected stub value for local worker platform version`() {
Yeah, I felt like it was worth _showing_ the test.  But I can remove it if it looks too weird

2023-01-11 13:03 UTC, fowlerrr commented on libs/platform-info/src/main/kotlin/net/corda/libs/platform/impl/PlatformInfoProviderImpl.kt
> +    private val classLoader: ClassLoader,
Yeah, that's fair enough.

2023-01-11 13:05 UTC, fowlerrr commented on libs/platform-info/src/main/kotlin/net/corda/libs/platform/impl/PlatformInfoProviderImpl.kt
> +    override val localWorkerPlatformVersion by lazy {
I'm not actually a massive fan of `lazy` to be honest. I was more keeping it for consistency with `localWorkerSoftwareVersion`.  That said, I'm pretty sure there's very little cost to getting this from the bundle context so I'll just remove the lazy.

2023-01-11 13:08 UTC, chrisr3 commented on libs/platform-info/src/main/kotlin/net/corda/libs/platform/impl/PlatformInfoProviderImpl.kt
> +    override val localWorkerPlatformVersion by lazy {
Just get _everything_ from `BundleContext`... :wink:

2023-01-11 13:36 UTC, fowlerrr commented on libs/platform-info/src/main/kotlin/net/corda/libs/platform/impl/PlatformInfoProviderImpl.kt
> +    private val classLoader: ClassLoader,
Richer but fits with what we actually use anyway.

2023-01-11 13:37 UTC, fowlerrr commented on libs/platform-info/src/main/kotlin/net/corda/libs/platform/impl/PlatformInfoProviderImpl.kt
>          val logger = contextLogger()
Actually, now we're using `BundleContext` there's nothing to log so I'm just removing it.

2023-01-11 13:42 UTC, fowlerrr commented on libs/platform-info/src/main/kotlin/net/corda/libs/platform/impl/PlatformInfoProviderImpl.kt
> +    override val localWorkerPlatformVersion by lazy {
So much easier!  Unfortunately this removes yet another integration test.  Or maybe that's fortunate?  Either way, it's gone now.

2023-01-11 13:46 UTC, fowlerrr commented on libs/platform-info/src/main/kotlin/net/corda/libs/platform/impl/PlatformInfoProviderImpl.kt
>          bundleManifest?.mainAttributes?.getValue(BUNDLE_VERSION)
Currently the manifest has:
```
Bundle-Version: 5.0.0.0-SNAPSHOT
```
And, as I have it now, we'll write all of that out.

2023-01-11 13:55 UTC, chrisr3 commented on libs/platform-info/src/main/kotlin/net/corda/libs/platform/impl/PlatformInfoProviderImpl.kt
> +    override val localWorkerPlatformVersion = bundleContext.getProperty("net.corda.platform.version").toInt()
:sparkles: _Magic String_ :sparkles:?

2023-01-11 15:48 UTC, fowlerrr commented on libs/platform-info/src/main/kotlin/net/corda/libs/platform/impl/PlatformInfoProviderImpl.kt
> +    override val localWorkerPlatformVersion = bundleContext.getProperty(PLATFORM_VERSION_KEY)?.toInt() ?: DEFAULT_PLATFORM_VERSION
I had to introduce a default version because the integration tests won't have the `platformVersion` in their bundle properties.  I'm not terribly keen on that but I don't know if it's acceptable or if we should be plumbing the `platformVersion` into test bundles too.

Preferences?

2023-01-11 16:57 UTC, chrisr3 commented on libs/platform-info/src/main/kotlin/net/corda/libs/platform/impl/PlatformInfoProviderImpl.kt
> +    override val localWorkerPlatformVersion = bundleContext.getProperty(PLATFORM_VERSION_KEY)?.toInt() ?: DEFAULT_PLATFORM_VERSION
You can add the platform version to the integration tests via the `test.bndrun` file:
```
-runproperties: \
    net.corda.platform.version=123
```
For bonus marks, you should even be able to use the correct Gradle property value, using something _like_ this:
```
-runproperties: \
    net.corda.platform.version=${project.platformVersion}
```

2023-01-12 09:12 UTC, simon-johnson-r3 commented on buildSrc/src/main/groovy/corda.common-app.gradle
> +    frameworkProperties.put('net.corda.platform.version', osgiRun.platformVersion)
I think we might be talking at cross purposes. When I talk about adding things in 2 places I mean maintainers of this file making changes like the one Ryan has done here.

I'm suggesting the method looks something like this:
```
TaskProvider<FrameworkPropertyFile> writeFrameworkPropertyFile = tasks.register("writeFrameworkPropertyFile", FrameworkPropertyFile) {
    frameworkProperties = osgiRun.frameworkPropertiesToWriteToFile
}
```
where that getter looks like this inside OsgiRun. This way all the logic about the superset of framework properties to write is in one place.
```
    Provider<? extends String> getFrameworkPropertiesToWriteToFile() {
        <--- make the superset here
    }
```

2023-01-12 09:31 UTC, fowlerrr commented on libs/platform-info/src/main/kotlin/net/corda/libs/platform/impl/PlatformInfoProviderImpl.kt
> +    override val localWorkerPlatformVersion = bundleContext.getProperty(PLATFORM_VERSION_KEY)?.toInt() ?: DEFAULT_PLATFORM_VERSION
I think using the a dummy field is probably better.  If I used the correct property I'd have to then find it from `gradle.properties` to match against in the test.  This is simpler and still gets the job done.

2023-01-12 10:24 UTC, fowlerrr commented on libs/platform-info/src/main/kotlin/net/corda/libs/platform/impl/PlatformInfoProviderImpl.kt
> +    override val localWorkerPlatformVersion = bundleContext.getProperty(PLATFORM_VERSION_KEY)?.toInt() ?: DEFAULT_PLATFORM_VERSION
Also, this doesn't help for the `BundleVersion` string which I'd want to check as well.  I think we can leave the integration tests out for now.

2023-01-13 09:44 UTC, chrisr3 requested changes
The tests don't need to depend on Felix - `osgi.core` will do instead.

2023-01-13 09:44 UTC, chrisr3 commented on libs/platform-info/build.gradle
> +    testImplementation "org.apache.felix:org.apache.felix.framework:$felixVersion"
I doubt you need all of Felix here. Will just `org.osgi:osgi.core` do instead?

2023-01-13 09:44 UTC, chrisr3 commented on buildSrc/src/main/groovy/corda.common-app.gradle
> +    frameworkProperties.put('net.corda.platform.version', osgiRun.platformVersion)
I'd suggest leaving it "as is" until if/when we need to add another mandatory but internal value into the framework properties.

2023-01-13 16:11 UTC, simon-johnson-r3 approved these changes

2023-01-16 09:47 UTC, chrisr3 approved these changes
LGTM

2023-01-16 10:28 UTC, mcgovc approved these changes
LGTM - build

2023-01-16 10:29 UTC, merged