CORE-9058 Group approval rules API
corda/corda-runtime-os pull request #2908
Opened 2023-01-12 12:25 UTC by YashNabar

https://r3-cev.atlassian.net/browse/CORE-9058

2023-01-12 14:52 UTC, charlieR3 commented on components/membership/membership-service-impl/src/main/kotlin/net/corda/membership/service/impl/MemberOpsServiceProcessor.kt
> +    private inner class AddApprovalRuleRequestHandler : RpcHandler<AddApprovalRuleRequest> {
I had a similar comment to this on Yiftach's PR recently - I don't think this needs to go through the membership worker. The changes have the RPC worker, asking the membership worker to persist through the database worker. All the membership worker is doing is checking if it's a valid holding ID and if it's not an MGM, both of which could just be done on the RPC worker side and then the `membershipPersistenceClient` could just be called directly from the RPC worker, cutting out the membership worker and the additional use of the RPC pattern (which we need to try reduce anyway soon)

2023-01-13 08:43 UTC, YashNabar commented on components/membership/membership-service-impl/src/main/kotlin/net/corda/membership/service/impl/MemberOpsServiceProcessor.kt
> +    private inner class AddApprovalRuleRequestHandler : RpcHandler<AddApprovalRuleRequest> {
Removed in [2a9431e](https://github.com/corda/corda-runtime-os/pull/2908/commits/2a9431ef536bc5b9b0f6bf70633d72f8a2a5001c)

2023-01-16 14:56 UTC, vkolomeyko commented on components/membership/membership-http-rpc/src/main/kotlin/net/corda/membership/httprpc/v1/MGMRpcOps.kt
> +        rule: String,
Just a siggestion: Rather than having two `String` as two body parameters, woud it not be better to introduce a dedicated data class as follows:
```
data class GroupApprovalRuleParam(val ruleRegEx: String, ruleName: String)
```

2023-01-16 14:56 UTC, vkolomeyko commented on components/membership/membership-http-rpc/src/main/kotlin/net/corda/membership/httprpc/v1/MGMRpcOps.kt
> +        label: String? = null
Suggestion: Why not to introduce data class encapsulating those two Strings?
```
data class GroupApprovalRule(val ruleRegEx: String, val ruleName: String)
```

2023-01-16 14:56 UTC, vkolomeyko commented on components/membership/membership-http-rpc/src/main/kotlin/net/corda/membership/httprpc/v1/MGMRpcOps.kt
> +    ): Collection<String>
```suggestion
    ): Collection<GroupApprovalRuleWithId>
```
as per above.

2023-01-16 14:56 UTC, vkolomeyko commented on components/membership/membership-http-rpc/src/main/kotlin/net/corda/membership/httprpc/v1/MGMRpcOps.kt
> +    @HttpRpcPUT(
```suggestion
    @HttpRpcDELETE(
```

2023-01-16 17:29 UTC, charlieR3 reviewed
Review still in progress but submitting a couple points now to review in the morning.

2023-01-16 17:29 UTC, charlieR3 commented on components/membership/membership-http-rpc/src/main/kotlin/net/corda/membership/httprpc/v1/MGMRpcOps.kt
> +    ): String?
When would null be returned?

2023-01-16 17:29 UTC, charlieR3 commented on components/membership/membership-client/src/main/kotlin/net/corda/membership/client/MGMOpsClient.kt
> +     * @param holdingIdentityShortHash The holding identity ID of the MGM of the membership group to be joined.
```suggestion
     * @param holdingIdentityShortHash The holding identity ID of the MGM.
```
I'm not sure tat "to be joined" makes sense for the generate group policy endpoint

2023-01-16 17:29 UTC, charlieR3 commented on components/membership/membership-client/src/main/kotlin/net/corda/membership/client/MGMOpsClient.kt
> +    @Throws(CouldNotFindMemberException::class, MemberNotAnMgmException::class)
The RPC impl seems to also expect a membership persistence exception

2023-01-16 17:29 UTC, charlieR3 commented on components/membership/membership-client/src/main/kotlin/net/corda/membership/client/MGMOpsClient.kt
> +     * @param ruleType Can be `STANDARD` for group approval rules, or `PREAUTH` for pre-auth token rules.
This comment might go out of sync if we modify `ApprovalRuleType` at all. Could be better to say something like `The approval rule type for this rule. See [ApprovalRuleType] for the available types.`

2023-01-16 17:29 UTC, charlieR3 commented on components/membership/membership-client/src/main/kotlin/net/corda/membership/client/MGMOpsClient.kt
> +     * @param ruleType Can be `STANDARD` for group approval rules, or `PREAUTH` for pre-auth token rules.
(same comment for the `getApprovalRules` function)

2023-01-16 17:29 UTC, charlieR3 commented on components/membership/membership-persistence-client-impl/src/main/kotlin/net/corda/membership/impl/persistence/client/MembershipPersistenceClientImpl.kt
> +            buildMembershipRequestContext(viewOwningIdentity.toAvro()),
Maybe not something to fix in this PR, but looking at this, I think almost everywhere we call `buildMembershipRequestContext` we are calling `HoldingIdentity#toAvro()`. Could be a good idea to change the signature of `buildMembershipRequestContext` to the non-avro type and just call `toAvro` in the function.

2023-01-16 17:29 UTC, charlieR3 commented on components/membership/membership-persistence-service-impl/src/main/kotlin/net/corda/membership/impl/persistence/service/handler/PersistApprovalRuleHandler.kt
> +                    ruleId,
What is the expected behaviour if the ID is already in use?

2023-01-16 17:52 UTC, nikinagy reviewed
First set of comments, will continue tomorrow.

2023-01-16 17:52 UTC, nikinagy commented on components/membership/membership-http-rpc/src/main/kotlin/net/corda/membership/httprpc/v1/MGMRpcOps.kt
> +    ): Collection<String>
I would expect to have the ID listed here as Viktor suggested. We can't even delete without the ID, so returning only the regexes are not making too much sense.

2023-01-16 17:52 UTC, nikinagy commented on components/membership/membership-http-rpc-impl/src/main/kotlin/net/corda/membership/impl/httprpc/v1/MGMRpcOpsImpl.kt
> +                    message = "Member with holding identity $holdingIdentityShortHash is not an MGM.",
Can we have a common val for these messages? too much code repeat
In fact probably would be even better to have a function for creating this InvalidInputDataException as its the same in the whole class.

2023-01-16 17:52 UTC, nikinagy commented on components/membership/membership-http-rpc-impl/src/test/kotlin/net/corda/membership/impl/httprpc/v1/MGMRpcOpsTest.kt
> +            mgmRpcOps.activate("")
can we move these to a common function called activate() or startService()?

2023-01-16 17:52 UTC, nikinagy commented on components/membership/membership-http-rpc-impl/src/test/kotlin/net/corda/membership/impl/httprpc/v1/MGMRpcOpsTest.kt
> +            mgmRpcOps.stop()
can we move these to a common function called deactivate() or stopService()?

2023-01-16 17:52 UTC, nikinagy commented on components/membership/membership-http-rpc-impl/src/test/kotlin/net/corda/membership/impl/httprpc/v1/MGMRpcOpsTest.kt
> +            val label = "label"
Rule and label are highly used within this class, can be const both of them.

2023-01-16 17:52 UTC, nikinagy commented on components/membership/membership-http-rpc-impl/src/test/kotlin/net/corda/membership/impl/httprpc/v1/MGMRpcOpsTest.kt
> +            val ruleId = "rule-id"
Const here too

2023-01-16 17:52 UTC, nikinagy commented on components/membership/membership-http-rpc-impl/src/test/kotlin/net/corda/membership/impl/httprpc/v1/MGMRpcOpsTest.kt
> +                mgmRpcOps.deleteGroupApprovalRule("ABS09234745D", "rule-id")
have const for this holding identity too

2023-01-16 17:52 UTC, nikinagy commented on components/membership/membership-client/src/main/kotlin/net/corda/membership/client/MGMOpsClient.kt
>       * @throws [MemberNotAnMgmException] If the member [holdingIdentityShortHash] is not an MGM.
```suggestion
     * @throws [MemberNotAnMgmException] If the member identified by [holdingIdentityShortHash] is not an MGM.
```

2023-01-16 17:52 UTC, nikinagy commented on components/membership/membership-client/src/main/kotlin/net/corda/membership/client/MGMOpsClient.kt
> +     * @throws [MemberNotAnMgmException] If the member [holdingIdentityShortHash] is not an MGM.
```suggestion
     * @throws [MemberNotAnMgmException] If the member identified by [holdingIdentityShortHash] is not an MGM.
```

2023-01-16 17:52 UTC, nikinagy commented on components/membership/membership-client/src/main/kotlin/net/corda/membership/client/MGMOpsClient.kt
> +     * @throws [MemberNotAnMgmException] If the member [holdingIdentityShortHash] is not an MGM.
```suggestion
     * @throws [MemberNotAnMgmException] If the member identified by [holdingIdentityShortHash] is not an MGM.
```

2023-01-16 17:52 UTC, nikinagy commented on components/membership/membership-client/src/main/kotlin/net/corda/membership/client/MGMOpsClient.kt
> +     * @throws [MemberNotAnMgmException] If the member [holdingIdentityShortHash] is not an MGM.
```suggestion
     * @throws [MemberNotAnMgmException] If the member identified by [holdingIdentityShortHash] is not an MGM.
```

2023-01-16 17:52 UTC, nikinagy commented on components/membership/membership-client-impl/src/main/kotlin/net/corda/membership/impl/client/MGMOpsClientImpl.kt
> +            ).getOrThrow()
mgmHoldingIdentity(holdingIdentityShortHash) can be directly called here, avoid one time usage vals

2023-01-16 17:52 UTC, nikinagy commented on components/membership/membership-client-impl/src/main/kotlin/net/corda/membership/impl/client/MGMOpsClientImpl.kt
> +                mgmHoldingIdentity,
same comment as above

2023-01-16 17:52 UTC, nikinagy commented on components/membership/membership-client-impl/src/main/kotlin/net/corda/membership/impl/client/MGMOpsClientImpl.kt
> +                mgmHoldingIdentity,
same comment as above

2023-01-16 17:52 UTC, nikinagy commented on components/membership/membership-client-impl/src/test/kotlin/net/corda/membership/impl/client/MGMOpsClientTest.kt
> +            )
why not stop the client here?

2023-01-16 17:52 UTC, nikinagy commented on components/membership/membership-client-impl/src/test/kotlin/net/corda/membership/impl/client/MGMOpsClientTest.kt
> +            setUpRpcSender(null)
I think that these stuff can be unified into one function at least, to have less repetition and less chance to have any mistakes.

2023-01-16 17:52 UTC, nikinagy commented on components/membership/membership-client-impl/src/test/kotlin/net/corda/membership/impl/client/MGMOpsClientTest.kt
> +                MembershipQueryResult.Success(listOf("rule"))
When we use the same string values more than once, can we make them as consts?

2023-01-16 17:52 UTC, nikinagy commented on components/membership/membership-client-impl/src/test/kotlin/net/corda/membership/impl/client/MGMOpsClientTest.kt
> +            )
stop is missing here too

2023-01-16 17:52 UTC, nikinagy commented on components/membership/membership-client-impl/src/test/kotlin/net/corda/membership/impl/client/MGMOpsClientTest.kt
> +                MembershipPersistenceResult.Success("rule-id")
We have a const with the same value called RULE_ID, can we use that here?

2023-01-16 17:52 UTC, nikinagy commented on components/membership/membership-client-impl/src/test/kotlin/net/corda/membership/impl/client/MGMOpsClientTest.kt
> +            val ruleId = "rule-id"
We have a const with the same value called RULE_ID, can we use that here?

2023-01-17 10:48 UTC, nikinagy commented on components/membership/membership-persistence-client-impl/src/test/kotlin/net/corda/membership/impl/persistence/client/MembershipPersistenceClientImplTest.kt
> +            val ruleId = "id"
Consts are needed in this whole test class

2023-01-17 10:48 UTC, nikinagy commented on libs/membership/membership-datamodel/src/test/kotlin/net/corda/membership/datamodel/ApprovalRulesEntityTest.kt
> +            assertNotEquals(e1, null)
isn't this the same as assertnotnull?

2023-01-17 10:48 UTC, nikinagy commented on libs/membership/membership-datamodel/src/test/kotlin/net/corda/membership/datamodel/ApprovalRulesEntityTest.kt
> +            val e1 = ApprovalRulesEntity(
you can put these one time usage vals into the assertions directly

2023-01-17 10:48 UTC, nikinagy commented on libs/membership/membership-datamodel/src/test/kotlin/net/corda/membership/datamodel/ApprovalRulesEntityTest.kt
> +            assertNotEquals(e1, null)
btw what are we testing here? it's not really clear

2023-01-17 10:50 UTC, nikinagy commented
Next time we do manual testing, can we attach some screenshots to the ticket? Or just describe it in a very short section what scenarios you followed, etc.

2023-01-17 11:10 UTC, charlieR3 commented on components/membership/membership-service-impl/src/test/kotlin/net/corda/membership/service/impl/MemberOpsServiceProcessorTest.kt
> +        on { getApprovalRules(any(), any()) } doReturn MembershipQueryResult.Success(listOf("rule"))
Is anything using this?

2023-01-17 11:10 UTC, charlieR3 commented on libs/membership/membership-datamodel/src/test/kotlin/net/corda/membership/datamodel/RegistrationRequestEntityTest.kt
> +    fun `entities are not equal if registration id matches`() {
What is this change for? It looks like the test is still comparing for equality

2023-01-17 11:10 UTC, charlieR3 commented on components/membership/membership-persistence-service-impl/src/main/kotlin/net/corda/membership/impl/persistence/service/handler/QueryApprovalRulesHandler.kt
> +                .map { it.ruleRegex }
I think this is mentioned already on the review of the API, but I think we should return everything here. i.e. rule, rule type, label, and ID

2023-01-17 11:17 UTC, YashNabar commented on libs/membership/membership-datamodel/src/test/kotlin/net/corda/membership/datamodel/ApprovalRulesEntityTest.kt
> +            assertNotEquals(e1, null)
This is because we have overridden `equals()`. This tests line 31 of `ApprovalRulesEntity`

2023-01-17 11:39 UTC, YashNabar commented on components/membership/membership-http-rpc/src/main/kotlin/net/corda/membership/httprpc/v1/MGMRpcOps.kt
> +        rule: String,
Added in [701e350](https://github.com/corda/corda-runtime-os/pull/2908/commits/701e3508fd7a20ddbb2d39ea34884b8b51da2ec1)

2023-01-17 11:46 UTC, YashNabar commented on components/membership/membership-persistence-service-impl/src/main/kotlin/net/corda/membership/impl/persistence/service/handler/PersistApprovalRuleHandler.kt
> +                    ruleId,
Discussed offline, that would be an integrity constraint violation and will be handled in `MembershipPersistenceRequest.execute()`

2023-01-17 11:47 UTC, YashNabar commented on components/membership/membership-persistence-service-impl/src/main/kotlin/net/corda/membership/impl/persistence/service/handler/QueryApprovalRulesHandler.kt
> +                .map { it.ruleRegex }
Discussed offline, now returning the ID, regex, and label

2023-01-17 15:38 UTC, charlieR3 commented on components/membership/membership-http-rpc/src/main/kotlin/net/corda/membership/httprpc/v1/MGMRpcOps.kt
> +    ): String
Should this be `ApprovalRuleInfo` now?

2023-01-17 15:38 UTC, charlieR3 commented on components/membership/membership-http-rpc/src/main/kotlin/net/corda/membership/httprpc/v1/MGMRpcOps.kt
> +        path = "{holdingIdentityShortHash}/approval/rules/delete/{ruleId}",
Do you think we could remove `delete` from the URL since the HTTP verb is delete?

2023-01-17 15:38 UTC, charlieR3 commented on components/membership/membership-http-rpc-impl/src/main/kotlin/net/corda/membership/impl/httprpc/v1/MGMRpcOpsImpl.kt
> +            } catch (e: MembershipPersistenceException) {
You're catching `MembershipPersistenceException` here and in `addGroupApprovalRule` and mapping it to a very specific error message in both cases even though the exception seems more generic. Should the message from the persistence exception be used instead or maybe a specific exception created for the scenarios these are being mapped to?

2023-01-17 15:38 UTC, charlieR3 commented on components/membership/membership-client/src/main/kotlin/net/corda/membership/client/MGMOpsClient.kt
> +    fun addApprovalRule(
Could be good to do something similar here and have a data class for rule, rule type and label, and return `ApprovalRuleDetails` for consistency

2023-01-17 15:38 UTC, charlieR3 commented on components/membership/membership-http-rpc-impl/src/main/kotlin/net/corda/membership/impl/httprpc/v1/MGMRpcOpsImpl.kt
> +            } catch (e: MembershipPersistenceException) {
Unless there's only one possibility for throwing a persistence exception in each case.

2023-01-17 15:38 UTC, charlieR3 commented on components/membership/membership-persistence-client/src/main/kotlin/net/corda/membership/persistence/client/MembershipPersistenceClient.kt
> +        rule: String,
Could also use a data class here for rule info and return `ApprovalRuleDetails` for consistency

2023-01-18 08:46 UTC, wzur-r3 requested changes

2023-01-18 08:46 UTC, wzur-r3 commented on gradle.properties
> +cordaApiVersion=5.0.0.613-alpha-1673956888246
this cannot be right

we should never use a build from a pull requests here

2023-01-18 09:12 UTC, YashNabar commented on gradle.properties
> +cordaApiVersion=5.0.0.613-alpha-1673956888246
This is temporary till the related corda-api change is merged. This will be changed back to beta+ before merging.

2023-01-18 10:41 UTC, charlieR3 submitted a review, later dismissed
LGTM

2023-01-18 17:22 UTC, charlieR3 approved these changes
LGTM

2023-01-18 17:29 UTC, wzur-r3 approved these changes
LGTM for Gradle files

2023-01-19 09:19 UTC, vkolomeyko approved these changes
LGTM

2023-01-19 09:22 UTC, merged