NOTICK Transaction verification tests
corda/corda-runtime-os pull request #2915
Opened 2023-01-13 15:33 UTC by lankydan

2023-01-13 16:26 UTC, vlajos submitted a review, later dismissed
LGTM.

2023-01-13 17:37 UTC, blsemo commented on components/ledger/ledger-utxo-flow/src/main/kotlin/net/corda/ledger/utxo/flow/impl/transaction/verifier/UtxoTransactionEncumbranceVerifier.kt
> +class UtxoTransactionEncumbranceVerifier(private val transaction: UtxoLedgerTransaction) {
What's the point of creating a class when it does not encapsulate any data beyond the one function call?

2023-01-13 17:42 UTC, MrMatthewLayton approved these changes, later dismissed
LGTM

2023-01-13 17:44 UTC, MrMatthewLayton commented on components/ledger/ledger-utxo-flow/src/main/kotlin/net/corda/ledger/utxo/flow/impl/transaction/verifier/UtxoTransactionEncumbranceVerifier.kt
> +class UtxoTransactionEncumbranceVerifier(private val transaction: UtxoLedgerTransaction) {
@blsemo The Single Responsibility Principle; the caller likely shouldn't be responsible for this verification.

2023-01-16 10:09 UTC, blsemo commented on components/ledger/ledger-utxo-flow/src/main/kotlin/net/corda/ledger/utxo/flow/impl/transaction/verifier/UtxoTransactionEncumbranceVerifier.kt
> +class UtxoTransactionEncumbranceVerifier(private val transaction: UtxoLedgerTransaction) {
Ok but it's still a single function you call, you just wrap it in a class?

2023-01-19 14:37 UTC, MrMatthewLayton commented on components/ledger/ledger-utxo-flow/src/main/kotlin/net/corda/ledger/utxo/flow/impl/transaction/verifier/UtxoTransactionEncumbranceVerifier.kt
> +class UtxoTransactionEncumbranceVerifier(private val transaction: UtxoLedgerTransaction) {
@blsemo Yes that makes sense, we could just have top-level functions for this.

2023-02-08 22:26 UTC, MrMatthewLayton requested changes

2023-02-08 22:26 UTC, MrMatthewLayton commented on components/ledger/ledger-utxo-flow/src/main/kotlin/net/corda/ledger/utxo/flow/impl/transaction/verifier/UtxoTransactionBuilderVerifier.kt
> +        check(transactionBuilder.getEncumbranceGroups().all { it.value.isNotEmpty() }) {
Encumbrance groups must contain > 1 item.

2023-02-09 09:52 UTC, lankydan commented on components/ledger/ledger-utxo-flow/src/main/kotlin/net/corda/ledger/utxo/flow/impl/transaction/verifier/UtxoTransactionBuilderVerifier.kt
> +        check(transactionBuilder.getEncumbranceGroups().all { it.value.isNotEmpty() }) {
Ah ok, I misunderstood that code then.

2023-02-09 11:01 UTC, MrMatthewLayton approved these changes

2023-02-09 18:39 UTC, merged