CORE-9469 Use the Crypto API to fetch signing keys
corda/corda-runtime-os pull request #2960
Opened 2023-01-23 15:06 UTC by nkovacsx

### Overview

Previously we were using `MemberInfo`s to fetch the notary keys for signing. 
Now we use the crypto API to fetch the signing keys that correspond to the notary service's (composite) key.

### Testing

Added an extra test scenario to `LedgerUniquenessCheckerClientServiceImpl` where we test both simple keys as well.
Re-run current smoke/e2e tests.

2023-01-24 08:40 UTC, relyafi requested changes

2023-01-24 08:40 UTC, relyafi commented on components/uniqueness/uniqueness-checker-client-service-impl/src/main/kotlin/net/corda/uniqueness/client/impl/LedgerUniquenessCheckerClientServiceImpl.kt
> +        val selectedSigningKey = signingKeys.values.filterNotNull().first()
Lines 147 and 151 appear to be doing repeated work. It might be cleaner to condense all of this into something like:

```suggestion
        val selectedSigningKey = signingService
            .findMySigningKeys(setOf(notaryServiceKey)).values
            .filterNotNull()
            .firstOrNull()
            
        require(selectedSigningKey != null) {
            ...
        }
```

2023-01-24 08:40 UTC, relyafi commented on components/uniqueness/uniqueness-checker-client-service-impl/src/main/kotlin/net/corda/uniqueness/client/impl/LedgerUniquenessCheckerClientServiceImpl.kt
> +            "Could not find any keys that belongs to the notary service's public key."
```suggestion
            "Could not find any keys associated with the notary service's public key."
```

2023-01-24 08:40 UTC, relyafi commented on components/uniqueness/uniqueness-checker-client-service-impl/src/main/kotlin/net/corda/uniqueness/client/impl/LedgerUniquenessCheckerClientServiceImpl.kt
> +            "The notary key selected for signing is not part of the notary service key."
```suggestion
            "The notary key selected for signing is not associated with the notary service key."
```

2023-01-24 08:40 UTC, relyafi commented on components/uniqueness/uniqueness-checker-client-service-impl/src/main/kotlin/net/corda/uniqueness/client/impl/LedgerUniquenessCheckerClientServiceImpl.kt
> +        require(notaryServiceKey.containsAny(setOf(selectedSigningKey))) {
```suggestion
        require(notaryServiceKey.isFulfilledBy(selectedSigningKey)) {
```

We've already selected an exact key, so no need to use the collection API? I've had a look in corda-api and I _think_ this is composite key compatible, but you'll need to double check.

2023-01-24 08:40 UTC, relyafi commented on components/uniqueness/uniqueness-checker-client-service-impl/src/test/kotlin/net/corda/uniqueness/client/impl/LedgerUniquenessCheckerClientServiceImplTest.kt
> +    fun `Signing is successful when the provided notary service key is a simple key and the selected key does not match`() {
```suggestion
    fun `Signing is unsuccessful when the provided notary service key is a simple key and the selected key does not match`() {
```

2023-01-24 11:43 UTC, nkovacsx commented on components/uniqueness/uniqueness-checker-client-service-impl/src/main/kotlin/net/corda/uniqueness/client/impl/LedgerUniquenessCheckerClientServiceImpl.kt
> +        require(notaryServiceKey.containsAny(setOf(selectedSigningKey))) {
Hmm good point, thanks!

2023-01-24 12:26 UTC, nkovacsx commented on components/uniqueness/uniqueness-checker-client-service-impl/src/main/kotlin/net/corda/uniqueness/client/impl/LedgerUniquenessCheckerClientServiceImpl.kt
> +        val selectedSigningKey = signingKeys.values.filterNotNull().first()
Good point!

2023-01-24 13:36 UTC, relyafi submitted a review, later dismissed
LGTM

2023-01-24 15:46 UTC, blsemo approved these changes, later dismissed
LGTM

2023-01-25 14:55 UTC, nkovacsx commented
Removed `isFulfilledBy` as it seems it's not exactly what we want. It checks that the provided key(s) completely fulfils the composite key which is not true in our case. Replaced it with `containsAny` which will be a double check but it can't hurt.

2023-01-25 15:33 UTC, relyafi approved these changes, later dismissed

2023-01-26 08:50 UTC, blsemo approved these changes

2023-01-26 09:52 UTC, merged