CORE-9451 crypto config rework broken WIP
corda/corda-runtime-os pull request #3025
Opened 2023-01-31 11:31 UTC by dickon

2023-02-02 16:16 UTC, driessamyn reviewed
Looks good to me, just one minor comment, but will wait for @kyriathar 's review.

2023-02-02 16:16 UTC, driessamyn commented on processors/member-processor/src/integrationTest/kotlin/net/corda/processor/member/MemberProcessorTestUtils.kt
> +        fun Publisher.publishDefaultCryptoConf(cryptoConfig: Config) =
I don't think this change is necessary.

2023-02-02 16:26 UTC, dickon commented on processors/member-processor/src/integrationTest/kotlin/net/corda/processor/member/MemberProcessorTestUtils.kt
> +        fun Publisher.publishDefaultCryptoConf(cryptoConfig: Config) =
Yes, it was left over from an earlier direction I took and then largley reverted. Fixed.

2023-02-06 15:42 UTC, kyriathar reviewed
Some comments, still need to look at dynamic config that we removed.

2023-02-06 15:42 UTC, kyriathar commented on applications/workers/release/crypto-worker/src/main/kotlin/net/corda/applications/workers/crypto/CryptoWorker.kt
>      var hsmId = ""
I think this refers to the hard HSMs which we will not support so I agree it should be removed. Could we please raise a JIRA ticket and reference it from here if not intended to remove in this PR?

2023-02-06 15:42 UTC, kyriathar commented on applications/workers/worker-common/src/main/kotlin/net/corda/applications/workers/workercommon/WorkerHelpers.kt
> +        )
I think `SmartConfigFactory` is already available through `SmartConfig.factory` so maybe we don't need this data class.

2023-02-06 15:42 UTC, kyriathar commented on applications/workers/worker-common/src/main/kotlin/net/corda/applications/workers/workercommon/WorkerHelpers.kt
> +         * but do not fill in defaults.
nitpicky: I think there are mentioned some implementation details here. Could we simplify to say: 

"Creates bootstrap configuration out of command line configuration and gets validated against schema: `corda.boot.json`

It is then passed to workers' processors and also to `ConfigurationReadService` (see `ConfigurationReadService.bootstrapConfig`)."

Maybe also briefly say what it contains?

2023-02-06 15:42 UTC, kyriathar commented on applications/workers/worker-common/src/main/kotlin/net/corda/applications/workers/workercommon/WorkerHelpers.kt
> +            //
I think maybe remove this comment? First part should be mentioned on kDoc. Then the defaulting I think you mean happens later. Here the defaulting is whatever comes in from for `DefaultWorkerParams` and workers specific defaulted fields.

2023-02-06 15:42 UTC, kyriathar commented on applications/workers/worker-common/src/main/kotlin/net/corda/applications/workers/workercommon/WorkerHelpers.kt
> +            val smartConfigFactory = SmartConfigFactory
We could remove this variable and inline with `bootConfig`.

2023-02-06 15:42 UTC, kyriathar commented on components/configuration/README.md
> +soruces of configuration, we also write configuration records to a to Kafka so that they can be passed around multiple
```suggestion
sources of configuration, we also write configuration records to Kafka so that they can be passed around multiple
```

2023-02-06 15:42 UTC, kyriathar commented on components/configuration/README.md
> +   but what is in it is guaranteed to match the schema, or else this step will fail.
I believe when you say "all keys specified" you mean dynamic config coming in from RPC. So different than bootstrap config. I think this section might be a bit misleading.

2023-02-06 15:42 UTC, kyriathar commented on components/configuration/README.md
> +Corda makes use of the [typesafe config](https://github.com/lightbend/config) configuration library. We extend
I think let's remove this README file from here and lets make it a confluence wiki page. Then we can review there and potentially add it back here. I think, it is currently very detailed making it a bit hard to follow. Also might become obsolete if any of the steps changes.

2023-02-06 15:42 UTC, kyriathar commented on components/configuration/configuration-read-service/src/main/kotlin/net/corda/configuration/read/ConfigurationReadService.kt
> +     *  @throws ConfigurationException If the bootstrap configuration is provided after a connection has been
I would revert these kDocs.

2023-02-06 15:42 UTC, kyriathar commented on applications/workers/release/combined-worker/src/main/kotlin/net/corda/applications/workers/combined/CombinedWorker.kt
> +        // getBootstrapConfig and the PostgresDbSetup below.
Should we remove this comment?

2023-02-06 15:42 UTC, kyriathar commented on libs/crypto/crypto-config-impl/src/main/kotlin/net/corda/crypto/config/impl/CryptoConfigUtils.kt
> +const val HSM_MAP_ITEM_OBJ = "hsmMap.%s"
I think revert back to private? Seems to only getting used in here.

2023-02-06 15:42 UTC, kyriathar commented on tools/plugins/initial-config/src/main/kotlin/net/corda/cli/plugin/initialconfig/CryptoConfigSubcommand.kt
> +            listOf(EncryptionSecretsServiceFactory())
My understanding is, in this cli tool we statically use `EncryptionSecretsServiceFactory`. But Corda could be using some different one? In which case it will not be able to decrypt these secrets?

2023-02-06 15:42 UTC, kyriathar commented on libs/crypto/crypto-core/src/main/kotlin/net/corda/crypto/core/aes/KeyCredentials.kt
> -package net.corda.crypto.core.aes
Removing this class has increased the changes footprint of this PR I think.

2023-02-06 17:53 UTC, driessamyn commented on applications/workers/worker-common/src/main/kotlin/net/corda/applications/workers/workercommon/WorkerHelpers.kt
> +        )
Good spot. We don't need this I think.

2023-02-06 17:54 UTC, dickon commented on applications/workers/release/crypto-worker/src/main/kotlin/net/corda/applications/workers/crypto/CryptoWorker.kt
>      var hsmId = ""
I don' thtink we need the overhead of a JIRA ticket for each tech debt TODO. I'll clarify the comment though, it's too vague.

2023-02-06 17:54 UTC, driessamyn commented on components/configuration/README.md
> +Corda makes use of the [typesafe config](https://github.com/lightbend/config) configuration library. We extend
I think some of this is already captured in the github wiki, so may you're right, maybe it should go there.

2023-02-06 19:18 UTC, dickon commented on applications/workers/worker-common/src/main/kotlin/net/corda/applications/workers/workercommon/WorkerHelpers.kt
> +        )
Yes, nice, done.

2023-02-06 19:19 UTC, dickon commented on applications/workers/release/crypto-worker/src/main/kotlin/net/corda/applications/workers/crypto/CryptoWorker.kt
>      var hsmId = ""
Jira Link added

2023-02-06 19:32 UTC, dickon commented on applications/workers/worker-common/src/main/kotlin/net/corda/applications/workers/workercommon/WorkerHelpers.kt
> +         * but do not fill in defaults.
The comment does address is implementation details. I don't see any problem with having such material in this comment, nor do I see anywhere else to put such a comment.  If this was split out to an interface and a subclass that implements the interface then you'd have a point. I did take the rest of your comment.

2023-02-06 19:37 UTC, dickon commented on applications/workers/worker-common/src/main/kotlin/net/corda/applications/workers/workercommon/WorkerHelpers.kt
> +            //
I updated the comment to clarify a little.

2023-02-06 19:39 UTC, dickon commented on applications/workers/worker-common/src/main/kotlin/net/corda/applications/workers/workercommon/WorkerHelpers.kt
> +            val smartConfigFactory = SmartConfigFactory
This changed a bit as a result of using SmartConfig.factory; I think it is okay now.

2023-02-06 19:41 UTC, dickon commented on components/configuration/README.md
> +   but what is in it is guaranteed to match the schema, or else this step will fail.
I don't think it's misleading, and I'm not sure what you are getting at.

2023-02-06 19:44 UTC, dickon commented on components/configuration/configuration-read-service/src/main/kotlin/net/corda/configuration/read/ConfigurationReadService.kt
> +     *  @throws ConfigurationException If the bootstrap configuration is provided after a connection has been
:+1: done

2023-02-06 19:51 UTC, dickon commented on components/configuration/README.md
> +Corda makes use of the [typesafe config](https://github.com/lightbend/config) configuration library. We extend
It's not clear that there's any reason to keep this internal. I agree it is tightly coupled to the code, which was one reason I put it here. I'm not sure how the github wiki handles branching, but usually wikis aren't good at that,  so the reason we still have significant detail in the READMEs is to give us the opportunity and encouragement to keep it in sync with the code.  Github wikis are good for point-in-time text. 

I don't think any of the detail here is irrelevant (and feel free to quibble on particular clauses in the text if you disagree) if you want to understand how configuration works, and configuration is important.  Simplification would be welcome, although I don't see much opportunity given our requirements.

2023-02-06 19:52 UTC, dickon commented on applications/workers/release/combined-worker/src/main/kotlin/net/corda/applications/workers/combined/CombinedWorker.kt
> +        // getBootstrapConfig and the PostgresDbSetup below.
Why?

2023-02-06 19:52 UTC, dickon commented on libs/crypto/crypto-config-impl/src/main/kotlin/net/corda/crypto/config/impl/CryptoConfigUtils.kt
> +const val HSM_MAP_ITEM_OBJ = "hsmMap.%s"
yeah done

2023-02-06 19:57 UTC, dickon commented on tools/plugins/initial-config/src/main/kotlin/net/corda/cli/plugin/initialconfig/CryptoConfigSubcommand.kt
> +            listOf(EncryptionSecretsServiceFactory())
Yeah, comment and ticket added.

2023-02-06 19:57 UTC, dickon commented on libs/crypto/crypto-core/src/main/kotlin/net/corda/crypto/core/aes/KeyCredentials.kt
> -package net.corda.crypto.core.aes
Right, but it's also dead code, since it was only used in this one place, so to not do so would have increased tech debt.

2023-02-06 19:58 UTC, dickon commented on components/configuration/README.md
> +soruces of configuration, we also write configuration records to a to Kafka so that they can be passed around multiple
done, thanks

2023-02-07 10:00 UTC, driessamyn requested changes

2023-02-07 10:00 UTC, driessamyn commented on .run/Combined Worker Local.run.xml
> +    <option name="PROGRAM_PARAMETERS" value="--instance-id=0 -mbus.busType=DATABASE -ddatabase.user=user -ddatabase.pass=password -ddatabase.jdbc.url=jdbc:postgresql://localhost:5432/cordacluster -dd
This should not be committed.

2023-02-07 11:04 UTC, driessamyn commented on applications/workers/release/combined-worker/src/main/kotlin/net/corda/applications/workers/combined/CombinedWorker.kt
> +        // getBootstrapConfig and the PostgresDbSetup below.
Is it still valid as the factory is available as a property on the SmartConfig?

2023-02-07 11:04 UTC, driessamyn commented on components/configuration/README.md
> +Corda makes use of the [typesafe config](https://github.com/lightbend/config) configuration library. We extend
The Github wiki isn't internal.

I think the question is really about how many places we have developer documentation in.

I agree it doesn't feel right to be here as it is inconsistent with other documentation.
I feel like it's too  much detail as well, which will go out of date quickly, but I appreciate that's subjective.

2023-02-07 11:37 UTC, dickon commented on .run/Combined Worker Local.run.xml
> +    <option name="PROGRAM_PARAMETERS" value="--instance-id=0 -mbus.busType=DATABASE -ddatabase.user=user -ddatabase.pass=password -ddatabase.jdbc.url=jdbc:postgresql://localhost:5432/cordacluster -dd
Yes, that was probabl a mistake in git rebasing, glad you spotted it.

2023-02-07 11:37 UTC, dickon commented on .run/Combined Worker Local.run.xml
> +    <option name="PROGRAM_PARAMETERS" value="--instance-id=0 -mbus.busType=DATABASE -ddatabase.user=user -ddatabase.pass=password -ddatabase.jdbc.url=jdbc:postgresql://localhost:5432/cordacluster -dd
reverted

2023-02-07 12:28 UTC, ronanbrowne submitted a review, later dismissed
LGTM - build

2023-02-07 13:06 UTC, driessamyn approved these changes
LGTM

2023-02-07 14:51 UTC, Tom-Fitzpatrick approved these changes

2023-02-07 14:58 UTC, mag1c-48 approved these changes
lgtm - build

2023-02-07 15:00 UTC, merged