CORE-9787: Enable local build cache
corda/corda-runtime-os pull request #3044
Opened 2023-02-01 15:40 UTC by knguyen-r3

* Enable usage of build cache locally
* Implemented new identity access base using gradleEnterprise.buildCache

2023-02-01 15:56 UTC, chrisr3 commented
Why on Earth to we want to enable the build cache locally? IIRC, the last time we had that turned on, people were trying to debug their JUnit tests ,and wondering why they were completing without stopping at any breakpoints?!

2023-02-01 18:13 UTC, ronanbrowne commented
@chrisr3 , thanks for flagging.

developer productivity is becoming more of an issue as runtime os grows to more than 300 submodels, 

Maybe before my time on the test issue as this is the first time we have configured grades remote cache to true for local use.
point taken, However, we shouldn't leverage the cache for compilation optimization / image building etc

as a workaround we can do something like this to avoid test caching locally based on remote outputs

```
tasks.withType(Test).configureEach {
 if (localDevEnv()) {  // sudo code
     outputs.upToDateWhen { false }
  }
}
```

2023-02-01 20:01 UTC, driessamyn commented
> @chrisr3 , thanks for flagging.
> 
> developer productivity is becoming more of an issue as runtime os grows to more than 300 submodels,
> 
> Maybe before my time on the test issue you mentioned, as this is the first time we have configured grades remote cache to true for local use. point taken, However, we should leverage the cache for compilation optimization / image building etc
> 
> as a workaround, we can do something like this to avoid test caching locally based on remote outputs
> 
> ```
> tasks.withType(Test).configureEach {
>  if (!System.getenv().containsKey("JENKINS_URL")) {  // not a CI env so local user
>      outputs.upToDateWhen { false }
>   }
> }
> ```

Or we can teach people how to run a build without the cache.
Personally, I would appreciate not having to sit through the 13 minutes of "unit" (they're so no unit tests) tests, 99% of which aren't impacted by my change.

2023-02-01 20:27 UTC, ronanbrowne commented
@chrisr3 / @driessamyn  I reached out to Gradle on this via their community slack channel for Gradle Ent support and got the following response.

TLDR: delegate to gradle let it decide, IntelliJ  will always choose to re-run a test if you explicitly tell it to even if cach is up-to-date

"IntelliJ usually also cares for the test always being rerun using an init script if you "run tests" even if they are delegated to Gradle, because IntelliJ has the opinion, if a user asks to run the tests, they should run and not be skipped.

I personally would not recommend disabling the cache for such a reason even if they were up-to-date or cached when run through IntelliJ properly. Even if one wonders why no breakpoints are hit an the test finished immediately, that should only happen once with confusion and then it should be clear what happened and why the next time.

But if you must, there are multiple possibilities:
- disable caching for test tasks
- disable caching for test tasks when run through IntelliJ
- disable caching for test tasks if some Gradle property is set so that the ones insisting can have the behaviour they want with the flick of a switch
- enable caching and tell people that insist to either disable the caching completely by setting in their Gradle user home, then it is also for all projects they work on, not only a specific one
- enable caching and tell people to use an init script in their Gradle user home to do whatever they want, like for example disabling caching on test tasks."


I am in favour here of going with gradles recommendation activating and giving someone the option to disable caching should they _really_ need to. Which can be done via `--no-build-cache` or `org.gradle.caching=false`

2023-02-02 09:36 UTC, ronanbrowne requested changes
see comment

2023-02-02 09:36 UTC, ronanbrowne commented on settings.gradle
> +                enabled = true
We need to make sure there is no issue if a dev doesn't have a valid API key set

```suggestion
                enabled = apiKey?.trim() ? true : false
```

2023-02-02 12:08 UTC, yarivus approved these changes
LGTM

2023-02-02 13:15 UTC, ronanbrowne approved these changes
LGTM

2023-02-02 17:32 UTC, merged