[CORE-9865] Interop/ Interop processor
corda/corda-runtime-os pull request #3048
Opened 2023-02-01 17:37 UTC by szymonsztuka

Added first cut of `InteropProcessor` reading and writing messages to P2P topics. The  message payload is a reused `SessionEvent` type for now.

New worker added in module `application/workers/interop`class
`net.corda.applications.workers.interop.InteropWorker`. 
New processor in module `processors/interop-processor` class `net.corda.processors.interop.internal.InteropProcessorImpl`.
It has a member field (@Reference)of `InteropService`.
New durable processor and service in module `components/interop/interop-service`
Class `net.corda.interop.service.InteropProcessor`contains the code producing (temporarily) messages back to `Schemas.P2P.P2P_OUT_TOPIC`.
The processor is bind to listen to `Schemas.P2P.P2P_IN_TOPIC` by the new service 
`net.corda.interop.service.InteropService`. 

Integration test added.

2023-02-02 12:27 UTC, yarivus requested changes

2023-02-02 12:27 UTC, yarivus commented on applications/workers/release/interop-worker/src/main/kotlin/net/corda/applications/workers/interop/InteropWorker.kt
> +    private val flowProcessor: InteropProcessor,
rename to interopProcessor

2023-02-02 12:27 UTC, yarivus commented on applications/workers/release/interop-worker/src/main/kotlin/net/corda/applications/workers/interop/InteropWorker.kt
> +        applicationBanner.show("Flow Worker", platformInfoProvider)
```suggestion
        applicationBanner.show("InterOp Worker", platformInfoProvider)
```

2023-02-02 12:27 UTC, yarivus commented on applications/workers/release/interop-worker/src/main/kotlin/net/corda/applications/workers/interop/InteropWorker.kt
> +        logger.info("Flow worker stopping.")
```suggestion
        logger.info("InterOp worker stopping.")
```

2023-02-02 12:27 UTC, yarivus commented on applications/workers/release/interop-worker/src/main/kotlin/net/corda/applications/workers/interop/InteropWorker.kt
> +/** Additional parameters for the flow worker are added here. */
```suggestion
/** Additional parameters for the interop worker are added here. */
```

Also - why do we need this additional stuff (InteropWorkerParams) - is it used currently ?

2023-02-02 12:27 UTC, yarivus commented on components/interop/interop-service/src/integrationTest/kotlin/net/corda/interop/service/integration/InteropServiceIntegrationTest.kt
> +class InteropServiceIntegrationTest {
I think you should start leveraging CRAFT5 from the get-go ...
Maybe initially in a very simple way and not using much of it ...
However, as tests will grow and become more complex, later it would be harder

2023-02-02 12:27 UTC, yarivus commented on components/interop/interop-service/src/integrationTest/kotlin/net/corda/interop/service/integration/InteropServiceIntegrationTest.kt
> +        // Test config updates don't break Flow Session Filter Service
"Flow" ?

2023-02-02 12:27 UTC, yarivus commented on components/interop/interop-service/src/integrationTest/kotlin/net/corda/interop/service/integration/InteropServiceIntegrationTest.kt
> +class TestFlowSessionFilterProcessor(
should this be renamed to reflect the InterOp flow ?

2023-02-02 12:27 UTC, yarivus commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
> +    override fun onNext(
name 'onNext' to short to reflect intent of the method ... so maybe a comment would help

2023-02-02 12:27 UTC, yarivus commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
> +        //flowConfig: SmartConfig
remove commented out code

2023-02-02 16:40 UTC, SaurabhR3 requested changes

2023-02-02 16:40 UTC, SaurabhR3 commented on applications/workers/release/interop-worker/src/main/kotlin/net/corda/applications/workers/interop/InteropWorker.kt
> +    /** Parses the arguments, then initialises and starts the [flowProcessor] and [verificationProcessor]. */
Should be interop processor

2023-02-02 16:40 UTC, SaurabhR3 commented on applications/workers/release/interop-worker/src/main/kotlin/net/corda/applications/workers/interop/InteropWorker.kt
> +        logger.info("Flow worker starting.")
Interop processor starting.

2023-02-02 16:40 UTC, SaurabhR3 commented on components/interop/interop-service/build.gradle
> +}
Not sure, we really need all dependencies. It's better to add as and when required.

2023-02-02 16:40 UTC, SaurabhR3 commented on components/interop/interop-service/src/integrationTest/kotlin/net/corda/interop/service/integration/InteropServiceIntegrationTest.kt
> +    fun `verify events are forwarded to the correct topic`() {
what sort of events it is? I think it can be renamed.

2023-02-02 16:57 UTC, szymonsztuka commented on components/interop/interop-service/src/integrationTest/kotlin/net/corda/interop/service/integration/InteropServiceIntegrationTest.kt
> +class TestFlowSessionFilterProcessor(
Fixed in https://github.com/corda/corda-runtime-os/pull/3048/commits/7360ddf706c3f30179a9e14d938a78efa2887ae0

2023-02-02 16:58 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
> +    override fun onNext(
Fixed in https://github.com/corda/corda-runtime-os/pull/3048/commits/7360ddf706c3f30179a9e14d938a78efa2887ae0, I've change the name of the class to show it's role `P2POutMessageCounter`

2023-02-02 16:58 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
> +        //flowConfig: SmartConfig
Fixed in https://github.com/corda/corda-runtime-os/commit/7360ddf706c3f30179a9e14d938a78efa2887ae0

2023-02-02 17:05 UTC, szymonsztuka commented on applications/workers/release/interop-worker/src/main/kotlin/net/corda/applications/workers/interop/InteropWorker.kt
> +    private val flowProcessor: InteropProcessor,
Fixed in https://github.com/corda/corda-runtime-os/commit/7360ddf706c3f30179a9e14d938a78efa2887ae0

2023-02-02 17:05 UTC, szymonsztuka commented on components/interop/interop-service/src/integrationTest/kotlin/net/corda/interop/service/integration/InteropServiceIntegrationTest.kt
> +        // Test config updates don't break Flow Session Filter Service
Renamed in https://github.com/corda/corda-runtime-os/commit/7360ddf706c3f30179a9e14d938a78efa2887ae0

2023-02-02 17:08 UTC, szymonsztuka commented on components/interop/interop-service/build.gradle
> +}
At the moment most of them are required.

2023-02-02 17:12 UTC, szymonsztuka commented on applications/workers/release/interop-worker/src/main/kotlin/net/corda/applications/workers/interop/InteropWorker.kt
> +    /** Parses the arguments, then initialises and starts the [flowProcessor] and [verificationProcessor]. */
Renamed in https://github.com/corda/corda-runtime-os/pull/3048/commits/625152628d0da20cb38c228afefda33100fa7bdc

2023-02-02 17:12 UTC, szymonsztuka commented on applications/workers/release/interop-worker/src/main/kotlin/net/corda/applications/workers/interop/InteropWorker.kt
> +        logger.info("Flow worker starting.")
Renamed in https://github.com/corda/corda-runtime-os/pull/3048/commits/625152628d0da20cb38c228afefda33100fa7bdc

2023-02-02 17:12 UTC, szymonsztuka commented on components/interop/interop-service/src/integrationTest/kotlin/net/corda/interop/service/integration/InteropServiceIntegrationTest.kt
> +    fun `verify events are forwarded to the correct topic`() {
Fix the name in https://github.com/corda/corda-runtime-os/pull/3048/commits/625152628d0da20cb38c228afefda33100fa7bdc

2023-02-03 09:30 UTC, yarivus reviewed
Much better ;) 
Still some pending comments

2023-02-03 09:47 UTC, szymonsztuka commented on components/interop/interop-service/src/integrationTest/kotlin/net/corda/interop/service/integration/InteropServiceIntegrationTest.kt
> +class InteropServiceIntegrationTest {
CRAFT5 is QA tool for black-box testing, this is internal component white-box testing

2023-02-03 10:17 UTC, yarivus commented on components/interop/interop-service/src/integrationTest/kotlin/net/corda/interop/service/integration/InteropServiceIntegrationTest.kt
> +class InteropServiceIntegrationTest {
I disagree w/ this blanket statement - it's too black/white.
CRAFT5 has constructs that will help in testing such components.

I hope @abellagonzalo / @tlawson3 can have a quick review and guide accordingly.

2023-02-03 10:33 UTC, tlawson3 commented on components/interop/interop-service/src/integrationTest/kotlin/net/corda/interop/service/integration/InteropServiceIntegrationTest.kt
> +class InteropServiceIntegrationTest {
https://r3holdco.slack.com/archives/C04LNPWTVCH/p1675354349090189

2023-02-03 10:41 UTC, yarivus commented on components/interop/interop-service/src/integrationTest/kotlin/net/corda/interop/service/integration/InteropServiceIntegrationTest.kt
> +class InteropServiceIntegrationTest {
Reading the linked discussion - I see no contradiction to my comment 
Some CRAFT5's constructs can be leveraged in this case.

2023-02-03 12:32 UTC, szymonsztuka commented on components/interop/interop-service/src/integrationTest/kotlin/net/corda/interop/service/integration/InteropServiceIntegrationTest.kt
> +class InteropServiceIntegrationTest {
I think there is misunderstanding: "_I think you should start leveraging CRAFT5 from the get-go_". I'm using integration tests accordingly to standards in this project. You are referring to CRAFT5 which is not this project and it's not used in this project.

2023-02-03 13:14 UTC, tlawson3 commented on components/interop/interop-service/src/integrationTest/kotlin/net/corda/interop/service/integration/InteropServiceIntegrationTest.kt
> +class InteropServiceIntegrationTest {
We looked at adding CRAFT5 into this runtime-os project a while back, and it was shot down as this is an open source project; and can only depend on other open source dependencies. Owen and Kat should know all about it.

2023-02-03 13:21 UTC, yarivus commented on components/interop/interop-service/src/integrationTest/kotlin/net/corda/interop/service/integration/InteropServiceIntegrationTest.kt
> +class InteropServiceIntegrationTest {
Fair point.
@abellagonzalo we should revise this direction as it consistently limits our testing.
An alternative which was also discussed in the past is separating the testing and its code to another repo (not corda-runtime-os).
This approach has already been taken by the non-functional-testing + soak-test + performance

2023-02-06 10:22 UTC, merged