CORE-9881 : Interop Message reader/ writer
corda/corda-runtime-os pull request #3073
Opened 2023-02-06 17:17 UTC by SaurabhR3

1. Mapping payload to InteropMessage 
2. Interop message transformer, convert the InteropMessage to Facade Request (Serialisation and De-serialisation for FacadeRequest) 
3. Changed Integration test for InteropMessage

2023-02-06 19:17 UTC, yarivus reviewed
see my comments

2023-02-06 19:17 UTC, yarivus commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/data/Facade.kt
> +data class FacadeId(val owner: String, val name: HierarchicalName, val version: String) {
The source filename will probably confuse with Dom's work ... 
Also, it seems you're defining FacadeId here - please coordinate w/ @r3domfox and consider renaming this file

2023-02-06 19:17 UTC, yarivus commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/data/FacadeParameterType.kt
> +sealed class FacadeParameterType<T> {
Is this class coordinated (taken) from @r3domfox  ?

2023-02-06 19:17 UTC, yarivus commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/data/JsonDeserialisation.kt
> +}
Can't we make this 1 class - anyways it's templated with FacadeRequest & FacadeResponse 🤔

2023-02-06 19:17 UTC, yarivus commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/data/JsonSerialisation.kt
> +}
Same comment here - we should be able to make this a single class instead of 2 (anyways we use template and write FacadeRequest and FacadeResponse)

2023-02-07 12:58 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/data/Facade.kt
> +data class FacadeId(val owner: String, val name: HierarchicalName, val version: String) {
I have used/copied these classes from @r3domfox facade implementation. I will double check with @r3domfox.

2023-02-07 12:59 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/data/FacadeParameterType.kt
> +sealed class FacadeParameterType<T> {
All these classes taken from facade implementation created by @r3domfox .

2023-02-07 13:08 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/data/JsonDeserialisation.kt
> +}
As it is associated with FacadeRequest and FacadeResponse, it is easily taken care by jakson serialisation and deserialisation. Also in FacadeRequest `inParameters` and FacadeResponse `outParameters` are getting de-serialised. using same method within this class.

2023-02-07 13:09 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/data/JsonSerialisation.kt
> +}
Please have a look to similar comment above.

2023-02-07 13:48 UTC, yarivus approved these changes
LGTM

2023-02-07 14:02 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/data/JsonDeserialisation.kt
> +}
We need a concrete class as the concrete type class is passed to annotation parameter (e.g. `@JsonDeserialize(using = FacadeRequestDeserializer::class)`)

2023-02-07 14:56 UTC, szymonsztuka requested changes

2023-02-07 14:56 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
> +        )
I would prefer to place a trivial code into one, to lines and don't introduce unnecessary new lines, e.g.:
```
    private val cordaAvroDeserializer: CordaAvroDeserializer<InteropMessage> =
        cordaAvroSerializationFactory.createAvroDeserializer({}, InteropMessage::class.java)
```
Instead of this:
```
    private val cordaAvroDeserializer: CordaAvroDeserializer<InteropMessage> =
        cordaAvroSerializationFactory.createAvroDeserializer(
            {},
            InteropMessage::class.java
        )
```

2023-02-07 14:56 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
> +        cordaAvroSerializationFactory.createAvroSerializer({})
the `(` and `)`can be committed: `cordaAvroSerializationFactory.createAvroSerializer{}`

2023-02-07 14:56 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
> -            SUBSYSTEM
The header generation should not be removed and replaced by putting just the same original header, the header generation here is on purpose to flip sender and receiver.

2023-02-07 14:56 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
> +            logger.info("Converted interop message to facade request : $InteropMessageTransformer.getFacadeRequest(interopMessage)}")
Instead using the core logic just for debug, better to transform Avro payload to FacadeRequest, and then again when the response is generated, transform FacadeRequest into Avro instead just reusing original Avro. In this case we can check serialisation and deserialisation.

2023-02-07 14:56 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/data/Facade.kt
> +
Maybe add some TODO (in all Facade classes) saying this is temporarily copied code from WEFT project, later on will be replaces by WEFT?

2023-02-07 14:56 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/InteropMessageTransformer.kt
> +class InteropMessageTransformer {
Just suggestion, I would personally inline those methods where they are used in InteropProcessor and don't created another layer. But it can like this.

2023-02-07 17:24 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
> -            SUBSYSTEM
SessionEvent is carrying some info like `initiatingIdentity` and `initiatedIdentity` which is available in headers and it was adding that info to generate new object of `AuthenticatedMessageHeader`. As we don't have any specific header generation requirement right now I used existing header object. 
I am not sure, it is important right now to flip the sender and receiver.
Please suggest

2023-02-07 17:30 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
> +            logger.info("Converted interop message to facade request : $InteropMessageTransformer.getFacadeRequest(interopMessage)}")
In this case, as we are not doing any process there is not any facade response. Also i believe, when we will get the facade response at that time we do't need to serialise the FacadeRequest again.

2023-02-07 17:30 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
> +        )
It was due to code formatting.

2023-02-07 17:33 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
> -            SUBSYSTEM
Please refer to your research/design https://r3-cev.atlassian.net/wiki/spaces/CB/pages/4304764992/Interop+Message+Contents where you wrote where these headers are.
It's important to flip sender with a receiver because we want to send the message back (to the sender) and not send again to ourselves (receiver).

2023-02-07 17:34 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
> +        cordaAvroSerializationFactory.createAvroSerializer({})
Fixed in ce98421

2023-02-07 18:12 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
> +            logger.info("Converted interop message to facade request : $InteropMessageTransformer.getFacadeRequest(interopMessage)}")
Fixed in 146d6cf

2023-02-07 18:13 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
> -            SUBSYSTEM
Fixed in 146d6cf

2023-02-07 19:15 UTC, yarivus approved these changes
LGTM

2023-02-07 19:15 UTC, yarivus commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/data/Facade.kt
> +data class FacadeId(val owner: String, val name: HierarchicalName, val version: String) {
Where do you see Facade in this file ... it's just the `FacadeId` and `of()`

2023-02-08 16:38 UTC, szymonsztuka approved these changes

2023-02-08 16:52 UTC, merged

2023-02-08 17:39 UTC, yarivus reviewed
thnx @szymonsztuka