CORE-9550 Add full public key id in DB signing keys
corda/corda-runtime-os pull request #3091
Opened 2023-02-08 14:20 UTC by kyriathar

WIP - raising for failures

2023-02-08 17:27 UTC, dickon commented on components/crypto/crypto-persistence-impl/src/main/kotlin/net/corda/crypto/persistence/impl/SigningKeyStoreImpl.kt
> +            if (ids[0].length == 12) {
This feels a bit too much of a hack, though i see your TODO above that this is temporary.

2023-02-08 17:28 UTC, dickon commented on components/crypto/crypto-persistence-impl/src/main/kotlin/net/corda/crypto/persistence/impl/SigningKeyStoreImpl.kt
> +            if (ids[0].length == 12) {
... since you never know when you can continue your work.

2023-02-09 15:30 UTC, kyriathar commented on components/crypto/crypto-persistence-impl/src/main/kotlin/net/corda/crypto/persistence/impl/SigningKeyStoreImpl.kt
> +            if (ids[0].length == 12) {
This is now removed

2023-02-13 09:32 UTC, mnesbit commented on components/crypto/crypto-client-impl/src/main/kotlin/net/corda/crypto/client/impl/CryptoOpsClientImpl.kt
> +    // TODO Users who are using this API need to revisit to determine if they need to migrate to search by full Id
For the REST calls I thin it is safe to assume we will continue with short id's. It is only when we are transmitting key info on the network that that is insufficient

2023-02-13 09:40 UTC, kyriathar commented on components/crypto/crypto-client-impl/src/main/kotlin/net/corda/crypto/client/impl/CryptoOpsClientImpl.kt
> +    // TODO Users who are using this API need to revisit to determine if they need to migrate to search by full Id
Both `lookupKeysByShortIds` and `lookupKeysByFullIds` APIs are now available. In our code base we currently only use `lookupKeysByShortIds` (ex `lookup`) because that's what we only had before. So users of if API might need to revisit to see if they 'd need to migrate to look with full key ids instead (sounds like all uses apart from REST calls).

2023-02-13 10:44 UTC, dickon commented on components/crypto/crypto-client-impl/src/main/kotlin/net/corda/crypto/client/impl/CryptoOpsClientImpl.kt
> +    // TODO Users who are using this API need to revisit to determine if they need to migrate to search by full Id
I find the complexity of 2 lenghts of key ID needs to be justified. Perhaps it's simply too expensive to send full IDs, but that feels like premature optimisation, and quite likey to be trivial compared to other run-time costs around Corda.

2023-02-13 15:46 UTC, dickon commented on components/crypto/crypto-persistence-impl/src/main/kotlin/net/corda/crypto/persistence/impl/SigningKeyStoreImpl.kt
> +            if (ids[0].length == 12) {
Might be nice to get the number 12 from the API, but not essential for me to approve.

2023-02-13 15:48 UTC, dickon commented on components/crypto/crypto-client-impl/src/main/kotlin/net/corda/crypto/client/impl/CryptoOpsClientImpl.kt
> +    // TODO Users who are using this API need to revisit to determine if they need to migrate to search by full Id
I now understand the reason for 2 different key lengths; we want shorter forms when conciseness matters, e.g. URL query strings, and we need longer forms where collisions are serious.

2023-02-13 15:52 UTC, dickon commented on components/crypto/crypto-persistence-impl/src/main/kotlin/net/corda/crypto/persistence/impl/SigningKeyStoreImpl.kt
> +        // TODO Add caching
This caching probably does need restoring before we can merge it.

2023-02-13 15:52 UTC, dickon commented on components/crypto/crypto-persistence-impl/src/main/kotlin/net/corda/crypto/persistence/impl/SigningKeyStoreImpl.kt
> +//            return cache.get(CacheKey(tenantId, publicKey.publicKeyId())) { cacheKey ->
If we don't do caching let's delete this commented out line.

2023-02-13 15:53 UTC, dickon commented on components/crypto/crypto-persistence-impl/src/main/kotlin/net/corda/crypto/persistence/impl/SigningKeyStoreImpl.kt
> +        // TODO Test edge scenario where short Ids clash at lookup
yeah, possibly is worth having a clash test, at least so we fail in a consistent way.

2023-02-13 16:02 UTC, dickon commented on components/crypto/crypto-persistence-model/src/main/kotlin/net/corda/crypto/persistence/db/model/SigningKeyEntity.kt
> +     * The key id, which is calculated as SHA256 converted to HEX string with only first 12 characters if it.
This denormalises the database in a nasty way, which is going to cause us problems in the future. I think we shouldn't do this, and instead keep the database as storing only the full length key id. 

In particular, we'll have to do leading prefix LIKE query, and trust that the database can use an index for that.

2023-02-13 16:02 UTC, dickon commented on components/crypto/crypto-persistence-model/src/main/kotlin/net/corda/crypto/persistence/db/model/SigningKeyEntity.kt
> +     * The key id, which is calculated as SHA256 converted to HEX string with only first 12 characters if it.
... which would probably also make this PR smaller.

2023-02-13 16:04 UTC, dickon requested changes
I think we need to preserve normalisation, i.e. store only full IDs. And we need to preserve caching.

I skimmed the rest, but that's quite a bit change so I'll go through more carefully when that's done.

2023-02-13 16:07 UTC, dickon commented on components/membership/certificates-client-impl/src/test/kotlin/net/corda/membership/certificate/client/impl/HostedIdentityEntryFactoryTest.kt
> +        const val SESSION_KEY_ID = "AB0123456789"
this change should be left out, it causes quite a  bit of extra stuff later. Add a TODO maybe instead.

2023-02-13 16:08 UTC, dickon requested changes

2023-02-13 16:08 UTC, dickon commented on gradle.properties
> +cordaApiVersion=5.0.0.638-alpha-1676039595844
revert, when your're ready

2023-02-13 16:12 UTC, dickon commented on components/crypto/crypto-client-impl/src/main/kotlin/net/corda/crypto/client/impl/CryptoOpsClientImpl.kt
> +    fun lookupKeysByShortIdsProxy(tenantId: String, candidateKeys: ShortHashes): CryptoSigningKeys {
So I think we shouldn't hang up on 12 byte prefixes, but instead allow arbitrary length prefixes, as for instance git does.

I said separately we can't store the short ID and full ID in the database without causing denormalisation trouble, so we will have to do LIKE prefix matching down in the database, so it'd actually be cleaner and easier to just allow arbitrary length prefixes, as long as it is not ambibiguous, i.e. the prefix uniquely selects a key hash.

So the ShortHashes class can go away.

2023-02-13 17:08 UTC, kyriathar commented on components/crypto/crypto-persistence-impl/src/main/kotlin/net/corda/crypto/persistence/impl/SigningKeyStoreImpl.kt
> +        // TODO Add caching
Caching is going to be restored with a follow up PR under same ticket.

2023-02-13 17:08 UTC, kyriathar commented on components/crypto/crypto-persistence-impl/src/main/kotlin/net/corda/crypto/persistence/impl/SigningKeyStoreImpl.kt
> +//            return cache.get(CacheKey(tenantId, publicKey.publicKeyId())) { cacheKey ->
Will be added with caching PR.

2023-02-13 17:09 UTC, kyriathar commented on components/membership/certificates-client-impl/src/test/kotlin/net/corda/membership/certificate/client/impl/HostedIdentityEntryFactoryTest.kt
> +        const val SESSION_KEY_ID = "AB0123456789"
Test fails without a valid `ShortHash` hex string.

2023-02-14 15:59 UTC, mnesbit submitted a review, later dismissed
OK

2023-02-16 07:11 UTC, wzur-r3 submitted a review, later dismissed
LGTM for Gradle build files

2023-02-16 11:50 UTC, dickon requested changes
Great work @kyriathar 



I have some minor nitpicks, and I can see 2 blocking issues:

1. It'd be easier to keep the caching removed here  than prove we don't need it.
2. I don't see a uniqueness constraint yet on the short hashes for signing keys (but maybe I missed it). We agreed this should be done in the database, on a per virtual node basiss.

2023-02-16 11:50 UTC, dickon commented on components/crypto/crypto-client-impl/src/main/kotlin/net/corda/crypto/client/impl/CryptoOpsClientImpl.kt
> +                            .also { secureHash -> keyIdsForLogging.add(secureHash.toString()) }
Cleaner to do this without a mutable list, using a separate map.

2023-02-16 11:50 UTC, dickon commented on components/crypto/crypto-client-impl/src/main/kotlin/net/corda/crypto/client/impl/CryptoOpsClientImpl.kt
> +                            .also { shortHash -> keyIdsForLogging.add(shortHash) }
and again, we don't need the side effects, just map it.

2023-02-16 11:50 UTC, dickon commented on components/crypto/crypto-client-impl/src/main/kotlin/net/corda/crypto/client/impl/CryptoOpsClientImpl.kt
> +        return request.execute(Duration.ofSeconds(20), CryptoSigningKeys::class.java)!!
Handle the null case explicitly and throw a meaningful exception if need be.

2023-02-16 11:50 UTC, dickon commented on components/crypto/crypto-client-impl/src/main/kotlin/net/corda/crypto/client/impl/CryptoOpsClientImpl.kt
> +        return request.execute(Duration.ofSeconds(20), CryptoSigningKeys::class.java)!!
oh I see the use of !! was already all over the code, nevermind, this PR is big enough already and better to make another PR one fine day that does something better than !!  here

2023-02-16 11:50 UTC, dickon commented on components/crypto/crypto-client/src/main/kotlin/net/corda/crypto/client/CryptoOpsClient.kt
> +     * Looks for keys owned by tenant of id [tenantId] from the list of [keyIds].
It doesn't just look, it returns what it finds, so I think the "Returns list of keys" phrasing was better.

2023-02-16 11:50 UTC, dickon commented on components/crypto/crypto-client/src/main/kotlin/net/corda/crypto/client/CryptoOpsClient.kt
> +     */
We should comment here on what we do to prevent collisions being a problem with ShortHash

2023-02-16 11:50 UTC, dickon commented on components/crypto/crypto-persistence-impl/src/main/kotlin/net/corda/crypto/persistence/impl/SigningKeyStoreImpl.kt
> +        // TODO Add caching
We need to know that we're not going to cause a performance problem by temporarily deleting the signing. Especially as we've got a beta cut off shortly. That's probably going to much harder to figure out than keeping in the caching

2023-02-16 11:50 UTC, dickon commented on components/crypto/crypto-persistence-impl/src/main/kotlin/net/corda/crypto/persistence/impl/SigningKeyStoreImpl.kt
> +                    "FROM SigningKeyEntity WHERE tenantId=:tenantId AND keyId IN(:keyIds)",
If we haven't guaranteed no collisions via database constraints we should check for collisions here.

2023-02-16 11:50 UTC, dickon commented on components/crypto/crypto-persistence-model/src/main/kotlin/net/corda/crypto/persistence/db/model/SigningKeyEntity.kt
> +     * The short key id, which is calculated as SHA256 converted to HEX string with only first 12 characters if it.
We should explain about collisions and the safe use of the short key ID here.

2023-02-16 11:50 UTC, dickon commented on components/crypto/crypto-service-impl/src/test/kotlin/net/corda/crypto/service/impl/SigningServiceGeneralTests.kt
> +            digestService = mock()
Annoying we have to update so much repeated code. In my refactroing work I'm reducing the duplication in the test cases, but this PR is not the place.

Well done for getting through it.

2023-02-16 11:50 UTC, dickon commented on components/crypto/crypto-service-impl/src/test/kotlin/net/corda/crypto/service/impl/bus/CryptoFlowOpsBusProcessorTests.kt
> +                val bytesCaptor = argumentCaptor<ByteArray>()
This is nice. As it happens I tried to do something similar earlier in the week but couldn't figure out how so used `it.arguments.first() as ByteArray` but this way, while more verbose, avoids the cast.

However, is it not possible to use the full digest service here? Or does that involve more plumbing and moves away from unit testing?

2023-02-16 11:50 UTC, dickon commented on components/membership/certificates-client-impl/src/test/kotlin/net/corda/membership/certificate/client/impl/HostedIdentityEntryFactoryTest.kt
> +        const val SESSION_KEY_ID = "AB0123456789"
Yeah okay I see now.

2023-02-16 11:50 UTC, dickon commented on gradle.properties
> +cordaApiVersion=5.0.0.646-alpha-1676545684879
Remove before final approval, when you  have the version lock.

2023-02-16 11:50 UTC, dickon commented on processors/crypto-processor/src/integrationTest/kotlin/net/corda/processors/crypto/tests/CryptoProcessorTests.kt
> +        assertTrue(listsOfBytesAreEqual(queriedVnode2KeysEncoded, queriedByFullIdsVnode2KeysEncoded))
nice test

2023-02-16 11:50 UTC, dickon commented on processors/crypto-processor/src/integrationTest/kotlin/net/corda/processors/crypto/tests/CryptoProcessorTests.kt
> +    bytesList0.size == bytesList1.size &&
surprised there's no library for this, but doesn't matter to do our own

2023-02-16 14:20 UTC, kyriathar commented on components/crypto/crypto-client-impl/src/main/kotlin/net/corda/crypto/client/impl/CryptoOpsClientImpl.kt
> +                            .also { secureHash -> keyIdsForLogging.add(secureHash.toString()) }
Did this like so to save an extra iteration through candidate keys. Can change if you think it's better though.

As an aside, I think `candidateKeys` should be made a set to avoid duplicates in request.

2023-02-16 14:25 UTC, kyriathar commented on components/crypto/crypto-client/src/main/kotlin/net/corda/crypto/client/CryptoOpsClient.kt
> +     * Looks for keys owned by tenant of id [tenantId] from the list of [keyIds].
Good point, rephrased it to say:

"Returns keys with key ids in [keyIds] which are owned by tenant of id [tenantId]."

2023-02-16 14:35 UTC, kyriathar commented on components/crypto/crypto-client/src/main/kotlin/net/corda/crypto/client/CryptoOpsClient.kt
> +     */
Good point, added.

2023-02-16 14:38 UTC, kyriathar commented on components/crypto/crypto-persistence-impl/src/main/kotlin/net/corda/crypto/persistence/impl/SigningKeyStoreImpl.kt
> +                    "FROM SigningKeyEntity WHERE tenantId=:tenantId AND keyId IN(:keyIds)",
(short) key id was reverted to be PK of signing keys DB table, so there can be no collisions on (short) key id per tenant.

2023-02-16 14:45 UTC, kyriathar commented on components/crypto/crypto-persistence-model/src/main/kotlin/net/corda/crypto/persistence/db/model/SigningKeyEntity.kt
> +     * The short key id, which is calculated as SHA256 converted to HEX string with only first 12 characters if it.
I already mentioned on `CryptoOpsClient` APIs, which are visible to users. Can also add here if you think it adds value.

2023-02-16 14:48 UTC, kyriathar commented on components/crypto/crypto-service-impl/src/test/kotlin/net/corda/crypto/service/impl/bus/CryptoFlowOpsBusProcessorTests.kt
> +                val bytesCaptor = argumentCaptor<ByteArray>()
Yeah, it was how I came up with recapturing I think, there should be some more proper way I believe. Yeah the tests below rely heavily on this being mocked I think.

2023-02-16 14:49 UTC, kyriathar commented on processors/crypto-processor/src/integrationTest/kotlin/net/corda/processors/crypto/tests/CryptoProcessorTests.kt
> +    bytesList0.size == bytesList1.size &&
Looked for one but couldn't find

2023-02-16 14:53 UTC, kyriathar commented
>I have some minor nitpicks, and I can see 2 blocking issues:
>
> 1. It'd be easier to keep the caching removed here than prove we don't need it.
> 2. I don't see a uniqueness constraint yet on the short hashes for signing keys (but maybe I missed it). We agreed this should be done in the database, on a per virtual node basiss.

1. Caching currently works for look ups by short key ids, there is no caching for when looking with full key ids, working on a subsequent PR to add it. Agreed there might be some performance risk.
2. Short key ids are PK in signing keys DB table. Please see https://github.com/corda/corda-api/blob/c533cd31887c1f6b461c29e11d702d8cbce34214/data/db-schema/src/main/resources/net/corda/db/schema/vnode-crypto/migration/vnode-crypto-creation-v1.0.xml#L55

2023-02-16 14:57 UTC, kyriathar commented on components/crypto/crypto-client-impl/src/main/kotlin/net/corda/crypto/client/impl/CryptoOpsClientImpl.kt
> +                            .also { shortHash -> keyIdsForLogging.add(shortHash) }
Same as above.

2023-02-17 14:41 UTC, dickon commented on components/crypto/crypto-client-impl/src/main/kotlin/net/corda/crypto/client/impl/CryptoOpsClientImpl.kt
> +                            .also { secureHash -> keyIdsForLogging.add(secureHash.toString()) }
Fair enough.

2023-02-17 14:45 UTC, dickon reviewed
Just a couple of conversations open still, nearly there.

2023-02-17 14:45 UTC, dickon commented on components/crypto/crypto-client-impl/src/main/kotlin/net/corda/crypto/client/impl/CryptoOpsClientImpl.kt
> +                            .also { shortHash -> keyIdsForLogging.add(shortHash) }
ok

2023-02-17 14:45 UTC, dickon commented on components/crypto/crypto-client/src/main/kotlin/net/corda/crypto/client/CryptoOpsClient.kt
> +     */
great

2023-02-17 14:45 UTC, dickon commented on components/crypto/crypto-persistence-impl/src/main/kotlin/net/corda/crypto/persistence/impl/SigningKeyStoreImpl.kt
> +        // TODO Add caching
I approved the caching PR off this PR, let's merge that then resolve this conversation.

2023-02-17 14:45 UTC, dickon commented on components/crypto/crypto-persistence-impl/src/main/kotlin/net/corda/crypto/persistence/impl/SigningKeyStoreImpl.kt
> +//            return cache.get(CacheKey(tenantId, publicKey.publicKeyId())) { cacheKey ->
ditto above

2023-02-17 14:45 UTC, dickon commented on components/crypto/crypto-persistence-impl/src/main/kotlin/net/corda/crypto/persistence/impl/SigningKeyStoreImpl.kt
> +                    "FROM SigningKeyEntity WHERE tenantId=:tenantId AND keyId IN(:keyIds)",
okay good. Please  point me at the code which sets the short key ID as a unique PK so I can review and close this conversation.

2023-02-17 14:45 UTC, dickon commented on components/crypto/crypto-persistence-model/src/main/kotlin/net/corda/crypto/persistence/db/model/SigningKeyEntity.kt
> +     * The short key id, which is calculated as SHA256 converted to HEX string with only first 12 characters if it.
okay, not important to mention twice.

2023-02-17 14:45 UTC, dickon commented on components/crypto/crypto-service-impl/src/test/kotlin/net/corda/crypto/service/impl/bus/CryptoFlowOpsBusProcessorTests.kt
> +                val bytesCaptor = argumentCaptor<ByteArray>()
okay

2023-02-17 14:45 UTC, dickon commented on processors/crypto-processor/src/integrationTest/kotlin/net/corda/processors/crypto/tests/CryptoProcessorTests.kt
> +    bytesList0.size == bytesList1.size &&
okay

2023-02-17 14:53 UTC, dickon commented
@kyriathar  pointed me at the PK which is at [https://github.com/corda/corda-api/blob/af61b2638a51112214182bf0ebdb90ba62b54a93/d[…]db/schema/vnode-crypto/migration/vnode-crypto-creation-v1.0.xml](https://github.com/corda/corda-api/blob/af61b2638a51112214182bf0ebdb90ba62b54a93/data/db-schema/src/main/resources/net/corda/db/schema/vnode-crypto/migration/vnode-crypto-creation-v1.0.xml#L55)

2023-02-17 14:54 UTC, dickon commented on components/crypto/crypto-persistence-impl/src/main/kotlin/net/corda/crypto/persistence/impl/SigningKeyStoreImpl.kt
> +                    "FROM SigningKeyEntity WHERE tenantId=:tenantId AND keyId IN(:keyIds)",
The code is at [https://github.com/corda/corda-api/blob/af61b2638a51112214182bf0ebdb90ba62b54a93/d[…]db/schema/vnode-crypto/migration/vnode-crypto-creation-v1.0.xml](https://github.com/corda/corda-api/blob/af61b2638a51112214182bf0ebdb90ba62b54a93/data/db-schema/src/main/resources/net/corda/db/schema/vnode-crypto/migration/vnode-crypto-creation-v1.0.xml#L55)

2023-02-17 17:07 UTC, dickon submitted a review, later dismissed
LGTM

Let's get the API change in now, since that's ready, despite what I said earlier about temporarily removing caching.

2023-02-20 11:06 UTC, dickon approved these changes
LGTM

2023-02-20 11:09 UTC, mnesbit approved these changes
OK

2023-02-20 11:19 UTC, ronanbrowne approved these changes
LGTM - build

2023-02-20 11:19 UTC, yift-r3 commented on components/membership/certificates-client-impl/src/main/kotlin/net/corda/membership/certificate/client/impl/HostedIdentityEntryFactory.kt
> +            cryptoOpsClient.lookupKeysByIds(
Can you change the `getKey` first argument to be short hash?

2023-02-20 11:19 UTC, yift-r3 commented on components/membership/membership-p2p/src/main/kotlin/net/corda/membership/p2p/helpers/KeySpecExtractor.kt
> +                ShortHash.of(publicKey.publicKeyId())
Can we make the `publicKeyId` return a short hash? If not, can we add a function to PublicKey to return a short hash? If not, what should we do it the string is not a valid short hash?

2023-02-20 11:19 UTC, yift-r3 commented on components/membership/membership-rest-impl/src/main/kotlin/net/corda/membership/impl/rest/v1/CertificatesRestResourceImpl.kt
> +                keyIds = listOf(ShortHash.of(keyId))
To ensure we throw the correct exception - `hortHash.of` -> `hortHash.ofOrThrow`.

2023-02-20 11:19 UTC, yift-r3 commented on components/membership/membership-rest-impl/src/main/kotlin/net/corda/membership/impl/rest/v1/KeysRestResourceImpl.kt
> +                    keyIds = ids.map { ShortHash.of(it) }
To ensure we throw the correct exception - `hortHash.of` -> `hortHash.ofOrThrow`.

2023-02-20 11:19 UTC, yift-r3 commented on components/membership/membership-rest-impl/src/main/kotlin/net/corda/membership/impl/rest/v1/KeysRestResourceImpl.kt
> +                keyIds = listOf(ShortHash.of(keyId))
To ensure we throw the correct exception - `hortHash.of` -> `hortHash.ofOrThrow`.

2023-02-20 11:19 UTC, yift-r3 commented on components/membership/registration-impl/src/main/kotlin/net/corda/membership/impl/registration/dynamic/member/DynamicMemberRegistrationService.kt
> +            cryptoOpsClient.lookupKeysByIds(tenantId, keyIds.map { ShortHash.of(it) }).also { keys ->
If the short hash is invalid we need to throw the correct exception

2023-02-20 11:19 UTC, yift-r3 commented on components/membership/registration-impl/src/main/kotlin/net/corda/membership/impl/registration/dynamic/mgm/MGMRegistrationMemberInfoHandler.kt
> +            listOf(ShortHash.of(keyId))
If the short hash is invalid we need to throw the correct exception

2023-02-20 11:24 UTC, yift-r3 approved these changes
(Agreed to apply my comments in another pull request)

2023-02-20 11:26 UTC, kyriathar commented on components/membership/certificates-client-impl/src/main/kotlin/net/corda/membership/certificate/client/impl/HostedIdentityEntryFactory.kt
> +            cryptoOpsClient.lookupKeysByIds(
I might be wrong but, I believe this is outside the scope of this PR, I exposed `ShortHash` and `SecureHash` at crypto ops client APIs, users should be aligning call sites?

2023-02-20 11:29 UTC, kyriathar commented on components/membership/membership-p2p/src/main/kotlin/net/corda/membership/p2p/helpers/KeySpecExtractor.kt
> +                ShortHash.of(publicKey.publicKeyId())
Valid point but I think same as above, APIs using the crypto ops client ones should be revised, but under some different PR.

2023-02-20 11:35 UTC, kyriathar commented on components/membership/membership-rest-impl/src/main/kotlin/net/corda/membership/impl/rest/v1/CertificatesRestResourceImpl.kt
> +                keyIds = listOf(ShortHash.of(keyId))
Not really sure I follow here, `ShortHash.of` throws `ShortHashException` if doesn't finds appropriate length or string is not hex string. Maybe you mean `ShortHashException` is not an appropriate exception to be propagated back?  I feel this is again the caller of the API who should be handling this.

2023-02-20 11:53 UTC, merged

2023-02-20 14:33 UTC, kyriathar commented on components/membership/membership-p2p/src/main/kotlin/net/corda/membership/p2p/helpers/KeySpecExtractor.kt
> +                ShortHash.of(publicKey.publicKeyId())
There is a ticket raised to revisit [CORE-10267](https://r3-cev.atlassian.net/browse/CORE-10267) functions. We should end up having hashing helper functions that take a digest service, since we only want hash through the digest services. 

On the above, `ShortHash.of` will validate hex string from `publicKeyId()` and throw `ShortHashException` if string not valid.

2023-02-20 15:27 UTC, kyriathar commented on components/membership/registration-impl/src/main/kotlin/net/corda/membership/impl/registration/dynamic/member/DynamicMemberRegistrationService.kt
> +            cryptoOpsClient.lookupKeysByIds(tenantId, keyIds.map { ShortHash.of(it) }).also { keys ->
I went back to see what is calling this, so it is not a rest resource. Currently that will throw if hex string is not valid (Please see `ShortHash.of`).

Unless you mean we need to make it more strict and use `ShortHash.parse`?

2023-02-20 15:30 UTC, yift-r3 commented on components/membership/registration-impl/src/main/kotlin/net/corda/membership/impl/registration/dynamic/member/DynamicMemberRegistrationService.kt
> +            cryptoOpsClient.lookupKeysByIds(tenantId, keyIds.map { ShortHash.of(it) }).also { keys ->
If the register throws a random exception, we will retry it several times. If the key is invalid, we should not retry it at all. To stop the retry loop, if the key ID is not a short hash, we should throw an `InvalidMembershipRegistrationException`.