CORE-8034 Renamed 'application/rpc-worker' module to 'application/rest-worker', updated helm charts accordingly
corda/corda-runtime-os pull request #3110
Opened 2023-02-09 17:10 UTC by ben-millar

### Description:
This PR satisfies [CORE-8034](https://r3-cev.atlassian.net/browse/CORE-8034); part of the greater renaming initiative tracked by [CORE-7044](https://r3-cev.atlassian.net/browse/CORE-7044).  

[CORE-8034]: https://r3-cev.atlassian.net/browse/CORE-8034?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-02-13 13:40 UTC, ben-millar commented on applications/workers/release/combined-worker/src/main/kotlin/net/corda/applications/workers/combined/CombinedWorker.kt
> +    @Option(names = ["-r", "--rest-params"], description = ["RPC parameters for the worker."])
This description should be changed to 'rest'

2023-02-13 13:42 UTC, ben-millar commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/virtualnode/VirtualNodeRestTest.kt
> +class VirtualNodeRestTest {
This change is out of scope and should be reverted.

2023-02-13 17:27 UTC, ben-millar commented
This should be unblocked by https://github.com/corda/corda-shared-build-pipeline-steps/pull/566/files

2023-02-16 15:35 UTC, ben-millar commented
Merge alongside:
API Changes: https://github.com/corda/corda-api/pull/862
Pipeline Changes: https://github.com/corda/corda-shared-build-pipeline-steps/pull/573

2023-02-16 16:51 UTC, wzur-r3 requested changes

2023-02-16 16:51 UTC, wzur-r3 commented on .ci/e2eTests/Jenkinsfile
> +@Library('corda-shared-build-pipeline-steps@bm/CORE-7040/CORE-8034') _
I know that is for testing, please change it back to `5.0` before merge

2023-02-16 16:51 UTC, wzur-r3 commented on Jenkinsfile
> +@Library('corda-shared-build-pipeline-steps@bm/CORE-7040/CORE-8034') _
I know that is for testing, please change it back to 5.0 before merge

2023-02-16 17:09 UTC, ben-millar commented on Jenkinsfile
> +@Library('corda-shared-build-pipeline-steps@bm/CORE-7040/CORE-8034') _
For sure. There are some breaking pipeline changes which need to be made in-sync with this, so I'm chatting with @ronanbrowne as to what this should be – possibly >5.0.

2023-02-16 17:17 UTC, mnesbit commented on .ci/e2eTests/Jenkinsfile
> +@Library('corda-shared-build-pipeline-steps@bm/CORE-7040/CORE-8034') _
Yes definitely don't forget this

2023-02-16 17:24 UTC, mnesbit submitted a review, later dismissed

2023-02-16 18:26 UTC, davidcurrie reviewed
LGTM - will approve once ready to merge

2023-02-20 10:32 UTC, ben-millar commented on .ci/e2eTests/Jenkinsfile
> +@Library('corda-shared-build-pipeline-steps@5.0.1') _
@wzur-r3 Updated version here in line with this PR https://github.com/corda/corda-shared-build-pipeline-steps/pull/573

2023-02-20 10:32 UTC, ben-millar commented on Jenkinsfile
> +@Library('corda-shared-build-pipeline-steps@5.0.1') _
@wzur-r3 Updated version here also in line with this PR https://github.com/corda/corda-shared-build-pipeline-steps/pull/573

2023-02-20 17:26 UTC, ronanbrowne approved these changes
LGTM - build

2023-02-20 17:40 UTC, vkolomeyko approved these changes
LGTM

2023-02-20 20:08 UTC, wzur-r3 approved these changes
LGTM for Jenkinsfiles and Gradle files

2023-02-21 09:58 UTC, davidcurrie approved these changes
🚀

2023-02-21 09:59 UTC, merged