[CORE-9842] Add Hardcoded InterOp Group Policies to GroupPolicyReader
corda/corda-runtime-os pull request #3129
Opened 2023-02-13 12:43 UTC by julia-filipczak

Adding hardcoded interop group policy to enable early development. This includes the addition of the interop member role, implementation of the new interop group policy and changes in the group policy provider to handle the new group policy type.

2023-02-13 13:32 UTC, yarivus reviewed
see some comments

2023-02-13 13:32 UTC, yarivus commented on components/membership/group-policy-impl/src/main/kotlin/net/corda/membership/impl/grouppolicy/GroupPolicyProviderImpl.kt
> +            if (isInterop) {
we should try to aim to be more OOD/OOP ... and have InteropGroupPolicyParser inherit from GroupPolicyParser
and then the right code will activate the right parse ...
( Maybe not in this PR )

2023-02-13 13:32 UTC, yarivus commented on libs/membership/membership-impl/src/main/kotlin/net/corda/membership/lib/impl/grouppolicy/v1/InteropGroupPolicyImpl.kt
> +      "-----BEGIN CERTIFICATE-----\r\nMIIFHjCCBAagAwIBAgISAy1ybKW9u73QQxLAktLHTEQQMA0GCSqGSIb3DQEBCwUA\r\nMDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQD\r\nEwJSMzAeFw0yMjA1MTExNTAxM
is this the hard-coding ?
Is this intentional ?

2023-02-13 14:25 UTC, szymonsztuka requested changes
Summary:
In general the PR conflates "hardcoded data" to allow working from get-go with a possible research what GroupPolicy data is needed for Interop/LinkManager, and both aims are not reached.  
As this seems structurally wrong approach I deferred from minor comments and just put 2-3 of them, my general questions:

1)  The first DoD (definition of Done)  bullet:
"* Addition of new ‘InterOp’ Member role to be used in the Member Context"
Probably code change is ok, but doesn't really introduce any functionality now.

2) We created new InteropGroupPolicy which is sibling of MemberGroupPolicy and provides exactly the same getters (as the both are alias for GroupPolicy interface.) 
As researched before, we don't need MGM Provided info or static memebers, howeverexisting  Group Policies Parsers and base classes treat them optionally, so in theory we can reuse existing parser/data at start (starting with superset).

There is second DoD bullet which I'm not sure what is current rational for it:
"When the GroupPolicyReader needs to fetch the Group Policy for a Holding Identity, it will check if the MemberInfo is an InterOp Identity and if so calls a different class to the GroupPolicyParser "

We created a lot of code with parallel hierarchy of parsers and grouppolicies, but frankly or this is exactly the same code - in some cases we dropped members in static group (but this is anyway non production code), or we just internally hardcocded some values meaning this is not even a proper parser (it's a parser returning the same values regardles of input). 
Also having completely separated hierarchy will be hard to maintain, what e.g. they introduce new value for "sessionKeyPolicy" and our hardcoded one in parser becomes obsolete, we have no way to detect this unless we run real deployment and LinkManager start refusing to work with our values. 
What is new or different that existing parsers couldn't do? Again we have identical data class to the existing MemeberGroupPolicy so I guess we should be able to use exactly the same parser?

If we are introducing a parser we should add a real working parser which could show - interop group JSON is different and we need to parse it differently.
Also we use our new code only during registration event, but I'm not sure are trigger any registration now, as we don't have any code to initiate registration, the point was to hardcode whenever data is read, not to implement writing of our data.


3)  We don't have the original source of information (VirtualNodeInfo) which writes data to VirtualNodeInfoReadServiceImpl. 
Because of this our "pseudo-membership-group" will never appear in GroupPolicyProviderImpl, whenever LinkMnager asks of a HoldingIdentity belonging to this pseudo-group.
Therefore the quick and hardcoded fix is as follows: whenever GroupPolicyProviderImpl fails to find something when asked via API/interface method, then it defers to in memory map with 1-2 Hardcoded GroupPolicies.
This would be sufficient for the last bullet of DoD:
"* A hardcoded GroupPolicy object is returned with default values and fixed GroupName where MGM is Null."

This PR lacks such code - 
out of box we don't have any hardcode values e.g. "GoldBond" group policy (ang. e.g. For "Alice@GoldBond" and "Bo@GoldBond").

2023-02-13 14:25 UTC, szymonsztuka commented on libs/membership/membership-common/src/main/kotlin/net/corda/membership/lib/grouppolicy/InteropGroupPolicyParser.kt
> +    fun get(holdingIdentity: HoldingIdentity): InteropGroupPolicy
Parser is for parsing,  not for keeping some internal collection of already parsed data. As in all duplicated classes, why we can reuse `GroupPolicyParser` interface?

2023-02-13 14:25 UTC, szymonsztuka commented on libs/membership/membership-common/src/main/kotlin/net/corda/membership/lib/interop/MemberInteropDetails.kt
> +data class MemberInteropDetails(
What this is for, it's never used.

2023-02-13 14:25 UTC, szymonsztuka commented on components/membership/group-policy-impl/src/main/kotlin/net/corda/membership/impl/grouppolicy/GroupPolicyProviderImpl.kt
> +                    val gp = parseGroupPolicy(holdingIdentity, checkForInteropRole(memberContext))
I may be wrong but the surrounding code in this method expect MGM and is designed to deal with MGM, so adding our flag will not trigger anything. As well the following up existing check expects this and MGM group Policy otherwise we don't register anything.

2023-02-13 14:36 UTC, szymonsztuka commented on libs/membership/membership-common/src/main/kotlin/net/corda/membership/lib/grouppolicy/InteropGroupPolicyParser.kt
> +    fun get(holdingIdentity: HoldingIdentity): InteropGroupPolicy
^why we can'**t** reuse ...

2023-02-13 14:49 UTC, yarivus commented
> Summary: In general the PR conflates "hardcoded data" to allow working from get-go with a possible research what GroupPolicy data is needed for Interop/LinkManager, and both aims are not reached. As this seems structurally wrong approach I deferred from minor comments and just put 2-3 of them, my general questions:
> 
> 1. The first DoD (definition of Done)  bullet:
>    "* Addition of new ‘InterOp’ Member role to be used in the Member Context"
>    Probably code change is ok, but doesn't really introduce any functionality now.
> 2. We created new InteropGroupPolicy which is sibling of MemberGroupPolicy and provides exactly the same getters (as the both are alias for GroupPolicy interface.)
>    As researched before, we don't need MGM Provided info or static memebers, howeverexisting  Group Policies Parsers and base classes treat them optionally, so in theory we can reuse existing parser/data at start (starting with superset).
> 
> There is second DoD bullet which I'm not sure what is current rational for it: "When the GroupPolicyReader needs to fetch the Group Policy for a Holding Identity, it will check if the MemberInfo is an InterOp Identity and if so calls a different class to the GroupPolicyParser "
> 
> We created a lot of code with parallel hierarchy of parsers and grouppolicies, but frankly or this is exactly the same code - in some cases we dropped members in static group (but this is anyway non production code), or we just internally hardcocded some values meaning this is not even a proper parser (it's a parser returning the same values regardles of input). Also having completely separated hierarchy will be hard to maintain, what e.g. they introduce new value for "sessionKeyPolicy" and our hardcoded one in parser becomes obsolete, we have no way to detect this unless we run real deployment and LinkManager start refusing to work with our values. What is new or different that existing parsers couldn't do? Again we have identical data class to the existing MemeberGroupPolicy so I guess we should be able to use exactly the same parser?
> 
> If we are introducing a parser we should add a real working parser which could show - interop group JSON is different and we need to parse it differently. Also we use our new code only during registration event, but I'm not sure are trigger any registration now, as we don't have any code to initiate registration, the point was to hardcode whenever data is read, not to implement writing of our data.
> 
> 3. We don't have the original source of information (VirtualNodeInfo) which writes data to VirtualNodeInfoReadServiceImpl.
>    Because of this our "pseudo-membership-group" will never appear in GroupPolicyProviderImpl, whenever LinkMnager asks of a HoldingIdentity belonging to this pseudo-group.
>    Therefore the quick and hardcoded fix is as follows: whenever GroupPolicyProviderImpl fails to find something when asked via API/interface method, then it defers to in memory map with 1-2 Hardcoded GroupPolicies.
>    This would be sufficient for the last bullet of DoD:
>    "* A hardcoded GroupPolicy object is returned with default values and fixed GroupName where MGM is Null."
> 
> This PR lacks such code - out of box we don't have any hardcode values e.g. "GoldBond" group policy (ang. e.g. For "Alice@GoldBond" and "Bo@GoldBond").

I guess this is somewhat aligned with my specific comments too.
Unless I misunderstood @szymonsztuka .

2023-02-13 15:01 UTC, szymonsztuka commented
> I guess this is somewhat aligned with my specific comments too. Unless I misunderstood @szymonsztuka .

It's aligned with your first comment, it's a bit orthogonal to your second comment with hard-coded keys as strings (I think we need to produce a pair of PrivatePublic keys, not only have public ones),  the actual way of hard-coding is to be debated

2023-02-13 16:59 UTC, jmacmahonr3 commented
> 

Hi @szymonsztuka 
I just want to clear up what is meant by : "When the GroupPolicyReader needs to fetch the Group Policy for a Holding Identity, it will check if the MemberInfo is an InterOp Identity and if so calls a different class to the GroupPolicyParser" 

As you mention in your third point we don't have access to vnode info meaning we cannot retrieve the InterOpGroupPolicies in the same way as we do for normal member group policies. The intension is that we modify GroupPolicyProvider to be able to provide both InterOp and regular group policies. GroupPolicyParser is used for specifically getting metadata from the Virtual Node info to parse the cpi's group policy. As we'll be reading the InterOp data from a new kafka topic it makes sense to add a new class to read it from the queue. The original hope was that if we could assert that the Holding Identity's MemberInfo had a specific Interop Role associated with it then we would be able to logically know where to look for the group policy but from the Pr i can see it hasn't worked out that way.

2023-02-13 17:05 UTC, jmacmahonr3 commented on libs/membership/membership-impl/src/main/kotlin/net/corda/membership/lib/impl/grouppolicy/v1/InteropGroupPolicyImpl.kt
> +      "-----BEGIN CERTIFICATE-----\r\nMIIFHjCCBAagAwIBAgISAy1ybKW9u73QQxLAktLHTEQQMA0GCSqGSIb3DQEBCwUA\r\nMDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQD\r\nEwJSMzAeFw0yMjA1MTExNTAxM
Should be for now.

2023-02-14 15:00 UTC, yarivus approved these changes
LGTM

2023-02-20 11:47 UTC, closed without merging