CORE-10826: collapse a few classes into SoftCryptoService
corda/corda-runtime-os pull request #3164
Opened 2023-02-16 09:29 UTC by dickon

2023-02-17 12:05 UTC, wzur-r3 submitted a review, later dismissed
LGTM for Gradle files

2023-02-20 09:04 UTC, dickon commented on components/crypto/crypto-service-impl/src/test/kotlin/net/corda/crypto/service/impl/infra/TestServicesFactory.kt
> +    val wrappingKeyCache: Cache<String, WrappingKey> = CacheFactoryImpl().build(
When we later squash together CryptoService and SoftCryptoService sub-projects we can use the test functions makeWrappingKeyCache and makePrivateKeyCache rather than duplicate the logic here.

2023-03-06 10:30 UTC, fowlerrr reviewed
A few simple comments to start.  I get the basic gist but want to read through it again after the merge conflicts are sorted.

2023-03-06 10:30 UTC, fowlerrr commented on components/crypto/crypto-service-impl/src/main/kotlin/net/corda/crypto/service/impl/SigningServiceImpl.kt
> +                masterKeyAlias = ref.masterKeyAlias!!
I'm not generally a fan of `!!` in our code as it never leaves a good exception behind it.

2023-03-06 10:30 UTC, fowlerrr commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoService.kt
> +        logger.info("createWrappingKey(alias=$masterKeyAlias failIfExists=$failIfExists) cached=$cached available=$available")
I don't think this needs to a an `info` log.  It seems more `trace` level.

2023-03-06 10:30 UTC, fowlerrr commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoService.kt
> +            logger.info("Not creating wrapping key for '$masterKeyAlias' since a key is available")
Again, this probably doesn't need to be `info`.  See https://github.com/corda/platform-eng-design/blob/master/core/corda-5/corda-5.0/standards/logging.md

2023-03-06 10:30 UTC, fowlerrr commented on libs/crypto/cipher-suite/src/main/kotlin/net/corda/crypto/cipher/suite/CryptoService.kt
> +     * @param masterKeyAlias the alias of the key to be used as a wrapping key. TODO - rename wrappingKeyAlias
Why not just rename it now?

2023-03-07 13:28 UTC, driessamyn requested changes
Superficial review, but some comments around the use of cache.

2023-03-07 13:28 UTC, driessamyn commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/SupportedSchemes.kt
> +val SUPPORTED_SCHEMES: List<Pair<String, List<SignatureSpec>>> = listOf(
Wouldn't this more efficient and easier to look up on (in `deriveSupportedSchemes` for example) as a `Map<String, List<SignatureSpec>>`

2023-03-07 13:28 UTC, driessamyn commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoServiceProviderImpl.kt
> +                Caffeine.newBuilder()
I realise this is a copy/paste from existing, code, but we can never do `Caffeine.newBuilder()` directly, but must go through our `CacheFactoryImpl`.

Otherwise, the security manager may prevent eviction.

2023-03-07 13:28 UTC, driessamyn commented on components/crypto/crypto-softhsm-impl/src/test/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoServiceCachingTests.kt
> + * testing as by default the eviction is scheduled on an executor, so it's not exactly deterministic.
Why do we need to unit test _actual_ eviction?
Shouldn't we inject a mocked out cache (or `CacheFactory`) so that we can force the eviction behaviour.
We shouldn't be interested in testing Caffeine itself, just our code.

2023-03-07 13:28 UTC, driessamyn commented on components/crypto/crypto-softhsm-impl/src/test/kotlin/net/corda/crypto/softhsm/impl/infra/MakePrivateKeyCache.kt
> +        .maximumSize(size)
Why do we need a real cache here?

2023-03-07 13:28 UTC, driessamyn commented on components/crypto/crypto-softhsm-impl/src/test/kotlin/net/corda/crypto/softhsm/impl/infra/MakeWrappingKeyCache.kt
> +        .maximumSize(100)
As above.

2023-03-07 13:28 UTC, driessamyn commented on components/crypto/crypto-service-impl/src/test/kotlin/net/corda/crypto/service/impl/infra/TestServicesFactory.kt
> +            .maximumSize(0)
Is it necessary to use real caches?
Should we mock out the cache or `CacheFactory`?

2023-03-07 14:14 UTC, dickon commented on components/crypto/crypto-service-impl/src/test/kotlin/net/corda/crypto/service/impl/infra/TestServicesFactory.kt
> +            .maximumSize(0)
It's probably more concise the way I have it than to mock the cache, but on the other hand using Caffeine increases the test code footprint.

2023-03-07 14:36 UTC, kyriathar reviewed
A first review. Still need to review test code.

2023-03-07 14:36 UTC, kyriathar commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoService.kt
> +import net.corda.crypto.softhsm.deriveSupportedSchemes
Needs imports rearrangement

2023-03-07 14:36 UTC, kyriathar commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoService.kt
> +val PRIVATE_KEY_ENCODING_VERSION: Int = 1
These could use `const`.

2023-03-07 14:36 UTC, kyriathar commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoService.kt
> + * The heart of the crypto processor.
Doesn't really say much.

2023-03-07 14:36 UTC, kyriathar commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoService.kt
> + * without a database, without OSGi and without SmartConfig, which makes it easy to test.
Should be moved above param section

2023-03-07 14:36 UTC, kyriathar commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoServiceProviderImpl.kt
> -    private val digestService: PlatformDigestService,
Think we should put this `digestService` reference back, and hand it over to `SoftCryptoService` instead of creating a new instance of it (at `SoftCryptoService` init).

2023-03-07 14:36 UTC, kyriathar commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoService.kt
> +    private val wrappingKeyCache: Cache<String, WrappingKey>,
So `wrappingKeyMap` is now flattened to be `wrappingKeyCache` and `wrappingKeyStore`. Nitpicky: could we please re-order to keep them close

2023-03-07 14:36 UTC, kyriathar commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoService.kt
> +        val cached = wrappingKeyCache.getIfPresent(masterKeyAlias) != null
Could rename to `isCached`

2023-03-07 14:36 UTC, kyriathar commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoService.kt
> +        val available = if (cached) true else wrappingKeyStore.findWrappingKey(masterKeyAlias) != null
`IsAvailable`

2023-03-07 14:36 UTC, kyriathar commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoService.kt
> +        logger.info("createWrappingKey(alias=$masterKeyAlias failIfExists=$failIfExists) cached=$cached available=$available")
I do agree this feels `trace`. Not really sure it adds much logging if it is cached or not. Maybe available adds but could be separated from this log line.

2023-03-07 14:36 UTC, kyriathar commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoService.kt
> +        val wrappedKeyMaterial = rootWrappingKey.wrap(wrappingKey)
So before wrapping the wrapping key with the root wrapping key was taking place in `CachingSoftWrappingKeyMap.putWrappingKey` I think?

2023-03-07 14:36 UTC, kyriathar commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoService.kt
> +        val wrappedKeyMaterial = rootWrappingKey.wrap(wrappingKey)
Fine to leave for consistency if that is what we using elsewhere but maybe we should be renaming to `wrappingKeyWrapped`

2023-03-07 14:36 UTC, kyriathar commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoService.kt
> +    open fun wrapPrivateKey(wrappingKey: WrappingKey, privateKey: PrivateKey): ByteArray = wrappingKey.wrap(privateKey)
Can we get away with not having this function as open which only serves testing purposes?

2023-03-07 14:36 UTC, kyriathar commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoService.kt
> +        return GeneratedWrappedKey(keyPair.public, privateKeyMaterial, PRIVATE_KEY_ENCODING_VERSION)
nit: maybe worth adding named parameters, parameters not named same with arguments in this case.

2023-03-07 14:36 UTC, kyriathar commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoService.kt
> +    fun getWrappingKey(alias: String): WrappingKey = wrappingKeyCache.get(alias) {
`getWrappingKey` method can probably be private?

2023-03-07 14:36 UTC, kyriathar commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoService.kt
> +            wrappingKeyStore.findWrappingKey(alias) ?: throw IllegalStateException("The $alias is not created yet.")
Exception message could be more descriptive to say "Wrapping key of alias = \"$alias\" is not created yet."

2023-03-07 14:36 UTC, kyriathar commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoService.kt
> +        }
This is how it used to be, but not entirely sure why `rootWrappingKey.algorithm == wrappingKeyInfo.algorithmName`?

2023-03-07 14:36 UTC, kyriathar commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoService.kt
> +    open fun unwrapPrivateKey(key: WrappingKey, keyMaterial: ByteArray): PrivateKey = key.unwrap(keyMaterial)
Same as above, could we get away with not having this open method for testing purposes?

2023-03-07 14:36 UTC, kyriathar commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoService.kt
> +    fun getPrivateKey(publicKey: PublicKey, spec: KeyMaterialSpec): PrivateKey =
`getPrivateKey` should probably be private?

2023-03-07 14:36 UTC, kyriathar commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoService.kt
> +    fun wrappingKeyExists(wrappingKeyAlias: String): Boolean {
This is only used in tests...maybe remove?

2023-03-07 14:36 UTC, kyriathar commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoServiceProviderImpl.kt
> -        private val digestService: PlatformDigestService,
As said above need to put back `digestService` here too

2023-03-07 14:36 UTC, kyriathar commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoServiceProviderImpl.kt
> +            val wrappingKeyCacheConfig = wrappingKeyMapConfig.getConfig("cache")
This config tree seems obsolete since we decoupled, it should be now two different things? Root key config and wrapping keys cache? (Maybe for a different PR but worth raising a JIRA to keep it tracked I think)

2023-03-07 14:36 UTC, kyriathar commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoServiceProviderImpl.kt
> +            if (privateKeyMapName != KEY_MAP_CACHING_NAME && privateKeyMapName != KEY_MAP_TRANSIENT_NAME)
We deleted caching and transient key maps didn't we? So maybe we should also drop these configurations too? To hopefully also simplify crypto configuration.

2023-03-07 14:36 UTC, kyriathar commented on libs/crypto/cipher-suite/src/main/kotlin/net/corda/crypto/cipher/suite/KeyMaterialSpec.kt
> + * could still be null for HSMs which use built-in wrapping keys. TODO - rename to wrappingKeyAlias
If not renaming in this PR maybe raise a JIRA to keep it recorded?

2023-03-07 14:36 UTC, kyriathar commented on components/crypto/crypto-softhsm-impl/src/test/kotlin/net/corda/crypto/softhsm/impl/infra/TestWrappingKeyStore.kt
> +open class TestWrappingKeyStore(
I think instead of opening it an overriding, can inject callback in here instead.

2023-03-07 14:42 UTC, kyriathar commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoService.kt
> +open class SoftCryptoService(
Could we please change `SoftCryptoService` to not be open only for testing purposes?

2023-03-07 15:11 UTC, dickon commented on components/crypto/crypto-service-impl/src/test/kotlin/net/corda/crypto/service/impl/infra/TestServicesFactory.kt
> +            .maximumSize(0)
In future work I'd like to revisit all the tests using TestServiceFacotry and move towards nice unit tests and some e2e tests.

2023-03-07 15:12 UTC, dickon commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/SupportedSchemes.kt
> +val SUPPORTED_SCHEMES: List<Pair<String, List<SignatureSpec>>> = listOf(
good idea; working on this locally.

2023-03-07 20:14 UTC, dickon commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoService.kt
> +        logger.info("createWrappingKey(alias=$masterKeyAlias failIfExists=$failIfExists) cached=$cached available=$available")
So I was trying to make this purely a refactoring and the base ode has logger.info. However we may as well take the opportunity to address the review comments people have.

2023-03-07 20:14 UTC, dickon commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/SupportedSchemes.kt
> +val SUPPORTED_SCHEMES: List<Pair<String, List<SignatureSpec>>> = listOf(
done

2023-03-07 20:14 UTC, dickon commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoService.kt
> +import net.corda.crypto.softhsm.deriveSupportedSchemes
roll on an autoformatter which deals with this.

2023-03-07 20:14 UTC, dickon commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoService.kt
> +val PRIVATE_KEY_ENCODING_VERSION: Int = 1
will do

2023-03-07 20:14 UTC, dickon commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoService.kt
> + * The heart of the crypto processor.
will remve

2023-03-07 20:14 UTC, dickon commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoService.kt
> + * without a database, without OSGi and without SmartConfig, which makes it easy to test.
y

2023-03-07 20:14 UTC, dickon commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoService.kt
> +import net.corda.crypto.softhsm.deriveSupportedSchemes
done

2023-03-07 20:14 UTC, dickon commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoService.kt
> +import net.corda.crypto.softhsm.deriveSupportedSchemes
done

2023-03-07 20:14 UTC, dickon commented on components/crypto/crypto-service-impl/src/test/kotlin/net/corda/crypto/service/impl/infra/TestServicesFactory.kt
> +            .maximumSize(0)
I made the cache parameters nullable, so this goes away.

2023-03-07 20:14 UTC, dickon commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoService.kt
> +val PRIVATE_KEY_ENCODING_VERSION: Int = 1
done

2023-03-07 20:14 UTC, dickon commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoService.kt
> + * The heart of the crypto processor.
done

2023-03-07 20:14 UTC, dickon commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoService.kt
> +        val wrappedKeyMaterial = rootWrappingKey.wrap(wrappingKey)
renamed to `wrappingKeyEncrypted`

2023-03-07 20:14 UTC, dickon commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoService.kt
> +        val wrappedKeyMaterial = rootWrappingKey.wrap(wrappingKey)
y

2023-03-07 20:14 UTC, dickon commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoService.kt
> +            logger.info("Not creating wrapping key for '$masterKeyAlias' since a key is available")
done, see previous discussion on info

2023-03-07 20:14 UTC, dickon commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoService.kt
> +        logger.info("createWrappingKey(alias=$masterKeyAlias failIfExists=$failIfExists) cached=$cached available=$available")
reduce logging level

2023-03-07 20:14 UTC, dickon commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoService.kt
> +    open fun wrapPrivateKey(wrappingKey: WrappingKey, privateKey: PrivateKey): ByteArray = wrappingKey.wrap(privateKey)
done

2023-03-07 20:14 UTC, dickon commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoService.kt
> +        return GeneratedWrappedKey(keyPair.public, privateKeyMaterial, PRIVATE_KEY_ENCODING_VERSION)
I'll align the name and go to keyword arguments here.

2023-03-07 20:14 UTC, dickon commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoService.kt
> +        val cached = wrappingKeyCache.getIfPresent(masterKeyAlias) != null
Name beginning with "is" sound like predicate functions to me, but I tried it and it did make the code more readable so I'll do this

2023-03-07 20:14 UTC, dickon commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoService.kt
> +        val available = if (cached) true else wrappingKeyStore.findWrappingKey(masterKeyAlias) != null
will do

2023-03-07 20:14 UTC, dickon commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoService.kt
> +    open fun unwrapPrivateKey(key: WrappingKey, keyMaterial: ByteArray): PrivateKey = key.unwrap(keyMaterial)
gone

2023-03-07 20:14 UTC, dickon commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoService.kt
> +open class SoftCryptoService(
done, for better or worse.

2023-03-07 20:14 UTC, dickon commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoService.kt
> +    private val wrappingKeyCache: Cache<String, WrappingKey>,
The cache arguments are now optional, which works best if they are at the ened of the list.

2023-03-07 20:14 UTC, dickon commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoService.kt
> +        val cached = wrappingKeyCache.getIfPresent(masterKeyAlias) != null
done

2023-03-07 20:14 UTC, dickon commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoService.kt
> +    fun getWrappingKey(alias: String): WrappingKey = wrappingKeyCache.get(alias) {
I'll add @VisibleForTesting

2023-03-07 20:14 UTC, dickon commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoService.kt
> +            wrappingKeyStore.findWrappingKey(alias) ?: throw IllegalStateException("The $alias is not created yet.")
This text is from CachingSoftWrappingKeyMap.kt and I was trying to preserve behaviour. But now you come to mention it, sure, why not, I'll take that.

2023-03-07 20:14 UTC, dickon commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoService.kt
> +        }
Good spot, I've added a TODO and will review this with the wrapping key rotation work package. I'm thinking drop this requirement, but want to think more about it.

2023-03-07 20:14 UTC, dickon commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoService.kt
> +    fun getPrivateKey(publicKey: PublicKey, spec: KeyMaterialSpec): PrivateKey =
made @VisibleForTesting

2023-03-07 20:14 UTC, dickon commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoService.kt
> +    fun wrappingKeyExists(wrappingKeyAlias: String): Boolean {
Added @VisibleForTesting

Or we could make it an extension method in SoftCryptoOperationsTests.kt but visibility of the properties is an issue. And I don't see a problem with making it public if there's ever a need.

2023-03-07 20:14 UTC, dickon commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoServiceProviderImpl.kt
> -    private val digestService: PlatformDigestService,
Yes, good call, I think that's more correct and consistent even though the change saved plumbing, so I've restored it, with a default argument on SoftCryptoService to avoid test bloat.

2023-03-07 20:14 UTC, dickon commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoServiceProviderImpl.kt
> -        private val digestService: PlatformDigestService,
done

2023-03-07 20:14 UTC, dickon commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoServiceProviderImpl.kt
> +            val wrappingKeyCacheConfig = wrappingKeyMapConfig.getConfig("cache")
config structure is in  corda-api but I'm not sure if it'll need locking down with the API freeze. In any case I don't want ot mix up an API change now.

Once we've got rid of the HSM map the config can be much simpler.

So a no-op for now. I'm not yet sure enough of what to do to write a detailed  JIRA ticket at this point.

2023-03-07 20:14 UTC, dickon commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoServiceProviderImpl.kt
> +                Caffeine.newBuilder()
I had a quick look at CacheFactoryImpl but don't understand how to configure builder paramters. Separate ticket please to explain the issue, separate PR.

2023-03-07 20:14 UTC, dickon commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoServiceProviderImpl.kt
> +            if (privateKeyMapName != KEY_MAP_CACHING_NAME && privateKeyMapName != KEY_MAP_TRANSIENT_NAME)
See above; yes I would like to clean up the config in the future, but in one go rather than lots of little steps, since it requires corda-api changes and coordination with users such as QA.

2023-03-07 20:16 UTC, dickon commented on components/crypto/crypto-softhsm-impl/src/test/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoServiceCachingTests.kt
> + * testing as by default the eviction is scheduled on an executor, so it's not exactly deterministic.
This is a comment that has been moved around rather than added here, and in this refactoring PR I'm not really interested in deleting tests, which would warrant separate consideration.

2023-03-07 21:06 UTC, dickon commented on components/crypto/crypto-softhsm-impl/src/test/kotlin/net/corda/crypto/softhsm/impl/infra/MakePrivateKeyCache.kt
> +        .maximumSize(size)
I've:

1. Made caching optional
2. Grouped all the testing of caching in to one file

2023-03-07 21:07 UTC, dickon commented on components/crypto/crypto-softhsm-impl/src/test/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoServiceCachingTests.kt
> + * testing as by default the eviction is scheduled on an executor, so it's not exactly deterministic.
rephrased the comment

2023-03-07 21:07 UTC, dickon commented on components/crypto/crypto-softhsm-impl/src/test/kotlin/net/corda/crypto/softhsm/impl/infra/MakeWrappingKeyCache.kt
> +        .maximumSize(100)
see above

2023-03-07 21:09 UTC, dickon commented on components/crypto/crypto-softhsm-impl/src/test/kotlin/net/corda/crypto/softhsm/impl/infra/MakePrivateKeyCache.kt
> +        .maximumSize(size)
The best way to test caching is very much an open question. It may be worth mocking it out, but that's somewhat awkward; you pretty much end up inventing a real cache, with argument capture etc.  And there's enough in this PR and I don't see many disadavnatges in using a real caffeine cache in a single group of tests.

2023-03-07 21:10 UTC, dickon commented on components/crypto/crypto-softhsm-impl/src/test/kotlin/net/corda/crypto/softhsm/impl/infra/TestWrappingKeyStore.kt
> +open class TestWrappingKeyStore(
no longer open

2023-03-07 21:19 UTC, dickon commented on libs/crypto/cipher-suite/src/main/kotlin/net/corda/crypto/cipher/suite/CryptoService.kt
> +     * @param masterKeyAlias the alias of the key to be used as a wrapping key. TODO - rename wrappingKeyAlias
Makes an already larger PR even harder to review. Better to do the rename only in one PR, not mix it up with some contentious stuff about caching and chopping a bunch of classes.

2023-03-07 21:23 UTC, dickon commented on libs/crypto/cipher-suite/src/main/kotlin/net/corda/crypto/cipher/suite/KeyMaterialSpec.kt
> + * could still be null for HSMs which use built-in wrapping keys. TODO - rename to wrappingKeyAlias
Good idea, Added https://r3-cev.atlassian.net/browse/CORE-11474

2023-03-07 21:23 UTC, dickon commented on libs/crypto/cipher-suite/src/main/kotlin/net/corda/crypto/cipher/suite/KeyMaterialSpec.kt
> + * could still be null for HSMs which use built-in wrapping keys. TODO - rename to wrappingKeyAlias
Good idea, Added https://r3-cev.atlassian.net/browse/CORE-11474

2023-03-07 22:14 UTC, kyriathar commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoService.kt
> +        val wrappedKeyMaterial = rootWrappingKey.wrap(wrappingKey)
Thank you, and that does sound better however I afterwards saw that we use "Material" for wrapped keys in many places elsewhere so maybe let's leave as it was to maybe rename at some point later across all uses to be consistent. I shouldn't have flagged this

2023-03-08 09:15 UTC, driessamyn commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoServiceProviderImpl.kt
> +                Caffeine.newBuilder()
No. This can't be a separate ticket because it's a bug and a super simple change.
The executor must be the `SecManagerForkJoinPool` otherwise eviction from the cache will fail (be blocked by the Security Manager).
Just look at how it's done elsewhere.

2023-03-08 09:21 UTC, driessamyn commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoService.kt
> +    @VisibleForTesting
smell

2023-03-08 09:23 UTC, driessamyn commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoService.kt
> +    fun getPrivateKey(publicKey: PublicKey, spec: KeyMaterialSpec): PrivateKey =
`@VisibleForTesting` is almost always a smell. It's usually an indication of a single responsibility violation.
If this needs to be tested, it should be injected in.

It's ok for now as I don't want this refactoring to get out of hand, but keep it in mind for new code.

2023-03-08 09:25 UTC, driessamyn commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoServiceProviderImpl.kt
> +                Caffeine.newBuilder()
Actually, I sorry, I misread this. It's already using the CacheFactoryImpl.
This really should be injected though.

2023-03-08 09:26 UTC, driessamyn commented on components/crypto/crypto-softhsm-impl/src/test/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoServiceCachingTests.kt
> + * testing as by default the eviction is scheduled on an executor, so it's not exactly deterministic.
But my point is, you are correct that you can't test eviction because then you need to rely on timeouts etc. But if you used a mock cache instead, you could test the behaviour of our code around eviction.

2023-03-08 09:27 UTC, driessamyn commented on libs/crypto/cipher-suite/src/main/kotlin/net/corda/crypto/cipher/suite/KeyMaterialSpec.kt
> + * could still be null for HSMs which use built-in wrapping keys. TODO - rename to wrappingKeyAlias
Add JIRA reference in the TODO comment please.

2023-03-08 09:28 UTC, driessamyn submitted a review, later dismissed

2023-03-08 09:44 UTC, dickon commented on libs/crypto/cipher-suite/src/main/kotlin/net/corda/crypto/cipher/suite/KeyMaterialSpec.kt
> + * could still be null for HSMs which use built-in wrapping keys. TODO - rename to wrappingKeyAlias
I thought we didn't want private JIRA references in our code, but I suppose that's only because the comment was sufficient in that case.

2023-03-08 09:46 UTC, dickon commented on libs/crypto/cipher-suite/src/main/kotlin/net/corda/crypto/cipher/suite/KeyMaterialSpec.kt
> + * could still be null for HSMs which use built-in wrapping keys. TODO - rename to wrappingKeyAlias
ok

2023-03-08 09:49 UTC, fowlerrr commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoService.kt
> +    @VisibleForTesting
Yeah, I feel like some of these don't _need_ to be visible for testing.  And plenty don't need to be there at all (do we need the un/wrap counts?).

Yes, it makes a bit of a mess when you have to mock values (and then see what we do with those mocks) but it's better than leaking.  I do think we should revisit these to try and remove them if we can.  At a minimum could we at least make all of these classes `internal` so the leak is contained to the package?

2023-03-08 09:58 UTC, dickon commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoServiceProviderImpl.kt
> +                Caffeine.newBuilder()
I've made CacheFactoryImpl injected locally.

2023-03-08 10:08 UTC, dickon commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoService.kt
> +open class SoftCryptoService(
and pushed now

2023-03-08 10:10 UTC, dickon commented on components/crypto/crypto-service-impl/src/main/kotlin/net/corda/crypto/service/impl/SigningServiceImpl.kt
> +                masterKeyAlias = ref.masterKeyAlias!!
Agreed, it was a shortcut. I reworked a number of uses of !! throughout the patch to throw more meaningful errors.

2023-03-08 10:12 UTC, dickon commented on components/crypto/crypto-service-impl/src/main/kotlin/net/corda/crypto/service/impl/SigningServiceImpl.kt
> +                masterKeyAlias = ref.masterKeyAlias!!
and I just checked; I see no new uses of !! and I removed a few.

2023-03-08 10:13 UTC, dickon commented on components/crypto/crypto-softhsm-impl/src/test/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoServiceCachingTests.kt
> + * testing as by default the eviction is scheduled on an executor, so it's not exactly deterministic.
True and a good idea, which I'd prioritise that work below key rotation and fast builds so do not propose to do in this PR.

2023-03-08 10:18 UTC, kyriathar commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoServiceProviderImpl.kt
> +            val wrappingKeyCacheConfig = wrappingKeyMapConfig.getConfig("cache")
Raised this [#CORE-11477](https://r3-cev.atlassian.net/browse/CORE-11477) to capture the need to revisit crypto configuration.

2023-03-08 10:31 UTC, fowlerrr commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoServiceProviderImpl.kt
> +    private val cacheFactoryImpl: CacheFactoryImpl
Will this work?  `CacheFactoryImpl` isn't an OSGi component...  Worth running up an instance to be sure.  (if it does I'll be happy to know that!)

2023-03-08 10:33 UTC, dickon commented on libs/crypto/cipher-suite/src/main/kotlin/net/corda/crypto/cipher/suite/KeyMaterialSpec.kt
> + * could still be null for HSMs which use built-in wrapping keys. TODO - rename to wrappingKeyAlias
pushed

2023-03-08 10:46 UTC, fowlerrr commented on components/crypto/crypto-softhsm-impl/src/test/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoServiceProviderTests.kt
> -    fun setup() {
Why are we removing the `@BeforeEach`?  Are we sure that we won't have overlap errors between tests?

2023-03-08 10:48 UTC, fowlerrr submitted a review, later dismissed
I'm generally okay with this as a step towards other fixes.  I think there's still plenty to do. But most of my concerns are around code structure, which can be fixed later.  Code _correctness_ is probably the main concern at this point.  And, from my limited understanding, this still does what we need it to.

2023-03-08 10:52 UTC, dickon commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoService.kt
> +    @VisibleForTesting
I agree, though not at this point. And I think the notions are a bit vague to write up into a JIRA ticket et.

2023-03-08 11:13 UTC, kyriathar commented on components/crypto/crypto-softhsm-impl/src/test/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoServiceOperationsTests.kt
> +    fun `should generate deterministic signatures for some algorithms`(
This test name seems to have changed from 
`SoftCryptoService should generate deterministic signatures for EdDSA, SPHINCS-256 and RSA` to

`should generate deterministic signatures for some algorithms`.

No need to block the PR from going in for this, but I think we should revert.

2023-03-08 11:19 UTC, dickon commented on components/crypto/crypto-softhsm-impl/src/test/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoServiceOperationsTests.kt
> +    fun `should generate deterministic signatures for some algorithms`(
So I dropped "SoftCryptoService" for consistency with other test names. And this is a parameterised test, so you get the algorithm names in the test runner output, and we don't need to restate the list. So I think my name is better.

2023-03-08 11:28 UTC, dickon commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoServiceProviderImpl.kt
> +    private val cacheFactoryImpl: CacheFactoryImpl
It didn't. I ended up changing this. Maybe we should make `CacheFactoryImpl` be OSGi at some point but not right n ow.

2023-03-08 11:44 UTC, dickon commented on components/crypto/crypto-softhsm-impl/src/test/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoServiceProviderTests.kt
> -    fun setup() {
So I believe this is safe, and the tests seem reliable, but could be wrong due to the complexity of lifecycle. I'll revisit in future work on SoftCryptoService.

2023-03-08 12:05 UTC, fowlerrr submitted a review, later dismissed

2023-03-08 13:22 UTC, kyriathar commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoServiceProviderImpl.kt
> +    private val cacheFactoryImpl: CacheFactoryImpl
If you wanted to inject  `CacheFactory` at `SoftCryptoServiceProviderImpl` constructor you can do it like we do for example in `ChunkDbWriterFactoryImpl`

2023-03-08 13:24 UTC, kyriathar commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoService.kt
> +    private val digestService: PlatformDigestService = PlatformDigestServiceImpl(schemeMetadata)
`digestService` here shouldn't be having a defaulted value.

2023-03-08 13:30 UTC, kyriathar commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoService.kt
> +    private var unwrapCounter = AtomicInteger()
I understand these are introduced for testing purposes. Can we please find a way around this to then remove them?

2023-03-08 13:34 UTC, dickon commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoService.kt
> +    private var unwrapCounter = AtomicInteger()
No, I think they'd ideally be exposed as metrics if we really had the metrics support in place for that.

2023-03-08 23:19 UTC, dickon commented on libs/crypto/cipher-suite/src/main/kotlin/net/corda/crypto/cipher/suite/CryptoService.kt
> +     * @param masterKeyAlias the alias of the key to be used as a wrapping key. TODO - rename wrappingKeyAlias
I did the rename

2023-03-09 10:49 UTC, fowlerrr approved these changes
LGTM.  Plenty more to do but this is a good next step

2023-03-09 10:51 UTC, merged

2023-03-09 10:53 UTC, dickon commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoService.kt
> +    private val digestService: PlatformDigestService = PlatformDigestServiceImpl(schemeMetadata)
removed default

2023-03-09 10:53 UTC, dickon commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoService.kt
> +    private var unwrapCounter = AtomicInteger()
Removed; there's a test fixture that does this now