CORE-9318 Separate DB users for automatic bootstrap and runtime WIP
corda/corda-runtime-os pull request #3166
Opened 2023-02-16 10:08 UTC by jacob-scott3141

2023-02-16 13:50 UTC, wzur-r3 requested changes

2023-02-16 13:50 UTC, wzur-r3 commented on .ci/e2eTests/corda.yaml
> +    host: "prereqs-postgresql"
why this change?

we use the same Helm chart to deploy up 3 different deployments, and fixing a name here is not a good idea

2023-02-16 13:52 UTC, wzur-r3 commented on applications/workers/release/rpc-worker/src/e2eTest/resources/create.multi.clusters.sh
> +    --set 'kafka.replicaCount=1,kafka.zookeeper.replicaCount=1,kafka.offsetsTopicReplicationFactor=1,kafka.transactionStateLogReplicationFactor=1' \
please use one `--set` per value

2023-02-16 13:52 UTC, wzur-r3 commented on applications/workers/release/rpc-worker/src/e2eTest/resources/install.aws.sh
> +  --set 'kafka.replicaCount=1,kafka.zookeeper.replicaCount=1,kafka.offsetsTopicReplicationFactor=1,kafka.transactionStateLogReplicationFactor=1' \
please use one `--set` per value

2023-02-16 13:57 UTC, wzur-r3 commented on values.yaml
> +            name: "prereqs-postgresql"
rather than hardcode the name of the secret here, please use variable in template as defaults, so multiple deployments in the same Kubernetes namespace don't interfere with each other

2023-02-16 15:04 UTC, davidcurrie requested changes

2023-02-16 15:04 UTC, davidcurrie commented on .ci/e2eTests/corda.yaml
> +    host: "prereqs-postgresql"
Probably my fault - I forget that there are a bunch of overrides being applied by the pipeline. The real problem here is that we now have duplication between the pipeline and `create.multi.clusters.sh`. The latter hasn't been kept up to date but we need to apply the same overrides in both places.

2023-02-16 15:04 UTC, davidcurrie commented on .ci/e2eTests/corda.yaml
> +          name: "prereqs-postgresql"
The secret name here and also the one in `bootstrap.db` need to be overridden too as we have multiple postgres deployments.

2023-02-16 15:04 UTC, davidcurrie commented on values.yaml
> +            name: "prereqs-postgresql"
This one should be hard-coded. It's used by developers locally and is designed to work out of the box when they have provided no overrides to a prereqs install. There should be a similar change in `values-prereqs.yaml` though (for the new prereqs chart).

2023-02-17 12:01 UTC, davidcurrie commented on applications/workers/release/rpc-worker/src/e2eTest/resources/create-clusters.sh
> +#!/usr/bin/env bash
where did this script come from? doesn't it do the same thing as `create.multi.clusters.sh` but more verbosely?

2023-02-17 12:01 UTC, davidcurrie commented on .ci/e2eTests/corda.yaml
> +        value: "postgres"
this will fail in the CI until `bootstrap.db.cluster.password.valueFrom.secretKeyRef.name` is set in the shared pipeline script

2023-02-19 17:30 UTC, yarivus reviewed
See pending comments

2023-02-19 17:30 UTC, yarivus commented on .ci/e2eTests/Jenkinsfile
> +@Library('corda-shared-build-pipeline-steps@jacob/CORE-9318') _
this should be temp

2023-02-21 10:54 UTC, closed without merging