CORE-9842 Add Hardcoded InterOp Group Policies to GroupPolicyReader
corda/corda-runtime-os pull request #3173
Opened 2023-02-16 15:14 UTC by julia-filipczak

(Continued from #3129) Adding hardcoded interop group policy to enable early development. This includes the addition of the interop member role and InteropGroupPolicyReader which provides the hardcoded group policy as a string to be parsed in GroupPolicyProvider.

2023-02-16 15:29 UTC, szymonsztuka requested changes
Just one obligatory change

2023-02-16 15:29 UTC, szymonsztuka commented on libs/membership/membership-common/src/main/kotlin/net/corda/membership/lib/grouppolicy/InteropGroupPolicyReader.kt
> +  "groupId": "7c5d6948-e17b-44e7-9d1c-fa4a3f667cad",
This will later (albeit soon)  have the same value as one from the recent Saurabh PR https://github.com/corda/corda-runtime-os/commit/e372f4493133bbd539ed765ffd10a964661724b7, later on as well those keys definitions

2023-02-16 15:29 UTC, szymonsztuka commented on libs/membership/membership-common/src/main/kotlin/net/corda/membership/lib/grouppolicy/InteropGroupPolicyReader.kt
> +      "-----BEGIN CERTIFICATE-----\nMIIDQTCCAimgAwIBAgITBmyfz5m/jAo54vB4ikPmljZbyjANBgkqhkiG9w0BAQsF\nADA5MQswCQYDVQQGEwJVUzEPMA0GA1UEChMGQW1hem9uMRkwFwYDVQQDExBBbWF6\nb24gUm9vdCBDQSAxMB4XDTE1MDUyNjA
The alternative way would be to extract certificates to   a file in resources:          `this::class.java.getResource("/dummy_certificate.pem")?.readText()`
see https://github.com/corda/corda-runtime-os/blob/e372f4493133bbd539ed765ffd10a964661724b7/components/interop/interop-service/src/main/kotlin/net/corda/interop/service/InteropMemberRegistrationService.kt#L37
and then they are here: https://github.com/corda/corda-runtime-os/tree/interop/5.0/components/interop/interop-service/src/main/resources
or even to take the whole file into a resource file.
So probably or let's keep all as it is or move the whole group policy to resource file. Anyway soon some kind of testing and making the values compatible  with what we are no pushing to other queues can cover this work (https://github.com/corda/corda-runtime-os/commit/e372f4493133bbd539ed765ffd10a964661724b7)

2023-02-16 15:29 UTC, szymonsztuka commented on components/membership/group-policy-impl/src/main/kotlin/net/corda/membership/impl/grouppolicy/GroupPolicyProviderImpl.kt
> +        ?: return null
We could add a log warn in case `interopGroupPolicyReader.getGroupPolicy()` returns null (this is more for the future), but this would break up this compact if expression. However `getGroupPolicy`method signature needs to be changed to
`getGroupPolicy(identity: HoldingIdentity)` - it needs to have a parameter `HoldingIdentity`, inside we now ignore it, if a compiler don't allow use, just for some `logger.info("Searching for interoperability group for $identity")`

2023-02-16 16:11 UTC, szymonsztuka requested changes

2023-02-16 16:11 UTC, szymonsztuka commented on components/membership/group-policy-impl/src/main/kotlin/net/corda/membership/impl/grouppolicy/GroupPolicyProviderImpl.kt
> +    private val interopGroupPolicyReader: InteropGroupPolicyReader
Also this is probably an important one - maybe you need create an interface first and this field should be a type of interface, in the class you need to provide some annotation, follow the example of `GroupPolicyParser` from line 60-61 here. This build throws a runtime exception which may be result of this.

2023-02-16 17:12 UTC, SaurabhR3 requested changes

2023-02-16 17:12 UTC, SaurabhR3 commented on components/membership/registration-impl/src/main/kotlin/net/corda/membership/impl/registration/MemberRole.kt
> +                        readInterop(context)
How are we going to use Interop Role?

2023-02-16 17:12 UTC, SaurabhR3 commented on libs/membership/membership-common/src/main/kotlin/net/corda/membership/lib/grouppolicy/InteropGroupPolicyReader.kt
> +}
It would be better to move this in json file and read from resources like `this::class.java.getResource("/interop-group-policy.json")?.readText()`

2023-02-16 17:13 UTC, szymonsztuka commented on components/membership/registration-impl/src/main/kotlin/net/corda/membership/impl/registration/MemberRole.kt
> +                        readInterop(context)
James has a plan for it later on

2023-02-20 10:24 UTC, szymonsztuka commented on libs/membership/membership-common/src/main/kotlin/net/corda/membership/lib/grouppolicy/InteropGroupPolicyReader.kt
> +}
I think we can address this is the follow up ticket, when all hard-coded values (also send to queues) will be make consistent.

2023-02-20 17:38 UTC, charlieR3 commented on libs/membership/membership-common/src/main/kotlin/net/corda/membership/lib/MemberInfoExtension.kt
> +         * Interop role properties
Should this be something more descriptive like:
```suggestion
         * Interop service name
```
(I'm not sure what interop service name is so maybe there's a better description)

2023-02-20 17:38 UTC, charlieR3 commented on components/membership/registration-impl/src/main/kotlin/net/corda/membership/impl/registration/MemberRole.kt
> +            notariesKeysFactory: () -> List<KeyDetails>,
Weird that `notariesKeysFactory` is part of the base class here when it has nothing to do with notaries. Mostly an observation since I know you didn't make it that way. Something to tidy up in the future I think.

2023-02-20 17:38 UTC, charlieR3 commented on libs/membership/membership-impl/src/main/kotlin/net/corda/membership/lib/impl/grouppolicy/InteropGroupPolicyReaderImpl.kt
> +    "sessionPki": "Standard",
Just FYI, if this was `NoPKI` then `sessionTrustRoots` could be empty since it is ignored.

2023-02-20 17:38 UTC, charlieR3 commented on libs/membership/membership-impl/src/main/kotlin/net/corda/membership/lib/impl/grouppolicy/InteropGroupPolicyReaderImpl.kt
> +  "cipherSuite": {
You could simplify things here and just leave this empty as it's not currently used anywhere.

2023-02-20 17:38 UTC, charlieR3 commented on tools/plugins/topic-config/src/main/kotlin/net/corda/cli/plugins/topicconfig/Create.kt
> +        "interop" to listOf("flow", "combined")
Not sure if this was intentional and is more hardcoding to get things working but it doesn't seem correct. Although I'm not familiar with this code. It seems like it would give an interop processor access to flow topics.

2023-02-20 17:38 UTC, charlieR3 commented on libs/membership/membership-impl/src/main/kotlin/net/corda/membership/lib/impl/grouppolicy/InteropGroupPolicyReaderImpl.kt
> +    // only if HoldingIdentity's group contains "interop" (case-insensitive) in its name.
This _might_ cause issues since group ID is supposed to be a UUID

2023-02-20 18:49 UTC, jmacmahonr3 commented on libs/membership/membership-impl/src/main/kotlin/net/corda/membership/lib/impl/grouppolicy/InteropGroupPolicyReaderImpl.kt
> +    // only if HoldingIdentity's group contains "interop" (case-insensitive) in its name.
Hey @charlieR3 
All of our data for the first 3 milestones is hardcoded. So the incoming group policy id will be deterministic. We are also just saying if there isn't a group policy for a given identity at the p2p layer then just use an interop one.

2023-02-20 18:55 UTC, szymonsztuka commented on tools/plugins/topic-config/src/main/kotlin/net/corda/cli/plugins/topicconfig/Create.kt
> +        "interop" to listOf("flow", "combined")
yes, this is unrelated to functionalities of this PR, but it was needed to make Interop Processor work

2023-02-21 08:48 UTC, nikinagy commented on components/membership/group-policy-impl/src/test/kotlin/net/corda/membership/impl/grouppolicy/GroupPolicyProviderImplTest.kt
> +    fun `Interop groupPolicy is returned when CPI metadata is null `() {
Can we test non-happy paths too?

2023-02-21 08:48 UTC, nikinagy commented on components/membership/registration-impl/src/main/kotlin/net/corda/membership/impl/registration/MemberRole.kt
> +            notariesKeysFactory: () -> List<KeyDetails>,
Also, just to double-check: a member can either have notary or interop role, but not both, right?

2023-02-21 08:48 UTC, nikinagy commented on components/membership/registration-impl/src/main/kotlin/net/corda/membership/impl/registration/MemberRole.kt
> +                "$ROLES_PREFIX.$index" to INTEROP_ROLE,
this can be a const

2023-02-21 08:48 UTC, nikinagy commented on libs/membership/membership-impl/src/main/kotlin/net/corda/membership/lib/impl/grouppolicy/InteropGroupPolicyReaderImpl.kt
> +    // only if HoldingIdentity's group contains "interop" (case-insensitive) in its name.
This change will definitely break the schema validation during registration: https://github.com/corda/corda-api/blob/release/os/5.0/data/membership-schema/src/main/resources/net/corda/schema/membership/group/policy/1.0/corda.group.policy.json
(although i am not completely sure what are the plans with this)

2023-02-21 12:05 UTC, jmacmahonr3 requested changes

2023-02-21 12:05 UTC, jmacmahonr3 commented on libs/membership/membership-impl/src/main/kotlin/net/corda/membership/lib/impl/grouppolicy/InteropGroupPolicyReaderImpl.kt
> +class InteropGroupPolicyReaderImpl @Activate constructor(): InteropGroupPolicyReader {
@julia-filipczak can you add a todo to this and link to the following ticket explaining this work will later get it's own topic: https://r3-cev.atlassian.net/browse/CORE-10445

2023-02-21 13:17 UTC, szymonsztuka commented on libs/membership/membership-impl/src/main/kotlin/net/corda/membership/lib/impl/grouppolicy/InteropGroupPolicyReaderImpl.kt
> +    // only if HoldingIdentity's group contains "interop" (case-insensitive) in its name.
@nikinagy I think interop code will not trigger a registration code, but anyway there is a soft requirement to be compatible with this:
``` 
 "groupId": {
      "description": "The group ID (UUID) that this file relates to, or constant 'CREATE_ID' if a new ID must be generated. A new ID should be generated only for an MGM.",
      "pattern": "^([a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[1-5][a-fA-F0-9]{3}-[89aAbB][a-fA-F0-9]{3}-[a-fA-F0-9]{12})|CREATE_ID$"
```   
to avoid using checking `interop` string we could hardcode up 2 to UUIDs which we would expect to be an `Interop group` - this would be anyway temporarily.

2023-02-21 13:21 UTC, szymonsztuka approved these changes
I'm happy with resolution of my comments

2023-02-21 13:40 UTC, jmacmahonr3 commented on components/membership/registration-impl/src/main/kotlin/net/corda/membership/impl/registration/MemberRole.kt
> +            notariesKeysFactory: () -> List<KeyDetails>,
Yes. There is no such concept as an identity adding interop notary role

2023-02-21 13:44 UTC, jmacmahonr3 requested changes

2023-02-21 13:44 UTC, jmacmahonr3 commented on components/membership/registration-impl/src/main/kotlin/net/corda/membership/impl/registration/MemberRole.kt
> +                "$ROLES_PREFIX.$index" to INTEROP_ROLE,
@julia-filipczak please address this

2023-02-21 13:44 UTC, jmacmahonr3 commented on libs/membership/membership-impl/src/main/kotlin/net/corda/membership/lib/impl/grouppolicy/InteropGroupPolicyReaderImpl.kt
> +    "sessionPki": "Standard",
@julia-filipczak can you address this please

2023-02-21 13:44 UTC, jmacmahonr3 commented on libs/membership/membership-impl/src/main/kotlin/net/corda/membership/lib/impl/grouppolicy/InteropGroupPolicyReaderImpl.kt
> +  "cipherSuite": {
@julia-filipczak can you address this please

2023-02-21 13:49 UTC, SaurabhR3 approved these changes

2023-02-21 14:19 UTC, szymonsztuka commented on libs/membership/membership-impl/src/main/kotlin/net/corda/membership/lib/impl/grouppolicy/InteropGroupPolicyReaderImpl.kt
> +    // only if HoldingIdentity's group contains "interop" (case-insensitive) in its name.
@julia-filipczak  what about checking if group id equals this literal: https://github.com/corda/corda-runtime-os/blob/e372f4493133bbd539ed765ffd10a964661724b7/components/interop/interop-service/src/main/kotlin/net/corda/interop/service/InteropMemberRegistrationService.kt#L35
so this would be the same value as one hardcoded in MemeberInfos?

2023-02-21 16:51 UTC, szymonsztuka approved these changes

2023-02-21 17:27 UTC, merged