CORE-9865 Interop Processor hosted inside Flow Worker
corda/corda-runtime-os pull request #3178
Opened 2023-02-16 17:30 UTC by szymonsztuka

2023-02-21 11:56 UTC, jmacmahonr3 requested changes

2023-02-21 11:56 UTC, jmacmahonr3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
> +import net.corda.data.p2p.app.UnauthenticatedMessage
I'm wondering if it's better to comment out with a TODO and link to the other ticket that adds AuthenticatedMessages

2023-02-21 11:56 UTC, jmacmahonr3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
> +    private fun generateAppMessage(
As per previous comments when, might be better to leave a todo to highlight where change is needed.

2023-02-21 11:56 UTC, jmacmahonr3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropService.kt
> +        //below is temporary tactical code to setup members of interop group and send the first message,
Please Add todo for linking to the following ticket: https://r3-cev.atlassian.net/browse/CORE-10446.

2023-02-21 12:26 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
> +import net.corda.data.p2p.app.UnauthenticatedMessage
added TODO before the class declaration https://github.com/corda/corda-runtime-os/pull/3178/commits/8f38b8172f645b089e3756bfc586d7e29a0d4505

2023-02-21 12:27 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropService.kt
> +        //below is temporary tactical code to setup members of interop group and send the first message,
Added TODO to the ticket https://github.com/corda/corda-runtime-os/pull/3178/commits/8f38b8172f645b089e3756bfc586d7e29a0d4505, in general is a bit tricky as the lost of code is "temporary" evolving, I would say more that 50% is expected to be rewritten

2023-02-21 12:27 UTC, SaurabhR3 requested changes

2023-02-21 12:27 UTC, SaurabhR3 commented on applications/workers/release/flow-worker/src/main/kotlin/net/corda/applications/workers/flow/FlowWorker.kt
> +    private val interopProcessor: InteropProcessor,
`,` not required at the end

2023-02-21 12:27 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
> +                            val messageId: String, val traceId: String? = null, val subsystem: String = SUBSYSTEM)
Better to move this in data package

2023-02-21 12:27 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
> +    private fun UnauthenticatedMessage.toCommonHeader() =
Probably does not need this method as it is single line and not used anywhere else.

2023-02-21 12:27 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/InteropMemberRegistrationService.kt
> +        val testId = "test1"
It would be great to change it to `testId` to `keyId` as it is key for Record

2023-02-21 12:33 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
> +                            val messageId: String, val traceId: String? = null, val subsystem: String = SUBSYSTEM)
This is just internal class used by exclusively by InteropProcessor, hence it is an inner class, this is not something related to Facade (as data package has).

2023-02-21 13:05 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
> +    private fun UnauthenticatedMessage.toCommonHeader() =
Inlined in https://github.com/corda/corda-runtime-os/pull/3178/commits/42bd0d36c75315f59db5576ed5d7e25af6fcfafa

2023-02-21 13:46 UTC, SaurabhR3 requested changes

2023-02-21 13:46 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
> +                            val messageId: String, val traceId: String? = null, val subsystem: String = SUBSYSTEM)
I believe data package is common for all data classes in Interop processor and not only for Facade related classes.

2023-02-21 17:11 UTC, yarivus requested changes

2023-02-21 17:11 UTC, yarivus commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
>              if (authMessage != null && authMessage is AuthenticatedMessage && authMessage.header.subsystem == SUBSYSTEM) {
The if and else if have the same code block except for one word.
So the code can be simplified:
```
if (authMessage != null && authMessage.header.subsystem == SUBSYSTEM) {
    val kuku = if authMessage is AuthenticatedMessage ttl else null
    val header = with(authMessage.header) { CommonHeader(source, destination, kuku, messageId) }
    getOutputRecord(header, authMessage.payload, appMessage.key)?.let { outputRecord ->
        outputEvents.add(outputRecord)
    }
}
```

2023-02-21 17:27 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
>              if (authMessage != null && authMessage is AuthenticatedMessage && authMessage.header.subsystem == SUBSYSTEM) {
yes, the branch was eliminated in https://github.com/corda/corda-runtime-os/pull/3178/commits/80af710bda904b667461f7869683412a14bcfa02  (for now dealing only with one case UnauthenticatedMessage)

2023-02-21 18:09 UTC, yarivus approved these changes
LGTM

2023-02-22 09:41 UTC, yarivus approved these changes
LGTM

2023-02-22 16:43 UTC, yarivus reviewed
checkpointing review - looks good

2023-02-24 12:46 UTC, yarivus reviewed
see some minor comments

2023-02-24 12:46 UTC, yarivus commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropService.kt
> +        //logger.info("Publishing seed message")
leftover commented out code

2023-02-24 12:46 UTC, yarivus commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/HardcodedInteropMemberRegistrationService.kt
> +        val payload = "{\"method\": \"org.corda.interop/platform/tokens/v1.0/reserve-tokens\"," +
maybe worth formatting this for increased readability (using newlines and indents)

2023-02-24 17:41 UTC, jmacmahonr3 requested changes

2023-02-24 17:41 UTC, jmacmahonr3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropService.kt
> +        logger.info("starting")
Is this consistent with logging in other processors ?

2023-02-24 17:41 UTC, jmacmahonr3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropService.kt
> +        logger.info("starting")
It's nitpicking i know but just a small thing to ensure we are consistent with FlowProcessor etc

2023-02-24 21:04 UTC, yarivus approved these changes
LGTM

2023-02-27 14:32 UTC, yarivus reviewed
see pending comments

2023-02-28 09:01 UTC, yarivus reviewed
checkpointing review LGTM

2023-02-28 09:56 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropService.kt
> +        //logger.info("Publishing seed message")
Intentionally left commented out, see PR description.

2023-02-28 10:16 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropService.kt
> +        logger.info("starting")
excess logging has been removed

2023-02-28 10:16 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/HardcodedInteropMemberRegistrationService.kt
> +        val payload = "{\"method\": \"org.corda.interop/platform/tokens/v1.0/reserve-tokens\"," +
fixed

2023-02-28 13:01 UTC, SaurabhR3 requested changes

2023-02-28 13:01 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
>              val authMessage = appMessage.value?.message
As it is changed to UnAuthenticated message, better to change the variable name to `unAuthMessage`

2023-02-28 13:01 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
> +        }
Looks like code alignment issue

2023-02-28 15:41 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
>              val authMessage = appMessage.value?.message
fixed https://github.com/corda/corda-runtime-os/pull/3178/commits/f96cc352e66da4aa70deefb130a69a250092365c

2023-02-28 15:41 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
> +        }
fixed https://github.com/corda/corda-runtime-os/pull/3178/commits/f96cc352e66da4aa70deefb130a69a250092365c

2023-02-28 16:06 UTC, SaurabhR3 approved these changes

2023-02-28 16:40 UTC, yarivus approved these changes
LGTM

2023-02-28 16:55 UTC, jmacmahonr3 approved these changes
LGTM

2023-02-28 16:58 UTC, merged