dickon/CORE-6044-health-port
corda/corda-runtime-os pull request #3185
Opened 2023-02-20 11:59 UTC by dickon

2023-02-22 08:19 UTC, ronanbrowne approved these changes, later dismissed
LGTM

2023-02-26 17:55 UTC, driessamyn requested changes

2023-02-26 17:55 UTC, driessamyn commented on applications/workers/worker-common/src/main/kotlin/net/corda/applications/workers/workercommon/internal/Constants.kt
> +internal const val WORKER_MONITOR_PORT = 7004
I think this changes it for all workers, but we should just change the default for the combined worker I believe (otherwise all deployments are impacted).

2023-03-01 09:38 UTC, davidcurrie commented on applications/workers/worker-common/src/main/kotlin/net/corda/applications/workers/workercommon/internal/Constants.kt
> +internal const val WORKER_MONITOR_PORT = 7004
I take it the decision was made that this should be changed for all deployments?

2023-03-01 10:09 UTC, davidcurrie commented
Apologies - I've just merged a change that tramples all over the Helm chart. On the plus side, there's now only one place to change the port number...

2023-03-01 10:09 UTC, dickon commented on applications/workers/worker-common/src/main/kotlin/net/corda/applications/workers/workercommon/internal/Constants.kt
> +internal const val WORKER_MONITOR_PORT = 7004
On the other hand that means the combined worker has a different port number for monitoring, which is a bit surprising.

I'll change the helm charts for now.

2023-03-01 13:33 UTC, driessamyn commented on applications/workers/worker-common/src/main/kotlin/net/corda/applications/workers/workercommon/internal/Constants.kt
> +internal const val WORKER_MONITOR_PORT = 7004
> I take it the decision was made that this should be changed for all deployments?

@davidcurrie , no, I don't think that decision was made.

The scope of this ticket was changing the default port for the combined worker as 7000 is problematic on some macs, but I'm not convinced that changing it everywhere at this stage is the best.

2023-03-01 13:34 UTC, driessamyn commented on .run/Combined Worker Local.run.xml
> +            value="--instance-id=0 -mbus.busType=DATABASE -spassphrase=password -ssalt=salt -ddatabase.user=user -ddatabase.pass=password -ddatabase.jdbc.url=jdbc:postgresql://localhost:5432/cordaclu
This shouldn't include the enterprise addon configuration

2023-03-06 13:33 UTC, driessamyn commented on applications/workers/release/combined-worker/src/main/kotlin/net/corda/applications/workers/combined/CombinedWorker.kt
> +// See CORE-6044
Let's not have the JIRA reference here as our JIRA is not public. I think the comment explains the reason.

2023-03-06 13:34 UTC, driessamyn commented on applications/workers/worker-common/src/main/kotlin/net/corda/applications/workers/workercommon/DefaultWorkerParams.kt
> +class DefaultWorkerParams(healthPortOverride: Int? = null) {
```suggestion
class DefaultWorkerParams(healthPortOverride: Int = WORKER_MONITOR_PORT) {
```

Would maybe be simpler?

2023-03-07 11:07 UTC, dickon commented on applications/workers/worker-common/src/main/kotlin/net/corda/applications/workers/workercommon/internal/Constants.kt
> +internal const val WORKER_MONITOR_PORT = 7004
Let's just change for the combined worker at this point.

2023-03-07 11:13 UTC, dickon commented on applications/workers/release/combined-worker/src/main/kotlin/net/corda/applications/workers/combined/CombinedWorker.kt
> +// See CORE-6044
I had often wondered about that. (There are hundreds of JIRA references in the tree).

I will remove this.

2023-03-07 11:14 UTC, dickon commented on applications/workers/worker-common/src/main/kotlin/net/corda/applications/workers/workercommon/DefaultWorkerParams.kt
> +class DefaultWorkerParams(healthPortOverride: Int? = null) {
Yeah, I like it, thanks. Will apply.

2023-03-07 11:15 UTC, dickon commented on applications/workers/release/combined-worker/src/main/kotlin/net/corda/applications/workers/combined/CombinedWorker.kt
> +// See CORE-6044
done

2023-03-07 11:15 UTC, dickon commented on .run/Combined Worker Local.run.xml
> +            value="--instance-id=0 -mbus.busType=DATABASE -spassphrase=password -ssalt=salt -ddatabase.user=user -ddatabase.pass=password -ddatabase.jdbc.url=jdbc:postgresql://localhost:5432/cordaclu
removed

2023-03-07 11:37 UTC, driessamyn approved these changes, later dismissed
LGTM

2023-03-09 08:57 UTC, davidcurrie approved these changes, later dismissed
👍

2023-03-09 11:22 UTC, davidcurrie approved these changes

2023-03-09 12:11 UTC, mag1c-48 approved these changes
LGTM - build files

2023-03-09 12:14 UTC, merged