CORE-10465 Implement Interop Service & outgoing request handler
corda/corda-runtime-os pull request #3194
Opened 2023-02-21 10:36 UTC by ac101m

# Changes
- Add temporary/speculative `invokeInterop` API.

2023-03-24 11:02 UTC, yarivus approved these changes
LGTM

2023-03-24 11:02 UTC, yarivus commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/application/services/impl/FlowMessagingImpl.kt
> +        session.close()
is there a mechanism of implicit session.close() ?
In C# it was very common to use `using` statement:
```
using (val session = createInteropFlowSession(memberName)) {

} // here the session.close() is called
```
If not ... what will happen if one of the prior calls to `session.close()` throws ?

2023-03-24 11:02 UTC, yarivus commented on components/interop/interop-service/src/integrationTest/kotlin/net/corda/interop/service/integration/InteropServiceIntegrationTest.kt
> +    @Disabled("Temporarily disabled as part of CORE-10465")
placeholder comment not to leave disabled

2023-03-24 11:02 UTC, yarivus reviewed
See my comments @ac101m

2023-03-24 11:06 UTC, ac101m commented on components/interop/interop-service/src/integrationTest/kotlin/net/corda/interop/service/integration/InteropServiceIntegrationTest.kt
> +    @Disabled("Temporarily disabled as part of CORE-10465")
So this was actually added by @szymonsztuka, there is an ongoing conversation about what to do with these. It may actually be necessary that they remain disabled for a couple of merges!

2023-03-24 11:34 UTC, ac101m commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/application/services/impl/FlowMessagingImpl.kt
> +        session.close()
So I actually tried this when I was writing this code, but because `FlowSession` doesn't implement `Closeable`, we can't do this. Also, sessions are cleaned up automatically when the flow ends. I've added a try/finally block for good measure.

P.S. I'm fairly sure loose sessions are cleaned up when the flow ends!

2023-03-24 16:06 UTC, ac101m commented on components/interop/interop-service/src/integrationTest/kotlin/net/corda/interop/service/integration/InteropServiceIntegrationTest.kt
> +    @Disabled("Temporarily disabled as part of CORE-10465")
These have now been re-enabled

2023-03-24 16:09 UTC, szymonsztuka approved these changes
As written in TODOs a workaround in FlowMapper will be short lived, however it proved that new API works.

2023-03-24 17:02 UTC, jmacmahonr3 approved these changes
LGTM but please add necessary tickets and todo changes.

2023-03-24 17:02 UTC, jmacmahonr3 commented on libs/flows/flow-mapper-impl/src/main/kotlin/net/corda/flow/mapper/impl/executor/SessionEventExecutor.kt
> +    // Temporary hack for CORE-10465, will be removed in subsequent PR
If there is a ticket that we have to remove this can you add a TODO with the ticket name ? 
If we don't have a ticket can you please create one.

2023-03-24 17:02 UTC, jmacmahonr3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/messaging/ConcurrentFlowMessaging.kt
> +        TODO("The simulator does not currently support facade calls.")
We should probably create a ticket for this as well .... although im not sure who would own it. 
Raise this with me again next week.

2023-03-24 17:11 UTC, ac101m commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/messaging/ConcurrentFlowMessaging.kt
> +        TODO("The simulator does not currently support facade calls.")
I have a couple of thoughts about this, we can discuss on Monday during our 121

2023-03-24 17:18 UTC, ac101m commented on libs/flows/flow-mapper-impl/src/main/kotlin/net/corda/flow/mapper/impl/executor/SessionEventExecutor.kt
> +    // Temporary hack for CORE-10465, will be removed in subsequent PR
So, we can't actually put a literal TODO in the code because detekt will complain about it! But I suspect CORE-10420 will be the ticket that removes this stuff. Comments have been amended appropriately.

2023-03-25 12:29 UTC, yarivus requested changes

2023-03-25 12:29 UTC, yarivus commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/application/services/impl/FlowMessagingImpl.kt
> +            session.sendAndReceive(FacadeInvocation::class.java, request)
You should employ the try...finally on the other statements call before `val response =....`

2023-03-27 09:23 UTC, ac101m commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/application/services/impl/FlowMessagingImpl.kt
> +            session.sendAndReceive(FacadeInvocation::class.java, request)
The other statement is just a constructor call which doesn't throw, but I've moved it for good measure anyway.

2023-03-27 10:18 UTC, ac101m commented on libs/flows/flow-mapper-impl/src/main/kotlin/net/corda/flow/mapper/impl/executor/SessionEventExecutor.kt
> +    // Temporary hack for CORE-10465, will be removed in subsequent PR
Added `@Suppress("ForbiddenComment")` and added TODO

2023-03-27 13:56 UTC, jmacmahonr3 commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/messaging/ConcurrentFlowMessaging.kt
> +        TODO("The simulator does not currently support facade calls.")
@ac101m we forgot to discuss this. Do you want to capture your thoughts here?

2023-03-27 14:16 UTC, ac101m commented on simulator/runtime/src/main/kotlin/net/corda/simulator/runtime/messaging/ConcurrentFlowMessaging.kt
> +        TODO("The simulator does not currently support facade calls.")
Yup, thought I was forgetting something, in summary:
- API is temporary/placeholder at the moment so there's no need to do this now.
- Definitely need to talk to devex about it in the future, do multi-cluster simulations even make sense?
- Future injectable intereop service class might offer a softer way to signal to the user that the functionality is/is not present.
Otherwise, I think an offline discussion is likely to be more productive.

2023-03-27 21:07 UTC, yarivus approved these changes
LGTM

2023-03-28 09:48 UTC, yarivus approved these changes
LGTM

2023-03-28 12:33 UTC, szymonsztuka approved these changes

2023-03-28 12:50 UTC, merged