CORE-9318 Separate DB users for automatic bootstrap and runtime WIP
corda/corda-runtime-os pull request #3196
Opened 2023-02-21 12:50 UTC by jacob-scott3141

Updated changes to work with REST / RPC  name changes

2023-02-21 15:00 UTC, jacob-scott3141 commented on .ci/e2eTests/Jenkinsfile
> +@Library('corda-shared-build-pipeline-steps@jacob/CORE-9318') _
Need to revert this before merge

2023-02-21 16:39 UTC, davidcurrie requested changes

2023-02-21 16:39 UTC, davidcurrie commented on values.yaml
> +            key: "password"
```suggestion
            key: "postgres-password"
```

2023-02-21 16:39 UTC, davidcurrie commented on values.yaml
> +        value: "user"
No reason why this should be different from what we have in the CI.
```suggestion
        value: "postgres"
```

2023-02-21 16:39 UTC, davidcurrie commented on values-prereqs.yaml
> +        value: "user"
Just to keep people on their toes, I named these differently in the new `corda-dev-prereqs` chart. You should check that these overrides work there.
```suggestion
            name: "prereqs-postgres"
            key: "postgres-password"
      username:
        value: "postgres"
```

2023-02-21 17:02 UTC, yarivus reviewed
see pending comment

2023-02-21 17:02 UTC, yarivus commented on .ci/e2eTests/Jenkinsfile
> +@Library('corda-shared-build-pipeline-steps@jacob/CORE-9318') _
please ensure this is changed before the merge ;)

2023-02-22 09:36 UTC, davidcurrie submitted a review, later dismissed
👍

2023-02-22 10:51 UTC, davidcurrie approved these changes
👍

2023-02-22 11:07 UTC, yarivus approved these changes
LGTM

2023-02-22 12:50 UTC, merged