CORE-10556 Migrate `CryptoConnectionsFactory` from using lifecycle `AbstractComponent`
corda/corda-runtime-os pull request #3218
Opened 2023-02-22 13:17 UTC by kyriathar

…tConfigurableComponent` to plain lifecycle

2023-03-06 09:51 UTC, dickon reviewed
Looks good. 

Please would you undo the rename components/crypto/crypto-persistence-impl/src/test/kotlin/net/corda/crypto/persistence/impl/tests/CryptoConnectionsFactoryTests.kt -> components/crypto/crypto-persistence-impl/src/test/kotlin/net/corda/crypto/persistence/impl/tests/CryptoConnectionsFactoryTest.kt (i.e. removing the plural) to make the change easier to review.

2023-03-06 11:41 UTC, dickon requested changes

2023-03-06 11:41 UTC, dickon commented on components/crypto/crypto-persistence-impl/src/test/kotlin/net/corda/crypto/persistence/impl/tests/CryptoConnectionsFactoryTest.kt
> +    @Order(1)
Why the strict ordering?

2023-03-06 11:41 UTC, dickon commented on components/crypto/crypto-persistence-impl/src/main/kotlin/net/corda/crypto/persistence/impl/CryptoConnectionsFactoryImpl.kt
> +    override fun start() {
can we use the Kotlin delegated properties  to save these stub methods?

2023-03-06 11:41 UTC, dickon commented on components/crypto/crypto-persistence-impl/src/main/kotlin/net/corda/crypto/persistence/impl/CryptoConnectionsFactoryImpl.kt
> +                        log.info("Received ${event.status::name} event, closing resources")
I don't think we should clear caches just because of DOWN or ERROR events, if there's any chance of an UP event later.

2023-03-06 11:41 UTC, dickon commented on components/crypto/crypto-persistence-impl/src/main/kotlin/net/corda/crypto/persistence/impl/CryptoConnectionsFactoryImpl.kt
> +            ::dbConnectionManager,
Nitpicking, but if this will all fit on one line I think we should format it that way. Smallness matters.

2023-03-06 11:41 UTC, dickon commented on components/crypto/crypto-persistence-impl/src/main/kotlin/net/corda/crypto/persistence/impl/CryptoConnectionsFactoryImpl.kt
> +            connections!!.get(tenantId) { createEntityManagerFactory(tenantId) }
It's not clear that `connections` is always notnull, so let's handle this more gracefully.

Ideally let's make connections notnull.

2023-03-06 11:41 UTC, dickon commented on components/crypto/crypto-persistence-impl/src/main/kotlin/net/corda/crypto/persistence/impl/CryptoConnectionsFactoryImpl.kt
> +    var connections: Cache<String, EntityManagerFactory>? = null
I think it'd be better to have the word cache in the identifier here.

2023-03-06 11:41 UTC, dickon commented on components/crypto/crypto-persistence-impl/src/main/kotlin/net/corda/crypto/persistence/impl/CryptoConnectionsFactoryImpl.kt
> +    var connections: Cache<String, EntityManagerFactory>? = null
How about construction a cache with default parameters here, which we then replace (or better reconfigure in caffine permits) when the config comes in?

2023-03-06 11:41 UTC, dickon commented on components/crypto/crypto-persistence-impl/src/main/kotlin/net/corda/crypto/persistence/impl/CryptoConnectionsFactoryImpl.kt
> +                    "virtual node for $tenantId is not registered."
`throw throw` looks wrong.

2023-03-06 11:41 UTC, dickon commented on components/crypto/crypto-persistence-impl/src/main/kotlin/net/corda/crypto/persistence/impl/CryptoConnectionsFactoryImpl.kt
> +                        updateStatus(event.status)
Not clear if we should go DOWN if an upstream is down since that stops callers  using cache connections.

2023-03-06 11:41 UTC, dickon commented on components/crypto/crypto-persistence-impl/src/main/kotlin/net/corda/crypto/persistence/impl/CryptoConnectionsFactoryImpl.kt
> +                updateStatus(LifecycleStatus.UP)
Isn't it possible that a vital upstream is still down at this point?

2023-03-06 11:41 UTC, dickon commented on components/crypto/crypto-persistence-impl/src/test/kotlin/net/corda/crypto/persistence/impl/tests/CryptoConnectionsFactoryTest.kt
> +    @Order(1)
I mean, this probably prevents test parallelism so should be avoided unless there's a good reason.

2023-03-06 13:13 UTC, kyriathar commented on components/crypto/crypto-persistence-impl/src/test/kotlin/net/corda/crypto/persistence/impl/tests/CryptoConnectionsFactoryTest.kt
> +    @Order(1)
Good point but I don't think there is test parallelism within same test class. @ronanbrowne I think this is the case?

2023-03-06 13:15 UTC, kyriathar commented on components/crypto/crypto-persistence-impl/src/main/kotlin/net/corda/crypto/persistence/impl/CryptoConnectionsFactoryImpl.kt
> +    override fun start() {
Not really sure I understand this one

2023-03-06 13:16 UTC, kyriathar commented on components/crypto/crypto-persistence-impl/src/main/kotlin/net/corda/crypto/persistence/impl/CryptoConnectionsFactoryImpl.kt
> +                        log.info("Received ${event.status::name} event, closing resources")
This is a good point, but I believe this is how it used to work. Happy to register a JIRA about it, to tackle under different piece of work.

2023-03-06 13:17 UTC, kyriathar commented on components/crypto/crypto-persistence-impl/src/main/kotlin/net/corda/crypto/persistence/impl/CryptoConnectionsFactoryImpl.kt
> +            ::dbConnectionManager,
Can't, too long line then.

2023-03-06 13:18 UTC, kyriathar commented on components/crypto/crypto-persistence-impl/src/main/kotlin/net/corda/crypto/persistence/impl/CryptoConnectionsFactoryImpl.kt
> +                    "virtual node for $tenantId is not registered."
Fixed

2023-03-06 13:20 UTC, kyriathar commented on components/crypto/crypto-persistence-impl/src/main/kotlin/net/corda/crypto/persistence/impl/CryptoConnectionsFactoryImpl.kt
> +    var connections: Cache<String, EntityManagerFactory>? = null
Will change to `connectionsCache`, I think business should be on name.

2023-03-06 13:23 UTC, kyriathar commented on components/crypto/crypto-persistence-impl/src/main/kotlin/net/corda/crypto/persistence/impl/CryptoConnectionsFactoryImpl.kt
> +    var connections: Cache<String, EntityManagerFactory>? = null
Again, change in behavior I think, could do under different JIRA, the way it currently is, is the equivalent to what it used to be i.e. ex `ActiveImpl` which was holding the cache was created upon receiving configuration for this component (which was configuration for the cache I believe).

2023-03-06 13:26 UTC, kyriathar commented on components/crypto/crypto-persistence-impl/src/main/kotlin/net/corda/crypto/persistence/impl/CryptoConnectionsFactoryImpl.kt
> +                updateStatus(LifecycleStatus.UP)
Getting a `ConfigChangedEvent` at this point means we previously got `RegistrationStatusChangeEvent.status == UP` which means at that point all dependent components went UP and then registered to `ConfigurationReadService` for config updates. If something went DOWN/ ERROR after that means a new `RegistrationStatusChangeEvent.status == UP/ DOWN` this time.

2023-03-06 13:47 UTC, kyriathar commented on components/crypto/crypto-persistence-impl/src/main/kotlin/net/corda/crypto/persistence/impl/CryptoConnectionsFactoryImpl.kt
> +            connections!!.get(tenantId) { createEntityManagerFactory(tenantId) }
Good catch this one, I think resources generally tend to be nullable. I do agree that we should not be allowing a `NullPointerException`. Will take care of that.

2023-03-06 13:54 UTC, kyriathar commented on components/crypto/crypto-persistence-impl/src/main/kotlin/net/corda/crypto/persistence/impl/CryptoConnectionsFactoryImpl.kt
> +                        updateStatus(event.status)
Good catch. Not really sure either. What you imply here is maybe split the dependent components to watch them separately. Again I believe worth raising a JIRA for this one to be handled separately.

2023-03-06 13:58 UTC, kyriathar commented on components/crypto/crypto-persistence-impl/src/main/kotlin/net/corda/crypto/persistence/impl/CryptoConnectionsFactoryImpl.kt
> +                        updateStatus(event.status)
I also believe the way it currently is, is how it used to work before too.

2023-03-07 08:23 UTC, dickon commented on components/crypto/crypto-persistence-impl/src/test/kotlin/net/corda/crypto/persistence/impl/tests/CryptoConnectionsFactoryTest.kt
> +    @Order(1)
Doesn't matter, if we don't need the ordering we shouldn't specify it, and as far as I can see these tests are independent of each other.

2023-03-07 10:58 UTC, dickon approved these changes, later dismissed
overall LGTM, ticket filed on the cache issue.

2023-03-07 10:58 UTC, dickon commented on components/crypto/crypto-persistence-impl/src/main/kotlin/net/corda/crypto/persistence/impl/CryptoConnectionsFactoryImpl.kt
> +            ::dbConnectionManager,
okay

2023-03-07 10:58 UTC, dickon commented on components/crypto/crypto-persistence-impl/src/main/kotlin/net/corda/crypto/persistence/impl/CryptoConnectionsFactoryImpl.kt
> +    var connections: Cache<String, EntityManagerFactory>? = null
Fair enough on not changing behaviour here, so I wrote https://r3-cev.atlassian.net/browse/CORE-11419 to  track this idea.

2023-03-07 10:58 UTC, dickon commented on components/crypto/crypto-persistence-impl/src/main/kotlin/net/corda/crypto/persistence/impl/CryptoConnectionsFactoryImpl.kt
> +                        log.info("Received ${event.status::name} event, closing resources")
Covered in https://r3-cev.atlassian.net/browse/CORE-11419

2023-03-07 10:58 UTC, dickon commented on components/crypto/crypto-persistence-impl/src/main/kotlin/net/corda/crypto/persistence/impl/CryptoConnectionsFactoryImpl.kt
> +                updateStatus(LifecycleStatus.UP)
That's a more brittle assumption than we need to make.

I'd be willing to approve that with a comment though it seems feasible to check that here.

2023-03-07 10:58 UTC, dickon commented on components/crypto/crypto-persistence-impl/src/main/kotlin/net/corda/crypto/persistence/impl/CryptoConnectionsFactoryImpl.kt
> +    override fun start() {
https://kotlinlang.org/docs/delegation.html

I had a go and got as far as:

```

@Component(service = [CryptoConnectionsFactory::class])
class CryptoConnectionsFactoryImpl @Activate constructor(
    @Reference(service = LifecycleCoordinatorFactory::class)
    coordinatorFactory: LifecycleCoordinatorFactory,
    @Reference(service = ConfigurationReadService::class)
    private val configurationReadService: ConfigurationReadService,
    @Reference(service = DbConnectionManager::class)
    private val dbConnectionManager: DbConnectionManager,
    @Reference(service = JpaEntitiesRegistry::class)
    private val jpaEntitiesRegistry: JpaEntitiesRegistry,
    @Reference(service = VirtualNodeInfoReadService::class)
    private val virtualNodeInfoReadService: VirtualNodeInfoReadService
) : CryptoConnectionsFactory, LifecycleCoordinator by coordinatorFactory.createCoordinator(
        LifecycleCoordinatorName(CryptoConnectionsFactory::class.simpleName),
        DependentComponents.of(dbConnectionManager, virtualNodeInfoReadService, configurationReadService),
        processEvent
)  {
    companion object {
        private val log = LoggerFactory.getLogger(CryptoConnectionsFactory::class.java)
    }
```

However that's not legal since we can't reference `processEvent` at that location.

2023-03-07 13:31 UTC, driessamyn commented on components/crypto/crypto-persistence-impl/src/test/kotlin/net/corda/crypto/persistence/impl/tests/CryptoConnectionsFactoryTest.kt
> +    @Order(1)
Agree with @dickon .
Assume all test run in parallel because maybe one day they will.
We should only enforce order if there's a very good reason. It's generally an anti-pattern.

2023-03-07 13:39 UTC, driessamyn commented on components/crypto/crypto-persistence-impl/src/main/kotlin/net/corda/crypto/persistence/impl/CryptoConnectionsFactoryImpl.kt
> +    @VisibleForTesting
Needing `@VisibleForTesting` is usually a smell.
I appreciate the structure existed, but generally try to see how things can be tested without needing to do this. In most cases, keeping to the single responsibility principle will mean you don't need to do this.

2023-03-07 13:39 UTC, driessamyn commented on components/crypto/crypto-persistence-impl/src/main/kotlin/net/corda/crypto/persistence/impl/CryptoConnectionsFactoryImpl.kt
> +                    // intentional
Why?

2023-03-07 13:39 UTC, driessamyn commented on components/crypto/crypto-persistence-impl/src/main/kotlin/net/corda/crypto/persistence/impl/CryptoConnectionsFactoryImpl.kt
> +    return CacheFactoryImpl().build(
`CacheFactoryImpl` should probably be injected so that you can inject a mock/stub during testing.

2023-03-07 15:54 UTC, kyriathar commented on components/crypto/crypto-persistence-impl/src/test/kotlin/net/corda/crypto/persistence/impl/tests/CryptoConnectionsFactoryTest.kt
> +    @Order(1)
These tests are actually dependent hence the ordering to avoid duplication. Will change them to be independent.

2023-03-07 15:55 UTC, kyriathar commented on components/crypto/crypto-persistence-impl/src/main/kotlin/net/corda/crypto/persistence/impl/CryptoConnectionsFactoryImpl.kt
> +            connections!!.get(tenantId) { createEntityManagerFactory(tenantId) }
Changed it to require not null before using it.

2023-03-08 10:51 UTC, kyriathar commented on components/crypto/crypto-persistence-impl/src/main/kotlin/net/corda/crypto/persistence/impl/CryptoConnectionsFactoryImpl.kt
> +                    // intentional
That was there before this change, not really sure. 

From the looks of it, so that it proceeds with closing all of the entity manager factories even if some `close()` fails? Though I can see it can only throw `IllegalStateException` if the entity manager factory has been closed already.

2023-03-08 11:39 UTC, kyriathar commented on components/crypto/crypto-persistence-impl/src/main/kotlin/net/corda/crypto/persistence/impl/CryptoConnectionsFactoryImpl.kt
> +    return CacheFactoryImpl().build(
Done

2023-03-09 11:04 UTC, dickon commented on components/crypto/crypto-persistence-impl/src/test/kotlin/net/corda/crypto/persistence/impl/tests/CryptoConnectionsFactoryTest.kt
> +    @Order(1)
Let's get this merged first, it's been open too long and I want it in. A ticket to remove the dependencies between tests would be the best way forward.

2023-03-09 11:06 UTC, dickon commented on components/crypto/crypto-persistence-impl/src/main/kotlin/net/corda/crypto/persistence/impl/CryptoConnectionsFactoryImpl.kt
> +            connections!!.get(tenantId) { createEntityManagerFactory(tenantId) }
Great, looks good

2023-03-09 11:06 UTC, dickon commented on components/crypto/crypto-persistence-impl/src/main/kotlin/net/corda/crypto/persistence/impl/CryptoConnectionsFactoryImpl.kt
> +                        updateStatus(event.status)
Let's not change that now then.

2023-03-09 11:07 UTC, dickon commented on components/crypto/crypto-persistence-impl/src/main/kotlin/net/corda/crypto/persistence/impl/CryptoConnectionsFactoryImpl.kt
> +                updateStatus(LifecycleStatus.UP)
But let's get this in, we can come back to this.

2023-03-09 11:07 UTC, dickon commented on components/crypto/crypto-persistence-impl/src/main/kotlin/net/corda/crypto/persistence/impl/CryptoConnectionsFactoryImpl.kt
> +    @VisibleForTesting
Fine but let's not repeat the mistake of requiring perfection on a refactoring change, it slows us down too much.

2023-03-09 11:08 UTC, dickon commented on components/crypto/crypto-persistence-impl/src/main/kotlin/net/corda/crypto/persistence/impl/CryptoConnectionsFactoryImpl.kt
> +                    // intentional
Okay, old code, no need to fix in a useful refactoring step.

2023-03-09 11:09 UTC, dickon commented on components/crypto/crypto-persistence-impl/src/main/kotlin/net/corda/crypto/persistence/impl/CryptoConnectionsFactoryImpl.kt
> +    return CacheFactoryImpl().build(
I'm happy with how it is now.

2023-03-09 11:10 UTC, dickon commented
LGTM, nice work @kyriathar

2023-03-09 11:11 UTC, dickon approved these changes
LGTM, nice work @kyriathar

2023-03-09 11:13 UTC, merged