CORE:10425 : Facade to flow mapper implementation
corda/corda-runtime-os pull request #3236
Opened 2023-02-23 15:46 UTC by SaurabhR3

1. Facade mapper service.
2. Code snippet to read the facade to flow mapping from CPI info reader metadata
3. Dummy facade to flow mapping configuration

2023-02-24 11:39 UTC, szymonsztuka requested changes
The code changes has no impact on interop processor (the new code is never invoked).

2023-02-24 11:39 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/FacadeToFlowMapperService.kt
> +
delete extra line

2023-02-24 11:39 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/FacadeToFlowMapperService.kt
> +            .first { it.facadeId == facadeId }.mapping
Would be the later solution (final one) using a yaml file as well, or this will be read from class annotations (Weft annotations)? If the latter we could skip adding this test file and reading from yaml altogether.

2023-02-24 11:39 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/FacadeToFlowMapperService.kt
> +        //TODO: Now we are using hardcoded facade definition and
Is this the final code which is just commented out for now, or  a sample for development in the future? If the latter this could be moved to a next ticket responsible for integration with these services, it the first, why not use this code and then just add fallback to the code reading the hardcoded `"/dummy-facade-to-flow-config.yaml")?.readText()`

2023-02-24 12:16 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/FacadeToFlowMapperService.kt
> +            .first { it.facadeId == facadeId }.mapping
Interop Processor will read the mapping config file provided by cordapp developer in cpi metadata. Weft annotations will not read it by any way.

2023-02-24 12:24 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/FacadeToFlowMapperService.kt
> +        //TODO: Now we are using hardcoded facade definition and
This is not final code as it is neither in use nor tested. Once the changes about pushing the mapping config in CPI Matadata will be made/available(hopefully in couple of weeks) then we need to play another integration story for this. Also needs to remove the dummy facade.
We can implement the fallback mechanism if virtual node is not available. But I think still we will need integration story later to integrate with Julia's changes

2023-02-24 12:27 UTC, SaurabhR3 commented
> The code changes has no impact on interop processor (the new code is never invoked).

I deliberately not invoked it, I think its better to integrate it with Julia's changes once they are ready.

2023-02-24 12:58 UTC, yarivus requested changes

2023-02-24 12:58 UTC, yarivus commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/data/FacadeFlowInfo.kt
> +data class Mapping(val facadeMethod : String, val flowName : String)
I think `Mapping` should be renamed to something more specific (e.g. `FacadeMethodMapping`)

2023-02-24 12:58 UTC, yarivus commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/FacadeToFlowMapperService.kt
> +        //Now we are using hardcoded facade definition and
add a space `//Now` to align with the rest of the comment

2023-02-24 12:58 UTC, yarivus commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/FacadeToFlowMapperService.kt
> +    fun getFlowName(
add newline before `fun getFlowName`

2023-02-24 12:58 UTC, yarivus commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/FacadeToFlowMapperService.kt
> +        // The following code snippet suggest that how we can read it when it will be available.
`suggest` => `suggests`
and remove 'that'
and `and when it will be`

2023-02-24 12:58 UTC, yarivus commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/FacadeToFlowMapperService.kt
> +        if(vNodeInfo != null) {
add space in `if(`

2023-02-24 14:11 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/FacadeToFlowMapperService.kt
> +
Resolved in d0a6982

2023-02-24 14:50 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/FacadeToFlowMapperService.kt
> +        //TODO: Now we are using hardcoded facade definition and
"This is not final code as it is neither in use nor tested." so what the point of this ticket and PR, if it's neither tested not used. 
Also this code should be already invoked in interop processor to see if it working, even if the result is used in dummy way - e.g. repackage as message in the response. 
I don't think the ticker is blocked by others, you can implemented the fully fledged code  to gather information via third party services and knowingly that they will not return any data so you can add the fallback hard-codded value for now.

2023-02-24 15:14 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/FacadeToFlowMapperService.kt
> +            .first { it.facadeId == facadeId }.mapping
Understood, clear now.

2023-02-24 15:18 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/FacadeToFlowMapperService.kt
> +        //TODO: Now we are using hardcoded facade definition and
Ok ignore my part "_I don't think the ticker is blocked ....._" as I see in the new commit you  have enabled the code.

2023-02-24 15:41 UTC, szymonsztuka requested changes

2023-02-24 15:41 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/FacadeToFlowMapperService.kt
> +            return mapper.readValue(
Would be better to integrated  the "temporary code" almost as it would the production code - so any code routine shared by temp and not temp code is coded only once ( with very minimal way just fallback to hardcoded one). More specifically there should be single occurrence of `mapper.readValue` which takes value from the first branch  or the hardcoded one if the "prod" returns null:
````
val mappings =  //  try { /*getting from vNodeInfo (the whole if not null branch)*/ } catch (e: Exception) { log.warn() 
 null }?: this::class.java.getResource("/dummy-facade-to-flow-config.yaml")?.readText()
mapper.readValue(mappings, ....)
````

2023-02-24 15:41 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/FacadeToFlowMapperService.kt
> +            return cpiMetadata.cpksMetadata.first().cordappManifest.attributes.get("") ?: ""
I think this takes MANIFEST file , those files has specific format.  Maybe better already hard-coded here what file name we are taking from the manifest.

2023-02-24 15:41 UTC, szymonsztuka commented on components/interop/interop-service/src/main/resources/dummy-facade-to-flow-config.yaml
> +facade-flow-mapping:
If this is a final format it begs for some unit tests with the new data classes.

2023-02-24 16:00 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/data/FacadeFlowInfo.kt
> +data class Mapping(val facadeMethod : String, val flowName : String)
Changed in ea72206

2023-02-24 16:00 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/FacadeToFlowMapperService.kt
> +    fun getFlowName(
Changed in ea72206

2023-02-24 16:01 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/FacadeToFlowMapperService.kt
> +        // The following code snippet suggest that how we can read it when it will be available.
Changed in ea72206

2023-02-24 16:02 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/resources/dummy-facade-to-flow-config.yaml
> +facade-flow-mapping:
Added in ea72206

2023-02-24 16:02 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/FacadeToFlowMapperService.kt
> +        if(vNodeInfo != null) {
Changed in ea72206

2023-02-24 16:12 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/FacadeToFlowMapperService.kt
> +        //Now we are using hardcoded facade definition and
Changed in ea72206

2023-02-24 16:17 UTC, szymonsztuka commented on components/interop/interop-service/src/main/resources/dummy-facade-to-flow-config.yaml
> +facade-flow-mapping:
cool

2023-02-24 16:44 UTC, jmacmahonr3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/FacadeToFlowMapperService.kt
> +            return cpiMetadata.cpksMetadata.first().cordappManifest.attributes.get("") ?: ""
I don't understand what you are referring to here @szymonsztuka

2023-02-24 16:59 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/FacadeToFlowMapperService.kt
> +            return cpiMetadata.cpksMetadata.first().cordappManifest.attributes.get("") ?: ""
I thought we are taking typical JAR Manifest file, however we are accessing Corda specific data structures, which invalidates partially my comment. So the comment was more to trigger some discussion about where the data comes from: 
We are taking the first cpk (`cpksMetadata.first()`) - what about if there are more cpks and our data is in the second/third one?
Then access string from the map of attributes  (should we decide for some particular name  instead of `""`). I'm not sure if the attribute can have the whole yaml file as text?
`data class CordappManifest(
....
val attributes: Map<String, String>
`
Also why returning empty string if not found, following the existing convention we should throw exception.

2023-02-24 17:10 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/FacadeToFlowMapperService.kt
> +            return cpiMetadata.cpksMetadata.first().cordappManifest.attributes.get("") ?: ""
I would suggest, please do not consider this code as final code. We are going to have discussion with Owen and Dries on Monday. The current implementation to read from cpi metadata is just a proposal, how we can read the metadata.
I need to update this based on discussion with Owen and Dries. Actually that was the main reason initially I kept that code commented.

2023-02-24 17:23 UTC, jmacmahonr3 requested changes

2023-02-24 17:23 UTC, jmacmahonr3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/FacadeToFlowMapperService.kt
> +                this::class.java.getResource("/dummy-facade-to-flow-config.yaml")?.readText(),
I'm wondering our class structure is correct here. 
I think we should probably followed the class hierarchy of how membership layer gets grouppolicy 

So we would have a facadeMapperProvider which would get the raw file and pass it to a FacadeMapperParser

2023-02-24 17:23 UTC, jmacmahonr3 commented on components/interop/interop-service/src/main/resources/dummy-facade-to-flow-config.yaml
> +    flow-name: com.net.corda.flow.GetBalanceFlow
Dumb question buy have we validated that this is how the actual flow mapper is expecting us to call flows ? 
It's important to make sure the output of this service is everything we need on the flow side to ask the Flow Processor / Flow mapper to start a flow

2023-02-24 21:03 UTC, yarivus approved these changes
LGTM

2023-02-27 14:32 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/resources/dummy-facade-to-flow-config.yaml
> +    flow-name: com.net.corda.flow.GetBalanceFlow
If we think about the RPCOps Rest API, it uses 3 parameters 
1. clientId : it can be id to identity client request. 
2. flowClassName : full class name
3. requestBody : request parameters to to make a call to flow.
I have used similar flow class name convention as RPCOps API
Hope that okay.

2023-02-27 17:59 UTC, yarivus reviewed
LGTM

2023-02-28 13:11 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/FacadeToFlowMapperService.kt
> +                this::class.java.getResource("/dummy-facade-to-flow-config.yaml")?.readText(),
As this is temporary code and will be removed when we will start fetching the mapping from CPI Metadata. Hence thought of better to keeping it in single line with reading and parsing the file.

2023-02-28 13:16 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/FacadeToFlowMapperService.kt
> +            return mapper.readValue(
Leverage Kotlin expression nature of if else (as I posted in the previous comment) , ignore my formatting in the snippet below:
```
 val content =
        if (vNodeInfo != null) {
            ...
            cpiMetadata.cpksMetadata.first().cordappManifest.attributes[FACADE_TO_FLOW_MAPPING]?:""
        } else {
            this::class.java.getResource("/dummy-facade-to-flow-config.yaml")?.readText().toString()
        }
```

2023-02-28 13:16 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/FacadeToFlowMapperService.kt
> +                .first { it.facadeId == facadeId }.facadeMethodMapping
I'm fine with any formatting style but it should be consistent, here each new chained expression part is in the new line, so maybe lets put `.facadeMethodMapping` in the new line as well, I'm fines for wrapping all in as fewer lines as possible

2023-02-28 13:16 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/FacadeToFlowMapperService.kt
> +                .first { it.facadeMethod == facadeName }
`.first` may throw NPE, we should deal with it via  meaningful error message, same applies to line above

2023-02-28 13:16 UTC, szymonsztuka commented on components/interop/interop-service/src/test/kotlin/net/corda/interop/service/FacadeToFlowMapperServiceTest.kt
> +        val flowName = facadeToFlowMapperService.getFlowName( holdingIdentity, facadeId, facadeMethod)
extra space after `(`

2023-02-28 15:12 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/FacadeToFlowMapperService.kt
> +                .first { it.facadeMethod == facadeName }
Added in f8ea8

2023-02-28 15:33 UTC, szymonsztuka requested changes

2023-02-28 15:33 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/FacadeToFlowMapperService.kt
> +        facadeMethodMapping.filterNotNull().first { it.facadeMethod == facadeName }
This is better: 
```
private fun findMappingByFacadeName(
        facadeMethodMapping: List<FacadeMethodMapping>,
        facadeName: String
    ) = facadeMethodMapping.firstOrNull{ it.facadeMethod == facadeName } ?: 
         throw IllegalStateException("Failed to find facade to flow mapping for facadeName : $facadeName")
```

or 
```
...
) = try {
        facadeMethodMapping.first { it.facadeMethod == facadeName }  
    } catch (e: NoSuchElementException) {
        throw IllegalStateException("Failed to find facade to flow mapping for facadeName : $facadeName")
    }
```
the citation of Intellij compiler advise `.filterNotNull()` in this line:  _Useless call on collection type_.
Samme for the next function.

2023-02-28 15:33 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/FacadeToFlowMapperService.kt
> +            checkNotNull(facadeFlowMapping.facadeFlowMapping) { "Failed to find facadeFlowMapping $facadeFlowMapping" }
Should be this check moved inside the method to be consistent with other methods, they don't return null objects only throw an exception.

2023-02-28 16:43 UTC, yarivus approved these changes
LGTM

2023-02-28 17:17 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/FacadeToFlowMapperService.kt
> +        facadeMethodMapping.filterNotNull().first { it.facadeMethod == facadeName }
Issue was with parser, it was adding null values if does not find the data for property. I have added appropriate annotations in data classes to fail it while parsing.

2023-02-28 17:22 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/FacadeToFlowMapperService.kt
> +            checkNotNull(facadeFlowMapping.facadeFlowMapping) { "Failed to find facadeFlowMapping $facadeFlowMapping" }
Removed it as it is not required now.

2023-02-28 17:27 UTC, szymonsztuka approved these changes
As spoken offline, this PR will be follow up by another PR addressing an integration with InteropProcessor (InteropProcessor invokes this method to get mapping). I would personally do not create a new service (`FacadeToFlowMapperService`) just for one method for now, but we can at later stage think if it's better to have a separate service or merge with existing one.

2023-02-28 17:27 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/FacadeToFlowMapperService.kt
> +                ?.flowName
I presume maybe in later stages we would like have info at which stage we failed to find something, method name, facade name, so we can or log it or send back as response. But this is potentially for the future.

2023-03-01 18:33 UTC, szymonsztuka approved these changes

2023-03-01 20:32 UTC, yarivus commented on components/interop/interop-service/src/main/resources/dummy-facade-to-flow-config.yaml
> +{
this is no longer a YAML so rename the file to .json

2023-03-01 20:32 UTC, yarivus requested changes
see comment

2023-03-02 14:25 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/resources/dummy-facade-to-flow-config.yaml
> +{
Changed in f2ba0db

2023-03-02 14:46 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/FacadeToFlowMapperServiceImpl.kt
> +        mapper.readValue(content, MutableMap::class.java)
Could we parse it to some Pojo object to avoid this `<*, *>` and then force casting to (`as MutableMap<*,*>`)?

2023-03-02 15:22 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/FacadeToFlowMapperServiceImpl.kt
> +        mapper.readValue(content, MutableMap::class.java)
Changed in a319c

2023-03-02 15:39 UTC, szymonsztuka commented on components/interop/interop-service/src/main/resources/dummy-facade-to-flow-config.json
> +    "reserve-tokens": "com.net.corda.flow.ReserveTokenFlow"
I think this is not an intended JSON semantics - the file has no keys, both "key" and "values" are effctively values, we can read the proper intention of each value if it's not described by a key.  This has the ripple effect in inability to parse into a typed object with proper field,  so previously we had yam like this:
```
facade-flow-mapping:
- facade-id: org.corda.interop/platform/hello-interop/v1.0
  facade-method-mapping:
  - facade-method: say-hello
    flow-name: com.net.corda.flow.SayHelloFlow
```
So we have assigned meaning as "facade-id", "facade-name" etc. I think we should follow convention while transitioning to JSON

2023-03-02 15:39 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/FacadeToFlowMapperServiceImpl.kt
> +@Suppress("UNCHECKED_CAST")
This has just moved the issue up also preventing compile check over the whole class.

2023-03-02 15:44 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/resources/dummy-facade-to-flow-config.json
> +    "reserve-tokens": "com.net.corda.flow.ReserveTokenFlow"
If you remember, in Demo session @r3domfox  suggested compact json format like this `{  "org.corda.interop/platform/hello-interop/v1.0": {    "say-hello": "..."  }}`
I have made changed accordingly.

2023-03-02 15:47 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/FacadeToFlowMapperServiceImpl.kt
> +@Suppress("UNCHECKED_CAST")
Moved to method level.

2023-03-02 19:14 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/FacadeToFlowMapperServiceImpl.kt
> +@Suppress("UNCHECKED_CAST")
The compiler is warning about this unchecked cast exception on  a purpose, how the code behave if this exception will be thrown?

2023-03-02 19:18 UTC, szymonsztuka commented on components/interop/interop-service/src/main/resources/dummy-facade-to-flow-config.json
> +    "reserve-tokens": "com.net.corda.flow.ReserveTokenFlow"
The suggestion was not to use linear search and lists, however I think "maps" could be hidden behind/or implemented as well-typed POJO class. This would probably make obsolete the forced casting like `(facadeIdMap as MutableMap<String, String>)`.

2023-03-03 09:32 UTC, szymonsztuka commented on components/interop/interop-service/src/main/resources/dummy-facade-to-flow-config.json
> +    "reserve-tokens": "com.net.corda.flow.ReserveTokenFlow"
We have 2 more options (ignore formatting), file contains pairs, each value has a meaning full key, it's easy to read by human, however it's not a map:
```
{   "facade": " org.corda.interop/platform/hello-interop/v1.0",
    "mappings": [
        { "name": "say-hello",
          "flow": "com.net.corda.flow.SayHelloFlow",
        },
        {  "name": "get-balance",
          "flow": "com.net.corda.flow.GetBalanceFlow"
        }]
  },
  {
    "facade": " org.corda.interop/platform/toekns/v1.0",
    "mappings": [
    ....
```
and some mix of your approach (adding "facade and mapping key, leaving actual mappings as a map):
```
{ [ {
  "facade": " org.corda.interop/platform/hello-interop/v1.0",
  "mappings": 
    {
      "say-hello": "com.net.corda.flow.SayHelloFlow",
      "get-balance": "com.net.corda.flow.GetBalanceFlow"
    }
},
{
"facade": " org.corda.interop/platform/tokens/v1.0",
"mappings":  { 
   ....
```

2023-03-03 10:07 UTC, yarivus reviewed
LGTM - still pending comments

2023-03-03 10:08 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/FacadeToFlowMapperServiceImpl.kt
> +@Suppress("UNCHECKED_CAST")
What about such method:
```
    @Suppress("UNCHECKED_CAST")
    private fun getFacadeMapping(content: String): Map<String, Map<String, String>> = try {
        mapper.readValue(content, MutableMap::class.java) as Map<String, Map<String, String>>
    } catch (e: Exception) {
        throw IllegalStateException("Unable to parse the facade to flow mapping : $e")
    }
```
It's still has suppressed casting but in the same line in which we know it's parse as Map of Maps

2023-03-03 10:44 UTC, yarivus approved these changes
LGTM

2023-03-03 11:12 UTC, driessamyn reviewed
I don't have much context, so only reviewed this in the context I have around the relation between the facade mapping doc and CPKs.

2023-03-03 11:12 UTC, driessamyn commented on components/interop/interop-service/build.gradle
> +    implementation "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.12.5"
Bit of a detail, but we always put version numbers in `gradle.properties`

2023-03-03 11:12 UTC, driessamyn commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/FacadeToFlowMapperServiceImpl.kt
> +            checkNotNull(vNodeInfo) {
This is a bit odd as you're doing 2 null checks on the same object.

2023-03-03 11:12 UTC, driessamyn commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/FacadeToFlowMapperServiceImpl.kt
> +                "Failed to find the virtual node info for holder '${destinationIdentity}' in ${virtualNodeInfoReadService::class.java}"
I think you'll need to consider what happens in this scenario.
More specifically, what does it mean to have an invalid VNode ID? Is this a retriable error (e.g. is there a chance the data isn't up to date yet), or is this fatal, and what does that mean for the rest of the interop process?

2023-03-03 11:12 UTC, driessamyn commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/FacadeToFlowMapperServiceImpl.kt
> +            check(cpiMetadata.cpksMetadata.isNotEmpty()) { "No CPKs defined for CPI Meta data id='${cpiMetadata.cpiId}'" }
As above. What are the impact of these exceptions?

2023-03-03 11:12 UTC, driessamyn commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/FacadeToFlowMapperServiceImpl.kt
> +            // If the packaging team will change the solution in the future, then we need make appropriate changes.
I don't understand this comment, or the implementation below.

- Why pick the first CPK? And what is there for the packaging team to change? As discussed, a CPI consists of multiple CPKs, including multiple workflow CPKs. Picking the first one, at random, doesn't make any sense.
- Why look at the manifest first, then load a resource file? I thought the solution discussed was that this facade to flow mapping would be a resource file inside the CPKs? This will need to be extracted from the CPKs at installation time, then stored in the DB and published to Kafka, I think as part of the `CpkMetadata` object.

2023-03-03 11:12 UTC, driessamyn commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/FacadeToFlowMapperServiceImpl.kt
> +            this::class.java.getResource("/dummy-facade-to-flow-config.json")?.readText().toString()
This is a bit odd too.
If you want to hardcode stuff, it would make more sense to change the `CpkMetada` class and hardcode it there.

2023-03-03 11:12 UTC, driessamyn commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/FacadeToFlowMapperServiceImpl.kt
> +            throw IllegalStateException("Failed to fetch facade to flow mapping.")
Again. What is the implication of an exception here?

2023-03-03 11:12 UTC, driessamyn commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/FacadeToFlowMapperServiceImpl.kt
> +    private fun getFacadeMapping(content: String): MutableMap<String, MutableMap<String, String>> = try {
It would probably make sense to do JSON schema validation on this document.

2023-03-03 11:40 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/FacadeToFlowMapperServiceImpl.kt
> +            checkNotNull(vNodeInfo) {
The first if is just to use the fallback on hardcoded mapping. The second one I kept deliberately so that when we will remove the hardcoded one, we need to throw the exception if vNode is null. Second one is not getting called now.

2023-03-03 11:52 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/FacadeToFlowMapperServiceImpl.kt
> +            this::class.java.getResource("/dummy-facade-to-flow-config.json")?.readText().toString()
Right now we are adding dummy/hardcoded stuff at most of the places. As of now we don't have real virtual node to entertain the interop request, so we don't have any associated CPI and CPKs. Hence we choose to add this hardcoded mapping in interop processor.  Hope that make sense.

2023-03-03 14:18 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/FacadeToFlowMapperServiceImpl.kt
> +            // If the packaging team will change the solution in the future, then we need make appropriate changes.
@driessamyn The comment you have highlighted is older one, I will change it. To give you context, This code is not getting called in the current interops request processing as there is no real virtual node. I have added this code just to mimic or represents the future way of implementation and that also prior to our meeting.
I think it's really creating more confusion, so I will remove it for now.

2023-03-03 15:12 UTC, owenstanford commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/FacadeToFlowMapperServiceImpl.kt
> +    private fun getFacadeMapping(content: String): MutableMap<String, MutableMap<String, String>> = try {
I'm assuming we should do this at the point of upload?

2023-03-03 15:19 UTC, owenstanford commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/FacadeToFlowMapperServiceImpl.kt
> +            val facadeFlowMapping = getFacadeMapping(content)
Given the façade metadata is a known structure and will be validated, it might be easier to define define a set of facade meta data classes you can deserialize into, it might be a bit cleaner than the map navigation.

2023-03-03 15:33 UTC, owenstanford commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/FacadeToFlowMapperServiceImpl.kt
> +            this::class.java.getResource("/dummy-facade-to-flow-config.json")?.readText().toString()
We've not looked at the design in detail yet but I'm assuming we will end up with something a bit like this:
```
enum WellKnownResource{
    INTEROP_FACADE,
    EXTERNAL_CHANNELS
}

data class CpkMetadata(
    val cpkId: CpkIdentifier,
    val manifest: CpkManifest,
    val mainBundle: String,
    val libraries: List<String>,
    val wellKnownResourceFiles Map<WellKnownResource,String>,
```

As mentioned there is potential for the developers to add multiple CPKs each with a resource, so the platform will need to handle that in some way. I guess there is a question about when we do this, is it part of validation or is it a runtime concern? My view is that we don't really want failures at runtime for simple validation checks that could be done during upload. @driessamyn thoughts?
FYI @filipesoliveira

2023-03-03 17:58 UTC, driessamyn commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/FacadeToFlowMapperServiceImpl.kt
> +            this::class.java.getResource("/dummy-facade-to-flow-config.json")?.readText().toString()
> My view is that we don't really want failures at runtime for simple validation checks that could be done during upload.

I agree with @owenstanford on this.

I'm not entirely sure whether we should have something like `val wellKnownResourceFiles Map<WellKnownResource,String>` or just multiple properties (e.g. `val interOpFacade: String, val externalChannels: String`). This would follow what we do with groupPolicy on `CpiMetadata`.

If those are JSON files and we have JSON schemas, we could validate them against that at the point of uploading, but I don't think we'd want to go beyond that in terms of how much the upload process knows about InterOp (or external channels).
So don't think the "how do we handle multiple" question should be solved in the packaging layer. Assuming it's valid to have multiple the InterOp code should be responsible for processing all of them, but the packaging layer can individually validate them against a JSON schema.

WRT to the hardcoded stuff, I don't really understand why having the or what the benefit is of using a resource file, but I'll leave that to you.

2023-03-03 18:04 UTC, driessamyn commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/FacadeToFlowMapperServiceImpl.kt
> +            val facadeFlowMapping = getFacadeMapping(content)
Probably a question for the wrong audience (@r3domfox or @jmacmahonr3 maybe?), but given French keyboards are in a global minority, isn't Facade with the c cedille going to really annoy the crap out of everybody? I think I may actually refuse to spell it like that EVER unless it's in French text. 
C cedille isn't even part of the English alphabet.

2023-03-06 09:14 UTC, owenstanford commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/FacadeToFlowMapperServiceImpl.kt
> +            val facadeFlowMapping = getFacadeMapping(content)
spell check corrected, but now I know hw much it annoys you, I try to use it everywhere ;)

2023-03-06 09:19 UTC, driessamyn commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/FacadeToFlowMapperServiceImpl.kt
> +            val facadeFlowMapping = getFacadeMapping(content)
That's ok. I'll resort to responding in French or Dutch or maybe a mixture of the two.

2023-03-06 16:07 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/FacadeToFlowMapperServiceImpl.kt
> +                "Failed to find the virtual node info for holder '${destinationIdentity}' in ${virtualNodeInfoReadService::class.java}"
For milestone-2 we are adding these error logs and throwing the error. For future milestone we are going to send these error back to caller flow, so that caller flow can take appropriate action.

2023-03-06 16:08 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/FacadeToFlowMapperServiceImpl.kt
> +            check(cpiMetadata.cpksMetadata.isNotEmpty()) { "No CPKs defined for CPI Meta data id='${cpiMetadata.cpiId}'" }
Just like above in future milestone these errors will be sent back caller flow.

2023-03-06 16:14 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/FacadeToFlowMapperServiceImpl.kt
> +            throw IllegalStateException("Failed to fetch facade to flow mapping.")
This basically concludes that the mapping is not configured either by cordapp application developer or there are some issue while reading it. 
Changed error message to more specific now. 
Similar to other error scenario in future milestone it be communicated back to caller flow form interop processor.

2023-03-06 16:15 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/FacadeToFlowMapperServiceImpl.kt
> +    private fun getFacadeMapping(content: String): MutableMap<String, MutableMap<String, String>> = try {
Changed to Pojo and we can validate in future milestone while uploading the file using json schema.

2023-03-06 18:12 UTC, yarivus reviewed
minor comment

2023-03-06 18:12 UTC, yarivus commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
> +                            val traceId: String? = null, val subsystem: String = SUBSYSTEM)
I think that for increased readability each param should be on its own in a separate line

2023-03-06 21:09 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
> +                            val traceId: String? = null, val subsystem: String = SUBSYSTEM)
Fixed in 644fd4f

2023-03-07 08:50 UTC, yarivus approved these changes
LGTM

2023-03-07 14:35 UTC, yarivus approved these changes
LGTM - clean merge

2023-03-07 14:58 UTC, jmacmahonr3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
> +                MemberX500Name.parse(header.destination.x500Name),
The params here are incorrect but it'll need to be fixed by the whomever commits their work second between you and @julia-filipczak

2023-03-07 14:59 UTC, jmacmahonr3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
> +                MemberX500Name.parse(header.destination.x500Name),
Sorry to be clear: you are passing in the alias when you should be passing in the real holding identity but that's not something you have access to until julia's pr is merged

2023-03-07 15:00 UTC, jmacmahonr3 approved these changes
LGTM

2023-03-08 12:01 UTC, merged