CORE-11196: dont swap branch for tag build on downstream jobs
corda/corda-runtime-os pull request #3284
Opened 2023-03-01 18:22 UTC by ronanbrowne

Ensure when creating a release of C5 we don't attempt to swap branches for tag build - as this will fail, a downstream tag of e2e test should just use the head of that tag

2023-03-01 20:56 UTC, yarivus requested changes

2023-03-01 20:56 UTC, yarivus commented on .ci/e2eTests/JenkinsfileCombinedWorker
> +                    if ((params.COMMIT_TO_CHECKOUT && env.CHANGE_ID == null) && env.TAG_NAME == null ) {  // CHANGE_ID only populated in PRs
From a separate PR, same comment here - consistency of parenthesis usage.
I would write it, for clarity as such:
```
if (params.COMMIT_TO_CHECKOUT &&
    env.CHANGE_ID == null &&
    env.TAG_NAME == null ) {
```

2023-03-03 13:16 UTC, ronanbrowne commented on .ci/e2eTests/JenkinsfileCombinedWorker
> +                    if ((params.COMMIT_TO_CHECKOUT && env.CHANGE_ID == null) && env.TAG_NAME == null ) {  // CHANGE_ID only populated in PRs
Update, I've left on one line However as IMO that is more readable for simple conditional logic like this to see at a glace.

2023-03-03 14:45 UTC, yarivus approved these changes
LGTM

2023-03-04 10:04 UTC, merged