CORE-10427 - Alias Identity Mapper
corda/corda-runtime-os pull request #3291
Opened 2023-03-02 15:54 UTC by julia-filipczak

Translating the alias into it’s underlying holding identity to enable it to start a flow in the flow processor. Alias Mapping is only required in the direction of Alias to underlying Holding Identity. This involves adding mapping information to the Alias's MemberInfo.

2023-03-02 16:02 UTC, szymonsztuka approved these changes

2023-03-02 16:12 UTC, szymonsztuka requested changes

2023-03-02 16:12 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/HardcodedInteropMemberRegistrationService.kt
> +                KeyValuePair(INTEROP_ALIAS_MAPPING, "O=Alice,L=London,C=GB@Gold"),
This will also assign this alias and role to both memebers `Alice Alter Ego` and `Alice` which I think is not intended. This fields needs to be assigned only to `Alice Alter Ego` MemberInfo.

2023-03-02 16:14 UTC, julia-filipczak commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/HardcodedInteropMemberRegistrationService.kt
> +                KeyValuePair(INTEROP_ALIAS_MAPPING, "O=Alice,L=London,C=GB@Gold"),
I was under the impression that both dummy identities defined in this class are aliases for the real alice identity.

2023-03-02 16:16 UTC, jmacmahonr3 requested changes

2023-03-02 16:16 UTC, jmacmahonr3 commented on libs/membership/membership-common/src/main/kotlin/net/corda/membership/lib/MemberInfoExtension.kt
> +        const val INTEROP_ALIAS_MAPPING = "corda.interop.mapping"
maybe call this "corda.interop.alias.identity"

2023-03-02 16:16 UTC, jmacmahonr3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/HardcodedInteropMemberRegistrationService.kt
> +                KeyValuePair(INTEROP_ALIAS_MAPPING, "O=Alice,L=London,C=GB@Gold"),
Reminder this is the gotcha 
We will know the x500 of the real holding identity but we won't know the group name so we'll need to search for it.

2023-03-02 16:17 UTC, jmacmahonr3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/HardcodedInteropMemberRegistrationService.kt
> +                KeyValuePair(INTEROP_ALIAS_MAPPING, "O=Alice,L=London,C=GB@Gold"),
@SaurabhR3 please confirm as I was under the same opinion as Julia 
If this is correct @julia-filipczak can you rename this to Alice-Ego & Alice-Alter-Ego

2023-03-02 16:22 UTC, jmacmahonr3 approved these changes
LGTM

2023-03-02 16:51 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/HardcodedInteropMemberRegistrationService.kt
> +                KeyValuePair(INTEROP_ALIAS_MAPPING, "O=Alice,L=London,C=GB@Gold"),
Ok, right, however the they should belong to different groups - e.g. `Alice Alter Ego` is alias for Alice in Gold, while `Alice`is an alias for Alice in e.g  "USD network". Also we are hard-coding IDs of real membership groups, we have no guarantees that they will be called `Gold`, `Bond` etc.
In this sense I guess it will be impossible to hardcore the value and have any successful run in e2e tests.  Would need to assign a real groups to our hard-coded indites from above.

2023-03-02 17:32 UTC, julia-filipczak commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/HardcodedInteropMemberRegistrationService.kt
> +                KeyValuePair(INTEROP_ALIAS_MAPPING, "O=Alice,L=London,C=GB@Gold"),
This will be later addressed by searching by the x500 name of the host identity, in our test environment we will make sure that the x500 names are unique so we should be able to overcome the fact that we cannot determine the groupId.

2023-03-02 18:56 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/HardcodedInteropMemberRegistrationService.kt
> +                KeyValuePair(INTEROP_ALIAS_MAPPING, "O=Alice,L=London,C=GB"),
_Translating the alias into it’s underlying holding identity_ the value above is not `HoldingIdentity` because it doesn't contain a group. Will your code in the follow up PR be able to find a `HoldingIdentity` based on identity's X500Name only? What is format of this `INTEROP_ALIAS_MAPPING` field?

2023-03-03 09:10 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/HardcodedInteropMemberRegistrationService.kt
> +                KeyValuePair(INTEROP_ALIAS_MAPPING, "O=Alice,L=London,C=GB"),
I've read  your explanation, so in the code I would add a comment  e.g. `// Incomplete value, missing GroupId for testing purposes`, if we go back to having '@Gold' as originally in this Pr then we should put a comment `//Hardcoded group Id will be ignored by now`

2023-03-03 09:55 UTC, szymonsztuka approved these changes

2023-03-03 11:29 UTC, merged

2023-03-03 11:32 UTC, SaurabhR3 approved these changes