CORE-10427 - Alias Identity Mapper part 2
corda/corda-runtime-os pull request #3299
Opened 2023-03-03 13:44 UTC by julia-filipczak

Adding method to return mapping of alias name and the hardcoded name of the real holding identity and invoking it in the interop processor.

2023-03-03 14:06 UTC, szymonsztuka requested changes

2023-03-03 14:06 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
> +                logger.info("The alias ${unAuthMessage.header.destination.x500Name} is mapped to the real holding identity ${getRealHoldingIdentity(unAuthMessage.header.destination).values.firstOrNul
Why first and not a second or third?

2023-03-03 14:06 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
> +    private fun getRealHoldingIdentity(recipientId: net.corda.data.identity.HoldingIdentity): MutableMap<String, String> {
The method, name "getRealHoldingIdentity" doesn't do what it says, it doesn't return a HoldingIdentity but a map of something.

2023-03-03 14:06 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
> +        cache[recipientId.x500Name.toString()] = "O=Alice,L=London,C=GB"
Why this function insert to the cache, should this function get from the cache? Again filling up data to the cache is other concern, e.g. during service startup.

2023-03-03 14:50 UTC, jmacmahonr3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
> +                logger.info("The alias ${unAuthMessage.header.destination.x500Name} is mapped to the real holding identity ${getRealHoldingIdentity(unAuthMessage.header.destination).values.firstOrNul
@julia-filipczak is the assumption that there will only be 1 matching x500 ?

2023-03-03 14:59 UTC, szymonsztuka requested changes

2023-03-03 14:59 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
> +    private fun getRealHoldingIdentity(recipientId: net.corda.data.identity.HoldingIdentity): String? {
I think we should return HoldingIdentity object not a string (the same type what is used a parameter).

2023-03-03 15:28 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
> +                        )?.x500Name.toString()
print the whole Holding Identity this is not needed (`?.x500Name.toString())` , think what to print when Identity is null (not found)

2023-03-03 16:34 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
> +        return cache[recipientId.x500Name.toString()]
Currently we are returning null, should we return _hardcoded name of the real holding identity_ as written in the PR description?

2023-03-03 16:37 UTC, julia-filipczak commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
> +        return cache[recipientId.x500Name.toString()]
What would this hardcoded name correspond to if we're not actually placing anything in the cache yet?

2023-03-03 16:55 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
> +        return cache[recipientId.x500Name.toString()]
If you are returning null then it's fine, change the PR description, if you want to return something hardcoded then e.g.:
```
private fun getRealHoldingIdentity(recipientId: net.corda.data.identity.HoldingIdentity): HoldingIdentity? {
        return HoldingIdentity(MemberX500Name.parse("CN=Alice, O=Alice Corp, L=LDN, C=GB"), "Gold")
}
```
or 
```
private fun getRealHoldingIdentity(recipientId: net.corda.data.identity.HoldingIdentity): HoldingIdentity? {
        val cache = mutableMapOf<String, HoldingIdentity>()
        // As the cache is empty returning hardcoded Alice from Gold for now
        return cache[recipientId.x500Name.toString()] ? HoldingIdentity(MemberX500Name.parse("CN=Alice, O=Alice Corp, L=LDN, C=GB"), "Gold")
}
```
or
```
private fun getRealHoldingIdentity(recipientId: net.corda.data.identity.HoldingIdentity): HoldingIdentity? {
        val cache = mutableMapOf<String, HoldingIdentity>()
        // As the cache is empty returning the same Identity with hardoced group "Gold" 
        return cache[recipientId.x500Name.toString()] ? HoldingIdentity(recipientId.x500Name, "Gold")
}
```

2023-03-03 16:56 UTC, jmacmahonr3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
> +        return cache[recipientId.x500Name.toString()]
Create a method that gets called on processor start up called loadAliasInfo and create the hardcoded map there. 
Then in your getRealIdentity method just call that map.

2023-03-06 13:04 UTC, szymonsztuka approved these changes

2023-03-07 08:48 UTC, yarivus reviewed
Checkpointing review

2023-03-07 08:48 UTC, yarivus commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/InteropAliasTranslatorImpl.kt
> +        private const val GROUP_NAME = "interop_stub_hosting_map"
Is this the right group name ?
Shouldn't the name contain alias & translator ?

2023-03-07 08:48 UTC, yarivus commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/InteropAliasTranslatorImpl.kt
> +class InteropAliasTranslatorImpl(
I'm assuming you're planning a unit-test for this class

2023-03-07 10:49 UTC, jmacmahonr3 requested changes

2023-03-07 10:49 UTC, jmacmahonr3 commented on components/interop/interop-service/build.gradle
> +    implementation project(":components:link-manager")
What are we dependent on from link manager ?

2023-03-07 10:49 UTC, jmacmahonr3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/InteropAliasTranslatorImpl.kt
> +class InteropAliasTranslatorImpl(
Please add a comment to this class explaining why we need it also please link to the Ticket from milestone 4 where the db worker will write to memberInfo topic which will allow us to delete this class.

2023-03-07 10:49 UTC, jmacmahonr3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
> +                val groupReader = membershipGroupReaderProvider.getGroupReader(unAuthMessage.header.destination.toCorda())
these three lines can be extracted to a method

2023-03-07 13:44 UTC, jmacmahonr3 commented
@julia-filipczak is interop/5.0 the correct branch ? I thought that that was the milestone 1 branch ?

2023-03-07 13:51 UTC, szymonsztuka commented
> @julia-filipczak is interop/5.0 the correct branch ? I thought that that was the milestone 1 branch ?

This is the only branch having Interop code

2023-03-07 13:55 UTC, jmacmahonr3 commented
> > @julia-filipczak is interop/5.0 the correct branch ? I thought that that was the milestone 1 branch ?
> 
> This is the only branch having Interop code

Didn't Saurabh cut another branch? 
We should have one branch per milestone going forward. This will enable Dave M to test without the code changing under his feet.

2023-03-07 16:37 UTC, SaurabhR3 requested changes

2023-03-07 16:37 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
> +        override fun onNext(
Extra space

2023-03-07 16:37 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
> +        )
You can remove extra line here

2023-03-07 16:37 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
> +
Better to just accept `destination: String` as parameter rather than complete object `unAuthMessage: UnauthenticatedMessage`

2023-03-09 12:14 UTC, yarivus reviewed
no comments - checkpointing review

2023-03-10 11:29 UTC, yarivus reviewed
checkpointing review - looks good

2023-03-10 14:19 UTC, jmacmahonr3 approved these changes

2023-03-10 15:52 UTC, yarivus approved these changes
LGTM

2023-03-15 23:37 UTC, yarivus approved these changes
LGTM

2023-03-16 11:06 UTC, jmacmahonr3 approved these changes
LGTM

2023-03-16 12:08 UTC, yarivus approved these changes
LGTM

2023-03-16 12:44 UTC, SaurabhR3 approved these changes

2023-03-16 16:15 UTC, yarivus approved these changes
LGTM

2023-03-16 17:27 UTC, merged