CORE-10383 Add query registration implementation
corda/corda-runtime-os pull request #3327
Opened 2023-03-07 14:51 UTC by nkovacsx

### Overview

Queries can now be registered by implementing the interface `VaultNamedQueryFactory` in a CPK. This way the sandbox will automatically pick up the given query implementation and will register it to the `VaultNamedQueryRegistry`.

### Test Notes

- Added new unit tests
- Testing in a flow is not possible for now because the registry is only visible in the DB worker, smoke tests will be added in the next ticket when we create the communication between DB worker <-> flow worker

2023-03-09 17:33 UTC, lankydan commented on components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/query/VaultNamedQueryRegistry.kt
> +    fun getQuery(name: String): VaultNamedQuery?
Don't need any `@Suspendable`s in the implementation either, not until we do the flow side.

2023-03-09 17:33 UTC, lankydan commented on components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/query/impl/VaultNamedQueryBuilderFactoryImpl.kt
> +class VaultNamedQueryBuilderFactoryImpl @Activate constructor(
It should already be thread safe because we're creating new builders, that eventually register themselves. The registration is then adding to a map. So as long as the map is thread safe, then we're good. We'll probably want a `ConcurrentHashMap` if you haven't used one already.

2023-03-09 17:33 UTC, lankydan commented on components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/query/impl/VaultNamedQueryBuilderFactoryImpl.kt
> +        private val logger = LoggerFactory.getLogger(this::class.java.enclosingClass)
Don't need the double private. Just have the private on the companion object.

Can we use the class name instead of `this::class.java.enclosingClass`, not a big deal but I don't really like it.

I prefer `log` but can live with `logger` since a lot of others use it :)

2023-03-09 17:33 UTC, lankydan commented on components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/query/impl/VaultNamedQueryBuilderFactoryImpl.kt
> +    override fun create(queryName: String): VaultNamedQueryBuilder {
We can remove the suspendable. Because we're not in flows, we should be safe to use `logger.debug {}` again.

2023-03-09 17:33 UTC, lankydan commented on components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/query/impl/VaultNamedQueryFactoryProvider.kt
> +        // TODO extra checks needed?
Not sure. Do other providers do things?

2023-03-09 17:33 UTC, lankydan commented on components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/query/impl/VaultNamedQueryRegistryImpl.kt
> +    private val queryStorage = ConcurrentHashMap<String, VaultNamedQuery>()
Cool, you already used a `ConcurrentHashMap` so I think we're good for thread safety.

2023-03-09 17:33 UTC, lankydan commented on components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/query/impl/VaultNamedQueryRegistryImpl.kt
> +        require(queryStorage[query.name] == null) {
This check is correct.

Can we log a warn as well and change "stored" to "registered" in the message.

To make this threadsafe we should use one of the `compute` style methods. We risk it not existing when we do `queryStorage[query.name] == null` but then existing when we call `queryStorage[query.name] = query`.

2023-03-09 17:33 UTC, lankydan commented on components/ledger/ledger-persistence/src/test/kotlin/net/corda/ledger/persistence/query/VaultNamedQueryBuilderFactoryImplTest.kt
> +            .collect(mockCollector)
Looking at this, and after talking to @blsemo I think the `collect` should only be allowed as the last operation before `register`.

So we should modify the public interfaces of the builder to cope with this. We'd need the collect method to return a different interface which you can only then call `register`.

I'm not sure what the nicest way to achieve this is. I'd like `register` to be common between the "normal" builder and the "collected" builder but naming wise it seems weird. Have a think and see if you can come up with anything, otherwise we can talk about it.

2023-03-09 17:33 UTC, lankydan commented on components/ledger/ledger-persistence/src/test/kotlin/net/corda/ledger/persistence/query/VaultNamedQueryBuilderFactoryImplTest.kt
> +class VaultNamedQueryBuilderFactoryImplTest {
Can we also have a more specific test for the builder class.

2023-03-10 10:13 UTC, nkovacsx commented on components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/query/impl/VaultNamedQueryBuilderFactoryImpl.kt
> +class VaultNamedQueryBuilderFactoryImpl @Activate constructor(
good point!

2023-03-10 10:14 UTC, nkovacsx commented on components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/query/impl/VaultNamedQueryBuilderFactoryImpl.kt
> +        private val logger = LoggerFactory.getLogger(this::class.java.enclosingClass)
As I saw the double private is a common practice throughout the code since @chrisr3 's changes. Not sure if it does anything or why we do it.

2023-03-10 10:18 UTC, nkovacsx commented on components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/query/impl/VaultNamedQueryRegistryImpl.kt
> +        require(queryStorage[query.name] == null) {
Good point!

2023-03-10 10:42 UTC, nkovacsx commented on components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/query/impl/VaultNamedQueryFactoryProvider.kt
> +        // TODO extra checks needed?
Yeah they do but not sure because we have fewer requirements in place. I mean if the class implements `VaultNamedQueryFactory` it's pretty much ok. Unless the `register` is not called but not sure if that's something we should check.

2023-03-10 14:55 UTC, lankydan approved these changes, later dismissed

2023-03-10 16:06 UTC, lankydan approved these changes, later dismissed

2023-03-10 16:08 UTC, ronanbrowne submitted a review, later dismissed
lgtm - build

2023-03-10 16:14 UTC, driessamyn requested changes

2023-03-10 16:14 UTC, driessamyn commented on processors/db-processor/build.gradle
> +    runtimeOnly project(':components:ledger:ledger-persistence')
This is already an implementation component. It has to be one or the other.

2023-03-10 16:35 UTC, lankydan approved these changes

2023-03-10 16:36 UTC, driessamyn approved these changes
Ok for packaging & DB

2023-03-10 16:43 UTC, ronanbrowne approved these changes

2023-03-10 16:59 UTC, merged