CORE-8338 Upgrade the flow worker to use Kryo 5.4.0
corda/corda-runtime-os pull request #3365
Opened 2023-03-13 16:41 UTC by mbrkic-r3

Upgrade to Kryo 5.4.0

2023-03-13 16:43 UTC, mbrkic-r3 commented on libs/serialization/serialization-kryo/src/main/kotlin/net/corda/kryoserialization/DefaultKryoCustomizer.kt
> -                addDefaultSerializer(Arrays.asList("").javaClass, ArraysAsListSerializer())
This should be already added: https://github.com/EsotericSoftware/kryo/blob/master/src/com/esotericsoftware/kryo/Kryo.java#L225

2023-03-13 16:43 UTC, mbrkic-r3 commented on libs/serialization/serialization-kryo/src/main/kotlin/net/corda/kryoserialization/DefaultKryoCustomizer.kt
> -                addDefaultSerializer(BitSet::class.java, BitSetSerializer())
This should be already added:
https://github.com/EsotericSoftware/kryo/blob/master/src/com/esotericsoftware/kryo/Kryo.java#L228

2023-03-13 16:45 UTC, mbrkic-r3 commented on libs/serialization/serialization-kryo/src/main/kotlin/net/corda/kryoserialization/DefaultKryoCustomizer.kt
> +                // Add external serializers
Moved to the top because default serializers are searched in the reverse order in which they are added

2023-03-13 17:30 UTC, mbrkic-r3 commented on libs/serialization/serialization-kryo/src/main/kotlin/net/corda/kryoserialization/DefaultKryoCustomizer.kt
> +                addDefaultSerializerAsFirst(NonSerializable::class.java, NonSerializableSerializer)
This serializer should be found first, which for version 5 means it should be added as the last. However, there is [additional logic](https://github.com/EsotericSoftware/kryo/blob/master/src/com/esotericsoftware/kryo/Kryo.java#L432) that checks whether type related to any of already registered serializers is assignable from this one (`NonSerializabe`) and in that case it will make this serializer (`NonSerializableSerializer`) lower priority. This means that if there is a serializer for specific class, although class is marked as `NonSerializabe`, it will be serialized.
Implementation below uses reflection to add `NonSerializableSerializer` at the first place, making it highest priority.
Alternative solutions are:
- Extending `Kryo` and overriding `getDefaultSerializer` to implement custom logic for choosing a serializer. Problem with this is that `Kryo` instance seems to be created by `Quasar`.
- Using annotations instead of `NonSerializable` interface (`@DefaultSerializer(NonSerializableSerializer::class`). This might make some components additionally dependent on `Kryo`.

2023-03-13 17:32 UTC, mbrkic-r3 commented on gradle.properties
> +kryoSerializerVersion = 0.45
This was copied from related `Quasar` PR but it actually won't help as the library doesn't support `Kryo` version 5

2023-03-13 20:45 UTC, chrisr3 reviewed
Given that this is only a _DRAFT_ PR... :wink:

2023-03-13 20:45 UTC, chrisr3 commented on gradle.properties
> +quasarVersion = 0.8.10_kryo5-SNAPSHOT
This is a _temporary_ Quasar version number.

2023-03-13 20:45 UTC, chrisr3 commented on libs/serialization/serialization-kryo/src/main/kotlin/net/corda/kryoserialization/DefaultKryoCustomizer.kt
> +                references = true
Do you need to set `references = true`? My understanding is that in Kryo 5.x, the `Kryo` object has no `ReferenceResolver` by default, and that:
```
val kryo = Kryo(MapReferenceResolver())
```
will set `references = true` automatically.

2023-03-13 20:45 UTC, chrisr3 commented on libs/serialization/serialization-kryo/src/main/kotlin/net/corda/kryoserialization/DefaultKryoCustomizer.kt
> +        }
There _must_ be a better solution here than using Java reflection like this to access private fields, and especially since this is _precisely_ the kind of reflection usage that modern JVMs are working towards making impossible.

The point here is presumably that we want Kryo to use our custom serializers that only throw exceptions for all instances of `NonSerializable` and `SpecificRecord`. So if we can no longer achieve that by inserting our serializers in a particular order, then why not filter the unwanted serializers out and so not register them in the first place?
```kotlin
private companion object {
    private val FORBIDDEN_TYPES = unmodifiableSet(setOf(NonSerializable::class.java, SpecificRecord::class.java))
}

// Serializers for more specific types have higher precedence, and
// so we cannot add serializers for extensions of forbidden types.
val externalSerializers = serializers.filterNot { serializer ->
    FORBIDDEN_TYPES.any { type -> type.isAssignableFrom(serializer.key) }
}.toSortedMap(compareBy(Class<*>::getName))

// Add external serializers
for ((clazz, serializer) in externalSerializers) {
    addDefaultSerializer(clazz, serializer)
}
```

2023-03-13 20:45 UTC, chrisr3 commented on gradle.properties
> +kryoSerializerVersion = 0.45
Although it was built against Kryo 5.0.0-RC1, and its OSGi metadata claims to support Kryo >= 5.0...?

2023-03-13 20:45 UTC, chrisr3 commented on libs/serialization/serialization-kryo/src/main/kotlin/net/corda/kryoserialization/DefaultKryoCustomizer.kt
> -                addDefaultSerializer(BitSet::class.java, BitSetSerializer())
Yes, Kryo 5 has _a_ serializer called  `BitSetSerializer`. How does Kryo's own serializer differ from the one from `kryo-serializers`?

2023-03-13 20:45 UTC, chrisr3 commented on libs/serialization/serialization-kryo/src/main/kotlin/net/corda/kryoserialization/DefaultKryoCustomizer.kt
> -                addDefaultSerializer(Arrays.asList("").javaClass, ArraysAsListSerializer())
Yes, Kryo has _a_ serializer called `ArraysAsListSerializer`. How does Kryo's own serializer differ from the `kryo-serializers` one?

2023-03-13 20:45 UTC, chrisr3 commented on libs/serialization/serialization-kryo/src/main/kotlin/net/corda/kryoserialization/DefaultKryoCustomizer.kt
> +                // Add external serializers
I don't think that's _quite_ true. If Kryo already has a serializer whose target type "is assignable" to a new serializer's own target type then the new serializer will be registered _after_ the existing one.

2023-03-14 08:46 UTC, mbrkic-r3 commented on libs/serialization/serialization-kryo/src/main/kotlin/net/corda/kryoserialization/DefaultKryoCustomizer.kt
> -                addDefaultSerializer(Arrays.asList("").javaClass, ArraysAsListSerializer())
I didn't look at implementations, maybe we need few tests just to make sure the one in Kryo can be used with all uses cases we have. In general I don't think it's really important if these are two different implementations as long as it does the job. As I understand, we also want to get rid of using `de.javakaffee.kryoserializers`, so we should use (port) implementation from there only if such serializer is missing in Kryo or has some serious issues.

2023-03-14 08:47 UTC, mbrkic-r3 commented on libs/serialization/serialization-kryo/src/main/kotlin/net/corda/kryoserialization/DefaultKryoCustomizer.kt
> -                addDefaultSerializer(BitSet::class.java, BitSetSerializer())
Similar to the comment above, I don't think it's so important how they differ, unless we find a serious issue. This one is simple though, so it's easy to compare. Kryo's serializer uses (`set.toLongArray()`) and then `output.writeLongs`, while the one from `de.javakaffee.kryoserializers` writes booleans using `output.writeBoolean(bitSet.get(i))`.

2023-03-14 08:50 UTC, mbrkic-r3 commented on libs/serialization/serialization-kryo/src/main/kotlin/net/corda/kryoserialization/DefaultKryoCustomizer.kt
> +                // Add external serializers
That's right and I've mentioned that in the comment below (but otherwise it's a reverse other, which is opposite to as it was in version 4)

2023-03-14 09:01 UTC, mbrkic-r3 commented on gradle.properties
> +kryoSerializerVersion = 0.45
According to [CORE-6290](https://r3-cev.atlassian.net/browse/CORE-6290) we are not going to use that. I'm not aware about specific reasons but my assumption was because it doesn't support version 5. [Website](https://github.com/magro/kryo-serializers) says it's a
> project that provides [kryo](https://github.com/EsotericSoftware/kryo) (v2, v3, v4) serializers

While it was built against 5.0.0-RC1, it might not work with [5.4.0](https://github.com/EsotericSoftware/kryo#kryo-versioning-and-upgrading):
> The minor version is increased if binary or source compatibility of the documented public API is broken.

2023-03-14 09:11 UTC, mbrkic-r3 commented on libs/serialization/serialization-kryo/src/main/kotlin/net/corda/kryoserialization/DefaultKryoCustomizer.kt
> +                references = true
In Kryo 4 references were [enabled by default](https://github.com/EsotericSoftware/kryo/wiki/Kryo-v4#references):
> By default, each appearance of an object in the graph after the first is stored as an integer ordinal. This allows multiple references to the same object and cyclic graphs to be serialized. This has a small amount of overhead and can be disabled to save space if it is not needed

While in Kryo 5 they are [disabled by default](https://github.com/EsotericSoftware/kryo#references):
> By default references are not enabled. This means if an object appears in an object graph multiple times, it will be written multiple times and will be deserialized as multiple, different objects. When references are disabled, circular references will cause serialization to fail.
...
MapReferenceResolver is used by default if a reference resolver is not specified. 

So this was added in order to have the same behaviour as before.

2023-03-14 09:13 UTC, chrisr3 commented on gradle.properties
> +kryoSerializerVersion = 0.45
I think [CORE-6290](https://r3-cev.atlassian.net/browse/CORE-6290) is stating an _ambition_ rather than a hard-and-fast requirement. Have you tried asking the Kryo maintainers what our recommended upgrade path should be?

2023-03-14 09:24 UTC, mbrkic-r3 commented on libs/serialization/serialization-kryo/src/main/kotlin/net/corda/kryoserialization/DefaultKryoCustomizer.kt
> +        }
Yes, I also don't like it (but reflection was already used in this class). It would be good to find some alternative solution.
I guess majority of classes will use default serializer (`FieldSerializer`), so I'm not sure that suggested approach would work (as it would have to be used for some classes but not for those that are marked as non serializable).

2023-03-14 10:01 UTC, chrisr3 commented on libs/serialization/serialization-kryo/src/main/kotlin/net/corda/kryoserialization/DefaultKryoCustomizer.kt
> +        }
The suggested approach works because it means there is only _one_ Kryo serializer for those types which are assignable to `NonSerializable`. As demonstrated by the corresponding unit test.

2023-03-14 10:11 UTC, mbrkic-r3 commented on libs/serialization/serialization-kryo/src/main/kotlin/net/corda/kryoserialization/DefaultKryoCustomizer.kt
> +        }
I'm not sure I understand what you mean, could you please provide the name of that unit test?

2023-03-14 11:11 UTC, chrisr3 commented on libs/serialization/serialization-kryo/src/main/kotlin/net/corda/kryoserialization/DefaultKryoCustomizer.kt
> +        }
> I'm not sure I understand what you mean, could you please provide the name of that unit test?

`net.corda.kyroserialization.KryoCheckpointSerializerTest`

Which demonstrates that filtering `NonSerializableTestClass.Serializer` out of the external serializers is an effective way of ensuring that Kryo still selects `NonSerializableSerializer` to serialize instances of `NonSerializableTestClass`.

2023-03-21 17:24 UTC, chrisr3 requested changes
Some of the `DefaultKryoCustomizer` serializer factories aren't quite right.

2023-03-21 17:24 UTC, chrisr3 commented on libs/serialization/serialization-kryo/src/main/kotlin/net/corda/kryoserialization/DefaultKryoCustomizer.kt
> +                kryo.setDefaultSerializer(defaultFactory)
As the Javadocs say:
```java
/** If the returned config settings are modified, {@link #updateFields()} must be called. */
public FieldSerializerConfig getFieldSerializerConfig () {
    return config;
}
```
In your case, it would be better to pass the configuration options via the `SerializerFactory` constructor.

2023-03-21 17:24 UTC, chrisr3 commented on libs/serialization/serialization-kryo/src/main/kotlin/net/corda/kryoserialization/DefaultKryoCustomizer.kt
> +                })
I don't believe these `isSupported()` implementations are correct because we would like these serializers to support everything which _is assignable_ to `Iterator` and `Throwable`. (Why would we want to serialize a _literal_ `Iterator` class?) But we already register these serializers against `Iterator.class` and `Throwable.class` anyway, which makes me think that `isSupported()` is for choosing _specific_ iterators and throwables instead. To support _all_ such instances, we would only need to return `true` here.

But I think both of these serializers should actually extend `BaseSerializerFactory` really:
```java
/** A serializer factory which always returns true for {@link #isSupported(Class)}. */
public abstract static class BaseSerializerFactory<T extends Serializer> implements SerializerFactory<T> {
    public boolean isSupported (Class type) {
        return true;
    }
}
```

2023-03-21 17:24 UTC, chrisr3 commented on libs/serialization/serialization-kryo/src/main/kotlin/net/corda/kryoserialization/DefaultKryoCustomizer.kt
> +                // Serializers for more specific types have higher precedence, and
Does registering the external serializers first make _any_ difference?

Can CorDapps register custom Kryo serializers for _specific_ types which override any of Corda's more generic ones?

2023-03-21 19:44 UTC, chrisr3 commented on libs/serialization/serialization-kryo/src/main/kotlin/net/corda/kryoserialization/DefaultKryoCustomizer.kt
> +                // Serializers for more specific types have higher precedence, and
Yes, I agree. However, I have now discovered that my example code is actually testing the `ObjectArraySerializer` and not the `CollectionSerializer` :facepalm:. It looks like _both_ of these default serializers have this optimisation, and will need overriding. Are there any others please?

2023-03-22 15:22 UTC, mbrkic-r3 commented on libs/serialization/serialization-kryo/src/main/kotlin/net/corda/kryoserialization/DefaultKryoCustomizer.kt
> +                // Serializers for more specific types have higher precedence, and
Order matters as the first serializer found in Kryo's internal list will be used. In version 4 adding a serializer would add it at the end of internal list, while in version 5, it's added to the beginning of the list, however, there are some exceptions to this, serializers for specific classes come before serializers for generic classes.

Assuming we have classes:
`class A`
`class B: A()`

Registering external serializers last:
```
addDefaultSerializer(A::class.java, PlatformSerializerA())
addDefaultSerializer(B::class.java, PlatformSerializerB())
addDefaultSerializer(A::class.java, AppSerializerA())
addDefaultSerializer(B::class.java, AppSerializerB())
```
will result with order:
```
1. PlatformSerializerB
2. AppSerializerB
3. PlatformSerializerA
4. AppSerializerA
```
While registering external serializers first:
```
addDefaultSerializer(A::class.java, AppSerializerA())
addDefaultSerializer(B::class.java, AppSerializerB())
addDefaultSerializer(A::class.java, PlatformSerializerA())
addDefaultSerializer(B::class.java, PlatformSerializerB())
```
will result with:
```
1. AppSerializerB
2. PlatformSerializerB
3. AppSerializerA
4. PlatformSerializerA
```

So if there is generic type (`A`) serializer registered by platform (`PlatformSerializerA`), app will override it for specific type (`B`) serializer (`AppSerializerB`) regardless of the order they are added. Is this a problem?

However, order makes a difference if there are serializers being added for the same type. Which order should we use for adding serializers?

2023-03-22 15:37 UTC, mbrkic-r3 commented on libs/serialization/serialization-kryo/src/main/kotlin/net/corda/kryoserialization/DefaultKryoCustomizer.kt
> +                kryo.setDefaultSerializer(defaultFactory)
fixed

2023-03-22 15:37 UTC, mbrkic-r3 commented on libs/serialization/serialization-kryo/src/main/kotlin/net/corda/kryoserialization/DefaultKryoCustomizer.kt
> +                })
fixed

2023-03-22 15:40 UTC, mbrkic-r3 commented on libs/serialization/serialization-kryo/src/main/kotlin/net/corda/kryoserialization/DefaultKryoCustomizer.kt
> +                addDefaultSerializerAsFirst(NonSerializable::class.java, NonSerializableSerializer)
This was refactored according to @chrisr3's suggestion to filter the unwanted serializers out and so not register them in the first place/

2023-03-22 15:46 UTC, mbrkic-r3 commented on libs/serialization/serialization-kryo/src/main/kotlin/net/corda/kryoserialization/DefaultKryoCustomizer.kt
> +        }
There is a test `serialization of an avro generated class throws an exception`, it was just missing `addDefaultSerializer(Externalizable::class.java, ExternalizableKryoSerializer<Externalizable>())`, which is performed by Quasar, in order to manifest the issue described here: https://r3-cev.atlassian.net/browse/CORE-8338?focusedCommentId=237038

2023-03-23 07:51 UTC, mbrkic-r3 commented on libs/serialization/serialization-kryo/src/main/kotlin/net/corda/kryoserialization/DefaultKryoCustomizer.kt
> -                addDefaultSerializer(Iterator::class.java) { kryo, type ->
Removed `IteratorSerializer` because it was causing NPE at `java.util.ArrayList$Itr.hasNext` and everything seems to work fine without it.

2023-03-23 07:55 UTC, mbrkic-r3 commented on libs/serialization/serialization-kryo/src/test/kotlin/net/corda/kryoserialization/KryoCheckpointSerializerTest.kt
> +
Added tests for serializing Iterators, [the same ones](https://github.com/corda/corda/pull/6176/files) that were originally created when `IteratorSerializer` was introduced. `IteratorSerializerTest` was removed as it could not reproduce the error even when `IteratorSerializer` was not used.

2023-03-23 09:03 UTC, chrisr3 commented on libs/serialization/serialization-kryo/src/main/kotlin/net/corda/kryoserialization/DefaultKryoCustomizer.kt
> -                addDefaultSerializer(Iterator::class.java) { kryo, type ->
I don't think removing `IteratorSerializer` is a good idea! There are things called "CorDapps" which might still need this, some of which are written by third parties...

2023-03-23 09:31 UTC, mbrkic-r3 commented on libs/serialization/serialization-kryo/src/main/kotlin/net/corda/kryoserialization/DefaultKryoCustomizer.kt
> -                addDefaultSerializer(Iterator::class.java) { kryo, type ->
This iterator will make CorDapps fail in the same way as it made CordApp in the smoke test fail with NPE mentioned above. As commented below, the test that was related to this serializer was passing even without serializer being used. Tests that were originally created when this serializer were added to the codebase and they are passing as well. So I cannot reproduce any issue when serializing iterators without this serializer, while using it causes issues.

2023-03-29 08:08 UTC, chrisr3 commented on gradle.properties
> +quasarVersion = 0.8.10_kryo5-SNAPSHOT
This PR needs to be using Quasar 0.9.0_r3-SNAPSHOT now.

2023-03-29 08:11 UTC, chrisr3 commented on libs/serialization/serialization-kryo/src/main/kotlin/net/corda/kryoserialization/DefaultKryoCustomizer.kt
> -                addDefaultSerializer(Iterator::class.java) { kryo, type ->
_How_ does this serializer cause an NPE? Does this NPE still occur after you've upgraded to Quasar 0.9.0_r3-SNAPSHOT?

2023-03-29 08:39 UTC, mbrkic-r3 commented on gradle.properties
> +quasarVersion = 0.8.10_kryo5-SNAPSHOT
updated

2023-03-29 08:46 UTC, mbrkic-r3 commented on libs/serialization/serialization-kryo/src/main/kotlin/net/corda/kryoserialization/DefaultKryoCustomizer.kt
> -                addDefaultSerializer(Iterator::class.java) { kryo, type ->
Here are failed test due to using that serializer: https://ci02.dev.r3.com/blue/organizations/jenkins/Corda5%2Fcorda-runtime-os-combined-worker-e2e-tests/detail/PR-3365/7/tests

Here is an example from workers' logs:
```kotlin
16:11:43.507 [single-threaded-scheduled-executor-1] WARN  net.corda.flow.fiber.FlowFiberImpl {client_id=3215707d-5d8e-4f91-9b27-8b09b04068b2, flow_id=2d4fc27c-aeb8-4e5d-9075-3eed3a7e29f5, session_event_id=828a4b42-9dc3-46cb-bdab-588a0861c2de, vnode_id=0CFCD4F0D6CD} - Flow failed
java.lang.NullPointerException: null
	at java.util.ArrayList$Itr.hasNext(ArrayList.java:992) ~[?:?]
	at net.cordapp.testing.smoketests.flow.RpcSmokeTestFlow.startSessions(RpcSmokeTestFlow.kt:513) ~[?:?]
	at net.cordapp.testing.smoketests.flow.RpcSmokeTestFlow.access$startSessions(RpcSmokeTestFlow.kt:33) ~[?:?]
	at net.cordapp.testing.smoketests.flow.RpcSmokeTestFlow$commandMap$3.invoke(RpcSmokeTestFlow.kt:44) ~[?:?]
	at net.cordapp.testing.smoketests.flow.RpcSmokeTestFlow$commandMap$3.invoke(RpcSmokeTestFlow.kt:44) ~[?:?]
	at net.cordapp.testing.smoketests.flow.RpcSmokeTestFlow.execute(RpcSmokeTestFlow.kt:452) ~[?:?]
	at net.cordapp.testing.smoketests.flow.RpcSmokeTestFlow.call(RpcSmokeTestFlow.kt:100) ~[?:?]
	at net.corda.flow.fiber.ClientStartedFlow.invoke(ClientStartedFlow.kt:14) ~[?:?]
	at net.corda.flow.fiber.FlowFiberImpl.runFlow(FlowFiberImpl.kt:99) ~[?:?]
	at net.corda.flow.fiber.FlowFiberImpl.run(FlowFiberImpl.kt:66) ~[?:?]
	at net.corda.flow.fiber.FlowFiberImpl.run(FlowFiberImpl.kt:23) ~[?:?]
	at co.paralleluniverse.fibers.Fiber.run1(Fiber.java:1165) ~[?:?]
	at co.paralleluniverse.fibers.Fiber.exec(Fiber.java:861) ~[?:?]
	at co.paralleluniverse.fibers.RunnableFiberTask.doExec(RunnableFiberTask.java:100) ~[?:?]
	at co.paralleluniverse.fibers.RunnableFiberTask.run(RunnableFiberTask.java:91) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at co.paralleluniverse.concurrent.util.ScheduledSingleThreadExecutor$ScheduledFutureTask.access$001(ScheduledSingleThreadExecutor.java:160) ~[?:?]
	at co.paralleluniverse.concurrent.util.ScheduledSingleThreadExecutor$ScheduledFutureTask.run(ScheduledSingleThreadExecutor.java:272) ~[?:?]
	at co.paralleluniverse.concurrent.util.ScheduledSingleThreadExecutor.work(ScheduledSingleThreadExecutor.java:119) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
```

I'll retest it with Quasar 0.9.0_r3-SNAPSHOT

2023-03-29 09:42 UTC, JamesHR3 reviewed
Quick question about generic vs specific serializers following on from Chris, otherwise looks good.

2023-03-29 09:42 UTC, JamesHR3 commented on libs/serialization/serialization-kryo/src/main/kotlin/net/corda/kryoserialization/DefaultKryoCustomizer.kt
> +                // Serializers for more specific types have higher precedence, and
Overriding a generic type could be a problem if it allows an app to break something like a public key serializer.

If we have no way around this here then it might be one to tackle in some follow up.

2023-03-29 10:34 UTC, mbrkic-r3 commented on libs/serialization/serialization-kryo/src/main/kotlin/net/corda/kryoserialization/DefaultKryoCustomizer.kt
> -                addDefaultSerializer(Iterator::class.java) { kryo, type ->
It's also failing with Quasar 0.9.0_r3-SNAPSHOT: https://ci02.dev.r3.com/blue/organizations/jenkins/Corda5%2Fcorda-runtime-os-e2e-tests/detail/PR-3503/2/tests

Added "original" `IteratorSerializer` tests are failing as well: https://ci02.dev.r3.com/blue/organizations/jenkins/Corda5%2Fcorda-runtime-os/detail/PR-3503/1/tests/

2023-03-29 11:11 UTC, chrisr3 commented on libs/serialization/serialization-kryo/src/main/kotlin/net/corda/kryoserialization/DefaultKryoCustomizer.kt
> -                addDefaultSerializer(Iterator::class.java) { kryo, type ->
Then please explain _why_ these tests are failing rather than just trying to shoot the messenger.

2023-03-29 11:17 UTC, mbrkic-r3 commented on libs/serialization/serialization-kryo/src/main/kotlin/net/corda/kryoserialization/DefaultKryoCustomizer.kt
> -                addDefaultSerializer(Iterator::class.java) { kryo, type ->
They were failing int the first build preventing to check whether flows in smoke tests will have the same issue so they were commented out (check commits and related builds in that PR).

What is the idea of forcing our own serializer that fails even the tests it was intended to solve, when Kryo version 5 can obviously serialize iterators without any of those issues?

2023-03-29 11:37 UTC, chrisr3 commented on libs/serialization/serialization-kryo/src/main/kotlin/net/corda/kryoserialization/DefaultKryoCustomizer.kt
> -                addDefaultSerializer(Iterator::class.java) { kryo, type ->
_And NPE is always a bug!_ What is that serializer doing to trigger an NPE? Can you prove that `IteratorSerializer` is _responsible_ for the NPE, rather than just tripping over an underlying and undiscovered problem in Kryo 5?

Why doesn't [this commit](https://github.com/corda/corda-runtime-os/pull/3410/commits/02436b327a09ba1e5f962e72c8278017557e6a2e) in PR #3410 also fail with NPEs?

2023-03-29 12:01 UTC, chrisr3 commented on libs/serialization/serialization-kryo/src/main/kotlin/net/corda/kryoserialization/DefaultKryoCustomizer.kt
> -                addDefaultSerializer(Iterator::class.java) { kryo, type ->
What happens when you configure the `CompatibleFieldSerializer` correctly?
```kotlin
val config = CompatibleFieldSerializerConfig().apply {
    ignoreSyntheticFields = false
    extendedFieldNames = true
}
return IteratorSerializer(type, CompatibleFieldSerializer(kryo, type, config))
```

2023-03-29 12:22 UTC, mbrkic-r3 commented on libs/serialization/serialization-kryo/src/main/kotlin/net/corda/kryoserialization/DefaultKryoCustomizer.kt
> +                // Serializers for more specific types have higher precedence, and
Should we implement this only for some types, that would be added to `FORBIDDEN_TYPES`, or should we prevent adding any external serializer that overrides existing ones (which might be a problem since we don't have access to already added serializers)?

2023-03-29 12:34 UTC, thiagoviana commented on libs/serialization/serialization-kryo/src/test/kotlin/net/corda/kryoserialization/KryoCheckpointSerializerTest.kt
> +
Since we are using Kryo, and the work is to upgrade it to version 5, and Kryo has added missing serializers that basically will make us not needing using our custom ones anymore, is there any reason for us to insist in not doing the proper upgrade and get the benefits of having everything in only one place? 

Why should we invest time investigating something that is no longer necessary, it's ready and working? Maybe we are missing something. Can you shed some light on this @chrisr3  ? We are always keen to learn.

Of course we can take a look at this later and learn more about the why, for the sake of knowledge. But it seems  that now we are running out of time, meaning, we might be losing an important deadline.

2023-03-29 13:00 UTC, JamesHR3 commented on libs/serialization/serialization-kryo/src/main/kotlin/net/corda/kryoserialization/DefaultKryoCustomizer.kt
> +                // Serializers for more specific types have higher precedence, and
I think we might have explicitly blocked serializing public keys with a custom serializer before, but everything else I think we just allow (from memory). So we could block serializers for more specific versions of that, and leave everything else for now.

2023-03-29 13:06 UTC, mbrkic-r3 commented on libs/serialization/serialization-kryo/src/main/kotlin/net/corda/kryoserialization/DefaultKryoCustomizer.kt
> -                addDefaultSerializer(Iterator::class.java) { kryo, type ->
This fixes issues with smoke tests: https://github.com/corda/corda-runtime-os/pull/3365/files#r1151856658 and also most of the "original" unit tests: https://ci02.dev.r3.com/blue/organizations/jenkins/Corda5%2Fcorda-runtime-os/detail/PR-3503/4/tests . Since we also have e.g. `LinkedHashMapIteratorSerializer`, I guess that failing test might be fixed if we add serializers in a different order.

But the question remains, why to use `IteratorSerializer` if Kryo 5 serializes iterators without any issue?

2023-03-29 13:31 UTC, mbrkic-r3 commented on libs/serialization/serialization-kryo/src/main/kotlin/net/corda/kryoserialization/DefaultKryoCustomizer.kt
> +                // Serializers for more specific types have higher precedence, and
I can't find the code that blocked serializing public keys, @chrisr3 are you aware of such code?

2023-03-29 14:21 UTC, chrisr3 commented on libs/serialization/serialization-kryo/src/main/kotlin/net/corda/kryoserialization/DefaultKryoCustomizer.kt
> -                addDefaultSerializer(Iterator::class.java) { kryo, type ->
> But the question remains, why to use IteratorSerializer if Kryo 5 serializes iterators without any issue?

To answer that question, you must discover why someone decided that they needed to write `IteratorSerializer` in the first place. Why did they bother, if the default serializers were enough?

2023-03-29 14:24 UTC, mbrkic-r3 commented on libs/serialization/serialization-kryo/src/main/kotlin/net/corda/kryoserialization/DefaultKryoCustomizer.kt
> -                addDefaultSerializer(Iterator::class.java) { kryo, type ->
Update: changing order of serializers fixed remaining tests that were failing.

2023-03-29 14:26 UTC, mbrkic-r3 commented on libs/serialization/serialization-kryo/src/main/kotlin/net/corda/kryoserialization/DefaultKryoCustomizer.kt
> -                addDefaultSerializer(Iterator::class.java) { kryo, type ->
> To answer that question, you must discover why someone decided that they needed to write IteratorSerializer in the first place. Why did they bother, if the default serializers were enough?

And I did exactly that. I took "original" tests, added them here and make sure that this error is not happening with Kryo 5.

2023-03-29 14:41 UTC, chrisr3 commented on libs/serialization/serialization-kryo/src/main/kotlin/net/corda/kryoserialization/DefaultKryoCustomizer.kt
> -                addDefaultSerializer(Iterator::class.java) { kryo, type ->
But _it appears_ that `IteratorSerializer` is intended to serialize "basic" iterators, but that it cannot handle iterators for `LinkedHashMap`, `LinkedHashSet`, and possibly `LinkedList`. Which would explain why:
- `LinkedHashMapIteratorSerializer`
- `LinkedHashMapEntrySerializer`
- `LinkedListItrSerializer`

were all written too. The order they are added to Kryo is also obviously crucial.

But someone _must_ have had a reason to implement **all** of these, possibly relating to detecting concurrent modifications. Unfortunately, the test coverage doesn't really explain anything, which means while the tests all passing is _necessary_, it is not _sufficient_.

2023-03-29 14:54 UTC, mbrkic-r3 commented on libs/serialization/serialization-kryo/src/main/kotlin/net/corda/kryoserialization/DefaultKryoCustomizer.kt
> -                addDefaultSerializer(Iterator::class.java) { kryo, type ->
@josephzunigadaly Do youi maybe remember wheter tests [here](https://github.com/corda/corda/pull/6176/files#diff-679e938473bd9ded65ea04819cdfb45e09f76a6db4fa3ec96356c58b5f1d3708) (and ported to this PR) were sufficient to reproduce the error due to which `IteratorSerializer` was created?

2023-03-29 15:37 UTC, chrisr3 commented on libs/serialization/serialization-kryo/src/test/kotlin/net/corda/kryoserialization/KryoCheckpointSerializerTest.kt
> +
@thiagoviana At the moment, the situation appears to be that one of the smoke tests was failing because an `ArrayList` iterator was throwing an NPE after Kryo deserialization, and that deleting our Kryo `IteratorSerializer` made that NPE "go away".

I saw no deeper explanation of the NPE than that. And it would now appear that the NPE was merely the result of our `IteratorSerializer` not configuring its `CompatibleFieldSerializer` correctly for Kryo 5.

Somebody obviously went to the trouble of writing our `IteratorSerializer`, as well as serializers for **3 other iterators**, and so AFAICT we need to be able to determine whether the original problem that someone needed to fix has now been resolved in Kryo 5. And if it has, then we can likely delete **4** serializers instead of just 1.

I have investigated other NPEs as part of this upgrade to Kryo 5, and have discovered one caused by an interaction between Quasar's Kryo enhancements and Kryo 5 _itself_. This particular NPE required _significant_ effort to fix, and could not be resolved by just throwing a test away.

2023-03-29 15:49 UTC, fowlerrr commented on libs/serialization/serialization-kryo/src/main/kotlin/net/corda/kryoserialization/DefaultKryoCustomizer.kt
> -                addDefaultSerializer(Iterator::class.java) { kryo, type ->
I wrote those.  And it was because (in C4) we had an issue where those serializers were pulling in the whole map just to capture the iterator.  And, IIRC, for _each_ iterator.  Though I don't recall the exact details.

In any event, the issue was to avoid a massive slowdown on serialization/checkpoint when there was an iterator present during a suspend.  I'll see if I can dig up the old ENT issue.

2023-03-29 15:49 UTC, fowlerrr commented on libs/serialization/serialization-kryo/src/main/kotlin/net/corda/kryoserialization/DefaultKryoCustomizer.kt
> -                addDefaultSerializer(Iterator::class.java) { kryo, type ->
But @chrisr3 is right.  This is about more than just "it didn't work before".

2023-03-29 15:52 UTC, fowlerrr commented on libs/serialization/serialization-kryo/src/main/kotlin/net/corda/kryoserialization/DefaultKryoCustomizer.kt
> -                addDefaultSerializer(Iterator::class.java) { kryo, type ->
I might be mixing up the problem here.  I specifically wrote the `Linked*IteratorSerializer`s. 

Here's the old PR: https://github.com/corda/enterprise/pull/2733

2023-03-29 15:55 UTC, mbrkic-r3 commented on libs/serialization/serialization-kryo/src/main/kotlin/net/corda/kryoserialization/DefaultKryoCustomizer.kt
> -                addDefaultSerializer(Iterator::class.java) { kryo, type ->
According to the PR linked in my comment above, issues was ENT-5141 and `IteratorSerializer` was not introduced together with `Linked*Serializer`s

2023-03-29 15:59 UTC, mbrkic-r3 commented on libs/serialization/serialization-kryo/src/test/kotlin/net/corda/kryoserialization/KryoCheckpointSerializerTest.kt
> +
As mentioned in the comments above, `IteratorSerializer` and `Linked*IteratorSerializers` were created at different times and for different reasons.

2023-03-29 16:01 UTC, chrisr3 commented on libs/serialization/serialization-kryo/src/test/kotlin/net/corda/kryoserialization/KryoCheckpointSerializerTest.kt
> +
According to @fowlerrr, these iterators:
- `LinkedHashMap$Entry`
- `LinkedList$ListItr`

were written to resolve [ENT-3856](https://github.com/corda/enterprise/pull/2733).

2023-03-29 16:29 UTC, chrisr3 commented on libs/serialization/serialization-kryo/src/test/kotlin/net/corda/kryoserialization/KryoCheckpointSerializerTest.kt
> +
> As mentioned in the comments above, `IteratorSerializer` and `Linked*IteratorSerializers` were created at different times and for different reasons.

Yes, thank you @fowlerrr for taking those few minutes to investigate.

2023-03-30 10:54 UTC, mbrkic-r3 commented on libs/serialization/serialization-kryo/src/main/kotlin/net/corda/kryoserialization/DefaultKryoCustomizer.kt
> -                addDefaultSerializer(Iterator::class.java) { kryo, type ->
`IteratorSerializer` brought back as there was a test case foiund (added) that fails with Kryo 5 default serializers.

2023-03-30 10:55 UTC, mbrkic-r3 commented on libs/serialization/serialization-kryo/src/main/kotlin/net/corda/kryoserialization/DefaultKryoCustomizer.kt
> +                // Serializers for more specific types have higher precedence, and
In Corda 4 `PrivateKeySerializer` was registered for several classes: [https://github.com/corda/corda/blob/10aaedc9fc82ba787d46e51ffbc6caf511234297/node-[…]da/nodeapi/internal/serialization/kryo/DefaultKryoCustomizer.kt](https://github.com/corda/corda/blob/10aaedc9fc82ba787d46e51ffbc6caf511234297/node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/kryo/DefaultKryoCustomizer.kt#L111)
however, looking at it's implementation, it didn't prevent anything: [https://github.com/corda/corda/blob/10aaedc9fc82ba787d46e51ffbc6caf511234297/node-[…]in/kotlin/net/corda/nodeapi/internal/serialization/kryo/Kryo.kt](https://github.com/corda/corda/blob/10aaedc9fc82ba787d46e51ffbc6caf511234297/node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/kryo/Kryo.kt#L289)

2023-03-30 10:56 UTC, mbrkic-r3 commented on libs/serialization/serialization-kryo/src/main/kotlin/net/corda/kryoserialization/DefaultKryoCustomizer.kt
> +                // Serializers for more specific types have higher precedence, and
@mnesbit commented via slack:
> maybe we don't worry about it for now seeing as C4 had Kryo allow it

2023-03-30 10:57 UTC, chrisr3 reviewed
If we're already customising our `Kryo` by invoking `DefaultKryoCustomizer.customize()` then the tests shouldn't need to repeat any of those customisations. Specifically,
```
isRegistrationRequired = false
```
If someone were to remove this setting from `customize()` then the code would break, but many of these tests would still pass. That doesn't sound like a Good Thing :thinking:.

2023-03-30 10:57 UTC, chrisr3 commented on libs/serialization/serialization-kryo/src/test/kotlin/net/corda/kryoserialization/KryoCheckpointSerializerTest.kt
> +                Kryo(CordaClassResolver(sandboxGroup), MapReferenceResolver()).apply { isRegistrationRequired = false },
You don't need to set `isRegistrationRequired = false` because this is done by `customize()`.

2023-03-30 10:57 UTC, chrisr3 commented on libs/serialization/serialization-kryo/src/test/kotlin/net/corda/kryoserialization/KryoCheckpointSerializerTest.kt
> +                        isRegistrationRequired = false
`isRegistrationRequired = false` is set by `customize()`.

2023-03-30 10:57 UTC, chrisr3 commented on libs/serialization/serialization-kryo/src/test/kotlin/net/corda/kryoserialization/serializers/SingletonSerializeAsTokenSerializerTest.kt
> +                Kryo(CordaClassResolver(sandboxGroup), MapReferenceResolver()).apply { isRegistrationRequired = false },
`isRegistrationRequired = false` is already set by `customize()`.

2023-03-30 10:57 UTC, chrisr3 commented on libs/serialization/serialization-kryo/src/test/kotlin/net/corda/kryoserialization/serializers/SingletonSerializeAsTokenSerializerTest.kt
> +                Kryo(CordaClassResolver(sandboxGroup), MapReferenceResolver()).apply { isRegistrationRequired = false },
`isRegistrationRequired = false` is already set by `customize()`.

2023-03-30 10:57 UTC, chrisr3 commented on testing/kryo-serialization-testkit/src/main/kotlin/net/corda/kryoserialization/testkit/KryoTestUtils.kt
> +                kryo.isRegistrationRequired = false
`KryoCheckpointSerializerBuilderImpl` invokes `DefaultKryoCustomizer.customize()`, and so you shouldn't need to set `isRegistrationRequired = false` here.

2023-03-30 11:02 UTC, mnesbit commented on libs/serialization/serialization-kryo/src/main/kotlin/net/corda/kryoserialization/DefaultKryoCustomizer.kt
> +                // Serializers for more specific types have higher precedence, and
PublicKeys definitely always was fine to serialize. PrivateKeys actually seems to be allowed in C4, but not on AMQP, so I think we allow that too

2023-03-30 12:39 UTC, JamesHR3 commented on libs/serialization/serialization-kryo/src/main/kotlin/net/corda/kryoserialization/DefaultKryoCustomizer.kt
> +                // Serializers for more specific types have higher precedence, and
Ok, that's fine. Let's leave it for now in that case.

2023-03-30 12:39 UTC, JamesHR3 approved these changes, later dismissed
I think assuming Chris is comfortable with this we're good.

2023-03-30 12:43 UTC, mbrkic-r3 commented on libs/serialization/serialization-kryo/src/test/kotlin/net/corda/kryoserialization/KryoCheckpointSerializerTest.kt
> +                Kryo(CordaClassResolver(sandboxGroup), MapReferenceResolver()).apply { isRegistrationRequired = false },
fixed

2023-03-30 12:43 UTC, mbrkic-r3 commented on libs/serialization/serialization-kryo/src/test/kotlin/net/corda/kryoserialization/KryoCheckpointSerializerTest.kt
> +                        isRegistrationRequired = false
fixed

2023-03-30 12:43 UTC, mbrkic-r3 commented on libs/serialization/serialization-kryo/src/test/kotlin/net/corda/kryoserialization/serializers/SingletonSerializeAsTokenSerializerTest.kt
> +                Kryo(CordaClassResolver(sandboxGroup), MapReferenceResolver()).apply { isRegistrationRequired = false },
fixed

2023-03-30 12:43 UTC, mbrkic-r3 commented on testing/kryo-serialization-testkit/src/main/kotlin/net/corda/kryoserialization/testkit/KryoTestUtils.kt
> +                kryo.isRegistrationRequired = false
fixed

2023-03-30 14:25 UTC, mbrkic-r3 commented on libs/serialization/serialization-kryo/src/test/kotlin/net/corda/kryoserialization/serializers/SingletonSerializeAsTokenSerializerTest.kt
> +                Kryo(CordaClassResolver(sandboxGroup), MapReferenceResolver()).apply { isRegistrationRequired = false },
fixed

2023-03-30 14:32 UTC, JamesHR3 approved these changes

2023-03-30 14:38 UTC, chrisr3 approved these changes
LGTM

2023-03-31 08:07 UTC, driessamyn approved these changes
LGTM

2023-03-31 08:35 UTC, merged