CORE-11651 - Rename metrics tags to conform to the micrometer guidelines.
corda/corda-runtime-os pull request #3367
Opened 2023-03-14 10:12 UTC by driessamyn

Some of our metrics tag names do not follow the convention stated on the [MicroMeter documentation](https://micrometer.io/docs/concepts#_naming_meters). 

This PR renames them.

2023-03-14 10:25 UTC, davidcurrie requested changes

2023-03-14 10:25 UTC, davidcurrie commented on libs/metrics/src/main/kotlin/net/corda/metrics/CordaMetrics.kt
> +        // NOTE: please ensure the metric names adhere to the convensions described on https://micrometer.io/docs/concepts#_naming_meters
```suggestion
        // NOTE: please ensure the metric names adhere to the conventions described on https://micrometer.io/docs/concepts#_naming_meters
```

2023-03-14 10:25 UTC, davidcurrie commented on libs/metrics/src/main/kotlin/net/corda/metrics/CordaMetrics.kt
> +        OperationStatus("status"),
why the short names for these three?

2023-03-14 13:56 UTC, driessamyn commented on libs/metrics/src/main/kotlin/net/corda/metrics/CordaMetrics.kt
> +        OperationStatus("status"),
I just thought the what the id or status was for would be obvious from the context and the short form is maybe more readable. 
But happy to change this back, maybe @LWogan has a view, I think he introduced these.

2023-03-14 14:07 UTC, davidcurrie commented on libs/metrics/src/main/kotlin/net/corda/metrics/CordaMetrics.kt
> +        OperationStatus("status"),
It was a genuine question as I can see benefits either way. As you say, given the context, the short names are undoubtedly preferable. Are there scenarios though where you might use these same tags (i.e. the same values) but where the meaning may not be clear? If so, it would be preferable to use the same tag name in both places. I may just be overthinking this though!

2023-03-14 14:11 UTC, driessamyn commented on libs/metrics/src/main/kotlin/net/corda/metrics/CordaMetrics.kt
> +        OperationStatus("status"),
> would be preferable to use the same tag name in both places. I may just be overthinking this though!

I think it would even just from a ux point of view as it's less terms to be familiar with.

I didn't change the Enum name as I think the full context there is probably useful from a code perspective.

2023-03-15 09:12 UTC, davidcurrie approved these changes

2023-03-15 10:03 UTC, merged