CORE-11215 Changed emptySet() to null
corda/corda-runtime-os pull request #3378
Opened 2023-03-15 15:21 UTC by Cap-j

2023-03-15 15:29 UTC, pmck91 reviewed
LGTM 🙂

2023-03-15 15:42 UTC, fowlerrr requested changes
Could you pop the test in too?  Just to make it more complete

2023-03-21 14:08 UTC, fowlerrr submitted a review, later dismissed

2023-03-23 15:14 UTC, pmck91 approved these changes
LGTM :)

2023-03-23 15:14 UTC, merged