CORE-9981
corda/corda-runtime-os pull request #3397
Opened 2023-03-16 15:51 UTC by pmck91

Ledger needs access to the currently running CPI’s information to be able to save it into the metadata of transactions and digital signatures. (name, version, signerSummaryHash, fileChecksum)
Ideally this should be populated into the context of the flow when the flow gets started and made accessible in the flow.

2023-03-16 16:10 UTC, LWogan reviewed
The location of the changes and the values set make sense to me.

2023-03-16 16:10 UTC, LWogan commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/runner/impl/FlowRunnerImpl.kt
> +                    contextProperties.put("corda.cpiName", metadata.cpiId.name)
I don't think we can use KeyValuePairList like this. Im new enough to it myself but I think you need to build 
KeyValuePair objects and add them to a list "List<.KeyValuePair> items;" which is a field in KeyValuePairList. The put() method used here is some method inherited by some avro super type

Simon added a corda helper class to make life easier called KeyValueStore which has an api closer to a Map and has a .avro method to convert to a KeyValuePairList. Example::
https://github.com/corda/corda-runtime-os/blob/65e55b30bdb85e32f3b362b6d5fadd20ca0604da/components/flow/flow-service/src/integrationTest/kotlin/net/corda/flow/testing/context/FlowServiceTestContext.kt#L267

2023-03-16 16:10 UTC, LWogan commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/runner/impl/FlowRunnerImpl.kt
> +                    contextProperties.put("corda.cpiName", metadata.cpiId.name)
We should probably store the keys in a constants file somewhere accessible by  flow code and flow-engine code..... maybe in the flow-api project, net.corda.flow.state package, not sure.

2023-03-23 10:38 UTC, simon-johnson-r3 requested changes

2023-03-23 10:38 UTC, simon-johnson-r3 commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/runner/impl/FlowRunnerImpl.kt
> +            if (it == null) contextProperties
This null check on `it` is not so Kotlin like, it would be better as:
```
return virtualNodeInfoReadService.get(holdingIdentity)?.let {
...
} ?: contextProperties
```
Then you don't need the double return in the let, or the one on line 147, or the return type so I think:
```
private fun getPropertiesWithCpiMetadata(
        ...
    ) = virtualNodeInfoReadService.get(holdingIdentity)?.let {
          KeyValueStore().apply {
               ...
          }.avro
        } ?: contextProperties
```
would do it, and then you might be able to remove the @Suppress too

2023-03-23 10:38 UTC, simon-johnson-r3 commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/runner/impl/FlowRunnerImpl.kt
> +                        contextProperties.items.forEach { prop ->
should this part about contextProperties be out of the `cpiInfoReadService.get(it.cpiIdentifier)?.let` ? Otherwise you'll lose them unnecessarily if that is null.

2023-03-23 10:38 UTC, simon-johnson-r3 commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/flow/FlowTests.kt
> +        assertThat(result.flowResult).contains(applicationCpiName)
It feels like the two ends of this test don't quite meet up. You could output the data from the flow as JSON and the parse that in here quite easily. If you didn't want to check exact values then you could check they were populated with something at least.

Or you could just output the application name as that's all you check here.

I guess you output the full set because it helps with manual testing, but I think there should be some match up between the automated test and the smoke test output. Future maintainers might be wondering what their responsibility is if new fields are added.

2023-03-23 10:38 UTC, simon-johnson-r3 commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/runner/impl/FlowRunnerImpl.kt
> +        val remotePlatformProperties =
Are these really the remote flow properties, you appear to pass the holding Id of the flow about to be executed? Is remote implying counterparty here?

Note that `remoteToLocalContextMapper` and the use of its return type is quite basic at the moment, it uses all platform properties as both current and counterparty context because they didn't differ at the point that method was written. The method was split out in order to make this logic modifiable at a later date.

At line 106 `localContext.counterpartySessionProperties` you'll basically pass `remotePlatformProperties` as counterparty session properties and I don't think that is your intent necessarily.

The intent when this was written was the flow context would eventually contain not just the current flow context, but also the context of the counterparty that initiated you. But that is not yet implemented because it is only now in this PR that flow context gets some of that information which differs across the 2 flows. This is probably the time to mull over and implement how both of these sets of context are exposed to the cordapp developer. Might be worth checking with @mnesbit what expectations are.

2023-03-27 14:20 UTC, mnesbit commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/runner/impl/FlowRunnerImpl.kt
> +        val remotePlatformProperties =
My intent was that in a flow corda.platformVersion and corda.cpiVersion (or whatever name we settled on) and similar platform properties are always of local system. In an initiated flow we would send across the platform+user properties from initiator. We would start forming the context properties for initiated flow. The initiator platform properties would be renamed from corda.xxx to corda.initiated.xxx (we don't have to preserve more than one level in this i.e. don't send from initiator any corda.initiator items). The local platform properties would be written into context as normal (possibly squashing any unrescued initiator values). The user properties should be copied over as as, so that they continue to be available in initiated flow as they were to initiator.

2023-03-28 11:59 UTC, pmck91 commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/runner/impl/FlowRunnerImpl.kt
> +        val remotePlatformProperties =
thanks for clearing that up! What Ill do is copy over the initiator details and rename them and place them in the remotePlatformContextProperties, I can do this in [remoteToLocalContextMapper](https://github.com/corda/corda-runtime-os/blob/85526d0e5131ae707cffd73db7a74ea34b4ea0ec/components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/runner/impl/RemoteToLocalContextMapper.kt), then I can fill in the others as normal into platformProperties?

2023-03-28 16:22 UTC, mnesbit commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/runner/impl/RemoteToLocalContextMapper.kt
> +        if (!kvp.key.contains("corda.initiator")) {
use startsWith

2023-03-28 16:24 UTC, mnesbit commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/runner/impl/RemoteToLocalContextMapper.kt
> +    val initiatorPlatformContextProperties = renameInitiatorProps(remotePlatformContextProperties)
Where do we set the local platform properties? Shouldn't we do that in this function too?

2023-03-29 09:02 UTC, pmck91 commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/runner/impl/RemoteToLocalContextMapper.kt
> +    val initiatorPlatformContextProperties = renameInitiatorProps(remotePlatformContextProperties)
they're set later after the mapping, back in the flowRunnerImpl

2023-03-29 13:15 UTC, simon-johnson-r3 approved these changes, later dismissed

2023-03-30 14:45 UTC, ronanbrowne approved these changes
lgtm (build change)

2023-03-30 14:48 UTC, merged