CORE-10420 Changes to FlowMapper
corda/corda-runtime-os pull request #3442
Opened 2023-03-22 09:48 UTC by szymonsztuka

WIP

2023-03-22 17:23 UTC, jmacmahonr3 approved these changes
One comment but not blocking 
Looks grand

2023-03-22 17:23 UTC, jmacmahonr3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/filter/InteropP2PFilterProcessor.kt
> +            authMessage !is AuthenticatedMessage ||
do we need to add another todo here ?

2023-03-22 17:36 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/filter/InteropP2PFilterProcessor.kt
> +            authMessage !is AuthenticatedMessage ||
no this should be fine, we expecting AuthenticatedMessages  (even establishing a session, like SessionInit message(which you can consider as not authenticated yet) is  also wrapped into AuthenticatedMessage.

2023-03-24 11:29 UTC, yarivus reviewed
see comment

2023-03-24 11:29 UTC, yarivus commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropService.kt
> +//import net.corda.schema.configuration.ConfigKeys.FLOW_CONFIG
remove commented out code

2023-03-24 13:29 UTC, SaurabhR3 requested changes

2023-03-24 13:29 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
> +//import net.corda.schema.configuration.FlowConfig
Unused/commented import

2023-03-24 13:29 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
> +import java.util.*
Better to add specific import than * for single UUID

2023-03-24 13:29 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
> +            }
Why are you not applying deserialiser to payload if `sessionEvent.payload` is type `SessionData`? Which component is going to set the InteropMessage as payload in SessionData?

2023-03-24 13:29 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
> +                logger.info("Pass-through event ${sessionEvent::class.java} without FacadeRequest")
What would be the implication of this log?

2023-03-24 13:29 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
> +                destinationIdentity,
I believe This will be real identity coming from flow processor, it has to be converted to Alias before setting up to header for P2P Out topic.

2023-03-24 13:58 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
> +                logger.info("Pass-through event ${sessionEvent::class.java} without FacadeRequest")
The log statement in the logs.

2023-03-24 13:59 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
> +            }
The payload types of SessionInit is different from the payload's type of SessionData.
_Which component is going to set the InteropMessage as payload in SessionData?_ our handler in FlowProcessor, see Alex PR.

2023-03-24 14:01 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
> +                destinationIdentity,
Yes this is part of other tickets

2023-03-24 14:01 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropService.kt
> +//import net.corda.schema.configuration.ConfigKeys.FLOW_CONFIG
addressed in https://github.com/corda/corda-runtime-os/pull/3442/commits/e8fda0c3521a91c70fe56cdf94e24ff29894a693

2023-03-24 14:01 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
> +//import net.corda.schema.configuration.FlowConfig
addressed in https://github.com/corda/corda-runtime-os/pull/3442/commits/e8fda0c3521a91c70fe56cdf94e24ff29894a693

2023-03-24 14:02 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
> +import java.util.*
Fixed in https://github.com/corda/corda-runtime-os/pull/3442/commits/e8fda0c3521a91c70fe56cdf94e24ff29894a693

2023-03-24 16:24 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
> +                logger.info("Pass-through event ${sessionEvent::class.java} without FacadeRequest")
There are messages of Session protocol which need to be passed but we don't interpret them in InteropProcessor, like e.g. SessionClose, at least this is the current understanding, hence open-ended way of passing them and not suppressing,.

2023-03-28 13:34 UTC, yarivus approved these changes
LGTM

2023-03-28 14:38 UTC, ac101m reviewed
A few minor comments

2023-03-28 14:38 UTC, ac101m commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
> +                logger.info("Pass-through event ${sessionEvent::class.java} without FacadeRequest")
I think this is likely to make the logs quite noisy, not sure we need logging here. At very least it should be `log.trace()` rather than info! 

(unless you feel it's still required for debugging)

2023-03-28 14:38 UTC, ac101m commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/filter/InteropP2PFilterService.kt
> +     */
This comment needs updating (assuming you copied this code from the existing p2p filter), ditto for any other similar occurrences.

2023-03-28 14:38 UTC, ac101m commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/HardcodedInteropMemberRegistrationService.kt
> +                    )
Not sure if it's just github, but the indentation here seems a little messed up.

2023-03-28 14:38 UTC, ac101m commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/HardcodedInteropMemberRegistrationService.kt
>              )
More goofy indentation

2023-03-28 14:38 UTC, ac101m commented on libs/flows/flow-mapper-impl/src/main/kotlin/net/corda/flow/mapper/impl/executor/SessionEventExecutor.kt
> +    private val outputTopic = getSessionEventOutputTopic(messageDirection, sessionEvent)
The session event object already contains message direction. I recommend either just passing the session event, or passing messageDirection and isInterop separately.

2023-03-28 14:38 UTC, ac101m commented on libs/flows/flow-mapper-impl/src/main/kotlin/net/corda/flow/mapper/impl/executor/SessionInitExecutor.kt
> +    private val outputTopic = getSessionEventOutputTopic(messageDirection, sessionEvent)
ditto

2023-03-28 15:27 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
> +                logger.info("Pass-through event ${sessionEvent::class.java} without FacadeRequest")
yeah, it's temporary for debugging, also we already filtering INTEROP messages only

2023-03-28 15:43 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
> +                logger.info("Pass-through event ${sessionEvent::class.java} without FacadeRequest")
As this log is under INBOUND request processing, which means it always should have facadeRequest object populated. And if it is null which means, client has not set all data and this needs to be communicated back to caller. I think it should be the `error`.

2023-03-28 16:12 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
> +                logger.info("Pass-through event ${sessionEvent::class.java} without FacadeRequest")
Not really the current P2P  Session protocol can trigger other messages e.g. SessionClose, SessionConfirmation, SessionAck, which doesn't invoke new flow/has the traditional request. We probably will address the Session protocol in the near future, on it's own which may simplify this code/eliminate pas through.

2023-03-28 16:20 UTC, SaurabhR3 requested changes

2023-03-28 16:20 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
>      private val config: SmartConfig,
It may not be your changes but unused constructer param `lifecycleCoordinatorFactory `, `subscriptionFactory ` and `config `

2023-03-28 16:20 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
> +            )
The above code will not return the RealHoldingIdentity. It will return the same destinationAlias identity.
`identityMappingCache` contains both Real and Alias identities, In order to get the real identity we need to have real holding identity x500name and that is fetched in method `getRealHoldingIdentityFromAliasMapping`

2023-03-28 16:20 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/filter/InteropP2PFilterProcessor.kt
> +    }
Method name can be changed to `processInteropMessage()` or something more meaningful.

2023-03-28 16:20 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/filter/InteropP2PFilterProcessor.kt
> +        }
Why do we need to toggle session?

2023-03-28 16:20 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/HardcodedInteropMemberRegistrationService.kt
>              )
And many commented lines

2023-03-28 16:29 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
>      private val config: SmartConfig,
Exactly, I don't want to produce even a bigger diff in this PR so I left them.

2023-03-28 16:42 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
> +            )
This code added in CORE-10427 never really worked, hence the TODO just above to revisit it. I've added better TODO description in 7417f41

2023-03-28 16:42 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/filter/InteropP2PFilterProcessor.kt
> +    }
Done 7417f41

2023-03-28 16:44 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/filter/InteropP2PFilterProcessor.kt
> +        }
As the same session object is created and use by both parties (exchange), what is "initiating" for you it "initiated" for your adversary, so for inbound you need to do a flip (more or less, we follow what is in the same code for P2PFlowFilter).

2023-03-28 16:46 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/HardcodedInteropMemberRegistrationService.kt
>              )
The commented code means it's not used but it's still important to carry some knowledge, which may be soon reused.

2023-03-28 17:08 UTC, szymonsztuka commented on libs/flows/flow-mapper-impl/src/main/kotlin/net/corda/flow/mapper/impl/executor/SessionEventExecutor.kt
> +    private val outputTopic = getSessionEventOutputTopic(messageDirection, sessionEvent)
Fixed in 7417f41 and 1b8151107

2023-03-28 17:08 UTC, szymonsztuka commented on libs/flows/flow-mapper-impl/src/main/kotlin/net/corda/flow/mapper/impl/executor/SessionInitExecutor.kt
> +    private val outputTopic = getSessionEventOutputTopic(messageDirection, sessionEvent)
Fixed in 7417f41 and 1b8151107

2023-03-28 17:08 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/HardcodedInteropMemberRegistrationService.kt
> +                    )
Fixed in 7417f41.

2023-03-28 17:09 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/filter/InteropP2PFilterService.kt
> +     */
Fixed in 7417f41.

2023-03-28 19:13 UTC, yarivus reviewed
LGTM - but pending comments

2023-03-29 09:21 UTC, yarivus reviewed
Looks good

2023-03-29 10:35 UTC, SaurabhR3 approved these changes

2023-03-29 10:38 UTC, ac101m approved these changes
LGTM

2023-03-29 12:14 UTC, merged

2023-03-29 14:09 UTC, yarivus commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropService.kt
> +//import net.corda.schema.configuration.ConfigKeys.FLOW_CONFIG
@szymonsztuka - please resolve comments before merging PRs

2023-03-29 14:17 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropService.kt
> +//import net.corda.schema.configuration.ConfigKeys.FLOW_CONFIG
This code is intentional left commented out, there is a TODO the line above (you are commenting outdated file)