CORE-11739: Change Helm chart to use custom TLS certificate for REST
corda/corda-runtime-os pull request #3456
Opened 2023-03-23 16:26 UTC by vkolomeyko

2023-03-27 13:49 UTC, vkolomeyko commented on libs/rest/ssl-cert-read-impl/src/main/kotlin/net/corda/rest/ssl/impl/SslCertReadServiceImpl.kt
> +            if (pemObject is PEMKeyPair) {
This was necessary as Helm's `genSignedCert` produces `KeyPair` when `$cert.Key` is used.

2023-03-27 13:50 UTC, vkolomeyko commented on charts/corda-lib/templates/_worker.tpl
> +          - "-rtls.crt.path=/rest/tls/tls.crt"
The "meat" of the change where new arguments are passed to the image at start-up.

2023-03-27 14:31 UTC, vkolomeyko commented on charts/corda/values.yaml
> +  bootstrapServers: "change-me-kafka:9092"
Having an empty string was violating constrains for this field.

2023-03-27 21:23 UTC, davidcurrie requested changes

2023-03-27 21:23 UTC, davidcurrie commented on charts/corda-lib/templates/_helpers.tpl
> +{{ .Values.workers.rest.tls.ca.valueFrom.secretKeyRef.key | default "ca" }}
Defacto key names for these in k8s would be `tls.crt`, `tls.key`, and `ca.crt`. (The first two, at least, are what you get when you create a Kubernetes secret of type `tls`.)

2023-03-27 21:23 UTC, davidcurrie commented on charts/corda-lib/templates/_helpers.tpl
> +{{ .Values.workers.rest.tls.crt.valueFrom.secretKeyRef.name | default (printf "%s-rest-tls" (include "corda.fullname" .)) }}
At least as the configuration currently stands, you could have different user-provided secret names for each of the three files.

2023-03-27 21:23 UTC, davidcurrie commented on charts/corda-lib/templates/_worker.tpl
> +            secretName: {{ include "corda.restTlsSecretName" $ | quote }}
As above, these files could be in three different secrets.

2023-03-27 21:23 UTC, davidcurrie commented on charts/corda/templates/secrets.yaml
> +{{- $interCert := genSignedCert "REST Worker Intermediary Cert" nil nil 365 $ca }}
What are we gaining from having an intermediate certificate here when we put the root certificate in the chain anyway?

2023-03-27 21:23 UTC, davidcurrie commented on charts/corda/templates/secrets.yaml
> +{{- $altNames := list ( printf "%s.c5.r3.com" .Release.Namespace ) ( printf "%s.%s.svc" $restWorkerName .Release.Namespace ) "localhost" }}
What's the purpose of the `c5.r3.com` domain here? It's probably worth including the `%s` and `%s.%s` options here and maybe also giving them the option of specifying the cluster domain name as well (usually `cluster.local` by default but is often configurable). I think it tends to divide opinion but I would not include `localhost` in this list.

2023-03-27 21:23 UTC, davidcurrie commented on charts/corda/templates/secrets.yaml
> +{{- $restWorkerName := "rest-worker" }}
This should be the service name (currently embedded as `$workerName` in `corda.worker` so would need extracting into its own function if this stays here).

2023-03-27 21:23 UTC, davidcurrie commented on charts/corda/templates/secrets.yaml
> +{{- $cert := genSignedCert $restWorkerName (list "127.0.0.1") $altNames 365 $interCert }}
I'd probably just leave the list of IPs as `nil` as this is not a helpful IP to use.

2023-03-27 21:23 UTC, davidcurrie commented on charts/corda/values.yaml
> +  bootstrapServers: "change-me-kafka:9092"
That's deliberate - it means that the user has to provide a value before they can perform an install.

2023-03-27 21:23 UTC, davidcurrie commented on charts/corda/values.schema.json
> +                                            "$ref": "#/$defs/config"
the config schema supports both `value` and `valueFrom` whereas your implementation does not

2023-03-27 21:23 UTC, davidcurrie commented on charts/corda/values.yaml
> +            key: ""
I'm inclined to think that this pattern has outlived its usefulness here. When specifying a username and password it was possible that you might want to provide the username as a value and the password via a secret. I'm not convinced that it's useful to be able to specify the certificates/key in different secrets here. I'm not even sure whether, given there is a standard TLS secret format, it's useful to be able to override the key names. Perhaps we should just have a `tlsSecretName` field and be done with it?! I'll sleep on that one...

2023-03-27 21:23 UTC, davidcurrie commented on charts/corda/templates/workers.yaml
> +  ( dict "httpPort" 8888 "restTlsSecret" true )
A better abstraction here would be to use `additionalWorkArgs` to pass the three extra parameters. I'd then just have the generic worker function look for the existence of a `tls` field in the values to see whether it should mount a secret (and drop the `rest` from the mount location).

2023-03-27 21:23 UTC, davidcurrie commented on charts/corda/templates/secrets.yaml
> +{{- $restWorkerName := "rest-worker" }}
I'd push all of this into `secrets.yaml` and make a generic `corda.tlsSecret` function.

2023-03-27 21:23 UTC, davidcurrie commented on charts/corda/templates/secrets.yaml
> +{{- $ca := genCA "REST Worker Certification Authority" 1000 }}
Is it worth having something in here that makes it clear that this is self-signed?

2023-03-28 09:28 UTC, vkolomeyko commented on charts/corda/values.yaml
> +  bootstrapServers: "change-me-kafka:9092"
Sure - I will undo this change.

2023-03-28 09:29 UTC, vkolomeyko commented on charts/corda-lib/templates/_helpers.tpl
> +{{ .Values.workers.rest.tls.crt.valueFrom.secretKeyRef.name | default (printf "%s-rest-tls" (include "corda.fullname" .)) }}
I think I will change this approach to a **single** secret name only which will have to contain all 3 keys.

2023-03-28 09:30 UTC, vkolomeyko commented on charts/corda-lib/templates/_worker.tpl
> +            secretName: {{ include "corda.restTlsSecretName" $ | quote }}
As above, this will be changed to a single secret.

2023-03-28 09:32 UTC, vkolomeyko commented on charts/corda/templates/secrets.yaml
> +{{- $interCert := genSignedCert "REST Worker Intermediary Cert" nil nil 365 $ca }}
It was just to illustrate that we can have longer certificate chains. I can eliminate intermediate bit, if there is objection.

2023-03-28 09:33 UTC, vkolomeyko commented on charts/corda/templates/secrets.yaml
> +{{- $altNames := list ( printf "%s.c5.r3.com" .Release.Namespace ) ( printf "%s.%s.svc" $restWorkerName .Release.Namespace ) "localhost" }}
Sure - I will add an option allowing to specify the domain name.
Will remove `localhost` as well.

2023-03-28 09:34 UTC, vkolomeyko commented on charts/corda/templates/secrets.yaml
> +{{- $cert := genSignedCert $restWorkerName (list "127.0.0.1") $altNames 365 $interCert }}
Sure - I will remove IPs.

2023-03-28 09:35 UTC, vkolomeyko commented on charts/corda/values.schema.json
> +                                            "$ref": "#/$defs/config"
As per above, I will change this schema to have just a single secret name for all 3 keys.

2023-03-28 09:36 UTC, vkolomeyko commented on charts/corda/values.yaml
> +            key: ""
Yeap, one secret name is the way to go, I think. It was mentioned on multiple instances above as well.

2023-03-28 09:38 UTC, vkolomeyko commented on charts/corda/templates/workers.yaml
> +  ( dict "httpPort" 8888 "restTlsSecret" true )
Sure - I will change.

2023-03-28 09:38 UTC, vkolomeyko commented on charts/corda/templates/secrets.yaml
> +{{- $restWorkerName := "rest-worker" }}
Sure - I will change.

2023-03-28 09:39 UTC, vkolomeyko commented on charts/corda/templates/secrets.yaml
> +{{- $ca := genCA "REST Worker Certification Authority" 1000 }}
Sure, I will change it to `REST Worker Self-Signed Certification Authority`.

2023-03-28 14:59 UTC, vkolomeyko commented on charts/corda-lib/templates/_helpers.tpl
> +{{-     if or $field.value $v.generate $v.explicit }}
I no longer need change for `explicit` value passing.
However, I thought of it as being a useful facility for the future.
Happy to undo it, if people feel this is unnecessary.

2023-03-28 20:10 UTC, davidcurrie requested changes

2023-03-28 20:10 UTC, davidcurrie commented on charts/corda-lib/templates/_helpers.tpl
> +{{- end }}
I'm still not sold on the need to be able to have user-definable key values here. I think they've sufficiently standard that it is fair to just say that the secret needs to have three data fields called `tls.crt`, `tls.key`, and `ca.crt`. See for example: https://cert-manager.io/docs/concepts/certificate/

If you do want them to be user-configurable, then I think `tls.crt`, `tls.key`, and `ca.crt` should still be the default values. The default values should live in `values.yaml` where the user can see them.

2023-03-28 20:10 UTC, davidcurrie commented on charts/corda-lib/templates/_helpers.tpl
> +{{-     if or $field.value $v.generate $v.explicit }}
Why not have `corda.tlsSecret` call this function once it has prepared the certificates?

2023-03-28 20:10 UTC, davidcurrie commented on charts/corda-lib/templates/_helpers.tpl
> +{{- $interCert := genSignedCert $interName nil nil 365 $ca }}
My question still remains: why have an intermediary certificate here?

2023-03-28 20:10 UTC, davidcurrie commented on charts/corda-lib/templates/_helpers.tpl
> +{{- $kind := index . 1 }}
`kind` has a very specific meaning in Kubernetes resources so it might be worth calling this something different

2023-03-28 20:10 UTC, davidcurrie commented on charts/corda-lib/templates/_helpers.tpl
> +{{- $existingSecret := lookup "v1" "Secret" $.Release.Namespace $secretName }}
What happens if the existing secret has different key names or alt names to the values that are now specified on the chart?

2023-03-28 20:10 UTC, davidcurrie commented on charts/corda-lib/templates/_helpers.tpl
> +    "helm.sh/hook": pre-install
These can go as I don't think this secret needs to be available at pre-install time. Kubernetes will ensure that the REST worker does not start until the secret is available.

2023-03-28 20:10 UTC, davidcurrie commented on charts/corda-lib/templates/_helpers.tpl
> +{{- $cert := genSignedCert $kind nil $altNames 365 $interCert }}
It is fine to allow additional or overridden `altNames` to be configured but the internal DNS names that Kubernetes will allocate should certainly be the defaults (as you had started to do previously). Likewise, I'd expect the CN should be the service name.

2023-03-28 20:10 UTC, davidcurrie commented on charts/corda-lib/templates/_worker.tpl
> +                path: "ca.crt"
If the key names are fixed, this all gets a lot simpler but I'd still like to see this not explicitly depend on the worker type here. So either pass the secret name (and keys if needed) as parameters into the `corda.worker` function or swap the conditional for a `with .tls`.

2023-03-28 20:10 UTC, davidcurrie commented on charts/corda/values.yaml
> +        secretKey: ""
As above, if these are staying then they should have default values in them

2023-03-28 20:10 UTC, davidcurrie commented on charts/corda/values.yaml
> +      # the name of the secret to derive information below
"leaf" comments should begin `--`

2023-03-28 20:10 UTC, davidcurrie commented on charts/corda/values.yaml
> +      # the name of the secret to derive information below
the comment is used in generated documentation where you can't rely on "below" still being meaningful

2023-03-28 20:10 UTC, davidcurrie commented on charts/corda/values.yaml
> +      # the name of the secret to derive information below
the comment should make it clear that you need to provide the name of an existing secret containing the credentials or that one will get generated using self-signed certificates

2023-03-28 20:10 UTC, davidcurrie commented on charts/corda/values.yaml
> +          - "*.another.one.r3.com"
We shouldn't have `r3.com` in here. As per the comments above, my preference would be for this to be an empty list by default and to have the default names based on the Kubernetes internal service names. With the ingress route we discussed, the only thing accessing these certificates will be something like nginx running in the same Kubernetes cluster as the workers.

2023-03-29 08:19 UTC, vkolomeyko commented on charts/corda-lib/templates/_helpers.tpl
> +{{- $interCert := genSignedCert $interName nil nil 365 $ca }}
Sure - I have replied here: https://github.com/corda/corda-runtime-os/pull/3456#discussion_r1150305230

I can remove intermediate bit, if necessary.

2023-03-29 08:19 UTC, vkolomeyko commented on charts/corda-lib/templates/_helpers.tpl
> +{{- $kind := index . 1 }}
How about changing this to `purpose` ?

2023-03-29 08:22 UTC, vkolomeyko commented on charts/corda-lib/templates/_helpers.tpl
> +{{-     if or $field.value $v.generate $v.explicit }}
I found this function rather complicated as it is at the moment.
Also this function takes `.Values...` as an input parameter and then it assumes that secret keys will be stored in a particular way under `.Values`.
Hence I decided against using it.

2023-03-29 08:22 UTC, davidcurrie commented on charts/corda-lib/templates/_helpers.tpl
> +{{- $interCert := genSignedCert $interName nil nil 365 $ca }}
Sorry - I didn't see your earlier response. I don't think we should be using this as an example of how to create a certificate. This should just be the minimum needed when they haven't done so.

2023-03-29 08:23 UTC, vkolomeyko commented on charts/corda-lib/templates/_helpers.tpl
> +{{- end }}
OK, sure.
Let me rename those secret names and move them to `values.yaml`.

2023-03-29 08:25 UTC, davidcurrie commented on charts/corda-lib/templates/_helpers.tpl
> +{{-     if or $field.value $v.generate $v.explicit }}
OK - that's fine. In which case, yes, could you please remove the `explicit` logic again.

2023-03-29 08:37 UTC, vkolomeyko commented on charts/corda-lib/templates/_helpers.tpl
> +{{- $existingSecret := lookup "v1" "Secret" $.Release.Namespace $secretName }}
If a secret exists and keys mismatch then in this particular function nothing is going to happen, i.e. no new secret will be created.
Then at REST worker pod start-up time an error is likely to occur when trying to mount a secret with non-existent key name. Which I think is fine.
@davidcurrie - what would you rather happen? Do you want another clause to this function to validate existence of the secret keys here?

2023-03-29 08:37 UTC, vkolomeyko commented on charts/corda-lib/templates/_helpers.tpl
> +    "helm.sh/hook": pre-install
Sure - I will remove.

2023-03-29 08:38 UTC, vkolomeyko commented on charts/corda-lib/templates/_helpers.tpl
> +{{- $cert := genSignedCert $kind nil $altNames 365 $interCert }}
Sure - I will change that.

2023-03-29 08:39 UTC, vkolomeyko commented on charts/corda-lib/templates/_worker.tpl
> +                path: "ca.crt"
Sure - I see your point. Let me re-work.

2023-03-29 08:39 UTC, vkolomeyko commented on charts/corda/values.yaml
> +        secretKey: ""
Sure - will change.

2023-03-29 08:40 UTC, vkolomeyko commented on charts/corda/values.yaml
> +      # the name of the secret to derive information below
Sure, I will change.

2023-03-29 08:41 UTC, vkolomeyko commented on charts/corda/values.yaml
> +          - "*.another.one.r3.com"
Sure - I will change.

2023-03-29 09:36 UTC, vkolomeyko commented on charts/corda-lib/templates/_helpers.tpl
> +{{-     if or $field.value $v.generate $v.explicit }}
Removed.

2023-03-29 09:39 UTC, vkolomeyko commented on charts/corda-lib/templates/_helpers.tpl
> +{{- $interCert := genSignedCert $interName nil nil 365 $ca }}
Removed.

2023-03-29 10:04 UTC, davidcurrie commented on charts/corda-lib/templates/_helpers.tpl
> +{{- $existingSecret := lookup "v1" "Secret" $.Release.Namespace $secretName }}
As you say, if the `keys` are changed then it will fail later and I think it's fine to expect the user just to correct them as they would if they were using their own certificate. The `altNames` is more problematic as, if this changes, they probably are expecting the certificate to be regenerated. I'm guessing extracting these from the existing certificate is non-trivial in this context so perhaps it is worth writing these into the secret as well, or maybe adding them as annotations?

2023-03-29 12:17 UTC, vkolomeyko commented on charts/corda-lib/templates/_helpers.tpl
> +{{- $existingSecret := lookup "v1" "Secret" $.Release.Namespace $secretName }}
Sure - I will `altNames` as annotations.

2023-03-29 15:10 UTC, davidcurrie requested changes

2023-03-29 15:10 UTC, davidcurrie commented on charts/corda/values.yaml
> +    tls:
include the optional properties here as well, particularly as the README is generated from the comments in this file, not the schema - so something like:
```
  # ...
  generation:
     # -- ....
     altNames: []
```

2023-03-29 15:10 UTC, davidcurrie commented on charts/corda/values.schema.json
> +                                                    "title": "Alternative names to be include into a certificate when generated."
```suggestion
                                                    "title": "Alternative names to be included in a certificate when generated."
```

2023-03-29 15:10 UTC, davidcurrie commented on charts/corda/values.schema.json
> +                                            "title": "The name of the secret to derive information below. If missing, a new secret will be created and certificates/keys generated."
```suggestion
                                            "title": "The name of the Kubernetes secret containing the certificate, private key and CA certificate. If not specified, a new secret will be created and certificates/keys generated."
```

2023-03-29 15:10 UTC, davidcurrie commented on charts/corda/values.yaml
> +      # -- the name of the K8s secret to derive information about certificate, private key and CA certificate
```suggestion
      # -- the name of the Kubernetes secret containing the certificate, private key and CA certificate; if not specified, a new secret will be created and certificates/keys generated
```

2023-03-29 15:10 UTC, davidcurrie commented on charts/corda-lib/templates/_helpers.tpl
> +{{- if not $existingSecret }}
We generate a certificate if they give us a name but a secret doesn't exist with that name. I think we should only generate if they don't give us a name AND the generated secret doesn't already exist. If they gave us a name and the secret doesn't exist (maybe there was a typo), it should just error out when the worker tries to start.

2023-03-29 15:10 UTC, davidcurrie commented on charts/corda-lib/templates/_helpers.tpl
> +{{- end }}
You cover `altNames` being empty elsewhere so we should always have a list by now

2023-03-29 15:10 UTC, davidcurrie commented on charts/corda-lib/templates/_helpers.tpl
> +{{- $altNames = ( append $altNames ( printf "%s.%s.svc" $serviceName $.Release.Namespace ) ) }}
The list should also contain `( printf "%s.%s" $serviceName $.Release.Namespace )`

2023-03-29 15:10 UTC, davidcurrie commented on charts/corda-lib/templates/_helpers.tpl
> +    certificate/altNames: {{ toString ( toStrings ( $altNames ) ) | quote }}
The purpose of adding the annotations was to check that they are the same as the current value of `altNames` when retrieving an existing secret.

2023-03-29 15:10 UTC, davidcurrie commented on charts/corda-lib/templates/_helpers.tpl
> +    certificate/altNames: {{ toString ( toStrings ( $altNames ) ) | quote }}
Isn't `altNames` already a list of strings? I would expect to see something more like `join "," $altNames`

2023-03-29 15:22 UTC, vkolomeyko commented on charts/corda-lib/templates/_helpers.tpl
> +{{- end }}
Not quite.
```
{{- $altNames := list }}
{{- if .Values.workers.rest.tls.generation }}
{{-   $altNames = .Values.workers.rest.tls.generation.altNames }}
{{- end}}
```
covers the case when `generation` section is missing. However, there can be a situation when `generation` section is present, but `altNames` inside inside it were not provided.
Therefore, I think this is still necessary.

2023-03-29 15:32 UTC, vkolomeyko commented on charts/corda-lib/templates/_helpers.tpl
> +{{- if not $existingSecret }}
Sure - let me alter logic here.

2023-03-29 16:13 UTC, davidcurrie requested changes

2023-03-29 16:13 UTC, davidcurrie commented on charts/corda-lib/templates/_helpers.tpl
> +{{-   end }}
Sorry - I've made this more complicated than it needs be. I'd just skip calling `corda.tlsSecret` if `secretName` has been set. It's better to let Kubernetes handle the existence or otherwise of that secret. By putting a check here you're adding an explicit ordering constraint (the secret must exist before Corda is deployed) which is a bit of an anti-pattern.

2023-03-29 16:13 UTC, davidcurrie commented on charts/corda-lib/templates/_helpers.tpl
> +{{- if not $existingSecret }}
this needs to be "or there is an existing secret but with the wrong altNames"

2023-03-29 16:13 UTC, davidcurrie commented on charts/corda/values.yaml
> +      generation:
missing comment

2023-03-29 16:30 UTC, vkolomeyko commented on charts/corda-lib/templates/_helpers.tpl
> +{{-   end }}
Changed.

2023-03-29 16:56 UTC, vkolomeyko commented on charts/corda-lib/templates/_helpers.tpl
> +{{- if not $existingSecret }}
Sure, I have incorporated annotations diffing as well.

2023-03-30 16:21 UTC, davidcurrie approved these changes
LGTM 🚀 

Tested this locally by deploying a cluster with `--set "workers.rest.tls.generation.altNames[0]=localhost"`. I could then execute a "secure" curl against the REST API as follows:
```
kubectl port-forward --namespace dcurrie deployment/corda-rest-worker 8888 &
curl --cacert <(kubectl get secret corda-rest-tls -o go-template='{{ index .data "ca.crt" | base64decode }}') -X POST https://localhost:8888/api/v1/hello\?addressee\=David -u admin:admin
Handling connection for 8888
Hello, David! (from admin)
```
The only issue I've identified is that, if `altNames` is updated, the certificate is regenerated but the REST worker deployment is not rolled over. We can either document that the deployment needs to be rolled manually or use [this trick](https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments). Either way, I'm happy to see this merged as-is.

2023-03-30 16:30 UTC, filipesoliveira approved these changes

2023-03-30 16:33 UTC, merged