CORE-10424 : Changes to identify fake identity from real one PART - I : For interop group of two
corda/corda-runtime-os pull request #3464
Opened 2023-03-24 13:55 UTC by SaurabhR3

2023-03-24 15:51 UTC, szymonsztuka reviewed
I thought that we decided to work on solution ready for groups bigger than 2 members, so the mechanism using `StateAndEventProcessor`, which  will invalidate this PR entirely.

2023-03-25 12:32 UTC, yarivus requested changes

2023-03-25 12:32 UTC, yarivus commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropAliasProcessor.kt
> +            val filteredMap = identityMappingCache.filter {(key, value) -> key != fakeIdentity && value.groupId == groupId }
Why are you searching the inequality of fakeIdentity ?
Shouldn't it be equal by fakeIdentity && groupId ?

2023-03-28 13:07 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropAliasProcessor.kt
> +            val filteredMap = identityMappingCache.filter {(key, value) -> key != fakeIdentity && value.groupId == groupId }
Its removed now

2023-03-28 13:30 UTC, yarivus requested changes

2023-03-28 13:30 UTC, yarivus commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropService.kt
> +        private const val CLEANUP_TASK = "TASK"
```suggestion
        private const val CLEANUP_TASK = "CLEANUP_TASK"
```

2023-03-28 13:30 UTC, yarivus commented on gradle.properties
> +cordaApiVersion=5.0.0-INTEROP.0-alpha-1680006496201
why are you going backwards ?

2023-03-28 13:46 UTC, ac101m commented on gradle.properties
> +cordaApiVersion=5.0.0-INTEROP.0-alpha-1680006496201
We need to track API versioning separately for the interop feature branch. Sharing the version number with mainline is likely to cause problems for us in the the future.

When we merge from mainline or make a breaking change, we'll increment our version number. When it comes time to merge back into mainline, we'll increment the mainline version number.

Collisions shouldn't occur because of the `-INTEROP` suffix to the corda product version.

2023-03-28 15:48 UTC, szymonsztuka requested changes

2023-03-28 15:48 UTC, szymonsztuka commented on components/interop/interop-service/src/integrationTest/kotlin/net/corda/interop/service/integration/InteropServiceIntegrationTest.kt
> +            val eventTopic = subscriptionFactory.createStateAndEventSubscription(
The test reader doesn't need to be of type`StateAndEventProcessor`, leave it as`DurableProcessor`. It checks what it on `P2P_OUT_TOPIC`, and this PR doesn't alter what is send on that topic and it doesn't store our internal state etc.

2023-03-29 09:37 UTC, SaurabhR3 commented on gradle.properties
> +cordaApiVersion=5.0.0-INTEROP.0-alpha-1680006496201
When I created corda-api PR it generates the artefacts with name `alpha` : [https://ci02.dev.r3.com/job/Corda5/job/corda-api/job/PR-1010/1/](url) 
So I have to use `alpha` to make this build happy.

OR probably I need to merge the corda-api PR and then it will generate the `beta` and I can use it. I am not sure about it. Need to check.

2023-03-29 13:48 UTC, yarivus reviewed
LGTM but pending comments

2023-03-31 10:54 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropService.kt
> +        private const val CLEANUP_TASK = "TASK"
Fixed in 910e547

2023-03-31 10:56 UTC, SaurabhR3 commented on gradle.properties
> +cordaApiVersion=5.0.0-INTEROP.0-alpha-1680006496201
This will be fixed as part of last commit, when corda-api changes will be merged.

2023-03-31 10:56 UTC, SaurabhR3 commented on components/interop/interop-service/src/integrationTest/kotlin/net/corda/interop/service/integration/InteropServiceIntegrationTest.kt
> +            val eventTopic = subscriptionFactory.createStateAndEventSubscription(
Fixed in 910e547

2023-03-31 11:00 UTC, szymonsztuka commented on gradle.properties
> +cordaApiVersion=5.0.0-INTEROP.3-SNAPSHOT
You need to use corresponding Alpha build (with precise number) from https://github.com/corda/corda-api/pull/1010, after that PR is merged, you need to switch to `5.0.0-INTEROP.3-beta+` in this PR.

2023-03-31 11:06 UTC, SaurabhR3 commented on gradle.properties
> +cordaApiVersion=5.0.0-INTEROP.3-SNAPSHOT
I have triggered the alpha build now, I will change it once it is available. Till the time build will be red

2023-03-31 11:32 UTC, ac101m commented on gradle.properties
> +cordaApiVersion=5.0.0-INTEROP.3-SNAPSHOT
Should also note, there's no need to pick a specific version number until tests are passing and the PR has been approved. When you get to the point of merging your api PR, just set the version number to the next available one (probably going to be 2 in this case).

2023-03-31 11:37 UTC, szymonsztuka requested changes

2023-03-31 11:37 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
> +                                state?.aliasHoldingIdentity,
In general it's a bit tricky reasoning when we have a saved state already, as first message may arrived to the processor from both sides (INBOUND and OUTBOUND). At least we need to prevent what if a state is null? If it's null then use value as in the previous code.
`state?.aliasHoldingIdentity ?: destinationIdentity.x500Name,`

2023-03-31 15:04 UTC, jmacmahonr3 requested changes
Some small comments but looking good

2023-03-31 15:04 UTC, jmacmahonr3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
> +//TODO import commented out - see TODO adding FLOW_CONFIG below:
Please add a ticket number of the ticket where we are going to do this work. If this ticket doesn't exist we can create one.

2023-03-31 15:04 UTC, jmacmahonr3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
> +                            ), //TODO replace groups with alias one
Add Ticket Please

2023-03-31 15:04 UTC, jmacmahonr3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropListener.kt
> +            if (expiryTime != null && state.status == InteropStateType.INVALID) {
Maybe a dumb question but do we care if we have an expiry time but the state is still invalid ?

2023-03-31 15:04 UTC, jmacmahonr3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropListener.kt
> +            if (expiryTime != null && state.status == InteropStateType.INVALID) {
I see we check it on post commit but do we need to check it here too ?

2023-03-31 15:38 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
> +//TODO import commented out - see TODO adding FLOW_CONFIG below:
This is not my change it is from Szymon's changes, @szymonsztuka do we have ticket number for this?

2023-03-31 15:40 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
> +                            ), //TODO replace groups with alias one
Removed comment as we are setting alias here.

2023-03-31 15:41 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropListener.kt
> +            if (expiryTime != null && state.status == InteropStateType.INVALID) {
I am not 100% sure here, I just kept it consistent with flow mapper processor.

2023-03-31 16:14 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
> +                                state?.aliasHoldingIdentity,
I believe in outbound message state must be available. If we set the `destinationIdentity.x500Name` wouldn't it be wrong? Source and Destination will be destinationIdentity.

2023-03-31 16:17 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
> +//TODO import commented out - see TODO adding FLOW_CONFIG below:
CORE-12208

2023-03-31 16:21 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
> +                            ), //TODO replace groups with alias one
Fixed in eded1b3

2023-03-31 16:22 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
> +//TODO import commented out - see TODO adding FLOW_CONFIG below:
FIxed in eded1b3

2023-03-31 16:23 UTC, szymonsztuka requested changes

2023-03-31 16:23 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
> +                                state?.aliasHoldingIdentity,
1. The status for outbound message is present only if this is a message created from a responder flow, if a message is created from an initiating flow then this is the first message ever hitting the processor, and it's still outbound.
2. Even if the 1st) statement would be incorrect,  the compiler tells you this can be null `state?`, so you have second reason to have a remedy on this.

2023-03-31 16:24 UTC, jmacmahonr3 approved these changes
Make sure you resolve any remaining comments but LGTM

2023-03-31 16:36 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
> +                                state?.aliasHoldingIdentity,
I am still unsure how initiating flow request can be outbound message? Also even initiating flow will be outbound still we can't just keep the source and destination same while moving message to p2p-out topic. Better to discuss it on call.

2023-03-31 17:17 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
> +                                state?.aliasHoldingIdentity,
@szymonsztuka thanks for a call, fixed in c52dc76

2023-03-31 18:14 UTC, szymonsztuka approved these changes
before the merge, mereg corda-api first with increased APi version, then here change `cordaApiVersion=5.0.0-INTEROP.3-alpha-1680260631242`to  `cordaApiVersion=5.0.0-INTEROP.3-beta+`

2023-04-03 12:56 UTC, SaurabhR3 commented on gradle.properties
> +cordaApiVersion=5.0.0-INTEROP.0-alpha-1680006496201
Fixed in 4054268

2023-04-03 13:36 UTC, yarivus approved these changes
LGTM

2023-04-03 13:47 UTC, merged