CORE-9886: Enable Docker Authentication
corda/corda-runtime-os pull request #3478
Opened 2023-03-27 12:06 UTC by knguyen-r3

* Modified function setCredentialsOnBaseImage to be able to handle local Docker credential

2023-03-27 19:57 UTC, ronanbrowne commented
FYI: I needed to force push to rebase this as old artifacts were outdated and could not be built locally.

2023-03-27 20:05 UTC, ronanbrowne commented
@knguyen-r3 I had a look at this, and your issue is on line 220 

https://github.com/corda/corda-runtime-os/blob/knguyen/CORE-9886/enable_docker_authentication/buildSrc/src/main/groovy/DeployableContainerBuilder.groovy#L221

` builder = Jib.from(imageName)`
 
 is called, this is trying to pull the base image without authenticating.
 
Can you try and remove that line and replace it with and re test this.
  
` builder = setCredentialsOnBaseImage(builder)`

which will authenticate (presuming you have the relivent env vars set).

2023-03-28 13:50 UTC, ronanbrowne requested changes
see comments  (i know still in draft)

2023-03-28 13:50 UTC, ronanbrowne commented on buildSrc/src/main/groovy/DeployableContainerBuilder.groovy
> +            logger.info("DEBUG setCredentialsOnBaseImage")
```suggestion
            logger.info("Authenticating against Docker Hub for base image resolution")
```

2023-03-28 13:50 UTC, ronanbrowne commented on buildSrc/src/main/groovy/DeployableContainerBuilder.groovy
> +            logger.info("DEBUG artifactory setCredentialsOnBaseImage")
```suggestion
            logger.info("Authenticating against Artifactory for base image resolution")
```

2023-03-28 13:50 UTC, ronanbrowne commented on buildSrc/src/main/groovy/DeployableContainerBuilder.groovy
> +        // Else need to authenticate locally on docker hub
I'd remove this comment as IMO it's unnecessary

2023-03-28 13:50 UTC, ronanbrowne commented on buildSrc/src/main/groovy/DeployableContainerBuilder.groovy
> +        logger.info("DEBUG setCredentialsOnBaseImage")
remember to remove this line

2023-03-29 12:59 UTC, ronanbrowne approved these changes
LGTM

2023-03-29 12:59 UTC, merged

2023-03-29 13:43 UTC, yarivus commented on buildSrc/src/main/groovy/DeployableContainerBuilder.groovy
> +        else if ((dockerHubUsername.get() != null && !dockerHubUsername.get().isEmpty()) && (dockerHubPassword.get() != null && !dockerHubPassword.get().isEmpty())){
add a space before '{' and break the conditions to separate lines:
```
else if ((dockerHubUsername.get() != null && !dockerHubUsername.get().isEmpty()) &&
         (dockerHubPassword.get() != null && !dockerHubPassword.get().isEmpty())) {
```
See the previous 'if' and apply the same.