CORE-10691 - avro schema registry from kafka
corda/corda-runtime-os pull request #3488
Opened 2023-03-28 10:44 UTC by driessamyn

We need to make sure that all workers have a schema of any message that can be posted in a cluster.  This is to ensure that, as messages evolve, that they can still be deserialized.  Avro expects to have both the original and expected schema for deserialization.  So when a message evolves we need to be able to have both sides available.

There should be an enhancement such that the schema registry can receive all of the schemas and add any new ones for which is doesn’t already know about from initialization.

This change makes all processors fetch existing schemas from the schemas (compacted) topic and publishes any new schemas to that topic.

2023-03-28 11:18 UTC, simon-johnson-r3 commented on components/configuration/configuration-read-service-impl/src/main/kotlin/net/corda/configuration/read/impl/AvroSchemaProcessor.kt
> +        const val PUBLISH_TIMEOUT = 5L
I usually add _SECONDS on to these to you don't have to go and check and it's obvious if there's a mistake at the point of use, must have forgotten here

2023-03-28 21:26 UTC, simon-johnson-r3 requested changes

2023-03-28 21:26 UTC, simon-johnson-r3 commented on components/configuration/configuration-read-service-impl/src/test/kotlin/net/corda/configuration/read/impl/AvroSchemaProcessorTest.kt
> +         `when`(publisher.publish(any())).doAnswer {
Mockito's Kotlin support adds a `whenever` function to get round this being a keyword.

2023-03-28 21:26 UTC, simon-johnson-r3 commented on components/configuration/configuration-read-service-impl/src/test/kotlin/net/corda/configuration/read/impl/AvroSchemaProcessorTest.kt
> +    }
can you add `verify(publisher).publish(any())` here?
otherwise if publish is never called the test would still pass

2023-03-28 21:26 UTC, simon-johnson-r3 commented on libs/schema-registry/schema-registry-impl/src/test/kotlin/net/corda/schema/registry/impl/AvroSchemaRegistryImplTest.kt
> +            assertThat(registry.schemasByFingerprintSnapshot).size().isEqualTo(schemasCount+1)
minor, but should we have spaces around operators?

2023-03-28 21:26 UTC, simon-johnson-r3 commented on libs/schema-registry/schema-registry-impl/src/test/kotlin/net/corda/schema/registry/impl/AvroSchemaRegistryImplTest.kt
> +    fun `containsSchema returbs false if schema does not exists`() {
typos
returbs -> returns
exists -> exist

2023-03-28 21:26 UTC, simon-johnson-r3 commented on libs/schema-registry/schema-registry-impl/src/test/kotlin/net/corda/schema/registry/impl/AvroSchemaRegistryImplTest.kt
> +
minor: double CR

2023-03-28 21:26 UTC, simon-johnson-r3 commented on libs/schema-registry/schema-registry/src/main/kotlin/net/corda/schema/registry/AvroSchemaRegistry.kt
> +     * Returns true if the Registry has a schema with the given [Fingerprint].
this would be more consistent as
`@return true if the Registry has a schema with the given [Fingerprint].`

2023-03-28 21:26 UTC, simon-johnson-r3 commented on libs/schema-registry/schema-registry/src/main/kotlin/net/corda/schema/registry/AvroSchemaRegistry.kt
> +     * Current, point in time, view of all [Schema]s in the registry, keyed by [Fingerprint].
@return

Maybe `Current, point in time,` should be `Snapshot of all...` or similar. The reason I say this is I thought I knew what you meant, but I had to go and double check the implementation to be sure.

2023-03-28 21:57 UTC, driessamyn commented on components/configuration/configuration-read-service-impl/src/test/kotlin/net/corda/configuration/read/impl/AvroSchemaProcessorTest.kt
> +         `when`(publisher.publish(any())).doAnswer {
Thanks. Didn't know that, usually use the `do {` construct, and copied this from another example.

Changed now.

2023-03-28 21:57 UTC, driessamyn commented on components/configuration/configuration-read-service-impl/src/test/kotlin/net/corda/configuration/read/impl/AvroSchemaProcessorTest.kt
> +    }
Good catch. Thanks!

2023-03-28 21:59 UTC, driessamyn commented on libs/schema-registry/schema-registry/src/main/kotlin/net/corda/schema/registry/AvroSchemaRegistry.kt
> +     * Current, point in time, view of all [Schema]s in the registry, keyed by [Fingerprint].
I was trying to capture that it is a copy of the map that is returned. But you're right, Snapshot is probably a better description. Changed now.

2023-03-29 07:56 UTC, simon-johnson-r3 submitted a review, later dismissed

2023-03-29 08:06 UTC, fowlerrr submitted a review, later dismissed

2023-03-29 08:52 UTC, fowlerrr submitted a review, later dismissed

2023-03-29 09:03 UTC, fowlerrr approved these changes

2023-03-29 09:05 UTC, simon-johnson-r3 approved these changes

2023-03-29 09:45 UTC, mcgovc approved these changes
LGTM - build changes

2023-03-29 09:58 UTC, yift-r3 approved these changes
LGTM (Gateway + Link manager)

2023-03-29 15:09 UTC, merged