[CORE-11976] Use session context properties for interop session identification
corda/corda-runtime-os pull request #3497
Opened 2023-03-28 16:07 UTC by ac101m

# Changes
- Add isInteropSession context property to to flow context properties map.

2023-04-04 12:58 UTC, yarivus requested changes

2023-04-04 12:58 UTC, yarivus commented on libs/flows/flow-mapper-impl/src/integrationTest/kotlin/net/corda/flow/mapper/integration/FlowMapperIntegrationTest.kt
> +        val flowMapperState = FlowMapperState("flowKey", null, FlowMapperStateType.OPEN, false)
why do we explicitly specify the `false` parameter if all functions have a default value of false ? 
This would immensely reduce the amount of changes in this PR

2023-04-04 12:58 UTC, yarivus commented on libs/flows/flow-mapper-impl/src/main/kotlin/net/corda/flow/mapper/impl/executor/SessionInitExecutor.kt
> +                FlowMapperState(flowKey, null, FlowMapperStateType.OPEN, true),
this would be the only change in this PR for when it's true - see my prev comment

2023-04-04 13:21 UTC, ac101m commented on libs/flows/flow-mapper-impl/src/integrationTest/kotlin/net/corda/flow/mapper/integration/FlowMapperIntegrationTest.kt
> +        val flowMapperState = FlowMapperState("flowKey", null, FlowMapperStateType.OPEN, false)
I've used defaults where I can, but `FlowMapperState` is an avro type. We get this all-parameters constructor and that's it! It might be possible to use the generated builder to do this, but this would mean many more code changes.

2023-04-05 11:03 UTC, jmacmahonr3 approved these changes
Looks alright to me

2023-04-05 11:16 UTC, SaurabhR3 approved these changes

2023-04-05 15:27 UTC, merged