CORE-10422 Interop integration Initating and Inisated Interop Flows via Interop new topic
corda/corda-runtime-os pull request #3499
Opened 2023-03-28 22:49 UTC by szymonsztuka

2023-03-29 10:07 UTC, ac101m commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/handlers/events/SessionEventHandler.kt
> +                .setInitiatorType(if (sessionId.contains("INTEROP")) FlowInitiatorType.INTEROP else FlowInitiatorType.P2P)
Will need to be aware of this later, as I'm currently working on removing the session ID hack!

2023-03-29 10:13 UTC, ac101m reviewed
A few initial comments

2023-03-29 10:13 UTC, ac101m commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/impl/FlowGlobalPostProcessorImpl.kt
> +            .map { if (isInterop(context)) { it /*wrap payload intoInterop, add Interop FLage etc*/ } else { it } }
typo here in flag

2023-03-29 10:13 UTC, ac101m commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/impl/FlowGlobalPostProcessorImpl.kt
> +        }
I don't think this is necessary, see condition in if statement below.

2023-03-31 15:17 UTC, jmacmahonr3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/HardcodedInteropMemberRegistrationService.kt
> +    //Below method is to push the dummy interops member data to MEMBER_LIST_TOPIC
why is this a new class as opposed to rewriting the original class and what was the need for redoing the implementation i.e what did we miss the first time ?

2023-03-31 15:25 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/HardcodedInteropMemberRegistrationService.kt
> +    //Below method is to push the dummy interops member data to MEMBER_LIST_TOPIC
short answer, it was never a real service, rather a collection of static methods, the core issue is that we were unable to know a real groupId upfront (as it changes), and at runtime there is service offering a  method "list all member infos/hosted identities, and I will pick what I need". You always need to know what you are looking for. So (still) a temporary solution is to create our aliases dynamically, when the real MemberInfos are registered, at that time we exactly know what will be real group ID for example.

2023-03-31 17:21 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/HardcodedInteropMemberRegistrationService.kt
> +    //Below method is to push the dummy interops member data to MEMBER_LIST_TOPIC
I meant to say at runtime _there ~~is~~ **isn't** a service offering a method ...._

2023-04-06 16:22 UTC, ac101m reviewed
A few code style thoughts and a couple question, but otherwise looks okay to me!

2023-04-06 16:22 UTC, ac101m commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/flow/FlowTests.kt
> +            "alias" to charlyX500.replace("$testRunUniqueId", "$testRunUniqueId Alias")
charly -> charlie

2023-04-06 16:22 UTC, ac101m commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/handlers/events/SessionEventHandler.kt
> +                .setInitiatorType(if (initialSessionState.isInteropSession) FlowInitiatorType.INTEROP else FlowInitiatorType.P2P)
Would prefer if this were assigned it's own variable!

2023-04-06 16:22 UTC, ac101m commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropMembersProducer.kt
> +class InteropMembersProducer  {
This class has no members. It can be a singleton (or methods can be static), or maybe loose methods. Maybe we need a  place for interop specific utility functions? :thinking:

2023-04-06 16:22 UTC, ac101m commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
> +//            }
Curious, why is this commented out rather than removed?

2023-04-06 16:22 UTC, ac101m commented on libs/flows/flow-mapper-impl/src/main/kotlin/net/corda/flow/mapper/impl/executor/SessionInitExecutor.kt
> +                    FlowMapperEvent(sessionEvent)
Not a fan of brace-less if statements like this

2023-04-06 16:22 UTC, ac101m commented on libs/flows/flow-mapper-impl/src/main/kotlin/net/corda/flow/mapper/impl/executor/SessionInitExecutor.kt
> +                    FlowMapperEvent(sessionEvent)
Also, should we be re-using the flow mapper event class? Perhaps we should use an InteropProcessorEvent or something like this?

2023-04-11 13:13 UTC, szymonsztuka commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/flow/FlowTests.kt
> +            "alias" to charlyX500.replace("$testRunUniqueId", "$testRunUniqueId Alias")
`charly` variable is in the main, I don't want to "fix" it because this will cause unnecessary diff

2023-04-12 14:37 UTC, szymonsztuka commented on libs/flows/flow-mapper-impl/src/main/kotlin/net/corda/flow/mapper/impl/executor/SessionInitExecutor.kt
> +                    FlowMapperEvent(sessionEvent)
fixed

2023-04-12 14:38 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
> +//            }
fixed, still is not really used, but no code is un-commented

2023-04-12 14:38 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropMembersProducer.kt
> +class InteropMembersProducer  {
fixed, moved to a real class as static methods

2023-04-12 14:39 UTC, szymonsztuka commented on libs/flows/flow-mapper-impl/src/main/kotlin/net/corda/flow/mapper/impl/executor/SessionInitExecutor.kt
> +                    FlowMapperEvent(sessionEvent)
It's for speed up the development (no need changes to corda-api), we may use own types thought later on

2023-04-14 05:02 UTC, SaurabhR3 requested changes

2023-04-14 05:02 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
>              }
The above code is not returning the facadeName, it is returning the facadeRequest. Better to change the name.

2023-04-14 05:02 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
> +                }
in the catch block you may need to add `return StateAndEventProcessor.Response(state, emptyList())`

2023-04-14 05:02 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
> +                        }
Just a suggestion, its better to add this in method, than having multiple `apply`

2023-04-14 07:45 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
> +                }
The warn is on purpose to pass the message further, as in this "exploratory" phase it's better not to skip the message, as well see just one line below there is TODO, the facadeName is not used for now.

2023-04-14 08:33 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
> +                        }
Fixed in [dadd83f](https://github.com/corda/corda-runtime-os/pull/3499/commits/dadd83f74f852889961db0760c2f9a8e2b91cb1c)

2023-04-14 08:34 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/InteropProcessor.kt
>              }
Added explanationa sa TODO in [dadd83f](https://github.com/corda/corda-runtime-os/pull/3499/commits/dadd83f74f852889961db0760c2f9a8e2b91cb1c), yes the code very confusing at the moment, but is improved in the follow up PR for the next ticket.

2023-04-14 13:26 UTC, SaurabhR3 approved these changes

2023-04-14 13:45 UTC, merged