CORE-10407: Resolve warnings related to Java modules.
corda/corda-runtime-os pull request #3522
Opened 2023-03-30 22:16 UTC by chrisr3

Open Java modules to prevent warnings about "illegal access".

Also fix some general Gradle warnings about deprecated APIs.

2023-03-31 14:49 UTC, vkolomeyko approved these changes
LGTM (on behalf of @corda/rest )

2023-03-31 14:55 UTC, mcgovc approved these changes
LGTM - build changes

2023-03-31 15:14 UTC, fowlerrr approved these changes
LGTM

2023-03-31 15:18 UTC, driessamyn commented
Please don't merge this until the api breaking changes that are needed for today's deadline.

2023-03-31 15:20 UTC, chrisr3 commented
> Please don't merge this until the api breaking changes that are needed for today's deadline.

This isn't about APIs, it's just Gradle and Bnd.

2023-03-31 15:21 UTC, driessamyn commented
> > Please don't merge this until the api breaking changes that are needed for today's deadline.
> 
> This isn't about APIs, it's just Gradle and Bnd.

I know, but those merges have priority. We don't want conflicts. See comms on the channel.

2023-03-31 15:27 UTC, chrisr3 commented
> I know, but those merges have priority. We don't want conflicts. See comms on the channel.

What kind of 11:59:59.9999 hour kind of change could be conflicting with this PR?! Is someone trying to remove OSGi before Beta3?

2023-03-31 15:33 UTC, yift-r3 commented on components/membership/registration-impl/build.gradle
> +    integrationTestRuntimeOnly project(':components:membership:membership-persistence-client-impl')
We have the `components/membership/registration-impl/src/integrationTest/kotlin/net/corda/membership/impl/registration/dummy/TestMembershipPersistenceClientImpl.kt` to avoid adding this dependency.

2023-03-31 15:38 UTC, fowlerrr requested changes
Just holding this until the "Big Merge" is done

2023-03-31 15:39 UTC, driessamyn commented
> > I know, but those merges have priority. We don't want conflicts. See comms on the channel.
> 
> What kind of 11:59:59.9999 hour kind of change could be conflicting with this PR?! Is someone trying to remove OSGi before Beta3?

It's a 53 file change. Not worth the risk. There is no reason for this to go in today, unlike the other 3 PRs that are lined up to go in shortly.

2023-03-31 15:56 UTC, chrisr3 commented on components/membership/registration-impl/build.gradle
> +    integrationTestRuntimeOnly project(':components:membership:membership-persistence-client-impl')
> We have the `components/membership/registration-impl/src/integrationTest/kotlin/net/corda/membership/impl/registration/dummy/TestMembershipPersistenceClientImpl.kt` to avoid adding this dependency.

Unfortunately it's currently required to provide `MembershipQueryClientImpl`, and no alternative is available. This module clearly has issues, but I don't know what the "correct" fix is. The best I've been able to do is enable "service resolving" to verify that everything is present.

2023-03-31 15:59 UTC, yift-r3 commented on components/membership/registration-impl/build.gradle
> +    integrationTestRuntimeOnly project(':components:membership:membership-persistence-client-impl')
We can create a dummy `MembershipQueryClient` in the same way we do a dummy for the `MembershipPersistenceClient`. Having the actual client implementation without the service will cause a lot of pain...

2023-03-31 16:34 UTC, fowlerrr approved these changes
Unblocking.  Still good.

2023-04-01 10:50 UTC, chrisr3 commented on components/membership/registration-impl/build.gradle
> +    integrationTestRuntimeOnly project(':components:membership:membership-persistence-client-impl')
You (as in "the platform network team") can resolve this issue however you see fit, _in a subsequent PR_. This _particular_ PR concerns "resolving warnings related to Java modules", and it has high-lighted an _existing_ issue with these OSGi tests.

2023-04-03 08:09 UTC, yift-r3 approved these changes
Ticket for additional work created

2023-04-03 08:09 UTC, yift-r3 commented on components/membership/registration-impl/build.gradle
> +    integrationTestRuntimeOnly project(':components:membership:membership-persistence-client-impl')
https://r3-cev.atlassian.net/browse/CORE-12212 created. Any other things we need to do?

2023-04-03 08:21 UTC, merged