CORE-11759: Add support for Corda Prometheus PodMonitor
corda/corda-runtime-os pull request #3536
Opened 2023-04-03 11:26 UTC by oscardalmau-r3

2023-04-03 16:39 UTC, davidcurrie requested changes

2023-04-03 16:39 UTC, davidcurrie commented on charts/corda/values.yaml
> +podMonitor:
This should be under `metrics`

2023-04-03 16:39 UTC, davidcurrie commented on charts/corda-lib/templates/_helpers.tpl
> +  name: corda
the name should take into account the Helm release

2023-04-03 16:39 UTC, davidcurrie commented on charts/corda-lib/templates/_helpers.tpl
> +      app.kubernetes.io/name: corda
this should use the `corda.name` function as we do when generating the label

2023-04-03 16:39 UTC, davidcurrie commented on charts/corda-lib/templates/_helpers.tpl
> +  jobLabel: corda
can't remember how this is used but should it also use the release name?

2023-04-03 16:39 UTC, davidcurrie commented on charts/corda/values.schema.json
> +                    "title": "labels that can be used so PodMonitor is discovered by Prometheus",
be consistent about "pod monitor" or "PodMonitor"

2023-04-03 16:39 UTC, davidcurrie commented on charts/corda/values.schema.json
> +                    "type": "object",
can we be more precise about the properties of this object?

2023-04-04 10:09 UTC, oscardalmau-r3 commented on charts/corda/values.yaml
> +podMonitor:
Done

2023-04-04 10:09 UTC, oscardalmau-r3 commented on charts/corda-lib/templates/_helpers.tpl
> +  name: corda
Done - sorry I forgot about this

2023-04-04 10:09 UTC, oscardalmau-r3 commented on charts/corda-lib/templates/_helpers.tpl
> +      app.kubernetes.io/name: corda
Done

2023-04-04 10:09 UTC, oscardalmau-r3 commented on charts/corda-lib/templates/_helpers.tpl
> +  jobLabel: corda
Done

2023-04-04 10:09 UTC, oscardalmau-r3 commented on charts/corda/values.schema.json
> +                    "title": "labels that can be used so PodMonitor is discovered by Prometheus",
Done

2023-04-04 10:11 UTC, oscardalmau-r3 commented on charts/corda/values.schema.json
> +                    "type": "object",
@davidcurrie I don't think we can. In the `non-functional-tests` we use `release` key, but Prometheus can be installed in different ways and `release` may not be an option always.

2023-04-04 11:10 UTC, davidcurrie approved these changes
👍

2023-04-04 11:36 UTC, merged