CORE-12177 - Flow External Messaging - Add vNode route building
corda/corda-runtime-os pull request #3538
Opened 2023-04-03 14:00 UTC by filipesoliveira

Updated the code so that the route configuration is generated based on the route default and channels configuration.
The route configuration is stored as part of the virtual node.
Added the test `ExternalMessagingRouteConfigGeneratorTest` to ensure the generated configuration is generated correctly.
Added the test `ExternalMessagingConfigProviderTest` to ensure the ExternalMessaging configuration is converted correctly from a `SmartConfig` type to a dto.
The test `ExternalChannelsConfigValidatorTest` has been updated based recent changes to the API and has been enabled again.

2023-04-03 14:01 UTC, filipesoliveira commented
This ticket depends on https://github.com/corda/corda-runtime-os/pull/3526.

2023-04-03 14:12 UTC, filipesoliveira commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/CpiMetadataLite.kt
> +    val cpks: Set<CpkMetadata> = emptySet()   // Todos: The default value must be removed.
I am looking at this at the moment.

2023-04-03 14:21 UTC, owenstanford commented on libs/external-messaging/src/main/kotlin/net/corda/libs/external/messaging/ExternalMessagingRouteConfigGeneratorImpl.kt
> +                // Todo: The following conversion should be placed in a more generic place
I would be tempted to move this to it's own config provider class, that you inject in, at some point we will extend the config to use vnode defaults with a global defaults fallback.
```
interface ExternalMessaginingConfigProvider
{
 fun getDefaults(): ExternalMessagingConfigDefaults 
} 
```

2023-04-03 14:26 UTC, owenstanford commented on libs/external-messaging/src/main/kotlin/net/corda/libs/external/messaging/ExternalMessagingRouteConfigGeneratorImpl.kt
> +        return ExternalMessagingRouteConfigSerializerImpl().serialize(
inject in the serializer it will make testing much easier/cleaner

2023-04-03 14:29 UTC, owenstanford commented on libs/external-messaging/src/main/kotlin/net/corda/libs/external/messaging/ExternalMessagingRouteConfigGeneratorImpl.kt
> +            val mapper = jacksonObjectMapper()
I'd create a serializer that can be passed in to avoid the need for testing serialization as part of the route gen, it's probably reasonable to add this as a method to the ExternalMessagingRouteConfigSerializer maybe needs a more generic name

2023-04-03 14:53 UTC, owenstanford commented on libs/external-messaging/src/main/kotlin/net/corda/libs/external/messaging/entities/ChannelType.kt
> +    SEND("send"),
lets update the schema for channels in the API repo to use `SEND` and `SEND_RECEIVE` and we can then use a simple enum, also this will align with the capitalization of the enum in the routes default

2023-04-03 15:53 UTC, filipesoliveira commented on libs/external-messaging/src/main/kotlin/net/corda/libs/external/messaging/entities/ChannelType.kt
> +    SEND("send"),
Great. That will make the code a lot better.

2023-04-03 15:53 UTC, filipesoliveira commented on libs/external-messaging/src/main/kotlin/net/corda/libs/external/messaging/entities/ChannelType.kt
> +    SEND("send"),
PR for the API: https://github.com/corda/corda-api/pull/1035

2023-04-03 17:08 UTC, filipesoliveira commented on libs/external-messaging/src/main/kotlin/net/corda/libs/external/messaging/ExternalMessagingRouteConfigGeneratorImpl.kt
> +            val mapper = jacksonObjectMapper()
I created a separate class called `ExternalMessagingChannelConfigSerializer`.

2023-04-06 16:19 UTC, owenstanford commented on libs/external-messaging/build.gradle
> +    implementation project(path: ':libs:virtual-node:virtual-node-info')
why the `path: `?

2023-04-06 16:22 UTC, owenstanford commented on libs/external-messaging/src/main/kotlin/net/corda/libs/external/messaging/ExternalMessagingConfigProviderImpl.kt
> +
blank line

2023-04-06 16:28 UTC, filipesoliveira commented on libs/external-messaging/build.gradle
> +    implementation project(path: ':libs:virtual-node:virtual-node-info')
This line was added by IntelliJ. I will fix it.

2023-04-11 08:15 UTC, ronanbrowne requested changes

2023-04-11 08:15 UTC, ronanbrowne commented on components/virtual-node/virtual-node-write-service-impl/build.gradle
> +    implementation project(path: ':libs:external-messaging')
you don't need the path keyword here. 
```suggestion
    implementation project(':libs:external-messaging')
```

2023-04-11 08:28 UTC, filipesoliveira commented on components/virtual-node/virtual-node-write-service-impl/build.gradle
> +    implementation project(path: ':libs:external-messaging')
Yes, you are right. I though I had removed all of them.

2023-04-11 08:30 UTC, ronanbrowne submitted a review, later dismissed
LGTM (Just Gradle changes reviewed)

2023-04-11 08:42 UTC, vkolomeyko commented on components/chunking/chunk-db-write-impl/src/test/kotlin/net/corda/chunking/db/impl/validation/ExternalChannelsConfigValidatorTest.kt
>  class ExternalChannelsConfigValidatorTest {
I wonder if we should have this class in `net.corda.chunking.db.impl.validation` package?

To me chunking has to do with CPI upload in chunks, whereas here we are performing validation of the CPK metadata.
Similarly I wonder if it is a good idea for `ExternalChannelsConfigValidator` to be in `net.corda.chunking.db.impl.validation` package? Possibly, it may be better to place it under `net.corda.libs.packaging.core` or `net.corda.libs.packaging.core.validation` ?

2023-04-11 09:52 UTC, filipesoliveira commented on components/chunking/chunk-db-write-impl/src/test/kotlin/net/corda/chunking/db/impl/validation/ExternalChannelsConfigValidatorTest.kt
>  class ExternalChannelsConfigValidatorTest {
I understand that the `ExternalChannelsConfigValidator` is not in the best place. But let's do that change has part of another PR. Btw, would it be better to move the class to the package `net.corda.libs.configuration.validation` since the `ExternalChannelsConfigValidator` depends on `ConfigurationValidatorFactory`?

2023-04-11 09:54 UTC, filipesoliveira commented on components/chunking/chunk-db-write-impl/src/test/kotlin/net/corda/chunking/db/impl/validation/ExternalChannelsConfigValidatorTest.kt
>  class ExternalChannelsConfigValidatorTest {
Another note about the same topic. More work should be done to move the other classes that also live under the package `net.corda.chunking.db.impl.validation`.

![image](https://user-images.githubusercontent.com/6329837/231125332-589c0870-dd21-4366-9475-e313de806de2.png)

2023-04-11 09:54 UTC, vkolomeyko commented on components/chunking/chunk-db-write-impl/src/test/kotlin/net/corda/chunking/db/impl/validation/ExternalChannelsConfigValidatorTest.kt
>  class ExternalChannelsConfigValidatorTest {
Yes, definitely let's make do those changes as a separate PR.
As for best packages/modules, let's sync-up when @owenstanford is back.

2023-04-11 10:05 UTC, filipesoliveira commented on components/chunking/chunk-db-write-impl/src/test/kotlin/net/corda/chunking/db/impl/validation/ExternalChannelsConfigValidatorTest.kt
>  class ExternalChannelsConfigValidatorTest {
Since other people have also made the same suggestion, I have created a ticket to ensure this is not left behind.
Ticket:
https://r3-cev.atlassian.net/browse/CORE-12396

2023-04-11 13:51 UTC, kyriathar approved these changes
I think `CpiMetadataLite` was meant to be lite, it didn't hold cpks metadata, maybe now no longer needed if returned from all repository functions? Or if only needed for one of them maybe we could return some pair of CpiMetadataLite + cpks to keep others "lite"?

2023-04-11 13:54 UTC, filipesoliveira commented
> [kyriathar](/kyriathar)

I was planning to remove the `CpiMetadaLite` in https://r3-cev.atlassian.net/browse/CORE-12392 to simplify the code.

2023-04-11 13:55 UTC, kyriathar commented
Yeah, only just saw that PR, cool thank you!

2023-04-11 14:16 UTC, vkolomeyko approved these changes
LGTM

2023-04-11 15:10 UTC, ronanbrowne approved these changes

2023-04-11 15:11 UTC, merged