CORE-12378: implenet support methods to reduce duplciation
corda/corda-runtime-os pull request #3580
Opened 2023-04-09 20:54 UTC by ronanbrowne

Following on from

https://github.com/corda/corda-shared-build-pipeline-steps/pull/708

and https://github.com/corda/corda5-enterprise/pull/34

implement the support methods migrated to the Jenkins Shared library project to reduce duplication between this combined worker job and the Enterprise implementation

2023-04-09 20:54 UTC, ronanbrowne commented on .ci/e2eTests/JenkinsfileCombinedWorker
> +@Library('corda-shared-build-pipeline-steps@CORE-12378-C5-Ent-pipeline-support') _
temp while testing

2023-04-11 15:04 UTC, yarivus requested changes

2023-04-11 15:04 UTC, yarivus commented on .ci/e2eTests/JenkinsfileCombinedWorker
> +                script {
why does this need a script { } scope ?

2023-04-11 15:04 UTC, yarivus commented on .ci/e2eTests/JenkinsfileCombinedWorker
> +                script {
same comment as prev

2023-04-11 18:54 UTC, ronanbrowne commented on .ci/e2eTests/JenkinsfileCombinedWorker
> +                script {
@yarivus you can not call a method on a object in a Jenkins declarative scrip pipeline , such as 

`pipelineUtils.createPostgresDatabase(postgresPort, postgresHost, postgresDb, postgresCredentialsId)
`

it simply will not compile without being in a script block, we did not previously need this as we used a different approach, we were simply calling a method which already existed in this class so no object declaration needed

2023-04-11 18:54 UTC, ronanbrowne commented on .ci/e2eTests/JenkinsfileCombinedWorker
> +                script {
see answer above

2023-04-12 18:37 UTC, yarivus approved these changes
LGTM

2023-04-14 06:15 UTC, merged