Dickon/core 9790 helm changes
corda/corda-runtime-os pull request #3610
Opened 2023-04-13 13:09 UTC by dickon

2023-04-13 16:11 UTC, davidcurrie requested changes

2023-04-13 16:11 UTC, davidcurrie commented on charts/corda-lib/templates/_bootstrap.tpl
> +           {{- if and (hasKey .Values "config") (hasKey .Values.config "vault") (hasKey .Values.config.vault "url") -}}
I believe this is dangerous as it relies on you being on a version of Helm that is built with a version of go that supported lazy evaluation in templates. There's a hack to handle the chained nulls which is to introduce parentheses e.g. `if ((.Values.config).vault).url`

2023-04-14 11:36 UTC, dickon commented on charts/corda-lib/templates/_bootstrap.tpl
> +           {{- if and (hasKey .Values "config") (hasKey .Values.config "vault") (hasKey .Values.config.vault "url") -}}
Okay, I didn't know that was maybe unsupported sometimes. Fixed.

2023-04-14 13:20 UTC, simon-johnson-r3 requested changes

2023-04-14 13:20 UTC, simon-johnson-r3 commented on kubernetes-deploy.sh
> +#! /bin/zsh
This is a mac specific script, I'm not sure how popular it will be to commit it to git to the OS repo. It means someone has to maintain it always, and there's no test for that. And we'd probably want equivalents for Linux and Windows. I guess at the very least it would have to be named appropriately for the platform.

I wonder if this is one of those cases where whilst clearly useful, it's probably easier to maintain these some other way outside the repo for internal developer use then get into the wider discussion?

I note the upcoming hackathon has "Tools for Corda" as one of its topics, perhaps this would be a good time to assess stuff like this?

2023-04-14 13:20 UTC, simon-johnson-r3 commented on charts/corda-lib/templates/_bootstrap.tpl
> +        {{- if (((.Values).config).vault).url }}
I assume the brackets are necessary here?

2023-04-14 13:20 UTC, simon-johnson-r3 commented on charts/corda-lib/templates/_bootstrap.tpl
> +        {{- include "corda.generateAndExecuteSql" ( dict "name" "db" "Values" .Values "Chart" .Chart "Release" .Release "schema" "RBAC" "namePostfix" "schemas" "sequenceNumber" 1) | nindent 8 }}
Sequence numbers might be inconvenient to maintain as inserting steps will mean changing multiple lines.
I see we already have name, do these really add anything?

2023-04-14 13:20 UTC, simon-johnson-r3 commented on charts/corda-lib/templates/_bootstrap.tpl
> +        - name: 14-apply-db-secrets-to-vault
These 2 curl commands were in my PoC but we agreed to remove them and instead have them pushed by the CI pipeline. They should be deleted from here.

2023-04-14 13:50 UTC, dickon commented on charts/corda-lib/templates/_bootstrap.tpl
> +        - name: 14-apply-db-secrets-to-vault
We should still be able to support efficient local installation of Enterprise Corda, and in particular the Vault support.

2023-04-14 13:59 UTC, dickon commented on charts/corda-lib/templates/_bootstrap.tpl
> +        {{- include "corda.generateAndExecuteSql" ( dict "name" "db" "Values" .Values "Chart" .Chart "Release" .Release "schema" "RBAC" "namePostfix" "schemas" "sequenceNumber" 1) | nindent 8 }}
Without sequence numbers, it is not clear that there's a strict ordering with sequential dependencies  on these init containers. That confused me for a bit. Both `k9s` and `kubectl describe pod` sort the init containers by name, which obscures the sequential ordering and makes it look like there are no dependencies.

With the sequence numbers, I think it is more clear in `k9s` and the other tools which following the sorting convention what's happening:

![Screenshot 2023-04-13 at 17 09 15](https://user-images.githubusercontent.com/266672/232063407-04ba2674-9955-4635-8895-9d88863b50ee.png)

and if something does go wrong you can tell at a glance which it is.

I do agree there's a little overhead in maintaining the numbering, but since operating the helm chart and looking at the current status is much more common than authoring it we should optimise for reading.

2023-04-14 14:00 UTC, dickon commented on charts/corda-lib/templates/_bootstrap.tpl
> +        {{- if (((.Values).config).vault).url }}
They are. @davidcurrie believes some versions of helm do not have short-circuit evaluation logic, but for an obscure reason this structure stops Helm printing an error if vault is not mentioined in the Values.

2023-04-14 14:02 UTC, davidcurrie commented on charts/corda-lib/templates/_bootstrap.tpl
> +        {{- if (((.Values).config).vault).url }}
Obscure it certainly is. See https://stackoverflow.com/questions/59795596/how-to-make-nested-variables-optional-in-helm for the details.

2023-04-14 14:08 UTC, simon-johnson-r3 commented on charts/corda-lib/templates/_bootstrap.tpl
> +        - name: 14-apply-db-secrets-to-vault
This is as per https://r3holdco.slack.com/archives/C0527PCBKTR/p1681214437759929 if you want to deviate from this plan, you should probably take it to that channel again.

2023-04-18 16:45 UTC, dickon commented on charts/corda-lib/templates/_bootstrap.tpl
> +        - name: 14-apply-db-secrets-to-vault
This is gone now.

2023-04-19 07:46 UTC, simon-johnson-r3 approved these changes, later dismissed

2023-04-19 10:19 UTC, davidcurrie reviewed
nothing all that substantive...

2023-04-19 10:19 UTC, davidcurrie commented on charts/corda-lib/templates/_bootstrap.tpl
> +        {{- include "corda.generateAndExecuteSql" ( dict "name" "rpc"  "Values" .Values "Chart" .Chart "Release" .Release "environmentVariablePrefix" "REST_API_ADMIN"  "schema" "RBAC"  "searchPath" "
not your doing but this should probably be called `rest` now rather than `rpc`

2023-04-19 10:19 UTC, davidcurrie commented on charts/corda-lib/templates/_bootstrap.tpl
> +- name: {{ printf "%02d" .sequenceNumber }}-create-{{ .name }}
nit
```suggestion
- name: {{ printf "%02d-create-%s" .sequenceNumber .name }}
```

2023-04-19 10:19 UTC, davidcurrie commented on charts/corda-lib/templates/_bootstrap.tpl
> +- name: {{ printf "%02d" (add .sequenceNumber 1)}}-apply-{{ .name }}
```suggestion
- name: {{ printf "%02d-apply-%s" (add .sequenceNumber 1) .name }}
```

2023-04-19 10:19 UTC, davidcurrie commented on kubernetes-deploy.sh
> +  --values ../corda-runtime-os/values-prereqs.yaml \
if the script has to be run from the root of `corda-runtime-os`, why the path?

2023-04-19 10:19 UTC, davidcurrie commented on kubernetes-deploy.sh
> +helm upgrade --install corda -n corda charts/corda \
nit: shouldn't matter given we're cleaning out the namespace anyway but just to make a point...
```suggestion
helm install corda -n corda charts/corda \
```

2023-04-19 10:19 UTC, davidcurrie commented on kubernetes-deploy.sh
> +./gradlew publishOSGiImage
This is only going to work for Docker Desktop users. Do we want to try and detect if they're using minikube and do the `eval $(minikube docker-env)` if so? Not doing it is a common reason for failed deployments for minikube users. If nothing else, maybe it should be in the script but commented out?

2023-04-19 10:19 UTC, davidcurrie commented on kubernetes-deploy.sh
> +# Currently the init containers are not repeatble, so ensure we start from scratch each time
```suggestion
# Currently the init containers are not repeatable, so ensure we start from scratch each time
```

2023-04-19 13:44 UTC, dickon commented on charts/corda-lib/templates/_bootstrap.tpl
> +        {{- include "corda.generateAndExecuteSql" ( dict "name" "rpc"  "Values" .Values "Chart" .Chart "Release" .Release "environmentVariablePrefix" "REST_API_ADMIN"  "schema" "RBAC"  "searchPath" "
changed

2023-04-19 13:44 UTC, dickon commented on charts/corda-lib/templates/_bootstrap.tpl
> +- name: {{ printf "%02d" .sequenceNumber }}-create-{{ .name }}
done

2023-04-19 13:45 UTC, dickon commented on kubernetes-deploy.sh
> +  --values ../corda-runtime-os/values-prereqs.yaml \
I wondered about that (inherited that logic from Simon). Maybe it's because it gives a nicer error if the charts cannot be found but that's tenuous. Simplified.

2023-04-19 13:46 UTC, dickon commented on kubernetes-deploy.sh
> +helm upgrade --install corda -n corda charts/corda \
done

2023-04-19 13:46 UTC, dickon commented on kubernetes-deploy.sh
> +# Currently the init containers are not repeatble, so ensure we start from scratch each time
done

2023-04-19 14:14 UTC, dickon commented on kubernetes-deploy.sh
> +./gradlew publishOSGiImage
Added commented out

2023-04-19 14:47 UTC, dickon commented on charts/corda-lib/templates/_bootstrap.tpl
> +- name: {{ printf "%02d" (add .sequenceNumber 1)}}-apply-{{ .name }}
done

2023-04-19 14:47 UTC, dickon commented on kubernetes-deploy.sh
> +./gradlew publishOSGiImage
done

2023-04-19 15:43 UTC, davidcurrie approved these changes
LGTM

2023-04-19 16:22 UTC, merged