CORE-12304 Cascade Intermittent Unavailability Caused by DB Worker Restart
corda/corda-runtime-os pull request #3611
Opened 2023-04-13 13:29 UTC by kyriathar

2023-04-13 15:22 UTC, simon-johnson-r3 commented on components/configuration/configuration-read-service-impl/src/main/kotlin/net/corda/configuration/read/impl/ConfigReadServiceEventHandler.kt
> -        avroSubReg = coordinator.followStatusChangesByName(setOf(sub.subscriptionName))
by removing these, this component's UP and DOWN status is no longer tethered to the UP and DOWN status of the subscriptions, I'm not sure this is what you really want is it?

2023-04-13 15:51 UTC, kyriathar commented on components/configuration/configuration-read-service-impl/src/main/kotlin/net/corda/configuration/read/impl/ConfigReadServiceEventHandler.kt
> -        avroSubReg = coordinator.followStatusChangesByName(setOf(sub.subscriptionName))
Good catch, yeah no longer needed the UP for it, as we now intend to mark config read service as `UP` after `ConfigProcessor.onSnapshot` has run, but the `DOWN`s/ `ERROR`s are now disconnected indeed.

2023-04-14 09:02 UTC, kyriathar commented on components/configuration/configuration-read-service-impl/src/main/kotlin/net/corda/configuration/read/impl/ConfigReadServiceEventHandler.kt
> -        avroSubReg = coordinator.followStatusChangesByName(setOf(sub.subscriptionName))
Brought back following the subscriptions to follow their `DOWN`s/ `ERROR`s

2023-04-17 15:11 UTC, fowlerrr requested changes
I think the bulk of the change is okay but I'm not comfortable with that change to `LifecycleTest`.  I think we need to keep the lambdas from getting out of control

2023-04-17 15:11 UTC, fowlerrr commented on libs/lifecycle/lifecycle-test-impl/src/main/kotlin/net/corda/lifecycle/test/impl/LifecycleTest.kt
> +        onUppingDependency: () -> Unit = {}
I think `onDependencyUp` would be clearer, though I'm not sure we need yet-another-lambda here.  Probably better to repurpose `verificationWhenUp` and change the names to something that means "do verification and/or other tasks".  No idea what that name would be though... 🤔

2023-04-17 15:28 UTC, kyriathar commented on libs/lifecycle/lifecycle-test-impl/src/main/kotlin/net/corda/lifecycle/test/impl/LifecycleTest.kt
> +        onUppingDependency: () -> Unit = {}
Renamed as proposed and also introduced `onDependencyDown` as discussed offline

2023-04-17 15:38 UTC, fowlerrr approved these changes

2023-04-18 15:43 UTC, kyriathar commented
Closing as we already have the above behavior through `CompactedSubscriptionImpl`

2023-04-18 15:43 UTC, closed without merging