CORE-12374: Create new helm pipeline
corda/corda-runtime-os pull request #3614
Opened 2023-04-13 14:30 UTC by knguyen-r3

Added new file `Jenkinsfile_PublishHelmChart` to allow independent publishing of Helm charts without being tied to the PR gates of a repo.

This new job will _not_ be a PR gate but rather an on-demand utility job a developer may use to produce charts for a downstream consumer (non-functional tests etc.)

**Tested:** https://ci02.dev.r3.com/job/Corda5/job/Publish%20Helm%20Pipeline/job/PR-3614/

2023-04-14 14:41 UTC, yarivus requested changes

2023-04-14 14:41 UTC, yarivus commented on .ci/PublishHelmChart/Jenkinsfile_PublishHelmChart
> +import com.r3.build.enums.BuildEnvironment
```suggestion

import com.r3.build.enums.BuildEnvironment
```

2023-04-14 14:41 UTC, yarivus commented on .ci/PublishHelmChart/Jenkinsfile_PublishHelmChart
> +}
unify:
```
def gradlewMinimumLogging(String... args) {
    def allArgs = args.join(' ')
    sh "${isUnix() ? './gradlew' : './gradlew.bat'} ${allArgs} \${GRADLE_ADDITIONAL_ARGS} \${GRADLE_PERFORMANCE_TUNING}"
}
```

2023-04-14 20:04 UTC, ronanbrowne requested changes

2023-04-14 20:04 UTC, ronanbrowne commented on .ci/PublishHelmChart/Jenkinsfile_PublishHelmChart
> +                        renderWidget("Published Corda helm chart repo name: ${publishingUtils.getHelmRepo()}")
On further consideration, the Full OCI path of the helm chart would be beneficial to render, not just the repo name

i.e.
oci://corda-os-docker.software.r3.com/helm-charts/PR-123/corda 

all this information is available to be built up from the ENV vars you have set above

2023-04-14 20:05 UTC, ronanbrowne requested changes

2023-04-14 20:05 UTC, ronanbrowne commented on .ci/PublishHelmChart/Jenkinsfile_PublishHelmChart
> +        GRADLE_ADDITIONAL_ARGS = ''
this servers no purpose in this job, remove

2023-04-17 13:16 UTC, ronanbrowne requested changes

2023-04-17 13:16 UTC, ronanbrowne commented on .ci/PublishHelmChart/Jenkinsfile_PublishHelmChart
> +            */
Duplicate comment, we don't need it twice, once at the publishing stage will suffice, remove from here please

2023-04-17 13:16 UTC, ronanbrowne commented on .ci/PublishHelmChart/Jenkinsfile_PublishHelmChart
> +            /*
I know this was a copy and paste, but for clarity here, please add an example of each type of publishing. 

e.g.

```suggestion
            * Release tag          corda-os-docker-stable.software.r3.com/helm-charts/<branch-name>      <CHART_VERSION>
            * e.g.  corda-os-docker-stable.software.r3.com/helm-charts/5.0.0.0-Beta3/corda
            *
            * Release/main branch  corda-os-docker-unstable.software.r3.com/helm-charts/<branch-name>    <CHART_VERSION>-beta.<TIMESTAMP>
            * e.g. corda-os-docker-unstable.software.r3.com/helm-charts/release/os/5.0/corda
            *
            * PR / feature branch  corda-os-docker-dev.software.r3.com/helm-charts/<branch-name>         <CHART_VERSION>-alpha.<TIMESTAMP>
            * e.g. corda-os-docker-unstable.software.r3.com/helm-charts/PR-223/corda
            */

```

2023-04-17 13:20 UTC, yarivus reviewed
LGTM - but pending comments

2023-04-17 16:17 UTC, yarivus approved these changes
LGTM

2023-04-17 17:10 UTC, ronanbrowne approved these changes
LGTM

2023-04-18 08:22 UTC, merged