Ronanb/core 12505/fix dh sso issue
corda/corda-runtime-os pull request #3635
Opened 2023-04-17 15:04 UTC by ronanbrowne

2023-04-17 16:29 UTC, yarivus requested changes

2023-04-17 16:29 UTC, yarivus commented on buildSrc/src/main/groovy/DeployableContainerBuilder.groovy
> +        } else if ((dockerHubUsername.get() != null && !dockerHubUsername.get().isEmpty()) && (dockerHubPassword.get() != null && !dockerHubPassword.get().isEmpty())){
```suggestion
        } else if ((dockerHubUsername.get() != null && !dockerHubUsername.get().isEmpty()) &&
                   (dockerHubPassword.get() != null && !dockerHubPassword.get().isEmpty())) {
```

2023-04-17 17:28 UTC, yarivus submitted a review, later dismissed
LGTM

2023-04-17 20:06 UTC, ronanbrowne commented
Follow on change to use the same pattern for not just docker hub but Artifactory values, which an external user will also not have set

2023-04-18 08:35 UTC, yarivus approved these changes
LGTM

2023-04-18 13:18 UTC, merged