CORE-10430/ CORE-11971 - Integrating facades into platform
corda/corda-runtime-os pull request #3646
Opened 2023-04-18 13:45 UTC by julia-filipczak

2023-05-05 16:57 UTC, szymonsztuka approved these changes
Minor comments, one outstanding thing could be delegated to new PR/ticket.

2023-05-05 16:57 UTC, szymonsztuka commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/application/services/impl/interop/parameters/TypeParameters.kt
> +            ParameterTypeLabel.BOOLEAN.typeName -> RawParameterType<Boolean>(ParameterTypeLabel.BOOLEAN)
As discussed, let add TODO if quick win is harder to achieve - this looks as main part of wiring  `RawParameterType` with the `ParameterTypeLabel` but here looks like exposed and not "object oriented".
Could for example `RawParameterType` had a constructor in which it would create a respective  `ParameterTypeLabel` ?

2023-05-05 16:57 UTC, szymonsztuka commented on components/flow/flow-service/src/test/kotlin/net/corda/flow/application/services/interop/facade/FacadeSpec.kt
> +        println(inputStream)
Remove `println`, Dom left this wile preparing for the company presentation.

2023-05-05 16:57 UTC, szymonsztuka commented on components/flow/flow-service/src/test/kotlin/net/corda/flow/application/services/interop/facade/FacadeSpec.kt
> +               //TODO originally it was using "Java's" implied "name" field of an enum
We can remove this TODO?

2023-05-05 17:41 UTC, szymonsztuka commented on components/flow/flow-service/build.gradle
> +    testImplementation "io.kotest:kotest-runner-junit5:5.5.4"
We can add TODO that removal of kotest is scheduled for in the other ticket (provide ticket number)

2023-05-06 19:52 UTC, yarivus requested changes

2023-05-06 19:52 UTC, yarivus commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/application/services/impl/interop/binding/FacadeInterfaceBinding.kt
> +     */
```suggestion
    /**
     * Obtain the [FacadeInParameterBinding] for the method parameter at the given index
     * @param parameterIndex The index of the method parameter to get the binding for
     */
```

Please change in other places

2023-05-06 19:52 UTC, yarivus commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/application/services/impl/interop/facade/FacadeImpl.kt
> +        //TODO address !!
TODO ?

2023-05-06 19:52 UTC, yarivus commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/application/services/impl/interop/facade/FacadeImpl.kt
> +        //TODO address !!
see other TODOs

2023-05-06 19:52 UTC, yarivus commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/application/services/impl/interop/proxies/JacksonJsonMarshaller.kt
> +
redundant newline

2023-05-06 19:52 UTC, yarivus commented on components/flow/flow-service/src/test/kotlin/net/corda/flow/application/services/interop/facade/JsonSerialisationSpec.kt
> +            )
seems your indentation here is off ... thus 2 consecutive ')' under each other

2023-05-08 11:16 UTC, yarivus approved these changes
LGTM

2023-05-08 14:51 UTC, yarivus approved these changes
LGTM

2023-05-09 16:12 UTC, yarivus approved these changes
LGTM

2023-05-11 12:21 UTC, merged

2023-05-11 17:10 UTC, yarivus reviewed
thx @szymonsztuka