CORE-12440: Increase External Event Logging
corda/corda-runtime-os pull request #3656
Opened 2023-04-19 12:05 UTC by jujoramos

Update flow external event manager so it registers under INFO log level
whenever external events are sent or received.

2023-04-28 10:05 UTC, JamesHR3 reviewed
Couple of thoughts.

2023-04-28 10:05 UTC, JamesHR3 commented on components/crypto/crypto-service-impl/src/main/kotlin/net/corda/crypto/service/impl/bus/CryptoFlowOpsBusProcessor.kt
> +        return withMDC(mdc) {
I wonder if this return actually makes this code harder to read, particularly with the nested returns that then bubble up to the `withMDC` level rather than exiting this function.

2023-04-28 10:05 UTC, JamesHR3 commented on components/crypto/crypto-service-impl/src/main/kotlin/net/corda/crypto/service/impl/bus/CryptoFlowOpsBusProcessor.kt
> +                    logger.error(
I think this log should be a `warn` rather than `error`, particularly as it's transient. (Appreciate this isn't something you've changed though.)

2023-04-28 10:05 UTC, JamesHR3 commented on components/crypto/crypto-service-impl/src/main/kotlin/net/corda/crypto/service/impl/bus/CryptoFlowOpsBusProcessor.kt
> +
Did this autoformat? Might be worth getting rid of the whitespace here.

2023-04-28 10:05 UTC, JamesHR3 commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/impl/FlowMDCServiceImpl.kt
> +        const val MDC_SESSION_EVENT_ID = "session.event.id"
Should these constants also be in `net.corda.utilities`? Feels like we have a split of where these constants live.

2023-04-28 10:10 UTC, jujoramos commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/impl/FlowMDCServiceImpl.kt
> +        const val MDC_SESSION_EVENT_ID = "session.event.id"
I wasn't sure whether these ones are only pertinent to flows or not, that's why I didn't move them to `net.corda.utilities` directly. Makes sense to have them all in the same place, though, I'll make the change.

2023-04-28 10:16 UTC, jujoramos commented on components/crypto/crypto-service-impl/src/main/kotlin/net/corda/crypto/service/impl/bus/CryptoFlowOpsBusProcessor.kt
> +                    logger.error(
👍

2023-04-28 10:17 UTC, jujoramos commented on components/crypto/crypto-service-impl/src/main/kotlin/net/corda/crypto/service/impl/bus/CryptoFlowOpsBusProcessor.kt
> +
👍

2023-04-28 11:33 UTC, jujoramos commented on components/crypto/crypto-service-impl/src/main/kotlin/net/corda/crypto/service/impl/bus/CryptoFlowOpsBusProcessor.kt
> +        return withMDC(mdc) {
Done

2023-04-28 11:34 UTC, jujoramos commented on components/crypto/crypto-service-impl/src/main/kotlin/net/corda/crypto/service/impl/bus/CryptoFlowOpsBusProcessor.kt
> +    override fun onNext(events: List<Record<String, FlowOpsRequest>>): List<Record<*, *>> {
RequestId and FlowId are now part of the MDC context for all logged messages, so I've removed `{ requestId: $requestId, key: $flowId }` from the message string itself.

2023-04-28 12:33 UTC, conalsmith-r3 submitted a review, later dismissed
lgtm

2023-04-28 15:29 UTC, vlajos submitted a review, later dismissed
LGTM.

2023-05-02 08:37 UTC, seanbrereton submitted a review, later dismissed
LGTM (gradle files only)

2023-05-02 08:49 UTC, fowlerrr commented on components/flow/flow-rest-resource-service-impl/src/main/kotlin/net/corda/flow/rest/impl/v1/FlowRestResourceImpl.kt
> +        val flowContextPlatformProperties = mapOf(
Very minor but may adjust the comment above?  "is the only property" isn't correct anymore.  Not worth waiting for a build if we want to get his in though.

2023-05-02 08:49 UTC, fowlerrr commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/external/events/impl/ExternalEventManagerImpl.kt
> +        log.info("Processing response for external event with id '{}'", requestId)
I'm not sure about raising the level of these.  We were asked to reduce the volume of logging above INFO level.

2023-05-02 08:49 UTC, fowlerrr commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/external/events/impl/ExternalEventManagerImpl.kt
> +        log.info("Dispatching external event with id '{}' to '{}'", externalEventState.requestId, eventToSend.topic)
Same here.  Are we introducing a lot more logging now?

2023-05-02 08:54 UTC, jujoramos commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/external/events/impl/ExternalEventManagerImpl.kt
> +        log.info("Processing response for external event with id '{}'", requestId)
I might have misunderstood @mnesbit 's comment the other day, but I think the idea is to be able to track down whenever an event leaves/enters any particular worker so yeah, we deliberately increased the level of this message.

2023-05-02 08:54 UTC, jujoramos commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/external/events/impl/ExternalEventManagerImpl.kt
> +        log.info("Dispatching external event with id '{}' to '{}'", externalEventState.requestId, eventToSend.topic)
Same as above, yes.

2023-05-02 08:57 UTC, driessamyn commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/external/events/impl/ExternalEventManagerImpl.kt
> +        log.info("Processing response for external event with id '{}'", requestId)
I agree with @fowlerrr . 
This feels to me like a tracing thing, not a logging thing.

2023-05-02 08:58 UTC, jujoramos commented on components/flow/flow-rest-resource-service-impl/src/main/kotlin/net/corda/flow/rest/impl/v1/FlowRestResourceImpl.kt
> +        val flowContextPlatformProperties = mapOf(
👍

2023-05-02 09:06 UTC, dickon reviewed
Nice. LGTM. I'd not looked much at MDC before but having consistent attributes we can pull out should be handy for difficult issues we might hit in the future.

2023-05-02 09:06 UTC, dickon commented on components/flow/flow-rest-resource-service-impl/src/test/kotlin/net/corda/flow/rest/impl/v1/FlowRestResourceImplTest.kt
> +        assertThatThrownBy {
Is there an issue with the previous Jupiter form of `assertThrows`? I don't really mind either way but without knowing any better I'd probably have used the slightly more compact variant we had before.

(I ask for the sake of general curiousity rather than any objection here).

2023-05-02 09:15 UTC, jujoramos commented on components/flow/flow-rest-resource-service-impl/src/test/kotlin/net/corda/flow/rest/impl/v1/FlowRestResourceImplTest.kt
> +        assertThatThrownBy {
No issues at all, just a matter of preference I guess. I had to add an extra assertion so went straight for `assertj`.

2023-05-02 09:39 UTC, jujoramos commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/external/events/impl/ExternalEventManagerImpl.kt
> +        log.info("Processing response for external event with id '{}'", requestId)
Just spoke with @JamesHR3 and @mnesbit regarding this: the amount of logging will certainly be increased across the board but it is still something we need in order to trace the entire flow execution across workers. We'll likely need to investigate tools and/or other formats in the future to reduce the amount of space required, but for the time being logging is what we have.

2023-05-02 09:44 UTC, kyriathar submitted a review, later dismissed
LGTM (crypto files)

2023-05-02 09:50 UTC, fowlerrr commented on components/flow/flow-rest-resource-service-impl/src/test/kotlin/net/corda/flow/rest/impl/v1/FlowRestResourceImplTest.kt
> +        assertThatThrownBy {
I prefer what you've put in.  It's slightly more readable, to me.

2023-05-02 09:50 UTC, fowlerrr submitted a review, later dismissed

2023-05-02 11:20 UTC, driessamyn commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/external/events/impl/ExternalEventManagerImpl.kt
> +        log.info("Processing response for external event with id '{}'", requestId)
Worth looping in @davidcurrie as it will have implications on the deployed cluster.

2023-05-02 11:24 UTC, driessamyn requested changes

2023-05-02 11:24 UTC, driessamyn commented on components/flow/flow-rest-resource-service-impl/src/test/kotlin/net/corda/flow/rest/impl/v1/FlowRestResourceImplTest.kt
The majority of change in this file are stylistic changes that have nothing to do with the purpose of this PR.
I think they should be undone. 
`AssertThrows` is consistently used across the codebase, so I don't think we need to change it for the sake of it.
It just makes reviewing the PR harder, which is already hard to review due to the source branch being on a fork.

2023-05-02 11:28 UTC, driessamyn commented on libs/utilities/src/main/kotlin/net/corda/utilities/LogUtils.kt
> +const val MDC_EXTERNAL_EVENT_ID = "corda.external.event.id"
Should these be corda-api if we expect users to be able to filter/search for these?

2023-05-02 11:44 UTC, jujoramos commented on components/flow/flow-rest-resource-service-impl/src/test/kotlin/net/corda/flow/rest/impl/v1/FlowRestResourceImplTest.kt
I'd argue that `assertj` is also consistently used across the code base 🤷‍♂️:

```
➜  corda-runtime-os git:(feature/CORE-12440) ✗ grep -I -R "org.assertj.core.api.Assertions" | sort | wc -l
     837
➜  corda-runtime-os git:(feature/CORE-12440) ✗ grep -I -R "org.junit.jupiter.api.Assertions" | sort | wc -l
     759
```

I've reverted the change, anyways.

---

Aside from that, we should probably choose a single testing library and go for it to prevent these frictions (same applies for the "branch on main repo" vs "branch on personal fork" approaches).

2023-05-02 12:20 UTC, davidcurrie commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/external/events/impl/ExternalEventManagerImpl.kt
> +        log.info("Processing response for external event with id '{}'", requestId)
Does it need to be at a level that we have enabled by default though vs modifying the level when we want to collect this information?

2023-05-02 12:21 UTC, driessamyn commented on components/flow/flow-rest-resource-service-impl/src/test/kotlin/net/corda/flow/rest/impl/v1/FlowRestResourceImplTest.kt
I agree both are used. My point is there's no point in changing just for the sake of preference, unless you're going to suggest standardizing on one and make the change across the board. Otherwise it's just bike shedding and that's expensive when half a dozen people need to review those changes.

> Aside from that, we should probably choose a single testing library and go for it to prevent these frictions

This may have been a good candidate to look at for the dev friction event. But this is only successful if it ends up removing one of the usages, not change the balance marginally from one to the other.

> same applies for the "branch on main repo" vs "branch on personal fork" approaches

I don't know anybody else in the team who uses personal forks.
I can't really see any advantages either.

2023-05-02 12:23 UTC, jujoramos commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/external/events/impl/ExternalEventManagerImpl.kt
> +        log.info("Processing response for external event with id '{}'", requestId)
Yes, the ask was to have this logged under the default `log-level` so any issues can be analysed straight away (otherwise we would need to tell customers to change the `log-level` and reproduce the problem).

2023-05-02 12:24 UTC, jujoramos commented on components/flow/flow-rest-resource-service-impl/src/test/kotlin/net/corda/flow/rest/impl/v1/FlowRestResourceImplTest.kt
👍

2023-05-02 12:28 UTC, davidcurrie commented on components/flow/flow-rest-resource-service-impl/src/test/kotlin/net/corda/flow/rest/impl/v1/FlowRestResourceImplTest.kt
> I don't know anybody else in the team who uses personal forks.

I do

> I can't really see any advantages either.

We wouldn't have 401 branches in `corda-runtime-os` for starters...

I'm intrigued to know what your review process is such that a PR from a fork is harder. It's a pattern well-supported in the GitHub UI, the GitHub CLI, and in IntelliJ.

2023-05-02 12:28 UTC, jujoramos commented on components/flow/flow-rest-resource-service-impl/src/test/kotlin/net/corda/flow/rest/impl/v1/FlowRestResourceImplTest.kt
> I can't really see any advantages either.

The first one that comes to mind is having a "clean" repository with only active branches, specifically for `develop` and released version support (such as `support/5.0`, `support/5.1`, `support/6.X`, whatever).

2023-05-02 12:28 UTC, jujoramos commented on components/flow/flow-rest-resource-service-impl/src/test/kotlin/net/corda/flow/rest/impl/v1/FlowRestResourceImplTest.kt
Ah, @davidcurrie beat me to it.

2023-05-02 12:31 UTC, davidcurrie commented on libs/utilities/src/main/kotlin/net/corda/utilities/LogUtils.kt
> +const val MDC_EXTERNAL_EVENT_ID = "corda.external.event.id"
fwiw: PS were asking recently if there was a document that covered these MDC keys

2023-05-02 12:36 UTC, driessamyn commented on components/flow/flow-rest-resource-service-impl/src/test/kotlin/net/corda/flow/rest/impl/v1/FlowRestResourceImplTest.kt
We don't have `develop` or `support` branches.
I think branch clean-up is a completely separate issue.

> I'm intrigued to know what your review process is such that a PR from a fork is harder.

`git fetch` doesn't get the forked branches, so checking out the forked branch is just more hassle.

2023-05-02 12:38 UTC, driessamyn submitted a review, later dismissed
approved for packaging team.

2023-05-02 12:38 UTC, jujoramos commented on libs/utilities/src/main/kotlin/net/corda/utilities/LogUtils.kt
> +const val MDC_EXTERNAL_EVENT_ID = "corda.external.event.id"
Maybe in the future as part of another `PR` (probably in `5.0.1`)?. I want to get this merged before the deadline for `5.0.0`, and I would put extra thought regarding the actual names used within the MDC if we are gonna make this part of the public api.

2023-05-02 12:44 UTC, davidcurrie commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/external/events/impl/ExternalEventManagerImpl.kt
> +        log.info("Processing response for external event with id '{}'", requestId)
This is a point of contention between myself and @mnesbit. If we insist on abusing logging in this manner then we should at least update the standards that @fowlerrr documented [here](https://github.com/corda/platform-eng-design/blob/master/core/corda-5/corda-5.0/standards/logging.md) to justify it.

2023-05-02 12:45 UTC, davidcurrie commented on libs/utilities/src/main/kotlin/net/corda/utilities/LogUtils.kt
> +const val MDC_EXTERNAL_EVENT_ID = "corda.external.event.id"
Just because it's not in `corda-api`, don't assume that people won't come to rely on it.

2023-05-02 12:48 UTC, jujoramos commented on libs/utilities/src/main/kotlin/net/corda/utilities/LogUtils.kt
> +const val MDC_EXTERNAL_EVENT_ID = "corda.external.event.id"
> Just because it's not in corda-api, don't assume that people won't come to rely on it.

Agreed, but having these constants defined within `corda-api` has stronger implications. I'm not saying that we shouldn't do it, just that we shouldn't do it now as part of this `PR`.

2023-05-02 12:52 UTC, jujoramos commented on components/flow/flow-rest-resource-service-impl/src/test/kotlin/net/corda/flow/rest/impl/v1/FlowRestResourceImplTest.kt
> +        assertThatThrownBy {
These changes have been reverted, resolving this discussion now.

2023-05-02 12:54 UTC, mnesbit commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/external/events/impl/ExternalEventManagerImpl.kt
> +        log.info("Processing response for external event with id '{}'", requestId)
I agree that we are likely logging too much into what is essentially a human readable stream. The problem is these events are BAU critical. Do we have a high volume tracing/logging mechanism?

2023-05-02 12:57 UTC, seanbrereton approved these changes, later dismissed
LGTM (build files)

2023-05-02 13:01 UTC, davidcurrie commented on libs/utilities/src/main/kotlin/net/corda/utilities/LogUtils.kt
> +const val MDC_EXTERNAL_EVENT_ID = "corda.external.event.id"
I really just meant: if you think the names should change, now's the time to change them wherever they might be defined.

2023-05-02 13:10 UTC, davidcurrie commented on components/flow/flow-rest-resource-service-impl/src/test/kotlin/net/corda/flow/rest/impl/v1/FlowRestResourceImplTest.kt
```
gh pr checkout 3656
```

2023-05-02 13:17 UTC, davidcurrie commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/external/events/impl/ExternalEventManagerImpl.kt
> +        log.info("Processing response for external event with id '{}'", requestId)
> Do we have a high volume tracing/logging mechanism?

No - because we didn't prioritise that for 5.0. I still think there's a distinction between what we're looking for here in terms of performance tuning (which is definitely in the realm of tracing), and what I think you're suggesting a customer wants in terms of understanding the state of a flow execution (which I'd suggest should be a part of the API).

2023-05-02 13:35 UTC, davidcurrie commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/external/events/impl/ExternalEventManagerImpl.kt
> +        log.info("Processing response for external event with id '{}'", requestId)
As a compromise, perhaps we could put these flow events on a separate logger? That would make it easier to enable/disable them en masse.

2023-05-02 14:28 UTC, jujoramos commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/external/events/impl/ExternalEventManagerImpl.kt
> +        log.info("Processing response for external event with id '{}'", requestId)
@davidcurrie : I've added an extra [commit](https://github.com/corda/corda-runtime-os/pull/3656/commits/90eabe1a6f5d0f446c1df5d9df0ce9ffbcd08aa9) with some changes, flow tracing is enabled by default but it can be optionally removed by customers through the following configuration:
```
<MarkerFilter marker="FLOW_TRACING" onMatch="DENY" onMismatch="NEUTRAL"/>
```

Sounds reasonable?.

2023-05-02 14:37 UTC, davidcurrie commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/external/events/impl/ExternalEventManagerImpl.kt
> +        log.info("Processing response for external event with id '{}'", requestId)
Thanks, @jujoramos. I had no idea that markers were even a thing! That looks reasonable (given where we are in the release).

2023-05-02 14:37 UTC, davidcurrie approved these changes

2023-05-02 15:25 UTC, seanbrereton approved these changes

2023-05-02 15:45 UTC, driessamyn approved these changes

2023-05-02 15:51 UTC, merged