CORE-11167 Pre-install checks for Corda Cluster
corda/corda-runtime-os pull request #3657
Opened 2023-04-19 12:17 UTC by jacob-scott3141

## Description
This PR adds a new plugin for the Corda CLI, called preinstall, which performs pre-install checks for the Corda platform. The plugin provides several subcommands, such as check-limits, check-postgres, check-kafka, and run-all, which verify different aspects of the Corda installation process.

## Motivation
The pre-install plugin is designed to help in the deployment of Corda to ensure that the Corda environment is properly configured and set up before installing the platform. By running the preinstall checks, users can more easily identify and fix potential issues with resource limitations, Postgres connectivity / DB issues, and Kafka cluster connectivity / broker issues.

## Usage
The easiest way to test the preinstall plugin is using the CLI-Plugin-Host. To do this, first compile the plugin using Gradle:

`./gradlew clean :tools:plugins:preinstall:build`

Then, copy the build files from corda-runtime-os to corda-cli-plugin-host:

`cp ./corda-runtime-os/tools/plugins/preinstall/build/libs/preinstall-cli-plugin-*.jar ./corda-cli-plugin-host/build/plugins/`

Finally, run the plugin from the CLI plugin host with:

`./gradlew run --args="preinstall \<subcommand\> [options] \<path\>"`

Replace `<subcommand>` with the desired subcommand, `<path>` with the path to the YAML file containing the relevant configuration settings, and `[options]` with any optional flags supported by the subcommand. See the` README.md` for more info.

For example, to run all pre-install checks, use the run-all subcommand:

`./gradlew run --args="preinstall run-all -v /path/to/config.yaml -n corda -f /path/to/truststore.jks"`

2023-04-20 11:01 UTC, davidcurrie commented on tools/plugins/preinstall/README.md
> +                              number of brokers are correctly configured
were you unable to get this from the admin API then?

2023-04-20 11:01 UTC, davidcurrie commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/CheckKafka.kt
> +    @Option(names = ["-f", "--file"], description = ["The file location of the truststore if TLS is enabled"])
Are we not able to retrieve the truststore from the secret given in the config?

2023-04-20 11:01 UTC, davidcurrie commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/CheckKafka.kt
> +                    "\"$saslUsername\" password=\"$saslPassword\" ;"
still need the option for `PLAIN` here

2023-04-20 11:01 UTC, davidcurrie commented on tools/plugins/preinstall/README.md
> +                              number of brokers are correctly configured
actually, when I then see how this is used, I'm confused about what this is meant to represent - is it the number of replicas that have been specified for the Corda topics? We should be taking that from the bootstrap properties (and it doesn't make sense to check if we're not creating the topics).

2023-04-20 11:01 UTC, davidcurrie commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/CheckKafka.kt
> +            } catch (_: NullPointerException) {
not nice - put an explicit null check up front

2023-04-20 11:01 UTC, davidcurrie commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/CheckKafka.kt
> +                    log("If SSL is enabled, you must provide the location of the truststore file with -f.", ERROR)
it would be better to propagate an exception here than have to handle the nulls

2023-04-20 11:01 UTC, davidcurrie commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/CheckLimits.kt
> +        val limits: ResourceValues = resources.limits
what if they're not set? or the limits are set and not the resources or vice-versa?

2023-04-20 11:01 UTC, davidcurrie commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/CheckLimits.kt
> +            log("Resource requests for $name have been exceeded!\n", ERROR)
it would be preferable to be explicit about exactly where the problem lies here e.g. `Memory request ${requests.memory} exceeds limit ${limits.memory} for $name`

2023-04-20 11:01 UTC, davidcurrie commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/CheckLimits.kt
> +        if (check) {println("[INFO] All resource requests are appropriate and are under the set limits.")}
it would be good if the return code for the command reflected whether the checks passed or not

2023-04-20 11:01 UTC, davidcurrie commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/CheckLimits.kt
> +            log("Resource requests for $name are appropriate and are under the set limits\n", INFO)
we don't really check they are "appropriate" at the moment

2023-04-20 11:01 UTC, davidcurrie commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/CheckPostgres.kt
> +    @Option(names = ["-v", "--verbose"], description = ["Display additional information when connecting to postgres"])
We should probably consistently use `PostgreSQL`

2023-04-20 11:01 UTC, davidcurrie commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/CheckPostgres.kt
> +        val password: String = getCredentialOrSecret(yaml.db.cluster.password, namespace) ?: return
potentially there also the bootstrap DB credentials to check

2023-04-20 11:01 UTC, davidcurrie commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/PreInstallPlugin.kt
> +        logger.info("stopping preinstall plugin")
elsewhere I've lowered the priority of these as they're not very useful `info` messages

2023-04-20 11:01 UTC, davidcurrie commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/PreInstallPlugin.kt
> +        }
why not actually use a logging library as we do in the other plugins?

2023-04-20 11:01 UTC, davidcurrie commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/PreInstallPlugin.kt
> +            log("Working Directory = ${System.getProperty("user.dir")}\n", INFO)
what's this used for?

2023-04-20 11:01 UTC, davidcurrie commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/PreInstallPlugin.kt
> +                return null
use exceptions

2023-04-20 11:01 UTC, davidcurrie commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/PreInstallPlugin.kt
> +                null
exceptions

2023-04-20 11:01 UTC, davidcurrie commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/PreInstallPlugin.kt
> +                    log("Username secret could not be found in namespace $namespace.", ERROR)
the log messages say `Username` but it won't always be a username

2023-04-20 11:01 UTC, davidcurrie commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/PreInstallPlugin.kt
> +                    return null
we should default to using whatever namespace the kubernetes context is currently pointing at

2023-04-20 11:01 UTC, davidcurrie commented on tools/plugins/preinstall/src/test/kotlin/net/corda/cli/plugins/preinstall/CheckSecretsTests.kt
> +@CommandLine.Command(name = "sub-command", description = ["Example subcommand."])
?!?

2023-04-20 11:09 UTC, jacob-scott3141 commented on tools/plugins/preinstall/README.md
> +                              number of brokers are correctly configured
In the extension I thought about checking that the number of brokers was configured correctly - so I was thinking for example the replicaCount from prereqs-eks.yaml could be used to make sure the number of brokers is greater than the replica count

2023-04-20 11:10 UTC, davidcurrie commented on tools/plugins/preinstall/README.md
> +                              number of brokers are correctly configured
but you connect to Kafka and ask it how many brokers there are - can't you just use that?

2023-04-20 12:33 UTC, jacob-scott3141 commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/CheckKafka.kt
> +    @Option(names = ["-f", "--file"], description = ["The file location of the truststore if TLS is enabled"])
Yes, I think I can use ssl.truststore.certificates as an alternative to ssl.truststore.location

2023-04-20 12:36 UTC, jacob-scott3141 commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/CheckKafka.kt
> +                    "\"$saslUsername\" password=\"$saslPassword\" ;"
Is Plain ever used in the case where TLS is not enabled? I thought it was written this way to prevent this

2023-04-20 12:49 UTC, jacob-scott3141 commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/PreInstallPlugin.kt
> +            log("Working Directory = ${System.getProperty("user.dir")}\n", INFO)
This was useful for passing a relative path for file parsing

2023-04-20 13:03 UTC, davidcurrie commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/PreInstallPlugin.kt
> +            log("Working Directory = ${System.getProperty("user.dir")}\n", INFO)
Perhaps more useful would be just to output the absolute path of the file that you're loading.

2023-04-20 13:10 UTC, davidcurrie commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/CheckKafka.kt
> +                    "\"$saslUsername\" password=\"$saslPassword\" ;"
Written where? The combination doesn't make great sense (sending credentials in plain across non-TLS connection) but I don't think Kafka prevents it.

2023-04-20 13:12 UTC, jacob-scott3141 commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/CheckKafka.kt
> +                    "\"$saslUsername\" password=\"$saslPassword\" ;"
The bootstrap template here https://github.com/corda/corda-runtime-os/blob/release/os/5.0/charts/corda-lib/templates/_bootstrap.tpl#L333

2023-04-20 13:28 UTC, davidcurrie commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/CheckKafka.kt
> +                    "\"$saslUsername\" password=\"$saslPassword\" ;"
Either that was a response to a different comment or it's the wrong line!

2023-04-20 13:31 UTC, jacob-scott3141 commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/CheckKafka.kt
> +                    "\"$saslUsername\" password=\"$saslPassword\" ;"
Apologies, updated the link just now

2023-04-20 13:33 UTC, davidcurrie commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/CheckKafka.kt
> +                    "\"$saslUsername\" password=\"$saslPassword\" ;"
yeah - I think that's just wrong!

2023-04-20 13:35 UTC, jacob-scott3141 commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/CheckKafka.kt
> +                    "\"$saslUsername\" password=\"$saslPassword\" ;"
I just assumed it was written to prevent the use of SASL Plain without TLS

2023-04-20 13:50 UTC, davidcurrie commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/CheckKafka.kt
> +                    "\"$saslUsername\" password=\"$saslPassword\" ;"
if we did want to prevent it, it would be better to explicitly fail on that combination rather than just specifying the wrong login module...

2023-04-20 16:12 UTC, davidcurrie commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/PreInstallPlugin.kt
> +                    client.namespace ?: "default"
That's not quite what I meant... I meant use the namespace that the provided Kubernetes context is pointing at. Typically that's what you get if you don't specify a namespace at all.

2023-04-25 08:36 UTC, yarivus requested changes

2023-04-25 08:36 UTC, yarivus commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/RunAll.kt
> +    @CommandLine.Option(names = ["-n", "--namespace"], description = ["The namespace in which to look for both the Postgres " +
I think breaking the string and concat using '+' is less readable ...
Either leave as 1 line or better break the annotation to parameter on each newline

2023-04-25 08:36 UTC, yarivus commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/RunAll.kt
> +    @CommandLine.Option(names = ["-n", "--namespace"], description = ["The namespace in which to look for both the Postgres " +
Fix other occurrences

2023-04-25 08:36 UTC, yarivus commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/PreInstallPlugin.kt
> +            if(!file.isFile) {
```suggestion
            if (!file.isFile) {
```

2023-04-25 08:36 UTC, yarivus commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/CheckKafka.kt
> +    @Option(names = ["-n", "--namespace"], description = ["The namespace in which to look for the Kafka secrets if TLS or " +
see other comment of mine regarding breaking the strings and concat ... fix everywhere please

2023-04-25 08:36 UTC, yarivus commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/CheckKafka.kt
> +        println("[INFO] Kafka client connected to cluster with ID ${clusterID}.")
use logger ?

2023-04-25 08:36 UTC, yarivus commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/CheckPostgres.kt
> +class CheckPostgres : Runnable, PluginContext(){
```suggestion
class CheckPostgres : Runnable, PluginContext() {
```

2023-04-25 08:36 UTC, yarivus commented on tools/plugins/preinstall/src/test/resources/KafkaTest0.yaml
maybe better rename the yaml file to a name which indicates what it's testing for.
For example: KafkaTest0.yaml => kafka-test-sasl-plain.yaml

2023-04-27 08:11 UTC, jacob-scott3141 commented on tools/plugins/preinstall/README.md
> +                              number of brokers are correctly configured
I get what you meant now, the changes should be in place

2023-04-27 08:11 UTC, jacob-scott3141 commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/CheckKafka.kt
> +    @Option(names = ["-f", "--file"], description = ["The file location of the truststore if TLS is enabled"])
This is done now

2023-04-27 08:54 UTC, yarivus submitted a review, later dismissed
LGTM

2023-04-27 11:06 UTC, yarivus approved these changes, later dismissed
LGTM

2023-04-27 20:24 UTC, yarivus commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/CheckLimits.kt
> +        getLogger().info("${name.uppercase()}:")
wouldn't it be easier to get the logger once instead of each log line ?

2023-04-27 20:24 UTC, yarivus reviewed
see comment / question

2023-04-28 09:55 UTC, davidcurrie requested changes

2023-04-28 09:55 UTC, davidcurrie commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/CheckKafka.kt
> +        names = ["-u", "--url"],
I really wouldn't try and support this option. I can't imagine a scenario where the URL is going to be enough on its own (you're always going to need some credentials as well at a minimum) and rather than trying to expose all of the client configuration options I'd just require them to have set up the Kubernetes context correctly in advance of calling the CLI.

2023-04-28 09:55 UTC, davidcurrie commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/CheckKafka.kt
> +        names = ["-f", "--file"],
Likewise, I'd keep it simple and not support this option either. We're expecting to be able to retrieve secrets from Kubernetes so why not the same for the truststore?

2023-04-28 09:55 UTC, davidcurrie commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/CheckKafka.kt
> +        description = ["The timeout in milliseconds for testing the kafka connection - defaults to 3000"]
```suggestion
        description = ["The timeout in milliseconds for testing the Kafka connection - defaults to 3000"]
```

2023-04-28 09:55 UTC, davidcurrie commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/CheckKafka.kt
> +        description = ["The maximum ms a connection can be idle for while testing the kafka connection - defaults to 5000"]
Is this something that we really need to expose?
```suggestion
        description = ["The maximum milliseconds a connection can be idle for while testing the Kafka connection - defaults to 5000"]
```

2023-04-28 09:55 UTC, davidcurrie commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/CheckKafka.kt
> +        open fun getNodes(): Collection<Node>? {
nit: a friendlier signature would be to always return at least an empty collection

2023-04-28 09:55 UTC, davidcurrie commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/CheckKafka.kt
> +        var connectionsMaxIdleMs: Int = 5000
There's a slightly strange split of responsibilities here. Either have this class do all the work of extracting the properties from YAML, or have all that work done outside and pass in the extracted values.

2023-04-28 09:55 UTC, davidcurrie commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/CheckKafka.kt
> +                props["ssl.truststore.type"] = yaml.kafka.tls.truststore!!.type.uppercase()
I suspect the `!!` here is indicative of that strange split as I'm guessing you've already verified somewhere else that the truststore is not `null`.

2023-04-28 09:55 UTC, davidcurrie commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/CheckKafka.kt
> +                props["sasl.mechanism"] = yaml.kafka.sasl.mechanism
As previously discussed, if you don't want to support `PLAIN` here (which is a reasonable stance) then we should flag that as an error.

2023-04-28 09:55 UTC, davidcurrie commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/CheckKafka.kt
> +                throw BrokerException("Number of brokers (${nodes.size}) is less than replica count.")
why is this not just a failed report?

2023-04-28 09:55 UTC, davidcurrie commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/CheckKafka.kt
> +        }
I'd be tempted to factor this differently into three separate checks - one for the mechanism, one for username, and one for password.

2023-04-28 09:55 UTC, davidcurrie commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/CheckKafka.kt
> +        report.addEntry(ReportEntry("Connect to Kafka cluster using client", true))
At least as far as it is possible, I'd expect to always see the same set of entries in the results and just different combinations of pass/fail.

2023-04-28 09:55 UTC, davidcurrie commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/CheckLimits.kt
> +    @Parameters(index = "0", description = ["YAML file containing resource limit overrides for the corda install"])
```suggestion
    @Parameters(index = "0", description = ["YAML file containing resource limit overrides for the Corda install"])
```

2023-04-28 09:55 UTC, davidcurrie commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/CheckLimits.kt
> +    // split resource into a digit portion and a unit portion
and... the function does a bit more than that!

2023-04-28 09:55 UTC, davidcurrie commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/CheckLimits.kt
> +        getLogger().info("${name.uppercase()}:")
if this is to provide context for the next two lines then they should really all be one log entry

2023-04-28 09:55 UTC, davidcurrie commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/CheckPostgres.kt
> +        description = ["YAML file containing either the username and password value, or valueFrom.secretKeyRef.key fields for PostgreSQL"]
It's not really just the `key` fields though. Maybe something like "YAML file containing the username and password values for PostgreSQL either as values or as secret references"

2023-04-28 09:55 UTC, davidcurrie commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/CheckPostgres.kt
> +            if (connection.isValid(0)) {
if `isValid` returns `false`, what does that mean? should we be creating a report entry for that?

2023-04-28 09:55 UTC, davidcurrie commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/PreInstallPlugin.kt
> +        description = ["Preinstall checks for corda."])
```suggestion
        description = ["Preinstall checks for Corda."])
```

2023-04-28 09:55 UTC, davidcurrie commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/PreInstallPlugin.kt
> +        }
There seems to be something a bit circular here. The subcommands set these into the context so that they can retrieve them again?

2023-04-28 09:55 UTC, davidcurrie commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/PreInstallPlugin.kt
> +        fun getCredentialOrSecret(values: SecretValues, namespace: String?, url: String?): String {
nit: I'd just call this `getCredential` or, if you wanted to be really explicit, `getCredentialFromValueOrSecret` but it always returns a credential

2023-04-28 09:55 UTC, davidcurrie commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/PreInstallPlugin.kt
> +            credential = credential ?: run {
logic is the wrong way round - the secret takes precedence (if the name is not null/empty)

2023-04-28 09:55 UTC, davidcurrie commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/PreInstallPlugin.kt
> +                }
Is there a downside to continually rebuilding the client?

2023-04-28 09:55 UTC, davidcurrie commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/PreInstallPlugin.kt
> +            return "$check: ${if (result) "PASSED" else "FAILED"}"
are we losing important information about why it failed by not including the exception message?

2023-04-28 09:55 UTC, davidcurrie commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/PreInstallPlugin.kt
> +    class Report (private var report: MutableList<ReportEntry> = mutableListOf()) {
calling both the class and variable report is confusing - maybe `entries` for that latter?

2023-04-28 09:55 UTC, davidcurrie commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/PreInstallPlugin.kt
> +            return if (result.result) 0 else 1
I think you just want something like `if (report.all { it.result } 0 else 1`

2023-04-28 09:55 UTC, davidcurrie commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/PreInstallPlugin.kt
> +        fun testsPassed(): Int {
this is conflating a report concern (did everything pass) and a command concern (return code) - I'd just return a boolean here and then convert to a return code in the command

2023-04-28 09:55 UTC, davidcurrie commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/PreInstallPlugin.kt
> +            return acc
this should be able to use a (suitably modified) `entry.toString` then you can have something like:

```
return report.filter { !it.result }.joinToString(separator = "\n")
```

2023-04-28 09:55 UTC, davidcurrie commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/PreInstallPlugin.kt
> +            return acc
```
report.joinToString(separator = "\n")
```

2023-04-28 09:55 UTC, davidcurrie commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/PreInstallPlugin.kt
> +    )
I think there need to be a few more `?` in here...

2023-04-28 09:55 UTC, davidcurrie commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/RunAll.kt
> +        description = ["The namespace in which to look for both the Postgres and Kafka secrets"]
```suggestion
        description = ["The namespace in which to look for both the PostgreSQL and Kafka secrets"]
```

2023-04-28 09:55 UTC, davidcurrie commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/RunAll.kt
> +        CommandLine(kafkaCMD).execute(path, *kafkaArgs.toTypedArray())
does this gain you something over just executing `call` directly?

2023-04-28 09:55 UTC, davidcurrie commented on tools/plugins/preinstall/src/test/kotlin/net/corda/cli/plugins/preinstall/TestSubCommands.kt
> +    fun testFileParsing() {
Preference should be one test per method - so `testFileParsingResources`, `testFileParsingPostgreSQL`, ...

2023-04-28 09:55 UTC, davidcurrie commented on tools/plugins/preinstall/src/test/kotlin/net/corda/cli/plugins/preinstall/TestSubCommands.kt
> +        CommandLine(limits).execute(path)
Worth checking the return codes?

2023-04-28 09:55 UTC, davidcurrie commented on tools/plugins/preinstall/src/test/kotlin/net/corda/cli/plugins/preinstall/TestSubCommands.kt
> +            assertTrue( ck.report.toString().contains("Connect to Kafka cluster using client: PASSED") )
how about a test for failing to connect to Kafka?

2023-05-03 08:36 UTC, jacob-scott3141 commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/RunAll.kt
> +        CommandLine(kafkaCMD).execute(path, *kafkaArgs.toTypedArray())
`execute` allows you to pass the PicoCLI command line arguments to the subcommand, I don't believe you can do that by running `call`

2023-05-03 15:53 UTC, yarivus reviewed
LGTM - but still pending comments

2023-05-03 16:20 UTC, jacob-scott3141 commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/CheckKafka.kt
> +        names = ["-f", "--file"],
This is optional, as it is capable of fetching the truststore from a secret. Do you think it's not worth supporting a truststore location? I originally added it to match the functionality of the helm charts.

2023-05-03 16:49 UTC, davidcurrie commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/CheckKafka.kt
> +        names = ["-f", "--file"],
The Helm chart itself always takes the truststore as the location of an existing secret. I'd stop there given you have the logic to handle that.

2023-05-04 08:45 UTC, yarivus submitted a review, later dismissed
LGTM

2023-05-04 08:46 UTC, jacob-scott3141 commented on tools/plugins/preinstall/src/test/kotlin/net/corda/cli/plugins/preinstall/TestSubCommands.kt
> +        CommandLine(limits).execute(path)
I've added a return code for the limits file parsing, but in this case postgres and kafka will always return zero here because there is no access to a cluster or postgres / kafka instances

2023-05-04 08:51 UTC, yarivus submitted a review, later dismissed
LGTM

2023-05-04 14:50 UTC, yarivus approved these changes, later dismissed
LGTM

2023-05-04 16:51 UTC, yarivus approved these changes, later dismissed
LGTM

2023-05-04 17:13 UTC, davidcurrie requested changes

2023-05-04 17:13 UTC, davidcurrie commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/CheckKafka.kt
> +        description = ["The timeout in milliseconds for testing the kafka connection - defaults to 3000"]
```suggestion
        description = ["The timeout in milliseconds for testing the Kafka connection - defaults to 3000"]
```

2023-05-04 17:13 UTC, davidcurrie commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/CheckKafka.kt
> +        description = ["The namespace in which to look for both the Postgres and Kafka secrets"]
I'm trying (and probably failing) to be consistent about using `PostgreSQL`, at least in external facing documentation:
```suggestion
        description = ["The namespace in which to look for both the PostgreSQL and Kafka secrets"]
```

2023-05-04 17:13 UTC, davidcurrie commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/CheckKafka.kt
> +    class KafkaProperties(private val bootstrapServers: String) {
This should now just be a Kotlin data class.

2023-05-04 17:13 UTC, davidcurrie commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/CheckKafka.kt
> +            val saslEnabled = !(saslUsername == null && saslPassword == null)
Given you've previously worked out whether TLS and SASL are enabled, it would be better to keep hold of that information rather than attempting to reverse engineer it again here.

2023-05-04 17:13 UTC, davidcurrie commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/CheckKafka.kt
> +    fun connect(client: KafkaAdmin, replicas: Int?) {
would prefer a more meaningful name given what the method does e.g. `checkConnectionAndSufficientBroker`

2023-05-04 17:13 UTC, davidcurrie commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/CheckKafka.kt
> +        creds.timeout = timeout
The `let`s are a bit redundant given you can pass through null values. I suspect the `KafkaProperties` abstraction is now just getting in the way - you'd be better off just building the Kafka properties as you go through the YAML.

2023-05-04 17:13 UTC, davidcurrie commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/CheckKafka.kt
> +                    TruststoreNotFoundException("If SSL is enabled, you must provide entries for kafka.tls.truststore."))) {
This isn't true - if the broker's certs would be trusted by the JVM (as they are for MSK, for example), you don't need to provide a truststore

2023-05-04 17:13 UTC, davidcurrie commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/CheckKafka.kt
> +                return 1
here and elsewhere: do we need to return here or could we continue on to perform other verifications? nothing more frustrating than having to fix one problem at a time

2023-05-04 17:13 UTC, davidcurrie commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/CheckLimits.kt
> +        yaml.resources?.let { checkResources(it, "resources") }
we don't really care that `resources` on its own is valid - what we care about is that, for each type of worker, the combination of the worker-specific resources and the defaults specified in `resources` is valid

2023-05-04 17:13 UTC, davidcurrie commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/CheckPostgres.kt
> +        val dbPass = yaml.bootstrap?.db?.cluster?.password ?: yaml.db.cluster.password
We should verify both sets of credentials here. Those that are in `db.cluster` and, if they are different, those in `bootstrap.db.cluster`.

2023-05-04 17:13 UTC, davidcurrie commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/CheckPostgres.kt
> +        val postgresUrl = "jdbc:postgresql://${yaml.db.cluster.host}:${yaml.db.cluster.port}/postgres"
the database name (on the end of the URL) should also come from the YAML

2023-05-04 17:13 UTC, davidcurrie commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/PreInstallPlugin.kt
> +            if (secretKey.isNullOrEmpty() || secretName.isNullOrEmpty())  {
although it is later enforced by the chart, we should check that if you have a `secretName` then they should have specified a `secretKey`

2023-05-04 17:13 UTC, davidcurrie commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/PreInstallPlugin.kt
> +    class ReportEntry(private var check: String, var result: Boolean, var reason: Exception? = null) {
```suggestion
    class ReportEntry(private var check: String, var result: boolean, var reason: Exception? = null) {
```

2023-05-04 17:13 UTC, davidcurrie commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/PreInstallPlugin.kt
> +                entry += "\n\t - $message \n\t - $cause"
If they're not provided I just wouldn't add them to the message

2023-05-04 17:13 UTC, davidcurrie commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/RunAll.kt
> +        CommandLine(kafkaCMD).execute(path, *kafkaArgs.toTypedArray())
but you could just set them directly on the `Callable` could you not? e.g. `limitsCMD.path = path`

2023-05-05 14:09 UTC, yarivus submitted a review, later dismissed
LGTM

2023-05-08 18:49 UTC, yarivus submitted a review, later dismissed
LGTM

2023-05-09 08:25 UTC, jacob-scott3141 commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/CheckKafka.kt
> +        creds.timeout = timeout
I've kept the KafkaProperties for now; for me it helps with readability to separate the parsing of the yaml and fetching of secrets from the building of the properties, but if you would prefer the properties to assemble them together I can make that change

2023-05-09 08:25 UTC, yarivus requested changes

2023-05-09 08:25 UTC, yarivus commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/CheckLimits.kt
> +            }
I don't follow this logic ... if `requests?.memory` can be null ... then why assign it the `defaultRequests?` which are assigned null as well ?!
IOW why do you need `defaultRequests` set to null at all if you used `ResourceValues?`

2023-05-09 08:25 UTC, yarivus commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/CheckLimits.kt
>              }
same comment as before

2023-05-09 08:25 UTC, yarivus commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/CheckPostgres.kt
> +        if (bootstrapUsername != null && bootstrapUsername != username && bootstrapPassword != null) {
a comment is needed why you choose to call `connect()` again w/ different params.

2023-05-09 08:25 UTC, yarivus commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/PreInstallPlugin.kt
> +                if (!credential.isNullOrEmpty() && secretName.isNullOrEmpty()) {
Maybe this condition should be not nested ?!
You want to return the credential when: `!credential.isNullOrEmpty() && secretName.isNullOrEmpty() && !secretKey.isNullOrEmpty()` 
At least that's what the exception msg says ;)

2023-05-09 09:51 UTC, jacob-scott3141 commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/CheckLimits.kt
> +            }
The ResourceValue object can be null, in which case it is assigned `defaultRequests` - if the ResourceValue object itself is not not null, it can still have null fields for memory or cpu, in which case the default is used for that field

2023-05-09 15:31 UTC, yarivus submitted a review, later dismissed
LGTM

2023-05-11 09:34 UTC, davidcurrie requested changes

2023-05-11 09:34 UTC, davidcurrie commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/PreInstallPlugin.kt
> +        val resources: ResourceConfig
Should this be nullable?

2023-05-11 09:34 UTC, davidcurrie commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/CheckLimits.kt
> +        yaml.workers?.p2pGateway?.let { checkResources(it.resources, "P2P gateway") }
This means we only check the resources if there is some configuration specified for the bootstrap/worker whereas we always want to perform the checks. Currently, it won't fail if I specify invalid or no defaults but I don't override any of the worker properties. Worth adding a test for this.

2023-05-11 09:34 UTC, davidcurrie commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/CheckPostgres.kt
> +            connect(postgresUrl, bootstrapUsername!!, bootstrapPassword!!)
Could you get something in the report entry that lets the user know this is for the bootstrap credentials so they know where to look when it fails?

2023-05-11 09:34 UTC, davidcurrie commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/PreInstallPlugin.kt
> +            }
The logic here is still not quite right - if I have a `secretName` then I must have a `secretKey`

2023-05-11 12:07 UTC, jacob-scott3141 commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/CheckLimits.kt
> +        yaml.workers?.p2pGateway?.let { checkResources(it.resources, "P2P gateway") }
Just to double check - is it supposed to fail if defaults aren't supplied?

2023-05-11 13:16 UTC, davidcurrie commented on tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/CheckLimits.kt
> +        yaml.workers?.p2pGateway?.let { checkResources(it.resources, "P2P gateway") }
The question is not whether defaults are supplied or not, it is whether or not bootstrap and each worker have valid values (taking into account both the specific and default values). Previously I'd suggested this is where it might be useful to have different levels of severity but let's not get into that now. Let's just say that valid means that both requests and limits have been specified and limits >= requests.

2023-05-11 17:14 UTC, yarivus approved these changes
LGTM

2023-05-11 18:40 UTC, davidcurrie approved these changes
LGTM - thanks for persevering @jacob-scott3141 !

2023-05-12 08:11 UTC, merged

2023-05-31 10:39 UTC, dickon commented
Just a friendly reminder that we generally squash all our PRs and prefer not to have authors like "root <root@LDNW-95ZJMN3>".