CORE-9070: use corda micrometer fork
corda/corda-runtime-os pull request #3683
Opened 2023-04-21 17:18 UTC by ronanbrowne

Published fork of the following https://github.com/micrometer-metrics/micrometer/releases/tag/v1.11.0-RC1 which has OSGi support. 

This should be replaced with the real micrometer version once micrometer 1.11.0 GA is released

2023-04-24 09:03 UTC, driessamyn commented
Thanks for doing this, @ronanbrowne 

I think this can be removed now too: https://github.com/corda/corda-runtime-os/blob/dcaf4a3901e04a7066a17b80e4b27289147375ff/build.gradle#L204

2023-04-24 11:16 UTC, ronanbrowne commented
> Thanks for doing this, @ronanbrowne
> 
> I think this can be removed now too:
> 
> https://github.com/corda/corda-runtime-os/blob/dcaf4a3901e04a7066a17b80e4b27289147375ff/build.gradle#L204
The next lines declare a Maven repo entry for "corda-dependencies"  ( i'v updated this from corda-dependecies-dev to corda-dependecies for this non-snapshot versions location) 

perhaps i am misunderstanding, but In this context the comment is still valid as once the "real" 1.11.0 is out we can revert to that and remove this?

2023-04-24 12:17 UTC, yarivus requested changes

2023-04-24 12:17 UTC, yarivus commented on libs/metrics/build.gradle
> +    api ("net.corda.micrometer:micrometer-core:$micrometerVersion") {
why not have the `net.corda.micrometer` as a gradle property ?

2023-04-24 12:23 UTC, driessamyn commented
> > Thanks for doing this, @ronanbrowne
> > I think this can be removed now too:
> > https://github.com/corda/corda-runtime-os/blob/dcaf4a3901e04a7066a17b80e4b27289147375ff/build.gradle#L204
> 
> The next lines declare a Maven repo entry for "corda-dependencies" ( i'v updated this from corda-dependecies-dev to corda-dependecies for this non-snapshot versions location)
> 
> perhaps i am misunderstanding, but In this context the comment is still valid as once the "real" 1.11.0 is out we can revert to that and remove this?
> 
> edit: although i can update the comment to more accurately reflect current reality

Yes, you're right, but I think this was only needed since it was consuming from the `-dev` repo. I think it should now be able to resolve this without the `exclusiveContent` block.
It doesn't harm to have it there though.

2023-04-24 14:49 UTC, ronanbrowne commented on libs/metrics/build.gradle
> +    api ("net.corda.micrometer:micrometer-core:$micrometerVersion") {
@yarivus While that's certainly possible, this will change once more and then our need for this is over, so it's an extra property to be maintained with minimal benefit - It feels like we are creating more code unnecessarily to externalize this. unlike something like a version, we will maintain long-term and want in a centralized place.

2023-04-24 17:41 UTC, yarivus approved these changes
LGTM

2023-04-24 17:41 UTC, ronanbrowne commented
> > > Thanks for doing this, @ronanbrowne
> > > I think this can be removed now too:
> > > https://github.com/corda/corda-runtime-os/blob/dcaf4a3901e04a7066a17b80e4b27289147375ff/build.gradle#L204
> > 
> > 
> > The next lines declare a Maven repo entry for "corda-dependencies" ( i'v updated this from corda-dependecies-dev to corda-dependecies for this non-snapshot versions location)
> > perhaps i am misunderstanding, but In this context the comment is still valid as once the "real" 1.11.0 is out we can revert to that and remove this?
> > edit: although i can update the comment to more accurately reflect current reality
> 
> Yes, you're right, but I think this was only needed since it was consuming from the `-dev` repo. I think it should now be able to resolve this without the `exclusiveContent` block. It doesn't harm to have it there though.

Removing the block breaks compilation as we don't have a repository block declared further up for corda-dependencies (only corda-dpendecies-dev)  i could add this as a normal dependency block but I've left this as to minimize dependencies we are unknowingly pulling in from this repo, I've updated comments however for clarity

2023-04-25 07:08 UTC, driessamyn commented
> > > > Thanks for doing this, @ronanbrowne
> > > > I think this can be removed now too:
> > > > https://github.com/corda/corda-runtime-os/blob/dcaf4a3901e04a7066a17b80e4b27289147375ff/build.gradle#L204
> > > 
> > > 
> > > The next lines declare a Maven repo entry for "corda-dependencies" ( i'v updated this from corda-dependecies-dev to corda-dependecies for this non-snapshot versions location)
> > > perhaps i am misunderstanding, but In this context the comment is still valid as once the "real" 1.11.0 is out we can revert to that and remove this?
> > > edit: although i can update the comment to more accurately reflect current reality
> > 
> > 
> > Yes, you're right, but I think this was only needed since it was consuming from the `-dev` repo. I think it should now be able to resolve this without the `exclusiveContent` block. It doesn't harm to have it there though.
> 
> Removing the block breaks compilation as we don't have a repository block declared further up for corda-dependencies (only corda-dpendecies-dev) i could add this as a normal dependency block but I've left this as to minimize dependencies we are unknowingly pulling in from this repo, I've updated comments however for clarity

Makes sense. I thought we already had it.
Thanks

2023-04-25 07:09 UTC, driessamyn approved these changes
LGTM

2023-04-25 07:44 UTC, merged