CORE-7793 - Failed serialization when producing Kafka records should send the Flow to the DLQ
corda/corda-runtime-os pull request #3742
Opened 2023-04-27 14:46 UTC by pmck91

To fix this potential infinite loop, we can return null for un-serializable records, and push an explanation sting to the DLQ as we cant push the data that failed to serialize. 

For other uses of the serializer they may expect the exception, so we only return null in the case a throwOnSerializationError is true.

We have decided that the api for corda's avro serializers should be moved from corda-api to runtime-os
I have ported CordaAvroSerializer, CordaAvroDeserializer, CordaAvroSerializationFactory. 

I have added a Boolean field (defaults to true to match current behaviour) 'throwOnSerializationError ' to the CordaProducerBuilder. this will allow us to decide if we wish to maintain current behaviour and throw when a serialization error occurs, or swallow it and allow it be handled by the onError handler only. 

Most of the files in this PR are just import changes. 
The following are files of interest:

- CordaSubscriptionFactory
- StateAndEventBuilder
- StateAndEventSubscriptionImpl
- CordaAvroSerializer
- CordaAvroSerializerImpl
- CordaAvroDeserializer
- CordaAvroSerializationFactory
- KafkaCordaProducerBuilderImpl

2023-05-03 08:57 UTC, LWogan commented on libs/serialization/serialization-avro/src/main/java/net/corda/serialization/package-info.java
> +package net.corda.serialization;
We should move this new lib to a different package other than net.corda.serialization;.  Maybe something with the word avro in it would do?

In OSGI we cant have 2 bundles  export the same package. If we did then  OSGI wouldnt know which bundle to wire to, to get the classes for an imported package. OSGI doesn't look inside the packages for specific classes when wiring together bundles. it just wires import package to export package at startup so it would have a 50/50 chance of getting it right.

Serialization-internal has  already taken net.corda.serialization
https://github.com/corda/corda-runtime-os/blob/release/os/5.0/libs/serialization/serialization-internal/src/main/java/net/corda/serialization/package-info.java

2023-05-03 18:26 UTC, LWogan reviewed
Looks good. Glad to move this out of corda-api given we dont have any intentions on letting customers implement their own avro serializers. These API changes will allow us to better handle these serialization error use cases!

Given this is mostly complete I think we should apply the same changes youve made in CordaAvroSerializerImpl  to the CordaDBAvroSerializerImpl. Should be quick enough and this will keep the logic in our two bus implementations consistent. 

This would allow us to write a db message bus integration test easily to test the dead letter functionality too _I think_. We have some similar tests for the deserialization dead letter logic in testing:message-pattern:integrationTests DurableSubscriptionIntegrationTest & StateAndEventSubscriptionIntegrationTest. We could try out writing a processor that outputs non avro/string/bytearray type objects and see if it will fail serialization and trigger the DLQ.

2023-05-03 18:26 UTC, LWogan commented on components/membership/membership-persistence-service-impl/src/main/kotlin/net/corda/membership/impl/persistence/service/handler/AddNotaryToGroupParametersHandler.kt
> +        cordaAvroSerializationFactory.createAvroSerializer(false) {
I think this is the only one youve set it to false for. is it an easter egg to see if we're paying attention :D

I think lets just leave it as the default "true" and leave it up to this ticket to modify the logic to handle the error case better https://r3-cev.atlassian.net/browse/CORE-9673

2023-05-03 18:26 UTC, LWogan commented on libs/messaging/kafka-message-bus-impl/src/main/kotlin/net/corda/messagebus/kafka/serialization/CordaAvroSerializerImpl.kt
>  class CordaAvroSerializerImpl<T : Any>(
we should put some kdocs and @param tags on this class to help explain the logic

2023-05-03 18:26 UTC, LWogan commented on libs/messaging/kafka-message-bus-impl/src/main/kotlin/net/corda/messagebus/kafka/serialization/CordaAvroSerializerImpl.kt
> +                    // We don't want to throw as that would mean the entire poll (with possibly
i think move this comment up to the class level. might need a little rewrite. it reads as if this class only handles message pattern serialization, might confuse someone not familiar with the message patterns, consumer and produce loop and that use case etc

2023-05-03 18:26 UTC, LWogan commented on libs/messaging/kafka-message-bus-impl/src/test/kotlin/net/corda/messagebus/kafka/serialization/CordaAvroSerializerImplTest.kt
>      data class SerializeTester(val contents: String = "test contents")
You mentioned you're going to add a unit test, just in case anyone else adds a comment!

2023-05-03 18:26 UTC, LWogan commented on libs/messaging/message-bus/src/main/kotlin/net/corda/messagebus/api/producer/builder/CordaProducerBuilder.kt
> +     * @param onSerializationError a callback to receive messages that fail to serialize.  In the producer feed
missing kdoc for throwOnError. 

kdoc for onSerializationError might need a little altering as it has the old description about it being used to decide whether to return null

2023-05-03 18:26 UTC, LWogan commented on libs/serialization/serialization-avro/build.gradle
> +    implementation platform("net.corda:corda-api:$cordaApiVersion")
i dont think you need

    implementation platform("net.corda:corda-api:$cordaApiVersion")

2023-05-03 18:26 UTC, LWogan commented on libs/serialization/serialization-avro/src/main/kotlin/net/corda/avro/serialization/CordaAvroSerializationFactory.kt
> +     */
They were missing already before but we should add some @param and @return  kdocs to explain clearly the new functionality and how it relates to the flags. not sure why we didnt have them before already. 

I know it hasnt changed since the move from corda-api but please add some for the createAvroDeserializer method too.

2023-05-03 18:26 UTC, LWogan commented on libs/messaging/kafka-message-bus-impl/src/main/kotlin/net/corda/messagebus/kafka/serialization/CordaAvroSerializerImpl.kt
> +                    val message = "Failed to serialize instance of class type ${data::class.java.name} containing " +
this should fit on one line. i think detekt is configured to 140 line lengths. intellij defaults to 120

2023-05-03 18:26 UTC, LWogan commented on libs/messaging/messaging-impl/src/main/kotlin/net/corda/messaging/subscription/StateAndEventSubscriptionImpl.kt
> +                nullableProducer = builder.createProducer(config, false) { data ->
we should add this dead letter records lambda to the same place in  EventLogSubscriptionImpl

2023-05-04 09:05 UTC, pmck91 commented on components/membership/membership-persistence-service-impl/src/main/kotlin/net/corda/membership/impl/persistence/service/handler/AddNotaryToGroupParametersHandler.kt
> +        cordaAvroSerializationFactory.createAvroSerializer(false) {
I was searching for this and couldnt find it!

2023-05-04 11:21 UTC, simon-johnson-r3 requested changes

2023-05-04 11:21 UTC, simon-johnson-r3 commented on libs/messaging/messaging-impl/src/main/kotlin/net/corda/messaging/subscription/consumer/builder/StateAndEventBuilder.kt
> +        throwOnError: Boolean = true,
From this layer of abstraction, and those down except the serializer itself I think `throwOnError` is misleading. I had to go and look what sort of errors it would throw on, and then it wasn't quite clear whether I would get `onSerializationError` called either way, which required another follow through of the code.

I suggest renaming to `throwOnSerializationError` explaining why that is important to control (as per @LWogan's comment above about this information being in the wrong place).

Then I would document that `onSerializationError` is called no matter what `throwOnSerializtionError` is set to.

2023-05-04 11:21 UTC, simon-johnson-r3 commented on libs/messaging/kafka-message-bus-impl/src/main/kotlin/net/corda/messagebus/kafka/serialization/CordaAvroSerializerImpl.kt
> +                        runOnErrorLambda(message, onError)
I can't see a compelling reason not to move `runOnErrorLambda` above the `if`?
Then you can remove the helper method entirely as it's only a one liner anyway.

2023-05-04 11:21 UTC, simon-johnson-r3 commented on libs/serialization/serialization-avro/src/main/kotlin/net/corda/avro/serialization/CordaAvroSerializationFactory.kt
> +        onError: Consumer<ByteArray>,
Small point, and not related to this change, but I find it unusual that when I'm creating a deserializer, the first parameter is not the class but the error consumer.

I also find the use of Consumer<> here a little idiosyncratic when this is really an error callback. Consumer has a semantic meaning that is not really appropriate in this use case. Perhaps this is because it was moved from a Java api and some Java functional interface to represent the callback was required then? Either way I think this will confuse future maintainers and accepting a Kotlin lambda would be better.

2023-05-04 11:41 UTC, pmck91 commented on libs/serialization/serialization-avro/src/main/kotlin/net/corda/avro/serialization/CordaAvroSerializationFactory.kt
> +        onError: Consumer<ByteArray>,
Ive swapped it to a regular lambda now

2023-05-04 13:08 UTC, vkolomeyko commented on applications/workers/release/rest-worker/build.gradle
> +    e2eTestImplementation project(':libs:serialization:serialization-avro')
Why do we need this extra "implementation" dependency when no source files been modified which use classes from that module?

2023-05-04 13:16 UTC, seanbrereton submitted a review, later dismissed
LGTM(build files only)

2023-05-04 13:58 UTC, simon-johnson-r3 commented on libs/serialization/serialization-avro/src/main/kotlin/net/corda/avro/serialization/CordaAvroSerializationFactory.kt
> +        onError: Consumer<ByteArray>,
Am I correct in thinking you switched it on createAvroSerializer but not createAvroDeserializer?

2023-05-04 14:02 UTC, pmck91 commented on libs/serialization/serialization-avro/src/main/kotlin/net/corda/avro/serialization/CordaAvroSerializationFactory.kt
> +        onError: Consumer<ByteArray>,
missed it! added now

2023-05-04 14:25 UTC, simon-johnson-r3 submitted a review, later dismissed

2023-05-04 14:52 UTC, LWogan reviewed
Looking good! Almost there!

2023-05-04 14:52 UTC, LWogan commented on libs/messaging/kafka-message-bus-impl/src/main/kotlin/net/corda/messagebus/kafka/serialization/CordaAvroDeserializerImpl.kt
> + * @property onError lambda to be run on deserialization error
expectedClass missing

2023-05-04 14:52 UTC, LWogan commented on libs/messaging/message-bus/src/main/kotlin/net/corda/messagebus/api/producer/builder/CordaProducerBuilder.kt
> +     * @param onSerializationError a callback to receive messages that fail to serialize.  In the producer feed
This is still a bit off
```
@param onSerializationError a callback to receive messages that fail to serialize. In the producer feed
these will show up as records with a null value, which means they should be removed from any maps.
```

should be something like:
`@param onSerializationError a callback to execute when serialization fails 
`
theres other stuff that uses the serializer, not just producers, and this flag doesnt flag whether we return null anymore

2023-05-04 15:17 UTC, pmck91 commented on applications/workers/release/rest-worker/build.gradle
> +    e2eTestImplementation project(':libs:serialization:serialization-avro')
without it the task :applications:workers:release:rest-worker:compileE2eTestKotlin fails as it cant find the supertypes which were previously supplied by corda api

```
Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:
    class net.corda.messagebus.kafka.serialization.CordaAvroSerializationFactoryImpl, unresolved supertypes: net.corda.avro.serialization.CordaAvroSerializationFactory
```

2023-05-04 16:19 UTC, vkolomeyko commented on applications/workers/release/rest-worker/build.gradle
> +    e2eTestImplementation project(':libs:serialization:serialization-avro')
But if this is the case should module containing `CordaAvroSerializationFactoryImpl` have dependency on module containing `CordaAvroSerializationFactory` as `api` dependency?
If transitive dependency expressed that way this will eliminate the need to put `implementation project(':libs:serialization:serialization-avro')` in many modules.

2023-05-04 16:22 UTC, vkolomeyko commented on libs/messaging/kafka-message-bus-impl/build.gradle
> +    implementation project(":libs:serialization:serialization-avro")
```suggestion
    api project(":libs:serialization:serialization-avro")
```
Due to `CordaAvroSerializationFactoryImpl` using `CordaAvroSerializationFactory` as a super-type.

2023-05-05 08:18 UTC, vkolomeyko commented on components/chunking/chunk-db-write-impl/build.gradle
> +    implementation project(":libs:serialization:serialization-avro")
Do we need this line?

2023-05-05 08:18 UTC, vkolomeyko commented on components/flow/flow-p2p-filter-service/build.gradle
> +    implementation project(":libs:serialization:serialization-avro")
Do we need this line?

2023-05-05 08:18 UTC, vkolomeyko commented on components/membership/membership-service-impl/build.gradle
> +    implementation project(":libs:serialization:serialization-avro")
Do we need this line, provided that no source code been changed?

2023-05-05 10:14 UTC, LWogan commented on libs/messaging/message-bus/src/main/kotlin/net/corda/messagebus/api/producer/builder/CordaProducerBuilder.kt
> +     * @param throwOnSerializationError throw exception on error or return null defaults to true
can remove throwOnSerializationError now

2023-05-05 10:15 UTC, LWogan commented on libs/messaging/messaging-impl/src/main/kotlin/net/corda/messaging/subscription/consumer/builder/StateAndEventBuilder.kt
> +     * @param throwOnSerializationError throw exception on serialization error, or return null. defaults to throw
need to remove throwOnSerializationError kdoc

2023-05-05 10:15 UTC, LWogan commented on libs/serialization/serialization-avro/src/main/kotlin/net/corda/avro/serialization/CordaAvroSerializationFactory.kt
> +     * @param throwOnSerializationError throw an exception on serialization failure, or return null (defaults to true)
need to remove throwOnSerializationError kdoc

2023-05-05 10:16 UTC, LWogan reviewed
couple kdocs to remove, and we need to merge the other pr into this one. Other than that this is good to go

2023-05-05 10:33 UTC, LWogan commented on components/flow/flow-p2p-filter-service/build.gradle
> +    implementation project(":libs:serialization:serialization-avro")
there is code in this lib using this in flow p2p filter

2023-05-05 10:34 UTC, LWogan commented on components/membership/membership-service-impl/build.gradle
> +    implementation project(":libs:serialization:serialization-avro")
this one is used too

2023-05-05 10:34 UTC, LWogan commented on components/chunking/chunk-db-write-impl/build.gradle
> +    implementation project(":libs:serialization:serialization-avro")
this one could be changed to integrationTestImplementation i think

2023-05-05 12:46 UTC, LWogan approved these changes, later dismissed
LGTM

2023-05-05 12:57 UTC, thiagoviana submitted a review, later dismissed

2023-05-05 13:34 UTC, charlieR3 approved these changes
LGTM (network team files)

2023-05-05 13:36 UTC, mag1c-48 approved these changes
LGTM - build only

2023-05-05 13:50 UTC, simon-johnson-r3 approved these changes

2023-05-05 13:52 UTC, merged