CORE-9483 Removing requireBoxedType check from FlowSession and FlowMessaging classes
corda/corda-runtime-os pull request #3768
Opened 2023-04-28 16:44 UTC by ben-millar

2023-05-11 12:40 UTC, lankydan reviewed
Seems reasonable.

Probably not one for 5.0 because this change looks backwards compatible.

Also worth @chrisr3 or @josephzunigadaly having a quick look due to serialization/sandbox change.

2023-05-11 12:40 UTC, lankydan commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/application/sessions/impl/FlowSessionImpl.kt
> +        // We could call `.kotlin.javaObjectType` on non-primitive types too, and it would have no effect,
Extract this into a method and remove the comment imo.

2023-05-11 12:43 UTC, ben-millar commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/application/sessions/impl/FlowSessionImpl.kt
> +        // We could call `.kotlin.javaObjectType` on non-primitive types too, and it would have no effect,
Makes sense, I'll do that

2023-05-12 11:04 UTC, ben-millar commented
Currently, one of the new unit tests I added to test `char` serialisation is failing. After much hair pulling I've traced the root cause down to the Data library in Java ([DOCS](https://qpid.apache.org/releases/qpid-proton-j-0.33.8/api/org/apache/qpid/proton/codec/Data.html)). The `putChar()` and `getChar()` functions in this library use integer values (32-bit) rather than chars (16-bit); this widening is done to allow for negative values representing EOF characters, but this is causing a cast to fail in [DeserializationInput::doReadObject()](https://github.com/corda/corda-runtime-os/blob/release/os/5.1/libs/serialization/serialization-amqp/src/main/kotlin/net/corda/internal/serialization/amqp/DeserializationInput.kt#L145)

```
Internal deserialization failure: java.lang.ClassCastException: Cannot cast java.lang.Integer to java.lang.Character
```

Currently taking a look at the best way to fix this.

2023-05-12 15:05 UTC, chrisr3 commented
Derp, is someone suggesting that AMQP has been unable to handle primitive Java types for the past 7 years? :thinking:

2023-05-12 15:08 UTC, chrisr3 commented
> It's important to note that, unlike Java, Kotlin has no primitive types; instead, all primitive types (e.g., boolean, float, int) are represented by boxed classes.

Not quite. It's actually like this:
- `Int` -> `int`
- `Int?` -> `java.lang.Integer`
- `Short` -> `short`
- `Short?` -> `java.lang.Short`
- `Byte` -> `byte`
- `Byte?` -> `java.lang.Byte`
- `Char` -> `char`
- `Char?` -> `java.lang.Character`
- `Float` -> `float`
- `Float?` -> `java.lang.Float`
- `Double` -> `double`
- `Double?` -> `java.lang.Double`

The point is that Java primitives can _never_ be `null`.

2023-05-12 15:20 UTC, chrisr3 requested changes
AMQP serialization has _always_ supported Java primitive types - see [AMQPPrimitiveSerializer](https://github.com/corda/corda-runtime-os/blob/release/os/5.1/libs/serialization/serialization-amqp/src/main/kotlin/net/corda/internal/serialization/amqp/standard/AMQPPrimitiveSerializer.kt). Consequently, there should not be any need to touch `DeserializationInput`.

Seriously, what's going on?

2023-05-12 15:27 UTC, ben-millar commented
> AMQP serialization has _always_ supported Java primitive types - see [AMQPPrimitiveSerializer](https://github.com/corda/corda-runtime-os/blob/release/os/5.1/libs/serialization/serialization-amqp/src/main/kotlin/net/corda/internal/serialization/amqp/standard/AMQPPrimitiveSerializer.kt). Consequently, there should not be any need to touch `DeserializationInput`.
> 
> Seriously, what's going on?

@chrisr3 
AMQP serialization has always supported Java primitive types (Not so much 'handle' as return essentially untouched); the purpose of this ticket is to enable our flow sessions to handle Java primitive types. _However_, this work uncovered the fact that our implementation of `DeserializationInput` could not handle `char` types, because they were being cast to integers by the `AMQPPrimitiveSerializer` (for valid reasons).

The functional changes to DeserializationInput simply add handling for this ([HERE](https://github.com/corda/corda-runtime-os/pull/3768/files#diff-021102d7da23c7b21bd4e30bdfa4027ab6a6b9466f9a0c7f309cbb8c0894fc0eR333)) and, while doing that, I split out the `readObject()` function so it wouldn't need `@Suppress("NestedBlockDepth", "ComplexMethod")` annotations to pass the linter.

2023-05-12 15:48 UTC, chrisr3 commented
> this work uncovered the fact that our implementation of `DeserializationInput` could not handle `char` types, because they were being cast to integers by the `AMQPPrimitiveSerializer` (for valid reasons).

I am _deeply sceptical_ of any changes to AMQP's handing of primitive types. Our `SerializationOutputTests` class may not _explicitly_ test `char` atm, but that's easily fixed:
```diff
diff --git a/libs/serialization/serialization-amqp/src/test/kotlin/net/corda/internal/serialization/amqp/SerializationOutputTests.kt b/libs/serialization/serialization-amqp/src/test/kotlin/net/corda/internal/serialization/amqp/SerializationOutputTests.kt
index a442695e42..fc93e21cda 100644
--- a/libs/serialization/serialization-amqp/src/test/kotlin/net/corda/internal/serialization/amqp/SerializationOutputTests.kt
+++ b/libs/serialization/serialization-amqp/src/test/kotlin/net/corda/internal/serialization/amqp/SerializationOutputTests.kt
@@ -100,6 +100,9 @@ class SerializationOutputTests {
     @CordaSerializable
     data class TestBoolean(val b: Boolean)
 
+    @CordaSerializable
+    data class TestChar(val c: Char)
+
     @CordaSerializable
     interface FooInterface {
         val pub: Int
@@ -332,6 +335,12 @@ class SerializationOutputTests {
         serdes(obj)
     }
 
+    @Test
+    fun `test char`() {
+        val obj = TestChar('?')
+        serdes(obj)
+    }
+
     @Test
     fun `test foo implements`() {
         val obj = FooImplements("Hello World!", 123)
```
And it passes, which suggests to me that `AMQPPrimitiveSerializer` is working correctly.

2023-05-12 15:59 UTC, chrisr3 commented
> The functional changes to DeserializationInput simply add handling (narrowing conversion back to `char`) for this ([HERE](https://github.com/corda/corda-runtime-os/pull/3768/files#diff-021102d7da23c7b21bd4e30bdfa4027ab6a6b9466f9a0c7f309cbb8c0894fc0eR333))

Are you trying to serialize _naked_ primitive types with AMQP? I don't believe we have **ever** supported doing that - @mnesbit?

2023-05-12 16:33 UTC, ben-millar commented
> > The functional changes to DeserializationInput simply add handling (narrowing conversion back to `char`) for this ([HERE](https://github.com/corda/corda-runtime-os/pull/3768/files#diff-021102d7da23c7b21bd4e30bdfa4027ab6a6b9466f9a0c7f309cbb8c0894fc0eR333))
> 
> Are you trying to serialize _naked_ primitive types with AMQP? I don't believe we have **ever** supported doing that - @mnesbit?

Actually, you've uncovered a good point. So, honest-to-goodness primitive types are handled as of today [HERE](https://github.com/corda/corda-runtime-os/blob/release/os/5.1/libs/serialization/serialization-amqp/src/main/kotlin/net/corda/internal/serialization/amqp/DeserializationInput.kt#L214) – we simply return them... Or so it may seem. In actuality, the fact that the `obj` parameter is of type `Any` will cast any primitive objects to their boxed equivalent, so this will never be hit.

2023-05-12 16:40 UTC, ben-millar commented
> ```
>@CordaSerializable
>data class TestChar(val c: Char)
>
>@Test
>fun `test char`() {
>    val obj = TestChar('?')
>    serdes(obj)
>}
>```

Re: this test, I mentioned it offline (but it's worth noting here for future reference), by wrapping the `char` in a dataclass we're invoking the `ComposableObjectSerializer` rather than the `AMQPPrimitiveSerializer`. This, in turn, invokes the `ComposableTypePropertySerializer` on the `char` which delegates to `AMQPCharProperty[Write/Read]Strategy` [HERE](https://github.com/corda/corda-runtime-os/blob/release/os/5.1/libs/serialization/serialization-amqp/src/main/kotlin/net/corda/internal/serialization/amqp/ComposableTypePropertySerializer.kt#L221) which do the same sort of casting as I've added for the failing case.

2023-05-15 14:03 UTC, chrisr3 reviewed
I think this PR has a deeper problem.

2023-05-15 14:03 UTC, chrisr3 commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/application/persistence/PersistenceServiceImpl.kt
> -        requireBoxedType(entityClass)
But how would you declare _any_ native Java or Kotlin type to be a JPA `@Entity` in the first place? :confused::exploding_head:

I'd have thought something like:
```kotlin
if (!entityClass.isAnnotationPresent(Entity::class.java)) {
    throw IllegalArgumentException("$entityClass is not a JPA entity")
}
```
would be more appropriate, possibly with
```kotlin
requireCordaSerializable(entityClass)
```
thrown in.

2023-05-15 14:03 UTC, chrisr3 commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/application/services/impl/FlowMessagingImpl.kt
> -        requireBoxedType(receiveType)
I'd actually prefer
```kotlin
requireCordaSerializable(receiveType)
```
here.

2023-05-15 14:03 UTC, chrisr3 commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/application/sessions/impl/FlowSessionImpl.kt
> -        requireBoxedType(receiveType)
I'd prefer
```kotlin
requireCordaSerializable(receiveType)
requireCordaSerializable(payload::class.java)
```
here.

---

Or maybe not - see comment.

2023-05-15 14:03 UTC, chrisr3 commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/application/services/impl/FlowMessagingImpl.kt
> -            requireBoxedType(payload::class.java)
Or maybe
```kotlin
requireCordaSerializable(payload::class.java)
```
?

2023-05-17 10:19 UTC, chrisr3 commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/application/services/impl/FlowMessagingImpl.kt
> -        requireBoxedType(receiveType)
Actually, maybe I wouldn't after all. The problem is that `receiveType` may be an `interface` type, e.g. some kind of marker interface. The type of the actual _object_ received could be:
```kotlin
@CordaSerializable
data class Response(val message: String) : Marker
```
which _is_ `@CordaSerializable`, but `interface Marker` wouldn't know that :crying_cat_face:.

2023-07-12 15:59 UTC, closed without merging