CORE-7074 - move to official micrometer release
corda/corda-runtime-os pull request #3860
Opened 2023-05-12 08:44 UTC by driessamyn

Remove dependency on R3 compiled version of Micrometer, since our patch was merged in the official version.

2023-05-12 09:37 UTC, ronanbrowne commented
Finally :wink:

2023-05-12 10:12 UTC, driessamyn commented
> Finally 😉

Yes, if it had been released 48h earlier we wouldn't have had to release our own :( 

Sorry for putting a bunch of work on you only for a single release. 🍻 on me next time ;)

2023-05-12 10:41 UTC, ronanbrowne approved these changes, later dismissed
LGTM

2023-05-12 11:45 UTC, yarivus submitted a review, later dismissed
LGTM

2023-05-12 14:26 UTC, chrisr3 requested changes

2023-05-12 14:26 UTC, chrisr3 commented on buildSrc/src/main/groovy/corda.quasar-app.gradle
> +        'io.micrometer:micrometer.**',
This is supposed to be a package glob, not a Maven coordinate.

2023-05-12 14:31 UTC, driessamyn commented on buildSrc/src/main/groovy/corda.quasar-app.gradle
> +        'io.micrometer:micrometer.**',
Thanks for spotting this, @chrisr3 
I've changed it now.

2023-05-12 14:35 UTC, chrisr3 approved these changes
:+1:

2023-05-15 07:48 UTC, yarivus approved these changes
LGTM

2023-05-15 07:53 UTC, merged