CORE-10453 : Remote alias look up service
corda/corda-runtime-os pull request #3863
Opened 2023-05-12 11:30 UTC by SaurabhR3

1. Created injectable RemoteAliasLookUpService
2. Implemented hardcoded RemoteAliasLookUpService
3. Injected the service in FacadeInvocationFlow for logging purpose

2023-05-12 11:51 UTC, yarivus requested changes

2023-05-12 11:51 UTC, yarivus commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/RemoteAliasLookUpServiceImpl.kt
> +    SingletonSerializeAsToken {
```suggestion
class RemoteAliasLookUpServiceImpl @Activate constructor() :
    RemoteAliasLookUpService, UsedByFlow, SingletonSerializeAsToken {
```
I think it's more readable to have all the inherited in a single newline.

2023-05-12 11:51 UTC, yarivus commented on testing/cpbs/test-invocation-cordapp/src/main/kotlin/com/r3/corda/testing/interop/FacadeInvocationFlow.kt
> +//import net.corda.v5.application.interop.RemoteAliasLookUpService
remove comment - it's duplicate

2023-05-15 16:14 UTC, yarivus approved these changes
LGTM - minor style comment left

2023-05-15 16:56 UTC, SaurabhR3 commented on testing/cpbs/test-invocation-cordapp/src/main/kotlin/com/r3/corda/testing/interop/FacadeInvocationFlow.kt
> +//import net.corda.v5.application.interop.RemoteAliasLookUpService
Fixed in 2402153

2023-05-15 16:56 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/RemoteAliasLookUpServiceImpl.kt
> +    SingletonSerializeAsToken {
Fixed in 7c369e5

2023-05-15 16:56 UTC, yarivus approved these changes
Even Better - LGTM

2023-05-15 17:33 UTC, szymonsztuka commented on testing/cpbs/test-invocation-cordapp/src/main/kotlin/com/r3/corda/testing/interop/FacadeInvocationFlow.kt
> +        val alice = "CN=Alice Gold Alias, O=Alice Corp, L=LDN, C=GB";
This value should not be hard-coded in the flow.

2023-05-15 17:33 UTC, szymonsztuka commented on testing/cpbs/test-invocation-cordapp/src/main/kotlin/com/r3/corda/testing/interop/FacadeInvocationFlow.kt
> +        val cpiName = "Gold.cpi"
This value should not be hard-coded in the flow.

2023-05-15 17:33 UTC, szymonsztuka commented on testing/cpbs/test-invocation-cordapp/src/main/kotlin/com/r3/corda/testing/interop/FacadeInvocationFlow.kt
> +        log.info("AliasMemberInfo list for facadeId : $aliasMembers")
The result of the lookup has no impact on the flow/ is not use later on. In this case why to add this code?

2023-05-16 11:19 UTC, SaurabhR3 commented on testing/cpbs/test-invocation-cordapp/src/main/kotlin/com/r3/corda/testing/interop/FacadeInvocationFlow.kt
> +        log.info("AliasMemberInfo list for facadeId : $aliasMembers")
There are following 2 reasons
1. Client flow can inject the newly created injectable service . 
2. Logging the result confirms that client flow can make a use of its api.

2023-05-16 12:42 UTC, jmacmahonr3 requested changes

2023-05-16 12:42 UTC, jmacmahonr3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/HardcodedAliasIdentityServiceImpl.kt
> +                        "Gold", "Gold.cpi", listOf(
It wouldn't be gold.cpi as that's the file name. It's more likely to be "Gold Trading.

2023-05-16 12:42 UTC, jmacmahonr3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/RemoteAliasLookUpServiceImpl.kt
> +class RemoteAliasLookUpServiceImpl @Activate constructor() :
I'd suggest renaming to just RemoteAliasLookUp

2023-05-16 12:42 UTC, jmacmahonr3 commented on testing/cpbs/test-invocation-cordapp/src/main/kotlin/com/r3/corda/testing/interop/FacadeInvocationFlow.kt
> +        val cpiName = "Gold.cpi"
As mentioned earlier cpi name could be multiple words in a String like "Big Bank Gold Trading"

2023-05-16 12:42 UTC, jmacmahonr3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/RemoteAliasLookUpServiceImpl.kt
> +class RemoteAliasLookUpServiceImpl @Activate constructor() :
Also can we write a component test for it without using the facade invocation flow ?

2023-05-16 13:08 UTC, szymonsztuka commented on testing/cpbs/test-invocation-cordapp/src/main/kotlin/com/r3/corda/testing/interop/FacadeInvocationFlow.kt
> +        log.info("AliasMemberInfo list for facadeId : $aliasMembers")
You are using this code as pseudo unit test, nothing else. Please remove this code form the flow or make it contribute to the business logic.

2023-05-16 13:29 UTC, SaurabhR3 commented on testing/cpbs/test-invocation-cordapp/src/main/kotlin/com/r3/corda/testing/interop/FacadeInvocationFlow.kt
> +        val alice = "CN=Alice Gold Alias, O=Alice Corp, L=LDN, C=GB";
Fixed in d05b965

2023-05-16 13:29 UTC, SaurabhR3 commented on testing/cpbs/test-invocation-cordapp/src/main/kotlin/com/r3/corda/testing/interop/FacadeInvocationFlow.kt
> +        val cpiName = "Gold.cpi"
Fixed in d05b965

2023-05-16 13:33 UTC, yarivus approved these changes
LGTM

2023-05-16 13:35 UTC, SaurabhR3 commented on testing/cpbs/test-invocation-cordapp/src/main/kotlin/com/r3/corda/testing/interop/FacadeInvocationFlow.kt
> +        log.info("AliasMemberInfo list for facadeId : $aliasMembers")
It's not the unit test, this is to validate that can service be injected in client flow? and can client flow use the API of injected service? This can not be tested in Unit test. It needs a client flow.
If we remove this code how can we prove that the `RemoteAliasLookUpService` is an `Injectable Service` for client flow?

2023-05-16 13:44 UTC, szymonsztuka commented on testing/cpbs/test-invocation-cordapp/src/main/kotlin/com/r3/corda/testing/interop/FacadeInvocationFlow.kt
> +        log.info("AliasMemberInfo list for facadeId : $aliasMembers")
We know we can inject `RemoteAliasLookUpService` because it's an injectable service as any other services, or even this code line `@CordaInject lateinit var remoteAliasLookUpService: RemoteAliasLookUpService` proves we can inject. However the actuall usage of the service here doesn't add anything to the business logic of the flow (the result of a call is not use to invoke a facade).

2023-05-16 14:49 UTC, SaurabhR3 commented on testing/cpbs/test-invocation-cordapp/src/main/kotlin/com/r3/corda/testing/interop/FacadeInvocationFlow.kt
> +        log.info("AliasMemberInfo list for facadeId : $aliasMembers")
Fixed in 215a0d5

2023-05-16 14:49 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/HardcodedAliasIdentityServiceImpl.kt
> +                        "Gold", "Gold.cpi", listOf(
Fixed in 215a0d5

2023-05-16 14:50 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/RemoteAliasLookUpServiceImpl.kt
> +class RemoteAliasLookUpServiceImpl @Activate constructor() :
Comment 1. Fixed in 215a0d5
Comment 2. Working on it.

2023-05-16 14:51 UTC, SaurabhR3 commented on testing/cpbs/test-invocation-cordapp/src/main/kotlin/com/r3/corda/testing/interop/FacadeInvocationFlow.kt
> +        val cpiName = "Gold.cpi"
Fixed in 215a0d5

2023-05-16 15:26 UTC, yarivus approved these changes
LGTM

2023-05-17 08:21 UTC, simon-johnson-r3 requested changes

2023-05-17 08:21 UTC, simon-johnson-r3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/RemoteAliasLookUpImpl.kt
> +            memberInfo.identifier.equals(
Is this a Java-ism? In Kotlin you should use the structural equality operator == otherwise future maintainers will think you are doing something special here - unless you are doing something special, but then I'm wondering what.

2023-05-17 08:48 UTC, szymonsztuka requested changes

2023-05-17 08:48 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/RemoteAliasLookUpImpl.kt
> +            memberInfo.identifier.equals(
What if we have more entries matching the filter, then why we are taking the first one and not the second one? 
Also `getAliasMemberData` doesn't guarantee any stable ordering, at least nothing is described about this, so it could happen the same invocation could return a different entry each time.

2023-05-17 08:48 UTC, szymonsztuka commented on testing/cpbs/test-invocation-cordapp/src/main/kotlin/com/r3/corda/testing/interop/FacadeInvocationFlow.kt
> -
Undo line removal.

2023-05-17 08:48 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/RemoteAliasLookUpImpl.kt
> +    override fun lookup(facadeId: String?): List<AliasMemberInfo> {
Just a suggestion as this is more about the design, if a client code really need to get all aliases supporting the given facade , then it can use the latter function `getAliasMemberData()` and filter manually, exactly what is in the body of this method. We don't need to complicate API.

2023-05-17 08:48 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/HardcodedAliasIdentityServiceImpl.kt
> +class HardcodedAliasIdentityDataServiceImpl @Activate constructor() : AliasIdentityDataService {
Why this service is separated from  `RemoteAliasLookUpImpl` ? Seems like the only responsibility for this service is to store hardcoded data, then it can be just moved to a private method of 'RemoteAliasLookupImpl'.
Other note, the hardcoded data is never used, why bother to have this data then?

2023-05-17 08:48 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/HardcodedAliasIdentityServiceImpl.kt
> +data class DummyAliasMemberInfo(
If this is a temporary class, prefer using anonymous instances of an interface. Alos does it mean we do have only an interface `AliasMemberInfo` and we don't have any proper (aka not Dummy" in name ) call implementing those interface.

2023-05-17 08:48 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/HardcodedAliasIdentityServiceImpl.kt
> +data class GroupData(
This (and the next class) seem like should be in API, so how Cordapps can use it? I'm not sure is there different API for Cordapp and these classes are used only for InteropService?

2023-05-17 10:39 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/HardcodedAliasIdentityServiceImpl.kt
> +class HardcodedAliasIdentityDataServiceImpl @Activate constructor() : AliasIdentityDataService {
I've amending my previous comment, after thinking, i know that I ask to remove a sample usage from a flow, and now I'm complaining about no using the code in any flow. What about creating a new flow in the existing Cordapp to use this new API with hard-coded data, the result of the flow could return data from AliasMemberInfo.  How this approach is better than adding to the existing flow - it's clearly separates the usage, then new flow aim is just to use service with hardcoded data to output it, while the same new service has now real use (fro now) in the existing flow:
```
class AliasLookupTestFlow : ClientStartableFlow {

    @CordaInject
    lateinit var aliasLookup:  ...type


    @Suspendable
    override fun call(requestBody: ClientRequestBody): String {
        
        val args = requestBody.getRequestBodyAsMap(jsonMarshallingService, String::class.java, String::class.java)

        val interopGroupId = getArgument(args, "interopGroupId")
        val facadeId = getArgument(args, "facadeId")
        val alias = MemberX500Name.parse(getArgument(args, "alias"))
        //..whaterver is needed 

        val result = aliasLookup.lookup() 

        return result.toString() //If toString() doesn't return anything nice consider creating manually string with some fileds from result
    }
}
```

2023-05-17 12:14 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/RemoteAliasLookUpImpl.kt
> +            memberInfo.identifier.equals(
@szymonsztuka We are comparing value against the `identifier` and this `identifier` will be unique. This unique constraint we need to add at the time of alias registration. We are going to develop the alias registration in upcoming milestone.  So here we can say that only one Alias member info will be available and there won't be second.

2023-05-17 12:16 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/RemoteAliasLookUpImpl.kt
> +    override fun lookup(facadeId: String?): List<AliasMemberInfo> {
We discussed this and agree on this in our deep dive session hence I have added this API.

2023-05-17 12:25 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/HardcodedAliasIdentityServiceImpl.kt
> +class HardcodedAliasIdentityDataServiceImpl @Activate constructor() : AliasIdentityDataService {
Actually I would avoid to create the new cordapp for such reason. Ultimately what we need is to call API, after that whether you print it as a log or return it to caller does not make much difference. According to me both are not adding any value.

2023-05-17 12:29 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/HardcodedAliasIdentityServiceImpl.kt
> +data class DummyAliasMemberInfo(
I am not a fan of anonymous instances, How about changing the name from `Dummy` to `Fake` or `AliasInfo`?
Bear in mind that these classes will be removed soon.

2023-05-17 12:31 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/HardcodedAliasIdentityServiceImpl.kt
> +data class GroupData(
All the classes in `HardcodedAliasIdentityServiceImpl` are temporary and just to create the fake data. They are not going to be used by any other service.

2023-05-17 12:38 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/HardcodedAliasIdentityServiceImpl.kt
> +data class DummyAliasMemberInfo(
I have removed Dummy from classes

2023-05-17 13:02 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/HardcodedAliasIdentityServiceImpl.kt
> +class HardcodedAliasIdentityDataServiceImpl @Activate constructor() : AliasIdentityDataService {
I don't want to create a cordapp, just add a new flow (_What about creating a new flow in the **existing** Cordapp ..._)

2023-05-17 13:02 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/HardcodedAliasIdentityServiceImpl.kt
> +data class GroupData(
The whole service  `HardcodedAliasIdentityServiceImpl` looks like temporary service, so maybe for simplicity just move the method of the hardcoded data to `RemoteAliasLookUpImpl`. We do have some temporary services in our code, however I think most likely if created if you have a proper interface, but tactically if don't have the desierd implementation yet, or the temporary service requires to be a service to achieve it's role (like AliasProcessor is quasi-temporary, but it listens to a Kafka queue, so it needs to exists, and maybe it couldn't be refactored to a method or it would complicate other code).

2023-05-17 13:02 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/HardcodedAliasIdentityServiceImpl.kt
> +@Component(service = [AliasIdentityDataService::class])
`HardcodedAliasIdentityDataServiceImpl` is not used in the code as a Corda service, we can remove this annotation.

2023-05-17 13:02 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/RemoteAliasLookUpImpl.kt
> +        return HardcodedAliasIdentityDataServiceImpl().getAliasIdentityData().flatMap { it.members }.toList()
What about just hard-coding the result here (the list),  it would reduce number of classes and fake services (`HardcodedAliasIdentityDataServiceImpl`).

2023-05-17 13:02 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/HardcodedAliasIdentityServiceImpl.kt
> +        return "ANYSHORTHASH"
This is not a hardcoded data class, we should not have  `return "ANYSHORTHASH"`, we do need a field or a code to compute a hash from other existing field.

2023-05-17 13:02 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/HardcodedAliasIdentityServiceImpl.kt
> +        return networks.map { AliasMember(member, it.network, groupName, it.cpiName, it.facadeIds) }.toMutableList()
Maybe better returning immutable list, or if these are unique it could be a set (however probably in Corda we generally do use sets?), so it can be a list.

2023-05-17 13:17 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/RemoteAliasLookUpImpl.kt
> +        return HardcodedAliasIdentityDataServiceImpl().getAliasIdentityData().flatMap { it.members }.toList()
I did it because of following reason.

1. I don't want to create the hard coded data in RemoteAliasLookUpImpl as it is not its responsibility. Its responsibility is just to filter the data as per API.
2. When we will fetch the real data from cache, we will need one service, for that reason I have created AliasIdentityDataService
3. From the class name `HardcodedAliasIdentityDataServiceImpl` you guess the purpose.

Even if we try to hard code the result there, we need to either create the anonymous instances or data classes in RemoteAliasLookUpImpl, I personally feel it does not look good, just for reducing the some classes.

2023-05-17 13:18 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/RemoteAliasLookUpImpl.kt
> +        return getAliasMemberData().firstOrNull {
Would a map be better data structure (not from performance point of view, as we want have many elements), but from a conceptual point of view (we search for a result which we know is unique ( this is a unique identifier`"$x500Name@$cpiName"` across the whole view of my aliases)?

2023-05-17 13:20 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/HardcodedAliasIdentityServiceImpl.kt
> +        return "ANYSHORTHASH"
This is hardcoded data, why do we need to compute it from other field? and from which field?

2023-05-17 13:26 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/RemoteAliasLookUpImpl.kt
> +        return getAliasMemberData().firstOrNull {
May be, for that we need to process the cache entry to create the map.

2023-05-17 13:31 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/RemoteAliasLookUpImpl.kt
> +        return HardcodedAliasIdentityDataServiceImpl().getAliasIdentityData().flatMap { it.members }.toList()
Ok.
1 . I don't think this is true, we don't know yet, but ok.
2. `AliasIdentityDataService` is not used by `RemoteAliasLookUpImpl`.
3.  `HardcodedAliasIdentityDataServiceImpl` type has already been hardcoded/leaked into `RemoteAliasLookUpImpl.getAliasMemberData` method, so for me a simpler solution would be just a function here.
`RemoteAliasLookUpImpl` doesn't use the service as an interface on, we can't inject implementation but without a need to modify the code `RemoteAliasLookUpImpl`.

2023-05-17 13:49 UTC, yarivus approved these changes
LGTM

2023-05-17 13:51 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/RemoteAliasLookUpImpl.kt
> +        return HardcodedAliasIdentityDataServiceImpl().getAliasIdentityData().flatMap { it.members }.toList()
1. We know that creating or fetching cache data is not responsibility of RemoteAliasLookUp, data will be provided by another service from cache.
2. 3. I agree `AliasIdentityDataService` is not used in `RemoteAliasLookUpImpl`

I am still not convinced that we should move function and data classes in `RemoteAliasLookUpImpl` and remove the `HardcodedAliasIdentityDataServiceImpl`
We can just get rid of `AliasIdentityDataService` as we don't know how the API will look like for this.

2023-05-17 15:29 UTC, jmacmahonr3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/RemoteAliasLookUpImpl.kt
> +        return getAliasMemberData().firstOrNull {
Likely best to ask how MemberLookup works and model after them. Consistency is good

2023-05-18 15:51 UTC, yarivus approved these changes
LGTM

2023-05-18 15:51 UTC, yarivus approved these changes
LGTM

2023-05-19 13:18 UTC, szymonsztuka commented on testing/cpbs/test-invocation-cordapp/src/main/kotlin/com/r3/corda/testing/interop/FacadeInvocationFlow.kt
> +        log.info("AliasMemberInfo list for facadeId : $aliasMembers")
As spoken offline, yes it would be beneficial to add new new API call to this flow even if this doesn't have impact on the flow, however it shows to the reader that there will be API needed in each such flows - so in summary I'm withdrawing my objections/previous comments in this thread.

2023-05-19 13:19 UTC, szymonsztuka commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/HardcodedAliasIdentityServiceImpl.kt
> +        return "ANYSHORTHASH"
Fair, agree

2023-05-19 14:48 UTC, SaurabhR3 commented on testing/cpbs/test-invocation-cordapp/src/main/kotlin/com/r3/corda/testing/interop/FacadeInvocationFlow.kt
> +        log.info("AliasMemberInfo list for facadeId : $aliasMembers")
Fixed in 8464599

2023-05-19 14:49 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/RemoteAliasLookUpServiceImpl.kt
> +class RemoteAliasLookUpServiceImpl @Activate constructor() :
Added FetchFacadeFromAliasIdentityFlow which can be used for testing now and when we will have the actual implementation of  RemoteAliasLookUp

2023-05-19 14:50 UTC, SaurabhR3 commented on testing/cpbs/test-invocation-cordapp/src/main/kotlin/com/r3/corda/testing/interop/FacadeInvocationFlow.kt
> -
Fixed in 8464599

2023-05-19 14:50 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/HardcodedAliasIdentityServiceImpl.kt
> +class HardcodedAliasIdentityDataServiceImpl @Activate constructor() : AliasIdentityDataService {
Fixed in 8464599

2023-05-19 14:52 UTC, szymonsztuka approved these changes

2023-05-19 14:52 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/HardcodedAliasIdentityServiceImpl.kt
> +@Component(service = [AliasIdentityDataService::class])
Removed

2023-05-19 14:53 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/RemoteAliasLookUpImpl.kt
> +        return HardcodedAliasIdentityDataServiceImpl().getAliasIdentityData().flatMap { it.members }.toList()
Fixed in 8464599

2023-05-19 14:54 UTC, SaurabhR3 commented on components/interop/interop-service/src/main/kotlin/net/corda/interop/service/impl/RemoteAliasLookUpImpl.kt
> +        return getAliasMemberData().firstOrNull {
ok

2023-05-19 15:02 UTC, yarivus approved these changes
LGTM

2023-05-19 15:45 UTC, szymonsztuka approved these changes

2023-05-19 16:14 UTC, merged

2023-05-19 16:18 UTC, yarivus reviewed
thx @SaurabhR3