CORE-7287 duplicate topic keys bug
corda/corda-runtime-os pull request #3892
Opened 2023-05-16 16:07 UTC by ciaran238

Not ready for review

2023-07-04 09:02 UTC, simon-johnson-r3 commented
One thing I'm not entirely clear on. I assume this is a solution to that bug only because it avoids calling the function relating to auto topic creation in the db? Do we know why this is failing in the first place? Changing the combined worker setup so it writes topics on first startup is not such a bad idea, I just wonder if we know why auto topic creation isn't already working?

2023-07-04 09:03 UTC, simon-johnson-r3 requested changes

2023-07-04 09:03 UTC, simon-johnson-r3 commented on libs/application/application-db-setup/src/main/kotlin/net/corda/application/dbsetup/PostgresDbSetup.kt
I assume this is supposed to replace auto creation? Has that then been turned off?

2023-07-04 09:03 UTC, simon-johnson-r3 commented on libs/application/application-db-setup/src/main/kotlin/net/corda/application/dbsetup/PostgresDbSetup.kt
> +            createTopics()
Maybe make this more explicit: `createTopicsOnDbMessageBus` ?

2023-07-04 09:03 UTC, simon-johnson-r3 commented on libs/application/application-db-setup/src/main/kotlin/net/corda/application/dbsetup/PostgresDbSetup.kt
> +            createTopics()
This will cause problems if we configure the combined worker to use Kafka, which is a common use case. If will need to be called conditionally based on something like (needs checking):
```
params.defaultParams.messaging[BUS_TYPE] == BusType.DB.name
```
You can see an example of this parameter being used here: https://github.com/corda/corda-runtime-os/blob/dcaf4a3901e04a7066a17b80e4b27289147375ff/applications/workers/worker-common/src/main/kotlin/net/corda/applications/workers/workercommon/WorkerHelpers.kt#L100

2023-07-04 09:03 UTC, simon-johnson-r3 commented on libs/messaging/db-message-bus-datamodel/src/main/kotlin/net/corda/messagebus/db/datamodel/TopicEntry.kt
> +@Table(name = "messagebus.topic")
The rule is that entity definitions are always schema agnostic. Almost all schemas are configurable, however it is true that the message bus schema is (currently) hard coded as a parameter for the combined worker (rather than fed in on launch) here: https://github.com/corda/corda-runtime-os/blob/ec0ff3502c9ad26b27cd57d776dee33c44e72bce/applications/workers/release/combined-worker/src/main/kotlin/net/corda/applications/workers/combined/CombinedWorker.kt#L106

Here's an example of that being read: https://github.com/corda/corda-runtime-os/blob/411b9a6dc8bec4b5f7532615c855850cfa0877dd/libs/messaging/db-message-bus-impl/src/main/kotlin/net/corda/messagebus/db/configuration/DbBusConfigMergerImpl.kt#L23

The code should read this parameter and accommodate the schema at runtime in `createTopics` rather than have it hard coded in the annotation.

2023-07-04 09:03 UTC, simon-johnson-r3 commented on libs/messaging/db-message-bus-impl/src/main/kotlin/net/corda/messagebus/db/persistence/DBAccess.kt
> +        const val defaultNumPartitions = 3
This is only in here for auto topic creation. If we don't need that any more, we might consider moving it. It's the kind of thing which might be configurable externally. For now it could probably go alongside the postgres setup stuff.

2023-07-04 09:14 UTC, thiagoviana commented on libs/application/application-db-setup/src/main/kotlin/net/corda/application/dbsetup/PostgresDbSetup.kt
If that's the case, I believe this is also something we would need to change:

**?: if (autoCreate) {**


```/**
     * If auto topic creation is enabled then will create the topic
     */
    fun getTopicPartitionMapFor(topic: String): Set<CordaTopicPartition> {
        val topicEntry = executeWithErrorHandling(
            "get topic partition map",
            allowDuplicate = true,
        ) { entityManager ->
            entityManager.find(TopicEntry::class.java, topic)
                ?: if (autoCreate) {
                    val topicEntry = TopicEntry(topic, defaultNumPartitions)
                    entityManager.persist(topicEntry)
                    topicEntry
                } else {
                    throw CordaMessageAPIFatalException("Cannot find topic $topic")
                }
        }
        val topicPartitions = mutableSetOf<CordaTopicPartition>()
        repeat(topicEntry.numPartitions) { partition ->
            topicPartitions.add(CordaTopicPartition(topic, partition))
        }
        return topicPartitions
    }```

2023-07-04 16:35 UTC, pmck91 commented on applications/workers/release/combined-worker/src/main/kotlin/net/corda/applications/workers/combined/CombinedWorker.kt
> +        val createTopics = params.defaultParams.messaging[BUS_TYPE] == BusType.DB.name
perhaps a comment here, describing what this flag does would aid readability

2023-07-04 16:42 UTC, pmck91 commented on libs/application/application-db-setup/src/main/kotlin/net/corda/application/dbsetup/PostgresDbSetup.kt
Looking at the code, it looks like that comment provided context for the function call, which has changed. So the comment should be removed. The code also default autocorrect to true

https://github.com/corda/corda-runtime-os/blob/37615e6b9612a0649065954cda2b40449a177ead/libs/messaging/db-message-bus-impl/src/main/kotlin/net/corda/messagebus/db/persistence/DBAccess.kt#L132

the check could probably just be removed entirely. In this PR or a new ticket

2023-07-05 07:08 UTC, wzur-r3 approved these changes, later dismissed
LGTM for Gradle changes

2023-07-05 09:47 UTC, thiagoviana commented on applications/workers/release/combined-worker/src/main/kotlin/net/corda/applications/workers/combined/CombinedWorker.kt
> +        val createTopics = params.defaultParams.messaging[BUS_TYPE] == BusType.DB.name
It seems that this:

```params.defaultParams.messaging[BUS_TYPE] == BusType.DB.name```

It's comparing:

``` "DATABASE" == "DB" ```

2023-07-05 10:50 UTC, ciaran238 commented on libs/application/application-db-setup/src/main/kotlin/net/corda/application/dbsetup/PostgresDbSetup.kt
I have removed the auto creation as it wont be used anymore

2023-07-05 10:51 UTC, ciaran238 commented on libs/application/application-db-setup/src/main/kotlin/net/corda/application/dbsetup/PostgresDbSetup.kt
> +            createTopics()
changed to suggested name

2023-07-05 10:53 UTC, ciaran238 commented on libs/application/application-db-setup/src/main/kotlin/net/corda/application/dbsetup/PostgresDbSetup.kt
> +            createTopics()
A condition to check the bus type has been created

2023-07-05 10:54 UTC, ciaran238 commented on libs/messaging/db-message-bus-impl/src/main/kotlin/net/corda/messagebus/db/persistence/DBAccess.kt
> +        const val defaultNumPartitions = 3
I moved this as suggested

2023-07-13 08:09 UTC, ciaran238 commented on applications/workers/release/combined-worker/src/main/kotlin/net/corda/applications/workers/combined/CombinedWorker.kt
> +        val createTopics = params.defaultParams.messaging[BUS_TYPE] == BusType.DB.name
I have added this comment

2023-07-13 08:50 UTC, ciaran238 commented on libs/messaging/db-message-bus-datamodel/src/main/kotlin/net/corda/messagebus/db/datamodel/TopicEntry.kt
> +@Table(name = "messagebus.topic")
I have removed these changes I made to TopicEntry, and instead added a new connection in `PostgresDbSetup.kt` for the messagebus and made changes to `SqlFormatters.kt` so that columns can be annotated with `@Id`

2023-07-17 16:05 UTC, ben-millar reviewed
Mostly LGTM, just a couple of small comments to double check

2023-07-17 16:05 UTC, ben-millar commented on testing/db-message-bus-testkit/src/main/kotlin/net/corda/db/messagebus/testkit/DBSetup.kt
> +            if(!topicsCreated) {
Do we need to check this here if it's already done in `PostgresDbSetup`? Or vice versa; can we just do it in one of the two spots?

2023-07-17 16:05 UTC, ben-millar commented on applications/workers/release/combined-worker/src/main/kotlin/net/corda/applications/workers/combined/CombinedWorker.kt
> +            dbBusType,
Discussed offline, just check if we need to pass this bool in.

2023-07-18 08:24 UTC, ciaran238 commented on testing/db-message-bus-testkit/src/main/kotlin/net/corda/db/messagebus/testkit/DBSetup.kt
> +            if(!topicsCreated) {
This is for the in-memory db message bus which doesnt use `PostgresDbSetup`

2023-07-19 11:21 UTC, simon-johnson-r3 requested changes

2023-07-19 11:21 UTC, simon-johnson-r3 commented on applications/workers/worker-common/src/main/kotlin/net/corda/applications/workers/workercommon/WorkerHelpers.kt
> +    DATABASE
Because the name value of this enum value is used in the code, where it is compared to bootstrap parameters passed to the worker, it forms part of the worker public API. You shouldn't then change it because we do not permit breaking API changes between versions of Corda.

2023-07-19 11:21 UTC, simon-johnson-r3 commented on libs/application/application-db-setup/src/main/kotlin/net/corda/application/dbsetup/PostgresDbSetup.kt
> +                DbMessageBusSetup().createTopicsOnDbMessageBus(messageBusConnection())
Code like this, where you instantiate something, call a single method on it, and never use the instance again can point to an anti-pattern. Specifically that is more likely to be true where you must call that single method and there is no other method to call, which is the case here. In other words, if you must always do this and only this, there is no real point in instantiating anything at all.

Here I would suggest moving `createTopicsOnDbMessageBus` into the companion object of `DbMessageBusSetup` and leaving the call point as
```
DbMessageBusSetup.createTopicsOnDbMessageBus(messageBusConnection())
```
Then it remains scoped, but no temporary object instance is required.

2023-07-19 11:21 UTC, simon-johnson-r3 commented on testing/db-message-bus-testkit/src/main/kotlin/net/corda/db/messagebus/testkit/DBSetup.kt
> +    var topicsCreated = false
Should this be private, and do we need it at all?

2023-07-19 11:21 UTC, simon-johnson-r3 commented on libs/application/application-db-setup/src/main/kotlin/net/corda/application/dbsetup/DbMessageBusSetup.kt
> +    /** creates the topics for the INMEMORY or DATABASE db message bus
Generally speaking you would stick to the code style of the surrounding code. Here that would dictate to put `/**` on it's own line.

2023-07-19 11:21 UTC, simon-johnson-r3 commented on libs/application/application-db-setup/src/main/kotlin/net/corda/application/dbsetup/DbMessageBusSetup.kt
> +        messageBusConnection.use { connection ->
The use of `use` here means this function closes the connection. That is not documented in the api, but you should also consider, given you pass the connection in to this function and its created externally, whether that is really what you want.

I would suggest the caller, who is in control of creating the connection would be better placed to say whether they wanted it closed or not.

2023-07-19 11:21 UTC, simon-johnson-r3 commented on testing/db-message-bus-testkit/src/main/kotlin/net/corda/db/messagebus/testkit/DBSetup.kt
> +                DbMessageBusSetup().createTopicsOnDbMessageBus(dataSource.connection)
`dataSource.connection` was closed already on line 52. Actually I see it was also closed on line 50 too, an existing problem! I guess this works because `close` isn't doing much, or perhaps release back to a pool such that the connection is still valid - although this will mess up pool management.

I wouldn't make the problem worse. Could you try and refactor so `close` is only called once? (note that this overlaps with the comment I made on `DbMessageBusSetup` above about closing connections.

2023-07-19 11:21 UTC, simon-johnson-r3 commented on libs/application/application-db-setup/src/main/kotlin/net/corda/application/dbsetup/DbMessageBusSetup.kt
> +            if (!connection.autoCommit) {
This strikes me as a bit non-deterministic. Here you are saying the function takes control of commits after all inserts are executed, but you also allow auto commits, where you can leave the db in a bad state if half of them are committed only.

I would suggest making the contract of this method (i.e. documenting in the header) that commits are controlled in all cases, and then guarding against that at runtime by putting a
```
require(!messageBusConnection.autoCommit()) { ... }
```
at the top of the function.

2023-07-24 13:36 UTC, ciaran238 commented on libs/application/application-db-setup/src/main/kotlin/net/corda/application/dbsetup/DbMessageBusSetup.kt
> +        messageBusConnection.use { connection ->
👍

2023-07-24 13:36 UTC, ciaran238 commented on libs/application/application-db-setup/src/main/kotlin/net/corda/application/dbsetup/DbMessageBusSetup.kt
> +    /** creates the topics for the INMEMORY or DATABASE db message bus
👍

2023-07-24 13:37 UTC, ciaran238 commented on testing/db-message-bus-testkit/src/main/kotlin/net/corda/db/messagebus/testkit/DBSetup.kt
> +                DbMessageBusSetup().createTopicsOnDbMessageBus(dataSource.connection)
👍

2023-07-24 13:37 UTC, ciaran238 commented on libs/application/application-db-setup/src/main/kotlin/net/corda/application/dbsetup/DbMessageBusSetup.kt
> +            if (!connection.autoCommit) {
👍

2023-07-24 13:37 UTC, ciaran238 commented on libs/application/application-db-setup/src/main/kotlin/net/corda/application/dbsetup/PostgresDbSetup.kt
> +                DbMessageBusSetup().createTopicsOnDbMessageBus(messageBusConnection())
👍

2023-07-24 14:02 UTC, ciaran238 commented on testing/db-message-bus-testkit/src/main/kotlin/net/corda/db/messagebus/testkit/DBSetup.kt
> +    var topicsCreated = false
Yes, it should be private. It is needed because the `beforeAll`  may be executed more than once but the topics only need to be created once.

2023-07-25 14:55 UTC, simon-johnson-r3 approved these changes, later dismissed

2023-07-25 14:59 UTC, pmck91 commented on applications/workers/worker-common/src/main/kotlin/net/corda/applications/workers/workercommon/WorkerHelpers.kt
> +    DATABASE
Is a better solution to change params.defaultParams.messaging[BUS_TYPE] to be db?

2023-07-25 15:06 UTC, thiagoviana approved these changes, later dismissed

2023-07-25 15:08 UTC, ciaran238 commented on applications/workers/worker-common/src/main/kotlin/net/corda/applications/workers/workercommon/WorkerHelpers.kt
> +    DATABASE
I dont think so, I think it should have been `DATABASE` before. 
params.defaultParams.messaging[BUS_TYPE]  is the key for what is passed in as the message bus type, it is documented that it should be KAFKA or DATABASE ([Combined Worker README](https://github.com/corda/corda-runtime-os/tree/release/os/5.1/applications/workers/release/combined-worker#from-the-command-line))

2023-07-25 15:19 UTC, mbrkic-r3 commented on libs/application/application-db-setup/src/main/kotlin/net/corda/application/dbsetup/DbMessageBusSetup.kt
> +            log.debug { "Got bundle $bundle for class (net.corda.schema.Schemas::class.java)" }
I guess we don't need "::class.java" in log message

2023-07-25 15:30 UTC, ronanbrowne approved these changes, later dismissed
LGTM (build)

2023-07-25 15:34 UTC, ciaran238 commented on libs/application/application-db-setup/src/main/kotlin/net/corda/application/dbsetup/DbMessageBusSetup.kt
> +            log.debug { "Got bundle $bundle for class (net.corda.schema.Schemas::class.java)" }
👍

2023-07-25 15:37 UTC, thiagoviana approved these changes

2023-07-25 15:39 UTC, ronanbrowne approved these changes

2023-07-26 08:52 UTC, merged