CORE-10051 Remove `HSMRegistrationBusService`
corda/corda-runtime-os pull request #3905
Opened 2023-05-17 15:08 UTC by kyriathar

- removes `HSMRegistrationBusService` and inlines `HSMRegistrationBusProcessor` creation in `CryptoProcessorImpl`
- removes crypto Kafka RPC clients dependencies from Crypto worker since Crypto Kafka relays are removed
- closes previous bus processor subscriptions on subscriptions re-creations
- removes duplicate following of dependent components of `CryptoProcessorImpl`
- adds lifecycle unit test for `CryptoProcessorImpl` asserting its lifecycle in terms of bus processor subscriptions
- aligns retrying config type with config schema

2023-05-18 09:50 UTC, dickon commented
Looks good. I did wonder whether we need to close the subscriptions. I don't think we ever have, even when we had standalone bus services, but there could be a leak there if the components goes down then up often?

2023-05-19 08:02 UTC, ronanbrowne requested changes
Minor comment on build.gradle

2023-05-19 08:02 UTC, ronanbrowne commented on processors/crypto-processor/build.gradle
> +//    runtimeOnly project(":libs:lifecycle:lifecycle-impl")
Should this be removed ?

2023-05-19 08:21 UTC, kyriathar commented on processors/crypto-processor/build.gradle
> +//    runtimeOnly project(":libs:lifecycle:lifecycle-impl")
Removed

2023-05-19 09:16 UTC, ronanbrowne approved these changes, later dismissed
LGTM - (build changes only)

2023-05-23 09:50 UTC, dickon commented on libs/crypto/crypto-config-impl/src/main/kotlin/net/corda/crypto/config/impl/RetryingConfig.kt
> +class RetryingConfig(internal val config: SmartConfig) : SmartConfig by config {
I think long term we can get rid of these config classes and use SmartConfig directly, but there's a case for leaving them in place, and for now this change is a good step since you are focussed on other things.

2023-05-23 09:50 UTC, dickon commented on processors/crypto-processor/build.gradle
> -    implementation project(":components:crypto:crypto-client-hsm")
Nice, I love seeing dependencies disappear

2023-05-23 09:50 UTC, dickon commented on processors/crypto-processor/src/test/kotlin/net/corda/processors/crypto/internal/CryptoProcessorImplTest.kt
> +                coordinatorFactory,
minor style point, not a blocker, but I'd use all keyword arguments on any argument list this long, since if someone needs to change the argument list of CryptoProcessorImpl later they have to do a lot of counting with positional arguments, especially if they don't add at the end.

Normally I switch over to keyword arguments when the functional call extends over multiple lines.

2023-05-23 09:50 UTC, dickon commented on processors/crypto-processor/src/test/kotlin/net/corda/processors/crypto/internal/CryptoProcessorImplTest.kt
> +        LifecycleTest {
I didn't know we could test lifecycle without bringing up OSGi, which I think this is doing. Nice.

(If this is bringing up OSGi I'd probably want it in the integrationTest directory).

2023-05-23 09:50 UTC, dickon commented on processors/crypto-processor/src/main/kotlin/net/corda/processors/crypto/internal/CryptoProcessorImpl.kt
> -        ::cryptoOpsClient,
I think it was intentional to include cryptoOpsClient here, so that CryptoProcessorImpl doesn't go up until everything it needs is ready. But I don't think that's essential, so maybe dropping what we don't need is okay. 

In this case, `CryptoOpsClient` is not OSGi and not Lifecycle, so it is just pointless, so deleting it is good.

(Changed my mind twice on this :))

2023-05-23 09:50 UTC, dickon commented on processors/crypto-processor/src/main/kotlin/net/corda/processors/crypto/internal/CryptoProcessorImpl.kt
> +    @get:VisibleForTesting
Seems a bit of a hack, but I don't really mind, can't see many problems coming from this.

2023-05-23 09:50 UTC, dickon commented on processors/crypto-processor/src/main/kotlin/net/corda/processors/crypto/internal/CryptoProcessorImpl.kt
> -    @Reference(service = JpaEntitiesRegistry::class)
So we imported the same thing twice with different names? Weird, seems a mistake.

Please keep the names aligned, so keep `jpaEntitiesRegistry` and delete `entitiesRegistry` since the class is called `JpaEntitiesRegistry`.

2023-05-23 09:50 UTC, dickon commented on processors/crypto-processor/src/main/kotlin/net/corda/processors/crypto/internal/CryptoProcessorImpl.kt
> +        flowOpsSubscription!!.start()
I know it's probably impossible for any of these !! to fail but I still believe we should not use !! in production codepaths, instead just log an ERROR and do nothing.

2023-05-23 09:50 UTC, dickon commented on processors/crypto-processor/src/main/kotlin/net/corda/processors/crypto/internal/CryptoProcessorImpl.kt
> +        flowOpsSubscription?.close()
Is this `close` enough to kill the thread and release everything?

2023-05-23 09:53 UTC, kyriathar commented on processors/crypto-processor/src/test/kotlin/net/corda/processors/crypto/internal/CryptoProcessorImplTest.kt
> +        LifecycleTest {
Doesn't brings up OSGi, just unit tests lifecycle stuff.

2023-05-23 09:56 UTC, kyriathar commented on libs/crypto/crypto-config-impl/src/main/kotlin/net/corda/crypto/config/impl/RetryingConfig.kt
> +class RetryingConfig(internal val config: SmartConfig) : SmartConfig by config {
Yes agreed, for now I just aligned it to be closer to schema to be more intuitive.

2023-05-23 09:56 UTC, kyriathar commented on processors/crypto-processor/build.gradle
> -    implementation project(":components:crypto:crypto-client-hsm")
Yes we no longer need the crypto clients within the crypto worker since Kafka relays are removed.

2023-05-23 09:57 UTC, kyriathar commented on processors/crypto-processor/src/main/kotlin/net/corda/processors/crypto/internal/CryptoProcessorImpl.kt
> -        ::cryptoOpsClient,
I don't think that's needed anymore, the `CryptoOpsClient` was included within the crypto worker because of the Kafka relays.

2023-05-23 09:58 UTC, kyriathar commented on processors/crypto-processor/src/main/kotlin/net/corda/processors/crypto/internal/CryptoProcessorImpl.kt
> +    @get:VisibleForTesting
That was needed to write the lifecycle unit test for the crypto processor, because the crypto processor is not a `Lifecycle`.

2023-05-23 10:06 UTC, kyriathar commented on processors/crypto-processor/src/main/kotlin/net/corda/processors/crypto/internal/CryptoProcessorImpl.kt
> -    @Reference(service = JpaEntitiesRegistry::class)
I just thought to leave to not increase PR's diff. Valid point, will address.

2023-05-23 10:23 UTC, kyriathar commented on processors/crypto-processor/src/test/kotlin/net/corda/processors/crypto/internal/CryptoProcessorImplTest.kt
> +                coordinatorFactory,
This is testing code so shouldn't matter much, named parameters seem more overhead to me in this case.

2023-05-23 10:24 UTC, kyriathar commented on processors/crypto-processor/src/main/kotlin/net/corda/processors/crypto/internal/CryptoProcessorImpl.kt
> +        flowOpsSubscription?.close()
Not really sure. I suppose it also kills the background thread for this subscription.

2023-05-23 10:32 UTC, kyriathar commented on processors/crypto-processor/src/main/kotlin/net/corda/processors/crypto/internal/CryptoProcessorImpl.kt
> +        flowOpsSubscription!!.start()
Yes I think it's impossible, in other case we just use some `it` reference to start them. Applied suggestion.

2023-05-23 11:24 UTC, fowlerrr commented on processors/crypto-processor/src/main/kotlin/net/corda/processors/crypto/internal/CryptoProcessorImpl.kt
> +        flowOpsSubscription?.close()
Yeah, it does exactly that.  Stops the background thread so no more callback from the old subscription (after whatever is pending, of course)

2023-05-23 11:27 UTC, fowlerrr commented on processors/crypto-processor/src/main/kotlin/net/corda/processors/crypto/internal/CryptoProcessorImpl.kt
> +        flowOpsSubscription?.close()
Having said that, subscriptions are _usually_ a good candidate for managed resources as you'll want to close them automatically on stop/close _and_ here.

Usually if your mechanism is to always `close -> create new` in the same place and you aren't doing anything else with the subscription then you should consider a managed resource.

If you're doing something else with the subscriptions then it gets trickier.

2023-05-23 11:32 UTC, fowlerrr commented on processors/crypto-processor/src/main/kotlin/net/corda/processors/crypto/internal/CryptoProcessorImpl.kt
> +    @get:VisibleForTesting
I think the correct (but out of scope) action would be to expose any created coordinators in the `LifecycleTest` suite.  I might look into that at some point.  It would be better than exposing internals.

2023-05-23 13:08 UTC, kyriathar commented on processors/crypto-processor/src/main/kotlin/net/corda/processors/crypto/internal/CryptoProcessorImpl.kt
> +        flowOpsSubscription?.close()
Changed to use managed resources.

2023-05-23 13:23 UTC, fowlerrr approved these changes, later dismissed

2023-05-23 16:01 UTC, fowlerrr approved these changes

2023-05-24 08:03 UTC, JamesHR3 approved these changes

2023-05-24 08:45 UTC, driessamyn approved these changes
LGTM

2023-05-24 08:50 UTC, merged