CORE-13161 Add initial interop grammar demo cordapp implementation
corda/corda-runtime-os pull request #3928
Opened 2023-05-22 10:20 UTC by ac101m

# Changes
- Add skeleton token cordapp for grammar demo.

# Info
- This will be moved out of the `corda-runtime-os` repo at a later date.
- Separate PR to implement ERC20-esque interface using interop facades (see: https://github.com/corda/corda-runtime-os/pull/3865).
- Application contracts are basically just stubs, no security whatsoever!

2023-05-22 11:30 UTC, szymonsztuka approved these changes

2023-05-22 12:38 UTC, yarivus requested changes

2023-05-22 12:38 UTC, yarivus commented on testing/cpbs/interop-demo/deploy.sh
> +set -e
why are we using this **VERY** long .sh file ?
Most of these steps are achieved using a mix of gradle + Jenkins pipeline ... 
Have you considered using that ?
I can't remember in previous interop demos such a .sh file ...

2023-05-22 12:38 UTC, yarivus commented on testing/cpbs/interop-demo/deploy.sh
> +cat > gradle-plugin-default-key.pem << EOF
this may be flagged by CIDER security ... 
Is there a way to do this in an alternative way ?

Maybe you should consult @ronanbrowne 's team ...

2023-05-22 12:38 UTC, yarivus commented on testing/cpbs/interop-demo/deploy.sh
> +echo "CPI_CHECKSUM=$CPI_CHECKSUM"
this (lines 182-203) could be 1 function of the script (if you still proceed with this long script).

Lines 140-169 could be another function ... 

You get the idea ;)

2023-05-22 12:42 UTC, ac101m commented on testing/cpbs/interop-demo/deploy.sh
> +set -e
This actually isn't the only janky shellscript we're currently making use of in interop...
I don't like it much either.
That being said, it's just for the purposes of the (now delayed) grammar demo. It's never going to be a permanent fixture anywhere.
Later the demo (basically all the files in this PR) will be moved out of runtime-os. It was more convenient in the short term to add it to runtime-os (or so I was told).

2023-05-22 12:48 UTC, yarivus commented on testing/cpbs/interop-demo/deploy.sh
> +set -e
I understand, but maybe if you consult the build team ... then either now or next time we will have to spend lesser time to create this long .sh file ...
If not, then next time we'll probably do the same thing (which seems less robust and debuggable)

2023-05-22 12:56 UTC, ronanbrowne commented on testing/cpbs/interop-demo/deploy.sh
> +cat > gradle-plugin-default-key.pem << EOF
there's no private key contained here , so it's not flagged by cider

2023-05-22 12:58 UTC, ronanbrowne commented on testing/cpbs/interop-demo/deploy.sh
> +cd ../corda-runtime-os && ./gradlew :tools:plugins:package:build -x test :tools:plugins:mgm:build -x test
if your goal is just to produce artifacts could run

./gradlew :tools:plugins:package:assemble :tools:plugins:mgm:assemble

no need for -x test then ( same with other places your doing build -x test)

2023-05-22 13:02 UTC, ronanbrowne commented on testing/cpbs/interop-demo/deploy.sh
> +cp ../corda-runtime-os/tools/plugins/package/build/libs/package-cli-plugin-*.jar ../corda-runtime-os/tools/plugins/mgm/build/libs/mgm-cli*.jar ./build/plugins/
runtime-os  now produces a fully packed version of the CLI with all it's plugins , are you sure you really need to do this copying around and building CLI first ?

see task `cliInstallArchive` in tools/build.gradle of rutnime-os , which would be triggered by the assemble task anyway

2023-05-22 13:32 UTC, szymonsztuka commented on testing/cpbs/interop-demo/deploy.sh
> +set -e
As far as I know, Corda doesn't  have such script or utility to run something on your local PC quickly without a simulator, this was partially confirmed by QA.
You have or a) Jenkins pipeline + e2e test, or b) Craft5 which is always incompatible with latest code version .... or a "stock" scripts/doc pages, which you need manually edit data/copy/paste for each deployment.

2023-05-22 14:12 UTC, ac101m commented on testing/cpbs/interop-demo/deploy.sh
> +cp ../corda-runtime-os/tools/plugins/package/build/libs/package-cli-plugin-*.jar ../corda-runtime-os/tools/plugins/mgm/build/libs/mgm-cli*.jar ./build/plugins/
I have no idea! (not the original author of this script), will experiment.

2023-05-22 15:09 UTC, szymonsztuka commented on testing/cpbs/interop-demo/deploy.sh
> +cp ../corda-runtime-os/tools/plugins/package/build/libs/package-cli-plugin-*.jar ../corda-runtime-os/tools/plugins/mgm/build/libs/mgm-cli*.jar ./build/plugins/
yes, a core of the script could have some redundant parts (due to being outdated or following some official docs)

2023-05-22 15:09 UTC, szymonsztuka approved these changes

2023-05-22 15:11 UTC, szymonsztuka commented on testing/cpbs/interop-demo/deploy.sh
> +echo "CPI_CHECKSUM=$CPI_CHECKSUM"
We plan for CORE-13032 to address this deployment in more sustainable way.

2023-05-23 08:50 UTC, ronanbrowne approved these changes
LGM (based on script issues being addressed in CORE-13032)

2023-05-23 08:58 UTC, merged

2023-05-23 13:28 UTC, yarivus commented on testing/cpbs/interop-demo/deploy.sh
> +cd ../corda-runtime-os && ./gradlew :tools:plugins:package:build -x test :tools:plugins:mgm:build -x test
@ac101m / @szymonsztuka take note that not all `-x test` were addressed following @ronanbrowne 's comments