core-notick - c5.0 freeze code owners proposal
corda/corda-runtime-os pull request #3986
Opened 2023-05-31 07:57 UTC by driessamyn

2023-05-31 12:15 UTC, relyafi approved these changes

2023-06-01 11:53 UTC, yarivus requested changes
@driessamyn  Any special reason I was removed from everything ?

2023-06-01 13:39 UTC, vkolomeyko commented on .github/CODEOWNERS
> +/applications/workers/release/rest-worker/      @vkolomeyko @mnesbit @driessamyn @ronanbrowne @rick-r3 @fenryka
Do we need to put individuals as owners/approvers when there is a team in GitHub for a particular functional area? (e.g. @corda/rest )

2023-06-01 13:40 UTC, relyafi commented on .github/CODEOWNERS
> +/applications/workers/release/rest-worker/      @vkolomeyko @mnesbit @driessamyn @ronanbrowne @rick-r3 @fenryka
> Do we need to put individuals as owners/approvers when there is a team in GitHub for a particular functional area? (e.g. @corda/rest )

@vkolomeyko I think that would be a bit more open than we'd like for 5.0, given that we only wanted a specific nominated SME, rather than a broader group.

2023-06-01 13:44 UTC, vkolomeyko commented on .github/CODEOWNERS
> +/applications/workers/release/rest-worker/      @vkolomeyko @mnesbit @driessamyn @ronanbrowne @rick-r3 @fenryka
But what if SME is not available on a given week when approval is needed? Who is going to approve in this case?

2023-06-01 14:14 UTC, relyafi commented on .github/CODEOWNERS
> +/applications/workers/release/rest-worker/      @vkolomeyko @mnesbit @driessamyn @ronanbrowne @rick-r3 @fenryka
It would fall back to the existing limited approvers list. They still have the ability to approve, this approach retains control, whilst reducing the bottlenecking on the existing limited approvers.

2023-06-01 14:35 UTC, driessamyn commented on .github/CODEOWNERS
> +/applications/workers/release/rest-worker/      @vkolomeyko @mnesbit @driessamyn @ronanbrowne @rick-r3 @fenryka
Yes, @relyafi is correct. This is just a compromise from the full "change freeze" situation. 

> But what if SME is not available on a given week when approval is needed? Who is going to approve in this case?

This is why there is a list of back-ups for each.

2023-06-01 14:36 UTC, driessamyn commented on .github/CODEOWNERS
> +/applications/workers/release/rest-worker/      @vkolomeyko @mnesbit @driessamyn @ronanbrowne @rick-r3 @fenryka
Yes, @relyafi is correct. This is just a compromise from the full "change freeze" situation. 

> But what if SME is not available on a given week when approval is needed? Who is going to approve in this case?

This is why there is a list of back-ups for each.

2023-06-01 14:38 UTC, driessamyn commented
> @driessamyn Any special reason I was removed from everything ?

I didn't think you'd be interested in being a reviewer/approver for core changes.
Feel free to add yourself to the engineering services groups you're interested in.

2023-06-01 15:38 UTC, yarivus commented
> > @driessamyn Any special reason I was removed from everything ?
> 
> I didn't think you'd be interested in being a reviewer/approver for core changes. Feel free to add yourself to the engineering services groups you're interested in.

I was added there by Ronan as some parts of the runtime-os I do review.

2023-06-02 07:38 UTC, driessamyn commented
> > > @driessamyn Any special reason I was removed from everything ?
> > 
> > 
> > I didn't think you'd be interested in being a reviewer/approver for core changes. Feel free to add yourself to the engineering services groups you're interested in.
> 
> I was added there by Ronan as some parts of the runtime-os I do review.

This change reverts back to a more granular list. As before, please add yourself to the lines you want to have control over.

2023-06-02 10:43 UTC, yarivus commented
> > > > @driessamyn Any special reason I was removed from everything ?
> > > 
> > > 
> > > I didn't think you'd be interested in being a reviewer/approver for core changes. Feel free to add yourself to the engineering services groups you're interested in.
> > 
> > 
> > I was added there by Ronan as some parts of the runtime-os I do review.
> 
> This change reverts back to a more granular list. As before, please add yourself to the lines you want to have control over.

For simplicity - please add me where ronanb applies as it was ;)

2023-07-26 11:10 UTC, closed without merging