CORE-11037 Read extra properties from DbConfig
corda/corda-runtime-os pull request #4052
Opened 2023-06-09 12:05 UTC by kyriathar

2023-06-09 15:11 UTC, simon-johnson-r3 requested changes

2023-06-09 15:11 UTC, simon-johnson-r3 commented on components/db/db-connection-manager/src/main/kotlin/net/corda/db/connection/manager/DbConfig.kt
> +    // TODO all the following configuration reading should probably be changed to mandatory (i.e. throw if not found),
if this is true right now, we should just do it and remove the TODO

2023-06-09 15:11 UTC, simon-johnson-r3 commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeDbFactoryImpl.kt
>              val config = createDbConfig(
Here you will need to create a config with all the new values. For now you'll need to hard code the values, like we do at line 30. At some point we'll need to move all those hard coded values elsewhere.

2023-06-12 08:55 UTC, kyriathar commented on components/db/db-connection-manager/src/main/kotlin/net/corda/db/connection/manager/DbConfig.kt
> +    // TODO all the following configuration reading should probably be changed to mandatory (i.e. throw if not found),
Done

2023-06-12 11:19 UTC, kyriathar commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeDbFactoryImpl.kt
>              val config = createDbConfig(
Done I think. I can see we treat as optional the below parameters within `fun createDbConfig`: 
* `jdbcUrl`
* `maxPoolSize`
* `minPoolSize`

However, we are always passing in arguments for those at call site. Should we make them non optional?

2023-06-12 11:51 UTC, simon-johnson-r3 commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeDbFactoryImpl.kt
>              val config = createDbConfig(
Yes I think so. `minPoolSize` can be nullable all the way to the HikariCP API, but I'm not sure that's a good idea as it leaks details of that through the abstraction. I assume by the time we call `createDbConfig` we already have a final version of `maxPoolSize` from whatever config and as such we can always set `minPoolSize` ourselves if the config value is `null`.

2023-06-12 17:19 UTC, kyriathar commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeDbFactoryImpl.kt
>              val config = createDbConfig(
Removed unneeded optional and nullable which are not needed as per the call site.

2023-06-14 14:31 UTC, simon-johnson-r3 requested changes

2023-06-14 14:31 UTC, simon-johnson-r3 commented on components/db/db-connection-manager/src/main/kotlin/net/corda/db/connection/manager/DbConfig.kt
> +    // The below `hashPath` takes care the case where DB_POOL_MIN_SIZE is null (DB_POOL_MIN_SIZE will always be present)
typo: hasPath

2023-06-14 14:39 UTC, simon-johnson-r3 submitted a review, later dismissed

2023-06-14 15:22 UTC, fowlerrr submitted a review, later dismissed

2023-06-14 19:09 UTC, driessamyn commented on components/db/db-connection-manager/src/main/kotlin/net/corda/db/connection/manager/DbConfig.kt
> +        configWithFallback.getInt(DatabaseConfig.DB_POOL_VALIDATION_TIMEOUT).toLong().run(Duration::ofSeconds)
Can we add the unit of time to the var name? (E.g. `_MS`, `_S`) so it's easier to figure out what is expected?

2023-06-14 19:09 UTC, driessamyn commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeDbFactoryImpl.kt
>              val config = createDbConfig(
I'm not sure what the actual values should be, but I think they need to come from config too.

I disagree with the min=0, max=10 value, because I can't see how we'd ever need 10 vnode connections in a pool, unless we have a bug.

2023-06-15 09:59 UTC, kyriathar commented
> I'm not sure what the actual values should be, but I think they need to come from config too.

> I disagree with the min=0, max=10 value, because I can't see how we'd ever need 10 vnode connections in a pool, unless we have a bug.

From offline conversation with @yift-r3 it seems that indeed max pool size of 1 should be fine for the most part. A need for a second connection could be when an API call (admin call I believe) comes in to DB worker for the same VNode.  

We can discuss over this and most likely bring max pool size for VNode datasources down to 1 (or 2) when populating the VNode configuration values in follow-up PR I think.

2023-06-15 10:05 UTC, simon-johnson-r3 commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeDbFactoryImpl.kt
>              val config = createDbConfig(
They should come from the Config yes. That is out of scope for this story however, it will be in a later one. Note that some of these values were hard coded from way back already, we haven't changed anything in that regard.

I also think it's unlikely we need 10 vnode connections but I think we need the metrics story really.

2023-06-15 10:48 UTC, kyriathar commented on components/db/db-connection-manager/src/main/kotlin/net/corda/db/connection/manager/DbConfig.kt
> +        configWithFallback.getInt(DatabaseConfig.DB_POOL_VALIDATION_TIMEOUT).toLong().run(Duration::ofSeconds)
Raised https://github.com/corda/corda-api/pull/1150 to address this comment.

2023-06-15 15:50 UTC, kyriathar commented on components/db/db-connection-manager/src/main/kotlin/net/corda/db/connection/manager/DbConfig.kt
> +        configWithFallback.getInt(DatabaseConfig.DB_POOL_VALIDATION_TIMEOUT).toLong().run(Duration::ofSeconds)
Done

2023-06-15 16:37 UTC, driessamyn approved these changes
LGTM

2023-06-15 16:48 UTC, merged