CORE-10444 Initial registration implementation
corda/corda-runtime-os pull request #4074
Opened 2023-06-13 13:58 UTC by ac101m

# Changes
- Add interop reader/writer services.
- Add interop alias identity cache service.
- Add kafka topic for interop information.
- Add alias identity administration endpoints.

# Review notes (address and delete before squash+merge!)
- Key in kafka topic is currently `<shortHash>:<interopGroupUUID>`, key is parsed when filling the cache, which is a bit hacky and needs a second opinion.
- Review package & module structure for consistency.
- Review naming of interop alias identities and make this consistent (`InteropIdentity` rather than `Alias` or `InteropAliasIdentity` or similar).
- Review TODOs in code messages and remove any related suppression annotations.
- Review log statement levels.

2023-06-14 13:53 UTC, ac101m commented on settings.gradle
> +
@julia-filipczak I assume you used the "create module" functionality in intellij? Unfortunately, that feature can't be trusted! Also, libs:interop is not actually a module (or rather it doesn't need to be). I'm fixing this on my branch, no need to do anything yourself. Just a heads up!

2023-06-14 13:55 UTC, ac101m commented on components/interop/interop-rest-service-impl/src/main/kotlin/net/corda/virtualnode/rest/impl/v1/InteropRestResourceHandler.kt
> +package net.corda.virtualnode.rest.impl.v1
@julia-filipczak Probably want to use a different package name. Something like `net.corda.interop.rest.impl.v1` I suspect!

2023-06-28 11:15 UTC, jmacmahonr3 requested changes

2023-06-28 11:15 UTC, jmacmahonr3 commented on components/interop/alias-info-cache-service-impl/src/main/kotlin/net/corda/interop/aliasinfo/cache/impl/AliasInfoCacheServiceEventHandler.kt
> +        coordinator.createManagedResource("InteropAliasIdentityProcessor.subscription") {
Change to InteropIdentityProcessor

2023-06-28 11:15 UTC, jmacmahonr3 commented on libs/interop/interop-rest/src/main/kotlin/net/corda/libs/interop/endpoints/v1/InteropRestResource.kt
> +    fun getInterOpGroups(
This should take the Hosting Identity's Vnode short hash as an input. 
Output should be a map of GroupID to GroupPolicy json.  

@ac101m & @szymonsztuka thoughts ?

2023-06-28 11:15 UTC, jmacmahonr3 commented on libs/interop/interop-rest/src/main/kotlin/net/corda/libs/interop/endpoints/v1/InteropRestResource.kt
> +    fun getInterOpIdentities(
Maybe convert to a map as well

2023-06-28 13:20 UTC, szymonsztuka commented on components/interop/alias-info-cache-service/src/main/kotlin/net/corda/interop/aliasinfo/cache/AliasInfoCacheService.kt
> +    fun getAliasIdentities(shortHash: String): Map<String, InteropAliasIdentity>
we should not return a map, `InteropAliasIdentity` already contains a field: _groupId – UUID of interop group_. Let's not duplicate data.

2023-06-28 13:20 UTC, szymonsztuka commented on components/interop/alias-info-cache-service/src/main/kotlin/net/corda/interop/aliasinfo/cache/AliasInfoCacheService.kt
> +    fun removeAliasIdentity(shortHash: String, aliasIdentity: InteropAliasIdentity)
What about error cases, e.g. we try to remove not present alias? maybe we should follow a Java map remove/put method convention?

2023-06-28 13:20 UTC, szymonsztuka commented on components/interop/alias-info-read-service-impl/src/main/kotlin/net/corda/interop/aliasinfo/read/impl/InteropAliasInfoReadServiceEventHandler.kt
> +        // re-register with saurabhs kafka topic
Is this something missing / TODO  or this comment needs to be removed.

2023-06-28 13:20 UTC, szymonsztuka commented on components/interop/alias-info-write-service-impl/src/main/kotlin/net/corda/interop/aliasinfo/write/impl/InteropAliasIdentityProducer.kt
> +            InteropAliasInfoWriteServiceImpl.log.error("Interop alias identity publisher is null, not publishing.")
Use instance logger from 'this' class.

2023-06-28 13:20 UTC, szymonsztuka commented on libs/interop/interop-rest/src/main/kotlin/net/corda/libs/interop/endpoints/v1/InteropRestResource.kt
> +    fun getInterOpGroups(
Rename to  `holdingidentityid`to `holdinginidentityshorthash` here and in other endpoints. I know we use both in various other endpoints but ...shorthash seems to be more consistent.

2023-06-28 13:20 UTC, szymonsztuka commented on components/interop/interop-rest-service-impl/src/main/kotlin/net/corda/interop/rest/impl/v1/InteropRestResourceImpl.kt
> +        holdingidentityid: String?
Is there any issue with having non nullable `holdingidentityid` parameter ....

2023-06-28 13:20 UTC, szymonsztuka commented on components/interop/interop-rest-service-impl/src/main/kotlin/net/corda/interop/rest/impl/v1/InteropRestResourceImpl.kt
> +            holdingidentityid!!,
If the parameter needs to be nullable (see previous question) then please don't use !!, validate if it's non nullable.

2023-06-28 13:20 UTC, szymonsztuka commented on components/interop/interop-rest-service-impl/src/main/kotlin/net/corda/interop/rest/impl/v1/InteropRestResourceImpl.kt
> +        return ResponseEntity.ok("OK")
Add case for data validation and sending "not-ok" response.

2023-06-28 13:20 UTC, szymonsztuka commented on components/interop/interop-rest-service-impl/src/main/kotlin/net/corda/interop/rest/impl/v1/InteropRestResourceImpl.kt
> +        return ResponseEntity.ok("OK")
Btw the response doesn't match the description from the endpoint.

2023-06-28 13:20 UTC, szymonsztuka commented on components/interop/interop-rest-service-impl/src/main/kotlin/net/corda/interop/rest/impl/v1/InteropRestResourceImpl.kt
> +        val groupToAliasMappings = aliasInfoCacheService.getAliasIdentities(holdingidentityid!!)
Same issue as above eliminate all `!!` as this will cause NPE.

2023-06-28 13:20 UTC, szymonsztuka commented on components/interop/interop-rest-service-impl/src/main/kotlin/net/corda/interop/rest/impl/v1/InteropRestResourceImpl.kt
> +        return listOf(UUID.randomUUID())
Should we check if holding the Vnode Hash has any InteropIdentitites, or even if Vnode exists?

2023-06-28 13:27 UTC, jmacmahonr3 requested changes

2023-06-28 13:27 UTC, jmacmahonr3 commented on components/interop/alias-info-cache-service-impl/src/main/kotlin/net/corda/interop/aliasinfo/cache/impl/AliasInfoCacheServiceEventHandler.kt
> +package net.corda.interop.aliasinfo.cache.impl
@ac101m we should probably change the cache name

2023-06-28 13:27 UTC, jmacmahonr3 commented on components/interop/alias-info-cache-service-impl/src/main/kotlin/net/corda/interop/aliasinfo/cache/impl/AliasInfoCacheServiceEventHandler.kt
> +        private const val GROUP_NAME = "interop_alias_identity"
Change Group name

2023-06-28 13:27 UTC, jmacmahonr3 commented on components/interop/alias-info-cache-service-impl/src/main/kotlin/net/corda/interop/aliasinfo/cache/impl/AliasInfoCacheServiceEventHandler.kt
> +class AliasInfoCacheServiceEventHandler(
Update cache name to be InterOpIdentityCache

2023-06-28 13:27 UTC, jmacmahonr3 commented on components/interop/alias-info-cache-service-impl/src/main/kotlin/net/corda/interop/aliasinfo/cache/impl/AliasInfoCacheServiceImpl.kt
> +class AliasInfoCacheServiceImpl @Activate constructor(
Fix name

2023-06-28 13:27 UTC, jmacmahonr3 commented on components/interop/alias-info-cache-service/src/main/kotlin/net/corda/interop/aliasinfo/cache/AliasInfoCacheService.kt
> +interface AliasInfoCacheService : Lifecycle {
Fix all names in this class

2023-06-28 13:27 UTC, jmacmahonr3 commented on components/interop/alias-info-cache-service/src/main/kotlin/net/corda/interop/aliasinfo/cache/AliasInfoCacheService.kt
> +interface AliasInfoCacheService : Lifecycle {
@ac101m im wondering if we need to think about returning a wrapper for the map so that we have some other object where we can see our own identities as well as our identities we can talk to. This might make it easier for flow egress.

2023-06-28 13:27 UTC, jmacmahonr3 commented on components/interop/alias-info-write-service-impl/src/main/kotlin/net/corda/interop/aliasinfo/write/impl/InteropAliasIdentityProducer.kt
> +    fun publishAliasIdentity(shortHash: String, interopAliasIdentity: InteropAliasIdentity) {
fix name

2023-06-28 13:27 UTC, jmacmahonr3 commented on components/interop/alias-info-write-service-impl/src/main/kotlin/net/corda/interop/aliasinfo/write/impl/InteropAliasInfoWriteServiceImpl.kt
> +            hostingVnode = "?"
@julia-filipczak it's up to you to fix this bit as you need to update the put

2023-06-28 13:27 UTC, jmacmahonr3 commented on components/interop/interop-rest-service-impl/src/main/kotlin/net/corda/interop/rest/impl/v1/InteropRestResourceImpl.kt
> +    override val protocolVersion = 1
move this higher up in the class. Ease of reading

2023-06-28 13:27 UTC, jmacmahonr3 commented on components/interop/interop-rest-service-impl/src/main/kotlin/net/corda/interop/rest/impl/v1/InteropRestResourceImpl.kt
> +//        ::interopManagementService
Remove comment

2023-06-28 13:27 UTC, jmacmahonr3 commented on components/interop/interop-write-service-impl/src/main/kotlin/net/corda/interop/write/service/producer/AliasIdentityProducer.kt
> +class AliasIdentityProducer(
Fix name

2023-06-28 13:27 UTC, jmacmahonr3 commented on components/interop/interop-write-service-impl/src/main/kotlin/net/corda/interop/write/service/producer/HostedIdentityProducer.kt
> +class HostedIdentityProducer(
Needs a comment explaining this class. 
Would be confusing for anyone looking for the actual Hosted Identities topic producer

2023-06-28 13:27 UTC, jmacmahonr3 commented on components/interop/interop-write-service-impl/src/main/kotlin/net/corda/interop/write/service/producer/HostedIdentityProducer.kt
> +        private val logger = LoggerFactory.getLogger(this::class.java.enclosingClass)
Add a todo linked to the gateway ticket

2023-06-28 13:27 UTC, jmacmahonr3 commented on libs/interop/interop-core/src/main/kotlin/net/corda/interop/core/AliasIdentity.kt
> +    val hostingVnode : String
USe short hash here

2023-06-28 13:46 UTC, ac101m commented on components/interop/alias-info-cache-service/src/main/kotlin/net/corda/interop/aliasinfo/cache/AliasInfoCacheService.kt
> +    fun getAliasIdentities(shortHash: String): Map<String, InteropAliasIdentity>
The map serves as an index that removes the need to iterate over aliases. If duplication of data really is a concern, we should introduce a new cache entry datatype that doesn't contain the group UUID.

2023-06-28 13:58 UTC, ac101m commented on components/interop/alias-info-cache-service/src/main/kotlin/net/corda/interop/aliasinfo/cache/AliasInfoCacheService.kt
> +    fun removeAliasIdentity(shortHash: String, aliasIdentity: InteropAliasIdentity)
I disagree. The presence of the `previousValue` allows us to detect discrepancies between what's in the topic and what 's in the cache, but it doesn't allow us to detect them at the time those discrepancies occur. Only later. Because of this, I feel it's better to correct the discrepancy and print a warning than it is to fail outright (which will only create more discrepancies).

2023-06-28 14:05 UTC, ac101m commented on components/interop/alias-info-read-service-impl/src/main/kotlin/net/corda/interop/aliasinfo/read/impl/InteropAliasInfoReadServiceEventHandler.kt
> +        // re-register with saurabhs kafka topic
The read service is currently not used, not actually sure how we plan to use it in the future. @jmacmahonr3

2023-06-28 14:06 UTC, ac101m commented on components/interop/alias-info-write-service-impl/src/main/kotlin/net/corda/interop/aliasinfo/write/impl/InteropAliasIdentityProducer.kt
> +            InteropAliasInfoWriteServiceImpl.log.error("Interop alias identity publisher is null, not publishing.")
I blame intellij :wink: 
(fixed)

2023-06-28 14:09 UTC, ac101m commented on components/interop/interop-rest-service-impl/src/main/kotlin/net/corda/interop/rest/impl/v1/InteropRestResourceImpl.kt
> +        holdingidentityid: String?
Yeah, it doesn't make any sense to create an interop identity without an associated holding identity, probably shouldn't be nullable!

2023-06-28 14:17 UTC, szymonsztuka commented on components/interop/alias-info-write-service-impl/src/main/kotlin/net/corda/interop/aliasinfo/write/impl/InteropAliasInfoWriteServiceImpl.kt
> +            hostingVnode = "?"
This field is anyway redundant (Avro schema is wrong), but if we need to put a value it would be `holdingIdentityShortHash`.

2023-06-28 14:17 UTC, szymonsztuka commented on components/interop/interop-rest-service-impl/src/main/kotlin/net/corda/interop/rest/impl/v1/InteropRestResourceImpl.kt
> +//        ::interopManagementService
Remove

2023-06-28 14:17 UTC, szymonsztuka commented on components/interop/interop-rest-service-impl/src/main/kotlin/net/corda/interop/rest/impl/v1/InteropRestResourceImpl.kt
> +        for (groupToAliasMapping in groupToAliasMappings) {
Better use functional filter/map "stream" methods on groupToAliasMappings instead an explicit loop.

2023-06-28 14:17 UTC, szymonsztuka commented on components/interop/interop-rest-service-impl/src/main/kotlin/net/corda/interop/rest/impl/v1/InteropRestResourceImpl.kt
> +                CreateInteropIdentityRequest(
Is this existing convention, "Request" as we are building a response here, so a class named `GetInterOpIdentityResponse` would be more suitable. Also we do not create an identity in this method.

2023-06-28 20:23 UTC, ac101m commented on components/interop/interop-rest-service-impl/src/main/kotlin/net/corda/interop/rest/impl/v1/InteropRestResourceImpl.kt
> +        return listOf(UUID.randomUUID())
We'll need a verification step, but I think this work is slated for after this PR, as it can proceed independently of other work.

2023-06-29 14:49 UTC, ac101m commented on libs/interop/interop-core/src/main/kotlin/net/corda/interop/core/AliasIdentity.kt
> +    val hostingVnode : String
This class is actually unneeded. Removed.

2023-06-30 09:13 UTC, jmacmahonr3 commented on components/interop/alias-info-cache-service/src/main/kotlin/net/corda/interop/aliasinfo/cache/AliasInfoCacheService.kt
> +    fun getAliasIdentities(shortHash: String): Map<String, InteropAliasIdentity>
@ac101m Follow up with me on this one

2023-06-30 09:16 UTC, jmacmahonr3 commented on components/interop/alias-info-cache-service/src/main/kotlin/net/corda/interop/aliasinfo/cache/AliasInfoCacheService.kt
> +    fun removeAliasIdentity(shortHash: String, aliasIdentity: InteropAliasIdentity)
@szymonsztuka I'm marking this as resolved. I agree with Alex's point and we can update in next epic if needed.

2023-06-30 09:17 UTC, jmacmahonr3 commented on components/interop/alias-info-read-service-impl/src/main/kotlin/net/corda/interop/aliasinfo/read/impl/InteropAliasInfoReadServiceEventHandler.kt
> +        // re-register with saurabhs kafka topic
As mentioned previously this will be used for the reconciler from later in this milestone

2023-06-30 09:18 UTC, jmacmahonr3 commented on components/interop/interop-rest-service-impl/src/main/kotlin/net/corda/interop/rest/impl/v1/InteropRestResourceImpl.kt
> +        return ResponseEntity.ok("OK")
@julia-filipczak  Make sure to follow standard way of returning errors from corda rpc endpoints

2023-06-30 09:19 UTC, jmacmahonr3 commented on components/interop/interop-rest-service-impl/src/main/kotlin/net/corda/interop/rest/impl/v1/InteropRestResourceImpl.kt
> +        return listOf(UUID.randomUUID())
This will likely be folded in as part of the verification work when adding the db to the process

2023-06-30 09:19 UTC, jmacmahonr3 commented on components/interop/interop-rest-service-impl/src/main/kotlin/net/corda/interop/rest/impl/v1/InteropRestResourceImpl.kt
> +        return listOf(UUID.randomUUID())
@ac101m can you add a todo linked to a new ticket on data verification

2023-06-30 09:22 UTC, jmacmahonr3 commented on components/interop/interop-write-service-impl/src/main/kotlin/net/corda/interop/write/service/producer/HostedIdentityProducer.kt
> +        private val logger = LoggerFactory.getLogger(this::class.java.enclosingClass)
@jmacmahonr3 fix this please.

2023-06-30 09:24 UTC, jmacmahonr3 commented on components/interop/alias-info-write-service-impl/src/main/kotlin/net/corda/interop/aliasinfo/write/impl/InteropAliasInfoWriteServiceImpl.kt
> +            hostingVnode = "?"
@ac101m change name on hostingVnode. Field is not redundant as it refers to the VirtualNode that owns the Alias.

2023-06-30 09:49 UTC, ac101m commented on components/interop/interop-rest-service-impl/src/main/kotlin/net/corda/interop/rest/impl/v1/InteropRestResourceImpl.kt
> +    override fun getInterOpIdentities(holdingidentityshorthash: String): List<RestInteropIdentity> {
Rename `groupToAliasMappings` in this method to `groupToInteropIdentityMapings` or maybe just `interopIdentities`

2023-06-30 09:49 UTC, ac101m commented on components/interop/interop-rest-service-impl/src/main/kotlin/net/corda/interop/rest/impl/v1/InteropRestResourceImpl.kt
> +        logger.info("AliasIdentity created.")
`AliasIdentity` -> `InteropIdentity`

2023-06-30 14:37 UTC, ac101m reviewed
Only one comment, otherwise, I'm happy to merge all this!

2023-06-30 14:37 UTC, ac101m commented on processors/rest-processor/src/integrationTest/resources/swaggerBaseline.json
> +        "description" : "",
Missing a description here

2023-06-30 14:43 UTC, julia-filipczak commented on processors/rest-processor/src/integrationTest/resources/swaggerBaseline.json
> +        "description" : "",
I'm not entirely sure but it seems like this endpoint gets added by default whenever you create a RestResource as I didn't explicitly define it. Scrolling through the file it looks like every API has one and all of them have the description left as empty string so it might be fine as it is.

2023-06-30 17:02 UTC, yarivus requested changes

2023-06-30 17:02 UTC, yarivus commented on components/interop/interop-identity-read-service/src/main/kotlin/net/corda/interop/identity/read/InteropIdentityReadService.kt
> +interface InteropIdentityReadService : Lifecycle {
WiP ?
Howcome we don't have any apis here ?

2023-06-30 17:02 UTC, yarivus commented on components/interop/interop-identity-cache-service/src/main/kotlin/net/corda/interop/identity/cache/InteropIdentityCacheService.kt
> +    fun putInteropIdentities(shortHash: String, identity: InteropIdentity)
If you're putting a single identity - then this API should not be in plural (e.g. Identities)

2023-06-30 17:02 UTC, yarivus commented on components/interop/interop-identity-read-service-impl/src/main/kotlin/net/corda/interop/identity/read/impl/InteropIdentityReadServiceImpl.kt
> +) : InteropIdentityReadService {
where does this class implement a "read" of any kind ... I just see lifecycle stuff.

2023-06-30 17:02 UTC, yarivus commented on components/interop/interop-identity-write-service-impl/src/main/kotlin/net/corda/interop/identity/write/impl/HostedIdentityProducer.kt
> +    fun publishHostedInteropIdentity(identity: InteropIdentity) {
need some func comment ... where is this published to ?

2023-06-30 17:02 UTC, yarivus commented on components/interop/interop-identity-write-service-impl/src/main/kotlin/net/corda/interop/identity/write/impl/HostedIdentityProducer.kt
> +            listOf(DUMMY_CERTIFICATE),
should be marked as TODO ?

2023-06-30 17:02 UTC, yarivus commented on components/interop/interop-rest-service-impl/src/main/kotlin/net/corda/interop/rest/impl/v1/InteropRestResourceImpl.kt
> +                     … //all content from our hardcoded group policy file"
is this valid ?

2023-06-30 17:19 UTC, ac101m commented on components/interop/interop-identity-read-service/src/main/kotlin/net/corda/interop/identity/read/InteropIdentityReadService.kt
> +interface InteropIdentityReadService : Lifecycle {
There was a miscommunication and we ended up not needing this service for this epic, but we will need it for the reconcilers later. We left them in as it will save a little time later.

2023-06-30 17:26 UTC, ac101m commented on components/interop/interop-identity-cache-service/src/main/kotlin/net/corda/interop/identity/cache/InteropIdentityCacheService.kt
> +    fun putInteropIdentities(shortHash: String, identity: InteropIdentity)
You're right, renamed

2023-06-30 17:27 UTC, ac101m commented on components/interop/interop-identity-read-service-impl/src/main/kotlin/net/corda/interop/identity/read/impl/InteropIdentityReadServiceImpl.kt
> +) : InteropIdentityReadService {
As above, this is placeholder for now!

2023-06-30 17:28 UTC, ac101m commented on components/interop/interop-identity-write-service-impl/src/main/kotlin/net/corda/interop/identity/write/impl/HostedIdentityProducer.kt
> +    fun publishHostedInteropIdentity(identity: InteropIdentity) {
See comment at the top of the class!

2023-07-03 09:35 UTC, jmacmahonr3 commented on processors/rest-processor/src/integrationTest/resources/swaggerBaseline.json
> +        "description" : "",
Marking as resolved as no action needed.

2023-07-03 09:38 UTC, jmacmahonr3 commented on components/interop/interop-identity-read-service/src/main/kotlin/net/corda/interop/identity/read/InteropIdentityReadService.kt
> +interface InteropIdentityReadService : Lifecycle {
As Alex said, we are building upon this work later. Im going to mark this conversation as resolved as no action is needed.

2023-07-03 09:57 UTC, jmacmahonr3 commented on components/interop/interop-rest-service-impl/src/main/kotlin/net/corda/interop/rest/impl/v1/InteropRestResourceImpl.kt
> +                     … //all content from our hardcoded group policy file"
Just needs a todo linking it to a later ticket

2023-07-03 11:04 UTC, jmacmahonr3 approved these changes
LGTM

2023-07-04 12:01 UTC, yarivus approved these changes
LGTM

2023-07-04 12:01 UTC, yarivus commented on components/interop/interop-identity-read-service-impl/src/main/kotlin/net/corda/interop/identity/read/impl/InteropIdentityReadServiceImpl.kt
> +) : InteropIdentityReadService {
OK thanks

2023-07-04 12:27 UTC, merged