CORE-11037 Move DBConfig.kt contents out of api module to use sites
corda/corda-runtime-os pull request #4084
Opened 2023-06-14 17:26 UTC by kyriathar

2023-06-15 10:53 UTC, simon-johnson-r3 requested changes

2023-06-15 10:53 UTC, simon-johnson-r3 commented on components/db/db-connection-manager-impl/src/main/kotlin/net/corda/db/connection/manager/impl/DataSourceFactoryHelper.kt
> +    fun DataSourceFactory.createFromConfig(config: SmartConfig): CloseableDataSource {
I find it a bit unusual that this is in the internal object. Is there a reason for scoping them like this?

2023-06-15 10:53 UTC, simon-johnson-r3 commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeDbFactoryImpl.kt
> +internal fun createDbConfig(
I'd be tempted to make this a private function of `VirtualNodeDbFactoryImpl`
I assume it's internal for testing? Maybe see if you can derive the successful operation of this method from some other use of the class instance's public api? Chances are if you wrote this from scratch, you would have made it private and not bothered to unit test it, and we only got to this point because of emergent design.

2023-06-15 11:08 UTC, kyriathar commented on components/db/db-connection-manager-impl/src/main/kotlin/net/corda/db/connection/manager/impl/DataSourceFactoryHelper.kt
> +    fun DataSourceFactory.createFromConfig(config: SmartConfig): CloseableDataSource {
Good point, will pull it out of the object.

2023-06-15 14:28 UTC, kyriathar commented on components/db/db-connection-manager-impl/src/main/kotlin/net/corda/db/connection/manager/impl/DataSourceFactoryHelper.kt
> +    fun DataSourceFactory.createFromConfig(config: SmartConfig): CloseableDataSource {
Done

2023-06-15 14:29 UTC, kyriathar commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeDbFactoryImpl.kt
> +internal fun createDbConfig(
Made `createDbConfig` private and expanded existing test to assert more expected VNode datasource configurations.

2023-06-16 10:07 UTC, simon-johnson-r3 requested changes

2023-06-16 10:07 UTC, simon-johnson-r3 commented on components/virtual-node/virtual-node-write-service-impl/src/test/kotlin/net/corda/virtualnode/write/db/impl/VirtualNodeDbFactoryImplTest.kt
> +        // TODO A VNode DML max pool size datasource needs to be changed to 1. This will change in follow-up PR.
I don't think we should have TODO comments in the os code. When you change this the test would fail anyway, so it can't be forgotten.

2023-06-16 10:10 UTC, kyriathar commented on components/virtual-node/virtual-node-write-service-impl/src/test/kotlin/net/corda/virtualnode/write/db/impl/VirtualNodeDbFactoryImplTest.kt
> +        // TODO A VNode DML max pool size datasource needs to be changed to 1. This will change in follow-up PR.
Good point, removed

2023-06-16 11:13 UTC, simon-johnson-r3 approved these changes

2023-06-19 08:47 UTC, merged