ES-96/SBOM generation
corda/corda-runtime-os pull request #4089
Opened 2023-06-15 10:27 UTC by seanbrereton

Creating SBOM using the cyclonedx plugin.
Adding a task to zip the sboms into 1 folder and publish them.
Tested locally: https://gradle.dev.r3.com/s/mfpjlwzubrjww

2023-06-15 17:53 UTC, ronanbrowne requested changes

2023-06-15 17:53 UTC, ronanbrowne commented on build.gradle
> +            skipConfigs = ["integrationTestCompileOnlyDependenciesMetadata", "testCompileOnlyDependenciesMetadata", "compileOnlyDependenciesMetadata", "apiDependenciesMetadata"]
`skipConfigs `should not be needed if `includeConfigs` id used.

2023-06-15 17:53 UTC, ronanbrowne commented on build.gradle
> +            destination = file("build/reports/SBOM")
```suggestion
            destination = file("${buildDIr}/reports/SBOM")
```

2023-06-15 18:24 UTC, yarivus requested changes

2023-06-15 18:24 UTC, yarivus commented on build.gradle
> +            destination = file("build/reports/SBOM")
> 

Actually should be 
```suggestion
            destination = file("${buildDir}/reports/SBOM")
```

2023-06-15 18:24 UTC, yarivus commented on build.gradle
> +    String srcDestination = buildDir.toString() + "/archive/SBOM/"
`srcDestination` is confusing ... I propose `sourceDestFolder` or `sourceTargetFolder` (or Folder=>Path)

2023-06-19 12:22 UTC, yarivus submitted a review, later dismissed
LGTM

2023-06-20 08:55 UTC, ronanbrowne approved these changes
LGTM

2023-06-20 08:57 UTC, ronanbrowne requested changes
See comment

2023-06-20 08:57 UTC, ronanbrowne commented on settings.gradle
> +        id "org.cyclonedx.bom" version "1.7.4"
Sorry missed this. Can we externalize the property to gradle.properties?

2023-06-20 12:22 UTC, yarivus approved these changes
LGTM

2023-06-20 14:17 UTC, ronanbrowne approved these changes
LGTM

2023-06-20 14:19 UTC, merged