CORE-10444 : Changes to create interop API
corda/corda-runtime-os pull request #4099
Opened 2023-06-16 07:35 UTC by SaurabhR3

1. Created interop rest resource with two api 1) Get interop groups and 2) Create interop identity
2. Fixed issue with package info and bnd test
3. Fixed OpenAPICompatibilityTest
4. Updated SwaggerBaseline.json

I have kept some of the code commented as Julia needs this for API development

2023-06-16 10:15 UTC, julia-filipczak approved these changes

2023-06-16 11:05 UTC, jmacmahonr3 approved these changes
LGTM

2023-06-16 11:55 UTC, yarivus commented on processors/rest-processor/src/integrationTest/kotlin/net/corda/processors/rest/OpenApiCompatibilityTest.kt
> +            InteropRestResource::class.java,
for consistency add a comment too ;)

2023-06-16 11:57 UTC, yarivus requested changes

2023-06-16 11:57 UTC, yarivus commented on components/interop/interop-rest-service-impl/src/main/kotlin/net/corda/interop/rest/impl/v1/InteropRestResourceImpl.kt
> +//    override fun createInterOpIdentity(x500Name: String, groupId: UUID): ResponseEntity<AsyncResponse> {
remove commented out code

2023-06-19 09:24 UTC, yarivus requested changes

2023-06-19 09:24 UTC, yarivus commented on processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/DBProcessorImpl.kt
> +    // TODO: Temporarily added here, reevaluate this before merge
placeholder comment to check before merge

2023-06-19 09:24 UTC, yarivus commented on processors/db-processor/build.gradle
> +    // TODO: re-evaluate this before merge. Does this belong in the DB processor?
placeholder comment to check before merge

2023-06-19 09:24 UTC, yarivus commented on components/interop/alias-info-read-service/src/main/kotlin/net/corda/interop/aliasinfo/read/InteropAliasInfoReadService.kt
> +interface InteropAliasInfoReadService : Lifecycle {
I'm not sure why you need 2 packages for InteropAliasInfoReadService & InteropAliasInfoWriteService.
You can have a single package and define both classes source files there ... 
I think it's over-engineering

2023-06-19 09:24 UTC, yarivus commented on components/interop/alias-info-read-service/src/main/kotlin/net/corda/interop/aliasinfo/read/InteropAliasInfoReadService.kt
> +interface InteropAliasInfoReadService : Lifecycle {
Take note this separation adds double package-info.java, detekt, build.gradle files etc

2023-06-19 09:24 UTC, yarivus commented on components/interop/alias-info-read-service-impl/src/main/kotlin/net/corda/interop/aliasinfo/read/impl/InteropAliasInfoReadServiceImpl.kt
> +) : InteropAliasInfoReadService {
Maybe worth implementing InteropAliasInfoServiceImpl  which does most of the common code ...
Also, worth considering having a single InteropAliasInfoService interface

2023-06-19 09:24 UTC, yarivus commented on components/interop/alias-info-read-service-impl/src/main/kotlin/net/corda/interop/aliasinfo/read/impl/InteropAliasInfoReadServiceEventHandler.kt
> +class InteropAliasInfoReadServiceEventHandler(
consider code reuse between the InfoReadServiceEventHandler and InfoWriteServiceEventHandler

2023-06-20 09:12 UTC, SaurabhR3 commented
This PR was just to show Julia creation of REST API, closing this PR

2023-06-20 09:12 UTC, closed without merging