CORE-14685: Create a testing framework using JUnit and OSGi.
corda/corda-runtime-os pull request #4105
Opened 2023-06-16 14:53 UTC by chrisr3

2023-06-23 14:59 UTC, abellagonzalo approved these changes, later dismissed
LGTM

2023-06-26 11:42 UTC, dickon reviewed
Great stuff. I've got one batch of comments here, I want to take more time to play with the driver, but the key point is that I can live with what Chris has had to do to the crypto code for now, we can make the crypto service more amenable to this later.

I can also confirm I was able to run the new dirver based flow positive and negative tests myself in my IDE, they started up in 7s, and I can run the debugger on them, which is a good step forward giving the amout of functionaltiy they code.

2023-06-26 11:42 UTC, dickon commented on testing/driver/src/main/kotlin/net/corda/testing/driver/impl/DriverDSLImpl.kt
> +        private fun getPackageEntry(header: String?, packageName: String?): String? {
dead code

2023-06-26 11:42 UTC, dickon commented on testing/driver/src/main/java/net/corda/testing/driver/DriverDSL.java
> +public interface DriverDSL {
I'm not sure calling this a DSL is the clearest way to descirbe it; maybe 'DriverControl' would be clearer?

(I struggle a bit with the word driver here since it's a different sense of driver than I've usually used, but it is a sense of the word driver that JUnit uses so it is the right choice)

2023-06-26 11:42 UTC, dickon commented on testing/driver/driver-testing/src/integrationTest/kotlin/net/corda/testing/driver/tests/ConsensualLedgerTests.kt
> +class ConsensualLedgerTests {
This is a name clash with `applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/ledger/ConsensualLedgerTests.kt` ; how about `ConsensualLedgerDriverTests`?

2023-06-26 11:42 UTC, dickon commented on testing/driver/driver-testing/src/integrationTest/kotlin/net/corda/testing/driver/tests/ConsensualLedgerTests.kt
> +        driver.run { dsl ->
**Might** be worth using lambda receiver syntax in this situation?

Not that the reduced syntax required is necessarily always more readable than what you have here, but they do seem to be popular for DSLs.

2023-06-26 11:42 UTC, dickon commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/DriverCryptoServiceProviderImpl.kt
> +class DriverCryptoServiceProviderImpl @Activate constructor(
If we exported more pieces can this move to `driver-engine` ? I can live with it for now and take a ticket to move all mentions of driver out of the production crypto directories, and reduce duplication if possible, which would probably involve moving some code around as well as exporting more.

2023-06-26 11:45 UTC, chrisr3 commented on testing/driver/driver-testing/src/integrationTest/kotlin/net/corda/testing/driver/tests/ConsensualLedgerTests.kt
> +class ConsensualLedgerTests {
Actually, I would like to resolve this by throwing the smoke tests version away :no_mouth:.

2023-06-26 11:47 UTC, chrisr3 commented on testing/driver/src/main/java/net/corda/testing/driver/DriverDSL.java
> +public interface DriverDSL {
I've called it a DSL partly for "continuity" with Corda 4's driver, but also because it has elements like "startNode" and "runFlow". I expect to add other elements later.

2023-06-26 11:49 UTC, chrisr3 commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/DriverCryptoServiceProviderImpl.kt
> +class DriverCryptoServiceProviderImpl @Activate constructor(
Yes, I _definitely_ want this inside `driver-engine` to that it can use the driver's constants.

2023-06-26 11:52 UTC, chrisr3 commented on testing/driver/driver-testing/src/integrationTest/kotlin/net/corda/testing/driver/tests/ConsensualLedgerTests.kt
> +        driver.run { dsl ->
I need this to work in Java too. The `run` and `let` functions are declared in `AbstractDriver`:
```java
    public final <R> R let(@NotNull ThrowingFunction<DriverDSL, R> action) {
        checkDriver();
        return action.apply(driver);
    }

    public final void run(@NotNull ThrowingConsumer<DriverDSL> action) {
        checkDriver();
        action.accept(driver);
    }
```

2023-06-26 11:57 UTC, chrisr3 commented on testing/driver/src/main/kotlin/net/corda/testing/driver/impl/DriverDSLImpl.kt
> +        private fun getPackageEntry(header: String?, packageName: String?): String? {
:+1:

2023-06-26 17:47 UTC, yarivus reviewed
See comments.
Thanks for this work 🙏

2023-06-26 17:47 UTC, yarivus commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/DriverCryptoServiceProviderImpl.kt
> +    }
Couldn't this implementation create multiple instances if called in parallel by multiple callers w/o mutual exclusion ?
(all callers might still see wrappingRepository as null ... BTW where do you set it's value ?)

2023-06-26 17:47 UTC, yarivus commented on components/ledger/ledger-persistence/src/integrationTest/kotlin/net/corda/ledger/persistence/consensual/tests/ConsensualLedgerMessageProcessorTests.kt
> -        Assumptions.assumeFalse(DbUtils.isInMemory, "Skipping this test when run against in-memory DB.")
Is this removal (assumeFalse) still correct for runtime-os repo code w/o the driver or is it a necessity for the implementation of Driver ?

2023-06-26 17:47 UTC, yarivus commented on components/ledger/ledger-persistence/src/integrationTest/kotlin/net/corda/ledger/persistence/consensual/tests/ConsensualLedgerMessageProcessorTests.kt
> -        Assumptions.assumeFalse(DbUtils.isInMemory, "Skipping this test when run against in-memory DB.")
Same question applies to other locations in other files.

2023-06-26 17:47 UTC, yarivus commented on components/ledger/ledger-persistence/src/integrationTest/kotlin/net/corda/ledger/persistence/utxo/tests/datamodel/UtxoEntityFactory.kt
> -    fun createUtxoCpkEntity(
Why is this removed ? Is it not needed anymore (obsolete code) or is it moved elsewhere ?

2023-06-26 17:47 UTC, yarivus commented on libs/db/db-orm/src/main/kotlin/net/corda/orm/DatabaseType.kt
> +interface DatabaseTypeProvider {
Why do you still need the DB Type provider if you've implemented the query providers with concrete implementations for postgres & hsqldb ?
Having the type - means you'll at some point ask on the value in a switch/when statement which is counter-OOP

2023-06-26 17:47 UTC, yarivus commented on testing/driver/build.gradle
> +'''
```suggestion
        bnd '''\
                -conditionalpackage: aQute.*
                Import-Package:
        '''
```

2023-06-26 17:47 UTC, yarivus commented on testing/driver/src/main/java/net/corda/testing/driver/DriverDSL.java
> +public interface DriverDSL {
I also find it confusing the word "driver" and also DSL (is it really a Domain Specific Language ? or is this acronym something else ?)

2023-06-26 17:47 UTC, yarivus commented on testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/config/SmartConfigProvider.kt
> +        val config = ConfigFactory.empty()
R U planning to externalize these config params to the gradle properties ?

2023-06-26 17:47 UTC, yarivus commented on testing/driver/driver-testing/src/integrationTest/kotlin/net/corda/testing/driver/tests/ConsensualLedgerTests.kt
> +        logger.info("{}, {} and {} started successfully", alice.commonName, bob.commonName, charlie.commonName)
can switch everywhere to string interpolation ... please 🙏
```suggestion
        logger.info("${alice.commonName}, ${bob.commonName} and ${charlie.commonName} started successfully")
```

2023-06-26 17:47 UTC, yarivus commented on testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/crypto/MemoryWrappingRepository.kt
> +class MemoryWrappingRepository : WrappingRepository {
I'm not sure why you needed this wrapper as opposed to using ConcurrentHashMap<String, WrappingKeyInfo>() directly where needed ...
Isn't this over-engineering ?

2023-06-26 17:47 UTC, yarivus commented on testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/db/DbConnectionManagerImpl.kt
> +        private const val DRIVER_DB_NAME = "test-driver"
I propose renaming to "test-driver-db"

2023-06-26 17:47 UTC, yarivus commented on testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/db/DriverEntityManagerConfiguration.kt
> +class DriverEntityManagerConfiguration(
isn't this a data class ?

2023-06-26 17:47 UTC, yarivus commented on testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/db/InMemoryDatabaseTypeProvider.kt
> +class InMemoryDatabaseTypeProvider : DatabaseTypeProvider {
Having inheritance just for providing the DB type value as opposed to class (and object) implementation of the different DBs ... doesn't seem to fit well in terms of OOP

2023-06-26 17:47 UTC, yarivus commented on testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/flow/RunFlowImpl.kt
> +        }
(As non expert in Kotlin) - isn't there a built-in construct to make this code 1 liner ?
[ like C++ STL constructs and in other languages ]

2023-06-26 17:47 UTC, yarivus commented on testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/flow/RunFlowImpl.kt
> +            }
this code is very long and hard to read ... can you introduce some encapsulation using some private methods ?

2023-06-26 17:47 UTC, yarivus commented on testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/ledger/LedgerProcessor.kt
> +class LedgerProcessor @Activate constructor(
Is this a re-implementation of the Corda ledger (as Simulator did for several Corda constructs) ?
If so - can you explain the rationale ?

2023-06-26 17:47 UTC, yarivus commented on testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/sandbox/Constants.kt
> +const val WAIT_MILLIS = 100L
I think this needs a more specific name than `WAIT_MILLIS`, if you're using it for certain type of wait.
If you're using it absolutely across every single wait in the code then fine but I'd doubt it.
If you're using it once or twice in the code - I won't even bother w/ a constant in this case ...

2023-06-26 17:47 UTC, yarivus commented on testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/sandbox/CpiLoader.kt
> +    fun stop()
it's strange to have stop() but no start()

2023-06-26 17:47 UTC, yarivus commented on testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/sandbox/CpiInfoServiceImpl.kt
> +    override val isRunning: Boolean
Where is this turned off or on ?

2023-06-26 17:47 UTC, yarivus commented on testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/sandbox/EmbeddedNodeServiceImpl.kt
> +        // The names of the bundles to place as public bundles in the sandbox service's platform sandbox.
is this comment reflecting some future TODO that still needs to be done ... or the intention is something else ?

2023-06-26 17:47 UTC, yarivus commented on testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/sandbox/EmbeddedNodeServiceImpl.kt
> +    override fun setMembershipGroup(network: Map<MemberX500Name, PublicKey>) {
It feels like the membership group setting is out of place ... why is this function not in some MembershipGroupServiceImpl or something like that ?

2023-06-26 17:47 UTC, yarivus commented on testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/sandbox/GroupPolicyProviderImpl.kt
> +    override fun registerListener(name: String, callback: (HoldingIdentity, GroupPolicy) -> Unit) {
maybe worth adding a comment on why this is blank impl ... or ... what's the future intention ...

2023-06-26 17:47 UTC, yarivus commented on testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/sandbox/MembershipGroupReaderProviderImpl.kt
> +class MembershipGroupReaderProviderImpl @Activate constructor(
maybe this class should also implement `setMembershipGroup` from the EmbeddedNodeService ?

2023-06-26 17:47 UTC, yarivus commented on testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/sandbox/ServiceFactoryImpl.kt
> +        }
I'm not 100% sure, but seems like you could change the loop and check `while (remainingMillis <= 0)` from the get-go instead of having the break condition inside.

2023-06-26 17:47 UTC, yarivus commented on testing/driver/driver-testing/src/integrationTest/kotlin/net/corda/testing/driver/tests/FlowDriverTest.kt
> +    private val alice = MemberX500Name.parse("CN=Alice, OU=Testing, O=R3, L=London, C=GB")
worth considering having those X500 strings as shorthand constants ... as you're using the same ones multiple times.

2023-06-26 17:47 UTC, yarivus commented on testing/driver/src/main/java/net/corda/testing/driver/AbstractDriver.java
> +    AbstractDriver(@NotNull String schemeName, @NotNull Set<MemberX500Name> members) {
why do you need both @NotNull and requireNonNull ?

2023-06-26 17:47 UTC, yarivus commented on testing/driver/src/main/java/net/corda/testing/driver/Framework.java
> +    ) throws InterruptedException, TimeoutException;
2 ₵ : I'd unify both APIs to a single one (and if the filter is null it acts like the 2nd)
Less complexity of code at the end of day

2023-06-26 17:47 UTC, yarivus commented on testing/driver/src/main/kotlin/net/corda/testing/driver/impl/DriverInternalDSL.kt
> +interface DriverInternalDSL : DriverDSL {
why is this interface needed in addition to DriverDSL ?

2023-06-26 17:47 UTC, yarivus commented on testing/driver/src/main/kotlin/net/corda/testing/driver/impl/FlowRunner.kt
> +class FlowRunner(private val dsl: DriverInternalDSL) {
This looks like "over-classes" ...
Can't we implement `runFlow()` in the DriverDSL (or the internal) ?

2023-06-26 17:47 UTC, yarivus commented on testing/driver/src/main/kotlin/net/corda/testing/driver/impl/DriverDSLImpl.kt
> +                && symbolicName !in forbiddenSymbolicNames
A question to the previous exclude lists too and these symbolic names ...
How often would the maintainer have to modify these lists and what knowledge is expected of the him/her to be able to make the right choices for the values in those lists ?

2023-06-26 19:15 UTC, chrisr3 commented on components/ledger/ledger-persistence/src/integrationTest/kotlin/net/corda/ledger/persistence/utxo/tests/datamodel/UtxoEntityFactory.kt
> -    fun createUtxoCpkEntity(
It is dead code.

2023-06-26 19:16 UTC, chrisr3 commented on testing/driver/build.gradle
> +'''
No thanks.

2023-06-26 19:20 UTC, chrisr3 commented on components/ledger/ledger-persistence/src/integrationTest/kotlin/net/corda/ledger/persistence/consensual/tests/ConsensualLedgerMessageProcessorTests.kt
> -        Assumptions.assumeFalse(DbUtils.isInMemory, "Skipping this test when run against in-memory DB.")
These tests can now execute locally using an embedded HSQLDB database, and so there is no longer any need to skip them.

2023-06-26 19:22 UTC, chrisr3 commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/DriverCryptoServiceProviderImpl.kt
> +    }
The crypto code is currently being refactored, and so this component is only temporary.

2023-06-26 19:26 UTC, chrisr3 commented on libs/db/db-orm/src/main/kotlin/net/corda/orm/DatabaseType.kt
> +interface DatabaseTypeProvider {
The correct concrete implementation to use is selected by which `DatbaseTypeProvider` component instance is created.

> Having the type - means you'll at some point ask on the value in a switch/when statement which is counter-OOP

There is no such switch/when statement in this code.

2023-06-26 19:28 UTC, chrisr3 commented on testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/config/SmartConfigProvider.kt
> +        val config = ConfigFactory.empty()
Potentially some, although most of them are likely to be completely uninteresting.

2023-06-26 19:28 UTC, chrisr3 commented on testing/driver/driver-testing/src/integrationTest/kotlin/net/corda/testing/driver/tests/ConsensualLedgerTests.kt
> +        logger.info("{}, {} and {} started successfully", alice.commonName, bob.commonName, charlie.commonName)
No thanks.

2023-06-26 19:29 UTC, chrisr3 commented on testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/crypto/MemoryWrappingRepository.kt
> +class MemoryWrappingRepository : WrappingRepository {
This code only exists to make the current crypto code work.

2023-06-26 19:31 UTC, chrisr3 commented on testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/db/DriverEntityManagerConfiguration.kt
> +class DriverEntityManagerConfiguration(
This is an internal class, and we are not remotely interested in either its `equals()` or `hashCode()` functions. Consequently there is absolutely _no point_ making it a `data` class.

2023-06-26 19:33 UTC, chrisr3 commented on testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/db/InMemoryDatabaseTypeProvider.kt
> +class InMemoryDatabaseTypeProvider : DatabaseTypeProvider {
This is an OSGi component, and `DatabaseTypeProvider` is its OSGi service type.

2023-06-26 19:33 UTC, chrisr3 commented on testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/flow/RunFlowImpl.kt
> +        }
Not to my knowledge, no. If there had been then I would have used it already.

2023-06-26 19:36 UTC, chrisr3 commented on testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/flow/RunFlowImpl.kt
> +            }
This is only the first iteration. Its most important goal atm is to _work_ rather than win a beauty pageant.

2023-06-26 19:40 UTC, chrisr3 commented on testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/ledger/LedgerProcessor.kt
> +class LedgerProcessor @Activate constructor(
`LedgerProcessor` exists to handle a flow's ledger-related events, should the flow have any. In exactly the same way that `CryptoProcessor` exists to handle a flow's crypto-related events.

I didn't reference the Simulator code when writing this.

2023-06-26 19:41 UTC, chrisr3 commented on testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/sandbox/Constants.kt
> +const val WAIT_MILLIS = 100L
This constant is internal to the `driver-engine` code, and exists to avoid the use of "magic numbers".

2023-06-26 19:44 UTC, chrisr3 commented on testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/sandbox/CpiInfoServiceImpl.kt
> +    override val isRunning: Boolean
This component has no choice but to implement Corda's `Lifecycle` interface, of which `isRunning` is a member. It therefore returns `true` "just for fun" because it is utterly irrelevant to the driver's operation in every conceivable way.

2023-06-26 19:46 UTC, chrisr3 commented on testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/sandbox/EmbeddedNodeServiceImpl.kt
> +        // The names of the bundles to place as public bundles in the sandbox service's platform sandbox.
The comment is accurately describing what these names are. There is no "TODO".

2023-06-26 19:51 UTC, chrisr3 commented on testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/sandbox/EmbeddedNodeServiceImpl.kt
> +    override fun setMembershipGroup(network: Map<MemberX500Name, PublicKey>) {
The driver's embedded OSGi framework exposes the `EmbeddedNodeService` to JUnit so that JUnit can configure the embedded OSGi framework. The `setMembershipGroup` function is therefore _exactly_ where it needs to be.

2023-06-26 19:52 UTC, chrisr3 commented on testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/sandbox/GroupPolicyProviderImpl.kt
> +    override fun registerListener(name: String, callback: (HoldingIdentity, GroupPolicy) -> Unit) {
I need a `GroupPolicyProvider` component, but not necessarily all of its functions. The `registerListener` function is likely to be one of those whose implementation is of no interest whatsoever.

2023-06-26 19:54 UTC, chrisr3 commented on testing/driver/src/main/java/net/corda/testing/driver/AbstractDriver.java
> +    AbstractDriver(@NotNull String schemeName, @NotNull Set<MemberX500Name> members) {
Because `@NotNull` is just an annotation. Actually forbidding `null` values requires `requireNotNull`.

2023-06-26 19:55 UTC, chrisr3 commented on testing/driver/src/main/kotlin/net/corda/testing/driver/impl/DriverInternalDSL.kt
> +interface DriverInternalDSL : DriverDSL {
Because it contains an extra function which is "internal".

2023-06-26 19:56 UTC, chrisr3 commented on testing/driver/src/main/kotlin/net/corda/testing/driver/impl/FlowRunner.kt
> +class FlowRunner(private val dsl: DriverInternalDSL) {
I _deliberately_ moved the `FlowRunnerImpl` code _out_ of `DriverDSLImpl` because `DriverDSLImpl` was becoming too large.

2023-06-26 19:58 UTC, chrisr3 commented on testing/driver/src/main/kotlin/net/corda/testing/driver/impl/DriverDSLImpl.kt
> +                && symbolicName !in forbiddenSymbolicNames
Maintainers are not expected to need to modify these list very often, if at all.

2023-06-26 20:08 UTC, chrisr3 commented on testing/driver/src/main/java/net/corda/testing/driver/Framework.java
> +    ) throws InterruptedException, TimeoutException;
The `getService(Class, Duration)` variant just invoked the other variant with `filter=null` anyway. However, I don't invoke either functions very often anyway.

2023-06-26 20:15 UTC, chrisr3 commented on testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/db/DbConnectionManagerImpl.kt
> +        private const val DRIVER_DB_NAME = "test-driver"
For the life of me, I cannot remember _ever_ seeing this value being logged anywhere anyway.

2023-06-26 20:19 UTC, chrisr3 commented on testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/sandbox/CpiLoader.kt
> +    fun stop()
It doesn't appear to be used, and so is likely just inherited from the `:testing:sandboxes` code.

2023-06-26 20:19 UTC, yarivus commented on testing/driver/build.gradle
> +'''
Don't you agree it's more readable when indented ?
Or, is it problematic to bnd ?

2023-06-26 20:20 UTC, chrisr3 commented on testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/sandbox/MembershipGroupReaderProviderImpl.kt
> +class MembershipGroupReaderProviderImpl @Activate constructor(
Derp, _why?!?!_

2023-06-26 20:21 UTC, yarivus commented on components/ledger/ledger-persistence/src/integrationTest/kotlin/net/corda/ledger/persistence/consensual/tests/ConsensualLedgerMessageProcessorTests.kt
> -        Assumptions.assumeFalse(DbUtils.isInMemory, "Skipping this test when run against in-memory DB.")
Thanks for clarifying 🙂

2023-06-26 20:23 UTC, chrisr3 commented on testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/sandbox/ServiceFactoryImpl.kt
> +        }
This loop always executes `getServiceReferences()` immediately, and only worries about waiting afterwards. This is the behaviour I want.

2023-06-26 20:25 UTC, yarivus commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/DriverCryptoServiceProviderImpl.kt
> +    }
Thanks for clarifying.
So core platform folks will make this class redundant?
Maybe best to add a comment reflecting this and your comment here.
Thanks 
@dickon for awareness

2023-06-26 20:25 UTC, chrisr3 commented on testing/driver/driver-testing/src/integrationTest/kotlin/net/corda/testing/driver/tests/FlowDriverTest.kt
> +    private val alice = MemberX500Name.parse("CN=Alice, OU=Testing, O=R3, L=London, C=GB")
The individual test classes don't care what X500 names other classes are using. That they happen to be the same is just a coincidence.

2023-06-26 20:32 UTC, chrisr3 commented on testing/driver/build.gradle
> +'''
I do not agree that it's more readable. It's certainly not consistent with the rest of the code-base.

2023-06-26 20:44 UTC, yarivus commented on testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/config/SmartConfigProvider.kt
> +        val config = ConfigFactory.empty()
Thanks 👍

2023-06-26 20:46 UTC, chrisr3 commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/DriverCryptoServiceProviderImpl.kt
> +    }
See the comment at the top of this PR:
> Note that the crypto code is being refactored atm. My hope is that the SoftCryptoService can be moved out of :components and into :libs, at which point I will be able to fold DriverCryptoServiceProviderImpl into :testing:driver:driver-engine as well.

2023-06-26 20:49 UTC, yarivus commented on testing/driver/driver-testing/src/integrationTest/kotlin/net/corda/testing/driver/tests/ConsensualLedgerTests.kt
> +        logger.info("{}, {} and {} started successfully", alice.commonName, bob.commonName, charlie.commonName)
But please explain why not ?
What's the downside ?

2023-06-26 20:56 UTC, yarivus commented on testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/crypto/MemoryWrappingRepository.kt
> +class MemoryWrappingRepository : WrappingRepository {
What is missing in using directly the ConcurrentHashMap that impedes the crypto code from working ?

2023-06-26 20:57 UTC, yarivus commented on testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/db/DriverEntityManagerConfiguration.kt
> +class DriverEntityManagerConfiguration(
Got it. 🙏

2023-06-26 21:02 UTC, yarivus commented on testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/flow/RunFlowImpl.kt
> +            }
I see your point, but my comment wasn't for beauty but rather for easier handoff to other coders ...
As discussed in the last few months, we would like the DevEx to adopt the code quickly and be able to maintain and enhance ...

2023-06-27 10:26 UTC, yarivus commented on testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/sandbox/EmbeddedNodeServiceImpl.kt
> +    override fun setMembershipGroup(network: Map<MemberX500Name, PublicKey>) {
Thanks for clarifying

2023-06-27 10:27 UTC, yarivus commented on testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/sandbox/MembershipGroupReaderProviderImpl.kt
> +class MembershipGroupReaderProviderImpl @Activate constructor(
You've explained in another comment - so disregard.

2023-06-27 10:28 UTC, yarivus commented on testing/driver/src/main/java/net/corda/testing/driver/AbstractDriver.java
> +    AbstractDriver(@NotNull String schemeName, @NotNull Set<MemberX500Name> members) {
Thanks for explaining

2023-06-27 10:29 UTC, yarivus commented on testing/driver/src/main/kotlin/net/corda/testing/driver/impl/DriverInternalDSL.kt
> +interface DriverInternalDSL : DriverDSL {
But the fact it may be exposed doesn't mean that JUnit will leverage/use it ... right ?
If so, I thought it's better to simplify by reducing over-classes

2023-06-27 10:30 UTC, yarivus commented on testing/driver/src/main/kotlin/net/corda/testing/driver/impl/FlowRunner.kt
> +class FlowRunner(private val dsl: DriverInternalDSL) {
Makes sense

2023-06-27 11:20 UTC, yarivus commented on testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/db/DbConnectionManagerImpl.kt
> +        private const val DRIVER_DB_NAME = "test-driver"
so no problem renaming right ?
Just makes more sense when reading the code

2023-06-27 11:22 UTC, chrisr3 commented on testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/flow/RunFlowImpl.kt
> +            }
This is the initial version only, and I still have to implement UTXO.

2023-06-27 11:25 UTC, yarivus commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/DriverCryptoServiceProviderImpl.kt
> +    }
thanks

2023-06-27 11:26 UTC, yarivus commented on testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/flow/RunFlowImpl.kt
> +            }
OK - so hoping to see some encapsulation later

2023-06-27 12:01 UTC, dickon commented on testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/flow/RunFlowImpl.kt
> +            }
I don't think this code is hard to read, and it is clean and elegant compared to some of our heavily encapsulated code. If soem logic is  inherelty long and runs to hundreds of lines simply splitting it up into half a dozen small pieces doesn't always help.

2023-06-27 12:08 UTC, dickon commented on testing/driver/driver-testing/src/integrationTest/kotlin/net/corda/testing/driver/tests/ConsensualLedgerTests.kt
> +        logger.info("{}, {} and {} started successfully", alice.commonName, bob.commonName, charlie.commonName)
I've had this conversation before with Chris before and I don't have the link he shared to hand, but https://stackoverflow.com/questions/10555409/logger-slf4j-advantages-of-formatting-with-instead-of-string-concatenation explains the issue. We do care about performance of Corda and @yarivus's version will use more resources when info level logging is disabled than what Chris wrote. That's why much of the Corda code uses the function argument (lambda) versions of logging methods, where the function is not called (I hope) and the string not constructed if the log level is disabled. The objection to that is it's not standard in the Java community, whereas what Chris wrote is probably the most common form. 

I personally feel the objection to the lambda form  not being standard and portable to Java is a minor concern given we chose Kotlin at all, so we're already moving away from the most standard choice, i.e. probably still plain Java 8 despite all the verbosity that would by Kotlin.

The interpolated form is more readable once you get used to it, which matters to me, but not enough to ignore the performance aspects.

2023-06-27 12:15 UTC, dickon commented on testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/crypto/MemoryWrappingRepository.kt
> +class MemoryWrappingRepository : WrappingRepository {
Constructing a SoftCryptoService requires an implementation of `WrappingRepository` - see `components/crypto/crypto-softhsm-impl/src/test/kotlin/net/corda/crypto/softhsm/impl/infra/MakeCryptoService.kt`. Chris is finding a way to instantiate the crypto code without all the multi database complexity we have in the full production scenarios. What's interesting is that we're going with `ConcurrentHashMap` here rather than running the production `WrappingRepositoryImpl` against  `HSQLDB`. However, as Chris noted Crypto is under active development, the changes I'm working on now will make that much easier to do, and we can probably ditch this class after some further development of the crypto processor code to be more mechanically sympathetic to the driver approach.

2023-06-27 12:22 UTC, dickon commented on libs/db/db-orm/src/main/kotlin/net/corda/orm/DatabaseType.kt
> +interface DatabaseTypeProvider {
Agree with Chris, in other words it is necessary to control OSGi dependency injection, there's no inherent reason that this will violate polymorphism of database type and the theoretical risks if they occur should be caught in code review.

2023-06-27 12:24 UTC, dickon commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/DriverCryptoServiceProviderImpl.kt
> +class DriverCryptoServiceProviderImpl @Activate constructor(
Okay then I'll ask to let me priortise that change once this goes in and my current crypto feature; the PR is big enough and it'd be a merge nightmare if we start moving code around in this branch.

2023-06-27 16:07 UTC, simon-johnson-r3 requested changes
I've added comments up to now, but this PR is enormous and complex. I will continue to review it.

2023-06-27 16:07 UTC, simon-johnson-r3 commented on components/virtual-node/cpk-read-service-impl/src/main/kotlin/net/corda/cpk/read/impl/services/CpkChunksKafkaReader.kt
> +        cpkChunksFileManager.assembleCpk(cpkChecksum, chunks)?.also { cpkPath ->
I don't quite understand this change.
`also` is typically used when you have an object and you want to invoke some additional methods on it, but most importantly it returns the object so you can do, e.g.
`return myObject.also { log.info(myobject) }.also { something else }`

When you want to run code on the return of a method, `let` is the convention. Whilst you could argue because you don't care about the return value either will do, semantically this is a misuse of `also`.

2023-06-27 16:07 UTC, simon-johnson-r3 commented on libs/db/db-orm/src/main/kotlin/net/corda/orm/DatabaseType.kt
> +interface DatabaseTypeProvider {
> The correct concrete implementation to use is selected by which DatbaseTypeProvider component instance is created.

Could you point me at that, I don't seem to be able to find it?

All I can see here is classes filtering on a specific type, then to use the instance to write back to the log something they already knew. I'm probably missing something.

2023-06-27 16:07 UTC, simon-johnson-r3 commented on testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/db/DbConnectionManagerImpl.kt
> +    private val dataSource = DriverDataSource(InMemoryDataSourceFactory(dataSourceFactory).create(DRIVER_DB_NAME).also { db ->
As far as I can tell here you are applying the vnode-vault schema to the in memory database, is that correct? This is the schema which is used when vnodes are created by Corda on the fly. The bootstrapped database is populated with the config, crypto and rbac schemas.

2023-06-27 16:07 UTC, simon-johnson-r3 commented on testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/flow/RunFlowImpl.kt
> +                    while (responseEvents.isNotEmpty()) {
What's the plan to maintain this parallel logic when we add new features to Corda? Do we just have to be aware of it and try and adapt it appropriately?

2023-06-27 16:07 UTC, simon-johnson-r3 commented on testing/driver/src/main/java/net/corda/testing/driver/DriverDSL.java
> +public interface DriverDSL {
I would also agree. Many of us never worked on Corda 4 and wouldn't understand the term in that context, and I assume that applies to most customers looking through this open source code too.

More importantly Kotlin has a whole `DSL` builder pattern and even a `@DslMarker` annotation to facilitate that. I think this will be confused with that. And in the wider use of the term, it's nothing like a `DSL` as most would understand it. Same goes for 'driver', it's reusing a term that means something totally different already.

2023-06-27 16:07 UTC, simon-johnson-r3 commented on testing/driver/src/main/java/net/corda/testing/driver/AbstractDriver.java
> +
Is this written in Java because we intend to expose it to customers or for some other reason? If that is the case, it would effectively become part of a public api, with everything that goes along with management of that.

2023-06-27 16:07 UTC, simon-johnson-r3 commented on testing/driver/src/main/java/net/corda/testing/driver/AbstractDriver.java
> +
These look like Kotlin scope functions at the point of use, but act differently. For example reading this in Kotlin code `driver.let { dsl ->` is really quite confusing.

2023-06-27 16:07 UTC, simon-johnson-r3 commented on testing/driver/src/main/java/net/corda/testing/driver/Service.java
> +    default Service<T> andAlso(@NotNull ThrowingConsumer<T> action) throws Exception {
this isn't used anywhere, can it be tested?

2023-06-27 16:21 UTC, chrisr3 commented on components/virtual-node/cpk-read-service-impl/src/main/kotlin/net/corda/cpk/read/impl/services/CpkChunksKafkaReader.kt
> +        cpkChunksFileManager.assembleCpk(cpkChecksum, chunks)?.also { cpkPath ->
> When you want to run code on the return of a method,

But we _don't_ want to run code on the return of this `let` method because its result is `Unit`, i.e. `void`.
```kotlin
cpkChunksFileManager.assembleCpk(cpkChecksum, chunks)?.let { cpkPath ->
    // etc
    onCpkAssembled(cpk.metadata.fileChecksum, cpk)
} ?: logger.warn("CPK assemble has failed for: $cpkChecksum")
```
What we _actually_ want to do is execute `onCpkAssembled()` if `cpkPath` is not null, and otherwise log a message.

2023-06-27 16:29 UTC, chrisr3 commented on testing/driver/src/main/java/net/corda/testing/driver/AbstractDriver.java
> +
They have the same semantics as the Kotlin equivalents, but are implemented in Java because the driver needs to be usable from Java.

2023-06-27 16:34 UTC, chrisr3 commented on testing/driver/src/main/java/net/corda/testing/driver/AbstractDriver.java
> +
It's written in Java because I don't expect every single CorDapp developer to write their CorDapps in Kotlin.

2023-06-27 16:37 UTC, chrisr3 commented on testing/driver/src/main/java/net/corda/testing/driver/Service.java
> +    default Service<T> andAlso(@NotNull ThrowingConsumer<T> action) throws Exception {
DriverDSLImpl.kt#290
```kotlin
private fun loadCordapps(memberNames: Set<MemberX500Name>): List<VirtualNodeInfo> {
    val vNodes = mutableListOf<VirtualNodeInfo>()

    getService(EmbeddedNodeService::class.java, null, Duration.ZERO).andAlso { ens ->
```

FlowRunner.kt#19
```kotlin
return try {
    dsl.getFramework(memberX500Name).getService(RunFlow::class.java, null, timeout).andThen { runner ->
        runner.runFlow(virtualNodeInfo.toAvro(), flowClass.name, flowArgMapper.get())
```

2023-06-27 16:42 UTC, chrisr3 commented on testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/flow/RunFlowImpl.kt
> +                    while (responseEvents.isNotEmpty()) {
It will likely need _some_ maintenance going forwards. However, it has proved to be surprisingly resilient to date.

I have created some integration tests that replicate some of the smoke tests already, and should be able to replicate the rest of the smoke tests as the driver becomes more complete.

2023-06-27 16:47 UTC, chrisr3 commented on testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/db/DbConnectionManagerImpl.kt
> +    private val dataSource = DriverDataSource(InMemoryDataSourceFactory(dataSourceFactory).create(DRIVER_DB_NAME).also { db ->
As of right now, I have only needed the `vnode-vault` schema because the ledger components require it. The driver doesn't use Kafka or HTTP, or have any users who need "permissions", and so I am hoping not to need any of the others.

2023-06-27 16:52 UTC, chrisr3 commented on libs/db/db-orm/src/main/kotlin/net/corda/orm/DatabaseType.kt
> +interface DatabaseTypeProvider {
The "default" `DatabaseTypeProvider` component is called `DefaultDatabaseTypeProvider` (funnily enough), and lives in `net.corda.orm.impl`. It configures Corda to use Postgres.

The `TestDatabaseTypeProviderFactory` component shuts the default component down and creates another one dynamically for either HSQLDB or Postgres, depending on the result of the existing `DbUtils.isInMemory` property.

2023-06-27 17:04 UTC, chrisr3 commented on testing/driver/src/main/java/net/corda/testing/driver/DriverDSL.java
> +public interface DriverDSL {
"driver" is a _far_ nicer term than "Subset of Corda inside an embedded OSGi container".

Short and snappy, and without any scary "OSGi" references.

2023-06-27 19:26 UTC, yarivus commented on testing/driver/driver-testing/src/integrationTest/kotlin/net/corda/testing/driver/tests/ConsensualLedgerTests.kt
> +        logger.info("{}, {} and {} started successfully", alice.commonName, bob.commonName, charlie.commonName)
Thanks for the detailed explanation @dickon 👍 
BTW - this is pretty unfortunate ... other languages have optimizations around this

2023-06-27 19:29 UTC, yarivus commented on testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/crypto/MemoryWrappingRepository.kt
> +class MemoryWrappingRepository : WrappingRepository {
Thanks again for the detailed info @dickon 🙂

2023-06-27 19:39 UTC, yarivus commented on testing/driver/src/main/java/net/corda/testing/driver/DriverDSL.java
> +public interface DriverDSL {
@simon-johnson-r3 has raised several comments that make sense.
@chrisr3 I urge you to reconsider, and try to think another name than DSL (especially)

2023-06-27 19:43 UTC, yarivus reviewed
checkpointing review.
I've resolved some of the replied comments. Thanks 🙏
I see that there are some unresolved comments (in discussion)

2023-06-28 07:39 UTC, dickon commented on testing/driver/driver-testing/src/integrationTest/kotlin/net/corda/testing/driver/tests/ConsensualLedgerTests.kt
> +        driver.run { dsl ->
I'm not clear what reaasons people might have for using the driver from Java.

2023-06-28 07:51 UTC, simon-johnson-r3 commented on components/virtual-node/cpk-read-service-impl/src/main/kotlin/net/corda/cpk/read/impl/services/CpkChunksKafkaReader.kt
> +        cpkChunksFileManager.assembleCpk(cpkChecksum, chunks)?.also { cpkPath ->
I don't understand your explanation. The `?:` applies always to the `?` the choice of scope function is not relevant to that. Kotlin developers will read the `?:` as relating to the return of `assembleCpk` in all cases, it has nothing to do with the contents of the scope function or the choice of that.

2023-06-28 07:57 UTC, simon-johnson-r3 commented on testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/db/DbConnectionManagerImpl.kt
> +    private val dataSource = DriverDataSource(InMemoryDataSourceFactory(dataSourceFactory).create(DRIVER_DB_NAME).also { db ->
The `vnode-vault` schema is usually written when Corda creates a vnode inside a schema named by Corda. Where are you writing it to here? I don't understand how the ledger is associating what you write here with a particular vnode, do you know?

2023-06-28 08:01 UTC, simon-johnson-r3 commented on testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/flow/RunFlowImpl.kt
> +                    while (responseEvents.isNotEmpty()) {
Ok, so I read that as smoke tests will likely pick up deviations. Sounds reasonable.

2023-06-28 08:03 UTC, simon-johnson-r3 commented on testing/driver/src/main/java/net/corda/testing/driver/AbstractDriver.java
> +
Ok, that's what I was getting at. So then we are expecting customers to use this and it has to be api managed in the same way any other api does. It would not be acceptable to break this api in a later release of Corda or customers would be forced to rewrite their tests. Do we have plans to this end?

2023-06-28 08:10 UTC, simon-johnson-r3 commented on testing/driver/src/main/java/net/corda/testing/driver/AbstractDriver.java
> +
In Kotlin `driver.let { dsl ->` the `dsl` would demonstrate referencial equality to `driver`. I assume that is not the case here? 

Perhaps more importantly `driver.let {` would be a strange thing to do in the first place, it doesn't offer you anything. That's just running the code in the scope function in all cases with `driver` renamed to `it`.

Typically `let` is used on a function which returns a value to avoid creating a temp variable, or where an expected null can be handled with a `driver?.let {`.

2023-06-28 08:12 UTC, simon-johnson-r3 commented on testing/driver/src/main/java/net/corda/testing/driver/Service.java
> +    default Service<T> andAlso(@NotNull ThrowingConsumer<T> action) throws Exception {
Yes, fair enough. I did a search prior to expanding that file which GitHub collapsed by default.

2023-06-28 08:29 UTC, chrisr3 commented on testing/driver/src/main/java/net/corda/testing/driver/AbstractDriver.java
> +
The point of `let` is to execute a lambda that transform `T` into `R`, _and then returns the value of `R`._ 

For example:
```kotlin
val aliceResult = driver.let { dsl ->
    dsl.runFlow(mandelbrot.single { it.holdingIdentity.x500Name == alice }, CalculateBlockFlow::class.java) {
        jsonMapper.writeValueAsString(request)
    }
} ?: fail("aliceResult must not be null")
```
In this case, `aliceResult` is assigned to the return value of `dsl.runFlow()`.

`AbstractDriver.let` is so named to mirror the definition and behaviour of Kotlin's `let` function.

Furthermore, I cannot rename it to `run` or `apply` because these already exist as Kotlin functions with different semantics.

2023-06-28 08:33 UTC, chrisr3 commented on testing/driver/src/main/java/net/corda/testing/driver/AbstractDriver.java
> +
This API is customer-facing, and so we _are_ going to have to manage this API, yes. AFAIK no plans to do this yet exist.

2023-06-28 08:34 UTC, chrisr3 commented on testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/db/DbConnectionManagerImpl.kt
> +    private val dataSource = DriverDataSource(InMemoryDataSourceFactory(dataSourceFactory).create(DRIVER_DB_NAME).also { db ->
I don't write to `vnode-vault` schema directly, but Corda's `ledger` modules do and I use Corda's `ledger` modules.

2023-06-28 10:00 UTC, chrisr3 commented on components/virtual-node/cpk-read-service-impl/src/main/kotlin/net/corda/cpk/read/impl/services/CpkChunksKafkaReader.kt
> +        cpkChunksFileManager.assembleCpk(cpkChecksum, chunks)?.also { cpkPath ->
With `let`:
```kotlin
val obj1: Path? = assembleCpk()
val obj2: Unit? = assembleCpk()?.let { onCpkAssembled(it) }
val obj3: Unit = assembleCpk()?.let { onCpkAssembled(it) } ?: throw Exception()
```
whereas with `also`:
```kotlin
val obj1: Path? = assembleCpk()
val obj2: Path? = assembleCpk()?.also { onCpkAssembled(it) }
val obj3: Path = assembleCpk()?.also { onCpkAssembled(it) } ?: throw Exception()
```
The `let` function is for returning the result of the lambda to the caller, except that `onCpkAssembled()` doesn't have any result to return. Hence switch to using `also`, which _doesn't_ expect its lambda to return anything.

2023-06-28 11:29 UTC, chrisr3 commented on testing/driver/src/main/java/net/corda/testing/driver/DriverDSL.java
> +public interface DriverDSL {
I _actually like_ the name "driver".

2023-06-28 11:39 UTC, chrisr3 commented on testing/driver/driver-testing/src/integrationTest/kotlin/net/corda/testing/driver/tests/ConsensualLedgerTests.kt
> +        driver.run { dsl ->
People who write CorDapps in Java are likely to want to write their tests in Java too.

2023-06-29 08:48 UTC, simon-johnson-r3 commented on testing/driver/src/main/java/net/corda/testing/driver/DriverDSL.java
> +public interface DriverDSL {
The main objections are that these words already mean something different in the software industry, and that they are well used terms and well understood in those contexts already.

We're trying avoid confusion for future maintainers and customers who look at this code. They will come to it with the well used definitions of 'driver' and 'dsl' in their minds already, and wonder why this code doesn't look like a driver or dsl to them. This is easily alleviated with a quick rename in the IDE now, rather than forever explaining that this isn't a driver or dsl as they understand them, but reuse of those terms for something else.

2023-06-29 08:58 UTC, simon-johnson-r3 commented on components/virtual-node/cpk-read-service-impl/src/main/kotlin/net/corda/cpk/read/impl/services/CpkChunksKafkaReader.kt
> +        cpkChunksFileManager.assembleCpk(cpkChecksum, chunks)?.also { cpkPath ->
That is a technical description of the return type of the scope functions, yes, but it's not a description of "what it's for". The semantics of these functions is defined here: https://kotlinlang.org/docs/scope-functions.html

Notably:
`Executing a lambda on non-null objects: let`
`Additional effects: also`

Here you are quite clearly wanting the former not the latter. The return type is incidental because you are not using it, so introducing `obj1` etc. into this example is changing the use case of the code from the code in the PR.

I would fully agree if you were capturing the return value here you'd write some different code, but that has nothing to do with this code I'm making a comment on.

2023-06-29 09:07 UTC, simon-johnson-r3 commented on testing/driver/src/main/java/net/corda/testing/driver/AbstractDriver.java
> +
See comment above, that is not the point of `let`. The literal function definition is not a description of the defined semantic meaning of `let`. Besides, in Kotlin the object reference passed to `let` is the object you call `let` on, so here you don't even have the same literal definition. See https://kotlinlang.org/docs/scope-functions.html#function-selection

2023-06-29 09:37 UTC, driessamyn commented on testing/driver/src/main/java/net/corda/testing/driver/AbstractDriver.java
> +
Agree with the above. This will need to be broken up so that the API exists in the API repo so we can guarantee no breaking changes between minor versions.

I appreciate this is non-trivial work, and it's also not so important while we only ship "Betas" of this feature, so I would suggest that work is captured in a JIRA that has to be completed before this gets merged into the main branch. 
CC @abellagonzalo

2023-06-29 09:56 UTC, simon-johnson-r3 commented on libs/db/db-orm/src/main/kotlin/net/corda/orm/DatabaseType.kt
> +interface DatabaseTypeProvider {
My question really is why do we need to do all that? `databaseTypeProvider.databaseType` only seems to be used in logs. But this is a large change and perhaps I've missed something.

It seems `TestDatabaseTypeProviderFactory` does the actual swapping out of the database components based on `DbUtils.isInMemory`, isn't that enough?

2023-06-29 10:25 UTC, abellagonzalo commented
@dickon @driessamyn @yarivus @simon-johnson-r3 @corda/flow-worker 
Hi all, as agreed yesterday we are going to work on a Feature Branch from now on. Can you all please approve the PR so we can move forward?
<img width="683" alt="image" src="https://github.com/corda/corda-runtime-os/assets/3661560/7071bf59-d8f1-4302-8b1f-0277e6d42a17">

2023-06-29 10:25 UTC, abellagonzalo approved these changes

2023-06-29 10:42 UTC, chrisr3 commented on libs/db/db-orm/src/main/kotlin/net/corda/orm/DatabaseType.kt
> +interface DatabaseTypeProvider {
- Corda has a "default" `DatabaseTypeProvider` component that selects Postgres.
- The driver deactivates this "default" and replaces it with its own `DatabaseTypeProvider` component that selects HSQLDB.
- `TestDatabaseTypeProviderFactory` belong to the `db-testkit` and so only exists for running the tests. It also deactivates the "default" component, and dynamically creates a `DatabaseTypeProvider` component based on the result of `DbUtils.isInMemory`.

The point is that the OSGi framework ultimately contains only _one_ `DatabaseTypeProvider`: whether this is for HSQLDB or Postgres determines which of the `UtxoQueryProvider` and `ConsensualQueryProvider` components can be activated.

The driver does not use `db-testkit` by default, although you could probably include it manually if you wanted to use Postgres instead of HSQLDB.

2023-06-29 11:04 UTC, simon-johnson-r3 commented on libs/db/db-orm/src/main/kotlin/net/corda/orm/DatabaseType.kt
> +interface DatabaseTypeProvider {
Thanks for that explanation. It's was this bit `determines which of the UtxoQueryProvider and ConsensualQueryProvider components can be activated.` I was looking for.

So is it that OSGi uses this:
```
    (target = HSQLDB_TYPE_FILTER)
    databaseTypeProvider: DatabaseTypeProvider
```
to determine which of those classes to use as the implementation for UtxoQueryProvider?

It's saying, "if my databaseTypeProvider has `property = [ HSQLDB_TYPE_FILTER ]` then use me" (and likewise in the other class)?

2023-06-29 11:12 UTC, chrisr3 commented on libs/db/db-orm/src/main/kotlin/net/corda/orm/DatabaseType.kt
> +interface DatabaseTypeProvider {
`target` is an LDAP filter that selects a candidate whose properties match. So we have a `database.type` property whose value is either `hsqldb` or `postgres`, and a filter which selects a component accordingly:
```kotlin
@Component
class HsqldbConsensualQueryProvider @Activate constructor(
    @Reference(target = "(database.type=hsqldb)")
    databaseTypeProvider: DatabaseTypeProvider
) : ConsensualQueryProvider {
    // etc
}
```

2023-06-29 16:05 UTC, chrisr3 commented
I need this PR merged into the feature branch.

2023-06-29 18:08 UTC, yarivus commented on testing/driver/driver-testing/src/integrationTest/kotlin/net/corda/testing/driver/tests/ConsensualLedgerTests.kt
> +        driver.run { dsl ->
I agree w/ @chrisr3 on this one

2023-06-29 20:18 UTC, chrisr3 commented on testing/driver/src/main/java/net/corda/testing/driver/AbstractDriver.java
> +
I read that as a helpful guide to help you choose, not an exhaustive hard-and-fast decree that _must_ be obeyed, and especially since it goes on to say:
> The use cases of different scope functions overlap, **so you can choose which functions to use based on the specific conventions used in your project or team**.

At the end of the day, I am looking at the generated code and using `also` generates better code.

2023-06-29 20:22 UTC, chrisr3 commented on components/virtual-node/cpk-read-service-impl/src/main/kotlin/net/corda/cpk/read/impl/services/CpkChunksKafkaReader.kt
> +        cpkChunksFileManager.assembleCpk(cpkChecksum, chunks)?.also { cpkPath ->
That article also says:
> The use cases of different scope functions overlap, so you can choose which functions to use based on the specific conventions used in your project or team.

and so it is clearly not even trying to be definitive here. Kotlin is a programming language and so at the end of the day, the technical description _is_ "what it's for".

2023-06-30 07:55 UTC, driessamyn commented
> @dickon @driessamyn @yarivus @simon-johnson-r3 @corda/flow-worker Hi all, as agreed yesterday we are going to work on a Feature Branch from now on. Can you all please approve the PR so we can move forward? 

See [branching strategy guidelines](https://r3-cev.atlassian.net/wiki/spaces/CB/pages/4450451570/Corda+5+Branching+Strategy#Feature-Branches), specifically:

* The PRs need to be reviewed, and should be squashed onto the feature branch
* The usual PR gates apply
* Remember that all commits to the feature branch will be merged onto the release branch in the end

This means reviews are still needed and valuable.

However, some of the things raised are not trivial change and should probably be addressed separately (e.g. moving API into API repo, decision on naming).
I suggest these things are captured in a JIRAs that will need to be resolved in subsequent PRs, but before this gets merged into main.

2023-06-30 09:24 UTC, yarivus commented
> > @dickon @driessamyn @yarivus @simon-johnson-r3 @corda/flow-worker Hi all, as agreed yesterday we are going to work on a Feature Branch from now on. Can you all please approve the PR so we can move forward?
> 
> See [branching strategy guidelines](https://r3-cev.atlassian.net/wiki/spaces/CB/pages/4450451570/Corda+5+Branching+Strategy#Feature-Branches), specifically:
> 
> * The PRs need to be reviewed, and should be squashed onto the feature branch
> * The usual PR gates apply
> * Remember that all commits to the feature branch will be merged onto the release branch in the end
> 
> This means reviews are still needed and valuable.
> 
> However, some of the things raised are not trivial change and should probably be addressed separately (e.g. moving API into API repo, decision on naming). I suggest these things are captured in a JIRAs that will need to be resolved in subsequent PRs, but before this gets merged into main.

@chrisr3 - let's follow this approach and create JIRA issues for DevEx board for the comments which cannot be trivially changed in this PR.
This will enable to move fwd.
Thanks 🙏

2023-06-30 09:36 UTC, yarivus commented on testing/driver/src/main/java/net/corda/testing/driver/DriverDSL.java
> +public interface DriverDSL {
Folks, I propose we move fwd.
Let's take this rename discussion into the design doc ... currently, we can "live" with the names as they are and move fwd to enable the PR merge.

2023-06-30 09:45 UTC, yarivus commented on libs/db/db-orm/src/main/kotlin/net/corda/orm/DatabaseType.kt
> +interface DatabaseTypeProvider {
As @chrisr3 explained in detail my original question and the follow-up questions by @simon-johnson-r3 I'm resolving this one.

2023-06-30 11:24 UTC, yarivus approved these changes
LGTM - few comments pending from others

2023-06-30 12:59 UTC, thiagoviana approved these changes
LGTM - going to a feature branch as agreed.

2023-06-30 18:08 UTC, merged