CORE-13565 Add extra datasource properties to db bootstrap config
corda/corda-runtime-os pull request #4112
Opened 2023-06-20 06:37 UTC by kyriathar

2023-06-20 15:51 UTC, davidcurrie approved these changes, later dismissed
LGTM

2023-06-26 07:57 UTC, davidcurrie commented on charts/corda-lib/templates/_bootstrap.tpl
> +             {{- " '--keepalive-time'" -}}, {{ (index .Values.bootstrap.db (.dbName | default .name)).dbConnectionPool.keepaliveTimeSeconds | quote }}, {{- " " -}}
I don't think you need to explicitly add the space on the end of each argument given that you're including a space on the start of the next one.

2023-06-26 14:28 UTC, davidcurrie approved these changes, later dismissed
👍

2023-06-27 15:16 UTC, davidcurrie submitted a review, later dismissed
🚀

2023-06-27 16:20 UTC, simon-johnson-r3 commented on charts/corda/values.schema.json
> +                                            "title": "minimum JDBC connection pool size for crypto DB"
I think we should describe what `null` means

2023-06-27 16:26 UTC, simon-johnson-r3 requested changes

2023-06-27 16:26 UTC, simon-johnson-r3 commented on charts/corda/values.schema.json
> +                                            "title": "minimum JDBC connection pool size for crypto DB"
I think we should describe what `null` means
(and all occurrences below)

2023-06-27 16:26 UTC, simon-johnson-r3 commented on charts/corda/values.yaml
> +        # -- minimum JDBC connection pool size for crypto DB
probably add a note about null here too, it's the first place most end users will encounter it

2023-06-28 09:29 UTC, kyriathar commented on charts/corda/values.schema.json
> +                                            "title": "minimum JDBC connection pool size for crypto DB"
Good point. Addressed.

2023-06-28 09:37 UTC, kyriathar commented on charts/corda/values.yaml
> +        # -- minimum JDBC connection pool size for crypto DB
Done

2023-06-28 12:36 UTC, simon-johnson-r3 approved these changes

2023-06-28 14:07 UTC, davidcurrie approved these changes
LGTM

2023-06-28 14:10 UTC, merged