CORE-14513 Skip Message Bus for Same Topic/Key
corda/corda-runtime-os pull request #4199
Opened 2023-06-30 14:36 UTC by Cap-j

Change for POC branch to make code mergeable

2023-06-30 15:12 UTC, yarivus commented on tmp/ca/ca/.ca/keystore.jks
R U sure the tmp/ca/ca/.ca/ folder should not be gitignored ?

2023-06-30 15:48 UTC, Cap-j commented on tmp/ca/ca/.ca/keystore.jks
Unintentional commit - deleted now, thank you!

2023-07-01 12:45 UTC, yarivus reviewed
some comments

2023-07-01 12:45 UTC, yarivus commented on libs/messaging/messaging-impl/src/main/kotlin/net/corda/messaging/subscription/StateAndEventSubscriptionImpl.kt
> +                    newEventsToProcess.clear()
I'd check if it's more performant to declare the `newEventsToProcess` in the loop iteration rather than clearing it every iteration

2023-07-01 12:45 UTC, yarivus commented on libs/messaging/messaging-impl/src/main/kotlin/net/corda/messaging/subscription/StateAndEventSubscriptionImpl.kt
> +    private fun toCordaConsumerRecord(sourceRecord: CordaConsumerRecord<K, E>, newEvent : Record<K, E>) =
this private func has no benefit, better calling the `CordaConsumerRecord` c'tor where needed.

2023-07-01 12:45 UTC, yarivus commented on libs/messaging/messaging-impl/src/main/kotlin/net/corda/messaging/subscription/StateAndEventSubscriptionImpl.kt
> +        recordsToProcess: MutableList<Record<K, E>>,
I'd put the `recordsToProcess` as the return type, this will make the code simpler here and in the call-site.

2023-07-03 14:14 UTC, Cap-j commented on libs/messaging/messaging-impl/src/main/kotlin/net/corda/messaging/subscription/StateAndEventSubscriptionImpl.kt
> +                    newEventsToProcess.clear()
Refactoring code to change the return type as per the last comment resolved this issue too.

2023-07-03 14:14 UTC, Cap-j commented on libs/messaging/messaging-impl/src/main/kotlin/net/corda/messaging/subscription/StateAndEventSubscriptionImpl.kt
> +    private fun toCordaConsumerRecord(sourceRecord: CordaConsumerRecord<K, E>, newEvent : Record<K, E>) =
Addressed, thank you!

2023-07-03 14:14 UTC, Cap-j commented on libs/messaging/messaging-impl/src/main/kotlin/net/corda/messaging/subscription/StateAndEventSubscriptionImpl.kt
> +        recordsToProcess: MutableList<Record<K, E>>,
Refactored to change return type

2023-07-03 14:20 UTC, pmck91 commented on libs/messaging/messaging-impl/src/main/kotlin/net/corda/messaging/subscription/StateAndEventSubscriptionImpl.kt
> +                        val ret = CordaConsumerRecord(it.topic, event.partition, event.offset, it.key, it.value, event.timestamp, event.headers)
we can remove the val ret part here, and ret from the next line. It was added to aid in debug logging

2023-07-04 10:02 UTC, ben-millar commented
This new logic probably needs tests in `StateAndEventSubscriptionImplTest.kt` and `StateAndEventSubscriptionIntegrationTest.kt`

2023-07-04 11:45 UTC, yarivus approved these changes
LGTM

2023-07-04 11:52 UTC, pmck91 approved these changes

2023-07-04 12:14 UTC, driessamyn requested changes
This is a message pattern change, so should be considered medium to high risk.

Given the linked JIRA mentions a POC, do we have evidence that this is a good change and makes a measurable difference?
Can the attached JIRA be updated with relevant information?

FYI @JamesHR3

2023-07-04 15:11 UTC, Cap-j commented
@driessamyn For POC test results, see [this Confluence page](https://r3-cev.atlassian.net/wiki/spaces/CB/pages/4522147874/Test+16+-+Skip+P2P+layer+when+parties+are+on+the+same+cluster)

2023-07-04 16:12 UTC, thiagoviana commented
> @driessamyn For POC test results, see [this Confluence page](https://r3-cev.atlassian.net/wiki/spaces/CB/pages/4522147874/Test+16+-+Skip+P2P+layer+when+parties+are+on+the+same+cluster)

@driessamyn [This](https://r3-cev.atlassian.net/wiki/spaces/CB/pages/4529389617/Test+18+-+Allow+Subscription+Processors+to+feed+subset+of+events+back+into+itself+without+going+to+bus+first+MSK) is what you're looking for.

@Cap-j the previously shared confluent page is not related to this PR.

2023-07-06 14:09 UTC, owenstanford commented on libs/messaging/messaging-impl/src/main/kotlin/net/corda/messaging/subscription/StateAndEventSubscriptionImpl.kt
> +                    eventsToProcess.addAll(newEventsToProcess.map {CordaConsumerRecord(
~~Does this work with the commit offsets?~~
~~The commit offsets works out the max offset for the batch of input events, if the initial event was part of a batch and the synthetic event was processed by itself, would it not be possible for it to commit an earlier offset (albeit only relevant in a rebalance or failure scenario).~~
~~For Example:~~
~~batch 1:~~
~~- event 1 offset 0 - outputs wakeup event (that's fast tracked and added to the next batch)~~
~~- event 2 offset 1~~
~~- event 3 offset 2~~
~~batch 2: (nothing received from kafka)~~
~~- synthetic wakeup event offset 0 (copied from the source event)~~
Ignore, I've looked at the code again, I see you are processing the wakeup event as part of the same initial batch

2023-07-28 13:38 UTC, closed without merging