CORE-13570 Default datasource properties for vnode connections
corda/corda-runtime-os pull request #4218
Opened 2023-07-05 06:33 UTC by kyriathar

2023-07-07 10:39 UTC, davidcurrie requested changes
Reviewed for chart changes...

2023-07-07 10:39 UTC, davidcurrie commented on charts/corda/values.schema.json
> +                            "title": "TODO configuration",
Resolve `TODO` here and elsewhere

2023-07-07 10:39 UTC, davidcurrie commented on charts/corda-lib/templates/_bootstrap.tpl
>          - name: 11-create-db-users-and-grant
the sequence numbers should follow on...
```suggestion
        - name: 15-create-db-users-and-grant
```

2023-07-07 10:39 UTC, davidcurrie commented on charts/corda/values.yaml
> +    virtualNodesDdlPoolConfig:
On naming: everything in here is "config". I'd also be tempted to structure it to be more in line with the current `crypto` and `rbac` stanzas. So, without getting too carried away with layers of nesting, maybe something like:
```
virtualNode:
  ddlConnectionPool:
     ...
  dmlConnectionPool:
     ...
  ```
  
  Also, a whole load more `TODO` in here that need resolving.

2023-07-07 12:25 UTC, kyriathar commented on charts/corda/values.yaml
> +    virtualNodesDdlPoolConfig:
Good catch this one. I pushed a renaming change, but kept structure same, to (**I think**) be a bit more consistent with how other configurations (e.g. `rbac` and `crypto`) map to a dedicated DB row each (i.e. a row per db connection).

2023-07-07 13:29 UTC, dickon commented on charts/corda/values.yaml
> +    virtualNodesDdlPoolConfig:
I'm not a huge fan of stating DDL and DML here; not everyone is going to know those acronyms, and what's in this stanza is not the DDL or DML itself, but rather connection details for setting up the definitions in the database, or doing CRUD oeprations.

2023-07-07 13:51 UTC, simon-johnson-r3 requested changes

2023-07-07 13:51 UTC, simon-johnson-r3 commented on charts/corda/values.yaml
> +    # Virtual Nodes DDL connections configuration for Corda managed Virtual Nodes DBs
I'm not sure the term "DBs" here makes sense. At this level we only support using the cluster db as a vnode db, and that would seem to be aligned with the fact this is under a `db:` parent.

Perhaps consider:
Virtual Nodes DDL connection configuration for each Corda managed Virtual Node schema in the db

And the same for DML

2023-07-07 13:51 UTC, simon-johnson-r3 commented on charts/corda/values.schema.json
> +                            "title": "Virtual Nodes DDL connections configuration for Corda managed Virtual Nodes DBs",
See comment on values.yaml for proposed slight rewording

2023-07-07 13:51 UTC, simon-johnson-r3 commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeDbFactoryImpl.kt
> +
This function should be surplus to requirements after this change, so it probably needs a little attention.

Before this change:
- All db connections are represented by `DataSource`s
- All `DataSource`s are created via configs
- Configs come from db_connections rows, or in the case of the cluster/config, from startup params (because it has to)
- Vnodes are a special case. We don't have anywhere to grab a config from, so we create a config at runtime from hard coded values, using this function `createDbConfig`.

After this change:
- Vnodes get config from rows in the db_connections table, alleviating the need to create a config at runtime.

As discussed there is an issue of the JDBL url and authentication. So I would expect a helper method to inject those into the config we already have. That roughly tallies with the parameter I see passed here. So I think they key is to change this function to reflect that only.

2023-07-07 13:51 UTC, simon-johnson-r3 commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterFactory.kt
> +        // TODO The following configs and `virtualNodeDbFactory` do not depend on dynamic config so they could be extracted out to not be
This may be true, but it wasn't affected by this PR. I would delete this comment and raise a ticket on that. But I'm not even entirely sure we need to raise that, it's an optimisation we might not benefit from.

2023-07-07 13:51 UTC, simon-johnson-r3 commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterFactory.kt
> +            requireNotNull(dbConnectionManager.getDataSourceConfig(VIRTUAL_NODES_DDL_POOL_CONFIG, DbPrivilege.DDL)) {
`require...` functions throw `IllegalArgumentException` which would be a bit odd in the middle of a function where no arguments are being interrogated. I think you might want `check...` equivalent which will throw `IllegalStateException` and is designed for more runtime state like things.

2023-07-07 14:21 UTC, kyriathar commented on charts/corda-lib/templates/_bootstrap.tpl
>          - name: 11-create-db-users-and-grant
Done

2023-07-07 14:27 UTC, dickon commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterFactory.kt
> +            requireNotNull(dbConnectionManager.getDataSourceConfig(VIRTUAL_NODES_DDL_POOL_CONFIG, DbPrivilege.DDL)) {
Nice tip, @simon-johnson-r3 , I've probably been overusin `require`.

2023-07-07 14:33 UTC, kyriathar commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterFactory.kt
> +        // TODO The following configs and `virtualNodeDbFactory` do not depend on dynamic config so they could be extracted out to not be
Sure, it shouldn't make much difference I agree, only re-creating it while we couldn't. Removing comment as it's minor.

2023-07-07 14:50 UTC, kyriathar commented on charts/corda/values.schema.json
> +                            "title": "TODO configuration",
I believe resolved them

2023-07-07 15:31 UTC, dickon commented on components/db/db-connection-manager/src/main/kotlin/net/corda/db/connection/manager/DbConnectionsRepository.kt
> +    fun getDataSourceConfig(name: String, privilege: DbPrivilege): Config?
Needs kdoc. But really I don't know what you're trying to achieve here, and I'm not 100% sure about building out ahead of implementing the methods but having both getClusterDataSource and getDataSourceConfig confuses me a bit. I can live with this for now though.

2023-07-07 15:32 UTC, dickon reviewed
It seems a shame to have to list out these config parameters in so many places, there's some inconclusive chat on slack about this.

2023-07-07 16:08 UTC, driessamyn commented on components/db/db-connection-manager-impl/src/main/kotlin/net/corda/db/connection/manager/impl/LateInitDbConnectionOps.kt
> +    override fun getDataSourceConfig(name: String, privilege: DbPrivilege): Config? =
I think this needs to be `SmartConfig` (same everywhere else) as it can contain "secrets" (e.g. password).

If we want to delay turning into a config object (I can see we turn it into `SmartConfig` later on), then we should just treat this as a String I think.

2023-07-10 12:56 UTC, kyriathar commented on components/db/db-connection-manager-impl/src/main/kotlin/net/corda/db/connection/manager/impl/LateInitDbConnectionOps.kt
> +    override fun getDataSourceConfig(name: String, privilege: DbPrivilege): Config? =
I believe at this point we are only reading the vnodes datasource pool configuration from the DB so no secrets at this point (?) and then we are turning it into a complete vnode connection configuration which contains a secret which is the password of the DB user.

2023-07-10 13:02 UTC, kyriathar commented on components/db/db-connection-manager/src/main/kotlin/net/corda/db/connection/manager/DbConnectionsRepository.kt
> +    fun getDataSourceConfig(name: String, privilege: DbPrivilege): Config?
It's a good point actually. Here we are trying to handle this "special" case of vnodes datasource configuration, out of which we only need the pool configuration. 

Whereas in all other cases configurations in `db_connection` table maps to a `Datasource` (per record/ row).

2023-07-10 13:02 UTC, kyriathar commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterFactory.kt
> +            requireNotNull(dbConnectionManager.getDataSourceConfig(VIRTUAL_NODES_DDL_POOL_CONFIG, DbPrivilege.DDL)) {
Done

2023-07-10 13:03 UTC, kyriathar commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterFactory.kt
> +        // TODO The following configs and `virtualNodeDbFactory` do not depend on dynamic config so they could be extracted out to not be
Removed

2023-07-10 13:18 UTC, kyriathar commented on charts/corda/values.yaml
> +    # Virtual Nodes DDL connections configuration for Corda managed Virtual Nodes DBs
Good point.

Updated as suggested.

2023-07-10 13:18 UTC, kyriathar commented on charts/corda/values.schema.json
> +                            "title": "Virtual Nodes DDL connections configuration for Corda managed Virtual Nodes DBs",
Done

2023-07-10 13:22 UTC, kyriathar commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeDbFactoryImpl.kt
> +
Good catch! Yes this function is currently only being used to create Vnode datasource config.

Updated its name to `createVirtualNodeDbConfig`.

2023-07-10 13:24 UTC, driessamyn commented on components/db/db-connection-manager-impl/src/main/kotlin/net/corda/db/connection/manager/impl/LateInitDbConnectionOps.kt
> +    override fun getDataSourceConfig(name: String, privilege: DbPrivilege): Config? =
We're explicitly stating in the documentation that any config object can contain a secret. I.e. we don't define what is secret and what isn't, that is down to the operator.
Whether it's likely one of those things will be a secret is a different question. But what do we gain here by turning it into `Config`?

2023-07-10 13:28 UTC, kyriathar commented on components/db/db-connection-manager-impl/src/main/kotlin/net/corda/db/connection/manager/impl/LateInitDbConnectionOps.kt
> +    override fun getDataSourceConfig(name: String, privilege: DbPrivilege): Config? =
I believe only making the API a bit more explicit/ clear but not much more than that.

2023-07-10 13:54 UTC, simon-johnson-r3 commented on components/db/db-connection-manager-impl/src/main/kotlin/net/corda/db/connection/manager/impl/LateInitDbConnectionOps.kt
> +    override fun getDataSourceConfig(name: String, privilege: DbPrivilege): Config? =
I think @driessamyn has a point, and I think this relates to my comment below too. And also the comment @dickon makes actually.

The intent of this change is to make vnode connection configs more like other connection configs. 

I think `VirtualNodeDbFactoryImpl` instead of having a `createVirtualNodeDbConfig` function, should perhaps have access to `dbConnectionManager`, from which it extracts a data source directly, just like everything else. The only difference here is you need to inject (replace) the jdbc url and authentication.

You have 2 options for that
1) Pass those into a new api `getDataSource(jdbcOverrides...)`
2) Get the smart config and write over them in `VirtualNodeDbFactoryImpl`

I'm not sure which is preferable, perhaps play around with it and see what drops out? I'm leaving towards (2) because it keeps the details of the differences away from `dbConnectionManager`.

2023-07-10 14:00 UTC, simon-johnson-r3 commented on components/db/db-connection-manager-impl/src/main/kotlin/net/corda/db/connection/manager/impl/LateInitDbConnectionOps.kt
> +    override fun getDataSourceConfig(name: String, privilege: DbPrivilege): Config? =
Actually that wouldn't work for (2) because this is a get method, you'd potentially be sharing a datasource and overwriting values in it which wouldn't work. Might have to do (1).

2023-07-10 14:08 UTC, simon-johnson-r3 commented on components/db/db-connection-manager-impl/src/main/kotlin/net/corda/db/connection/manager/impl/LateInitDbConnectionOps.kt
> +    override fun getDataSourceConfig(name: String, privilege: DbPrivilege): Config? =
Don't think I was thinking option (2) through actually...

2023-07-11 05:49 UTC, kyriathar commented on components/db/db-connection-manager-impl/src/main/kotlin/net/corda/db/connection/manager/impl/LateInitDbConnectionOps.kt
> +    override fun getDataSourceConfig(name: String, privilege: DbPrivilege): Config? =
I see what you mean, good point.

I think the issue with that is that we need to get a a datasource config to pass it into `DbConnectionImpl` (it needs a `SmartConfig` and not a `DataSource` at this point).

2023-07-25 10:12 UTC, kyriathar commented
For this work, we are going to go with the approach in [#1186](https://github.com/corda/corda-api/pull/1186) and [#4349](https://github.com/corda/corda-runtime-os/pull/4349).

2023-07-25 10:12 UTC, closed without merging