CORE-13098 - Merge feature branch back into release branch
corda/corda-runtime-os pull request #4219
Opened 2023-07-05 10:30 UTC by nikinagy

Resolved conflicts:
StartRegistrationHandlerTest.kt

Patch file:
[merge.patch](https://github.com/corda/corda-runtime-os/files/11956853/merge.patch)

2023-07-06 08:52 UTC, dimosr submitted a review, later dismissed
LGTM

2023-07-11 09:30 UTC, seanbrereton approved these changes
LGTM (gradle only)

2023-07-11 09:34 UTC, seanbrereton requested changes
Still using alpha version in gradle.properties

2023-07-11 09:35 UTC, kyriathar commented on components/crypto/crypto-component-core-impl/src/main/kotlin/net/corda/crypto/component/impl/RetryUtils.kt
> +            Thread.sleep((1000 * 1.0.pow(i+1)).roundToLong())
Why have we added this extra sleep here? Aren't we already doing it at line 12?

2023-07-11 09:38 UTC, nikinagy commented on components/crypto/crypto-component-core-impl/src/main/kotlin/net/corda/crypto/component/impl/RetryUtils.kt
> +            Thread.sleep((1000 * 1.0.pow(i+1)).roundToLong())
Good catch! addressed in [07729e3](https://github.com/corda/corda-runtime-os/pull/4219/commits/07729e3932a573dfc00129549e4455f097cacbf3)

2023-07-11 09:40 UTC, nikinagy commented
> Still using alpha version in gradle.properties

@seanbrereton I think we need to use alpha until the Api PR is not merged (and usually that's when people switch to beta+ version), without that this PR would fail on the build runs. But correct me if I am wrong.

2023-07-11 13:09 UTC, vkolomeyko commented on build.gradle
> +            outputName = "${project.name}-corda-runtime-os-sbom"
Nit: Do we need this change?

2023-07-11 13:10 UTC, josephzunigadaly commented on applications/workers/release/rest-worker/src/e2eTest/kotlin/net/corda/applications/workers/rest/MultiClusterDynamicNetworkTest.kt
> +    @Tag("Unstable")
What does this mean? Are we expecting this test to fail?

2023-07-11 13:10 UTC, vkolomeyko commented on gradle.properties
> +cordaApiVersion=5.1.0.6-alpha-1688549679598
We need to merge `corda-api` work first and build `5.1.0.5-beta` version.

2023-07-11 13:27 UTC, nikinagy commented on build.gradle
> +            outputName = "${project.name}-corda-runtime-os-sbom"
IntelliJ removed this during the merge, do we really need this tab here?

2023-07-11 13:28 UTC, nikinagy commented on applications/workers/release/rest-worker/src/e2eTest/kotlin/net/corda/applications/workers/rest/MultiClusterDynamicNetworkTest.kt
> +    @Tag("Unstable")
I think these were flaky for a while and until we did some investigations these got marked this tag, but as I can see this change recently got removed on the release branch, so I will remove it as well.

2023-07-11 13:29 UTC, nikinagy commented on applications/workers/release/rest-worker/src/e2eTest/kotlin/net/corda/applications/workers/rest/MultiClusterDynamicNetworkTest.kt
> +    @Tag("Unstable")
addressed in [48fb13c](https://github.com/corda/corda-runtime-os/pull/4219/commits/48fb13cc3f9e996641763916dccc8f17cb24234f)

2023-07-11 13:31 UTC, nikinagy commented on gradle.properties
> +cordaApiVersion=5.1.0.6-alpha-1688549679598
I know, but first this PR needs to be reviewed too. I don't want to block API-runtime merges, because I address comments on this one.

2023-07-11 13:32 UTC, josephzunigadaly commented on applications/workers/release/rest-worker/src/e2eTest/kotlin/net/corda/applications/workers/rest/MultiClusterDynamicNetworkTest.kt
> +    @Tag("Unstable")
Thank you.

We've got a few more instances:
* applications/workers/release/rest-worker/src/e2eTest/kotlin/net/corda/applications/workers/rest/SessionCertificateTest.kt
* applications/workers/release/rest-worker/src/e2eTest/kotlin/net/corda/applications/workers/rest/SessionCertificateTest.kt
* applications/workers/release/rest-worker/src/e2eTest/kotlin/net/corda/applications/workers/rest/StaticNetworkTest.kt

2023-07-11 13:39 UTC, josephzunigadaly commented on applications/workers/release/rest-worker/src/e2eTest/kotlin/net/corda/applications/workers/rest/MultiClusterDynamicNetworkTest.kt
> +    @Tag("Unstable")
One more:
applications/workers/release/rest-worker/src/e2eTest/kotlin/net/corda/applications/workers/rest/SingleClusterDynamicNetworkTest.kt

2023-07-11 14:15 UTC, nikinagy commented on applications/workers/release/rest-worker/src/e2eTest/kotlin/net/corda/applications/workers/rest/MultiClusterDynamicNetworkTest.kt
> +    @Tag("Unstable")
Removed these in [789fb4b](https://github.com/corda/corda-runtime-os/pull/4219/commits/789fb4bf3dd3cfe06f05448a7fb1174bcdded839) and [93952ec](https://github.com/corda/corda-runtime-os/pull/4219/commits/93952ecfb28547fd2bdc11c66c6826cc29347eda)

2023-07-11 15:09 UTC, dimosr approved these changes

2023-07-11 15:11 UTC, seanbrereton approved these changes
LGTM (build)

2023-07-11 15:17 UTC, vkolomeyko commented on build.gradle
> +            outputName = "${project.name}-corda-runtime-os-sbom"
No, that's fine.

2023-07-11 15:18 UTC, vkolomeyko approved these changes
LGTM

2023-07-11 15:35 UTC, merged