CORE-14484 Implement interop group management
corda/corda-runtime-os pull request #4221
Opened 2023-07-05 13:37 UTC by ac101m

# Changes
- Refactor interop identity cache service for better isolation of holding identity views.

2023-07-05 15:17 UTC, szymonsztuka commented on components/interop/interop-identity-cache-service/src/main/kotlin/net/corda/interop/identity/cache/InteropIdentityCacheEntry.kt
> +data class InteropIdentityCacheEntry(
This is modeled exactly like Kafka entry, which is flatten list of entries of different type. Let's forget about that class, how to model this: 
1) HoldingIdentity has set of InteropGroups
2) In each InteropGroup HoldingIdentity must have it's own InteropIdentty (x500Name) which is presenting to others
3) In each Interopgroup there is set of other InteropIdentities (x500Name values)

2023-07-05 15:41 UTC, ac101m commented on components/interop/interop-identity-cache-service/src/main/kotlin/net/corda/interop/identity/cache/InteropIdentityCacheEntry.kt
> +data class InteropIdentityCacheEntry(
See `InteropIdentityCacheView`

2023-07-10 18:38 UTC, jmacmahonr3 requested changes

2023-07-10 18:38 UTC, jmacmahonr3 commented on components/interop/interop-identity-cache-service-impl/src/main/kotlin/net/corda/interop/identity/cache/impl/InteropIdentityCacheViewImpl.kt
> +class InteropIdentityCacheViewImpl(private val holdingIdentityShortHash: String): InteropIdentityCacheView {
I think we are missing a method which is effectively "get my alias for this group"

2023-07-10 18:38 UTC, jmacmahonr3 commented on libs/interop/interop-core/src/main/kotlin/net/corda/interop/core/InteropIdentity.kt
> +data class InteropIdentity(
We'll need to add list of facadeIds here as well

2023-07-10 18:38 UTC, jmacmahonr3 commented on libs/interop/interop-rest/src/main/kotlin/net/corda/libs/interop/endpoints/v1/InteropRestResource.kt
>      ): Map<UUID,String>
@szymonsztuka @ac101m @julia-filipczak 

I think we are going to need to remove any and all references to the groupId that exist external to the cluster. 
The get method is probably fine but I think we will need to bring back InterOp Group 'Names' and each cluster generates their own UUID for the group. This makes the UUID more likely to be unique and makes the user experience nicer. Thoughts ?

2023-07-11 09:33 UTC, ac101m commented on components/interop/interop-identity-cache-service-impl/src/main/kotlin/net/corda/interop/identity/cache/impl/InteropIdentityCacheViewImpl.kt
> +class InteropIdentityCacheViewImpl(private val holdingIdentityShortHash: String): InteropIdentityCacheView {
This is actually the reason the (as of yet unused) constructor parameter is here, so that we can detect when newly added identities belong to the virtual node. I'll add this today.

2023-07-11 14:07 UTC, ac101m commented on components/interop/interop-identity-cache-service-impl/src/main/kotlin/net/corda/interop/identity/cache/impl/InteropIdentityCacheViewImpl.kt
> +class InteropIdentityCacheViewImpl(private val holdingIdentityShortHash: String): InteropIdentityCacheView {
Added method for fetching owned identities

2023-07-20 09:31 UTC, ac101m commented on components/interop/interop-rest-service-impl/src/main/kotlin/net/corda/interop/rest/impl/v1/InteropRestResourceImpl.kt
> +        return interopIdentityJson + "\n" + groupPolicy
This doesn't produce valid json!
Should probably do something along the lines of:
```
{
    "identity": $interopIdentityJson,
    "groupPolicy": $groupPolicy
}
```
Or better still, create a specific ExportInteropIdentityResponse object and return that.

2023-07-21 16:11 UTC, ac101m reviewed
@julia-filipczak A few endpoint related comments

2023-07-21 16:11 UTC, ac101m commented on components/interop/interop-rest-service-impl/src/main/kotlin/net/corda/interop/rest/impl/v1/InteropRestResourceImpl.kt
> +    override fun getInterOpGroups(vnodeshorthash: String): Map<UUID, String> {
@julia-filipczak Should rename this to `holdingIdentityShortHash` as it is exposed to the user in the endpoint. It should then be converted to a virtual node short hash by looking up the virtual node info.

2023-07-21 16:11 UTC, ac101m commented on components/interop/interop-rest-service-impl/src/main/kotlin/net/corda/interop/rest/impl/v1/InteropRestResourceImpl.kt
> +        vnodeshorthash: String
ditto

2023-07-21 16:11 UTC, ac101m commented on components/interop/interop-rest-service-impl/src/main/kotlin/net/corda/interop/rest/impl/v1/InteropRestResourceImpl.kt
> +
Ditto, input parameter should be the holding identity short hash, then we need a lookup to get the virtual node short hash.

2023-07-21 16:11 UTC, ac101m commented on components/interop/interop-rest-service-impl/src/main/kotlin/net/corda/interop/rest/impl/v1/InteropRestResourceImpl.kt
> +    override fun getInterOpIdentities(vnodeshorthash: String): List<InteropIdentityResponse> {
ditto

2023-07-21 16:11 UTC, ac101m commented on components/interop/interop-rest-service-impl/src/main/kotlin/net/corda/interop/rest/impl/v1/InteropRestResourceImpl.kt
> +        val cacheView = interopIdentityCacheService.getVirtualNodeCacheView(vnodeshorthash)
The `getByHoldingIdentityShortHash` method has a nullable return value. If it's null, that means the virtual node doesn't exist, which is an error case! You should check this and generate an error message something along the lines of "No virtual node found with short hash {holdingIdentityShortHash}", or similar. You'll need this check in all endpoints that accept a holding identity short hash.

2023-07-21 16:11 UTC, ac101m commented on components/interop/interop-rest-service-impl/src/main/kotlin/net/corda/interop/rest/impl/v1/InteropRestResourceImpl.kt
> +    override fun exportInterOpIdentity(vnodeshorthash: String, interopIdentityShortHash: String): String {
Ditto here, use holding identity short hash and convert to virtual node short hash with a lookup

2023-07-21 16:11 UTC, ac101m commented on components/interop/interop-rest-service-impl/src/main/kotlin/net/corda/interop/rest/impl/v1/InteropRestResourceImpl.kt
> +        vnodeshorthash: String
ditto

2023-07-21 16:11 UTC, ac101m commented on components/interop/interop-rest-service-impl/src/main/kotlin/net/corda/interop/rest/impl/v1/InteropRestResourceImpl.kt
> +                owningVirtualNodeShortHash = vnodeshorthash,
This should be the owning virtual node short hash from the rest interop identity object

2023-07-21 16:11 UTC, ac101m commented on libs/interop/interop-rest/src/main/kotlin/net/corda/libs/interop/endpoints/v1/types/InteropIdentityResponse.kt
> +    val shortHash: String?,
I think this may be a source of some of your confusion. We don't need to export the interop identity short hash, but we do need to export the owning virtual node short hash! Rename this to `owningVirtualNodeShortHash`, and make it non nullable.

2023-07-21 16:11 UTC, ac101m commented on components/interop/interop-rest-service-impl/src/main/kotlin/net/corda/interop/rest/impl/v1/InteropRestResourceImpl.kt
> +                endpointUrl = restInteropIdentity.endpointUrl
These two data points shouldn't be passed in by REST. They should come from the virtual node info object iirc @jmacmahonr3 correct me if I'm wrong.

2023-07-21 16:11 UTC, ac101m commented on libs/interop/interop-rest/src/main/kotlin/net/corda/libs/interop/endpoints/v1/types/RestInteropIdentity.kt
>  )
When creating a new interop identity, we don't need the endpoint protocol or endpoint url as that info comes from the owning virtual node. We may want separate objects for creating and importing, or for these to be nullable. Again, @jmacmahonr3 correct me if I am mistaken.

2023-07-24 16:45 UTC, jmacmahonr3 commented on components/interop/interop-rest-service-impl/src/main/kotlin/net/corda/interop/rest/impl/v1/InteropRestResourceImpl.kt
> +                endpointUrl = restInteropIdentity.endpointUrl
I had to look into this one a bit. For the moment in Corda5 endpointProtocol is one fixed value so we should just inherit both from Vnode data

2023-07-24 16:46 UTC, jmacmahonr3 commented on libs/interop/interop-rest/src/main/kotlin/net/corda/libs/interop/endpoints/v1/types/RestInteropIdentity.kt
>  )
I think it's fine to return them as part of a get to make sure that the data is up to date incase your own url changes and then we would somehow do a refresh but for now it doesn't need to be implicitly passed in

2023-07-24 17:36 UTC, ac101m commented on libs/interop/interop-rest/src/main/kotlin/net/corda/libs/interop/endpoints/v1/types/RestInteropIdentity.kt
>  )
We need to split this class into separate request/response classes for each endpoint.

- `CreateInteropIdentityRequestData`/`CreateInteropIdentityResponseData`
- `ExportInteropIdentityResponseData`
- `ImportInteropIdentityRequestData`

Reasoning:

Several parameters are not required when creating, for example the group ID is optional when creating and the endpoint protocol and endpointUrl should not be present when creating. If we use the same class for all of this, we'll need a lot of nullable fields and a lot of checking.

2023-07-24 17:36 UTC, ac101m commented on libs/interop/interop-rest/src/main/kotlin/net/corda/libs/interop/endpoints/v1/types/RestInteropIdentity.kt
> +    val owningVirtualNodeShortHash: String,
Also, this should be `holdingIdentityShortHash` as it's exposed to the user.

2023-07-24 17:36 UTC, ac101m commented on libs/interop/interop-rest/src/main/kotlin/net/corda/libs/interop/endpoints/v1/types/InteropIdentityResponse.kt
> +data class InteropIdentityResponse(
Let's also have separate response classes for each endpoint.

2023-07-25 08:57 UTC, ac101m commented on libs/interop/interop-rest/src/main/kotlin/net/corda/libs/interop/endpoints/v1/types/RestInteropIdentity.kt
>  )
I'm talking specifically about the create endpoint here. Also, there's nothing _implicit_ about it! If it's a field in this class, then it ends up being _required_ whenever this is passed. This is why I think we should be having separate request/response objects for each endpoint.

2023-07-25 14:22 UTC, jmacmahonr3 requested changes

2023-07-25 14:22 UTC, jmacmahonr3 commented on components/interop/interop-group-policy-read-service/src/main/kotlin/net/corda/interop/group/policy/read/InteropGroupPolicyReadService.kt
> +    fun getGroupPolicy(groupId: String) : String?
@SaurabhR3 maybe better to take UUID and then convert to string in Impl

2023-07-25 14:22 UTC, jmacmahonr3 commented on components/interop/interop-identity-cache-service-impl/src/main/kotlin/net/corda/interop/identity/cache/impl/InteropIdentityCacheServiceEventHandler.kt
>  class InteropIdentityCacheServiceEventHandler(
@ac101m & @szymonsztuka 
Maybe in this PR we should remove all uses of the name 'cache' and appropriately replace them with either reader or nothing. 

InteropIdenityCacheServiceEventHandler becomes InteropIdenityServiceEventHandler for example

2023-07-25 14:22 UTC, jmacmahonr3 commented on components/interop/interop-identity-cache-service-impl/src/main/kotlin/net/corda/interop/identity/cache/impl/InteropIdentityCacheServiceImpl.kt
> +    private val cacheData = HashMap<String, InteropIdentityCacheViewImpl>()
InteropIdenityCacheView should likely become InteropIdenityServiceReader or something else that doesn't use the word Cache

2023-07-25 14:22 UTC, jmacmahonr3 commented on components/interop/interop-identity-cache-service-impl/src/main/kotlin/net/corda/interop/identity/cache/impl/InteropIdentityCacheViewImpl.kt
> +    private val byGroupId = HashMap<String, HashSet<InteropIdentity>>()
As stated previously some of these will be removed as likely unneeded by a filter by FacadeId would be helpful.

2023-07-25 14:22 UTC, jmacmahonr3 commented on components/interop/interop-identity-cache-service/src/main/kotlin/net/corda/interop/identity/cache/InteropIdentityCacheView.kt
> +interface InteropIdentityCacheView {
As mentioned above we should remove our use of the word Cache. 
I think InterOpIdentityServiceReader maybe ?

2023-07-25 14:22 UTC, jmacmahonr3 commented on components/interop/interop-identity-write-service-impl/src/main/kotlin/net/corda/interop/identity/write/impl/InteropIdentityWriteServiceImpl.kt
> +    override fun addInteropIdentity(vNodeShortHash: String, identity: InteropIdentity) {
We should address this todo as part of this pr. Add a param for isOwned which decides which topics we write to.
@ac101m

2023-07-25 14:22 UTC, jmacmahonr3 commented on components/interop/interop-identity-write-service-impl/src/main/kotlin/net/corda/interop/identity/write/impl/MembershipInfoProducer.kt
> +        private val DUMMY_CERTIFICATE =
@SaurabhR3 or @ac101m add todo and link to the following ticket 
https://r3-cev.atlassian.net/browse/CORE-15749

2023-07-25 14:22 UTC, jmacmahonr3 commented on components/interop/interop-identity-write-service-impl/src/main/kotlin/net/corda/interop/identity/write/impl/MembershipInfoProducer.kt
> +                    "9DEA9C982267BD142162ADC141C1C11C2F547C3C37B4C693A3EA3A017C2C6563"
Extract to a value and a todo linked to this ticket 
https://r3-cev.atlassian.net/browse/CORE-15749

2023-07-25 14:22 UTC, jmacmahonr3 commented on components/interop/interop-identity-write-service-impl/src/main/kotlin/net/corda/interop/identity/write/impl/MembershipInfoProducer.kt
> +                    "DFE65EAD29C556DF3A9C94C1A0F2C2155FFCC0768A282E18985BB021E8103B9D"
Same as above

2023-07-25 14:22 UTC, jmacmahonr3 commented on libs/interop/interop-rest/src/main/kotlin/net/corda/libs/interop/endpoints/v1/types/InteropIdentityResponse.kt
> +data class InteropIdentityResponse(
I think eventually we will have to move to async response but for now this is grand

2023-07-25 14:22 UTC, jmacmahonr3 commented on libs/interop/interop-rest/src/main/kotlin/net/corda/libs/interop/endpoints/v1/types/RestInteropIdentity.kt
>      val x500Name: String,
Is this used in the export? If not do we need the x500?

2023-07-25 14:22 UTC, jmacmahonr3 commented on libs/interop/interop-rest/src/main/kotlin/net/corda/libs/interop/endpoints/v1/types/RestInteropIdentity.kt
> +    val facadeIds: List<String>,
Should this be list of FacadeId objects ?

2023-07-25 17:05 UTC, ac101m commented on components/interop/interop-rest-service-impl/src/main/kotlin/net/corda/interop/rest/impl/v1/InteropRestResourceImpl.kt
> +                "No virtual node found with short hash $holdingIdentityShortHash."
As this is used in a few places, let's give it it's own method.

2023-07-25 17:06 UTC, ac101m commented on libs/interop/interop-rest/src/main/kotlin/net/corda/libs/interop/endpoints/v1/types/RestInteropIdentity.kt
>      val x500Name: String,
This is currently used in the export, but won't be for much longer.

2023-07-25 17:07 UTC, ac101m commented on components/interop/interop-identity-write-service-impl/src/main/kotlin/net/corda/interop/identity/write/impl/InteropIdentityWriteServiceImpl.kt
> +    override fun addInteropIdentity(vNodeShortHash: String, identity: InteropIdentity) {
This functionality is already in place. If the vNodeShortHash matches the owner vNodeShortHash in the identity, it's an owned identity.

2023-07-25 17:08 UTC, ac101m commented on components/interop/interop-identity-cache-service/src/main/kotlin/net/corda/interop/identity/cache/InteropIdentityCacheView.kt
> +interface InteropIdentityCacheView {
Fair enough, will refactor this

2023-07-25 17:09 UTC, ac101m commented on libs/interop/interop-rest/src/main/kotlin/net/corda/libs/interop/endpoints/v1/types/InteropIdentityResponse.kt
> +data class InteropIdentityResponse(
No. There are differences between the import/export/create. We need separate classes for each of the rest endpoints. That's what the meeting I dragged everyone through this morning was about.

2023-07-26 14:07 UTC, ac101m commented on components/interop/interop-identity-cache-service-impl/src/main/kotlin/net/corda/interop/identity/cache/impl/InteropIdentityCacheServiceEventHandler.kt
>  class InteropIdentityCacheServiceEventHandler(
I've renamed all instances of `InteropIdentityCache<whatever>` to `InteropIdentityRegistry<whatever>`, lmk if you think this is ok

2023-07-26 14:19 UTC, SaurabhR3 commented on libs/interop/interop-rest/src/main/kotlin/net/corda/libs/interop/endpoints/v1/types/RestInteropIdentity.kt
>  )
@ac101m I would remove postfix `Data` from all mentioned class name

2023-07-26 14:22 UTC, SaurabhR3 commented on components/interop/interop-identity-cache-service-impl/src/main/kotlin/net/corda/interop/identity/cache/impl/InteropIdentityCacheServiceEventHandler.kt
>  class InteropIdentityCacheServiceEventHandler(
I would simply go with `InteropIdentityService<whatever>`

2023-07-26 14:32 UTC, SaurabhR3 commented
@jmacmahonr3 @szymonsztuka  @ac101m  @julia-filipczak In this implementation we have created many modules `interop-identity-cache-service`, `interop-identity-cache-service-impl`, `interop-identity-read-service`, `interop-identity-read-service-impl`, `interop-identity-write-service`, `interop-identity-write-service-impl`, `interop-group-policy-read-service` , `interop-group-policy-read-service-impl`

If we follow the pattern used in `virtual-node-info-read-service` we can get rid of many unnecessary modules and total modules size will be half for interop.

Whats your thoughts?

2023-07-26 16:47 UTC, ac101m commented
> Whats your thoughts?

I noticed this as well. We don't actually need separate modules for implementation and interfaces, just separate packages. I think we should do this, but probably not right away. Let's hold it until everything else is working.

2023-07-27 11:42 UTC, ac101m commented on libs/interop/interop-rest/src/main/kotlin/net/corda/libs/interop/endpoints/v1/types/RestInteropIdentity.kt
>  )
Ended up not using this exact naming

2023-07-27 16:50 UTC, ac101m commented on components/interop/interop-identity-write-service-impl/src/main/kotlin/net/corda/interop/identity/write/impl/MembershipInfoProducer.kt
> +                    "9DEA9C982267BD142162ADC141C1C11C2F547C3C37B4C693A3EA3A017C2C6563"
Done

2023-07-27 17:39 UTC, ac101m reviewed
Another pass over the endpoints, still some issues!

2023-07-27 17:39 UTC, ac101m commented on components/interop/interop-identity-write-service-impl/src/main/kotlin/net/corda/interop/identity/write/impl/InteropIdentityWriteServiceImpl.kt
> +    }
Add space after previous method, some code style issues also (indentation, space before parentheses).
Also, is this robust enough? I'd be more confident of this if we actually parsed the json.

2023-07-27 17:39 UTC, ac101m commented on components/interop/interop-identity-write-service-impl/src/main/kotlin/net/corda/interop/identity/write/impl/InteropIdentityWriteServiceImpl.kt
> +    override fun addInteropIdentity(vNodeShortHash: String, identity: InteropIdentity) {
Oh, I misunderstood this! Thought we were talking about the cache itself for some reason. This is now fixed.

2023-07-27 17:39 UTC, ac101m commented on components/interop/interop-rest-service-impl/src/main/kotlin/net/corda/interop/rest/impl/v1/InteropRestResourceImpl.kt
> +        )
@julia-filipczak Missing some checks here!
If the group is not "CREATE_ID", or a valid UUID, we need to throw an appropriate error.
Also, if the group ID _is_ "CREATE_ID" we need to throw an error if `members` has any elements.

@jmacmahonr3 @SaurabhR3 Should there also be a check to see if the group is already present, and maybe a comparison with the pre-existing group data?

2023-07-27 17:39 UTC, ac101m commented on components/interop/interop-rest-service-impl/src/main/kotlin/net/corda/interop/rest/impl/v1/InteropRestResourceImpl.kt
> +                endpointProtocol = "endpointProtocol",
Still need to figure out how to get these out of the member list topic.

2023-07-27 17:39 UTC, ac101m commented on components/interop/interop-rest-service-impl/src/main/kotlin/net/corda/interop/rest/impl/v1/InteropRestResourceImpl.kt
> +                facadeIds = listOf("facadeIds"),
@jmacmahonr3 What's the plan with the facade IDs on create? Do we want to pass them in with the create request, or should they be inherited from the virtual node somehow?

2023-07-27 17:39 UTC, ac101m commented on components/interop/interop-rest-service-impl/src/main/kotlin/net/corda/interop/rest/impl/v1/InteropRestResourceImpl.kt
> +        val cacheView = interopIdentityRegistryService.getVirtualNodeCacheView(holdingIdentityShortHash)
Extract vNodeShortHash into a variable, then use it here and in the InteropIdentityResponse constructor.

2023-07-27 17:39 UTC, ac101m commented on components/interop/interop-rest-service-impl/src/main/kotlin/net/corda/interop/rest/impl/v1/InteropRestResourceImpl.kt
> +                it.endpointProtocol
Might be a good idea to name the iterator variable, e.g: `interopIdentities.map { interopIdentity ->`.
Also I would use keyword arguments for readability here.

2023-07-27 17:39 UTC, ac101m commented on components/interop/interop-rest-service-impl/src/main/kotlin/net/corda/interop/rest/impl/v1/InteropRestResourceImpl.kt
> +        val groupPolicy = getGroupPolicy()
TODO: We need to read the correct group policy here

2023-07-27 17:39 UTC, ac101m commented on components/interop/interop-rest-service-impl/src/main/kotlin/net/corda/interop/rest/impl/v1/InteropRestResourceImpl.kt
> +                "The members list is empty, no interop identities exist."
I feel this error message is a little unclear here.
Maybe more like "No members provided in request, nothing to import." or something like this.

2023-07-27 17:39 UTC, ac101m commented on components/interop/interop-rest-service-impl/src/main/kotlin/net/corda/interop/rest/impl/v1/InteropRestResourceImpl.kt
> +        )
We need a check here that the group ID is _not_ "CREATE_ID", if it is at this stage, that's an error.

2023-07-27 17:39 UTC, ac101m commented on components/interop/interop-rest-service-impl/src/main/kotlin/net/corda/interop/rest/impl/v1/InteropRestResourceImpl.kt
> +        val owningIdentityShortHash = importInteropIdentityRestRequest.members[0].owningIdentityShortHash
This is not correct. We need to iterate over the members and add each of them in turn.

2023-07-27 17:39 UTC, ac101m commented on components/interop/interop-rest-service-impl/src/main/kotlin/net/corda/interop/rest/impl/v1/InteropRestResourceImpl.kt
> +        val owningVirtualNodeShortHash = vNodeInfo.getVNodeShortHash()
The owning virtual node may not exist on the cluster where this is being imported!
In this case, don't do the check. Just take the owningVirtualNodeShortHash value from the member and put it directly into the InteropIdentity.

2023-07-27 17:39 UTC, ac101m commented on components/interop/interop-rest-service-impl/src/main/kotlin/net/corda/interop/rest/impl/v1/InteropRestResourceImpl.kt
> +            holdingIdentityShortHash,
We do want to check this one though! Use `getAndValidateVirtualNodeInfoByShortHash` on this.

2023-07-27 17:39 UTC, ac101m commented on components/interop/interop-rest-service-impl/src/main/kotlin/net/corda/interop/rest/impl/v1/InteropRestResourceImpl.kt
> +        endpointProtocol: String,
These fields are part of the `MemberData` object, we don't need them here.

2023-07-28 13:04 UTC, SaurabhR3 requested changes

2023-07-28 13:04 UTC, SaurabhR3 commented on libs/interop/interop-rest/src/main/kotlin/net/corda/libs/interop/endpoints/v1/types/ExportInteropIdentityRest.kt
> +class ExportInteropIdentityRest {
@ac101m @jmacmahonr3  I think the name of the class can be changed to something like `InteropMemberIdentity` or `InteropMember`. Export represents functionality here.

2023-07-28 13:04 UTC, SaurabhR3 commented on libs/interop/interop-rest/src/main/kotlin/net/corda/libs/interop/endpoints/v1/types/ExportInteropIdentityRest.kt
> +    class Response(
Also Better to keep the separate Response classes rather than adding it as inner class.

2023-07-28 14:10 UTC, ac101m commented on libs/interop/interop-rest/src/main/kotlin/net/corda/libs/interop/endpoints/v1/types/ExportInteropIdentityRest.kt
> +    class Response(
Why?
`ExportInteropIdentityRest.Request` and `ExportInteropIdentity.Response` are expressive and easily readable.

2023-07-28 14:11 UTC, ac101m commented on libs/interop/interop-rest/src/main/kotlin/net/corda/libs/interop/endpoints/v1/types/ExportInteropIdentityRest.kt
> +class ExportInteropIdentityRest {
These classes are deliberately named after the endpoints they are associated with.

2023-07-31 16:41 UTC, yarivus reviewed
a few comments

2023-07-31 16:41 UTC, yarivus commented on components/interop/interop-identity-registry-service-impl/src/main/kotlin/net/corda/interop/identity/cache/impl/InteropIdentityRegistryServiceEventHandler.kt
> +    private val cacheService: InteropIdentityRegistryServiceImpl
```suggestion
    private val registryService: InteropIdentityRegistryServiceImpl
```

2023-07-31 16:41 UTC, yarivus commented on libs/interop/interop-core/src/main/kotlin/net/corda/interop/core/Utils.kt
> +            return interopHoldingIdentity.shortHash.value
```suggestion
            return HoldingIdentity(MemberX500Name.parse(name), groupId).shortHash.value
```

2023-07-31 16:41 UTC, yarivus commented on components/interop/interop-identity-registry-service/src/main/kotlin/net/corda/interop/identity/cache/InteropIdentityRegistryService.kt
> +    fun getVirtualNodeCacheView(virtualNodeShortHash: String): InteropIdentityRegistryView
Why is `Cache` word required in the name of the API ?

2023-07-31 16:41 UTC, yarivus commented on components/interop/interop-identity-write-service-impl/src/main/kotlin/net/corda/interop/identity/write/impl/InteropGroupPolicyProducer.kt
> +        futures.forEach { it.get() }
I don't follow this code - what is it trying to do ?
You publish a list of records which create futures and then you block for them to complete ?

2023-07-31 16:41 UTC, yarivus commented on components/interop/interop-identity-write-service-impl/src/main/kotlin/net/corda/interop/identity/write/impl/InteropIdentityWriteServiceImpl.kt
> +    override fun publishGroupPolicy(groupId: String, groupPolicy: String) : String {
```suggestion
    }

    override fun publishGroupPolicy(groupId: String, groupPolicy: String) : String {
```

2023-07-31 16:41 UTC, yarivus commented on libs/interop/interop-core/src/main/kotlin/net/corda/interop/core/InteropIdentity.kt
> + * Currently, the kotlin data class implementation takes care of this.
is this comment still relevant once the equals is explicitly implemented here ?

2023-08-01 07:45 UTC, ac101m commented on components/interop/interop-identity-registry-service-impl/src/main/kotlin/net/corda/interop/identity/cache/impl/InteropIdentityRegistryServiceEventHandler.kt
> +    private val cacheService: InteropIdentityRegistryServiceImpl
Yup. looks like I missed those!

2023-08-01 07:47 UTC, ac101m commented on libs/interop/interop-core/src/main/kotlin/net/corda/interop/core/Utils.kt
> +            return interopHoldingIdentity.shortHash.value
Done

2023-08-01 07:48 UTC, ac101m commented on components/interop/interop-identity-registry-service/src/main/kotlin/net/corda/interop/identity/cache/InteropIdentityRegistryService.kt
> +    fun getVirtualNodeCacheView(virtualNodeShortHash: String): InteropIdentityRegistryView
Left over from the rename, resolved

2023-08-01 07:53 UTC, ac101m commented on components/interop/interop-identity-write-service-impl/src/main/kotlin/net/corda/interop/identity/write/impl/InteropGroupPolicyProducer.kt
> +        futures.forEach { it.get() }
This was a pattern that I followed from elsewhere in the codebase without really understanding. Looking at the kdoc for `publish` though, it looks like it's an error reporting mechanism and the futures return either an error or `true`. Will look into this a little and clean it up if necessary.

2023-08-01 07:54 UTC, ac101m commented on libs/interop/interop-core/src/main/kotlin/net/corda/interop/core/InteropIdentity.kt
> + * Currently, the kotlin data class implementation takes care of this.
It is not! Fixed.

2023-08-01 07:55 UTC, ac101m commented on components/interop/interop-identity-write-service-impl/src/main/kotlin/net/corda/interop/identity/write/impl/InteropIdentityWriteServiceImpl.kt
> +    override fun publishGroupPolicy(groupId: String, groupPolicy: String) : String {
Fixed

2023-08-01 07:57 UTC, ac101m commented on components/interop/interop-identity-write-service-impl/src/main/kotlin/net/corda/interop/identity/write/impl/InteropIdentityWriteServiceImpl.kt
> +    }
Resolved in response to review comment from yariv

2023-08-01 13:51 UTC, yarivus reviewed
Still pending comments.
@jmacmahonr3 / @ac101m / @SaurabhR3 / @julia-filipczak 
Please resolve the outdated comments - a bit of cleanup would be more clear to see what's still pending

2023-08-01 14:16 UTC, ac101m commented on components/interop/interop-rest-service-impl/src/main/kotlin/net/corda/interop/rest/impl/v1/InteropRestResourceImpl.kt
> +                endpointUrl = restInteropIdentity.endpointUrl
Marking as resolved as there is another comment further down to deal with this

2023-08-02 20:44 UTC, yarivus reviewed
still pending comments 
Try to resolve comments of resolved issues

2023-08-03 20:19 UTC, yarivus reviewed
pending comments

2023-08-03 20:19 UTC, yarivus commented on components/interop/interop-identity-write-service-impl/src/main/kotlin/net/corda/interop/identity/write/impl/InteropGroupPolicyProducer.kt
> +        futures.forEach { it.get() }
Is this comment still pending @ac101m ?

2023-08-04 09:54 UTC, ac101m commented on components/interop/interop-identity-write-service-impl/src/main/kotlin/net/corda/interop/identity/write/impl/InteropGroupPolicyProducer.kt
> +        futures.forEach { it.get() }
Yup, totally slipped my mind, taking a look now

2023-08-04 10:36 UTC, ac101m commented on components/interop/interop-identity-write-service-impl/src/main/kotlin/net/corda/interop/identity/write/impl/InteropGroupPolicyProducer.kt
> +        futures.forEach { it.get() }
Done, added a catch/rethrow to these

2023-08-06 19:17 UTC, yarivus reviewed
LGTM

2023-08-10 11:14 UTC, yarivus reviewed
see some comments

2023-08-10 11:14 UTC, yarivus commented on build.gradle
> +                languageVersion = of(17)
why are we reverting the java 17 changes ?

2023-08-10 11:14 UTC, yarivus commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/application/services/impl/InteropIdentityLookUpImpl.kt
> +//        }
commented out code

2023-08-10 11:14 UTC, yarivus commented on components/flow/flow-service/src/test/kotlin/net/corda/flow/fiber/ClientRequestBodyImplTest.kt
> +        val executionContext = FlowFiberExecutionContext(checkpoint, mock(), holdingIdentity, mock(), mock(),mock(), emptyMap(), mock())
```suggestion
        val executionContext = FlowFiberExecutionContext(checkpoint, mock(), holdingIdentity, mock(), mock(), mock(), emptyMap(), mock())
```

2023-08-10 11:14 UTC, yarivus commented on components/flow/flow-service/src/test/kotlin/net/corda/flow/fiber/FlowFiberExecutionContextTest.kt
> +        val context = FlowFiberExecutionContext(mock(), mock(), holdingIdentity, mock(), mock(),mock(), emptyMap(), mock())
```suggestion
        val context = FlowFiberExecutionContext(mock(), mock(), holdingIdentity, mock(), mock(), mock(), emptyMap(), mock())
```

2023-08-10 11:14 UTC, yarivus commented on components/interop/interop-identity-registry-service-impl/src/main/kotlin/net/corda/interop/identity/cache/impl/InteropIdentityRegistryViewImpl.kt
> +        byFacadeId.forEach{
```suggestion
        byFacadeId.forEach {
```

2023-08-10 11:14 UTC, yarivus commented on components/interop/interop-identity-registry-service-impl/src/main/kotlin/net/corda/interop/identity/cache/impl/InteropIdentityRegistryViewImpl.kt
> +            if (it.value.contains(identity)){
```suggestion
            if (it.value.contains(identity)) {
```

2023-08-10 11:14 UTC, yarivus commented on components/interop/interop-identity-registry-service-impl/src/main/kotlin/net/corda/interop/identity/processor/InteropIdentityProcessor.kt
> +        if (newValue?.localToVNode == true){
```suggestion
        if (newValue?.localToVNode) {
```

2023-08-10 11:14 UTC, yarivus commented on testing/cpbs/interop-token-demo-workflows/src/main/kotlin/com/r3/corda/demo/interop/tokens/workflows/interop/GetInteropIdentity.kt
> +    }
```suggestion
        }
    }
```

2023-08-10 11:14 UTC, yarivus commented on testing/cpbs/interop-token-demo-workflows/src/main/kotlin/com/r3/corda/demo/interop/tokens/workflows/interop/SimpleSwapFlow.kt
> +                facadeService.getProxy(facadeId, TokensFacade::class.java,myInteropInfo)
```suggestion
                facadeService.getProxy(facadeId, TokensFacade::class.java, myInteropInfo)
```

2023-08-10 11:14 UTC, yarivus commented on testing/cpbs/test-invocation-cordapp/src/main/kotlin/com/r3/corda/testing/interop/FacadeInvocationFlow.kt
>          log.info("AliasMemberInfo for $alias  : $aliasMember")
should this still be named `aliasMember` ? (also AliasMemberInfo in the log)

2023-08-10 21:28 UTC, yarivus reviewed
pending comments

2023-08-10 21:28 UTC, yarivus commented on components/interop/interop-identity-registry-service-impl/src/main/kotlin/net/corda/interop/identity/cache/impl/InteropIdentityRegistryViewImpl.kt
placeholder comment for commented out code

2023-08-10 21:28 UTC, yarivus commented on libs/interop/interop-rest/src/test/kotlin/net/corda/libs/interop/endpoints/v1/Test1.kt
rename from Test1

2023-08-10 21:28 UTC, yarivus commented on libs/interop/interop-rest/src/main/kotlin/net/corda/libs/interop/endpoints/v1/types/ImportInteropIdentityRest2.kt
will Rest2 and Rest3 remain ?

2023-08-11 08:50 UTC, szymonsztuka commented on libs/interop/interop-rest/src/main/kotlin/net/corda/libs/interop/endpoints/v1/types/ImportInteropIdentityRest2.kt
this is temporary helper code to unblock Julia

2023-08-11 09:02 UTC, szymonsztuka commented on libs/interop/interop-rest/src/test/kotlin/net/corda/libs/interop/endpoints/v1/Test1.kt
Fixed, changed the name to something meaningful

2023-08-11 09:30 UTC, jmacmahonr3 requested changes

2023-08-11 09:30 UTC, jmacmahonr3 commented on libs/interop/interop-rest/src/main/kotlin/net/corda/libs/interop/endpoints/v1/types/GroupPolicy.kt
> +    val members: List<String>
@julia-filipczak we don't want to store the members. Our group policy shouldn't contain it.

@SaurabhR3 & @szymonsztuka

2023-08-11 09:30 UTC, jmacmahonr3 commented on libs/interop/interop-rest/src/main/kotlin/net/corda/libs/interop/endpoints/v1/types/GroupPolicy.kt
> +    val registrationProtocol: String,
@julia-filipczak registration protocol & sync protocol are not fields we need in our policy. I think we have to have them for now so best to hardcode them to a dummy value. 

@SaurabhR3 & @szymonsztuka

2023-08-11 10:10 UTC, szymonsztuka commented on libs/interop/interop-rest/src/main/kotlin/net/corda/libs/interop/endpoints/v1/types/GroupPolicy.kt
> +    val members: List<String>
I've answered indirectly on slack, yes this is just a big current JSON in used, so I started from a superset, but My aim was just testing JSON->Kotlin-> String, my aim was not decide which fields are needed, so fell free to trim them

2023-08-11 13:12 UTC, yarivus reviewed
unresolved comments

2023-08-11 15:01 UTC, yarivus reviewed
checkpoint review

2023-08-11 15:53 UTC, yarivus reviewed
checkpoint review

2023-08-12 10:58 UTC, yarivus reviewed
see some new comments

2023-08-12 10:58 UTC, yarivus commented on components/interop/interop-identity-registry-service-impl/src/main/kotlin/net/corda/interop/identity/cache/impl/InteropIdentityRegistryViewImpl.kt
> +    private val byShortHash = HashMap<ShortHash, InteropIdentity>()
what's the difference ?
Why is one named byShortHash and the other byVirtualNode ?
Can't we have just the version which maps: `HashMap<ShortHash, HashSet<InteropIdentity>>()` ?
The single version can be a private case for that (having a single InteropIdentity in the HashSet).

2023-08-12 10:58 UTC, yarivus commented on components/interop/interop-identity-registry-service-impl/src/main/kotlin/net/corda/interop/identity/cache/impl/InteropIdentityRegistryViewImpl.kt
> +    override fun getIdentitiesByShortHash(): Map<ShortHash, InteropIdentity> =
My prev comment will make these methods 1 method too 
(Let's simplify things)

2023-08-13 18:58 UTC, yarivus reviewed
pending comments

2023-08-14 11:47 UTC, yarivus reviewed
checkpoint review

2023-08-14 11:47 UTC, yarivus commented on components/interop/interop-identity-registry-service-impl/src/main/kotlin/net/corda/interop/identity/cache/impl/InteropIdentityRegistryServiceEventHandler.kt
> +        //configSubscription?.close()
placeholder commented out

2023-08-14 13:41 UTC, yarivus reviewed
checkpoint review

2023-08-14 14:15 UTC, jmacmahonr3 commented on components/interop/interop-identity-registry-service-impl/src/main/kotlin/net/corda/interop/identity/cache/impl/InteropIdentityRegistryViewImpl.kt
> +    private val byShortHash = HashMap<ShortHash, InteropIdentity>()
So Interop Identities have their own short hash. 
InterOp Identities are owned by Virtual Nodes who are referred to by their short hashes. 
So it's get by 'child Identity' vs 'parent Identity'

2023-08-14 14:15 UTC, jmacmahonr3 commented on components/interop/interop-identity-registry-service-impl/src/main/kotlin/net/corda/interop/identity/cache/impl/InteropIdentityRegistryViewImpl.kt
> +    override fun getIdentitiesByShortHash(): Map<ShortHash, InteropIdentity> =
See previous comment

2023-08-14 14:16 UTC, jmacmahonr3 commented on components/interop/interop-identity-registry-service-impl/src/main/kotlin/net/corda/interop/identity/cache/impl/InteropIdentityRegistryServiceEventHandler.kt
> +        //configSubscription?.close()
i'm adding this experimentally as advice from Flow team was we don't/shouldn't need it

2023-08-14 14:40 UTC, yarivus commented on components/interop/interop-identity-registry-service-impl/src/main/kotlin/net/corda/interop/identity/cache/impl/InteropIdentityRegistryViewImpl.kt
> +    private val byShortHash = HashMap<ShortHash, InteropIdentity>()
I still don't follow ... 
Maybe you should rename `byShortHash` and `byVirtualNode` to reflect parent/child relationships.

If not totally equivalent (to parent/child relationships), at the end of day a single map `HashMap<ShortHash, HashSet<InteropIdentity>>()` will work for both ... right ?
In the parent case it will give a HashSet of size 1 ,,,, and in the children a HashSet w/ all the children mapped to that ShortHash input.

2023-08-14 14:40 UTC, yarivus reviewed
checkpoint review

2023-08-14 15:58 UTC, yarivus reviewed
checkpoint review

2023-08-16 18:47 UTC, yarivus reviewed
checkpoint review

2023-08-16 18:47 UTC, yarivus commented on components/flow/flow-service/src/test/kotlin/net/corda/flow/service/FlowServiceTest.kt
> +                //Arguments.of(LifecycleCoordinatorName.forComponent<InteropIdentityRegistryService>())
placeholder comment

2023-08-16 18:47 UTC, yarivus commented on components/flow/flow-service/src/test/kotlin/net/corda/flow/service/FlowServiceTest.kt
> +    //private val interopIdentityRegistryService = mock<InteropIdentityRegistryService>()
placeholder comment

2023-08-17 13:19 UTC, yarivus reviewed
see minor comment (and try to cleanup the rest of the comments)

2023-08-17 13:19 UTC, yarivus commented on components/interop/interop-rest-service-impl/src/main/kotlin/net/corda/interop/rest/impl/v1/InteropRestResourceImpl.kt
> +        if(interopIdentityRegistryService
```suggestion
        if (interopIdentityRegistryService
```

2023-08-18 19:25 UTC, yarivus reviewed
checkpoint review

2023-08-20 21:18 UTC, jmacmahonr3 requested changes

2023-08-20 21:18 UTC, jmacmahonr3 commented on components/interop/interop-identity-write-service-impl/src/main/kotlin/net/corda/interop/identity/write/impl/MembershipInfoProducer.kt
> +        private const val INTEROP_GROUP_ID = "3dfc0aae-be7c-44c2-aa4f-4d0d7145cf08"
@SaurabhR3 this needs to updated to use the appropriate GroupId

2023-08-20 21:18 UTC, jmacmahonr3 commented on components/interop/interop-identity-write-service-impl/src/main/kotlin/net/corda/interop/identity/write/impl/MembershipInfoProducer.kt
> +                    KeyValuePair(MemberInfoExtension.INTEROP_ROLE, "interop"),
@SaurabhR3 Make "interop" a constant. 

Also add INTEROP_ALIAS_MAPPING as a field as this is needed for incoming messages. 

FYI @ac101m the InterOp process should check the INTEROP_ALIAS_MAPPING on incoming messages to find the correct owning vnode.

2023-08-20 21:18 UTC, jmacmahonr3 commented on libs/interop/interop-rest/src/main/kotlin/net/corda/libs/interop/endpoints/v1/types/ExportInteropIdentityRest.kt
> +class ExportInteropIdentityRest {
No action to take here. Marking as resolved.

2023-08-21 11:08 UTC, ac101m reviewed
Whole lot of comments, most of them minor

2023-08-21 11:08 UTC, ac101m commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/application/services/impl/FacadeServiceImpl.kt
> +        val transportLayer = MessagingDispatcher(flowMessaging, jsonMarshallingService,x500Name , groupId)
Code style

2023-08-21 11:08 UTC, ac101m commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/application/services/impl/InteropIdentityLookUpImpl.kt
> +    InteropIdentityLookUp, UsedByFlow, SingletonSerializeAsToken {
Code style, move `) :` to beginning of line, remove space and put inherited classes/interfaces on same line.

2023-08-21 11:08 UTC, ac101m commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/application/services/impl/InteropIdentityLookUpImpl.kt
> +        return InteropIdentityInfoImpl(identityInfo.applicationName,identityInfo.facadeIds,identityInfo.x500Name,identityInfo.groupId)
Code style, spaces following commas.

2023-08-21 11:08 UTC, ac101m commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/application/services/impl/InteropIdentityLookUpImpl.kt
> +        return identityInfo.map { InteropIdentityInfoImpl(it.applicationName, it.facadeIds, it.x500Name,it.groupId) }
code style

2023-08-21 11:08 UTC, ac101m commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/application/services/impl/InteropIdentityLookUpImpl.kt
> +
Remove extra newline

2023-08-21 11:08 UTC, ac101m commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/fiber/FlowFiberExecutionContext.kt
> +    val interopIdentityRegistryView : InteropIdentityRegistryView,
Code style, remove space leading colon.

2023-08-21 11:08 UTC, ac101m commented on components/flow/flow-service/src/test/kotlin/net/corda/flow/service/FlowServiceTest.kt
> +                Arguments.of(LifecycleCoordinatorName.forComponent<FlowExecutor>())//,
Let's get rid of this comment :rofl:

2023-08-21 11:08 UTC, ac101m commented on components/interop/interop-group-policy-read-service-impl/src/main/kotlin/net/corda/interop/group/policy/read/impl/InteropGroupPolicyReadServiceEventHandler.kt
> +            log.info("onNext currentData=${currentData.size} newRecord=${newRecord}" )
Code style, trailing space in log.info parameter list

2023-08-21 11:08 UTC, ac101m commented on components/interop/interop-group-policy-read-service-impl/src/main/kotlin/net/corda/interop/group/policy/read/impl/InteropGroupPolicyReadServiceEventHandler.kt
> +            log.info("onSnapshot=${currentData.size}" )
Trailing space

2023-08-21 11:08 UTC, ac101m commented on components/interop/interop-group-policy-read-service/src/main/kotlin/net/corda/interop/group/policy/read/InteropGroupPolicyReadService.kt
> +    fun getGroupPolicy(groupId: String) : String?
Code style, remove spaces leading semicolons

2023-08-21 11:08 UTC, ac101m commented on components/interop/interop-identity-read-service-impl/src/main/kotlin/net/corda/interop/identity/read/impl/InteropIdentityReadServiceImpl.kt
> +        ::interopIdentityRegistryService
Why is the registry service required in the read service?

2023-08-21 11:08 UTC, ac101m commented on components/interop/interop-identity-registry-service-impl/src/main/kotlin/net/corda/interop/identity/registry/impl/InteropIdentityRegistryServiceEventHandler.kt
> +        //configSubscription = null
This shouldn't be commented out. If the processor is getting told to stop, we need to close the subscription.

2023-08-21 11:08 UTC, ac101m commented on components/interop/interop-identity-registry-service-impl/src/main/kotlin/net/corda/interop/identity/registry/impl/InteropIdentityRegistryViewImpl.kt
> +        identity.facadeIds.forEach{
Code style, space after `forEach`

2023-08-21 11:08 UTC, ac101m commented on components/interop/interop-identity-registry-service-impl/src/main/kotlin/net/corda/interop/identity/registry/impl/InteropIdentityRegistryViewImpl.kt
> +    }
Code style, remove unnecessary space

2023-08-21 11:08 UTC, ac101m commented on components/interop/interop-identity-registry-service-impl/src/main/kotlin/net/corda/interop/identity/registry/impl/InteropIdentityRegistryViewImpl.kt
> +        byFacadeId.forEach{
code style

2023-08-21 11:08 UTC, ac101m commented on components/interop/interop-identity-registry-service-impl/src/main/kotlin/net/corda/interop/identity/registry/impl/InteropIdentityRegistryViewImpl.kt
> +    }
Code style, remove unneeded space

2023-08-21 11:08 UTC, ac101m commented on components/interop/interop-identity-registry-service-impl/src/test/kotlin/net/corda/interop/identity/registry/impl/InteropIdentityRegistryServiceImplTest.kt
> +                FacadeId.of("org.corda.interop/platform/tokens/v2.0")),
Code style, I don't think we need this newline

2023-08-21 11:08 UTC, ac101m commented on components/interop/interop-identity-registry-service-impl/src/test/kotlin/net/corda/interop/identity/registry/impl/InteropIdentityRegistryViewImplTest.kt
> +                FacadeId.of("org.corda.interop/platform/tokens/v2.0")),
Ditto, unnecessary newline

2023-08-21 11:08 UTC, ac101m commented on components/interop/interop-identity-registry-service-impl/src/test/kotlin/net/corda/interop/identity/registry/impl/InteropIdentityRegistryViewImplTest.kt
> +        val facadeMap1 = facadeToIds[facadeId1.toString()] ?: throw NullPointerException("No Facade data found for given FacadeId")
Use `checkNotNull` with lazy message

2023-08-21 11:08 UTC, ac101m commented on components/interop/interop-identity-registry-service-impl/src/test/kotlin/net/corda/interop/identity/registry/impl/InteropIdentityRegistryViewImplTest.kt
> +        val facadeMap2 = facadeToIds[facadeId2.toString()] ?: throw NullPointerException("No Facade data found for given FacadeId")
Use `checkNotNull` with lazy message

2023-08-21 11:08 UTC, ac101m commented on components/interop/interop-identity-write-service-impl/src/main/kotlin/net/corda/interop/identity/write/impl/InteropIdentityWriteServiceImpl.kt
> +    }
We should not be doing a "find and replace" on a json string!
Parse this using `ObjectMapper.readTree()` and operate on json nodes instead.

2023-08-21 11:08 UTC, ac101m commented on components/interop/interop-identity-write-service-impl/src/main/kotlin/net/corda/interop/identity/write/impl/MembershipInfoProducer.kt
> +                    KeyValuePair(MemberInfoExtension.INTEROP_ROLE, "interop"),
So after some reflection, this mechanism doesn't work. In order to fill in these fields on import, we do a virtual node lookup. This won't work if the vnode is on another cluster. Will take care of this either as a part of my current work or create a ticket for it.

2023-08-21 11:08 UTC, ac101m commented on components/interop/interop-rest-service-impl/src/main/kotlin/net/corda/interop/rest/impl/v1/InteropRestResourceImpl.kt
>      //TODO Add correct group policy as part of the import task CORE-10450
Is this TODO still valid?

2023-08-21 11:08 UTC, ac101m commented on components/interop/interop-rest-service-impl/src/main/kotlin/net/corda/interop/rest/impl/v1/InteropRestResourceImpl.kt
> +    }
Make naming of these methods consistent

2023-08-21 11:08 UTC, ac101m commented on components/interop/interop-rest-service-impl/src/main/kotlin/net/corda/interop/rest/impl/v1/InteropRestResourceImpl.kt
> +    )
Use val rather than constructing new list on every call.

2023-08-21 11:08 UTC, ac101m commented on components/interop/interop-service/build.gradle
> +
Remove unneeded space

2023-08-21 11:08 UTC, ac101m commented on components/membership/group-policy-configuration-validation-impl/src/main/kotlin/net/corda/membership/group/policy/validation/impl/InteropGroupPolicyValidatorImpl.kt
> +        } ?: return
Not familiar with this code, but is it sensible to just return on null like this?

2023-08-21 11:08 UTC, ac101m commented on libs/membership/membership-common/src/main/kotlin/net/corda/membership/lib/grouppolicy/GroupPolicy.kt
> +
Unneeded newline

2023-08-21 11:08 UTC, ac101m commented on libs/membership/membership-common/src/main/kotlin/net/corda/membership/lib/grouppolicy/GroupPolicy.kt
> +
Unneeded newline

2023-08-21 11:08 UTC, ac101m commented on libs/membership/membership-common/src/main/kotlin/net/corda/membership/lib/grouppolicy/GroupPolicy.kt
> +
Unneeded newline

2023-08-21 11:08 UTC, ac101m commented on libs/membership/membership-common/src/main/kotlin/net/corda/membership/lib/grouppolicy/GroupPolicy.kt
> +
Unneeded newline

2023-08-21 11:08 UTC, ac101m commented on libs/membership/membership-common/src/main/kotlin/net/corda/membership/lib/grouppolicy/GroupPolicy.kt
> +
Unneeded newline

2023-08-21 11:08 UTC, ac101m commented on libs/membership/membership-common/src/main/kotlin/net/corda/membership/lib/grouppolicy/GroupPolicy.kt
> +
Unneeded newline

2023-08-21 11:08 UTC, ac101m commented on libs/membership/membership-common/src/main/kotlin/net/corda/membership/lib/grouppolicy/GroupPolicy.kt
> +
Unneeded newline

2023-08-21 11:08 UTC, ac101m commented on libs/membership/membership-common/src/main/kotlin/net/corda/membership/lib/grouppolicy/GroupPolicy.kt
> +
Unneeded newline

2023-08-21 11:08 UTC, ac101m commented on libs/membership/membership-common/src/main/kotlin/net/corda/membership/lib/grouppolicy/GroupPolicy.kt
> +
Unneeded newline

2023-08-21 11:08 UTC, ac101m commented on libs/membership/membership-common/src/main/kotlin/net/corda/membership/lib/grouppolicy/GroupPolicy.kt
> +interface InteropGroupPolicy : GroupPolicy
@jmacmahonr3 @SaurabhR3 Is it wise to relax restrictions on the base `GroupPolicy` interface?

2023-08-21 11:08 UTC, ac101m commented on libs/membership/membership-common/src/main/kotlin/net/corda/membership/lib/grouppolicy/GroupPolicyParser.kt
> +    ): InteropGroupPolicy?
Make return value non nullable. Throw an exception instead.

2023-08-21 11:08 UTC, ac101m commented on libs/membership/membership-impl/src/main/kotlin/net/corda/membership/lib/impl/grouppolicy/GroupPolicyParserImpl.kt
> +    override fun parseInteropGroupPolicy(groupPolicy: String): InteropGroupPolicy? {
Ditto, make interop group policy non nullable

2023-08-21 11:08 UTC, ac101m commented on libs/membership/membership-impl/src/main/kotlin/net/corda/membership/lib/impl/grouppolicy/v1/InteropGroupPolicyImpl.kt
> +class InteropGroupPolicyImpl(rootNode: JsonNode) : InteropGroupPolicy {
Code style, remove space between parameter list and colon

2023-08-21 11:08 UTC, ac101m commented on libs/membership/membership-impl/src/main/kotlin/net/corda/membership/lib/impl/grouppolicy/v1/InteropGroupPolicyImpl.kt
> +    internal inner class ProtocolParametersImpl : GroupPolicy.ProtocolParameters {
Code style, unneeded space

2023-08-21 11:08 UTC, ac101m commented on libs/membership/membership-impl/src/main/kotlin/net/corda/membership/lib/impl/grouppolicy/v1/InteropGroupPolicyImpl.kt
> +    internal inner class P2PParametersImpl(rootNode: JsonNode) : GroupPolicy.P2PParameters {
Code style, unneeded space

2023-08-21 11:08 UTC, ac101m commented on libs/membership/membership-impl/src/main/kotlin/net/corda/membership/lib/impl/grouppolicy/v1/InteropGroupPolicyImpl.kt
> +    ) : GroupPolicy.MGMInfo, Map<String, String> by map
Code style, unneeded space

2023-08-21 11:08 UTC, ac101m commented on libs/membership/membership-impl/src/main/kotlin/net/corda/membership/lib/impl/grouppolicy/v1/InteropGroupPolicyImpl.kt
> +    ) : GroupPolicy.CipherSuite, Map<String, String> by map
Code style, unneeded space

2023-08-21 11:08 UTC, ac101m commented on processors/rest-processor/src/integrationTest/resources/swaggerBaseline-v1.json
> +        "description" : "This method returns Json String containing GroupID, Group Policy and my InterOpIdentityInfo.",
"Export a holding identity for import by other virtual nodes."

2023-08-21 11:08 UTC, ac101m commented on processors/rest-processor/src/integrationTest/resources/swaggerBaseline-v1.json
> +          "description" : "ID of the holding identity which interop identity is to be returned.",
Grammatical error here!

2023-08-21 11:08 UTC, ac101m commented on processors/rest-processor/src/integrationTest/resources/swaggerBaseline-v1.json
> +            "description" : "ID of the holding identity which interop identity is to be returned.",
Ditto

2023-08-21 11:08 UTC, ac101m commented on processors/rest-processor/src/integrationTest/resources/swaggerBaseline-v1.json
> +        "description" : "This method imports the interop identity.",
"Import an interop identity into a virtual node."

2023-08-21 11:08 UTC, ac101m commented on processors/rest-processor/src/integrationTest/resources/swaggerBaseline-v1.json
> +          "description" : "ID of the holding identity which interop identity is to be returned.",
Grammar

2023-08-21 11:08 UTC, ac101m commented on processors/rest-processor/src/integrationTest/resources/swaggerBaseline-v1.json
> +            "description" : "ID of the holding identity which interop identity is to be returned.",
Ditto

2023-08-21 11:08 UTC, ac101m commented on processors/rest-processor/src/integrationTest/resources/swaggerBaseline-v1.json
> +                "$ref" : "#/components/schemas/Request"
The schemas just being called "request" and "response" bothers me. Not specific enough for a wide scope like this. Include parent class name in there maybe?

2023-08-21 11:08 UTC, ac101m commented on testing/cpbs/interop-token-demo-workflows/src/main/kotlin/com/r3/corda/demo/interop/tokens/workflows/interop/GetInteropIdentity.kt
> +        try {
Remove one of these newlines

2023-08-21 11:08 UTC, ac101m commented on testing/cpbs/interop-token-demo-workflows/src/main/kotlin/com/r3/corda/demo/interop/tokens/workflows/interop/ReserveTokensFlow.kt
> +            facadeService.getProxy(facadeId, TokensFacade::class.java,interOPIdentity)
Code style, space after comma

2023-08-21 11:08 UTC, ac101m commented on testing/cpbs/test-invocation-cordapp/src/main/kotlin/com/r3/corda/testing/interop/FacadeInvocationFlow.kt
> +
Remove unneeded newlines

2023-08-21 11:59 UTC, yarivus reviewed
folks I think you should pause to do some cleanups very soon ...
This PR is getting very messy

2023-08-21 12:21 UTC, ac101m commented
> folks I think you should pause to do some cleanups very soon ... This PR is getting very messy

The functionality is (in theory) complete. It's just debugging + cleanup from here on out.

2023-08-21 13:54 UTC, jmacmahonr3 commented on processors/rest-processor/src/integrationTest/resources/swaggerBaseline-v1.json
> +                "$ref" : "#/components/schemas/Request"
@julia-filipczak please resolve

2023-08-21 15:49 UTC, yarivus commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/application/services/impl/InteropIdentityLookUpImpl.kt
> +            identityInfo.x500Name, identityInfo.groupId)
```suggestion
        return InteropIdentityInfoImpl(
            identityInfo.applicationName,
            identityInfo.facadeIds,
            identityInfo.x500Name,
            identityInfo.groupId)
```

2023-08-21 15:49 UTC, yarivus reviewed
checkpointing review

2023-08-21 17:28 UTC, ac101m reviewed
A few methods still named cache rather than registry

2023-08-21 17:28 UTC, ac101m commented on components/interop/interop-identity-registry-service-impl/src/main/kotlin/net/corda/interop/identity/processor/InteropIdentityProcessor.kt
> +    private fun updateCacheEntry(key: RecordKey, oldEntry: InteropIdentity, newEntry: InteropIdentity) {
Should update this method to `updateRegistryEntry`

2023-08-21 17:28 UTC, ac101m commented on components/interop/interop-identity-registry-service-impl/src/main/kotlin/net/corda/interop/identity/processor/InteropIdentityProcessor.kt
> +    private fun insertCacheEntry(key: RecordKey, newEntry: InteropIdentity) {
Ditto

2023-08-21 17:28 UTC, ac101m commented on components/interop/interop-identity-registry-service-impl/src/main/kotlin/net/corda/interop/identity/processor/InteropIdentityProcessor.kt
> +    private fun removeCacheEntry(key: RecordKey, oldEntry: InteropIdentity) {
Ditto

2023-08-22 10:29 UTC, yarivus reviewed
some comments pending

2023-08-22 10:29 UTC, yarivus commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/impl/FlowGlobalPostProcessorImpl.kt
> +        )
no need to create the HoldingIdentity - you only need the shortHash

2023-08-22 13:36 UTC, yarivus reviewed
pending comments

2023-08-22 16:20 UTC, ac101m commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/impl/FlowGlobalPostProcessorImpl.kt
> +        )
Fixed

2023-08-22 18:59 UTC, yarivus reviewed
pending comments

2023-08-23 10:17 UTC, ac101m commented on components/interop/interop-rest-service-impl/src/main/kotlin/net/corda/interop/rest/impl/v1/InteropRestResourceImpl.kt
>      //TODO Add correct group policy as part of the import task CORE-10450
@SaurabhR3 Do you know if this is still valid?

2023-08-23 10:23 UTC, ac101m commented on components/interop/interop-rest-service-impl/src/main/kotlin/net/corda/interop/rest/impl/v1/InteropRestResourceImpl.kt
> +    )
Will leave this alone as it is a stand-in for an as-of-yet unimplemented process

2023-08-23 10:30 UTC, ac101m commented on components/membership/group-policy-configuration-validation-impl/src/main/kotlin/net/corda/membership/group/policy/validation/impl/InteropGroupPolicyValidatorImpl.kt
> +        } ?: return
Just looked into this, the return value from `parseInteropGroupPolicy()` isn't nullable so this isn't necessary. Removed.

2023-08-23 10:34 UTC, ac101m commented on libs/membership/membership-common/src/main/kotlin/net/corda/membership/lib/grouppolicy/GroupPolicyParser.kt
> +    ): InteropGroupPolicy?
Turns out this isn't actually nullable!

2023-08-23 10:41 UTC, ac101m commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/application/services/impl/InteropIdentityLookUpImpl.kt
> +            identityInfo.x500Name, identityInfo.groupId)
Done

2023-08-23 10:54 UTC, szymonsztuka requested changes

2023-08-23 10:54 UTC, szymonsztuka commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/application/services/impl/FacadeServiceImpl.kt
> +    override fun <T : Any?> getProxy(facadeId: String?, expectedType: Class<T>?, interOpIdentity: InterOpIdentityInfo): T {
As API is in Java `InterOpIdentityInfo` should  to be a nullable type `InterOpIdentityInfo?`, change `interOpIdentity: InterOpIdentityInfo` -> `interOpIdentity: InterOpIdentityInfo?` + deal if nullability in the method as before

2023-08-23 10:54 UTC, szymonsztuka commented on libs/membership/membership-common/src/main/kotlin/net/corda/membership/lib/grouppolicy/GroupPolicy.kt
> -        @get:Throws(BadGroupPolicyException::class)
I think we should not modify the existing interface (unless we add something new optional), as we changing semantics of MGM Group policy.

2023-08-23 10:54 UTC, szymonsztuka commented on libs/membership/membership-impl/src/main/kotlin/net/corda/membership/lib/impl/grouppolicy/v1/InteropGroupPolicyImpl.kt
> +class InteropGroupPolicyImpl(rootNode: JsonNode) : InteropGroupPolicy {
This class is about 70% of copy of `MemberGroupPolicyImpl` - it contains the same code expect some removals, I think this is unmanageable solution, can we use inheritance (override), aggregation or anything to remove code duplication or is this a temporary solution?

2023-08-23 11:20 UTC, yarivus reviewed
pending comments

2023-08-23 11:57 UTC, SaurabhR3 requested changes

2023-08-23 11:57 UTC, SaurabhR3 commented on components/interop/interop-service/src/integrationTest/kotlin/net/corda/interop/service/integration/InteropServiceIntegrationTest.kt
>      fun `verify interop processor sends messages to flow mapper event topic and p2p out topic`() {
@szymonsztuka @jmacmahonr3 are we going to use/maintain this test now onwards ?

2023-08-23 11:57 UTC, SaurabhR3 commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/application/services/impl/FacadeServiceImpl.kt
> +    override fun <T : Any?> getProxy(facadeId: String?, expectedType: Class<T>?, interOpIdentity: InterOpIdentityInfo): T {
Done

2023-08-23 12:21 UTC, SaurabhR3 commented on libs/membership/membership-impl/src/main/kotlin/net/corda/membership/lib/impl/grouppolicy/v1/InteropGroupPolicyImpl.kt
> +class InteropGroupPolicyImpl(rootNode: JsonNode) : InteropGroupPolicy {
I agree with you most of the code was pretty much copy as it has dependency on GroupPolicy interface. The idea when I did this change was to evaluate, how can we use the member group policy for interop. So I kept it most of the similar with other `MemberGroupPolicyImpl`. I am sure we need to revisit this code in next milestone.

2023-08-23 13:01 UTC, szymonsztuka commented on libs/membership/membership-impl/src/main/kotlin/net/corda/membership/lib/impl/grouppolicy/v1/InteropGroupPolicyImpl.kt
> +class InteropGroupPolicyImpl(rootNode: JsonNode) : InteropGroupPolicy {
Ok, I suppose we have a ticket for this. Anyway at any time we risk this code (logic which we copied from them) is not in sync if other team make some changes, and we will not know about it, therefore I think this should be addressed this ASAP.

2023-08-23 13:03 UTC, szymonsztuka commented on components/interop/interop-service/src/integrationTest/kotlin/net/corda/interop/service/integration/InteropServiceIntegrationTest.kt
>      fun `verify interop processor sends messages to flow mapper event topic and p2p out topic`() {
I think we should keep maintaining this test, this was commented out to make the branch green (and check other things don't fail).

2023-08-23 13:23 UTC, ac101m commented on components/interop/interop-identity-registry-service-impl/src/main/kotlin/net/corda/interop/identity/cache/impl/InteropIdentityRegistryViewImpl.kt
> +    private val byShortHash = HashMap<ShortHash, InteropIdentity>()
I've renamed these to `byShortHash` and `byVirtualNodeShortHash`

2023-08-23 13:28 UTC, ac101m commented on libs/membership/membership-common/src/main/kotlin/net/corda/membership/lib/grouppolicy/GroupPolicy.kt
> +interface InteropGroupPolicy : GroupPolicy
I think the consensus is that this is a problem and we need to fix it. We have to restore these annotations and deal with the fallout in our own code ourselves.

2023-08-23 13:29 UTC, ac101m commented on libs/membership/membership-common/src/main/kotlin/net/corda/membership/lib/grouppolicy/GroupPolicy.kt
> -        @get:Throws(BadGroupPolicyException::class)
@SaurabhR3 What was the reason this change was made?

2023-08-23 13:52 UTC, yarivus reviewed
pending comments (thx for cleaning up @ac101m )

2023-08-23 19:37 UTC, yarivus reviewed
pending comments

2023-08-24 07:49 UTC, SaurabhR3 commented on libs/membership/membership-common/src/main/kotlin/net/corda/membership/lib/grouppolicy/GroupPolicy.kt
> -        @get:Throws(BadGroupPolicyException::class)
@charlieR3 @szymonsztuka @ac101m @jmacmahonr3 
The group policy for interop does not need most of the fields in member/mgm group policy. So we thought of creating new group policy and its parser for interop. But the link manager is very tightly coupled with member/ mgm group policy and its parser. If we create new group policy for interop then we need to make more changes in link manager. 

If we make use of existing group policy interface then we may not need to do additional changes in link manager. 
As part of this change, I have relaxed the `BadGroupPolicyException` annotations on GroupPolicy interface and created new implementation as `InteropGroupPolicy`. 

In order to verify that I am not breaking any existing change, I have checked that we have an appropriate mandatory checks in `MemberGroupPolicyImpl ` and `MGMGroupPolicyImpl ` for relaxed fields.

2023-08-24 07:56 UTC, SaurabhR3 commented on libs/membership/membership-common/src/main/kotlin/net/corda/membership/lib/grouppolicy/GroupPolicy.kt
> +interface InteropGroupPolicy : GroupPolicy
@ac101m I have tagged you in other comment for the query related to this change.

2023-08-24 08:43 UTC, jmacmahonr3 commented on components/interop/interop-service/src/integrationTest/kotlin/net/corda/interop/service/integration/InteropServiceIntegrationTest.kt
>      fun `verify interop processor sends messages to flow mapper event topic and p2p out topic`() {
Yes, there is a ticket dedicated to unblocking and making this test green

2023-08-24 08:45 UTC, jmacmahonr3 commented on libs/membership/membership-common/src/main/kotlin/net/corda/membership/lib/grouppolicy/GroupPolicy.kt
> -        @get:Throws(BadGroupPolicyException::class)
Lets discuss after standup

2023-08-24 09:01 UTC, charlieR3 commented on libs/membership/membership-common/src/main/kotlin/net/corda/membership/lib/grouppolicy/GroupPolicy.kt
> -        @get:Throws(BadGroupPolicyException::class)
Can you elaborate on what `we have an appropriate mandatory checks in MemberGroupPolicyImpl and MGMGroupPolicyImpl for relaxed fields.` involved? I can't see those two files changing in this PR so I'm wondering do they no longer throw `BadGroupPolicyException` (i.e. were they changed in another PR?)

2023-08-24 09:03 UTC, szymonsztuka commented on libs/membership/membership-common/src/main/kotlin/net/corda/membership/lib/grouppolicy/GroupPolicy.kt
>          val tlsPki: TlsPkiMode
I think we removed several `@get:Throws(BadGroupPolicyException::class)`  for fields used (or will be used) by Interop Group, mainly relates to sesssions.

2023-08-24 09:57 UTC, SaurabhR3 commented on libs/membership/membership-common/src/main/kotlin/net/corda/membership/lib/grouppolicy/GroupPolicy.kt
> -        @get:Throws(BadGroupPolicyException::class)
No, The checks are already in place there, if we see class `MemberGroupPolicyImpl` , it has `override val fileFormatVersion = rootNode.getMandatoryInt(FILE_FORMAT_VERSION)` 
So in order to construct the `fileFormatVersion` it has the `getMandatoryInt()` check and which internally throws `BadGroupPolicyException` if value is not present. Likewise all the fields have this check at implementation level.  

If I am not wrong, the annotations at interface level are bit duplication in this case.

2023-08-24 15:48 UTC, ac101m commented on components/interop/interop-identity-registry-service-impl/src/main/kotlin/net/corda/interop/identity/cache/impl/InteropIdentityRegistryViewImpl.kt
> +    private val byShortHash = HashMap<ShortHash, InteropIdentity>()
I think james' explanation above was a little confusing. `InteropIdentity` objects contain both their own short hash and the short hash of the owning virtual node. These two maps are just indexes that allow lookup based on those fields. Marking as resolved @yariv feel free to revive the conversation if you think this needs more work.

2023-08-24 15:54 UTC, ac101m commented on testing/cpbs/test-invocation-cordapp/src/main/kotlin/com/r3/corda/testing/interop/FacadeInvocationFlow.kt
>          log.info("AliasMemberInfo for $alias  : $aliasMember")
Updated!

2023-08-24 16:08 UTC, ac101m commented on components/interop/interop-group-policy-read-service/src/main/kotlin/net/corda/interop/group/policy/read/InteropGroupPolicyReadService.kt
> +    fun getGroupPolicy(groupId: String) : String?
We now have a ticket for replacing UUID strings with UUID objects, closing this comment.

2023-08-24 16:17 UTC, yarivus reviewed
pending comments

2023-08-24 16:28 UTC, ac101m commented on libs/membership/membership-common/src/main/kotlin/net/corda/membership/lib/grouppolicy/GroupPolicy.kt
> -        @get:Throws(BadGroupPolicyException::class)
This has been pushed out into a separate ticket and will be handled as a separate PR. Marking as resolved.

2023-08-24 16:28 UTC, ac101m commented on components/interop/interop-service/src/integrationTest/kotlin/net/corda/interop/service/integration/InteropServiceIntegrationTest.kt
>      fun `verify interop processor sends messages to flow mapper event topic and p2p out topic`() {
Marking as resolved as separate ticket covers this

2023-08-24 16:32 UTC, ac101m commented on components/interop/interop-rest-service-impl/src/main/kotlin/net/corda/interop/rest/impl/v1/InteropRestResourceImpl.kt
>      //TODO Add correct group policy as part of the import task CORE-10450
Looks like this is done, resolving

2023-08-24 17:09 UTC, ac101m commented on processors/rest-processor/src/integrationTest/resources/swaggerBaseline-v1.json
> +                "$ref" : "#/components/schemas/Request"
Resolved

2023-08-24 18:04 UTC, ac101m commented on libs/membership/membership-impl/src/main/kotlin/net/corda/membership/lib/impl/grouppolicy/v1/InteropGroupPolicyImpl.kt
> +class InteropGroupPolicyImpl(rootNode: JsonNode) : InteropGroupPolicy {
Marking as resolved as we have a separate task for this now

2023-08-24 18:04 UTC, ac101m commented on libs/membership/membership-common/src/main/kotlin/net/corda/membership/lib/grouppolicy/GroupPolicy.kt
>          val tlsPki: TlsPkiMode
Ditto, we've got a ticket for group policy related tasks now!

2023-08-25 09:54 UTC, szymonsztuka commented on libs/membership/membership-common/src/main/kotlin/net/corda/membership/lib/grouppolicy/GroupPolicy.kt
>          val tlsPki: TlsPkiMode
but we should not remove these checks here, as even currently we do use tlsPki field and all others from p2p session, if our "readers" don't validate them then it already wrong at this point

2023-08-25 10:39 UTC, ac101m reviewed
A few final comments, then I think we're good to go.

2023-08-25 10:39 UTC, ac101m commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/application/services/impl/InteropIdentityLookUpImpl.kt
> +class InteropIdentityLookUpImpl @Activate constructor(
Real trivial/pedantic thing, but "lookup" is one word in this context, maybe decapitilise "Up"

2023-08-25 10:39 UTC, ac101m commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/application/services/impl/InteropIdentityLookUpImpl.kt
> +    ) : InteropIdentityLookUp, UsedByFlow, SingletonSerializeAsToken {
Code style, line shouldn't be tabbed in

2023-08-25 10:39 UTC, ac101m commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/application/services/impl/InteropIdentityLookUpImpl.kt
> +        val identityInfo = getInteropRegistry().getIdentitiesByFacadeId()[facadeId.toString()]  ?: return emptyList()
Code style, two spaces before the elvis operator

2023-08-25 10:39 UTC, ac101m commented on libs/interop/interop-rest/src/test/kotlin/net/corda/libs/interop/endpoints/v1/InteropJsonToDataClassesTest.kt
> +"""
Clean up indentation and use `trimIndent()`

2023-08-25 10:39 UTC, ac101m commented on libs/interop/interop-rest/src/test/kotlin/net/corda/libs/interop/endpoints/v1/InteropJsonToDataClassesTest.kt
> +        )
Ditto, we can probably use `trimIndent()` and multi-line strings here too.

2023-08-25 10:39 UTC, ac101m commented on testing/cpbs/interop-token-demo-workflows/src/main/kotlin/com/r3/corda/demo/interop/tokens/workflows/interop/GetInteropIdentity.kt
> +                ?: throw NullPointerException("Could not find Interop Identity for given name ${flowArgs.applicationName}")
Use `checkNotNull` or `requireNotNull`

2023-08-25 10:41 UTC, julia-filipczak commented on components/flow/flow-service/src/integrationTest/kotlin/net/corda/flow/testing/fakes/FakeInteropIdentityRegistryService.kt
> +            TODO("Not yet implemented")
Should there be a ticket number associated with all these TODOs?

2023-08-25 10:41 UTC, julia-filipczak commented on components/interop/interop-identity-registry-service-impl/src/main/kotlin/net/corda/interop/identity/registry/impl/InteropIdentityRegistryServiceEventHandler.kt
> +        //configSubscription = null
Should this be uncommented before merging?

2023-08-25 10:41 UTC, julia-filipczak commented on components/interop/interop-identity-registry-service/src/main/kotlin/net/corda/interop/identity/registry/InteropIdentityRegistryView.kt
> +     * Get identities within the view as a map with the FacadeId as Key and a set of InterOpIdentities that implement
Very minor but `Key` could be changed to lowercase here

2023-08-25 10:41 UTC, julia-filipczak commented on libs/membership/membership-common/src/main/kotlin/net/corda/membership/lib/grouppolicy/GroupPolicyParser.kt
> +     * Parses a interop GroupPolicy from [String] to [GroupPolicy].
Minor - `an` interop group policy

2023-08-25 10:41 UTC, julia-filipczak commented on libs/membership/membership-impl/src/main/kotlin/net/corda/membership/lib/impl/grouppolicy/GroupPolicyParserImpl.kt
> +                    logger.error("$FAILED_PARSING Caused by: ${e.message}")
Nothing major but perhaps it would be useful to change the error message slightly, `"$FAILED_PARSING Caused by: ${e.message}"` is used 3 times across this file, I remember when debugging I had to number them to figure out which method it was coming from.

2023-08-25 10:41 UTC, julia-filipczak commented on testing/cpbs/interop-token-demo-workflows/src/main/kotlin/com/r3/corda/demo/interop/tokens/workflows/interop/SimpleReserveTokensFlowV3.kt
>          val alias = MemberX500Name.parse(getArgument(args, "alias"))
I thought we were moving away from using the term `alias`?

2023-08-25 10:41 UTC, julia-filipczak commented on testing/cpbs/interop-token-demo-workflows/src/main/kotlin/com/r3/corda/demo/interop/tokens/workflows/interop/SwapResponderSubFlow.kt
> +        require(myInteropInfo != null) { "Cant get InteropIdentityInfo for ${applicationName}." }
`Cant` -> `Can't`

2023-08-25 10:42 UTC, SaurabhR3 requested changes

2023-08-25 10:42 UTC, SaurabhR3 commented on components/interop/interop-identity-registry-service-impl/src/main/kotlin/net/corda/interop/identity/registry/impl/InteropIdentityRegistryServiceEventHandler.kt
> +        //configurationReadService.start()
If not required better to remove it

2023-08-25 10:42 UTC, SaurabhR3 commented on components/flow/flow-service/build.gradle
unnecessary new line

2023-08-25 10:42 UTC, SaurabhR3 commented on components/flow/flow-service/build.gradle
> +
unnecessary new line

2023-08-25 10:42 UTC, SaurabhR3 commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/impl/FlowGlobalPostProcessorImpl.kt
> +            log.warn("Interop counterparty '${counterparty}' does not exist!")
shouldn't it be logged as an error?

2023-08-25 10:49 UTC, ac101m commented on components/flow/flow-service/src/integrationTest/kotlin/net/corda/flow/testing/fakes/FakeInteropIdentityRegistryService.kt
> +            TODO("Not yet implemented")
Not in this case I don't think! This is a mock implementation, I imagine this method is never called by the tests and if it is, it's mocked using mockito. Also there are other mocked "fake" classes around the place with similar TODO statements in them.

2023-08-25 10:49 UTC, SaurabhR3 commented on components/flow/flow-service/src/integrationTest/kotlin/net/corda/flow/testing/fakes/FakeInteropIdentityRegistryService.kt
> +            TODO("Not yet implemented")
This is fake implementation so as and when required these methods can be implemented. No ticket required for this.

2023-08-25 10:50 UTC, ac101m commented on testing/cpbs/interop-token-demo-workflows/src/main/kotlin/com/r3/corda/demo/interop/tokens/workflows/interop/SimpleReserveTokensFlowV3.kt
>          val alias = MemberX500Name.parse(getArgument(args, "alias"))
Yeah, looks like I missed this one, will take care of it

2023-08-25 10:56 UTC, SaurabhR3 commented on libs/membership/membership-common/src/main/kotlin/net/corda/membership/lib/grouppolicy/GroupPolicy.kt
>          val tlsPki: TlsPkiMode
@szymonsztuka If we remove this check now, this will impact the registration process, as we parse the group policy content in rest api.
We need keep it for now and I will take care as a part of the new ticket.

2023-08-25 11:34 UTC, szymonsztuka commented on libs/membership/membership-common/src/main/kotlin/net/corda/membership/lib/grouppolicy/GroupPolicy.kt
>          val tlsPki: TlsPkiMode
We do provide all those files (below) as a part of REST request:
```
  val sessionTrustRoots: List<String>,
    val tlsTrustRoots: List<String>,
    val sessionPki: String,
    val tlsPki: String,
    val tlsVersion: String,
    val protocolMode: String,
    val tlsType: String
```
see data classes used for parameters of REST method  `fun createInterOpIdentity`.
+ data used in reg-pack test (InitialGroupPolicy.json).

You have removed the validation of those fields (why?), This is an arbitrary decision, we need to validate these fields and have them as we they were part of interop-group policy even before. We should not "break" unnecessary the existing behavior (these removed annotation, especially not controlled by us) just to "fix" it later. So why alter it in the first place in order to undo this next?

2023-08-25 11:47 UTC, SaurabhR3 commented on components/flow/flow-service/src/integrationTest/kotlin/net/corda/flow/testing/fakes/FakeInteropIdentityRegistryService.kt
> +            TODO("Not yet implemented")
@julia-filipczak Hope you are happy and we can resolve this.

2023-08-25 11:59 UTC, SaurabhR3 commented on libs/membership/membership-common/src/main/kotlin/net/corda/membership/lib/grouppolicy/GroupPolicy.kt
>          val tlsPki: TlsPkiMode
Okay, so removed constraints for fields within `P2pParameters` can be revert now.

2023-08-25 12:08 UTC, ac101m commented on libs/membership/membership-impl/src/main/kotlin/net/corda/membership/lib/impl/grouppolicy/GroupPolicyParserImpl.kt
> +                    logger.error("$FAILED_PARSING Caused by: ${e.message}")
Looking at this, the logic is actually incorrect, we shouldn't be logging and throwing

2023-08-25 12:14 UTC, szymonsztuka requested changes

2023-08-25 12:14 UTC, szymonsztuka commented on components/interop/interop-rest-service-impl/src/main/kotlin/net/corda/interop/rest/impl/v1/InteropRestResourceImpl.kt
> +        interopGroupPolicyValidator.validateGroupPolicy(json)
@SaurabhR3 , @julia-filipczak , @ac101m, I think there is  “unsynchronised” way of naddling a group policy (especially p2p parameters) across layers which can be shows in this REST method:

1.	REST endpoint validates a group policy file implicitly by imposing a data class with non nullable fields.

 ```
 override fun createInterOpIdentity(
 createInteropIdentityRestRequest: CreateInteropIdentityRest.Request,
```

At that point we have strongly typed object - aka it's validated.

2. Then we change it back to a string to pass it for a validation to a minimal group policy validator:

```
val json = mapper.writeValueAsString(createInteropIdentityRestRequest.groupPolicy)
interopGroupPolicyValidator.validateGroupPolicy(json
...
```

This validator is already incompatible (more relaxed) than the implicit REST validation already performed

3. Then we pass the string of a group policy to a service to publish to Kafka queue:
```
        val interopGroupId = interopIdentityWriteService.publishGroupPolicy(
            groupIdField,
            json
        )
```

The service doesn’t do any validation (explicit or implicit) internally - here is more or less fine but in general
the service doesn't have any defensive mechanism (will publish any string it).

We have several potential solution to fix this:
**Solution a)**
 - improve validation in `interopGroupPolicyValidator`  to match what is already implicitly validated by 1 (REST)
 - change parameter in method of `interopIdentityWriteService` to use strongly typed data class (so it knows that data is "validated")

**Solution b)** 
- Remove implicit REST endpoint validation by changing signature of group policy data to String
- improve validation `interopGroupPolicyValidator` to do full p2p params validation, the service should probably also change string to strongly typed data classes
- change parameter in `interopIdentityWriteService` to use strongly typed data class (so it knows that data is "validated")

**Solution c)** 
  - (same as in b) Remove implicit REST endpoint validation by changing signature of group policy data to String
  - (same as in a) improve validation in `interopGroupPolicyValidator` to do full p2p validation
  - preserve unguarded method  `interopIdentityWriteService.publishGroupPolicy` taking just a string

**Solution d)**
-  same as in b) Remove implicit REST endpoint validation by changing signature of group policy data to String
-  REST does not invoke `interopGroupPolicyValidator` service, validation is moved inside `interopIdentityWriteService.publishGroupPolicy`
- (as in other solutions) improve validation of the service so it does full p2p params validation 
- `interopIdentityWriteService` takes group policy as string however internally validated it

2023-08-25 12:22 UTC, ac101m reviewed
A few additional comments

2023-08-25 12:22 UTC, ac101m commented on libs/membership/membership-impl/src/main/kotlin/net/corda/membership/lib/impl/grouppolicy/GroupPolicyParserImpl.kt
> +                    throw BadGroupPolicyException(FAILED_PARSING, e)
Don't log and throw.
Doing this causes exceptions to be logged multiple times.

2023-08-25 12:22 UTC, ac101m commented on libs/membership/membership-impl/src/main/kotlin/net/corda/membership/lib/impl/grouppolicy/GroupPolicyParserImpl.kt
> +                throw BadGroupPolicyException(EMPTY_GROUP_POLICY)
Ditto, don't log and throw

2023-08-25 12:30 UTC, SaurabhR3 commented on components/interop/interop-rest-service-impl/src/main/kotlin/net/corda/interop/rest/impl/v1/InteropRestResourceImpl.kt
> +        interopGroupPolicyValidator.validateGroupPolicy(json)
@szymonsztuka can we please have a new ticket for this improvement as it is not the burning?

2023-08-25 12:35 UTC, SaurabhR3 commented on libs/membership/membership-impl/src/main/kotlin/net/corda/membership/lib/impl/grouppolicy/GroupPolicyParserImpl.kt
> +                    logger.error("$FAILED_PARSING Caused by: ${e.message}")
@ac101m Right now this method is consumed in REST API, I think it important to throw exceptions here, because we don't want to accept the malformed group policy.

2023-08-25 12:37 UTC, jmacmahonr3 commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/application/services/impl/InteropIdentityLookUpImpl.kt
> +class InteropIdentityLookUpImpl @Activate constructor(
https://r3-cev.atlassian.net/browse/CORE-16659 I've made a ticket for this

2023-08-25 12:40 UTC, jmacmahonr3 commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/impl/FlowGlobalPostProcessorImpl.kt
> +            log.warn("Interop counterparty '${counterparty}' does not exist!")
@ac101m ?

2023-08-25 12:42 UTC, jmacmahonr3 commented on libs/membership/membership-impl/src/main/kotlin/net/corda/membership/lib/impl/grouppolicy/GroupPolicyParserImpl.kt
> +                    throw BadGroupPolicyException(FAILED_PARSING, e)
@ac101m can you create a ticket for this ?

2023-08-25 12:43 UTC, ac101m commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/impl/FlowGlobalPostProcessorImpl.kt
> +            log.warn("Interop counterparty '${counterparty}' does not exist!")
No, this isn't an error case at this stage. This was added temporarily as the logging statements further down are at debug log level and so don't show up in kubernetes logs by default. I left it in because I felt it may be useful and save someone some time in the future. Should be either left as-is or removed entirely.

2023-08-25 12:57 UTC, SaurabhR3 commented on libs/membership/membership-impl/src/main/kotlin/net/corda/membership/lib/impl/grouppolicy/GroupPolicyParserImpl.kt
> +                    throw BadGroupPolicyException(FAILED_PARSING, e)
I think this is required as you can see the exception in flow worker and rest api log, and that is good I believe.

2023-08-25 13:03 UTC, jmacmahonr3 commented on libs/membership/membership-impl/src/main/kotlin/net/corda/membership/lib/impl/grouppolicy/GroupPolicyParserImpl.kt
> +                throw BadGroupPolicyException(EMPTY_GROUP_POLICY)
This class will be reverted as part of https://r3-cev.atlassian.net/browse/CORE-16623

2023-08-25 13:03 UTC, jmacmahonr3 commented on libs/membership/membership-impl/src/main/kotlin/net/corda/membership/lib/impl/grouppolicy/GroupPolicyParserImpl.kt
> +                    throw BadGroupPolicyException(FAILED_PARSING, e)
This will be resolved as part of https://r3-cev.atlassian.net/browse/CORE-16623

2023-08-25 13:08 UTC, ac101m commented on components/interop/interop-identity-registry-service-impl/src/main/kotlin/net/corda/interop/identity/registry/impl/InteropIdentityRegistryServiceEventHandler.kt
> +        //configurationReadService.start()
Removed

2023-08-25 13:08 UTC, jmacmahonr3 commented on components/interop/interop-rest-service-impl/src/main/kotlin/net/corda/interop/rest/impl/v1/InteropRestResourceImpl.kt
> +        interopGroupPolicyValidator.validateGroupPolicy(json)
Converting this to a ticket https://r3-cev.atlassian.net/browse/CORE-16661

2023-08-25 13:09 UTC, jmacmahonr3 commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/application/services/impl/InteropIdentityLookUpImpl.kt
> +class InteropIdentityLookUpImpl @Activate constructor(
Marking as resolved

2023-08-25 13:09 UTC, LWogan commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/impl/FlowGlobalPostProcessorImpl.kt
> +            log.warn("Interop counterparty '${counterparty}' does not exist!")
error logs are for fatal/unrecoverable worker things only.

https://r3-cev.atlassian.net/wiki/spaces/CB/pages/4169859082/C5+Logging+goals

2023-08-25 13:10 UTC, szymonsztuka commented on components/interop/interop-rest-service-impl/src/main/kotlin/net/corda/interop/rest/impl/v1/InteropRestResourceImpl.kt
> +        interopGroupPolicyValidator.validateGroupPolicy(json)
I would prefer to fix this sooner rather than later, but I will not block the PR if it's done as part of next work item.

2023-08-25 13:13 UTC, jmacmahonr3 commented on libs/membership/membership-common/src/main/kotlin/net/corda/membership/lib/grouppolicy/GroupPolicy.kt
>          val tlsPki: TlsPkiMode
This solution will be replaced according to the following ticket https://r3-cev.atlassian.net/browse/CORE-16623
This will ensure the original checks are restored.

2023-08-25 13:14 UTC, jmacmahonr3 commented on testing/cpbs/interop-token-demo-workflows/src/main/kotlin/com/r3/corda/demo/interop/tokens/workflows/interop/GetInteropIdentity.kt
> +                ?: throw NullPointerException("Could not find Interop Identity for given name ${flowArgs.applicationName}")
@julia-filipczak please acknowledge

2023-08-25 13:14 UTC, jmacmahonr3 commented on libs/interop/interop-rest/src/test/kotlin/net/corda/libs/interop/endpoints/v1/InteropJsonToDataClassesTest.kt
> +        )
@julia-filipczak please acknowledge

2023-08-25 13:15 UTC, jmacmahonr3 commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/impl/FlowGlobalPostProcessorImpl.kt
> +            log.warn("Interop counterparty '${counterparty}' does not exist!")
Marking as resolved. 
Thanks Lorcan

2023-08-25 13:15 UTC, jmacmahonr3 commented on components/interop/interop-rest-service-impl/src/main/kotlin/net/corda/interop/rest/impl/v1/InteropRestResourceImpl.kt
> +        interopGroupPolicyValidator.validateGroupPolicy(json)
I'll make the ticket high priority and it can be picked up on Tuesday

2023-08-25 13:16 UTC, SaurabhR3 commented on libs/interop/interop-rest/src/test/kotlin/net/corda/libs/interop/endpoints/v1/InteropJsonToDataClassesTest.kt
> +"""
Done

2023-08-25 13:20 UTC, SaurabhR3 commented on libs/interop/interop-rest/src/test/kotlin/net/corda/libs/interop/endpoints/v1/InteropJsonToDataClassesTest.kt
> +        )
I think its more readable right now as it is expected list of certs.

2023-08-25 13:23 UTC, ac101m commented on libs/membership/membership-impl/src/main/kotlin/net/corda/membership/lib/impl/grouppolicy/GroupPolicyParserImpl.kt
> +                    throw BadGroupPolicyException(FAILED_PARSING, e)
@SaurabhR3 The exception you throw will eventually be caught somewhere else and logged there, causing the same exception to be logged twice in two different places. For this reason, when catch an exception, you either handle and log, or you wrap and rethrow, but you don't do both.

2023-08-25 13:24 UTC, szymonsztuka commented on components/interop/interop-rest-service-impl/src/main/kotlin/net/corda/interop/rest/impl/v1/InteropRestResourceImpl.kt
> +        interopGroupPolicyValidator.validateGroupPolicy(json)
tracked by https://r3-cev.atlassian.net/browse/CORE-16661 and as I understand also for other tickets to fix group policy parsing

2023-08-25 13:26 UTC, ac101m commented on libs/membership/membership-impl/src/main/kotlin/net/corda/membership/lib/impl/grouppolicy/GroupPolicyParserImpl.kt
> +                    throw BadGroupPolicyException(FAILED_PARSING, e)
Resolving as this won't be sticking around anyway

2023-08-25 13:33 UTC, julia-filipczak commented on libs/interop/interop-rest/src/test/kotlin/net/corda/libs/interop/endpoints/v1/InteropJsonToDataClassesTest.kt
> +        )
I agree with Saurabh on this I think

2023-08-25 13:33 UTC, SaurabhR3 approved these changes

2023-08-25 13:38 UTC, szymonsztuka requested changes

2023-08-25 13:38 UTC, szymonsztuka commented on libs/membership/membership-common/src/main/kotlin/net/corda/membership/lib/grouppolicy/GroupPolicy.kt
> -    @get:Throws(BadGroupPolicyException::class)
This field is nullable anyway, so I would revert removing this "throws", I mean this doesn't impact our code, if MGM has illogical annotation it's up to them.

2023-08-25 13:38 UTC, szymonsztuka commented on libs/membership/membership-common/src/main/kotlin/net/corda/membership/lib/grouppolicy/GroupPolicy.kt
> -        @get:Throws(BadGroupPolicyException::class)
This field is nullable anyway, so I would revert removing this "throws", this doesn't impact our code, if MGM has an illogical annotation it's up to them

2023-08-25 13:56 UTC, szymonsztuka commented on libs/membership/membership-common/src/main/kotlin/net/corda/membership/lib/grouppolicy/GroupPolicy.kt
>          val tlsPki: TlsPkiMode
this commit has adressed my comment https://github.com/corda/corda-runtime-os/pull/4221/commits/07a2195b9c61c10a629fd5174f7e1b4652a9b20f but now there is another commit to revert former commit https://github.com/corda/corda-runtime-os/pull/4221/commits/e27ba96274fa3239543fe65a6ca5eab82731e232
so this is back to unresolved.

2023-08-25 14:17 UTC, LWogan reviewed
Flow changes look ok. 

It would be nice to see more kdocs in general as a practice. Its helpful for future maintainers and debuggers, especially for the flow team. We end up as the first responders to most bugs because QA run flows and we're the flow team. Anything to help us understand whats going on and follow the code is great.

2023-08-25 14:17 UTC, LWogan commented on components/interop/interop-group-policy-read-service/src/main/kotlin/net/corda/interop/group/policy/read/InteropGroupPolicyReadService.kt
> +interface InteropGroupPolicyReadService: Lifecycle {
no kdocs

2023-08-25 14:17 UTC, LWogan commented on components/interop/interop-identity-registry-service-impl/src/main/kotlin/net/corda/interop/identity/processor/InteropIdentityProcessor.kt
> +class InteropIdentityProcessor(
Could do with a class level kdoc to explain whats going on here. it will help future maintainers.

2023-08-25 14:17 UTC, LWogan commented on components/interop/interop-group-policy-read-service-impl/src/main/kotlin/net/corda/interop/group/policy/read/impl/InteropGroupPolicyReadServiceEventHandler.kt
> +        configurationReadService.start()
remove this line. The config read service is started at the processor level

2023-08-25 14:17 UTC, LWogan commented on components/interop/interop-identity-registry-service-impl/src/main/kotlin/net/corda/interop/identity/registry/impl/InteropIdentityRegistryServiceImpl.kt
> +    fun putInteropIdentity(holdingIdentityShortHash: ShortHash, identity: InteropIdentity) {
Need KDocs on any APIs exposed by the class

2023-08-25 14:17 UTC, LWogan commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/impl/FlowGlobalPostProcessorImpl.kt
>              val timeoutWindow = context.config.getLong(SESSION_MISSING_COUNTERPARTY_TIMEOUT_WINDOW)
beware that in the new flow session protocol we will be getting rid of retry here. If the lookup fails the first time, the flow will fail.

2023-08-25 14:42 UTC, SaurabhR3 commented on libs/membership/membership-common/src/main/kotlin/net/corda/membership/lib/grouppolicy/GroupPolicy.kt
>          val tlsPki: TlsPkiMode
Reverted

2023-08-25 14:58 UTC, szymonsztuka approved these changes

2023-08-25 15:13 UTC, jmacmahonr3 commented
> Flow changes look ok.
> 
> It would be nice to see more kdocs in general as a practice. Its helpful for future maintainers and debuggers, especially for the flow team. We end up as the first responders to most bugs because QA run flows and we're the flow team. Anything to help us understand whats going on and follow the code is great.

I'll add a ticket to do this work

2023-08-25 15:15 UTC, SaurabhR3 commented on components/interop/interop-group-policy-read-service/src/main/kotlin/net/corda/interop/group/policy/read/InteropGroupPolicyReadService.kt
> +interface InteropGroupPolicyReadService: Lifecycle {
Done

2023-08-25 15:15 UTC, SaurabhR3 commented on components/interop/interop-identity-registry-service-impl/src/main/kotlin/net/corda/interop/identity/processor/InteropIdentityProcessor.kt
> +class InteropIdentityProcessor(
Done

2023-08-25 15:15 UTC, SaurabhR3 commented on components/interop/interop-group-policy-read-service-impl/src/main/kotlin/net/corda/interop/group/policy/read/impl/InteropGroupPolicyReadServiceEventHandler.kt
> +        configurationReadService.start()
Done

2023-08-25 15:15 UTC, SaurabhR3 commented on components/interop/interop-identity-registry-service-impl/src/main/kotlin/net/corda/interop/identity/registry/impl/InteropIdentityRegistryServiceImpl.kt
> +    fun putInteropIdentity(holdingIdentityShortHash: ShortHash, identity: InteropIdentity) {
Done

2023-08-25 15:16 UTC, SaurabhR3 commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/impl/FlowGlobalPostProcessorImpl.kt
>              val timeoutWindow = context.config.getLong(SESSION_MISSING_COUNTERPARTY_TIMEOUT_WINDOW)
@ac101m any thoughts on this?

2023-08-25 15:20 UTC, ac101m commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/impl/FlowGlobalPostProcessorImpl.kt
>              val timeoutWindow = context.config.getLong(SESSION_MISSING_COUNTERPARTY_TIMEOUT_WINDOW)
I don't think the interop identity lookup is any less robust than the membership group lookup. If once is enough there, then it's enough on our end too if you ask me!

Unless I'm misunderstanding something here?

2023-08-25 15:44 UTC, ac101m reviewed
LGTM

2023-08-25 16:07 UTC, jmacmahonr3 approved these changes

2023-08-25 18:30 UTC, merged

2023-08-27 15:29 UTC, yarivus reviewed
thx @ac101m