CORE-10051: further removal of HSM abstractions
corda/corda-runtime-os pull request #4253
Opened 2023-07-08 08:05 UTC by dickon

2023-07-08 17:02 UTC, chrisr3 commented
This is inevitably going to impact the "crypto" code in the driver. Can we merge #4251 and #4254 before this one please? Then I can merge `release/os/5.1` into the `feature/flow-testing` branch and defer updating the driver's crypto integration until you have completed your changes.

2023-07-11 12:38 UTC, simon-johnson-r3 requested changes

2023-07-11 12:38 UTC, simon-johnson-r3 commented on components/crypto/crypto-service-impl/src/main/kotlin/net/corda/crypto/service/TenantInfoService.kt
> +     * Result type is HSMAssociationInfo, which is a type defined in the public API and therefore
This comment wont make sense out of the context of this PR, e.g. 6 months from now. I think it would be better to explain it in terms of the standard
`@return Information pertinent to the tenant registration`

And then maybe change the description of `HSMAssociationInfo` over in that class file to suggest some of the information might not be useful at this point in time.

2023-07-11 12:38 UTC, simon-johnson-r3 commented on components/crypto/crypto-service-impl/src/main/kotlin/net/corda/crypto/service/TenantInfoService.kt
> +     * Lookup settings assigned HSM by tenant and category.
I think there's words missing here, or am I reading it incorrectly?

2023-07-11 12:38 UTC, simon-johnson-r3 commented on components/crypto/crypto-service-impl/src/main/kotlin/net/corda/crypto/service/impl/SigningServiceImpl.kt
> +            // TODO always return GeneratedWrappedKey here
Can we remove this TODO, perhaps by creating a new ticket? It's not obvious when it will be done. If it's already in a later PR, perhaps we can just not mention it?

2023-07-11 12:38 UTC, simon-johnson-r3 commented on components/crypto/crypto-service-impl/src/test/kotlin/net/corda/crypto/service/impl/SigningServiceGeneralTests.kt
> +        private val wrappingKeyAlias = "Enoch Root"
Not sure what the policy on stuff like this is. Given this is an open source project I suggest we try to avoid it and stick to something formal like "alias1"?

2023-07-11 12:38 UTC, simon-johnson-r3 commented on components/crypto/crypto-service-impl/src/test/kotlin/net/corda/crypto/service/impl/SigningServiceImplTest.kt
> +    private val masterKeyAlias = "IAMGROOT"
same here

2023-07-11 12:38 UTC, simon-johnson-r3 commented on components/crypto/crypto-service-impl/src/test/kotlin/net/corda/crypto/service/impl/infra/TestServicesFactory.kt
> +    val signingService: SigningService by lazy {
is there a reason this is lazy?

2023-07-11 12:38 UTC, simon-johnson-r3 commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoService.kt
> + * @param signingRepositoryFactory which provides a factory for [SigningRepository], which provides save and
There's no `signingRepositoryFactory` parameter here.

2023-07-11 12:38 UTC, simon-johnson-r3 commented on components/crypto/crypto-softhsm-impl/src/test/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoServiceOperationsTests.kt
> +        private val signingRepository: SigningRepository = mock()
is this used anywhere?

2023-07-11 12:38 UTC, simon-johnson-r3 commented on components/crypto/crypto-softhsm-impl/src/test/kotlin/net/corda/crypto/softhsm/impl/infra/MakeCryptoService.kt
> +    wrappingRepository: WrappingRepository = TestWrappingRepository()
Just a note that this trailing comma is actually more aligned to the Kotlin coding standards than not having it. I don't suggest you add it back in now, but I don't recommend removing them in the future either (our code base is split between the two at the moment).

2023-07-11 12:38 UTC, simon-johnson-r3 commented on libs/crypto/crypto-config-impl/src/main/kotlin/net/corda/crypto/config/impl/CryptoConfigUtils.kt
> +// TODO remove me, dead?
I would either remove the method or the comment. It will build or it wont after all!

2023-07-11 12:38 UTC, simon-johnson-r3 commented on libs/crypto/crypto-config-impl/src/main/kotlin/net/corda/crypto/config/impl/CryptoConfigUtils.kt
> -private const val HSM_ID = "hsmId"
if these were private before, are they used anywhere?

2023-07-11 12:38 UTC, simon-johnson-r3 commented on libs/crypto/crypto-config-impl/src/main/kotlin/net/corda/crypto/config/impl/CryptoHSMConfig.kt
> +// TODO remove me, dead?
same, I would either remove the comment or the class

2023-07-11 12:38 UTC, simon-johnson-r3 commented on components/crypto/crypto-service-impl/src/main/kotlin/net/corda/crypto/service/impl/SigningServiceImpl.kt
> -import net.corda.cache.caffeine.CacheFactoryImpl
might be used elsewhere in this module, but if not, can Caffeine be removed from the build.gradle? (triggered by seeing it included in another build.gradle below)

2023-07-11 12:38 UTC, simon-johnson-r3 commented on processors/crypto-processor/src/main/kotlin/net/corda/processors/crypto/internal/CryptoProcessorImpl.kt
> +        val expireAfterAccessMins = cachingConfig.getConfig(EXPIRE_AFTER_ACCESS_MINS).getLong(DEFAULT)
I know it comes from elsewhere, but I find `DEFAULT` a bit of a vague constant name...

2023-07-11 12:38 UTC, simon-johnson-r3 commented on processors/crypto-processor/src/main/kotlin/net/corda/processors/crypto/internal/CryptoProcessorImpl.kt
> +        // TODO drop this compatibility code that supports name between KEY_MAP_TRANSIENT_NAME and if so disables caching
does this need a ticket rather than a comment?

2023-07-11 12:50 UTC, Sakpal commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/HSMRepositoryImpl.kt
> +                    ?: createAndPersistAssociation(em, tenantId, "SOFT", masterKeyPolicy)
Minor: Can we make a variable out of this string `"SOFT"` as I can see it has been used at multiple places?

2023-07-11 21:28 UTC, dickon reviewed
Thanks Simon for your detailed attention, I've addressed all that feedback.

2023-07-11 21:28 UTC, dickon commented on components/crypto/crypto-service-impl/src/main/kotlin/net/corda/crypto/service/TenantInfoService.kt
> +     * Result type is HSMAssociationInfo, which is a type defined in the public API and therefore
`HSMAssociationInfo` is an autogenerated Avro stub, so we cannot include our own javadoc. It's also public API so I'm not looking to change at this stage

2023-07-11 21:28 UTC, dickon commented on components/crypto/crypto-service-impl/src/main/kotlin/net/corda/crypto/service/TenantInfoService.kt
> +     * Result type is HSMAssociationInfo, which is a type defined in the public API and therefore
Done. Comments rewritten to kdoc conventions and be more self-contained.

That is good pracitce and Corda standard, even though we violate that in places.

2023-07-11 21:28 UTC, dickon commented on components/crypto/crypto-service-impl/src/main/kotlin/net/corda/crypto/service/TenantInfoService.kt
> +     * Lookup settings assigned HSM by tenant and category.
fixed

2023-07-11 21:28 UTC, dickon commented on components/crypto/crypto-service-impl/src/main/kotlin/net/corda/crypto/service/impl/SigningServiceImpl.kt
> -import net.corda.cache.caffeine.CacheFactoryImpl
No, we still have a reference to `com.github.benmanes.caffeine.cache.Cache` here, and we construct caffeine in test cases. However, api+testImplementaiton should work so I'll try that.

2023-07-11 21:28 UTC, dickon commented on components/crypto/crypto-service-impl/src/main/kotlin/net/corda/crypto/service/impl/SigningServiceImpl.kt
> +            // TODO always return GeneratedWrappedKey here
Done. It turns out I'd already made the change so the TODO was an error.

2023-07-11 21:28 UTC, dickon commented on components/crypto/crypto-service-impl/src/test/kotlin/net/corda/crypto/service/impl/SigningServiceGeneralTests.kt
> +        private val wrappingKeyAlias = "Enoch Root"
done

2023-07-11 21:28 UTC, dickon commented on components/crypto/crypto-service-impl/src/test/kotlin/net/corda/crypto/service/impl/SigningServiceImplTest.kt
> +    private val masterKeyAlias = "IAMGROOT"
done

2023-07-11 21:28 UTC, dickon commented on components/crypto/crypto-service-impl/src/test/kotlin/net/corda/crypto/service/impl/infra/TestServicesFactory.kt
> +    val signingService: SigningService by lazy {
To speed up test run times. Not all test classes that use this suite of test fixtures need all of them. We see this in other parts of Corda e.g. P2P.

The fact that not all of them are lazy is a bit weird, but for the most part the more expensive constructors are handled via `lazy`.

2023-07-11 21:28 UTC, dickon commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/HSMRepositoryImpl.kt
> +                    ?: createAndPersistAssociation(em, tenantId, "SOFT", masterKeyPolicy)
Done.

There already was a `val` in CryptConsts, I now use that everywhere.

2023-07-11 21:28 UTC, dickon commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoService.kt
> + * @param signingRepositoryFactory which provides a factory for [SigningRepository], which provides save and
fixed

2023-07-11 21:28 UTC, dickon commented on components/crypto/crypto-softhsm-impl/src/test/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoServiceOperationsTests.kt
> +        private val signingRepository: SigningRepository = mock()
deleted

2023-07-11 21:28 UTC, dickon commented on components/crypto/crypto-softhsm-impl/src/test/kotlin/net/corda/crypto/softhsm/impl/infra/MakeCryptoService.kt
> +    wrappingRepository: WrappingRepository = TestWrappingRepository()
We need a consensus on this between you and @chrisr3 who has pushed the opposite way.

However, it wasn't intentional so I reverted it.

2023-07-11 21:28 UTC, dickon commented on libs/crypto/crypto-config-impl/src/main/kotlin/net/corda/crypto/config/impl/CryptoConfigUtils.kt
> -private const val HSM_ID = "hsmId"
deleted it instead of making it public

2023-07-11 21:28 UTC, dickon commented on libs/crypto/crypto-config-impl/src/main/kotlin/net/corda/crypto/config/impl/CryptoConfigUtils.kt
> +// TODO remove me, dead?
TODO removed. It is still used.

2023-07-11 21:28 UTC, dickon commented on libs/crypto/crypto-config-impl/src/main/kotlin/net/corda/crypto/config/impl/CryptoHSMConfig.kt
> +// TODO remove me, dead?
TODO deleted. At the time I was trying to absolutely minimise PR size, so deleting more at once than necessary goes against that desire to mimise changes.

2023-07-11 21:28 UTC, dickon commented on processors/crypto-processor/src/main/kotlin/net/corda/processors/crypto/internal/CryptoProcessorImpl.kt
> +        val expireAfterAccessMins = cachingConfig.getConfig(EXPIRE_AFTER_ACCESS_MINS).getLong(DEFAULT)
Maybe so, but I don't think we change or shoudl it now; this is code which has been moved rather than written for this purpose, and the names are in the config which is locked down public API .

2023-07-11 21:28 UTC, dickon commented on processors/crypto-processor/src/main/kotlin/net/corda/processors/crypto/internal/CryptoProcessorImpl.kt
> +        // TODO drop this compatibility code that supports name between KEY_MAP_TRANSIENT_NAME and if so disables caching
This comment already exists in the code in its old location. However the TODO is old and has effectively been done so I'll remove  it.

2023-07-11 21:30 UTC, dickon commented
> This is inevitably going to impact the "crypto" code in the driver. Can we merge #4251 and #4254 before this one please? Then I can merge `release/os/5.1` into the `feature/flow-testing` branch and defer updating the driver's crypto integration until you have completed your changes.

These are both merged now.

2023-07-12 07:39 UTC, simon-johnson-r3 approved these changes

2023-07-12 08:35 UTC, seanbrereton approved these changes
LGTM (blt)

2023-07-12 08:53 UTC, yift-r3 approved these changes
Network changes LGTM.

2023-07-12 09:11 UTC, merged

2023-07-12 09:11 UTC, kyriathar commented on components/crypto/crypto-service-impl/src/main/kotlin/net/corda/crypto/service/HSMService.kt
> -interface HSMService : Lifecycle {
FWIW I believe this change here makes this service not aligned anymore with the the rest of the SOFT hsm concept within the code base/ in the DB/ in rest APIs.

2023-07-12 09:11 UTC, kyriathar commented on components/crypto/crypto-service-impl/src/main/kotlin/net/corda/crypto/service/TenantInfoService.kt
> +    fun lookup(tenantId: String, category: String): HSMAssociationInfo?
FWIF I believe these APIs here are now less meaningful of what their actually doing, compared to what they used to be before.