CORE-15157 Snyk update io.fabric8:kubernetes-client dependency
corda/corda-runtime-os pull request #4266
Opened 2023-07-10 15:46 UTC by jacob-scott3141

2023-07-10 16:20 UTC, ronanbrowne requested changes

2023-07-10 16:20 UTC, ronanbrowne commented on tools/plugins/preinstall/build.gradle
> +    implementation "io.fabric8:kubernetes-client:6.7.2"
I know you're just bumping what was here already, but really this should be an external version like the others referenced from gradle.properties file

2023-07-10 18:06 UTC, davidcurrie approved these changes
LGTM

2023-07-11 08:24 UTC, seanbrereton approved these changes
lgtm

2023-07-11 08:53 UTC, yarivus approved these changes
LGTM

2023-07-11 08:59 UTC, ronanbrowne approved these changes
LGTM

2023-07-11 09:05 UTC, merged