Jsinclair/es 13611/impliment helm chart parameters
corda/corda-runtime-os pull request #4276
Opened 2023-07-11 11:58 UTC by JasonSinclair95

Add topologySpread, common labels and affinity features to helm chart.

All has been tested by running the helm template command to see how the helm chart will be deployed.

https://r3-cev.atlassian.net/browse/CORE-13611

2023-07-11 12:12 UTC, jacob-scott3141 reviewed
Just a couple of nit picks but otherwise LGTM

2023-07-11 12:12 UTC, jacob-scott3141 commented on charts/corda-lib/templates/_worker.tpl
> +weight: {{ $weight}}
Can this be `{{ $weight }}`?

2023-07-11 12:12 UTC, jacob-scott3141 commented on charts/corda/values.schema.json
> +            "title": "affinity for pod assignment"
`"Affinity for pod assignment"`

2023-07-11 12:12 UTC, jacob-scott3141 commented on charts/corda-lib/templates/_helpers.tpl
> +  {{- toYaml . | nindent 2 }}
Does this display the list with the `- ` correctly? as in
``` 
topologySpreadConstraints:
  - value:
      subValue
    ...
```

2023-07-11 12:35 UTC, JasonSinclair95 commented on charts/corda-lib/templates/_helpers.tpl
> +  {{- toYaml . | nindent 2 }}
after testing it displayed the correct format - so yep

2023-07-11 12:36 UTC, JasonSinclair95 commented on charts/corda/values.schema.json
> +            "title": "affinity for pod assignment"
i think i should have made topology lowercase, if anything. seems all titles start with lowercase for example "override chart name"

2023-07-11 12:37 UTC, JasonSinclair95 commented on charts/corda-lib/templates/_worker.tpl
> +weight: {{ $weight}}
I'm not to sure, but what would the benefit be?

2023-07-11 12:39 UTC, jacob-scott3141 commented on charts/corda-lib/templates/_worker.tpl
> +weight: {{ $weight}}
Just a formatting thing, shouldn't affect the code

2023-07-11 12:43 UTC, JasonSinclair95 commented on charts/corda-lib/templates/_worker.tpl
> +weight: {{ $weight}}
Id be tempted to leave it, this code was very tedious to get working. and it would remain consistent with the way variables are defined throughout the chart for example $worker etc...

2023-07-11 12:59 UTC, davidcurrie requested changes

2023-07-11 12:59 UTC, davidcurrie commented on charts/corda-lib/templates/_helpers.tpl
> +{{- if .Values.topologySpreadConstraints }}
nit: you don't need the `if` if you have `with` as the `with` is conditional on having a value

2023-07-11 12:59 UTC, davidcurrie commented on charts/corda-lib/templates/_helpers.tpl
> +{{- end }}
nit: should have a newline at the end

2023-07-11 12:59 UTC, davidcurrie commented on charts/corda/values.yaml
> +# Affinity for pod assignment
```suggestion
# -- affinity for pod assignment
```

2023-07-11 12:59 UTC, davidcurrie commented on charts/corda/values.yaml
> +# Topology Spread Constraints
```suggestion
# -- topology spread constraints
```

2023-07-11 12:59 UTC, davidcurrie commented on charts/corda/values.yaml
> +# extra labels to add to all deployed objects
```suggestion
# -- extra labels to add to all deployed objects
```

2023-07-11 12:59 UTC, davidcurrie commented on charts/corda-lib/templates/_worker.tpl
> +      affinity:
would it make more sense to put the `affinity:` inside `corda.affinity` so it matches `corda-topologySpreadConstraints`?

2023-07-11 12:59 UTC, davidcurrie commented on charts/corda-lib/templates/_worker.tpl
> +weight: {{ $weight}}
because I highlighted the same thing in a review of @jacob-scott3141 's!

2023-07-11 12:59 UTC, davidcurrie commented on charts/corda-lib/templates/_worker.tpl
> +{{- $_ := set $affinity.podAntiAffinity "preferredDuringSchedulingIgnoredDuringExecution" ( append $affinity.podAntiAffinity.preferredDuringSchedulingIgnoredDuringExecution ( fromYaml (include "corda
```suggestion
{{- $_ := set $affinity.podAntiAffinity "preferredDuringSchedulingIgnoredDuringExecution" ( append $affinity.podAntiAffinity.preferredDuringSchedulingIgnoredDuringExecution ( fromYaml ( include "corda.defaultAffinity" ( list ( add ( len $affinity.podAntiAffinity.preferredDuringSchedulingIgnoredDuringExecution ) 1 ) $worker ) ) ) ) }}
```

2023-07-11 12:59 UTC, davidcurrie commented on charts/corda-lib/templates/_worker.tpl
> +{{- end }}
newline

2023-07-11 12:59 UTC, davidcurrie commented on charts/corda/values.schema.json
> +            "title": "topology spread constraints."
```suggestion
            "title": "topology spread constraints"
```

2023-07-11 12:59 UTC, davidcurrie commented on charts/corda/values.schema.json
> +            "title": "labels to add to all deployed objects",
```suggestion
            "title": "extra labels to add to all deployed objects",
```

2023-07-11 12:59 UTC, davidcurrie commented on charts/corda/values.schema.json
> +            "type": "array",
can you define the types of the items in the list? [this](https://github.com/instrumenta/kubernetes-json-schema/blob/master/master-standalone/topologyspreadconstraint-v1.json) may help if it's still accurate

2023-07-11 12:59 UTC, davidcurrie commented on charts/corda/values.schema.json
> +            "type": "object",
as above, can you define the object more precisely?

2023-07-11 13:20 UTC, davidcurrie commented on charts/corda-lib/templates/_worker.tpl
> +weight: {{ $weight}}
I think the consistency is to have spaces between braces and other text

2023-07-11 16:09 UTC, JasonSinclair95 commented on charts/corda-lib/templates/_worker.tpl
> +      affinity:
could you explain this one a bit more please?

2023-07-13 12:13 UTC, davidcurrie commented on charts/corda/values.schema.json
> +            }
I don't think you want to use `additionalProperties` here (as it only makes sense for objects). I think you want `items` to define the type of the objects in the array.

2023-07-13 12:13 UTC, davidcurrie commented on charts/corda/values.schema.json
> +                    "array"
does it really take properties with all three of these types? or is everything under here an object?

2023-07-13 13:37 UTC, JasonSinclair95 commented on charts/corda/values.schema.json
> +                    "array"
your right. within the object is

2023-07-13 13:49 UTC, davidcurrie approved these changes
LGTM

2023-07-13 15:08 UTC, merged