CORE-9483 Enable sending of primitives across sessions
corda/corda-runtime-os pull request #4291
Opened 2023-07-12 15:29 UTC by ben-millar

2023-07-14 14:05 UTC, LWogan reviewed
This is great work Ben! The logic looks good to me. Given that its in a sensitive area, i'd like to get @mnesbit s input before approving.

We might need to check the kdocs in corda-api on these apis to ensure theres no comments saying "you cant send primitive types" as there might be. You might need to check with the docs team as well to see if theres any guidance given to cordapp developers telling them the same.

2023-07-14 14:05 UTC, LWogan commented on libs/serialization/serialization-amqp/src/test/kotlin/net/corda/internal/serialization/amqp/SerializationHelperTests.kt
> +class SerializationHelperTests {
nice test coverage!

2023-07-14 14:05 UTC, LWogan commented on libs/serialization/serialization-amqp/src/main/kotlin/net/corda/internal/serialization/amqp/SerializationHelper.kt
> +        is Collection<*> -> {
I think you should add a kdoc to this function to adequately explain this function. It will be confusing to anyone without context.

2023-07-14 17:12 UTC, emilybowe reviewed
LGTM, pending @mnesbit review
Good explanation of this in the demo earlier, made this much easier to go through 👍

2023-07-17 12:21 UTC, ben-millar commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/flow/FlowTests.kt
> +    @Test
NB: This test still has the potential to fail on the combined worker until this PR is merged, fixing the DBMessageBusImpl: https://github.com/corda/corda-runtime-os/pull/4304

2023-07-18 14:05 UTC, fenryka reviewed
Just a few comments, feel free to ignore as otherwise looks fine

2023-07-18 14:05 UTC, fenryka commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/application/sessions/impl/FlowSessionImpl.kt
> +        return processReceivedPayload(receiveType, received)
minor comment, but why are we changing the established context of the parameter order? I'm not saying if one is better than the other but it feels a little weird to invert it unless we're bringing things inline with a wider set of established conventions

2023-07-18 14:05 UTC, fenryka commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/application/sessions/impl/FlowSessionImpl.kt
> +        return processReceivedPayload(receiveType, received)
same comment as above on inverting the parameter ordering

2023-07-18 14:05 UTC, fenryka commented on libs/serialization/serialization-amqp/src/main/kotlin/net/corda/internal/serialization/amqp/SerializationHelper.kt
> + * Checks if the given [type] is Corda serializable (if it has or inherits the [CordaSerializable] annotation),
Technically this function doesn't check this (in that it returns true or false), it enforces it

2023-07-18 14:05 UTC, fenryka commented on libs/serialization/serialization-amqp/src/main/kotlin/net/corda/internal/serialization/amqp/SerializationHelper.kt
> +        is Collection<*> -> {
should we check that the collection type is on our allowed set of collections (If that's still a thing, i.e. those with stable and ordering)

2023-07-18 14:05 UTC, fenryka commented on libs/serialization/serialization-amqp/src/main/kotlin/net/corda/internal/serialization/amqp/SerializationHelper.kt
> +fun requireCordaSerializable(type: Any?) {
Question: What do we expect people to do with this function? IIRC the serialiser enforces this, so it is already "required", this function throws earlier in the call stack potentially, but then we're adding an overhead of runtime checking each and every time we call this and thus could do the check at compile time (at least for CorDaps)... so I guess I'm just curious why add this function when this is already enforced

2023-07-18 14:05 UTC, fenryka commented on libs/serialization/serialization-amqp/src/test/kotlin/net/corda/internal/serialization/amqp/SerializationHelperTests.kt
> +    fun `isArray should correctly determine if type is an array type`() {
Should this also test primitive Arrays int[] for example?

2023-07-18 14:54 UTC, ben-millar commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/application/sessions/impl/FlowSessionImpl.kt
> +        return processReceivedPayload(receiveType, received)
Whoops! I'll refactor that, good catch.

2023-07-18 15:01 UTC, ben-millar commented on libs/serialization/serialization-amqp/src/main/kotlin/net/corda/internal/serialization/amqp/SerializationHelper.kt
> +fun requireCordaSerializable(type: Any?) {
Actually, this function already existed. This change just extends it to handle collections on a per-element basis (because this is how AMQP will handle them, too).

Originally, I modified it as I was going to use it to enforce that types passed to `send`/`receive` were Corda serializable but, actually, this wouldn't work as we could be passing a concrete type which is annotated serializable, but which is inherited from an interface which is not.

I decided to keep the change in the PR anyway, as I think it's more correct.

2023-07-19 11:53 UTC, ben-millar commented on libs/serialization/serialization-amqp/src/main/kotlin/net/corda/internal/serialization/amqp/SerializationHelper.kt
> +        is Collection<*> -> {
I looked into this. There is an allowed set of collections in the `CollectionSerializer` covering lists and sets, but this is just for the collection types not covered by other serializers (I.e., we have an `ArraySerializer`, `MapSerializer`, etc.).

I'm sure there are some collection types (¿`EnumSet`?) that we can't handle, but it feels too heavy handed to pull together all of these allowed sets from various serializers just for this check. Good question tho, it was informative to check this stuff.

2023-07-19 12:10 UTC, ben-millar commented on libs/serialization/serialization-amqp/src/test/kotlin/net/corda/internal/serialization/amqp/SerializationHelperTests.kt
> +    fun `isArray should correctly determine if type is an array type`() {
c-style arrays in Kotlin, TIL! Added a test case

2023-07-19 15:13 UTC, fenryka commented on libs/serialization/serialization-amqp/src/main/kotlin/net/corda/internal/serialization/amqp/SerializationHelper.kt
> +fun requireCordaSerializable(type: Any?) {
I guess my concern would be that in adding this enforcement check, we're adding a lot of runtime overhead to something that is already enforced later on, i.e. it can't go wrong so we're going to spend a few instructions earlier on also checking that... happy path we do more work, unhappy path we catch it earlier. 

NOTE: by "a lot of" we're talking maybe 20 instructions at most so it's really not significant in any way... I'm just old enough to remember when that would've been an issue we'd have wanted to avoid, old lady shouts at cloud :D

2023-07-19 15:41 UTC, ben-millar commented on libs/serialization/serialization-amqp/src/main/kotlin/net/corda/internal/serialization/amqp/SerializationHelper.kt
> +fun requireCordaSerializable(type: Any?) {
Yeah, actually, I think you're right; it hasn't really been sitting well with me since yesterday 🤔 I'm gonna follow the KISS principal and roll this change back.

2023-07-19 16:22 UTC, simon-johnson-r3 commented
One of the issues that concerned me in the JIRA ticket is that this support is not well documented, and in fact if you try and send something that is not `@CordaSerializable` the error message leads you to believe only `@CordaSerializable` types are allowed. Can we make it clear in the public api that primitive types are now supported? I don't think this is a breaking change to the contract as we are widening it.

2023-07-19 16:22 UTC, simon-johnson-r3 requested changes

2023-07-19 16:22 UTC, simon-johnson-r3 commented on testing/cpbs/test-cordapp/src/main/kotlin/com/r3/corda/testing/smoketests/flow/RpcSmokeTestFlow.kt
> +    @Suspendable
The scope of smoke tests is being reduced in favour of e2e tests, and I think given this is a specific feature test might be a better fit there. I think @owenstanford is leading that, perhaps he has an opinion?

2023-07-19 18:32 UTC, ben-millar commented on testing/cpbs/test-cordapp/src/main/kotlin/com/r3/corda/testing/smoketests/flow/RpcSmokeTestFlow.kt
> +    @Suspendable
I agree, I'll move this to the E2E test repo. I just wanted it to run against the PR to demonstrate that the changes are working before I port it.

2023-07-20 08:45 UTC, ben-millar commented on testing/cpbs/test-cordapp/src/main/kotlin/com/r3/corda/testing/smoketests/flow/RpcSmokeTestFlow.kt
> +    @Suspendable
> Can we make it clear in the public api that primitive types are now supported?
Are you looking for a change to the docs on the API side?

2023-07-20 12:40 UTC, ben-millar commented on testing/cpbs/test-cordapp/src/main/kotlin/com/r3/corda/testing/smoketests/flow/RpcSmokeTestFlow.kt
> +    @Suspendable
API PR to add context https://github.com/corda/corda-api/pull/1184/files

2023-07-20 12:49 UTC, simon-johnson-r3 approved these changes

2023-07-20 12:58 UTC, LWogan approved these changes
LGTM. As mentioned in my last review, please check with docs team in case there's anything regarding the old restriction that needs to be removed. Will need a release note at a minimum

2023-07-20 13:00 UTC, merged