Core 15351/log trace span to separate log file
corda/corda-runtime-os pull request #4299
Opened 2023-07-13 13:45 UTC by ZawarR3

2023-07-13 15:13 UTC, josephzunigadaly commented on libs/rest/rest-server-impl/build.gradle
> +            'tracing')
This looks like an accidental edit. Please can we undo this change?

2023-07-13 15:16 UTC, josephzunigadaly commented on libs/tracing/src/main/kotlin/net/corda/tracing/impl/BraveTracingService.kt
> +            val reporters = mutableListOf<Reporter<Span>>(Reporter.CONSOLE)
`Reporter.CONSOLE` should still be commented out

```suggestion
            val reporters = mutableListOf<Reporter<Span>>(/*Reporter.CONSOLE*/)
```

2023-07-13 15:31 UTC, josephzunigadaly commented on osgi-framework-bootstrap/src/main/resources/log4j2.xml
> +        <logger name="brave.Tracer" level="info">
I think the default level should be "off" for this so that it can be enabled when wanted but normally is switched off.

2023-07-13 15:32 UTC, josephzunigadaly commented on osgi-framework-bootstrap/src/main/resources/log4j2.xml
> +                     filePattern="logs/corda-trace-spans.%d{MM-dd-yyyy}.%i.log"
I think `yyyy-MM-dd` is a better date format because it is always sortable.

2023-07-14 13:42 UTC, owenstanford commented on osgi-framework-bootstrap/src/main/resources/log4j2.xml
> +        <logger name="brave.Tracer" level="info">
We should exclude `brave.tracer` from the other loggers so we only get the trace output in the trace log file.

2023-07-14 14:35 UTC, ZawarR3 commented on osgi-framework-bootstrap/src/main/resources/log4j2.xml
> +        <logger name="brave.Tracer" level="info">
I agree, currently working on it.

2023-07-18 09:22 UTC, owenstanford commented on libs/tracing/src/main/kotlin/net/corda/tracing/impl/BraveTracingService.kt
> +                logger.info(span.toString())
We should check to see if logging is enabled before logging to save the cost of the  span.toString()
```if (!logger.isLoggable(Level.INFO)) return ;```

2023-07-18 09:26 UTC, owenstanford reviewed
We should be able to delete the `NoopTracingService` class now.

2023-07-18 09:28 UTC, ZawarR3 commented on libs/tracing/src/main/kotlin/net/corda/tracing/impl/BraveTracingService.kt
> +                logger.info(span.toString())
is this okay: `       
 override fun report(span: Span) {
            if (logger.isLoggable(Level.INFO)) {
                logger.info(span.toString())
            }
        }`

2023-07-18 09:30 UTC, owenstanford commented on libs/tracing/src/main/kotlin/net/corda/tracing/impl/BraveTracingService.kt
> +                logger.info(span.toString())
yes

2023-07-18 09:39 UTC, ZawarR3 commented on osgi-framework-bootstrap/src/main/resources/log4j2.xml
> +            </Filters>
I forgot to remove this filter, it's not needed. I'll remove it on the next commit.

2023-07-25 16:26 UTC, josephzunigadaly approved these changes, later dismissed

2023-07-28 13:08 UTC, simon-johnson-r3 requested changes

2023-07-28 13:08 UTC, simon-johnson-r3 commented on libs/tracing/src/main/kotlin/net/corda/tracing/impl/BraveTracingService.kt
> +import java.util.*
I'm not sure we allow wildcard imports, although admittedly the Kotlin standard don't explicitly prevent it.

2023-07-28 13:08 UTC, simon-johnson-r3 commented on libs/tracing/src/main/kotlin/net/corda/tracing/impl/BraveTracingService.kt
> +        if (zipkinHost != null){
there should be a space between ) and { here, I would run this through the intellij formatter to save you some time and prevent these kinds of formatting comments in PRs generally

2023-07-28 13:08 UTC, simon-johnson-r3 commented on libs/tracing/src/main/kotlin/net/corda/tracing/impl/BraveTracingService.kt
> +        val logReporter = LogReporter()
Kotlin can be quite a terse language and generally developers try to embrace that. Here I would suggest
```
reporters.add(LogReporter())
```
It's not a competition to reduce the number of code lines, but removal of variables which are only used once and which call a trivial constructor illustrates to the reader this is the only point of use, and it's one thing Kotlin is quite good at promoting IMHO

2023-07-31 10:32 UTC, simon-johnson-r3 submitted a review, later dismissed

2023-07-31 15:01 UTC, simon-johnson-r3 approved these changes

2023-07-31 15:41 UTC, merged