CORE - 15403: Update Snyk vulnerability
corda/corda-runtime-os pull request #4316
Opened 2023-07-17 13:10 UTC by nargas-ritu

CORE - 15403: Update Snyk vulnerability

2023-07-17 13:21 UTC, vkolomeyko approved these changes, later dismissed
LGTM

2023-07-17 13:39 UTC, yarivus submitted a review, later dismissed
LGTM

2023-07-18 09:29 UTC, yarivus requested changes

2023-07-18 09:29 UTC, yarivus commented on .snyk
> +  SNYK-JAVA-ORGBOUNCYCASTLE-5771340:
```suggestion
SNYK-JAVA-ORGBOUNCYCASTLE-5771340:
```

Let's remain consistent with tabs/spaces

2023-07-18 09:45 UTC, vkolomeyko approved these changes
LGTM

2023-07-18 09:46 UTC, yarivus approved these changes
LGTM

2023-07-18 09:47 UTC, ronanbrowne approved these changes
LGTM

2023-07-18 10:28 UTC, merged