CORE-13937: serializer DRAFT
corda/corda-runtime-os pull request #4322
Opened 2023-07-17 15:29 UTC by jennyang-r3

draft

2023-07-17 16:42 UTC, lankydan commented on components/ledger/ledger-utxo-flow/src/main/kotlin/net/corda/ledger/utxo/flow/impl/flows/finality/serializer/FinalityPayloadSerializer.kt
> +        return FinalityPayloadProxy(obj.initialTransaction, obj.transferAdditionalSignatures)
Make the map in `FinalityPayload` public and then pass the map into the proxy instead.

This means that the serialized form of the `FinalityPayload` is just a map of string to bytes and nothing else.

2023-07-17 16:42 UTC, lankydan commented on components/ledger/ledger-utxo-flow/src/main/kotlin/net/corda/ledger/utxo/flow/impl/flows/finality/serializer/FinalityPayloadSerializer.kt
> +        return FinalityPayload(proxy.initialTransaction, proxy.transferAdditionalSignatures, serializationService)
Once we've pass the map into the proxy we'll want to call the constructor you have with the map and the serialization service here.

2023-07-17 16:42 UTC, lankydan commented on components/ledger/ledger-utxo-flow/src/main/kotlin/net/corda/ledger/utxo/flow/impl/flows/finality/v1/UtxoFinalityFlowV1.kt
> +    private val serializationService: SerializationService,
I'd rather that the `SerializationServce` relied on `@CordaInject` to be injected into this class.

2023-07-17 16:42 UTC, lankydan commented on components/ledger/ledger-utxo-flow/src/main/kotlin/net/corda/ledger/utxo/flow/impl/flows/finality/v1/UtxoFinalityFlowV1.kt
>          })
Unneeded formatting.

2023-07-17 16:42 UTC, lankydan commented on components/ledger/ledger-utxo-flow/src/main/kotlin/net/corda/ledger/utxo/flow/impl/flows/finality/serializer/kryo/FinalityPayloadKryoSerializer.kt
> +class FinalityPayloadKryoSerializer @Activate constructor(
I don't think this will work correctly.

If someone sent us a V1 version of the payload and we have V2 with an extra field, it will try to pull an extra field out of the map that doesn't exist and cause an error.

To keep things simple, especially because our usage is not _that_ complicated. I suggest that we remove the `lazy` fields from `FinalityPayload` and keep them as getters. This means that we can make keep the writing into the kryo output as the `map` from the payload and then read it back in when deserializing.

If we want to keep the lazy fields then we'd need something like `LazyStateAndRefImplKryoSerializer`, but I don't think we'd need that because `FinalityPayload` is internal to us and we basically read everything out of it straight away at the moment.

We could always make it lazy in the future if needed without issue.

2023-07-18 09:50 UTC, lankydan commented on components/ledger/ledger-utxo-flow/src/test/kotlin/net/corda/ledger/utxo/flow/impl/flows/finality/v1/UtxoReceiveFinalityFlowV1Test.kt
> +    ) {
Revert this formatting change.

2023-07-18 09:50 UTC, lankydan commented on components/ledger/ledger-utxo-flow/src/test/kotlin/net/corda/ledger/utxo/flow/impl/flows/finality/v1/UtxoReceiveFinalityFlowV1Test.kt
> +        whenever(signedTransaction.addMissingSignatures()).thenReturn(
There are a lot of unneeded formatting changes.

2023-07-18 09:50 UTC, lankydan commented on components/ledger/ledger-utxo-flow/src/main/kotlin/net/corda/ledger/utxo/flow/impl/flows/finality/v1/UtxoFinalityFlowV1.kt
> +                ), sessions.toSet()
put `sessions.toSet()` on a new line

2023-07-18 09:50 UTC, lankydan commented on components/ledger/ledger-utxo-flow/src/main/kotlin/net/corda/ledger/utxo/flow/impl/flows/finality/serializer/kryo/FinalityPayloadKryoSerializer.kt
> +    }
This should be passing in a map into the `FinalityPayload` constructor.

2023-07-18 09:50 UTC, lankydan commented on components/ledger/ledger-utxo-flow/src/main/kotlin/net/corda/ledger/utxo/flow/impl/flows/finality/FinalityPayload.kt
> +    val map: Map<String, ByteArray>,
We have both `map` and `payload` as public accessors to the map of data. Either `map` should be private or `payload` should be removed. We do not need both to be public. I think having the `map` public is probably the right solution,

2023-07-18 09:50 UTC, lankydan commented on components/ledger/ledger-utxo-flow/src/main/kotlin/net/corda/ledger/utxo/flow/impl/flows/finality/FinalityPayload.kt
> +data class FinalityPayload @ConstructorForDeserialization constructor(
Because we're using serializers now, we can remove `@ConstructorForDeserialization constructor` since we're explicitly defining how to serialize/deserialize this class now.

2023-07-18 09:50 UTC, lankydan commented on components/ledger/ledger-utxo-flow/src/main/kotlin/net/corda/ledger/utxo/flow/impl/flows/finality/UtxoFinalityFlow.kt
> +    private val pluggableNotaryClientFlow: Class<PluggableNotaryClientFlow>,
Undo this change.

2023-07-18 09:50 UTC, lankydan commented on components/ledger/ledger-utxo-flow/src/main/kotlin/net/corda/ledger/utxo/flow/impl/flows/finality/UtxoFinalityFlow.kt
> +    private val pluggableNotaryClientFlow: Class<PluggableNotaryClientFlow>,
Undo this change.

2023-07-18 09:50 UTC, lankydan commented on components/ledger/ledger-utxo-flow/src/main/kotlin/net/corda/ledger/utxo/flow/impl/flows/finality/serializer/FinalityPayloadSerializer.kt
> +    service = [InternalCustomSerializer::class, UsedByFlow::class, UsedByPersistence::class, UsedByVerification::class],
We don't need `UsedByPErsistence` or `UsedByVerification` for this class.

2023-07-18 09:50 UTC, lankydan commented on components/ledger/ledger-utxo-flow/src/main/kotlin/net/corda/ledger/utxo/flow/impl/flows/finality/serializer/FinalityPayloadSerializer.kt
> +): BaseProxySerializer<FinalityPayload, FinalityPayloadProxy>(), UsedByFlow, UsedByPersistence, UsedByVerification {
Same as comment above.

2023-07-18 09:50 UTC, lankydan commented on components/ledger/ledger-utxo-flow/src/main/kotlin/net/corda/ledger/utxo/flow/impl/flows/finality/serializer/kryo/FinalityPayloadKryoSerializer.kt
> +    service = [CheckpointInternalCustomSerializer::class, UsedByFlow::class, UsedByVerification::class],
We don't need `UsedByVerification` here.

2023-07-18 09:50 UTC, lankydan commented on components/ledger/ledger-utxo-flow/src/main/kotlin/net/corda/ledger/utxo/flow/impl/flows/finality/serializer/kryo/FinalityPayloadKryoSerializer.kt
> +) : CheckpointInternalCustomSerializer<FinalityPayload>, UsedByFlow, UsedByVerification {
Remove `UsedByVerification`.

2023-07-18 09:50 UTC, lankydan commented on components/ledger/ledger-utxo-flow/src/main/kotlin/net/corda/ledger/utxo/flow/impl/flows/finality/serializer/kryo/FinalityPayloadKryoSerializer.kt
> +    }
Did we test this, because I _think_ this would fail if it was run.

2023-07-18 09:50 UTC, lankydan commented on libs/flows/flow-api/src/main/kotlin/net/corda/flow/application/versioning/VersionedSendFlowFactory.kt
> + *         return UtxoFinalityFlowV1(transaction, sessions, pluggableNotaryClientFlow, serializationService, finalityVersion)
Correct this code to match the real code.

2023-07-18 09:50 UTC, nkovacsx requested changes
I'm not really happy with the fact that we pass a service into a POJO (data) class, could we do something with that?

2023-07-18 09:50 UTC, nkovacsx commented on components/ledger/ledger-utxo-flow/src/main/kotlin/net/corda/ledger/utxo/flow/impl/flows/finality/FinalityPayload.kt
> +    private val serializationService: SerializationService
Having a service property inside a data class is something we shouldn't do. Couldn't we just pass in the already serialized object? @lankydan what do you think?

2023-07-18 09:50 UTC, nkovacsx commented on components/ledger/ledger-utxo-flow/src/main/kotlin/net/corda/ledger/utxo/flow/impl/flows/finality/serializer/FinalityPayloadSerializer.kt
> +        get() = FinalityPayload::class.java
I don't think you need the explicit getters here.

2023-07-18 09:53 UTC, lankydan commented on components/ledger/ledger-utxo-flow/src/main/kotlin/net/corda/ledger/utxo/flow/impl/flows/finality/FinalityPayload.kt
> +    private val serializationService: SerializationService
It has to be this way, if we want the getters to work as they are. So if we don't pass in a `SerializationService` then the getters need to take in the service to deserialize the contents. Or, we we just have the getters return bytes are deserialize in the flow. That _might_ be simpler to understand but generally the amount of code will be the same.

@blsemo @relyafi thoughts?

2023-07-18 10:08 UTC, jennyang-r3 commented on components/ledger/ledger-utxo-flow/src/main/kotlin/net/corda/ledger/utxo/flow/impl/flows/finality/serializer/kryo/FinalityPayloadKryoSerializer.kt
> +    }
If this is going to be a map, are we reading this as `Map<String, Any>?` But we have separate getters for each property in the map. Or am I making no sense?

2023-07-18 10:10 UTC, lankydan commented on components/ledger/ledger-utxo-flow/src/main/kotlin/net/corda/ledger/utxo/flow/impl/flows/finality/FinalityPayload.kt
> +    private val serializationService: SerializationService
Passing in the `SerializationService` into the getters might be the right solution but will wait for others to comment.

2023-07-18 17:15 UTC, jennyang-r3 commented
Closing the PR since the scenario initially thought about wouldn't happen, which is why we created this PR.

2023-07-18 17:15 UTC, closed without merging