CORE-15138 Move ledger e2e tests from runtime OS to e2e repo
corda/corda-runtime-os pull request #4329
Opened 2023-07-18 15:24 UTC by PranushanR3

2023-07-18 17:39 UTC, ronanbrowne submitted a review, later dismissed
LGMT (build change)

2023-07-19 10:40 UTC, nkovacsx requested changes
Just one minor comment, I'm not sure why we need the new de/serializers.

2023-07-19 10:40 UTC, nkovacsx commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/ledger/UtxoLedgerTests.kt
> +    internal object SecureHashSerializer : com.fasterxml.jackson.databind.JsonSerializer<SecureHash>() {
Why do we need these de/serializers?

2023-07-19 10:44 UTC, PranushanR3 commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/ledger/UtxoLedgerTests.kt
> +    internal object SecureHashSerializer : com.fasterxml.jackson.databind.JsonSerializer<SecureHash>() {
This is because they are being used in line 39 and 40 in the ObjectMapper.

2023-07-19 11:45 UTC, PranushanR3 commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/ledger/UtxoLedgerTests.kt
> +    internal object SecureHashSerializer : com.fasterxml.jackson.databind.JsonSerializer<SecureHash>() {
This is being used on line 39 and 40 by the object builder. The SecureHash is then used on line 164 to parse the result.

2023-07-20 15:35 UTC, blsemo reviewed
Looks mostly ok to me, but I wonder about the changes to the test utilities lib?

2023-07-20 15:35 UTC, blsemo commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/ledger/UtxoLedgerTests.kt
> +    internal object SecureHashSerializer : com.fasterxml.jackson.databind.JsonSerializer<SecureHash>() {
I think the answer Nandor was looking for is:
You had to move it here because it was re-used from the (now deleted) consensual tests (which was a code smell anyway).

2023-07-20 15:35 UTC, blsemo commented on testing/e2e-test-utilities/src/main/kotlin/net/corda/e2etest/utilities/Utils.kt
> +fun parseSecureHashString(hashString: String) = parseSecureHash(hashString)
Where is this used?

2023-07-20 15:35 UTC, blsemo commented on testing/e2e-test-utilities/build.gradle
> +    implementation project(':libs:crypto:crypto-core')
Why is this required now?

2023-07-21 07:59 UTC, PranushanR3 commented on testing/e2e-test-utilities/src/main/kotlin/net/corda/e2etest/utilities/Utils.kt
> +fun parseSecureHashString(hashString: String) = parseSecureHash(hashString)
This is now used in the ConsensualLedgerTests which has been moved to the `e2e-tests` repo.

2023-07-21 08:01 UTC, PranushanR3 commented on testing/e2e-test-utilities/build.gradle
> +    implementation project(':libs:crypto:crypto-core')
This is in order to have access to the parseSecureHash method used in the `utils.kt` file. This method is needed in the `utils.kt` file in order to have access to the method in the `ConsensualLedgerTests.kt` file now in the e2e repo.

2023-07-21 08:36 UTC, lankydan reviewed
I feel similar to the other comments, I'm confused why removing one test has caused the addition of other code.

Also based on the ticket, shouldn't `Utxo Ledger - custom query can be executed and results are returned if no offset is provided and limit is maximize` be moved as well?

2023-07-23 17:57 UTC, chrisr3 commented
I see a lot smoke tests being migrated out of `corda-runtime-os` recently. Can I request that the relevant CPBs in `:testing:cpbs` remain intact please, because I am still using them to test my Driver.

2023-07-24 08:24 UTC, PranushanR3 commented
> I see a lot smoke tests being migrated out of `corda-runtime-os` recently. Can I request that the relevant CPBs in `:testing:cpbs` remain intact please, because I am still using them to test my Driver.

I have not touched any of the `testing:cpbs` and so it should all still be there.

2023-07-24 08:26 UTC, chrisr3 commented
> I have not touched any of the `testing:cpbs` and so it should all still be there.

That's fine. My comment was addressed to the wider audience :wink:.

2023-07-24 12:15 UTC, blsemo commented on testing/e2e-test-utilities/src/main/kotlin/net/corda/e2etest/utilities/Utils.kt
> +fun parseSecureHashString(hashString: String) = parseSecureHash(hashString)
If it's only used in the ConsensualLedgerTests in the e2e repo, it should probably live there? Having a method in a smoketest package that does not get called doesn't make sense.

2023-07-26 08:19 UTC, PranushanR3 commented on testing/e2e-test-utilities/src/main/kotlin/net/corda/e2etest/utilities/Utils.kt
> +fun parseSecureHashString(hashString: String) = parseSecureHash(hashString)
We need it to be in the smoketest package due to the fact we can't access the crypto library from the `corda5-e2e-tests` repo.

2023-07-28 08:54 UTC, lankydan approved these changes

2023-07-28 09:08 UTC, nkovacsx approved these changes

2023-07-28 11:06 UTC, ronanbrowne approved these changes

2023-07-28 11:38 UTC, merged