CORE-15739 Add evm smart contract tests for interop-solution
corda/corda-runtime-os pull request #4356
Opened 2023-07-24 15:36 UTC by ILoomans

### Purpose

This pull request is to serve as a baseline for adding & testing EVM smart contracts on our test-evm netwrok that we will be relying on for building and Interop process from Ethereum to Corda & vice versa. 

###  What does it contain?

This added module 'evm-interop-contracts' contains smart contract code (.sol) files, and tests to run on these smart contracts

- /contracts -> Contains the solidity smart contracts
- /test -> Contains the tests

This repository also generates a contract ABI (Application Binary Interface) by running:

`
npx hardhat compile
`

These ABI files are needed for encoding/decoding smart contract transactions & sending it to the Ethereum network.

### Why are we not using Java/Kotlin?

The interop  team decided that using Hardhat, a tools for compiling, testing and deploying Ethereum smart contracts was the best tool we could use for exactly this purpose.  Java/Kotlin based tools such as Web3J and Web3J-unit add many more steps to achieve this, and have no built in tools for generating a contract ABI's or testing smart contracts. Beyond this hardhat has become an industry standard for testing smart contracts. I spoke with @fenryka to confirm that this is the best solution!

### What will this PR enable the Interop Team to do?

This pull request will together with the work that @mag1c-48 did in creating a hyperledger-besu kubernetes pipeline, allow us to deploy an ethereum network, confirm that the network and smart contracts are working as expected, and continue to build our EVM-interop solution!

Let me know if you have any questions

2023-07-24 15:51 UTC, yarivus reviewed
see comments

2023-07-24 15:51 UTC, yarivus commented on components/interop/web3j-service/.idea/workspace.xml
does this need to be gitignored ?

2023-07-24 15:51 UTC, yarivus commented on testing/evm-interop-contracts/test/ERC1155Token.ts
should this source file be renamed to ERC1155TokenTests.ts (as it's effectively full of test-cases) ?

2023-07-24 15:51 UTC, yarivus commented on testing/evm-interop-contracts/test/ERC20Token.ts
same comment as prev file

2023-07-24 15:51 UTC, yarivus commented on testing/evm-interop-contracts/test/Storage.ts
same comment as previous file

2023-07-24 15:51 UTC, yarivus commented on testing/evm-interop-contracts_/README.md
this file seems duplicate with the other README.md

2023-07-24 15:51 UTC, yarivus commented on testing/evm-interop-contracts_/artifacts/@openzeppelin/contracts/token/ERC1155/ERC1155.sol/ERC1155.dbg.json
should .dbg.json files need to be gitignored ?

2023-07-24 15:51 UTC, yarivus commented on testing/evm-interop-contracts_/contracts/ERC20Token.sol
seems like duplicated files in the folder `evm-interop-contracts_`

2023-07-25 08:16 UTC, ILoomans commented on testing/evm-interop-contracts_/artifacts/@openzeppelin/contracts/token/ERC1155/ERC1155.sol/ERC1155.dbg.json
These files will be ignored because they are under the artifacts directory

2023-07-25 08:17 UTC, ILoomans commented on testing/evm-interop-contracts/test/ERC1155Token.ts
Files have been renamed!

2023-07-25 08:17 UTC, ILoomans commented on testing/evm-interop-contracts_/contracts/ERC20Token.sol
Removed this

2023-07-25 08:32 UTC, yarivus reviewed
still pending comments

2023-07-25 08:32 UTC, yarivus commented on testing/evm-interop-contracts/README.md
why have you deleted this copy of README.md ?

2023-07-25 09:05 UTC, ILoomans commented on testing/evm-interop-contracts/README.md
Okay I have removed the workspace.xml file and added a more appropriate README.md

2023-07-25 09:38 UTC, yarivus requested changes

2023-07-25 09:38 UTC, yarivus commented on testing/evm-interop-contracts/contracts/ERC20Token.sol
> +
```suggestion

```

2023-07-25 09:38 UTC, yarivus commented on testing/evm-interop-contracts/contracts/Storage.sol
> +    /**
```suggestion
    mapping (address => struct1) structMapper;

    /**
```

2023-07-25 09:38 UTC, yarivus commented on testing/evm-interop-contracts/contracts/ERC20Token.sol
> +
```suggestion
    }

```

2023-07-25 09:38 UTC, yarivus commented on .gitignore
R U sure you need to change the root .gitignore if you've added the testing/evm-interop-contracts/.gitignore ?

2023-07-25 10:11 UTC, yarivus reviewed
see pending comment

2023-07-25 10:11 UTC, yarivus commented on .gitignore
> +# Add gitignore for appropriate evm files
R U sure you need to change this file once you have testing/evm-interop-contracts/.gitignore ?

2023-07-25 10:26 UTC, yarivus approved these changes
LGTM

2023-07-25 11:53 UTC, merged