CORE-13740 Fix caching of vnode EMFs
corda/corda-runtime-os pull request #4364
Opened 2023-07-25 16:17 UTC by kyriathar

WIP - Reverting commit that needs undoing first - Raising for testing.

2023-07-27 09:04 UTC, chrisr3 commented on components/db/db-connection-manager/src/main/kotlin/net/corda/db/connection/manager/DbConnectionOps.kt
> +    fun getOrCreateEntityManagerFactory(connectionId: UUID, entitiesSet: JpaEntitiesSet): EntityManagerFactory
_Another_ variant of `getOrCreateEntityManagerFactory`? We already have _two_:
```kotlin
fun getOrCreateEntityManagerFactory(db: CordaDb, privilege: DbPrivilege): EntityManagerFactory

fun getOrCreateEntityManagerFactory(name: String, privilege: DbPrivilege, entitiesSet: JpaEntitiesSet): EntityManagerFactory
```

It worries me that a new function with such a _very_ similar signature could be doing something radically different :worried:.

But as I understand it, _every_ new `EntityManagerFactory` instance will allocate memory that can never be reclaimed without also unloading those entities' host bundle. Which means that we _cannot_ allow the platform to create an open-ended number of `EntityManagerFactory` instances outside of a sandbox.

2023-07-27 09:32 UTC, kyriathar commented on components/db/db-connection-manager/src/main/kotlin/net/corda/db/connection/manager/DbConnectionOps.kt
> +    fun getOrCreateEntityManagerFactory(connectionId: UUID, entitiesSet: JpaEntitiesSet): EntityManagerFactory
Interesting point, thanks! 

Sounds to me like a public sandbox references types (entities) belonging to user bundles? So could it be we cannot unload those user bundles then till we release the respective EMFs?

Back to this PR, I believe it doesn't change the above behavior (i.e. how we are caching the EMFs).

It's that we didn't want to get vnode EMFs via connection name and DB privilege as these are quite internal/ esoteric but rather the more appropriate pointer which is the connection ID.

2023-07-28 10:05 UTC, conalsmith-r3 commented on components/db/db-connection-manager/src/main/kotlin/net/corda/db/connection/manager/DbConnectionOps.kt
> +    fun getOrCreateEntityManagerFactory(connectionId: UUID, entitiesSet: JpaEntitiesSet): EntityManagerFactory
I plugged in the VirtualNodeReconciliationContext so reconcilers reused EMF from the cache and can confirm it fixes the mem leak:

A comparison, about 40 minutes apart, the reconcilers in question are running every 5 seconds:
```
after 10min
Loaded classes: 26,103
Allocated All Pools: 345 MB
Used Metaspace: 190 MB
Used CodeHeap 'profiled nmethods': 74 MB
Used CodeHeap 'non-profiled nmethods': 37 MB
Used Compressed Class Space: 17 MB
Used CodeHeap 'non-nmethods': 1.7 MB

after 50min
Loaded classes: 26,103
Allocated All Pools: 346 MB
Used Metaspace: 190 MB
Used CodeHeap 'profiled nmethods': 73 MB
Used CodeHeap 'non-profiled nmethods': 37 MB
Used Compressed Class Space: 17 MB
Used CodeHeap 'non-nmethods': 1.7 MB
```

2023-07-28 10:54 UTC, simon-johnson-r3 requested changes

2023-07-28 10:54 UTC, simon-johnson-r3 commented on components/db/db-connection-manager/src/main/kotlin/net/corda/db/connection/manager/DbConnectionOps.kt
> +    fun getOrCreateEntityManagerFactory(connectionId: UUID, entitiesSet: JpaEntitiesSet): EntityManagerFactory
Discussed offline. We're going to go for a formalised design which limits to 1 EMF per row in the db connections db via an EMF store. The api which is called to get an EMF would have no effect on the number of EMFs and essentially would do the same underneath, it's simply looking up the row/EMF using different data. It's not quite a cache, although in principal it will exhibit the same behaviour we see in this PR.

2023-07-28 12:45 UTC, simon-johnson-r3 commented on components/db/db-connection-manager-impl/src/main/kotlin/net/corda/db/connection/manager/impl/DbConnectionOpsCachedImpl.kt
> +    // TODO Maybe we could consider replacing the above cache with the one below. All `db_connection`s have/ get an ID.
If we want to submit this PR as a first step to alleviate the user experience problem, I would at least make this comment accurate in terms of the direction we wish to go in.

2023-07-28 13:41 UTC, simon-johnson-r3 approved these changes, later dismissed
Approving on the basis this works in principle like our desired solution. That should be recorded in another JIRA ticket, but will not make substantial differences and it's better this is resolved sooner rather than later.

2023-07-28 13:51 UTC, yift-r3 commented on components/db/db-connection-manager-impl/src/main/kotlin/net/corda/db/connection/manager/impl/DbConnectionOpsCachedImpl.kt
> +    //  duplicate entity proxies loaded in the class loader as identified in https://r3-cev.atlassian.net/browse/CORE-15806.
Can we avoid the link to Jira in the source code? CORE-15806 should be enough.

2023-07-28 13:51 UTC, yift-r3 commented on components/membership/certificates-service-impl/src/integrationTest/kotlin/net/corda/membership/certificate/service/impl/CertificatesServiceImplTest.kt
> +            virtualNodeInfoReadServiceMock)
Nitpick: can you add a comma and a new line?

2023-07-28 13:51 UTC, yift-r3 commented on components/membership/certificates-service-impl/src/test/kotlin/net/corda/membership/certificate/service/impl/DbClientImplTest.kt
>      fun `retrieveCertificates will not close the node factory`() {
The name of this test should be `retrieveCertificates will not close the cluster factory`

2023-07-28 13:58 UTC, yift-r3 approved these changes
LGTM

2023-07-31 09:05 UTC, simon-johnson-r3 approved these changes

2023-07-31 09:31 UTC, merged