CORE-15297: refactor crypto processor to reduce OSGI and layering
corda/corda-runtime-os pull request #4369
Opened 2023-07-26 12:24 UTC by dickon

2023-07-27 14:49 UTC, Sakpal commented on components/crypto/crypto-service-impl/src/test/kotlin/net/corda/crypto/service/impl/SigningServiceGeneralTests.kt
> -class SigningServiceGeneralTests {
Major: Have we moved this tests somewhere else? Or these tests are not relevant anymore with the changes made?

2023-07-27 14:56 UTC, Sakpal commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/HSMRepositoryImpl.kt
> +                    ?: createAndPersistAssociation(em, tenantId, CryptoConsts.SOFT_HSM_ID, masterKeyPolicy)
Major: Duplicate/Redundant line?

2023-07-27 15:58 UTC, dickon commented on components/crypto/crypto-service-impl/src/test/kotlin/net/corda/crypto/service/impl/SigningServiceGeneralTests.kt
> -class SigningServiceGeneralTests {
That's a good question, which I address in the description:

> We remove many test cases, which are testing layers that no longer exist, and move other test cases to reflect the newly simplified structure. All the tests in SigningServiceGeneralTests move to SoftCryptoServiceGeneralTests.

So all the tests in this file are now in SoftCryptoServiceGeneralTests.

2023-07-27 16:03 UTC, dickon commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/HSMRepositoryImpl.kt
> +                    ?: createAndPersistAssociation(em, tenantId, CryptoConsts.SOFT_HSM_ID, masterKeyPolicy)
Actually I already fixed this, it looks like it was a merge error. So if you reload the PR in github or repull the branch it should disappear.

2023-07-27 16:22 UTC, Sakpal commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoService.kt
> +    private fun <R> recoverable(description: String, block: () -> R) = try {
Curious: Can you help me understand the use of this method?

2023-07-27 16:40 UTC, dickon commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoService.kt
> +    private fun <R> recoverable(description: String, block: () -> R) = try {
Recoverable runs a block of code, and catches and wraps certain exceptions in a way that lets the caller know what is required. This was used to be done  in the decorator layer before, and it requirement is part of the way Corda delivers robustness. We could just have a try/catch constrict with the exception wrapping logic in each place, but this way is easier to write and read, provided the reader is familiar with the function.

2023-07-28 08:12 UTC, Sakpal commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoService.kt
> +    private val signingKeyInfoCache: Cache<SecureHash, SigningKeyInfo>,
Major: Is this new support for cache, related to the caching of signing keys?

2023-07-28 08:16 UTC, Sakpal commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoService.kt
> +    override fun querySigningKeys(
Curious: Is all of this functions added below, moved from some other files?

2023-07-28 08:19 UTC, Sakpal commented on libs/crypto/crypto-config-impl/src/main/kotlin/net/corda/crypto/config/impl/CryptoConfigUtils.kt
> +// TODO remove me, dead?
Major: Can we mark this in JIRA instead?

2023-07-28 08:19 UTC, Sakpal commented on libs/crypto/crypto-config-impl/src/main/kotlin/net/corda/crypto/config/impl/CryptoHSMConfig.kt
> +// TODO remove me, dead?
Major: Can we mark this in JIRA instead?

2023-07-28 08:27 UTC, Sakpal commented on libs/crypto/crypto-core/src/main/kotlin/net/corda/crypto/core/SigningKeyInfo.kt
> +    fun convertToCryptoSigningKey(keyEncodingService: KeyEncodingService): CryptoSigningKey = CryptoSigningKey(
Major: This looks like a Utility function for converting one data object to another. Any particular reason why we are keeping this in one of the POJO's and not a separate utils file?

Also, this is adding some business logic in this Data class(POJO) and adds reference to other classes in it, thus creating a dependency.

2023-07-28 10:42 UTC, dickon commented on libs/crypto/crypto-config-impl/src/main/kotlin/net/corda/crypto/config/impl/CryptoConfigUtils.kt
> +// TODO remove me, dead?
done

2023-07-28 10:48 UTC, dickon commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoService.kt
> +    override fun querySigningKeys(
yes, they all came from  `SigningServiceImpl`

2023-07-28 10:52 UTC, dickon commented on libs/crypto/crypto-config-impl/src/main/kotlin/net/corda/crypto/config/impl/CryptoHSMConfig.kt
> +// TODO remove me, dead?
Created https://r3-cev.atlassian.net/browse/CORE-15824, TOOD deleted

2023-07-28 11:32 UTC, dickon commented on libs/crypto/crypto-core/src/main/kotlin/net/corda/crypto/core/SigningKeyInfo.kt
> +    fun convertToCryptoSigningKey(keyEncodingService: KeyEncodingService): CryptoSigningKey = CryptoSigningKey(
On the other hand having it here improves locality of reference within the code, which I think is more important than the other considerations you mention.

2023-07-28 14:28 UTC, simon-johnson-r3 requested changes

2023-07-28 14:28 UTC, simon-johnson-r3 commented on components/crypto/crypto-service-impl/src/main/kotlin/net/corda/crypto/service/impl/TenantInfoServiceImpl.kt
> +    private fun ensureWrappingKey(association: HSMAssociationInfo, cryptoService: CryptoService) {
You appear to have added a requirement to pass a member property to a member function here, is that a mistake?

2023-07-28 14:28 UTC, simon-johnson-r3 commented on components/crypto/crypto-service-impl/src/main/kotlin/net/corda/crypto/service/impl/bus/CryptoFlowOpsBusProcessor.kt
> +                        // TODO CORE-15264 - remove the retry here, Corda 5 architecture is that the flow should do the retries.
I would phrase this a bit less like there's something missing, because that isn't true, we just over engineered a retry. How about just `CORE-15264 will remove the retry here...`

2023-07-28 14:28 UTC, simon-johnson-r3 commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/TenantInfoService.kt
> +    fun populate(tenantId: String, category: String, cryptoService: CryptoService): HSMAssociationInfo
typically we inject dependent services, is there a reason you pass one here?

2023-07-28 14:28 UTC, simon-johnson-r3 commented on libs/crypto/crypto-core/src/main/kotlin/net/corda/crypto/core/CryptoService.kt
> +        context: Map<String, String> = EMPTY_CONTEXT,
`context: Map<String, String> = emptyMap()` would be fine and more normal here (and other places) I think? Kotlin already provides an easy means to do this already. It saves the reader from looking up what EMPTY_CONTEXT is.

2023-07-28 14:28 UTC, simon-johnson-r3 commented on libs/crypto/crypto-core/src/main/kotlin/net/corda/crypto/core/SigningKeyInfo.kt
> +    fun convertToCryptoSigningKey(keyEncodingService: KeyEncodingService): CryptoSigningKey = CryptoSigningKey(
I think this should be `toCryptoSigningKey` as in `toString` etc.

If you want to break the dependency in the data class, you could make it an extension function - and some members of the Kotlin community, including the author of Effective Kotlin would suggest that in cases like this where only public properties are used. I'm not sure you'd get a great deal of benefit from that in this case though.

2023-07-28 15:02 UTC, dickon commented on components/crypto/crypto-service-impl/src/main/kotlin/net/corda/crypto/service/impl/bus/CryptoFlowOpsBusProcessor.kt
> +                        // TODO CORE-15264 - remove the retry here, Corda 5 architecture is that the flow should do the retries.
I removed the TODO, that seems to be the way we are going.

2023-07-28 15:02 UTC, dickon commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/TenantInfoService.kt
> +    fun populate(tenantId: String, category: String, cryptoService: CryptoService): HSMAssociationInfo
I clarified this in the docstring; the trouble is that there's a dependency cycle here.

2023-07-28 15:02 UTC, dickon commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/TenantInfoService.kt
> +    fun populate(tenantId: String, category: String, cryptoService: CryptoService): HSMAssociationInfo
and I could flatten TenantInfoSerivce into CryptoServiceImpl, and have not done so yet since CryptoServiceImpl is already large.

2023-07-28 15:02 UTC, dickon commented on libs/crypto/crypto-core/src/main/kotlin/net/corda/crypto/core/SigningKeyInfo.kt
> +    fun convertToCryptoSigningKey(keyEncodingService: KeyEncodingService): CryptoSigningKey = CryptoSigningKey(
Name changed.

I'd like to read up on the extension method point; my initial thinking is that in this case it'd be a surprising departure from standard OOP technique. But I don't think we should hold this work up on this point; I seem to recall examples going either way on this.

2023-07-28 15:02 UTC, dickon commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoService.kt
> +    private fun <R> recoverable(description: String, block: () -> R) = try {
I clarified this is in a kdoc.

2023-07-28 15:33 UTC, dickon commented on libs/crypto/crypto-core/src/main/kotlin/net/corda/crypto/core/SigningKeyInfo.kt
> +    fun convertToCryptoSigningKey(keyEncodingService: KeyEncodingService): CryptoSigningKey = CryptoSigningKey(
Having just bought and studied Item 45 and 46 in Effecitve Kotlin I think on balance the authors of that book would prefer my style rather an extension method here.

2023-07-28 15:34 UTC, dickon commented on components/crypto/crypto-service-impl/src/main/kotlin/net/corda/crypto/service/impl/TenantInfoServiceImpl.kt
> +    private fun ensureWrappingKey(association: HSMAssociationInfo, cryptoService: CryptoService) {
I discussed this directly with Simon; he hadn't noticed I'd dropped cryptoService as as member property, due to the cycle.

2023-07-28 15:40 UTC, dickon commented on libs/crypto/crypto-core/src/main/kotlin/net/corda/crypto/core/CryptoService.kt
> +        context: Map<String, String> = EMPTY_CONTEXT,
This is code pasted from SigningService and is in 5.1 (https://github.com/corda/corda-runtime-os/blob/13c6ffded20a55ba01d46a19ee37bfee680805ab/components/crypto/crypto-service-impl/src/main/kotlin/net/corda/crypto/service/SigningService.kt#L19 )  I take the point about style but due to the size and time elapsed on this PR I think I should minimise the number of changes. And this point doesn't feel it rates a JIRA ticket, nor would it be the first style issue I'd want to address.

2023-07-28 15:43 UTC, dickon commented on components/crypto/crypto-service-impl/src/main/kotlin/net/corda/crypto/service/impl/TenantInfoServiceImpl.kt
> +    private fun ensureWrappingKey(association: HSMAssociationInfo, cryptoService: CryptoService) {
Furthermore, we discussed other ways of getting rid of the cycle, but what we have works and is pretty low impact on the code so I'd like to move on.

2023-07-31 07:57 UTC, simon-johnson-r3 commented on components/crypto/crypto-service-impl/src/main/kotlin/net/corda/crypto/service/impl/TenantInfoServiceImpl.kt
> +    private fun ensureWrappingKey(association: HSMAssociationInfo, cryptoService: CryptoService) {
I'd suggest here a complete decoupling of the classes, by introducing either an interface or higher order function, e.g.
```
populate(tenantId, category) { wrappingKeyAlias, context ->
  cryptoService.createWrappingKey(false, wrappingKeyAlias, context)
}
```

2023-07-31 07:58 UTC, simon-johnson-r3 approved these changes
I'm approving this with some minor comments still outstanding. They don't affect the logic of the code. Over time it would be good to fix these.

2023-07-31 08:26 UTC, merged

2023-07-31 08:29 UTC, dickon commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/TenantInfoService.kt
> +    fun populate(tenantId: String, category: String, cryptoService: CryptoService): HSMAssociationInfo
https://r3-cev.atlassian.net/browse/CORE-15853 to revisit this, a story on the tech debt epic.

2023-07-31 08:33 UTC, dickon commented on libs/crypto/crypto-core/src/main/kotlin/net/corda/crypto/core/CryptoService.kt
> +        context: Map<String, String> = EMPTY_CONTEXT,
https://r3-cev.atlassian.net/browse/CORE-15854 to track this, story in tech debt epic.