ES-1036: Enable Multi Cluster Tests Run
corda/corda-runtime-os pull request #4393
Opened 2023-08-01 14:47 UTC by knguyen-r3

* Updated build.gradle to only run the multi-cluster tests.

2023-08-02 07:55 UTC, ronanbrowne commented
@knguyen-r3 can you rebase this branch with the latest from release/os/5.1 your PR is failing as it is missing this commit from the base branch which is now needed https://github.com/corda/corda-runtime-os/commits/release/os/5.1 due to a change in a lower layer of application stack (corda-cli)

2023-08-02 18:11 UTC, ronanbrowne submitted a review, later dismissed
LGTM

2023-08-02 20:27 UTC, yarivus requested changes, later dismissed

2023-08-02 20:27 UTC, yarivus commented on build.gradle
> +                  excludeTags 'runAllTestsNoExclusions'
```suggestion
                    excludeTags 'runAllTestsNoExclusions'
```

2023-08-03 09:40 UTC, ronanbrowne approved these changes, later dismissed
LGTM

2023-08-03 15:27 UTC, ronanbrowne approved these changes, later dismissed
LGTM

2023-08-03 17:32 UTC, ronanbrowne commented on build.gradle
> +                    excludeTags 'MultiCluster', 'runUnstableTests'
```suggestion
                    excludeTags 'MultiCluster', 'Unstable'
```

we need to refrecn the unit tag here, which is `Unstable` , runUnstableTests is the gradle property which controls this

2023-08-03 17:33 UTC, ronanbrowne commented on build.gradle
> +                    excludeTags 'MultiCluster', 'runUnstableTests'
I've applied this

2023-08-03 17:33 UTC, ronanbrowne approved these changes

2023-08-04 09:13 UTC, merged

2023-08-04 12:42 UTC, yarivus reviewed
thx @knguyen-r3