CORE-15586 Split verification from TransactionSignatureService into TransactionSignatureVerificationService
corda/corda-runtime-os pull request #4445
Opened 2023-08-11 09:05 UTC by vlajos

2023-08-14 14:52 UTC, jmacmahonr3 requested changes

2023-08-14 14:52 UTC, jmacmahonr3 commented on components/ledger/ledger-common-flow/src/main/kotlin/net/corda/ledger/common/flow/impl/transaction/TransactionSignatureVerificationServiceImpl.kt
> +    override fun verifySignature(
@vlajos would it be possible to take a list or a set of keys ? 

cc @szymonsztuka

2023-08-14 15:30 UTC, vlajos commented on components/ledger/ledger-common-flow/src/main/kotlin/net/corda/ledger/common/flow/impl/transaction/TransactionSignatureVerificationServiceImpl.kt
> +    override fun verifySignature(
Generally, we prefer the simplest approach in APIs and let the consumers build the more complicated scenarios from the building blocks.
In this case, I think the caller side could use a similar function:
```
fun verifySignature(
    secureHash: SecureHash,
    signatureWithMetadata: DigitalSignatureAndMetadata,
    publicKeys: List<PublicKey>,
    digestService: DigestService
) {
    val digestAlgorithmOfKeyId = signatureWithMetadata.signature.by.algorithm
    val publicKey = requireNotNull(publicKeys.firstOrNull {
        digestService.hash(
            it.encoded,
            DigestAlgorithmName(digestAlgorithmOfKeyId)
        ) == signatureWithMetadata.signature.by
    }) {
        "The key Id of the provided signature does not match the provided public keys' id."
    }
    transactionSignatureVerificationService.verifySignature(secureHash, signatureWithMetadata, publicKey)
}
```
Could this work for you?

2023-08-17 10:28 UTC, szymonsztuka approved these changes, later dismissed

2023-08-17 10:28 UTC, szymonsztuka commented on components/ledger/ledger-common-flow/src/main/kotlin/net/corda/ledger/common/flow/impl/transaction/TransactionSignatureVerificationServiceImpl.kt
> +            require(proof.leaves.filter { secureHash.bytes contentEquals it.leafData }.size == 1) {
So essentially for batch signature (which is returned by the signing "activity") we check it contains a given  transation id. A question not necessarily related to this code, there is no semantics here what "transaction id" is, but we know in Corda UTXO model this should be a hash value of the transaction (content/binary)?

2023-08-17 10:28 UTC, szymonsztuka commented on components/ledger/ledger-common-flow/src/main/kotlin/net/corda/ledger/common/flow/impl/transaction/TransactionSignatureVerificationServiceImpl.kt
> +    override fun verifySignature(
Would DigestService be available in a class extending `net.corda.v5.ledger.utxo.Contract` ? I think yes, but haven't tried this:
```
class NotaryVerifyContract : Contract {
    @CordaInject
    lateinit var transactionSignatureVerificationService: TransactionSignatureVerificationService
    @CordaInject
    lateinit var digestService: DigestService

```

2023-08-17 10:28 UTC, szymonsztuka commented on testing/cpbs/ledger-utxo-demo-contract/src/main/kotlin/com/r3/corda/demo/utxo/contract/notaryverify/NotaryVerifyContract.kt
> +    lateinit var transactionSignatureVerificationService: TransactionSignatureVerificationService
So just to clarify, I can use this service inside Contract verification code like here below?

2023-08-17 15:49 UTC, vlajos commented on components/ledger/ledger-common-flow/src/main/kotlin/net/corda/ledger/common/flow/impl/transaction/TransactionSignatureVerificationServiceImpl.kt
> +    override fun verifySignature(
Yes. There is a related e2e test CorDapp with its test: https://github.com/corda/corda-e2e-tests/blob/release/5.1/apps/ledger-utxo-demo-contract/src/main/kotlin/com/r3/corda/demo/utxo/contract/ValidVerifyInjectionContract.kt

2023-08-17 15:54 UTC, vlajos commented on components/ledger/ledger-common-flow/src/main/kotlin/net/corda/ledger/common/flow/impl/transaction/TransactionSignatureVerificationServiceImpl.kt
> +            require(proof.leaves.filter { secureHash.bytes contentEquals it.leafData }.size == 1) {
`TransactionSignature...ServiceImpl.kt` does not care too much about the transaction ids apart from expecting `SecureHash`s. (Wrapped in `TransactionWithMetadata` in some cases.)
In platform code, these are transaction ids calculated as the root hash of the transaction's Merkle tree. But this service does not check anything like this.

2023-08-17 15:55 UTC, vlajos commented on testing/cpbs/ledger-utxo-demo-contract/src/main/kotlin/com/r3/corda/demo/utxo/contract/notaryverify/NotaryVerifyContract.kt
> +    lateinit var transactionSignatureVerificationService: TransactionSignatureVerificationService
Yes. https://github.com/corda/corda-runtime-os/pull/4445#discussion_r1297417039

2023-08-17 16:34 UTC, blsemo reviewed
Looks fine to me, apart from introducing a new smoke test in the runtime-os repo.

2023-08-17 16:34 UTC, blsemo commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/ledger/UtxoLedgerTests.kt
> +    @Test
Are you planning to move this test to the e2e test repo before merging? I don't think we should add more smoke tests...

2023-08-18 07:55 UTC, vlajos commented on applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/ledger/UtxoLedgerTests.kt
> +    @Test
Yes. That is the plan. (I mentioned it on slack too.)

2023-08-18 09:25 UTC, szymonsztuka commented on components/ledger/ledger-common-flow/src/main/kotlin/net/corda/ledger/common/flow/impl/transaction/TransactionSignatureVerificationServiceImpl.kt
> +    override fun verifySignature(
cool!

2023-08-18 09:25 UTC, szymonsztuka commented on testing/cpbs/ledger-utxo-demo-contract/src/main/kotlin/com/r3/corda/demo/utxo/contract/notaryverify/NotaryVerifyContract.kt
> +    lateinit var transactionSignatureVerificationService: TransactionSignatureVerificationService
perfect!

2023-08-18 10:13 UTC, blsemo submitted a review, later dismissed
LGTM

2023-08-18 13:47 UTC, jmacmahonr3 submitted a review, later dismissed

2023-08-18 14:33 UTC, blsemo approved these changes
LGTM

2023-08-18 15:30 UTC, merged