CORE-16230 Split UniquenessProcessor into its own worker
corda/corda-runtime-os pull request #4457
Opened 2023-08-14 15:34 UTC by mbrkic-r3

UniquenessProcessor split into its own worker

2023-08-14 16:49 UTC, chrisr3 commented
Errr, _**why**_ split the uniqueness processor into its own worker? Doesn't this change fly in the face of everything we've recently learnt about Kafka? :exploding_head:

I cannot _for the life of me_ understand how this can possibly make Corda 5 process flows any faster. More likely, it will do the exact opposite, while also making Corda more expensive to operate.

2023-08-14 20:32 UTC, mbrkic-r3 commented
Flows will communicate with other workers via RPC, not Kafka. Having more different processors in different workers will enable scaling each of them as separately. I'm not sure whether/how much difference will it actually make, @Omar-awad did a POC and can comment more regarding this.

2023-08-15 08:34 UTC, chrisr3 commented
> Flows will communicate with other workers via RPC, not Kafka. Having more different processors in different workers will enable scaling each of them as separately. I'm not sure whether/how much difference will it actually make, @Omar-awad did a POC and can comment more regarding this.

At the moment, each flow processor is deployed alongside its own uniqueness processor within the same JVM, and I really don't see how you can get any faster than that.

2023-08-18 08:16 UTC, relyafi commented
> Flows will communicate with other workers via RPC, not Kafka. Having more different processors in different workers will enable scaling each of them as separately. I'm not sure whether/how much difference will it actually make, @Omar-awad did a POC and can comment more regarding this.

@mbrkic-r3 that doesn't sound like a strong reason to me - I thought we'd established during the GA release cycle about the need to show a benefit from performance related changes? Can you point me to the evidence of the performance testing you've done to show that this change will be a positive one?

From conversations I've had with @driessamyn and @Omar-awad it sounds like there are other reasons for making this change, but the difficulty is this hasn't been properly communicated with the SME's, and I need that background in order to sensibly review this PR. Can we get a meeting set up with yourself / @JamesHR3 / @Omar-awad to discuss the background in more detail?

> At the moment, each flow processor is deployed alongside its own uniqueness processor within the same JVM, and I really don't see how you can get any faster than that.

@chrisr3 not quite - it actually lives as part of the DB worker alongside the DB processor, with the idea being that it is then co-located with DB access functions which matter given how DB sensitive the uniqueness checker is. But I agree with the thrust of your argument.

2023-08-18 08:58 UTC, chrisr3 commented
> @chrisr3 not quite - it actually lives as part of the DB worker alongside the DB processor, with the idea being that it is then co-located with DB access functions which matter given how DB sensitive the uniqueness checker is. But I agree with the thrust of your argument.

OK. The problem with writing something like the driver is that you end up finding and using all the necessary components, but without always understanding where they fit into a _real_ Corda deployment :wink:.

But regardless, I had thought we'd discovered that our Kafka problem was _at least in part_ due to our unnecessarily sending messages over Kafka that could have been handled locally.

As an aside, I have previously (i.e. before R3) written servers for a micro-service architecture that was designed to communicate via HTTP(S), and IIRC it was very much an "eventually consistent" system requiring idempotent messaging. And it wasn't trivial to write either!

2023-08-18 13:20 UTC, Omar-awad commented
>I thought we'd established during the GA release cycle about the need to show a benefit from performance related changes? Can you point me to the evidence of the performance testing you've done to show that this change will be a positive one?

This change will not have performance improvements by itself as it is part of a bigger initiative which is documented in high level here: https://r3-cev.atlassian.net/wiki/spaces/CB/pages/4552491009/Corda+Scalable+Topology+Design. As of why we need this segregation then please refer to another PR comment here: https://github.com/corda/corda-runtime-os/pull/4465#issuecomment-1683769408 

> But regardless, I had thought we'd discovered that our Kafka problem was _at least in part_ due to our unnecessarily sending messages over Kafka that could have been handled locally, which could have been addressed without many of the efforts I am seeing now.

The two main issues we are tackling in the next release are:

 - Optimize the events flow in the system by reducing loops and congestion on some topics.
 - Revise heavy communication protocols in an effort to reduce the number of messages over-the-wire.

2023-08-18 13:32 UTC, chrisr3 commented
> > I thought we'd established during the GA release cycle about the need to show a benefit from performance related changes? Can you point me to the evidence of the performance testing you've done to show that this change will be a positive one?
> 
> This change will not have performance improvements by itself as it is part of a bigger initiative which is documented in high level here: https://r3-cev.atlassian.net/wiki/spaces/CB/pages/4552491009/Corda+Scalable+Topology+Design. As of why we need this segregation then please refer to another PR comment here: [#4465 (comment)](https://github.com/corda/corda-runtime-os/pull/4465#issuecomment-1683769408)

Actually, I think @relyafi was asking to examine the performance data that presumably underlies all these extensive architectural changes. I don't think that particular comment qualifies.

2023-08-18 13:35 UTC, Omar-awad commented
>Actually, I think [@relyafi](https://github.com/relyafi) was asking to examine the performance data that presumably underlies all these extensive architectural changes. I don't think that particular comment qualifies.

Please refer to the design document. The reasoning and the verification is documented there.

2023-08-18 14:20 UTC, relyafi commented
@Omar-awad:

> This change will not have performance improvements by itself as it is part of a bigger initiative which is documented in high level here: https://r3-cev.atlassian.net/wiki/spaces/CB/pages/4552491009/Corda+Scalable+Topology+Design.

Thanks for forwarding that document. The overall theoretical approach seems reasonable, but I don't see it mention splitting the uniqueness worker as one of its objectives? Combined with the fact that you say this has no performance benefits in and of itself, why do we feel this change is necessary at this point?

> The two main issues we are tackling in the next release are:
> 
> * Optimize the events flow in the system by reducing loops and congestion on some topics.
> * Revise heavy communication protocols in an effort to reduce the number of messages over-the-wire.

I don't see how this change addresses either of these issues? Uniqueness already has its own topic, and this change doesn't do anything with communication protocols.

> Please refer to the design document. The reasoning and the verification is documented there.

The only evidence I see in that document is a PoC, which I'm assuming has made a multitude of changes? It could be that the individual changes made in the PoC were a mix of positive, neutral, and negative, and on balance they turned out to be positive. That does not mean we can infer that every change in the PoC was a positive.

The only way to do that is A/B testing for a specific change we want to make. I think the following from the acceptance criteria of the document you linked backs this up:

_Implemented components should show clear value in being shipped._

As it stands, I don't think this PR passes that test.

2023-08-18 14:47 UTC, driessamyn approved these changes
Change LGTM and lines up with the intended design.

2023-08-18 14:58 UTC, relyafi requested changes, later dismissed
See Jira ticket for my comments.

2023-08-18 17:19 UTC, relyafi reviewed
See Jira ticket for my comments.

2023-08-18 17:27 UTC, relyafi reviewed
See Jira ticket for my comments.

2023-08-19 23:35 UTC, Omar-awad approved these changes
All good.

2023-08-21 09:08 UTC, ben-millar approved these changes
LGTM

2023-08-21 10:08 UTC, mcgovc commented on .ci/JenkinsfileSnykDelta
> +@Library('corda-shared-build-pipeline-steps@mbrkic-r3/CORE-16230/uniqueness-worker') _
```suggestion
@Library('corda-shared-build-pipeline-steps@5.1') _
```

2023-08-21 10:08 UTC, mcgovc commented on .ci/PublishHelmChart/Jenkinsfile_PublishHelmChart
> +@Library('corda-shared-build-pipeline-steps@mbrkic-r3/CORE-16230/uniqueness-worker') _
```suggestion
@Library('corda-shared-build-pipeline-steps@5.1') _
```

2023-08-21 10:08 UTC, mcgovc commented on .ci/e2eTests/Jenkinsfile
> +@Library('corda-shared-build-pipeline-steps@mbrkic-r3/CORE-16230/uniqueness-worker') _
```suggestion
@Library('corda-shared-build-pipeline-steps@5.1') _
```

2023-08-21 10:08 UTC, mcgovc commented on .ci/e2eTests/JenkinsfileCombinedWorker
> +@Library('corda-shared-build-pipeline-steps@mbrkic-r3/CORE-16230/uniqueness-worker') _
```suggestion
@Library('corda-shared-build-pipeline-steps@5.1') _
```

2023-08-21 10:08 UTC, mcgovc commented on .ci/e2eTests/JenkinsfileCombinedWorkerLinux
> +@Library('corda-shared-build-pipeline-steps@mbrkic-r3/CORE-16230/uniqueness-worker') _
```suggestion
@Library('corda-shared-build-pipeline-steps@5.1') _
```

2023-08-21 10:08 UTC, mcgovc commented on .ci/e2eTests/JenkinsfileCombinedWorkerWindows
> +@Library('corda-shared-build-pipeline-steps@mbrkic-r3/CORE-16230/uniqueness-worker') _
```suggestion
@Library('corda-shared-build-pipeline-steps@5.1') _
```

2023-08-21 10:08 UTC, mcgovc commented on .ci/e2eTests/JenkinsfileMultiClusterTest
> +@Library('corda-shared-build-pipeline-steps@mbrkic-r3/CORE-16230/uniqueness-worker') _
```suggestion
@Library('corda-shared-build-pipeline-steps@5.1') _
```

2023-08-21 10:08 UTC, mcgovc commented on .ci/e2eTests/JenkinsfileUnstableTest
> +@Library('corda-shared-build-pipeline-steps@mbrkic-r3/CORE-16230/uniqueness-worker') _
```suggestion
@Library('corda-shared-build-pipeline-steps@5.1') _
```

2023-08-21 10:08 UTC, mcgovc commented on .ci/e2eTests/ethereum/Jenkinsfile
> +@Library('corda-shared-build-pipeline-steps@mbrkic-r3/CORE-16230/uniqueness-worker') _
```suggestion
@Library('corda-shared-build-pipeline-steps@5.1') _
```

2023-08-21 10:08 UTC, mcgovc commented on .ci/nightly/JenkinsfileNightly
> +@Library('corda-shared-build-pipeline-steps@mbrkic-r3/CORE-16230/uniqueness-worker') _
```suggestion
@Library('corda-shared-build-pipeline-steps@5.1') _
```

2023-08-21 10:08 UTC, mcgovc commented on .ci/nightly/JenkinsfileSnykScan
> +@Library('corda-shared-build-pipeline-steps@mbrkic-r3/CORE-16230/uniqueness-worker') _
```suggestion
@Library('corda-shared-build-pipeline-steps@5.1') _
```

2023-08-21 10:08 UTC, mcgovc commented on .ci/nightly/JenkinsfileUnstableTests
> +@Library('corda-shared-build-pipeline-steps@mbrkic-r3/CORE-16230/uniqueness-worker') _
```suggestion
@Library('corda-shared-build-pipeline-steps@5.1') _
```

2023-08-21 10:08 UTC, mcgovc commented on .ci/nightly/JenkinsfileWindowsCompatibility
> +@Library('corda-shared-build-pipeline-steps@mbrkic-r3/CORE-16230/uniqueness-worker') _
```suggestion
@Library('corda-shared-build-pipeline-steps@5.1') _
```

2023-08-21 10:08 UTC, mcgovc commented on .ci/versionCompatibility/Jenkinsfile
> +@Library('corda-shared-build-pipeline-steps@mbrkic-r3/CORE-16230/uniqueness-worker') _
```suggestion
@Library('corda-shared-build-pipeline-steps@5.1') _
```

2023-08-21 10:08 UTC, mcgovc commented on .ci/versionCompatibility/latest-version.Jenkinsfile
> +@Library('corda-shared-build-pipeline-steps@mbrkic-r3/CORE-16230/uniqueness-worker') _
```suggestion
@Library('corda-shared-build-pipeline-steps@5.1') _
```

2023-08-21 10:08 UTC, mcgovc commented on Jenkinsfile
> +@Library('corda-shared-build-pipeline-steps@mbrkic-r3/CORE-16230/uniqueness-worker') _
```suggestion
@Library('corda-shared-build-pipeline-steps@5.1') _
```

2023-08-21 10:13 UTC, mcgovc approved these changes
LGTM

2023-08-21 10:15 UTC, ronanbrowne commented on Jenkinsfile
> +@Library('corda-shared-build-pipeline-steps@mbrkic-r3/CORE-16230/uniqueness-worker') _
Discussed here https://github.com/corda/corda-shared-build-pipeline-steps/pull/1061#issuecomment-1685923026 - will leave as is and address in second PR to minimize impacts

2023-08-21 11:20 UTC, thiagoviana approved these changes

2023-08-21 15:24 UTC, josephzunigadaly approved these changes

2023-08-21 15:48 UTC, oscardalmau-r3 approved these changes

2023-08-21 17:32 UTC, blsemo approved these changes
Looks ok to me.

2023-08-22 08:22 UTC, merged