CORE-16174 WIP initial commit of session init refactor
corda/corda-runtime-os pull request #4483
Opened 2023-08-17 10:44 UTC by LWogan

Please contact via slack for pr discussion

2023-08-21 13:14 UTC, ronanbrowne approved these changes
LGTM (Jenkins file / properties file changes only reviewed )

2023-08-23 11:22 UTC, JamesHR3 reviewed
I've assumed the TODOs are for a follow up in this feature branch. If not they should probably be resolved too.

2023-08-23 11:22 UTC, JamesHR3 commented on Jenkinsfile
> -    combinedWorkere2eTests: false,
Presumably you'll need to revert these changes?

2023-08-23 11:22 UTC, JamesHR3 commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/handlers/events/SessionEventHandler.kt
> +    private fun getSessionInitIfPresent(sessionEvent: SessionEvent?): SessionInit? {
Think you can rewrite this to be a little clearer:

```kotlin
return when (val payload = sessionEvent?.payload) {
    is SessionInit -> payload
    is SessionData -> payload.sessionInit
    else -> null
}
```

2023-08-23 11:22 UTC, JamesHR3 commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/handlers/requests/sessions/CloseSessionsRequestHandler.kt
> +        /*val checkpoint = context.checkpoint
Should this commented out code be removed?

2023-08-23 11:22 UTC, JamesHR3 commented on testing/cpbs/test-cordapp/src/main/kotlin/com/r3/corda/testing/smoketests/flow/InitiatedSmokeTestFlow.kt
> +        log.info("Starting initiated flow")
Do we still want this log?

2023-08-23 12:58 UTC, conalsmith-r3 commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/handlers/events/SessionEventHandler.kt
> +            payload
so SessionInit will still be sent when flow calls session.getCounterpartyInfo before any data has been transferred, would the counterparty info fit better in a SessionData so we can remove SessionInit from existing on its own entirely?

2023-08-23 13:23 UTC, owenstanford commented on components/flow/flow-mapper-impl/src/main/kotlin/net/corda/flow/mapper/impl/executor/SessionInitHelper.kt
> +                Record(Schemas.Flow.FLOW_EVENT_TOPIC, flowId, FlowEvent(flowId, sessionEvent))
for consistency is there a reason not to use the record factory for all records?

2023-08-23 13:40 UTC, conalsmith-r3 commented on components/flow/flow-mapper-impl/src/main/kotlin/net/corda/flow/mapper/impl/executor/SessionEventExecutor.kt
> +            sessionInitHelper.processSessionInit(sessionEvent, sessionInit, flowConfig, instant)
Should we also be recording metrics here for session inits? I.e. move 

```
            CordaMetrics.Metric.FlowMapperCreationCount.builder()
                .withTag(CordaMetrics.Tag.FlowEvent, sessionInit::class.java.name)
                .build().increment()
```
into the sessionInitHelper

2023-08-23 13:58 UTC, LWogan commented on Jenkinsfile
> -    combinedWorkere2eTests: false,
this change is the revert. they were disabled in the feature branch

2023-08-23 13:59 UTC, LWogan commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/handlers/requests/sessions/CloseSessionsRequestHandler.kt
> +        /*val checkpoint = context.checkpoint
yeah, theres a comment below. Separate task to do this properly.

2023-08-23 14:00 UTC, LWogan commented on testing/cpbs/test-cordapp/src/main/kotlin/com/r3/corda/testing/smoketests/flow/InitiatedSmokeTestFlow.kt
> +        log.info("Starting initiated flow")
Yeah i think its useful. there's logs on the initiating side but none this side.

2023-08-23 14:02 UTC, LWogan commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/handlers/events/SessionEventHandler.kt
> +            payload
CounterpartyInfo is stored in sessionContextProperties which is now set at SessionEvent level. 

It wouldnt fit in SessionData as you can ask for CounterpartyInfo when no data is being exchanged,

Theres other fields in SessionInit which are only sent 1 direction from initiator to initiated so I think we'll need that avro object going forward

2023-08-23 14:04 UTC, LWogan commented on components/flow/flow-mapper-impl/src/main/kotlin/net/corda/flow/mapper/impl/executor/SessionInitHelper.kt
> +                Record(Schemas.Flow.FLOW_EVENT_TOPIC, flowId, FlowEvent(flowId, sessionEvent))
I've only just merged the record factory pr into this one. I may need to ammend this.

2023-08-23 14:06 UTC, LWogan commented on components/flow/flow-mapper-impl/src/main/kotlin/net/corda/flow/mapper/impl/executor/SessionEventExecutor.kt
> +            sessionInitHelper.processSessionInit(sessionEvent, sessionInit, flowConfig, instant)
good spot!

2023-08-23 15:48 UTC, LWogan commented on components/flow/flow-mapper-impl/src/main/kotlin/net/corda/flow/mapper/impl/executor/SessionInitHelper.kt
> +                Record(Schemas.Flow.FLOW_EVENT_TOPIC, flowId, FlowEvent(flowId, sessionEvent))
updated

2023-08-25 09:14 UTC, simon-johnson-r3 requested changes

2023-08-25 09:14 UTC, simon-johnson-r3 commented on components/flow/flow-mapper-impl/src/main/kotlin/net/corda/flow/mapper/impl/executor/SessionEventExecutor.kt
> -        return if (flowMapperState == null) {
This is a matter of style preference I suppose, but Kotlin would let you write this more concisely, and specifically without the double check for `flowMapperState` being null which adds a bit of extra challenge to read:

```
override fun execute() = if (flowMapperState == null) {
  getInitPayload(sessionEvent.payload)?.let { sessionInit->
    sessionInitHelper.processSessionInit(sessionEvent, sessionInit, flowConfig, instant)
  } ?: handleNullState()
} else {
  processOtherSessionEvents(flowMapperState)
}

private fun getInitPayload(payload: Any) = when (payload) {
    is SessionInit -> payload
    is SessionData -> payload.sessionInit
    else -> null
}
```

2023-08-25 09:14 UTC, simon-johnson-r3 commented on components/flow/flow-mapper-impl/src/main/kotlin/net/corda/flow/mapper/impl/executor/SessionEventExecutor.kt
> +                //todo - CORE-15757/ CORE-16184
There are lots of debates about whether todo's in code are are good idea. Firstly I would say this should be `// TODO` which highlights the comment correctly in the IDE, but anyway, given this isn't really anything to do with this PR but instead a pointer in the code for some other developer to follow for some different ticket later on - perhaps just add a github link to this code line under the relevant tickets instead and delete the comment?

Not only would that alleviate the need for a discussion, but it would help those developers track the code down without having to rely on this.

2023-08-25 09:14 UTC, simon-johnson-r3 commented on components/flow/flow-mapper-impl/src/main/kotlin/net/corda/flow/mapper/impl/executor/SessionInitHelper.kt
> +     * Process a [sessionEvent] and [sessionInit] payload to producer a flow mapper state
typo: producer -> produce

2023-08-25 09:14 UTC, simon-johnson-r3 commented on components/flow/flow-mapper-impl/src/main/kotlin/net/corda/flow/mapper/impl/executor/SessionInitHelper.kt
> +class SessionInitHelper(private val recordFactory: RecordFactory) {
I find it odd to read in the code that a class called `helper` is instantiated. Not least because you instantiate it on behalf of its users and pass it around.

It's used by SessionEventExecutor and SessionInitExecutor and only has 1 public method, and it's only stateful purpose is to store `recordFactory`.

Could you just make `processSessionInit` a publicly accessible (static) function which takes `recordFactory` as a parameter as well, and call it direct in SessionEventExecutor and SessionInitExecutor (passing those the `recordFactory` on construction)?

2023-08-25 09:14 UTC, simon-johnson-r3 commented on components/flow/flow-mapper-impl/src/main/kotlin/net/corda/flow/mapper/impl/executor/SessionInitHelper.kt
> +
Again a minor style thing, but Kotlin allows you reduce functions which only return into aliases like:
```
    private fun getSessionInitOutputs(
        messageDirection: MessageDirection?,
        sessionEvent: SessionEvent,
        sessionInit: SessionInit,
        flowConfig: SmartConfig,
        instant: Instant
    ) = if (messageDirection == MessageDirection.INBOUND) {
```

I would consider this optional though.

2023-08-25 09:14 UTC, simon-johnson-r3 commented on components/flow/flow-mapper-impl/src/main/kotlin/net/corda/flow/mapper/impl/executor/SessionInitHelper.kt
> +    data class SessionInitOutputs(
should this be private?

2023-08-25 09:14 UTC, simon-johnson-r3 commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/application/sessions/impl/FlowSessionImpl.kt
> +            getFlowInfoFromSessionContext() ?: throw CordaRuntimeException(
Am I reading this correctly, you seem to have called this function already to set `counterPartyFlowInfo`?

2023-08-25 09:14 UTC, simon-johnson-r3 commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/application/sessions/impl/FlowSessionImpl.kt
> +    private fun getFlowInfoFromSessionProps(sessionProperties: KeyValuePairList?): FlowInfo? {
We seem to have evolved to a state where we have 2 helper functions which are only ever called from each other in one place? Perhaps this could be refactored a bit?

2023-08-25 09:14 UTC, simon-johnson-r3 commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/application/sessions/impl/FlowSessionImpl.kt
> +        if (sessionProperties == null) return null
this line is only here because line 61 allows nulls (the other call point already does a null check itself): `val sessionProperties = sessionState?.sessionProperties`

I wonder if the code can be refactored a little to avoid the need for it and make the two points consistently check for null?

My motivation here is that there are multiple return points in this method already.

2023-08-25 09:14 UTC, simon-johnson-r3 commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/handlers/events/SessionEventHandler.kt
> +            val sessionInit = getSessionInitIfPresent(nextSessionEvent)
I think this could do with a bit of refactoring. You pass `nextSessionEvent` to a function, and then on the next line ask if it's null. If it was null the function returns null anyway.

2023-08-25 09:14 UTC, simon-johnson-r3 commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/handlers/events/SessionEventHandler.kt
> +                    if (sessionEvent.payload is SessionInit) {
what if it isn't a SessionInit? Is it correct that case is not handled?

2023-08-25 09:14 UTC, simon-johnson-r3 commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/handlers/requests/SubFlowFinishedRequestHandler.kt
> +            //TODO - CORE-15757 / CORE-16184 do this properly
I don't think we can let this comment go into the open source repo. This is aside from whether we consider TODO's ok or not, we shouldn't let people believe we've committed code which doesn't work properly. Presumably you actually mean, this code works fine, but a different implementation is perhaps coming later. But that is potentially true of all code.

2023-08-25 09:14 UTC, simon-johnson-r3 commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/handlers/requests/SubFlowFinishedRequestHandler.kt
> +            }.onEach {
do you need a second loop here, could you not do a find and set the property in a single iteration?

2023-08-25 09:14 UTC, simon-johnson-r3 commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/handlers/requests/sessions/CloseSessionsRequestHandler.kt
> +        //TODO CORE-15757 / CORE-16184 - implement close properly
Same as above, let's not try to erroneously suggest we submit not working code.

2023-08-25 09:14 UTC, simon-johnson-r3 commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/handlers/requests/sessions/CloseSessionsRequestHandler.kt
> +            if (sessionsToClose.contains(it.sessionId))
If you want to split an `if` statement on multiple lines it's dangerous to not include braces. It's a common mistake that the next developer comes along an adds something at line 73 which they think is encapsulated within the `if` and isn't.

Personally I'd put all `if` code in braces to prevent this from ever happening, but at least please put it on one line. If it doesn't fit then revert to braces

2023-08-25 09:14 UTC, simon-johnson-r3 commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/sessions/impl/FlowSessionManagerImpl.kt
> +    ): SessionState {
Another style choice, but consider using `=`

2023-08-25 09:14 UTC, simon-johnson-r3 commented on libs/flows/session-manager-impl/src/main/kotlin/net/corda/session/manager/impl/SessionManagerImpl.kt
> +    ): SessionState {
Consider `=`

2023-08-25 09:14 UTC, simon-johnson-r3 commented on libs/flows/session-manager-impl/src/main/kotlin/net/corda/session/manager/impl/SessionManagerImpl.kt
> +        val messagesToReturn= handleSessionTimeouts(sessionState, config, instant, sessionEvents, identity)
typo missing space before =

2023-08-25 09:14 UTC, simon-johnson-r3 commented on libs/flows/session-manager-impl/src/main/kotlin/net/corda/session/manager/impl/SessionManagerImpl.kt
>          if (sessionEvents.isEmpty()) return emptyList()
in the current incarnation of the implementation if `sessionEvents` is empty, that is an empty list of session events, so that is not a special case and I think this line is not needed?

2023-08-25 09:14 UTC, simon-johnson-r3 commented on libs/flows/session-manager-impl/src/main/kotlin/net/corda/session/manager/impl/processor/SessionDataProcessorReceive.kt
> +        val sessionInit = payload.sessionInit
I think this code is saying we should handle either a sessionState or a sessionInit, and I think it's the same if you do the simpler:
```
if (sessionState != null) {
  getInboundDataEventResult(sessionState, sessionId)
} else if (sessionInit != null) {
  val newSessionState = sessionInitProcessorReceive.execute()
  getInboundDataEventResult(newSessionState, sessionId)
} else {
  ...
}
```
but please check this!

2023-08-25 09:14 UTC, simon-johnson-r3 commented on libs/flows/session-manager-impl/src/main/kotlin/net/corda/session/manager/impl/processor/SessionDataProcessorSend.kt
> +    private fun isInitiatedParty(sessionEvent: SessionEvent) : Boolean {
this logic appears in two places, consider making this a public helper is that's simple

2023-08-25 14:53 UTC, JamesHR3 commented on components/flow/flow-mapper-impl/src/main/kotlin/net/corda/flow/mapper/impl/executor/SessionInitExecutor.kt
> +    private val sessionInitHelper: SessionInitHelper,
Thinking about it - do you need `SessionInitExecutor` at all? We had this because we wanted quite different handling between session init messages and session data messages. However, we're now trying to do the same handling in both the "normal" session event handler and this session init handler. Can we just use a single session event handler to do this? Does that let you simplify the code in the mapper elsewhere?

2023-08-25 14:53 UTC, JamesHR3 commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/application/sessions/impl/FlowSessionImpl.kt
> +            getFlowInfoFromSessionContext() ?: throw CordaRuntimeException(
The `suspend` in the middle will cause this to return a different result when calling it a second time (assuming the response from the counterparty had the relevant information in).

2023-08-25 14:53 UTC, JamesHR3 commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/impl/FlowGlobalPostProcessorImpl.kt
> +        //TODO - CORE-15757 should we fail immediately here instead?
Did you make any progress on answering this question?

2023-08-25 14:53 UTC, JamesHR3 commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/runner/impl/FlowRunnerImpl.kt
>                  }
Isn't this now effectively a `null` check on `payload`?

2023-08-25 15:13 UTC, simon-johnson-r3 commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/application/sessions/impl/FlowSessionImpl.kt
> +            getFlowInfoFromSessionContext() ?: throw CordaRuntimeException(
Ok, the first time I guess we issue a request, from then on it's in the flow checkpoint.

2023-08-28 08:43 UTC, LWogan commented on components/flow/flow-mapper-impl/src/main/kotlin/net/corda/flow/mapper/impl/executor/SessionEventExecutor.kt
> +                //todo - CORE-15757/ CORE-16184
im merging to my feature branch, not release so i think this is  matter of personal preference.

2023-08-28 08:45 UTC, LWogan commented on components/flow/flow-mapper-impl/src/main/kotlin/net/corda/flow/mapper/impl/executor/SessionInitHelper.kt
> +class SessionInitHelper(private val recordFactory: RecordFactory) {
Ill make it a proper service and inject it where its required.

2023-08-28 08:55 UTC, LWogan commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/handlers/events/SessionEventHandler.kt
> +                    if (sessionEvent.payload is SessionInit) {
if its not a SessionInit, then theres nothing to do here. We only respond with a confirm if weve successfully initialize the checkpoint and the session event payload was a SesionInit. This can only happen when the user calls getCounterpartyInfo before any sends or receives are executed.

2023-08-28 08:56 UTC, LWogan commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/handlers/requests/SubFlowFinishedRequestHandler.kt
> +            //TODO - CORE-15757 / CORE-16184 do this properly
This is going into a feature branch as part of multiple prs. I don't see any issue with this

2023-08-28 08:59 UTC, LWogan commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/handlers/requests/SubFlowFinishedRequestHandler.kt
> +            }.onEach {
This is being written here https://github.com/corda/corda-runtime-os/pull/4482. The close handlers are not being worked on in this pr

2023-08-28 09:30 UTC, LWogan commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/impl/FlowGlobalPostProcessorImpl.kt
> +        //TODO - CORE-15757 should we fail immediately here instead?
I'm updating this to fail the flow immediately as we no longer support retries

2023-08-28 09:44 UTC, LWogan commented on components/flow/flow-mapper-impl/src/main/kotlin/net/corda/flow/mapper/impl/executor/SessionInitExecutor.kt
> +    private val sessionInitHelper: SessionInitHelper,
I've refactored this a bit per Simons comments. Its not massively different to what you reviewed though. Ill have a think on it.

2023-08-28 09:50 UTC, LWogan commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/runner/impl/FlowRunnerImpl.kt
>                  }
Not sure I follow. Its checking to see if this is the first event received (which can be an Init or Data). If it is, extract out the SessionInit object (to be used to get user/platform context properties from)

2023-08-29 07:45 UTC, LWogan commented on components/flow/flow-mapper-impl/src/main/kotlin/net/corda/flow/mapper/impl/executor/SessionEventExecutor.kt
> +                //todo - CORE-15757/ CORE-16184
After some discussions yesterday it looks like the close logic changes might not make it into our next release scheduled for friday so im going to update this pr to remove the TODOs

2023-08-29 08:23 UTC, simon-johnson-r3 commented on components/flow/flow-mapper-impl/src/main/kotlin/net/corda/flow/mapper/impl/executor/SessionEventExecutor.kt
> +                //todo - CORE-15757/ CORE-16184
> im merging to my feature branch, not release so i think this is matter of personal preference?

Sorry I didn't notice that. I was summoned to this review in slack.

2023-08-29 15:47 UTC, JamesHR3 commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/runner/impl/FlowRunnerImpl.kt
>                  }
`getInitPayload` returns `SessionInit?`, so `if (payload is SessionInit)` is now equivalent to `if (payload != null)`, which might be clearer.

2023-08-29 15:59 UTC, simon-johnson-r3 approved these changes

2023-08-30 05:50 UTC, LWogan commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/runner/impl/FlowRunnerImpl.kt
>                  }
applied

2023-08-30 08:32 UTC, merged