CORE-13624 Service side idempotency id for persistence requests
corda/corda-runtime-os pull request #4491
Opened 2023-08-18 12:12 UTC by kyriathar

2023-08-30 11:19 UTC, simon-johnson-r3 requested changes

2023-08-30 11:19 UTC, simon-johnson-r3 commented on components/persistence/entity-processor-service-impl/src/integrationTest/kotlin/net/corda/entityprocessor/impl/tests/PersistenceExceptionTests.kt
> +//    private lateinit var virtualNodeService: VirtualNodeService
commented out code?

2023-08-30 11:19 UTC, simon-johnson-r3 commented on components/persistence/entity-processor-service-impl/src/integrationTest/kotlin/net/corda/entityprocessor/impl/tests/PersistenceExceptionTests.kt
> +        // the below code block runs before every test
what is the thinking behind this over assigning them in @BeforeEach ?

2023-08-30 11:19 UTC, simon-johnson-r3 commented on components/persistence/entity-processor-service-impl/src/integrationTest/kotlin/net/corda/entityprocessor/impl/tests/PersistenceExceptionTests.kt
> +        assertNull(((record1.single().value as FlowEvent).payload as ExternalEventResponse).error)
consider creating a helper like:
`assertIsExternalEventResponseWithoutError(record1)`

2023-08-30 11:19 UTC, simon-johnson-r3 commented on components/persistence/entity-processor-service-impl/src/main/kotlin/net/corda/entityprocessor/impl/internal/EntityMessageProcessor.kt
> +        fun isDuplicateRequest(e: PersistenceException): Boolean =
Major: I would strongly recommend not trying to parse an assert message, which is not part of a managed api, and instead simply catch exceptions from each of the persist lines individually

I suggest something like this:
```
is PersistEntities -> {
    val requestId = UUID.fromString(request.flowExternalEventContext.requestId)
    
    val entityResponse = em.transaction {
        withDeduplicationCheck(requestId, it) {
          persistenceServiceInternal.persist(serializationService, it, entityRequest)
        }
    }
    responseFactory.successResponse(
        request.flowExternalEventContext,
        entityResponse
    )
}
// you don't need the try/catch any more
```
With the helper function:

```
private fun withDeduplicationCheck(requestId: UUID, entityManager: EntityManager, block:() -> EntityResponse): EntityResponse {
    try {
        requestsIdsRepository.persist(requestId, entityManager)
    } catch (e: PersistenceException) {
        // A persistence exception thrown in the de-duplication check means we have already performed the operation and
        // can therefore treat the request as successful
        return EntityResponse(emptyList(), KeyValuePairList(emptyList()))
    }
    return block()
}
```

2023-08-30 11:19 UTC, simon-johnson-r3 commented on components/persistence/entity-processor-service-impl/src/main/kotlin/net/corda/entityprocessor/impl/internal/EntityMessageProcessor.kt
> +                            EntityResponse(emptyList(), KeyValuePairList(emptyList()))
The merge function returns an entity response with information filled in here. Can you check that isn't important?

(I know this will change the nature of my suggestion above, but I think that's still a good solution, just might require some refinement)

2023-08-30 11:19 UTC, simon-johnson-r3 commented on components/persistence/persistence-service-common/src/main/kotlin/net/corda/persistence/common/internal/EntitySandboxServiceImpl.kt
> +                entityClasses + persistenceRequestIdEntityClass
I'm not entirely convinced JPA is helping you here. The INSERT statement for the request Id would be trivial to write, only needs to exists in one place, and means you don't need to worry about registering the Hibernate class like this.

2023-08-30 11:58 UTC, kyriathar commented on components/persistence/entity-processor-service-impl/src/integrationTest/kotlin/net/corda/entityprocessor/impl/tests/PersistenceExceptionTests.kt
> +        // the below code block runs before every test
So, these used to be in a `@BeforeEach` originally, then changed them [here](https://github.com/corda/corda-runtime-os/pull/4433/files#diff-1e11121a06b09f4342b336f579cd1a1746cdc152c25b9004c091cbc588efcc18R117) to before all thinking that the same `virtualNodeInfo` and `cpkFileHashes` are re-used across tests since we are loading the same CPB. However, that caused an issue where it would cache sandbox context and re-use it, where we need to create new one here for each test, so put them back.

2023-08-30 12:02 UTC, kyriathar commented on components/persistence/entity-processor-service-impl/src/integrationTest/kotlin/net/corda/entityprocessor/impl/tests/PersistenceExceptionTests.kt
> +        // the below code block runs before every test
Actually they were in a `@BeforeAll` function but registered in a `net.corda.testing.sandboxes.lifecycle.EachTestLifecycle` which runs before each test.

2023-08-30 12:04 UTC, kyriathar commented on components/persistence/entity-processor-service-impl/src/integrationTest/kotlin/net/corda/entityprocessor/impl/tests/PersistenceExceptionTests.kt
> +//    private lateinit var virtualNodeService: VirtualNodeService
Removed

2023-08-30 14:26 UTC, kyriathar commented on components/persistence/entity-processor-service-impl/src/integrationTest/kotlin/net/corda/entityprocessor/impl/tests/PersistenceExceptionTests.kt
> +        assertNull(((record1.single().value as FlowEvent).payload as ExternalEventResponse).error)
Done

2023-08-30 14:36 UTC, kyriathar commented on components/persistence/entity-processor-service-impl/src/main/kotlin/net/corda/entityprocessor/impl/internal/EntityMessageProcessor.kt
> +        fun isDuplicateRequest(e: PersistenceException): Boolean =
Good point! Changed to use `EntityManager.flush` instead, so we can get the PK constraint violation on persisting the request id rather than on committing the transaction.

2023-08-30 14:40 UTC, kyriathar commented on components/persistence/entity-processor-service-impl/src/main/kotlin/net/corda/entityprocessor/impl/internal/EntityMessageProcessor.kt
> +                            EntityResponse(emptyList(), KeyValuePairList(emptyList()))
Actually good catch. Merge needs duplicate-found path needs aligning with normal one to be made idempotent.

2023-09-01 07:36 UTC, kyriathar commented on components/persistence/persistence-service-common/src/main/kotlin/net/corda/persistence/common/internal/EntitySandboxServiceImpl.kt
> +                entityClasses + persistenceRequestIdEntityClass
Replaced entity with native query.

2023-09-05 12:51 UTC, simon-johnson-r3 commented on components/persistence/entity-processor-service-impl/src/integrationTest/kotlin/net/corda/entityprocessor/impl/tests/PersistenceExceptionTests.kt
> +        // the below code block runs before every test
Ok it appears `EachTestLifecycle` is a registered JUnit extension which handles the initializing and closing of sanboxes. You need to put this in a method because you OSGi inject the service which it targets.

i think that it's a bit odd to set this up in a `@BeforeAll` but I understand why now at least so let's not worry so much about it.

2023-09-05 13:01 UTC, simon-johnson-r3 commented on components/persistence/entity-processor-service-impl/src/main/kotlin/net/corda/entityprocessor/impl/internal/EntityMessageProcessor.kt
> +                    onDuplication = {
I would switch wound `onDuplication` and `block`, that way you can do

```
withDeduplicationCheck(...,  onDuplication = {}) {
    persistenceServiceInternal.persist(serializationService, it, entityRequest)
}
```
which reads more naturally for a "with" function.

2023-09-05 13:05 UTC, simon-johnson-r3 commented on components/persistence/entity-processor-service-impl/src/main/kotlin/net/corda/entityprocessor/impl/internal/EntityMessageProcessor.kt
> +            is MergeEntities -> {
I thought we were going to drop the dedeuplication check for merges?

Also I'm not sure returning `EntityResponse(entityRequest.entities` will work, don't you need to return the results of the last operation?

2023-09-06 14:06 UTC, simon-johnson-r3 approved these changes, later dismissed

2023-09-20 08:22 UTC, simon-johnson-r3 submitted a review, later dismissed

2023-09-20 12:31 UTC, davidcurrie submitted a review, later dismissed
LGTM

2023-09-20 12:56 UTC, davidcurrie approved these changes

2023-09-21 07:49 UTC, simon-johnson-r3 approved these changes

2023-09-21 07:55 UTC, merged