CORE-11675 remove the hard coded avro serializers from the producer and consumer builders
corda/corda-runtime-os pull request #4519
Opened 2023-08-24 08:11 UTC by ciaran238

2023-08-24 15:32 UTC, josephzunigadaly commented on libs/messaging/db-message-bus-impl/src/main/kotlin/net/corda/messagebus/db/serialization/CordaDBAvroSerializerImpl.kt
> +            val message = "Failed to serialize instance of class type ${data!!::class.java.name} containing $data"
We should avoid the `!!` operator here. We don't want to throw a null pointer exception while building our error message.

I'd also remove `$data` from the log message.

2023-08-24 15:35 UTC, josephzunigadaly commented on libs/messaging/kafka-message-bus-impl/src/main/kotlin/net/corda/messagebus/kafka/serialization/CordaAvroSerializerImpl.kt
> +            val message = "Failed to serialize instance of class type ${data!!::class.java.name} containing $data"
Same with this one

2023-08-24 16:14 UTC, simon-johnson-r3 requested changes

2023-08-24 16:14 UTC, simon-johnson-r3 commented on libs/serialization/serialization-avro/src/main/kotlin/net/corda/avro/serialization/CordaAvroSerializer.kt
> +    fun serialize(data: T?): ByteArray?
I don't like the fact we've polluted our Kotlin api to shoehorn this in as a Kafka `Serializer<>`, I suggest we revert this and resolve the null issue in the adaptor passed to `KafkaProducer`.

2023-08-24 16:14 UTC, simon-johnson-r3 commented on libs/messaging/kafka-message-bus-impl/src/main/kotlin/net/corda/messagebus/kafka/producer/builder/KafkaCordaProducerBuilderImpl.kt
> -                CordaAvroSerializerImpl(avroSchemaRegistry, onSerializationError)
Could we consider having an extension function for `CordaAvroSerializationFactory` which returns you a Kafka `Serializer<>`?

That function would return you an adaptor instead of defining one inline here. And it could deal with the possibility of being told to serialize null (see comment in `CordaAvroSerializer`.

Here it would look like `cordaAvroSerializationFactory.createAvroBasedKafkaSerializer(...)`

I think at the point of use that is quite expressive. What we have now is a little esoteric. It's probably fine to define that extension function in this file.

2023-08-24 16:14 UTC, simon-johnson-r3 commented on libs/messaging/db-message-bus-impl/src/main/kotlin/net/corda/messagebus/db/serialization/CordaDBAvroSerializerImpl.kt
> +    override fun serialize(data: T?): ByteArray? {
I assume you could revert this if you deal with the null in the adaptor as suggested in other comments.

2023-08-25 15:30 UTC, ben-millar approved these changes
For the serializer tests, I think I'd rather check the values too rather than just checking that the result isn't null, but I'll leave that up to you.

2023-08-25 15:30 UTC, ciaran238 commented on libs/messaging/kafka-message-bus-impl/src/main/kotlin/net/corda/messagebus/kafka/producer/builder/KafkaCordaProducerBuilderImpl.kt
> -                CordaAvroSerializerImpl(avroSchemaRegistry, onSerializationError)
I implemented this but have done so in a separate interface, I think it makes sense to separate it from the CordaAvroSerializationFactory

2023-08-30 13:17 UTC, josephzunigadaly approved these changes

2023-08-30 14:35 UTC, simon-johnson-r3 approved these changes

2023-12-18 00:18 UTC, closed without merging