Pranushan/CORE-16125 Enhance db utils sql server support
corda/corda-runtime-os pull request #4524
Opened 2023-08-24 13:23 UTC by PranushanR3

This PR is adds support for SQL server

2023-08-24 16:38 UTC, blsemo reviewed
Could we structure the change so that all the tests use the abstract DbUtils class, and we inject the implementation at runtime - so that testing everything against a different database does not require changing the code everywhere?

2023-08-24 16:38 UTC, blsemo commented on build.gradle
> +        inputs.property('sqlPassword',sqlPassword)
Does `sql` stand for SqlServer here? If yes, that is a bit confusing, as it could also mean generic sql database. Probably better to either use `mssqlPort` or `sqlserverPort`.

2023-08-24 16:38 UTC, blsemo commented on testing/db-testkit/src/main/kotlin/net/corda/db/testkit/DbUtilsAbstract.kt
> +abstract class DbUtilsAbstract {
The name is rather unconventional. Should either be `AbstractDbUtils` or `DbUtilsBase`.

2023-08-29 09:16 UTC, relyafi requested changes
I'm a bit concerned at the number of files that have had to change in this PR, and the fact that pretty much all tests are now using a `PostgresDbUtils` library. Ultimately, all of these tests should work with SQL server, and indeed any other arbitrary future database we add.

With that in mind, I would expect us to maintain a single `DbUtils` library, which instantiates the correct connection based on which properties were set. Setting both postgres as sql server properties at the same time should cause failure, and this can be validated at runtime. As it stands, it's not clear to me how we would run the tests with SQL server.

If we go with this approach, then I think this PR becomes a much smaller change.

I also think there needs to be a clearer description on the PR, and notes on how we tested.

2023-08-29 09:16 UTC, relyafi commented on build.gradle
> +        systemProperty 'sqlPassword',sqlPassword
I think these should match the properties set earlier.
```suggestion
        systemProperty 'mssqlPort', sqlPort
        systemProperty 'mssqlUser',sqlUser
        systemProperty 'mssqlPassword',sqlPassword
```

2023-08-29 09:16 UTC, relyafi commented on gradle.properties
> +# The user should be set to sa as SQL server defaults to this when starting up
I think it needs to be made clearer that these are still related to the above DB integration test settings, and are mutually exclusive with the Postgres settings.

2023-08-29 09:16 UTC, relyafi commented on libs/db/db-core/src/main/kotlin/net/corda/db/core/SQLDataSourceFactory.kt
> +class SQLDataSourceFactory(
```suggestion
class MsSqlDataSourceFactory(
```

2023-08-30 14:24 UTC, simon-johnson-r3 commented
A summary of my thoughts on this change is that we've ended up with a design with a class hierarchy to manage just a single string with the driver class defined in it, but where we have a genuine and significant change in functional behaviour (in DbUtils) we have gone for conditional code based on booleans.

It feels like we've done this the wrong way round, that the data source factory is pretty generic and can be a single class with a driver injected when instantiated, and the DbUtils is the place where the real changes are needed and that should be split into a more OO approach?

For example, in DbUtils we've ended up with this:
```
fun createDataSource(

  if (!isPostgres) {
    val factory = PostgresDataSourceFactory()
  
  else {
    val factory = SQLDataSourceFactory()
```
So we've wrapped an OO based factory with a non OO factory method.

Much of what is here now is probably emergent design centred around the fact we have hard coded Postgres support in the past. I would suggest instead of worrying about what's in the code now, start by drawing out what we want the class hierarchy and factory scheme to look like for its client code.

2023-08-30 14:28 UTC, simon-johnson-r3 requested changes
See previous comment.

2023-08-31 07:55 UTC, simon-johnson-r3 commented
Could you switch the title of the PR, the ticket is `CORE-16215`

2023-09-04 12:56 UTC, relyafi reviewed
This looks like a much more scalable solution now. I still think there's room to improve the maintainability - see specific comments.

There's also quite a few unnecessary changes to whitespace, variable names, and import ordering. I've commented where I've spotted these, but please review and make sure that these are corrected, and ensure that new code is also following the standard whitespace conventions.

Finally, the general comment from my last review still applies - there needs to be a clearer description on the PR, and notes on how we tested. We should confirm that HSQLDB, Postgres and MS SQL all run correctly following these changes.

2023-09-04 12:56 UTC, relyafi commented on libs/db/db-core/src/main/kotlin/net/corda/db/core/SQLDataSourceFactory.kt
> +class SQLDataSourceFactory(
> I think this comment is still relevant, would also rename file to reflect updated class name

2023-09-04 12:56 UTC, relyafi commented on testing/db-testkit/src/main/kotlin/net/corda/db/testkit/DbUtils.kt
> +import net.corda.schema.configuration.DatabaseConfig
Not sure why we changed the existing import ordering? I'd put them in order as this aids maintainability. You can also use the "optimize imports" option by right clicking on the file in the project explorer in IntelliJ, and it will apply the correct ordering for you.

2023-09-04 12:56 UTC, relyafi commented on testing/db-testkit/src/main/kotlin/net/corda/db/testkit/DbUtils.kt
> +        inMemoryDbName : String,
Unnecessary (and inconsistent) change?

2023-09-04 12:56 UTC, relyafi commented on testing/db-testkit/src/main/kotlin/net/corda/db/testkit/DbUtils.kt
> +    ):EntityManagerConfiguration{
```suggestion
    ):EntityManagerConfiguration {
```

Again, unnecessary (and incorrect) whitespace change

(This looks to be a recurring theme in the PR - please review all instances and revert where necessary)

2023-09-04 12:56 UTC, relyafi commented on testing/db-testkit/src/main/kotlin/net/corda/db/testkit/DbUtils.kt
> +        }
This approach works, but it may become unwieldy as we add more databases.

Ultimately we know what each database type needs to supply, it's effectively the information that each function returns in this object. I wonder if it might be cleaner and more scalable to define an interface which specifies each of these functions, have a different implementation for each DB type, and then have the `DBUtils` construct one of these classes once as part of initialisation?

That means that the implementation for each DB type would be separated into different classes / files, and we'd only need to do the if statement once on initialisation here. All the functions could then just delegate to the specific DB class.

2023-09-04 12:56 UTC, relyafi commented on testing/db-testkit/src/main/kotlin/net/corda/db/testkit/DbUtils.kt
> +            var jdbcurl = "jdbc:postgresql://$host:$port/$db"
```suggestion
            var jdbcUrl = "jdbc:postgresql://$host:$port/$db"
```

Use camel-case for `jdbcUrl`. Previously it was like this, so not sure why it was changed. There's a few instances of this,  they should all be corrected.

2023-09-04 12:56 UTC, relyafi commented on gradle.properties
> +# The user should be set to sa as SQL server defaults to this when starting up
This suggests the property needs setting to this. But we already default in the code, so I don't think this is true?

What are we saying here? If we are saying that the user _must_ always be sa, then there's no point in having the property. If it _could_ be different (which I suspect it could be if someone overrode the name when provisioning the container), then it doesn't seem any different from Postgres, and doesn't need to be explicitly called out?

2023-09-04 12:56 UTC, relyafi commented on gradle.properties
> +# DB integration tests
```suggestion
# DB integration tests (MS SQL)
```

Would also make it clear in these comments that only one set of DB-specific properties should be set. I'd also update the Postgres comments to reflect the above, and update / remove line 152 (which is now inaccurate)

2023-09-05 10:29 UTC, blsemo reviewed
I don't think it's quite there yet.
I would imagin HSQL to have its own helper, not be a sub-case of Postgres. That would also allow to clean up the interface and thus the other implementations.

2023-09-05 10:29 UTC, blsemo commented on libs/db/db-core/src/main/kotlin/net/corda/db/core/BaseDataSourceFactory.kt
> +class BaseDataSourceFactory(
```suggestion
class DataSourceFactory(
```
Not actually a base class anymore.

2023-09-05 10:29 UTC, blsemo commented on testing/db-testkit/src/main/kotlin/net/corda/db/testkit/DbUtils.kt
> +    val isInMemory: Boolean
I think the `inMemory` should be a third helper implementation, not a special case on the postgres one.

2023-09-05 10:29 UTC, blsemo commented on testing/db-testkit/src/main/kotlin/net/corda/db/testkit/DbUtils.kt
> +    override val isInMemory = System.getProperty(MSSQL_PORT_PROPERTY).isNullOrBlank()
Shouldn't this always be `false` for MS SQL?

2023-09-05 13:28 UTC, blsemo reviewed
Getting there, but I think it needs a bit of extra clean-up.

2023-09-05 13:28 UTC, blsemo commented on testing/db-testkit/src/main/kotlin/net/corda/db/testkit/DbUtils.kt
>                  .withValue(DatabaseConfig.DB_PASS, ConfigValueFactory.fromAnyRef(password))
I think the else branch should be an error now - when using HSQL, we should not use the PostgresHelper.

2023-09-05 13:28 UTC, blsemo commented on libs/db/db-core/src/main/kotlin/net/corda/db/core/DBBaseDataSourceFactory.kt
> +class DBBaseDataSourceFactory(
Do we actually still need this class? All it does is capturing the HikariDataSourceFactory, so maybe a free standing `createDatasource()` method would do?

2023-09-05 13:28 UTC, blsemo commented on testing/db-testkit/src/main/kotlin/net/corda/db/testkit/DbUtils.kt
> +    override fun getAdminUser() = if (isInMemory()) "sa" else getPropertyNonBlank("postgresUser","postgres")
You can hardcode this one to `sa` - it's always in memory.
Similar for a lot of other occurences in this file - whenever `isInMemory` is constant, you can remove the extra if checks.

2023-09-05 13:28 UTC, blsemo commented on testing/db-testkit/src/main/kotlin/net/corda/db/testkit/DbUtils.kt
> +        logger.info("Using in-memory (HSQL) DB".emphasise())
Should probably check that `inMemoryDbName` is not blank.

2023-09-05 13:28 UTC, blsemo commented on testing/db-testkit/src/main/kotlin/net/corda/db/testkit/DbUtils.kt
> +    val isNotMSSQL = System.getProperty("mssqlPort").isNullOrBlank()
```suggestion
    val isPostgres = !System.getProperty("postgresPort").isNullOrBlank()
    val isMSSQL = !System.getProperty("mssqlPort").isNullOrBlank()
```

2023-09-05 13:28 UTC, blsemo commented on testing/db-testkit/src/main/kotlin/net/corda/db/testkit/DbUtils.kt
> +        !isNotMSSQL -> SQLServerHelper()
Should probably check that not MsSql and Postgres have both been set.

2023-09-05 13:28 UTC, blsemo commented on testing/db-testkit/src/main/kotlin/net/corda/db/testkit/DbUtils.kt
> +    var utilsHelper: DbUtilsHelper = when {
Could this be `val`? Shouldn't change in the lifetime of the process.

2023-09-05 13:28 UTC, blsemo commented on testing/db-testkit/src/main/kotlin/net/corda/db/testkit/DbUtils.kt
Ideally split this file into separate files per class. Also, please sort out the formatting - there are a few cases of double empty lines, and a few functions have no empty lines between them.

2023-09-05 14:34 UTC, PranushanR3 commented on libs/db/db-core/src/main/kotlin/net/corda/db/core/DBBaseDataSourceFactory.kt
> +class DBBaseDataSourceFactory(
Left this the same as this class is still being used in other places other than the DbUtills. Changing this would require refactoring those other files such as `PostgresEntityMangerConfigurationTest. `

2023-09-05 15:48 UTC, blsemo reviewed
Nearly there, a few more remarks...

2023-09-05 15:48 UTC, blsemo commented on libs/db/db-core/src/main/kotlin/net/corda/db/core/DBBaseDataSourceFactory.kt
> +class DBBaseDataSourceFactory(
Hmm, but you still need to touch all those places because you changed the name of the class - I still don't see the point of this class in the current form.

2023-09-05 15:48 UTC, blsemo commented on libs/messaging/db-message-bus-impl/src/main/kotlin/net/corda/messagebus/db/persistence/DbUtils.kt
> +        DBBaseDataSourceFactory(HikariDataSourceFactory()).create(
```suggestion
        DBBaseDataSourceFactory().create(
```
No point adding the default arg here.

2023-09-05 15:48 UTC, blsemo commented on testing/db-testkit/src/main/kotlin/net/corda/db/testkit/PostgresHelper.kt
> +class PostgresHelper : DbUtilsHelper{
These helpers look like they have a lot of overlap - could you check if we can have a base class that implements the shared bits, and only specialise the bits that are genuinely different?

2023-09-07 10:28 UTC, blsemo approved these changes, later dismissed
Looks good to me.

2023-09-07 15:00 UTC, blsemo commented on testing/db-testkit/src/main/kotlin/net/corda/db/testkit/AbstractDBHelper.kt
> +            .withValue(DatabaseConfig.DB_PASS, ConfigValueFactory.fromAnyRef(password))
Slighly more kotlin-y (and less code duplication)
```suggestion
        val currentJdbcUrl = if(!schemaName.isNullOrBlank()) "$jdbcUrl?currentSchema=$schemaName" else jdbcUrl
        return ConfigFactory.empty()
            .withValue(DatabaseConfig.JDBC_URL, ConfigValueFactory.fromAnyRef(currentJdbcUrl))
            .withValue(DatabaseConfig.DB_USER, ConfigValueFactory.fromAnyRef(user))
            .withValue(DatabaseConfig.DB_PASS, ConfigValueFactory.fromAnyRef(password))
```

2023-09-07 16:20 UTC, blsemo submitted a review, later dismissed
LGTM

2023-09-08 08:53 UTC, relyafi reviewed
PR description / test notes broadly looks good now. Appreciate that we won't get a successful run of the full tests with SQL server as we do have further changes needed to support this, butI  think we should at least try and get one successful test case from our existing set of tests to show we were able to connect / read / write to SQL server.

2023-09-08 08:53 UTC, relyafi commented on libs/db/db-core/src/main/kotlin/net/corda/db/core/BaseDataSourceFactory.kt
> +class BaseDataSourceFactory(
Is `BaseDataSourceFactory` still an accurate name, given this is now just the singular implementation (after the latest changes)? I wonder if this should just be `DataSourceFactory` (maybe too generic?) or `CordaDataSourceFactory`?

2023-09-08 08:53 UTC, relyafi commented on build.gradle
> +        systemProperty 'mssqlPassword',mssqlPassword
```suggestion
        systemProperty 'mssqlUser', mssqlUser
        systemProperty 'mssqlPassword', mssqlPassword
```

2023-09-08 08:53 UTC, relyafi commented on testing/db-testkit/src/main/kotlin/net/corda/db/testkit/AbstractDBHelper.kt
> +abstract class AbstractDBHelper : DbUtilsHelper{
```suggestion
abstract class AbstractDBHelper : DbUtilsHelper {
```

2023-09-08 08:53 UTC, relyafi commented on testing/db-testkit/src/main/kotlin/net/corda/db/testkit/AbstractDBHelper.kt
> +abstract class AbstractDBHelper : DbUtilsHelper{
This class may benefit from a KDoc description explaining its purpose.

2023-09-08 08:53 UTC, relyafi commented on testing/db-testkit/src/main/kotlin/net/corda/db/testkit/AbstractDBHelper.kt
> +        if(!schemaName.isNullOrBlank()){
```suggestion
        if (!schemaName.isNullOrBlank()) {
```

2023-09-08 08:53 UTC, relyafi commented on testing/db-testkit/src/main/kotlin/net/corda/db/testkit/AbstractDBHelper.kt
> +            if(createSchema){
```suggestion
            if (createSchema) {
```

2023-09-08 08:53 UTC, relyafi commented on testing/db-testkit/src/main/kotlin/net/corda/db/testkit/AbstractDBHelper.kt
> +        }else{
```suggestion
        val currentJdbcUrl = if (!schemaName.isNullOrBlank()) {
            "$jdbcUrl?currentSchema=$schemaName"
        } else {
```

2023-09-08 08:53 UTC, relyafi commented on testing/db-testkit/src/main/kotlin/net/corda/db/testkit/DbUtilsHelper.kt
> +interface DbUtilsHelper {
This may also benefit from a KDoc.

2023-09-08 08:53 UTC, relyafi commented on testing/db-testkit/src/main/kotlin/net/corda/db/testkit/DbUtilsHelper.kt
> +            conn.prepareStatement("CREATE SCHEMA IF NOT EXISTS $schemaName;").execute()
Is this SQL database agnostic?

2023-09-08 08:53 UTC, relyafi commented on testing/db-testkit/src/main/kotlin/net/corda/db/testkit/HSQLHelper.kt
> +        if(inMemoryDbName.isBlank()){
```suggestion
        if (inMemoryDbName.isBlank()) {
```

2023-09-08 10:31 UTC, PranushanR3 commented on testing/db-testkit/src/main/kotlin/net/corda/db/testkit/DbUtilsHelper.kt
> +            conn.prepareStatement("CREATE SCHEMA IF NOT EXISTS $schemaName;").execute()
Just looked it up and seems like it needs a different statement. It should be more along the line of 
```
IF NOT EXISTS (SELECT schema_name FROM information_schema.schemata WHERE schema_name = 'YourSchemaName')
BEGIN
    EXEC('CREATE SCHEMA YourSchemaName')
END
```
Will try get this changed today before I head out

2023-09-08 10:46 UTC, simon-johnson-r3 requested changes

2023-09-08 10:46 UTC, simon-johnson-r3 commented on testing/db-testkit/src/main/kotlin/net/corda/db/testkit/DbUtilsHelper.kt
> +    fun getPropertyNonBlank(key: String, defaultValue: String): String {
This method sticks out here. I understand you want a generic helper method to do this, but I would separate those out from the polymorphic helpers on a per db level.

2023-09-11 14:23 UTC, relyafi commented on testing/db-testkit/src/main/kotlin/net/corda/db/testkit/dbutilsimpl/HelperUtils.kt
> +}
I wonder if this should be wrapped in an `object` to provide a namespace? The function name alone feels generic enough it could clash with other things. Or maybe these should just be moved to the existing `DbUtils` file in the testkit? This doesn't necessarily feel specific to our helpers.

2023-09-11 14:48 UTC, simon-johnson-r3 submitted a review, later dismissed

2023-09-12 08:11 UTC, wzur-r3 submitted a review, later dismissed
LGTM for Gradle configuration files

2023-09-12 14:16 UTC, blsemo commented
I managed to run the test `EntitiesInBundlesTest` against Sqlserver, ensuring it uses the correct database and schema as specified by the test.
![image](https://github.com/corda/corda-runtime-os/assets/1558288/dc0bece3-12aa-494a-ba41-a57135307a09)

2023-09-14 15:19 UTC, nkovacsx commented on libs/db/osgi-integration-tests/build.gradle
> +    integrationTestRuntimeOnly "com.microsoft.sqlserver:mssql-jdbc:11.2.3.jre17"
Shouldn't we have a property for this driver version instead of just hardcoding it?

2023-09-14 15:23 UTC, nkovacsx commented on testing/db-testkit/src/main/kotlin/net/corda/db/testkit/dbutilsimpl/PostgresHelper.kt
> +            conn.prepareStatement("CREATE SCHEMA IF NOT EXISTS $schemaName;").execute()
do we need to do this for Postgres? Shouldn't this just be a noop?

2023-09-14 15:27 UTC, nkovacsx commented on testing/db-testkit/src/main/kotlin/net/corda/db/testkit/dbutilsimpl/AbstractDBHelper.kt
> +    abstract fun createSchema(connection: Connection, schemaName: String): Pair<String, String>
Maybe this should be called something more explicit as it is quite confusing why a schema creation would return a `Pair<String, String>`. Probably `createSchemaAndUser` or `initialiseSchemaAndUser`?

2023-09-14 15:29 UTC, nkovacsx commented on libs/db/osgi-integration-tests/build.gradle
> +    integrationTestRuntimeOnly "com.microsoft.sqlserver:mssql-jdbc:11.2.3.jre17"
Just see this was fixed now.

2023-09-14 15:31 UTC, nkovacsx commented on testing/db-testkit/src/main/kotlin/net/corda/db/testkit/dbutilsimpl/AbstractDBHelper.kt
> +        logger.info("Using URL $jdbcUrl".emphasise())
Probably don't need to log this twice.

2023-09-14 15:32 UTC, blsemo commented on testing/db-testkit/src/main/kotlin/net/corda/db/testkit/dbutilsimpl/PostgresHelper.kt
> +            conn.prepareStatement("CREATE SCHEMA IF NOT EXISTS $schemaName;").execute()
What should be a no op here?

2023-09-15 09:27 UTC, relyafi commented on testing/db-testkit/src/main/kotlin/net/corda/db/testkit/dbutilsimpl/PostgresHelper.kt
> +            conn.prepareStatement("CREATE SCHEMA IF NOT EXISTS $schemaName;").execute()
Yeah I think we still need to create a schema, we were doing this before right? It's just that MS SQL has different syntax?

2023-09-15 09:33 UTC, relyafi approved these changes, later dismissed
LGTM

2023-09-15 12:17 UTC, mbrkic-r3 commented on build.gradle
> +        inputs.property('mssqlPort', mssqlPort)
Are we going to use all types of databases or just one of them (in which case we could use same properties e.g. `dbType`, `dbUser`, etc)?

2023-09-15 12:17 UTC, mbrkic-r3 commented on libs/db/db-core/src/test/kotlin/PostgresEntityManagerConfigurationTest.kt
> +        createDataSource(
Why don't we use `PostgresHelper.createDataSource()` here?

2023-09-15 12:17 UTC, mbrkic-r3 commented on libs/messaging/db-message-bus-impl/src/main/kotlin/net/corda/messagebus/db/persistence/DbUtils.kt
> +        createDataSource(
Why don't we use `PostgresHelper.createDataSource()` here?

2023-09-15 12:17 UTC, mbrkic-r3 commented on libs/messaging/db-topic-admin-impl/src/main/kotlin/net/corda/libs/messaging/topic/factory/DBTopicUtilsFactory.kt
> +            createDataSource(
Why don't we use `PostgresHelper.createDataSource()` here?

2023-09-15 12:17 UTC, mbrkic-r3 commented on testing/db-testkit/src/main/kotlin/net/corda/db/testkit/DbUtils.kt
> +    private val utilsHelper: DbUtilsHelper = when {
If only one should be set then it would be better to have generic parameters (that includes DB type).

2023-09-15 12:17 UTC, mbrkic-r3 commented on testing/db-testkit/src/main/kotlin/net/corda/db/testkit/dbutilsimpl/AbstractDBHelper.kt
> +                "$jdbcUrl?currentSchema=$schemaName&reWriteBatchedInserts=true"
Isn't this Postgres specific?

2023-09-15 12:17 UTC, mbrkic-r3 commented on testing/db-testkit/src/main/kotlin/net/corda/db/testkit/dbutilsimpl/HelperUtils.kt
> +fun getPropertyNonBlank(key: String, defaultValue: String): String {
Do we need this function, could we use `System.getProperty(key, defaultValue)` instead?

2023-09-15 12:17 UTC, mbrkic-r3 commented on testing/db-testkit/src/main/kotlin/net/corda/db/testkit/dbutilsimpl/SQLServerHelper.kt
> +                conn.prepareStatement("IF NOT EXISTS ( SELECT  * FROM sys.schemas WHERE   name = N'$schemaName' )\n" +
This might be more readable by using multiline string and `trimIndent()`.

2023-09-15 13:18 UTC, blsemo commented on libs/messaging/db-message-bus-impl/src/main/kotlin/net/corda/messagebus/db/persistence/DbUtils.kt
> +        createDataSource(
I don't think we want to use code from Testkit here? This is main, i.e. potentially prod code.

2023-09-15 13:19 UTC, blsemo commented on testing/db-testkit/src/main/kotlin/net/corda/db/testkit/dbutilsimpl/AbstractDBHelper.kt
> +                "$jdbcUrl?currentSchema=$schemaName&reWriteBatchedInserts=true"
Good point - that whole method needs more looking at.

2023-09-15 13:19 UTC, blsemo commented on testing/db-testkit/src/main/kotlin/net/corda/db/testkit/DbUtils.kt
> +    private val utilsHelper: DbUtilsHelper = when {
I am not sure I understand the comment? What should be a generic parameter on what?

2023-09-15 13:27 UTC, mbrkic-r3 commented on libs/messaging/db-message-bus-impl/src/main/kotlin/net/corda/messagebus/db/persistence/DbUtils.kt
> +        createDataSource(
Right, I've missed that. Wouldn't be better to have a class for Postgres that can be used for prod code packages so it's clear this doesn't work with all database types?

2023-09-15 13:31 UTC, mbrkic-r3 commented on testing/db-testkit/src/main/kotlin/net/corda/db/testkit/DbUtils.kt
> +    private val utilsHelper: DbUtilsHelper = when {
e.g. instead of having properties "postgresPort" and "mssqlPort" to have generic property "dbPort", and then additionally, property "dbType" based on which we choose the helper below.

2023-09-15 16:42 UTC, blsemo commented on testing/db-testkit/src/main/kotlin/net/corda/db/testkit/dbutilsimpl/HelperUtils.kt
> +fun getPropertyNonBlank(key: String, defaultValue: String): String {
I've tried it - but it behaves differnetly - it returns a blank string if the property is defined without value rather than the default.

2023-09-18 14:24 UTC, blsemo commented on libs/messaging/db-message-bus-impl/src/main/kotlin/net/corda/messagebus/db/persistence/DbUtils.kt
> +        createDataSource(
We had that - but the only diff for different databases was just the driver class/jdbc URL, so having a differnent class literally wrapping two strings for each DB was deemed too repetitive.

2023-09-19 09:10 UTC, relyafi reviewed
Some minor comments.

Also, there may be follow-up actions required on merging this PR, as we are breaking backwards compatibility by removing the postgres specific system properties. We should probably put out a message to engineers to tell people about this change, and this will also likely require updating of Jenkinsfiles so the CI builds don't break.

2023-09-19 09:10 UTC, relyafi commented on gradle.properties
> +# Only one set of these properties need to be set, either the postgres details or the mssql details. If neither set it falls back to HSQL (in-memory)
This comment needs updating to reflect the new properties

2023-09-19 09:10 UTC, relyafi commented on components/uniqueness/backing-store-impl/src/backingStoreBenchmark/README.md
>     properties as used by other database based tests in this repo.
```suggestion
   production grade database, and is unlikely to provide realistic results. Additional
   properties, such as user, password etc. can also be specified. These are the same set of
   properties as used by other database based tests in this repo.
```

2023-09-19 09:10 UTC, relyafi commented on components/ledger/ledger-persistence/src/integrationTest/kotlin/net/corda/ledger/persistence/utxo/tests/UtxoLedgerMessageProcessorTests.kt
> + *     gradlew integrationTest -PdatabaseType=POSTGRES [-PdatabaseAdminPassword=<password> -PdatabaseAdminUser=<user>]
This isn't an exhaustive list of arguments - might be better to just refer to the optional arguments defined in the gradle config?

2023-09-19 09:10 UTC, relyafi commented on libs/db/readme.md
> +
This content looks good, but we might need to review the document structure, as this currently sits under a Postgres heading, and this content is not Postgres specific.

2023-09-19 09:10 UTC, relyafi commented on testing/db-testkit/src/main/kotlin/net/corda/db/testkit/DbUtils.kt
> +    val isInMemory = utilsHelper.isInMemory()
Does this need to be a DB specific attribute, or is this implied by being `DatabaseType.HSQL`?

2023-09-19 09:10 UTC, relyafi commented on testing/db-testkit/src/main/kotlin/net/corda/db/testkit/dbutilsimpl/HelperUtils.kt
> +}
@blsemo think this still applies?

2023-09-19 15:29 UTC, driessamyn approved these changes, later dismissed
LGTM

2023-11-01 07:58 UTC, wzur-r3 submitted a review, later dismissed
LGTM

2023-11-13 18:14 UTC, closed without merging

2023-11-13 18:14 UTC, blsemo commented
Closing to re-open clean PR against 5.2