CORE-15756 Segregated and Granular Corda Workers
corda/corda-runtime-os pull request #4528
Opened 2023-08-25 06:14 UTC by mbrkic-r3

Following logistical changes were implemented (components and messaging transport used for their communication stay the same):

- Created PersistenceProcessor that uses LedgerPersistenceService and FlowPersistenceService (they are not used anymore in DB worker).

- Created PersistenceWorker that uses PersistenceProcessor.

2023-08-31 00:23 UTC, ben-millar approved these changes, later dismissed

2023-08-31 11:54 UTC, mcgovc commented
See comment - https://github.com/corda/corda-shared-build-pipeline-steps/pull/1108#issuecomment-1700897299

2023-08-31 14:08 UTC, wzur-r3 submitted a review, later dismissed
LGTM

2023-08-31 14:23 UTC, davidcurrie reviewed
LGTM for @corda/cluster-management - will approve once TODOs are resolved

2023-08-31 15:04 UTC, simon-johnson-r3 commented on charts/corda/values.yaml
> +    clusterDbConnectionPool:
We may find this triggers some database connection errors in pipelines. This is not necessarily the end of the world as our dev-prereqs still has the max allowed connections set quite low and we can increase it further. Just a heads up.

2023-08-31 15:35 UTC, simon-johnson-r3 submitted a review, later dismissed

2023-08-31 16:01 UTC, thiagoviana submitted a review, later dismissed
LGTM

2023-08-31 16:02 UTC, davidcurrie approved these changes, later dismissed
LGTM

2023-08-31 16:33 UTC, davidcurrie approved these changes
Still LGTM!

2023-08-31 16:33 UTC, thiagoviana approved these changes

2023-08-31 16:33 UTC, ben-millar approved these changes

2023-08-31 16:36 UTC, simon-johnson-r3 approved these changes

2023-08-31 16:37 UTC, mcgovc approved these changes
LGTM

2023-08-31 16:37 UTC, dickon approved these changes
LGTM.

I think the justification in CORE-15756 is rather one sided, but if that's what we want this seems a nice piece of work to deliver it.

2023-08-31 16:43 UTC, blsemo requested changes, later dismissed
I am ok with the content of this change, however the path for the FlowMapperProcessor files look wrong - the packages should be represented as a directory hierarchy, not a directory with loads of dots in the name.

2023-08-31 16:43 UTC, blsemo commented on processors/flow-mapper-processor/src/main/java/net.corda.processors.flow.mapper/package-info.java
The path on this one looks wrong! What happened when creating this package?

2023-08-31 16:47 UTC, jujoramos approved these changes
LGTM

2023-09-01 08:02 UTC, josephzunigadaly approved these changes
Rest owned files look ok

2023-09-01 08:06 UTC, owenstanford approved these changes
Looks ok to me

2023-09-01 08:07 UTC, merged

2023-09-01 10:50 UTC, ben-millar commented on processors/flow-mapper-processor/src/main/java/net.corda.processors.flow.mapper/package-info.java
https://github.com/corda/corda-runtime-os/pull/4569