NOTICK : Sync syntax with release 5.1
corda/corda-runtime-os pull request #4557
Opened 2023-08-31 09:03 UTC by SaurabhR3

2023-08-31 09:34 UTC, jmacmahonr3 approved these changes
LGTM

2023-08-31 10:55 UTC, ac101m requested changes

2023-08-31 10:55 UTC, ac101m commented on gradle.properties
> +cordaApiVersion=5.1.0-INTEROP.15-alpha-1693465318193
Need to update this to 16-beta+ once API PR is merged

2023-08-31 11:57 UTC, ac101m approved these changes
LGTM

2023-09-04 19:39 UTC, ac101m requested changes
Tested locally, looks to be working!
But I think the diff is unnecessarily large, with some re-ordered added/deleted things that didn't need changing.
I think it's probably best not to delete any code outright here, and just to comment it, so that context is maintained and we can resolve future merges correctly.

2023-09-04 19:39 UTC, ac101m commented on components/link-manager/src/main/kotlin/net/corda/p2p/linkmanager/outbound/OutboundMessageProcessor.kt
> -            }
I think it would be wise to leave this code in, commented out with a comment, rather than to delete it entirely. Will be helpful to whoever picks up the related ticket to fix this later, and will also provide context to people merging in the future.

2023-09-04 19:39 UTC, ac101m commented on components/link-manager/src/main/kotlin/net/corda/p2p/linkmanager/outbound/OutboundMessageProcessor.kt
> +        val destMemberInfo = membershipGroupReaderProvider.lookup(
Undo rename, we shouldn't be refactoring stuff in link manager!

2023-09-04 21:27 UTC, szymonsztuka requested changes
The last change in e82eeec12db2c892bac1b812b24da271cbdd6c4a to find a temp workaround is wrong as it alters the platform behaviour and is too invasive. I think the only change should be to modify behavior of `isHostedLocallyAndSessionKeyMatch` method in for the case it's processes interop based Memebr info, we know  when it does then it throws an exception, so we should catch this exception, the existing method:
```
  override fun isHostedLocallyAndSessionKeyMatch(member: MemberInfo) =
        locallyHostedIdentityToIdentityInfo[member.holdingIdentity]?.let { identityInfo ->
            member.sessionInitiationKeys.any { memberSessionKey ->
                identityInfo.allSessionKeysAndCertificates.any {
                    it.sessionPublicKey.encoded.contentEquals(memberSessionKey.encoded)
                }
            }
        } ?: false
```
Should be wrapped with try catch:
```
  override fun isHostedLocallyAndSessionKeyMatch(member: MemberInfo) =
        try {
        locallyHostedIdentityToIdentityInfo[member.holdingIdentity]?.let { identityInfo ->
            member.sessionInitiationKeys.any { memberSessionKey ->
                identityInfo.allSessionKeysAndCertificates.any {
                    it.sessionPublicKey.encoded.contentEquals(memberSessionKey.encoded)
                }
            }
        } ?: false
        } catch (exp: Exception) { false }
```
Not sure if we shout return true or false when exception is caught, but this should be the only change I think.

2023-09-05 11:14 UTC, szymonsztuka commented
Regarding my last comment (https://github.com/corda/corda-runtime-os/pull/4557#pullrequestreview-1609963860) - the workaround proposal I think it should return true in case of an exception is cought.

2023-09-06 09:28 UTC, merged