CORE-16319: State Manager API & Implementation
corda/corda-runtime-os pull request #4602
Opened 2023-09-07 10:30 UTC by jujoramos

Add initial API and basic implementation for the State Manager.

2023-09-07 10:30 UTC, jujoramos commented
Split from https://github.com/corda/corda-runtime-os/pull/4501.
Corda API changes: https://github.com/corda/corda-api/pull/1240.

2023-09-07 11:13 UTC, conalsmith-r3 commented on libs/state-manager/state-manager-impl/src/test/kotlin/net/corda/libs/statemanager/impl/StateManagerImplTest.kt
> +    fun `get state creates tx and uses repository`() {
we prob should add a few more unit tests for the repository functions, but we do have the integration test coverage

2023-09-07 11:15 UTC, conalsmith-r3 commented on libs/state-manager/state-manager-impl/src/main/kotlin/net/corda/libs/statemanager/impl/repository/impl/StateRepositoryImpl.kt
> +            .setParameter(STAR_TIMESTAMP, start)
minor - typo

2023-09-07 11:19 UTC, conalsmith-r3 commented on libs/state-manager/state-manager-api/src/main/kotlin/net/corda/libs/statemanager/api/Metadata.kt
> +            supportedBoxedPrimitives.contains(value::class.java) -> true
should we use `supportedBoxedPrimitives.any { it.isAssignableFrom(value::class.java) }` instead?

2023-09-07 12:14 UTC, jujoramos commented on libs/state-manager/state-manager-impl/src/main/kotlin/net/corda/libs/statemanager/impl/repository/impl/StateRepositoryImpl.kt
> +            .setParameter(STAR_TIMESTAMP, start)
👍

2023-09-07 13:13 UTC, driessamyn commented on libs/state-manager/state-manager-api/src/main/kotlin/net/corda/libs/statemanager/api/State.kt
> +     * that must generally not be part of the state itself.
Just curious, why is the guidance that it should not be part of the state?
May it not be acceptable to extract something from the state into metadata if we know it must be query-able, for example?

2023-09-07 13:13 UTC, driessamyn commented on libs/state-manager/state-manager-impl/build.gradle
> +description 'State Manager Implementation'
This is one example where I think it is justified to have an separate module for the implementation (not sure why we do that everywhere else and collect 250+ modules on the way), but shouldn't we indicate in this module that this is the postgres implementation? I.e if this is `state-manager-postgres`, we may one day have a `state-manager-redis` and/or `state-manager-coherence`, for example.

2023-09-07 13:13 UTC, driessamyn commented on libs/state-manager/state-manager-impl/build.gradle
> +DynamicImport-Package: org.hibernate.proxy
Do we need to use Hibernate for this?

2023-09-07 13:13 UTC, driessamyn commented on libs/state-manager/state-manager-impl/src/main/kotlin/net/corda/libs/statemanager/impl/StateManagerImpl.kt
> +@Suppress("ForbiddenComment")
Can we fix the comment rather than suppress the warning?

2023-09-07 13:13 UTC, driessamyn commented on libs/state-manager/state-manager-impl/src/main/kotlin/net/corda/libs/statemanager/impl/StateManagerImpl.kt
> +class StateManagerImpl(
Similar to the comment in the API repo. Would it be worth having a group/namespace/partition argument so that we can have multiple logical state managers that can be partitions separately?

2023-09-07 13:13 UTC, driessamyn commented on libs/state-manager/state-manager-api/src/main/kotlin/net/corda/libs/statemanager/api/State.kt
> +    val state: S,
maybe `value` would be a better? (to avoid state.state)

2023-09-07 13:13 UTC, driessamyn commented on libs/state-manager/state-manager-impl/src/main/kotlin/net/corda/libs/statemanager/impl/StateManagerImpl.kt
> +    private val deserializers: MutableMap<Class<*>, CordaAvroDeserializer<*>> = ConcurrentHashMap(),
I'm in 2 minds about this, so not saying it's wrong. But is it right that the state manager is also responsible for serialisation (and hence has an opaque/implicit requirement that it can only store objects that have avro serialisers registered)?
It feels a bit wrong and may it makes more sense for value to always be a binary blob so that the consumer of the state manager can be responsible for serialisation.

2023-09-07 13:13 UTC, driessamyn commented on libs/state-manager/state-manager-impl/src/main/kotlin/net/corda/libs/statemanager/impl/model/v1/StateEntity.kt
> +@NamedNativeQuery(
As above, I'm really not convinced we should pay the overhead of Hibernate in this case, especially if we use native queries.
Queries will generally be simple and performance and tunability is very important in this case.

2023-09-07 13:35 UTC, jujoramos commented on libs/state-manager/state-manager-api/src/main/kotlin/net/corda/libs/statemanager/api/Metadata.kt
> +            supportedBoxedPrimitives.contains(value::class.java) -> true
👍

2023-09-07 13:36 UTC, jujoramos commented on libs/state-manager/state-manager-api/src/main/kotlin/net/corda/libs/statemanager/api/State.kt
> +     * that must generally not be part of the state itself.
Bad working on my part, thanks 👍.

2023-09-07 13:38 UTC, jujoramos commented on libs/state-manager/state-manager-api/src/main/kotlin/net/corda/libs/statemanager/api/State.kt
> +    val state: S,
👍

2023-09-07 15:06 UTC, jujoramos commented on libs/state-manager/state-manager-api/src/main/kotlin/net/corda/libs/statemanager/api/State.kt
> +     * that must generally not be part of the state itself.
I meant "wording", not "working" 😅

2023-09-07 19:37 UTC, jujoramos commented on libs/state-manager/state-manager-impl/build.gradle
> +description 'State Manager Implementation'
> not sure why we do that everywhere else and collect 250+ modules on the way 

💯 


> shouldn't we indicate in this module that this is the postgres implementation? I.e if this is `state-manager-postgres`, we may one day have a `state-manager-redis` and/or `state-manager-coherence`, for example.

I'd go for `state-manager-db-impl` or something similar, as to indicate that the persistent storage is a database system. I don't know if we want to include `postgres`, though, we might want to support other databases in the short term future as the rest of the platform does. I doubt customers will use database system `X` for the Corda platform and database system `Y` for just the state manager.

2023-09-07 19:38 UTC, jujoramos commented on libs/state-manager/state-manager-impl/build.gradle
> +DynamicImport-Package: org.hibernate.proxy
Similar to my previous comment, Hibernate is included just as an abstraction layer between the state manager and the chosen RDBMS.

2023-09-07 19:39 UTC, jujoramos commented on libs/state-manager/state-manager-impl/src/main/kotlin/net/corda/libs/statemanager/impl/StateManagerImpl.kt
> +@Suppress("ForbiddenComment")
The forbidden comments are all `TODO`s, actually 😅 . Guess we can try to provide a quick implementation of the missing methods instead of suppressing the warning, the idea was to have the `TODO`s for a short period of time only (not more than 1 or 2 weeks).

2023-09-07 19:41 UTC, jujoramos commented on libs/state-manager/state-manager-impl/src/main/kotlin/net/corda/libs/statemanager/impl/StateManagerImpl.kt
> +    private val deserializers: MutableMap<Class<*>, CordaAvroDeserializer<*>> = ConcurrentHashMap(),
Yeah, I'm also sitting on the fence for this one... I'll remove the serailizers for the time being, we can always put them back if needed.

2023-09-07 19:43 UTC, jujoramos commented on libs/state-manager/state-manager-impl/src/main/kotlin/net/corda/libs/statemanager/impl/model/v1/StateEntity.kt
> +@NamedNativeQuery(
I agree but, as before, defaulting to a single database backend won't allow customers to customise this part as they'll be able to do for the rest of the platform; not sure that's what we want.

2023-09-08 08:14 UTC, driessamyn commented on libs/state-manager/state-manager-impl/build.gradle
> +description 'State Manager Implementation'
That's fair. Happy with `db-impl`. 👍

2023-09-08 08:21 UTC, driessamyn commented on libs/state-manager/state-manager-impl/build.gradle
> +DynamicImport-Package: org.hibernate.proxy
But what's the point, especially if we are using native queries?
It brings a fair amount of overhead (EMFs are expensive for example) and less flexibility for very little benefit. In this case, I suspect even the SQL queries will be the same for each DB type unless we want to explicitly tune them for a particular DB, in which case we'd loose the  benefit of Hibernate anyway.
Longer term, I think we should discuss removing Hibernate anywhere we don't have user schemas (where we have a good case for JPA) as we don't really use it as an ORM, just as a SQL abstraction layer, and it's very expensive for the value in that case.
In think for this library, it would be easy to not have Hibernate as it's quite separate from the rest of the persistence management.

2023-09-08 08:24 UTC, driessamyn commented on libs/state-manager/state-manager-impl/src/main/kotlin/net/corda/libs/statemanager/impl/StateManagerImpl.kt
> +@Suppress("ForbiddenComment")
I agree that that's a questionable rule, but I always worry when we have temporary suppression as it's easy to forget about them.
If we don't agree with the rule, we should change the rule rather than suppress it everywhere (maybe a topic to bring to the weekly meeting).

BTW. the rule actually triggers `TODO:` but not `TODO -` for example. 🤷

2023-09-08 08:26 UTC, driessamyn commented on libs/state-manager/state-manager-impl/src/main/kotlin/net/corda/libs/statemanager/impl/model/v1/StateEntity.kt
> +@NamedNativeQuery(
We don't allow customers to customise this anyway. We only support a given set of DBs (currently 1, postgres). 
Work is underway to support an additional, but I believe that hibernate will in this instance give is very little over standard JDBC. We will need a facility to customise queries per DB dialect anyway because we use native queries elsewhere that need to vary between DB dialects.

2023-09-08 15:30 UTC, jujoramos commented on libs/state-manager/state-manager-impl/build.gradle
> +DynamicImport-Package: org.hibernate.proxy
Due to the existing tooling around Hibernate within the Corda platform, and in an attempt to speed up the first deliverable of the State Manager, it was agreed offline to keep using Hibernate in the short term and create tickets to entirely remove it in favour of direct JDBC access.

2023-09-08 15:30 UTC, jujoramos commented on libs/state-manager/state-manager-impl/src/main/kotlin/net/corda/libs/statemanager/impl/StateManagerImpl.kt
> +@Suppress("ForbiddenComment")
👍

2023-09-08 15:31 UTC, jujoramos commented on libs/state-manager/state-manager-impl/src/main/kotlin/net/corda/libs/statemanager/impl/model/v1/StateEntity.kt
> +@NamedNativeQuery(
Due to the existing tooling around Hibernate within the Corda platform, and in an attempt to speed up the first deliverable of the State Manager, it was agreed offline to keep using Hibernate in the short term and create tickets to entirely remove it in favour of direct JDBC access.

2023-09-10 22:02 UTC, jujoramos commented on libs/state-manager/state-manager-impl/src/test/kotlin/net/corda/libs/statemanager/impl/StateManagerImplTest.kt
> +    fun `get state creates tx and uses repository`() {
Done

2023-09-10 22:14 UTC, jujoramos commented on libs/state-manager/state-manager-impl/src/main/kotlin/net/corda/libs/statemanager/impl/StateManagerImpl.kt
> +class StateManagerImpl(
It might be worth, sure, but I'm not sure how it will work at the implementation level; guess I'll need to read some about DB partitioning and check how it fits here.

2023-09-11 07:27 UTC, driessamyn commented on libs/state-manager/state-manager-impl/src/main/kotlin/net/corda/libs/statemanager/impl/StateManagerImpl.kt
> +class StateManagerImpl(
I was more thinking of having it as a logical partition for now, which would allow us to tune things later.
I.e. we don't need to have the implementation on day 1, but if it is in the API, then it allows us to tune behind the scenes.
I think most of the potential implementations support a kind of partitioning. E.g. [Postgresql](https://www.postgresql.org/docs/current/ddl-partitioning.html), [Redis](https://redis-doc-test.readthedocs.io/en/latest/topics/partitioning/)

2023-09-11 09:13 UTC, jujoramos commented on libs/state-manager/state-manager-impl/src/main/kotlin/net/corda/libs/statemanager/impl/StateManagerImpl.kt
> +class StateManagerImpl(
I've been talking with @Omar-awad and @vinir3 today, we are a bit tight in terms of time so we think is best to go with we have right now and add the extra functionality later. Hope that's okay with you?.

2023-09-11 09:25 UTC, driessamyn commented on libs/state-manager/state-manager-impl/src/main/kotlin/net/corda/libs/statemanager/impl/StateManagerImpl.kt
> +class StateManagerImpl(
Sure. It was just a suggestion. 
The only downside of not doing it now is that adding it later on will require an (internal) API change.

2023-09-11 09:29 UTC, jujoramos commented on libs/state-manager/state-manager-impl/src/main/kotlin/net/corda/libs/statemanager/impl/StateManagerImpl.kt
> +class StateManagerImpl(
Agreed 👍 . We'll get back to this before the actual release, though, so we should be fine.

2023-09-11 10:40 UTC, conalsmith-r3 commented on libs/state-manager/state-manager-api/src/main/kotlin/net/corda/libs/statemanager/api/State.kt
> +     * The typed state itself.
minor - this doc needs updated

2023-09-11 10:43 UTC, jujoramos commented on libs/state-manager/state-manager-api/src/main/kotlin/net/corda/libs/statemanager/api/State.kt
> +     * The typed state itself.
👍

2023-09-11 13:36 UTC, conalsmith-r3 reviewed
LGTM once we merge corda-api

2023-09-11 14:07 UTC, driessamyn commented on libs/state-manager/state-manager-db-impl/src/main/kotlin/net/corda/libs/statemanager/impl/repository/impl/StateRepositoryImpl.kt
> +            "SELECT * FROM ${DbSchema.STATE_MANAGER_TABLE} s WHERE (s.metadata->>'$key')::::$nativeType $comparison '$value'",
We should not have a SELECT * if using a Native Query, but list the fields required.

2023-09-11 14:07 UTC, driessamyn commented on libs/state-manager/state-manager-db-impl/src/main/kotlin/net/corda/libs/statemanager/impl/model/v1/StateEntity.kt
> +)
I'm not sure how nicely this manual version increment is going to play with Hibernate's optimistic locking.
Maybe not a problem for now, but keep an eye on it, and another reason to maybe move away from hibernate (or completely adopt it).

2023-09-11 14:07 UTC, driessamyn commented on libs/state-manager/state-manager-api/src/main/kotlin/net/corda/libs/statemanager/api/State.kt
> +        return result
Why do these need to be overriden given it is a data class?

2023-09-11 15:03 UTC, jujoramos commented on libs/state-manager/state-manager-db-impl/src/main/kotlin/net/corda/libs/statemanager/impl/model/v1/StateEntity.kt
> +)
We'll keep an eye (there's already a ticket to thoroughly test and improve the optimistic locking part).

2023-09-11 15:03 UTC, jujoramos commented on libs/state-manager/state-manager-db-impl/src/main/kotlin/net/corda/libs/statemanager/impl/repository/impl/StateRepositoryImpl.kt
> +            "SELECT * FROM ${DbSchema.STATE_MANAGER_TABLE} s WHERE (s.metadata->>'$key')::::$nativeType $comparison '$value'",
👍

2023-09-11 15:17 UTC, jujoramos commented on libs/state-manager/state-manager-api/src/main/kotlin/net/corda/libs/statemanager/api/State.kt
> +        return result
Due to the `ByteArray` property, according to the IDE, it's recommended to override `hashCode()` and `equals()` in this case, even for data classes (I haven't checked the actual reasons for the recommendation, though).

2023-09-11 15:31 UTC, driessamyn commented on libs/state-manager/state-manager-api/src/main/kotlin/net/corda/libs/statemanager/api/State.kt
> +        return result
I'm guessing this is the reason: https://blog.jetbrains.com/kotlin/2015/09/feedback-request-limitations-on-data-classes/

Worth understanding and adding a comment as otherwise somebody may just delete them.

2023-09-12 08:06 UTC, wzur-r3 requested changes

2023-09-12 08:06 UTC, wzur-r3 commented on gradle.properties
> +cordaApiVersion=5.1.0.19-alpha-1694441708944
please make sure this is updated back to beta

2023-09-12 09:41 UTC, jujoramos commented on gradle.properties
> +cordaApiVersion=5.1.0.19-alpha-1694441708944
Yes, once the api changes are merged I'll revert this back.

2023-09-12 09:41 UTC, JamesHR3 commented on libs/state-manager/state-manager-api/src/main/kotlin/net/corda/libs/statemanager/api/StateManager.kt
> +    fun create(states: Collection<State>): Map<String, Exception>
Worth being explicit that this isn't transactional and is best effort (assuming that's the case) - we'll try every state in the collection regardless, and we'll store anything that succeeds even if some fail.

Probably worth the same description for the other APIs on this interface (assuming that's true).

What's the behaviour if there is already a state on the key? Does it fail or does it overwrite the old one?

2023-09-12 09:41 UTC, JamesHR3 commented on libs/state-manager/state-manager-api/src/main/kotlin/net/corda/libs/statemanager/api/StateManager.kt
> +    fun update(states: Collection<State>): Map<String, State>
Interesting that this is transactional. Does that mean if any of the states have mismatched versions none of them will be updated? If that's the case I don't think the return type makes sense any more - it'll either be the input collection or empty. If it's not the case then I think the comment is a bit misleading.

2023-09-12 09:41 UTC, JamesHR3 commented on libs/state-manager/state-manager-api/src/main/kotlin/net/corda/libs/statemanager/api/StateManager.kt
> +    fun delete(states: Collection<State>): Map<String, State>
Same comment here as for the update case.

2023-09-12 09:41 UTC, JamesHR3 commented on libs/state-manager/state-manager-db-impl/src/integrationTest/kotlin/net/corda/libs/statemanager/impl/tests/StateManagerIntegrationTest.kt
> +    fun canCreateBasicStates(stateCount: Int) {
Minor, but for test cases you can use function names wrapped in backticks to make the test case names easier to read, e.g.

```kotlin
fun `can create basic states`(stateCount: Int) {
}
```

Sometimes the output of parameterized tests is named in an unhelpful way by default, so you might want to consider changing the display name. See https://junit.org/junit5/docs/current/user-guide/#writing-tests-parameterized-tests-display-names.

2023-09-12 09:41 UTC, JamesHR3 commented on libs/state-manager/state-manager-db-impl/src/main/kotlin/net/corda/libs/statemanager/impl/StateManagerImpl.kt
> +    @VisibleForTesting
I'm not really a fan of `@VisibleForTesting`, it usually implies that the tests are not really testing the class contract and are verifying some detail of the implementation. 

In this case you could write tests that verify you call update/delete on the set you're expecting to be matched and return the mismatched ones. Then you're free to change how you calculate which items are which without invalidating the unit test.

2023-09-12 09:41 UTC, JamesHR3 commented on libs/state-manager/state-manager-db-impl/src/main/kotlin/net/corda/libs/statemanager/impl/StateManagerImpl.kt
> +                    logger.warn("Optimistic locking check failed for States ${it.entries.joinToString()}")
`warn` might be a little strong for these, but `info` seems appropriate to me. Do we anticipate that a locking failure is an error the user might need to worry about? It seems to me more likely to occur if there's a race between processes and they need to retry, which doesn't seem to be an issue from a user perspective.

2023-09-12 09:41 UTC, JamesHR3 commented on libs/state-manager/state-manager-db-impl/src/main/kotlin/net/corda/libs/statemanager/impl/repository/impl/StateRepositoryImpl.kt
> +        val results = keys.chunked(50) { chunkedKeys ->
The 50 here should probably be a constant.

Is this something we may want to tune?

2023-09-12 09:41 UTC, JamesHR3 commented on libs/state-manager/state-manager-db-impl/src/main/kotlin/net/corda/libs/statemanager/impl/repository/impl/StateRepositoryImpl.kt
> +//        Should we use this instead of casting to the specific type (::text, ::numeric, ::boolean)?
Would be good to resolve this question and either put this code in or remove it.

2023-09-12 11:10 UTC, jujoramos commented on libs/state-manager/state-manager-db-impl/src/integrationTest/kotlin/net/corda/libs/statemanager/impl/tests/StateManagerIntegrationTest.kt
> +            { _, _ -> 0 },
This should use `State.VERSION_INITIAL_VALUE` now, shouldn't it?

2023-09-12 16:47 UTC, jujoramos commented on libs/state-manager/state-manager-api/src/main/kotlin/net/corda/libs/statemanager/api/StateManager.kt
> +    fun create(states: Collection<State>): Map<String, Exception>
KDocs updated.

> What's the behaviour if there is already a state on the key? Does it fail or does it overwrite the old one?

It fails and returns the error to the caller as part of the result Map.

2023-09-12 16:47 UTC, jujoramos commented on libs/state-manager/state-manager-api/src/main/kotlin/net/corda/libs/statemanager/api/StateManager.kt
> +    fun update(states: Collection<State>): Map<String, State>
KDocs updated.

2023-09-12 16:47 UTC, jujoramos commented on libs/state-manager/state-manager-api/src/main/kotlin/net/corda/libs/statemanager/api/StateManager.kt
> +    fun delete(states: Collection<State>): Map<String, State>
KDocs updated.

2023-09-12 16:47 UTC, jujoramos commented on libs/state-manager/state-manager-db-impl/src/main/kotlin/net/corda/libs/statemanager/impl/StateManagerImpl.kt
> +                    logger.warn("Optimistic locking check failed for States ${it.entries.joinToString()}")
You're right, changed the log level to `info` 👍

2023-09-12 16:54 UTC, jujoramos commented on libs/state-manager/state-manager-db-impl/src/main/kotlin/net/corda/libs/statemanager/impl/StateManagerImpl.kt
> +    @VisibleForTesting
👍

2023-09-12 17:18 UTC, jujoramos commented on libs/state-manager/state-manager-db-impl/src/integrationTest/kotlin/net/corda/libs/statemanager/impl/tests/StateManagerIntegrationTest.kt
> +    fun canCreateBasicStates(stateCount: Int) {
> For test cases you can use function names wrapped in backticks to make the test case names easier to read, e.g.

I know, but I like the old way of squashing all words together to make our livers harder :-).

> Sometimes the output of parameterized tests is named in an unhelpful way by default,

Yeah, I didn't consider it necessary for this scenario. Made the change, anyways 👍

2023-09-12 20:32 UTC, jujoramos commented on libs/state-manager/state-manager-db-impl/src/main/kotlin/net/corda/libs/statemanager/impl/repository/impl/StateRepositoryImpl.kt
> +//        Should we use this instead of casting to the specific type (::text, ::numeric, ::boolean)?
Removed.

2023-09-12 20:34 UTC, jujoramos commented on libs/state-manager/state-manager-db-impl/src/main/kotlin/net/corda/libs/statemanager/impl/repository/impl/StateRepositoryImpl.kt
> +        val results = keys.chunked(50) { chunkedKeys ->
This seemed like a magic number to me as well but forgot to remove it. Unless @conalsmith-r3 has any objections, I'd vote for removing it and getting it back in the future if needed.

2023-09-13 05:42 UTC, wzur-r3 approved these changes
LGTM for files owned by BLT

2023-09-13 07:55 UTC, conalsmith-r3 commented on libs/state-manager/state-manager-db-impl/src/main/kotlin/net/corda/libs/statemanager/impl/repository/impl/StateRepositoryImpl.kt
> +        return entityManager
We need to keep an eye on this query as IN clause with large amounts of keys could be inefficient, hence why I went with chunked approach initially. Let's go with this but keep an eye out.

2023-09-13 07:59 UTC, conalsmith-r3 approved these changes

2023-09-13 10:17 UTC, jujoramos commented on libs/state-manager/state-manager-db-impl/src/main/kotlin/net/corda/libs/statemanager/impl/repository/impl/StateRepositoryImpl.kt
> +        return entityManager
👍

2023-09-13 13:26 UTC, JamesHR3 approved these changes

2023-09-13 14:56 UTC, merged