add pod and container security contexts to chart
corda/corda-runtime-os pull request #4623
Opened 2023-09-12 08:48 UTC by jacob-scott3141

2023-09-12 09:11 UTC, davidcurrie requested changes

2023-09-12 09:11 UTC, davidcurrie commented on charts/corda-lib/templates/_worker.tpl
> +      {{- with .Values.podSecurityContext }}
I think you need to use `$.Values` here (which is why the build is failing)

2023-09-12 09:11 UTC, davidcurrie commented on charts/corda/values.yaml
> +  # -- linux capabilities for users
only leaf doc comments should have `--`

2023-09-12 09:11 UTC, davidcurrie commented on charts/corda/values.schema.json
> +        "containerSecurityContext": {
I think there are some extra values here that we don't currently use but should still allow the user to set. Take a look at the schema here, for example:
https://github.com/instrumenta/kubernetes-json-schema/blob/master/v1.7.4/securitycontext.json
https://github.com/instrumenta/kubernetes-json-schema/blob/master/v1.7.4/podsecuritycontext.json

2023-09-12 09:11 UTC, davidcurrie commented on charts/corda/values.schema.json
> +        "podSecurityContext": {
Not all of these fields exist for the pod security context (e.g. `capabilities` can only be specified at the container level). Take a look at the schema referenced above.

2023-09-12 09:11 UTC, davidcurrie commented on charts/corda/values.schema.json
> +                            "type": "array",
We should be say what the type of the items in the array are e.g. https://github.com/instrumenta/kubernetes-json-schema/blob/master/v1.7.4/capabilities.json#L7-L12

2023-09-12 10:38 UTC, jacob-scott3141 commented on charts/corda/values.schema.json
> +        "containerSecurityContext": {
Do you know what version we're using? The schema for podsecuritycontext doesn't have a runAsGroup in this version

2023-09-12 10:47 UTC, davidcurrie commented on charts/corda/values.schema.json
> +        "containerSecurityContext": {
So, we currently say `1.23`. Unfortunately that site stops at 1.18 but that at least gets you a bit closer:
https://github.com/instrumenta/kubernetes-json-schema/blob/master/v1.18.1/podsecuritycontext.json

The definitive source is probably the API docs: https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#security-context

2023-09-12 13:49 UTC, davidcurrie commented on charts/corda-lib/templates/_helpers.tpl
> +  {{ . | toYaml }}
need another `nindent` here

2023-09-12 15:58 UTC, davidcurrie reviewed
LGTM - can you verify that, as per the ticket, you can set the two values to `nil` and then nothing gets included in the deployments? Then, as discussed, we should make the `corda` changes to `corda-enterprise` first and then we can merge this PR with the `corda-lib` updates in.

2023-09-13 11:26 UTC, davidcurrie approved these changes
LGTM

2023-09-13 11:27 UTC, merged