Proof of Action Lock State (Part 1)
corda/corda-runtime-os pull request #4626
Opened 2023-09-12 13:18 UTC by julia-filipczak

2023-10-02 15:46 UTC, szymonsztuka requested changes

2023-10-02 15:46 UTC, szymonsztuka commented on testing/cpbs/atomic-swap-workflows/src/main/kotlin/com/r3/corda/atomic/swap/workflows/CreateLockFlow.kt
> +            log.info("KEYS PLEASE lockState.participants: ${lockState.participants}")
Remove all statements `log.info("KEYS PLEASE`... used when troubleshooting.

2023-10-02 15:46 UTC, szymonsztuka commented on testing/cpbs/atomic-swap-workflows/src/main/kotlin/com/r3/corda/atomic/swap/workflows/CreateLockFlow.kt
> +            val assetWithCompositeKey = constructLockedAsset(inputState, newOwnerInfo)
`assetWithCompositeKey` is not used as a whole and it's an unnecessary intermediate object, consider in-lining this code here:
```
val compositeKey = compositeKeyGenerator.create(
            listOf(
                CompositeKeyNodeAndWeight(asset.owner, 1),
                CompositeKeyNodeAndWeight(newOwner.ledgerKeys.single(), 1)
            ), 1
        )

        outputState.withNewOwner(compositeKey, listOf(asset.owner, newOwner.ledgerKeys[0]))
```

2023-10-02 15:46 UTC, szymonsztuka commented on testing/cpbs/atomic-swap-workflows/src/main/kotlin/com/r3/corda/atomic/swap/workflows/CreateLockFlow.kt
> +//                listOf(assetWithCompositeKey.owner)
Remove unused code

2023-10-02 15:46 UTC, szymonsztuka commented on testing/cpbs/atomic-swap-workflows/src/main/kotlin/com/r3/corda/atomic/swap/workflows/UnlockFlow.kt
> +//                .addSignatories(inputLockState.participants)// alice, bob
Remove unused code

2023-10-02 15:46 UTC, szymonsztuka commented on testing/cpbs/atomic-swap-workflows/src/main/kotlin/com/r3/corda/atomic/swap/workflows/UnlockFlow.kt
> +                .addSignatories(newState.participants)//bob
remove `//bob`

2023-10-02 15:46 UTC, szymonsztuka commented on testing/cpbs/atomic-swap-contracts/src/main/kotlin/com/r3/corda/atomic/swap/contracts/AssetContract.kt
> +        // Switches case based on the command
Remove all comemnd in this calls, they are duplicating exactly the code e.g.:
```
// Rules applied only to transactions with the Transfer Command.
            is AssetCommands.Transfer -> {
```

2023-10-02 15:46 UTC, szymonsztuka commented on testing/cpbs/atomic-swap-contracts/src/main/kotlin/com/r3/corda/atomic/swap/contracts/AssetContract.kt
> +        const val REQUIRE_SINGLE_COMMAND = "Requires a single command."
I would inline all text into the contract code, it make the contract code more readable.

2023-10-02 15:46 UTC, szymonsztuka commented on testing/cpbs/atomic-swap-contracts/src/main/kotlin/com/r3/corda/atomic/swap/contracts/AssetContract.kt
> +    private infix fun String.using(expr: () -> Boolean) {
I think this method is not used so we can remove it

2023-10-02 15:46 UTC, szymonsztuka commented on testing/cpbs/atomic-swap-contracts/src/main/kotlin/com/r3/corda/atomic/swap/contracts/AssetContract.kt
> +                val asset = transaction.getOutputStates(Asset::class.java)[0]
In all those cases instead of index access `[0]`we can use method `.first()`

2023-10-02 15:46 UTC, szymonsztuka commented on testing/cpbs/atomic-swap-contracts/src/main/kotlin/com/r3/corda/atomic/swap/contracts/LockContract.kt
> +                        (transaction.outputContractStates.size == 1)
The unlock command should allow only a specific "actor" to unlock an asset.

2023-10-02 15:46 UTC, szymonsztuka commented on testing/cpbs/atomic-swap-contracts/src/main/kotlin/com/r3/corda/atomic/swap/contracts/LockContract.kt
> +    private infix fun String.using(expr: () -> Boolean) {
I think this is not in use.

2023-10-02 15:46 UTC, szymonsztuka commented on testing/cpbs/atomic-swap-contracts/src/main/kotlin/com/r3/corda/atomic/swap/states/Asset.kt
> +    private val participants: List<PublicKey>) : OwnableState {
This is lowest priority, I think we should make this constructor private one, and add another constructor which would set `participants = listOf(owner)`

2023-10-02 15:46 UTC, szymonsztuka commented on testing/cpbs/atomic-swap-contracts/src/main/kotlin/com/r3/corda/atomic/swap/states/Asset.kt
> +        return Asset(newOwner, assetName, assetId, newParticipants)
This is lowest priority, we should derived participants like that:
we should retain the previous owner in participants list and then add the new owner.
In general here I think participants should be always the owner and eventually former owner of the asset, we can compute it internally no need to force user to put it in parameters.

2023-10-02 15:46 UTC, szymonsztuka commented on testing/cpbs/atomic-swap-workflows/src/main/kotlin/com/r3/corda/atomic/swap/workflows/CreateLockFlow.kt
> +                .addSignatories(assetWithCompositeKey.owner)
I'm curious that this type of lock works as it doesn't use encumbrances.

2023-10-02 17:09 UTC, szymonsztuka requested changes

2023-10-02 17:09 UTC, szymonsztuka commented on testing/cpbs/atomic-swap-contracts/src/main/kotlin/com/r3/corda/atomic/swap/contracts/AssetContract.kt
> +            }
Should we add the check that (at least) input.owner should sign the transaction, or maybe even old and new owners should sign the transaction. This is in fact business dependent, but we could keep consistent (as in `AssetCommands.Create` we do check who sign, so maybe in `AssetCommands.Transfer` we should have such type of a check as well.)

2023-10-02 17:09 UTC, szymonsztuka commented on testing/cpbs/atomic-swap-contracts/src/main/kotlin/com/r3/corda/atomic/swap/contracts/LockContract.kt
> +                "The signer of the unlock should be the new owner of the Asset state." using (outputState.participants == transaction.signatories)
There is a single "actor" who can unlock only, the other actor cant unlock. Also only one "actor" do sign unlock (in business terms only one actor will unlock).

2023-10-02 17:09 UTC, szymonsztuka commented on testing/cpbs/atomic-swap-contracts/src/main/kotlin/com/r3/corda/atomic/swap/states/LockState.kt
> +    val assetId: String,
I don't think we need `assetId` and `assetName`, at least in the most plain version of lock. They may server some "compliance" purpose / vault search but they absolutely are not used in the contract logic.

2023-10-03 10:17 UTC, julia-filipczak commented on testing/cpbs/atomic-swap-contracts/src/main/kotlin/com/r3/corda/atomic/swap/contracts/LockContract.kt
> +                "The signer of the unlock should be the new owner of the Asset state." using (outputState.participants == transaction.signatories)
In this case `outputState.participants` is a single actor.

2023-10-03 10:38 UTC, szymonsztuka requested changes

2023-10-03 10:38 UTC, szymonsztuka commented on testing/cpbs/atomic-swap-contracts/src/main/kotlin/com/r3/corda/atomic/swap/contracts/LockContract.kt
> +                "The signer of the unlock should be the new owner of the Asset state." using (outputState.participants == transaction.signatories)
The contract code has no such constraint (how many participants are in `participants` collections), and more other `LockCommands.Lock` suggests there may be  2 participants.
You are inferring some extra knowledge looking at code written in flows but a contract code needs to be independent and prevent people of writing wrong flows (flows creating wrong transactions).

2023-10-03 11:30 UTC, szymonsztuka requested changes

2023-10-03 11:30 UTC, szymonsztuka commented on testing/cpbs/atomic-swap-contracts/src/main/kotlin/com/r3/corda/atomic/swap/contracts/LockContract.kt
> +        val outputState = transaction.getOutputStates(Asset::class.java).first()
I don't think The Lock contract shout have access or require code of Asset class. Can we built `LockContract` which is agnostic to an object (states) it's locking or depends on as minimally as possible? 
For example what if we what to use our Lock with "Orange" state or "Bushel of Wheat" State ? Then we would need to write new Lock code with `val outputState = transaction.getOutputStates("Bushel of Wheat"::class.java).first()`

2023-10-03 11:30 UTC, szymonsztuka commented on testing/cpbs/atomic-swap-contracts/src/main/kotlin/com/r3/corda/atomic/swap/contracts/LockContract.kt
> +                        (outputState.owner == transaction.signatories)
Here we just check that the new owner has signed it, but I think there are specific condition who can be the new owner. The contract code doesn't state it, doesn't check it, so a thief "actor"  (aka not Bob or alice) can assigned themself to be an owner of the state and added themself as signatory.

2023-10-04 16:21 UTC, szymonsztuka requested changes

2023-10-04 16:21 UTC, szymonsztuka commented on testing/cpbs/atomic-swap-contracts/src/main/kotlin/com/r3/corda/atomic/swap/contracts/LockContract.kt
> +                        (transaction.outputContractStates.size == 1)
And I would also check that Lock is not longer in output states, like? :
`(transaction.getOnputStates(LockState::class.java).size == 0)`

2023-10-04 16:21 UTC, szymonsztuka commented on testing/cpbs/atomic-swap-contracts/src/main/kotlin/com/r3/corda/atomic/swap/contracts/LockContract.kt
> +                        (outputState.owner == transaction.signatories.first())
Check this in similar way as in Asset - via checking if a collection contain an element.

2023-10-04 16:21 UTC, szymonsztuka commented on testing/cpbs/atomic-swap-contracts/src/main/kotlin/com/r3/corda/atomic/swap/states/Asset.kt
> +        return Asset(newOwner, assetName, assetId, newParticipants)
Due to some Kotlin wrnings as discoverd by @julia-filipczak  (and it probably know problem https://discuss.kotlinlang.org/t/data-class-with-private-constructor/25599) let's skip that refactoring I was proposing.

2023-10-04 16:21 UTC, szymonsztuka commented on testing/cpbs/atomic-swap-workflows/src/main/kotlin/com/r3/corda/atomic/swap/workflows/CreateLockFlow.kt
> +        // Build composite key
Remove unnecessary comment + maybe more compact code:
```
    private fun constructCompositeKey(asset: Asset, newOwner: MemberInfo): PublicKey =
         compositeKeyGenerator.create(
            listOf(
                CompositeKeyNodeAndWeight(asset.owner, 1),
                CompositeKeyNodeAndWeight(newOwner.ledgerKeys.single(), 1)
            ), 1
        )
```

2023-10-04 16:21 UTC, szymonsztuka commented on testing/cpbs/atomic-swap-contracts/src/main/kotlin/com/r3/corda/atomic/swap/states/Asset.kt
> +    private val participants: List<PublicKey>) : OwnableState {
Ignore this comment - see https://github.com/corda/corda-runtime-os/pull/4626#discussion_r1346147857

2023-10-05 10:30 UTC, szymonsztuka approved these changes

2023-10-05 11:35 UTC, merged