CORE-17007 : Changes for interop p2p params
corda/corda-runtime-os pull request #4634
Opened 2023-09-13 14:27 UTC by SaurabhR3

1. Added logic to fetch p2p params for interop
2. Reverted group policy interface
3. Added/Fixed Test

2023-09-13 14:51 UTC, ac101m requested changes
Couple trivial things, otherwise looks good to me at a glance. Probably good to get someone with more familiarity to review this.

2023-09-13 14:51 UTC, ac101m commented on components/membership/group-policy-impl/src/main/kotlin/net/corda/membership/impl/grouppolicy/GroupPolicyProviderImpl.kt
> +            if(groupPolicyJson != null) {
Code style, space following if

2023-09-14 13:57 UTC, ac101m approved these changes
LGTM

2023-09-14 14:53 UTC, wzur-r3 reviewed
LGTM for files owned by BLT (Gradle configurations)

2023-09-14 14:53 UTC, wzur-r3 approved these changes

2023-09-19 08:41 UTC, jmacmahonr3 requested changes
Minor Comments but once resolved looks good

2023-09-19 08:41 UTC, jmacmahonr3 commented on components/link-manager/build.gradle
> +//    implementation project(":components:interop:interop-group-policy-read-service")
Delete commented lines.

2023-09-19 08:41 UTC, jmacmahonr3 commented on components/link-manager/build.gradle
> +//    runtimeOnly project(":components:interop:interop-group-policy-read-service")
Delete

2023-09-19 08:41 UTC, jmacmahonr3 commented on components/membership/group-policy-impl/src/test/kotlin/net/corda/membership/impl/grouppolicy/GroupPolicyProviderImplTest.kt
> +//    @Test
Is this test failing ? 
Delete or rewrite

2023-09-19 10:01 UTC, SaurabhR3 commented on components/membership/group-policy-impl/src/main/kotlin/net/corda/membership/impl/grouppolicy/GroupPolicyProviderImpl.kt
> +            if(groupPolicyJson != null) {
Fixed in 2e92d71

2023-09-19 10:04 UTC, SaurabhR3 commented on components/link-manager/build.gradle
> +//    implementation project(":components:interop:interop-group-policy-read-service")
Fixed in 4c49eef

2023-09-19 10:04 UTC, SaurabhR3 commented on components/link-manager/build.gradle
> +//    runtimeOnly project(":components:interop:interop-group-policy-read-service")
Fixed in 4c49eef

2023-09-19 10:05 UTC, SaurabhR3 commented on components/membership/group-policy-impl/src/test/kotlin/net/corda/membership/impl/grouppolicy/GroupPolicyProviderImplTest.kt
> +//    @Test
No, it was commented to check something
Fixed in 4c49eef

2023-09-19 10:20 UTC, jmacmahonr3 approved these changes
LGTM

2023-09-19 10:49 UTC, merged