CORE-16620 Implement interop identity delete endpoint
corda/corda-runtime-os pull request #4664
Opened 2023-09-19 00:50 UTC by ac101m

# Changes
- Add delete endpoint
- Fix an error with interop identity deletion in the interop processor

2023-09-19 10:36 UTC, jmacmahonr3 commented
I think this approach is fine but i'd be eager to see what the the impact on deleting an identity mid flow is ... I imagine we'd break things pretty badly. It's an area we'd want to test

2023-10-06 13:32 UTC, vkolomeyko requested changes

2023-10-06 13:32 UTC, vkolomeyko commented on processors/rest-processor/src/integrationTest/resources/swaggerBaseline-v1.json
> +    "/interop/{holdingidentityshorthash}/delete/identity/{interopidentityshorthash}" : {
New REST APIs should not be added to v1 as this is representation of C5.0 GA release.
I.e. this file should remain unchanged.

Please see my proposed changes to the annotations of newly created methods.

2023-10-06 13:32 UTC, vkolomeyko commented on libs/interop/interop-rest/src/main/kotlin/net/corda/libs/interop/endpoints/v1/InteropRestResource.kt
> +        responseDescription = "Response entity with the status of the request."
```suggestion
        responseDescription = "Response entity with the status of the request.",
        minVersion = RestApiVersion.C5_1
```

2023-10-06 13:32 UTC, vkolomeyko commented on libs/interop/interop-rest/src/main/kotlin/net/corda/libs/interop/endpoints/v1/InteropRestResource.kt
> +        responseDescription = "Response entity with the status of the request."
```suggestion
        responseDescription = "Response entity with the status of the request.",
        minVersion = RestApiVersion.C5_1
```

2023-10-06 13:32 UTC, vkolomeyko commented on libs/interop/interop-rest/src/main/kotlin/net/corda/libs/interop/endpoints/v1/InteropRestResource.kt
> +        responseDescription = "Response entity with the status of the request."
```suggestion
        responseDescription = "Response entity with the status of the request.",
        minVersion = RestApiVersion.C5_1
```

2023-10-06 13:32 UTC, vkolomeyko commented on libs/interop/interop-rest/src/main/kotlin/net/corda/libs/interop/endpoints/v1/types/InteropIdentityResponse.kt
> +    val endpointProtocol: String,
Change to this type will have an effect on `v1` REST API. I think we do need to create an almost identical data container for C5.1 onwards.

2023-10-06 14:14 UTC, ac101m commented on processors/rest-processor/src/integrationTest/resources/swaggerBaseline-v1.json
> +    "/interop/{holdingidentityshorthash}/delete/identity/{interopidentityshorthash}" : {
Yup, we've been kicking this can down the road for some time now. We have been adding interop endpoints since before the 5.0GA and have yet to update our feature branch.

I'll apply your suggestions for the new endpoints introduced here, but fixing this issue for our other endpoints is out of scope for this PR. I've created a [separate ticket](https://r3-cev.atlassian.net/browse/CORE-17530) to move all our existing endpoints to 5.1+ and reset the 5.0 baseline to match that in `release/os/5.1`.

2023-10-06 14:16 UTC, ac101m commented on libs/interop/interop-rest/src/main/kotlin/net/corda/libs/interop/endpoints/v1/types/InteropIdentityResponse.kt
> +    val endpointProtocol: String,
As previously stated, this is going into an interop feature branch where (despite erroneously being added to the 5.0 baseline), all our APIs are unreleased.

2023-10-06 14:31 UTC, ac101m commented on processors/rest-processor/src/integrationTest/resources/swaggerBaseline-v1.json
> +    "/interop/{holdingidentityshorthash}/delete/identity/{interopidentityshorthash}" : {
After thinking about this a little more, this will be quicker to do all at once. Will raise a separate PR for this now.

2023-10-06 14:31 UTC, vkolomeyko approved these changes
Fine to merge into team's branch.

2023-10-06 14:53 UTC, szymonsztuka commented on components/interop/interop-identity-write-service-impl/src/main/kotlin/net/corda/interop/identity/write/impl/HostedIdentityProducer.kt
> +        if (publisher.get() == null) {
We could use a variable:
```
val pub = publisher.get()
```
And the we don't need to cast to not-null (`!!`):
```
val futures = pub.publish(listOf(record))
```
Same suggestion for all new similar code in this PR.

2023-10-06 15:10 UTC, ac101m commented on components/interop/interop-identity-write-service-impl/src/main/kotlin/net/corda/interop/identity/write/impl/HostedIdentityProducer.kt
> +        if (publisher.get() == null) {
Done

2023-10-06 15:18 UTC, szymonsztuka approved these changes

2023-10-09 12:40 UTC, jmacmahonr3 approved these changes
LGTM

2023-10-09 14:56 UTC, merged