CORE-17055 Add CI job for plugin smoke tests
corda/corda-runtime-os pull request #4707
Opened 2023-09-26 13:56 UTC by YashNabar

Adds a CI job for running Corda CLI plugin smoke tests against the Combined Worker. This job is currently set up to be triggered manually during development, and is not run on a schedule or as a PR-gate.

2023-09-26 14:11 UTC, mcgovc commented on .ci/JenkinsfileCombinedWorkerPluginsSmokeTests
> +            sendSlackNotifications("danger", "BUILD FAILURE - Combined Worker E2E Tests", true, "#corda-corda5-build-notifications")
Not sure if you want to send a Slack notification at all, but if keeping this I would say it should be updated to reflect the correct tests. 
```suggestion
            sendSlackNotifications("danger", "BUILD FAILURE - Combined Worker Plugins Smoke Tests", true, "#corda-corda5-build-notifications")
```

2023-09-26 14:16 UTC, YashNabar commented on .ci/JenkinsfileCombinedWorkerPluginsSmokeTests
> +            sendSlackNotifications("danger", "BUILD FAILURE - Combined Worker E2E Tests", true, "#corda-corda5-build-notifications")
Thanks, I've removed that in [2370f04](https://github.com/corda/corda-runtime-os/pull/4707/commits/2370f0451b6cc6bebb2d791ac35c045320c9c042)

2023-09-27 10:38 UTC, YashNabar commented
Plugin smoke tests: https://ci02.dev.r3.com/blue/organizations/jenkins/Corda5%2Fcorda-runtime-os-combined-worker-plugins-smoke-tests/detail/PR-4707/4/tests

2023-09-27 13:07 UTC, dimosr submitted a review, later dismissed
LGTM - I'll leave the BLT team to review the Jenkins/gradle files in a bit more detail as they are the experts on that area.

2023-09-27 13:46 UTC, ronanbrowne requested changes
Minor comment

2023-09-27 13:46 UTC, ronanbrowne commented on .ci/JenkinsfileCombinedWorkerPluginsSmokeTests
> +                    splunkLogGenerator()
```suggestion
```

Minor,  You can remove this, as Splunk will be discontinued at the end of this month.

2023-09-27 14:22 UTC, mcgovc approved these changes
LGTM

2023-09-27 15:41 UTC, ronanbrowne approved these changes
LGTM

2023-09-27 15:43 UTC, dimosr approved these changes

2023-09-27 15:45 UTC, merged