CORE-16797 Apply Kafka topic configurations
corda/corda-runtime-os pull request #4710
Opened 2023-09-26 14:46 UTC by bpaunescu

- Remove `delete` functionality of the topic configuration plugin
- Add ability to apply topics configuration from a user specified file

If a topic already exists, it will not be re-created. This means that if the topic configuration is different, the existing one will remain as we do not delete anything and the configuration cannot be changed in place.

All topic ACLs are applied as specified in the file or generated based on user provided arguments. Access cannot be restricted via the plugin.

2023-09-28 13:49 UTC, simon-johnson-r3 commented on charts/corda-lib/templates/_bootstrap.tpl
> +            'connect',
We can't really allow this change because we've changed the public api.

Even if we believed customers weren't using this tool, we'd have to change the public docs:
https://docs.r3.com/en/platform/corda/5.0/deploying-operating/deployment/deploying/manual-bootstrapping.html

and have to pick through our own codebases and documentation to reflect this. For example I did a quick search in this repo and found a couple of hits at least, e.g. https://github.com/corda/corda-runtime-os/blob/31bcefb4364ef5bc7f93b6d901856d667f37e289/libs/tracing/README.md?plain=1#L82

We deploy Corda in various pipelines and scripts we might be breaking here. And of course this impacts our customers too.

2023-09-28 13:51 UTC, simon-johnson-r3 requested changes
All looks good except to revert the breaking change.

2023-09-29 12:34 UTC, davidcurrie reviewed
LGTM but question for Simon on what should happen to existing topics.

2023-09-29 12:34 UTC, davidcurrie commented on tools/plugins/topic-config/src/main/kotlin/net/corda/cli/plugins/topicconfig/CreateConnect.kt
> +                    println("The following topics already exist and will not be included in the configuration update: " +
@simon-johnson-r3 - is this the expected behaviour for existing topics, or are we expecting to reconcile config to match the latest requirements?

2023-09-29 12:47 UTC, simon-johnson-r3 commented on tools/plugins/topic-config/src/main/kotlin/net/corda/cli/plugins/topicconfig/CreateConnect.kt
> +                    println("The following topics already exist and will not be included in the configuration update: " +
I'd say it's not ideal but we could live with it if we had to.

@bpaunescu is there a technical reason we cannot apply the new configuration?

2023-09-29 13:08 UTC, bpaunescu commented on tools/plugins/topic-config/src/main/kotlin/net/corda/cli/plugins/topicconfig/CreateConnect.kt
> +                    println("The following topics already exist and will not be included in the configuration update: " +
I initially thought it's not possible to update topic configuration, but there is a method `incrementalAlterConfigs()` which takes a map of topic to config and updates. Happy to do that. I believe the previous behaviour of the tool was to either delete or ignore existing topics before applying the configuration.

2023-09-29 14:46 UTC, bpaunescu commented on tools/plugins/topic-config/src/main/kotlin/net/corda/cli/plugins/topicconfig/CreateConnect.kt
> +                    println("The following topics already exist and will not be included in the configuration update: " +
@davidcurrie @simon-johnson-r3 I've updated the code to no longer ignore existing topics. Any configuration either from the preview or from user provided file will be applied as is to existing topics. Existing values are updated, new ones are added. Nothing is removed.

2023-09-29 15:59 UTC, davidcurrie approved these changes
LGTM. Having added the ability to update the config, that does still leave the potential for a mismatch in partition/replica count but that's a harder problem to solve and it sounds like you might be revisiting the partition part anyway.

2023-09-29 16:11 UTC, simon-johnson-r3 approved these changes

2023-09-29 16:56 UTC, merged