CORE-15758 Parallel flow pipeline
corda/corda-runtime-os pull request #4731
Opened 2023-09-28 13:36 UTC by lankydan

2023-10-02 11:33 UTC, lankydan commented
Metrics exposed by the micrometer executor service metrics (couldn't find documentation on them, so had to look them up in grafana):

| Metric                                                        | Type      | Description                                                                           |
|---------------------------------------------------------------|-----------|---------------------------------------------------------------------------------------|
| corda_taskmanager_flow_executor_active_threads	              | gauge	    | The approximate number of threads that are actively executing tasks	                  |
| corda_taskmanager_flow_executor_completed_tasks_total	        | counter	  | The approximate total number of tasks that have completed execution	                  |
| corda_taskmanager_flow_executor_idle_seconds_count	          | counter	  | Count of events that have been observed for the base metric ()	                      |
| corda_taskmanager_flow_executor_idle_seconds_max	            | gauge		  |                                                                                       |
| corda_taskmanager_flow_executor_idle_seconds_sum	            | counter	  | Total sum of all observed values for the base metric ()	                              |
| corda_taskmanager_flow_executor_pool_core_threads	            | gauge	    | The core number of threads for the pool                                               |
| corda_taskmanager_flow_executor_pool_max_threads	            | gauge	    | The maximum allowed number of threads in the pool	                                    |
| corda_taskmanager_flow_executor_pool_size_threads	            | gauge	    | The current number of threads in the pool	                                            |
| corda_taskmanager_flow_executor_queue_remaining_tasks	        | gauge	    | The number of additional elements that this queue can ideally accept without blocking	|
| corda_taskmanager_flow_executor_queued_tasks	                | gauge	    | The approximate number of tasks that are queued for execution	                        |
| corda_taskmanager_flow_executor_scheduled_once_total	        | counter		|                                                                                       |
| corda_taskmanager_flow_executor_scheduled_repetitively_total	| counter		|                                                                                       |
| corda_taskmanager_flow_executor_seconds_count	                | counter	  | Count of events that have been observed for the base metric ()                        |	
| corda_taskmanager_flow_executor_seconds_max	                  | gauge		  |                                                                                       |
| corda_taskmanager_flow_executor_seconds_sum	                  | counter	  | Total sum of all observed values for the base metric ()                               |

2023-10-04 08:55 UTC, ronanbrowne requested changes

2023-10-04 08:55 UTC, ronanbrowne commented on libs/task-manager/build.gradle
> +    compileOnly 'org.osgi:osgi.annotation:8.0.1'
Minor, but my understanding is this dependency version is provided by the java platform sub-module we have in[ corda-api ](https://github.com/corda/corda-api/blob/release/os/5.1/corda-api/build.gradle#L44-L48) which this module also depends on, so expressing a version here is not necessary, much like you have done already with `org.jetbrains.kotlin:kotlin-osgi-bundle`

2023-10-06 16:15 UTC, mbrkic-r3 commented on libs/messaging/messaging-impl/src/main/kotlin/net/corda/messaging/mediator/factory/MultiSourceEventMediatorFactoryImpl.kt
> +            taskManagerFactory.createThreadPoolTaskManager(
@Omar-awad Do we want to use one `TaskManager` instance per worker or it's fine that event mediator has it's own?

2023-10-06 16:15 UTC, mbrkic-r3 commented on libs/metrics/src/main/kotlin/net/corda/metrics/CordaMetrics.kt
> +             * Time it took to execute a task, includes time waiting to be scheduled.
This seems to be wrong (copy of above)

2023-10-06 16:15 UTC, mbrkic-r3 commented on libs/serialization/serialization-kryo/src/main/kotlin/net/corda/kryoserialization/impl/KryoCheckpointSerializerBuilderImpl.kt
> +        val pool = object : Pool<Kryo>(true, false, 8) {
Parameter `maximumCapacity` shouldn't be hardcoded. Number of parallel flow executions should be configurable   (and also used by flow engine instance of event mediator).

2023-10-06 16:15 UTC, mbrkic-r3 commented on libs/messaging/messaging-impl/src/main/kotlin/net/corda/messaging/mediator/factory/MultiSourceEventMediatorFactoryImpl.kt
> +                threads = 8
Parameter `threads` shouldn't be hardcoded but come from `EventMediatorConfig`.

2023-10-06 16:15 UTC, mbrkic-r3 commented on libs/serialization/serialization-kryo/src/main/kotlin/net/corda/kryoserialization/impl/KryoCheckpointSerializerBuilderImpl.kt
> +                this.peak
Is this needed?

2023-10-06 16:15 UTC, mbrkic-r3 commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/fiber/factory/FlowFiberFactoryImpl.kt
> +    private val currentThreadFiberExecutor = object : FiberExecutorScheduler("Flow Fiber scheduler", SameThreadExecutor.getExecutor()) {
What happens when current thread is used to run `Fiber`, is it blocked until `Fiber` is finished? I'm wondering whether timeout detection will work while `Fiber` is running (i.e. line below is not executed after `Fiber` is already finished).
https://github.com/corda/corda-runtime-os/blob/release/os/5.1/components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/impl/FlowExecutionPipelineStage.kt#L94

2023-10-10 08:29 UTC, lankydan commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/fiber/factory/FlowFiberFactoryImpl.kt
> +    private val currentThreadFiberExecutor = object : FiberExecutorScheduler("Flow Fiber scheduler", SameThreadExecutor.getExecutor()) {
It blocks the current thread.

The same thread executor literally calls the fiber's run method and returns once its finished.

If we want timeout detection then we're probably better off using a normal thread pool instead.

2023-10-10 11:07 UTC, lankydan commented on libs/messaging/messaging-impl/src/main/kotlin/net/corda/messaging/mediator/factory/MultiSourceEventMediatorFactoryImpl.kt
> +                threads = 8
Raised https://github.com/corda/corda-api/pull/1287 to support this change.

2023-10-10 11:08 UTC, lankydan commented on libs/serialization/serialization-kryo/src/main/kotlin/net/corda/kryoserialization/impl/KryoCheckpointSerializerBuilderImpl.kt
> +        val pool = object : Pool<Kryo>(true, false, 8) {
Not hard coding this is going to be a larger change since this configuration of the kryo serializer is pretty deep down and I can't see (right now) how to pass a config object to it.

Can we merge this PR as is and we can raise a ticket to sort out the configuration?

2023-10-10 11:12 UTC, mbrkic-r3 commented on libs/serialization/serialization-kryo/src/main/kotlin/net/corda/kryoserialization/impl/KryoCheckpointSerializerBuilderImpl.kt
> +        val pool = object : Pool<Kryo>(true, false, 8) {
Yes, please rise a ticket for it.

2023-10-10 11:19 UTC, mbrkic-r3 commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/fiber/factory/FlowFiberFactoryImpl.kt
> +    private val currentThreadFiberExecutor = object : FiberExecutorScheduler("Flow Fiber scheduler", SameThreadExecutor.getExecutor()) {
Could you please create a ticket to take a look how to solve that later.

2023-10-11 12:45 UTC, driessamyn approved these changes, later dismissed
LGTM

2023-10-11 12:45 UTC, driessamyn commented on libs/task-manager/build.gradle
> +    implementation "com.google.guava:guava:$guavaVersion"
Is it worth bringing Guava in just for the `ThreadFactoryBuilder`? Isn't that one of the libs we always have trouble patching etc?

2023-10-11 13:03 UTC, lankydan commented on libs/task-manager/build.gradle
> +    implementation "com.google.guava:guava:$guavaVersion"
I can try take it out, its just the way I common setup thread names.

2023-10-12 13:09 UTC, lankydan commented
API PR - https://github.com/corda/corda-api/pull/1287

2023-10-13 15:28 UTC, ronanbrowne submitted a review, later dismissed
LGTM re buid / my inial comments

2023-10-16 08:22 UTC, rick-r3 commented on libs/serialization/serialization-kryo/src/main/kotlin/net/corda/kryoserialization/impl/KryoCheckpointSerializerBuilderImpl.kt
> +        val pool = object : Pool<Kryo>(true, false, 8) {
There's no need to set an upper bound is there?  The default is `Integer.MAX_VALUE`.  It only makes instances if none are available, and so it will make the _minimum_ necessary.    Unless you are trying to constrain parallelism using this bound.... but a thread pool would be a more natural way to do that.

2023-10-16 08:22 UTC, rick-r3 commented on libs/serialization/serialization-kryo/src/test/kotlin/net/corda/kryoserialization/KryoCheckpointSerializerTest.kt
> +        return object : Pool<Kryo>(true, false, 4) {
Again, presumably no need to define an upper bound.

2023-10-16 08:22 UTC, rick-r3 commented on libs/serialization/serialization-kryo/src/test/kotlin/net/corda/kryoserialization/serializers/SingletonSerializeAsTokenSerializerTest.kt
> +        return object : Pool<Kryo>(true, false, 4) {
No need for upper bound

2023-10-16 15:30 UTC, driessamyn approved these changes
LGTM

2023-10-16 16:07 UTC, merged