CORE-17437: State Manager Configuration Section
corda/corda-runtime-os pull request #4780
Opened 2023-10-05 11:24 UTC by jujoramos

Promote State Manager configuration to its own section and remove it
from under the Messaging configuration.

2023-10-05 19:54 UTC, jujoramos commented
Related api change: https://github.com/corda/corda-api/pull/1277

2023-10-06 13:00 UTC, sprintengine commented on libs/application/application-db-setup/src/main/kotlin/net/corda/application/dbsetup/PostgresDbSetup.kt
> +            "net/corda/db/schema/state-manager/db.changelog-master.xml" to "STATE_MANAGER",
we also need to change this in _bootstrap.tpl. however, I already know this isn't working correctly, and I've made changes to calling database spec in two other branches, so I think leave it for now to reduce my merge conflicts.

2023-10-06 13:00 UTC, sprintengine commented on libs/configuration/configuration-merger/src/main/kotlin/net/corda/libs/configuration/merger/ConfigMerger.kt
> +    fun getConfig(bootConfig: SmartConfig, configKey: String, existingConfig: SmartConfig?): SmartConfig
Yeah this is a better API

2023-10-06 13:00 UTC, sprintengine commented on libs/configuration/configuration-validation/src/main/kotlin/net/corda/libs/configuration/validation/impl/ConfigurationValidatorImpl.kt
> +            isTypeLoose = true
+1 

This validator does appear to be set up to apply defaults when a property is missing, but perhaps not when an object is missing. Wonder what is the correct approach to get defaults applied, maybe our state-manager config schema is missing a default object. For example, the defaults weren't getting applied to the state manager jdbc directory. Something I might try out at a later time when I get some free time.

2023-10-06 13:00 UTC, sprintengine commented on applications/workers/worker-common/src/test/kotlin/net/corda/applications/workers/workercommon/internal/BootstrapConfigTest.kt
> -    }
Surely if the "isLooseType" setting works, this test should still pass?

2023-10-06 15:43 UTC, conalsmith-r3 commented on libs/application/application-db-setup/src/main/kotlin/net/corda/application/dbsetup/PostgresDbSetup.kt
> +            "net/corda/db/schema/state-manager/db.changelog-master.xml" to "STATE_MANAGER",
If I merge PR-4791 first, you'll have to update the bootstrap template https://github.com/corda/corda-runtime-os/pull/4791/files#diff-6488cdf0bdcc5c363da8948f42ead979f4346e4fcff509d46f959ab517fcecd6

2023-10-09 11:05 UTC, jujoramos commented on libs/application/application-db-setup/src/main/kotlin/net/corda/application/dbsetup/PostgresDbSetup.kt
> +            "net/corda/db/schema/state-manager/db.changelog-master.xml" to "STATE_MANAGER",
👍

2023-10-09 11:06 UTC, jujoramos commented on libs/configuration/configuration-validation/src/main/kotlin/net/corda/libs/configuration/validation/impl/ConfigurationValidatorImpl.kt
> +            isTypeLoose = true
Agreed in that we might want to test the defaulting part further in the future but, as you correctly stated, that shouldn't be part of this `PR` so I'll resolve this comment 👍

2023-10-09 11:23 UTC, jujoramos commented on applications/workers/worker-common/src/test/kotlin/net/corda/applications/workers/workercommon/internal/BootstrapConfigTest.kt
> -    }
The test passes just fine, yeah, but we are not manually casting the properties ourselves anymore so I don't think the test belong here. I'll add another one under `ConfigurationValidatorImplTest` instead.

2023-10-09 14:43 UTC, JamesHR3 approved these changes, later dismissed

2023-10-09 16:06 UTC, mbrkic-r3 submitted a review, later dismissed

2023-10-09 16:16 UTC, JamesHR3 submitted a review, later dismissed

2023-10-09 16:16 UTC, conalsmith-r3 submitted a review, later dismissed

2023-10-09 16:32 UTC, mbrkic-r3 submitted a review, later dismissed

2023-10-09 16:53 UTC, simon-johnson-r3 submitted a review, later dismissed

2023-10-09 16:54 UTC, driessamyn requested changes

2023-10-09 16:54 UTC, driessamyn commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/maintenance/FlowMaintenanceImpl.kt
> +        if (config.containsKey(ConfigKeys.STATE_MANAGER_CONFIG)) {
I don't think this is correct as this assumes that the messaging config is always already there when the state manager config arrives. 

I think they need to be treated separate.

2023-10-10 08:23 UTC, driessamyn approved these changes
LGTM

2023-10-10 08:31 UTC, JamesHR3 approved these changes

2023-10-10 08:32 UTC, merged