CORE-16966: Proof of Action Lock State (Part 2)
corda/corda-runtime-os pull request #4786
Opened 2023-10-05 15:53 UTC by julia-filipczak

Adding the reclaim functionality to the atomic swap cordapp.

2023-10-10 13:31 UTC, szymonsztuka requested changes

2023-10-10 13:31 UTC, szymonsztuka commented on testing/cpbs/atomic-swap-contracts/src/main/kotlin/com/r3/corda/atomic/swap/contracts/LockContract.kt
> +                "Only lock state creator can do a reclaim" using (transaction.signatories.contains(inputLockState.creator))
This checks if one of the signatories is the creator, but doesn't check the direction in which the assets was transferred. What if both parties signed a transaction, that this check passes regardless who is receiving the asset (I know that this is highly unlikely scenario).

2023-10-10 13:34 UTC, jmacmahonr3 commented on testing/cpbs/atomic-swap-contracts/src/main/kotlin/com/r3/corda/atomic/swap/contracts/AssetContract.kt
> -                val input = transaction.getInputStates(Asset::class.java).first()
I'd add a todo or reach out to the ledger team about composite keys being considered the same owner. This is fine for now but it's important to keep in mind

2023-10-10 16:01 UTC, szymonsztuka requested changes

2023-10-10 16:01 UTC, szymonsztuka commented on testing/cpbs/atomic-swap-contracts/src/main/kotlin/com/r3/corda/atomic/swap/contracts/LockContract.kt
> +                val inputLockState = transaction.getInputStates(LockState::class.java).first()
Move this line after the line with the check `transaction.getInputStates(LockState::class.java).size == 1`, once we know we have a lock state then we can safely access it via `.first()` without worry of throwing NullPointerException.

2023-10-12 08:50 UTC, szymonsztuka commented on testing/cpbs/atomic-swap-contracts/src/main/kotlin/com/r3/corda/atomic/swap/contracts/LockContract.kt
> +                val timeWindowUntil = transaction.timeWindow.from
Maybe this variable should be called `timeWindowFrom` or maybe better `recailTransactionStartTime` or something like that?

2023-10-12 08:50 UTC, szymonsztuka commented on testing/cpbs/atomic-swap-contracts/src/main/kotlin/com/r3/corda/atomic/swap/contracts/LockContract.kt
> +                        "only after the time-window to claim the encumbered assets" using (timeWindowUntil != null &&
I'm finding this error message a bit confusing : it roughly have two messages:  "_a time window hasn't expired_" , "_a time window needs to start after some other time window_" , + inconsistent wording "time widow" vs "time-window".

2023-10-12 08:50 UTC, szymonsztuka commented on testing/cpbs/atomic-swap-workflows/src/main/kotlin/com/r3/corda/atomic/swap/workflows/ReclaimFlow.kt
> +            val timeWindowForReclaim = lockState.state.contractState.timeWindow.plusSeconds(31)
Why 31?

2023-10-12 08:50 UTC, szymonsztuka commented on testing/cpbs/atomic-swap-workflows/src/main/kotlin/com/r3/corda/atomic/swap/workflows/ReclaimFlow.kt
> +
remove the extra line

2023-10-12 08:50 UTC, szymonsztuka commented on testing/cpbs/atomic-swap-workflows/src/main/kotlin/com/r3/corda/atomic/swap/workflows/ReclaimFlow.kt
> +                .setTimeWindowBetween(timeWindowForReclaim, Instant.now())
I'm quite surprised how this can work, in normal system there will be always i minimal delay between a transaction creation and sending it to notary,  so notary will never have chance to sign this transaction if the time window expiration in set to `Instant.now()`

2023-10-12 08:53 UTC, szymonsztuka commented on testing/cpbs/atomic-swap-workflows/src/main/kotlin/com/r3/corda/atomic/swap/workflows/ReclaimFlow.kt
> +                .setTimeWindowBetween(timeWindowForReclaim, Instant.now())
Maybe this transaction is not notarized by a notary, or the notary has disabled time window checking?

2023-10-12 10:25 UTC, szymonsztuka requested changes

2023-10-12 10:25 UTC, szymonsztuka commented on testing/cpbs/atomic-swap-contracts/src/main/kotlin/com/r3/corda/atomic/swap/contracts/LockContract.kt
> +                        transaction.timeWindow.until < reclaimTransactionStartTime.plusSeconds(86400))
Remove this ad-hoc rule, why one day? Anyway this makes reclaim testing impossible.

2023-10-12 10:43 UTC, julia-filipczak commented on testing/cpbs/atomic-swap-workflows/src/main/kotlin/com/r3/corda/atomic/swap/workflows/ReclaimFlow.kt
> +            val timeWindowForReclaim = lockState.state.contractState.timeWindow.plusSeconds(31)
Just a random number

2023-10-12 10:46 UTC, julia-filipczak commented on testing/cpbs/atomic-swap-contracts/src/main/kotlin/com/r3/corda/atomic/swap/contracts/LockContract.kt
> +                        transaction.timeWindow.until < reclaimTransactionStartTime.plusSeconds(86400))
Setting an upper limit so that the time window doesn't last for ages. Can change it to a different value. Why does it make testing impossible?

2023-10-12 11:47 UTC, szymonsztuka commented on testing/cpbs/atomic-swap-contracts/src/main/kotlin/com/r3/corda/atomic/swap/contracts/LockContract.kt
> +                        transaction.timeWindow.until < reclaimTransactionStartTime.plusSeconds(86400))
Ok, right, true it doesn't impact testing. However we should not decided that you can only 24 hours reclaim window opportunity. The asset may stuck forever in limbo. Rather I would expect the new owner has fixed amount of time to unlock. But anyway if we want to model this we probably need to have optional values in the lock state set at the beginning e.g.: I give you X and you have unlimited time to unlock but after Y time I can reclaim, and then I have limited time to reclaim. Or the other option you have limited time to unlock after i have unlimited time to reclaim. But for sure such values should not be hard-coded in the contract code designed to be a general example.

2023-10-12 11:49 UTC, szymonsztuka commented on testing/cpbs/atomic-swap-workflows/src/main/kotlin/com/r3/corda/atomic/swap/workflows/ReclaimFlow.kt
> +            val timeWindowForReclaim = lockState.state.contractState.timeWindow.plusSeconds(31)
Make it 30 seconds but also allow to pass the value to the flow, so user can tune it, make this parameter optional and if user doesn't provide a value set to 30 seconds.

2023-10-12 15:11 UTC, szymonsztuka approved these changes

2023-10-12 15:31 UTC, szymonsztuka approved these changes

2023-10-12 16:08 UTC, merged