CORE-10180: Escape string parameters when creating json to prevent possible injection attacks
corda/corda-runtime-os pull request #4825
Opened 2023-10-10 15:24 UTC by anien

- Escape string parameters
- Fix most of the kdoc parameters

2023-10-10 15:28 UTC, dickon commented
Looks okay, probably needs some unit tests.

2023-10-10 18:46 UTC, ronanbrowne requested changes
See dependency query

2023-10-10 18:46 UTC, ronanbrowne commented on tools/plugins/initial-config/build.gradle
> +    implementation "com.fasterxml.jackson.core:jackson-databind:$jacksonVersion"
Just double-checking you need

`implementation "com.fasterxml.jackson.core:jackson-databind:$jacksonVersion"`

as I see you are only using 

`com.fasterxml.jackson.module.kotlin.jacksonObjectMapper
`

2023-10-11 07:35 UTC, anien commented on tools/plugins/initial-config/build.gradle
> +    implementation "com.fasterxml.jackson.core:jackson-databind:$jacksonVersion"
Ah, good point. I was trying few bits and didn't check at the end which packages I need at the end. I'll double check.

2023-11-08 16:33 UTC, dickon commented
LGTM

2023-11-08 16:33 UTC, dickon approved these changes, later dismissed
LGTM

2023-11-14 09:57 UTC, closed without merging

2023-11-14 09:57 UTC, anien commented
Changing base branch shows some outstanding commits that shouldn't be part of this PR. I'll create a new one.