CORE-17733 - batch the creation of states in state-manager
corda/corda-runtime-os pull request #4942
Opened 2023-10-20 11:11 UTC by conalsmith-r3

Splitting this out into its own PR as it is potentially more risky

2023-10-20 12:24 UTC, jujoramos requested changes

2023-10-20 12:24 UTC, jujoramos commented on libs/state-manager/state-manager-db-impl/src/integrationTest/kotlin/net/corda/libs/statemanager/impl/tests/StateManagerIntegrationTest.kt
> +
Can we use the query from `queryProvider` instead?

2023-10-20 12:24 UTC, jujoramos commented on libs/state-manager/state-manager-db-impl/src/main/kotlin/net/corda/libs/statemanager/impl/repository/impl/StateRepositoryImpl.kt
> +            // - If optimistic locking check fails for a statement in the batch, that statement will have a '0' in the 'results' array.
There is not optimistic locking for the create statement, the insert can only fail if the unique key is violated, right?

2023-10-20 12:40 UTC, conalsmith-r3 commented on libs/state-manager/state-manager-db-impl/src/main/kotlin/net/corda/libs/statemanager/impl/repository/impl/StateRepositoryImpl.kt
> +            // - If optimistic locking check fails for a statement in the batch, that statement will have a '0' in the 'results' array.
Good spot I copy/pasted this, if insert fails the query returns a "0" in the result IntArray

2023-10-20 12:43 UTC, conalsmith-r3 commented on libs/state-manager/state-manager-db-impl/src/integrationTest/kotlin/net/corda/libs/statemanager/impl/tests/StateManagerIntegrationTest.kt
> +
Yeah I can change this function to use positional parameters instead of named parameters,

2023-10-23 10:22 UTC, jujoramos commented on libs/state-manager/state-manager-db-impl/src/integrationTest/kotlin/net/corda/libs/statemanager/impl/tests/StateManagerIntegrationTest.kt
> +import java.util.*
Weird that `detekt` didn't pick this up?, shouldn't we use specific imports instead of the wildcard?.

2023-10-23 13:31 UTC, conalsmith-r3 commented on libs/state-manager/state-manager-db-impl/src/main/kotlin/net/corda/libs/statemanager/impl/repository/impl/PostgresQueryProvider.kt
> +            ON CONFLICT DO NOTHING
I added a test where it tries to create some states with a primary key too long for the column.

The test does not behave exactly as expected:

**Expected outcome:** 
The failing prepared statement commands will be added to the results `IntArray` with a "EXECUTE_FAILED" value (-2)

**Actual outcome:**
The entire batch is aborted with an exception:
```
java.sql.BatchUpdateException: Batch entry 0 INSERT INTO state
VALUES ('key_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx1-fabf5853-8b61-4fcf-a282-822a729e549d', ?, 0, CAST('{}' as JSONB), CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
ON CONFLICT DO NOTHING was aborted: ERROR: value too long for type character varying(255)  Call getNextException to see other errors in the batch.
	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:165)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2402)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:574)
	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:896)
	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:919)
	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1685)
	at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:127)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java)
	at net.corda.libs.statemanager.impl.repository.impl.StateRepositoryImpl.create(StateRepositoryImpl.kt:26)
	at net.corda.libs.statemanager.impl.StateManagerImpl.create(StateManagerImpl.kt:39)
	at net.corda.libs.statemanager.impl.tests.StateManagerIntegrationTest.primaryKeyLengthFailuresWhenPersistingSomeStatesDoesNotHaltTheEntireBatch(StateManagerIntegrationTest.kt:218)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: org.postgresql.util.PSQLException: ERROR: value too long for type character varying(255)
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2713)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2401)
	... 12 more
```

2023-10-23 20:22 UTC, conalsmith-r3 commented on libs/state-manager/state-manager-db-impl/src/main/kotlin/net/corda/libs/statemanager/impl/repository/impl/PostgresQueryProvider.kt
> +            ON CONFLICT DO NOTHING
I made some changes to address this scenario.

It is likely an edge case, but an edge case that actually came up today in [slack discussions](https://r3holdco.slack.com/archives/C03ABNX2RHP/p1698047294341219)

2023-10-23 21:00 UTC, conalsmith-r3 commented on libs/state-manager/state-manager-db-impl/src/main/kotlin/net/corda/libs/statemanager/impl/StateManagerImpl.kt
> +            logger.info("Error during batch state creation. Retrying creation of ${e.failedStates.size} states without batching.", e)
Conflicts, such as a primary key already exists, are handled in the batch create function. They are "ignored" and return a 0 which is translated to a "failed key".

This logic may be overkill, but catches errors in the batch such as `value too long for type character varying(255)`. These aren't treated as conflicts by postgres driver, but abort the entire batch.

Aborting entire batch is unnecessary because some states in a batch could be perfectly fine. Re-attempting to create these states individually will avoid infinite loop of flow engine retries and states in the same batch never completing.

2023-12-12 00:01 UTC, closed without merging