CORE-17881: [WIP] Individual State Manager Per Worker Type
corda/corda-runtime-os pull request #4948
Opened 2023-10-20 14:20 UTC by jujoramos

2023-10-20 15:43 UTC, davidcurrie commented on charts/corda-lib/templates/_bootstrap.tpl
> +kind: Job
My previous comment about running these jobs serially being sub-optimal still stands.

2023-10-20 15:43 UTC, davidcurrie commented on charts/corda-lib/templates/_bootstrap.tpl
> +            {{- include "corda.bootstrapStateManagerDbEnv" ( list $ $worker $workerKey $authConfig ) | nindent 12 }}
I think this should be `corda.stateManagerDbEnv`; otherwise, we're putting the bootstrap credentials into the `db_connections` table. (Looks like this may have been an existing issue.)

2023-10-20 15:43 UTC, davidcurrie commented on charts/corda-lib/templates/_stateManager.tpl
> +{{- end -}}
The same comment I made on Conal's original PR: this conditional is redundant. You could just use the first branch and then all of the parts fall through to their respective cluster DB equivalents anyway.

2023-10-20 15:43 UTC, davidcurrie commented on charts/corda-lib/templates/_stateManager.tpl
> +        {{- end }}
nit: this section is doubly indented

2023-10-20 15:43 UTC, davidcurrie commented on charts/corda-lib/templates/_stateManager.tpl
> +        {{- if $worker.stateManager.db.host }}
ditto

2023-10-20 15:43 UTC, davidcurrie commented on charts/corda-lib/templates/_stateManager.tpl
> +        {{- if $worker.stateManager.db.host }}
ditto

2023-10-20 15:43 UTC, davidcurrie commented on charts/corda-lib/templates/_stateManager.tpl
> +        {{- if $worker.stateManager.db.host }}
ditto

2023-10-20 15:43 UTC, davidcurrie commented on charts/corda/templates/bootstrap.yaml
> +{{-     if and (not $workerConfig.stateManager.db.host) (ne $authConfig.username.value "") (not $authConfig.valueFrom) -}}
`""` is falsy and I think you need to look all the way down to the secret name making the logic something like:
```suggestion
{{-     if and ( not $workerConfig.stateManager.db.host ) ( not $authConfig.username.value ) ( not $authConfig.valueFrom.secretKeyRef.name ) -}}
```

2023-10-20 15:43 UTC, davidcurrie commented on charts/corda/templates/bootstrap.yaml
> +{{-       fail ( printf "Must specify workers.%s.stateManager.host when bootstrap.db.stateManager.%s is configured" $workerName $workerName ) }}
Is the error message the wrong way round? When they specify a separate host, they need to provide credentials?

2023-10-20 15:43 UTC, davidcurrie commented on charts/corda/templates/secrets.yaml
> +{{-   if and ($workerConfig.stateManager) ($workerConfig.stateManager.db.host) ($workerConfig.stateManager.db.username) (and (or ($workerConfig.stateManager.db.username.value) ($workerConfig.stateMan
We deliberately specify a supported version of `helm` that doesn't have this problem but, FYI, older versions of go-template did not have lazy evaluation so you had to nest conditionals rather than using `and`. Also worth noting that you can use parentheses to trap null pointers e.g. `( ( $workerConfig.stateManager ).db.host )` will evaluate to `null` if `$workerConfig.stateManager` is `null` rather than failing.

2023-10-20 15:43 UTC, davidcurrie commented on charts/corda/templates/secrets.yaml
> +{{-   if and ($workerConfig.stateManager) ($workerConfig.stateManager.db.host) ($workerConfig.stateManager.db.username) (and (or ($workerConfig.stateManager.db.username.value) ($workerConfig.stateMan
All that said, I don't understand why this is checking anything other than that `db.host` has been set?

2023-10-20 15:46 UTC, davidcurrie commented on charts/corda-lib/templates/_bootstrap.tpl
> +            {{- include "corda.bootstrapStateManagerDbEnv" ( list $ $worker $workerKey $authConfig ) | nindent 12 }}
Ignore that - I remember you telling me before that this isn't populating `db_connections`, it's using the credentials with liquibase.

2023-10-20 15:50 UTC, jujoramos commented on charts/corda-lib/templates/_bootstrap.tpl
> +kind: Job
It is sub-optimal, agreed, but I would need some bash magic in order to pass an arbitrary list of credentials and generate them one by one within a single job (different workers can connect to different state manager databases)... I'll create a ticket or something to improve it in the future (this part is not user facing so we can do it after the release).

2023-10-20 15:51 UTC, jujoramos commented on charts/corda-lib/templates/_stateManager.tpl
> +{{- end -}}
I'd need to an extra function for `{{- $workerConfig.stateManager.db.host -}}` in that case 🤔

2023-10-20 15:53 UTC, jujoramos commented on charts/corda-lib/templates/_stateManager.tpl
> +        {{- end }}
What do you mean?, I've tested the chart with different options to verify all branches and the resulting yaml file seemed correct 🤔

2023-10-20 15:53 UTC, davidcurrie commented on charts/corda-lib/templates/_bootstrap.tpl
> +kind: Job
It's kind of user-facing in that they're the ones who have to sit there while the pre-install jobs take an age to run through. It's certainly not going to help the setup times for our tests. I don't think there's any bash magic required - just take the same logic you have for iterating to create the jobs and iterate to create containers within a job.

2023-10-20 15:54 UTC, davidcurrie commented on charts/corda-lib/templates/_stateManager.tpl
> +{{- end -}}
You're right - I missed that one.

2023-10-20 15:55 UTC, davidcurrie commented on charts/corda-lib/templates/_stateManager.tpl
> +        {{- end }}
It'll be valid YAML but whereas you have an explicit indent of 6 for the bootstrap user, you have an indent of 8 for everything else.

2023-10-20 15:58 UTC, davidcurrie commented on charts/corda-lib/templates/_stateManager.tpl
> +        {{- end }}
But don't check the 6 to 8! The indentation is two spaces so it should be 6 here not 8.

2023-10-20 16:09 UTC, jujoramos commented on charts/corda-lib/templates/_stateManager.tpl
> +        {{- end }}
Will make the change, thanks 👍

2023-10-20 16:09 UTC, jujoramos commented on charts/corda-lib/templates/_stateManager.tpl
> +        {{- if $worker.stateManager.db.host }}
Will make the change, thanks 👍

2023-10-20 16:09 UTC, jujoramos commented on charts/corda-lib/templates/_stateManager.tpl
> +        {{- if $worker.stateManager.db.host }}
Will make the change, thanks 👍

2023-10-20 16:09 UTC, jujoramos commented on charts/corda-lib/templates/_stateManager.tpl
> +        {{- if $worker.stateManager.db.host }}
Will make the change, thanks 👍

2023-10-20 20:45 UTC, jujoramos commented on charts/corda/templates/secrets.yaml
> +{{-   if and ($workerConfig.stateManager) ($workerConfig.stateManager.db.host) ($workerConfig.stateManager.db.username) (and (or ($workerConfig.stateManager.db.username.value) ($workerConfig.stateMan
👍

2023-10-21 14:29 UTC, jujoramos commented on charts/corda/templates/bootstrap.yaml
> +{{-     if and (not $workerConfig.stateManager.db.host) (ne $authConfig.username.value "") (not $authConfig.valueFrom) -}}
Done (used another approach and improved the condition, though)

2023-10-21 14:30 UTC, jujoramos commented on charts/corda/templates/bootstrap.yaml
> +{{-       fail ( printf "Must specify workers.%s.stateManager.host when bootstrap.db.stateManager.%s is configured" $workerName $workerName ) }}
👍

2023-10-22 20:08 UTC, jujoramos commented on charts/corda-lib/templates/_bootstrap.tpl
> +kind: Job
I've tried using the same approach as with the regular bootstrap job (one `init-container` to generate the `sql` and one `container` to apply it), but it causes issues when trying to deploy Corda against a single state manager database instance (the developer use case I imagine), basically because the same Liquibase file is applied in parallel and the sql doesn't contain the `IF NOT EXISTS` for the `databasechangeloglock` table (containers executed within a `Job` are all started at once):
```
apply-state-manager-flow-mapper-worker Applying State Manager Specification for flow-mapper-worker...
apply-state-manager-flow-mapper-worker psql:/tmp/stateManager-flowMapper/statemanager.sql:2: NOTICE:  schema "state_manager" already exists, skipping
apply-state-manager-flow-mapper-worker psql:/tmp/stateManager-flowMapper/statemanager.sql:20: ERROR:  relation "databasechangeloglock" already exists

apply-state-manager-flow-worker Applying State Manager Specification for flow-worker...
apply-state-manager-flow-worker Applying State Manager Specification for flow-worker... Done!
```

---

Instead of the regular approach, so, I've included the state manager initialisation into the existing `setup-db` job but purely through `init-containers` to force sequential execution (is slower than before as we have more `init-containers`, but it's still faster than the original approach within the `PR` of having yet another 2 Jobs for the state manager setup).

2023-10-23 11:47 UTC, conalsmith-r3 reviewed
LGTM, tested helm template debug with a few state-manager overrides and it works as expected
```
helm template corda charts/corda --debug --values values-prereqs.yaml --values state-manager.yaml >  with-state-manager-yaml.txt
```

Tested without state-manager.yaml and it defaults correctly to cluster.
```
helm template corda charts/corda --debug --values values-prereqs.yaml >  without-sm.txt
```

Happy to approve once endToEndPipeline is merged

2023-10-23 12:44 UTC, conalsmith-r3 approved these changes
lgtm

2023-10-23 12:45 UTC, ronanbrowne approved these changes
LGTM

2023-10-23 12:49 UTC, JasonSinclair95 requested changes

2023-10-23 12:49 UTC, JasonSinclair95 commented on .ci/e2eTests/corda.yaml
> +      flow:
Do you still need this declared in the corda.yaml when the exact same is declared in the file [state-manager.yaml](https://github.com/corda/corda-runtime-os/pull/4948/files#diff-846a5c1c17ed9e802428faa4a5a513055ac384c16426c47ca3ad1b9b03ccd4f0)

2023-10-23 12:54 UTC, jujoramos commented on .ci/e2eTests/corda.yaml
> +      flow:
We need this here, yes, not only because the credentials are different, but because the files are used for different use cases (one for the pipeline, the other one for local deployment during development).

2023-10-23 12:56 UTC, JasonSinclair95 approved these changes
LGTM

2023-10-23 13:56 UTC, merged