CORE-17389: Process flow timeout events and clean up checkpoints
corda/corda-runtime-os pull request #4951
Opened 2023-10-20 15:50 UTC by JamesHR3

### Problem description

The flow engine currently responds to scheduled task triggers to produce flow timeout events when a session has timed out. These need to be processed to remove the timed out checkpoint and send any cleanup events (session errors and mapper cleanup events) to the rest of the system. The flow status also needs to be updated.

### Solution

Add a processor for the flow timeout events.

This PR also includes a checkpoint cleanup handler class, which generates the relevant events for when a flow is terminated with an error. This can be reused in the `FlowEventExceptionProcessor`, although this has not been integrated in this PR. The objective here is to encapsulate this cleanup logic. At present, there is a bug in the flow engine that means not all of this logic is present everywhere it is needed.

2023-10-24 15:05 UTC, LWogan approved these changes
I've made a small update to handle cleanup of flow mapper ERROR states. This could do with a followup when the state storage API can handle multiple MetaDataFilters +  TS query in a single query. 

I've raised a number of bugs related to some states not getting cleaned up. The main one is that we dont handle cleanup properly in the flow engine flow fatal exception handler for RPC mapper states. This was always there and can be handled by reusing the helper class added by this pr.

Theres also a small bug in the UtxoDemoFlow which results in a checkpoint that lingers which needs investigation, that i would have expected to have been solved by this pr.

But the main logic works so im happy to approve

2023-10-24 15:26 UTC, LWogan requested changes
redacted my last approval. I think theres an issue with the flow session timeout checkpoint cleanup part

2023-10-25 09:22 UTC, LWogan approved these changes
I've made some updates to handle:
- ERROR flow mapper state cleanup
- merging messaging config values into flow config for use by the flow session cleanup logic

I've raised some bugs around:
- flow engine does not cleanup RPC flow mapper states
- UtxoDemoFlow leaves sessions in a hung state (eventually cleaned up by logic in this pr)

Other than that this PR looks good to me. We should make use of the FlowMaintenance class in the flow engine to avoid duplicate code. A ticket has been raised for this.

2023-10-25 13:34 UTC, Omar-awad approved these changes
LGTM

2023-10-25 13:49 UTC, merged