DA5-8 Prerequisites for Serialize Merkle Proof - test base.
corda/corda-runtime-os pull request #5000
Opened 2023-10-27 11:10 UTC by szymonsztuka

Test signature proof generation by a notary. Add ability for UtxoLedgerTest to sign a batch transaction in order to generate Merkle Tree Proof. The existing UtxoLedgerTest had hardcoded signatures without calling singing service (or a mock), and there was never a proof produced (as not needed so far).

2023-10-27 12:22 UTC, vlajos submitted a review, later dismissed

2023-10-27 14:10 UTC, LWogan commented
5000! :)

2023-10-27 14:18 UTC, szymonsztuka commented
> 5000! :)

I won!

2023-10-27 16:05 UTC, ac101m requested changes
No major problems that I can see

2023-10-27 16:05 UTC, ac101m commented on testing/ledger/ledger-utxo-base-test/src/main/kotlin/net/corda/ledger/utxo/test/UtxoLedgerWithBatchSignerTest.kt
> + * Extension of [UtxoLedgerTest] base class with [singingService] service. The service can sign a batch of transactions
singing service?
:notes:

2023-10-27 16:05 UTC, ac101m commented on testing/ledger/ledger-utxo-base-test/src/main/kotlin/net/corda/ledger/utxo/test/UtxoLedgerWithBatchSignerTest.kt
> +    val singingService = TransactionSignatureServiceImpl(
:musical_note:

2023-10-27 16:30 UTC, szymonsztuka commented on testing/ledger/ledger-utxo-base-test/src/main/kotlin/net/corda/ledger/utxo/test/UtxoLedgerWithBatchSignerTest.kt
> + * Extension of [UtxoLedgerTest] base class with [singingService] service. The service can sign a batch of transactions
Fixed in https://github.com/corda/corda-runtime-os/pull/5000/commits/fd704d84816c6540085f0a2f56ea39d534c858eb

2023-10-30 07:51 UTC, vlajos approved these changes

2023-10-30 10:52 UTC, ac101m approved these changes
LGTM

2023-10-30 10:54 UTC, merged