CORE-17951 - State manager concurrent optimistic locking tests
corda/corda-runtime-os pull request #5028
Opened 2023-11-01 16:54 UTC by conalsmith-r3

2023-11-01 16:58 UTC, conalsmith-r3 commented on libs/state-manager/state-manager-db-impl/src/integrationTest/kotlin/net/corda/libs/statemanager/impl/tests/StateManagerIntegrationTest.kt
> -        val latch = CountDownLatch(1)
This test is still valid, it covers scenario where the same thread tries updating states sequentially, but mismatched version.

2023-11-01 17:00 UTC, conalsmith-r3 commented on libs/state-manager/state-manager-db-impl/src/integrationTest/kotlin/net/corda/libs/statemanager/impl/tests/StateManagerIntegrationTest.kt
> -            assertThat(failedUpdates).containsValues(
JUnit test assertions must be in the main thread, so failures here were being missed (although the assertions was wrong to begin with)

2023-11-02 11:54 UTC, conalsmith-r3 commented on libs/state-manager/state-manager-db-impl/src/integrationTest/kotlin/net/corda/libs/statemanager/impl/tests/TestHelper.kt
> +fun divideStatesBetweenThreads(
`windowed` didn't quite fit here, had to write my own function so the last group had element from the first.

2023-11-06 16:56 UTC, jujoramos commented on libs/state-manager/state-manager-db-impl/src/integrationTest/kotlin/net/corda/libs/statemanager/impl/tests/StateManagerIntegrationTest.kt
> +            .withFailMessage("Expected one failure for every state shared between another thread")
Would it be possible to somehow get the list of actual failed keys vs expected failed keys here?, otherwise the assertion itself won't be much useful when diagnosing issues.

2023-11-06 16:56 UTC, jujoramos commented on libs/state-manager/state-manager-db-impl/src/integrationTest/kotlin/net/corda/libs/statemanager/impl/tests/StateManagerIntegrationTest.kt
> +    }
Do need this test at all?.

2023-11-06 16:56 UTC, jujoramos commented on libs/state-manager/state-manager-db-impl/src/integrationTest/kotlin/net/corda/libs/statemanager/impl/tests/StateManagerIntegrationTest.kt
> +    fun `optimistic locking ensures no double updates across threads`() {
Worth adding the same tests for the delete operation?.

2023-11-10 12:13 UTC, conalsmith-r3 commented on libs/state-manager/state-manager-db-impl/src/integrationTest/kotlin/net/corda/libs/statemanager/impl/tests/StateManagerIntegrationTest.kt
> +    fun `optimistic locking ensures no double updates across threads`() {
We can't really make an assertion in the delete case, because we don't receive back the entities that failed to delete. 

That's because our delete query is `DELETE FROM $STATE_MANAGER_TABLE s WHERE s.$KEY_COLUMN = ? AND s.$VERSION_COLUMN = ?` - maybe it would be better to return the keys that were deleted.

2023-11-10 12:14 UTC, sprintengine commented on libs/state-manager/state-manager-db-impl/src/integrationTest/kotlin/net/corda/libs/statemanager/impl/tests/StateManagerIntegrationTest.kt
> +    }
I'll convert this to be multi-threaded

2023-11-10 12:22 UTC, jujoramos commented on libs/state-manager/state-manager-db-impl/src/integrationTest/kotlin/net/corda/libs/statemanager/impl/tests/StateManagerIntegrationTest.kt
> +    }
I was asking whether we need a test to check that delete is idempotent, actually; is it needed?.

2023-11-10 12:24 UTC, jujoramos commented on libs/state-manager/state-manager-db-impl/src/integrationTest/kotlin/net/corda/libs/statemanager/impl/tests/StateManagerIntegrationTest.kt
> +    fun `optimistic locking ensures no double updates across threads`() {
The delete operation returns the list of states that failed to be deleted due to optimistic locking so yeah, I'd say is worth having a "concurrent" test for it as well.

2023-11-10 12:27 UTC, conalsmith-r3 commented on libs/state-manager/state-manager-db-impl/src/integrationTest/kotlin/net/corda/libs/statemanager/impl/tests/StateManagerIntegrationTest.kt
> +    fun `optimistic locking ensures no double updates across threads`() {
Ah I was wrong, I forgot we query to get the failed deletes! Yeah definitely worth having this test so

2023-11-10 18:06 UTC, conalsmith-r3 commented on libs/state-manager/state-manager-db-impl/src/integrationTest/kotlin/net/corda/libs/statemanager/impl/tests/StateManagerIntegrationTest.kt
> +    fun `optimistic locking ensures no double updates across threads`() {
If an update fails because the state was already deleted, we do not return this as a "failed update", which is most likely a bug IMO.

We ought to return something to indicate an update failed because the state was deleted, i.e. the State "nullable" in the response map.

```
fun update(states: Collection<State>): Map<String, State?>
```

2023-11-10 18:29 UTC, conalsmith-r3 commented on libs/state-manager/state-manager-db-impl/src/integrationTest/kotlin/net/corda/libs/statemanager/impl/tests/StateManagerIntegrationTest.kt
> +    }
I've removed this one

2023-11-10 18:30 UTC, conalsmith-r3 commented on libs/state-manager/state-manager-db-impl/src/integrationTest/kotlin/net/corda/libs/statemanager/impl/tests/StateManagerIntegrationTest.kt
> +            .withFailMessage("Expected one failure for every state shared between another thread")
done

2023-11-10 18:45 UTC, conalsmith-r3 commented on libs/state-manager/state-manager-api/src/main/kotlin/net/corda/libs/statemanager/api/StateManager.kt
> +    fun update(states: Collection<State>): Map<String, State?>
This allows caller to know if an update failed because a state was already deleted.

@jujoramos let me know if it was intentional to hide this from the caller, I suspect there's no reason why we shouldn't let the caller know a state was attempted to be updated but it was deleted.

2023-11-10 19:05 UTC, conalsmith-r3 commented on libs/messaging/messaging-impl/src/main/kotlin/net/corda/messaging/mediator/MultiSourceEventMediatorImpl.kt
> +                failedToUpdateStateDoesNotExist.forEach { asynchronousOutputs.remove(it) }
@JamesHR3 let me know what you think here, AFAIK if the state manager tries to update a State but the checkpoint didn't exist, we should be able to ignore it, and remove any async outputs for that state.

2023-11-14 12:24 UTC, jujoramos commented on libs/messaging/messaging-impl/src/main/kotlin/net/corda/messaging/mediator/MultiSourceEventMediatorImpl.kt
> +                failedToUpdateStateDoesNotExist.forEach { asynchronousOutputs.remove(it) }
I don't think these changes belong to this `PR`, they should be tackled in another ticket.

2023-11-14 12:24 UTC, jujoramos commented on libs/state-manager/state-manager-api/src/main/kotlin/net/corda/libs/statemanager/api/StateManager.kt
> +    fun update(states: Collection<State>): Map<String, State?>
I don't think these changes belong to this PR, they should be tackled in another ticket.

2023-11-14 12:26 UTC, jujoramos commented on libs/state-manager/state-manager-db-impl/src/main/kotlin/net/corda/libs/statemanager/impl/StateManagerImpl.kt
> +
I don't think these changes belong to this PR, they should be tackled in another ticket.

2023-11-14 12:31 UTC, jujoramos commented on libs/state-manager/state-manager-db-impl/src/test/kotlin/net/corda/libs/statemanager/impl/StateManagerImplTest.kt
> +
I don't think these changes belong to this PR, they should be tackled in another ticket.

2023-11-14 13:04 UTC, jujoramos requested changes
Tests look good, but the part related to the behavioural changes shouldn't be part of this `PR`; we need a different ticket for it.

2023-11-14 13:04 UTC, jujoramos commented on libs/state-manager/state-manager-db-impl/src/integrationTest/kotlin/net/corda/libs/statemanager/impl/tests/StateManagerIntegrationTest.kt
> +            }
Can we assert that the entire state is the expected one and not just the version?.

2023-11-16 09:14 UTC, jujoramos approved these changes, later dismissed

2023-11-16 09:14 UTC, jujoramos commented on testing/db-testkit/src/main/kotlin/net/corda/db/testkit/DbUtils.kt
> +    @JvmOverloads
Do we need this extra annotation here?, are we invoking the `DbUtils` utility methods from Java anywhere?.

2023-11-16 09:14 UTC, jujoramos commented on testing/db-testkit/src/main/kotlin/net/corda/db/testkit/DbUtils.kt
> +        maxJdbcConnections: Int = 5
Nitpick: maybe call it maximumPoolSize for consistency?.

2023-11-16 09:14 UTC, jujoramos commented on libs/state-manager/state-manager-db-impl/src/integrationTest/kotlin/net/corda/libs/statemanager/impl/tests/MultiThreadedTestHelper.kt
> +        val statesOverlappingNextGroup: List<State>
Nitpick: `overlappingStates`.

2023-11-16 09:48 UTC, jujoramos approved these changes, later dismissed

2023-11-16 10:46 UTC, jujoramos approved these changes

2023-11-16 15:25 UTC, merged