CORE-12165: restore nested kafka topics
corda/corda-runtime-os pull request #5134
Opened 2023-11-20 14:28 UTC by dickon

2023-11-20 17:06 UTC, anien requested changes
First comments. I still need to review few other files.

2023-11-20 17:06 UTC, anien commented on processors/crypto-processor/src/main/kotlin/net/corda/processors/crypto/internal/CryptoProcessorImpl.kt
> +import java.util.*
Will this pass detekt?

2023-11-20 17:06 UTC, anien commented on processors/crypto-processor/src/main/kotlin/net/corda/processors/crypto/internal/CryptoProcessorImpl.kt
> +        val publisherConfig = PublisherConfig(UUID.randomUUID().toString(), false)
`val publisherConfig = PublisherConfig("CryptoProcessor", false)` or `val publisherConfig = PublisherConfig("RekeyBusProcessor", false)` might be better as it identifies the source of the record.

2023-11-20 21:17 UTC, anien commented on components/crypto/crypto-service-impl/src/main/kotlin/net/corda/crypto/service/impl/bus/CryptoRekeyBusProcessor.kt
> +                            wrappingKeyInfo . alias,
Remove spaces around dot ->`wrappingKeyInfo.alias`

2023-11-20 21:17 UTC, anien commented on components/crypto/crypto-service-impl/src/test/kotlin/net/corda/crypto/service/impl/bus/CryptoRekeyBusProcessorTests.kt
>      }
I think we can merge `do a mocked key rotation` and `key rotation re-wraps all the keys if limit is not specified` tests together. I don't think there is any value having it separately. Also, we might explain the number 2/4 here
`assertThat(rewrapPublishCapture.firstValue).hasSize(4)` as it is not obvious it contains the cluster db value.

2023-11-20 22:16 UTC, dickon commented on components/crypto/crypto-service-impl/src/main/kotlin/net/corda/crypto/service/impl/bus/CryptoRekeyBusProcessor.kt
> +                            wrappingKeyInfo . alias,
Okay. I don't really know what that arg does.

2023-11-20 22:19 UTC, dickon commented on components/crypto/crypto-service-impl/src/test/kotlin/net/corda/crypto/service/impl/bus/CryptoRekeyBusProcessorTests.kt
>      }
okay

2023-11-20 22:19 UTC, dickon commented on processors/crypto-processor/src/main/kotlin/net/corda/processors/crypto/internal/CryptoProcessorImpl.kt
> +        val publisherConfig = PublisherConfig(UUID.randomUUID().toString(), false)
done

2023-11-20 22:26 UTC, dickon commented on processors/crypto-processor/src/main/kotlin/net/corda/processors/crypto/internal/CryptoProcessorImpl.kt
> +import java.util.*
yes but we still don't need to do it so undoing. This would have been just IntelliJ automation.

2023-11-20 22:37 UTC, dickon commented on components/crypto/crypto-service-impl/src/main/kotlin/net/corda/crypto/service/impl/bus/CryptoRekeyBusProcessor.kt
> +                            wrappingKeyInfo . alias,
fixed

2023-11-20 23:16 UTC, anien commented on processors/crypto-processor/src/main/kotlin/net/corda/processors/crypto/internal/CryptoProcessorImpl.kt
> +        val rekeyPublisher =  publisherFactory.createPublisher(publisherConfig, messagingConfig)
Would be nice to fix the formatting.
```kotlin
        val publisherConfig = PublisherConfig("RekeyBusProcessor", false)
        val rekeyPublisher = publisherFactory.createPublisher(publisherConfig, messagingConfig)
```

2023-11-20 23:16 UTC, anien commented on gradle.properties
> +# Change to 5.1.0.xx-SNAPSHOT to pick up maven local published copy
Not sure we want this change.

2023-11-21 08:18 UTC, dickon commented on gradle.properties
> +# Change to 5.1.0.xx-SNAPSHOT to pick up maven local published copy
fixed.

2023-11-21 08:23 UTC, dickon commented on gradle.properties
> +# Change to 5.1.0.xx-SNAPSHOT to pick up maven local published copy
yes, merge/rebase error, fixed.

2023-11-21 08:59 UTC, anien approved these changes
LGTM!

2023-11-21 09:14 UTC, merged