CORE-18457: Remove entity persistence duplication
corda/corda-runtime-os pull request #5176
Opened 2023-11-27 15:01 UTC by emilybowe

Ticket _CORE-17819: PersistenceWorker - Remove Kafka Implementation, Review Missing Tests and Duplications_ includes removal of ledger persistence and entity persistence duplication.

This PR addresses subtask **CORE-18457: Remove entity persistence duplication**

This will include an api change to remove unused entity persistence topic: **//TODO**

2023-11-28 07:01 UTC, LWogan reviewed
I don't see anything untoward here. The JIRA title has "review missing tests" in it. Are you happy there are no missing tests?

2023-11-28 09:11 UTC, emilybowe commented
> I don't see anything untoward here. The JIRA title has "review missing tests" in it. Are you happy there are no missing tests?

Yes I think so. I think we've discussed it in brief ITO and Miljenko dropped a note in our team slack on the review for missing tests on his opinion that I think makes sense. Also most tests that were there before were switched over to use the new processor and just ones that are no longer used (specific kafka ones) were deleted. 👍

2023-11-28 09:37 UTC, LWogan submitted a review, later dismissed
Looks good to me.

2023-11-28 09:54 UTC, thiagoviana approved these changes, later dismissed

2023-11-28 11:41 UTC, simon-johnson-r3 requested changes

2023-11-28 11:41 UTC, simon-johnson-r3 commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/application/persistence/external/events/AbstractPersistenceExternalEventFactory.kt
> -            topic = Schemas.Persistence.PERSISTENCE_ENTITY_PROCESSOR_TOPIC,
The latest version of `ExternalEventRecord` allows topic to be null but the docs in that file have not been update to reflect what the consequence of this is (they have been updated for the `key` field null). Is it possible to add that as part of this PR?

I assume topic can be null if you aren't intending to use Kafka? But as the user of this class needs to know whether that's true or not, I'm not sure reusing the same class just to transfer payload (just 1 out of 3 things) is the best idea.

2023-11-28 11:41 UTC, simon-johnson-r3 commented on components/persistence/entity-processor-service-impl/src/main/kotlin/net/corda/entityprocessor/impl/internal/EntityRequestProcessor.kt
> +    override val requestClass: Class<EntityRequest>,
Would it be more usual to provide types as class parameters?

2023-11-28 11:41 UTC, simon-johnson-r3 commented on components/persistence/entity-processor-service/src/main/kotlin/net/corda/entityprocessor/EntityRequestSubscriptionFactory.kt
> -    fun create(config: SmartConfig): Subscription<String, EntityRequest>
You need to remove the comment above this. Also I think the header comment for the interface is now out of date?

2023-11-28 13:25 UTC, emilybowe commented on components/persistence/entity-processor-service-impl/src/main/kotlin/net/corda/entityprocessor/impl/internal/EntityRequestProcessor.kt
> +    override val requestClass: Class<EntityRequest>,
I checked with @JamesHR3 and you're right on this. I'll change this one in this PR and then raise a separate PR to fix the other workers.

2023-11-28 15:21 UTC, emilybowe commented on components/persistence/entity-processor-service-impl/src/main/kotlin/net/corda/entityprocessor/impl/internal/EntityRequestProcessor.kt
> +    override val requestClass: Class<EntityRequest>,
I've raised CORE-18579

2023-11-28 15:38 UTC, emilybowe commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/application/persistence/external/events/AbstractPersistenceExternalEventFactory.kt
> -            topic = Schemas.Persistence.PERSISTENCE_ENTITY_PROCESSOR_TOPIC,
I've updated the kdocs here, and I've raised CORE-18580

2023-11-28 15:38 UTC, emilybowe commented on components/persistence/entity-processor-service/src/main/kotlin/net/corda/entityprocessor/EntityRequestSubscriptionFactory.kt
> -    fun create(config: SmartConfig): Subscription<String, EntityRequest>
I've updated these kdocs

2023-11-28 15:48 UTC, simon-johnson-r3 submitted a review, later dismissed

2023-11-29 10:57 UTC, LWogan approved these changes
LGTM

2023-11-29 11:12 UTC, simon-johnson-r3 approved these changes

2023-11-29 11:17 UTC, merged