CORE-18504: set up state manager for crypto, and populate from REST worker
corda/corda-runtime-os pull request #5185
Opened 2023-11-30 09:38 UTC by dickon

- Adds support for state manager in rest and crypto workers
- Adds JDBC driver for rest worker to allow access to state manager

2023-11-30 15:54 UTC, vkolomeyko submitted a review, later dismissed
LGTM (on behalf @corda/rest)

2023-11-30 16:14 UTC, anien reviewed
First pass of the PR, I will need to do another one.

2023-11-30 16:14 UTC, anien commented on processors/member-processor/src/integrationTest/kotlin/net/corda/processor/member/MemberProcessorTestUtils.kt
> +
Is this test related to our changes or was it missed in previous PRs?

2023-11-30 16:14 UTC, anien commented on charts/corda/values.schema.json
> +                                "stateManager"
I think this most of the yaml changes need to be reviewed by @jujoramos.
Specifically here we add `stateManager` in required field for the rest worker, but we don't do the same for crypto worker and I don't understand all the implications of it.

2023-11-30 16:14 UTC, anien commented on charts/corda/values.yaml
> +          value: "rest_state_manager_user"
I would create a ticket for now to make sure we restrict the usage of this particular state manager db to only rest and crypto worker. Currently, it seems the default configuration is that it's shared between all workers that can use state manager.

2023-11-30 16:14 UTC, anien commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/response/KeyRotationStatusResponse.kt
> + */
We might need to update Kdocs. But I think this will change further, so maybe a ticket for now that we need to review kdocs and parameters for this file?

2023-11-30 16:14 UTC, anien commented on components/crypto/crypto-rest/src/test/kotlin/net/corda/crypto/rest/impl/KeyRotationRestResourceTest.kt
> +    private lateinit var publishToKafka: Publisher
I would rename this to `kafkaPublisher`.

2023-11-30 16:14 UTC, anien commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/impl/KeyRotationRestResourceImpl.kt
> +    private var publishToKafka: Publisher? = null
rename to `kafkaPublisher`?

2023-11-30 16:14 UTC, anien commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/impl/KeyRotationRestResourceImpl.kt
> +        logger.info("KeyRotationRestResource starting.")
I would either have this as a debug or removed completely.

2023-11-30 16:14 UTC, anien commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/impl/KeyRotationRestResourceImpl.kt
> +        logger.info("KeyRotationRestResource stopping.")
Same as above.

2023-11-30 16:28 UTC, dickon commented on processors/member-processor/src/integrationTest/kotlin/net/corda/processor/member/MemberProcessorTestUtils.kt
> +
This is now required since the crypto procesor waits for the STATE_MANAGER_CONFIG to arrive before it starts, so never starts in this test case, so the member processor integration test never gets past the lifecycle startup sequence and timeout.

Basically we have to touch everywhere which bootstraps crypto processor, and that includes the OSGi tests of things that consume the crypto procesosr, which include the memeber processor.

2023-11-30 16:31 UTC, dickon commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/impl/KeyRotationRestResourceImpl.kt
> +    private var publishToKafka: Publisher? = null
Not keen. `kafkaPublisher` suggests we are publishign the whole of Kafka.

2023-11-30 16:31 UTC, dickon commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/impl/KeyRotationRestResourceImpl.kt
> +        logger.info("KeyRotationRestResource starting.")
done

2023-11-30 16:31 UTC, dickon commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/impl/KeyRotationRestResourceImpl.kt
> +        logger.info("KeyRotationRestResource stopping.")
done

2023-11-30 16:32 UTC, dickon commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/response/KeyRotationStatusResponse.kt
> + */
I pulled this out in to another branch

2023-12-01 12:37 UTC, yift-r3 submitted a review, later dismissed
LGTM (network only)

2023-12-01 13:14 UTC, conalsmith-r3 commented on charts/corda/values.schema.json
> +                                "stateManager"
What does Crypto worker do if it does not receive a stateManager configuration? If SM is now a required piece of config for the crypto worker, we should reflect it in the schema

2023-12-01 13:14 UTC, conalsmith-r3 commented on charts/corda/values.yaml
> +          value: "rest_state_manager_user"
I have a design for a closely related ticket in progress: https://r3-cev.atlassian.net/browse/CORE-16416

2023-12-01 13:14 UTC, sprintengine commented on charts/corda/values.yaml
> +        name: crypto_state_manager
The intent is to share the one state manager between crypto and rest, right?

This causes the default behavior to point at a different one, this should match the one configured in rest worker.

(And you could probably name it something related to the type of state it holds.)

2023-12-01 13:17 UTC, conalsmith-r3 commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/impl/KeyRotationRestResourceImpl.kt
> +        val entries = stateManager!!.get(listOf(requestId))
should you check this isn't null first?

2023-12-01 13:43 UTC, conalsmith-r3 commented on charts/corda/values.yaml
> +          value: "rest_state_manager_user"
Probably the easiest way to restrict the usage is via permissions and credentials. 

Our auto-bootstrapping process uses the root/admin Postgres credentials from the `bootstrap.stateManager.crypto` config, and grants permissions to the user configured at `workers.crypto.stateManager.db.username`.

So as long as the boot config for crypto and rest both have the same pg instance's admin creds, if the credentials at `workers.crypto.stateManager.db.username` and `workers.rest.stateManager.db.username` are different, the boot process should configure both these users to have access.

2023-12-04 09:56 UTC, dickon commented on charts/corda/values.yaml
> +        name: crypto_state_manager
State manager is used to store the progress on key rotation, both at request level and individual rewrap work item. We've got more code under development which actually does that, but for now I wanted to get it in.

So, without state manager, the crypto processor can work and even do key rotation, but the operator will get no information about key rotation progress.

2023-12-04 10:45 UTC, conalsmith-r3 commented on charts/corda/values.yaml
> +        name: crypto_state_manager
I thought the intent was to share one StateManager instance between REST and crypto workers, no? e.g

![image](https://github.com/corda/corda-runtime-os/assets/68279385/076ded20-a6a5-4572-b4f2-55d9442c221c)

2023-12-04 11:10 UTC, anien commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/impl/KeyRotationRestResourceImpl.kt
> +    private var publishToKafka: Publisher? = null
Now it sounds more like a function name, not a property name.

2023-12-04 11:42 UTC, davidcurrie reviewed
I've only looked at the charts side of things but I concur with the other comments. If this is the REST worker accessing the crypto worker's DB then the DB details should only be defined on the crypto worker side with the REST worker just having different credentials (and it should be clear in the way those credentials are supplied that they are for accessing the crypto worker's DB, not any potential future state manager that the REST worker might have of its own).

2023-12-04 13:22 UTC, anien commented
> I've only looked at the charts side of things but I concur with the other comments. If this is the REST worker accessing the crypto worker's DB then the DB details should only be defined on the crypto worker side with the REST worker just having different credentials (and it should be clear in the way those credentials are supplied that they are for accessing the crypto worker's DB, not any potential future state manager that the REST worker might have of its own).

I have created a ticket for this https://r3-cev.atlassian.net/browse/CORE-18642

2023-12-04 13:26 UTC, anien commented on charts/corda/values.yaml
> +        name: crypto_state_manager
Correct, we want to share one StateManager instance between the REST and CRYPTO worker. But we want both rest and crypto worker to be able to read and write.

2023-12-04 13:33 UTC, anien commented on charts/corda/values.yaml
> +          value: "rest_state_manager_user"
I have created a ticket for this, so we can work on it separately: https://r3-cev.atlassian.net/browse/CORE-18642

2023-12-04 13:36 UTC, anien commented on charts/corda/values.schema.json
> +                                "stateManager"
Changed. State manager is now required for the crypto worker as well. We do need to use it in the key rotation, so I believe it's the best approach to mark it as required.

2023-12-04 13:37 UTC, anien commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/impl/KeyRotationRestResourceImpl.kt
> +    private var publishToKafka: Publisher? = null
I might leave it to another PR for now.

2023-12-04 13:56 UTC, jujoramos commented on charts/corda/values.yaml
> +        name: crypto_state_manager
@anien : I believe @conalsmith-r3 's concern is still in place, even if https://r3-cev.atlassian.net/browse/CORE-16416 is implemented. As things stand right now, the `crypto-worker` will use `crypto_state_manager` database and `rest-worker` will use `rest_state_manager`, so they won't be sharing anything.

2023-12-04 14:34 UTC, jujoramos commented on charts/corda/values.yaml
> +        # flow mapper worker JDBC connection pool configuration for State Manager DB
```suggestion
        # rest worker JDBC connection pool configuration for State Manager DB
```

2023-12-04 14:34 UTC, jujoramos commented on charts/corda/values.yaml
> +          # -- flow mapper worker maximum JDBC connection pool size for state manager DB
```suggestion
          # -- rest worker maximum JDBC connection pool size for state manager DB
```

2023-12-04 14:34 UTC, jujoramos commented on charts/corda/values.yaml
> +          # -- flow mapper worker minimum JDBC connection pool size for state manager DB; null value means pool's min size will default to pool's max size value
```suggestion
          # -- rest worker minimum JDBC connection pool size for state manager DB; null value means pool's min size will default to pool's max size value
```

2023-12-04 14:34 UTC, jujoramos commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/impl/KeyRotationRestResourceImpl.kt
> +                logger.info("State manager config is $stateManagerConfig")
Won't this leak credentials into the log?.

2023-12-04 14:34 UTC, jujoramos commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/impl/KeyRotationRestResourceImpl.kt
> +                logger.info("State manager created and started $stateManager")
Nitpick: the state manager doesn't have a `toString()` so this will likely show rubbish in the logs. you might want to log the `name` instead (or nothing at all).

2023-12-04 14:34 UTC, jujoramos commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/impl/KeyRotationRestResourceImpl.kt
> +private const val UPLOAD_TOPIC = REKEY_MESSAGE_TOPIC
Nitpick: do you need this const?, why don't just use `REKEY_MESSAGE_TOPIC`?.

2023-12-04 14:34 UTC, jujoramos commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/impl/KeyRotationRestResourceImpl.kt
> +    val requestId = UUID.randomUUID().toString()
Can we inject the `clientRequestId` or something set by the user here?, when the time comes, that will make troubleshooting easier 😅.

2023-12-04 14:34 UTC, jujoramos commented on processors/crypto-processor/src/main/kotlin/net/corda/processors/crypto/internal/CryptoProcessorImpl.kt
> +                logger.info("state manager config is $stateManagerConfig")
Similar as my other comments: I don't think these log messages under `INFO` level will be useful as they stand right now, and they might leak connection credentials as well.

2023-12-04 17:05 UTC, anien commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/impl/KeyRotationRestResourceImpl.kt
> +private const val UPLOAD_TOPIC = REKEY_MESSAGE_TOPIC
No real need for the const. Using topic name directly now.

2023-12-04 17:06 UTC, anien commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/impl/KeyRotationRestResourceImpl.kt
> +    val requestId = UUID.randomUUID().toString()
Possibly we can. Let's discuss with others.

2023-12-04 17:06 UTC, anien commented on processors/crypto-processor/src/main/kotlin/net/corda/processors/crypto/internal/CryptoProcessorImpl.kt
> +                logger.info("state manager config is $stateManagerConfig")
Removed.

2023-12-04 17:07 UTC, anien commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/impl/KeyRotationRestResourceImpl.kt
> +                logger.info("State manager created and started $stateManager")
I change the log message to debug and use `.name` even though the name is mainly just random, but in case of some debugging it might be useful.

2023-12-04 17:29 UTC, anien commented on charts/corda/values.yaml
> +        name: crypto_state_manager
Ah, got your point now.

2023-12-04 17:45 UTC, anien commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/impl/KeyRotationRestResourceImpl.kt
> +                logger.info("State manager config is $stateManagerConfig")
It doesn't show any details as it's currently implemented. But I also removed it now.

2023-12-04 17:53 UTC, anien commented on charts/corda/values.yaml
> +        name: crypto_state_manager
Done.

2023-12-05 11:22 UTC, anien commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/impl/KeyRotationRestResourceImpl.kt
> +    val requestId = UUID.randomUUID().toString()
From the offline conversation it was decided we keep the current work as is, but will add feature ticket to our backlog.

2023-12-05 14:03 UTC, anien commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/impl/KeyRotationRestResourceImpl.kt
> +                logger.info("State manager created and started $stateManager")
Hm, `.name` is breaking few tests. I have removed it and keeping for now just the string.

2023-12-05 15:34 UTC, anien commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/impl/KeyRotationRestResourceImpl.kt
> +        val entries = stateManager!!.get(listOf(requestId))
Done. PTAL.

2023-12-05 16:21 UTC, vkolomeyko commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/KeyRotationRestResource.kt
> +    ): List<Pair<String, String>>
Hm... status of rotation as a list of pairs... IMO this is way to generic/open to interpretation.
Can we not create a better `data class` which will represent the status of rotation better?

2023-12-06 08:06 UTC, anien commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/KeyRotationRestResource.kt
> +    ): List<Pair<String, String>>
I already have this changed to a data class in the follow up PR.

2023-12-06 10:32 UTC, josephzunigadaly commented on applications/workers/release/rest-worker/build.gradle
> +    dockerImageJdbc "org.postgresql:postgresql:$postgresDriverVersion"
Is this needed in the rest worker?

2023-12-06 11:13 UTC, anien commented on applications/workers/release/rest-worker/build.gradle
> +    dockerImageJdbc "org.postgresql:postgresql:$postgresDriverVersion"
Because we need db access from the rest worker to state manager db. It was now decided that we would only need read access, so I am going to check if in this case we still need this.

2023-12-06 12:54 UTC, anien commented on applications/workers/release/rest-worker/build.gradle
> +    dockerImageJdbc "org.postgresql:postgresql:$postgresDriverVersion"
@josephzunigadaly yes, we still need this.

2023-12-06 13:28 UTC, josephzunigadaly commented on applications/workers/release/rest-worker/build.gradle
> +    dockerImageJdbc "org.postgresql:postgresql:$postgresDriverVersion"
Thank you Anna. I wasn't expecting that to be the answer. I think I'm not the right person to review this. I'd need more information on the design being implemented.

2023-12-07 09:43 UTC, sprintengine commented on applications/workers/release/rest-worker/build.gradle
> +    dockerImageJdbc "org.postgresql:postgresql:$postgresDriverVersion"
Yes State Manager needs a JDBC driver to interact with the state storage for now as the back-end is a postgres db.

2023-12-07 09:46 UTC, vkolomeyko submitted a review, later dismissed
LGTM

2023-12-07 10:22 UTC, sprintengine commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/impl/KeyRotationRestResourceImpl.kt
> +        val sM = tryWithExceptionHandling(logger, "retrieve key rotation status") {
this check on stateManager has the wrong operation name.

Probably better off just wrapping both checks in one go, you can use !! after this block

```
tryWithExceptionHandling(logger, "start key rotation") {
    checkNotNull(publishToKafka)
    checkNotNull(stateManager)
}
```

If you're coming back to this code and can address it as a follow up, I'm happy to approve this PR.

2023-12-07 10:24 UTC, simon-johnson-r3 requested changes

2023-12-07 10:24 UTC, simon-johnson-r3 commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/impl/KeyRotationRestResourceImpl.kt
> +        val pTK = tryWithExceptionHandling(logger, "start key rotation") {
I'm not sure what's going on here. The purpose of `checkNotNull` is to throw `IllegalStateException` where you don't expect that to be the case but want to write defensive code. Here it's wrapped with `tryWithExceptionHandling` which implies you are trying to catch some exceptions, but that method doesn't really deal with `IllegalStateException` and even if it did, why would you explicitly throw that just to immediately suppress it?

I would also try to remove the use of these short variable names.

2023-12-07 10:24 UTC, simon-johnson-r3 commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/impl/KeyRotationRestResourceImpl.kt
> +    checkNotNull(serialized)
checkNotNull is designed to be used like a wrapper:
```
val serialized = checkNotNull(serializeStatus(status))
```

The fact you have to do this at all is actually a problem with the `CordaAvroSerializer` interface IMHO, it actually throws on error and shouldn't then return a nullable. But that's not for this PR...

2023-12-07 10:24 UTC, simon-johnson-r3 commented on components/crypto/crypto-service-impl/src/main/kotlin/net/corda/crypto/service/impl/bus/CryptoRekeyBusProcessor.kt
> +                require(flattend!=null)
`require` is for arguments to this function only (it throws `IllegalArgumentException`) here you should wrap this in `checkNotNull`, see comment above.

2023-12-07 10:24 UTC, simon-johnson-r3 commented on components/crypto/crypto-service-impl/src/main/kotlin/net/corda/crypto/service/impl/bus/CryptoRekeyBusProcessor.kt
> +                    i+1,
`i + 1`

2023-12-07 10:24 UTC, simon-johnson-r3 commented on components/crypto/crypto-service-impl/src/main/kotlin/net/corda/crypto/service/impl/bus/CryptoRekeyBusProcessor.kt
> +                    Instant.ofEpochMilli(timestamp), // TODO get creation timestamp rather than this hack
we shouldn't add comments like this, either the code should work or it shouldn't be submitted, I would remove it and add a JIRA ticket referencing where it is in the code and why it needs to change at a later date

2023-12-07 10:24 UTC, simon-johnson-r3 commented on components/crypto/crypto-service-impl/src/main/kotlin/net/corda/crypto/service/impl/bus/CryptoRekeyBusProcessor.kt
> +                val generationNumber = 0 // TODO find out the correct generation number
we shouldn't add comments like this, either the code should work or it shouldn't be submitted, I would remove it and add a JIRA ticket referencing where it is in the code and why it needs to change at a later date

2023-12-07 10:24 UTC, simon-johnson-r3 commented on processors/crypto-processor/src/main/kotlin/net/corda/processors/crypto/internal/CryptoProcessorImpl.kt
> +                val bootConfig = bootConfigRecord ?: throw IllegalStateException("Boot config not available.")
val bootConfig = checkNotNull(bootConfigRecord) { "Boot config not available." }

2023-12-07 10:24 UTC, simon-johnson-r3 commented on processors/crypto-processor/src/main/kotlin/net/corda/processors/crypto/internal/CryptoProcessorImpl.kt
> +                val stateManagerConfig: SmartConfig? = if (bootConfig.hasPath(StateManagerConfig.STATE_MANAGER))
This is a long-winded way of writing:
```
if (bootConfig.hasPath(StateManagerConfig.STATE_MANAGER)) {
    val stateManagerConfig = bootConfig.getConfig(StateManagerConfig.STATE_MANAGER)
    stateManager = stateManagerFactory.create(stateManagerConfig).also {
        it.start()
    }
}
```

2023-12-07 10:24 UTC, simon-johnson-r3 commented on processors/crypto-processor/src/main/kotlin/net/corda/processors/crypto/internal/CryptoProcessorImpl.kt
> +                logger.debug("State manager created and started.")
This isn't true in all cases. Should we throw here if it wasn't started? I assume the crypto worker isn't operable at this point. It would also be due to bad parameters so the whole cluster is unlikely to ever recover from this state.

We should definitely not log this here though, it could be misleading.

2023-12-07 10:24 UTC, simon-johnson-r3 commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/impl/KeyRotationRestResourceImpl.kt
> +        val newPublisher =
The use of `newPublisher` is unnecessary with this implementation. If you are perhaps expecting something to throw before setting `publishToKafka` to the new value, then you should set `publishToKafka` to `null` after the close.

2023-12-07 10:24 UTC, simon-johnson-r3 commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/impl/KeyRotationRestResourceImpl.kt
> +        val sM = tryWithExceptionHandling(logger, "retrieve key rotation status") {
See comment in next function.

2023-12-07 10:41 UTC, conalsmith-r3 commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/impl/KeyRotationRestResourceImpl.kt
> +        val pTK = tryWithExceptionHandling(logger, "start key rotation") {
+1 I agree there's a couple things not quite right here.

It does deal with `IllegalStateException` implicitly in that it'll convert it to a `InternalServerException`, which is also arguably not correct, `ServiceUnavailableException` could be a better exception to throw there. But yes, a better approach might be to just check if these required fields are null, and if so, throw the exception, rather than wrapping a check with another wrapper. 

```
fun validateDependencies() {
  if (state manager == null || publishToKafka == null) throw ServiceUnavailableException
}
```

2023-12-07 10:47 UTC, anien commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/impl/KeyRotationRestResourceImpl.kt
> +        val pTK = tryWithExceptionHandling(logger, "start key rotation") {
We want to return `HttpApiException` so it can return HTTP code as this is on the rest worker. `IllegalStateException` is not `HttpApiException`. `tryWithExceptionHandling` throws `InternalServerException` if it doesn't match any other previous exceptions, which in our case it doesn't. `InternalServerException` was recommended by @vkolomeyko.

2023-12-07 10:49 UTC, conalsmith-r3 commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/impl/KeyRotationRestResourceImpl.kt
> +        val pTK = tryWithExceptionHandling(logger, "start key rotation") {
Just thinking aloud, throwing IntenralServerException is probably OK. `ServiceUnavailableException` makes sense when something calls the crypto worker REST endpoints when they aren't "up" (or lifecycle coordinator isn't up) - I'm not sure we do that check I'd need to look at the javalin handler. So for this PR, when the component is UP but a dependency is null, something has went wrong, InternalServerException is probably appropriate.

2023-12-07 13:28 UTC, anien commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/impl/KeyRotationRestResourceImpl.kt
> +        val sM = tryWithExceptionHandling(logger, "retrieve key rotation status") {
Ah yes, that was copy paste error. I've changed it according your recommendation.

2023-12-07 13:28 UTC, anien commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/impl/KeyRotationRestResourceImpl.kt
> +    checkNotNull(serialized)
Changed.

2023-12-07 13:29 UTC, anien commented on components/crypto/crypto-service-impl/src/main/kotlin/net/corda/crypto/service/impl/bus/CryptoRekeyBusProcessor.kt
> +                require(flattend!=null)
Done. And thanks for clarification.

2023-12-07 13:29 UTC, anien commented on components/crypto/crypto-service-impl/src/main/kotlin/net/corda/crypto/service/impl/bus/CryptoRekeyBusProcessor.kt
> +                    i+1,
Done.

2023-12-07 13:30 UTC, anien commented on components/crypto/crypto-service-impl/src/main/kotlin/net/corda/crypto/service/impl/bus/CryptoRekeyBusProcessor.kt
> +                    Instant.ofEpochMilli(timestamp), // TODO get creation timestamp rather than this hack
The comment is actually wrong. It's the right thing to do as now we provide the timestamp when we create the record.

2023-12-07 13:30 UTC, anien commented on components/crypto/crypto-service-impl/src/main/kotlin/net/corda/crypto/service/impl/bus/CryptoRekeyBusProcessor.kt
> +                val generationNumber = 0 // TODO find out the correct generation number
This is a leftover from the previous change. We won't know the generation number at this time. So I have updated the comment.

2023-12-07 13:30 UTC, anien commented on processors/crypto-processor/src/main/kotlin/net/corda/processors/crypto/internal/CryptoProcessorImpl.kt
> +                val bootConfig = bootConfigRecord ?: throw IllegalStateException("Boot config not available.")
Updated.

2023-12-07 13:30 UTC, anien commented on processors/crypto-processor/src/main/kotlin/net/corda/processors/crypto/internal/CryptoProcessorImpl.kt
> +                val stateManagerConfig: SmartConfig? = if (bootConfig.hasPath(StateManagerConfig.STATE_MANAGER))
Updated.

2023-12-07 13:31 UTC, anien commented on processors/crypto-processor/src/main/kotlin/net/corda/processors/crypto/internal/CryptoProcessorImpl.kt
> +                logger.debug("State manager created and started.")
I added a check and removed the log.

2023-12-07 13:31 UTC, anien commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/impl/KeyRotationRestResourceImpl.kt
> +        val newPublisher =
I have removed the use of the `newPublisher`

2023-12-07 13:31 UTC, anien commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/impl/KeyRotationRestResourceImpl.kt
> +        val sM = tryWithExceptionHandling(logger, "retrieve key rotation status") {
Hope I have addressed this.

2023-12-08 09:32 UTC, conalsmith-r3 commented on components/crypto/crypto-rest/build.gradle
> +    runtimeOnly project(':libs:state-manager:state-manager-db-impl')
state manager implementation runtime dependency should just be at the processor level, e.g. [crypto processor](https://github.com/corda/corda-runtime-os/pull/5185/files#diff-0acc5ebb3e3fa40455c3dc052674ff60d272653a540b8dac8c3d8fcea4f27413), so I think you should be able to remove this

2023-12-11 13:12 UTC, anien commented on processors/crypto-processor/src/main/kotlin/net/corda/processors/crypto/internal/CryptoProcessorImpl.kt
> +                logger.debug("State manager created and started.")
I had to removed the check because of failing OSGi tests. Log is removed.

2023-12-11 15:17 UTC, anien commented on components/crypto/crypto-rest/build.gradle
> +    runtimeOnly project(':libs:state-manager:state-manager-db-impl')
runtimeOnly dependency is now moved to rest processor module.

2023-12-11 16:41 UTC, simon-johnson-r3 approved these changes, later dismissed

2023-12-11 17:03 UTC, conalsmith-r3 approved these changes, later dismissed

2023-12-12 08:27 UTC, ronanbrowne approved these changes, later dismissed
LGTM

2023-12-12 11:38 UTC, ronanbrowne approved these changes

2023-12-12 11:40 UTC, conalsmith-r3 approved these changes

2023-12-12 11:41 UTC, conalsmith-r3 approved these changes
lgtm

2023-12-12 11:59 UTC, vkolomeyko approved these changes
LGTM

2023-12-12 12:12 UTC, yift-r3 approved these changes
Network changes LGTM

2023-12-12 13:07 UTC, simon-johnson-r3 approved these changes

2023-12-12 13:16 UTC, merged