CORE-18501: Check flowStartOperationalStatus after flow checkpoint is initialized
corda/corda-runtime-os pull request #5241
Opened 2023-12-11 18:41 UTC by Tom-Fitzpatrick

This is intended to fix the underlying issue causing the e2e test "maintenance mode stops flows" to be flakey. https://r3-cev.atlassian.net/browse/CORE-18501

When this fails, it does so with the error: `Caused by: org.apache.avro.AvroTypeException: value null is not a FlowInitiatorType at FlowStatus.initiatorType`. This prevents the FlowStatus from being published to Kafka and so the flow never gets a KILLED status and is instead stuck in START_REQUESTED.

To fix this, this moves checking the flowStartOperationalStatus in StartFlowEventHandler to instead be checked in virtualNodeFlowOperationalChecks, after the flow checkpoint has been made. 

This means we don't have to create a FlowStatus without a checkpoint, which should remove the case where one was being made without a FlowInitiatorType.

2023-12-12 12:04 UTC, vkolomeyko commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/factory/impl/FlowMessageFactoryImpl.kt
> +            log.warn("Creating FlowStatus with null initiatorType")
Do we want to add more context to this warning logged from `FlowCheckpoint` ? So that we will be able to trace back how come that `initiatorType` is `null`.

2023-12-12 12:25 UTC, LWogan requested changes
Feedback given on slack. I think we can avoid a lot of the extra handling for no checkpoints by allowing the start flow handler to initialize the checkpoint and then we do the operational checks as part of the operational checks step in the flow pipeline

2023-12-12 15:51 UTC, Tom-Fitzpatrick commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/factory/impl/FlowMessageFactoryImpl.kt
> +            log.warn("Creating FlowStatus with null initiatorType")
More context would be better alright, but for now I've actually removed this log as we're hopefully fixing this issue with a different approach, detailed in the PR description.

2023-12-12 15:59 UTC, vkolomeyko commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/handlers/events/StartFlowEventHandler.kt
> -        val holdingIdentity = context.inputEventPayload.startContext.identity.toCorda()
Looks like we now have unused imports:
```
components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/handlers/events/StartFlowEventHandler.kt:7:1: The import 'net.corda.flow.pipeline.exceptions.FlowMarkedForKillException' is unused. [UnusedImports]	
components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/handlers/events/StartFlowEventHandler.kt:9:1: The import 'net.corda.virtualnode.OperationalStatus' is unused. [UnusedImports]	
components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/handlers/events/StartFlowEventHandler.kt:10:1: The import 'net.corda.virtualnode.read.VirtualNodeInfoReadService' is unused. [UnusedImports]	
components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/impl/FlowEventExceptionProcessorImpl.kt:3:1: The import 'net.corda.data.flow.FlowInitiatorType' is unused. [UnusedImports]	
components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/impl/FlowEventExceptionProcessorImpl.kt:4:1: The import 'net.corda.data.flow.event.StartFlow' is unused. [UnusedImports]	
components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/impl/FlowEventExceptionProcessorImpl.kt:5:1: The import 'net.corda.data.flow.output.FlowStates' is unused. [UnusedImports]	
components/flow/flow-service/src/test/kotlin/net/corda/flow/pipeline/handlers/events/StartFlowEventHandlerTest.kt:13:1: The import 'net.corda.virtualnode.read.VirtualNodeInfoReadService' is unused. [UnusedImports]
```

2023-12-12 16:13 UTC, Tom-Fitzpatrick commented on components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/handlers/events/StartFlowEventHandler.kt
> -        val holdingIdentity = context.inputEventPayload.startContext.identity.toCorda()
Got it, thanks :)

2023-12-12 16:20 UTC, LWogan approved these changes, later dismissed
LGTM. Be sure to run the e2e tests against the helm chart built for this pr. I think you already said you did on slack but just double check.

2023-12-13 09:53 UTC, Tom-Fitzpatrick commented
I ran the e2e tests locally as well as [here](https://ci02.dev.r3.com/job/Corda5/view/Full%20Health%205.2/job/corda5-e2e-tests/job/release%252F5.2/205/testReport/) and the ones relevant to this PR were all green.

2023-12-13 09:55 UTC, vkolomeyko approved these changes
LGTM

2023-12-13 09:56 UTC, LWogan approved these changes
LGTM

2023-12-13 09:59 UTC, merged