DA5-22: Distribution and validation of draft transactions
corda/corda-runtime-os pull request #5295
Opened 2023-12-18 10:33 UTC by julia-filipczak

2023-12-19 13:37 UTC, vlajos reviewed
A description of the PR would be useful.
Also cross-linking the API/runtime-os PRs makes reviewing easier.

2023-12-19 13:37 UTC, vlajos commented on components/ledger/ledger-utxo-flow/src/main/kotlin/net/corda/ledger/utxo/flow/impl/flows/transactiontransmission/ReceiveLedgerTransactionFlow.kt
> +        private val log: Logger = LoggerFactory.getLogger(ReceiveLedgerTransactionFlow::class.java)
Using `this::class.java` makes it a bit more future-proof. (If the flow gets renamed, it will follow automatically+shorter.)

2023-12-19 13:37 UTC, vlajos commented on components/ledger/ledger-utxo-flow/src/main/kotlin/net/corda/ledger/utxo/flow/impl/flows/transactiontransmission/SendAsLedgerTransactionFlow.kt
> +    private companion object { val log = LoggerFactory.getLogger(this::class.java) }
I think we usually have a few more line breaks in similar patterns.

2023-12-19 13:37 UTC, vlajos commented on components/ledger/ledger-utxo-flow/src/test/kotlin/net/corda/ledger/utxo/flow/impl/flows/transactiontransmission/ReceiveLedgerTransactionFlowTest.kt
> +    private val testState = TestState(listOf(publicKeyAlice))
I suspect these were needed in the example for the verification.
Are these needed here?

2023-12-19 13:37 UTC, vlajos commented on components/ledger/ledger-utxo-flow/src/test/kotlin/net/corda/ledger/utxo/flow/impl/flows/transactiontransmission/SendAsLedgerTransactionFlowTest.kt
> +        verify(flowEngine, never()).subFlow(TransactionBackchainSenderFlow(TX_ID, sessionAlice))
This (and the above) verify(ies) check only Alice.
I think adding Bob as well, would make it a bit more symmetric.

2023-12-21 10:58 UTC, vlajos requested changes

2023-12-21 10:58 UTC, vlajos commented on components/ledger/ledger-utxo-flow/src/test/kotlin/net/corda/ledger/utxo/flow/impl/flows/transactiontransmission/ReceiveLedgerTransactionFlowTest.kt
> +    private val publicKeyBob = mock<PublicKey>().also { whenever(it.encoded).thenReturn(byteArrayOf(0x02)) }
Are these two used somewhere?

2023-12-21 10:58 UTC, vlajos commented on components/ledger/ledger-utxo-flow/src/test/kotlin/net/corda/ledger/utxo/flow/impl/flows/transactiontransmission/ReceiveLedgerTransactionFlowTest.kt
> +    class TestState(private val participants: List<PublicKey>) : ContractState {
And this?

2023-12-21 10:58 UTC, vlajos commented on components/ledger/ledger-utxo-flow/src/test/kotlin/net/corda/ledger/utxo/flow/impl/flows/transactiontransmission/SendAsLedgerTransactionFlowTest.kt
> +    fun `sending unverified transaction should throw exception`() {
I think
```suggestion
    fun `exceptions get propagated back from receiver`() {
```
would be a bit more correct.
(Sending unverified transactions is OK with these new functions.)

2023-12-21 10:58 UTC, vlajos commented on components/ledger/ledger-utxo-flow/src/test/kotlin/net/corda/ledger/utxo/flow/impl/flows/transactiontransmission/ReceiveLedgerTransactionFlowTest.kt
> +    fun `receiving transaction with dependencies should call backchain resolution flow`() {
Can you add a test to cover the no dependencies case as well?

2024-01-08 11:10 UTC, vlajos approved these changes, later dismissed

2024-01-08 11:56 UTC, blsemo submitted a review, later dismissed
LGTM

2024-01-08 14:53 UTC, vlajos approved these changes, later dismissed

2024-01-08 15:23 UTC, vlajos approved these changes

2024-01-08 15:52 UTC, merged