ENT-1764/Log4j json timestamp edited
corda/corda-runtime-os pull request #5414
Opened 2024-01-10 18:44 UTC by mag1c-48

The log4j json format timestamp previously was in seconds since Epoch

Which is not human readable, this has been altered and converted into UTC format.

2024-01-11 15:30 UTC, davidcurrie requested changes

2024-01-11 15:30 UTC, davidcurrie commented on charts/corda/log4j2.xml
> +                        "format": "yyyy-MM-dd HH:mm:ss.SSS",
This should be in the ISO 8601 format that you had originally i.e. `yyyy-MM-dd'T'HH:mm:ss.SSS'Z'`

2024-01-11 15:30 UTC, davidcurrie commented on charts/corda/log4j2.xml
> +            <PatternLayout pattern="%d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5level %logger{36} %X - %msg%n"/>
I believe this should give you the equivalent of what we have in the JSON layout but it needs testing:
```suggestion
            <PatternLayout pattern="%d{ISO8601}{UTC} [%t] %-5level %logger{36} %X - %msg%n"/>
```

2024-01-11 17:19 UTC, davidcurrie commented on charts/corda/log4j2.xml
> +            <PatternLayout pattern="%d{ISO8601}{UTC} [%t] %-5level %logger{36} %X - %msg%n"/>
Sorry to mess you around, but looking at the output from the build, I realise that ISO8601 differs from RFC3339 in the preference for a comma rather than a period (although both are supported) and that it also does not require the timezone specifier. Can we use the following to be consistent across the JSON and text formats?
```suggestion
            <PatternLayout pattern="%d{yyyy-MM-dd'T'HH:mm:ss.SSS'Z'}{UTC} [%t] %-5level %logger{36} %X - %msg%n"/>
```

2024-01-12 10:11 UTC, davidcurrie approved these changes, later dismissed
LGTM

2024-01-12 10:19 UTC, mcgovc submitted a review, later dismissed
LGTM

2024-01-12 10:30 UTC, ronanbrowne approved these changes
LGMT

2024-01-12 10:56 UTC, merged