CORE-19262: Added support for unmananged key rotation status get api
corda/corda-runtime-os pull request #5437
Opened 2024-01-15 12:22 UTC by akankshaSharmaR3

2024-01-15 13:54 UTC, anien requested changes

2024-01-15 13:54 UTC, anien commented on testing/e2e-test-utilities/src/main/kotlin/net/corda/e2etest/utilities/ClusterUtils.kt
> +        condition { it.code == ResponseCode.ACCEPTED.statusCode }
This is not returning ACCEPTED code, but OK status code. Or some exception.

2024-01-15 13:57 UTC, akankshaSharmaR3 commented on testing/e2e-test-utilities/src/main/kotlin/net/corda/e2etest/utilities/ClusterUtils.kt
> +        condition { it.code == ResponseCode.ACCEPTED.statusCode }
Changed it to 'OK'.

2024-01-15 15:07 UTC, anien approved these changes, later dismissed
LGTM

2024-01-16 08:41 UTC, simon-johnson-r3 requested changes

2024-01-16 08:41 UTC, simon-johnson-r3 commented on testing/e2e-test-utilities/src/main/kotlin/net/corda/e2etest/utilities/ClusterUtils.kt
> +fun ClusterInfo.cryptoUnmanagedWrappingKeysRotationStatus(
The name of this function is a bit confusing. As far as I can tell it waits for an OK status or fails after timeout?

In that case it would be better named something like `waitForCryptoUnmanagedWrappingKeysRotation`

2024-01-16 08:43 UTC, akankshaSharmaR3 commented on testing/e2e-test-utilities/src/main/kotlin/net/corda/e2etest/utilities/ClusterUtils.kt
> +fun ClusterInfo.cryptoUnmanagedWrappingKeysRotationStatus(
Changed method name as suggested

2024-01-16 13:32 UTC, anien commented on testing/e2e-test-utilities/src/main/kotlin/net/corda/e2etest/utilities/ClusterUtils.kt
> +fun ClusterInfo.cryptoUnmanagedWrappingKeysRotationStatus(
I don't think that's completely correct now. We don't wait for key rotation, but for the key rotation status. Other functions use the same `assertWithRetry` but I don't really think the retry will happen much in this case and any other function has the wait in the name. To keep consistency, I would be keen on keeping the original name of the function.

2024-01-16 15:47 UTC, anien commented on testing/e2e-test-utilities/src/main/kotlin/net/corda/e2etest/utilities/ClusterUtils.kt
> +fun ClusterInfo.cryptoUnmanagedWrappingKeysRotationStatus(
@simon-johnson-r3  WDYT?

2024-01-17 08:13 UTC, akankshaSharmaR3 commented on testing/e2e-test-utilities/src/main/kotlin/net/corda/e2etest/utilities/ClusterUtils.kt
> +fun ClusterInfo.cryptoUnmanagedWrappingKeysRotationStatus(
Changed name to "getStatusForUnmanagedWrappingKeysRotation"

2024-01-17 09:50 UTC, anien commented on testing/e2e-test-utilities/src/main/kotlin/net/corda/e2etest/utilities/ClusterBuilder.kt
> +    fun getWrappingKeysProtocolVersion(): SimpleResponse {
Are we testing this? If yes, I am happy to leave it. Just not sure if we test it in other APIs.

2024-01-17 09:50 UTC, anien commented on testing/e2e-test-utilities/src/main/kotlin/net/corda/e2etest/utilities/ClusterBuilder.kt
> +            "/api/$REST_API_VERSION_PATH//wrappingkey/getprotocolversion",
```suggestion
            "/api/$REST_API_VERSION_PATH/wrappingkey/getprotocolversion",
```

2024-01-17 09:53 UTC, akankshaSharmaR3 commented on testing/e2e-test-utilities/src/main/kotlin/net/corda/e2etest/utilities/ClusterBuilder.kt
> +            "/api/$REST_API_VERSION_PATH//wrappingkey/getprotocolversion",
Updated

2024-01-17 09:53 UTC, anien commented on testing/e2e-test-utilities/src/main/kotlin/net/corda/e2etest/utilities/ClusterUtils.kt
> +fun ClusterInfo.getProtocolVersionForWrappingKeys(
I would suggest the name to be something like `getProtocolVersionForUnmanagedKeyRotation`, because the whole section in swagger/API is called Key Rotation (Which might change once we add managed key rotation).

2024-01-17 09:56 UTC, akankshaSharmaR3 commented on testing/e2e-test-utilities/src/main/kotlin/net/corda/e2etest/utilities/ClusterUtils.kt
> +fun ClusterInfo.getProtocolVersionForWrappingKeys(
Done

2024-01-17 09:57 UTC, simon-johnson-r3 commented on testing/e2e-test-utilities/src/main/kotlin/net/corda/e2etest/utilities/ClusterUtils.kt
> +fun ClusterInfo.cryptoUnmanagedWrappingKeysRotationStatus(
I guess the confusing part here is the use of the word "status". We are waiting for the http _status_ to be OK. But then we return the _status_ of key rotation which is something different entirely, contained within the contents of the OK response.

But anyway, I think the name is clearer now.

2024-01-17 09:58 UTC, simon-johnson-r3 submitted a review, later dismissed

2024-01-17 10:22 UTC, anien approved these changes, later dismissed

2024-01-17 11:41 UTC, anien approved these changes

2024-01-17 11:46 UTC, merged