CORE-18930: make transaction ID deterministic
corda/corda-runtime-os pull request #5443
Opened 2024-01-15 17:51 UTC by emilybowe

The privacy salt currently gets a unique ID for transactions that is random. We need it to be unique but also deterministic. The random aspect will be replaced with a concatenation of FlowID+suspendCount which are obtained from the checkpoint. To get this data, FlowFiberService will be used. A service will be created that uses FlowFiberService to give our privacy salt, so this can be injected in several places. Testing should show that transactions with the same flowID and suspendCount give the same ID (deterministic) even if created multiple times.

2024-01-17 15:55 UTC, LWogan reviewed
Looks good, few comments

2024-01-17 15:55 UTC, LWogan commented on components/ledger/ledger-common-flow-api/src/main/kotlin/net/corda/ledger/common/flow/transaction/PrivacySaltProviderService.kt
> +     * Returns a privacy salt
We should expand this kdoc to describe that it creates a deterministic unique salt based on a flows information.

2024-01-17 15:55 UTC, LWogan commented on components/ledger/ledger-common-flow/src/main/kotlin/net/corda/ledger/common/flow/impl/transaction/PrivacySaltProviderServiceImpl.kt
> +        val input = (flowID + suspendCount).repeat(10)
Ah i see there's a minimum size requirement for the salt. I think UUIDs length should meet the constraint though

2024-01-17 15:55 UTC, LWogan commented on libs/ledger/ledger-common-data/src/test/kotlin/net/corda/ledger/common/data/transaction/factory/WireTransactionFactoryImplTest.kt
> +    fun `draft`() {
guessing this is just some code for your local test purposes? leaving a comment to remind you to remove.

2024-01-17 15:55 UTC, LWogan commented on libs/ledger/ledger-common-data/src/test/kotlin/net/corda/ledger/common/data/transaction/factory/WireTransactionFactoryImplTest.kt
> +    fun `transaction ids are deterministic`() {
lets add a test which generates different salts for different flow ids too

2024-01-17 18:09 UTC, vlajos commented
Can two privacy salts be requested while`FlowID+suspendCount` is the same?
Although probably it is not a real problem if that is not possible, since `toSignedTransaction()`s, where the privacy salt gets assigned, suspend anyway. (at least for the signing operation IIRC.)

2024-01-18 10:58 UTC, emilybowe commented
> Details

@vlajos I've checked with @LWogan and we would say no, for the reason you mention (because toSignTransaction will always suspend) and as long as we're always signing after creating transactions the suspendCount will increment.

2024-01-18 14:50 UTC, vkolomeyko submitted a review, later dismissed
LGTM
(on behalf of @corda/rest)

2024-01-19 10:44 UTC, LWogan reviewed
Looks good. One test cleanup comment

2024-01-19 10:44 UTC, LWogan commented on testing/ledger/ledger-common-base-test/src/main/kotlin/net/corda/ledger/common/test/CommonLedgerTest.kt
> +    val privacySaltProviderService = PrivacySaltProviderServiceImpl(flowFiberService)
Its not ideal to have to update a bunch of tests with the same mocks to get flowid and suspend count to work.  

You could make privacySaltProviderService a mock and have it return a salt. Then  you could remove the setups from the additional tests .

e.g
`val privacySaltProviderService = mock<PrivacySaltProviderService>().apply {
        whenever(generatePrivacySalt()).thenReturn(PrivacySaltImpl("someBytes".toByteArray()))
    }`

i didn't test the above, but something like that should work.  I see theres a few other mocks in that class such as mockSigningService() so it should be fine to do the same.

2024-01-19 12:30 UTC, LWogan reviewed
One more thing! Almost there.

2024-01-19 12:30 UTC, LWogan commented on libs/ledger/ledger-common-data/src/test/kotlin/net/corda/ledger/common/data/transaction/factory/WireTransactionFactoryImplTest.kt
> +    fun setupPrivacySaltProviderService() {
Sorry I missed this on my first pass but the tests to check that the PrivacySaltProviderService makes deterministic/unqiue ids based on flowid and suspend count should be in PrivacySaltProviderServiceImpTest.

This WireTransactionFactoryImplTest.kt should just be using a mocked PrivacySaltProviderService.

his WireTransactionFactoryImplTest was testing the PrivacySaltProviderServiceImpl.

privacySaltProviderService should be removed from CommonLedgerTest. We only want to use mockPrivacySaltProviderService there

2024-01-19 14:55 UTC, LWogan approved these changes, later dismissed
LGTM

2024-01-19 15:20 UTC, blsemo requested changes
I don't think that approach is good. enough.
We need an iron clad guarantee that two distinct transactions have different ids, even if they're created in the same flow and have the same content.
And even if we always supend in the current implementation, this opens up an alley for surprising bugs in the future.

2024-01-19 15:44 UTC, blsemo commented on components/ledger/ledger-consensual-flow/src/main/kotlin/net/corda/ledger/consensual/flow/impl/transaction/factory/ConsensualSignedTransactionFactoryImpl.kt
> +        consensualTransactionBuilder: ConsensualTransactionBuilder,
Why was a trailing comma added here?

2024-01-19 15:44 UTC, blsemo commented on libs/ledger/ledger-common-data/src/main/kotlin/net/corda/ledger/common/data/transaction/factory/WireTransactionFactory.kt
>       *
The comment on this method is now wrong!

2024-01-19 15:44 UTC, blsemo commented on libs/ledger/ledger-common-data/src/main/kotlin/net/corda/ledger/common/data/transaction/factory/WireTransactionFactoryImpl.kt
> -            "Number of component groups in metadata structure description does not match with the real number!"
You removed this check on creating a new transaction.
Remember that the other function was only present to recreate  wire TX from the database, so has less stringent checks than one  exposed to a user facing API.

2024-01-19 15:44 UTC, blsemo commented on testing/ledger/ledger-common-base-test/src/main/kotlin/net/corda/ledger/common/test/CommonLedgerTest.kt
> +        whenever(generatePrivacySalt()).thenReturn(PrivacySaltImpl("someBytes".repeat(10).toByteArray())) }
Does this mean that all transactions in all tests using this CommonTests as base will have the same privacy salt?

2024-01-24 12:31 UTC, LWogan commented on libs/ledger/ledger-common-data/src/main/kotlin/net/corda/ledger/common/data/transaction/factory/WireTransactionFactory.kt
>       *
Why is this wrong?

2024-01-24 12:37 UTC, emilybowe reviewed
changes look good @LWogan ! 👍

2024-01-24 12:40 UTC, LWogan commented on libs/ledger/ledger-common-data/src/main/kotlin/net/corda/ledger/common/data/transaction/factory/WireTransactionFactoryImpl.kt
> -            "Number of component groups in metadata structure description does not match with the real number!"
Whats the best recourse here? Do we need to keep an explicit create NEW transaction function or is it ok to just keep the check in the create function with the signature of :
override fun create(
        componentGroupLists: List<List<ByteArray>>,
        privacySalt: PrivacySalt
    )

2024-01-24 12:41 UTC, LWogan commented on testing/ledger/ledger-common-base-test/src/main/kotlin/net/corda/ledger/common/test/CommonLedgerTest.kt
> +        whenever(generatePrivacySalt()).thenReturn(PrivacySaltImpl("someBytes".repeat(10).toByteArray())) }
I've updated it to return random bytes now each time its called

2024-01-24 16:19 UTC, LWogan commented on libs/ledger/ledger-common-data/src/main/kotlin/net/corda/ledger/common/data/transaction/factory/WireTransactionFactoryImpl.kt
> -            "Number of component groups in metadata structure description does not match with the real number!"
Is there any negatived to having the check present for transactions loaded from the db. If the transaction had to pass the check to be created, does it change after that?
Would it only require updating some ledger tests to provide more realistic data. I put it in and saw a few ledger tests fail as a result.

2024-01-24 22:11 UTC, LWogan commented on libs/ledger/ledger-common-data/src/main/kotlin/net/corda/ledger/common/data/transaction/factory/WireTransactionFactoryImpl.kt
> -            "Number of component groups in metadata structure description does not match with the real number!"
I spoke to @lankydan and @vlajos. Neither were aware of any reason why we couldn't have this check in the transaction. I've adjusted  a handful of tests to supply the correct number of groups.

It does leave an open question why this code existed. So far noone knows why. Perhaps legacy code to simplify tests?

```
val completeComponentGroupLists = (0 until metadata.getNumberOfComponentGroups()).map { index ->
            componentGroupLists.getOrElse(index) { arrayListOf() }
        }

2024-01-25 10:47 UTC, blsemo approved these changes
I think that should do it.

2024-01-25 10:54 UTC, LWogan approved these changes

2024-01-25 11:40 UTC, vkolomeyko approved these changes

2024-01-25 13:27 UTC, merged