CORE-13499: Implement key rotation status
corda/corda-runtime-os pull request #5446
Opened 2024-01-16 16:42 UTC by anien

**Changes**:
* store key rotation status in RekeyBusProcessor when we first get the key rotation request
* update key rotation status after each rewrap, update overall status if we rotated all keys in the current tenantId
* show user the resulting status of the key rotation (In Progress or Done) if the rotation ever started
* add check if the previous key rotation is in progress
* show user the timestamp of the last key rotation status, as the last key rotation might have happened long time ago

2024-01-16 16:45 UTC, dickon commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/impl/KeyRotationRestResourceImpl.kt
> +        logger.debug("State manager created and started ${stateManager!!.name}")
nit: `stateManager?.name` is better here.

2024-01-17 10:57 UTC, simon-johnson-r3 commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/impl/KeyRotationRestResourceImpl.kt
> +        logger.debug("State manager created and started ${stateManager!!.name}")
surprised it's even needed, stateManager couldn't be null here

2024-01-17 11:56 UTC, simon-johnson-r3 requested changes

2024-01-17 11:56 UTC, simon-johnson-r3 commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/impl/KeyRotationRestResourceImpl.kt
> +        val entries = stateManager!!.findByMetadataMatchingAll(
the convention is `stateManager!!` -> `checkNotNull(stateManager)` because it gives a better error message

2024-01-17 11:56 UTC, simon-johnson-r3 commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/impl/KeyRotationRestResourceImpl.kt
> +
there are a lot of strings used in here, should they be defined somewhere?

2024-01-17 11:56 UTC, simon-johnson-r3 commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/impl/KeyRotationRestResourceImpl.kt
> +            val keyRotationStatus = deserializer.deserialize(state.value)!!
I think we need better handling of the null here, that's a platform error as I understand it and we should log this and make the end user aware something very bad has gone wrong

2024-01-17 11:56 UTC, simon-johnson-r3 commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/impl/KeyRotationRestResourceImpl.kt
> +        stateManager!!.findByMetadataMatchingAll(
checkNotNull

2024-01-17 11:56 UTC, simon-johnson-r3 commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/impl/KeyRotationRestResourceImpl.kt
> +            // if we find one In Progress status, we know we are not done
minor: the comment doesn't match the logic, which is the other way round (i.e. it doesn't check for an `In Progress` state). I think you can actually just remove the comment as the code is quite clear.

2024-01-17 11:56 UTC, simon-johnson-r3 commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/impl/KeyRotationRestResourceImpl.kt
> +            if (state.modifiedTime.isAfter(lastUpdatedTimestamp)) lastUpdatedTimestamp = state.modifiedTime
I'm not sure about this line. Firstly I doubt `state.modifiedTime` would ever pre-date the beginning of 1970, and secondly no matter what `state.modifiedTime` was, I don't think here we should potentially try and change it.

I think passing `state.modifiedTime` directly into `KeyRotationStatusResponse` is fine?

2024-01-17 11:56 UTC, simon-johnson-r3 commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/impl/KeyRotationRestResourceImpl.kt
> +            if (state.metadata["status"] != "Done") rotationStatus = "In Progress"
the mapping between internal states and external states isn't really clear to me, do we need to do any translation? what internal state are we worried about propagating to the end user?

2024-01-17 11:56 UTC, simon-johnson-r3 commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/response/KeyRotationStatusResponse.kt
> + * @param total Total number of wrapping keys to be rotated for particular tenantId.
I don't think you meant `to be rotated` here. It's just the total number of wrapping keys for a particular `tenantId` I believe (i.e. in effect this number is unrelated to key rotation)?

2024-01-17 11:56 UTC, simon-johnson-r3 commented on components/crypto/crypto-service-impl/src/main/kotlin/net/corda/crypto/service/impl/bus/CryptoRekeyBusProcessor.kt
> +            stateManager!!.create(records)
checkNotNull

2024-01-17 11:56 UTC, simon-johnson-r3 commented on components/crypto/crypto-service-impl/src/main/kotlin/net/corda/crypto/service/impl/bus/CryptoRekeyBusProcessor.kt
> +                        serializer.serialize(status)!!,
checkNotNull

2024-01-17 11:56 UTC, simon-johnson-r3 commented on components/crypto/crypto-service-impl/src/main/kotlin/net/corda/crypto/service/impl/bus/CryptoRekeyBusProcessor.kt
> +            targetWrappingKeys.groupBy { it.first }.forEach {
the use of `it` on line 97 isn't that obvious, I assume it's tenantId, would be possible to add `{ tenantId ->` etc. here?

2024-01-17 11:56 UTC, simon-johnson-r3 commented on components/crypto/crypto-service-impl/src/main/kotlin/net/corda/crypto/service/impl/bus/CryptoRekeyBusProcessor.kt
> +        stateManager!!.findByMetadataMatchingAll(
checkNotNull

2024-01-17 11:56 UTC, simon-johnson-r3 commented on components/crypto/crypto-service-impl/src/main/kotlin/net/corda/crypto/service/impl/bus/CryptoRekeyBusProcessor.kt
> +        val toDelete = stateManager!!.findByMetadataMatchingAll(
checkNotNull

2024-01-17 11:56 UTC, simon-johnson-r3 commented on components/crypto/crypto-service-impl/src/main/kotlin/net/corda/crypto/service/impl/bus/CryptoRekeyBusProcessor.kt
> +        // TODO should we throw the exception?
They have failed delete because they have been updated since you fetched them above. The pattern here should be to repeat this process until it stops failing. I would suggest having some reasonable retry count, and only after then should you throw. If we cannot delete these states I'd suggest we shouldn't be trying to rotate, not least because we rely on the states to block duplicate attempts.

2024-01-17 11:56 UTC, simon-johnson-r3 commented on components/crypto/crypto-service-impl/src/main/kotlin/net/corda/crypto/service/impl/bus/CryptoRekeyBusProcessor.kt
> +                        request.oldParentKeyAlias + it.key + "keyRotation",  // rootKeyAlias + tenantId + keyRotation
Instead of the comment, perhaps we should have a helper function to generate the key called from both places?

2024-01-17 11:56 UTC, simon-johnson-r3 commented on components/crypto/crypto-service-impl/src/main/kotlin/net/corda/crypto/service/impl/bus/CryptoRewrapBusProcessor.kt
> +                    stateManager!!.get(listOf(request.oldParentKeyAlias + request.tenantId + "keyRotation"))
checkNotNull

2024-01-17 11:56 UTC, simon-johnson-r3 commented on components/crypto/crypto-service-impl/src/main/kotlin/net/corda/crypto/service/impl/bus/CryptoRewrapBusProcessor.kt
> +                        Thread.sleep(Random.nextLong(0, 1000))
Hmm, not sure about this...

2024-01-17 11:56 UTC, simon-johnson-r3 commented on gradle.properties
>  reflectAsmVersion = 1.11.9
is this some sort of merge issue?

2024-01-17 15:52 UTC, anien commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/impl/KeyRotationRestResourceImpl.kt
> +        val entries = stateManager!!.findByMetadataMatchingAll(
2 lines above this I have `checkNotNull(stateManager)`, it's part of  the `tryWithExceptionHandling`, but it still forces me to check on stateManager being not null.

2024-01-17 16:13 UTC, anien commented on gradle.properties
>  reflectAsmVersion = 1.11.9
It is.

2024-01-18 08:47 UTC, anien commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/impl/KeyRotationRestResourceImpl.kt
> +            if (state.modifiedTime.isAfter(lastUpdatedTimestamp)) lastUpdatedTimestamp = state.modifiedTime
This was meant to get the latest modified time between all records in state manager as they are grouped by tenantId. So if one tenant Id was updated later than the other, with this, we would get that latest modified time.
Also, users might then compare when the rotation started (if they made the note of the start time) with when the last rotation has finished.

2024-01-18 14:03 UTC, anien commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/impl/KeyRotationRestResourceImpl.kt
> +            if (state.metadata["status"] != "Done") rotationStatus = "In Progress"
I just thought that this gives us flexibility on how we are showing data to the user. And we can change it easily anytime.
If we use avro schema for returning it to the user, we would be tied to it and it would be harder to change. Also, current avro schema doesn't contain all the information we store in the metadata that we show to the user.

2024-01-18 14:05 UTC, anien commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/response/KeyRotationStatusResponse.kt
> + * @param total Total number of wrapping keys to be rotated for particular tenantId.
No, it does return the total number of keys that will be rotated for the tenant. Because tenant can have multiple wrapping keys, but not all of them must be wrapped by the current root wrapping key.

2024-01-18 14:12 UTC, anien commented on gradle.properties
>  reflectAsmVersion = 1.11.9
Hm, there doesn't seem to be a change, so not sure why github picked it up.

2024-01-18 14:12 UTC, anien commented
@simon-johnson-r3 I have addressed most of your comments, few more to go. PTAL.

2024-01-18 14:13 UTC, anien commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/impl/KeyRotationRestResourceImpl.kt
> +        logger.debug("State manager created and started ${stateManager!!.name}")
I have added private val for state manager checking if state manager is null. `!!` is gone.

2024-01-18 14:14 UTC, anien commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/impl/KeyRotationRestResourceImpl.kt
> +        val entries = stateManager!!.findByMetadataMatchingAll(
Sorted.

2024-01-18 14:15 UTC, anien commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/impl/KeyRotationRestResourceImpl.kt
> +
I have created an objects with string values (I can't use `enum` in some places because `State's` `Metadata` doesn't support `enum`.

2024-01-18 14:15 UTC, anien commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/impl/KeyRotationRestResourceImpl.kt
> +            val keyRotationStatus = deserializer.deserialize(state.value)!!
I did `checkNotNull` here.

2024-01-18 14:15 UTC, anien commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/impl/KeyRotationRestResourceImpl.kt
> +        stateManager!!.findByMetadataMatchingAll(
Sorted.

2024-01-18 14:15 UTC, anien commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/impl/KeyRotationRestResourceImpl.kt
> +            // if we find one In Progress status, we know we are not done
Comment removed.

2024-01-18 14:16 UTC, anien commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/impl/KeyRotationRestResourceImpl.kt
> +            if (state.modifiedTime.isAfter(lastUpdatedTimestamp)) lastUpdatedTimestamp = state.modifiedTime
I have added comment too.

2024-01-18 14:16 UTC, anien commented on components/crypto/crypto-service-impl/src/main/kotlin/net/corda/crypto/service/impl/bus/CryptoRekeyBusProcessor.kt
> +            stateManager!!.create(records)
Done.

2024-01-18 14:18 UTC, anien commented on components/crypto/crypto-service-impl/src/main/kotlin/net/corda/crypto/service/impl/bus/CryptoRekeyBusProcessor.kt
> +            targetWrappingKeys.groupBy { it.first }.forEach {
I named lambda parameters.

2024-01-18 14:18 UTC, anien commented on components/crypto/crypto-service-impl/src/main/kotlin/net/corda/crypto/service/impl/bus/CryptoRekeyBusProcessor.kt
> +        stateManager!!.findByMetadataMatchingAll(
Done.

2024-01-18 14:18 UTC, anien commented on components/crypto/crypto-service-impl/src/main/kotlin/net/corda/crypto/service/impl/bus/CryptoRekeyBusProcessor.kt
> +        val toDelete = stateManager!!.findByMetadataMatchingAll(
Done.

2024-01-18 14:19 UTC, anien commented on components/crypto/crypto-service-impl/src/main/kotlin/net/corda/crypto/service/impl/bus/CryptoRekeyBusProcessor.kt
> +                        request.oldParentKeyAlias + it.key + "keyRotation",  // rootKeyAlias + tenantId + keyRotation
I have created a helper function.

2024-01-18 14:28 UTC, anien commented on components/crypto/crypto-service-impl/src/main/kotlin/net/corda/crypto/service/impl/bus/CryptoRewrapBusProcessor.kt
> +                    stateManager!!.get(listOf(request.oldParentKeyAlias + request.tenantId + "keyRotation"))
Done.

2024-01-18 14:29 UTC, anien commented on components/crypto/crypto-service-impl/src/main/kotlin/net/corda/crypto/service/impl/bus/CryptoRekeyBusProcessor.kt
> +                        serializer.serialize(status)!!,
Done.

2024-01-19 09:56 UTC, anien commented on components/crypto/crypto-service-impl/src/main/kotlin/net/corda/crypto/service/impl/bus/CryptoRewrapBusProcessor.kt
> +                        Thread.sleep(Random.nextLong(0, 1000))
I have removed sleep. Elsewhere in the code when retries for state manager are happening, we don't have sleeps either.

2024-01-19 09:56 UTC, anien commented on components/crypto/crypto-service-impl/src/main/kotlin/net/corda/crypto/service/impl/bus/CryptoRekeyBusProcessor.kt
> +        // TODO should we throw the exception?
I added retries. And if we cannot delete records, we won't even start new key rotation.

2024-01-19 09:59 UTC, anien commented on gradle.properties
>  reflectAsmVersion = 1.11.9
Reverted.

2024-01-19 10:44 UTC, simon-johnson-r3 approved these changes

2024-01-19 17:54 UTC, vkolomeyko approved these changes
LGTM from @corda/rest point of view

2024-01-21 23:04 UTC, merged