CORE-18863: Helm Schema Changes 4 State Isolation
corda/corda-runtime-os pull request #5476
Opened 2024-01-22 11:15 UTC by jujoramos

Update json schema changes (Helm only) to support new deployment model
on which state types can be isolated and workers are allowed to access
more than a single State Manager instance.
Changes introduced by this commit are backward compatible with the
existing schema, comments were added so that the relevant code can be
entirely removed once the new deployment model is fully rolled out.

2024-01-22 15:26 UTC, davidcurrie requested changes

2024-01-22 15:26 UTC, davidcurrie commented on charts/corda/values.yaml
> +    # Administrator credentials per database to use when grating required runtime permissions
```suggestion
    # Administrator credentials per database to use when creating required runtime permissions
```

2024-01-22 15:26 UTC, davidcurrie commented on charts/corda/values.schema.json
> +                    "title": "Persistent Storage configuration to be used by the State Manager when dealing with 'keyRotation' states"
```suggestion
                    "title": "Persistent Storage configuration to be used by the State Manager when dealing with 'tokenPoolCache' states"
```

2024-01-22 15:26 UTC, davidcurrie commented on charts/corda/values.schema.json
> +                    "$comment": "TODO-[CORE-19372]: should we replace 'cluster', 'crypto' and 'rbac' by the new 'databases' section instead?.",
Ideally, yes. Is it more or less work to do that under the same ticket?

2024-01-22 15:26 UTC, davidcurrie commented on charts/corda/values.schema.json
> +                                "type": "array",
isn't the type of the items `object`? and do you need this anyway given it's defined in `databaseTemplate`?

2024-01-22 15:26 UTC, davidcurrie commented on charts/corda/values.schema.json
> +                        }
Previously, we've relied on schema validation to force the host to be set. Are you going to check this in the Helm template when the database is used by a state manager?

2024-01-22 15:26 UTC, davidcurrie commented on charts/corda/values.schema.json
> +                        "DATABASE"
The Kubernetes style would be to use Pascal case for enums...

2024-01-22 15:35 UTC, jujoramos commented on charts/corda/values.schema.json
> +                    "$comment": "TODO-[CORE-19372]: should we replace 'cluster', 'crypto' and 'rbac' by the new 'databases' section instead?.",
Certainly a bit more work, and likely a follow up ticket to avoid mixing state manager changes with the new helm deployment schema (list of databases instead of individual ones for `cluster`, `crypro` and `rbac`).

2024-01-22 15:35 UTC, jujoramos commented on charts/corda/values.schema.json
> +                    "title": "Persistent Storage configuration to be used by the State Manager when dealing with 'keyRotation' states"
👍

2024-01-22 15:36 UTC, jujoramos commented on charts/corda/values.yaml
> +    # Administrator credentials per database to use when grating required runtime permissions
👍

2024-01-22 15:36 UTC, jujoramos commented on charts/corda/values.schema.json
> +                                "type": "array",
Good catch 👍

2024-01-22 15:43 UTC, jujoramos commented on charts/corda/values.schema.json
> +                        "DATABASE"
Fair enough, I'll use `Database` (for the new schema only, though, won't update the old one as that might cause issues with existing deployment files and will be deleted shortly enough anyways).

2024-01-22 15:54 UTC, jujoramos commented on charts/corda/values.schema.json
> +                        }
That was the idea, yes, do you see any issues with that approach?.

2024-01-22 15:58 UTC, jujoramos commented on charts/corda/values.schema.json
> +                        }
I gave it a quick try, BTW, and it failed with the following 🤔:
```
 helm lint charts/corda --values values.yaml
==> Linting charts/corda
[INFO] Chart.yaml: icon is recommended
[ERROR] values.yaml: - databases.0.host: Does not match format 'hostname'
- databases.0: Must validate all the schemas (allOf)

[ERROR] templates/: values don't meet the specifications of the schema(s) in the following chart(s):
corda:
- databases.0.host: Does not match format 'hostname'
- databases.0: Must validate all the schemas (allOf)


Error: 1 chart(s) linted, 1 chart(s) failed
```

The  json schema was updated to:
```
                "host": {
                    "type": "string",
                    "format": "hostname",
                    "default": "",
                    "title": "The database host"
                },
```

And the `values.yaml` to:
```
# List of databases used by the Platform
databases:
  # The default database configuration
  - name: default
    # -- the default database host (required)
    host: ""
    # -- the default database port
    port: 5432
```

2024-01-23 10:22 UTC, conalsmith-r3 commented on charts/corda/values.schema.json
> +                "tokenPoolCache"
There's another type, used by LinkManager, I think they're calling it `SessionState`

2024-01-23 10:23 UTC, conalsmith-r3 commented on charts/corda/values.schema.json
> +                "tokenPoolCache"
Maybe we can call it something like linkManagerSession

2024-01-23 10:26 UTC, davidcurrie commented on charts/corda/values.schema.json
> +                        }
Thanks. I really just wanted to say that the default values don't have to validate against the schema if we want the schema to force people to provide some missing value i.e. the schema doesn't have to allow null if that's really not a valid value. I assume that at some point in the future it might be valid e.g. if we support other types of storage and the default database isn't being used but we can adjust the schema at that point.

2024-01-23 10:28 UTC, davidcurrie commented
Thanks for the updates. LGTM pending the additional state Conal has mentioned.

2024-01-23 10:30 UTC, jujoramos commented on charts/corda/values.schema.json
> +                "tokenPoolCache"
It's not fully integrated yet, in fact the messaging related workers are not using the `StateManager` at the moment (they're creating an instance through the factory, sure, but that's all). Aside from that, there will be two new states required by these workers and the names are not defined yet, that's why I haven't made any changes around that.

2024-01-23 11:22 UTC, jujoramos commented on charts/corda/values.schema.json
> +                "tokenPoolCache"
Done!

2024-01-23 11:57 UTC, conalsmith-r3 approved these changes, later dismissed

2024-01-23 11:58 UTC, davidcurrie commented on charts/corda/values.yaml
> +    partition: "state_manager"
```suggestion
    partition: "p2p_session"
```

2024-01-23 12:11 UTC, davidcurrie commented on charts/corda/values.yaml
> +    partition: "state_manager"
@conalsmith-r3 - is there a good reason for all of the state managers to share the same schema in the default single database scenario?

2024-01-23 12:14 UTC, jujoramos commented on charts/corda/values.yaml
> +    partition: "state_manager"
Discussed offline with @conalsmith-r3 : we don't allow schema configuration at the moment, but the feature will be added as part of `CORE-19033` so I've made the change here already.

2024-01-23 12:16 UTC, davidcurrie approved these changes
LGTM

2024-01-23 12:47 UTC, wzur-r3 approved these changes
LGTM

2024-01-23 12:48 UTC, conalsmith-r3 approved these changes

2024-01-23 13:18 UTC, merged