CORE-19367: Implement wrapping of signing keys with new wrapping keys
corda/corda-runtime-os pull request #5481
Opened 2024-01-22 16:29 UTC by malachyb

This PR implements functions to help with the rewrapping of signing keys as part of a key rotation. It also changes the SoftCryptoService.createWrappingKeyFrom function to return a UUID for future work which will require the UUID of the generated wrapping key.

2024-01-23 14:11 UTC, anien commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoService.kt
> +    private fun createWrappingKeyFrom(wrappingRepository: WrappingRepository, oldWrappingKey: WrappingKeyInfo): UUID {
Is the change of adding `UUID` required anywhere? I can't really see it used. `saveKey` calls `saveKeyWithId` and creates random UUID anyway. So the functionality is the same.
Or is this for something in the future?

2024-01-23 14:14 UTC, malachyb commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoService.kt
> +    private fun createWrappingKeyFrom(wrappingRepository: WrappingRepository, oldWrappingKey: WrappingKeyInfo): UUID {
This is for the future. We'll need the UUID of the new wrapping key later on for wrapping the signing keys

2024-01-23 14:41 UTC, anien commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SigningRepositoryImpl.kt
> +                em.persist(signingKeyMaterialEntity)
Should this be `persist` or `merge`? We are only changing the signing key material, as it is wrapped with new wrapping key, everything else stays the same I believe. So if the key is already in the db and you persist it, you will get an `EntityExistsException`.

2024-01-23 14:46 UTC, malachyb commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SigningRepositoryImpl.kt
> +                em.persist(signingKeyMaterialEntity)
I didn't realise that would happen. That probably means I need to rewrite the test for this as well then.

2024-01-23 14:51 UTC, anien commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/SigningRepository.kt
> +     * @return the [SigningKeyMaterialEntity] that describes the new key material
```suggestion
     * @return the [SigningKeyMaterialInfo] that describes the new key material
```

2024-01-23 14:53 UTC, anien commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/SigningRepository.kt
> +    fun createNewSigningKeyMaterial(newWrappingKey: WrappingKey, signingKeyId: UUID, signingKey: PrivateKey): SigningKeyMaterialInfo
I would be tempted to rename this as it doesn't really create a new signing key material. It only wraps existing signing key material with new wrapping key. But I know it was designed to be named it this way, so let's just leave it.

2024-01-23 14:59 UTC, anien commented on components/crypto/crypto-softhsm-impl/src/integrationTest/kotlin/repository/SigningRepositoryTest.kt
> +    fun `createNewSigningMaterial creates new key with same metadata`(emf: EntityManagerFactory) {
```suggestion
    fun `createNewSigningMaterial wraps key material with new wrapping key`(emf: EntityManagerFactory) {
```

2024-01-23 15:10 UTC, simon-johnson-r3 commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SoftCryptoService.kt
> +    private fun createWrappingKeyFrom(wrappingRepository: WrappingRepository, oldWrappingKey: WrappingKeyInfo): UUID {
@anien if you look at `createNewSigningKeyMaterial` it takes the new wrapping key UUID, this is because to create a new key material row you need to fill in wrapping_key_id. In my original plan I had this UUID being looked up again in the `createNewSigningKeyMaterial` function, but this is unnecessary with this small change. So we decided to make this change in this PR for speed and as it's kind of related to the prototype of `createNewSigningKeyMaterial`.

2024-01-23 15:12 UTC, anien commented on components/crypto/crypto-softhsm-impl/src/integrationTest/kotlin/repository/SigningRepositoryTest.kt
> +        assertThat(curr.size).isEqualTo(prev.size + 1)
With merging signing key info in db, we will get only one key material back, so this wouldn't make sense. 

We probably should have two test cases, one, where the signing key info didn't exist in db before and one, where the signing key info already existed in db and we are only replacing the newly wrapped key material.

2024-01-23 15:14 UTC, simon-johnson-r3 commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SigningRepositoryImpl.kt
> +                em.persist(signingKeyMaterialEntity)
The wrapping key Id is different, so we need a new material, and the entity marks the wrapping key as part of the id, so this is correct as it is I believe.

2024-01-23 15:24 UTC, simon-johnson-r3 requested changes

2024-01-23 15:24 UTC, simon-johnson-r3 commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SigningRepositoryImpl.kt
> +    override fun createNewSigningKeyMaterial(
Ok, I know I suggested this but now I look at it, either we should move this code back into the crypto service, or move it into the other function. That's because this class follows the "repository" pattern, which means it's supposed to act like a repository of signing keys. This function doesn't store or retrieve anything so there's no benefit for it being here and also it doesn't fit the pattern.

I think `saveSigningKeyMaterial` taking a `signingKeyMaterialInfo` is fine, so I'd suggest to just delete it and remember we need it in the next task one level above.

2024-01-23 15:24 UTC, simon-johnson-r3 commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/SigningRepository.kt
> +     * Saves a signing key material entity to the database
The intent of this function is less obvious than `savePrivateKey` so I'd a bit more explanation. Perhaps we should point out that this is for when we are rotating existing keys and isn't required when saving new keys as that is taken care of for you in the other method?

2024-01-23 15:26 UTC, simon-johnson-r3 commented on components/crypto/crypto-softhsm-impl/src/integrationTest/kotlin/repository/SigningRepositoryTest.kt
> +        assertThat(curr.size).isEqualTo(prev.size + 1)
That's not how managed key wrapping works, you always have to create a new material because it points to a new wrapping key. The only field that remains the same as before is the signing key id, because it pertains to the same signing key.

2024-01-23 15:28 UTC, simon-johnson-r3 commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/SigningRepository.kt
> +    fun createNewSigningKeyMaterial(newWrappingKey: WrappingKey, signingKeyId: UUID, signingKey: PrivateKey): SigningKeyMaterialInfo
actually I suggest to delete it entirely, see below

2024-01-23 16:06 UTC, anien commented on components/crypto/crypto-softhsm-impl/src/integrationTest/kotlin/repository/SigningRepositoryTest.kt
> +        assertThat(curr.size).isEqualTo(prev.size + 1)
Ah yes, it's because wrapping key uuid is always new as we create new wrapping key (with the same alias, but higher generation number). Am I correct?

2024-01-23 16:09 UTC, anien commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/SigningRepositoryImpl.kt
> +                em.persist(signingKeyMaterialEntity)
I would argue that we don't have a new key material. Private key stays the same. It's only wrapped with a new wrapping key. And that's only for storage purposes. For signing purposes, the material is the same.

2024-01-24 09:59 UTC, anien approved these changes
I had a chat with Simon and clarified how the key material is rewrapped.
We always create a new record in the database with the key material wrapped with new wrapping key. This points to the same signing key. So in that sense, we do have multiple key materials for one signing key. 

Therefore the code, method name and test now make sense to me.

2024-01-24 14:47 UTC, simon-johnson-r3 approved these changes

2024-01-24 14:51 UTC, merged