CORE-18698 Store and find filtered transactions in the database
corda/corda-runtime-os pull request #5485
Opened 2024-01-22 18:28 UTC by nkovacsx

This PR contains the following changes:
- Move FilteredTransaction and FilteredTransactionFactory and their implementations to a separate module called `ledger-filtered-transaction-api` and `ledger-filtered-transaction`. This is needed because the common flow module didn't allow us to use these in the persistence worker.
- Compile and test changes related to this new module
- A new interface called `MerkleProofInternal` which has a `merge` function on it so we don't have to use `MerkleProofImpl` everywhere.
- A new interface called `UtxoFilteredTransactionInternal` so we can access the its `FilteredTransaction`.
- `FilteredTransaction` now exposes `privacySalt`
- Remove previously public API related to Merkle Proofs from the `UtxoLedgerPersistenceService`
- New functions called `persistFilteredTransactions` and `findFilteredTransactions` on the `UtxoPersistenceService` API (persistence worker side)

2024-01-23 15:10 UTC, jennyang-r3 commented on components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/utxo/UtxoPersistenceService.kt
> +    fun findFilteredTransactions(
If this API is going to be used internally of `fetchFilteredTransactions` API within persistence service, this wouldn't need to be exposed here I think. wdyt?

2024-01-23 15:32 UTC, blsemo commented
I was wondering whether we need new modules for filtered transactions? Couldn't they be moved into `libs/ledger/ledger-utxo-data`? We tend to have too many modules which causes gradle slowness and OSGi overhead...

2024-01-23 16:16 UTC, nkovacsx commented on components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/utxo/UtxoPersistenceService.kt
> +    fun findFilteredTransactions(
`UtxoPersistenceService` is part of the persistence worker API and not the public API. That one is `UtxoLedgerPersistenceService` if that's what you meant.

2024-01-23 16:21 UTC, nkovacsx commented on components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/utxo/UtxoPersistenceService.kt
> +    fun findFilteredTransactions(
Or did you mean that this should just be a private function inside `UtxoPersistenceServiceImpl`?

2024-01-23 16:36 UTC, jennyang-r3 commented on components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/utxo/UtxoPersistenceService.kt
> +    fun findFilteredTransactions(
Yeah, I meant to keep it private, I don't see the point of making it available outside of the persistence service since we don't use it anywhere else than inside of it.

2024-01-24 10:29 UTC, nkovacsx commented on components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/utxo/UtxoPersistenceService.kt
> +    fun findFilteredTransactions(
Made it private

2024-01-25 07:59 UTC, dickon commented
I think we should split out moving the code around and get that merged first so it's easier to read the behaviour changes.

2024-01-25 10:30 UTC, blsemo commented on components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/utxo/impl/AbstractUtxoQueryProvider.kt
> +                SELECT utmpl.leaf_index
Can you get input from @ifrankrui on the best way to write those queries?

2024-01-25 10:30 UTC, blsemo commented on components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/utxo/impl/UtxoPersistenceServiceImpl.kt
> +                emptyList()
That  is not correct, is it?  A filtered transaction can have whole section of the top level proof filtered out and have hashes.

2024-01-25 10:30 UTC, blsemo commented on libs/crypto/cipher-suite/build.gradle
> +    api 'net.corda:corda-application'
Why does crypto need to depend on application? Can we avoid that?

2024-01-25 13:46 UTC, jennyang-r3 commented on components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/utxo/impl/UtxoPersistenceServiceImpl.kt
> +    ): Map<String, FilteredTransaction> {
```suggestion
    ): Map<String, List<FilteredTransaction?, List<DigitalSignatureAndMetadata>>> {
```
Did we not agree to persist and fetch signatures alongside a filtered transaction?

2024-01-26 11:22 UTC, nkovacsx commented on components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/utxo/impl/UtxoPersistenceServiceImpl.kt
> +    ): Map<String, FilteredTransaction> {
Yes but I haven't pushed those changes yet 😄

2024-01-26 16:29 UTC, nkovacsx commented on libs/crypto/cipher-suite/build.gradle
> +    api 'net.corda:corda-application'
Removed

2024-01-26 16:29 UTC, nkovacsx commented on components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/utxo/impl/UtxoPersistenceServiceImpl.kt
> +                emptyList()
Discussed offline, now storing the top level as well

2024-01-26 17:29 UTC, blsemo reviewed
Doesn't look to bad - I'm going to have another look on Monday with a fresh pair of eyes.

2024-01-26 17:29 UTC, blsemo commented on components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/utxo/impl/UtxoPersistenceServiceImpl.kt
> +                val metadataBytes = jsonValidator.canonicalize(
Couldn't we fish out the metadata bytes from the 0th component group Merkle proof?

2024-01-29 14:05 UTC, jennyang-r3 commented on components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/utxo/impl/AbstractUtxoQueryProvider.kt
> +            AND utc.leaf_idx IN (
Would indexing on column `utc.leaf_idx` on the `WHERE` clause help the query performance?

2024-01-30 00:10 UTC, vlajos commented on components/ledger/ledger-common-flow/src/main/kotlin/net/corda/ledger/common/flow/impl/transaction/filtered/serializer/amqp/FilteredTransactionSerializer.kt
> +    val privacySalt: PrivacySalt
Won't this cause any trouble with upgrades?
I suppose there should not be any serialized filtered tx in the db from 5.1.
But in-flight Kafka messages may be possible. (at notarization)

2024-01-30 00:10 UTC, vlajos commented on components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/utxo/UtxoPersistenceService.kt
> +        signatures: List<DigitalSignatureAndMetadata>,
How does this know the relationship between the transactions and the signatures?
The `impl` looks like storing all the combinations.

2024-01-30 00:10 UTC, vlajos commented on components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/utxo/impl/AbstractUtxoQueryProvider.kt
> +                AND group_idx <> -1
Why is this needed?
Should the root Merkle Proofs data not come from the non-hidden component group's root IDs?
Can anything with -1 be saved here?

2024-01-30 00:10 UTC, vlajos commented on components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/utxo/impl/AbstractUtxoQueryProvider.kt
>              JOIN {h-schema}utxo_transaction_component utc
These comments a bit above:
`SHA-256D:11111-8-13`
do not show the separators between the leaves.

2024-01-30 00:10 UTC, vlajos commented on components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/utxo/impl/AbstractUtxoQueryProvider.kt
>              JOIN {h-schema}utxo_transaction_component utc
Actually, probably other parts of it are outdated too.

2024-01-30 00:10 UTC, vlajos commented on components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/utxo/impl/AbstractUtxoQueryProvider.kt
> +            AND utc.leaf_idx IN (
I do not think so. The transaction id is much more selective. And I think that is already part of the primary key.

2024-01-30 00:10 UTC, vlajos commented on components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/utxo/impl/PostgresUtxoQueryProvider.kt
> +                VALUES (:id, :privacySalt, :accountId, :createdAt, :status, :updatedAt, :metadataHash, :isFiltered)
I guess/hope transactions cannot change from is_filtered to normal.
At least currently.
In theory, the union of multiple Merkle proofs could reveal all the leaves.

2024-01-30 00:10 UTC, vlajos commented on components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/utxo/impl/UtxoPersistenceServiceImpl.kt
> +                val metadataBytes = jsonValidator.canonicalize(
It should be there.

2024-01-30 00:10 UTC, vlajos commented on components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/utxo/impl/UtxoPersistenceServiceImpl.kt
> +                    TransactionStatus.VERIFIED,
Can it be a filtered transaction unverified? Or anything else?
At least invalid should be an option if the notary signature cannot be verified.
Or probably they are rejected much earlier.

2024-01-30 00:10 UTC, vlajos commented on components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/utxo/impl/UtxoPersistenceServiceImpl.kt
> +                // 5. Persist the top level merkle proof and its leaves data
What needs to be persisted from the top-level proof's leaves?

2024-01-30 00:10 UTC, vlajos commented on components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/utxo/impl/UtxoPersistenceServiceImpl.kt
> +                }
I think it would be good to follow the order of the operations of the normal persistTransaction call.
Maybe sharing some code with that. (Although that may cause too much mess. I am not sure about this.)
Also, these ones look missing from here:
- persistTransactionSource (input/reference) (Although this one assumes that the related component groups are not filtered out. And I guess they are. Anyway, maybe it would be worth a comment.)
- persistVisibleTransactionOutput
- markTransactionVisibleStatesConsumed (Probably the same as persistTransactionSource)

2024-01-30 00:10 UTC, vlajos commented on components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/utxo/impl/UtxoPersistenceServiceImpl.kt
> +                ftxDto.topLevelMerkleProof.leavesWithData,
I think this could come from the revealed components' roots.

2024-01-30 00:10 UTC, vlajos commented on components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/utxo/impl/UtxoPersistenceServiceImpl.kt
> +                }.reduce { accumulator, merkleProof ->
Do the top-level proofs not need a similar merge?

2024-01-30 00:10 UTC, vlajos commented on components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/utxo/impl/UtxoRepositoryImpl.kt
> +            val topLevelMerkleProof = transactionMerkleProofs.singleOrNull {
Cannot be more root proof?

2024-01-30 00:10 UTC, vlajos commented on components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/utxo/impl/UtxoPersistenceServiceImpl.kt
> +            merkleProof.leaves.map { it.index },
Are the leaves ordered the same way everywhere?

2024-01-30 00:10 UTC, vlajos commented on components/ledger/ledger-utxo-flow/src/main/kotlin/net/corda/ledger/utxo/flow/impl/persistence/LedgerPersistenceMetricOperationName.kt
> +    UpdateTransactionStatus
I think the new operations should have their metrics defined.

2024-01-30 00:10 UTC, vlajos commented on libs/crypto/cipher-suite/src/main/kotlin/net/corda/crypto/cipher/suite/merkle/MerkleProofFactory.kt
> -        groupId: Int,
I think the @Suspendable is not needed for this.

2024-01-30 00:10 UTC, vlajos commented on libs/ledger/ledger-common-data/src/main/kotlin/net/corda/ledger/common/data/transaction/TransactionMetadataUtils.kt
> +    fun createTopLevelDigestProvider(
I would use
`TransactionWithMetadata.getRootMerkleTreeDigestProvider ` here.

2024-01-30 00:10 UTC, vlajos commented on libs/ledger/ledger-common-data/src/main/kotlin/net/corda/ledger/common/data/transaction/TransactionMetadataUtils.kt
> +    }
The `*BATCH*` settings are for the notary for batch signatures.
I think `wireTransaction.getComponentGroupMerkleTreeDigestProvider()` is the one you need here.
(Maybe it needs to be extracted `Extensions.TransactionWithMetadata.kt`)

2024-01-30 00:10 UTC, vlajos commented on libs/ledger/ledger-common-data/src/main/kotlin/net/corda/ledger/common/data/transaction/filtered/factory/FilteredTransactionFactory.kt
> +    @Suspendable
Do these suspend?
If so, then its impl should probably do the same.
If not, I would remove the annotation.

2024-01-30 09:12 UTC, jennyang-r3 commented on components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/utxo/impl/UtxoPersistenceServiceImpl.kt
> +        account: String
There is a comment from @rick-r3 regarding this line: https://github.com/corda/corda-runtime-os/pull/5535#discussion_r1470800222
> I'm not studying this PR in great detail currently, but I would just point out that the association between filteredTransactions and signatures on this API signature is unclear. If I look at the signature (actually, return type) of findFilteredTransactionsAndSignatures, it uses a Map to draw a clear association between transactions and signatures.

Perhaps the signature here should be persistFilteredTransactions(signedFilteredTransactions: Map<FilteredTransaction, List<DigitialSignatureAndMetadata>>, account: String) to make the association clear?

2024-01-30 10:31 UTC, nkovacsx commented on components/ledger/ledger-common-flow/src/main/kotlin/net/corda/ledger/common/flow/impl/transaction/filtered/serializer/amqp/FilteredTransactionSerializer.kt
> +    val privacySalt: PrivacySalt
Yeah I still need to double check what we can do with this. Probably not ideal from an upgrade perspective.

2024-01-30 10:32 UTC, nkovacsx commented on components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/utxo/UtxoPersistenceService.kt
> +        signatures: List<DigitalSignatureAndMetadata>,
Yeah good point, this is just a logic mess-up from me. 🤦

2024-01-30 10:33 UTC, nkovacsx commented on components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/utxo/impl/AbstractUtxoQueryProvider.kt
>              JOIN {h-schema}utxo_transaction_component utc
Yeah good point, thanks

2024-01-30 11:45 UTC, nkovacsx commented on components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/utxo/impl/AbstractUtxoQueryProvider.kt
> +                AND group_idx <> -1
We'll save data for `-1` component group when persisting, otherwise we won't be able to rebuild the top level merkle proof.

2024-01-30 14:30 UTC, nkovacsx commented on components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/utxo/impl/UtxoPersistenceServiceImpl.kt
> +                    TransactionStatus.VERIFIED,
If the notary signature is invalid then I think the flow will fail before reaching this point.

2024-01-30 14:31 UTC, nkovacsx commented on components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/utxo/impl/UtxoPersistenceServiceImpl.kt
> +                }.reduce { accumulator, merkleProof ->
There will only be one top level proof for each transaction right?

2024-01-30 14:32 UTC, nkovacsx commented on components/ledger/ledger-utxo-flow/src/main/kotlin/net/corda/ledger/utxo/flow/impl/persistence/LedgerPersistenceMetricOperationName.kt
> +    UpdateTransactionStatus
That's going to be handled in @jennyang-r3 's PR probably. These are only used when called from a flow I believe and my stuff is not public to the flow side.

2024-01-30 14:34 UTC, nkovacsx commented on libs/ledger/ledger-common-data/src/main/kotlin/net/corda/ledger/common/data/transaction/TransactionMetadataUtils.kt
> +    fun createTopLevelDigestProvider(
The problem is at the point where we use this we don't have a transaction object yet. We only have the metadata and we use this function to create the top level merkle proof.

2024-01-30 14:35 UTC, vlajos commented on components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/utxo/impl/UtxoPersistenceServiceImpl.kt
> +                }.reduce { accumulator, merkleProof ->
Differently filtered transactions from the same original transaction can result in different top-level proof.
When different component groups are revealed/filtered.

2024-01-30 14:37 UTC, vlajos commented on components/ledger/ledger-utxo-flow/src/main/kotlin/net/corda/ledger/utxo/flow/impl/persistence/LedgerPersistenceMetricOperationName.kt
> +    UpdateTransactionStatus
I guess the persist/fetchFilteredTransactions will need metrics. However, I do not know which PR is supposed to cover them.

2024-01-30 14:39 UTC, nkovacsx commented on components/ledger/ledger-utxo-flow/src/main/kotlin/net/corda/ledger/utxo/flow/impl/persistence/LedgerPersistenceMetricOperationName.kt
> +    UpdateTransactionStatus
As I see we use the metrics in `UtxoLedgerPersistenceService` when we call the external event executor and that's going to be in @jennyang-r3 's PR.

2024-01-30 14:46 UTC, vlajos commented on libs/ledger/ledger-common-data/src/main/kotlin/net/corda/ledger/common/data/transaction/TransactionMetadataUtils.kt
> +    fun createTopLevelDigestProvider(
At first glance that `TransactionWithMetadata` extension does not really look very transaction-specific, maybe it could be simply easily refactored to be an extension for the `TransactionMetadata`, and then it could be used in both places. Anyway, it would be good to avoid duplicating similar logic.

2024-01-30 14:52 UTC, vlajos commented on components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/utxo/impl/UtxoPersistenceServiceImpl.kt
> +                                createTopLevelDigestProvider(filteredTransactionMetadata, merkleTreeProvider)
This should be component hash digest provider.

2024-01-30 14:52 UTC, vlajos commented on components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/utxo/impl/UtxoPersistenceServiceImpl.kt
> +                    } ?: ByteArray(0)
I think a MerkleTree needs to be created from `listOf(ByteArray(0))` instead of simply passing that value.

2024-01-30 15:05 UTC, nkovacsx commented on components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/utxo/impl/UtxoPersistenceServiceImpl.kt
> +                    } ?: ByteArray(0)
I'm not sure because I used an `<Int, ByteArray>` mapping in `createAuditMerkleProof`. Is that wrong?

2024-01-30 15:22 UTC, vlajos commented on components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/utxo/impl/UtxoPersistenceServiceImpl.kt
> +                    } ?: ByteArray(0)
WireTransaction creates the component trees like this:
```
merkleTreeProvider.createTree(
                    group.ifEmpty { listOf(ByteArray(0)) },
                    getComponentGroupMerkleTreeDigestProvider(privacySalt, index)
                )
```
So the empty one will end in a tree as well.

2024-01-30 15:22 UTC, vlajos commented on components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/utxo/impl/UtxoPersistenceServiceImpl.kt
> +                        serializationService.serialize(
Why is this serialization here?

2024-01-30 16:43 UTC, nkovacsx commented on components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/utxo/impl/UtxoPersistenceServiceImpl.kt
> +                    } ?: ByteArray(0)
Yeah that makes sense but the `MerkleProofImpl` takes in a `private val leaves: List<IndexedMerkleLeaf>` which takes in a `public byte[] getLeafData();`.

2024-01-30 18:02 UTC, jennyang-r3 commented on components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/utxo/impl/PostgresUtxoQueryProvider.kt
> +                VALUES (:id, :privacySalt, :accountId, :createdAt, :status, :updatedAt, :metadataHash, :isFiltered)
Is it intentional that we add `is_filtered` field for postgres only?

2024-01-30 18:50 UTC, vlajos commented on components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/utxo/impl/UtxoPersistenceServiceImpl.kt
> +                    } ?: ByteArray(0)
For the top tree, we need the bytes from `SecureHashe`s, those can come from the roots of Proofs, but also from the roots of the Trees.

2024-01-31 10:00 UTC, nkovacsx commented on libs/ledger/ledger-common-data/src/main/kotlin/net/corda/ledger/common/data/transaction/TransactionMetadataUtils.kt
> +    fun createTopLevelDigestProvider(
yeah good point

2024-01-31 10:01 UTC, nkovacsx commented on components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/utxo/impl/PostgresUtxoQueryProvider.kt
> +                VALUES (:id, :privacySalt, :accountId, :createdAt, :status, :updatedAt, :metadataHash, :isFiltered)
No, I haven't pushed any HSQL changes yet.

2024-01-31 15:10 UTC, vlajos commented on components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/utxo/impl/UtxoPersistenceServiceImpl.kt
> +                val componentGroupHashDigestProvider = filteredTransactionMetadata.getComponentGroupMerkleTreeDigestProvider(
Similar ones are created a bit above in Line 467.

2024-02-01 16:58 UTC, rick-r3 commented on components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/utxo/impl/PostgresUtxoQueryProvider.kt
> +                VALUES (:id, :privacySalt, :accountId, :createdAt, :status, :updatedAt, :metadataHash, :isFiltered)
> I guess/hope transactions cannot change from is_filtered to normal. At least currently. In theory, the union of multiple Merkle proofs could reveal all the leaves.

We know we need to write some additional test cases that will likely reveal the need for additional changes, but nee d to merge this to unblock other work.  In particular, I think you can receive a filtered transaction when you already have the signed transaction, and you can receive a signed transaction when you already have a filtered transaction - and I think we should always prefer the full signed transaction to be stored in these scenarios, with zero filtered transactions.

Logically, yes, you can create 2 or more filtered transactions from the same signed transaction that when you union them results in a full signed transaction again, but we are going to limit our use cases to different combinations of outputs being revealed and e.g. never any of the inputs, so in practice it won't be possible (for now).

2024-02-01 17:39 UTC, rick-r3 commented on components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/utxo/impl/UtxoPersistenceServiceImpl.kt
> +                }
I think this is a good question.  You are right about the source and consumed not being relevant (yet) since we are not going to have a use case for now where the inputs or references are revealed.  However, we could do a check here that they are not revealed and throw if they are to prevent someone (at R3) later assuming this code was complete?

The more important one is that we do need to populate the visible states for the visible outputs.  But.... I think there's a problem here that I'm not going to solve in a PR comment or late in day.  One to revisit.

2024-02-02 09:44 UTC, rick-r3 commented on components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/utxo/impl/UtxoPersistenceServiceImpl.kt
> +                }
This is a bigger problem here that needs a revisit.  I think ignore for the purposes of this PR.  I will try and write up something about the problem.

2024-02-02 09:47 UTC, rick-r3 submitted a review, later dismissed

2024-02-02 11:12 UTC, vlajos approved these changes, later dismissed
I added a few small things potentially for a later PR.

2024-02-02 11:12 UTC, vlajos commented on components/ledger/ledger-persistence/src/integrationTest/kotlin/net/corda/ledger/persistence/utxo/tests/UtxoPersistenceServiceImplTest.kt
> +            mapOf(filteredTransactionToStore to emptyList()),
It would be good to verify the signature persistence's execution path.
But that can happen in a separate PR/ticket.

2024-02-02 11:12 UTC, vlajos commented on components/ledger/ledger-persistence/src/integrationTest/kotlin/net/corda/ledger/persistence/utxo/tests/UtxoPersistenceServiceImplTest.kt
> +                    0,
UtxoComponentGroup.OUTPUTS_INFO.ordinal would be a bit nicer instead of the constant.
Or potentially using the `LedgerService.filterSignedTransaction` to replace the creation steps. (if that works in integration tests.)

2024-02-02 11:12 UTC, vlajos commented on components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/utxo/impl/UtxoPersistenceServiceImpl.kt
> +            filteredTransaction.id.toString() to Pair(filteredTransaction, ftxDto.signatures)
`transactionId` is already the same in string.

2024-02-02 11:12 UTC, vlajos commented on libs/ledger/ledger-common-data/src/main/kotlin/net/corda/ledger/common/data/transaction/Extensions.TransactionMetadata.kt
> +import java.util.*
Is detekt OK with wildcard import?

2024-02-02 11:52 UTC, rick-r3 submitted a review, later dismissed
Re-approve

2024-02-02 12:01 UTC, wzur-r3 requested changes

2024-02-02 12:01 UTC, wzur-r3 commented on gradle.properties
> +cordaApiVersion=5.2.0.35-alpha-1706867503433
please revert it back to a beta release

2024-02-02 13:08 UTC, mbrkic-r3 submitted a review, later dismissed
LGTM (flow related code)

2024-02-02 14:29 UTC, rick-r3 approved these changes

2024-02-02 14:46 UTC, vlajos approved these changes

2024-02-02 15:34 UTC, wzur-r3 approved these changes
LGTM

2024-02-02 15:38 UTC, merged