CORE-19424 - Avoid HikarCP for DDL operations
corda/corda-runtime-os pull request #5509
Opened 2024-01-24 18:30 UTC by driessamyn

Introduce a `enablePool` flag on creating DataSources, which is set to `true` by default, but is set to `false` for the DDL operations.

2024-01-25 14:01 UTC, kyriathar reviewed
Looks good in principle, as the first step of removing DDL connections from using pools. So this one removes client side pooling from DDL connections and [CORE-19425](https://r3-cev.atlassian.net/browse/CORE-19425) will do for server side pooling.

2024-01-25 14:01 UTC, kyriathar commented on components/db/db-connection-manager-impl/src/main/kotlin/net/corda/db/connection/manager/impl/DbConnectionsRepositoryImpl.kt
> +            return dataSourceFactory.createFromConfig(dbConfigFactory.create(config), DbPrivilege.DML == privilege)
nit: we might want to use named parameter here as it is not too obvious I think.

2024-01-25 14:01 UTC, kyriathar commented on components/db/db-connection-manager/src/main/kotlin/net/corda/db/connection/manager/DbConnectionsRepository.kt
> +    fun create(config: SmartConfig, enablePool: Boolean = true): CloseableDataSource
I think users of these APIs will always go for DML operations so it should be fine to default it to true?

Although I think there are other cases (most of them I believe) where we do DML operations acquire a pool only to close it when the request was handled. 

Maybe not for this PR and actually work for https://r3-cev.atlassian.net/browse/CORE-18280 but maybe in such cases we shouldn't be creating a Hikari pool? Should it be only create a Hikari pool only if we are to cache it? In which case perhaps the DB connection manager could determine to return a pooled datasource or not depending on whether it is to be cached or not?

2024-01-26 08:56 UTC, driessamyn commented on components/db/db-connection-manager-impl/src/main/kotlin/net/corda/db/connection/manager/impl/DbConnectionsRepositoryImpl.kt
> +            return dataSourceFactory.createFromConfig(dbConfigFactory.create(config), DbPrivilege.DML == privilege)
I thought the IDE tells you ;)
But fair enough, added now.

2024-01-26 09:01 UTC, driessamyn commented on components/db/db-connection-manager/src/main/kotlin/net/corda/db/connection/manager/DbConnectionsRepository.kt
> +    fun create(config: SmartConfig, enablePool: Boolean = true): CloseableDataSource
> I think users of these APIs will always go for DML operations so it should be fine to default it to true?

Not necessarily. I created some tickets to change the admin operations to skip the pool too.
More importantly, I think this component shouldn't be opinionated about what its consumer wants, so I think if we made assumptions here about what the consumer want, it's mixing up concerns.

>  Maybe not for this PR and actually work for CORE-18280 but maybe in such cases we shouldn't be creating a Hikari pool? Should it be only create a Hikari pool only if we are to cache it? In which case perhaps the DB connection manager could determine to return a pooled datasource or not depending on whether it is to be cached or not?

As above, I think that is mixing up concerns. The class creates connections but shouldn't be concerned with how they are used. Similarly, the DbManager shouldn't decide what type of connection to create either. It's reasonable to cache a pool of cluster connections, for example.

2024-01-26 09:27 UTC, simon-johnson-r3 requested changes

2024-01-26 09:27 UTC, simon-johnson-r3 commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt
> +                                    .createDatasource(virtualNodeInfo.vaultDdlConnectionId!!, enablePool = false),
I was always lead to believe the convention at R3 is to use `checkNotNull` to provide an IllegalStateException. Although I see this function already uses !! everywhere else.

2024-01-26 09:27 UTC, simon-johnson-r3 commented on libs/db/db-core/src/main/kotlin/net/corda/db/core/DataSourceFactoryImpl.kt
> +class DataSourceFactoryImpl(
The comment against this class is now out of date.

2024-01-26 09:27 UTC, simon-johnson-r3 commented on libs/db/db-core/src/main/kotlin/net/corda/db/core/CreateDataSourceMethod.kt
> +fun createUnpooledDataSource(
is this used for the db message bus implementation only, and the intent here is that at the point of use only one long lived connection is ever required?

2024-01-26 09:40 UTC, driessamyn commented on components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt
> +                                    .createDatasource(virtualNodeInfo.vaultDdlConnectionId!!, enablePool = false),
I didn't know about the convention ;) Is it written down somewhere?

Either way, I think changing that is out of scope for this PR given, as you said, it doesn't change the existing implementation in that respect.

2024-01-26 09:50 UTC, driessamyn commented on libs/db/db-core/src/main/kotlin/net/corda/db/core/CreateDataSourceMethod.kt
> +fun createUnpooledDataSource(
This method I thought was only used in tests and tooling (see screenshot below), so I figured it would be ok to be "un-pooled".
However, I just realised this may not be the best for the message bus emulation, so I replaced that to just use the factory.

I'm not entirely convinced of the value of this method, but wanted to limit the scope of this PR.

<img width="550" alt="image" src="https://github.com/corda/corda-runtime-os/assets/5557551/ef590bf1-891c-402f-8ee6-9c64fcb102cf">

2024-01-26 10:29 UTC, simon-johnson-r3 commented on libs/db/db-core/src/main/kotlin/net/corda/db/core/CreateDataSourceMethod.kt
> +fun createUnpooledDataSource(
Indeed. It's presence stuck out on this PR, but like you say, it's a job for another day.

2024-01-26 10:31 UTC, simon-johnson-r3 approved these changes

2024-01-26 11:08 UTC, LWogan approved these changes

2024-01-26 11:11 UTC, kyriathar commented on libs/db/db-core/src/main/kotlin/net/corda/db/core/DataSourceFactoryImpl.kt
> +    override fun create(
Maybe nit but I am not sure about this API now. There are options that only apply for pooled. For example someone could be passing in `maximumPoolSize`  and `enablePool = false`. Sounds like it should be split in two?

2024-01-26 11:15 UTC, driessamyn commented on libs/db/db-core/src/main/kotlin/net/corda/db/core/DataSourceFactoryImpl.kt
> +    override fun create(
The KDocs flag which arguments are ignored when pooling is disabled. 
I think this simplifies the consuming code (although we maybe should make all of those arguments optional with defaults).

2024-01-26 11:56 UTC, vkolomeyko approved these changes
LGTM on behalf of @corda/rest

2024-01-26 12:19 UTC, merged