ES-1827: Corda Runtime Gradle Plugin start stop corda tasks
corda/corda-runtime-os pull request #5536
Opened 2024-01-26 15:35 UTC by tlawson3

https://r3-cev.atlassian.net/browse/ES-1827
PR 2 of 4 relating to the Corda Runtime Gradle Plugin
Aim of this ticket was to:

- Recreate the start/stop/stop&clear tasks of the CSDE
- Add new use case for downloading alpha/beta builds

Added automated tests for the download Combined Worker logic
Not sure how we can test the start/stop tasks which spin up a docker container, in the pipeline
Tested manually:
<img width="305" alt="Screenshot 2024-01-26 at 15 33 07" src="https://github.com/corda/corda-runtime-os/assets/92731849/29e097aa-6b9e-4aac-b710-5d3ca4d0aabb">

1. Is there a better way to handle the credentials?
2. Is the Postgres JDBC version ok?

2024-01-26 16:06 UTC, davidcurrie commented on tools/corda-runtime-gradle-plugin/src/main/kotlin/net/corda/gradle/plugin/configuration/PluginConfiguration.kt
> +    val combinedWorkerVersion: Property<String> = objects.property(String::class.java).convention("5.0.1.0")
5.1?

2024-01-26 16:18 UTC, davidcurrie requested changes
Feel free to push back on anything that you think is going to take significant time and is going to go away anyway...

2024-01-26 16:18 UTC, davidcurrie commented on tools/corda-runtime-gradle-plugin/src/main/kotlin/net/corda/gradle/plugin/configuration/PluginConfiguration.kt
> +    val postgresJdbcVersion: Property<String> = objects.property(String::class.java).convention("42.4.3")
We use 42.6.0 in Corda itself: https://github.com/corda/corda-runtime-os/blob/release/os/5.2/gradle.properties#L99

2024-01-26 16:18 UTC, davidcurrie commented on tools/corda-runtime-gradle-plugin/README.md
> +        postgresJdbcVersion = "42.4.3"
Eventually we want these to be related to the build that is creating the plugin but, given this will change again if get to the containerised version, I'm not sure it's worth trying to address now. If nothing does change though, we need to remember to update the defaults to 5.2 before GA.

2024-01-26 16:18 UTC, davidcurrie commented on tools/corda-runtime-gradle-plugin/src/main/kotlin/net/corda/gradle/plugin/configuration/PluginConfiguration.kt
> +        .convention(System.getenv("CORDA_BIN") ?: "${System.getProperty("user.home")}/.corda/corda5")
Would be nice if this was specific to the Corda version but then the same is true of the CLI which is out of our control here. Again, a problem that goes away if we get to the containerised version.

2024-01-26 16:18 UTC, davidcurrie commented on tools/corda-runtime-gradle-plugin/src/main/kotlin/net/corda/gradle/plugin/cordalifecycle/CordaLifecycleHelper.kt
> +            "postgres:latest"
Could we pin this to `postgres:14.10` given that's what we're going to specify as the prereq version for Corda?

2024-01-26 16:18 UTC, davidcurrie commented on tools/corda-runtime-gradle-plugin/src/main/kotlin/net/corda/gradle/plugin/cordalifecycle/CordaLifecycleHelper.kt
> +        }
I'll be glad when all of this can go away too..

2024-01-26 16:19 UTC, tlawson3 commented on tools/corda-runtime-gradle-plugin/src/main/kotlin/net/corda/gradle/plugin/configuration/PluginConfiguration.kt
> +    val combinedWorkerVersion: Property<String> = objects.property(String::class.java).convention("5.0.1.0")
I did originally have it as 5.1, but it wouldn't start with the default config when I was testing it. The reason being: 5.1 needed some extra options on the start up command - https://github.com/corda/csde-gradle-plugin/blob/d6db5fbb708317aa45e859f346aa9ce916976a75/src/main/kotlin/net/corda/plugins/csde/cordalifecycle/CordaLifeCycleHelper.kt#L86-L90

From what I remember, passing those options when running 5.0 (and guessing 5.2) prevents the CW from starting. So we end up in the situation where 5.0 & 5.2+ needs the start command to NOT have these options; but if a user is using 5.1 we need those options.

Given we're targeting 5.2, and this plugin didn't exist for 5.1, I've not added any switching logic. 
When we come to the 5.2 cut, we should set this value to the final 5.2 release version

2024-01-26 16:27 UTC, tlawson3 commented on tools/corda-runtime-gradle-plugin/src/main/kotlin/net/corda/gradle/plugin/configuration/PluginConfiguration.kt
> +    val postgresJdbcVersion: Property<String> = objects.property(String::class.java).convention("42.4.3")
I wonder if there's anyway to pass this property through.

2024-01-26 17:07 UTC, anton-subbotin commented on tools/corda-runtime-gradle-plugin/README.md
> +        combinedWorkerVersion = "5.1.0.0"
It isn't really starting with the 5.1.0.0, worth changing in the README

2024-01-29 11:29 UTC, davidcurrie approved these changes
LGTM

2024-01-29 11:48 UTC, wzur-r3 approved these changes
LGTM

2024-01-29 11:49 UTC, anton-subbotin approved these changes
LGTM

2024-01-29 11:50 UTC, merged