CORE-19461: state for individual rotations complete (CryptoRewrapBusProcessor)
corda/corda-runtime-os pull request #5565
Opened 2024-01-31 12:02 UTC by malachyb

This PR handles the state manager updates of managed key rotation. The testing used by the class also had to change how its serializers were generated, as both the strategy used previously and the strategy used in https://github.com/corda/corda-runtime-os/pull/5539 did not work. The previous strategy didn't work with multiple serializer types being returned, as mockito did not allow us to change based on generics, and the strategy used in the linked PR did not allow for the return of multiple deserialisers, so this PR had to switch to having multiple factories, one for managed tests and another for unmanaged tests.

2024-02-01 13:05 UTC, simon-johnson-r3 requested changes

2024-02-01 13:05 UTC, simon-johnson-r3 commented on components/crypto/crypto-service-impl/src/main/kotlin/net/corda/crypto/service/impl/bus/CryptoRewrapBusProcessor.kt
> +            require(tenantIdSigningKeysRecords.size == 1) {
`require` throws `IllegalArgumentException`, which isn't a good fit here. It's possible the `request` has invalid values in it, but that's just a guess at this point in the code, in reality this is a problem with internal state at this point, so `check` is a better fit.

2024-02-01 13:05 UTC, simon-johnson-r3 commented on components/crypto/crypto-service-impl/src/main/kotlin/net/corda/crypto/service/impl/bus/CryptoRewrapBusProcessor.kt
> +            tenantIdSigningKeysRecords.forEach { (_, state) ->
You test there's only one of these already so `tenantIdSigningKeysRecords.single()` would be better than a loop over what you know is 1 thing.

2024-02-01 13:05 UTC, simon-johnson-r3 commented on components/crypto/crypto-service-impl/src/main/kotlin/net/corda/crypto/service/impl/bus/CryptoRewrapBusProcessor.kt
> +                    "Updating state manager record for tenantId ${state.metadata[KeyRotationMetadataValues.TENANT_ID]} " +
you can extract the tenantId much more simply by using `${request.tenantId}`

2024-02-01 13:05 UTC, simon-johnson-r3 commented on components/crypto/crypto-service-impl/src/main/kotlin/net/corda/crypto/service/impl/bus/CryptoRewrapBusProcessor.kt
> +                                deserializedStatus.rotatedKeys,
Here and below, you use `deserializedStatus.rotatedKeys` without taking care of incrementing for the newly rotated keys. I think means modifying `rewrapAllSigningKeysWrappedBy` to return the number of signing keys which were rewrapped too?

2024-02-01 13:05 UTC, simon-johnson-r3 commented on components/crypto/crypto-service-impl/src/main/kotlin/net/corda/crypto/service/impl/bus/CryptoRewrapBusProcessor.kt
> +        }
can you add a blank line here? I thought the IDE would insist on this actually.

2024-02-01 13:05 UTC, simon-johnson-r3 commented on components/crypto/crypto-service-impl/src/main/kotlin/net/corda/crypto/service/impl/bus/CryptoRewrapBusProcessor.kt
> +        if (total == rotatedKeys + 1) {
If total = 3 and rotatedKeys = 2, you'll mark it as DONE?

2024-02-01 13:07 UTC, simon-johnson-r3 commented on components/crypto/crypto-service-impl/src/test/kotlin/net/corda/crypto/service/impl/bus/CryptoRewrapBusProcessorTests.kt
> -    private val cryptoRewrapBusProcessor = CryptoRewrapBusProcessor(
I see why you've done this, although it would have been nice to test a `CryptoRewrapBusProcessor` set up the same way with both kinds of messages. If this is impractical with Mockito though we can let it go.

2024-02-01 13:11 UTC, simon-johnson-r3 commented on components/crypto/crypto-service-impl/src/test/kotlin/net/corda/crypto/service/impl/bus/CryptoRewrapBusProcessorTests.kt
> +        unmanagedCryptoRewrapBusProcessor.onNext(
You should add a test that the state after rotation is ok for both managed and unmanaged keys, see https://github.com/corda/corda-runtime-os/blob/cf0ac00cec68619e995557c5318a13e9d72256ea/components/crypto/crypto-service-impl/src/test/kotlin/net/corda/crypto/service/impl/bus/CryptoRekeyBusProcessorTests.kt#L194 for an example.

2024-02-01 14:11 UTC, malachyb commented on components/crypto/crypto-service-impl/src/main/kotlin/net/corda/crypto/service/impl/bus/CryptoRewrapBusProcessor.kt
> +        if (total == rotatedKeys + 1) {
rotatedKeys comes from the old state but I'll change where the + is to make it less confusing.

2024-02-05 17:20 UTC, simon-johnson-r3 approved these changes

2024-02-06 09:43 UTC, merged