ES-1828: Gradle plugin deploy CPI with static network
corda/corda-runtime-os pull request #5570
Opened 2024-01-31 15:43 UTC by tlawson3

https://r3-cev.atlassian.net/browse/ES-1828

Reproduce the heart and soul of the CSDE plugin.
Split some of the functionality so that the gradle/project specific things are in the taskImpl classes, and the "helpers" are pure kotlin: thinking ahead to when we pick up the Corda SDK.

Tested manually:
<img width="1631" alt="Screenshot 2024-01-31 at 15 20 07" src="https://github.com/corda/corda-runtime-os/assets/92731849/94bd4f5e-786a-4b2f-a321-a2fb09ba6838">

2024-01-31 16:11 UTC, ronanbrowne approved these changes, later dismissed
LGTM ....  for the BLT marked files, I'll leave the *.kt to someone else to review.

2024-01-31 16:34 UTC, anton-subbotin submitted a review, later dismissed
LGTM

2024-01-31 16:38 UTC, anton-subbotin approved these changes

2024-02-01 09:20 UTC, anton-subbotin requested changes

2024-02-01 09:20 UTC, anton-subbotin commented on tools/corda-runtime-gradle-plugin/src/main/kotlin/net/corda/gradle/plugin/configuration/ProjectContext.kt
> +    val notaryVersion: String = combinedWorkerVersion
Please bring it back as user-configurable property: there might be cases when comb.worker and notary versions need to be different

2024-02-01 09:59 UTC, anton-subbotin approved these changes, later dismissed

2024-02-01 13:01 UTC, ronanbrowne approved these changes, later dismissed

2024-02-01 17:14 UTC, davidcurrie reviewed
Long list of nits but fundamentally LGTM

2024-02-01 17:14 UTC, davidcurrie commented on tools/corda-runtime-gradle-plugin/src/main/kotlin/net/corda/gradle/plugin/ProjectUtils.kt
> + * @return a list of the virtual nodes which have already been created.
Missing `@param`. I'm not overly fussed on having Javadoc but if we have it, it should be correct!

2024-02-01 17:14 UTC, davidcurrie commented on tools/corda-runtime-gradle-plugin/src/main/kotlin/net/corda/gradle/plugin/cordapp/BuildCpiHelper.kt
> +            throw CordaRuntimeGradlePluginException("Cpb file not found at: $cpbFilePath.")
nit:
```suggestion
            throw CordaRuntimeGradlePluginException("CPB file not found at: $cpbFilePath.")
```

2024-02-01 17:14 UTC, davidcurrie commented on tools/corda-runtime-gradle-plugin/src/main/kotlin/net/corda/gradle/plugin/cordapp/CordappTasksImpl.kt
> +            throw CordaRuntimeGradlePluginException("Failed to read GroupPolicy from group policy file with exception: $e.")
Why would it be trying to use the Corda CLI here?

2024-02-01 17:14 UTC, davidcurrie commented on tools/corda-runtime-gradle-plugin/src/main/kotlin/net/corda/gradle/plugin/cordapp/CordappTasksImpl.kt
> +            if (membersNames?.any { requiredNode.x500Name == it } != true) {
I'm not looking at this in an IDE but is is this not just:
```suggestion
            if (!membersNames?.contains(requiredNode.x500Name)) {
```

2024-02-01 17:14 UTC, davidcurrie commented on tools/corda-runtime-gradle-plugin/src/main/kotlin/net/corda/gradle/plugin/cordapp/CordappTasksImpl.kt
> +        pc.logger.quiet("Creating ${pc.corDappCpiName} Cpi.")
```suggestion
        pc.logger.quiet("Creating ${pc.corDappCpiName} CPI.")
```

2024-02-01 17:14 UTC, davidcurrie commented on tools/corda-runtime-gradle-plugin/src/main/kotlin/net/corda/gradle/plugin/cordapp/CordappTasksImpl.kt
> +        pc.logger.quiet("Creating ${pc.notaryCpiName} Cpi.")
```suggestion
        pc.logger.quiet("Creating ${pc.notaryCpiName} CPI.")
```

2024-02-01 17:14 UTC, davidcurrie commented on tools/corda-runtime-gradle-plugin/src/main/kotlin/net/corda/gradle/plugin/cordapp/CordappTasksImpl.kt
> +        pc.logger.quiet("Cpi ${pc.corDappCpiName} uploaded: ${cpiUploadStatus.cpiFileChecksum}")
```suggestion
        pc.logger.quiet("CPI ${pc.corDappCpiName} uploaded: ${cpiUploadStatus.cpiFileChecksum}")
```

2024-02-01 17:14 UTC, davidcurrie commented on tools/corda-runtime-gradle-plugin/src/main/kotlin/net/corda/gradle/plugin/cordapp/CordappTasksImpl.kt
> +        pc.logger.quiet("Cpi ${pc.notaryCpiName} uploaded: ${notaryUploadStatus.cpiFileChecksum}")
```suggestion
        pc.logger.quiet("CPI ${pc.notaryCpiName} uploaded: ${notaryUploadStatus.cpiFileChecksum}")
```

2024-02-01 17:14 UTC, davidcurrie commented on tools/corda-runtime-gradle-plugin/src/main/kotlin/net/corda/gradle/plugin/cordapp/DeployCpiHelper.kt
> +            throw CordaRuntimeGradlePluginException("Failed to request upload of cpi: '$cpiName'.")
```suggestion
            throw CordaRuntimeGradlePluginException("Failed to request upload of CPI: '$cpiName'.")
```

2024-02-01 17:14 UTC, davidcurrie commented on tools/corda-runtime-gradle-plugin/src/main/kotlin/net/corda/gradle/plugin/cordapp/DeployCpiHelper.kt
> +            throw CordaRuntimeGradlePluginException("Failed to request upload of cpi: '$cpiName'.")
would also be useful to include the status code here

2024-02-01 17:14 UTC, davidcurrie commented on tools/corda-runtime-gradle-plugin/src/main/kotlin/net/corda/gradle/plugin/cordapp/DeployCpiHelper.kt
> +            throw CordaRuntimeGradlePluginException("Failed to request upload of cpi: '$cpiName'.")
```suggestion
            throw CordaRuntimeGradlePluginException("Failed to request upload of CPI: '$cpiName'.", e)
```

2024-02-01 17:14 UTC, davidcurrie commented on tools/corda-runtime-gradle-plugin/src/main/kotlin/net/corda/gradle/plugin/cordapp/DeployCpiHelper.kt
> +            throw CordaRuntimeGradlePluginException("Failed to check Cpis, response status:  ${response.status}.")
```suggestion
            throw CordaRuntimeGradlePluginException("Failed to check CPIs, response status:  ${response.status}.")
```

2024-02-01 17:14 UTC, davidcurrie commented on tools/corda-runtime-gradle-plugin/src/main/kotlin/net/corda/gradle/plugin/cordapp/DeployCpiHelper.kt
> +            throw CordaRuntimeGradlePluginException("Failed to check Cpis with exception: $e.")
```suggestion
            throw CordaRuntimeGradlePluginException("Failed to check Cpis with exception: ${e.message}.", e)
```

2024-02-01 17:14 UTC, davidcurrie commented on tools/corda-runtime-gradle-plugin/src/main/kotlin/net/corda/gradle/plugin/cordapp/DeployCpiHelper.kt
> +                        "Failed to verify Cpi Upload Status, current status: ${cpiUploadStatus.status}."
```suggestion
                        "CPI Upload Status is not OK, current status: ${cpiUploadStatus.status}."
```

2024-02-01 17:14 UTC, davidcurrie commented on tools/corda-runtime-gradle-plugin/src/main/kotlin/net/corda/gradle/plugin/cordapp/DeployCpiHelper.kt
> +                    throw CordaRuntimeGradlePluginException("Failed to get Cpi Upload Status, response status: ${response.status}.")
```suggestion
                    throw CordaRuntimeGradlePluginException("Failed to get CPI Upload Status, response status: ${response.status}.")
```

2024-02-01 17:14 UTC, davidcurrie commented on tools/corda-runtime-gradle-plugin/src/main/kotlin/net/corda/gradle/plugin/network/VNodeHelper.kt
> +        ) throw CordaRuntimeGradlePluginException("Cpi $cpiCheckSum not uploaded.")
```suggestion
        ) throw CordaRuntimeGradlePluginException("CPI $cpiCheckSum not uploaded.")
```

2024-02-01 17:14 UTC, davidcurrie commented on tools/corda-runtime-gradle-plugin/src/main/kotlin/net/corda/gradle/plugin/network/VNodeHelper.kt
> +            throw CordaRuntimeGradlePluginException("Failed to check cpis, response status: " + response.status)
```suggestion
            throw CordaRuntimeGradlePluginException("Failed to check CPIs, response status: " + response.status)
```

2024-02-01 17:14 UTC, davidcurrie commented on tools/corda-runtime-gradle-plugin/src/main/kotlin/net/corda/gradle/plugin/network/VNodeHelper.kt
> +            throw CordaRuntimeGradlePluginException("Failed to check cpis with exception: $e")
```suggestion
            throw CordaRuntimeGradlePluginException("Failed to check CPIs with exception: ${e.message}", e)
```

2024-02-01 17:14 UTC, davidcurrie commented on tools/corda-runtime-gradle-plugin/src/main/kotlin/net/corda/gradle/plugin/network/VNodeHelper.kt
> +                "Registration failed because more than virtual node for '${requiredNode.x500Name}'"
```suggestion
                "Registration failed because more than one virtual node for '${requiredNode.x500Name}'"
```

2024-02-01 17:14 UTC, davidcurrie commented on tools/corda-runtime-gradle-plugin/src/main/kotlin/net/corda/gradle/plugin/network/VNodeHelper.kt
> +            throw CordaRuntimeGradlePluginException("Failed to check registration status for $shortHash with exception: $e.")
```suggestion
            throw CordaRuntimeGradlePluginException("Failed to check registration status for $shortHash with exception: ${e.message}.", e)
```

2024-02-02 10:25 UTC, tlawson3 commented on tools/corda-runtime-gradle-plugin/src/main/kotlin/net/corda/gradle/plugin/cordapp/CordappTasksImpl.kt
> +            throw CordaRuntimeGradlePluginException("Failed to read GroupPolicy from group policy file with exception: $e.")
The `GroupPolicyHelper().createStaticGroupPolicy` invokes the Corda CLI network plugin with the command `mgm groupPolicy`. This is how we generate the static network definition. One of the hard dependencies on the Corda CLI, the other being the CPI package.

2024-02-02 10:32 UTC, davidcurrie commented on tools/corda-runtime-gradle-plugin/src/main/kotlin/net/corda/gradle/plugin/cordapp/CordappTasksImpl.kt
> +            throw CordaRuntimeGradlePluginException("Failed to read GroupPolicy from group policy file with exception: $e.")
That's not inside this try-catch though, is it?

2024-02-02 10:41 UTC, tlawson3 commented on tools/corda-runtime-gradle-plugin/src/main/kotlin/net/corda/gradle/plugin/cordapp/CordappTasksImpl.kt
> +            throw CordaRuntimeGradlePluginException("Failed to read GroupPolicy from group policy file with exception: $e.")
The error about Corda CLI will be written to the groupPolicyFile, which we are validating here. And if the error is about not finding/accessing the `corda-cli.jar` then we want to give the user a good error

2024-02-02 10:47 UTC, davidcurrie commented on tools/corda-runtime-gradle-plugin/src/main/kotlin/net/corda/gradle/plugin/cordapp/CordappTasksImpl.kt
> +            throw CordaRuntimeGradlePluginException("Failed to read GroupPolicy from group policy file with exception: $e.")
Gotcha - sorry, I hadn't fully grasped why it was looking for the error in the file.

2024-02-02 11:01 UTC, anton-subbotin approved these changes
LGTM

2024-02-05 09:25 UTC, wzur-r3 approved these changes
LGTM for Gradle configuration file

2024-02-05 09:35 UTC, davidcurrie approved these changes
🚀 LGTM

2024-02-05 09:44 UTC, merged