CORE-19372: Isolated Storage per State Type
corda/corda-runtime-os pull request #5598
Opened 2024-02-02 16:47 UTC by jujoramos

2024-02-05 20:25 UTC, davidcurrie reviewed
My only substantive comment is the one about `id` vs `name`.

2024-02-05 20:25 UTC, davidcurrie commented on charts/corda-lib/templates/_stateManager.tpl
> +      {{-   if $bootstrapSettings.username.valueFrom.secretKeyRef.name }}
```suggestion
      {{- if $bootstrapSettings.username.valueFrom.secretKeyRef.name }}
```

2024-02-05 20:25 UTC, davidcurrie commented on charts/corda/values.yaml
> +  - name: cordacluster
It is only in seeing this written down that I've realised what you were saying about `cordacluster` vs `default`. Is it not indicative that there is a problem with using the database name as the identifier to match with `storageId` given that it might not be unique? The DBA might me a list of database hosts in each of which they have created a database called `corda`. I suspect your initial intuition was correct that there should be an `id` of `default` with the `name` set to `cordacluster`.

2024-02-06 08:25 UTC, jujoramos commented on charts/corda/values.yaml
> +  - name: cordacluster
Dang, that's a good point actually, we should have caught this during the design review 👎. Let me fix it, and thanks for catching it.

2024-02-06 15:45 UTC, davidcurrie reviewed
LGTM

2024-02-06 15:45 UTC, davidcurrie commented on .ci/e2eTests/Jenkinsfile
> +@Library('corda-shared-build-pipeline-steps@CORE-19345-newSmConfig') _
TODO: revert

2024-02-06 15:46 UTC, jujoramos commented on .ci/e2eTests/Jenkinsfile
> +@Library('corda-shared-build-pipeline-steps@CORE-19345-newSmConfig') _
Yep, planning to revert this one once changes to `corda-shared-build-pipeline-steps` have been merged and the `PR` can execute against `corda-shared-build-pipeline-steps@5.2`.

2024-02-06 15:50 UTC, LWogan approved these changes, later dismissed
Fine from flow worker perspective

2024-02-06 15:51 UTC, mag1c-48 requested changes
shared lib reference needs to be reverted

2024-02-06 15:51 UTC, mag1c-48 commented on Jenkinsfile
> +@Library('corda-shared-build-pipeline-steps@CORE-19345-newSmConfig') _
Needs to be reverted

2024-02-06 15:53 UTC, jujoramos commented on Jenkinsfile
> +@Library('corda-shared-build-pipeline-steps@CORE-19345-newSmConfig') _
It needs to be reverted indeed, but https://github.com/corda/corda-api/pull/1486 and https://github.com/corda/corda-shared-build-pipeline-steps/pull/1588 need to be merged before I can revert `corda-shared-build-pipeline-steps@5.2`.

2024-02-06 16:50 UTC, ronanbrowne commented on Jenkinsfile
> +@Library('corda-shared-build-pipeline-steps@CORE-19345-newSmConfig') _
Discussed with @jujoramos on a call, we will merge with this to minimize disruption, and a follow-up PR will immediately revert this back to 5.2

2024-02-06 16:51 UTC, ronanbrowne commented on .ci/e2eTests/Jenkinsfile
> +@Library('corda-shared-build-pipeline-steps@CORE-19345-newSmConfig') _
https://github.com/corda/corda-runtime-os/pull/5598#discussion_r1480232136

2024-02-06 16:52 UTC, ronanbrowne approved these changes
LGTM (blt)

2024-02-06 16:55 UTC, LWogan approved these changes

2024-02-06 16:56 UTC, mag1c-48 approved these changes
LGTM - following chat with @ronanbrowne

2024-02-06 17:31 UTC, merged