CORE-18641 Initial work for sandbox testing in isolation
corda/corda-runtime-os pull request #5600
Opened 2024-02-02 17:12 UTC by bpaunescu

- Added stress tests for Flow and Persistence sandboxes
- Added some test metrics
- Added utilities to facilitate metrics data consumption using Prometheus and Grafana

2024-02-06 13:16 UTC, ronanbrowne requested changes
Few queries on `applications/tools/metrics-webserver/build.gradle` i'll leave the *kt code to a platform engineer to review.

2024-02-06 13:16 UTC, ronanbrowne commented on applications/tools/metrics-webserver/build.gradle
> +        manifest {
Looks like the formatting is off there?

2024-02-06 13:16 UTC, ronanbrowne commented on applications/tools/metrics-webserver/build.gradle
> +tasks.named('jar', Jar) {
Is there any expectation for this Jar to be published externally to Maven Central as part of our release process or is the presumption a user will always build it if needed as described in readme.md

2024-02-09 10:54 UTC, bpaunescu commented on applications/tools/metrics-webserver/build.gradle
> +tasks.named('jar', Jar) {
There is no current plan to publish this anywhere. It's sufficient to build a jar locally or run it directly from Intellij.

2024-02-09 10:58 UTC, bpaunescu commented on applications/tools/metrics-webserver/build.gradle
> +        manifest {
Attempted to improve it.

2024-02-09 13:00 UTC, ronanbrowne approved these changes
LGTM re my comments

2024-02-09 15:53 UTC, kyriathar approved these changes
OK

2024-02-09 15:58 UTC, merged