CORE-19560: Ignore old and new key alias, rotate all keys which are not wrapped by default master wrapping key
corda/corda-runtime-os pull request #5616
Opened 2024-02-06 08:58 UTC by anien

Changes:
- Remove the references to old and new key alias. We now wrap all keys where parent_key_alias is not the default_master_wrapping_key. 
- Retrieve default_master_wrapping_key from the config and pass to Rekey and Rewrap processors.
- Changes are reflected only on crypto side, the values coming from rest worker are ignored. Rest worker changes will follow.
- Remove tests covering checks for old and new key alias.
- Update tests.

2024-02-06 12:00 UTC, anien commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/impl/KeyRotationRestResourceImpl.kt
> +        val deserializedValueOfOneRecord = unmanagedKeyStatusDeserializer.deserialize(records.first().value)
I had to remove the null check because newKeyAlias is currently null for the time being.

2024-02-06 18:12 UTC, simon-johnson-r3 requested changes

2024-02-06 18:12 UTC, simon-johnson-r3 commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/impl/KeyRotationRestResourceImpl.kt
> +        val deserializedValueOfOneRecord = unmanagedKeyStatusDeserializer.deserialize(records.first().value)
I don't quite understand this, the check is around `deserializedValueOfOneRecord` which still can't be null?

2024-02-06 18:12 UTC, simon-johnson-r3 commented on components/crypto/crypto-service-impl/src/main/kotlin/net/corda/crypto/service/impl/bus/CryptoRekeyBusProcessor.kt
> +            when (request.managedKey) {
is the indentation off here, or is this a github-ism?

2024-02-06 18:12 UTC, simon-johnson-r3 commented on components/crypto/crypto-service-impl/src/main/kotlin/net/corda/crypto/service/impl/bus/CryptoRekeyBusProcessor.kt
> +                KeyType.MANAGED -> {
same with indentation here

2024-02-06 18:12 UTC, simon-johnson-r3 commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/WrappingRepository.kt
> +    /**
Can we delete `findKeysWrappedByParentKey` now?

2024-02-06 18:12 UTC, simon-johnson-r3 commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/WrappingRepository.kt
> +    /**
Also I mention this in the class header docs

2024-02-06 18:12 UTC, simon-johnson-r3 commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/WrappingRepository.kt
> +     * Find all wrapping keys in the database which were NOT wrapped by a specific parent key. As noted above, if you run
it's actually noted above for `findKeysWrappedByParentKey` specifically

2024-02-06 18:44 UTC, anien commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/impl/KeyRotationRestResourceImpl.kt
> +        val deserializedValueOfOneRecord = unmanagedKeyStatusDeserializer.deserialize(records.first().value)
It literally got `deserializedValueOfOneRecord.newParentKeyAlias is null` error. So I think it checks each value individually.

2024-02-06 18:45 UTC, anien commented on components/crypto/crypto-service-impl/src/main/kotlin/net/corda/crypto/service/impl/bus/CryptoRekeyBusProcessor.kt
> +            when (request.managedKey) {
This might be cause by the merge where lots of indentation was happening. I will fix this.

2024-02-06 18:52 UTC, anien commented on components/crypto/crypto-service-impl/src/main/kotlin/net/corda/crypto/service/impl/bus/CryptoRekeyBusProcessor.kt
> +                KeyType.MANAGED -> {
Fixed

2024-02-06 18:56 UTC, anien commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/WrappingRepository.kt
> +    /**
You are right. This can be deleted. It's now only used in tests. Let me update those too.

2024-02-06 23:00 UTC, anien commented on components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/WrappingRepository.kt
> +     * Find all wrapping keys in the database which were NOT wrapped by a specific parent key. As noted above, if you run
As we now have only one function, I believe it's now correct.

2024-02-07 08:48 UTC, simon-johnson-r3 commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/impl/KeyRotationRestResourceImpl.kt
> +        val deserializedValueOfOneRecord = unmanagedKeyStatusDeserializer.deserialize(records.first().value)
The output from `checkNotNull` on a failure is fixed and doesn't mention any specifics of the type or value:
```
{ "Required value was null." }
```
so the error you were seeing must have been from something else?

This test passes for me
```
    @Test
    fun `null check`() {
        val status = UnmanagedKeyStatus()

        assertThat(status.newParentKeyAlias).isNull()

        val deserializedValueOfOneRecord =
            checkNotNull(status)

        deserializedValueOfOneRecord.hashCode()
    }
```

2024-02-07 08:50 UTC, simon-johnson-r3 approved these changes

2024-02-07 08:56 UTC, anien commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/impl/KeyRotationRestResourceImpl.kt
> +        val deserializedValueOfOneRecord = unmanagedKeyStatusDeserializer.deserialize(records.first().value)
Hm, probably it indeed come from something else. Let me check that in the next PR.

2024-02-07 08:57 UTC, merged