CORE-19563: Remove check that previous key rotation has finished
corda/corda-runtime-os pull request #5625
Opened 2024-02-06 13:39 UTC by malachyb

This PR removes the check that a previous key rotation had finished in both unmanaged and managed key rotations. Additionally, it adds a check that the state manager is active, which would previously throw an error as a side effect of checking the previous rotation status. Technically, the check will throw the error from trying to access `stateManager.isRunning`, but I have written the code to throw the same error that is thrown by the failed attempt at accessing it.

2024-02-06 15:56 UTC, simon-johnson-r3 requested changes

2024-02-06 15:56 UTC, simon-johnson-r3 commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/impl/KeyRotationRestResourceImpl.kt
> +        if (!stateManager.isRunning) {
a more idiomatic and logically equivalent Kotlin version is:
`check(stateManager.isRunning) { "State manager for key rotation is not initialised" }`

2024-02-06 15:56 UTC, simon-johnson-r3 commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/impl/KeyRotationRestResourceImpl.kt
> +        if (!stateManager.isRunning) {
same here

2024-02-06 15:56 UTC, simon-johnson-r3 commented on components/crypto/crypto-service-impl/src/main/kotlin/net/corda/crypto/service/impl/bus/CryptoRekeyBusProcessor.kt
> +        try {
This is picking up a programming error, so it's unusual to suppress it like this. Actually now I look at the code, why does any of it work like this?

The problem seems to be in `CryptoProcessorImpl`, because state manager requires the boot config, but we should not have let that propagate all the way down here, just to throw/ignore it. It's not part of this ticket, but it might be better if you want to handle this, to handle it up there and remove the nullability of state manager everywhere else.

2024-02-06 15:56 UTC, simon-johnson-r3 commented on components/crypto/crypto-service-impl/src/test/kotlin/net/corda/crypto/service/impl/bus/CryptoRekeyBusProcessorTests.kt
> +        `when`(stateManager.findByMetadataMatchingAll(any())).thenReturn(simulatedExistingStateMap)
Mockito for Kotlin provides the `whenever` function so you don't have to wrap `when` like this

2024-02-08 13:43 UTC, anien commented on components/crypto/crypto-service-impl/src/main/kotlin/net/corda/crypto/service/impl/bus/CryptoRekeyBusProcessor.kt
> +            "State manager for key rotation is not initialised."
I would move this to onNext function at the beginning because we shouldn't really start key rotation when stateManager is not running.

2024-02-08 14:07 UTC, anien commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/impl/KeyRotationRestResourceImpl.kt
> +        }
I think we should move this just before `when` so we check it state manager is initialized for both unmanaged and managed key rotation

2024-02-08 14:09 UTC, anien commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/impl/KeyRotationRestResourceImpl.kt
> +            "State manager for key rotation is not initialised."
Looks like a merge issue. We now check if `tenantId.isEmpty` twice. Let's keep this one here and remove the one under `else` branch just below here.

2024-02-08 14:13 UTC, anien commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/impl/KeyRotationRestResourceImpl.kt
> +            listOf(
This looks like indentation issue after merge.

2024-02-08 14:18 UTC, anien commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/impl/KeyRotationRestResourceImpl.kt
> +            "State manager for key rotation is not initialised."
Also, I would move `check(::stateManager.isInitialized)` just under `tryWithExceptionHandling(logger, "start key rotation") {` so we have checks of the internal services first, then we check for input parameter (tenant is empty). 

Not sure if it's possible to move `check(::stateManager.isInitialized)` under `tryWithExceptionHandling`? to have both checks for kafka publisher and state manager together? I am not too fussy about this though, it would just look nice.

2024-02-08 14:20 UTC, anien commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/impl/KeyRotationRestResourceImpl.kt
> +        )
Merge issue. This code should have been removed.

2024-02-08 18:32 UTC, anien commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/impl/KeyRotationRestResourceImpl.kt
> +        }
We now have inconsistency in exception type thrown between `getKeyRotationStatus` and `startKeyRotation` when state manager is not initialized. I would use `tryWithExceptionHandling` in both cases as this was suggested by rest team some time ago. But let's do that as a follow up PR.

2024-02-08 18:33 UTC, anien approved these changes
One small comment for a follow up PR, otherwise looks good to me!

2024-02-09 09:37 UTC, simon-johnson-r3 commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/impl/KeyRotationRestResourceImpl.kt
> +        stateManager = stateManagerFactory.create(stateManagerConfig, StateManagerConfig.StateType.KEY_ROTATION)
it should really be impossible to replace the state manager like this, but this is an extension of the problem of it being a var - if you actually replaced the state manager nothing would work correctly

let's sort this out in that other ticket you raised though

2024-02-09 09:52 UTC, simon-johnson-r3 approved these changes

2024-02-09 09:55 UTC, merged