CORE 19588: warn if class not found
corda/corda-runtime-os pull request #5629
Opened 2024-02-06 15:34 UTC by dickon

2024-02-06 16:19 UTC, rick-r3 requested changes

2024-02-06 16:19 UTC, rick-r3 commented on libs/serialization/serialization-amqp/src/main/kotlin/net/corda/internal/serialization/model/TypeLoader.kt
> +                logger.warn("ClassNotFound ${ex.message} loading type for looking for ${identifier.prettyPrint()}")
You should include `ex` as second arg to `warn` so we get stack trace.

2024-02-06 20:09 UTC, rick-r3 commented on libs/serialization/serialization-amqp/src/main/kotlin/net/corda/internal/serialization/model/TypeLoader.kt
> +                logger.warn("ClassNotFound ${ex.message} loading type for looking for ${identifier.prettyPrint()}")
I've tweaked this line to do so

2024-02-07 07:01 UTC, rick-r3 approved these changes

2024-02-07 08:27 UTC, driessamyn approved these changes

2024-02-07 08:28 UTC, driessamyn approved these changes

2024-02-07 08:58 UTC, dickon commented on libs/serialization/serialization-amqp/src/main/kotlin/net/corda/internal/serialization/model/TypeLoader.kt
> +                logger.warn("ClassNotFound ${ex.message} loading type for looking for ${identifier.prettyPrint()}")
Thanks_

2024-02-07 09:01 UTC, merged