CORE-19561: Update REST side of key rotation
corda/corda-runtime-os pull request #5646
Opened 2024-02-07 12:39 UTC by anien

Changes:
- Merge POST call to start key rotation for both master wrapping key and vNode wrapping key rotation
- Merge GET call for key rotation status for both types of rotations
- Update paths for POST and GET call to reflect only one of each call is now present
- Use one more generic response for both POST and GET calls. Remove unneeded data class.
- Remove old and new key alias from start key rotation POST call. This is not needed anymore as master wrapping key rotation now checks the default master key alias flag.
- Update tests

2024-02-07 13:09 UTC, vkolomeyko submitted a review, later dismissed
LGTM from @corda/rest

2024-02-07 14:19 UTC, simon-johnson-r3 requested changes

2024-02-07 14:19 UTC, simon-johnson-r3 commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/KeyRotationRestResource.kt
> +        @RestPathParameter(description = "UUID of the virtual node or 'master' for master wrapping key rotation status.")
...or cluster crypto tenant from the predetermined list

2024-02-07 14:19 UTC, simon-johnson-r3 commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/KeyRotationRestResource.kt
> +     * Initiates the master wrapping key or vNode wrapping key rotation process.
or cluster crypto tenant

2024-02-07 14:19 UTC, simon-johnson-r3 commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/KeyRotationRestResource.kt
> +     * @return Key rotation response where the requestId is the unique ID for the key rotation start request.
Am I correct in thinking there is nothing you can do with this, except perhaps compare it with entries in the logs? I wonder whether we should address that point here, to stop people looking for some other api?

2024-02-07 14:19 UTC, simon-johnson-r3 commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/KeyRotationRestResource.kt
> +        description = "This method enables to rotate all wrapping keys for tenantId or master wrapping key.",
or cluster crypto tenant (also response)

2024-02-07 14:19 UTC, simon-johnson-r3 commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/impl/KeyRotationRestResourceImpl.kt
> +        return if (tenantId == "master") {
can we define "master" somewhere?

2024-02-07 14:19 UTC, simon-johnson-r3 commented on components/crypto/crypto-rest/src/test/kotlin/net/corda/crypto/rest/impl/KeyRotationRestResourceTest.kt
> +    // We need two wrapping key aliases - defaultMasterKeyAlias and anotherMasterKeyAlias
minor but it looks like `anotherMasterKeyAlias` is trying to describe a variable here

2024-02-07 14:19 UTC, simon-johnson-r3 commented on processors/rest-processor/src/integrationTest/resources/swaggerBaseline-v5_2.json
> +          "description" : "UUID of the virtual node or 'master' for master wrapping key rotation status.",
or crypto cluster tenant (all of these)

2024-02-07 14:33 UTC, anien commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/KeyRotationRestResource.kt
> +     * @return Key rotation response where the requestId is the unique ID for the key rotation start request.
Correct. We use that requestId when submitting kafka message from rest to crypto worker, but we disregard it afterwards. We thought about possibly using it configurable for users at some point. But didn't get that far.
It's easy to remove it and just acknowledge the request and don't return anything. Shall we do that?

2024-02-07 14:37 UTC, anien commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/impl/KeyRotationRestResourceImpl.kt
> +        return if (tenantId == "master") {
Will do.

2024-02-07 14:38 UTC, anien commented on components/crypto/crypto-rest/src/test/kotlin/net/corda/crypto/rest/impl/KeyRotationRestResourceTest.kt
> +    // We need two wrapping key aliases - defaultMasterKeyAlias and anotherMasterKeyAlias
I did renaming twice and forgot to rename the variable in the comment :)

2024-02-07 16:12 UTC, anien commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/KeyRotationRestResource.kt
> +        @RestPathParameter(description = "UUID of the virtual node or 'master' for master wrapping key rotation status.")
Changed.

2024-02-07 16:13 UTC, anien commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/KeyRotationRestResource.kt
> +     * Initiates the master wrapping key or vNode wrapping key rotation process.
Added.

2024-02-07 16:13 UTC, anien commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/KeyRotationRestResource.kt
> +     * @return Key rotation response where the requestId is the unique ID for the key rotation start request.
I have kept it for now, but we can simply remove it in a separate PR.

2024-02-07 16:13 UTC, anien commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/KeyRotationRestResource.kt
> +        description = "This method enables to rotate all wrapping keys for tenantId or master wrapping key.",
Done.

2024-02-07 16:13 UTC, anien commented on processors/rest-processor/src/integrationTest/resources/swaggerBaseline-v5_2.json
> +          "description" : "UUID of the virtual node or 'master' for master wrapping key rotation status.",
Fixed.

2024-02-07 16:50 UTC, simon-johnson-r3 approved these changes

2024-02-08 11:27 UTC, vkolomeyko approved these changes
LGTM

2024-02-08 11:30 UTC, merged