ES-1795 Update JenkinsfileCommentRebuild to remove duplicate comment builds
corda/corda-runtime-os pull request #5650
Opened 2024-02-07 14:22 UTC by jacob-scott3141

Uses the new `com.r3.build.BuildControl.killAnyBuildsInQueue`

2024-02-07 14:22 UTC, jacob-scott3141 commented
build e2e

2024-02-07 14:39 UTC, ronanbrowne commented
build e2e

2024-02-07 14:41 UTC, ronanbrowne commented
^build e2e$

2024-02-07 14:42 UTC, jacob-scott3141 commented
build e2e

2024-02-07 15:13 UTC, jacob-scott3141 commented
build e2e

2024-02-07 15:16 UTC, jacob-scott3141 commented
build e2e

2024-02-07 15:19 UTC, jacob-scott3141 commented
build e2e

2024-02-07 15:24 UTC, jacob-scott3141 commented
build e2e

2024-02-07 16:09 UTC, jacob-scott3141 commented
build e2e

2024-02-07 16:16 UTC, jacob-scott3141 commented
build e2e

2024-02-07 16:23 UTC, jacob-scott3141 commented
build e2e

2024-02-07 16:23 UTC, jacob-scott3141 commented
build e2e

2024-02-07 16:24 UTC, jacob-scott3141 commented
build e2e

2024-02-07 16:28 UTC, jacob-scott3141 commented
build e2e

2024-02-07 16:29 UTC, jacob-scott3141 commented
build e2e

2024-02-07 16:48 UTC, jacob-scott3141 commented
build e2e

2024-02-08 11:41 UTC, jacob-scott3141 commented
build e2e

2024-02-08 11:46 UTC, jacob-scott3141 commented
build e2e

2024-02-08 11:53 UTC, jacob-scott3141 commented
build e2e

2024-02-08 12:03 UTC, jacob-scott3141 commented
build e2e

2024-02-08 12:07 UTC, jacob-scott3141 commented
build e2e

2024-02-08 12:08 UTC, jacob-scott3141 commented
build e2e

2024-02-08 12:16 UTC, jacob-scott3141 commented
build e2e

2024-02-08 15:30 UTC, ronanbrowne requested changes

2024-02-08 15:30 UTC, ronanbrowne commented on .ci/JenkinsfileCommentRebuild
> +@Library('corda-shared-build-pipeline-steps@ES-1795') _
```suggestion
@Library('corda-shared-build-pipeline-steps@5.2) _
```

2024-02-08 15:32 UTC, mag1c-48 approved these changes
Ronan beat me to the request changes - so now here;s a LGTM :P

2024-02-08 15:33 UTC, ronanbrowne approved these changes

2024-02-08 16:30 UTC, jacob-scott3141 commented
build e2e

2024-02-08 16:58 UTC, merged