CORE-19621: Rename createdTimestamp to rotationInitiatedTimestamp
corda/corda-runtime-os pull request #5725
Opened 2024-02-19 13:32 UTC by malachyb

2024-02-20 12:13 UTC, simon-johnson-r3 requested changes

2024-02-20 12:13 UTC, simon-johnson-r3 commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/response/KeyRotationStatusResponse.kt
> + * @param rotationInitiatedTimestamp Timestamp of then the key rotation request was received.
this text (which you didn't write) doesn't make sense, we should take the opportunity to fix it

2024-02-20 13:43 UTC, malachyb commented on components/crypto/crypto-rest/src/main/kotlin/net/corda/crypto/rest/response/KeyRotationStatusResponse.kt
> + * @param rotationInitiatedTimestamp Timestamp of then the key rotation request was received.
I'm guessing it should say "when" instead of "then"? I think that would fix the sentence and make it make more sense.

2024-02-21 11:39 UTC, simon-johnson-r3 approved these changes

2024-02-21 11:39 UTC, merged