CORE-19933 Add test for verifying key aliases are unique
corda/corda-runtime-os pull request #5836
Opened 2024-03-07 17:07 UTC by bpaunescu

2024-03-08 09:22 UTC, simon-johnson-r3 requested changes

2024-03-08 09:22 UTC, simon-johnson-r3 commented on components/crypto/crypto-softhsm-impl/src/integrationTest/kotlin/repository/SigningRepositoryTest.kt
> +        assertThat(errorMessage).isEqualTo("org.hibernate.exception.ConstraintViolationException: could not execute statement")
this would be better as `assertThrows<ConstraintViolationException>(repo.savePrivateKey(ctx2))`
the problem with checking the error message is it could change under us on a Hibernate upgrade
also, here the error message isn't given you any more specific information the type of exception isn't giving you already

2024-03-08 09:34 UTC, driessamyn commented on components/crypto/crypto-softhsm-impl/src/integrationTest/kotlin/repository/SigningRepositoryTest.kt
> +        assertThat(errorMessage).isEqualTo("org.hibernate.exception.ConstraintViolationException: could not execute statement")
This test will fail when run against HSQL (locally and in some of the build pipelines).

2024-03-11 09:53 UTC, bpaunescu commented on components/crypto/crypto-softhsm-impl/src/integrationTest/kotlin/repository/SigningRepositoryTest.kt
> +        assertThat(errorMessage).isEqualTo("org.hibernate.exception.ConstraintViolationException: could not execute statement")
@driessamyn why would it fail? The test doesn't use anything that the other tests don't use.

2024-03-11 14:30 UTC, bpaunescu commented on components/crypto/crypto-softhsm-impl/src/integrationTest/kotlin/repository/SigningRepositoryTest.kt
> +        assertThat(errorMessage).isEqualTo("org.hibernate.exception.ConstraintViolationException: could not execute statement")
Updated assert to expect `SQLIntegrityConstraintViolationException`

2024-03-11 14:39 UTC, bpaunescu commented
Closing and re-creating PR. Since the API fix went in, the pipelines are not picking up latest version.

2024-03-11 14:39 UTC, closed without merging