CORE-3378: Corda cli plugin to upload cpi
corda/corda-runtime-os pull request #5848
Opened 2024-03-08 16:11 UTC by ShYogesh-R3

2024-03-12 10:35 UTC, davidcurrie commented
Should this be targeting 5.3 rather than 5.2? If so, although I appreciate there's not a lot of logic in this plugin, we're in the process of trying to push the implementation of plugins down into the new Corda SDK. In this case, that would be using the [CpiUploader](https://github.com/corda/corda-runtime-os/blob/release/os/5.3/libs/corda-sdk/src/main/kotlin/net/corda/sdk/packaging/CpiUploader.kt) class.

2024-03-12 10:48 UTC, tlawson3 reviewed
[The comment on the ticket](https://r3-cev.atlassian.net/browse/CORE-3378?focusedCommentId=294289) suggests this should be done via the SDK rather than have the CLI plugin use the rest resource directly in the run function

2024-03-12 10:48 UTC, tlawson3 commented on tools/plugins/cpi-upload/src/main/kotlin/net/corda/cli/plugins/cpiupload/commands/CPIUpload.kt
> +                    while (this.status(cpiUploadResult).status != "OK") {
infinite loop?

2024-03-12 10:52 UTC, vkolomeyko reviewed
Overall looks sensible, few comments posted.

2024-03-12 10:52 UTC, vkolomeyko commented on settings.gradle
> +include 'tools:plugins:cpi-upload'
Could we also change `CODEOWNERS` file to list REST team as an owner for this new module?

2024-03-12 10:52 UTC, vkolomeyko commented on tools/plugins/cpi-upload/build.gradle
> +    implementation "org.liquibase:liquibase-core:$liquibaseVersion"
Do we need LB for this plugin?

2024-03-12 10:52 UTC, vkolomeyko commented on tools/plugins/cpi-upload/build.gradle
> +        implementation(libs.snakeyaml)  {
This can also be removed, probably.

2024-03-12 10:52 UTC, vkolomeyko commented on tools/plugins/cpi-upload/build.gradle
> +    runtimeOnly libs.postgresql.jdbc
So as dependency on Postgres, I think.

2024-03-12 10:52 UTC, vkolomeyko commented on tools/plugins/cpi-upload/src/main/kotlin/net/corda/cli/plugins/cpiupload/CPIUploadCliPlugin.kt
> +        logger.debug("starting cpi upload plugin")
```suggestion
        logger.debug { "starting cpi upload plugin" }
```

2024-03-12 10:52 UTC, vkolomeyko commented on tools/plugins/cpi-upload/src/main/kotlin/net/corda/cli/plugins/cpiupload/CPIUploadCliPlugin.kt
> +        logger.debug("stopping cpi upload plugin")
```suggestion
        logger.debug { "stopping cpi upload plugin" }
```

2024-03-12 10:52 UTC, vkolomeyko commented on tools/plugins/cpi-upload/src/main/kotlin/net/corda/cli/plugins/cpiupload/commands/CPIUpload.kt
> +                    println("File type must be .cpi")
Instead of `println` it is best to use logger:
```
val sysOut: Logger = LoggerFactory.getLogger("SystemOut")
```
That way output will be sent to standard output as well as to the internal log file with a timestamp.

2024-03-12 10:52 UTC, vkolomeyko commented on tools/plugins/cpi-upload/src/main/kotlin/net/corda/cli/plugins/cpiupload/commands/CPIUpload.kt
> +                    logger.error(e.stackTrace.contentDeepToString())
```suggestion
                    logger.error("Unexpected error during CPI upload", e)
```

2024-03-12 10:52 UTC, vkolomeyko commented on tools/plugins/cpi-upload/src/main/kotlin/net/corda/cli/plugins/cpiupload/commands/CPIUpload.kt
> +                    return
It would probably make sense to allow the exception to propagate such that the CLI command exits with non-zero error code.

2024-03-12 11:01 UTC, tlawson3 commented
Appreciate it may be difficult to do, but can a `pluginSmokeTest` be created to cover this functionality?

2024-03-12 15:34 UTC, vkolomeyko commented on tools/plugins/cpi-upload/src/main/kotlin/net/corda/cli/plugins/cpiupload/commands/CPIUpload.kt
> +            return
```suggestion
            System.exit(1)
```

2024-03-12 15:34 UTC, vkolomeyko commented on tools/plugins/cpi-upload/src/main/kotlin/net/corda/cli/plugins/cpiupload/commands/CPIUpload.kt
> +            return
```suggestion
            System.exit(2)
```

2024-03-12 15:34 UTC, vkolomeyko commented on tools/plugins/cpi-upload/src/main/kotlin/net/corda/cli/plugins/cpiupload/commands/CPIUpload.kt
> +            return
```suggestion
            return System.exit(3)
```

2024-03-12 15:45 UTC, vkolomeyko commented
> Appreciate it may be difficult to do, but can a `pluginSmokeTest` be created to cover this functionality?

For CLI we tend to perform testing in E2E repo like [so](https://github.com/corda/corda-e2e-tests/blob/release/5.3/e2etest/src/e2eTest/kotlin/net/corda/e2etest/virtualnode/FlowExecutorE2eTest.kt). This ensures that:
1. CLI plugin was assembled and packaged as it should with no conflicts with existing commands;
2. New CLI plugin is available in the installer;
3. When CLI is run, In case of invalid arguments non-zero exit code returned as expected;
4. StdOut/StdErr can also be validated as necessary;
5. And most importantly once CLI successfully completed it indeed had a desired effect on the cluster.
For this functionality this might be that vNode can be successfully created from the CPI we have just uploaded.

2024-03-12 15:49 UTC, vkolomeyko commented on tools/plugins/cpi-upload/src/main/kotlin/net/corda/cli/plugins/cpiupload/commands/CPIUpload.kt
> +        if (cpi.extension != "cpi") {
```suggestion
        if (cpi.extension.toLower() != "cpi") {
```

2024-03-12 16:24 UTC, vkolomeyko approved these changes, later dismissed
LGTM

But let's have an E2E baseline PR ready, such that when we merge this PR, we will not leave E2E tests broken for too long.

2024-03-12 16:26 UTC, ShYogesh-R3 commented
> LGTM
> 
> But let's have an E2E baseline PR ready, such that when we merge this PR, we will not leave E2E tests broken for too long.

PR for changes in corda-e2e-tests repo - https://github.com/corda/corda-e2e-tests/pull/502

2024-03-12 16:28 UTC, davidcurrie requested changes
As per my earlier comment, I'd like to see this using the SDK's `CpiUploader`.

2024-03-12 16:31 UTC, ShYogesh-R3 commented
> As per my earlier comment, I'd like to see this using the SDK's `CpiUploader`.

Hi @davidcurrie , we are making use of SDK's `CpiUploader` only, see - https://github.com/corda/corda-runtime-os/pull/5848/files#diff-15bc9e828d728743b245d3efde7b4150af0bb0bb1a5437187fadc65345c5c327R59

2024-03-12 16:34 UTC, vkolomeyko reviewed
Few final touches

2024-03-12 16:34 UTC, vkolomeyko commented on tools/plugins/cpi-upload/src/main/kotlin/net/corda/cli/plugins/cpiupload/commands/CPIUpload.kt
> +        description = ["polls for result"]
```suggestion
        description = ["wait for confirmation that CPI been accepted by the cluster"]
```

2024-03-12 16:34 UTC, vkolomeyko commented on tools/plugins/cpi-upload/src/main/kotlin/net/corda/cli/plugins/cpiupload/commands/CPIUpload.kt
> +        sysOut.info("CPI Successfully Uploaded and applied. ")
```suggestion
        sysOut.info("CPI Successfully Uploaded and applied.")
```

2024-03-12 16:38 UTC, davidcurrie commented
> > As per my earlier comment, I'd like to see this using the SDK's `CpiUploader`.
> 
> Hi @davidcurrie , we are making use of SDK's `CpiUploader` only, see - https://github.com/corda/corda-runtime-os/pull/5848/files#diff-15bc9e828d728743b245d3efde7b4150af0bb0bb1a5437187fadc65345c5c327R59

Apologies - not sure what happened there. I must have been looking at an out-of-date diff...

2024-03-12 16:48 UTC, davidcurrie requested changes

2024-03-12 16:48 UTC, davidcurrie commented on tools/plugins/cpi-upload/src/main/kotlin/net/corda/cli/plugins/cpiupload/commands/CPIUpload.kt
> +        val sysOut: Logger = LoggerFactory.getLogger("SystemOut")
Is this a convention that we've used elsewhere? Having a logger called `SystemOut`?

2024-03-12 16:48 UTC, davidcurrie commented on tools/plugins/cpi-upload/src/main/kotlin/net/corda/cli/plugins/cpiupload/commands/CPIUpload.kt
> +        val restClient = createRestClient(
Could this reuse the original client?

2024-03-12 16:48 UTC, davidcurrie commented on tools/plugins/cpi-upload/src/main/kotlin/net/corda/cli/plugins/cpiupload/commands/CPIUpload.kt
> +        sysOut.info("CPI Successfully Uploaded and applied.")
nit:
```suggestion
        sysOut.info("CPI successfully uploaded and applied.")
```
Although what does "and applied" mean?

2024-03-12 16:48 UTC, davidcurrie commented on tools/plugins/cpi-upload/src/main/kotlin/net/corda/cli/plugins/cpiupload/commands/CPIUpload.kt
> +            sysOut.info(cpiUploadResult)
Would it be more useful to say what it is that's being output here?

2024-03-12 16:48 UTC, davidcurrie commented on tools/plugins/cpi-upload/src/main/kotlin/net/corda/cli/plugins/cpiupload/commands/CPIUpload.kt
> +        sysOut.info("CPI Successfully Uploaded and applied.")
And would it be useful if the CPI checksum was included in the output? (Better still if there was a quiet mode that just output this checksum for use in subsequent commands.)

2024-03-12 17:13 UTC, vkolomeyko commented on tools/plugins/cpi-upload/src/main/kotlin/net/corda/cli/plugins/cpiupload/commands/CPIUpload.kt
> +        val sysOut: Logger = LoggerFactory.getLogger("SystemOut")
yes, it is a special logger which outputs to the log file (with timestamp) as well as to standard output (without timestamp). Likewise there is a special logger `SystemErr`.

2024-03-13 08:09 UTC, wzur-r3 approved these changes, later dismissed
LGTM changes for Gradle configuration and CODEOWNERS

2024-03-13 09:10 UTC, vkolomeyko approved these changes, later dismissed
LGTM

2024-03-13 09:59 UTC, tlawson3 commented
> > Appreciate it may be difficult to do, but can a `pluginSmokeTest` be created to cover this functionality?
> 
> For CLI we tend to perform testing in E2E repo like [so](https://github.com/corda/corda-e2e-tests/blob/release/5.3/e2etest/src/e2eTest/kotlin/net/corda/e2etest/virtualnode/FlowExecutorE2eTest.kt). This ensures that:
> 
> 1. CLI plugin was assembled and packaged as it should with no conflicts with existing commands;
> 2. New CLI plugin is available in the installer;
> 3. When CLI is run, In case of invalid arguments non-zero exit code returned as expected;
> 4. StdOut/StdErr can also be validated as necessary;
> 5. And most importantly once CLI successfully completed it indeed had a desired effect on the cluster.
>    For this functionality this might be that vNode can be successfully created from the CPI we have just uploaded.

I don't see any tests written in PR https://github.com/corda/corda-e2e-tests/pull/502/files yet
Are they still coming?

2024-03-13 10:42 UTC, vkolomeyko commented
> I don't see any tests written in PR https://github.com/corda/corda-e2e-tests/pull/502/files yet Are they still coming?

Yes, this PR is just fixing CLI baseline which will be an immediate issue once this PR is fixed.
There will be a separate PR to E2E test functionality introduced on this PR.

2024-03-13 13:49 UTC, ShYogesh-R3 commented
Hi @davidcurrie , Can I get the required approval, Please!!

2024-03-13 17:30 UTC, davidcurrie requested changes

2024-03-13 17:30 UTC, davidcurrie commented on tools/plugins/cpi-upload/src/main/kotlin/net/corda/cli/plugins/cpiupload/commands/CPIUpload.kt
> +    private lateinit var restClient: RestClient<CpiUploadRestResource>
This smells a bit to me given it requires `run()` to be invoked before `pollForOKStatus()`. Can you go back to creating the `RestClient` in `run` but pass it as an argument to `pollForOKStatus`?

2024-03-13 17:30 UTC, davidcurrie commented on tools/plugins/cpi-upload/src/main/kotlin/net/corda/cli/plugins/cpiupload/commands/CPIUpload.kt
> +        try {
As I'm back looking at this again... rather than the `lateinit`, just use the try-catch as an expression i.e.
```
val cpiUploadResult = try {
   ...
   CpiUploader().uploadCPI(...).id
} catch ...
```

2024-03-14 07:46 UTC, ShYogesh-R3 commented on tools/plugins/cpi-upload/src/main/kotlin/net/corda/cli/plugins/cpiupload/commands/CPIUpload.kt
> +    private lateinit var restClient: RestClient<CpiUploadRestResource>
Done

2024-03-14 07:46 UTC, ShYogesh-R3 commented on tools/plugins/cpi-upload/src/main/kotlin/net/corda/cli/plugins/cpiupload/commands/CPIUpload.kt
> +        try {
Done

2024-03-14 08:47 UTC, vkolomeyko approved these changes
LGTM

2024-03-14 09:03 UTC, davidcurrie approved these changes
Thanks for the updates @ShYogesh-R3. LGTM

2024-03-14 09:26 UTC, merged