CORE-19326 -  Extra trace tags can be added using CLI
corda/corda-runtime-os pull request #5868
Opened 2024-03-12 17:14 UTC by filipesoliveira

2024-03-14 14:32 UTC, davidcurrie requested changes

2024-03-14 14:32 UTC, davidcurrie commented on charts/corda/values.yaml
> +      - "--trace-tags=namespace=$(K8S_NAMESPACE):pod=$(K8S_POD_NAME):node_name=$(K8S_NODE_NAME):container=$(K8_CONTAINER_NAME)"
We shouldn't use `extraArgs` for out-of-the-box functionality. (It was only added to facilitate tweaking config as part of testing.) This should be specified in the `corda.worker` function.

2024-03-14 14:32 UTC, davidcurrie commented on applications/workers/worker-common/src/main/kotlin/net/corda/applications/workers/workercommon/DefaultWorkerParams.kt
> +    @Option(names = ["--trace-tags"], split = ":", description = ["Trace tags that are applying to the log messages " +
Any particular reason for using `:` here?

2024-03-14 14:32 UTC, davidcurrie commented on applications/workers/worker-common/src/main/kotlin/net/corda/applications/workers/workercommon/DefaultWorkerParams.kt
> +            "which can be latter used to filter logs."])
```suggestion
    @Option(names = ["--trace-tags"], split = ":", description = ["Tags that are applied to trace spans " +
            "which can later be used to filter traces."])
```

2024-03-14 14:34 UTC, filipesoliveira commented on applications/workers/worker-common/src/main/kotlin/net/corda/applications/workers/workercommon/DefaultWorkerParams.kt
> +    @Option(names = ["--trace-tags"], split = ":", description = ["Trace tags that are applying to the log messages " +
I am using the colon to separate the different tags. Would you like to use a different character instead?

2024-03-14 14:38 UTC, davidcurrie commented on applications/workers/worker-common/src/main/kotlin/net/corda/applications/workers/workercommon/DefaultWorkerParams.kt
> +    @Option(names = ["--trace-tags"], split = ":", description = ["Trace tags that are applying to the log messages " +
What happens for other maps already in existence as CLI arguments? Do they just assume that the argument is specified multiple times?

2024-03-14 14:52 UTC, filipesoliveira commented on charts/corda/values.yaml
> +      - "--trace-tags=namespace=$(K8S_NAMESPACE):pod=$(K8S_POD_NAME):node_name=$(K8S_NODE_NAME):container=$(K8_CONTAINER_NAME)"
The code has been updated taking into account this comment.

2024-03-14 14:59 UTC, filipesoliveira commented on applications/workers/worker-common/src/main/kotlin/net/corda/applications/workers/workercommon/DefaultWorkerParams.kt
> +    @Option(names = ["--trace-tags"], split = ":", description = ["Trace tags that are applying to the log messages " +
Yes, I am assuming that people will duplicate the arguments for the other maps.

2024-03-14 15:02 UTC, filipesoliveira commented on applications/workers/worker-common/src/main/kotlin/net/corda/applications/workers/workercommon/DefaultWorkerParams.kt
> +    @Option(names = ["--trace-tags"], split = ":", description = ["Trace tags that are applying to the log messages " +
Here is an example:
![image](https://github.com/corda/corda-runtime-os/assets/6329837/54fe4c53-314b-457f-a4a9-32f32c5fc0c6)

2024-03-15 12:15 UTC, davidcurrie commented on charts/corda/values.yaml
> +  tags: "namespace=$(K8S_NAMESPACE):pod=$(K8S_POD_NAME):node_name=$(K8S_NODE_NAME):container=$(K8_CONTAINER_NAME)"
If this is to be exposed in the `values.yaml` (and I'm not convinced it necessarily needs to be), then I would prefer it to be in a more YAML-native format e.g.
```
    tags:
      namespace: "$(K8S_NAMESPACE)"
      pod: "$(K8S_POD_NAME)"
      node_name: "$(K8S_NODE_NAME)"
      container: "$(K8_CONTAINER_NAME)"
```

2024-03-15 12:15 UTC, davidcurrie commented on applications/workers/worker-common/src/main/kotlin/net/corda/applications/workers/workercommon/DefaultWorkerParams.kt
> +    @Option(names = ["--trace-tags"], split = ":", description = ["Tags that are applied to trace spans " +
What was the answer to the question about how other map-based CLI parameters work without specifying `split`?

2024-03-15 14:12 UTC, filipesoliveira commented on applications/workers/worker-common/src/main/kotlin/net/corda/applications/workers/workercommon/DefaultWorkerParams.kt
> +    @Option(names = ["--trace-tags"], split = ":", description = ["Tags that are applied to trace spans " +
From what I found, the arguments are being duplicated. This is an example: https://github.com/corda/corda-runtime-os/pull/5868#discussion_r1525033660.

2024-03-15 14:19 UTC, filipesoliveira commented on charts/corda/values.yaml
> +  tags: "namespace=$(K8S_NAMESPACE):pod=$(K8S_POD_NAME):node_name=$(K8S_NODE_NAME):container=$(K8_CONTAINER_NAME)"
I don't have a strong opinion where the configuration should live. I can still move this change to the `workers.yaml` as you previously suggested.

I made these changes in the `values.yaml` file to keep the tracing configuration in one place and help people find it when necessary. Again, I don't mind going for the approach that was initially suggested if that is the preference. Please let me know which option you prefer.

2024-03-15 14:19 UTC, davidcurrie commented on applications/workers/worker-common/src/main/kotlin/net/corda/applications/workers/workercommon/DefaultWorkerParams.kt
> +    @Option(names = ["--trace-tags"], split = ":", description = ["Trace tags that are applying to the log messages " +
Is there a good reason to do something different here?

2024-03-15 14:24 UTC, filipesoliveira commented on applications/workers/worker-common/src/main/kotlin/net/corda/applications/workers/workercommon/DefaultWorkerParams.kt
> +    @Option(names = ["--trace-tags"], split = ":", description = ["Trace tags that are applying to the log messages " +
The only reason is to make the command shorter.  For testing, I preferred the colon separated values. But if that is not a concerned in practical terms since the script is auto-generated, I can revert to the default strategy.

2024-03-15 14:35 UTC, filipesoliveira commented on charts/corda/values.yaml
> +  tags: "namespace=$(K8S_NAMESPACE):pod=$(K8S_POD_NAME):node_name=$(K8S_NODE_NAME):container=$(K8_CONTAINER_NAME)"
This is how it looks like after the change:
![image](https://github.com/corda/corda-runtime-os/assets/6329837/56dd3538-047d-48c8-8254-cfb984f14d24)

2024-03-15 14:36 UTC, filipesoliveira commented on applications/workers/worker-common/src/main/kotlin/net/corda/applications/workers/workercommon/DefaultWorkerParams.kt
> +    @Option(names = ["--trace-tags"], split = ":", description = ["Trace tags that are applying to the log messages " +
This is how it looks like after the change:
![image](https://github.com/corda/corda-runtime-os/assets/6329837/4847a012-5336-4782-8d4b-cdef48921a6e)

2024-03-15 14:48 UTC, filipesoliveira commented on charts/corda/values.yaml
> +  tags: "namespace=$(K8S_NAMESPACE):pod=$(K8S_POD_NAME):node_name=$(K8S_NODE_NAME):container=$(K8_CONTAINER_NAME)"
I went with the initial suggestion of making the changes on the `workers.yaml` file.

2024-03-15 17:59 UTC, davidcurrie commented on charts/corda/templates/workers.yaml
> +  ( dict "additionalWorkerArgs" ( list "--hsm-id=SOFT" "--trace-tag=namespace=$(K8S_NAMESPACE)" "--trace-tag=pod=$(K8S_POD_NAME)" "--trace-tag=node_name=$(K8S_NODE_NAME)" "--trace-tag=container=$(K8_
Nearly there! Given these are present on all workers, rather than using `additionalWorkerArgs`, they should just be inlined in `corda.worker` (where you previously had your `if $.Values.tracing.tags`).

2024-03-19 09:31 UTC, davidcurrie submitted a review, later dismissed
We're into the nice-to-haves now, so up to you whether you update again. Could you update the PR description though to match what was eventually implemented?

2024-03-19 09:31 UTC, davidcurrie commented on charts/corda-lib/templates/_worker.tpl
> +          - name: K8_CONTAINER_NAME
nit:
```suggestion
          - name: K8S_CONTAINER_NAME
```

2024-03-19 09:31 UTC, davidcurrie commented on charts/corda-lib/templates/_worker.tpl
> +          - "--trace-tag=container=$(K8_CONTAINER_NAME)"
if this is the online place you use it, you could just inline the container name here rather than using an environment variable, i.e.
```suggestion
          - "--trace-tag=container={{ $workerName }}"
```

2024-03-19 09:46 UTC, vkolomeyko submitted a review, later dismissed
LGTM

2024-03-19 10:26 UTC, vkolomeyko approved these changes
LGTM

2024-03-19 10:51 UTC, vkolomeyko approved these changes
LGTM

2024-03-19 11:00 UTC, davidcurrie approved these changes
LGTM - thanks for all of the updates

2024-03-19 11:02 UTC, merged