Liquibase 4.26.0 Deprecations
corda/corda-runtime-os pull request #5892
Opened 2024-03-18 16:07 UTC by malachyb

2024-03-19 10:38 UTC, malachyb commented
build e2e

2024-03-19 16:06 UTC, malachyb commented
build e2e

2024-03-20 10:30 UTC, vkolomeyko commented on libs/db/db-admin-impl/src/main/kotlin/net/corda/db/admin/impl/LiquibaseManager.kt
> +class LiquibaseManager(
I thought this PR was meant to address LB deprecated API calls only.
Why introduction of this class was necessary, please?

2024-03-20 10:39 UTC, malachyb commented on libs/db/db-admin-impl/src/main/kotlin/net/corda/db/admin/impl/LiquibaseManager.kt
> +class LiquibaseManager(
There was a lot of code duplication because everywhere the API was called previously needed to build the same command with almost zero variation.

2024-03-20 10:57 UTC, vkolomeyko commented on libs/db/db-admin-impl/src/main/kotlin/net/corda/db/admin/impl/LiquibaseManager.kt
> +class LiquibaseManager(
At the very least the PR description is misleading...

Also IMO this is wrong that OSGi export package `net.corda.db.admin.impl`. 
If `LiquibaseManager` is needed in multiple modules, it can introduced as an interface in module `db-admin` in a similar manner how it was done for `LiquibaseSchemaMigrator`.

2024-03-20 11:21 UTC, malachyb commented on libs/db/db-admin-impl/src/main/kotlin/net/corda/db/admin/impl/LiquibaseManager.kt
> +class LiquibaseManager(
I'm not sure that's possible since the plugins aren't OSGi components.

2024-03-20 11:55 UTC, josephzunigadaly commented on libs/db/db-admin-impl/src/main/kotlin/net/corda/db/admin/impl/LiquibaseManager.kt
> +class LiquibaseManager(
The export is here:
```
libs/db/db-admin-impl/src/main/java/net/corda/db/admin/impl/package-info.java
```

Implementations should not be exported. So this `package-info.java` should be removed. That will break access in OSGi environments. `LiquibaseSchemaMigrator` is an example of how to provide access in OSGi, the interface is visible and the implementation has a component annotation.

Code that does not use OSGi will not miss the `package-info.java` file. Deleting that file will not break them.

2024-03-20 13:16 UTC, malachyb commented on libs/db/db-admin-impl/src/main/kotlin/net/corda/db/admin/impl/LiquibaseManager.kt
> +class LiquibaseManager(
If I do that then I don't see how I can access the implementation from the plugin code.

2024-03-20 13:55 UTC, josephzunigadaly commented on libs/db/db-admin-impl/src/main/kotlin/net/corda/db/admin/impl/LiquibaseManager.kt
> +class LiquibaseManager(
The plugin code will continue to work as it does today. The package export only applies in OSGi environments.

2024-03-20 14:03 UTC, malachyb commented on libs/db/db-admin-impl/src/main/kotlin/net/corda/db/admin/impl/LiquibaseManager.kt
> +class LiquibaseManager(
So I continue importing the impl class from the plugin and add the interface for OSGi components?

2024-03-20 14:28 UTC, josephzunigadaly commented on libs/db/db-admin-impl/src/main/kotlin/net/corda/db/admin/impl/LiquibaseManager.kt
> +class LiquibaseManager(
Yes

2024-03-20 16:14 UTC, malachyb commented on libs/db/db-admin-impl/src/main/kotlin/net/corda/db/admin/impl/LiquibaseManager.kt
> +class LiquibaseManager(
I think I've just done what you said, but let me know if it looks like I've misunderstood. Also, when I removed the db-admin-impl `package-info.java` I got an error on build so I left it in.

2024-03-20 17:31 UTC, vkolomeyko commented on tools/plugins/virtual-node/src/main/kotlin/net/corda/cli/plugins/vnode/commands/PlatformMigration.kt
> +    private val liquibaseManager: LiquibaseManagerImpl = LiquibaseManagerImpl()
```suggestion
    private val liquibaseManager: LiquibaseManager = LiquibaseManagerImpl()
```

2024-03-20 17:31 UTC, vkolomeyko commented on tools/plugins/db-config/src/main/kotlin/net/corda/cli/plugins/dbconfig/Spec.kt
> +    private val liquibaseManager: LiquibaseManagerImpl = LiquibaseManagerImpl()
```suggestion
    private val liquibaseManager: LiquibaseManager = LiquibaseManagerImpl()
```

2024-03-20 17:31 UTC, vkolomeyko commented on libs/db/db-admin/src/main/kotlin/net/corda/db/admin/LiquibaseManager.kt
> + * @constructor Create Liquibase manager
```suggestion
```

2024-03-20 17:31 UTC, vkolomeyko commented on libs/db/db-admin/src/main/kotlin/net/corda/db/admin/LiquibaseManager.kt
> +     * @param sql The writer to write the sql to
```suggestion
     * @param sql An optional writer to output the sql into. Note: that if non-null value is passed the Liquibase transform is not actually performed, but intended DB changes are sent to the writer.
```

2024-03-25 10:56 UTC, vkolomeyko approved these changes
LGTM

2024-03-26 15:22 UTC, simon-johnson-r3 requested changes

2024-03-26 15:22 UTC, simon-johnson-r3 commented on libs/db/db-admin/src/main/kotlin/net/corda/db/admin/LiquibaseManager.kt
> + * Liquibase management helpers
comment needs adjustment, this isn't helpers

2024-03-26 15:22 UTC, simon-johnson-r3 commented on libs/db/db-admin-impl/src/main/kotlin/net/corda/db/admin/impl/LiquibaseManagerImpl.kt
> +        lb: Liquibase,
is this really something you can call a "liquibase manager"? you pass a liquibase instance into one of its members, it doesn't feel quite right

the method is called `update`, what is it you are trying to indicate you are updating here?

2024-03-27 08:42 UTC, simon-johnson-r3 approved these changes

2024-03-28 04:55 UTC, closed without merging