CORE-20226: Fix Constraint Violation error in Task Scheduler
corda/corda-runtime-os pull request #6039
Opened 2024-04-18 11:09 UTC by malachyb

2024-04-18 12:00 UTC, malachyb commented
build e2e

2024-04-18 13:20 UTC, malachyb commented
build e2e

2024-04-18 15:56 UTC, simon-johnson-r3 requested changes

2024-04-18 15:56 UTC, simon-johnson-r3 commented on libs/scheduler/scheduler-datamodel/src/main/kotlin/net/corda/libs/scheduler/datamodel/db/TaskSchedulerLogEntityRepository.kt
> +                val testQuery = em.createNamedQuery(TASK_SCHEDULER_LOG_GET_QUERY_NAME, TaskSchedulerLogEntity::class.java)
In cases like this it's best to move the common functionality into a helper function. Otherwise we're bound to change one query at some point and forget to change the other. As it happens, you've done this already to some extent because you omit to set the pessimistic lock the second read. Whilst you could argue it's not necessary if the error thrown was a constraint violation (because then we know the row exists already and there's no need for a write lock in case something else is writing it concurrently) if this has thrown for any other transient reason, we would potentially benefit from that write lock just as we did on line 29.

If you refactor this, another advantage is you can avoid using temp variables entirely. That would help you to spot that you are returning the wrong variable's result list item at line 44.

So I was thinking something like this:
```
    fun getOrInitialiseLog(taskName: String, schedulerId: String, em: EntityManager): TaskSchedulerLog {
        return getLogEntityForTask(em, taskName) ?:
        // try to persist, but catch a constraint violation caused by a possible race condition
        try {
            TaskSchedulerLogEntity(taskName, schedulerId, Instant.MIN, Date.from(Instant.now())).also {
                em.merge(it)
                em.flush()
            }
        } catch (e: PersistenceException) {
            // in this case, re-run the get query, if it still fails this wasn't a constraint violation
            return getLogEntityForTask(em, taskName) ?: throw e
        }
    }
```

2024-04-19 12:42 UTC, simon-johnson-r3 approved these changes

2024-04-19 12:43 UTC, merged