CORE-20247: InvalidParamsException: unable to find master wrapping key XXXXX in tenant YYYYY
corda/corda-runtime-os pull request #6041
Opened 2024-04-18 15:29 UTC by anien

In rare cases we have got a clash when generating key alias. This caused wrapping key not being saved in tenant's db as the alias was already cached as used. When generating key pair for the alias, wrapping key couldn't be find and the operation has failed.
The clashes happened, because we converted random uuid into string and then into bytes before converting it to hex and taking 12 chars. Conversion to string diluted the randomness of the uuid.
We are introducing a new function that converts uuid into bytes directly, keeping the randomness and therefore preventing the clashes to happen much less often.

2024-04-19 07:39 UTC, simon-johnson-r3 requested changes

2024-04-19 07:39 UTC, simon-johnson-r3 commented on libs/utilities/src/main/kotlin/net/corda/utilities/UuidUtils.kt
> +fun UUID.convertToBytes(): ByteArray {
I'd suggest `toBytes` was more Kotlin idiomatic?

2024-04-19 07:39 UTC, simon-johnson-r3 commented
Is there other places we want to address this? We could raise a separate ticket for it.

2024-04-22 09:43 UTC, anien commented on libs/utilities/src/main/kotlin/net/corda/utilities/UuidUtils.kt
> +fun UUID.convertToBytes(): ByteArray {
Renamed.

2024-04-22 09:54 UTC, anien commented
> Is there other places we want to address this? We could raise a separate ticket for it.

Yes, there are other places. I wanted to do it in a separate PRs, but it does make sense to raise a separate ticket ([done here](https://r3-cev.atlassian.net/browse/CORE-20420)).

2024-04-22 13:00 UTC, simon-johnson-r3 approved these changes

2024-04-22 13:01 UTC, merged