CORE-6717 Add persistence and reconciliation for hosted identities
corda/corda-runtime-os pull request #6080
Opened 2024-04-29 10:28 UTC by YashNabar

2024-04-29 15:34 UTC, nikinagy commented on components/membership/certificates-client-impl/src/test/kotlin/net/corda/membership/certificate/client/impl/HostedIdentityEntryFactoryTest.kt
> +                    null
```suggestion
                    null,
```

2024-04-29 15:34 UTC, nikinagy commented on components/membership/locally-hosted-identities-service-impl/src/main/kotlin/net/corda/membership/locally/hosted/identities/impl/LocallyHostedIdentitiesWriterImpl.kt
> +        // TODO change to trace
what about this todo?

2024-04-29 15:34 UTC, nikinagy commented on components/membership/locally-hosted-identities-service-impl/src/test/kotlin/net/corda/membership/locally/hosted/identities/impl/LocallyHostedIdentitiesServiceImplTest.kt
> +        1
```suggestion
        1,
```

2024-04-29 15:34 UTC, nikinagy commented on components/membership/locally-hosted-identities-service-impl/src/test/kotlin/net/corda/membership/locally/hosted/identities/impl/LocallyHostedIdentitiesServiceImplTest.kt
> +                1
```suggestion
                1,
```

2024-04-29 15:34 UTC, nikinagy commented on components/membership/membership-persistence-client-impl/src/main/kotlin/net/corda/membership/impl/persistence/client/MembershipPersistenceClientImpl.kt
> +        logger.info("Persisting locally-hosted identity for $holdingIdentity.")
maybe only log the short hash?

2024-04-29 15:34 UTC, nikinagy commented on components/membership/registration-impl/src/main/kotlin/net/corda/membership/impl/registration/staticnetwork/StaticMemberRegistrationService.kt
> +            1
```suggestion
            1,
```

2024-04-29 15:34 UTC, nikinagy commented on libs/membership/membership-datamodel/src/main/kotlin/net/corda/membership/datamodel/HostedIdentitySessionKeyInfoEntity.kt
> + * An entity representing the session key and certificate information for locally-hosted identities.
maybe add here that there can be multiple entries for a single holding identity?

2024-04-29 17:53 UTC, YashNabar commented on components/membership/locally-hosted-identities-service-impl/src/main/kotlin/net/corda/membership/locally/hosted/identities/impl/LocallyHostedIdentitiesWriterImpl.kt
> +        // TODO change to trace
That was there for testing, changed in [93a826b](https://github.com/corda/corda-runtime-os/pull/6080/commits/93a826b53083a0cfa85289862c29e02f94c2da4a)

2024-05-01 10:03 UTC, nikinagy commented on components/membership/membership-persistence-service-impl/src/main/kotlin/net/corda/membership/impl/persistence/service/handler/PersistHostedIdentityHandler.kt
> +            if (currentVersion != null) {
One thing in mind: since db requests can be processed in an unordered manner, should we check that current version is smaller than the one we are trying to persist?

2024-05-01 10:39 UTC, YashNabar commented on components/membership/membership-persistence-service-impl/src/main/kotlin/net/corda/membership/impl/persistence/service/handler/PersistHostedIdentityHandler.kt
> +            if (currentVersion != null) {
We don't have a version number for the entity we want to persist for comparison, we simply increment the previous one here. Or we could have the intended version specified on the REST endpoint, similar to config

2024-05-02 09:00 UTC, nikinagy submitted a review, later dismissed
LGTM

2024-05-03 11:39 UTC, simon-johnson-r3 requested changes

2024-05-03 11:39 UTC, simon-johnson-r3 commented on components/membership/locally-hosted-identities-service/src/main/kotlin/net/corda/membership/locally/hosted/identities/LocallyHostedIdentitiesWriter.kt
> +    override fun remove(recordKey: String)
This is a little misleading. You can't remove records from Kafka, which is a streaming platform. It would be better I think to call this "putNullRecord" (maybe you can think of a better name along these lines) and then write a description that this is to be used to write the fact that a hosted identity no longer exists.

2024-05-03 11:39 UTC, simon-johnson-r3 commented on components/membership/locally-hosted-identities-service-impl/src/main/kotlin/net/corda/membership/locally/hosted/identities/impl/LocallyHostedIdentitiesWriterImpl.kt
> + * Locally-hosted Identities writer to [put] and [remove] records from Kafka.
See comment I left on the interface `[remove] records from Kafka.` is misleading.

2024-05-03 11:39 UTC, simon-johnson-r3 commented on components/membership/certificates-client-impl/src/main/kotlin/net/corda/membership/certificate/client/impl/CertificatesClientImpl.kt
Does this mean this will only ever work in a single cluster? That we have no persistent records of members in other clusters, and (aside from any other problems with multi-cluster DR) this cluster will have no record of any members outside it in DR recovery situations?

2024-05-03 11:39 UTC, simon-johnson-r3 commented on components/membership/membership-persistence-service-impl/src/main/kotlin/net/corda/membership/impl/persistence/service/handler/PersistHostedIdentityHandler.kt
> +                deleteQuery
You are doing a `merge` below, do we need the query/delete?

2024-05-03 11:55 UTC, YashNabar commented on components/membership/certificates-client-impl/src/main/kotlin/net/corda/membership/certificate/client/impl/CertificatesClientImpl.kt
That is correct, a locally-hosted identities is only relevant in the context of the cluster that the vnode is on

2024-05-03 11:56 UTC, YashNabar commented on components/membership/locally-hosted-identities-service/src/main/kotlin/net/corda/membership/locally/hosted/identities/LocallyHostedIdentitiesWriter.kt
> +    override fun remove(recordKey: String)
Discussed offline, this comes from the reconciliation framework

2024-05-03 13:52 UTC, simon-johnson-r3 commented on components/membership/membership-persistence-service-impl/src/main/kotlin/net/corda/membership/impl/persistence/service/handler/PersistHostedIdentityHandler.kt
> +                deleteQuery
Discussed offline, two different entities involved.

2024-05-03 13:52 UTC, simon-johnson-r3 submitted a review, later dismissed

2024-05-09 09:42 UTC, simon-johnson-r3 approved these changes, later dismissed

2024-05-09 11:07 UTC, conalsmith-r3 submitted a review, later dismissed
LGTM

2024-05-09 12:18 UTC, conalsmith-r3 approved these changes

2024-05-09 12:29 UTC, merged