ES-2393: Remove reference from eks-e2e (e2e-tests-credentials) and replace with eks-e2e-01 (kubernetes-eks-e2e-01-credentials)
corda/corda-runtime-os pull request #6138
Opened 2024-05-15 15:43 UTC by mcgovc

Following on from the migration from eks-e2e Cluster to eks-e2e-01 Cluster references to the older credntials set on Jenkins should be updated to the new credentials.

2024-05-15 19:58 UTC, wzur-r3 requested changes
see my comment

2024-05-15 19:58 UTC, wzur-r3 commented on .ci/e2eTests/JenkinsfileCombinedWorker
> -}
this should stay, and the label would be `docker-on-demand-private-network`

2024-05-15 20:59 UTC, mcgovc commented on .ci/e2eTests/JenkinsfileCombinedWorker
> -}
Added, thanks

2024-05-16 07:02 UTC, wzur-r3 approved these changes
LGTM

2024-05-16 07:43 UTC, davidcurrie approved these changes
LGTM

2024-05-16 07:44 UTC, merged