Remove workaround
corda/corda-runtime-os pull request #6176
Opened 2024-05-30 14:50 UTC by anton-subbotin

2024-06-03 15:34 UTC, tlawson3 requested changes

2024-06-03 15:34 UTC, tlawson3 commented on libs/rest/generated-rest-client/build.gradle
> +        def targetLine = 'Serializer.jacksonObjectMapper.readValue\\(bodyContent, object: TypeReference<T>\\(\\) \\{}\\)'
Will you add the task input/output/uptoDateWhen, like in this draft PR: https://github.com/corda/corda-runtime-os/pull/6174/files

It makes the task more complete

2024-06-03 15:34 UTC, tlawson3 commented on libs/rest/generated-rest-client/src/test/kotlin/net/corda/restclient/generated/TestKnownIssues.kt
> +}
Can you add a test for that SQL endpoint you found?

2024-06-03 16:06 UTC, tlawson3 submitted a review, later dismissed

2024-06-03 16:28 UTC, anton-subbotin commented on libs/rest/generated-rest-client/src/test/kotlin/net/corda/restclient/generated/TestKnownIssues.kt
> +}
There are 10 overall endpoints with String return type. For now we are covering two of them - get MGM GroupPolicy and post CSR request; do you still think we need to add more?

2024-06-03 16:29 UTC, anton-subbotin commented on libs/rest/generated-rest-client/src/test/kotlin/net/corda/restclient/generated/TestKnownIssues.kt
> +}
If we want to be 100% safe we need to add tests for all of them...

2024-06-04 07:53 UTC, tlawson3 commented on libs/rest/generated-rest-client/src/test/kotlin/net/corda/restclient/generated/TestKnownIssues.kt
> +}
These tests are mock tests, which aren't actually triggering Corda. All we're covering is the generated client's ability to handle the expected response. My question is, are these 10 endpoints providing the similar kind of response to one another so we could assume we're ok? The SQL value could be different, depending on how it's escaped or not.

2024-06-04 08:58 UTC, anton-subbotin commented on libs/rest/generated-rest-client/src/test/kotlin/net/corda/restclient/generated/TestKnownIssues.kt
> +}
All of the responses are similar in a sense that it is a String with whatever a String can be, and are not supposed to be deserialised - even in the case of MGM Group Policy which _is_ a valid JSON String. 

I'll go and add the tests just to be on a safe side.

But then, ideally, we'd better have mock tests for all existing possible endpoints..

2024-06-04 10:24 UTC, anton-subbotin commented on tools/plugins/network/src/main/kotlin/net/corda/cli/plugins/network/BaseOnboard.kt
> +        println("Registration ID for '$name' is '${registrationId.value}'")
Spotted this one when running pluginSmokeTest

2024-06-04 10:30 UTC, anton-subbotin commented on libs/rest/generated-rest-client/src/test/kotlin/net/corda/restclient/generated/TestKnownIssues.kt
> +}
added few more test for different kinds of String responses (PEM, greeting, SQL)

2024-06-04 10:31 UTC, tlawson3 approved these changes

2024-06-04 10:39 UTC, ronanbrowne approved these changes
LGTM (build changes)

2024-06-04 10:49 UTC, merged