CORE-20695: Retire v1 REST version
corda/corda-runtime-os pull request #6203
Opened 2024-06-11 09:58 UTC by BenYip123

2024-06-14 09:12 UTC, vkolomeyko commented on processors/rest-processor/src/integrationTest/resources/readme.md
> +File [swaggerBaseline-$version.json](./swaggerBaseline-v5_1.json) represents a snapshot of Open API which REST Worker currently
```suggestion
File [swaggerBaseline-$version.json](./swaggerBaseline-v5_3.json) represents a snapshot of Open API which REST Worker currently
```

2024-06-14 10:37 UTC, vkolomeyko approved these changes, later dismissed
LGTM

2024-06-14 11:51 UTC, anton-subbotin reviewed
There still are usages of `/v1/` paths across the codebase, including under:
- `tools/corda-runtime-gradle-plugin/` - where applicable, should be switched to use earliest supported version, e.g. `v5_1`, @tlawson3 please comment
- `libs/permissions/` - mentioned in tests
- `libs/corda-sdk/` - affects Corda CLI (`bootstrap rbac` command)

2024-06-14 11:52 UTC, anton-subbotin requested changes
There still are usages of `/v1/` paths across the codebase

2024-06-14 12:19 UTC, tlawson3 commented
> There still are usages of `/v1/` paths across the codebase, including under:
> 
> * `tools/corda-runtime-gradle-plugin/` - where applicable, should be switched to use earliest supported version, e.g. `v5_1`, @tlawson3 please comment
> * `libs/permissions/` - mentioned in tests
> * `libs/corda-sdk/` - affects Corda CLI (`bootstrap rbac` command)

Regarding the gradle plugin

- net/corda/gradle/plugin/cordalifecycle/EnvironmentSetupHelper.kt Updating to 5_1 should be fine. I've created task https://r3-cev.atlassian.net/browse/ES-2460 to refactor it to remove the Unirest use but that would be outside the scope of this PR.
- net/corda/gradle/plugin/ProjectUtils.kt fun getExistingNodes isn't used so feel free to delete the function

2024-06-14 15:17 UTC, anton-subbotin submitted a review, later dismissed
LGTM

2024-06-17 08:23 UTC, vkolomeyko commented
Could we also remove source file `testing/e2e-test-utilities/src/main/kotlin/net/corda/e2etest/utilities/websocket/client/SmokeTestWebsocketClient.kt`? As it contains reference to `api/v1` and I do not think this Websocket functionality is still used in E2E tests.

2024-06-17 11:27 UTC, vkolomeyko approved these changes
LGTM

2024-06-17 12:26 UTC, ronanbrowne approved these changes
LGTM

2024-06-18 09:33 UTC, merged