CORE-20780 Added mapping of valid LifecycleStatus transitions
corda/corda-runtime-os pull request #6270
Opened 2024-07-09 14:58 UTC by ben-millar

2024-07-10 13:10 UTC, LWogan commented on libs/lifecycle/lifecycle-impl/src/main/kotlin/net/corda/lifecycle/impl/LifecycleCoordinatorImpl.kt
> +    private val transitions = mapOf(
Transitions from current status to the same status should be allowed. e.g UP -> UP , ERROR-> ERROR

2024-07-10 13:29 UTC, LWogan commented
This has been seen to occur in 5.2 after the patch to ThreadLooper applied here was merged.
https://github.com/corda/corda-runtime-os/pull/6261

This is due to the asynchronous nature of the lifecycle library. The previous patch attempted to block transitions from ERROR within the messaging library code. The status does not propagate immediately and so the ThreadLooper is still updating the status to DOWN, via close(), as it think the current status is still UP. This pr applies the restriction within the lifecycle library itself which is much better!

2024-07-10 17:21 UTC, ben-millar commented on libs/lifecycle/lifecycle-test-impl/src/main/kotlin/net/corda/lifecycle/test/impl/LifecycleTest.kt
> +        coordinator.stop()
Tests use this function to bring a given component back to `LifecycleStatus.UP` from other states, potentially including `LifecycleStatus.ERROR` — the code changes in this PR prevent us from bringing a component directly from `ERROR` -> `UP`, so we must first restart it.

2024-07-11 10:46 UTC, simon-johnson-r3 requested changes

2024-07-11 10:46 UTC, simon-johnson-r3 commented on libs/lifecycle/lifecycle-impl/src/main/kotlin/net/corda/lifecycle/impl/LifecycleCoordinatorImpl.kt
> +    private val transitions = mapOf(
Minor, but can we make this `permittedTransactions` for clarity? On a positive note, I think having this is a great idea, it covers both documenting the permitted transactions in the code _and_ runtime error handling.

Also this is static data, it should really be in the companion object.

2024-07-11 13:21 UTC, simon-johnson-r3 approved these changes

2024-07-11 13:25 UTC, merged