CORE-20737: Add change user's parent group ID endpoint
corda/corda-runtime-os pull request #6305
Opened 2024-07-24 12:38 UTC by BenYip123

- Adds endpoint to change a user's parent group ID

2024-07-24 17:40 UTC, BenYip123 commented on gradle.properties
> +cordaApiVersion=5.3.0.16-alpha-1721838135404
Reminder to update to `5.3.0.16-beta+` once `corda-api` is merged

2024-07-25 11:24 UTC, Tom-Fitzpatrick approved these changes, later dismissed
LGTM

2024-07-25 11:24 UTC, vkolomeyko reviewed
Looks reasonable.

Couple of comments posted.
Given that we introduced a new endpoint, let's not forget to update `UserAdmin` role for this additional operation.

2024-07-25 11:24 UTC, vkolomeyko commented on gradle.properties
> +cordaApiVersion=5.3.0.16-alpha-1721838135404
Should be possible to update now?

2024-07-25 11:24 UTC, vkolomeyko commented on libs/permissions/permission-manager-impl/src/main/kotlin/net/corda/libs/permissions/manager/impl/PermissionUserManagerImpl.kt
> +                    changeUserParentGroupIdDto.newParentGroupId,
Before dispatching Kafka call towards DB Worker, shall we check that the group indeed exists, when `newParentGroupId` is not `null`?

I note we do it on DB Worker side, but we can do it cheaply here to avoid unnecessary Kafka traffic in case of invalid arguments.

2024-07-25 13:52 UTC, anton-subbotin approved these changes
LGTM (corda-sdk changes)

2024-07-25 13:54 UTC, anton-subbotin requested changes

2024-07-25 13:54 UTC, anton-subbotin commented on libs/corda-sdk/src/main/kotlin/net/corda/sdk/bootstrap/rbac/Permissions.kt
> +        "ChangeUserGroupParentId" to "PUT:/api/$VERSION_PATH_REGEX/user/$UUID_REGEX/parent/changeParentId/$UUID_REGEX",
```suggestion
        "ChangeUserGroupParentId" to "PUT:/api/$VERSION_PATH_REGEX/user/$UUID_REGEX/parent/changeparentid/$UUID_REGEX",
```

2024-07-25 13:59 UTC, anton-subbotin approved these changes

2024-07-25 14:56 UTC, Tom-Fitzpatrick approved these changes

2024-07-25 16:03 UTC, vkolomeyko approved these changes
LGTM

2024-07-25 16:40 UTC, merged